### ISSUE TITLE
Can´t create any Course 

### ISSUE THREAD

**Issue by MuV1N** [Courseplay/Courseplay_FS22#100]
I am playing on Haut-Beyleron and i can´t create any Worker/Course with Courseplay (V1.0.0.4) for any field.
![fsScreen_2021_12_25_23_08_55](https://user-images.githubusercontent.com/75033565/147394384-16ef29b5-48d5-4ac1-a967-d33bd6bc573b.png)

**Comment by MuV1N** [comment]
[Image](
![image](https://user-images.githubusercontent.com/75033565/147394260-c9d07946-7754-413a-8e00-2803c76c1dc2.png)

**Comment by MuV1N** [comment]
![Bild_2021-12-25_230318](https://user-images.githubusercontent.com/75033565/147394268-f7446eda-16fa-477b-bd09-6238bfd61151.png)

**Comment by MuV1N** [comment]
![Bild_2021-12-25_230355](https://user-images.githubusercontent.com/75033565/147394276-34f64cc9-2c11-40b4-9e18-3a28cd358ebd.png)

**Comment by MuV1N** [comment]
![fsScreen_2021_12_25_22_57_44](https://user-images.githubusercontent.com/75033565/147394286-d5c34c04-0650-4572-ac24-3903d05e0273.png)

**Comment by MuV1N** [comment]
![fsScreen_2021_12_25_23_08_55](https://user-images.githubusercontent.com/75033565/147394349-7251deec-7891-4f11-b36f-0a9620345829.png)

**Comment by rohne83** [comment]
do you have an implement attached? Afaik course generation is only working for vehicles which can also be started with Giants standard helper.

**Comment by Tensuko** [comment]
Strange is that he can't even create a job for normal Giants 'Move to location' ...

@MuV1N do you have a logfile for us ?

**Comment by Resandise** [comment]
FYI, I'm on the same map, having no issues generating courses

**Comment by MuV1N** [comment]
I had fixed it I had installed Helper tool and yet it´s working
thank you a lot
