### ISSUE TITLE
[BUG_SP] Slurry linkage unfolds too early

### ISSUE THREAD

**Issue by VJH01** [Courseplay/Courseplay_FS22#1001]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Autodrive Course and Courseplay Field Course, Vehicle with slurry tanker and linkage or attachment. 

**Actual behavior**
After loading the slurry tanker with AutoDrive, the helper starts to unfold the linkage right after Autodrive reached the waypoint und hands over to Courseplay. AD waypoint is outside of the field.
In this case the linkage is only 18m, with 30m you might crash into trees or something else.

**Expected behavior**
Unfold the linkage on the field or/and near the Courseplay target waypoint on the field.

**Screenshots**
![Gülle](https://user-images.githubusercontent.com/96574322/153944946-1e32d94b-07f0-44d7-b743-b4087ae37b32.png)

**Courseplay version**
Version used: 7.0.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8063853/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Vervat Hydro Trike with Bomech Trac Pack ->original Giants content update
John Deere 230R with Farmtech Polycis 1550 ->no mods

**Relevant script mods**
Autodrive V2.0.0.4

**Comment by Tensuko** [comment]
Work in Progress and I am sure we have a similar Issue alreay.
