### ISSUE TITLE
[BUG_MP] Frage Speicherort Kurse

### ISSUE THREAD

**Issue by N3kr0E** [Courseplay/Courseplay_FS22#1009]
Hallo,

habe eben die Version 7.0.1.0 auf meinen Dedi geladen und die ersten Kurse generiert und gespeichert.
Nun kommt ein Freund auf den Server, jedoch sieht er keine Kurse.

Habe mal aufm FTP geschaut.. Da gibt es ein Verzeichnis "ModSettings", hier ist auch CP abgelegt. Wenn man sich durchklickt, dann kommt man im Ordner "Courses" auf den Ordner "Singeplayer" und hier finden sich keine Kurse.
Also lokal im selben Verzeichnis nachgeschaut, und dort finde ich auch die Kurse.

Kann es sein, dass die Kurse nur lokal, aber nicht auf dem Dedi gespeichert werden?

**Courseplay version**
Version used: v7.0.1.0

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
NF Marsch 4-fach

**Comment by Tensuko** [comment]
Kurse werden aktuell lokal gespeichert.
Speichern auf dem Server kommt später.

**Comment by N3kr0E** [comment]
Okay, alles klar. 
Vielen Dank für die schnelle Antwort und tolle Arbeit!
