### ISSUE TITLE
[Question]Düngefunktion bei Mod Sähmaschine nicht ausschaltbar

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1010]
Hallo. Ich möchte die Hatzenbichler 18m Sähmaschine (TERMINATOR TH18 mit Tankwagen TH1400 aus dem BigBud Pack) mit CP verwenden, ohne dass Dünger verwendet wird. Bei anderen Sähmaschinen  kann man das Düngen in den CP Einstellungen deaktivieren. Bei diesem Mod ist die Einstellung nicht vorhanden. 

Sitzt der Fehler vor dem PC? Ist der Mod fehlerhaft? Oder kann CP das bei mehrteiligen Sähmaschinen (noch) nicht?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8072787/log.txt)

**Comment by altbier1** [comment]
Ich hatte das selbe Problem bei der Hatzenbichler 18m Sähmaschine  von Onkel Yogi. Bei der Sähmaschine ist als vehicle type="fertilizingSowingMachine" eingetragen, beim Tankwagen steht / stand bei mir vehicle type="fillableImplement". Nach dem ändern des vehicle types des Tankwagen in ehicle type="fertilizingSowingMachine" konnte ich die Düngefunktion der Sähmaschine ausschalten. Ich vermute daher, dass CP noch nicht mit solchen Sähmaschinen klar kommt. 
Evtl. kann das Entwicklerteam das in einem  Update fixen

**Comment by schwiti6190** [comment]
Seems to me like the same issue as #968. There will a fix for this issue in the next version.
