### ISSUE TITLE
[BUG_SP] On merged field bale collector only collects original field

### ISSUE THREAD

**Issue by nlcoredump** [Courseplay/Courseplay_FS22#1011]
**Steps to reproduce**
On original elmcreek map merge 2 or more field into one. (course generator will see one field).
Create any kind of bales on the field
Start collecting bales in one part of the merged field

**Actual behavior**
Bale collector stops collecting bales when all bales in original field area are collected. While there are still bales on the merged field.
(log in screenshot says no more bales in field 54, but there are in 53 which is part of the merged field in my case)  Had this problem with all fields i merged.

**Expected behavior**
Collect all bales on in the merged area and stop when no more bales available.

**Courseplay version**
Version used: 7.0.1.0

**Log**
![cp_bug](https://user-images.githubusercontent.com/15627379/154127129-122a1ff4-c07f-44b6-bcb2-aaf6c753367d.jpg)

**Vehicles/ implements involved**
Which vehicle or implement?

ponge SPX816 autoload

Mod yes?

**Relevant script mods**
Autodrive 2.0.4.

**Comment by Tensuko** [comment]
Did you try to set a custom field arround your merged field (just to try it with collect bales, I know it won't work for course generator).

**Comment by nlcoredump** [comment]
When i draw a custom field around the merged fields the bale collector does find all the bales.

**Comment by Tensuko** [comment]
Alright then it stays like that for now.
