### ISSUE TITLE
[BUG_SP] the courseplay reduces the speed of some tractors with the gearbox

### ISSUE THREAD

**Issue by ontot** [Courseplay/Courseplay_FS22#1012]
the courseplay reduces the speed of some tractors having shifting gears. during work the tractors cannot exceed 6 or 9 km / h. this problem does not happen with the original game tractors. what could this problem depend on?

**Comment by Tensuko** [comment]
Mod Issue

**Comment by ontot** [comment]
OK thanks for the info. However I wanted to give you the best compliments for the work you are doing. Thanks again.

**Comment by Tensuko** [comment]
Thank you :)
