### ISSUE TITLE
[BUG_SP] Claas Lexion selfunload

### ISSUE THREAD

**Issue by Bosketti** [Courseplay/Courseplay_FS22#1013]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Created course for Lexion harvester with auto unload turned on.  Began harvest then placed unload vehicle in the field where harvesting had already occurred.

**Actual behavior**
I harvested field 57 with the Claas Lexion and had the auto unload feature turned on.  The harvester would go to the unload vehicle and pipe out, but would not unload.  I suspect there is a specific issue with this harvester.  If I recall correctly in FS19, the pipe is longer on this harvester than it is on other harvesters.  Both unload cycles for this field responded the same.  I had to stop the course and take over the harvester in order to reposition it for unload.  Once positioned it unloaded, to me this would indicate that it is not an issue with the unload vehicle.

**Expected behavior**
When the Harvester arrives at the unload vehicle, it should position itself correctly for the pipe length and unload unassisted.

**Screenshots**
Next harvest I will grab a screen shot..

**Courseplay version**
7.0.1.0

**Log**
Next harvest I will turn on debug to post.  Sorry.

**Map**
Elmcreek

**Vehicles/ implements involved**
Claas Lexion harvester included in game

**Relevant script mods**
no

**Comment by Tensuko** [comment]
> The harvester would go to the unload vehicle and pipe out, but would not unload

And exactly there we need to know why not ?
Does not hit the trailer right ?
Is correct at the trailer but won't unload anyway ?
Screenshot and logfile are rly needed here.
You should have taken those information1st and only then open an Issue...

**Comment by Bosketti** [comment]
My apologies for not having the screenshot and debug files.  This is my first time doing this.  I did not have debug turned on during that last harvest.  The harvester approaches the unload vehicle but ends up too close.  I had to manually move the harvester further away from the unload vehicle in order to unload.  Again, I will provide debug files when I harvest next.

**Comment by Bosketti** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8083714/log.txt)
![Screenshot Lexion unload fail](https://user-images.githubusercontent.com/99763791/154360908-f78722e1-8846-4c46-b66e-9bca0c309d46.png)

I have attached a log file and screen shot.  The harvester moves to unload but does not properly account for the length of the pipe and so the pipe extends beyond the trailer.  I don't have a screen shot showing this, but as the harvester was maneuvering into position it would unload while the pipe was over the trailer.

**Comment by pvaiko** [comment]
You forgot to mention that this a mod trailer. Does this happen with other trailers too?

**Comment by Bosketti** [comment]
My humblest apologies.  I was forgetting that the trailer is a mod and the trailer is the problem.  I will follow up accordingly with the author of the trailer mod.  I was only trying to be helpful.

**Comment by pvaiko** [comment]
No apology needed. So can you confirm that this is an issue with this trailer only?

**Comment by rohne83** [comment]
wouldn't rule out issue with the calculation of the correct unload position for the combine. The vanilla Lexion's pipe is very long and angled not 90 degrees but more than 100 degrees, which led to similar problems with self unloading this combine in the past already. Think we already had issues for this here. Barely use self unloading, so don't know whether this has been fixed meanwhile at least for unloading into vanilla trailers.

**Comment by Tensuko** [comment]
It is fixed and the angle and all that stuff should not be a problem, as this is not the only combine/harvester with an angled pipe/convoyr.

**Comment by pvaiko** [comment]
> angled not 90 degrees but more than 100 degrees, which led to similar problems with self unloading this combine in the past already

Nope, it was not the angle.

**Comment by pvaiko** [comment]
@Bosketti relax, I just wanted to know if it is specific to this trailer, looks like it is, and I really have no idea why, I checked it out. 

To figure out the offset we use the trailer's width (which is 3m, looks fine), the offset of the pipe's discharge node (no, not the length, @rohne83 ) which seems to work fine, and the fill node of the trailer. Which also seems to be ok. Had no more time to spend on this, sorry.

**Comment by Bosketti** [comment]
Thank you for looking into it.
