### ISSUE TITLE
Course Generation HUD  Displays accross 3 Screens

### ISSUE THREAD

**Issue by Brynkelly** [Courseplay/Courseplay_FS22#1015]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Click on Open Course Generator

**Actual behavior**
Course Generator Settings hud, stretches accross all three of my screens.

I have a 3 separate screens set up using a Screen Resolution 5760x1080  53:10. everything was OK upto version 7.0.0.21 at level 7.0.0.22 it then stretched.  Did not experience any problems in FS19

**Expected behavior**
Expect to see it on Screen one as before level 7.0.0.22

**Screenshots**
Have added 2 screen shots  one taken at Level 21 which shows on left hand screen only. Then one taken at Level 22 and onwards which shows Hud stretched accross 3 Screens.  I have tried altering Scale  in 'Game Hud Scale' but has no affect. Is there another setting in Courseplay that I have not found.

![Courseplay 7 0 0 21](https://user-images.githubusercontent.com/99799281/154242710-2fe2e525-b8df-48ea-b0cf-90bef0203a3b.JPG)

![Courseplay after 7 0 0 21](https://user-images.githubusercontent.com/99799281/154242880-301fc35b-e727-4b65-93d5-48b6c553a691.JPG)

**Courseplay version**
Version used:  7.0.1.0

**Log**
Please attach a log with all debug channels active.

For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elmcreek and every other map

**Vehicles/ implements involved**
All vehicles

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by schwiti6190** [comment]
Could you please retry this with the newest version and repopen this, if it's still a problem.

**Comment by Brynkelly** [comment]
Hi Sorry for the delay in responding to your email,  I have loaded the latest version 7.1  June 16.  the problem is the same showing across all 3 screens
