### ISSUE TITLE
[BUG_SP] Seeder refuses to seed, helper stuck - WAITING_FOR_LOWER: waiting for all tools to lower

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#1019]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create course with a seeder, run course.

**Actual behavior**
Seeder drives into position, gets stuck. WAITING_FOR_LOWER: waiting for all tools to lower.

**Expected behavior**
Work the field.

**Courseplay version**
Version used:  7.0.1.0 latest commit - the issue isn't present in 7.0.1.0 release

**Map**
Elmcreek

**Vehicles/ implements involved**
Fendt 1050/John Deere 1775NT (mod -  https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=232099&title=fs2022 )

**Relevant script mods**
At this point, more than I can count or list... VCA
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8083630/log.txt)

**Comment by Tensuko** [comment]
![fsScreen_2022_02_17_07_18_10](https://user-images.githubusercontent.com/27344744/154416990-6ca8fee3-5813-43c7-a94d-8e4bcd60dcf5.png)
Seems to only happen with the Mod.
Logfile contains 1st the mod, then the vanilla version.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8086056/log.txt)

**Comment by Tensuko** [comment]
Another Compare with the Kinze Version (wich seems to be the original one and the Mod is just a reskin...)
That one also waits to lower tools.
Not sure whats going on.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8086085/log.txt)

**Comment by pull2play** [comment]
> Another Compare with the Kinze Version (wich seems to be the original one and the Mod is just a reskin...) That one also waits to lower tools. Not sure whats going on. [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8086085/log.txt)

Seems to affect most (all?) seeders with a fertilising option. I just tried the Amazone Citan (default game seeder), and it throws the same error.

**Comment by Tensuko** [comment]
Yea we found the problem. Working on it.

**Comment by pull2play** [comment]
Seems to be fixed - ok to close unless you need this open for further debugging.
