### ISSUE TITLE
[Feature] Feldersteller

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/Courseplay_FS22#1026]
Hallo ich würde gerne meine Idee vorstellen.
Und zwar das wenn der CP Helfer einen Pflug hat man den Modus Felder Erstellen bekommt sodass Personen wie ich das ganz leicht Automatisieren können.
Was man angeben müsste wären nur die Gewünschten Eckpunkte und Kurven.
Ich meine Idee gefällt euch sodass ihr sie umsetzten werdet

**Comment by Tensuko** [comment]
You mean draw a field like this ?
![fsScreen_2022_02_17_18_59_15](https://user-images.githubusercontent.com/27344744/154542601-5449b83a-340d-40a6-bb0d-0fc1d1b57bb3.png)
And then generate a course inside ?
![fsScreen_2022_02_17_19_00_20](https://user-images.githubusercontent.com/27344744/154542655-72fb757f-76ad-4536-8d7c-8bd0c682a77f.png)

Thats already implemented :)
Not sure if I added that in the help section already, if not it will come soon.

**Comment by Terrabey** [comment]
Just a remember I will look at 14PM again
