### ISSUE TITLE
[BUG_MP] Target position in CP: fieldwork

### ISSUE THREAD

**Issue by VarusXX** [Courseplay/Courseplay_FS22#1028]
I generate a new job "CP: Fieldwork" (hopefully it is named so in engl client. I have a german client). Fieldposition is ok but Target position says the wrong course. (see picture) I set it to 180° and position says 360°. [Works fine on 270° or 90°]
![CP](https://user-images.githubusercontent.com/48722973/154563586-1fb1a602-b894-4b6a-8f86-5bbe7d9a897e.jpg)

**Comment by Tensuko** [comment]
That got nothing to do with us.

**Comment by VarusXX** [comment]
The position of the arrow shows to south (see left side of pic) and in your settings says "<x,y | 360°>". I accecpt what you say, but still wondering
