### ISSUE TITLE
[BUG_SP]Helfer beendet Arbeit, wenn er blockiert wird

### ISSUE THREAD

**Issue by Cassy-Blair** [Courseplay/Courseplay_FS22#1032]
Sobald der Helfer von einem Abfahrer oder anderen Hindernis blockiert wird, bricht er seine Arbeit ab und verlässt seinen Arbeitsplatz ohne sich bei mir abzumelden. Im LS19 bekam man da wenigstens noch die Meldung **"Drescher blockiert"** oder **"Drescher durchdrehende Reifen"** Aber daß er seinen Arbeitsplatz ohne Ankündigung verläßt gab es nie, er hat immer brav gewartet, bis man das Hindernis beseitigt hat.

**Comment by Tensuko** [comment]
Kommt alles noch, abwarten. Und wenn Bugreport, dann bitte Vollständig machen.
