### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by SeriouZ12** [Courseplay/Courseplay_FS22#1034]
**What is the problem this feature/enhancement solves?**
Id like the Combine to turn off when it is full and waiting for a  unloader to save fuel.

**Describe the solution you'd like**
The Combine should turn off the header so the RPM goes down when it is full and waits until it starts to unload.

**Comment by Tensuko** [comment]
All I had to do is type in "fuel" in the filter bar and look what I found: #140
