### ISSUE TITLE
[BUG_SP] Starting Course with seeder only filled with seeds 

### ISSUE THREAD

**Issue by Krel2011** [Courseplay/Courseplay_FS22#1035]
**Steps to reproduce**
Start course with airseeder only filled with seeds

**Actual behavior**
Triggerrs "error LUA update" and game crashes.

**Expected behavior**
Start seeding without stopping because fertilizer tank is empty.

**Courseplay version**
Version used: 7.0.10

**Log**
https://pastebin.com/rX2QJCiy

**Map**
ND Hastings

**Vehicles/ implements involved**

Giants 9420R and Hazenbilcher air seeder mod.

**Relevant script mods**
AD, CP

**Comment by Tensuko** [comment]
There is an important text that you removed from that template "READ FIRST" and it ask you to try to latest Version.
+ logfile not complete + not a CP Error.
Buddy, pls read Wiki Page :)
