### ISSUE TITLE
[BUG_SP] No field numbers on map (v.7.0.1.1)

### ISSUE THREAD

**Issue by Coornik** [Courseplay/Courseplay_FS22#1036]
**Actual behavior**
After few minutes mod hide field numbers on minimap.
In config file gameSettings.xml value "<ingameMapFilters>0</ingameMapFilters>" was changed to ~2 - which causes that on new games without mods you still cannot see the field numbers.

**Expected behavior**
visible field numbers on map

**Courseplay version**
Version used: 7.0.1.1

**Map**
Second

**Comment by Tensuko** [comment]
no log, no search used.... haaa
-> #1031
