### ISSUE TITLE
[Feature] Drescher sollten länger warten wenn voll

### ISSUE THREAD

**Issue by Plopsi** [Courseplay/Courseplay_FS22#1037]
*Preambel*
Ich schreib das mal auf Deutsch, sry. - Ich hoffe das ist OK.

Ist im zusammenspiel mit AutoDrive beim Drescherabtanken.

**What is the problem this feature/enhancement solves?**
Es passiert - besonders bei großen Feldern - mal das der Drescher mit dem Rohr in der Frucht voll wird. Je nachdem ob der im Vorgewende oder direkt inder Bahn ist, wird der entweder eine Tanktasche einschneiden um Platz zu für sich zu schaffen oder nur zurücksetzen und in die letzte Bahn setzen um Platz zu schafen. - Unglaublich großen Respekt das so ein Verhalten überhaupt möglich ist übrigens.

Das Problem ist eher ein Timingproblem. Der Drescher wartet und der AD kommt dann zum Abfahren. Aufgrund von unwägbarkeiten, kommt er aber Frontal vorbei und beim "vorbeischlängeln" tankt der schon ein paar Liter ab - fährt vorbei und will hinten wenden um von hinten an das Abtankrohr zu kommen.
Jetzt merkt der Drescher aber das er wieder nicht am Limit ist und fängt an weiter zu fahren. Ende der Geschichte ist ein Abfahrer-Drescher-Knäuel :D

**Describe the solution you'd like**
Îch denke der Drescher sollte - wenn er voll anhält um abgetankt zu werden - entweder länger warten sollte oder erst wieder loslegt wenn er einen gewissen prozentsatz abgetankt bekommen hat (20-30?). - Eventuell einstellbar?
Alternative ist natürlich länger warten - mindestens doppelt so lang, besser 3x.

**Describe alternatives you've considered**
Wäre auf der Seite von AD. Abfahren bei stehendem Drescher frontal zu ermöglichen (sprich nich immer dran vorbeifahren um von hinten anzufahren)

**Additional context**
Wir sind gerade im falschen ingame-Monat, sobald möglich kann ich auch gemarkte Screenshots anhängen...

**Thanks**
Das mod ist lit :D

**Comment by Tensuko** [comment]
Das ist aber ein AD Problem.
Da muss das Timeing angepasst werden und ich weis jetzt nicht wie das mit der nächsten Version sein wird.
Außerdem kann AD das doch steuern bei wieviel abgetankt werden soll.
