### ISSUE TITLE
Ladewagen fährt nicht ab

### ISSUE THREAD

**Issue by AstraThomas** [Courseplay/Courseplay_FS22#1039]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
-AD fährt zum Feld, Übergibt an CP. CP befüllt den Ladewagen bis 95%, dann wird wieder an AD Übergeben aber AD fährt nur wieder zum feld, Dort angekommen wird dauerhaft zwischen CP und AD hin und her übergeben

**Expected behavior**
-AD sollte zum feld fahren, an CP übergeben bis der ladewagen voll ist und dann zurück an AD übergeben der zum fermenter fährt, dort ablädt, wieder zum feld fahren und dann wieder von vorne (letzten wegpunkt) beginnen

**Courseplay version**
Version used: 7.0.0.1.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8100403/log.txt)

**Map**
Map played on.
NF Marsch ohne gräben V1.2

**Vehicles/ implements involved**
Which vehicle or implement?
Landini 7  230 Robo- six + Strautman Zelon ladewagen
Mod yes/no ?
Nein

**Comment by Tensuko** [comment]
Also ich konnte das nicht reproduzieren, weis nicht ob das nun schon an der 2.0.0.5 RC von AD liegt, aber CP hat da nicht direkt ein Problem...
![fsScreen_2022_02_18_22_52_14](https://user-images.githubusercontent.com/27344744/154766352-776a3594-d94c-43ef-bf12-8eeed54db140.png)

**Comment by Axel32019** [comment]
Sieht für mich nach "Klassiker" aus: AD Abladen ab Level mehr als 90% eingestellt.
Bitte in AD mal max. 90% einstellen!
