### ISSUE TITLE
Gerät am Ende einklappen ohne Funktion

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#104]
Auch die Funktion "Gerät am Ende des Kurses einklappen" funktioniert nicht.

Bisher getestet bei 2 großen Grubbern und einer Düngerspritze.

**Comment by BigBlackBahamut** [comment]
Hier schließe ich mich mit an. Funktioniert nicht das einklappen.

**Comment by XPiRiJenZ** [comment]
...und er fährt zu weit vor, nachdem die Arbeit beendet wurde.

![Screenshot 2021-12-27 13-05-25](https://user-images.githubusercontent.com/43669988/147470385-d4505a5e-c0c1-4e3e-93d1-12812c35709c.png)

**Comment by Tensuko** [comment]
> ...und er fährt zu weit vor, nachdem die Arbeit beendet wurde.

Oops. Passiert das mit allen Geräten ?
Das da ist schon sehr weit...
Frage mich ob das durch ein ausrollen verursacht wird und wir nur die 'Bremse' einbauen müssen.

**Comment by XPiRiJenZ** [comment]
> 
Hab es im Anschluss mit Ballenpresse probiert und die fährt auch auf diese Höhe, stoppt dann und beendet dann die Arbeit.
Ein Ausrollen findet nicht statt.

**Comment by XPiRiJenZ** [comment]
> > ...und er fährt zu weit vor, nachdem die Arbeit beendet wurde.
> 
> Oops. Passiert das mit allen Geräten ? Das da ist schon sehr weit... Frage mich ob das durch ein ausrollen verursacht wird und wir nur die 'Bremse' einbauen müssen.

Hab es im Anschluss mit Ballenpresse probiert und die fährt auch auf diese Höhe, stoppt dann und beendet dann die Arbeit.
Ein Ausrollen findet nicht statt.

**Comment by XPiRiJenZ** [comment]
"Problem" für das weite Vorfahren gefunden: Vorgewende wird beim Berechnen des Feldarbeitskurses nicht berücksichtigt.
![Screenshot 2021-12-27 22-21-48](https://user-images.githubusercontent.com/43669988/147508043-a87deb36-b855-467b-9c1b-2679cad927f3.png)

**Comment by Keppchen** [comment]
Kann man die Themen nicht trennen? Das weite vorfahren hat ja nichts mehr mit dem Thema hier zu tun...

**Comment by Tensuko** [comment]
> Kann man die Themen nicht trennen? Das weite vorfahren hat ja nichts mehr mit dem Thema hier zu tun...

passt schon...



> "Problem" für das weite Vorfahren gefunden: Vorgewende wird beim Berechnen des Feldarbeitskurses nicht berücksichtigt.

Schon spannend, bisher noch nicht hingekriegt.
Wenn du das auf eine Art und Weise hinbekommst, über Shift + 1-4 bitte mal course load/save/generate aktivieren und dann den Kurs generieren.
Da dann bitte ein Issue draus machen und das logfile anhängen.

**Comment by XPiRiJenZ** [comment]
@Tensuko tritt in der 7.0.0.9 nicht mehr auf.. Ich kann es nicht mehr reproduzieren.

**Comment by Tensuko** [comment]
Fold implements at end might be partly fixed, pls reopen if not working correctly.
