### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by MainPwrSrc** [Courseplay/Courseplay_FS22#1040]
**Steps to reproduce**

fs22

At the moment you generate new fieldwork for TopLiner 4090H harvester to work on a field, the ID field  numbers in mini map and map>Filter View are gone! They can be brought back at all but I had to reinstall a game.  

Field map numbers can be seen if you are in map view and press "X" going in to Farmland mode and if you are at "Active workers"

I reinstalled game to vanilla state and replicated this behavior.

**Actual behavior**
Open a new game easy mode, Elmcreek
On field 45 try to create fieldwork with TopLiner 4090H harvester 
Course is in <script src="https://gist.github.com/MainPwrSrc/3166dfd09f773244cf9eb344f8c68d15.js"></script>
After you press generate field work and exit, go to map view
There are no field ID numbers on map view > Filters
There are no field ID numbers on mini map on main screen

**Expected behavior**
I expected to field IDs be visible as they are used to be in Mini map and in map view when Filters are on screen as 

**Screenshots**
Attached.

**Courseplay version**
Version used: v7.0.1.1

**Log**
Attached

**Map**
Elmcreek but when fields ID are gone, they can not be seen nowhere. No on new save, or any other map at all.

**Vehicles/ implements involved**
vehicle  TopLiner 4090H
Mod - no 

**Relevant script mods**
Autodrive 2.0.0.4 and VCA are active.

![fsScreen_2022_02_18_22_36_39](https://user-images.githubusercontent.com/96818792/154764819-a6092b1f-9f75-4aa9-bdba-d6cd0d6a195c.png)
![fsScreen_2022_02_18_22_36_24](https://user-images.githubusercontent.com/96818792/154764829-ba860d0c-67fc-4187-a0fe-1d4a2fa37c85.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8100577/log.txt)

**Comment by Tensuko** [comment]
Good morning... #1031
