### ISSUE TITLE
[BUG_SP] Plowing problems

### ISSUE THREAD

**Issue by Zwoxlol** [Courseplay/Courseplay_FS22#1041]
**Courseplay version**
Version used: [v7.0.1.1]

**Log**
https://pastebin.com/PtXRcJMS

**Map**
US

**Vehicles/ implements involved**
Lizard Untergrundlockerer 6MT/9MT (Modhub)

Is there a way to prevent this? It happens with almost all plows. I noticed that it also happens more often with the Cultivators. 

![image](https://user-images.githubusercontent.com/65707907/154765332-b470dcd1-f640-4743-b4de-5b281e5d65dc.png)

![image](https://user-images.githubusercontent.com/65707907/154765452-24a5308d-66eb-4992-b43d-55a73871eb5e.png)

**Comment by Zwoxlol** [comment]
![image](https://user-images.githubusercontent.com/65707907/154769421-0313bbd6-8f11-45df-95b1-e6c2cc374fa2.png)

![image](https://user-images.githubusercontent.com/65707907/154769718-66b8752b-1832-4788-a6bc-4393dc93bde0.png)



Here the cultivator problem.

**Comment by regs1980** [comment]
If you reduce the working width by half a meter in CP, then this will not happen

**Comment by Zwoxlol** [comment]
> If you reduce the working width by half a meter in CP, then this will not happen. CP can do a lot, but not everything Set late raise and early lower

Half a meter? That's not a solution.
"but not everything" So the in game helper CAN do it. So why should CP not be able to.
"Set late raise and early lower" I have that on of my machines.

**Comment by regs1980** [comment]
Allow using the pathfinder in turns already tried in the vehicle settings

**Comment by Zwoxlol** [comment]
> Allow using the pathfinder in turns already tried in the vehicle settings Maybe that will make it better

Both Pathfinder Options are active

**Comment by regs1980** [comment]
Work on the lanes does not start in the headland

<img width="1114" alt="Screenshot_2" src="https://user-images.githubusercontent.com/13314443/154797547-9514b389-89b9-4747-aedc-69804e628ae3.png">

<img width="1395" alt="Screenshot_1" src="https://user-images.githubusercontent.com/13314443/154797586-bbefce37-8e06-4486-b7ed-66caacb146d8.png">

The field is clean

<img width="1524" alt="Screenshot_3" src="https://user-images.githubusercontent.com/13314443/154797686-af517bbe-4f72-46a4-a2b4-c48f92812724.png">

**Comment by pvaiko** [comment]
@regs1980 have no idea what are you trying to say with your last post.

**Comment by regs1980** [comment]
he starts at the headland, i have never seen a plow or cultivator that starts at the headland

**Comment by pvaiko** [comment]
It starts according to the setting you selected in the course generation screen. I'd recommend carefully reading all course generator settings before posting problems.

**Comment by Tensuko** [comment]
The base problem of this Issue is the plow that does't get into the turn the correct way and got nothing to do with the connection between headland and center...

Only the end post of @Zwoxlol is the not always so nice working connection track turn into the rows.

**Comment by pvaiko** [comment]
@Zwoxlol one way to prevent it would be disabling reverse for pathfinder.

**Comment by Tensuko** [comment]
Comes in 7.0.1.3
