### ISSUE TITLE
Lose all control of character

### ISSUE THREAD

**Issue by Pontiac76** [Courseplay/Courseplay_FS22#1043]
[EDIT] Removed references to slow tractors.  Seems the tractor I was using just wasn't up to the task and I didn't notice pre-install of this mod.

**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
- Load up an existing save
- Start this process NOT in a tractor
- Hit ESC, select Workers
- Select a worker
- Create the job using CP: Fieldwork
- Select custom field and start point
- Set headland to 2
- Generate
- Start job
Returns to main screen
- Move character, and all I can do is turn while the character moves backwards
- Lose control of most other keyboard controls.  Cannot hit ESC to bring up the menus

Second attempt:
Repeat the above but be IN the tractor.  Same effect essentially.  I can't ESC to the menu, I can't control the tractor.

**Actual behavior**
https://youtu.be/glvKiNBZXFs
A movie is worth a billion words

After this video, I tried a few different things;
- I reloaded the game, disabled all mods except CoursePlay.  I ran into the same problem.
- While I was in character mode, I hit TAB to switch to the tractor I wanted to do the work, still couldn't hit ESC to get out to the menu
- I hit H to unhire the worker and I got all my controls back.
- While in the tractor, I hit CTRL-H to hire the CP Worker, and the tractor started doing its job.

**Expected behavior**
The tractor should start on its own.

**Screenshots**
See YouTube video above

**Courseplay version**
Version used: 7.0.1.2

**Map**

**Vehicles/ implements involved**
Mower

**Relevant script mods**
All mods turned off eventually with the same result.

**Comment by Tensuko** [comment]
And you removed the most important part of that whole report...
logfile ?!

**Comment by Pontiac76** [comment]
That was my bad.  Sorry.

I've since been able to get the tractor to go.  I relaunched my game just now to get the log for you, but, it's working as expected, even with the completely wrong trailer.

If I run into this again, I'll repost.  Closing ticket.
