### ISSUE TITLE
[BUG_SP] Harvester continues work without fuel

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#1046]
The harvester continues working even after the vehicle runs out of fuel - see video. Helper buying fuel is switched off. Vehicle cannot be moved by player anymore.

**Expected behavior**
If I remember right, in FS19 Courseplay stopped working an gave a notice to refuel the vehicle.

**Screenshots**
see video

**Courseplay version**
Version used: 7.0.1.0

**Log**
see attachment

**Map**
NF mit Gräben

Only this mods are active:
- FS22_Courseplay
- Iconik_claas_harvester_pack_fs22

[log_20220219.txt](https://github.com/Courseplay/Courseplay_FS22/files/8101890/log_20220219.txt)

https://user-images.githubusercontent.com/76711921/154796439-e1146e38-e0fb-40fc-93bb-61ac914f3ada.mp4

**Comment by Tensuko** [comment]
That comes from the game and is the same with AD.
