### ISSUE TITLE
[BUG_SP] Frontank bei der Lemken Azurit 9 

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1047]
**Steps to reproduce**

Einfach die Lemken Azurit mit Frontank Ansähen lassen

**Actual behavior**

Hallo ich ich Spiele auf der NF Marsch. Die Saatkombi Lemken Azurit 9 mit Frontankt senkt bei der Cp Feldarbeit den Frontank mit auf und ab was so eigentlich nicht sein sollte (Denke ich zumindest)  

**Screenshots**
![fsScreen_2022_02_19_11_07_54](https://user-images.githubusercontent.com/80832669/154796588-48187aad-a7d0-40c4-bb30-b47b411d9025.png)
![fsScreen_2022_02_19_11_08_09](https://user-images.githubusercontent.com/80832669/154796592-120aeb08-923d-4342-8ade-a694f2a9ef1a.png)
![fsScreen_2022_02_19_11_07_10](https://user-images.githubusercontent.com/80832669/154796603-d0c211f7-903e-459c-9be0-58ae8b400577.png)
![fsScreen_2022_02_19_11_07_32](https://user-images.githubusercontent.com/80832669/154796610-9b306231-aa12-46bf-b2cb-26c55bfff142.png)

**Courseplay version**
Version used: 7.0.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8101908/log.txt)

**Map**
Nf Marsch 4 Fach mit Gräben

**Vehicles/ implements involved**
Fendt 724 Privat Umbau
Lemken Azurit 9 mit Fronttank (Beide Orginal)

**Relevant script mods**
Autodrive 

Falls noch Fragen sind oder ich was nicht richtig beschrieben habe bitte melden

**Comment by Tensuko** [comment]
Hmm ja bei der hast du recht, bei der Kuhn gehört es so.
Müssen wir mal schauen wie wir das machen.

**Comment by Tensuko** [comment]
Comes in 7.0.1.3
