### ISSUE TITLE
[Question] Hot Fix Beschreibung zu 7.0.1.2 verwirrend:

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/Courseplay_FS22#1048]
Eure Hot Fix Beschreibung ist etwas verwirrend, ich denke mal da Fehlt was:
"To get the field numbers back, go into ..\My Games\FarmingSimulator2022 and open the gameSettings.xml look for 0 and set the number back to 0."

Ich denke da fehlt das ingameMapFilters und dass man es von 2 auf 0 ändern soll :)

**Comment by Tensuko** [comment]
Oh scheiße.... hat recht der hat da etwas weggenommen.... danke ich fixe das eben.

**Comment by Clouseau219** [comment]
Wenn du noch die eine 0 gegen eine 2 tauscht dann passt es zu 100% :)

**Comment by Tensuko** [comment]
Hmm naja bei mir stand dort 18, von daher weis ich nicht was ich da als beispiel jetzt nehmen soll :D
