### ISSUE TITLE
[BUG_SP] Lead combine stops causing following combine to run into it

### ISSUE THREAD

**Issue by PittBoss97** [Courseplay/Courseplay_FS22#1055]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Setup two combines to combine a field with one headland and land field center using six passes per land. Start first combine and then start second combine to get started.  

**Actual behavior**
Both combines go around the field once and start on the center of the field. First couple lands are perfect then when they start the next land the lead combine stops after the turn second combine makes the turn and runs into the lead combine. If you place the second combine in front of the lead combine they will continue the course. 
Video Below Shows what happens.
https://youtu.be/4hvOqlxgsTI

**Expected behavior**
Lead combine should continue on ahead of the second combine throughout the whole field

**Courseplay version**
Version used: 7.0.0.28

**Log**
https://pastebin.com/raw/SYMcjpa3

**Map**
Deer Creek

**Vehicles/ implements involved**
John Deere X9 1100 and Claas Lexion 8800 both mods from Farming-Simulator.com modhub
Mod yes/no ?

**Relevant script mods**
Vehicle Enhancement Mod

**Comment by Tensuko** [comment]
Old Version, not complete logfile.....
