### ISSUE TITLE
[BUG_SP]  CP Doesn't recognise it runs out of fuel?

### ISSUE THREAD

**Issue by RayVolker** [Courseplay/Courseplay_FS22#1056]
CP doesn't recognise when vehicle has run out of fuel and continues to operate. Once CP is stopped manually or at end of course machine reports Needs to be refueled. Using CP V.7.0.1.1. Tried on multiple machines. Playing on Deere Creek Map.

**Comment by Tensuko** [comment]
7.0.1.2 is newest and say thanks for Giants, AI Driver runs without fuel, same for AD.
