### ISSUE TITLE
CP Vers. 7.0.1.2. Singleplayer Modus Field Numbers are not available.

### ISSUE THREAD

**Issue by Kniescheibe04** [Courseplay/Courseplay_FS22#1057]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by regs1980** [comment]
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.0.1.2

**Comment by Tensuko** [comment]
Correct
