### ISSUE TITLE
[Question] Abstand Konvoi bei Inselumfahrung gestört

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1058]
Bin mir nicht sicher, ob das ein Fehler ist oder nur Fehlbedienung: Habe ein großes Feld mit 2 kleinen, runden Inseln. Generiere einen Kurs mit 2 Mähdreschern und Inselumfahrung als Kreis. 
![a](https://user-images.githubusercontent.com/96873819/154837407-d2a85c7b-893c-4bc8-afbc-d5689297f0ba.png)

Bis zur ersten Insel fahren die Drescher schön im Abstand (links zuerst, rechts dahinter). Hab nicht zugeschaut, aber wahrscheinlich ab der ersten Insel ist plötzlich der rechte Drescher knapp vorne. Bei jeder Wende fahren die nun ineinander. Neustart ab nächstem Wegpunkt hilft nicht. Abstand wird wieder (verkehrt) hergestellt. 

Konvoi Abstand war in beiden Dreschern zum Kursanfang unterschiedlich und im Bereich 80-120m. Nach Insel 1 habe ich den Abstand auf 180m angehoben, damit der linke Drescher wieder (ca. 20-30m) vorne ist.  Nach Insel 2 (rechter Drescher außen) ist der Abstand automatisch wieder größer.

Laienhafte Vermutung: Durch die unterschiedlichen Radien bei den Inseln, wird der Abstand auf der Geraden durcheinander gebracht. 

Hab leider nach Insel 2 vehicle debug eingeschaltet. Keine Ahnung ob es hilft. 
[log - Kopie (4).txt](https://github.com/Courseplay/Courseplay_FS22/files/8103758/log.-.Kopie.4.txt)

Nebenbei: Welcher Abstand in den Einstellungen ist bei 2 Dreschern ausschlaggebend? Drescher links oder rechts?

**Comment by throsten** [comment]
Ach ja. CP v7.0.1.2

**Comment by pvaiko** [comment]
> Laienhafte Vermutung: Durch die unterschiedlichen Radien bei den Inseln, wird der Abstand auf der Geraden durcheinander gebracht.

Glaube ich nicht. Eher das hier:
`X9 1100/224: WORKING: convoy: need 2 vehicles, 3 active, 0 done`

Da ist was passiert, vielleicht hast ein Fahrzeug gestoppt, mit einem anderen ersetzt, keine Ahnung, aber es waren irgendwie 3 Fahrzeuge in Convoy statt nur 2, und das hat die Berechnung durcheinandergebracht. 

Ich werde auf jeden Fall was einbauen das so etwas schöner abfängt, aber mehr werden wir für Convoy mit Inselumfahrung nicht machen...

**Comment by throsten** [comment]
Das dritte Fahrzeug ist möglicherweise ein Traktor mit Ballenpresse gewesen. ;-) Wusste nicht, dass das den Konvoi stören kann. 

Ich habe dieses Feld jedoch schon 2x mit diesem Kurs abgeerntet und beide Male war es zwischen den beiden Inseln komisch. Beim ersten Mal jedoch ohne Ballenpresse, die hatte ich da noch nicht. 

Kann ich was bestimmtes machen, wenn ich das Feld beim nächsten Mal ernte?

**Comment by pvaiko** [comment]
Glaub nicht, da stimmt was mit unserer Berechnung nicht, die denken dass die Entfernung nie unter 91 m war. Muss ich schauen, kann nichts versprechen.

> Nebenbei: Welcher Abstand in den Einstellungen ist bei 2 Dreschern ausschlaggebend? Drescher links oder rechts?
Abstand ist zwischen zwei nachfolgenden Fahrzeuge, die Reihenfolge ermittelt CP selbst, also wer auch immer mehr Progress hat ist vorne.

**Comment by throsten** [comment]
[log - Kopie (5).zip](https://github.com/Courseplay/Courseplay_FS22/files/8122048/log.-.Kopie.5.zip)

Möglicherweise hilft das Log: Ich habe auf dem gleichen Feld einen neuen Kurs generiert. 2 Drescher, 2 Vorgewende, 6 Bahnen und einfache Inselumfahrung. Abfahren mit AD, Debug eingeschaltet.

Beobachtungen: 
- Abstand bei einfacher Inselumfahrung bleibt anscheinend gleich. Das funktioniert also. 
- Die Drescher sind aber bei der Wende einer Bahn vor der ersten Insel ineinander gefahren. Drescher links hat nach der Wende am Bahnanfang auf Drescher rechts gewartet und ist bei dessen Ankunft nicht losgefahren. 
- Das Abtanken am Feldende mit AD hat nicht funktioniert (ist aber glaube ich ein bekannter Fehler).

Nebenbei: Wie kann ich nur einen Traktor mit Ballenpresse auf einem Kurs von 2 Dreschern fahren lassen? Wollte das Feld damit erst links, dann rechts abfahren lassen. Der Traktor fährt erst los, hält aber nach ein paar Metern an.

**Comment by pvaiko** [comment]
> Die Drescher sind aber bei der Wende einer Bahn vor der ersten Insel ineinander gefahren. Drescher links hat nach der Wende am Bahnanfang auf Drescher rechts gewartet und ist bei dessen Ankunft nicht losgefahren.

Das ist eine komplizierte Situation, wahrscheinlich ist der Weg um die Insel ungefähr so lang wie die Eingestellte Entfernung. Da fragt man sich ob es sich lohnt, die eigene Zeit in diese Grenzfälle zu investieren, es gibt wahrscheinlich andere Bereiche wo mit deutlich weniger Aufwand deutlich mehr Gewinn zu erreichen ist.

> Wie kann ich nur einen Traktor mit Ballenpresse auf einem Kurs von 2 Dreschern fahren lassen? Wollte das Feld damit erst links, dann rechts abfahren lassen.

Das geht momentan noch nicht, aber wir arbeiten dran, das ist ein gutes Beispiel für wenig Aufwand, viel Nutzen.

**Comment by throsten** [comment]
Die Kollision war (aus meiner Laien-Sicht) unabhängig von der Insel, da mehrere Bahnen davor und bei einer Wende auf eine andere Bahn. 

Unabhängig davon kann ich die Aufwand/Nutzen Argumentation voll verstehen. Da habt ihr einen besseren Überblick. Wollte nur helfen.

**Comment by Tensuko** [comment]
Ist Teil von Update 7.0.1.3 (soon)
