### ISSUE TITLE
Kurs wird nicht richtig abgefahren

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/Courseplay_FS22#1059]
Hallo ich habe einen Bug bemerkt.
Hierbei geht es darum das der Kurs nicht richtig abgefahren wird.
Bemerkt habe ich das bei dem 10 Meter Pöttinger Mähwerk. Die Arbeitsbreite ist auf 10 Meter eingestellt mit einer Überlappung von 7% und 1 Vorgewende. Ihr könnt es selbst testen. Benutzt habe ich den Fendt Varo 942 mit den Mähwerken Pöttinger NOVACAT 301 AM ED Pro und dem Pöttinger NOVACAT A10 Cross Flow auf dem Feld 36 auf der Karte Haut-Beyleron. 

![Farming Simulator 22 20 02 2022 12_59_39](https://user-images.githubusercontent.com/89300041/154841511-f4c87feb-693b-4574-8c86-5a5241a4fba2.png)
e

**Comment by Terrabey** [comment]
Weiterhin werde ich andere Mähwerke testen um zu schauen ob es nur bedingt an dem Pöttinger ist oder auch bei dem anderen

**Comment by Tensuko** [comment]
Bugreports üben wir noch mal...

**Comment by Terrabey** [comment]
Warum hast du das Ticket geschlossen

**Comment by Terrabey** [comment]
Und was ist das für eine verarsche ihr wollt kaum an Info während die on Autodrive mich nach meinem ganzen Lebenslauf abfragen

**Comment by Tensuko** [comment]
Man kann es auch übertreiben mit der Dramatik!
Es gibt Grundlegende Info die wir brauchen, das hat nichts mit Verarsche zu tun!
Ausfüllen oder sein lassen, sonst bringt es GAR nichts.

**Comment by Tensuko** [comment]
> ihr wollt kaum an Info während die on Autodrive mich nach meinem ganzen Lebenslauf abfragen

Wir haben Issue Templates, im gegensatz zu AutoDrive, ich weis nicht was du hier verwechselst ?!
