### ISSUE TITLE
Grubber grubbert nicht bis an den Feldrand

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/Courseplay_FS22#106]
s. Bild, evtl. liegt es nur an dem speziellen Grubber (Amazone Cenio 4000 Super). Gerät anheben auf spät, absenken auf früh
![fsScreen_2021_12_26_08_54_59](https://user-images.githubusercontent.com/21023840/147402405-c5d15558-e02a-477a-9bc2-31b693215044.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7776699/log.txt)
.

**Comment by rohne83** [comment]
Das war auch im 19er schon so. Nicht nur Grubber, sondern zB auch Mähdrescher lassen/ließen da gerne etwas stehen. Sobald du aber mindestens ein Vorgewende machst (auch wenn augrund der großen Grasfläche am Rand eigentlich gar keins nötig ist), wird alles sauber bearbeitet.

**Comment by Keppchen** [comment]
Dafür gibt es die Option "Gerät anheben = spät". Das hat bei mir geholfen. Grubber, Pflug, Saatmaschine, Walze gehen jetzt alle bis zum Ende

**Comment by Tensuko** [comment]
Dafür ist das setting auch da.

**Comment by iljarogoff** [comment]
Ich hab oben geschrieben, dass ichs so eingestellt hab - dennoch lässt er was stehen
