### ISSUE TITLE
[BUG_SP] Arbeitsbreite manuell einstellen Bredal K165 nicht möglich

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1060]
**Steps to reproduce**
Düngerstreuer Bredal K165 anbauen und im Helfer Menü einen neuen CP-Job erstellen. Kursgenerator öffnen

**Actual behavior**
Die Arbeitsbreite lässt sich nur manuell über die Pfeile ändern. 

**Expected behavior**
Ein Klick auf den aktuellen Wert und damit die Direkteingabe der Arbeitsbreite ist nicht möglich.

**Courseplay version**
Version used: V7.0.1.2

**Log**
https://gist.github.com/alexx2104/1243567507aed4148cad3de7ac4b9f07

**Map**
NF Marsch 4fach ohne Gräben Version 1.3.1

**Vehicles/ implements involved**
McCormick X8.631 VT-Drive
Bredal K165 Düngerstreuer

**Relevant script mods**
nope

![2022-02-20 17_32_15-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/154853507-2d9e7a80-cd57-44e0-9c1a-75b51d233506.png)
![2022-02-20 17_32_26-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/154853509-304ee99e-b694-458e-9da8-8272bb7b20e3.png)
![2022-02-20 17_32_32-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/154853510-f0c6ab07-edfc-472a-a661-62662b48f874.png)

**Comment by regs1980** [comment]
Das lustige ist, wenn ein KFZ vor dem Bredal K165 angespannt ist beim Spielstart, dann lassen sich die Werte verändern, hängt man ihn aber ab und wieder an, dann tritt der Fehler auf.

**Comment by TobiHH78** [comment]
Ging mir heute mit unterschiedlichen Geräten und Fahrzeugen genauso. Konnte bei keinem Gerät den Wert manuell eingeben

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8104593/log.txt)
.

**Comment by alexx2104** [comment]
Generell wäre es schön, wenn automatisch erkannt werden würde, wenn im Düngerstreuer Kalk geladen ist. Dann beträgt die Arbeitsbreite ja nur noch 18m statt 30m. Aber keine Ahnung inwiefern das überhaupt möglich ist.

**Comment by Tensuko** [comment]
Neu Ankuppel wenn Kalk drin ist sollte gehen.
Momentan ist es nur durch an und abkuppel erkennbar, oder refresh im HUD (auf den Text klicken, könnte auch gehen).

**Comment by schwiti6190** [comment]
The original post is a duplicate of #983.
And the different work width for lime/fertilizer will be continued here #1067.

**Comment by alexx2104** [comment]
V7.0.1.3 eingesetzt. Problem besteht weiterhin. Arbeitsbreite mit Bredal K165 angehangen lässt sich nicht anpassen.

**Comment by alexx2104** [comment]
@Tensuko pls reopen.
