### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by SwedenT** [Courseplay/Courseplay_FS22#1061]
When using to workers on the same field, the speed is very inconsistent and hardly above 80% of implement capacity, and also the distance between the tractors are not consistent. Also when making turns at the end of the lands takes a lot of time, and has very irregular turns

On a flat land it should be able to control the speed

**Courseplay version**
Version used: 7.0.1.2

**Map**
Map played on wild west

**Vehicles/ implements involved**
Which vehicle or implement? CaseIH Steiger 620 and Schommie Cultivator 1425
Mod yes/no ? Tractor No Cultivator Yes

Otherwise, I'm very impressed with the amount of work put in to something like this

**Comment by Tensuko** [comment]
I don't see a problem here, also not a full report.
Calculation tweaks will be done but that is handeld in another Issue.
Don't forget that gearshifter on some tractors does have impact as well and some tractors get into some weird point of speed and power limit and shifting up and down.
So I can't tell whats the provblem.
Also what about the distance setting and so on...
Will close this, as there is no logfile and clear example on whats rly happening here, sry.
