### ISSUE TITLE
How to edit/delete custom field[Question]

### ISSUE THREAD

**Issue by Mannhood** [Courseplay/Courseplay_FS22#1075]
Hi
TY For your hard work on this mod I and many others apreciate it alot. My issue is I need to edit or delete a custom field that i have drawn. But I do not know how

**Comment by dominiczeth** [comment]
On the map for field jobs click anywhere so that no vehicle is selected. Then click on the name for the custom field and choose "delete" (I think it's backspace

**Comment by Tensuko** [comment]
Click the Name. Its all written in the help menu.
