### ISSUE TITLE
[BUG_SP] Anhänge Rübenernter + Ropa Anhänge Kartoffelernter + Wendemanöver

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1079]
**Steps to reproduce**
Krauthacker + Rübenernter(Grimme Rootster) für Traktor Feld ernten lassen und Selbst abtanken lassen

**Actual behavior**
Problem ist das er beim Selbstabtanken die breite des Rohres nicht beachtet und in den Hänger fährt. Das gleiche hat der Ropa keiler auch

2. Beim wenden am Feld Ende (Vorgewende) 
hebt er die geräter nicht aus und wendet komisch (Weiß aber nicht 
ob das durch den Graben ist
**Expected behavior**

**Screenshots**
Bilder zwecks Selbstentladung
![fsScreen_2022_02_23_01_31_07](https://user-images.githubusercontent.com/80832669/155243213-ab4dbec8-64c5-4fa9-9f19-e63720b737a4.png)
![fsScreen_2022_02_23_01_31_30](https://user-images.githubusercontent.com/80832669/155243236-8b79ac0b-c7cf-4c06-9df9-e4059884e618.png)
![fsScreen_2022_02_23_01_31_38](https://user-images.githubusercontent.com/80832669/155243270-3d983c09-c379-4e7e-beef-ac70aa207c95.png)
![fsScreen_2022_02_23_01_31_40](https://user-images.githubusercontent.com/80832669/155243292-2d534bda-62cd-446e-8e75-3a76f8b80d25.png)
![fsScreen_2022_02_23_01_31_43](https://user-images.githubusercontent.com/80832669/155243180-9e600797-9ab5-46f9-b948-bdb275587679.png)

Problem Vorgewende Drehung

![fsScreen_2022_02_23_01_35_57](https://user-images.githubusercontent.com/80832669/155243588-a3d52b46-0136-4a1c-b208-803e86f8442a.png)
![fsScreen_2022_02_23_01_36_07](https://user-images.githubusercontent.com/80832669/155243624-639e55a1-6d5d-4072-a1a3-e2f53a0b4b20.png)
![fsScreen_2022_02_23_01_36_09](https://user-images.githubusercontent.com/80832669/155243664-e477672c-2c88-49a5-aff6-8e9e9ee7134f.png)
![fsScreen_2022_02_23_01_36_14](https://user-images.githubusercontent.com/80832669/155243706-c5d01d1b-d7e2-4ac6-adc7-072c72448a3e.png)
![fsScreen_2022_02_23_01_36_21](https://user-images.githubusercontent.com/80832669/155243557-7e3b6def-c2a6-49c0-b135-9978f191128e.png)

**Courseplay version**
Version used: 7.01.2

**Log**
Log Selbstentladung
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8121085/log.txt)
Log Vorgewende
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8121101/log.txt)

**Map**
Nf Marsch mit Gräben

**Vehicles/ implements involved**
Which vehicle or implement?
Mod: Privater Traktor

**Relevant script mods**

Autodrive, Courseplay

**Comment by michal3110** [comment]
I also reported this problem and it was written off to me that it is not a problem, obviously there is a problem with these beet and potato vehicles 

https://github.com/Courseplay/Courseplay_FS22/issues/902

**Comment by pvaiko** [comment]
@michal3110 No one said there's no problem, you should probably read more carefully. Also #902 is still open, meaning it isn't fixed, not sure what is your point?

**Comment by pvaiko** [comment]
#1249 should have addressed the unload part of this
