### ISSUE TITLE
[Question] Kurs synchronisieren im MP

### ISSUE THREAD

**Issue by OliWit82** [Courseplay/Courseplay_FS22#1082]
Hallo, vielen Dank für die super Arbeit. 

Hab da eine Frage. 
Gibt es die Möglichkeit das die Kurse im Multiplayer auf dem Dedi Server gespeichert werden und mit den anderen Mitspielern synchronisiert werden?
Bei uns ist es aktuell so das jeder nur seine eigen generierten Kurse sieht. 

vielen Dank

**Comment by Tensuko** [comment]
Später.
Speichere einfach den Kurs aus dem Traktor deiner Mitspieler oder tausche Dateien aus.
