### ISSUE TITLE
[Question] MP Gespeicherte Kurse

### ISSUE THREAD

**Issue by Biebe83** [Courseplay/Courseplay_FS22#1084]
Hallo, vieleicht liegt es an uns aber wenn mein Kollege Kurse im CP speichert sehe ich die nicht bei mir auch wenn ich welche speichere sieht mein Kollege auch nicht. Server oder Spiel neu starten bringt auch nichts. Gibt es das ne Einstellung im CP oder kommt das erst noch in einer neuen Version vom CP. MFG

**Comment by Tensuko** [comment]
100 mal beantwortet, suche benutzen hilft....
Kurse werden aktuell nur lokal gespeichert.
Wenn dein Kollege einen Kurs von dir will, rein in den Traktor und selber abspeichern.
