### ISSUE TITLE
[BUG_SP] Minimap broken after install courseplay - Mac

### ISSUE THREAD

**Issue by raphaelmnobrega** [Courseplay/Courseplay_FS22#1085]
I am playing FS22 on my MacBook Pro. After installing the courseplay, my minimap is broken; I can't see the player mark in the minimap, so looking at the minimap, it is impossible to know where you are and which direction you are pointing. Also, all the field numbers in the minimap are gone.

**Comment by Tensuko** [comment]
And why you did not fully fill in the bug report ?!
Guess why we have a part "logfile" wich would help now.
And I forecast, that you have the wrong version and or didn't follow the instruction in 7.0.1.2 changelog.

**Comment by Tensuko** [comment]
Closed due to inactivity.
