### ISSUE TITLE
[BUG_SP] Course generation: up/down row does not reach headland

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1086]
**Steps to reproduce**
Drive generated course at this turn position

**Actual behavior**
Course not generated correctly at the marked turn position. Game crashes if driver comes to this position. 
![fsScreen_2022_02_23_17_13_30](https://user-images.githubusercontent.com/96873819/155361136-fe4a3c18-450a-4da4-8ad5-4588e6ed2583.jpeg)

When you do some minor changes at generation, it works correct, i.e. change width 0,1m or overlap%.
I have also seen that a complete row is missing at this field, but never driven this course. 

**Expected behavior**
Drivable courses. 

**Courseplay version**
Version used: 7.0.1.2

**Log**
[log - Kopie (6).txt](https://github.com/Courseplay/Courseplay_FS22/files/8125992/log.-.Kopie.6.txt)

**Map**
Mod Map: Deer Creek, big fields, not rectangular. 

Vanilla Tractor, Mod Seeder from Bourgault Pack. 

**Relevant script mods**
AD installed but not active

**Comment by Tensuko** [comment]
Don't understand that LUA Error in combination with Courseplay.
`2022-02-23 17:10 Error: Running LUA method 'update'.
dataS/scripts/objects/LoadingStation.lua(257) : bad argument #1 to 'min' (number expected, got nil)`

**Comment by pvaiko** [comment]
That's a mystery. @throsten I need the field definition XML (see Wiki)

**Comment by throsten** [comment]
Maybe I have to change the topic. I generated a new course (deleted the old one) with a defect. Tractor with weeder drive thru the strange turn without any problem as the course look like, see log.
[log - Kopie (7).txt](https://github.com/Courseplay/Courseplay_FS22/files/8129822/log.-.Kopie.7.txt)

Maybe it was something in the background that let the game crash by random reason while I was looking in the CP vehicle.

**Comment by throsten** [comment]
@pvaiko here you have the file. 
[cpFields.zip](https://github.com/Courseplay/Courseplay_FS22/files/8129837/cpFields.zip)

Took i.e. this values to generate a course:

![fsScreen_2022_02_24_06_06_19](https://user-images.githubusercontent.com/96873819/155462957-444c28b4-0c10-4c3a-b7f8-1d6aff66d8df.png)

![fsScreen_2022_02_24_06_06_22](https://user-images.githubusercontent.com/96873819/155462969-29ef3830-bb76-4189-abe7-e5f0194abf95.png)

You can see the defect in the background. at the same corner. For the next screen shot I changed only the headland overlap to 4%. Start point always the same. 

![fsScreen_2022_02_24_06_06_54](https://user-images.githubusercontent.com/96873819/155463147-aed281f1-1c95-449e-b44d-ccbf77ac517a.jpg)

**Comment by Tensuko** [comment]
Comes in 7.0.1.3
