### ISSUE TITLE
[Feature] Increase Working Width

### ISSUE THREAD

**Issue by schwyl** [Courseplay/Courseplay_FS22#1087]
**What is the problem this feature/enhancement solves?**
Working width maxes out at 50m

**Describe the solution you'd like**
Allow working widths above 150m

**Comment by Tensuko** [comment]
Why should we do this ?

**Comment by schwyl** [comment]
To allow those with mods to continue to enjoy using CP for field work

**Comment by Tensuko** [comment]
150m ?! Why on earth, no real work tool does have this.
Tell me what it is for and I consider this and not simply "to continue to enjoy using CP for field work"

**Comment by schwyl** [comment]
Some mods have a tool width of 100m + for fun on the crazy large fields. Its fun to use CP on those fields. When CP has a max of 50m it creates a ton of overlap. So I figured increasing the max working width to something nice a high would allow people to use those mods and CP.

**Comment by Misamangame** [comment]
Using 100+m tools on big fields is same like using 3m tools on medium fields, then you can enjoy CP with all features without stupid unrealistic tools.

**Comment by schwyl** [comment]
Anyhow I figured out the code to do it. So thanks for the discussion
