### ISSUE TITLE
Siliertank wird als Korntank erkannt

### ISSUE THREAD

**Issue by NEA1971** [Courseplay/Courseplay_FS22#109]
Hallo zusammen,
ich konnte gestern in der Version 7.0.0.3 mit dem Fendt Katana kein Mais häckseln. Der Katana ist mit einem Siliermittel-Tank ausgestattet und der war hier voll. Ich meine es kam sogar die Meldung, dass Helfer XY die Arbeit wegen vollem Korntank beenden musste, obwohl der Katana natürlich gar keinen Korntank hat...
VG

**Comment by Tensuko** [comment]
Könntest du für uns einmal schauen, wie der Giants Helfer damit umgeht ?
Kann der das ?
Wenn nein, dann müssen wir uns da was überlegen.

**Comment by NEA1971** [comment]
mach ich nachher. Ich meine aber, dass das mit dem internen Helfer normal funktioniert. Autodrive hatte mit dem Thema auch ein Problem....ich schau' aber nochmal nachher.

**Comment by nimanox** [comment]
meines wissens nach häckselt der einfach ohne siliermittel weiter

**Comment by NEA1971** [comment]
@nimanox das ist richtig, darum geht es bei der Problembeschreibung aber nicht - das Problem ist, dass der Häcksler mit vollständig gefülltem Siliertank nicht das Häckseln anfängt, erst wenn man den Siliertank etwas leergefahren hat funktioniert das wieder...

@Tensuko ich habe das jetzt mal mit dem Giants-Helfer und CP über das ESC-Menü ausprobiert. Giants funktioniert, bei CP kommt die Meldung mit vollem Korntank. Ich habe Screenshots von beiden Helfern gemacht...
![LS22-Siliermittel_CP](https://user-images.githubusercontent.com/45850108/147412266-04f27181-b9b8-4cd3-8bf1-b9836025e60e.png)
![LS22-Siliermittel_GiantsHelfer](https://user-images.githubusercontent.com/45850108/147412269-cea09835-a485-4d1f-9c35-3190d6282528.png)

**Comment by Tensuko** [comment]
Ok danke, dann müssen wir das für Häcksler anpassen.

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.

Additional Info:
If empty, there is no check yet, but is on our TODO.
