### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by sschiebrel** [Courseplay/Courseplay_FS22#1091]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
elmcreek new game
accept sowing contract, borrow equipment
generate a temp course and start at first waypoint.   
**Actual behavior**
the seeder unfolds, with a message stating it's empty, if I start the seeder manually for the first few secs, then engage at nearest waypoint, the green arrow on the minihud dissapears (not goes from green to dull.. the arrow is removed altogether).   the tractor then is set on cruise with no autosteering.  I can steer but not stop nor cancel the job.   in the worker menu, I show the worker up in the top corner working, but also have the option to create job, but not cancel the current one.   interestingly, if I go back into the tractor and disconnect the seeder, the tractor will then follow the course laid out.  I'm still unable to stop the tractor or turn off cruise.

it may have something to do with the seeder having a fert bucket as well that I do not fill..

**Expected behavior**
I expected the tractor to sow the field according to the corse.

**Screenshots**

**Courseplay version**
Version used: 7.0.1.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.  elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?  mccormick  x7.24   seeder  terrasem c6f
Mod yes/no ?  no

**Relevant script mods**
Mods like Autodrive or VCA and so on.  autodrive is installed but not used in this case.

**Comment by sschiebrel** [comment]
just went back and put fertilizer in the seeder as well... it then worked as excpected.   so I guess the request is to make fert optional for an AI worker on a seeder that can take both seed and fert.

**Comment by dominiczeth** [comment]
There is an option for fertilizer in the CP settings.

**Comment by Tensuko** [comment]
Just turn off fertilizer for the machine in settings.
