### ISSUE TITLE
[BUG_SP] Kurs umbenennen, alter Name bleibt im HUD, auch nach Kurs neu laden.

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1092]
**Steps to reproduce**
Kurs erstellen, diesen speichern, anschließend umbenennen.

**Actual behavior**
Kurs wird im Coursemanager (im ESC-Menü) umbenannt und korrekt angezeigt, im Mini-HUD bleibt der alte Name bestehen. Auch ein löschen des Kurses aus dem Fahrzeug und erneut laden ändert daran nichts.

**Expected behavior**
Kurs wird auch im Mini-HUD mit dem korrektem (neuen) Namen angezeigt

**Screenshots**
![image](https://user-images.githubusercontent.com/96819380/155523953-e8002bf2-e94b-436c-8a77-ec49fe3e9abc.png)
![image](https://user-images.githubusercontent.com/96819380/155523986-ce38d5c7-3c1d-4cbf-9fbd-8856b0869dfd.png)
![image](https://user-images.githubusercontent.com/96819380/155524011-ce23b2d0-9623-4037-a489-6d0a27bb76ee.png)

**Courseplay version**
Version used: V7.0.1.2

**Log**
https://gist.github.com/alexx2104/a419397b0ba2bfa313a1c703aac872a4

**Map**
NF Marsch 4fach ohne Gräben

**Vehicles/ implements involved**
McCormick XTV und Kverneland 12000 II DG, passiert aber bei allen Anbaugeräten

**Relevant script mods**
nope

**Comment by Tensuko** [comment]
Das ist kein Bug.
Den Kurs den du umbenannt hast ist der gespeicherte Kurse, nicht der geladene, welche extra behandelt wird.
Kurs neu laden und fertig.

**Comment by alexx2104** [comment]
Nein, reproduzier es bitte einmal selbst. Auch nach Kurs aus Fahrzeug entfernen und neu laden zeigt das Mini HUD weiter den alten Namen an

**Comment by alexx2104** [comment]
Thx 4 reopen

**Comment by Tensuko** [comment]
Comes in 7.0.1.3
