### ISSUE TITLE
Bug for Hosts in Multiplayer

### ISSUE THREAD

**Issue by Simonkirchi** [Courseplay/Courseplay_FS22#1097]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
When I played on a Lokal hosted server as Admin I have the Problem that I can´t open the cp menu and I can´t start a cp driver. [On first time I open my server and it work, but after rejoining it don´t work]

**Actual behavior**
When I played on a Lokal hosted server as Admin I have the Problem that I can´t open the cp menu and I can´t start a cp driver. [On first time I open my server and it work, but after rejoining it don´t work] My friend who joined the server can start cp, we are polaiing with 2 farms and than we have this bug. When we are Playing on one farm it works and we have nothing problemes. This problem is on all maps and cp versions. I have no problems in the log.

**Courseplay version**
Version used: I test it with all versions for Multiplayer

**Client Log**
I have nothin special in the log

**Player on the server**
2 Players

local hosted server

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
nothing

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Autodrive and VCA

**Comment by Simonkirchi** [comment]
When I played on a Lokal hosted server as Admin I have the Problem that I can´t open the cp menu and I can´t start a cp driver. [On first time I open my server and it work, but after rejoining it don´t work] My friend who joined the server can start cp, we are polaiing with 2 farms and than we have this bug. When we are Playing on one farm it works and we have nothing problemes. This problem is on all maps and cp versions. I have no problems in the log.

**Comment by Tensuko** [comment]
> **Client Log**
> I have nothin special in the log

That doesn't matter!
I want to see the logfiles.
And for MP, Server and Client will help more!

**Comment by Simonkirchi** [comment]
Ich habe herausgefunden das wenn ich die Taste zum öffnen des cp Menüs umlege ich das Menü wieder aufmachen kann. Jetzt kann ich auch wieder den cp Fahrer aktivieren. Ich weis nicht ob das daran gelegen hat vorallem da es sonst immer funktioniert. Ich habe auch sonst nichts an den Einstellungen geändert oder die cp Version gewechselt. Ich werde es jetzt mal eine weile testen und wenn wieder dieser Bug auftauchen sollte melde ich mich nochmal.
MFG und trotzdem vielen dank für die Antwort.  
( Ich möchte mich entschuldigen das ich es auf Deutsch schreibe. Ich bin nicht gerade gut in Englisch und das was ein Übersetzter da übersetzt macht so was von keinen Sinn so dass ich mich dazu entschieden habe auf deutsch zu schreiben.)

**Comment by Tensuko** [comment]
Wenn deutsch einfacher ist, kannst du auch deutsch schreiben. Trotzdem mach ich hier erst mal zu.
