### ISSUE TITLE
Extra Menu to adjust working width and offsets (to have a visual feedback)

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#11]
For later:
A menu that you can open when sitting inside a vehicle to adjust the working width and offsets with a visual feedback.
The lines are shown as long as you have that menu open.

![fsScreen_2021_12_13_19_09_43](https://user-images.githubusercontent.com/27344744/145870741-15702b94-ffa2-4006-acc5-c0e32433d4ea.png)

Right now I have no other Settings in mind where we would need visual Information, while changeing a setting.

**Comment by XPiRiJenZ** [comment]
Die aktuelle experimental sieht doch schon gut aus! Das Mini-HUD wird sehr viele Gemüter beruhigen, denke ich :)
Vermute aber, dass jetzt die Rufe aus der Comm lauter werden und weitere Funktionen gefordert werden...

**Comment by Tensuko** [comment]
Da magst du recht haben, aber der Platz dort ist limitiert und da wehren wir uns auch, etliche Dinge ein zu bauen. Es gibt 2-3 Dinge die man machen KÖNNTE, aber das bleibt ab zu warten... ich muss man Fahrzeug z.B. nicht beobachten wenn ich selfUnload aktiviere :)
