### ISSUE TITLE
Remove NAG screen in start-up [Feature]

### ISSUE THREAD

**Issue by BattleHook** [Courseplay/Courseplay_FS22#1102]
**What is the problem this feature/enhancement solves?**
I really don't like the nag-screen every time I start up a game. I read it once, I do not need to read it always,

**Describe the solution you'd like**
I would like to be able to hide the nag screen ( e.g. show no more option), since I have auto-start enabled in advanced setting mod, but it does not autostart now due to courseplay nag screen.

**Describe alternatives you've considered**
There are no  alternatives other than not using courseplay at the moment.

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/62392548/155808695-572a9845-6e6e-4e6a-a452-81311431e829.png)

**Comment by Tensuko** [comment]
@schwiti6190 is the check missing if the Version got written in the .xml ?

**Comment by ThomasBalder** [comment]
Just as an FYI: I have this issue too, but weirdly it does not seem to happen every time. Sometimes the pop-up does not show.
