### ISSUE TITLE
[Feature] Show (estimated) time remaining for course

### ISSUE THREAD

**Issue by ThomasBalder** [Courseplay/Courseplay_FS22#1108]
**What is the problem this feature/enhancement solves?**
Currently the only progress of the course is the amount of waypoints (i.e. 561/2886), but iirc in FS19 it showed the time remaining instead the amount of waypoints to go. As with FS19 showing time remaining gives you a better idea of progress.

**Describe the solution you'd like**
A timer that shows how long the current course takes/remains, similar of the same as with FS19.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Not applicable right now.

**Comment by Tensuko** [comment]
Alright, alright I keep it open here and close the Discussion :)

**Comment by venquessa** [comment]
I was thinking about this while playing last night.  I found timing 100 waypoints and then dividing that into the remainder gave me a time of 47 minutes and the field actually took about 49 minutes.
 
 In terms of implementation, not being a LUA developer, but pysdo design:
When a new course is loaded, or first waypoint is forced, reset a timer.  TotalTime = 0
When course play starts work, store the current sys time stamp.  startTime = SYS_TIME
When CP stops or is stopped, pause the timer (totalTime = totalTime + SYS_TIME-startTime)  startTime = null

The display then is just 
avgTimePerWaypoint = ((totalTime + startTime - SYS_TIME) / waypointsComplete  )
remainingTime = avgTimePerWaypoint * (totalWaypoint - wayPointsComplete )

It won't be accurate but it will be very indicative and close enough.

There maybe merit in trying to only time blocks of 100 waypoints and using that to estimate, this would address anything strange happening that speeds up the work or slows it down, like hills, trees, islands maybe.
