### ISSUE TITLE
Hächsler fährt nur noch ganz langsam

### ISSUE THREAD

**Issue by 60erjonny** [Courseplay/Courseplay_FS22#111]
Hallo
Mit den letzten Update, fährt der Hächsler nur noch ganz langsam und ruckelig.
Mähdrescher funktionieren jetzt gut.
Bei Version 7.0.0.3 ging es noch.
Log mit Debug 2+6 Channel erstellt und hoffe es passt so.
Bitte Info, wenn ich noch was nachreichen soll...
![fsScreen_2021_12_26_09_57_03](https://user-images.githubusercontent.com/63659182/147403557-16b8a019-f439-4c52-b7d5-d35cb4e7ff23.png)
![fsScreen_2021_12_26_09_57_09](https://user-images.githubusercontent.com/63659182/147403558-81fbb76d-d08d-4ae0-b41f-ed7776257c3d.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7776755/log.txt)
.

**Comment by Tensuko** [comment]
Bin mir nicht sicher, aber es könnte damit zusammen hängen: #113

**Comment by Tensuko** [comment]
Kannst du einmal die neueste Version damit testen ? 7.0.0.5

**Comment by 60erjonny** [comment]
Hallo

Leider hier keine Verbesserung..
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777243/log.txt)
.

**Comment by 60erjonny** [comment]
Problem tritt mit Courseplay for FS22 v7.0.0.7 nicht mehr auf...
