### ISSUE TITLE
[Feature] randkurse Anwählbar

### ISSUE THREAD

**Issue by LordNikon83** [Courseplay/Courseplay_FS22#1113]
**What is the problem this feature/enhancement solves?**
Randkurse die auf Feldern Liegen sind nicht anwählbar
**Describe the solution you'd like**
Vielleicht zusätztzlich zur Ziel/Feldposition noch eine option um einen Randkurs auszuwählen

**Comment by UnknownJoe** [comment]
Nice feature request. I just needed exact this. I rearranged some lines of code. Manual created courses will be selected first now.  

I dont know if it is helpful for you or for others who really need this feature and edit the code for themselves.

By the way. Thank you for this great mod. 

CpAiJobFieldWork.lua, Release 7.0.1.4
````
function CpAIJobFieldWork:validateFieldSetup(isValid, errorMessage)
	
	if not isValid then 
		return isValid, errorMessage
	end

	local vehicle = self.vehicleParameter:getVehicle()

	-- everything else is valid, now find the field
	local tx, tz = self.fieldPositionParameter:getPosition()
	
	self.customField = nil
	local fieldNum = CpFieldUtil.getFieldIdAtWorldPosition(tx, tz)
	CpUtil.infoVehicle(vehicle,'Scanning field %d on %s', fieldNum, g_currentMission.missionInfo.mapTitle)
	
	local customField = g_customFieldManager:getCustomField(tx, tz)
	
	
	-- Start Changes
	
	if not customField then
		self.hasValidPosition, self.fieldPolygon = g_fieldScanner:findContour(tx, tz)
		if not self.hasValidPosition then
			self.selectedFieldPlot:setVisible(false)
			return false, g_i18n:getText("CP_error_not_on_field")
		end
	else
		CpUtil.infoVehicle(vehicle, 'Custom field found: %s, disabling island bypass', customField:getName())
		self.fieldPolygon = customField:getVertices()
		self.customField = customField
		vehicle:getCourseGeneratorSettings().islandBypassMode:setValue(Island.BYPASS_MODE_NONE)
		self.hasValidPosition = true
	end;
	
	-- End Changes 
	
	
	--[[
	self.hasValidPosition, self.fieldPolygon = g_fieldScanner:findContour(tx, tz)
	if not self.hasValidPosition then
		local customField = g_customFieldManager:getCustomField(tx, tz)
		if not customField then
			self.selectedFieldPlot:setVisible(false)
			return false, g_i18n:getText("CP_error_not_on_field")
		else
			CpUtil.infoVehicle(vehicle, 'Custom field found: %s, disabling island bypass', customField:getName())
			self.fieldPolygon = customField:getVertices()
			self.customField = customField
			vehicle:getCourseGeneratorSettings().islandBypassMode:setValue(Island.BYPASS_MODE_NONE)
			self.hasValidPosition = true
		end
	end
	]]
	
	if self.fieldPolygon then
		self.selectedFieldPlot:setWaypoints(self.fieldPolygon)
		self.selectedFieldPlot:setVisible(true)
		self.selectedFieldPlot:setBrightColor(true)
	end
	return true, ''
end
````

**Comment by LordNikon83** [comment]
Thanks for the code, i´ll test it later.

**Comment by Nielwulf** [comment]
The code change worked as expected for me. I was finally able to select a custom field on Westby without it using a random field outline that didn't actually match anything.

**Comment by LordNikon83** [comment]
That was exactly what im looking for.

**Comment by FarmerMike87** [comment]
> Nette Feature-Anfrage. Ich brauchte genau das. Ich habe einige Codezeilen neu angeordnet. Manuell erstellte Kurse werden jetzt zuerst ausgewählt.
> 
> Ich weiß nicht, ob es für Sie oder andere hilfreich ist, die diese Funktion wirklich brauchen und den Code für sich selbst bearbeiten.
> 
> Übrigens. Vielen Dank für diesen tollen Mod.
> 
> CpAiJobFieldWork.lua, Version 7.0.1.4
> 
> ```
> function CpAIJobFieldWork:validateFieldSetup(isValid, errorMessage)
> 	
> 	if not isValid then 
> 		return isValid, errorMessage
> 	end
> 
> 	local vehicle = self.vehicleParameter:getVehicle()
> 
> 	-- everything else is valid, now find the field
> 	local tx, tz = self.fieldPositionParameter:getPosition()
> 	
> 	self.customField = nil
> 	local fieldNum = CpFieldUtil.getFieldIdAtWorldPosition(tx, tz)
> 	CpUtil.infoVehicle(vehicle,'Scanning field %d on %s', fieldNum, g_currentMission.missionInfo.mapTitle)
> 
> 	-- Start Changes	
> 
> 	local customField = g_customFieldManager:getCustomField(tx, tz)
> 	
> 	if not customField then
> 		self.hasValidPosition, self.fieldPolygon = g_fieldScanner:findContour(tx, tz)
> 		if not self.hasValidPosition then
> 			self.selectedFieldPlot:setVisible(false)
> 			return false, g_i18n:getText("CP_error_not_on_field")
> 		end
> 	else
> 		CpUtil.infoVehicle(vehicle, 'Custom field found: %s, disabling island bypass', customField:getName())
> 		self.fieldPolygon = customField:getVertices()
> 		self.customField = customField
> 		vehicle:getCourseGeneratorSettings().islandBypassMode:setValue(Island.BYPASS_MODE_NONE)
> 		self.hasValidPosition = true
> 	end;
> 	
> 	-- End Changes 
> 	
> 	
> 	--[[
> 	self.hasValidPosition, self.fieldPolygon = g_fieldScanner:findContour(tx, tz)
> 	if not self.hasValidPosition then
> 		local customField = g_customFieldManager:getCustomField(tx, tz)
> 		if not customField then
> 			self.selectedFieldPlot:setVisible(false)
> 			return false, g_i18n:getText("CP_error_not_on_field")
> 		else
> 			CpUtil.infoVehicle(vehicle, 'Custom field found: %s, disabling island bypass', customField:getName())
> 			self.fieldPolygon = customField:getVertices()
> 			self.customField = customField
> 			vehicle:getCourseGeneratorSettings().islandBypassMode:setValue(Island.BYPASS_MODE_NONE)
> 			self.hasValidPosition = true
> 		end
> 	end
> 	]]
> 	
> 	if self.fieldPolygon then
> 		self.selectedFieldPlot:setWaypoints(self.fieldPolygon)
> 		self.selectedFieldPlot:setVisible(true)
> 		self.selectedFieldPlot:setBrightColor(true)
> 	end
> 	return true, ''
> end
> ```

Wo muss ich den Textschnipsel den einfügen in welcher Zeile ??

**Comment by pvaiko** [comment]
So, is the consensus that custom fields should have preference? That is, if you select a spot which is a regular field and a custom field, the custom field should be selected?

**Comment by Tensuko** [comment]
Then we have the other Issue again, where you can't select a field withint a combined field like some ppl wanted to have....

**Comment by Nielwulf** [comment]
Can it be a toggle? Switch between prioritizing custom fields and map based fields?

**Comment by LordNikon83** [comment]
A switch or an entry in the options to select priority, would be the best solution.

**Comment by LordNikon83** [comment]
@FarmerMike87  ich hab dir die datei angehängt
[CpAIJobFieldWork.zip](https://github.com/Courseplay/Courseplay_FS22/files/8238267/CpAIJobFieldWork.zip)

**Comment by FarmerMike87** [comment]
> @FarmerMike87 ich hab dir die datei angehängt [CpAIJobFieldWork.zip](https://github.com/Courseplay/Courseplay_FS22/files/8238267/CpAIJobFieldWork.zip)

Besten Dank :)

**Comment by Tensuko** [comment]
Option to prefer custom fields. on or off
