### ISSUE TITLE
CpUtil.info() throws error

### ISSUE THREAD

**Issue by abelr1** [Courseplay/Courseplay_FS22#1114]
I am using the Rowtrac 500x with the Koeckerling_Allrounder plow attached.  I'm on the Haut-Beyleron map.  
CoursePlay  7.0.1.2 Farming Simulator 22 ver 1.3.0.0 b15515
I'm trying to go from field 31 approximately -239.9, 695.0 to field 26 approximately -608.2, 735.3.  I use Create Job, then goto, and the vehicle doesn't even move.  

I have had multiple issues...not just going from field to field.  When the issue arises, I am unable to tab to other vehicles, press escape to get the menu, or do much at all.  I press ` to get the console and I get the following error which repeats non-stop.  It doesn't freeze the game, but it freezes all of my actions.  If I am able to get into the vehicle, I can press H to dismiss the worker, which stops the error.   The error is:
D:/russe/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua:161: bad argument #3 to 'format' (no value)
2022-02-26 21:13 Error: Running LUA method 'update'.

[log (2).txt](https://github.com/Courseplay/Courseplay_FS22/files/8147955/log.2.txt)

**Comment by Tensuko** [comment]
Next time fill in our template!

**Comment by Andi-ger** [comment]
Hello,

I had the same problems with it, but I haven't had it since the new version.

**Comment by abelr1** [comment]
I updated and havent' had the issue anymore, but time hasn't permitted me to test thoroughly.  I will continue testing as I have time.  Thank you!

**Comment by schwiti6190** [comment]
@SerionNL221 Your error should be fixed with the newest version :)

**Comment by schwiti6190** [comment]
> I updated and havent' had the issue anymore, but time hasn't permitted me to test thoroughly. I will continue testing as I have time. Thank you!

When the error appears again, then please open the issue again or create a new one :)
