### ISSUE TITLE
[BUG_MP] Mouse pointer disappears when generating new course

### ISSUE THREAD

**Issue by DutchTed** [Courseplay/Courseplay_FS22#1116]
Very hard to reproduce without two people but we've managed it.

**Steps to reproduce**
Person A goes in to a menu to generate the course for a new field.
Person B tabs between vehicles.
Mouse pointer for person A disappears and person A has to quit out of the menus to get it to reappear

**Courseplay version**
7.0.1.0

**Player on the server**
2

Being played on local hosted server (person A is the host) 
Person B connecting via LAN (also sitting next to person A)
Only two players connected at the time so can't verify if this occurs with more players

**Map**
Various

**Vehicles/ implements involved**
Many

**Relevant script mods**
Autodrive is installed but we've only noticed this happening since installing courseplay.

**Comment by Tensuko** [comment]
Courseplay version
7.0.1.0
come on.....
Read Wiki! and also no logfile....
