### ISSUE TITLE
[BUG_SP] Steinsammler hält nicht an, wenn er voll ist

### ISSUE THREAD

**Issue by Cassy-Blair** [Courseplay/Courseplay_FS22#1117]
Seit dem Patch 1.3 hält der Standard  Giants KI Helfer an, wenn der Steinsammler voll ist und wartet darauf abgetankt zu werden. Leider funktioniert dieses aber noch nicht mit dem CP Helfer. Wäre toll, wenn dies mit dem nächsten Update möglich wäre.

**Comment by Tensuko** [comment]
Template nicht benutzt, gebt uns doch Zeit das wird das richtig einbinden könnne.... closed....
