### ISSUE TITLE
Starting field work, selecting field for new course

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/Courseplay_FS22#112]
Hello. Its my second post/issue report if we can cold it like that. 

Version 7.0.0.4

I find very hard to generate course on another field, this build  in game "pointer/indicator"  not working at least for m, or im just "old fashion" , maybe there is a possibility to create "choice of own fields " as it was in the previous version of the game and CP?   

Another thing i find weird/unnecessary .  When you select field with that pointer, CP worker folds  implement, makes circle from place where i wanted to start the field work and drives around to that pointer. . Its a bit time wasting.. 

Im playing using controller. Change of key settings , old keybind opening course generator and starting field work was on "x", now generator is on "a", thats an issue because when i try to use the pointer to set the location of next field i need to click "a" button on "co-ordinates" in top right bar, but "a"button opens generator.   So to set field with that location pointer i need to use mouse. This probably will be fixed in next version but i wanna mention it any way. 

I also noticed red indicator on implement ( seeder to be exact) when worker back up or struggles with something, or gets blocked  in older version i saw some yellow squares blinking in the distance on the map, didnt get situation when they show again so maybe you just fixed that.

Sorry if something is difficult to understand, language barrier etc 

https://user-images.githubusercontent.com/53440728/147404093-ead9549c-7ac7-4101-866b-b80815af5ffc.mp4

**Comment by Tensuko** [comment]
You can just place the target on any Field you want and generate the next course.
Also if the Helper is done with his last work.
Tested with 7.0.0.5
