### ISSUE TITLE
[BUG_SP] Vehicle drives on the wrong side of the course - only affects headland

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#1124]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Load a course with a headland, drive the course.

**Actual behavior**
In a multi vehicle convoy, a vehicle will drive on the opposite side of the course than intended (i.e. right instead of left).

**Expected behavior**
Vehicle should drive on correct side.

**Screenshots**
https://youtu.be/qJkxPEMiHl8  - example video, for simplicity I have used a single default vehicle with a default implement, but in a three vehicle convoy, vehicle nominally on the left will follow the same course as the vehicle nominally on the right

**Courseplay version**
7.0.1.2 - latest commit

**Map**
Default Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Default vehicles, affects all vehicles and implements.

**Relevant script mods**
N/A

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8152878/log.txt)

**Comment by Tensuko** [comment]
@pvaiko that seems to be the case when the startpoint is not on headland.

**Comment by pvaiko** [comment]
> hat seems to be the case when the startpoint is not on headland.

Then this was already in FS19...

**Comment by Tensuko** [comment]
I can maybe try this out...

**Comment by pull2play** [comment]
> @pvaiko that seems to be the case when the startpoint is not on headland.

I'm afraid that's incorrect. It doesn't matter where the start point is.

https://youtu.be/cnwxy4xJ0Aw

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8156114/log.txt)

**Comment by Tensuko** [comment]
Fixed in 7.0.1.3
