### ISSUE TITLE
[BUG_SP] Baler collides with own bales

### ISSUE THREAD

**Issue by der-cain** [Courseplay/Courseplay_FS22#1130]
**Steps to reproduce**
1. Create a course with automatic baler that also wraps the bales without headland
2. At the end of the lane the baler will move backward to move to the next lane
3. If at this point he just laid down a bale, it will crash with it and stop its course

Another similar scenario happens with headland
1. Create a course with headland and mow grass / wheat / etc
2. The baler will create the bales but it might collide with bales lying in the way in headland or when moving from the headland to the lanes it will go over an existing lane with bales already on it and collide with them

**Actual behavior**
Baler running into bales

**Expected behavior**
Ideally, the automatic baler will scan for bales and avoid/go around them during its work. Another solution might be to time the laying down of bales better, but I see that far more difficult.

**Screenshots**

**Courseplay version**
Version used: 

**Log**
I don't have a log yet but I can add it if required later on

**Map**
Elmcreek

**Vehicles/ implements involved**
Pöttinger Impress 185VC Pro

**Relevant script mods**
Autodrive is installed and active, but no relevant for this issue

**Comment by GeorgeEarslight** [comment]
You could start the course from up-down instead of headlands and also use a bale pusher front attachment.

**Comment by Tensuko** [comment]
@GeorgeEarslight hey buddy.
Exactly like that, what else should we do about this...


It is definitly not a bug.
You could also try to use pathfinder in turns (have to turn it on). It may avoid bales.

**Comment by der-cain** [comment]
Thanks for the quick response, I will try your suggestions!

**Comment by GeorgeEarslight** [comment]
> @GeorgeEarslight hey buddy. 

Hey Tensuko. You guys are doing a great job on the FS22 release.
I really like the restructured code from @pvaiko and @schwiti6190 and the clean Issue list by you.
