### ISSUE TITLE
[Question]Seitlicher Versatz bei (mod) Pflug stimmt nicht

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1137]
Nutze den großen 10,5m Pflug SPSL9 aus dem Big Bud Pack. Leider stimmt der seitliche Versatz nicht ganz. Kurs wurde mit 10,5m Breite angelegt (autobreite). Früher konnte man den seitlichen Versatz selber einstellen. Mit CP 7.0.1.3 soll der ja automatisch erkannt werden und die Einstellung ist gesperrt. Prinzipiell ja auch schöner. Es bleiben nur unbearbeitete Bereiche über.
![fsScreen_2022_03_03_17_50_08](https://user-images.githubusercontent.com/96873819/156616310-e05199b9-bc15-4f1c-b23b-7c0dd373e834.png)

Ist das nun ein Fehler in CP? Oder im Mod? Oder vor dem Bildschirm?

**Comment by Tensuko** [comment]
Wenn du genauer sagen würdest, welcher Pflug das ist, könnte ich mir das anschauen...

**Comment by throsten** [comment]
Es ist der Gregoire Besson SPSL9, der gleiche wie damals im LS19. Im LS22 ist er Teil des Big Bud Packs (https://fs22planet.com/de/the-big-bud-pack.html)

**Comment by Tensuko** [comment]
Schön von einer Klauseite wo auch unsere Mod runtergeladen werden kann, damit andere sich dran bereichern.
Nein danke, kein Support dafür.
Schau dir das an und versuch es selber ein zu binden: https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.

**Comment by regs1980** [comment]
Den Gregoire Besson SPSL9 gibt es jetzt auch im Modhub direkt von Giants.
 
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=244449&title=fs2022

Arbeitsbreite wird nicht erkannt.

**Comment by MoslessNeo** [comment]
Sorry to reopen this old and closed topic, but I would like to know if the team has plans to fix the bug that occurs with the Gregoire Besson SPSL9 and Trailed Lifter when using the Big Bud 747.
Course Play is very important for FS22 and I don't have the ability to help with it.
