### ISSUE TITLE
[Feature] Turn off combine header/equipment when unloading sitting still.

### ISSUE THREAD

**Issue by talianagisan** [Courseplay/Courseplay_FS22#1139]
**What is the problem this feature/enhancement solves?**
When my combine is unloading it keeps running the header meaning im burning 400L/h as i sit there unloading my tank which takes like a minute or two. This adds up pretty fast and when you have a field that takes 6-9 hours it uh... burns alot. Same with some other equipment.

**Describe the solution you'd like**
Header is turned off when unloading when sitting still. Turning off implements when being refilled or unloading (Within reason) would be a nice overall fix. 

**Describe alternatives you've considered**
Not sure other ways to go about this other than toggling/etc.

**Comment by Tensuko** [comment]
#140 duplicate
