### ISSUE TITLE
[BUG_SP] Convoy getting stuck on leader turn

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#1140]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a convoy.

**Actual behavior**
Leader gets stuck on turn, does not complete a turn, does not proceed, entire convoy comes to a halt. Possible mod issue?

**Expected behavior**
Convoy should move along.

**Screenshots**
https://youtu.be/18DLUmQ1wYY

**Courseplay version**
Version used:  7.0.1.3 - latest release

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8181787/log.txt)

Only had logging enabled on leader

**Map**
Elmcreek

**Vehicles/ implements involved**
Default tractors, non-modhub implement

**Relevant script mods**
Autodrive, VCA, many others

**Comment by Tensuko** [comment]
That doesn't make any sence...
Can you turn on the debug of the other tractors too ?

**Comment by pull2play** [comment]
Here's the entire sequence, all vehicles logged, hope this helps. 

https://youtu.be/JIv6ZvD8Crk

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8185333/log.txt)
.

**Comment by Tensuko** [comment]
That looks like selfblocking somehow... Thank you that should help.

**Comment by pvaiko** [comment]
No, not self. I know what's going on, an easy fix would be just to use smaller convoy distance I think.

**Comment by pull2play** [comment]
> No, not self. I know what's going on, an easy fix would be just to use smaller convoy distance I think.

I did. I initially caught this behaviour on a convoy distance of 50m. I then tried 200m, and then 150m.

**Comment by pull2play** [comment]
I am now seeing combines getting stuck in the middle of a headland for no reason. The leader just stops and then doesn't move. It appears only to affect new courses, generated with this CP version though. I have not run into this issue on any course generated prior to this version.

**Comment by Tensuko** [comment]
It that would be the case, single combine should stop at the same position.
