### ISSUE TITLE
Kurse einfahren.

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/Courseplay_FS22#1141]
Hallo Dev. Team vom CP
Tolle Sache, danke dass ihr den CP weiter endwickelt.
Mein Wunsch ist das der Kursgenerator wieder eigene Kurse zulässt, nicht nur Automatisch generieret. Also sowie im Vorgänger das ich einen Kurs selber einfahren kann welchen ich dann auch bearbeiten kann.  (Kurseditor) Und natürlich denn Strecken Generator um strecken abzufahren so dass wir den zB. Den Drescher auch wieder von CP Ab tanken lassen können. Nichts gegen AD aber bisher hatten wir CP und brauchten eigentlich nichts Weiteres. War Perfekt so!
Wenn ihre das schon geplant habt ist das natürlich top, wenn nicht wäre das ein Sahnehäubchen auf dem neuen CP. 
Danke euch für eure Arbeit.
Kurth

**Comment by Tensuko** [comment]
Nein wird nicht passieren und das wurde auch schon oft genug gesagt.

**Comment by LamaiK** [comment]
Wie immer sehr nett geantwortet Tensuko.
War sehr höfflich gefragt, lieber Tensuko.

Ich sehe das so das ihr jetzt lediglich einen besseren Feldarbeiter erschafft, mehr nicht. Könnt ihr auch gleich dem AD team überlassen.

Freudliche Grüsse für dich Tensuko.

Kurth
