### ISSUE TITLE
[Question] Is there a setting to let the pathfinder not drive out to the field border on turns?

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#1142]
I normally don't that the combine or tractors often drive out to the field border on turns. But now I got the issue that the Grimme Ventor gets stuck in trees sometimes (it actually stops before it collides) as it has quite a big overhang on the front. Is there an option to limit the field size for turns? Or is the pathfinder coupled to the field margin settings, then I could run a second course with a higher margin after the first headland is harvested. If there is no option, I can of course well live with it, but maybe someone just knows an easy trick.

**Comment by Tensuko** [comment]
The pathfinder should use the headland to drive from turn start to turn end.
Since I don't have a screenshot of your course or how the turn look like (debug) I can't answer you this question.

**Comment by DemsMani** [comment]
Thanks a lot for the answer. This already helps. So if it uses the headlands, a positive field margin (I have a negative one at the moment in order to catch the corners better) will actually do the trick.
