### ISSUE TITLE
 [BUG_MP] Kein Motorsound

### ISSUE THREAD

**Issue by MacRama1** [Courseplay/Courseplay_FS22#1143]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Feld bestellen 

**Actual behavior**

Folgendes Scenario:
Autordive bringt ein Fahrzeug an den Feldrand und übergibt es an CP.
Wenn CP  während der Feldarbeit der Dünger, das Saatgut oder das Herbizid ausgeht und CP das Fahrzeug an Autodrive zum nachfüllen  übergibt, verlieren die Fahrzeuge den Motorsound solange bis AD das Fahrzeug wieder zurück bringt, in dem Moment wo CP das Fahrzeug wieder übernimmt, ertönt auch wieder der Motorsound. Sämtliche Umweltgeräusche sind davon nicht betroffen.

**Expected behavior**
Motorsound sollte erhalten bleiben.

**Screenshots**

**Courseplay version**
Version used: 7.0.1.3 und auch  in 7.0.1.2

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
 4

**Dedicated server or local hosted server**
Dedicated  yes

**Map**
 La Plaine Francaise

 Claas Arion 660 & Hardi Mega 1200l / JD 8RX 410 & Väderstad Tempo L16 / Fendt 724 Vario & Lemken Solitair 12

Mod yes/no ? no

**Relevant script mods**
 Autodrive

**Comment by Tensuko** [comment]
Warum sind Client log und Server log nicht mit angehangen ?!

**Comment by MacRama1** [comment]
> Warum sind Client log und Server log nicht mit angehangen ?!
sorry, musste auf unseren serverinhaber warten.
habe versucht den fehler nochmal zu reproduzieren, gegen 19:27 war der sound wieder verschwunden.
heute nachmittag habe ich leider nicht auf die zeit geachtet, aber das war zu dem zeitpunkt der arion mit der hardi spritze.
[game.log](https://github.com/Courseplay/Courseplay_FS22/files/8188117/game.log)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8188118/log.txt)

**Comment by Tensuko** [comment]
Mal ohne (Version: 0.52 Beta) AAA_HiredHelperTool probiert ?

**Comment by MacRama1** [comment]
> 

ja, der helper ist erst heute dazu gekommen, das mit dem motorsound war auch schon davor

**Comment by schwiti6190** [comment]
@MacRama1 Passiert das nur bei der Übergabe an AD, wenn Ja hört sich das nach einem AD problem an. Vlt. mal in derem Discord vorbei schauen und/oder ein Issue da erstellen :)

**Comment by Selyria** [comment]
kann ich bestätigen ich habe es aber erst seit dem Patch 1.3 davor war alles okay bei mir ist es aber manchmal wen ich einfach selber rumfahren zack Sound vom Motor weg und zack wieder da

**Comment by MacRama1** [comment]
> @MacRama1 Passiert das nur bei der Übergabe an AD, wenn Ja hört sich das nach einem AD problem an. Vlt. mal in derem Discord vorbei schauen und/oder ein Issue da erstellen :)

@schwiti6190, nicht nur, manchmal auch bloß wenn ich das fahrzeug verlasse und wieder einsteige.

**Comment by Tensuko** [comment]
Dann ist es aber ein Game Bug und weder CP noch AD sind Schuld!

**Comment by MacRama1** [comment]
> Dann ist es aber ein Game Bug und weder CP noch AD sind Schuld!

nun, es ist auch nicht wirklich störend, mir ist halt aufgefallen das es nur bei der CP feldarbeit passiert.
würde das hier dann schließen.

PS. ich weiß nicht genau ob ich diese frage/anregung hier anhängen kann oder ob ich ein neues issue öffnen soll.
wäre es möglich das CP die arbeitsgeräte erst am ersten wegpunkt aufklappt anstatt direkt am feldrand?
es befinden sich häufig bäume, zäune, mauern etc. am feldrand und CP möchte dann mit aufgeklappten geräten  mit dem pathfinder dazwischen durchfahren wo er dann meistens hängen bleibt.
bitte sage mir ob ich dahingehend ein neues issue öffnen soll, und ob ich dieses eigentliche issue schließen soll.
gruß mac

**Comment by Tensuko** [comment]
> wäre es möglich das CP die arbeitsgeräte erst am ersten wegpunkt aufklappt anstatt direkt am feldrand?

Wir arbeiten dran.

**Comment by MacRama1** [comment]
danke für die schnelle antwort :)

**Comment by Tensuko** [comment]
Wird wohl ein Gamebug sein.

**Comment by Selyria** [comment]
Denke ich auch wenn ich Curseplay runter haue habe ich es auch noch. Und bei mir kam es mit Patch 1.3
