### ISSUE TITLE
[BUG_SP] does not recognize joined fields

### ISSUE THREAD

**Issue by dgonyou** [Courseplay/Courseplay_FS22#1144]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Join fields using plow, course play will not recognize it as joined 

**Actual behavior**
Courseplay will not recognize joined fields. Last time this worked correctly was Version 7.0.0.26

**Expected behavior**
Courseplay generally recognizes joined fields, this is not happening, so when you create CP work, it will only recognize original field bouderies.

**Screenshots**

**Courseplay version**
Version used: 7.0.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Frankenmouth

**Vehicles/ implements involved**
any

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
no log, no screenshots and high doubt aboud this Issue...

**Comment by dgonyou** [comment]
Reinstalled the latest version labeled 7.0.1.3 which loads as 7.0.1.2, but it now works correctly.

**Comment by Tensuko** [comment]
When I download our 7.0.1.3 from here:
https://github.com/Courseplay/Courseplay_FS22/releases
I get 7.0.1.3
I don't know where you try to get CP from, but if from any other side then github, you should not wonder about faulty versions!
