### ISSUE TITLE
[BUG_MP] an "active helper" entry is genereated in helper view in settings when using CP with AD

### ISSUE THREAD

**Issue by marcokaiser** [Courseplay/Courseplay_FS22#1146]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a CP job for a field (in this case collecting straw), and set AD (v2.0.0.4) to pick it up and deliver it to a silo. 

**Actual behavior**
For each time when AD hands back the job to CP, a new entry in the "active helpers" list in the helper map view in game settings is created, all pointing to the same vehicle. If you have multiple jobs set up with CP and AD, they all show this behavior.

**Expected behavior**
I would expect that only one entry for the CP job per vehicle remains in that active helpers list.

**Screenshots**
![image](https://user-images.githubusercontent.com/440889/156883177-44712ff1-c0af-45e3-84f8-d02a1b7c6a45.png)

**Courseplay version**
Version used: 7.0.1.3

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

2022-03-05 12:58 :15 [info lp46566] Xerion 3800/308: Start/stop cp helper
2022-03-05 12:58 :15 [info lp46566] Xerion 3800/308: Cp helper started.
2022-03-05 12:58 dataS/character/humans/npc/pedestrians/generic/npcCommon04_m.i3d (7.10 ms)
2022-03-05 12:58 :58 [dbg17 lp49083] setting waypoint visibility false, mode 1
2022-03-05 12:58 :58 [dbg17 lp49083] setting waypoint visibility true, mode 1
2022-03-05 13:01 Error: Running LUA method 'packetReceived'.
dataS/scripts/ai/events/AIJobStopEvent.lua(37) : attempt to index field 'aiMessage' (a nil value)
2022-03-05 13:01 dataS/character/humans/npc/pedestrians/generic/npcCommon02_f.i3d (9.68 ms)
2022-03-05 13:05 dataS/character/humans/npc/pedestrians/generic/npcCommon09_m.i3d (8.18 ms)
2022-03-05 13:12 Error: Running LUA method 'packetReceived'.
dataS/scripts/ai/events/AIJobStopEvent.lua(37) : attempt to index field 'aiMessage' (a nil value)
2022-03-05 13:17 dataS/character/humans/npc/pedestrians/generic/npcCommon04_m.i3d (6.45 ms)
2022-03-05 13:22 Error: Running LUA method 'packetReceived'.
dataS/scripts/ai/events/AIJobStopEvent.lua(37) : attempt to index field 'aiMessage' (a nil value)
2022-03-05 13:28 dataS/character/humans/npc/pedestrians/generic/npcCommon02_f.i3d (8.80 ms)

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
1 and 2

**Dedicated server or local hosted server**
Dedicated server yes/no ? YES

**Map**
NF Marsch 1.3.1

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? happens with various vehicles

**Relevant script mods**
AD 2.0.0.4

**Comment by Tensuko** [comment]
The complete logfiles would be good.

**Comment by JonasFovea** [comment]
I have the same problem.

Running on a server, CP v7.0.1.2 and AD v2.0.0.4

**Comment by Plopsi** [comment]
Minor problem, a little bit annoying, doesn't interfere with funcationality (as far as i can tell) - happens quite often.

I think it's the handover AD<->CP where the old entry isn't deleted, not sure if AD or CP entry.

**Comment by JonasFovea** [comment]
@Plopsi well it's slowly filling up the RAM, if you don't notice it.

When I first noticed it, my game was frozen because there were too many entries.

**Comment by Plopsi** [comment]
oh..  no didn't noticed it.. i think the most where around 10-20 entries, and the server restarts every ~24h.

good to know. will keep an eye on it.

**Comment by marcokaiser** [comment]
I tried to reproduce this in SP or in a MP session with just AD and CP - and it didn't happen. So I guess other mods might play into this as well. If I find the time to nail this down to specific combination of mods, I'll uplaod a log file. Right now I couldn't see anything in the logs even remotely hinting at the problem... 

If anyone else who experiences this problem can and wants to provide a log file, that'd be great!

**Comment by marcokaiser** [comment]
Oh, and yes - also happening on 7.1.0.2 for me, so this was not introduced in 7.1.0.3 I guess

**Comment by Tensuko** [comment]
logfile is always good but as you see no one attached one....

**Comment by Plopsi** [comment]
For now I can say, that with 7.0.1.4 I only have one "stuck" entry per vehicle - up to now.

But that seems to make the cruise control stuck on the vehicle with the entry - seems it's the entry of AD (as it activates the CC) - you can't deactivate CC afterwards and it's only deactivateable by resetting the vehicle or restart the server.
But need to investigate further to really find a reproduceable configuration.

**Comment by KCHARRO** [comment]
I hadn't noticed this, but I'll look, although I don't think this has happened to me, maybe a specific MOD?

**Comment by Plopsi** [comment]
Heres a good way to provocate entries:

Put an AD target point on a field, us a balewaggon which collects them from ground and fill it with bales.

Tell AD to drive to the point (only drive to, no other mode) on the field and hand over to CP (mode loading bales, so no course loaded) - endless entries.

AD will drive to the point, hand over to CP, CP sees the loader is full and hands back to AD. AD sees it's at it's destination and hands back to CP and so on and on and on - endless free entries ;)

**Comment by schwiti6190** [comment]
If this problem still exist with the newest cp and ad versions, then please reopen this :)
