### ISSUE TITLE
Falsche Einstellungen bei der Zuckerrohrernte ?

### ISSUE THREAD

**Issue by Noggele** [Courseplay/Courseplay_FS22#1147]
Hallo zusammen, 

ich das Problem, bei der Zuckerrohrernte, dass der Ernter und der Abfahrer nicht in einer Linie fahren, sondern der Abfahrer ein Stück hinterher. So kommt das Rohr nicht über den Anhänger. 
Mache ich bei den Einstellungen etwas falsch? Evtl. bei CP oder doch bei AD ?

Liebe Grüße

**Comment by Tensuko** [comment]
Da es sich um den Abfahrer handelt, ist die richtige Addresse AD.
