### ISSUE TITLE
[Enhancement] Proximity sensors bremst bei seitlichen Objekten (z.B. Bäume, Zäune) Fahrzeug ab

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/Courseplay_FS22#1148]
Sorry, ist natürlich SP nicht MP

**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Nahe Objekte neben dem Feld.

**Actual behavior**
Objekte neben dem Feld bremsen Fahrzeuge am 2km/h ab, obwohl genügend Platz ist.

Könnte man vielleicht eine Option einbauen, damit man die seitliche Erkennung abschalten oder die Reichweite reduzieren kann?

**Expected behavior**
Fahrzeug fährt mit normaler Geschwindigkeit weiter

**Screenshots**
[https://youtu.be/xz6ap5Q5IaE](https://youtu.be/xz6ap5Q5IaE)
[https://youtu.be/2vmrycmus6Y](https://youtu.be/2vmrycmus6Y)
[https://youtu.be/KnGy2d2HqCU](https://youtu.be/KnGy2d2HqCU)

**Courseplay version**
7.0.1.3

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8191665/log.txt)

**Player on the server**
Number of players on the server, as the bug appeared.

**Dedicated server or local hosted server**
Dedicated server yes/no ?
no

**Map**
Map played on.
NFM 1.3.1 OG

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD aber ausgeschaltet

**Comment by Tensuko** [comment]
> Könnte man vielleicht eine Option einbauen, damit man die seitliche Erkennung abschalten oder die Reichweite reduzieren kann?

Nein, das müssen wir irgendwie anders lösen.
Objekte dürfen halt nicht erkannt werden.
Für jeden kram eine Option macht CP nur noch weiter unnötig komplex für die User.

**Comment by pull2play** [comment]
This is a more pressing issue I think. I initially thought my combine getting stuck on headlands was just another manifestation of a different bug, but it wasn't - it's this one. For whatever reason, proximity sensor thinks a hill is an obstruction. The default AI worker has no such issues, as evidenced in video below.

https://youtu.be/yf5taBcOn0Q

**Comment by marcelmmx** [comment]
Well, in my case the combine slows down (also to 2km/h) on a steep hill in the middle of the field with no objects nearby. This happens when the combine runs parallel to the slope (not up or down the hill). As soon as the slope levels out the combine speed increases to whatever is currently set.

**Comment by pull2play** [comment]
> Well, in my case the combine slows down (also to 2km/h) on a steep hill in the middle of the field with no objects nearby. This happens when the combine runs parallel to the slope (not up or down the hill). As soon as the slope levels out the combine speed increases to whatever is currently set.

Yeah, it looks like it depends on the slope. In my case the combine just stops and doesn't move any further. I have observed this behaviour on two different fields now. Considering the default helper works fine, this should probably be reclassified as a CP bug, rather than an enhancement.

**Comment by Tensuko** [comment]
Depends on the distance to the objects.
If to close, combine stops.
Is made for not crash into Vehicles.

**Comment by Tensuko** [comment]
Never said it should do it...

**Comment by Tensuko** [comment]
Oh and about your Issue, who says its the procimity sensor ?

**Comment by pull2play** [comment]
> Oh and about your Issue, who says its the procimity sensor ?

Isn't that what the lines shooting off to the left represent in debug mode? I assumed that's the proximity sensor.

**Comment by Tensuko** [comment]
But I don't see lines to the left in your video and logfile says nothing about the sensor.

**Comment by pull2play** [comment]
> But I don't see lines to the left in your video and logfile says nothing about the sensor.

They're right there, visible at the end. I didn't post a log file with this video, and I don't think I had the proximity sensor debug active in the one in the other thread, as I didn't suspect the sensor at the time :)

![image](https://user-images.githubusercontent.com/24781572/157114302-0bce951c-5c76-4261-bbb2-6516703b8de6.png)

**Comment by Tensuko** [comment]
Ah there we go.
Well then it is the sensor.

**Comment by pull2play** [comment]
> Ah there we go. Well then it is the sensor.

Yep. I just did a quick test with a single combine, as per your suggestion in the other thread. Video and log:

https://youtu.be/ZbRPF-pAU1Y
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8200734/log.txt)

**Comment by pvaiko** [comment]
I see we seem to use the wrong mask (`CollisionFlag.STATIC_WORLD + CollisionFlag.TREE + CollisionFlag.DYNAMIC_OBJECT + CollisionFlag.VEHICLE`) for the proximity sensor, where `STATIC_WORLD` includes the terrain, so should probably be just `STATIC_OBJECTS`? Here's what we can choose from:

```lua
CollisionFlag.DEFAULT = registerFlag(0, "DEFAULT", "The default bit", true)
CollisionFlag.STATIC_WORLD = registerFlag(1, "STATIC_WORLD", "Collision with terrain, terrainHeight and static objects", true)
CollisionFlag.STATIC_OBJECTS = registerFlag(3, "STATIC_OBJECTS", "Collision with static objects", true)
CollisionFlag.STATIC_OBJECT = registerFlag(4, "STATIC_OBJECT", "A static object", true)
CollisionFlag.AI_BLOCKING = registerFlag(5, "AI_BLOCKING", "Blocks the AI", true)
CollisionFlag.TERRAIN = registerFlag(8, "TERRAIN", "Collision with terrain", true)
CollisionFlag.TERRAIN_DELTA = registerFlag(9, "TERRAIN_DELTA", "Collision with terrain delta", true)
CollisionFlag.CAMERA_BLOCKING = registerFlag(10, "CAMERA_BLOCKING", "Blocks outdoor vehicle camera", true)
CollisionFlag.TREE = registerFlag(11, "TREE", "A tree", true)
CollisionFlag.DYNAMIC_OBJECT = registerFlag(12, "DYNAMIC_OBJECT", "A dynamic object", true)
CollisionFlag.VEHICLE = registerFlag(13, "VEHICLE", "A vehicle", true)
CollisionFlag.PLAYER = registerFlag(14, "PLAYER", "A player", true)
CollisionFlag.BLOCKED_BY_PLAYER = registerFlag(15, "BLOCKED_BY_PLAYER", "Object that's blocked by a player", true)
CollisionFlag.ANIMAL = registerFlag(16, "ANIMAL", "An animal", true)
CollisionFlag.ANIMAL_POSITIONING = registerFlag(17, "ANIMAL_POSITIONING", "An object where animals can walk on", true)
CollisionFlag.AI_DRIVABLE = registerFlag(18, "AI_DRIVABLE", "AI can drive over this node", true)
CollisionFlag.GROUND_TIP_BLOCKING = registerFlag(19, "GROUND_TIP_BLOCKING", "Bit to block the ground tipping at this position", true)
CollisionFlag.TRIGGER_PLAYER = registerFlag(20, "TRIGGER_PLAYER", "A trigger for players", true)
CollisionFlag.TRIGGER_VEHICLE = registerFlag(21, "TRIGGER_VEHICLE", "A trigger for vehicles!", true)
CollisionFlag.TRIGGER_DYNAMIC_OBJECT = registerFlag(24, "TRIGGER_DYNAMIC_OBJECT", "A dynamic object", true)
CollisionFlag.TRIGGER_TRAFFIC_VEHICLE_BLOCKING = registerFlag(25, "TRIGGER_TRAFFIC_VEHICLE_BLOCKING", "A trigger that blocks the traffic vehicles", true)
CollisionFlag.TRIGGER_FORK = registerFlag(27, "TRIGGER_FORK", "A trigger for fork object mounting", true)
CollisionFlag.TRIGGER_ANIMAL = registerFlag(28, "TRIGGER_ANIMAL", "A trigger for animals", true)
CollisionFlag.FILLABLE = registerFlag(30, "FILLABLE", "A fillable node. Used in trailers and unload triggers", true)
CollisionFlag.WATER = registerFlag(31, "WATER", "Collision of the water plane", true)
```

**Comment by pvaiko** [comment]
Would be great if one of you could test this with the above commit on the issue-1148 branch.

**Comment by pull2play** [comment]
> Would be great if one of you could test this with the above commit on the issue-1148 branch.

It's better in the sense that the worker is no longer stuck, but there are still terrain collision issues on this particular course/field. I can test on a different field tomorrow.

https://youtu.be/7kbaQ3XfqYw
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8201394/log.txt)

**Comment by pvaiko** [comment]
@pull2play thanks, should now be fixed, at least it should not be hitting the terrain anymore.

**Comment by pvaiko** [comment]
> several places

Show me one such place, I tested it on that slope, looked all fine.

**Comment by pvaiko** [comment]
Also, which combine and header?

**Comment by pull2play** [comment]
> Also, which combine and header?

Both combines are from the GIANTS modhub:

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=228390&title=fs2022

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=228728&title=fs2022

Headers are the default JD 45X and a mod header (https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=229490&title=fs2022). The video and log below are of the X9 modhub mod and the default 45X header.

The field is a combined field - perhaps that could be causing the issue? But then why is the normal AI not getting obstructed there, but CP is.

https://youtu.be/igbQ0t_WvrA

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8205850/log.txt)

**Comment by pvaiko** [comment]
It says obstacle is 0.2 meters at 70 degrees, so there should be a very short debug line, probably reddish, somewhere on the left side but I can't see it.

**Comment by pvaiko** [comment]
On my map I have trees at that spot. Could it be a tree trunk not cleaned up completely?

**Comment by pull2play** [comment]
> On my map I have trees at that spot. Could it be a tree trunk not cleaned up completely?

I don't see any red lines to the left, just the ones in centre.

It's possible that it's a tree ghost, wouldn't be the first time tree removal didn't work properly. If it is though, it doesn't show up on wireframe. I'll go ahead and delete all trees in the area in the editor and see if that fixes the issue.

**Comment by pull2play** [comment]
Nope, removing trees didn't change anything, still getting stuck in that spot.

As for the red lines, these are the only red lines I see.

![20220308133205_1](https://user-images.githubusercontent.com/24781572/157238953-52e2ed01-02d2-4aa8-a195-de8b66ec6763.jpg)

**Comment by pvaiko** [comment]
Ok, then get me a savegame, we won't find is out what it is otherwise.

**Comment by pull2play** [comment]
> Ok, then get me a savegame, we won't find is out what it is otherwise.

Just the folder, or do you need something more? I'm fairly certain this has to be related to this being a combined field, because like you I ran the course on a default map with separate fields and it seemed to run fine.

[savegame1.zip](https://github.com/Courseplay/Courseplay_FS22/files/8206301/savegame1.zip)

**Comment by pvaiko** [comment]
Thanks, that's fine, and it seems to be terrain, on the right side but can't tell you why, it really should not do this.

**Comment by pull2play** [comment]
I tried the latest fix, but my combine is still getting stuck in that same spot, so I guess my problem is specific to my field and cannot be reproduced?

**Comment by pvaiko** [comment]
I can reproduce it with your savegame but not otherwise (latest fix is just a merge, you already tried that while it was on the branch). I suspect it is a Giants bug (but have no evidence) when removing trees or creating new fields. 

I don't plan to spend more time on it unless others report similar problems.

**Comment by pull2play** [comment]
> I can reproduce it with your savegame but not otherwise (latest fix is just a merge, you already tried that while it was on the branch). I suspect it is a Giants bug (but have no evidence) when removing trees or creating new fields.
> 
> I don't plan to spend more time on it unless others report similar problems.

Ok, thanks for trying. I guess I'll downgrade to a previous CP version that didn't have this issue and stay there for the time being.

**Comment by pvaiko** [comment]
Maybe you can try plowing or landscaping those areas, there is something which says it is terrain, very close to the right side of the header.

**Comment by pull2play** [comment]
> Maybe you can try plowing or landscaping those areas, there is something which says it is terrain, very close to the right side of the header.

Already tried that :) Like you said, probably a GIANTS bug. Maybe an invisible bump - I've noticed several of those on this map, can't fix that without messing around in GE and while I can delete a tree, I'm certainly no mapper. Oh well, I got nearly 500 hours out of FS22, time for a break anyway.

**Comment by pull2play** [comment]
Just out of curiosity - and sorry to keep banging on a dead horse - if the invisible blocking object is to the right, why doesn't it affect the centre lane? Shouldn't the centre combine also stop if the object is to the right of the leftmost header? That would put this obstacle directly in its path.

**Comment by pull2play** [comment]
> Maybe you can try plowing or landscaping those areas, there is something which says it is terrain, very close to the right side of the header.

I found the problem... This is what's tripping the proximity detector. There's - well, I don't know what this is, but these are under the fields in problem spots.

![20220309185124_1](https://user-images.githubusercontent.com/24781572/157501589-8282632b-f103-4277-8961-9e356eca8bee.jpg)

**Comment by Selyria** [comment]
Habe das Selbe Problem jetzt mal gefunden scheinbar gibt's probs mit zäunen und Bäumen ich habe das Feld jetzt einfach ein wenig kleiner gemacht so das er mehr platz zum Zaun hat damit ist das erstmal für mich behoben

https://youtu.be/nyP6k5YZOUE
