### ISSUE TITLE
[LUA Error] Error: Running LUA method 'update' - FieldWorkerProximityController.lua:116: attempt to index local 'otherStrategy' (a nil value)

### ISSUE THREAD

**Issue by mschaper76** [Courseplay/Courseplay_FS22#1149]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce vehicels stutter

**Actual behavior**
when i got 1 coursplay activatie running and i wanna start a second one it works well until i press start the vehicels stutter 

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: Courseplay v7.0.1.3

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8192441/log.txt)

**Map**
elmcreek, animal creek , NF March 4x v1.3.1 FS22 , Elm Creek Edit By Stevie v1.0.0.7 FS22

**Vehicles/ implements involved**
Fendt 1050 OY / Claas dominator108SL

**Relevant script mods**
none

**Comment by Tensuko** [comment]
2022-03-05 19:27 Error: Running LUA method 'update'.
D:/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/FieldWorkerProximityController.lua:116: attempt to index local 'otherStrategy' (a nil value)

**Comment by Plopsi** [comment]
Funny we expierenced this too today. And it seems to happen when two CP workers doing the same mission, like plowing or cultivating, on different fields. If they do different missions (seeding and plowing for example) it seems not to happen.
