### ISSUE TITLE
Gespeicherte Kurse

### ISSUE THREAD

**Issue by Namajo** [Courseplay/Courseplay_FS22#115]
Hi Leute,

erstmal vielen Dank, dass ihr dieses großartige Addon auch für den LS22 umsetzt. Im LS19 ist es das beste und hilfreichste Addon, gerade wenn man eine Vielzahl von Felder hat. Und ich bin sicher, dass ihr das auch für den LS22 so hinbekommt.

Nach den anderen gemeldeten Issues ist mir aufgefallen, dass die Verwaltung der gespeicherten Kurse nicht funktioniert. Ich kann zwar Kurse speichern, aber diese weder wieder laden, noch kann ich diese löschen.

MfG, Kevin

PS: Als Overlay-Menü ist die Bedienung viel komfortabler gewesen.

**Comment by Tensuko** [comment]
Doch das funktioniert.
Es ist nur anders als man denkt und ja da müssen wir unbedingt etwas tun und das haben wir auch schon besprochen.
Klick auf Kurs laden und DANN auf den Kurs den du laden willst.
Ja du musst den Ordner erst ausgewählt haben (ja das ist nicht ganz so schön, aber für die erste Version war das so okay).
Beim löschen oder verschieben das gleiche. Aktion anklicken, dann ausführen (Kurs anklicken zum löschen/umbenennen, Kurs dann ordner zum verschieben).
Ich mach heute eine Art FAQ mit Anleitung oder so...

**Comment by Namajo** [comment]
Danke für die Information. Wirklich etwas ungewohnt. Aber es funktioniert, wie du es beschrieben hast. Klar, dass ihr im Moment andere Dinge zu tun habt als es möglichst einfach zu machen.
Ihr macht das schon. :)
