### ISSUE TITLE
[BUG_SP] Total Crash game with 6 active helper 

### ISSUE THREAD

**Issue by michal3110** [Courseplay/Courseplay_FS22#1152]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

when working with five helpers, the game runs fine, after activating the sixth helper, the game is completely jammed, the helpers of the id are still straight, you can not ovate the game or the menu window, only the solution to turn it off is Ctrl+alt+del. I've tried it several times and the problem persists. 

**Screenshots**
video or screenshot cannot be taken because it is necessary to turn off the game in an emergency overhead.

**Courseplay version**
Version used: 7.0.1.3

**Log**

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
All machines
Mod yes/no ? Yes

**Relevant script mods**
NO 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8192971/log.txt)

**Comment by Tensuko** [comment]
Old Version:
(Version: 2.0.0.3) FS22_AutoDrive
Not working:
Available mod: (Hash: 4aa2e723e38c190d94468c450e4aec5d) (Version: 1.8.2.39) FS22_Follow_Me
Error: Unsupported mod description version in mod FS22_Follow_Me

Some Mod or anything seems to be super faulty and even makes probelms in your vehicles.xml

No Error from Courseplay found in your logfile.

2022-03-05 19:31   Error (C:/Users/micha/Documents/My Games/FarmingSimulator2022/savegame1/vehicles.xml): Failed to validate xml path 'vehicles.vehicle(32).FS22_Krone_Profi_Liner_AutoLoad.palletAutoLoader#lastUsedPalletTypeIndex' for 'savegame_vehicles'. Path not registered.
2022-03-05 19:31 LUA call stack:
  dataS/scripts/xml/XMLFile.lua (346) : printCallstack
  dataS/scripts/xml/XMLFile.lua (243) : getValueType
  =C:/Users/micha/Documents/My Games/FarmingSimulator2022/mods/FS22_Krone_Profi_Liner_AutoLoad/PalletAutoLoader.lua (290) : setValue
  dataS/scripts/vehicles/Vehicle.lua (1403) : saveToXMLFile
  dataS/scripts/utils/VehicleLoadingUtil.lua (640) : saveToXMLFile
  dataS/scripts/utils/VehicleLoadingUtil.lua (673) : saveVehiclesToSavegameXML
  dataS/scripts/FSCareerMissionInfo.lua (335) : save
  dataS/scripts/utils/Utils.lua (452) : oldFunc
  dataS/scripts/missions/SavegameController.lua (450) : saveToXMLFile
  =[C] (4294967295)
  dataS/scripts/missions/SavegameController.lua (789) : saveWriteSavegameStart
  dataS/scripts/FSBaseMission.lua (2986) : saveSavegame
  dataS/scripts/utils/Utils.lua (440) : oldFunc
  dataS/scripts/FSBaseMission.lua (2324) : saveSavegame
  dataS/scripts/FSBaseMission.lua (2150) : updateSaving
  dataS/scripts/missions/mission00.lua (583) : update
  dataS/scripts/main.lua (1381) : update
