### ISSUE TITLE
[Question]Gülle fahren

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1153]
Hallo
Ich wollte Gärreste von der BGA zum Feld fahren, Er zeigt oben im Balken an: Keine Wegstrecke gefunden habe ich was falsch eingestellt Siehe Bild
![Gärreste](https://user-images.githubusercontent.com/47453761/156936205-a18ad5fd-8758-4570-8b46-98b68fe7dfa6.png)

**Comment by Plopsi** [comment]
Nee irgendwo in deinem AD Netz gibts ne Dead-End sprich eine stelle wo er nicht weiter kommt, mach die punkte an und prüf mal ob du einen weg findest (achte auch die richtung der strecken).

Kenn ich in eigentlich jedem Netz gibt es strecken wo eine sektion falsch rum ist. Da hilft nur prüfen :)

Selten liegen auch 2 Punkte so übereinander das es aussieht das es passt, ist dann trotzdem nicht geschlossen.

Als Debughilfe, fahre langsam stück für stück/punkt für punkt die strecke ab und mache in regelmäßigen abständen den versuch AD fahren zu lassen, sobald es wieder übernimmt suche in dem umkreis nach einem fehler im netz.

- Plopsi

PS: gehört eher zu AD und nicht zu CP ;)

**Comment by Tensuko** [comment]
Ja und was sollen wir damit ? Closed.
