### ISSUE TITLE
[Question] Calmsden Farm Field 1 Course - Help needed

### ISSUE THREAD

**Issue by Will-Smith1965** [Courseplay/Courseplay_FS22#1154]
Would it be possible to create a course on field 1 Calmsden Farm without the impliments wrapping themselves around the poles or trees at each end of the island in the middle of the field. I think you guys do a very good job with what you do on here sorry i can not donate as i am disabled and cash is very tight many thanks

**Comment by Tensuko** [comment]
For that I would need to know where Field 1 is.
Normaly, Island bypass is the way to go.
Round Corners also do help and enough headland.
It also depends on the tool you use.
With a bit more Information I could help you a bit more on whats the best way for it.

**Comment by Will-Smith1965** [comment]
As to where is field 1 is it is on Calmsden farm in farming sim 22 and it is the field with the number 1 in the middle of it
tools used lemken 4.9m plough hardi 24m sprayer and lemken 12m seeder all get caught up on the electric poles and trees at the ends of the island tried using simple and circle both have the same result

**Comment by rohne83** [comment]
I think some screenshots showing the situation would help to understand the issue. In this case it should be very helpulf if you also acticate at least the course waypoints to be shown.

**Comment by Will-Smith1965** [comment]
As i am just a player and have no knowledge of programing i can only let you know what is happening with the program it would be nice if i understood the concepts of programing then i could fix it my self but i do not would it be possible for you to run the game for a while to see what happens and then you will see it first hand for the most part it runs well it will go around the poles etc. Then it will try to do the middle section of the field and totaly does not see the poles etc any more this is when it crashes into them this even happens with the combine harvester i am sorry i can not help with the route as the lines look like they will go around all obstacles but the machine seems to go where it wants thanks for your help and well done for the good work you do.

**Comment by Tensuko** [comment]
A Screenshot would be helpful to solve your problem or at least can advise you to a better way.

**Comment by Tensuko** [comment]
Sry that it took so long.
Those are 5m, 12m and 24m.
I used mostly default settings and changed only the width, amount of headland (2) and shard corners.
It might be that the start loaction takes a role in your Problem.
As said, I would need a Screenshot or a few to see your exact Problem.
For me the course looks good.
![fsScreen_2022_03_26_15_57_02](https://user-images.githubusercontent.com/27344744/160245183-8b2117ba-db2a-4d1f-b95c-b1e28c6eaefb.png)
![fsScreen_2022_03_26_15_58_34](https://user-images.githubusercontent.com/27344744/160245186-0c2d3213-2cc8-440b-b693-53a6700d20fb.png)
![fsScreen_2022_03_26_15_57_53](https://user-images.githubusercontent.com/27344744/160245187-af52d134-6563-425a-b9dc-c861f417b0e5.png)

**Comment by Tensuko** [comment]
Can also be discussed when closed, so closing.
