### ISSUE TITLE
[Question] Job CP Feldarbeit für Weinernte

### ISSUE THREAD

**Issue by MiMiNator** [Courseplay/Courseplay_FS22#1157]
Hallo zusammen,
für den New Holland Braud 9070l kann man keinen Job für CP-Feldarbeit erstellen. Kann man diese Einschränkung irgendwie irgendwo aufheben? Der Giants Helper ist dafür bekannterweise auch nicht freigeschaltet.

Ich würde einfach gerne testen ob ich CP dazu bringen kann auch die Trauben für mich zu ernten.
Mulchen und Düngen der Reben mit CP funktioniert bei mir mitlerweile problemlos.

Danke schonmal für eure Mühe
MiMi

**Comment by Tensuko** [comment]
Work in Progress
