### ISSUE TITLE
Zuckerrüben ernter Tiger 9

### ISSUE THREAD

**Issue by Neotras2552** [Courseplay/Courseplay_FS22#116]
Hallo beim Zuckerrüben Vollernter klappt CP das schneidewerk auf aber nicht die Maschiene dadurch, verbuggt die Maschine insofern das man sie selber nicht mehr benutzen / ernten kann.

**Comment by Tensuko** [comment]
Auch hier bitte immer die Version dazu schreiben (ggf logfile anhängen)...

**Comment by Neotras2552** [comment]
V 7.0.0.4

**Comment by Neotras2552** [comment]
log steht nichts drinne

**Comment by Neotras2552** [comment]
kann man eigentlich irgenwie einstellen das man alles loggt, auch wenn man spiel neustartet?

**Comment by Tensuko** [comment]
Du kannst im .zip file (oder besser wenn du CP über git clonst) im Ordner Config die debugchannels.xml aufmachen und dort die entsprechenden Kanäle auf true setzen. Dann sind die beim start immer an.

**Comment by Neotras2552** [comment]
Welche channel sind denn für euch hilfreich?

**Comment by Tensuko** [comment]
Fieldwork, Generator, Implement, ppc. Glaub das sind die passenden.

**Comment by Tensuko** [comment]
Kannst du bitte, wenn du das probiert hast, ein neues Issue auf machen mit den Informationen ?
Gerade mit der neuen Version die gleich kommt 7.0.0.8
Das wäre super, danke.
