### ISSUE TITLE
[BUG_SP] Loader Wagon fills only up to 95% 

### ISSUE THREAD

**Issue by schuelli238** [Courseplay/Courseplay_FS22#1160]
**Steps to reproduce**
Create a CP course to collect hay, grass and straw

**Actual behavior**
Loader wagon fills only up to 95% and will then move on to the unloading point.

**Expected behavior**
CP should load the loader wagon to 100%

**Screenshots**
https://youtu.be/KVO1iLDFd5s?t=870

**Courseplay version**
Version used: 7.0.1.3 

**Log**
Will provide later, but it's always the same behavior.

**Map**
Elmcreek & Rade

**Vehicles/ implements involved**
Default: Fendt 500, 

**Relevant script mods**
Autodrive, VCA, Enhanced Vehicle,

**Comment by Tensuko** [comment]
Not a bug, intended.
Will see if we change that back to a setting but for now we keep it like that, as we have other important things to do.
A bit patient pls.

**Comment by schuelli238** [comment]
No problem. Thanks for your work on this project.
