### ISSUE TITLE
[BUG_MP] Debugviews enabled in release

### ISSUE THREAD

**Issue by Plopsi** [Courseplay/Courseplay_FS22#1162]
It's a very small issue - more an information as a bug
Maybe there is something enabled I'm not aware of how to disable it.

Usually it disappears when CP reaches the first course point/or whatever point it wants to go to. But sometimes they get stuck until a new attempt is made to drive to a point.

**Steps to reproduce**
just start a CP course, put the start point a bit away

**Actual behavior**
a debugline of pathfinder appears

**Expected behavior**
no debugline appears

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17942998/157525485-9b57bc80-80ec-487b-8696-71168e3ce170.png)

**Courseplay version**
Version used: 7.1.0.4

**Player on the server**
2-4

**Dedicated server or local hosted server**
Dedicated server

**Map**
Nordfriesische Marsch x4

**Vehicles/ implements involved**
Up to now, all vehicles and implements.

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
already fixed for next version.
