### ISSUE TITLE
[BUG_SP] Convoy - workers colliding on headland when executing a 3-point turn

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#1166]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course with sharp headland turns and a short distance between workers

**Actual behavior**
When executing a 3-point turn on a headland, follower will collide with leader - I assume this is because the "thread" follows the turn and thus separation between workers can no longer be maintained

**Expected behavior**
Follower should wait for leader to complete turn

**Screenshots**
https://youtu.be/bx4fsqv6cro

**Courseplay version**
7.0.1.4

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8218718/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Default and mod tractors with a mod implement in this particular instance, but also affects default equipment

**Relevant script mods**
AD, VCA, multiple others

**Comment by Tensuko** [comment]
Distance to short.
Debug on the other tractor would have been more interesting to see the rope.

**Comment by pull2play** [comment]
> Distance to short. 

Yes, that was my point. The way separation is handled now, the default minimum safe distance should probably be increased, as 40m is too short. That said, a wider distance does have a knock-on effect elsewhere - this often creates collisions when - depending on course configuration - vehicles enter or exit a headland.

> Debug on the other tractor would have been more interesting to see the rope.

I'm not sure I understand? Debug was on all three tractors - or did I miss the first one? - if I did, I will try to rerun the course asap. The first tractor (left lane) was much further ahead of the other two, as there now doesn't appear to be any distance restrictions placed on the leader. As the left lane covers less ground during turns, the vehicle in that lane will always pull further ahead of its followers.

**Comment by Tensuko** [comment]
There will always be a problem point if you look at all the different kinds of course we can generate, it is way to diverse to have all situations solved 100%

I was just wondering where the rope was from the 1st tractor thats why I asked for debug.
Haven't seen it on the Video.

**Comment by pull2play** [comment]
Understood :) Since the entire course is close to an hour long, recreating the exact scenario will take too long. I did record an example where all three are visible - but it plays out differently due to distances involved. I appreciate that no obvious solution to this problem comes to mind, other than babysitting the course and manually halting workers in problem spots. I imagine it wouldn't be possible to dynamically increase and then contract distance when executing a 3-point turn?

Anyway, here's the video and log and I suppose it's ok to close this issue then, up to you :) Thanks.

https://youtu.be/75dv8qenOrQ

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8223461/log.txt)

**Comment by pvaiko** [comment]
#1161 may help with this a bit, and we'll certainly enhance this functionality in the future, step by step...

**Comment by pull2play** [comment]
> #1161 may help with this a bit, and we'll certainly enhance this functionality in the future, step by step...

Ok, I went ahead and did a quick test - this is actually worse now, it creates a hard block. Over the weekend I will go back and redo this on a clean map without any script or vehicle mods, just to rule out anything else, and report back then.

https://youtu.be/D8-9uSs2Dfo


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8224187/log.txt)

**Comment by pvaiko** [comment]
No need to redo anything just use a bigger distance.

**Comment by Tensuko** [comment]
Simple proximity sensor like in 19 could help too...
