### ISSUE TITLE
[Question]Abfahren bzw. Abladen bei 95%

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1167]
Hallo Leute, wieso füllt CP (in verbindung mit AD) nur bis 95% auf?
habe einen Traktor mit Ladewagen (deutz7 + claas cargos 9500) und dieser fährt den cp kurs und füllt nur bis 95% auf dann fährt der AD ab.
der claas convio drescher drischt auch nur bis zu 95% voll, stoppt und wartet auf den AD abfahrer
lg
andreas

**Comment by Tensuko** [comment]
Weil das von uns erst mal so gewollt ist.
Abwarten und Tee trinken.

**Comment by andreasthu** [comment]
ok,danke
