### ISSUE TITLE
Worker just drive in circles

### ISSUE THREAD

**Issue by caracarn3** [Courseplay/Courseplay_FS22#117]
Trying to get started testing this.   I am using on AFB Mapping 16x Hastings map.   Copied an existing save game over to new slot as starting point.   Course generated fine it appears for the field I am on.   When I start job with either first waypoint or nearest waypoint the harvester just drives in a circle.   It is not trying to harvest, has not lowered header, just circles.

**Comment by Tensuko** [comment]
Screenshot, logfile, Version and so on....

**Comment by pvaiko** [comment]
If it does not lower the header then most likely CP does not even have the control over the vehicle yet, it is still Giants driving.

**Comment by caracarn3** [comment]
Version 7.0.0.4
Log file: https://gist.github.com/caracarn3/1796faa006a207d79d19a840b8dcead6


![image](https://user-images.githubusercontent.com/24917927/147408511-0ad51bdd-5447-4582-bb4e-848a863d27b5.png)

**Comment by caracarn3** [comment]
@Tensuko Added what you asked for.   Not sure how to change the status from waiting for user so hoping this ping gets you.    

Also, tried CP on Elmcreek and was able to get it to work properly as wanted to make sure it was not me.   Then went back to this map and tried several fields and just random driving behavior.   One field it just started going down the road and then turn left a bit the get back on road the straight and would have just driven off the map if I let it.    

So does a map creator need to set something for CP to work with fields and it that perhaps the issue?   The courses are generated properly for the strange shaped fields but not sure if perhaps since this is a modded map there is some issue there?

**Comment by Tensuko** [comment]
I have not tested any modded map yet. Can't rly tell you.
For Fieldwork I thought it should not matter at all...
But thanks for your Feedback, so we know where we can look for.

**Comment by pvaiko** [comment]
Again, CP only drives the fieldwork, after the Giants helper drives to the target point. If the vehicle does not reach the target point, it is most likely not a CP issue.

Closing as 16x maps are not a priority now.
