### ISSUE TITLE
Debug lines visible before start point

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#1173]
Hello!
In the new version v7.0.1.4 I realized that the debug lines are visible on the way to the start point - see screenshot. Is this a new feature? Is there a possibility to switch this of?
![Courseplay_DebugLinien](https://user-images.githubusercontent.com/76711921/157762336-a810456c-0c6d-4db2-94c4-0779b26bb8b5.jpg)

Thanks!

P.S. Thank you very much for the work on the scripts - I'm very impressed by the speed you are working on getting it running in FS22.

**Comment by Tensuko** [comment]
Already fixed for next Version...
