### ISSUE TITLE
[BUG_SP] Blauer Balken auf dem Bildschirm

### ISSUE THREAD

**Issue by TobiHH78** [Courseplay/Courseplay_FS22#1178]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
Bei der aktuellen Dev-Version habe ich einen blauen Balken auf dem Bildschirm, der sich mit dem CP-Mousebutton verschieben lässt.
Bei der letzten Releaseversion tritt dieser Balken nicht auf..
Zum Start taucht er rechts oben auf., danach wie gesagt verschiebbar.

Habe an Mods auch lediglich CP & AD aktualisiert

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: Letzte Version, gerade runtergeladen

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Hobo`s Hollow 4x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

![1](https://user-images.githubusercontent.com/56259322/157906105-eba34fa8-31bd-4577-8802-74cad6138856.PNG)

![2](https://user-images.githubusercontent.com/56259322/157906141-4d1e53f0-55e4-4f74-9872-e35fcfdb2962.PNG)

**Comment by Tensuko** [comment]
Gut beobachtet.

**Comment by TobiHH78** [comment]
Und welchen tieferen Sinn hat der? Wäre ja nett, wenn du nicht nur mit so einem wahnsinnig witzigen Kommentar antworten würdest.

War eine ernst gemeinte Meldung, wenn da plötzlich auf dem Bildschirm etwas undefinierbares und scheinbar ohne Funktion behaftetes Rechteck auftaucht...

**Comment by Tensuko** [comment]
Wenn man sich an unsere Empfehlung halten würde, bei der Release Version zu bleiben, würden solche Fragen gar nicht erst aufkommen und "irgendwas" als bug reportet werden.

Wenn du schon den Main Branch runter lädst, dann könntest du dir auch die Commits durchlesen, was alles gepusht wurde auf den Main Branch, dann wüsstest du wofür das ist!

https://github.com/Courseplay/Courseplay_FS22/commit/41a166f3ce4046057a9761ef48a599cda5d938a6

**Comment by TobiHH78** [comment]
Was ich getan hätte wenn ich solche Sachen wissen würde. Nicht jeder ist bei solchen Dingen Vollprofi…

Aber danke, nun weiß ich Bescheid.

**Comment by Tensuko** [comment]
> Nicht jeder ist bei solchen Dingen Vollprofi…

Genau aus diesem Grund sagen wir, bleibt beim Release...
Dafür erstellen wir die changelogs usw damit das klar wird.
Irgend ein Stand von Release is halt irgend ein Stand...
