### ISSUE TITLE
[BUG_SP] cp doesn't stop when fuel runs out

### ISSUE THREAD

**Issue by FakeCrossed** [Courseplay/Courseplay_FS22#1183]
cp doesn't stop when fuel runs out

**Courseplay version**
Version used:  7.0.1.4

**Log**
[log.zip](https://github.com/Courseplay/Courseplay_FS22/files/8237152/log.zip)

**Comment by Tensuko** [comment]
.no template used and why on earth log zip

AD also does this so we think that got something to do with the game itself.
