### ISSUE TITLE
[BUG_MP] man sieht  zahlen wo couresplay aktiv ist 

### ISSUE THREAD

**Issue by Haumichweg** [Courseplay/Courseplay_FS22#1185]
![fsScreen_2022_03_12_11_04_17](https://user-images.githubusercontent.com/96336261/158013701-f63f97de-472f-48be-986b-f49d9db0fac2.png)
hiho seit dem neusten updatet sehen wir die zahlen ?! ist das normal jetz oder gibt es da eine Einstellung wo die nicht mehr sieht? wenn ja bitte bescheid geben :-)

Gruß Steve

**Comment by Tensuko** [comment]
Kein Template benutzt, keine Suche benutzt.... ist schon gefixt?! (nächste Version!)
