### ISSUE TITLE
[Enhancement] Schlenker nach aussen bei U-Wende?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1194]
Hallo Leute
bei mir fährt der Kartoffelroder bei einem spiralförmigem Kurs mit 6 Vorgewenden so einen komischen Schlenker nach aussen zur Feldgrenze bevor er die U-Wende beginnt:
![fsScreen_2022_03_13_17_31_48](https://user-images.githubusercontent.com/24860501/158069650-409ed158-94b3-4bfb-81f5-d66fef3a22dc.png)

das ende macht er normal:
![fsScreen_2022_03_13_17_32_16](https://user-images.githubusercontent.com/24860501/158069655-2e7b563e-7267-4d9a-8609-a153069c39f1.png)
![fsScreen_2022_03_13_17_32_22](https://user-images.githubusercontent.com/24860501/158069657-49d19020-82bf-4144-a25f-82034366d584.png)

Kurseinstellungen:
![fsScreen_2022_03_13_17_33_27](https://user-images.githubusercontent.com/24860501/158069663-9a478a54-1d48-499c-99e5-694a214a96b1.png)
![fsScreen_2022_03_13_17_32_06](https://user-images.githubusercontent.com/24860501/158069669-d0548f6f-19da-476d-a81d-1c3242473d7f.png)

edit:
auf der anderen Seite dasselbe
![fsScreen_2022_03_13_17_41_09](https://user-images.githubusercontent.com/24860501/158069826-2ec7010d-c36f-459b-bb51-092540ca3174.png)
![fsScreen_2022_03_13_17_41_11](https://user-images.githubusercontent.com/24860501/158069827-b550492f-ef36-4f04-8499-e4009fa93fc0.png)
![fsScreen_2022_03_13_17_41_17](https://user-images.githubusercontent.com/24860501/158069829-6b1606a3-5b6a-4a08-aa2b-0b8188dd7363.png)

ist das normal bzw soll das so sein?
lg
andreas

**Comment by Tensuko** [comment]
logfile mit den debugs ?

**Comment by andreasthu** [comment]
hallo Tensuko
hier die log und der Roderkurs (als txt)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8243326/log.txt)
[Roder.txt](https://github.com/Courseplay/Courseplay_FS22/files/8243327/Roder.txt)

hier nochmal auf HB, Feld 41:
(bilder heute vom Kurs bzw der log)
![fsScreen_2022_03_14_10_00_37](https://user-images.githubusercontent.com/24860501/158139518-fb17c666-ace2-4ed4-b4d7-49987e950188.png)
![fsScreen_2022_03_14_10_00_41](https://user-images.githubusercontent.com/24860501/158139529-bc878b64-9f5e-4abf-ac44-0d6736aa7d63.png)
![fsScreen_2022_03_14_10_00_43](https://user-images.githubusercontent.com/24860501/158139533-bc83e96e-2a3b-4dfb-b314-46fdf1e91b85.png)
![fsScreen_2022_03_14_10_01_11](https://user-images.githubusercontent.com/24860501/158139538-f65b0f85-8912-4f07-8851-4b8c3125c780.png)
!
![fsScreen_2022_03_14_10_01_15](https://user-images.githubusercontent.com/24860501/158139548-383a4786-d71a-4a53-8378-8ec262e63bde.png)
[Uploading fsScreen_2022_03_14_10_01_13.png…]()

lg
andreas

**Comment by rohne83** [comment]
Das scheint ja Pathfinder-Turn übers erste Vorgewende zu sein. Zumindest bei unregelmäßigen Feldern sieht man das ohnehin öfter mal, dass da nicht unbedingt immer der Weg genommen wird, den auch ein Mensch fahren würde. Und hier kommt einfach auch noch ein etwas anspruchsvolleres Fahrzeug hinzu. Bei dem Grimme befindet sich die Workarea ja extrem weit vor der Lenkachse, weswegen da eben auch deutliche Ausholbewegungen erforderlich sind. Am Ende des Turns gibt es ja ebenfalls so eine Ausholbewegung, nur dass sie dort nicht so krass ausfällt.

**Comment by andreasthu** [comment]
Das problem, auch beim Drescher mit 2 oder mehr headlanes, besteht mit 7.0.1.16 immer noch.
Lg
Andreas

**Comment by Tensuko** [comment]
Weis nicht ob @pvaiko das etwas abändern kann und man eher direkt auf die äußere Bahn zu fährt statt diese extra Bögen.
Dann wäre das immerhin etwas abgeschwächt.

**Comment by andreasthu** [comment]
ja, das wäre toll,
solange geradeaus fahren bis man an die äußerste Bahn kommt
lg
andreas

**Comment by rohne83** [comment]
Gestern auf der Landkreis Rostock hab ich wie es scheint eine besonders extreme Form dieses Verhaltens beobachtet, das zudem dazu geführt hat, dass die Wende überhaupt nicht mehr geklappt hat, und der erste Fahrer sich regelmäßig selbst entlassen hat.
Feld 45 (am südwestlichen Feldrand von Feld 6 das selbe gehabt), 2 mal 14 Meter, ein Vorgewende, Start auf den Feldreihen, Muster für die Feldmitte war kreisförmig (hat für Verbände bei der Bodenbearbeitung einfach die geringste Kollisionsgefahr und macht ein ziemlich gutes und durchaus auch im RL anzutreffendes Arbeitsbild).

![fsScreen_2022_07_30_00_03_40](https://user-images.githubusercontent.com/71030138/181897691-074b569b-6249-438a-a434-a50040e1cd48.png)
![fsScreen_2022_07_30_00_03_50](https://user-images.githubusercontent.com/71030138/181897993-89f2140f-3cb3-40bf-997d-371c92236df7.png)
![fsScreen_2022_07_30_00_04_18](https://user-images.githubusercontent.com/71030138/181898054-5bc047e2-6a8e-43e9-966c-eaf99dd40c0e.png)

**Comment by andreasthu** [comment]
Hallo @Tensuko 
ich schreib hier mal wieder, weil das eckenproblem hier nun etwas "verschärft" wurde.
seit kurzem (aktuelle main) hab ich nicht nur das der Drescher (nach 2 Vorgewenden) bei 6 Beeten beim der dritten Runde im ersten Beet (nahe der Feldgrenze nicht nur zur Feldecke raussteuert, sondern sogar ein kleines Stück retour schiebt:
![fsScreen_2022_09_22_09_13_14](https://user-images.githubusercontent.com/24860501/191683253-f43c54a6-b024-4db1-a506-2c04198a5af2.png)
![fsScreen_2022_09_22_09_13_17](https://user-images.githubusercontent.com/24860501/191683309-037549b5-74be-44eb-a26e-151302039ce7.png)

beim zweiten umlauf (vorher) klappt alles noch wunderbar:
![fsScreen_2022_09_22_09_13_43](https://user-images.githubusercontent.com/24860501/191683427-2133fedf-92d7-45e4-8337-69d6e0955bab.png)

auch bei dem nächsten Beet, und den folgenden, gibts ne normale wende:
![fsScreen_2022_09_22_09_14_20](https://user-images.githubusercontent.com/24860501/191683544-c3542f0e-e5b5-4e31-b1ca-778729040ee6.png)

kann sich der Drescher nicht nach vorne orientieren zur Feldkante, und die seitliche ignorieren?

btw, der (nachfolgende) Traktor mit Ladewagen, mitgleichem cp kurs fährt eine "normale" Wende:
![fsScreen_2022_09_22_09_22_49](https://user-images.githubusercontent.com/24860501/191684335-b96fe2d4-90cc-4010-af3f-e1846dbee420.png)

wenn gebraucht, hier noch der kurs:
[Dreschen.F19-21. 13,5m.txt](https://github.com/Courseplay/Courseplay_FS22/files/9623344/Dreschen.F19-21.13.5m.txt)
(map ist übrigens hobos hollow 4x)

lg
andreas

**Comment by Tensuko** [comment]
Habe das mit der aktuelle Version bei 2 Dreschern an der Ecke ausprobiert und konnte es bisher nicht reproduzieren.
Sollte das wieder auftauchen, bitte issue mit neuem log wieder auf machen.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/a4fdc0db-5f6a-4b88-99a7-5f6b103786d1)
