### ISSUE TITLE
Autodrive menu pops up on Active Worker screen

### ISSUE THREAD

**Issue by caracarn3** [Courseplay/Courseplay_FS22#120]
I have the AD HUD off but when I open the screen it appears.

![image](https://user-images.githubusercontent.com/24917927/147408307-e577f9c7-906c-4911-aa04-93de49aba0c3.png)

**Comment by Tensuko** [comment]
That is correct and wanted from AutoDrive. Whats not so good is that you can't close it. Pls Open an Issue for this on AutoDrive GitHub.
