### ISSUE TITLE
<coursplayfahrer übergabe von AD[BUG_SP]

### ISSUE THREAD

**Issue by masuti** [Courseplay/Courseplay_FS22#1201]
Wenn der CoursplayFahrer mit AD zum Feld geschickt wird und der Kurs beginnt auf Bahnen dann wird ein ganzer Schweif 
Coursplaypunkte angezeigt die auch am Bilschirmrand weiter weg vom Feld gesehen wird.
Version CP 7.01.14
Version AD 2.0.0.4

**Comment by dominiczeth** [comment]
Das ist seit Version 7.0.1.4 so. 
Seit CP mit zugeklappten Gerät zum Start fährt.

**Comment by Tensuko** [comment]
Suche nutzen, wurde schon oft genug gesagt ist gefixt mit der nächsten Version...
