### ISSUE TITLE
[Question] Anzeige wie lange eine Arbeit noch dauert?

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1205]
Hallo.
Ich wollte mal nachfragen ob den geplant ist wie im LS 19 wieder eine Anzeige einzufügen wie Lange z,b der Grubber brauch das Feld zu bearbeiten. Ich weiß das es momentan vlt andere Sachen gibt die wichtiger sind aber rein aus Interesse wollte ich mal nachfragen

**Comment by Tensuko** [comment]
#1108
