### ISSUE TITLE
Scheinbarer bug beim Walzen

### ISSUE THREAD

**Issue by AstraThomas** [Courseplay/Courseplay_FS22#1206]
**Steps to reproduce**
Steps to reproduce the behavior.
Die fendt 1100 Mt Raupe an die große 24m walze anhängen

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
Kurs erstellen > Feldmitte hoch runter, 2 vorgewende > Startpunkt (erster startpunkt) > Raupe Fährt hin klappt auf und während des aufklappens fährt die Raupe schon los. Ebenso wird das gerät bei den Wendemanövern nicht angehoben.

**Screenshots**

**Courseplay version**
Version used:  7.0.1.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8247778/log.txt)

**Map**
Map played on.
Huropn County 1.1.4

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Fendt 1100 MT + Dalbo Megaroll 2430
no mos

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Nope

**Comment by Tensuko** [comment]
> Ebenso wird das gerät bei den Wendemanövern nicht angehoben.

Schon mal selber versucht die Walze an zu heben?
Richtig, das geht nicht, weil es nicht vorgesehen ist vom Gerät her, die hat keine Hebefunktion.

Das ausklappen ist so ein Problem bei den Walzen, weil die ihre Animation sehr langsam abspielen.
Heist aber das wird nicht warten bis das Gerät aufgeklappt ist.

Wäre jetzt die Frage ob der Giants Helfer wartet bis die Walze aufgeklappt ist.
Bitte einmal ausprobieren.

**Comment by Tensuko** [comment]
Closed due to inactivity.
