### ISSUE TITLE
[Feature] Small UX improvement when loading courses that are in a different folder

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#1212]
**What is the problem this feature/enhancement solves?**
If a course is in a different folder than the one currently selected, when you click "load course" and then click that folder, you get a warning that "\<folder name\>" isn't a course. In the attached screenshot "planter" is the name of a folder, not a course.

**Describe the solution you'd like**
It should know that a folder isn't a course and allow the user to change folders without showing the warning. 

**Describe alternatives you've considered**
Making sure you're in the correct folder before clicking "load course" is the obvious suggestion...

**Additional context**
![fsScreen_2022_03_15_20_08_38](https://user-images.githubusercontent.com/30246276/158453475-7bbc3d2d-51f2-41cd-83fe-6a5c95fe12b1.png)

**Comment by Tensuko** [comment]
That can't be changed.
You have to first select the folder, then load the course.
