### ISSUE TITLE
Mouse disabled when on foot (mod conflict)

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/Courseplay_FS22#1214]
Hi team,

With the latest release the mouse is constant getting disabled when im on foot and want to activate the mouse. My mod uses the mouse on foot, but CP disables it in a update loop.
With this u blocking some functionality of my mod ;)

It seems in the script Courseplay.lua, function on line 260 is doing that. (@schwiti6190 added this )
Can u not disable this if not needed?

Thanks in advance
Bob

**Comment by Tensuko** [comment]
So you talk about https://github.com/Bobster82/FS22_VehicleInfo ?

**Comment by Bobster82** [comment]
Yes, thats right.

**Comment by schwiti6190** [comment]
@Bobster82 Hi there, 
you could simply overwritte this function: "Courseplay.updatePlayerActionEvents(player)". 
The mod action event compatibilities ar a mess, so I will probably not change this in the near future.

**Comment by Bobster82** [comment]
@schwiti6190  Hi,
I stopped modding for FS a few weeks back, Lost my fun. So I cant update any mods of mine due changes of other mods.
But I find it a bit strange that I need to change my mod due the fact you made a change that affects my mod (and maybe others too) 
Why is CP leading in showing the mouse cursor or not? Please dont prevent other mods not using the mouse in player mode.

**Comment by schwiti6190** [comment]
@Bobster82 I get your point but I don't see a easy fix at the moment and I neither have the time or motivation to fix this right now maybe at a later time. Mod confilct will always happen and we can't always change these on our side, as this complicates a already over complex mod even further sometimes from the code. Either you can look for a solution on your on and create a pull request, as you identified the parts in our code or you would have to wait :)

**Comment by Bobster82** [comment]
@schwiti6190 ,
Ok thanks for the answer. I removed your part from the code and I can continue ;) Maybe in the future there will be an update about this. Im not a programmer, so It would take me loads of time I dont have at the moment.
Keep up the great work, I know how time consuming it is.
Thanks

**Comment by dkfiremann** [comment]
You can disable the infotext box in the settings, that disable this mouse bug. 
And yes it is a bug. 
You can't use Measure mod, it will give you problems. 

@schwiti6190 you could make another filter on the action update, to check if there is any text/info in the text box. Right now you only check for if it is visible.
