### ISSUE TITLE
Kartoffelernter Fährt einfach rückwärts statt die Bahn zu wechseln 

### ISSUE THREAD

**Issue by Obsiana2019** [Courseplay/Courseplay_FS22#122]
Der Kartoffelernter fährt statt die Bahn zu wechseln einfach rückfährts bis er auf ein Hindernis trifft. Version 7.0.0.4

Er fährt die Strecke erst in die richtige Richtung und erntet und anschließend fährt er die selbe Strecke komplett rückwärts.

lg Obsiana

![image](https://user-images.githubusercontent.com/54123126/147408496-57388847-79c6-4a49-b3bc-941433e03852.png)

**Comment by Tensuko** [comment]
Oops. Will check that one... Thanks for Feedback.

**Comment by Neotras2552** [comment]
Zuckerrübenernter Auch

**Comment by Tensuko** [comment]
Ok, danke für die Info.

**Comment by Tensuko** [comment]
Should be fixed already.
