### ISSUE TITLE
[BUG_SP] Düngerstreuer streut nach Ende des Kurses weiter.

### ISSUE THREAD

**Issue by TheDivine07** [Courseplay/Courseplay_FS22#1222]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Düngerstreuer mit Mineraldünger ein Feld düngen lassen.

**Actual behavior**
Der Düngerstreuer fährt den gesamten Kurs problemlos ab bis er am Ende ankommt, stehenbleibt aber die Düngefunktion nicht abschaltet.

**Expected behavior**
Abschalten der Düngefunktion nach Beendigung des Kurses.

**Screenshots**
https://i.imgur.com/mJFUsal.png

**Courseplay version**
Version used: 7.0.1.5

**Log**
https://workupload.com/file/bJJGpADMdwx

**Map**
Haut Beyleron

**Vehicles/ implements involved**
Fendt Favorit 511c - Traktor - Standard
Bredal  K105 - Düngerstreuer - Standard

**Relevant script mods**
AD, VCA

**Comment by MacRama1** [comment]
das kann ich bestätigen, habe dasselbe Phänomen, ausserdem wird der motor nicht abgeschaltet, (womit der streuer auch nicht mehr streuen würde).

**Comment by Tensuko** [comment]
#1208
Suchfunktion ist was feines. Duplcate.
