### ISSUE TITLE
[BUG_MP] Fertilizer spreader does not switch off at the end of the route

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1224]
**Steps to reproduce**

I plan a route and then hook up the fertilizer truck and let it run along the route

**Actual behavior**

The fertilizer spreader does not go out at the end of the route if you are not sitting inside and just keeps running until empty.

**Expected behavior**

The fertilizer spreader should stop fertilizing at the end of the route

**Screenshots**
https://youtu.be/PGoqTObHX1E

**Courseplay version**
Version used: 7.0.1.5

**Client Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8274652/log.txt)

**Server Log**
[Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8274587/Server.Log.txt)

**Player on the server**
1

**Dedicated server or local hosted server**
Dedicated server Yes

**Map**

Nordfriesische Marsch 4fach]

**Vehicles/ implements involved**

Kein Mod Fahrzeug

**Relevant script mods**
Autodrive 2.0.0.5-RC

**Comment by Tensuko** [comment]
Aaaand the next one... Duplicate #1208

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/1222#issuecomment-1069557244
