### ISSUE TITLE
[Feature] Fahrgassen

### ISSUE THREAD

**Issue by ChrisKeng** [Courseplay/Courseplay_FS22#1225]
Da Wopsters ProSeed angekündigt wurde, wäre ggf. eine tolle Erweiterung des CourseGenerators, wenn man sogenannte Fahrgassen erstellen lassen kann beim Ansäen.

Im FS19 habe ich sonst immer das Feld komplett gesäet und dann einmal mit der erforderlichen Breite der Fahrgasse (z.b. 24m) dann einmal mit der Sähmaschine und eingeschalteter Fahrgassenerstellung das Feld noch einmal bearbeitet.

Hier wäre jedoch eine direkte Lösung angenehmer.

**Comment by Tensuko** [comment]
Wie stellst du dir das vor mit der Berechnung von Vorgewende, Bahnen und Üerlappungen ?
Das ist fast unmöglich das in Verbindung zu bringen...

**Comment by Aichinto** [comment]
Nur mal so ein Gedanke in den Raum geworfen...
Eventuell könnte man das über die Funktion "Beete" machen (quasi Anzahl der Beete * Arbeitsbreite = Spritzt breite) 
                                                                                                                                  7      *     3m             =  21 m
allerdings müsste man es dann schaffen zu sagen das er genau bei der 4ten reihe proseed aktivieren soll...
Was ich mir wiederum sehr kompliziert vorstelle...

aber war nur mal so ein Gedanke im raum

**Comment by Tensuko** [comment]
Ja und das ist eben das Problem...

Sry aber das ist zu komplex und hat eher wenig nutzen für uns.
Vlt irgendwann mal wenn nichts weiter zu tun ist, aber erst mal closed.
