### ISSUE TITLE
[Feature] Add Stone Pickers to Harvester class

### ISSUE THREAD

**Issue by m0box** [Courseplay/Courseplay_FS22#1226]
**What is the problem this feature/enhancement solves?**
Using stone picker the helper stops when picker is full requiring manual intervention to unload.

**Describe the solution you'd like**
To have the stone picker drive to and unload into a trailer on the side of the field as combine harvesters do when self-unload is selected.

**Describe alternatives you've considered**
Autodrive, but nothing to fully automate the process is available.

**Additional context**
CP v7.0.1.5

**Comment by m0box** [comment]
Ok sounds a plan, so which mode for AD should I select? I setup a little looping AD route that has a reverse to the trailer for unload. Now to link the CP activity with AD.

**Comment by Redster999** [comment]
I dont think AD recognize the trailer, there needs to be a trigger. I got a limefactory mod and dump it in there by using pickup and deliver mode. Works great. Just set ad up and hit the cp button, You can start on both cp and ad, both works fine as intended

**Comment by Tensuko** [comment]
The stonepicker needs a pipe for that.
I don't think it got one.
Beside that, we already said that the Stone Picker hand over to AD is on TODO.

**Comment by Tensuko** [comment]
Alright then :)
