### ISSUE TITLE
[BUG_MP] Implement lowered too late

### ISSUE THREAD

**Issue by cyler2k19** [Courseplay/Courseplay_FS22#1228]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Happening on any course with the Horsch Joker 12 RT from modhub or with the Amazone Citan 15001-C Seeder aswell

**Actual behavior**
Some implements are lowered too late after turning at the headlands. I already tried the option to lower the implement later but it's lowering still at the same position after turning. The tractor is driving a few meters forward, drive backwards with lowered implement and start to drive at the course again.

**Expected behavior**
Lower the implements directly after turning

**Screenshots**
https://youtu.be/8yWgrx7Lhq0

https://www.directupload.net/file/d/6490/mgyy9nq7_jpg.htm
https://www.directupload.net/file/d/6490/ctahcmim_jpg.htm
https://www.directupload.net/file/d/6490/3phfh4sz_jpg.htm
https://www.directupload.net/file/d/6490/6858ex54_jpg.htm

**Courseplay version**
Version used: 7.0.1.5

**Client Log**
https://gist.github.com/cyler2k19/84b09a7fab0e733d46c5a2a3246d5c39

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
1 or 2

**Dedicated server or local hosted server**
Dedicated server
 yes

**Map**
NF Marsch 1.2.0.0

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234610&title=fs2022](url)
Vanilla Amazone seeder

**Relevant script mods**
Autodrive, Enhanced Vehicle, etc

**Comment by Tensuko** [comment]
Did you set lower on early ?
