### ISSUE TITLE
Badly enters the first strip after 2 laps of the field

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#123]
Hi. Before opening I took a quick look and didn't see that there are any other messages related to this problem.
As in the screen, red line, the worker made the entrance abnormally. Then he continued and finished the job without any problems.
I started in the bottom left corner up. The gray line is a job not done. however it thins out and remains only for the first piece of the first strip that I had to go over later.
I think the whole log is there. Now I don't know if it took the working of the previous field. I didn't have the mod logs active and therefore there should be few messages. [https://pastebin.com/puaLu85h](https://pastebin.com/puaLu85h)

![fsScreen_2021_12_26_13_12_59](https://user-images.githubusercontent.com/96330304/147408385-d33acdc6-3007-4076-93f9-0054fa190a38.png)

**Comment by Tensuko** [comment]
That might be due to round corners or becouse the tool is a 3-point attached one.
With towed tools he should do a nice round circle to get very clear into the 1st row.

**Comment by Markus33-ITA** [comment]
Aside from the fact that I have noticed that it holds the instrument low when it should be getting it up in a relatively not short but reasonable time. Instead of going back and lining up, he continued on his way. Now I don't know if it depends on the fact that the strip is less wide than the instrument.
In previous versions less wide piece did it eventually.

**Comment by pvaiko** [comment]
Do you have that course saved and can post it here?

**Comment by Markus33-ITA** [comment]
no I don't keep it saved. I try in another playing trying to replicate the situation and save

**Comment by Markus33-ITA** [comment]
I tried 3 times on a new game reloading each time and 2 times, without reloading, in the same game of the screen. I was unable to replicate the anomaly.
Same field and same machining setup. He does not want to appear.
I have been very lucky to enable logs in abnormal work.

**Comment by pvaiko** [comment]
Reopen if you can reproduce it
