### ISSUE TITLE
[BUG_SP] Amazon TS10001 keeps running (and empty) as driver end course

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1232]
**Steps to reproduce**
get a course with the amazon TS10001

**Actual behavior**
not always, but sometimes, the drive get to the end of the course, and the Amazon keep running, empty the equipment, wasting fertilizer.
but it's not always happening
if i follow the driver, it's ok, if not, sometime i pick the deriver again and he continue empty the fertilizer, despite beeing at the end of the course

Dk if other player got the same sometimes :/

**Expected behavior**
Amazon should stop when the driver get to the end of course

**Screenshots**
hard to reproduce, i'm getting this when i'm not following the driver (doing other thing of following other driver)

**Courseplay version**
Version used: since 7.1.0.4

**Map**
Elmcreek

**Vehicles/ implements involved**
fastrack 8330 + amazton TS 10001 with fertilizer

**Relevant script mods**
AD 2.0.0.4

**Comment by Tensuko** [comment]
#1208
