### ISSUE TITLE
[Question]Wagen hängt

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1234]
Hallo
Kann man irgendwas einstellen damit der Wagen nicht an der Brücke festhängt 
![Baumwoll](https://user-images.githubusercontent.com/47453761/159065795-6f7082a9-f950-49e5-bb3c-3fddd2476606.png)

**Comment by Tensuko** [comment]
Falches GitHub, das heir ist CP und nicht AD.
Wenn du deinen Kurs auf der Brücke pro Spur hast und dein Wagen breiter als die Spur ist, was sollen wir oder die Jungs von AD dann machen ?
Den Wagen schrumpfen ?
