### ISSUE TITLE
[BUG_MP] Ballen sammeln auf user defined field

### ISSUE THREAD

**Issue by RolfN9597** [Courseplay/Courseplay_FS22#1235]
**Steps to reproduce**
Start collecting bales on a user defined field

**Actual behavior**
Error : No field found

**Expected behavior**
Start collecting bales

**Screenshots**
to verify tractor position, see attached screenshot

**Courseplay version**
latest  7.0.1.5

**Client Log**
attached

**Server Log**
attached

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server yes/no ? yes

**Map**
Map played on. la plaine francaise

**Vehicles/ implements involved**
Which vehicle or implement? 8280 TTV with RBM 2000
Mod yes/no ? no

**Relevant script mods**
Mods like Autodrive or VCA and so on. 
Autodrive yes, VCA yes
[game.log](https://github.com/Courseplay/Courseplay_FS22/files/8307112/game.log)
[log01.txt](https://github.com/Courseplay/Courseplay_FS22/files/8307121/log01.txt)
[game.log](https://github.com/Courseplay/Courseplay_FS22/files/8307123/game.log)

**Comment by Tensuko** [comment]
What is the term "user defined field" ?
You created on on your own or the actual custom Field saved with CP ?
Becouse with custom Field does work in SP.

**Comment by RolfN9597** [comment]
I mean a custom field created by CP (name is "cp-1"). As far as I understand, the data is saved in 
"C:\Users\<username>\Documents\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay\CustomFields\FS22_LaPlaineFrancaise.Laplainefrancaise\<fieldname>

If this is not synced with the server, that would explain it.

**Comment by Tensuko** [comment]
Thats the reason yea I think we did not synch custom fields yet.

**Comment by cyler2k19** [comment]
Got the same problem with the Kuhn square bale wrapper on a custom field on dedicated server.
