### ISSUE TITLE
[Question] Rohrposition Rübenroder

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1236]
Hallo CP-Team
ist es möglich, die Rohrposition beim Abtanken, z.b. dem Rübenroder zu speichern?
CP stellt immer die standartposition ein, daskann aber manchmal bei Hanglagen (der Ropa gleicht das ja aus) einfach zu tief sein.
lg
andreas

**Comment by Tensuko** [comment]
Geplant für später. Aktuell sind andere Dinge wichtiger.

**Comment by andreasthu** [comment]
Ja ok.
Weiß mir so zu helfen.
Hab in der panther2.xml die rotationswerte arm1 und arm3 in der pipeposition so geändert das mit "O" nun höher ausgefahren wird.
Lg
Andreas
