### ISSUE TITLE
Turn off engine when work is done[Feature]

### ISSUE THREAD

**Issue by meda22** [Courseplay/Courseplay_FS22#1237]
**What is the problem this feature/enhancement solves?**
It is probably a cosmetic thing - but when I play with manual turn on/off engine, worker always leaves engine on when job is done and worker leaves. 

**Describe the solution you'd like**
I would like worker to turn off the engine when job is done and worker leaves (e.g. it is not waiting for unload or something like that).

**Comment by Tensuko** [comment]
Should be already in.
Improovements will come but later.
