### ISSUE TITLE
[BUG] Ballenpressen werden nicht ausgeklappt

### ISSUE THREAD

**Issue by LordNikon83** [Courseplay/Courseplay_FS22#1239]
**Steps to reproduce**
Auf einen generierten kurs schicken.

**Actual behavior**
Die Presse wird nicht aufgeklappt. der pickup senkt sich kann aber nicht sammeln

**Expected behavior**
Das dass gerät aufgeklappt wird und ballen gepresst werden

**Courseplay version**
Version used: 7.0.1.5

**Player on the server**
player unabhängig

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
nf marsch

**Vehicles/ implements involved**
Which vehicle or implement?  Krone big pack 1290 hdp VC
Mod no ?

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Und im SP ?

**Comment by LordNikon83** [comment]
Sp nicht getestet mach ich aber gleich

**Comment by Tensuko** [comment]
Ok, also generelles Problem.

**Comment by Ulanawius** [comment]
Das Problem besteht auch bei der Claas und der Case Presse. Wenn die Presse schon ausgeklappt ist, wird der Kurs normal gestartet (2. Video).

https://user-images.githubusercontent.com/76711921/159141388-3a8f103c-37af-4495-92a3-d024a851a701.mp4

https://user-images.githubusercontent.com/76711921/159141390-7cc28819-052a-47d2-9c1c-b6ff6a29ecec.mp4

.

**Comment by Tensuko** [comment]
Wird generell sein, schauen wir uns an.

**Comment by Tensuko** [comment]
Drive to Fieldwork klappt soweit, aber auf dem Abschnitt wo die Geräte aufgeklappt werden, passiert bei den Ballenpressen nichts.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8311150/log.txt)
