### ISSUE TITLE
Translation_HU

### ISSUE THREAD

**Issue by fuggo2** [Courseplay/Courseplay_FS22#1240]
**Dear Developers**

I would like to ask if if I have "improved and supplemented with new features" an existing translation for CP, is there a chance that it will be included in the basic coding? or would that be a kind of insult to your's current translation colleague? I'm not a programmer, just because a couple of translations were missing, so I started to make them, and for each version I put my own translation in the downloaded CP and add it if there isn't enough text in my language yet. The mentioned language would be Hungarian. 

**Thanks**
fuggo2

**Comment by pvaiko** [comment]
Nem fog senki megsértődni, nem is tudom hirtelen van-e magyar fordítónk, én ami kevés időm erre van azt inkább kódolással töltöm. Szóval nyugodtan, csinálj pull request-et a javításaiddal.

Köszönjük.

**Comment by fuggo2** [comment]
Ez szuper, tényleg először csak magamnak csináltam, de talán egyszerűbb lenne ha nem kellene mindig keresgélnem a fordítandó dolgokat. nem tudom hogy ki fordította valamilyen szinten magyarra de miatta próbálkoztam, mert hiányzott sok dolog. megcsinálom azt a pull requestet ( bár nem tudom miez :D ) , remélem jó lesz

**Comment by pvaiko** [comment]
>  odáig megvagyok hogy eljutok a bejegyzés íráshoz, de az xml fájlt nem tudom beilleszteni.

Ennél sajnos kicsit bonyolultabb, keress rá, először egy forkot kell csinálni, azon módosítani és utána jön a pull request. Nem kell beilleszteni semmit, a giten keresztül működik az egész.

**Comment by fuggo2** [comment]
> > odáig megvagyok hogy eljutok a bejegyzés íráshoz, de az xml fájlt nem tudom beilleszteni.
> 
> Ennél sajnos kicsit bonyolultabb, keress rá, először egy forkot kell csinálni, azon módosítani és utána jön a pull request. Nem kell beilleszteni semmit, a giten keresztül működik az egész.

aha, akkor szerintem maradok magamnak, fogalmam sincs a git működéséről, csak ide járok leszedni az aktuális bétákat.

**Comment by pvaiko** [comment]
https://github.com/Courseplay/Courseplay_FS22/pull/1247
