### ISSUE TITLE
CpAIFrameExtentded 227

### ISSUE THREAD

**Issue by jojo05xx** [Courseplay/Courseplay_FS22#1242]
Ich kann nicht in die Map laden ich bekomme die Fehler Meldung in der log und das spiel läd nicht weiter wie 85%

-Screenshots
![20220319211111_1](https://user-images.githubusercontent.com/58558275/159138925-8eb2c670-fb0c-4d0c-86da-83313f7e8abe.jpg)

-Courseplay version
Version used: 7.0.1.6 and older 

-Map
NF Marsch

Danke für die Hilfe im voraus :)

**Comment by Tensuko** [comment]
Error nicht nachvollziehbar, template nicht benutzt, kein logfile...

**Comment by jojo05xx** [comment]
Wie kriege ich den logfile her ?

**Comment by jojo05xx** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8311099/log.txt)
 das ist meine log datei

**Comment by Tensuko** [comment]
#1245

**Comment by jojo05xx** [comment]
> #1245

Genau so ist es bei mir kann ich schon mal was tun oder gibt es noch keiene Lösung

**Comment by Tensuko** [comment]
Abwarten.
