### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by TheSnakeDoctor67** [Courseplay/Courseplay_FS22#1244]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Play game for more than an hour

**Actual behavior**
A clear and concise description of what happen.
after playing for some time when I attempt to create a course: Click job wheel>VP: Fieldwork>Open Course Generator and I get the attached screen. If I exit the game and reload the saved game it works per normal for 30-60 minutes then repeats.

**Expected behavior**
Normal course generator screen

**Screenshots**

**Courseplay version**
Version used: 7.0.1.5

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. currently Fox Farm but all maps

**Vehicles/ implements involved**
Which vehicle or implement? all
Mod yes/no ? mod or stock equipment

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive
![Farming Simulator 22 Screenshot 2022 02 21 - 18 46 52 46](https://user-images.githubusercontent.com/97072517/159142352-93b48b80-cbe0-4d83-a5e9-e5cfc3bca00d.png)

**Comment by Tensuko** [comment]
Where is the logfile ?

**Comment by TheSnakeDoctor67** [comment]
Sorry thought it was attached, will send it when I get home from work

**Comment by TheSnakeDoctor67** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8319001/log.txt)

**Comment by dominiczeth** [comment]
There are many faulty Mods in your Mod Folder...

**Comment by pvaiko** [comment]
There are many errors in that log, none from Courseplay. Also, the log has no indication of opening the course generator, there should always be an info entry in the log by the field scanner telling the field number and the map.

Reopen if you can reproduce with only CP enabled or you have a log from the time it happened.

**Comment by TheSnakeDoctor67** [comment]
Thanks, I'll check it out.
