### ISSUE TITLE
[Mod conflict/Issue]Nach Absturz, LS nur noch ohne CP startbar

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1245]
**Steps to reproduce**
CP war im Spiel zuvor irgendwie komisch (log leider überschrieben). Alle CP Fahrer sind von ihrem Kurs abgewichen und irgendwo gegen gefahren. Habe (auto) gespeichert und das Spiel beendet. 

Nach Neustart (mit CP) läd der LS nur bis 85% (log angehängt) und bleibt dann stehen. Deaktiviere ich CP, kann ich das Spiel normal starten. 

Hatte das mit v7.0.1.5 auch schon einmal. Da hat es gereicht CP einmal zu deaktivieren, speichern und wieder zu aktivieren.  Das geht jetzt (mit v16) auch nicht. 

Andere Spielstände werden (mit CP aktiv) noch geladen, z.B. Haut-Beyleron

Kann ich meinen Spielstand irgendwie reparieren?

**Courseplay version**
Version used: 7.0.1.15/16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8310777/log.txt)

**Map**
NF mit Gräben

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Es wäre schon interessant, wie das zustande kommt.
Bisher ist mir der Fehler noch nicht über den Weg gelaufen.

**Comment by throsten** [comment]
Ich hab jetzt mal mit den gleichen, aktiven Mods in einer anderen Karte einen Spielstand angelegt um zu schauen, ob es da auch auftritt. Bisher nicht. 

Welche Datei von CP könnte ich löschen, um in der NF Karte wieder mit CP reinzukommen?

Was könnte ich sonst noch machen um zu Helfen?

**Comment by Tensuko** [comment]
Du kannst die Karte mal ohne CP starten, speichern und dann wieder CP dazu packen.

**Comment by throsten** [comment]
Hab ich probiert. Hilft nix. Mit CP bleibt es bei 85% hängen.

Hab es aber anders lösen können, denn mir ist ohne CP (aber alle anderen Mods aktiv) im Menü das hier aufgefallen:
![fsScreen_2022_03_21_18_14_01](https://user-images.githubusercontent.com/96873819/159331081-31c78168-cb0c-4cc3-9619-8136387ac8b7.png)
Die Feldnummern sind alle weg.

Verursacht wurde das durch den Mod: Dynamische Feldpreise. 
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234740&title=fs2022

Wenn ich den rausnehme, stimmen die Anzeigen im Spielmenü wieder und das Spiel lädt auch mit CP. Seltsam ist nur, dass im log der letzte Eintrag auf CP lautet und das Spiel mit dem Preis-Mod zuvor über ne Woche normal lief. Auf einer anderen Karte laufen seit 2 Tagen auch beide parallel. Nehme an, dass es irgendetwas mit der Anzeige oder Reihenfolge im Spielmenü zu tun hat, da beide Mods hier Reiter hinzu fügen. Ist aber nur geraten. 

Wenn es hilft etwas zu verbessern, ok. Sonst bitte schließen, da es anscheinend ein anderer Mod verursacht hat.

**Comment by Tensuko** [comment]
Ach doch der Mod schon wieder.
Dann ist das Mod Issue und hat nichts mit uns zu tun.
Wir können nich immer die einzigen sein, die alles anpassen müssen für andere Mods...

Und ja der Grund wird sein, dass der Mod etwas ändert auf das wir zugreifen.
Muss man halt ohne den Mod klar kommen.
