### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by lutzemai** [Courseplay/Courseplay_FS22#1246]
Mit 7.0.1.6 lassen Maschinen wieder Ecken des Kurses stehen. Bei 7.0.1.5 gab es das Problem nicht.

![grafik](https://user-images.githubusercontent.com/98731693/159155316-439166fd-a329-4446-869c-f0153283bba1.png)

**Comment by Mannie313** [comment]
versuch mal früher absetzen und später anheben.

MFG Mannie313

**Comment by Tensuko** [comment]
Es hat einen Grund warum wir Templates erstellt haben...
