### ISSUE TITLE
version courseplay

### ISSUE THREAD

**Issue by mschaper76** [Courseplay/Courseplay_FS22#1248]
i Just downloaded COURSEPLAY V7.0.1.6 but in the modDesc.xml says its 7.0.1.4 

is there something gone wrong or is this a upload by another party?

**Comment by Tensuko** [comment]
And from where did you download it ?!

**Comment by mschaper76** [comment]
https://farmingsimulator22mods.com/

**Comment by Tensuko** [comment]
Da muss ich mal wieder ganz klar sagen, selber Schuld!
Das sind die absoluten drecks Modklau Seiten schlecht hin!

Es gibt aktuell nur eine einzige offizielle downloadseite und das ist bei uns:
https://github.com/Courseplay/Courseplay_FS22/releases

Dann kriegst du auch die Version die drauf steht.

**Comment by Tensuko** [comment]
Ops. Just did an Issue review, I don't know why I wrote this in german.
Pls stick to our Release only to get the correct Version.
Any page that shows CoursePlay as download and pure scram and mod stealing page.
Except forbidden-mods, wich should lead to GitHub.

**Comment by mschaper76** [comment]
> Ops. Just did an Issue review, I don't know why I wrote this in german. Pls stick to our Release only to get the correct Version. Any page that shows CoursePlay as download and pure scram and mod stealing page. Except forbidden-mods, wich should lead to GitHub.

@Tensuko its ok i can read german and i have now bookmark this page in my browser 
and is there somekind of headsup or waringsignal when there is a new version or must just check the page?
