### ISSUE TITLE
CP and AI Vehicle Extension helper do not work

### ISSUE THREAD

**Issue by BarnyHarz** [Courseplay/Courseplay_FS22#125]
Hello,

while using CoursePlay and AI Vehicle Extension Helper you can´t use Courseplay as your helper. Everytime you start the CP Helper with CP menu it also starts the AI helper and the generated course is ignored. Issue does not occur when AI helper is disabled in the savegame
![fsScreen_2021_12_26_14_05_31](https://user-images.githubusercontent.com/63304301/147409292-ab39911a-a389-40f2-bb3e-8e3463b87049.png)
![fsScreen_2021_12_26_14_18_27](https://user-images.githubusercontent.com/63304301/147409295-eaab085c-7f51-4e9a-8f29-dc955a8e1f43.png)
.

**Comment by Tensuko** [comment]
You can open AIVE Menu on that vehicle and turn it off, then it does work.
