### ISSUE TITLE
[BUG] Seeder no longer works properly

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1252]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
is since version 7.0.1.6 before all good

**Actual behavior**
somehow puts on right after reversing

**Expected behavior**
Should drive neatly backwards as in the versions before and then set on

**Screenshots**
https://youtu.be/fWSA-L_mHbA

**Courseplay version**
Version used: 7.0.1.6

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8311388/log.txt)

**Server Log**
[log Server.txt](https://github.com/Courseplay/Courseplay_FS22/files/8311386/log.Server.txt)

**Player on the server**
4

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Nordfriesische Marsch x4

**Vehicles/ implements involved**
John Deere 6230 R and Amazone Citan 15001-c

Mod no 

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Tested in SP...
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8311638/log.txt)
