### ISSUE TITLE
[Question] MP Problem mit einem neuen Kurs

### ISSUE THREAD

**Issue by Yoshi-01** [Courseplay/Courseplay_FS22#1255]
Hi, wenn ich einen Auftrag mir Courseplay erledige und ich ohne den Helfer (Courseplay) zu stoppen den Auftrag abgebe, beendet der Helfer zwar die Arbeit und es wird auch "Arbeit beendet" angezeigt jedoch kann ich keinen neuen Kurs mehr einstellen. CP im Helfer-Menü war nicht mehr auswählbar. Erst ein Neustart der Map (The French Plain) hat geholfen. Mach ich da was falsch oder muss ich daran denken zuerst den Helfer zu stoppen bevor ich den Auftrag abgebe?

**Comment by Tensuko** [comment]
Kein Plan, logfile ?

**Comment by Yoshi-01** [comment]
Wo/wie kann ich das Log rausziehen? ist ein Dedi-Server

**Comment by Tensuko** [comment]
Unter Einstellungen im Webinterface.

**Comment by Tensuko** [comment]
Closed due to inactivity.
