### ISSUE TITLE
[Feature] Save user vehicle settings(show course) when leaving the server as client.

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1258]
**What is the problem this feature/enhancement solves?**
It would be nice if show course the setting is saved as you set it when you leave the server and do not have to set after each relogg again.

**Describe the solution you'd like**
Settings are saved

**Additional context**
<img width="960" alt="fsScreen_2022_03_21_13_33_05" src="https://user-images.githubusercontent.com/179698/159262101-b0dcc8cf-a99f-4d6e-8132-99a604d44f7e.png">

<img width="960" alt="fsScreen_2022_03_21_13_35_00" src="https://user-images.githubusercontent.com/179698/159262107-e959df84-32f2-45dc-998d-7e7c6c12bd18.png">

https://youtu.be/H84Eq6KupZg

**Comment by Tensuko** [comment]
That setting is saved per vehicle...
