### ISSUE TITLE
Standardhelfer funktioniert nicht in Freie Fahrt / Standard Free Drive is not working 7.0.0.4

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#126]
Ich habe mir gerade das 7.0.0.4 installiert und festgestellt, dass der Standardhelfer nicht mehr funktioniert, wenn das CP aktiviert ist.
wenn ich den normalen Helfer für Freie Fahrt auswähle bleibt das Fahrzeug nur stehen und fährt nicht zum Zielpunkt.

Resume: 7.0.0.4 if CP is activeated Free Drive is not working, vehicle remains on place with activated Helper

**Comment by Tensuko** [comment]
What is the actual message of the game ?
Or does it simply don't do anything ?

**Comment by RealNeo80** [comment]
hmm, just do nothing, but after i restartet FS its working at the moment ... i keep an eye on it

**Comment by RealNeo80** [comment]
Keine weiteren Vorkommnise im Moment
