### ISSUE TITLE
[BUG_SP] Dont drive back to the lane beginning after turning

### ISSUE THREAD

**Issue by Schaemii** [Courseplay/Courseplay_FS22#1262]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
 Deactivate Pathfinder for turning (Pathfinder works like the bug too, but it seems to be "normal")

**Actual behavior**
When your CP-Helper turning/switch the lane he drives forward to stay straight in the lane, lowers the implement and begins

**Expected behavior**
When your CP-Helper turning/switch the lane he drives forward to stay straight in the lane, drives reverse to the lane beginning, lowers the implement and begins

**Screenshots**
https://youtu.be/HDKPfsOzERw

**Courseplay version**
Version used: latest 7.0.1.6

**Log**
https://pastebin.com/yFdhA5w0

**Map**
Elmcreek

**Vehicles/ implements involved**
 JD 8410R, Kockerling Vector 800

**Relevant script mods**
Not active AD

**Comment by Tensuko** [comment]
More fixes for turns incoming. #1252
