### ISSUE TITLE
[InfoFromDev] Help Menu

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#1266]
Hey Folks,

some of you maybe saw this already, we have expanded the ingame help menu by a lot.
Yes that is a lot of work for our translators, we highly appreciate your work.

Some things might not be clear enough, some things you may miss.
Pls let us know in this Issue, so we can add or change things.

But pls keep in mind, that we want to keep it as short as possible, to not have big walls of texts in the help menu.
We can also add more pictures, but for example we don't want to add several course examples.

On Todo:
- [x] Center Modes Spiral and Racetrack, expand the explanation with advantage (low priority)
- [x]  Course manager course saved only localy
- [x]  symetric turn
- [x]  Info Panel
- [ ]  Tips and Tricks section
- [ ]  Turn on Field/Pathfinder turn expand explanation
- [ ] Offset explanation

**Comment by Lactic68** [comment]
Hi,
Yeah that is a nice touch to expand the ingame Help Menu ! I'm working on it right now and I have noticed that one paragraph is repeated on the Course Manager Section
![CourseManagerHelpMenu](https://user-images.githubusercontent.com/70093234/160242943-67e742b5-e570-4b6f-a861-3237b6dc3e89.png)

**Comment by Tensuko** [comment]
Pls let me handle those and not add them in your PR.

**Comment by schwiti6190** [comment]
@Lactic68 Thanks for finding the bug :)
If you could seperate the pull requests next time, that would help us a lot.

**Comment by Lactic68** [comment]
@schwiti6190 @Tensuko Thank you for merging my PR. I understand that you would rather prefer that I submit one PR at a time without mixing corrections outside translations. Sorry if this disturbed you, my intention was of course the opposite :)

**Comment by KCHARRO** [comment]
I have a question: translation_es.xml: line 66 <text name="CP_baleFinder_balesLeftover" text="Bales left:"/>

Are you referring to those that remain to be collected in the field?....

**Comment by budjan** [comment]
i have a question, when i download the courseplay and move it to fs22 mod folder and open the game theres no courseplay mod when i play it, how can i fix it please help me
