### ISSUE TITLE
Required improvement of the entry curve after laps around the court

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#127]
Hi. I would like to ask for an improvement for the first corner after the laps of the field. the vehicle comes out of the field with the risk of damaging the crop.
There are 2 courses the first concerns field 45 while the second is not complete. I was trying if the anomaly came out but without success. [https://pastebin.com/ivNmrw99](https://pastebin.com/ivNmrw99)
The tool keeps it on the ground while the other turns up and down I have not noticed anything strange.

[CoursesField45.zip](https://github.com/Courseplay/Courseplay_FS22/files/7777110/CoursesField45.zip)

![fsScreen_2021_12_26_15_14_17](https://user-images.githubusercontent.com/96330304/147411357-a1a50e14-0b1c-4d51-b48e-f81deb2141b6.png)

If you want game save folder, please let me know.

**Comment by Tensuko** [comment]
Turn on Field is active ?

**Comment by Markus33-ITA** [comment]
Is active. For the sake of scruple I went to check and it is active.
![fsScreen_2021_12_26_18_24_36](https://user-images.githubusercontent.com/96330304/147415798-e81f9138-e88d-4887-a71f-3817db0b44cf.png)

**Comment by Tensuko** [comment]
Ok we check what we can do about this.

**Comment by Markus33-ITA** [comment]
Ok. Thank you

**Comment by rohne83** [comment]
Just a thought: not sure what the turning radius of the tractor, and work width of the implement are. But might be that it would only be possible to stay on field if driving backwards? Don't know whether entry into first field row allows reversing at all currently.

**Comment by Tensuko** [comment]
The turn is made more simple here.
Just an improovement so the corner won't be unworked.
We check that later.

**Comment by Tensuko** [comment]
We have another approach to this now and start the turn earlier on the connection track.
You may try out and report if that does work for you.

**Comment by Tensuko** [comment]
This got improovet already and even gets a 2nd review. Closing this.
