### ISSUE TITLE
[Question]Reben/oliven Bahnwechsel symetrisch/asymetrisch?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1270]
Hallo Cp
ich probiere gerade den rebenkurs aus, mit dem Blattschneider
da ich stirnseitig weniger platz habe für eine Bogenwende (ist das aucheine 3-zug-wende geplant) habe ich mich für 4 Geräte auf dem kurs entschieden, die ich nacheinander mit einem Gerät abfahre.
leider überspringt cp auf einer seite 7 reihen, auf der anderen dafür gleich die nächste:
![fsScreen_2022_03_24_09_19_11](https://user-images.githubusercontent.com/24860501/159873463-99588788-6732-4f6d-b25f-157957e4a391.png)
![fsScreen_2022_03_24_09_20_02](https://user-images.githubusercontent.com/24860501/159873468-e26d44db-3ff6-4b49-b741-743ddb465c4c.png)
und das geht sich dann mit der Bogenwende nicht aus.
kommt der symetrische/asymetrische Bahnwechsel da noch zum zug?
![fsScreen_2022_03_24_09_25_25](https://user-images.githubusercontent.com/24860501/159873726-53ae8910-2136-4acc-839c-2150289b7d14.png)

lg
andreas

**Comment by Tensuko** [comment]
Bitte halte dich vorerst an die angaben im Hilfemenü.

**Comment by andreasthu** [comment]
Ja, aber die Funktion "Reben überspringen" ist fürs Düngen, jede 2. Zeile oder so.
Habe die anleitung in google translate übersetzt, und hab das so verstanden.
Lg
Andreas

**Comment by Tensuko** [comment]
Das Problem ist Multitool.
Das ist was anderes als Reben überspringen.
Es ist eben etwas komplizierter und nicht alle kombinationen sind einfach möglich.

Man braucht nun mal Platz für einige Tools.
Wir werden das System aber nicht von heute auf morgen komplett aufbohren.
Es ist die erste Version und die wird so in das Release kommen mit entsprechenden Hinweis auf das Hilfe Menü.

Um enger zu wenden müssten wir sher komplex viel umbauen und das wollen wir nicht.
