### ISSUE TITLE
[BUG_SP]  Vehicle backing up too far off the edge of the field

### ISSUE THREAD

**Issue by sootysax** [Courseplay/Courseplay_FS22#1272]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Course generated with 1 headland, pick up cultivator set to early, lower tools set to late, turn only in-fields activated

**Actual behavior**
The vehicle is backing up way outside of the field, crashing into a fence and quitting the course.

**Expected behavior**
Turn in field is set to on, lower tools set to late..  I feel the vehicle is pulling forward and then backing up too far and should lower the tool when the back of the cultivator reaches the edge of the field

**Screenshots**
![Screenshot 2022-03-24 08 11 47](https://user-images.githubusercontent.com/6591048/159914221-c9aadc7f-672c-4919-83c6-b943a0354823.png)

![Screenshot 2022-03-24 08 10 06](https://user-images.githubusercontent.com/6591048/159914310-303f8f6d-49a4-42bf-87fc-351c34c8fe02.png)

**Courseplay version**
Version used: 7.0.1.7

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8341339/log.txt)

**Map**
Elsdorf 1.0

**Vehicles/ implements involved**
Which vehicle or implement?  JD 310 with Lemken Koralin 9 Cultivator
Mod yes/no ?
no

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pvaiko** [comment]
For the record, this is because of the weight attached to the front, we changed the AI marker logic for the all those grape tools/vehicles which don't seem to have a work area.

**Comment by Bartosz1234567** [comment]
In my save in "Hobo' s Farm"  Cworker drive back maybe 100m out field
