### ISSUE TITLE
[Feature]Vines routes

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#1274]
It would be useful to increase the number of row skips from 1, at least to 2. given that there are modded tools, for example the fertilizer sprayer, they have a working radius of more than 3 meters (6 meters total) they can reach 9 meters, therefore by setting 2, in the row jump, it would work correctly.

**Comment by Tensuko** [comment]
We want to keep it basic for now, sry.
Maybe later.
