### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by ltheoret** [Courseplay/Courseplay_FS22#1279]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki - done

**Steps to reproduce**
Steps to reproduce the behavior. create a courseplay course on any field the is not square and has inside corner or concave side.

**Actual behavior**
A clear and concise description of what happen. courseplay gladly plots a course off the field from one side to the other of the concave side or inside corner.

        +-----+ Example field shape courseplay will go off the field and go into obstacles on side of field to get from one 
         |         |  path from the left of the inside corner to the right.
+----+        |
|                  |
+-----------+

**Expected behavior**
A clear and concise description of what you expected to happen. the tractor or equipment will drive off the field into obstacles

**Screenshots**
If applicable, add screenshots to help explain your problem. course goes off field onto a highway surrounded by trees.
![image](https://user-images.githubusercontent.com/20023622/160047239-ffedb8b3-51a4-430c-b0c5-233c623106b6.png)

**Courseplay version**
Version used: 1.0.7.1

**Log**
Please attach a log with all debug channels active. n/a
For help with the debug channels,
please check out the readme at the github front page. 

**Map**
Map played on. Wild West by CAZZ64

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? any in game, pick one

**Relevant script mods**
Mods like Autodrive or VCA and so on. n/a

**Comment by Tensuko** [comment]
Not a bug, just a connection.
Pathfinder will take care of that and, more headland will solve that too.
