### ISSUE TITLE
[Question] Cotton Bale Loader

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#1280]
Not sure if this is a bug, or just something you haven't got to work on yet.

So I was doing a cotton harvest, using the a semi with the Lizard Module X Semi bale loader.  When I activated the collecting/wrapping bales function, it drives to the bale like it is a side loading bale trailer, when it is a rear loading.  Although it fun to watching do circles around the bale, it gets old after about the third time.  So, my question is, are you planning on implementing CP to collect bales with the Module X Semi trailer?

Also, I assuming it would be the same issue with the Lizard Module 4 trailer to, since it looks like it is rear loading too.  The McCormack Industries Cotton Tag Trailer looks to be a side loading trailer, so I would assume that one will work with CP, but that limits having to use the more expensive JD CP690 harvester that does round bales, where the Module 4 and Module X will accept both the square or round bales from either cotton harvester in the base game.

**Comment by Tensuko** [comment]
I am not sure if I know what you talk about.
Screenshot ?

**Comment by dominiczeth** [comment]
I know what he means. These two trailers can only load it when you drive backwards. 
![2022-03-25 08_50_21-Offizielle Webseite _ Landwirtschafts-Simulator](https://user-images.githubusercontent.com/18227603/160078429-e0eb175b-a462-4110-be94-a1bcd3e09e84.png)
![2022-03-25 08_50_14-Offizielle Webseite _ Landwirtschafts-Simulator](https://user-images.githubusercontent.com/18227603/160078445-efb7d59f-72d9-4805-a8f1-d8190f22ece6.png)

But courseplay can't load backwards at the moment. (And i think this won't be an easy fix)

**Comment by Tensuko** [comment]
Won't fix. Sry.
