### ISSUE TITLE
[BUG_SP] additional blue border with courseplay verison 

### ISSUE THREAD

**Issue by Wobby1** [Courseplay/Courseplay_FS22#1286]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
hole using standard
**Actual behavior**
A clear and concise description of what happen.
it will show an  "Coursplay blue Border" additional to the normaly Hud
**Expected behavior**

**Screenshots**
![CoursePlay](https://user-images.githubusercontent.com/102374114/160150767-acc9272e-252d-47c2-bebc-6643a8efcd02.jpg)

**Courseplay version**
Version used: v7.0.1.7

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Beyleron v1.1
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by regs1980** [comment]
This is the info text display
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.0.1.5

**Comment by Wobby1** [comment]
sorry but by me it has no functions. If i click on it it do nothing and furthermore it has no informations in it ..
It is only a blue banner wich shows " Courseplay v7.0.1.7"

**Comment by TobiHH78** [comment]
It has a function. It shows when a job is finished, a vehicle is blocked or some other informations, but of course only when the situation happens.

You can deactivate it in the settings if you don`t need it.

**Comment by Wobby1** [comment]
O.k thank you very much for this ! I will try it again
