### ISSUE TITLE
[Question] CP Helfer wartet nicht bis Gerät vollständig ausgeklappt ist

### ISSUE THREAD

**Issue by Holzotte** [Courseplay/Courseplay_FS22#1287]
Hi,

wenn man die Dalbo 2450 Walze in Verbindung mit dem CP Helfer einsetzt, wartet er nicht am ersten startpunkt bis die Walze vollständig ausgeklappt ist, sonder fährt sofort weiter auf dem Kurs und klappt wärendessen die Walze weiter aus was dazu führt das das Feld nicht komplett gewalzt wird.

**Comment by Tensuko** [comment]
#1206
Und was macht der Giants Helfer mit der Walze ?

**Comment by Holzotte** [comment]
sofort ausprobiert, er macht das selbe
