### ISSUE TITLE
[BUG_SP] Vineharvester stucked at start of next vines row when one is skipped

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#1292]
**Steps to reproduce**
1. With a Vineharvester and a 3 rows vineyard on Elmcreek (field 26)
2. Position set to on and skipped row to 1
3. Start at first point
4. First raw is OK
5. Turning radius is OK
6. Harvester miss only a few millimeters the correct position of the third row and is stucked

**Actual behavior**
Harvester is stucked. I also tried with vineyard ready to harvest (same result)
The 3 lines vineyard are created with the correct tool grid.

**Expected behavior**
No bump or stuck

**Screenshots**
The VineHarvester will be stucked approximately at the point 31.
![2022-03-26_19-46-58](https://user-images.githubusercontent.com/70093234/160253500-70c53229-7773-4158-a5bb-72a79bc71a95.png)

**Courseplay version**
Version used: 7.0.1.7

**Log**
[log-VineHarvestStucked.txt](https://github.com/Courseplay/Courseplay_FS22/files/8356175/log-VineHarvestStucked.txt)

**Map**
Elmcreek vanilla

**Vehicles/ implements involved**
Braud VineHarvester

**Relevant script mods**
Autodrive, Pro Shot, Tardis

**Comment by Tensuko** [comment]
Skip rows is not made for this.
Skip means rly skip and not work on them at all.
On our tests there was no stuck of the Harvester.

**Comment by Lactic68** [comment]
Same issue even without any skipped rows.
Log Attached : 
[log-VineHarvestStucked-WithoutSkipRow.txt](https://github.com/Courseplay/Courseplay_FS22/files/8357156/log-VineHarvestStucked-WithoutSkipRow.txt)

Vineharvester is stucked at the start of newt row

![2022-03-27_09-56-27](https://user-images.githubusercontent.com/70093234/160272500-96c7911a-f81f-4edc-b2df-ba60b4a9e73d.png)

**Comment by Lactic68** [comment]
I just have tried from the #1122 branch

**Comment by Tensuko** [comment]
Yea but it seems to not work correct.
Depending on the vines, it might do a 3 point turn and gets stucked.
Not sure if I have to increse the Radius again but I wanted to keep it slim.
