### ISSUE TITLE
[BUG_SP] Work  only on headland

### ISSUE THREAD

**Issue by zalankin** [Courseplay/Courseplay_FS22#1293]
I can’t choose to have the machine start the job in the center of the field. Only on the headland.
the game writes is missing it : 'CP_job_filedwork' in l10n_hu.xml
**Courseplay version**
Version used:  v7.0.1.7

**Comment by Tensuko** [comment]
The option should be there anyway, when it is just the translation.

**Comment by zalankin** [comment]
The option isn't there, that's why I wrote it.

**Comment by Tensuko** [comment]
logfile ?!

**Comment by pvaiko** [comment]
Fixed in b7fdf87e66f0a2f187769ebf473cc86a490ea89d with many other translation fixes.

> I can’t choose to have the machine start the job in the center of the field. Only on the headland.

Actually, you can, if you just click once it'll change to the center and generate correctly, only the text in the selection box is the same.
