### ISSUE TITLE
[BUG_SP] samson agrar us235 falsche Arbeitsbreite

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1299]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Generieren sie einen feldkurs mit dem Samson agrar us235 Miststreuer
**Actual behavior**
A clear and concise description of what happen.
Die automatische arbeitsbreite wird mit 12m berechnet.
**Expected behavior**
Der miststreuer hat aber 24m Arbeitsbreite. Ev berechnet cp die weite von workareastart bis workareawidth, miststreuer haben start aber bei x null, width bei 12 und height bei -12 ( jetzt beim eu235).
**Screenshots**

**Courseplay version**
Version used: 
7.0.1.7
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Haute Beyleron
**Vehicles/ implements involved**
Which vehicle or implement? Samson agrar EU235
Mod yes/no ? No

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Lg
Andreas

**Comment by Tensuko** [comment]
Vanilla ?

**Comment by andreasthu** [comment]
Ja der vanilla us235 streuer mit dem nh t8 traktor.
12m arbeitsbreite wird automatisch eingestellt.
Lg
Andreas

**Comment by Tensuko** [comment]
Hm okay schau ich mir an.

**Comment by andreasthu** [comment]
?
den kann man ja nur bei Reifen oder Kennzeichen konfigurieren.
arbeitsbreite hat der nur 24m.
auf deinem screenshot berechnet cp ja auch "nur" 12m.
sieht man da ja im cp-hud links unten.
lg
andreas

**Comment by Tensuko** [comment]
Den Miststreuer vlt nicht, aber der andere Brantner wo die Arbeitsbreite von der Config abhängig ist, desshalb ist das eine reine Information für dieses Issue damit diese Information irgendwo aufgeschrieben steht.

**Comment by andreasthu** [comment]
Ok, danke
Lg
Andreas
