### ISSUE TITLE
Krone Big X not harvesting.

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#130]
I just downloaded version 7.0.0.5, generated a course for my  Big X to harvest.  when I start the helper, it moves a meter, stops, clears the head, moves another meter, clears the head.  It does it 5 to 10 times, then stops completely, where I have to stop the helper and start it over.  When using version 7.0.0.4, it ran fine, but the speed was limited to 3 mph. I am using AD unloader, but when I turn off AD for my unloaders and attempt to drive the unloaders myself, it does the same thing.  When I drive the Big X myself with AD unloader, I have no issues.    

Log File
https://pastebin.com/yFbVyNJM

**Comment by Tensuko** [comment]
Can confirm this with 7.0.0.5 I wonder why the pipe does find the trailer, but he does not start....
![fsScreen_2021_12_26_19_28_10](https://user-images.githubusercontent.com/27344744/147416974-84cb1e1f-fa70-4478-83d9-099440c43564.png)
![fsScreen_2021_12_26_19_04_37](https://user-images.githubusercontent.com/27344744/147416976-266ed89b-537c-420f-91b4-dec8fed4baa7.png)

**Comment by svencorell** [comment]
same here with John Deere pendant... And I also can confirm the same issue with the Krone.

**Comment by Resandise** [comment]
Confirmed fixed as of 7.0.0.7
