### ISSUE TITLE
[BUG_MP] Mitspieler sieht meine gespeicherten Kurse nicht

### ISSUE THREAD

**Issue by Toggrim** [Courseplay/Courseplay_FS22#1302]
Hallo, mir ist aufgefallen das gespeicherte Kurse nur von dem sichtbar sind der diese Gespeichert hat. Mein Mitspieler sieht diese nicht und ich sehe auch seine gespeicherten nicht.
Wir spielen auf einem Dedi Server.

**Comment by Tensuko** [comment]
Das ist richtig weil die Kurse aktuell nur lokal gespeichert werden.
