### ISSUE TITLE
Debug abschlten. schreibt die log voll[Question]

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/Courseplay_FS22#1304]
Hallo CP Team. könnte man bitte die debug abschalten. meine log ist mittlerweile auf 5.13 MB angestiegen.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8374544/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Und das problem daran ist was ?
Festplatte voll ?
Sry aber das wird erst später gemacht.
Dem spielt juckt das nicht und wenn ich etwas debugge für länger mit allem an wird die log auch schon mal 200 MB groß.
Spiel Neustart macht eh immer ein clear der log.

Abwarten und Tee trinken.
Debug ist nun mal wichtig für die .dev Version.
