### ISSUE TITLE
[BUG_SP]Geometrie-Rechteck sitzt falsch auf den gezogenen Pflügen.

### ISSUE THREAD

**Issue by WernerWusel** [Courseplay/Courseplay_FS22#1307]
**Steps to reproduce**
Mit einem beliebigen Traktor und einem der Pflüge ein Feld bearbeiten. Egal welche Map.

**Actual behavior**
Das "Geometrierechteck", welches die Pflüge zur programmtechnischen Bearbeitung (internen) Darstellen, liegt falsch auf den Pflügen. Aus den Screenshots ist klar ersichtlich, dass das obere Ende des Pfluges korrekt im Rechteck (in einer Ecke) liegt. Das untere Ende des Pfluges liegt in der Mitte des Rechtecks. Das führt beim Zurücksetzen des Pfluges dazu, das dieser nach rechts verschoben wird. Beim anschließenden geradeaus Fahren ist dieser Umstand egal.
Das Rechteck wird korrekt zurück geschoben, der Pflug nicht, da die Räder des Pfluges im Winkel zum Rechteck stehen.

**Expected behavior**
Das Rechteck muss korrekt positioniert werden, dann klappts auch mit dem Zurücksetzen der Pflüge.

**Screenshots**
Das fehlerhafte Rechteck.
![20220325222610_1](https://user-images.githubusercontent.com/102391757/161227287-24ea7fdb-b3c4-4065-9295-9b2683d8e376.jpg)
![20220325223132_1](https://user-images.githubusercontent.com/102391757/161227497-1050beb7-a485-4b48-a08c-9aec3b0d2d5f.jpg)

Das gleiche beim 2ten Pflug.
![20220319142108_1](https://user-images.githubusercontent.com/102391757/161227778-065c4b58-94eb-4d47-8bfa-f3063b61f84a.jpg)

Wenn der Pflug gedreht ist, ist es auch falsch.
![20220319175622_1](https://user-images.githubusercontent.com/102391757/161228364-2b0d43d0-000b-4620-9fd9-92c3c0153ffb.jpg)
So sieht es aus wenn der Pflug gezogen wird. Ein schiefes Rechteck.
![20220310215041_1](https://user-images.githubusercontent.com/102391757/161228636-36c136d4-3b79-4fa5-bb31-ec20e0498be4.jpg)
Das ist, unter anderem, das Ergebnis.
![20220325234128_1](https://user-images.githubusercontent.com/102391757/161229082-82c924fc-a0bf-4088-8939-850bb09da6c3.jpg)

**Courseplay version**
Version used: 7.0.1.7
Dieser Fehler ist aber Versionsunabhängig und seit dem es diese Pflüge gibt vorhanden.

**Map**
Jede Map. Nichts spezielles.

**Vehicles/ implements involved**
Der blaue Pflug: LEMKEN Titan 18
Der rote Pflug:  Kverneland PW 100-12

Mod yes/no ?
Ja.

**Relevant script mods**
AD, VCA, und div. andere.

**Bemerkung**
Das Rechteck wird nicht von mir zur Anzeige gebracht (durch irgend eine Tätigkeit) sondern erscheint zufällig irgendwo auf dem Feld beim Arbeiten. Anscheinend merkt ein Programm, das hier etwas Faul ist.
Meine Frage aus Interesse: Wer Erzeugt dieses Rechteck und wer legt es auf den Pflug bzw. auf die Arbeitsgeräte, da ja jedes Tool so ein Rechteck besitzt.

**Comment by pvaiko** [comment]
Das Rechteck ist schräg weil es auf dem Root Node des Pfluges sitzt. Root Node kannst mit Giants Debug Vehicle Attributes sehen.

Vergiss das Rechteck bitte. Was ist das eigentliche Problem?

**Comment by WernerWusel** [comment]
Das Problem ist, dass die Pflüge nicht gerade zurück geschoben werden, sondern nach Rechts versetzt. Beim weiter fahren in der neuen Bahn muss der Pflug aus der falsch Position schräg in die neue Bahn gezogen werden. Das führt, wie in Bild 6 zu erkennen ist, zu unbearbeiteten Fehlstellen im Feld.
Das Rechteck ist aber ein gute Indikator für das Rückwärtsfahren. Wie in Bild 3 zu erkennen ist, wird das Rechteck parallel zum Feldrand geschoben, die Räder vom Pflug stehen aber im Winkel zum Rechteck und Feldrand. Daher das schieben nach Rechts.

**Comment by Tensuko** [comment]
Desshalb ist noch lange nicht die Lösung, dass das Rechteck falsch sitzt.
Das hat damit nichts zu tun.

**Comment by pvaiko** [comment]
Ich glaube was @Tensuko sagen wollte ist dass der Pflug dürfte gar nicht rückwärts fahren, das müssen wir noch konfigurieren.
