### ISSUE TITLE
[BUG_SP]Zu enger Wendekreis bei gezogenen Pflügen

### ISSUE THREAD

**Issue by WernerWusel** [Courseplay/Courseplay_FS22#1308]
**Steps to reproduce**
Mit einem beliebigen Traktor und einem der Pflüge auf einem beliebigen Feld pflügen. Warten bis die Spur zu Ende ist und der U-Turn beginnt. Wenn der Pflug nach Rechts gedreht ist und der U-Turn nach Rechts ausgeführt wird, kann man das Problem sehen. Wenn nach Links gedreht wird, dann nicht :)

**Actual behavior**
Die Pflüge haben in der Nähe der Traktorbefestigung ein Stützrad, welches mit dem Pflug gedreht wird (links - rechts). Nur wenn der U-Turn in die aktuelle Bearbeitungsrichtung ausgeführt wird und der Wendekreis zu klein ist, kommt es zur Blockade des Traktorrades auf der Seite des Stützrades vom Pflug (sieht man besser auf den Screenshots).
Der Witz nebenbei: Das "Blockierte Rad" dreht durch (obwohl Blockiert) und das andere, freie Rad, dreht sich normal. Sollte physikalisch eigentlich umgekehrt sein ;)

**Expected behavior**
Am Ende der Bahn, bevor ein U-Turn durchgeführt wird (in welche Richtung auch immer) den Pflug in die Mittelstellung (Taste B) bringen, dann den U-Turn durchführen und danach den Pflug in die Arbeitsstellung drehen (Taste B).

**Screenshots**
Der Pflug ist nach links gedreht, das Stützrad zeigt nach links und der Turn geht nach Rechts. Kein Problem mit den Wendekreis.
![20220326012935_1](https://user-images.githubusercontent.com/102391757/161242360-726b9583-0ab8-48ba-a7c5-2979a2c235f9.jpg)
Der Pflug ist nach Rechts gedreht, das Stützrad zeigt nach Rechts. Dadurch ist das rechte Hinterrad des Traktors schon bedenklich Nahe am Stützrad.
![20220326022825_1](https://user-images.githubusercontent.com/102391757/161242754-64cbd21c-c61c-48fa-9638-00cc0ee5dff5.jpg)
Der Einlenkradius ist relativ gering, aber das rechte Hinterrad des Traktors wird durch die Aufhängung der Stützrades blockiert.
![20220326030330_1](https://user-images.githubusercontent.com/102391757/161243172-05c5b3e7-50ec-44e3-96e1-4b5120460b34.jpg)

**Courseplay version**
Version used: 7.0.1.7
Gilt aber für alle Versionen.

**Vehicles/ implements involved**
LEMKEN Titan 18
Kverneland PW100-12

**Relevant script mods**
AD, VCA etc.

**Comment by WernerWusel** [comment]
@Tensuko wäre es nicht eleganter, wenn man, statt den Radius zu vergrößern, den Pflug in Mittelstellung bringt und zwar sofort wenn eine Bahn beendet wurde. Der Pflug muss sowieso gedreht werden, egal in welche Richtung und das geht immer über die Mittelstellung.

**Comment by Tensuko** [comment]
Nein.
