### ISSUE TITLE
problem with DALBO MEGA ROLL 2430[BUG_SP]

### ISSUE THREAD

**Issue by ontot** [Courseplay/Courseplay_FS22#1309]
even with this DALBO MEGA ROLL 2430 the cp does not wait for the opening and leaves a lot of unworked space.

**Comment by Tensuko** [comment]
Becouse this was discussed many times already.

**Comment by ontot** [comment]
Ah OK. sorry, but i didn't know. but what is the solution then? ... we have to wait for the next version?

**Comment by Tensuko** [comment]
We have to look at the tool, not sure why we don't wait for unfold, but since it is just "unfold it and start" it is nothing big.
