### ISSUE TITLE
7.0.0.5 Helper says finished job, but did nothing

### ISSUE THREAD

**Issue by TheSoldier91** [Courseplay/Courseplay_FS22#131]
Everytime i try to start a new job with the helper he says finished but only unfold the tool.
Normal working working neither.

**Comment by dominiczeth** [comment]
Please post log and test with original implements

**Comment by TheSoldier91** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777311/log.txt)

Tested on Elmcreek owned Field 43, original JD7810 and Köckerling Egge

Generated a course and hit start.

He drives to the starting point, unfolds, then stops with finished message

**Comment by Tensuko** [comment]
Do you have tested if you can use the tool with the Giants Helper ?
That msg mostly comes up if you can't use the tool on that field, becourse of the field state.

**Comment by TheSoldier91** [comment]
Yes, i've tried it with a spreader filled with fertilizer.
Manually - works fine
Giants Helper - didnt work
AIVE - didnt work
CP -  didnt work

Same result with köckinger Kreiselegge

Own field or field from a Mission, no difference

**Comment by TheSoldier91** [comment]
Yes, i've tried it with a spreader filled with fertilizer.
Manually - works fine
Giants Helper - didnt work
AIVE - didnt work
CP -  didnt work

Same result with köckinger Kreiselegge

Own field or field from a Mission, no difference
