### ISSUE TITLE
[BUG_SP] Notification HUD is not hidden if gsHudVisibility 0

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1312]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Activate the console and execute the command "gsHudVisibility 0"

**Actual behavior**
All HUD will be disabled (Courseplay, Autodrive, base game HUDs) except the Courseplay notification HUD

**Expected behavior**
 Courseplay notification HUD is hidden too

**Screenshots**
![image](https://user-images.githubusercontent.com/96819380/161382393-15657c0d-a7a3-49ff-a057-490574e32f82.png)

**Courseplay version**
Version used: 7.0.1.8

**Log**
https://gist.github.com/alexx2104/8be7503da2c023d4b75530b34eaa8984

**Map**
NF Marsch 4fach ohne Gräben

**Vehicles/ implements involved**
N/A

**Relevant script mods**
N/A

**Comment by Ulanawius** [comment]
Same behaviour when using the mod "HUD Toggle" from FS22 ModHub.
