### ISSUE TITLE
[Feature] Symmetric lane change should be a job parameter as it works similar to the laneoffset setting.

### ISSUE THREAD

**Issue by hell2o** [Courseplay/Courseplay_FS22#1313]
**What is the problem this feature/enhancement solves?**
Currently Symmetric lane change is set per vehicle, this causes conflicts when different vehicles on the same course have different settings. Unless I'm missing something being able to set it per vehicle only creates issues and gives no useful control over it being set per course.

**Describe the solution you'd like**
Symmetric lane change setting is defined in the course generation settings, instead of in the vehicles settings.

**Describe alternatives you've considered**
It could also be moved to a global setting but that gives a lot less control.

**Comment by Tensuko** [comment]
No it is not, since this is nothing based on the generator, but on the vehicle driving.
Won't change this.

**Comment by hell2o** [comment]
Okay, but my point isn't about where it is utilized in the code, but instead how it is used by players.

It seems to me more likely that a user would just want all the vehicles driving a course to use the same setting, rather than having to change it per vehicle every time they assign them to a new course.

There might be some use case that I'm not aware of but it seems that this behaviour would always be more desirable.

**Comment by Tensuko** [comment]
Same Problem.
How to tell wich Vehicle should change the setting -> only in the vehicle setting page.

**Comment by hell2o** [comment]
What do you mean?

The vehicle can tell which course it's on right? 
So the lane mode would be saved with the course in the same way that number of tools or work width is.

**Comment by schwiti6190** [comment]
@hell2o Hi there,
Your right as the settings is linked to the course, but only gets applied once the course is started. This enables the possibility to use the course with activated/deactivated setting. From a programmatically stand point this setting shoud be a job parameter. 
The problem would be the integration in the hud at the moment, so we might re visit this idea at a later time :)

**Comment by Tensuko** [comment]
> So the lane mode would be saved with the course in the same way that number of tools or work width is.

No!
As you can use the same course for different Vehicles + Tools, it depends on the Tool and not on the course.
It is a vehicle setting for some reasons and stays as a vehicle setting.

**Comment by hell2o** [comment]
I'm not sure what you mean.

Also I realised I had mistyped when writing the description and title, writing simultaneous when I should have written symmetric, I have corrected this.

**Comment by Tensuko** [comment]
I knew what you mean.
But our disicion to this is clear now and we won't change anything.
Reason:
That setting is purely based on the vehicle and have nothing to do with the course type.
Should never be global as you can run your tools on courses in a different way and should also not be automatic set for all tools on the same course.

It is simply just to have tools work lane by lange (e.g. from left to right and now have a lane skipped) wich leads into the possibilty that they hit each other.
If don't want that have them run as default and the lane will be kinda "skipped".
So they will never have their lanes next to each other.

Topic closed.
