### ISSUE TITLE
Copy Other Courses without saving

### ISSUE THREAD

**Issue by Skipper-is** [Courseplay/Courseplay_FS22#1315]
**What is the problem this feature/enhancement solves?**
When you wish to use an existing course with another implement (eg, the baler follows the rake) with a different vehicle, you have to save the course first, then load it with the other vehicle. Would be good if you could just copy the other vehicles temporary track straight over (like in FS19)

**Describe the solution you'd like**
Ability to copy another track. It could be in the saved tracks location - just a temporary 'save' of all the other vehicles currently with tracks.

**Describe alternatives you've considered**
Saving and Loading the track for a specific field, for a specific piece of machinery. It gets unwieldly quickly.

**Comment by Resandise** [comment]
This would be handy, not only for a baler following a Combine, baler behind a windrow, but also being able to copy over for Multi tool courses to all vehicles that you want to use on the course without saving the course.
