### ISSUE TITLE
[BUG_SP] Corn Chopper doesnt work with Autodrive

### ISSUE THREAD

**Issue by svensigi** [Courseplay/Courseplay_FS22#1319]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
When chopping corn, the Autodrive driver always drives into the chopper. This is new in recent versions, and Courseplay always gives the first order to follow the thresher behind. The pipe also selects the trailer, but the Courseplay chopper does not move. The Giants helper works perfectly. Maybe something is programmed with the distance too short from the pipe, the cheapest Claas is with the largest cutterbar.

**Expected behavior**
Turning the Chopper, then follows direct to the sides if enough space. 

**Screenshots**

**Courseplay version**
Version used: 7.0.1.9

**Comment by Tensuko** [comment]
And why is it a CP bug and not AD if AD drives to close ?
Did you check the Distance in AD ?

We only Drive the Chopper, nothing more...

**Comment by svensigi** [comment]
Distances are ok. i think its a CP bug, because it works with the Giants helper. 
But maybe its both, CP and AD
