### ISSUE TITLE
Combine crashing field 

### ISSUE THREAD

**Issue by Andystrong8484** [Courseplay/Courseplay_FS22#132]
Noticed this when combining and as he finishes the field game crashes

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777236/log.txt)

**Comment by Tensuko** [comment]
Tested this with 7.0.0.5 and I can't reproduce this.
You also have a callstack in your logfile long time before courseplay Error.
Pls fix your broken mods 1st and also install newest Patch of FS Version: 1.2.0.0 b14651
