### ISSUE TITLE
[Enhancement] Proximity Sensor reacts to unloader on connection track.

### ISSUE THREAD

**Issue by VJH01** [Courseplay/Courseplay_FS22#1320]
**Steps to reproduce**
Fieldcourse with Headlands, Chopper and tractor with trailer

**Actual behavior**
If the Krone use the Headland to get to the next row, he will only drive 2-5km/h. The Tractor and Trailer is sidewards to the Krone. Makes no difference if the tractor is driven bei AD or by hand. If you slow down the tractor an go behind the Krone he will speed up to 20km/h.

**Expected behavior**
Krone drives >20km/h with Tractor on his side, when he uses the headlnd without cutting.

**Screenshots**
![image](https://user-images.githubusercontent.com/96574322/161446317-a74ef609-dc0d-4641-a120-b7074a116bb8.png)

**Courseplay version**
Version used: 7.0.1.9

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8410677/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Krone 1180 with 9m cutter

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
I hope that attached picture of your log.txt is just a joke...

**Comment by pvaiko** [comment]
We can certainly deactivate the proximity sensor for certain vehicles, but please help me to put together a list of conditions on when exactly should it be deactivated (and won't result in other folks complaining about collisions).

**Comment by VJH01** [comment]
I updated the log, sorry for the mistake.

Maybe there is a third option, you can tell the AD Driver to wait at the beginning of the relocation. So you don't have to switch the sensor off.

**Comment by rohne83** [comment]
Or just less sensitivity? Right now the harvester slows down as soon as there's anything within 2m distance from the header. This will create huge headaches with the realistic modmaps where you have dozens of obstacles close to the field edge (but still clearly outside without any risk of collision). And already creates with unloaders. Not only when chopping, but also everytime I approach or leave a combine with the auger wagon it slows down to just 2kph due to this proximity sensor.
I think it should rather ignore everything which is more than 1 meter away. This should help for most maps and also for this issue here.

**Comment by Tensuko** [comment]
The sensitivity got to stay like that.
The sensor was implemented for a specific reason and reacts correctly for the problem.
As said, when to ignore something.
There are better solutions.

The sensor is off while discharging, should not be a problem when activly unloading the combine or chopper.

**Comment by rohne83** [comment]
Not during discharge, but directly before and thereafter when unloader is still next to the harvester (approaching or driving off) it initiates those harsh slow downs as well.
Where in code can I deactivate it then for myself? It's definitely a nice idea, but with current implementation I still fail to imagine situations where it would really prevent any issues. With its wide view and zero tolerance it's rather causing lots of headaches currently. Even a fence placed 1.5m away from the field edge (which is really far away for a fence, we will see dozens of modmaps with obstacles much closer) will still cause the worker to pass it with just 2kph all the way...

**Comment by pvaiko** [comment]
The easiest is probably set these all to 0 so they all look forward:
https://github.com/Courseplay/Courseplay_FS22/blob/98dcdcc6842766d88398e4c5a73ee16de5d521ac/scripts/ai/ProximitySensor.lua#L304

I'm open to suggestions to make it better. I can't exactly remember the scenario where @Tensuko and I came up with these angles, it solved one issue but may not work very well in other cases.

We know if it is a vehicle or not, and in 19, when CP (or a human) drove the other vehicle we just ignored it. 

We can also rotate the sensor, for instance proportionally with the current steering angle so it could be made narrower without impacting behavior when turning.

Or, we can be less sensitive to obstacles lying further outside. 

We can also add a something to the UI to deactivate the proximity sensor or change its parameters.

**Comment by rohne83** [comment]
Many thanks, pvaiko, for that information.

> We can also rotate the sensor, for instance proportionally with the current steering angle so it could be made narrower without impacting behavior when turning.
> 
> Or, we can be less sensitive to obstacles lying further outside.

Think those two points might be great additions which should help most to get a more fluent driving with near but not dangerous obstacles and unloaders.

**Comment by Tensuko** [comment]
Rotate the Sensor with the steering might be a solution.

The Situation was when our combine drives out of the pocket and the unloader is still there (human or AD).
So it won't pushes it away and causes a mess.
