### ISSUE TITLE
[BUG_SP] Fields merging / not merging

### ISSUE THREAD

**Issue by jufcar** [Courseplay/Courseplay_FS22#1322]
**Steps to reproduce**
Case 1:
Combine fields 76, 77, 78, 79 or fields 86, 90, 93
Case 2:
Conbine fields 97, 98, 99, 100, 107 but seperate to lower parts of fields 98, 99 and field 107 as seperate fields

**Actual behavior**
CP will seperate the fields in case one (pic 1-3) but include on of the seperated fields in case 2 (pic 4-5)

**Expected behavior**
Coming from previous CP versions in older FS games i expected CP to ignore the predefined field bounderies and merge the fields in case 1 as two large fields and ignore the small lower parts in the second case. 

**Screenshots**
![Case_1_1](https://user-images.githubusercontent.com/102970663/161553834-0b32cc1e-0681-4700-b80f-3c21f8f6d1d9.png)
![Case_1_2](https://user-images.githubusercontent.com/102970663/161553842-b5e04f42-890d-4dd2-a9a7-50ddc0685cdf.png)
![Case_1_3](https://user-images.githubusercontent.com/102970663/161553853-7a0d215c-b866-48eb-ac03-2f13df7a4112.png)
![Case_2_1](https://user-images.githubusercontent.com/102970663/161553862-e8964088-24ed-4e67-8db6-1434e078a050.png)
![Case_2_2](https://user-images.githubusercontent.com/102970663/161553870-c1b6bcf9-9367-484c-b0b1-81da602ccfc0.png)

**Courseplay version**
Version used: 7.0.1.9 and 7.0.1.7

**Log**
https://gist.github.com/jufcar/dc40680867a22ec2794b3ba69deb9f2e

**Map**
Zdziechow (mod: https://ls-portal.eu/de/fs22-zdziechow/ <- seems to be the official site the author uploaded his map to)

**Vehicles/ implements involved**
Tested with2 Combinations:
1:
Pöttinger Terrasem C6F (vanilla)
JCB 4220 (mod: https://forbidden-mods.de/filebase/file/30653-jcb-fastrac-4220/#overview)
2: 
Amazone ZA-TS 3200 (mod: https://forbidden-mods.de/filebase/file/26461-ls22-amazone-za-ts-3200-mit-streubreitenmarkierung/)
Claas Axion 870 (mod: https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=231662&title=fs2022)

**Relevant script mods**
CP does a lot, so i'm unsure which ones might colide, my guess is that for this specific bug non is relevan
[cpFields.zip](https://github.com/Courseplay/Courseplay_FS22/files/8410265/cpFields.zip)
t

**Comment by Resandise** [comment]
I have had issue where CP is merging fields that are not merged when trying to set up a course, and have to resetting the field position marker till it outlines the field I want without adding extra fields in.

**Comment by Tensuko** [comment]
No Issue wich combined fields with Version 7.0.1.11
It might be a Map Issue, not sure.
