### ISSUE TITLE
Wrong transfer of AD & CP for several vehicles [BUG_SP]

### ISSUE THREAD

**Issue by matse2886** [Courseplay/Courseplay_FS22#1329]
**Steps to reproduce**
(1)
When there are multiple (3) vehicles in the field, AD does not properly hand over to CP.
Vehicles do not drive as set (right/center/left). But now, as in this example, they are driving the other way around!
Vehicle on the left is driving on the right and vehicle on the left is driving on the right. What has also happened is that vehicles are all in one lane, e.g. driving on the left.

(2)
3 vehicles when sowing.

     Vehicle drives on the left (right)
     The vehicle is set to the center and also drives to the left
     The vehicle is set to the right and also drives to the left

(3)
also when the vehicles come back from filling up

**Screenshots**
![2022-04-02-16-59-17](https://user-images.githubusercontent.com/102803235/161690251-ae4c27f5-9d30-4ea5-a752-b4ed629ec1cb.jpg)
![2022-04-02-16-59-33](https://user-images.githubusercontent.com/102803235/161690268-27c01530-2e6f-4fbb-ae20-dadf8288d47c.jpg)
![2022-04-04-19-55-08](https://user-images.githubusercontent.com/102803235/161690312-1b833d5e-a26f-4a9f-ba59-a86b75934e86.jpg)

**Courseplay version**
7.0.1.9

**Log**
(Log 2)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8415417/log.txt)

(LOG 3)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8415419/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Which vehicle or implement?
Mod no 

**Relevant script mods**
AD  2.0.0.5

**Comment by HaploAW** [comment]
Be advised I think this is more so how AD hands over to CP. I have a fork of AD that is set to be reviewed that makes the hand over from AD to CP better. Uses the cpStartStopDriver() instead of using cpFirstWaypoint()
