### ISSUE TITLE
Drescher problem mit abladen im vorgewende 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/Courseplay_FS22#133]
hey hab ein kleines problem mit dem Drescher im vorgewende gefunden unzwar wenn man ihn abtanken will im Vorgewende fängt er an sein kleines Bünkerchen zu bauen und fährt einfach weiter anstadt zu warten biss er leer ist oder einfach auf seinem normalen kurs weiter zu fahren
![fsScreen_2021_12_26_17_46_53](https://user-images.githubusercontent.com/71101944/147414935-0b4c8827-05f2-4190-823c-926eb962efa4.png)

**Comment by Tensuko** [comment]
Funktioniert, ABER
![fsScreen_2021_12_26_18_58_14](https://user-images.githubusercontent.com/27344744/147416371-c9e69e84-234c-44ca-9019-c645b0a89b13.png)

Du musst Entlade Drescher im ersten Vorgewende aktivieren:
![fsScreen_2021_12_26_18_58_26](https://user-images.githubusercontent.com/27344744/147416359-0524b894-d026-47c1-94f6-3e286b0b39cf.png)

Oder wir stellen das auf default aktiviert.

Die Funktion entscheidet, ob wir im ersten Vorgewende schon Abtanken erlauben, oder er erst voll werden soll und sich die Tasche baut.
Er sollte trotzdem dann nicht falsch weiter fahren.

**Comment by Playlord75** [comment]
also wie gesagt wie auf dem bild bei mir ist er gefahren kann aber natürlich sein das das irgendwie ein einmaliger fehler war der nicht reproduzierbar ist LUL

**Comment by Brombee42** [comment]
Hatte das gleiche wie Spielherr75  bei Abladen im Vorgewende
![fsScreen_2021_12_27_05_37_23](https://user-images.githubusercontent.com/30389219/147512799-08324cb9-3568-48af-85d4-4ecd09854b83.png)

**Comment by Brombee42** [comment]
Warum fährt er Rückwärts als ob er eine Tasche reinfahren wollte.Er war auf der Ersten Bahn links und sein Bunker voll.
Warum hat er nicht entladen ?
![fsScreen_2021_12_27_05_38_46](https://user-images.githubusercontent.com/30389219/147512891-b60bf34f-6736-4c5f-ad5d-ae32894638eb.png)

Er fuhr dann auf der Zweiten Bahn vor  und nicht wieder zurück auf die erste Bahn Links

**Comment by Tensuko** [comment]
Hat sich wohl nen bug eingeschlichen, gucken wir uns auf alle Fälle an.

**Comment by Tensuko** [comment]
Müsste gefixt sein.
