### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by Yakuza112v2** [Courseplay/Courseplay_FS22#1330]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Actual behavior**
Now that I have the latest version on the server, I can no longer display the mini GUI and the mouse pointer is no longer there.

**Expected behavior**
Now that I have the latest version on the server, I can no longer display the mini GUI and the mouse pointer is no longer there.

**Courseplay version**
7.0.1.9

**Client Log**
[clientlog.txt](https://github.com/Courseplay/Courseplay_FS22/files/8417345/clientlog.txt)

**Server Log**
[Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8417313/Server.Log.txt)

**Player on the server**
1

**Dedicated server or local hosted server**
Dedicated server: yes

**Map**
NF March 4X

**Vehicles/ implements involved**
Yes there are vehicle mods available.
[Modlist.txt](https://github.com/Courseplay/Courseplay_FS22/files/8417416/Modlist.txt)

**Relevant script mods**
Autodrive

**Comment by Yakuza112v2** [comment]
Small fix: after I left the server, it would normally stop working, that wasn't the case this time and it continued after I logged back in. I had now deleted the files from CP in the savegame and logged in again. The mini-GUI then still did not open when I sat on the tractors that have previously continued, I then sat in another tractor and there I could then activate the GUI again. The GUI then also worked in the other two tractors.

**Comment by Tensuko** [comment]
You got a LUA Callstack related to the game files in your logfile.
Nothing CP related.
If you have CP 7.0.1.9 from our Release site, it should be no Problem, we tested MP.

Maybe you have AutoDrive Edit Mode active ?
You have to turn it off to use right click.

**Comment by Tensuko** [comment]
Closed due to inactivity.
