### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by bertls-hof** [Courseplay/Courseplay_FS22#1334]
Playing on Mac, is this a bug?

best regards and thank you for your great work!

<img width="549" alt="Bildschirmfoto 2022-04-05 um 19 55 58" src="https://user-images.githubusercontent.com/97104733/161819800-97f285c7-7218-4c46-96d0-a1bc9fcd7dd7.png">

**Comment by Tensuko** [comment]
If you would tell me what you think is the bug I could answer your question....

**Comment by bertls-hof** [comment]
The left window, its not possible to hide it!

**Comment by Tensuko** [comment]
Ofc it is!
General Settings -> turn off notification window.
