### ISSUE TITLE
[BUG_MP] Cultivator destroys part of the field

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1337]
**Steps to reproduce**
Buy cultivator and set tractor as below 2-3 headlands and let go

**Actual behavior**
Sets too early and destroys part of the crop

**Expected behavior**
Should not set down the cultivator too early and only set it down when it is level with the road surface.

**Screenshots**
https://youtu.be/9BApvo499ek

**Courseplay version**
Version used: 7.0.1.9

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8426714/log.txt)

**Server Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8426718/log.txt)

**Player on the server**
1-4

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Nordfriesische Marsch x4 Version 1.4.1.0

**Vehicles/ implements involved**
John Deere 8RX 310 & Farmet Kompaktomat 1570 Max

Mod no

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Sry but we won't do anything there.
This is mroe or less a User Problem.
No one will seed right after cultivating in RL.
Beside that, if you rly want to do that, try out to start on the center and not on headland (course generator option).
You will have unworked headland while those turns.

**Comment by Selyria** [comment]
> Sry but we won't do anything there. This is mroe or less a User Problem. No one will seed right after cultivating in RL. Beside that, if you rly want to do that, try out to start on the center and not on headland (course generator option). You will have unworked headland while those turns.

Well okay I play the game rather economically ^^
I thought that maybe the cultivator can be set so that he drives himself first straight and then resets and there on.

But well if they do not want to do anything is okay for me I'll let me think of something.
