### ISSUE TITLE
[Question] Cant connect to MP unless i remove/re-add CP locally

### ISSUE THREAD

**Issue by godgeneral16** [Courseplay/Courseplay_FS22#1339]
Hello. A couple of friends and i are using CP on our multiplayer server. My friends can play fine and dont run into any issues regarding CP and our modpack. I however encounter some strange behaviour. 

I sometimes lose connection to the server randomly, and in order to reconnect to the server i must remove the CP mod from my mods folder and replace it. Same needs to happen after a PC reboot. Is this something in CP that could cause the issue? Or is it maybe something with my FS setup? 

My mod folder contains the same mods as my friends. Also the issue is not there when CP is disabled on the server, so that makes me thing its something with CP, but maybe in combination with something else, but cant figure out what.

My logs dont give any information either.

**Comment by Tensuko** [comment]
logfile ? https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by godgeneral16** [comment]
Oh im sorry, i forgot to add it. Here you go: [https://pastebin.com/iUXeJzdk](https://pastebin.com/iUXeJzdk)

**Comment by Tensuko** [comment]
Well, this can't come from CP, your log looks okay beside an Error from another Mod, but nothing CP related.
Disconnects happens, depending on several things.
To find back the server and stuff, it may take a while.
Can't rly help you there if there is not Error involved.

Maybe Update to newester Version (7.0.1.9) if you use AD too.

**Comment by godgeneral16** [comment]
Thanks for the help anyway. Trying to rule out what can be the issue. Luckily not CP then, so i can keep using it 😄 

Regarding the not finding the server: i do find the server, i sync and then before it hits 100% i get disconnected already unless i do a sort of clean mod install. Its an odd bug that only i seem to have.

**Comment by Tensuko** [comment]
Maybe some other mod settings. Maybe reset the files inside modSettings
