### ISSUE TITLE
Combine harvester not continueing after selfunload.

### ISSUE THREAD

**Issue by nlcoredump** [Courseplay/Courseplay_FS22#134]
Hi,

I don't know if this is a bug or just my wrong expectations.   But every time i use the selfunload option, harvester drives to unload point at the side of the field, unloads, and then just sit there waiting, i would expect it to continue where it stopped harvesting, but no luck, i have to reset the driver to last point and have it continue there manually.

Is this expected behaviour?

**Comment by nlcoredump** [comment]
currentl using 7.0.0.4

**Comment by Tensuko** [comment]
Combine finds a course, but getting a LUA Error:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777356/log.txt)
![fsScreen_2021_12_26_19_04_37](https://user-images.githubusercontent.com/27344744/147416499-198eb6d4-d2c6-46ba-8dde-7978b7154ddc.png)
