### ISSUE TITLE
[BUG_SP]bourgault 3420-100 seeder will not follow generated course path

### ISSUE THREAD

**Issue by pierrehicks** [Courseplay/Courseplay_FS22#1340]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course with the Bourgault 3420-100 seeder and 71300 air cart. Start course and switch to another vehicle.

**Actual behavior**
After starting the course and then switching to another vehicle, when you come back to the seeder it will have gone off course or jack knifed itself causing it to miss spots or even stop driving the course. After switching back if it is still driving the course it will correct itself back to the course and continue driving correctly as long as you are watching it.

**Expected behavior**
The tractor/implement to follow the course even while driving another vehicle

**Courseplay version**
Version used: 7.0.1.9

**Log**
https://gist.github.com/pierrehicks/35b638b2c33776502ea27cfdd35205c6

**Map**
Shellbrook Creek

**Vehicles/ implements involved**
Fendt 1167 MT
Bourgault 3420-100 seeder
Bourgault 71300 Air Cart

**Relevant script mods**
AutoDrive

**Comment by Tensuko** [comment]
#1305
