### ISSUE TITLE
[BUG_SP] Look Ahead Distance for Chopper

### ISSUE THREAD

**Issue by eric4072** [Courseplay/Courseplay_FS22#1343]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Gras häckseln mit 4 Vorgewende, je 1 Reihe überspringen, NF Marsch Feld 13 und 45 und Feld 41.

**Actual behavior**
der Pathfinder scheint zu funktionieren, jedoch das Fahrzeug steuert den viel zu aggressiv an. Das ganze betrifft aber nur den Häcksler, mit Drescher tritt das Problem nicht auf

**Screenshots**
bei den Aufnahmen ist noch Version 1.7 installiert, 1.9 bringt aber das gleiche Bild

erstes Video mit pathfinder aktiv:
https://youtu.be/2Dj8DgyYJvM

log dazu:
[log1.txt](https://github.com/Courseplay/Courseplay_FS22/files/8444377/log1.txt)

zweites Video mit pathfinder aus:
https://youtu.be/2rlHo8toKZw

log dazu:
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/8444374/log2.txt)

das ein- und ausschalten scheint keine Veränderung zu bringen.
das schaukelt sich dann auf.

**Map**
Map played on.
NF-Marsch
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? ja

**Relevant script mods**
Mods like Autodrive or VCA and so on. ja

**Comment by Tensuko** [comment]
Video Privat,
Was heist das:

> jedoch das Fahrzeug steuert den viel zu aggressiv an

Welches Fahrzeug steuert wen zu aggressiv an ?

**Comment by eric4072** [comment]
Danke ;-)

**Comment by Tensuko** [comment]
Ist der Häcksler Vanilla oder Mod ?

**Comment by pvaiko** [comment]
Ist das ein Mod? Bei mir macht der 9900 sowas nicht, egal was ich einstelle.

**Comment by pvaiko** [comment]
Der müsste langsamer fahren wenn er lenkt. Das ist bei dir nicht der Fall. Das macht der Giants Engine normalerweise, bei dir fährt er mit 19-20 unabhängig von dem Lenkwinkel.

**Comment by eric4072** [comment]
Hallo nochmal, 

ja, sind Vanilla-häcksler, das Problem habe ich soeben gefunden:

AI Vehicle extension 0.1.6 ist nicht mehr kompatibel mit CP.

nach deaktivierung läuft alles normal. 

trotzdem danke ;-)
