### ISSUE TITLE
[BUG_SP]5 Drescher - Nummer 1 + 5 fahren nach Wiederaufnahme nicht korrekt los

### ISSUE THREAD

**Issue by MavericksBastelstube** [Courseplay/Courseplay_FS22#1347]
**Steps to reproduce**
Aktueller Fehler - Feld 17 auf der Wild West; Einsatz 5 Drescher im Verband. Start klappte. Die Vorgewende sind korrekt gefahren worden. Auch der Umgang von auf die Bahnen. Nach dem Speichern des Spielstandes wollte ich die Drescher wieder losschicken (Nahester Wegkpunkt). Der Drescher 1 (links 2) fährt entweder nicht los oder macht irgendwas. Die Drescher 2,3 und 4 fahren den korrekten Kurs wieter. Drescher 5 (rechts 2) macht nicht das was Er soll. Im Beispiel fährt Er zugeklappt im Kreis.

Passiert z.B. auch auf dem großen Feld links oben auf der NF Marsch oG (mir fällt gerade die Feldnummer nicht ein)

**Actual behavior**
siehe Video

**Expected behavior**
Das auch Drescher 1 und 5 die korrekten nächsten Wegpunkte ansteuern und der Verband wieder komplett korrekt weiterarbeitet

**Screenshots**
https://youtu.be/aPkOoW3en5o

**Courseplay version**
v7.0.1.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8445880/log.txt)

**Map**
Wild West v1.1.0.0 & NF Marsch oG v1.2

**Vehicles/ implements involved**
Class Lexion 8900
Mod -> no

**Relevant script mods**
Autodrive v2.0.0.5

**Comment by Tensuko** [comment]
Kann ich nicht reproduzieren.
An den Feldern kann es nicht liegen.

**Comment by Tensuko** [comment]
Bitte einmal ein logfile mit debug auf allen Fahrzeugen eingeschaltet anhängen.

**Comment by Thorty88** [comment]
Grüße diesen Fehler habe ich auch schon gehabt. Behoben habe ich dies ganz einfach, 
Bin etwas zurück gefahren Richtung dem Kurs den er gefahren ist also so zu sagen von Links (2) auf Links (1) und dann wieder eingeschaltet, Nächster oder Letzter Wegpunkt das Funktionierte dann wunderbar. 
ich vermute auch das er den Kurs auf der anderen Bahn findet und somit zu einem Konflikt kommt. 

Des weiteren ist es genau das gleiche Feld wie im Bericht des Beitrages, aber auch auf anderen Feldern ist das schon vorgekommen. 

LG
Thorty

**Comment by MavericksBastelstube** [comment]
Danke für den Tip @Thorty88 - hat aber leider auch nix gebracht. Stelle ich das Fz Links(2) auf den Platz von Links(1) und starte Seine Fahrt mit "Nahestem Wegpunkt" startet der Drescher nicht wie Er soll. Auch bei dem Wegpunkt erscheint wieder die Anzeige 1/xxxxx, was ja auch nicht korrekt ist

**Comment by MavericksBastelstube** [comment]
Vielen Dank! Funktioniert nun perfekt!
