### ISSUE TITLE
[BUG_SP] Amazon 150001-C issue, not working fine

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1349]
**Steps to reproduce**
Have a course in not squarred field

**Actual behavior**
not zone are not worked properly
driver lower the implement after start working zone (green line)

**Expected behavior**
Driver should do more manoeuvre to work on every part of field
driver should manoeuvre to set the implement before the working line

having this with some large/big implement (around 15m width or more)

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/58886243/162427862-6de4e6e8-afea-4455-8d7b-00b15864be51.png)
video : https://drive.google.com/file/d/1dtkX7PUXc0rl7n2nftftIbgI4mz46SvZ/view?usp=sharing

**Courseplay version**
Version used: 7.1.0.9

**Log**
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/8451442/log2.txt)

**Map**
Elmcreek, fields 36 to 43 merged

**Vehicles/ implements involved**
JD 8R + Amazon 150001-C

**Relevant script mods**
AD 2.0.0.5

**Comment by Tensuko** [comment]
Looks good to me.
![fsScreen_2022_04_08_15_55_17](https://user-images.githubusercontent.com/27344744/162450280-8a97fe65-91c2-4dbb-94b2-14bfb7e46ad0.png)

**Comment by Chico0008** [comment]
Yeah, but as you can see on the video, worker lower the seeder far after where he is sopposed to begin :/
dk why

**Comment by Tensuko** [comment]
Err that looks like an old bug... should be already fixed.
Will test one more thing later.

**Comment by Tensuko** [comment]
Can't help you right now buddy, must have a closer look.
Can you save your course and attach it here ?
![fsScreen_2022_04_08_16_47_13](https://user-images.githubusercontent.com/27344744/162462999-4854fd98-0987-4f0b-b8cb-7510ddf0343d.png)

**Comment by Chico0008** [comment]
course attached :)
[37 - 4 - 15m - Semoir 2.zip](https://github.com/Courseplay/Courseplay_FS22/files/8453518/37.-.4.-.15m.-.Semoir.2.zip)

**Comment by Tensuko** [comment]
@pvaiko was able to reproduce this... Any Idea ?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8454411/log.txt)
