### ISSUE TITLE
Kurse löschen

### ISSUE THREAD

**Issue by BigBlackBahamut** [Courseplay/Courseplay_FS22#135]
--GER--

Hallo,

wie kann man gespeicherte Kurse wieder löschen? Und ich meine nicht aus dem Fahrzeug sondern die gespeicherten Kurse in den erstellten Ordnern? Scheint so als wäre das nicht so einfach möglich. Da wäre es schön nachzubessern. Habe nicht Lust immer wieder das Spiel zu schließen um in den Explorer die Dateien zu löschen die für den Kurz sind. Außerdem wäre das ziemlich umständlich nachher im MP.

--ENG--

Hi there,

how can I delete saved courses? And I don't mean from the vehicle but the courses saved in the folders created? Seems like it's not that easy to do. It would be nice to make improvements. I don't feel like closing the game again and again in order to delete the files in Explorer that are for the short term. In addition, that would be rather cumbersome afterwards in the MP.

**Comment by Tensuko** [comment]
Im Generator auf edit, kurs löschen, kurs anklicken. Das spiel beenden weis nicht ob das nötig ist.

**Comment by BigBlackBahamut** [comment]
Oha, das ist aber kompliziert... Ich hoffe das wird noch überarbeitet da es ist eh schon komplizierter geworden ist im Allgemeinen.

Aber Danke für diese Info.

**Comment by BigBlackBahamut** [comment]
Aber immer klappt das nicht wirklich. Ich habe gerade das Problem das ich an einem Kurz einfach nicht mehr rankomme. Sobald ich im Generator bin komme ich nicht zu den gespeicherten Kurs den ich löschen möchte. Ich habe da kein Edit zu sehen. 

Ich versuche es weiter, wahrscheinlich muss man einen ganz bestimmten Weg gehen um das "Edit" sehen zu können. Es ist wirklich sehr kompliziert... :-(

**Comment by BigBlackBahamut** [comment]
Also, es ist wirklich kompliziert mal in den Modus zu kommen um die gespeicherten Kurse zu bearbeiten. Ich hoffe es kommt demnächst noch eine einfacherer Lösung dazu.

Ich musste erst einmal einen neuen Kurs generieren und kam dann erst in den Bereich um die Kurze löschen oder bewegen zu können. Und das klappte auch nicht immer.

**Comment by Tensuko** [comment]
Das erst ein Kurs drin sein muss, muss ich mir anschauen, aber der Manager wird erst mal so bleiben aus verschiedenen Gründen!

Es klappt sehr gut, wenn man weis wie, und an dem wie, daran arbeiten wir und es wird auch noch mehr Infos dazu geben.
