### ISSUE TITLE
Dalbo Mega Roll 2430, CP field job starts before roller completed unfolding

### ISSUE THREAD

**Issue by MiD4711** [Courseplay/Courseplay_FS22#1351]
**Steps to reproduce**
Create a CP Job with a tractor with the Dalbo Mega Roll 2430. Start the job at first waypoint.

**Actual behavior**
The tractor drives to the first waypoint and starts before the Roller is completely unfolded. The first few meters of the course are not rolled. (Note: The roller does not have the V-function for lowering, just the X for unfold)

**Expected behavior**
Tractor shall wait until the roller is fully extended before starting the course.

**Courseplay version**
Version used: 7.0.1.9 

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement? Dalbo Mega Roll 2430
Mod yes/no ? no

**Relevant script mods**
AD
VCA

**Comment by Tensuko** [comment]
#1265
