### ISSUE TITLE
[BUG_MP] Verliere Server Verbindung beim erstellen von Kursen

### ISSUE THREAD

**Issue by Hauni22** [Courseplay/Courseplay_FS22#1355]
**Steps to reproduce**
Katana 650 CP: Feldarbeit -> Field Position -> Ziel Position -> Kursgenerator (alles Standard oder mit Vorgewende geht beides nicht) 

**Actual behavior**
Bei jeder Kurs Generierung verliere ich die Verbindung zum Server(dauert 10sek bis die Meldung kommt kann aber nach der Generierung nichts mehr tun) verschiedene Felder oder Fahrzeuge und Geräten wurde schon versucht.
Der Kurs wird mir sogar auf der Map angezeigt bevor ich die Verbindung verliere.
Spiel neu installiert und alle Mods die nicht am Server sind wurden gelöscht. Spiel von HDD auf SDD gezogen.
Im SP funktioniert die Kurs Generierung mit den Mods

**Expected behavior**
Katana 650 CP: Feldarbeit -> Field Position -> Ziel Position -> Kursgenerierung starten -> Verbindung zum Server verloren

**Screenshots**
https://snipboard.io/GKapxr.jpg
https://snipboard.io/JRlZSY.jpg

**Courseplay version**
Version used: v7.0.1.9

**Client Log**
https://gist.github.com/Hauni22/f5d735bbd2f8d60308d8613a295ce5c2

**Server Log**
leider keinen Zugriff.

**Player on the server**
1/8

**Dedicated server or local hosted server**
Dedicated server yes/no ? yes (Nitrado)

**Map**
FS22_NF_Marsch_4fach_oG 1.4.1.0

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? Vanilla Fahrzeuge und Mod Fahrzeuge bzw. Geräte wurden getestet

**Relevant script mods**
AD and this is the Mod List from the Server: https://gist.github.com/Hauni22/510a07fd4e2846adf644bf9fe203e370

**Comment by Tensuko** [comment]
Fixed in next Release, will be pushed soon.

**Comment by Tensuko** [comment]
Can you test 7.0.1.13 ?
https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by Tensuko** [comment]
Closed due to inactivity.
A lot have changed since the Issues was created and have not more informations about this Problem.
