### ISSUE TITLE
save/ load course

### ISSUE THREAD

**Issue by Kuunlan01** [Courseplay/Courseplay_FS22#136]
Hi,

I can not seem to find how I can reload a previous course to another vehicle.
Usage example: create and drive a course with a combine and than load the same course on a tractor with baler.
Am I just not seeing it or is that not inplemented? ( the read me does say that save/load is present...)

**Comment by Tensuko** [comment]
Select your vehicle, go into the manager, click on load course, click on the course.

**Comment by Kuunlan01** [comment]
> Select your vehicle, go into the manager, click on load course, click on the course.

I totaly missed that :) thanks
