### ISSUE TITLE
[BUG_SP] CP übergibt nicht am AD nach dem sammeln von Steinen

### ISSUE THREAD

**Issue by Holzotte** [Courseplay/Courseplay_FS22#1368]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
Wenn ich mit CP auf meinem Feld Steine sammeln lasse, übergibt CP nicht an AD wenn der Steinsammler voll ist. Wenn ich dann AD manuell starte fährt er abladen. Nachdem er zurück kommt nimmt er seine Arbeit allerdings wieder normal auf, bis er voll ist und ich wieder manuell AD starten muss.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.1.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Niedersachsen 22

**Vehicles/ implements involved**
Which vehicle or implement? Fasttrac 8330 & Fendt 942 + Scorpio 550 NDS
Mod yes/no ? Steinsammler ja

**Relevant script mods**
AD 2.0.0.5

**Comment by Tensuko** [comment]
Abwarten und Tee trinken, da kommt noch was, bzw aktuell ist es so gewollt.

**Comment by Holzotte** [comment]
ok, danke für die Info
