### ISSUE TITLE
[Feature] Manual creation of routes with manual stops as in Courseplay for FS19

### ISSUE THREAD

**Issue by rauldelasheras** [Courseplay/Courseplay_FS22#137]
**What is the problem this feature/enhancement solves?**
With Courseplay in FS19 it was possible to create a route manually. with different stop points and an end point. I do not detect this function available with Courseplay in FS22. 

For example, let's imagine we have a harvester stored at a specific point on the map, where from that point it will go to different fields it has to harvest, we will have a route called 1_Harvester (for field 1), 2_Harverster (for field 2), 3_Harverst (for field 3) and so on. At points along the route, stops are introduced, which can be used to extend the harvester itself and lower the cutter, with more intermediate stopping points to bring trailers closer and empty the grain.

Attached is a video I have recorded in FS19 where I use this Courseplay function with a combine harvester and a trailer.
[https://youtu.be/v_ozqzhzy9A](url)

**Describe the solution you'd like**
The solution would be to **implement the same function available in the previous version**.

**Comment by Tensuko** [comment]
We won't add the Recording for now.
Sending a Worker to the Field, we use Giants and later AutoDrive.

Yes this is a problem for Combine, but you can do the exact same with 'free drive' or AutoDrive and when he arrives the point, put the combine together and start the Fieldwork.
