### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/Courseplay_FS22#1375]
**Steps to reproduce**
Use german language and a harvester.

**Actual behavior**
Only one of the two describing sentences from the option "Drescher selbst abtanken" is german.

**Expected behavior**
The second sentence should be german too.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/37582657/163004552-7fe5856d-698a-41a5-bbfb-1296241855c0.png)

**Courseplay version**
Version used: 7.0.1.11

**Vehicles/ implements involved**
Harvester

**Comment by Tensuko** [comment]
Huch, übersehen, wird angepasst.
