### ISSUE TITLE
[BUG_SP] Multiple tools - Right tool breaks off from course to explore the world

### ISSUE THREAD

**Issue by SuperPyroManiac** [Courseplay/Courseplay_FS22#1377]
**Steps to reproduce**
Create a course with 2 tools. You will see that the left tool is working perfect, and the right tool seems to work for about 30 minutes (halfway through my course) before suddenly breaking off from the course entirely and driving in random directions.

**Actual behavior**
Tractor set to the left path works fine in all my testing. Anytime I make a multiple tool course, the right tractor starts to do weird things halfway through the course including driving to fields far from the course or driving onto the rooftops of buildings outside of the course.
I attempt to re-setup the tractor slightly ahead in the course using the "Nearest Waypoint" option but no matter what it will just go back to the first waypoint. "Last Waypoint" just makes it start driving around the world in weird ways far from the course.

**Expected behavior**
I have 2 identical tractors and planters with corn, 3 headlands then up and down rows. 

**Screenshots**
Completely off the track driving in another field
https://i.imgur.com/LAzSujb.jpeg

Map view of the course
https://i.imgur.com/QIcoA6Z.png

Drove back to my property just to drive into the farm buildings:
https://i.imgur.com/Wh4zq9e.jpeg

Finally got stuck on the roof:
https://i.imgur.com/IIIozm1.jpeg

**Courseplay version**
Version used: 7.0.1.10

**Log**
https://gist.github.com/SuperPyroManiac/1c92a53328671ed69658956d100c53c3

**Map**
Fox Farms - Fields 1 2 and 4 combined.

**Vehicles/ implements involved**
Modded Case IH Magnum AFS US/EU Series x2
Stock Kinze 4905 Blue Drive Planter x2

**Relevant script mods**
N/A - Autodrive but not active in this case.

**Comment by Tensuko** [comment]
You do not have 7.0.1.10
-> (Version: 7.0.1.9) FS22_Courseplay

**Comment by SuperPyroManiac** [comment]
Just updated to the newest version right now, still the same issue.
https://i.imgur.com/V5EAOOe.jpeg

**Comment by Tensuko** [comment]
New logfile with debug setting active on both vehicles, then drive the course.

**Comment by pvaiko** [comment]
> New logfile with debug setting active on both vehicles, then drive the course.

Activate the Pure pursuit controller debug channel too.

**Comment by Selyria** [comment]
Yep can confirm the error try to reproduce the error again and upload a log.

What I can say is that I use Cosplay and Auto Drive together 

Curseplay does the field work and Autodrive refills seed when empty.

**Comment by Tensuko** [comment]
Closed due to inactivity, reopen with the requested information.
