### ISSUE TITLE
[BUG_MP] Curseplay does not run when you set not instantsetzen

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1378]
Steps to reproduce

Vehicle set slightly defective and then make a short start

Actual behavior

Curseplay no longer drives when I say do not instantset vehicles 

Expected behavior

Curseplay should not repair when setting the vehicle drive until it is 100% damaged. 

Screenshots

https://youtu.be/xverKV6Sk-k

Courseplay version
Version used: 7.0.1.11

Client Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8484817/log.txt)

Server Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8484816/log.txt)

Player on the server
4

Dedicated server or local hosted server
Dedicated server Yes

Map

Nordfriesische Marsch 4fach] 1.5

Vehicles/ implements involved

Kein Mod Fahrzeug

Relevant script mods
Autodrive 2.0.0.5

**Comment by Tensuko** [comment]
And what is your Setting at ?!

**Comment by Selyria** [comment]
Sry our mistake did not know that there are now settings there

**Comment by eric4072** [comment]
same here... i activate the function "repair tool with CP" and the message disappear...

% for maintenance in menu don´t have any reaction here
