### ISSUE TITLE
[Question] Module Express 635 Cotton combine

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#138]
Module Express 635 Cotton combine not work over CP version 7.0.0.5
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777422/log.txt)

module express 635 error

**Comment by Tensuko** [comment]
No Error from CP can be seen in your log but from other mods.
Clean your modfolder and provide the needed Informations with the correct Issue Template pls.
