### ISSUE TITLE
Courseplay with large harvesters & multiple headlands - field travel on outermost headland?

### ISSUE THREAD

**Issue by sylvesterworks** [Courseplay/Courseplay_FS22#1386]
Map: Old Stream Farm
Fields: Any (tested most recently on Field 51)
Crop: Potatoes
Tool: Grimme Ventor 4150
Settings: Sharp corners, 5 headlands, 4 rows to skip

This may be a setting that I haven't found yet - but when a tool is navigating the field, when there are multiple headlands - for some reason, the pathing when moving from one skipped row to the next takes the tool to the outermost headland path, then back into the center of the field to do it's pass. If the tool has to traverse the field in any way - it always wants to take the outermost headland.

The downside of this is that with such a large machine, it can't navigate the corners while staying on the field, and for the field in question - it gets constantly stuck when attempting to do any kind of corner because the machine swings so wide off of the field.

Should the field travel be on the outermost headland, or one of the other headlands?

**Comment by Tensuko** [comment]
There is no setting, it is like it is for now.
Duplicate #1194
