### ISSUE TITLE
[Question] Crossplay Support?

### ISSUE THREAD

**Issue by PanGeo-Code** [Courseplay/Courseplay_FS22#1390]
Well the titel says it,

Will there be crossplay support between pc mac ps4 ps4 xbox and so on?

Thanks,

**Comment by KITT3000** [comment]
No, consoles can't have non-Giants script-mods, plus it would be rather hard to operate this mod on a console and it might cause a console crash during course generation.

**Comment by Tensuko** [comment]
For Crossplay, custom Scripts would have to run on console, this is not the case, so no.
