### ISSUE TITLE
[Feature] After cultivating, hand over to Auto Drive and drive off the field.

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1395]
**What is the problem this feature/enhancement solves?**
Unfortunately, the tractors of Curseplay remain at the end of the route on the field it would be cool if these would drive off the field e.g. by handover to Auto Drive.

**Describe the solution you'd like**
Autodrive or Curseplay itself let the tractor drive off the field at the end.

**Comment by schwiti6190** [comment]
@Selyria Hi there, we have implement an interface for this. Could you create a Github issue on the autodrive github and ask for this implementation :)
