### ISSUE TITLE
[BUG_SP] Slurry applicator starts too late after pickup run (Autodrive)

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1397]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Have a slurry applicator drive in Autodrive "Pickup" mode in combination with Courseplay in a field.

**Actual behavior**
The slurry applicator starts at the starting point. When the slurry tank is empty, Courseplay hands over to Autodrive. Autodrive drives the slurry tanker to fill up. Back at the field, Courseplay starts at the last point. So far all is well and as desired. However, the slurry applicator is not completely unfolded and not lowered while the tractor is already driving off. This results in large areas that are not fertilized. (see screenshot)

**Expected behavior**
Slurry applicator waits until it is completely unfolded and lowered and only then starts. Also, it should turn a larger radius to the last point, so that the slurry tanker is straight behind the tractor.

**Screenshots**
![2022-04-16 13_15_37-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/163672945-6b3a11f8-bedc-4886-adce-29c2dc79663d.png)
![2022-04-16 13_16_04-Farming Simulator 22](https://user-images.githubusercontent.com/96819380/163672948-c148e3a3-190f-4d63-b7d0-998564784462.png)

**Courseplay version**
Version used: 7.0.1.11

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8499789/log.txt)

**Map**
NF Marsch 4fach ohne Gräben

**Vehicles/ implements involved**
Tractor: Fendt 1050
Slurry tanker: Kotte PQ 32000
Slurry distributor: Momech 4XL 

All no mods.

**Relevant script mods**
only Autodrive

**Comment by Tensuko** [comment]
Duplicate #1265
