### ISSUE TITLE
Combine stopping for terrain ? [BUG_SP]

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#1398]
Hello,

in last couple of days I experinced strange stopping of combine due to terrain change.  Combine simply stopped for no reason, only thing I think of can be caused by terrain? There were some terrain changes in all cases but nothing really "harsh" or very steep what should cause a problem. It happened for me on several fields on Nebraska map (12,28,3) with stock JD corn/normal header. Combine is Giants S790. CP itself did not switched off or release driver, still on green arrow, just combine was not moving without any notification or warning message. Added couple of screenshots. 

![20220416141531_1](https://user-images.githubusercontent.com/33344465/163674818-f2977461-138b-4054-b6ba-c930b02c27a8.jpg)

![20220416141500_1](https://user-images.githubusercontent.com/33344465/163674880-312969b7-36f0-465d-b108-4cbf5f7dcabe.jpg)

**Courseplay version**
Version used: 7.0.1.11 

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8499914/log.txt)

**Map**
Nebraska map by DJ modding
https://djmodding.itch.io/fs22-green-valley-nebraska-4x?fbclid=IwAR3VQxIAhYp5MhA46CIATa0S32tMCPPjNC7C3YUkeHatpC7yMWzIp5W3rdc

**Vehicles/ implements involved**
https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=229258&title=fs2022
Mod yes

**Comment by pvaiko** [comment]
Take a look at https://github.com/Courseplay/Courseplay_FS22/issues/1148#issuecomment-1062994693 maybe same problem here?

**Comment by Misamangame** [comment]
> 

Yes I guess it is same problem. But I did not had any joined fields or cutted trees there. I can make some video tomorow, I wasn't aware CP uses some kind of scanner/proximity sensor.  If we have to live with it I can survive I just always moved combine few cm forward with super strenght mod, because they have been stopping even on changing rows with cutter in raised position. Probably some smoothing of terrain can help atleast in some  areas.

**Comment by pvaiko** [comment]
The proximity sensor ignores the terrain, it must be detecting something else, but we were not able to find out what it was in #1148. If you want, post a savegame here with everything set up close to such a location so that the combine will stop after I start it, I can take look maybe we have more luck this time.

**Comment by Misamangame** [comment]
> The proximity sensor ignores the terrain, it must be detecting something else, but we were not able to find out what it was in #1148. If you want, post a savegame here with everything set up close to such a location so that the combine will stop after I start it, I can take look maybe we have more luck this time.

[savegame3.zip](https://github.com/Courseplay/Courseplay_FS22/files/8504799/savegame3.zip)

did not manage to upload on Gist so hope this will work. If not let me know will try proper way. There is S790 harvester by Giants https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=229258&title=fs2022

I also prepared 2 vanilla harvesters with vanilla headers, course for all of them is s790 should be included in savegame? just run them they are all 10s before stopping spot on field 3.

map can be found here : 
https://djmodding.itch.io/fs22-green-valley-nebraska-4x?fbclid=IwAR3VQxIAhYp5MhA46CIATa0S32tMCPPjNC7C3YUkeHatpC7yMWzIp5W3rdc

**Comment by Tensuko** [comment]
Should be fixed in 7.0.1.13
Pls report if Issue persists.
