### ISSUE TITLE
[BUG_SP] New Courses Created or Existing Courses Loaded won't Start with Courseplay giving message Vehicle or Tool Broken

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#1399]
**Steps to reproduce**
When Creating a Fieldwork Course for any task, or loading a previously saved Course, whenever I then click the button in the Menu to start job, Courseplay just gives me a message in the upper left corner of the screen that Vehicle or Tool is broken. Even though everything is fully repaired and maintained or is even a brand new machine fresh from the store or equipment leased for a contract.

Have checked the Courseplay Options and see some new entries for Fuel Threshold and Repair Threshold, but it makes no difference what setting I set these to from 0% up to 100%, Courseplay will still not start and tasks, claiming something is broken.

**Courseplay version**
Version used: v7.0.1.11

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8499965/log.txt)

**Map**
Haut Beyleron

**Vehicles/ implements involved**
Tried with Base Game Vehicles and Tools, Modded Vehicles and Tools, freshly leased/rented vehicles and tools and get the same issue with everything.

**Relevant script mods**
Latest Version of Autodrive Installed, however any options regarding refuelling and repairing are disabled.

**Comment by Tensuko** [comment]
#1378
