### ISSUE TITLE
[Feature] Schneidwerk beim Abtanken (im Stand) abschalten (Fuel Save)

### ISSUE THREAD

**Issue by Sacred-Shadow** [Courseplay/Courseplay_FS22#140]
Wäre cool, wenn der Drescher beim warten auf den Abfahrer o. auch beim abtanken selbst das Schneidwerk abschalten würde. 
Der steht da einfach rum, lässt das Schneidwerk in der Luft laufen und wartet, bis er abgetankt ist. 

Ökologischer wäre natürlich, da das Ding abzuschalten :D 
Trifft natürlich nur zu. wenn man das "im Stand abtanken" gewählt hat. 

Wobei der am Ende der Strecke auch stehen bleibt und das Schneidwerk laufen lässt, bis er abgetankt ist. 
Dabei lässt er auch das Rohr eingefahren, was dann für AD blöd ist ... 
Weiß nur nicht, ob das nen Bug is.

**Comment by Tensuko** [comment]
Ja das ist Fuel Save Mode und ist noch nicht implementiert.
