### ISSUE TITLE
Combines self-unload + Auger wagon[Question]

### ISSUE THREAD

**Issue by Vosh-ka** [Courseplay/Courseplay_FS22#1400]
![Anteckning 2022-04-16 173124](https://user-images.githubusercontent.com/103841324/163681043-f658c376-d2ac-4faf-b577-2f57b1cfd6f5.jpg)
![image](https://user-images.githubusercontent.com/103841324/163680933-a76b4cd4-a033-4769-bf87-ef2316aa26bd.png)

As seen in the image I would like to have the combine self-unload into the auger wagon, but it always parks too far away for it's own pipe, and I'm not sure if I'm doing something wrong or its a bug, hence I didn't want to submit a bug report.

If I park the truck and trailer where the auger wagon is, it self-unloads fine, but as soon as it's an auger wagon it seems to think the wagon is a meter wider, or it has a longer pipe than it does.

It seems to not matter which auger wagon I try, modded or vanilla, and if I install a shorter pipe on the combine it crashes into the back of the wagon instead (due to width of header)

**Comment by Tensuko** [comment]
Looks like a modded combine ?

**Comment by Vosh-ka** [comment]
Yes it is, I assumed that wouldn't matter much, but I will try with an unmodded one next and report back :)

**Comment by Vosh-ka** [comment]
Ok, tried the Lexion 8900 and it seems to work perfectly fine then, perhaps its because the modded harvester has a upgradable pipe? I will test some more

**Comment by Vosh-ka** [comment]
With a bit further testing, it seems like any combine with a changable pipe length doesn't work, somehow it gets confused as to its actual pipe length.

Vanilla or modded as long as it doesn't have a pipe that you can customize, it works fine it seems.
