### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Schmidtdel** [Courseplay/Courseplay_FS22#1402]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
CP Hud lässt sich nicht öffnen 

**Actual behavior**
Mit rechten maus klick passiert nix.Hud lässt sich nicht öffnen

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used:  7.01.12

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Standart Karten

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? No

![20220416_203711](https://user-images.githubusercontent.com/103847930/163688029-0a1b8219-acae-477a-b355-770de292d2e9.jpg)

**Relevant script mods**
 Autodrive 
![20220416_203720](https://user-images.githubusercontent.com/103847930/163688161-8a856c77-e90b-4a6f-94a7-c0df84df5165.jpg)

**Comment by Tensuko** [comment]
Logfile ? Globale Einstellungen mal angeguckt ?

**Comment by Schmidtdel** [comment]
Ja ist aktiviert aber tut sich nix. Logdatei ist sauber.

**Comment by Tensuko** [comment]
Mich interessiert nicht ob die log sauber ist, ich will die log sehen da du offenbar einer der ganz ganz wenigen bist bei dem das hud angeblich nicht geht....
