### ISSUE TITLE
Map Failing To Open When Courseplay Enabled[BUG_SP]

### ISSUE THREAD

**Issue by allytat2504** [Courseplay/Courseplay_FS22#1403]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Loading the map ''Knuston Farm''

**Actual behavior**
Game loads ''Knuston Farm'' to around 50% then stops... 

**Expected behavior**
Load Succesfullly

**Screenshots**
![fsScreen_2022_04_16_21_22_16](https://user-images.githubusercontent.com/103856272/163690260-ccb1e703-8b35-4d1b-9609-6ba1a11377ba.png)

**Courseplay version**
Version used: Courseplay for FS22 v7.0.1.12

**Log**
Please attach a log with all debug channels active.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8500589/log.txt)

For help with the debug channels,
please check out the readme at the github front page.

**Map**
Knuston Farm

**Vehicles/ implements involved**
No Mods

**Relevant script mods**
No Script Mods apart from Courseplay for FS22 v7.0.1.12

**Comment by Tensuko** [comment]
Not a CP bug.
Gamecode reference, must be some other mod.
