### ISSUE TITLE
Kurserstellung[Question]

### ISSUE THREAD

**Issue by dirkkleinalbaching** [Courseplay/Courseplay_FS22#1407]
Hallo, es ist in der aktuellen Version nicht möglich, dass man die Kurserstellung auf "Scharfer Kurs" stellen kann.

**Comment by Tensuko** [comment]
Changelog nicht gelesen, gz!

**Comment by schwiti6190** [comment]
@dirkkleinalbaching 

```
Added an "expert" Mode, wich we contain all the settings you are used to. However, the expert mode is turned off by default.

We try to make courseplay more accessible for new players to not be scared off all the settings.
Settings that are not accessible when expert mode is off, will use their default values.
To activate the expert Mode, go into global settings and turn it on.
``` Einfach in den Globalen Einstellungen umstellen.

**Comment by dirkkleinalbaching** [comment]
Hallo,  habe mir das Video von Xpirijens angeschaut. Ich kenne mich auf
Github nicht so aus wo ich was finde. Lg Dirk

schwiti6190 ***@***.***> schrieb am So., 17. Apr. 2022, 11:47:

**Comment by Tensuko** [comment]
Aber wo hast du die neue version denn runter geladen ?

**Comment by dirkkleinalbaching** [comment]
Die habe ich auf Github heruntergeladen.

Tensuko ***@***.***> schrieb am So., 17. Apr. 2022, 15:19:

**Comment by Tensuko** [comment]
Unter Release is doch auch die changelog...
