### ISSUE TITLE
Feldreihenwende ungünstig bei schrägen Feldern.

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#141]
Die Feldreihenwenden werden derzeit noch sehr ungünstig gefahren. Nicht nur, dass sie nur mit der für die Feldarbeit geltenden Geschwindigkeit gefahren werden, auch die Strecke ist nicht sonderlich Platz sparend. Beim Dreschen besteht sie aus zwei exakten 90Grad-Kurven, womit bei unregelmäßigen Feldern sehr weit aus dem Feld rausgefahren und auch oft an Hindernissen die weit jenseits des Feldes stehen hängengeblieben wird. Wende auf dem Feld ist aktiviert, aber scheint hier nichts zu bewirken. Gibts noch andere Einstellmöglichkeiten um das zu beheben? Im 19er hatten wir ja unterschiedliche Einstellmöglichkeiten für die Wendemaneuver (Pathfinder nutzen, etc).

![fsScreen_2021_12_26_20_13_21](https://user-images.githubusercontent.com/71030138/147418358-cc5a06b8-c8f8-4466-b217-1a30fa81c5ee.png)
Drescher kommt vom Reihenende links und fährt erstmal so wie er ist schnurgeradeaus bis auf Höhe der nächsten Feldreihe (ca bei den Traktoren) um dort erst wieder im 90 Grad-Winkel zurück in die nächste Reihe zu wechseln.
Ist das Feld 70 auf der Elmcreek, da werden die Reihen zumindest bei Beeten schräg generiert.

**Comment by Tensuko** [comment]
logfile ?

**Comment by rohne83** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7777489/log.txt)

Gibts eigentlich auch noch einen DebugChannel mit dem man sich die Wegpunkte für die Wende anzeigen lassen kann?

**Comment by Tensuko** [comment]
Das kommt auf den turn drauf an. Für diesen gibt es keine Wegpunkte in dem Sinne oder sind nicht als debug drin...

**Comment by Tensuko** [comment]
Pls try 7.0.0.8
Reopen if Error persists.
