### ISSUE TITLE
[BUG_SP] Combine should stop when can't harvest due to bad weather

### ISSUE THREAD

**Issue by ZGuderian** [Courseplay/Courseplay_FS22#1411]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
Drescher der schlechtes Wetter abwartet bleibt im Arbeitsmodus, Motor läuft auf Vollgas

**Expected behavior**
Schneidwerk heben, Motor während der Wartezeit abstellen.

**Screenshots**
No Screenshots

**Courseplay version**
Version used:  7.0.1.12

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Brandenburg

**Vehicles/ implements involved**
Which vehicle or implement?   Claas Trion 730
Mod yes/no ? yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Pls test with 7.0.1.13
It got improoved but not sure if 100% fixed.
