### ISSUE TITLE
[BUG_SP] Course assigned to vehicle after course generation errors

### ISSUE THREAD

**Issue by koza1258** [Courseplay/Courseplay_FS22#1412]
**Steps to reproduce**
Try to generate a course with at least one headland. 
An error will appear. 
Save the game. 
Enjoy a fatal error that damages the save. :)
Save the game with a fatal error in the link below.
[Corrupted save of the game](https://drive.google.com/file/d/1MbyBT27KZlL2MYPmdw7_FmrvvUsiDkVZ/view?usp=sharing) 

**Actual behavior**
The course has not generated.

**Expected behavior**
A course with one headland will be generated. Without corrupted save. :p

**How to fix locally**

Delete the wrong entry from the "**CpAssignedCourses.xml**" file. after deleting an entry, the game loads correctly.
`<Vehicle name="6250 R">`
       `<Course name="" workWidth="29.900000" numHeadlands="0" multiTools="1"/>`
`</Vehicle>`

**Screenshots**
The field is in a very unusual shape.
[Imgur](https://imgur.com/XD25spY)
[Imgur](https://imgur.com/bVfjcXl)

**Courseplay version**
Version used:  **v7.0.1.12** 

**Log**
[Course generation](https://gist.github.com/koza1258/83a1b006613888be372c2339c8178709)
[Game not load freeze on 85%](https://gist.github.com/koza1258/74905ce54f94a454325e56c1a2b33151)

**Map**
Erlengrat (standard)

**Vehicles/ implements involved**
6250 R(no mod) + BREADAL K165(no mod) 

**Relevant script mods**
I don't know Which is the Relevant. :(
- (Version: 1.0.0.0) FS22_additionalCurrencies
- (Version: 1.0.0.0) FS22_additionalGameSettings
- (Version: 1.5.0.0) FS22_aPalletAutoLoader
- (Version: 1.0.5.1) FS22_AutoloaderStockPackjw
- (Version: 1.0.0.0) FS22_AutoloadTruckPackDf
- (Version: 1.0.0.0) FS22_BaleCountSystem
- (Version: 1.0.0.2) FS22_BewareOfStraw
- (Version: 1.0.0.0) FS22_ClaasArion600
- (Version: 1.0.0.1) FS22_claasDiscoPack
- (Version: 1.0.0.1) FS22_claasJaguar980
- (Version: 7.0.1.12) FS22_Courseplay
- (Version: 1.0.0.0) FS22_cropGrowthStageInfo
- (Version: 1.1.0.0) FS22_cultivatorFieldCreator
- (Version: 1.0.0.0) FS22_Filllevelwarning
- (Version: 1.0.0.0) FS22_flieglFlatbed
- (Version: 1.0.0.0) FS22_Frontor_Labbe_Rotiel
- (Version: 1.0.0.0) FS22_guettlerAvant45
- (Version: 1.0.0.0) FS22_guettlerMatador610S
- (Version: 1.0.0.0) FS22_Guettler_Matador_30
- (Version: 1.0.0.0) FS22_HayLoft
- (Version: 1.0.0.0) FS22_hydraulicBaleFork
- (Version: 1.0.0.0) FS22_JD_1775NT_2022
- (Version: 1.0.1.0) FS22_KroneSwadro2000
- (Version: 1.0.0.0) FS22_LicensePlateManager
- (Version: 1.0.0.0) FS22_lommaZDK1802Pack
- (Version: 1.0.0.0) FS22_MachineryForBigBags
- (Version: 1.0.0.0) FS22_Magsi_Interface
- (Version: 1.1.0.0) FS22_MilkExtension
- (Version: 1.0.0.0) FS22_moreHoneyPalletPlaceOptions
- (Version: 1.3.0.0) FS22_netWrap_addon
- (Version: 1.0.0.0) FS22_paintAndTerraformAnywhere
- (Version: 1.1.0.0) FS22_QuickCamera
- (Version: 1.0.0.1) FS22_RefreshContracts
- (Version: 1.0.0.0) FS22_rootCropStorage
- (Version: 1.0.0.0) FS22_samaszTwist600
- (Version: 1.0.0.0) FS22_SuperPerson
- (Version: 1.0.1.0) FS22_Telehandler_BigBag_Lifter
- (Version: 1.3.0.0) FS22_twine_addon

**Comment by pvaiko** [comment]
The fact that the generator fails on this field, with all those nooks and island and those narrow spaces, especially with 29 m working width is no wonder (actually, I was surprised that at least once it was able to generate a course for that field with 29 m). 

The problem we need to fix is that such a generation error is not handled correctly, somehow the broken course seems to be still assigned to the vehicle.

**Comment by Albatrozs112** [comment]
@Tensuko Nothing change, again this error with grapes
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8620614/log.txt)
