### ISSUE TITLE
[Question] Eckverhalten Mähdrescher

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1417]
Hallo Leute
ich habe seit kurzem ein merkwürdiges Verhalten bei scharfen Vorgewendeecken festgestellt:
![fsScreen_2022_04_18_11_33_13](https://user-images.githubusercontent.com/24860501/163797885-b4256555-a9af-4141-81e1-8592ab03a419.png)
![fsScreen_2022_04_18_11_33_16](https://user-images.githubusercontent.com/24860501/163797909-d5ea4cae-4e41-48ce-a75d-eb0acd13ba51.png)
Hier hebt er das Schneidwerk an und fährt (mit Lenkeinschlag) weiter vor:
![fsScreen_2022_04_18_11_33_18](https://user-images.githubusercontent.com/24860501/163797959-95220461-0cd3-4902-b9ea-2578b94a5f13.png)
relativ weit:
![fsScreen_2022_04_18_11_33_22](https://user-images.githubusercontent.com/24860501/163797978-fb338d8b-16d3-4aa1-90ff-0c3603df4510.png)
dann setzt er ziemlich gerade zurück:
![fsScreen_2022_04_18_11_33_24](https://user-images.githubusercontent.com/24860501/163798057-bb762a5c-cb3b-4368-a2c0-768965554c3b.png)
![fsScreen_2022_04_18_11_33_28](https://user-images.githubusercontent.com/24860501/163798066-b97116a0-cf71-4dbb-b3a3-c4120ea0b475.png)
![fsScreen_2022_04_18_11_33_30](https://user-images.githubusercontent.com/24860501/163798089-4946f383-85b7-4897-ad30-c8d29dbc6664.png)
und irgendwann lenkt er dann doch ein:
![fsScreen_2022_04_18_11_33_33](https://user-images.githubusercontent.com/24860501/163798129-f3c29b2c-9779-443d-9f1a-f9518463c5f6.png)
![fsScreen_2022_04_18_11_33_35](https://user-images.githubusercontent.com/24860501/163798143-26d2b000-3b22-4928-aa94-ce578c08cd46.png)
![fsScreen_2022_04_18_11_33_37](https://user-images.githubusercontent.com/24860501/163798152-8eb31567-f61b-4da8-b169-49f65e62ebd6.png)
![fsScreen_2022_04_18_11_33_40](https://user-images.githubusercontent.com/24860501/163798157-44efcaba-bc9d-4f86-9c9e-7f979073c62a.png)
das ganze ist ziemlich raumgreifend, vor einiger zeit hat der Drescher deutlich kompakter gewendet,
er muss ja nicht bis zum Feldrand zurückschieben, es würde ja - mit etwas Platz dazwischen - bis zur Fruchtkante reichen.
log:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8505195/log.txt)

lg
andreas

**Comment by Tensuko** [comment]
Eigentlich sollte Fruchtumfahrung an sein und dann das richtige Manöver gemacht werden.

**Comment by andreasthu** [comment]
Fruchtumfahrung ist an:
![fsScreen_2022_04_18_15_27_52](https://user-images.githubusercontent.com/24860501/163815803-713497af-e27f-4356-aba0-3b80d84384ce.png)
![fsScreen_2022_04_18_15_28_01](https://user-images.githubusercontent.com/24860501/163815810-19fb8ff3-12cd-4899-b046-806954d8f138.png)
![fsScreen_2022_04_18_15_28_03](https://user-images.githubusercontent.com/24860501/163815817-a0dc498e-9e5e-434e-a2fc-bc4a84241b87.png)
das wendemanöver braucht nun aber im gegensatz zu früher extrem viel platz, wurde das extra so geändert?
lg
andreas

**Comment by Tensuko** [comment]
Nein, wie ich bereits sagte, das dort auf den bildern ist wie fruchtumfahrung aus.

**Comment by Tensuko** [comment]
Bei mir wird der korrekte Turn generiert.
Neues savegame, expert mode on.
![fsScreen_2022_04_18_18_24_57](https://user-images.githubusercontent.com/27344744/163839413-562f8cff-0ec6-47d6-bc06-1dc372f5da03.png)

**Comment by Tensuko** [comment]
Ach sry, ich meinte auch nicht die Fruchtumfahrung, die war nur für die Taschen.
Wenden auf dem Feld muss aktiv sein, sonst macht er den normalen AI turn.

**Comment by andreasthu** [comment]
Ja, wenn ich wenden auf dem feld aktiviere, setzt der drescher etwas zurück und drisch paralell ein stück eine zweite bahn ab, und dann wendet er im Feld. 
Ich meinte aber schon das wenden ausserhalb des Feldes. Bei vorigen versionen wendete der Drescher kompakter.
D.h. am ende stoppte er, schlug die lenkung ein und fuhr ein kleines stück vor, stoppte, lenkte in die gegenrichrung, und fuhr etwas zurück, aber nicht soweit das das schneidwerk den Feldrand erreichte, sondern etwa soweit bis zu hälfte der gedroschenen ersten bahn, dann schlug er wieder anders ein und begann die querbahn zu dreschen.
Ich kann morgen mal fotos dazu machen.
Lg
Andreas

**Comment by Tensuko** [comment]
Wenden auf dem Feld ist in deinen Bildern aus.
Wenn ich das ausschalte ist es wie bei dir, schalte ich das ein, ist es so wie es sein soll.

**Comment by andreasthu** [comment]
Ja, das wenden auf dem feld ist ausgeschaltet.
Aber trotzdem bräuchte der drescher auch so nicht bis zum kompletten Feldrand zurückfahren. Es würde reichen, wenn er bis zur getreidekante zurückschiebt und dann weiterdrischt.
Lg
Andreas
