### ISSUE TITLE
Maybe im just stupid[Question]

### ISSUE THREAD

**Issue by smoelf** [Courseplay/Courseplay_FS22#1422]
But after the .12 update with Expert mode. i cant find the option to turn it on. So now i miss all the usefull options from the mini HUD.

![2022-04-19](https://user-images.githubusercontent.com/47252179/163956538-ebdf9263-0aeb-4254-96e0-b5683e84535d.png)

**Comment by Tensuko** [comment]
Which language ? Logfile ?

**Comment by smoelf** [comment]
Its danish

**Comment by smoelf** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8511577/log.txt)

hope this works :P

**Comment by Tensuko** [comment]
Where did you download it.....
Available mod: (Hash: 9c2d754529522dc8028434fc8f06ef91) (Version: 7.0.1.9) FS22_Courseplay

**Comment by smoelf** [comment]
got it here, :P https://farmingsimulator22mods.com/
was using .11 before i updated yesterday. 

dont think the show course and copy/ phase course was in 0.9

**Comment by smoelf** [comment]
hehe yeah it says 0.9 now in the menu also... something went wrong.. ill try to delete it in the ingame menu and DL again... and see what happens

**Comment by schwiti6190** [comment]
@smoelf Always download cp from here pls: https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.0.1.12 
Every other site download is not offical supported.
You can give it a try with the newest verision.

**Comment by smoelf** [comment]
They f* up. tryed to DL again... and it said v 0.9 again.. 

So DL from here now and got the .12 Version now.. 

Funny is i have used that WWW since i startet playing fs17 :p 

But thx for the help m8.. 

/cheer 

Keep up the awesome work
