### ISSUE TITLE
[BUG_SP] Game Loading stuck after Updating to 1.4, can't play anymore

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1423]
Hi
after Updating the game this morning to 1.4, et CP to last version, game loading stuck a 85%
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8511773/log.txt)

Game was still working fine yesterday.

**Comment by Joa-Designer** [comment]
Same issue here, just after the update. Also updated courseplay.

**Comment by Tensuko** [comment]
Give us time pls. This may also be giants problem

**Comment by Joa-Designer** [comment]
Update: Courseplay mod works FINE. 

I've started a new savegame with 1 mod at a time and every mod works fine. However, when I add in all mods the game won't load past 85%. I hope this info helps. Seems like two or more mods are conflicting. 

Thank you.

**Comment by Tensuko** [comment]
2022-04-19 11:26 Error: Running LUA method 'update'.
dataS/scripts/specialization/TypeManager.lua(228) : attempt to index local 'spec' (a nil value)

**Comment by SchTummeL** [comment]
For me, the savegame starts shortly after the update, but after starting Courseplay, no more entries are recognized. Neither mouse movements nor keystrokes have any effect.

Farming Simulator 22 (Steam)
  Version: 1.4.0.0 b16523
Installed Mods: 
- Available mod: (Hash: 589d1b1ef35d41ebd6b94cd9e8e8efb0) (Version: 1.0.0.0) FS22_3rdPerson
- Available mod: (Hash: ab3cf294392f61318df41ff91171114e) (Version: 1.0.1.0) FS22_additionalFieldInfo
- Available mod: (Hash: d03a1495313c225f4540864cb9182df9) (Version: 1.0.0.0) FS22_airHoseConnectSound
- Available mod: (Hash: dcfd6d4feb203970a92709536f6cd7a5) (Version: 0.0.1.6) FS22_AIVehicleExtension
- Available mod: (Hash: ae3df20018a236d85ff474e8f3a6435c) (Version: 1.7.0.0) FS22_aPalletAutoLoader
- Available mod: (Hash: 182ea049e9d3ebf13569261b0392dca9) (Version: 2.0.0.5) FS22_AutoDrive
- Available mod: (Hash: 566fb649ed4e5834db1b96e0bac857f9) (Version: 7.0.1.12) FS22_Courseplay
- Available mod: (Hash: 38d4e33aee97945df08f9072a7356d09) (Version: 1.0.0.0) FS22_cropGrowthStageInfo
- Available mod: (Hash: 9b94704c10b51a8a9e2dcc01f21f3491) (Version: 1.1.0.0) FS22_frontloaderAxleLockRemover
- Available mod: (Hash: 15adafce7038589ebfdd9d004d49b728) (Version: 2.1.6.0) FS22_guidanceSteering
- Available mod: (Hash: 00537b69ff1e401d8500b1d6edd7847a) (Version: 1.0.0.0) FS22_InfoDisplayExtension
- Available mod: (Hash: 954e7e07c51051f34af74944745a5c36) (Version: 2.0.0.0) FS22_manualAttach
- Available mod: (Hash: 78ddd168268330dec7573e69f7d63755) (Version: 1.0.0.0) FS22_paintAndTerraformAnywhere
- Available mod: (Hash: 5a2406b07b3127420cee8f37ca7a382d) (Version: 1.1.0.0) FS22_ProductionInspector
- Available mod: (Hash: 5f00630e6459cc4b5b246452f00e40ca) (Version: 1.0.1.2) FS22_realDirtColor
- Available mod: (Hash: fac7731901e2f4168149cd25d0aa2729) (Version: 1.0.0.0) FS22_realDirtColorTracks
- Available mod: (Hash: 2dd8158aafdfde86fe2d552c2d46f2df) (Version: 1.0.0.0) FS22_realDirtFix
- Available mod: (Hash: f49dff764f9e3eb2c81b7f5960519efe) (Version: 1.0.1.6) FS22_SimpleInspector
- Available mod: (Hash: 39759122f3e098663446f62380ec6bcc) (Version: 1.4.0.0) FS22_strautmannSEK802_palletLoad
- Available mod: (Hash: 45b329950e139a5a4e2d3f24203f2007) (Version: 1.0.0.0) FS22_tensionbelt
- Available mod: (Hash: 9bbf1ca3903b0fddc13612d43ba0cb25) (Version: 1.1.0.0) FS22_VehicleControlAddon
- Available mod: (Hash: bf09d2fe9f92ca69c4ef580f54a21953) (Version: 1.0.0.0) FS22_Workplan
- Available mod: (Hash: fa093fb724d33da97b6a253902c90f82) (Version: 1.90 Beta) VehicleInspector

**Comment by Tensuko** [comment]
Pls don't post in panic mode, I need logfiles...

**Comment by NeonRider1999** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512242/log.txt)


Also so sieht meine Log aus. Jeder Script schmeißt den Fehler Error: No more Intervall Timers

**Comment by Tensuko** [comment]
> Jeder Script schmeißt den Fehler

Es ist schon mal nicht jeder Script, das kann ich zu 100% sagen.

**Comment by schwiti6190** [comment]
@NeonRider1999 Du wirst woll alle mods einmal durchtesten, d.h. nacheinader hinzufügen und schauen wo der Konflikt ist.
CP + persion farming lädt und läuft soweit.

**Comment by Chico0008** [comment]
It's weird
tried several things

with 1.4 if you try to load a game with CP or Precision, game won't load

Without CP nor Precision, game load OK

If you try to add Precision, you'll have the exact same error

2022-04-19 12:46 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/internalMods/FS22_precisionFarming/scripts/specializations/ExtendedWearable.lua(39) : attempt to index local 'spec' (a nil value)

**Comment by NeonRider1999** [comment]
@schwiti6190 Ja bin schon am Testen.

**Comment by Joa-Designer** [comment]
@Tensuko (sorry for the tag) here are my log file.
[
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512310/log.txt)
](url)

**Comment by Tensuko** [comment]
Calm down, CP Update for PC will come soon and the Update for the LUA Error is Giants part, they found the problem.
So relax and use the good weather (at least in north germany we have sunny weather) :D

**Comment by Sasch10** [comment]
> Calm down, CP Update for PF will come soon and the Update for the LUA Error is Giants part, they found the problem. So relax and use the good weather (at least in north germany we have sunny weather) :D

Ist schon bekannt, dass die CP-Hilfe, die neue Hilfe des Precison Faming Dlc's überblendet?

**Comment by ChaserCiC** [comment]
Hi guys,
just want to mention that on my system it was a different mod which causes the 85% issue, even that CP was the last in the logs and the first point to look [at.] After I removed "Configure Maintenance" (which I used because of the surreal weathering and maintainance costs) everything startet up as usual. 

Both Log files, with and without CM:

[log_withCM.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512562/log_withCM.txt)
[log_woCM.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512563/log_woCM.txt)

**Comment by schwiti6190** [comment]
> > Calm down, CP Update for PF will come soon and the Update for the LUA Error is Giants part, they found the problem. So relax and use the good weather (at least in north germany we have sunny weather) :D
> 
> Ist schon bekannt, dass die CP-Hilfe, die neue Hilfe des Precison Faming Dlc's überblendet?

Wird in der nächsten version gefixt sein.

**Comment by Chico0008** [comment]
> Hi guys, just want to mention that on my system it was a different mod which causes the 85% issue, even that CP was the last in the logs and the first point to look [at.] After I removed "Configure Maintenance" (which I used because of the surreal weathering and maintainance costs) everything startet up as usual.
> 
> Both Log files, with and without CM:
> 
> [log_withCM.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512562/log_withCM.txt) [log_woCM.txt](https://github.com/Courseplay/Courseplay_FS22/files/8512563/log_woCM.txt)

I confirm, same here, i had this mod too, deactivated, then my game with CP et Precision start again.
Thanks

**Comment by Tensuko** [comment]
![unknown](https://user-images.githubusercontent.com/27344744/163997964-9bd35116-cddf-4b60-bb1b-ae1ca2bcc39d.png)

**Comment by schwiti6190** [comment]
Giants patch was released :)
