### ISSUE TITLE
[BUG_SP]With Courseplay loaded the PF help is not there.   Also at time the individual environmental map for fields does not appear when zooming in.

### ISSUE THREAD

**Issue by caracarn3** [Courseplay/Courseplay_FS22#1425]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Load Courseplay

**Actual behavior**
Courseplay help appears to conflict with PF help.  When I remove CP and then load game again the PF help is there.  

**Expected behavior**
Both help sections should be present  (PF and CP)

**Screenshots**

**Courseplay version**
Version used: 7.0.1.12

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Wait for CP Update, fix already in the next Release.

**Comment by Tensuko** [comment]
Fixed in 7.0.1.13
