### ISSUE TITLE
[BUG_SP] Map stops loading at 85%

### ISSUE THREAD

**Issue by Hausi739** [Courseplay/Courseplay_FS22#1427]
Hi, i have updated Courseplay to version 1.0.7.12 yesterday. And i played for 3 hours and then i turned my pc off, when i turned it on today my Map (Niedersachsen) stopped loading at 85%.
 
I think that Courseplay is the issue because at the end of my log there stands: 
2022-04-19 18:44 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/simon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpInfoTexts.lua:49: attempt to index local 'spec' (a nil value)

i tried reinstalling courseplay, starting the map without courseplay (that worked), saving it and starting it with courseplay again that all didn't work. i even tried an backup savegame that i made after updating it, that dind't work too.
 
i attached the log file, just in case
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8514960/log.txt)

**Comment by CBene81** [comment]
Der BUG ist auch im MP

**Comment by Plopsi** [comment]
Main Reason on my server and all of whom i personally know it was ParkVehicle (MP+SP), but might also be others or even mod-combinations, but give it a try.

**Comment by Tensuko** [comment]
Those are the results from other Mods Errors.
That is becouse of the faulty Giants Patch.
Can only wait for Giants Patch to come out.
