### ISSUE TITLE
[Feature] manuell einen Kurs einfahren

### ISSUE THREAD

**Issue by taylorfx** [Courseplay/Courseplay_FS22#1429]
Zuerst erstmal, Super MOD, funktioniert klasse, ohne CP, wäre der LS22 nicht wirklich viel wert
Aber wie immer viele User, viele Wünsche
Auch ich hätte da Einen und zwar: Es wäre ein super Feature, wenn man einen Feldkurs auch selbst von Hand einfahren könnte. Ich ziele da im Besonderen auf Grasflächen hin. Diese sind ja oft ziemlich unregelmäßig, rund, gezackt und haben kaum beschreibbare Formen. Da gerät die Routing-Routine an Ihre Grenzen und das ist auch ganz verständlich. Mähen geht eigentlich immer, Wenden und Schwaden in den meisten Fällen, beim Pressen wird es dann aber schwierig, da die Pressen in den Wendekreisen dann nicht mehr mitkommen, die Schenkel teilweise zu kurz sind oder auch schon mal Ballen im Weg liegen. Die Probleme könnte man bei einer manuellen Kurserstellung relativ einfach berücksichtigen. Wenn man es auf Grasbearbeitung beschränkt, könnte man möglicherweise sogar auf ein Heben und Senken der Geräte verzichten da man ja auch durchfahren kann um das Pressen einfacher zu machen.
Ich glaube eigentlich, das es vor etwas längerer Zeit so eine Funktion schon mal gab (LS15 oder LS17), da ging aber das Pressen noch nicht
![Kurs-1](https://user-images.githubusercontent.com/6141754/164170174-939b5463-b353-48d1-91f5-b9296eec19ef.png)

**Comment by Tensuko** [comment]
Werf mal einen Blick in das ingame Hilfe Menu.
Da haben wir entsprechende Einträge.

**Comment by taylorfx** [comment]
Der Aufnahme-Button im HUD ist nach meinem Verständnis da, um einen Feld-RAND-Kurs einzufahren. Ich habe aber von einem Feldkurs geschrieben, ich will nicht den Feldrand erzeugen, der für ein Routing benötigt wird, der ist ja immer schon da, auch bei den Grasflächen, ich würde in den Sonderfällen den Kurs gerne selber einfahren und speichern können

**Comment by 60erjonny** [comment]
..nun dazu gibt es hier einige Möglichkeiten den Kurs Individuell generieren und gestallten zu lassen...gut es gab dazu schon, im LS19 einen Editormodus, aber ob der wieder kommt ist wohl jetzt nicht erste Prio...und bis jetzt habe ich alles mit CP "lösen können...aber ganz ehrlich, dann kannst du es gleich alles selber mähen und nicht CP es machen lassen...:-)

**Comment by taylorfx** [comment]
@60erjonny wo ist jetzt bitte der Unterschied, mähe ich selber, muss ich selber wenden, selber schwaden, selber pressen, da würde ein selbsr eingefahrener Kurs sehr gut kommen, das Routing in CO funktioniert ja wirklich gut, aber es hat logischerweise auch seine Grenzen. Das ist ja auch nicht schlimm, der selbsteingefahrene Kurs ist nur eine weitere Möglichkeit einen Kurs zu generieren.

**Comment by taylorfx** [comment]
@haamic, Danke für das Angebot, ich werde den "falschen Feldrandkurs" bei nächster Gelegenheit einfahren und melde mich dann bei dir. Ich nehme aber auch gerne eine Anleitung, wie man diesen Kurs in den fahrbaren Arbeitskurs konvertiert. Ich muss zuerst mein Game wieder richtig zum laufen bringen. 1.4.0 hat mir wohl die Inputbindung zerbröselt und die versuchte Programm-Reparatur dann auch noch die Map zurückgesetzt in der ich mühevoll kilometerweise die bescheuerten Zäune abgebaut hatte. Für mich war 1.4.0 ein Griff ins Klo. In Zukunkt wird vor einem Update wieder alles gesichert

**Comment by 60erjonny** [comment]
@taylorfx Möglichkeit...? Wenn es machbar ist, natürlich... Unterschied...? Nun, das es sich hier, immer noch um ein Spiel handelt und nicht die harte Realität...aber Egal...hier ist zu und deswegen, bin ich hier auch weg...

**Comment by Tensuko** [comment]
Es wird kein Kursaufzeichnen wie aus dem 19er geben.

**Comment by taylorfx** [comment]
für Haamic,
hoppla keine Ahnung wie ich dich kontaktieren kann ??

**Comment by taylorfx** [comment]
@haamic Hallo, hat eine Weile gedauert, einen Kurs einzufahren und ist doch nicht so einfach wie gedacht, da muss ich wahrscheinlich noch mal nacharbeiten, aber wenn du mir diesen Feldrandkurs konvertierst habe ich die Hoffnung, das ich das dann an deinem Beispiel auch selber hinbekomme und es hat auch eine Weile gedauert, bis ich herausgefunden habe, wie ich dich kontaktieren kann (wenn du mir hier antwortest :-) )

[CP-1.txt](https://github.com/Courseplay/Courseplay_FS22/files/8552244/CP-1.txt)

Gruß

Frank

**Comment by taylorfx** [comment]
@taylorfx 

Test

**Comment by haamic** [comment]
@taylorfx Leider müsstest du jetzt warten, bin im Krankenhaus. Aber vielleicht kann ich von der Ferne etwas tun.

**Comment by taylorfx** [comment]
Oweh, hoffentlich nichts schlimmes,
ist überhaupt kein Problem, ich übe mich in Geduld und wünsche gute Besserung.
Ich habe mal gerade den Dateiaufbau verglichen, der ist bei den Kursranddateien ja schon ein bisschen anders. Kopf und Fuss auszutauschen wäre ja kein Problem und die "Pipe" kann man ja auch locker durch "</wp>" ersetzen. Wie man das "<wp>" in einem Lauf an den Zeilenanfang generieren könnte fällt mir so auf Anhieb nicht ein. Die Parameter zwischen den Koordinaten scheint es ja dann nicht zwingend zu brauchen, aber wenn man raus bekäme wofür die stehen (heben, senken, starten, stoppen), dann wird es interessant.
Wenn ich das so sehe, bestätigt sich meine Vermutung, das das Feature selber einfahren für die Jungs ein Klacks wäre mit einer geringen Fehleranfälligkeit der Funktion. Schade, das Tensuko das hat mal gleich locker vom Tisch gewischt hat. Ich finde zwar das programmierte Routing richtig gut gelöst vom Ergebnis her, da muss man schon den Hut ziehen, nur leider geht ein normales Vorgewende nicht dreimal um den Acker, sondern ist nur an zwei gegenüberliegenden Kanten und hinten heißt es  auch noch Nachgewende außer beim Dreschen natürlich.

Aber noch mal Gute Besserung

Gruß
Frank

**Comment by taylorfx** [comment]
Oh, jetzt habe ich rumlameniert ohne zu sehen, das du die Datei ja schon angehängt hast, Erst mal Danke, ich werde heute Abend testen, wie bekommst du das <WP> anjeden Zeilenanfang, ich vermute ja wohl, nicht von Hand, oder?

Gruß
Frank

**Comment by haamic** [comment]
@taylorfx  hallo Frank, Danke wird schon werden, ist halt das weswegen man sich (so wie ich) heutzutage schnell mal auf der Intensivstation wiederfindet. 

Ich "excele" gerne und darüber Wandel ich die Kurse. Zumindest für meinen Gebrauch konnte ich mir damit helfen. 
Bekommst du sicher selber gewandelt, im Vergleich der beiden Kurse.
Gruss Micha

**Comment by taylorfx** [comment]
Okay, da darfst du ja wahrscheinlich nur eingeschränkt elektronisches Gerät benutzen wegen der vermeintlichen Störgefahr, da hatte ich es vor cirka 5 Wochen besser, ich habe aber nur 10 Tage intensiv im Wohnzimmer gecoucht, den ganzen Tag Homeoffice gemacht, ein paar unangenehme Symptome gehabt, bei uns nennt man das "die Freck han" und und konnte mich dann freitesten.

also dann noch mal, Vielen Dank für die Hilfe und Gute Besserung

Gruß

Frank

**Comment by taylorfx** [comment]
Hallo Micha,

wenn es wieder besser geht, Notepad++ ist das Tool für solche Änderngen, mit "Block-Editor " im Notepad++ kann man vor jede Zeile blitzschnell beliebige Zeichen einfügen, also ein Befehl für den markierten Bereich und am Ende wie gehabt suche "|" - ersetze mit "was das Herz begehrt"

Gruß

Frank

**Comment by haamic** [comment]
@taylorfx notepad++ ist schon klar. Es ging aber, Glaub ich, nicht nur darum Zeilen Anfang und Zeilen Ende hinzuzufügen, sondern auch die mittlere Koordinate zu entfernen. Das geschieht nicht händisch, in einzelnen Schritten, wie in np++. Ich kopier die kursdaten in excel und hab gleich die gewandelten Zeilen fertig da, ohne was selbst daran zu tun. Viele Wege führen nach Rom....das Ziel muss nur funktionieren.

**Comment by taylorfx** [comment]
@haamic Guten Morgen, freche Frage, weißt du, wofür die geänderten Parameter stehen, alo die 2. Zahl im Original, die du löschst ( 34,72) und die Parameter, die du in der neuen Kursdatei anpasst und dazufügst?

Feldrandkurs:
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<customField name="CP-1">
    <vertices>
142.27 34.72 -507.03|
142.43 34.69 -513.13|

neue Kursdatei:
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Courses>
    <Course name="Fahrkurs CP-1" workWidth="5.900000" numHeadlands="1" multiTools="1">
        <waypoints>
<wp>142.27 -507.03 - - - -1 - - -</wp>
<wp>142.43 -513.13 - - - -1 - - -</wp>

da wären: workWith, numHeadlands und multitools und der Parameterstring "- - - -1 - - -". Der besteht ja quasi aus 7 Variablen, respektive Ihren Platzhaltern. Da habe ich bis jetzt noch keine Info zu gefunden

Dein handgenerierter Kurs funktioniert übrigens Klasse, Schwader und Presse haben perfekt gearbeitet, es bleibt viel weniger Gras liegen, eigentlich fast keins und es geht natürlich deutlich schneller, weil die ganze Wenderei mit den Spitzkehren wegfällt.

Gruß
Frank

**Comment by haamic** [comment]
@taylorfx hallo Frank, schön das der Kurs läuft. Die Koordinate die da nicht benötigt wird, weiß ich nicht was das ist, könnte vielleicht die Höhe sein vom Gelände? Echt keine Ahnung sorry, die workwith ist ja egal, da du den Kurs ja eh mit deinem angehängten Gerät eingefahren hast. Ich hatte die Angaben aus einem normalen Arbeitskurs übernommen und so drin gelassen. die headland immer auf 1. man gaukelt CP quasi einen arbeitskurs mit einem vorgewende vor, was aber in Wirklichkeit dein kompletter Fahrkurs ist. Geht evtl. auch mit "0", aber egal, CP soll ja nur so fahren, wie selbst eingefahren. Die -1 in den 7 waypoint Optionen, konnte ich mir aus anderen Kursen ableiten. Bedeutet headland 1, würde er auf headland 2 wechseln stünde da -2. Was in deinem Fall dir vielleicht auch geholfen hätte und ich auch schon probiert habe ist, den Kurs normal erstellen lassen für Feld/Wiese und dann die Datei bearbeiten.die "True"s in den 7 waypoint Optionen für Beginn und Ende einer Wendung durch "-" ersetzen.da fährt CP quasi ohne zu bremsen auch die Strecke ab, wendet in einem Zug ohne Gerät anzuheben. Erwischt aber evtl auch weniger Gras, als beim selbsteingefahrenen Kurs.
