### ISSUE TITLE
[BUG_SP] Nach Kursladen keine Tastenreaktionen mehr

### ISSUE THREAD

**Issue by astra16v** [Courseplay/Courseplay_FS22#1432]
Hallo, nachdem Update auf 1.4 reagieren keine Tasten mehr sobald ich den Kurs geladen habe. Zu erst ist mir aufgefallen das die Tastenbelegung für Courseplay weg war (rechte Maustaste) diese kann ich auch nicht mehr in den Einstellungen aktivieren. Und sobald ich einen Kurs geladen habe kann ich weder aus dem Fahrzeug aussteigen noch in ein anderes switchen. Das Spiel muss ich dann mit ALT+F4 beenden. Das komische ist allerdings, das ich gestern spielen konnte ohne probleme und da war auch das Update auf 1.4 schon installiert worden. Erst gestern abend wo ich noch mal kurz zocken wollte kamen die fehler.

Anbei die Log Datei
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8529481/log.txt)
.

**Comment by Tensuko** [comment]
Da ich keinen Error in der log sehe kann ich dazu auch nichts weiter sagen.....

**Comment by astra16v** [comment]
Hab eben noch verschiedene dinge ausprobiert. Also Kursladen über das HUD funktioniert nicht so wie oben beschrieben. Wenn ich allerdings den Kurs über das Menü lade kann ich ohne probleme spielen.

**Comment by r0lf90** [comment]
Habe das gleiche Problem. Zunächst hat auch mit 1.4 alles funktioniert, dann aber auf einmal gleiches Problem.
![20220420234335_1](https://user-images.githubusercontent.com/104105828/164445656-70d514c2-b7cf-4d28-8b3e-cc9b1dbdf518.jpg)
Das Bild noch zum Hinweis, das ist es, was es mir oben an der Tastenbelegung plötzlich anzeigt. Der Test war in einem neuen Savegame mit Courseplay als einzig geladener Mod. Im Logfile findet sich nichts.
Das ganze passiert, wenn ich über das HUD ins Menü gehe und einen Kurs generiere.

**Comment by Tensuko** [comment]
Ich kann die Fehler nicht nachvollziehen.
Bitte mal steps to reproduce ausfüllen und es kann auch sein, dass ihr noch auf die .13 warten müsst von uns...

**Comment by r0lf90** [comment]
Ausgehende von einem neuen Save mit Courseplay als einzig geladenem Mod bei mir:
Steps to reproduce:
1. Drescher auf das Feld fahren.
2. Rechtsklick um das Courseplay-HUD zu öffnen
3. auf "kein Kurs" klicken, um den Kursgenerator zu öffnen
4. Den Kurs per Klick auf das entsprechende Feld generieren lassen
5. Menüs per ESC schließen
--> Ergebnis ist dann das oben gezeigte Bild und der Umstand, dass kein Tasteninput mehr funktioniert. Mausklicks gehen aber noch, komme also z.B. über einen Klick auf den Fahrzeugnamen in das Fahrzeugmenü und bei einem klick auf den Kursnamen in das Helfermenü....

Hoffe mal, dass das weiterhilft....

**Comment by Tensuko** [comment]
Genau so, nicht reproduzierbar.
Vlt hilft die neue Version, vlt kriegen wir die heute schon raus.

**Comment by r0lf90** [comment]
Komisch, scheint ja auch irgendwie ein SEHR spezifischer Bug zu sein. Dann hoffen wir mal auf die neue Version.

**Comment by patch110** [comment]
i have also had this issue but for me it seemed to only happen on existing save game not fresh start. hope this helps

**Comment by astra16v** [comment]
Steps to reproduce: (egal ob die Fahrzeuge auf dem Feld oder unter einer Halle stehen und egal welchesAnbaugerät, Sähmaschine, Düngerstreuer, Drescher etc)

1. Ins Fahrzeug switchen (Tab)
2. HUD öffnen (STRG+C (da rechte Maustaste bei mir nicht mehr geht und in den Einstellungen nicht mehr angenommen wird)
3. auf --/-- klicken
4. Kurs ausfählen
5. Kursladen 
6. Kurs aktvieren
7. ESC

Und das war es dann bei mir. Keine Tastenreaktion mehr. Das einzige was sich noch bewegt ist der Mauscourser und könnte wenn ich wollte AD fahren lassen.

**Comment by MiMiNator** [comment]
Gerade das Speil neu gestartet:
Fahrzeug A hatte bereits einen Kurs geladen, den Job habe ich dann gestartet, dann zu Fahrzeug B gewechselt, einen Kurs geladen  und auch diesen Job gestartet. Danach konnte ich problemlos zu einem anderen Fahrzeug wechseln.

**Comment by lxk3il** [comment]
Kann den Fehler bestätigen.
Auch hier tritt der Fehler auf, dass nach Laden eines Kurses keine Tastatureingaben mehr möglich sind. 
Ebenfalls taucht die Meldung `2022-04-21 13:16 Warning: Tried reverting to input context [] which is not defined.` im Log auf:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8532869/log.txt)

**Comment by Tensuko** [comment]
Ich zitiere mich mal selber:

> Genau so, nicht reproduzierbar.
> Vlt hilft die neue Version, vlt kriegen wir die heute schon raus.

**Comment by Tensuko** [comment]
Test the new Version pls.
I had no Issues at all with all my Mods (arround 180) and no keybind Issues or anything!
