### ISSUE TITLE
[Question] Einstellungen speichern

### ISSUE THREAD

**Issue by OpiGunnar** [Courseplay/Courseplay_FS22#1436]
hallo,warum kann man gemachte einstellungen nicht speichern?
nach jedem einloggen muss ich erstmal : vorhandene kurs, tastenbelegung,experten modus usw. de/ bzw aktivieren.
erlich,es nervt ein wenig, vorallem wenn der server schon was länger läuft und mehrere spieler schon ihre kurse gemacht haben!
wäre schön wenn man das speichern könnte

lg
Opi

**Comment by Tensuko** [comment]
Das wird alles gespeichert!
Die Frage wäre jetzt eher warum das bei dir anders ist und dazu wäre mal ein logfile hilfreich...

**Comment by schwiti6190** [comment]
@Taylor1684 Einfach sp starten einstellen passend setzten(geht nur um nutzer einstellungen) speichern und dann sind die gesetzt. Das liegt daran das du Client bist. Ist nicht so einfach vlt. implementieren wir das später mal :)

**Comment by Taylor1684** [comment]
@schwiti6190 Danke für den Tipp. Funktioniert jetzt.

**Comment by OpiGunnar** [comment]
ausprobiert,funzt,super 👍👍👍

aber das muss man ja erstmal wissen,danke für den tip

lg Opi

Am Do., 21. Apr. 2022 um 18:32 Uhr schrieb schwiti6190 <
***@***.***>:
