### ISSUE TITLE
[BUG_SP] Courseplay stops autoload trailers

### ISSUE THREAD

**Issue by tintong** [Courseplay/Courseplay_FS22#1438]
Hello,

Not sure if this is a Courseplay bug or the autoload scripts, but when testing with just Courseplay and one other mod enabled, the autoload trailer does not function. If I don't use Courseplay, then the autoload trailers work fine.

To reproduce this:

Use any trailer with autoload enabled, drive to either round bale / square bale / pallet and autoload does not function.
When attaching trailer, none of the autoload options show up either.

**Courseplay version**
Version used: 7.0.1.0

This is happening on FS22 1.4 patch and 1.4.1 patch. Previous versions work fine.

I can attach a log if needed, but when I look through the log, no errors are actually reported.

The map I am playing on is: Mecklenburg Lake District
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=237974&title=fs2022

This tractors I use are the standard Claas in game tractors. Does not matter which tractor, this happens on all.

The trailers with autoload that I tested this on are:
Aguas Tenias Platform Trailer Pack - https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=234121&title=fs2022

Autoload Stock Trailer Pack - https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=233456&title=fs2022

Pallet Autoload Specialization - https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=228819&title=fs2022

Any help would be appreciated please

Thanks

**Comment by Tensuko** [comment]
We already work together with Achimobil for its AutoLoadMod to work with Courseplay.
Pls have patient.

**Comment by tintong** [comment]
Thanks. Is there anyway I can help with this please?

**Comment by Tensuko** [comment]
yes you can, have patient and not stop us from working on it :)
