### ISSUE TITLE
[BUG_SP] Creation of a vineyard irrigation path.

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#1440]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Creation of a vineyard irrigation path.

**Actual behavior**
It locks all with screenshot as seen in the attached photo.

**Expected behavior**
The problem described above occurs when creating the path as it is from Generate Path

**Screenshots**
![Screenshot_13](https://user-images.githubusercontent.com/24955554/164503528-244eeee4-50c9-4abd-8f05-668e50136944.jpg)

**Courseplay version**
Version used: last branch manual

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8532612/log.txt)

**Map**
FermeBeyleron

**Vehicles/ implements involved**
Which vehicle or implement? Tony 10900 TTR/690:   MERCURY 4000L
Mod yes/no ? Tractor DLC  Mercury Mod

**Relevant script mods**
Autodrive present

**Comment by Roby1164** [comment]
Perfect, great schwiti6190, with this modification, it works perfectly and solved the problem ...

**Comment by Tensuko** [comment]
> Perfect, great schwiti6190, with this modification, it works perfectly and solved the problem ...

almost :)

**Comment by Tensuko** [comment]
Should be fixed now in 7.0.1.13
