### ISSUE TITLE
[Feature] Setting to collect wrapped bales only

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/Courseplay_FS22#1441]
**What is the problem this feature/enhancement solves?**
When you are about to collect an transport silage bales, you have to wait till all bales are wrapped. Otherwise the bale collector will collect gras bales as well.

**Describe the solution you'd like**
An option you can choose if you want to collect gras, silage or every typ of bales.

**Additional context**
Of course it would be possible to use a course, but you made this amazing featur that we don't need one anymore.
And thansk for all your astonishing and hard work. :)

**Comment by Resandise** [comment]
IMO all we need is an option to collect Wrapped or Unwrapped bales.

**Comment by Tritura2** [comment]
Yeah, that would be better. I was doing a lot of cotracts lately, so that i totally forgot, that it takes some time before changing to silage.
