### ISSUE TITLE
[Question] Abstände Weinreben

### ISSUE THREAD

**Issue by ChrisKeng** [Courseplay/Courseplay_FS22#1444]
Hallo an das Courseplay Team,

die Option, ebenfalls Weinberge mithilfe von Courseplay zu bewirtschaften, ist ein riesen Fortschritt in meinen Augen und als "Moselaner" ein muss :D Dafür erstmal einen rießen Dank an euch.

Hierzu habe ich jedoch eine Frage. Ich habe bis vor kurzen mit den Standard Rebabstand von 3m gearbeitet, die bei Giants so vorgeschrieben sind, dadurch jedoch, dass das ganze... Naja die Abstände sind dafür einfach zu groß, dafür braucht man dann keine Schmalspurtraktoren zukaufen, wenn ein schmaler Kompakttratkor ebenfalls reicht... Nun habe ich einen Mod, der das ganze auf 2.15m setzt. Ebenfalls auf Anfrage bei SMI und Edo bezüglich Mappa Italia, sollen die Rebabstände auf 2.5m eingestellt sein.

Nun zur Frage. Courseplay erkennt ja die Rebreihen, das ganze erkennt er ja in einem "Feld"... erkennt er dort jedoch nur die Reihenabstände von 3m?

mit dem 2.15m kann ich nur jeweils eine Reihe auswählen, jedoch nicht das ganze Feld. Mir ist klar, dass ihr nicht alle Möglichkeiten fürs Anfang umsetzen kann, aber ggf. verschiedene Abstände im Hinterkopf behalten könnt, da wohl der eine oder andere Spieler in Italien sich niederlassen wird :)

![fsScreen_2022_04_21_22_32_08](https://user-images.githubusercontent.com/101804048/164549802-d4613b75-82ea-4e8e-87a7-96379f8c3875.png)
![fsScreen_2022_04_21_22_32_01](https://user-images.githubusercontent.com/101804048/164549812-ecd7c29d-ce93-452c-a411-d184a285a25b.png)

**Comment by Tensuko** [comment]
Du musst beim normalen Abstand bleiben.
Wir können nicht noch mods die das modifizieren supporten.

Ich finde der Abstand von Giants passt gut für die Geräte. Irgendwo gibt es halt Grenzen.
