### ISSUE TITLE
Seed drill with Air Cart[BUG_SP]

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#1446]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course, 2 headland, sharp corners, Up/Down center, starting on headland

**Actual behavior**
When getting to first corner, after turning and while backing up, it appears it does not recognize the air cart and it steers off what ever directing it was facing, pulling the seeder/tractor off course, missing most of the corner.

**Expected behavior**
it to back up without issues and seed the corner of the field

**Screenshots**
![fsScreen_2022_04_21_21_49_04](https://user-images.githubusercontent.com/96673100/164586623-555821e8-62dc-442f-986a-a67428311f57.png)
![fsScreen_2022_04_21_21_49_13](https://user-images.githubusercontent.com/96673100/164586655-4be665b4-22b7-483a-99ee-f8193df91750.png)
![fsScreen_2022_04_21_21_49_21](https://user-images.githubusercontent.com/96673100/164586667-65e7c1eb-032b-4f3c-9132-18b018ca6478.png)
![fsScreen_2022_04_21_21_49_40](https://user-images.githubusercontent.com/96673100/164586685-186be037-c8cb-43ee-b53e-479532532655.png)

![fsScreen_2022_04_21_21_54_58](https://user-images.githubusercontent.com/96673100/164587163-a9707c54-972b-4d4e-a5fa-7f5dd8d3e386.png)

**Courseplay version**
Version used:  .12 and .13

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8536499/log.txt)

**Map**
Map played on.

Markhausen 4x

**Vehicles/ implements involved**

Case IH Steiger Wheeled 620
Seedhawk XL ToolBar 65FT w/ Seed Hawk 660 Air Cart (Mod)

Also with the Baurgault 3320-76 Paralink Hoe Drill w/ 7950 Air Cart (Mod)

**Relevant script mods**
AD but not active

**Comment by Resandise** [comment]
If I set the headland to Round, it doesn't need to back up on the corners, but I have to manually come back and get the corners, so either way, I would have to come back and caught the corners.

**Comment by Tensuko** [comment]
Do you rly think anyone on this planet is able to reverse that thing with all it's axes ?

Sry, but this tool can't be reversed and so the corners have to be smooth or round.
I would use round, then only one corner is not worked on.
