### ISSUE TITLE
[BUG_SP] Path creation.

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#1447]
In the latest versions the problem with the corners of the fields has returned. In particular with open angles, when they are over 90 degrees, which are created as a curve and not as an angle, with relative maneuver to carry out the complete work of the field.
as you can see in the attached photos, the 4 fields I work, all the open corners, are created as a curve, skipping pieces of land, this problem had appeared long ago, then it was solved, but now it is back .. This happens with all the types of vehicles / tools, standard and mod, small and large.

It is necessary that the angles, at least up to 110/120 degrees, are seen as angles and not as curves, in order to completely work the field.

![Screenshot_13](https://user-images.githubusercontent.com/24955554/164637850-0f8ba733-dae5-4b5c-a3a4-2168dfff2cde.jpg)

![Screenshot_16](https://user-images.githubusercontent.com/24955554/164629459-eb8ec54e-a677-478c-b70e-7a1eedea43c0.jpg)
![Screenshot_17](https://user-images.githubusercontent.com/24955554/164629624-b497edf7-9682-479d-be9f-f5251b176422.jpg)

The settings are the same as previously used, with Sharp angles, etc ...

Here is an example: Route created previously with the combine, correct angles.
![Screenshot_18](https://user-images.githubusercontent.com/24955554/164630863-5415bc32-cfb7-41d1-866c-077211cc0c99.jpg)
Same path created now .. round corners.
![Screenshot_19](https://user-images.githubusercontent.com/24955554/164632513-69f320e2-d28f-41cd-9fb7-95db5a83b02e.jpg)
Same route with different tractor and implement, same problem.
![Screenshot_20](https://user-images.githubusercontent.com/24955554/164633255-953b6cd5-d6cb-4d3b-954b-4f3eb5f1e83e.jpg)

**Comment by Tensuko** [comment]
I am pretty sure, that a logfile with the generated courses in it would help :)

What you could try to do is, check the field margin setting.
We still don't know why it sometimes shifts to a value....

**Comment by Roby1164** [comment]
I did a test, with the log cleaned up and just entering, creating a path, just to have only those data present.
I attach photos and logs, as you can see, the angle of the field, not at 90 degrees, but open, is managed as a curve, while the others are ok, all managed as angles ... I hope it will be useful.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8539527/log.txt)

![Screenshot_13](https://user-images.githubusercontent.com/24955554/164678555-d917fda8-ac81-46db-b21c-d1206dc50e1b.jpg)
![Screenshot_16](https://user-images.githubusercontent.com/24955554/164678564-08ed615a-a7ca-4605-a338-6d52226239bc.jpg)
![Screenshot_17](https://user-images.githubusercontent.com/24955554/164678585-0e306ee2-55bb-40d6-b89d-12528c5e924e.jpg)
![Screenshot_18](https://user-images.githubusercontent.com/24955554/164678601-d9102903-4571-4c36-a1fb-094cbcc62602.jpg)
![Screenshot_19](https://user-images.githubusercontent.com/24955554/164678623-335a223c-3b51-44da-a45b-dcbe9a44042e.jpg)

These are all ok
![Screenshot_20](https://user-images.githubusercontent.com/24955554/164678643-0d876bd3-183c-4f83-a46a-23a379505948.jpg)
![Screenshot_21](https://user-images.githubusercontent.com/24955554/164678676-eccdccb8-790a-45ff-8213-d0c4a5c8112e.jpg)
![Screenshot_22](https://user-images.githubusercontent.com/24955554/164678692-edafa7fa-bab5-4696-ae41-07997839f0d6.jpg)
![Screenshot_23](https://user-images.githubusercontent.com/24955554/164678703-6ea7ce3e-e817-411b-99fb-7f72dfb591cc.jpg)

**Comment by Roby1164** [comment]
Made other tests it is:
If we set the field margin from 0.4 upwards, i.e. the smallest positive field, and the overlap is increased, to at least 6%, the problem disappears.
![Screenshot_32](https://user-images.githubusercontent.com/24955554/164688369-316d9a32-c0e5-4bb5-b02d-3d4a93c08f03.jpg)
![Screenshot_33](https://user-images.githubusercontent.com/24955554/164688392-a12270ee-f7ec-4b51-a135-a8c75724a5f7.jpg)

Below these values, the problem persists, you could only increase the field margin, over 8%, and leave the overlap at 1%, but in this way, you run the risk of having the field margin not worked, but you get the same result that the angles are correct.

**Comment by Tensuko** [comment]
Its a problem of your startposition being in the corner:
One way of positioning the start in the corner, have it deep enough into the corner.
![fsScreen_2022_04_22_13_02_01](https://user-images.githubusercontent.com/27344744/164730502-ba40f077-6aed-4d44-b05b-1a42f10805e8.png)
The other way is to have it more "behind" the corner (in driving direction).
![fsScreen_2022_04_22_13_02_54](https://user-images.githubusercontent.com/27344744/164730607-d4863a16-a91c-4655-8450-b3200c5d45fa.png)

We have always suggested not to place the start point in the corner.
It can work but as you see it rly depends on where it rly is set.
I created several course with .13 Version and got always sharp corners, excpet when I place it slightly behind the corner.

**Comment by Roby1164** [comment]
> Its a problem of your startposition being in the corner: One way of positioning the start in the corner, have it deep enough into the corner. ![fsScreen_2022_04_22_13_02_01](https://user-images.githubusercontent.com/27344744/164730502-ba40f077-6aed-4d44-b05b-1a42f10805e8.png) The other way is to have it more "behind" the corner (in driving direction). ![fsScreen_2022_04_22_13_02_54](https://user-images.githubusercontent.com/27344744/164730607-d4863a16-a91c-4655-8450-b3200c5d45fa.png)
> 
> We have always suggested not to place the start point in the corner. It can work but as you see it rly depends on where it rly is set. I created several course with .13 Version and got always sharp corners, excpet when I place it slightly behind the corner.

I don't mind but I did a lot of tests, even starting in the middle of the side, counterclockwise, with more or less perimeter, but the only way to have the corners, as mentioned, is to set the field edge, narrower and increase the overlap. , I also recommend decreasing the working width, so that the first perimeter is worked correctly.

**Comment by Tensuko** [comment]
Not a big deal, move start point, not a bug.
