### ISSUE TITLE
[BUG_SP] Manure AI use from Heap

### ISSUE THREAD

**Issue by Tankieboy** [Courseplay/Courseplay_FS22#1448]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Select AI Refill Manure. Manure Heap Extension

**Actual behavior**
"needs to be refilled".

**Expected behavior**
AI to work and fill from Heap

**Screenshots**

**Courseplay version**
Version used: v7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8540505/log.txt)

**Map**
Calmsden

**Vehicles/ implements involved**
Which vehicle or implement?
Class  Arion 650 & Brantner TA12050 Power Spread +

**Relevant script mods**
Autodrive & PF

**Comment by Tensuko** [comment]
Does the Giants Helper refill from heap ?

**Comment by Tankieboy** [comment]
No! Assume it's the Heap's problem then?

**Comment by Tankieboy** [comment]
Maybe because I was using the extension?

**Comment by Tankieboy** [comment]
Tried with non extension manure  silo, same result, "needs to be refilled".

**Comment by Tankieboy** [comment]
Yes.
No.

**Comment by Tensuko** [comment]
From what I saw in a Video, can you drive next to it and fill up your manure spreader, like you fill up your seeder for example ?

**Comment by Tankieboy** [comment]
> From what I saw in a Video, can you drive next to it and fill up your manure spreader, like you fill up your seeder for example ?

I fail to see what this comment has to do with the original highlighted problem.

**Comment by Tensuko** [comment]
Simple:
If you can load from the Heap by pressing R just like with any other refilling for seeder and stuff, you can use AD to refill from your Heaps.

**Comment by Tensuko** [comment]
There you go, should be no problem to use AutoDrive to use Refill from Manure Heap.

![fsScreen_2022_04_22_15_55_27](https://user-images.githubusercontent.com/27344744/164728813-65e30d10-0342-4ce3-9026-042eda1ba4b4.png)

**Comment by Tensuko** [comment]
As it seems to be meant from Giants to Manure places work like that, it functions just like any refill station.
Sure not a bug.
