### ISSUE TITLE
[Enhancement] Pathfinder for vine work turns.

### ISSUE THREAD

**Issue by Jstraws** [Courseplay/Courseplay_FS22#1450]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a vineyard with what seems like a decent amount of turn space.
Set worker onto the vineyard.
The worker turns into a tree/fence/house etc for a few seconds then quits.

**Actual behavior**
When the worker is trying to turn to the next row the generated turn path is not taking into account obstacles/space.

**Expected behavior**
With pathfinding in turn enabled I expect the turn to avoid obstacles and possibly reverse to complete the course.

**Screenshots**
![image](https://user-images.githubusercontent.com/18311973/164738177-e0600bdb-61f2-4a4c-b0b3-11cdca33563e.png)

**Courseplay version**
Version used: 7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8541920/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Landini Rex 4-080 GT
TMC Cancela TPN 140
Mod: no

**Comment by Tensuko** [comment]
This is not a bug, this is working as intended, since we need to make sure to hit the vines on the right spot.

**Comment by Jstraws** [comment]
So is there no way to have it avoid obstacles like trees and fences?

**Comment by Tensuko** [comment]
Right now, no.
Working on vines is difficult.
But I must say even with a pathfinder it would be hard to turn on that narrow space you got there.
Maybe we can get the pathfinder working there, but I still say your space is very very narrow.

**Comment by Jstraws** [comment]
Alrighty, good to know! First time setting up vines so obviously I just underestimated the necessary space :( Ty!
