### ISSUE TITLE
[BUG_MP] Courseplay does not drive to last waypoint

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1452]
Steps to reproduce

Course planning with multiple vehicles
Tell AutoDrive where Saat is for automatic refueling

Let AutoDrive hand over to Curseplay

Actual behavior

Curseplay hands off to AutoDrive and drives to fill up seed or fertilizer, then AutoDrive drives to the field and hands off to Curseplay, then Curseplay drives to the last point, but that is wrong, either he is 2 lanes ahead or earlier rarely is it right or when there are 3 drivers Curseplay likes to drive double left or right when he should be driving center.

Expected behavior

Curseplay hands over to AutoDrive and drives to fill up seed or fertilizer, then AutoDrive drives to the field and hands over to Curseplay, then Curseplay drives to the last point where it left off and should drive the track it left again even with 3 drivers. So if it is set to the left, it should also continue to the left afterwards.

Screenshots

https://youtu.be/CEmx7jhbK2Q Long video with all because of etc

Here you can see that the first driver drives away well recharges and properly restarts the second you can see what happens when it goes wrong.

https://youtu.be/PWK0VW1J0Vs In this video, the driver is totally in the wrong lane.

<img width="1282" alt="Unbenannt" src="https://user-images.githubusercontent.com/179698/164948184-40a38d2f-04a5-490c-9483-f75873c12c78.png">

Courseplay version

Version used: 7.0.1.13

Client Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8563081/log.txt)

Server Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8563079/log.txt)

Player on the server
4

Dedicated server or local hosted server
Dedicated server Yes

Map

Nordfriesische Marsch 4fach] 1.5

Vehicles/ implements involved

Kein Mod Fahrzeug

Relevant script mods
Autodrive 2.0.0.5

**Comment by Tensuko** [comment]
Tested in SP, no problem, not sure why this would be a MP Problem.

@schwiti6190 any Idea  ?

![fsScreen_2022_04_24_20_20_51](https://user-images.githubusercontent.com/27344744/164990734-f527b9a2-b8af-4daf-a9de-e1b3886de38a.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8550285/log.txt)

**Comment by Selyria** [comment]
https://youtu.be/xNWbwPDgf90

I have again made a new video and reproduced the error again

**Comment by Selyria** [comment]
So have run again 3 seeders 

Seeder 1 runway left after fill up left runway
Seeder 2 runway center after fill up left runway
Seeder 3 runway right after fill up left runway

**Comment by Plopsi** [comment]
Can confirm this. When refilling with AD, after return all tools are going to left lane - so far they drive to the last waypoint, just not on the last lane. Seems to only happen in MP.

Need to check if I can create a clean log over the WE - any special channels needed?

- Plopsi

**Comment by xkriton** [comment]
Hi
Same issue here with multitool + autodrive. Loading vagon returns to left line after emptying by autodrive. Manual stop-start of CP returns it to correct line untill it goes for emptying again.
