### ISSUE TITLE
[Question] Wendemanöver mit angehängtem Gerät mit dem John Deere 7R

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1462]
Wie es im Titel schon steht, fällt mir auf, dass der 7R erhebliche Probleme in Verbindung mit Courseplay hat, wenn er zum Wenden rückwärts fahren muss.
Muss er rückwärts fahren, lenkt er nicht richtig, so dass das Gerät an der 3-Punkt-Afhängung oder der Anhängerkupplung einknickt. Ab da dreht sich das Ganze nur noch im Kreis.
Mit dem Standard Helfer funktioniert die Wende.
Ich habe schon sämtliche sonstige Anbauten, wie das spezielle Gewicht für den 7 R und den Frontlader abmontiert, dies brachte aber keinen Erfolg.

Hat Jemand eine Idee, warum er nicht richtig rückwärts fährt?
Der 7R ist der einzigste Traktor, der das Problem hat

As it is already in the title, I notice that the 7R has significant problems in conjunction with Courseplay if he has to turn backwards.
If he has to go backwards, he does not properly distract, so that the device is kinked at the 3-point Af-superman or the trailer hitch. From then on, the whole thing turns only in the circle.
With the standard helper, the turning works.
I have already removed all other attachments, such as the special weight for the 7 R and the front loader, but this did not succeed.

Someone has an idea why it does not drive backwards correctly?
The 7R is the unique tractor that has the problem

**Comment by Tensuko** [comment]
Ist das der mit angehängtem Gewichtplatte unten ?

**Comment by SchorschiBW** [comment]
Mit und ohne. Habe beides probiert.

**Comment by Tensuko** [comment]
Ich glaub schon das es daran liegt.

Debug einschalten, und nen turn fahren lassen, gucken mit und ohne Platte, Screenshot machen und zeigen.

**Comment by SchorschiBW** [comment]
Werde ich morgen machen, ich muss heute noch arbeiten

**Comment by SchorschiBW** [comment]
Okay, zunächst mal eine kurze Erklärung:

Probleme hatte ich mit der Version 7.0.1.12, da spielte es keine Rolle, ob die Gewichtsplatte angebaut war, oder nicht. Sobald er bei der Wende rückwärts fahren musste, schlug die Wende fehl.

Ich habe nun mal zwei Videos gemacht, einmal mit und einmal ohne Gewichtsplatte, allerdings mit der Version 7.0.1.13. Mit der aktuellen Version verbesserte sich das Problem dahingehend, dass der 7R zumindest OHNE Gewichtsplatte ordentlich wendet, MIT Gewichtsplatte hat er immer noch das das Einknicken beim rückwärts fahren.

Video mit Debug, mit Gewichtsplatte:

https://youtu.be/21W4enHM4PE

Video mit Debug, ohne Gewichtsplatte:

https://youtu.be/7Bg_HILi5ks

**Comment by Tensuko** [comment]
Das ist ein allgemeines Problem mit Gewichten, sollte auch bei anderen Traktoren der Fall sein.

**Comment by SchorschiBW** [comment]
Ich hatte das Problem tatsächlich nur beim 7R, ich teste aber mal Andere mit Frontgewichten und Radgewichten

**Comment by Tensuko** [comment]
Radgewichte speitl keine rolle, angeschlossene.

**Comment by SchorschiBW** [comment]
Also, ich habe nun ein bisschen herum probiert, verschiedene Traktoren und Anbaugeräte, mit und ohne Frontgewicht und stellte fest, dass selbst der 7R mit Frontgewicht einwandfrei funktioniert

**Comment by Tensuko** [comment]
Dann liegt es nur an der Gewichtsplatte beim 7R, wie bereits am Anfang gesagt :)

**Comment by SchorschiBW** [comment]
Schaut wohl so aus. Ist aber nicht so schlimm, ich weiß ja nun, wie man damit umgeht. Vielleicht fällt Euch im Team etwas dazu ein
Danke für die Hilfe

Kann geschlossen werden
