### ISSUE TITLE
[BUG_MP] Curseplay runs well at first and then stops

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1463]
Steps to reproduce

Good question have a briefly loaded on both vehicles and let them run at once both stood had to restart them first at the next turn stood again both. 

Actual behavior

Both vehicles stop at some point strangely next to each other 

Expected behavior

Should depart normally its route both

Screenshots

https://youtu.be/_jr1l-dQ9ec

Courseplay version

Version used: 7.0.1.13

Client Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8548644/log.txt)

Server Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8548645/log.txt)

Player on the server
4

Dedicated server or local hosted server
Dedicated server Yes

Map

Nordfriesische Marsch 4fach] 1.5

Vehicles/ implements involved

Kein Mod Fahrzeug

Relevant script mods
Autodrive 2.0.0.5

**Comment by Tensuko** [comment]
Increase the distance of convoy
