### ISSUE TITLE
Courseplayfehler

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#1464]
Guten morgen,
kann es sein, dass Courseplay z.B. beim Drescher nur noch die Kanten rund fährt und nicht scharf usw. ?

**Comment by Tensuko** [comment]
Nö. Kann nicht sein.

**Comment by StefanTreutler1974** [comment]
Lasse ich von Courseplay ein Feld berechnen mit einem Grubber, so macht Courseplay das gleiche wie beim Drescher. Irgendwie liegt wohl da ein Fehler bei mir vor in der Einstellung - weiß nur nicht wie.

**Comment by Tensuko** [comment]
Ich verstehe deine Aussage noch immer nicht....

Du musst schon sagen was du machen willst und was das ergebniss ist, sonst kann dir keine Helfen.
Da ist schon etwas mehr Text oder vlt sogar Bilder nötig.

**Comment by StefanTreutler1974** [comment]
Hat sich mittlerweile erledigt.  Danke.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.04.22, 17:32 schrieb Tensuko ***@***.***>:

   
  Ich verstehe deine Aussage noch immer nicht.... 
  Du musst schon sagen was du machen willst und was das ergebniss ist, sonst kann dir keine Helfen. Da ist schon etwas mehr Text oder vlt sogar Bilder nötig.
