### ISSUE TITLE
[BUG_SP] Anderson Biobaler entlädt Ballen nicht

### ISSUE THREAD

**Issue by Bamyentm97** [Courseplay/Courseplay_FS22#1467]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Mit Anderson Biobaler Pappeln einfahren bis er voll ist

**Actual behavior**
Biobaler ist voll und zeigt an das er entladen werden muss
**Expected behavior**
Entlädt Ballen und fährt weiter bis das Kursende erreicht wird

**Screenshots
![fsScreen_2022_04_24_18_49_27](https://user-images.githubusercontent.com/104317706/164987374-600ecd7a-853d-432a-a903-5eb9a6a523e4.png)
**

**Courseplay version**
Version used: 7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8550122/log.txt)

**Map**
No Man´s Land

**Vehicles/ implements involved**
Which vehicle or implement?
New Holland T8.
Anderson Biobaler
Mod yes/no ? yes

**Relevant script mods**
Autodrive.

**Comment by franky-bb** [comment]
'Y' Automatisches ablegen anschalten

**Comment by Tensuko** [comment]
Genau das ist mir auch eben über den Weg gelaufen....

**Comment by Tensuko** [comment]
Genau gesagt, war das nicht das eigentliche Problem(vlt eines davon), er wird nicht bis 100% gefüllt.

**Comment by Bamyentm97** [comment]
Bei dem Fahrzeug wurden dann auch die Einstellungen für Drescher angezeigt. Es hat geklappt als ich "Beim Entladen stehen bleiben" aktiviert habe, dann hat er ihn auf 100% gefüllt und entladen.

**Comment by Tensuko** [comment]
Okay, interessanter hinweis, danke für die Meldung!
