### ISSUE TITLE
[Question] Issue 1315 Paste: What is the point or how to use?

### ISSUE THREAD

**Issue by gSe7eN** [Courseplay/Courseplay_FS22#1470]
This goes with issue [1315](https://github.com/Courseplay/Courseplay_FS22/issues/1315), copying and pasting.

Copying and pasting a course is a brilliant idea. However, as programmed, useless. I have several 3 tool courses that I use. I can copy the course from the first vehicle and I see from the GUI that the copy is successful. However, there is absolutely no way to paste it on the subsequent vehicles. Either the correct way to use it is not obvious as to allow people to figure it out without help OR it's just broken. I can't figure it out at all.

Any help is appreciated.

**Comment by Resandise** [comment]
I have not have any issue with this, but I have noticed, when you are pasting it to the 2nd, 3rd, ... vehicles, you need to ensure they do not already have a previous course loaded.

**Comment by Tensuko** [comment]
> However, as programmed, useless.

Nothing about this is useless!

You can't have a course loaded in your vehicle where you want to paste the course.
Just as @Resandise wrote.

**Comment by gSe7eN** [comment]
That defeats the entire point, then. It takes more time to open the menu, clear the course, and then click on the paste button than it does to open the menu, use keyboard to clear the course, select the new already selected course from the last tractor, and activate the course. 

Simple solution: Please consider an option to overwrite the loaded course to make this feature useful.

**Comment by TobiHH78** [comment]
> That defeats the entire point, then. It takes more time to open the menu, clear the course, and then click on the paste button than it does to open the menu, use keyboard to clear the course, select the new already selected course from the last tractor, and activate the course.
> 
> Simple solution: Please consider an option to overwrite the loaded course to make this feature useful.

You don`t have to open the menu to clear a course. That can be done directly in the CP Hud mit 1 mouse click...

**Comment by Resandise** [comment]
![fsScreen_2022_04_25_10_28_54](https://user-images.githubusercontent.com/96673100/165122371-648bcb97-6632-44e0-901d-386f6f929221.png)
The circle with the line though it clears the course

**Comment by gSe7eN** [comment]
Thank you!
