### ISSUE TITLE
[BUG_SP]  repeated LUA error 

### ISSUE THREAD

**Issue by judg393** [Courseplay/Courseplay_FS22#1475]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
LUA error 
2022-04-26 07:36 Error: Running LUA method 'update'.
D:/FS22/Hobos/FS22_Courseplay/scripts/ai/AIDriveStrategyDriveToFieldWorkStart.lua:94: attempt to index a nil value

**Actual behavior**
everything working normally doing 2 contracts at once then seeders stop seeding though they keep driving their course they don't seed and kick out the above error repeatedly. this also then prevents saving

**Expected behavior**
seeders keep seeding and don't cause save to fail 
**Screenshots**
N/A

**Courseplay version**
Version used:  latest 7.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
HOBOs Hollow

**Vehicles/ implements involved**
Which vehicle or implement jcb medium tractor - base game and modded horsch seeder  also running JD 8760 (mod) and modded great plains planter had no problems for 100+ hours running the either 
Mod yes/no ? Y

**Relevant script mods**
Running AD 
better contracts 

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8560538/log.txt)

**Comment by judg393** [comment]
Also bugs out with previous version of CP however i think it may be a specific mod vehicle  (sorry not previously mentioned as i forgot it was running) 

Fendt F255GT (Mod by farmer andy)  again had no problems with it for a long time but it causes the error now when trying to run a fert course. I'm not sure how much support or investigation you do with individual mod bugs or if i'm best trying to report to creator (I can't actually remember if i have used this tractor post 1.4.1 either)

**Comment by Tensuko** [comment]
This seems to be the origin of your Error:
2022-04-26 07:34 Error: Running LUA method 'update'.
D:/FS22/Hobos/FS22_UniversalAutoload/UniversalAutoload.lua:1512: attempt to index global 'spec' (a nil value)

And that does not come from Courseplay.
Try it without the mod.

**Comment by judg393** [comment]
Ok thank you
