### ISSUE TITLE
Fahren im Konvoi (MP)

### ISSUE THREAD

**Issue by Nookiiie** [Courseplay/Courseplay_FS22#1476]
Hallo ich habe folgendes Problem. Wenn ich zwei  Fahrzeuge mit  ein Striegel wie folgt einstelle ( mit ad fahren zu Feld x  und an cp übergeben / cp Einstellung Kurs erzeugt mit zwei  Fahrzeugen, einer fährt links einer rechts) 
Beide Fahrzeuge fahren auch zu Feld x und fangen mit ihrer Arbeit an nur fahren beide links wobei das zweite Fahrzeug auf rechts steht  und auch als zweites gestartet wird.

**Comment by Tensuko** [comment]
Sollte mit der .13 behoben sein. Ob für MP kann ich nicht 100% sagen.

**Comment by Nookiiie** [comment]
Danke für die Antwort.  Scheint also bekannt zu sein. Dann weis ich wenigstens das es nicht an mir liegt xD
