### ISSUE TITLE
[Question] No Row Direction Setting in Course Generator

### ISSUE THREAD

**Issue by KawaiiHalo** [Courseplay/Courseplay_FS22#1479]
Hi all, I am using the latest version of Courseplay downloaded here from Github. I'm having an issue when generating a field for harvesting. Everything is normal except for the fact that I cannot set the direction for up/down rows. Normally this wouldn't be an issue for me, but I'm playing on a hilly map so having the combine travel horizontally across the face of the hill instead of up it is crucial. I've noticed in videos and the help menu that an option should exist for this, but it doesn't appear in the generator menu for me. TIA.

**Comment by 60erjonny** [comment]
...Experten Modus aktiviert...?

**Comment by Tensuko** [comment]
Or in english: Expert Mode on ?
