### ISSUE TITLE
small contribution

### ISSUE THREAD

**Issue by leo32128fs** [Courseplay/Courseplay_FS22#148]
Translation Portugues Brasil, Thank you for your excellent work
[translation_br.zip](https://github.com/Courseplay/Courseplay_FS22/files/7777670/translation_br.zip)

**Comment by Hapczi** [comment]
Hello!
I have prepared the Hungarian translation. How can I share it with the community?

**Comment by Tensuko** [comment]
Create a PullRequest on GitHub pls. If you don't know how to do this, pls read this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
Thanks for your contribution.
