### ISSUE TITLE
[Enhancement] Courseplay Hud-Größe

### ISSUE THREAD

**Issue by FalconDS9** [Courseplay/Courseplay_FS22#1480]
Könnt ihr bitte die Breite des Huds an die Breite (sehr wichtig) und vll auch Höhe des AutoDrive Huds anpassen? Das würde mir als OCDler einen Dorn aus dem Auge nehmen =) Sollte die Funktion kaum beeinträchtigen wenn der Text notfalls etwas kleiner werden muss um die Breite zu schaffen. Wenn Höhe und Breite dann mit ADs Default übereinstimmen währe eine Skallierfunktion via Menü wie bei AD noch das i-tüpfelchen, aber zweitrangig.
Vielen Dank.

![corseplayHUD](https://user-images.githubusercontent.com/95674549/165440371-e591681d-0127-4ad2-81bd-eedbcb818170.jpg)

**Comment by Tensuko** [comment]
Nein, sonst gibt es wieder probleme mit Textlängen.
