### ISSUE TITLE
[Question] Abfahrhelfer

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/Courseplay_FS22#1481]
Erst mal besten dank an das ganze Team für den Coursplay gute Arbeit.

Wird es einen Abfahrer wieder geben für Mais Häckseln, Silo schiebe usw., oder wird das alles über AD laufen.
Wenn ja gibt es da schon eine Zeitschiene?
Im voraus schon mal besten Dank für eine Rückantwort.

**Comment by Tensuko** [comment]
Keinen Abfahrer, vlt ÜLW Fahrer.
Silo schieben in Planung, aber Zeiten wird es von uns nie geben.
