### ISSUE TITLE
[BUG_SP => Enhancment] Vehicule got a default course when loading a game it has not before leaving

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1482]
Hello

I often got the case when a start my savegame, to see that all vehicle has the same course loaded
it seems to only happen i a quit a game having one or more vehicle working in fields, the other are just parked

sometime it's ok, but often after loading a game, others vehicle have the same course loaded, they had not any course before leaving my game.

it a strange behaviour because it's not always happening the same way
sometime all vehicle hav the same course, sometimes only few, sometimes none
i have 3 Case Magnum, 2 case streir, 2 case combine and 1 Krone BigM

usually it only case vehicle that have the same course, but this morning the Krone had it too

My log from this morning if it can help
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8569666/log.txt)

mod : CP 7.0.1.13
AD 2.0.0.5
others from modhub in log

PS : sorry for my poor english this morning >_<

**Comment by Tensuko** [comment]
I wasn't able to reproduce this with the .14
If I remove the course from the vehicle, save the game and reload it, it doesn't have a course loaded or any other course.

**Comment by Chico0008** [comment]
Still occure to me

if i leave my game having drivers working in field
often when i load my game later in the day, i start again my worker, and some other vehicle have the same course

yesterday i had 2 fendt favorit 500c working in the same field
and 1 of my 2 Class combine load the same course for no reason :(

had this on 0.14, on some earlier version, and also on 0.15
