### ISSUE TITLE
[Question] Do CP benefits from RTK station bonus from Precision Farming ?

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1483]
Hi
With Precision farming, it is said that an Rtk stations can help workers workds to 14% faster
does it only apply to Giant IA worker ? or can CP benefits from this too ?
(for now i have an RTK station but don't see any difference in time they need to do their work)

**Comment by Tensuko** [comment]
I don't even know how good the normal helper do benefit, but maybe CP does too then (as the tools should be able to run faster).
Can't 100% answer this.
