### ISSUE TITLE
Request Support for Stand alone Bale Wrapers

### ISSUE THREAD

**Issue by dansiegel1109** [Courseplay/Courseplay_FS22#149]
**What is the problem this feature/enhancement solves?**
As Grass Bale Wrapping is the SLOWEST part of the silage baling process, I would like to request official CP support for mobile wrappers (not the Anderson sausage makers, haha).  Specifically the Kuhn SW4014 and Kvernland 7850C, both stock/vaniall FS wrappers.

**Describe the solution you'd like**
I would think this to be quite simple in comparison to other feature requests - the wrapper needs to be unfolded by CP (and folded when done).  It also supports auto or manual dropping like the Vicon Fast Baler.  I imagine auto drop should be the CP default setting.  Further it would need its offset to be calculated and used, as once unfolded is sits to the right of the tractor.  It does not change sides when it turns like the Kvenland 4140L mower, rather it is fixed to the right side - and pivots on the hitch rather than being straight (if that matters for turns, in the rare event of wrapping a dropped bale while turning a row).  

Considering if you on relatively flat ground, I have witness CP baling to put the bale PRECISELY on the track, so I do not anticipate any problems with capture of the bale by the wrapper, as long as the offset it calculated correctly.

**Describe alternatives you've considered**
FollowMe is the only other automated alternative in FS - however FM is not released yet (zero ETA, may have a surprise drop like CP, haha).  However, CP is in all things superior to FM.  FM is easier to use for novice players new to CP or FM, however FM has many issues with trying to automate baling.  FM, you need to drive the lead tractor (or perhaps CP can do it).  Regardless, you always need multiple vehicles using FM - where as with CP you can do this one vehicle at a time, anytime you want, as the course is remembered.  And if there is a problem with the first vehicle in FM, all vehicles are fouled and you have quite a traffic jam.  And the last thing which makes FM not great with baling, is that if you mow and you forget to have your baler and then wrapper follow the mower, you have lost any opportunity for automation.  You must then bale manually and have the wrapper follow.

**Additional context**

**Comment by Tensuko** [comment]
That will come back, ofc.

**Comment by pvaiko** [comment]
See https://github.com/Courseplay/Courseplay_FS22/commit/b32d20ffe0de73a48865fd30a9a3e3794d492e8b

**Comment by pvaiko** [comment]
Wrappers should now be supported either by the bale finder mode or course with offset
