### ISSUE TITLE
[Feature] Automatic use of the ISARIA Sensors

### ISSUE THREAD

**Issue by Namajo** [Courseplay/Courseplay_FS22#1492]
**What is the problem this feature/enhancement solves?**
It were a cool feature, if the ISARIA sensors from Precision farming would be activated on fertilizing the field. Only if it's available, of cause.

**Describe the solution you'd like**
If precision farming addon is loaded and the vehicle has an INSARIA sensor (active or passive), it should be used on fertilizing the field to gain more economical points for the field.

**Describe alternatives you've considered**
If the implementation of this feature is not possible or to hard to fullfill, it were a nice thing if the sensors stay on while the vehicle is processing the course. Actually it disables it on every turn.

**Comment by rohne83** [comment]
Think this should work already, at least with the active one (separate shop item to be mounted at the front). When I did some small tests on PF, CP unfolded it at least and in the map it looked like it had effect compared to not using it.

**Comment by Tensuko** [comment]
The question is, does it work with Giants Helper ?

Whenever such a request is done -> try it out with Giants Helper, try it out with CP -> then request.

**Comment by Namajo** [comment]
Sorry, i didn't know about the relation between Giants Helper and CoursePlay.
The ISARIA Pro Active works properly. That's ok for me.
