### ISSUE TITLE
[BUG_SP] "Failed to open xml file" in log

### ISSUE THREAD

**Issue by Zlous** [Courseplay/Courseplay_FS22#1493]
**Steps to reproduce**
Download the FS22 Courseplay mod from GitHub and place into mods folder

**Actual behaviour**
The mod does not appear in the mod list when you load into the game, even though it's been placed in the right folder

**Expected behaviour**
I expected to load in to FS22 and find the Courseplay mod in the mod list and use the mod in-game

**Courseplay version**
Version used: v7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8594549/log.txt)

**Comment by KITT3000** [comment]
You downloaded the mod wrong, you downloaded the repository in ZIP format, but it is not a ready-made mod, best download the mod from here: https://github.com/Courseplay/Courseplay_FS22/releases/latest
