### ISSUE TITLE
[BUG_SP] Tiefenlockerer Kverneland mit Säeinheit

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1497]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

Hallo, 
Ich lasse meinen Acker mit dem Kverneland Tiefenlockerer bearbeiten. Dabei ist er mit einer Säeinheit ausgerüstet. Problem ist das wenn ich die Feldarbeit beginnt diese nicht mit eingeschaltet wird sodern das manuell von Hand geschehen muss.

**Steps to reproduce**
Den Kverneland DTX 300 AR mit Säeinheit auf einen Feldkurs schicken und Arbeiten lassen.

**Courseplay version**
Version used: 7.0.1.13

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8597980/log.txt)

**Map**
Map played on.
NDS

Which vehicle or implement?
Fendt 900 Vario

Orginal Tiefenlockerer, Mod Fendt 

**Relevant script mods**
Autodrive, CP

**Comment by Tensuko** [comment]
Schon mal in den Fahrzeugeinstellungen geguckt ?
Da sollte eine option sein zum einschalten der Saatfunktion von solchen Geräten.

**Comment by NeonRider1999** [comment]
Oh sry das habe ich wohl Übersehen. Ja habs gefunden danke für die Info
