### ISSUE TITLE
Helper not calling for full stone picker

### ISSUE THREAD

**Issue by raqumax** [Courseplay/Courseplay_FS22#150]
**Steps to reproduce**
Use the expensive stone picker (elho scorpio 550)and make a course to pick up stone on field. 

**Actual behavior**
The helper drive on and remove all stone even then stone picker toll is at max capacity 

**Expected behavior**
Call a text for emptying the stone picker

**Screenshots**

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Steyr 8150 and elho  scorpio 550

**Relevant script mods**
Autodrive
Manuel attach.
GPS.

**Comment by dansiegel1109** [comment]
I do know that this is a basegame bug as well, so perhaps CP/AD can do nothing about it.  Of course the basegame will not call an unloader and unload it, however the vanilla AI simply ignores that it is full and continues driving the ENTIRE field with a full load, not picking up anything.

**Comment by raqumax** [comment]
Arh ok, then we will have to wait on Giants.

**Comment by Tensuko** [comment]
Yes, this is a general Giants Problem.
I would rather want Giants to fix this in their code then we have to 'hack it' into the game :)
Thanks for understanding.
