### ISSUE TITLE
Not enable the ISARIA PRO Compact crop sensors (Precision Farming FS22 Mod)

### ISSUE THREAD

**Issue by BattleHook** [Courseplay/Courseplay_FS22#1500]
**What is the problem this feature/enhancement solves?**
When CoursePlay Worker starts and it is dark it also turns on de crop sensors (attached to the mirrors of the tractor). Since the compact sensors do not work without daylight a blinking warning message keeps showing up on screen.

**Describe the solution you'd like**
I would like a setting feature where the compact crop sensors can be disabled (during night) for CP worker.

**Describe alternatives you've considered**
disabling during certain times of day
disabling always for CP workers

**Additional context**
![Knipsel SHOP](https://user-images.githubusercontent.com/62392548/166157363-872e58e4-a9f0-46de-bb64-3f3d4125ef4f.PNG)
![Knipsel-CP Fieldwork](https://user-images.githubusercontent.com/62392548/166157518-71dcc53d-498d-4f18-9233-867ca619ad10.PNG)

**Comment by schwiti6190** [comment]
@BattleHook Hi, does this work correctly with the giants helper ?

**Comment by BattleHook** [comment]
> @BattleHook Hi, does this work correctly with the giants helper ?

@schwiti6190 
Hi. I had to test this since I normally only use the CoursePlay hlper as you wil understand ;)
When I activate the ingame (Giants-) Helper (same map, vehicle and implements) the same situation occurs
![Knipsel Fieldwork Giants helper](https://user-images.githubusercontent.com/62392548/166449939-88e487f3-19c8-41b4-a4f2-c3558a527eb8.PNG)
.

**Comment by cwattyeso** [comment]
The Passive Isaria Pro Compact Sensors that you buy on the vehicles themselves do not work at night. It does tell you this in the help section. If you want to fertilise and stuff at night you need to buy the front mounted active sensor from the store and attach to the three point link on the front of your tractor.

**Comment by BattleHook** [comment]
> The Passive Isaria Pro Compact Sensors that you buy on the vehicles themselves do not work at night or in poor weather. It does tell you this in the help section. They require daylight to activate the sensors. If you want to fertilise and stuff at night or in rain you need to buy the front mounted active sensor from the store and attach to the three point link on the front of your tractor.

@cwattyeso : thank you for your reply, but did you look at what I asked (including the screenshot of the shop) ? All you tell me is already known to me. Your reply does not provide an answer or solution to my question.

So the only option is to sell the compact models and remount them (in the workshop) for daytime use ? 
Where does the "Simulator" part in this game's name stand for ? Okee, I grasp the idea that it is not a 100% realistic sim, but nevertheless.....

**Comment by schwiti6190** [comment]
@BattleHook This is a bug by giants and will hopefully fixed. You could let them know with their bugtracker.

**Comment by BattleHook** [comment]
> @BattleHook This is a bug by giants and will hopefully fixed. You could let them know with their bugtracker.

@schwiti6190 : I will do that, Do you have for me a link to their bugtracker that works?

**Comment by schwiti6190** [comment]
Not sure how this works, as I haven't used it before: https://feedback.giants-software.com/login_page.php

**Comment by BattleHook** [comment]
the link works. Had to log in and fill dozens of fields. but its done , Now we just have to wait for them to fix Precision Farming mod (I guess).

**Comment by schwiti6190** [comment]
Yes, thanks for your feedback :) Will close this issue then.

**Comment by cwattyeso** [comment]
> > The Passive Isaria Pro Compact Sensors that you buy on the vehicles themselves do not work at night or in poor weather. It does tell you this in the help section. They require daylight to activate the sensors. If you want to fertilise and stuff at night or in rain you need to buy the front mounted active sensor from the store and attach to the three point link on the front of your tractor.
> 
> @cwattyeso : thank you for your reply, but did you look at what I originally asked (including the screenshot of the shop) or did you only see the follow up message? All you tell me is already known to me. Your reply does not provide an answer or solution to my question (feature request).
> 
> So the only option is to sell the compact models and remount them (in the workshop) for daytime use ? Where does the "Simulator" part in this game's name stand for ? Okee, I grasp the idea that it is not a 100% realistic sim, but nevertheless.....

My replydoes provide you with the answer. You should not fit passive sensors to tractors if you are going to be working in the dark, if you do really want to fertilise, seed or spread in the dark, you should really be buying the active sensor sensor attachment with front weights from the misc section of the store which allows your tractor to work all hours of the day. Again that is explained to you in the game and you should know this if you read what is on the screen and the help section.

However the bigger answer should be that workers and therefore Courseplay should stop working and stop fertilising/spreading when it's too dark for the passive sensors on the tractor to work, similar to how Courseplay will stop Harvesters now if it starts raining. They should only resume fertilising/spreading during the daylight hours.

**Comment by BattleHook** [comment]
> > > The Passive Isaria Pro Compact Sensors that you buy on the vehicles themselves do not work at night or in poor weather. It does tell you this in the help section. They require daylight to activate the sensors. If you want to fertilise and stuff at night or in rain you need to buy the front mounted active sensor from the store and attach to the three point link on the front of your tractor.
> > 
> > 
> > @cwattyeso : thank you for your reply, but did you look at what I originally asked (including the screenshot of the shop) or did you only see the follow up message? All you tell me is already known to me. Your reply does not provide an answer or solution to my question (feature request).
> > So the only option is to sell the compact models and remount them (in the workshop) for daytime use ? Where does the "Simulator" part in this game's name stand for ? Okee, I grasp the idea that it is not a 100% realistic sim, but nevertheless.....
> 
> @BattleHook My reply does provide you with the answer. You should not fit passive sensors to tractors if you are going to be working in the dark, if you do really want to fertilise, seed or spread in the dark, you should really be buying the active sensor sensor attachment with front weights from the misc section of the store which allows your tractor to work all hours of the day. Again that is explained to you in the game and you should know this if you read what is on the screen and the help section.
> 
> However the bigger answer should be that workers and therefore Courseplay should stop working and stop fertilising/spreading when it's too dark for the passive sensors on the tractor to work, similar to how Courseplay will stop Harvesters now if it starts raining. They should only resume fertilising/spreading during the daylight hours.

I agree to disagree with you on this matter.
As of the rest I consider this matter closed.

**Comment by cwattyeso** [comment]
Agree to Disagree all you like, but you really should learn how the game works, what Giants intended and why there are two different types of sensor. From my experience the passive sensors are a complete waste of time and should be ignored. Just use the active sensors. Most people use front weight on their tractors, so it's no real difference, now you have a front weight with a sensor frame included and that lets your vehicles and workers work every hour of the day and all year round.

If you want to use Passive Sensors then you need to accept you have to change the way you work your fields, as can only do so in Daylight and during Good Weather.

**Comment by BattleHook** [comment]
> Agree to Disagree all you like, but you really should learn how the game works, what Giants intended and why there are two different types of sensor. From my experience the passive sensors are a complete waste of time and should be ignored. Just use the active sensors. Most people use front weight on their tractors, so it's no real difference, now you have a front weight with a sensor frame included and that lets your vehicles and workers work every hour of the day and all year round.
> 
> If you want to use Passive Sensors then you need to accept you have to change the way you work your fields, as can only do so in Daylight and during Good Weather. This means paying attention to the in game clock and deciding whether you have enough time to complete a job, or whether you need to wait and leave it until the next morning.

Do not tell me I have to learn how the game works, I really know plenty of the game mechanics. But first of all it is called a "Simulator".
It should be my own gameplay choice if I want to mount the passive sensors. Sometimes the (rather wide) active sensor is just causing problems blocking the helper on trees or fences on certain fields on certain maps when using Courseplay. 
It is my choice to sacrifice some yield returns by not using crop sensors at all, e.g. when I have to work at night or rain, due to the month ending (and the opportunity to sow some particular kind of crop). 
It should not be neccesary to have to remove the passive sensors when driving at night or under bad weather conditions, just to get rid of the nagging warning. We don't remove the screenwipers during sunny days, or would you do this by editing the mods? (lucky for us there is no nagscreen telling us: "screenwipers have no effect during dry periods" and they have been so smart to just turn them automatically off during these dry periods)  ;)

For your information: I made a ticket at "Giants Software feedback" for this issue on the Precision Farming passive sensors. It has taken a while for them to answer, but they responded that they will fix this the next update (of the Precision Farming DLC).
