### ISSUE TITLE
[Enhancement] Wendemanöver Ropa (auch andere) geht über Feldgrenze

### ISSUE THREAD

**Issue by Achimobil** [Courseplay/Courseplay_FS22#1502]
**Steps to reproduce**
Z.b. Ropa 4m Schneidwerk. Kurs mit 5 Vorgewende und 8 Reihen

**Actual behavior**
Beim Wenden von den äußeren Bahnen fährt er zum Feldrand und dann wieder zurück, dabei kommt er über die Feldgrenze, was blockiert wenn dort ein Zaun, Gebäude oder Deich ist.

**Expected behavior**
Feldgrenzen beachten bei diesen Wendemanöver inkl. Schneidwerk. Also das Schneidwerk muss ebenfalls im Feld bleiben.

**Screenshots**
kurzes Video hier: https://youtu.be/TrViRMKySDM

**Courseplay version**
Version used: 7.0.1.13

**Log**
Da das Log immer so zugespammt ist und zu der Zeit vieles anderes lief habe ich das hier nicht angehängt. Ich habe den Kurs gespeichert und kann das jederzeit mit gewünschten channels noch mal machen und auch mehr videos liefern, falls benötigt. 

**Map**
NF Marsch neuste Version

**Vehicles/ implements involved**
Ropa, passiert aber auch mit dem standard Kartoffelroder
Mod yes/no ? Yes

**Relevant script mods**
Ich denke nicht, dass andere Mods da mit rein spielen.

**Comment by Tensuko** [comment]
Das ist ein Pathfinder turn, der will auf der äußersten Bahn fahren und beim einlenken (schwenkt halt aus) kommt er gegen diese Wand...
Ich weis nicht ob wir da mal eine Logik für finden, eine entsprechende innere Vorgewende Bahn zu verwenden.

**Comment by Achimobil** [comment]
Bei dem 18m schneidwerk aus dem Modhub hab ich das auch beim drescher. könnte man dem pathfinder nicht sagen er soll 1 oder 2 m abstand halten vom feldrand bei der berechnung?

**Comment by Tensuko** [comment]
Eventuell könnte man zum Headland einen offset einrechnen... muss man schauen.

**Comment by rohne83** [comment]
Kann grundsätzlich mit fast allen Geräten passieren, je nach Feldform und Geräteeigenschaften. Hatte ich im 19er auch schon öfter mal zB beim Säen wenn ich den PathfinderTurn manuell aufgrund der konkreten Feldform aktiviert hatte, dass er aufgrund des Ausschwenkens und des Benutzens eben der äußersten Vorgewendebahn trotzdem an Hindernissen am Feldrand hängen bleibt.
Offset oder falls vorhanden eine Bahn weiter innen nutzen wäre soweit auch das einzige das mir einfällt um das zu verhindern.

**Comment by pvaiko** [comment]
> Eventuell könnte man zum Headland einen offset einrechnen... muss man schauen.

Wir haben schon ein Field Margin Setting...

**Comment by Achimobil** [comment]
> Wir haben schon ein Field Margin Setting...

Ja, wenn ich da aber 2m einstellen würde, dann fehlen im Vorgewende doch 2m die nicht gemäht werden. Das wird also wenig bringen.

**Comment by pvaiko** [comment]
> Das wird also wenig bringen.

Dachte Fahrzeug nicht blockieren ist besser als 2m nicht mähen (wenn's überhaupt so viel braucht). 

Das ist eigentlich nicht der Pathfinder, und selbst wenn es der Pathfinder wäre, der würde so eine abrupt steile Wand wie in Video wahrscheinlich nicht ausweichen. 

Ab eine bestimmte Entfernung fahren wir immer auf dem äussersten Vorgewende, der Pathfinder findet nur den Weg zwischen Vorgewende und die Reihenende/start. Das ist um die Pathfinderlaufzeit zu minimieren, die einfachste Lösung wäre natürlich für die ganze Strecke den Pathfinder zu benutzen.

Wir könnten auch eine der inneren Vorgewende benutzen, das ist aber leider nicht so trivial weil es abhängig von der Geräteeigenschaften (turn radius, länge, usw.) schiefgehen kann.

**Comment by Achimobil** [comment]
Also der Pathfinder sucht den weg am ende der reihe zum ersten Vorgewende und nachher auch wieder zurück auf die nächste Bahn. Das es bei komischen schrägen Feldgrenzen da zu Problemen kommen kann, leuchtet mir ein, aber hier habe ich doch eine gerade Feldgrenze im 90° Winkel zu Bahn. Warum bekommt er dann am ende die Kurve nicht? Wo das Schneidwerk sitzt weiß er doch, sonst würde er ja nicht alles ordentlich ernten, oder hab ich was übersehen?

**Comment by pvaiko** [comment]
> Warum bekommt er dann am ende die Kurve nicht?

Ohne Logs schwer zu sagen, aber die Kurve und der Pfad selber sind alle in Ordnung hier, nur die Kollision zwischen Schneidwerk und Terrain ist entweder ignoriert oder gar nicht gefunden.

**Comment by Achimobil** [comment]
Also ich hab den Kurs gespeichert, so dass ich mich einfach wieder mit der Gerät da hin stellen kann ohne was anderes laufen zu lassen und kann die dann Log zukommen lassen.
- Welche von den logs unter Shift+4 soll ich dafür aktiveren?
- Fahrzeug Debug aktivieren?
- Video davon machen oder nur die Log Datei?

**Comment by pvaiko** [comment]
Pathfinder, turns, course, und Fahrzeug Debug aktivieren. Video wäre schön weil dann wir können den Kurs auch sehen, aber nicht unbedingt wichtig. Danke.

**Comment by Achimobil** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8605104/log.txt)
Beim versuch es noch mal mit aktiviertem log nach zu stellen ist er zwar wieder über die Feldgrenze gefahren, aber nicht so weit wie beim ersten Video. Warum kann ich leider nicht sagen, der Unterschied vom ersten zum zweiten Video ist nur, dass es jetzt abgeerntet ist. Aber seht selbst:
https://youtu.be/8Dj4j4sTa3Q

**Comment by pvaiko** [comment]
> Warum kann ich leider nicht sagen

Der hat jetzt die Wegpunkte auf dem Vorgewende gar nicht benutzt, sondern ein Direktpath mit Pathfinder. Wenn ich die Logs von dem ersten Video hätte, könnte ich sagen warum.

**Comment by Achimobil** [comment]
Leider habe ich die logs nicht aufgehoben, da dies nach 4 Stunden Spielzeit war dachte ich, die wäre etwas lang ;(

**Comment by Achimobil** [comment]
Da das so ja nicht nachstellbar ist, close ich das ticket.
Ich habe jetzt die neuste Version und die standard aktivierten logs lasse ich an.
Ist aber nicht wieder passiert, sollte es wieder passieren, dann werden ich ein neues ticket schreiben mit video und log ;)
