### ISSUE TITLE
[Feature] Support fuer Netzfolien etc in Pressen

### ISSUE THREAD

**Issue by schoos76** [Courseplay/Courseplay_FS22#1503]
**What is the problem this feature/enhancement solves?**
Wenn ich mit dem Netzfolien-Mod (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=231396&title=fs2022) spiele, dann faehrt die Presse einfach weiter sobald die Netzfolie zueende ist und nimmt kein weiteres Gut auf. 

**Describe the solution you'd like**
Wuenschenswert waere es, wenn die Presse in dem Fall stehenbleibt und eine entsprechende Meldung im HUD angezeigt wird. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by schwiti6190** [comment]
@schoos76 Hi, bleibt der normale Helfer stehen, wenn die Netzfolie leer ist ?

**Comment by schoos76** [comment]
Werde ich die naechsten Tage testen und berichten.

Mir war auch so als ob beim allerallersten Mal Folienwechsel die Presse stehenblieb.

**Comment by schwiti6190** [comment]
Falls noch was auffällt einfach das Issue wieder öffnen.
