### ISSUE TITLE
Auf die neuste CP Version aktualisiert und es fehlen sehr viele einstelungen im CP hud

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/Courseplay_FS22#1508]
hallo ich habe gestern auf die neuste CP Version gewechselt und wunderte mich warum es viele Einstellungen im hud nicht mehr gibt wie Vorgewende Einstellungen hinüber zu Start Richtung bis hin zu denn geschwindichkeits Einstellung bei bestimmten Situationen wie wenden etc ist das gewollt oder gibt es dort derzeit ein Problem oder muss ich irgendeine Einstellung vornehmen das mir alles angezeigt wir
![fsScreen_2022_05_03_14_43_29](https://user-images.githubusercontent.com/71101944/166455578-39267983-508d-465d-928f-bbc760f2c4f4.png)
![fsScreen_2022_05_03_14_46_57](https://user-images.githubusercontent.com/71101944/166455580-4296ae06-3c14-4f30-9308-19a60263a224.png)

**Comment by TobiHH78** [comment]
Experten-Modus aktivieren.

**Comment by Tensuko** [comment]
Hilfemenü und changelog nicht gelesen.
