### ISSUE TITLE
[BUG_SP] Sugar Beet Harvester Auto-Unload Bug

### ISSUE THREAD

**Issue by MrCanerican** [Courseplay/Courseplay_FS22#1509]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Set a trailer next to a field, set a trailer with the plow on the front, and harvest wagon on the back, and tell it to self-unload. 

**Actual behavior**
As it approaches, it slows down, lifts the ejection shute, and then stops about 2m short of the trailer, and since it can't unload, it stops.

**Expected behavior**
It should pull forward another ~10m after it lifts the ejection shute, so it will unload.

**Screenshots**
Didn't get one

**Courseplay version**
Version used: 7.0.1.14

**Log**
Can dig this out, or re-create if needed.

**Map**
Elm Creek

**Vehicles/ implements involved**
Which vehicle or implement? 
Farmtech Fortis 300 Trailer, pulled by CLAAS Arion 660, on the E side of Field 76.
CLAAS Axion 960 Terra Trac, with a Grimme FT300 on the front, and towing a Grimme Rootster 604.
Mod yes/no ? No

**Relevant script mods**
AP was installed but was not in use.

**Comment by Tensuko** [comment]
> **Screenshots**
> Didn't get one

That would help a lot.

> **Log**
> Can dig this out, or re-create if needed.

Always needed, thats why it is part of the Template.
