### ISSUE TITLE
[BUG_SP] Mod Tiefenlockerer klappt sich automatisch auf

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1511]
**Actual behavior**
Folgender Tiefenlockerer, der als Pflug läuft, klappt  seit CP-Version 7.0.1.14 beim ankuppeln automatisch auf:

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226965&title=fs2022

**Steps to reproduce**
Den Tiefenlockerer ankuppeln

**Expected behavior**
In den Vorgängerversionen klappte der Tiefenlockerer nicht auf beim ankuppeln.

**Courseplay version**

 7.0.1.14 

**Map**

Hobo's Hollow

Which vehicle or implement? 

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226965&title=fs2022

Mod yes/no ?

 yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Autodrive
FS22_EnhancedVehicle

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8619469/log.txt)

**Comment by timmi4026** [comment]
Das gleiche hab  ich seit der neuen Version mit dem Mulcher, und dem Lexion 8900 wenn ich ein Schneidwerk (draper) dran hänge, dann ist der instant offen der Drescher. Spiele MP

**Comment by caplink811** [comment]
Moin,
jenseits von, das habe ich auch, Probleme mit Drscher der aufklappt, wenn Schneidwerk mit Draper gekuppelt wird, sowie einem Grubber, der (ohne Interaction mit CP) irgendwo den Attacher in einem Meter Höhe vermutet, die Anmerkung, das es mit der 70113DEV vom 2404 noch nicht so war. Ich täte vermuten, es hängt mit dem agentattacher zusammen, aber das ist nur geratgen...

PS: natürlich wie immer, danke für die Zeit und Arbeit, die ihr investiert, und macht weiter so :-)

**Comment by johnwayne1930** [comment]
Habe das verhalten mit dem aufklappen ebenfalls beobachtet, mit 7.0.1.14 und dem "Kompaktomat 1570 Max" Grubber sowie "TJP 610" Mulcher, beide aus dem Basisspiel.
