### ISSUE TITLE
[Question]Feldkurs

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1515]
Hallo

Kann es sein das seit der neuesten Version ein Feldkurs nicht mehr generiert werden kann ?

**Comment by MateusKronbauer** [comment]
I'm having issues as well... When i try to make a course with manual direction of lines, even on a small field, it fails and on the log is says that it reached dangerous levels of memory use (for PS4), but i always did courses even on much bigger fields and it's been ok... When i use automatic direction it generates normally...

**Comment by Tensuko** [comment]
#1516
