### ISSUE TITLE
[BUG_SP]Kursgenerierung endet mit Fehler

### ISSUE THREAD

**Issue by WernerWusel** [Courseplay/Courseplay_FS22#1517]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Mit CP das Feld 77 (Screenshot) auswählen und einen Kurs generieren.

**Actual behavior**
Kursgenerierung wird gestartet nachdem alle Einstellungen in CP vorgenommen wurden. Nach kurzer Zeit wird die Generierung beendet und es wird der Fehler gemeldet. Es wurden viele verschiedene Einstellungen probiert, immer mit dem gleichen Ergebnis.
Mit Feld 76 nur zur Funktionskontrolle einen Kurs generiert. Der letzte im Log.
 
**Expected behavior**
Ich erwarte nicht viel, nur das auch auf Feld 77 von 215 Feldern auf der Map ein Kurs generiert werden kann. 

**Screenshots**
![20220504215524_1](https://user-images.githubusercontent.com/102391757/166818846-2c160f8b-3bee-46b9-a30e-f246d2c051ca.jpg)
![20220504215623_1](https://user-images.githubusercontent.com/102391757/166818883-0a3f418a-76d0-4da5-ab90-797cdc8ccaf1.jpg)
![20220504215822_1](https://user-images.githubusercontent.com/102391757/166818916-5d2f6ec3-3c25-4a2f-803e-4504cc79c313.jpg)

**Courseplay version**
7.0.1.14

**Log**
[log_CP_Fehler_2.txt](https://github.com/Courseplay/Courseplay_FS22/files/8626927/log_CP_Fehler_2.txt)
Im Log stehen mehrere vergebliche Versuche.

**Map**
Huron County Michigan

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
#1516
