### ISSUE TITLE
[BUG_SP] Some devices open very quickly after attaching

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1523]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Baler is folded. Unhook. attach again.

**Actual behavior**
Rake just pops down quickly

**Expected behavior**
Rake moves down slowly.

**Screenshots**
n/a

**Courseplay version**
Problem occurs since version 7.0.1.14. With version 7.0.1.13 the above behavior does not happen.

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8635618/log.txt)

**Map**
NF Marsch 4fach oG

**Vehicles/ implements involved**
Krone BigPack 1290 HDP + Nadal R90 (Mod)
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234272&title=fs2022

Similar behavior with John Deere X9 1100 (Mod)
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228728&title=fs2022

**Relevant script mods**
Krone BigPack 1290 HDP + Nadal R90 (Mod)
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234272&title=fs2022

**Comment by Tensuko** [comment]
#1511
