### ISSUE TITLE
[BUG_SP] CP GUI will not open

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#1525]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
open fs22, get in tractor, press delete key or right click

**Actual behavior**
the CP GUI won't open while in tractor. settings and such open, and i see the little "courseplay" bar, but the little window won't open. was working earlier today, andi didn't add any mods. 

**Expected behavior**
window should open
**Screenshots**

**Courseplay version**
Version used: 

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8636862/log.txt)

**Map**
Wild West 16x

**Vehicles/ implements involved**
Multiple/all

**Relevant script mods**
Autodrive, Engine start

**Comment by Tensuko** [comment]
Callstack from some other mod.
The "courseplay bar" is the info panel, as you can read up in changelog and help section.
If not open up, check your keybinds.

**Comment by Commissar0617** [comment]
thanks for the quick reply, somehow the keybinds for minigui and mouse activate got unset. vOv
