### ISSUE TITLE
[BUG_SP] Combine speed slows WAY down when you drive something near it to unload

### ISSUE THREAD

**Issue by sjmills** [Courseplay/Courseplay_FS22#1526]
It didn’t do this in 19.

**Steps to reproduce**
1. Make a course for harvesting.
2. Start the combine harvesting.
3. Get a tractor with a grain cart.
4. Wait for the combine to harvest a decent amount that you can offload to the cart.
5. Wait for the combine to start a nice long row that will give you a chance to offload into the moving tractor+cart.
6. Drive up next to the combine with the tractor+cart.

**Actual behavior**
The combine will slow way down to around 1mph when the tractor is detected as a possible collision object (I’m guessing). It will continue to go that slow until it actually begins to unload into the cart, then it will speed up to its normal harvesting speed.

**Expected behavior**
The combine should continue traveling its harvesting speed and not slow down.

**Screenshots**
None. I can capture a video if you need proof.

**Courseplay version**
Version used: 7.0.1.14

**Log**
Issue typed up on iPad. I’ll attach the log later.

**Map**
Any

**Vehicles/ implements involved**
Latest seen with TwinScrew combine, IH 2+2 tractor, and Brent gravity wagon, but experience with many other combinations.

**Relevant script mods**
Autodrive is used in this savegame, but not enabled during CoursePlay field work.

**Comment by sjmills** [comment]
Here's my game log. I enabled logging for the combine, but don't think I enabled the correct channels. I'd never done that before, so I'm sure I did things in the wrong order.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8636939/log.txt)

**Comment by Tensuko** [comment]
When unload it doesn't slow down.

**Comment by sjmills** [comment]
It does slow down. There are many of these lines in the log:
2022-05-05 19:59 :17 [dbg4 lp115056] 450/160: WORKING: Obstacle ahead, d = 1.9, deg = 62.0, slowing down to 2.0
The tractor and cart really aren't going to be hit by the combine or header, so it doesn't need to slow down that much. Something's wrong with the hit collision being too sensitive. I'll try to capture a video to show it.

**Comment by sjmills** [comment]
Yes, but it wastes a lot of time slowing way down while creeping up on the tractor+cart. Watch this video to see the very obvious problem. 

https://www.dropbox.com/s/485uijpjqbht567/CP%20combine%20too%20slow.mov?dl=0

**Comment by Tensuko** [comment]
Becouse you drive in front of the combine.

**Comment by Tensuko** [comment]
Approach from behind and it does work as intended.

**Comment by sjmills** [comment]
It didn't do that in 19. And I'm not in front of the combine, I'm beside it. It is very frustrating trying to match the speed of the combine when it keeps slowing down to 2mph and it should be traveling at 6-10mph, depending on the combine and header. And with some combines and headers, you HAVE to drive that close to it with the cart because of the pipe length.

**Comment by Tensuko** [comment]
"it didn't in 19" We are not in 19!

What do you not understand when I tell you to approach from behind and then drive next to und to unload and:


> When **_unload_** it doesn't slow down.

**Comment by sjmills** [comment]
I keep comparing it to 19 because this is a new BUG compared to 19. Having a worse user experience with the 22 version of CP compared to the 19 version is not a good way forward.

The video only showed one time where I was in front of it waiting for it to catch up. This is a very real-world situation. What I did not capture in the video was me approaching from BEHIND and it still slowing down to 2mph before the pipe was fully extended and it started to unload. This is a bug. I don't know why you're so reluctant to admit this is a bug.

It's even worse on a curvy course because the tractor is constantly getting in the way of the header, even though it's very much traveling in the harvested area, NOT ACTUALLY IN FRONT OF THE HEADER'S PATH.

**Comment by Tensuko** [comment]
If you compare it to 19 its your problem.
We have started all over for some reasons.

And you where in front of the header, it doesn't matter if to the side or not!
Think of turning of the combine, it have to look to the side and thats what we do.

Believe me or not. Thats how it is,c thats how it does work and it does work fine!

**Comment by sjmills** [comment]
A combine driver would not look to the side when the path is straight ahead. It should not care that a tractor is ahead of the header when it is off to the side and has no chance of an actual collision. A real farmer driving a combine would not slow down like CP is doing in 22. Take a look at this new video capture and see how many times the combine slows down when it has no reason so, making it even harder for the tractor+cart driver to get into position and match the speed.

https://www.dropbox.com/s/r8ruktne8sfethk/CP%20combine%20bug.mp4?dl=0

**Comment by Tritura2** [comment]
> A combine driver would not look to the side when the path is straight ahead.
>
>

I drove a combine and I always checked on the tractor and trailer to my side. And especially with your driving style, I wouldn’t not drive at all during unloading.

> … has no chance of an actual collision.
>
>

Your cutting table is way to big for this harvester, you hit it almost every time.

When you approach it from behind and stay there till unloading starts there are no problems. Just use a smaller cutting table and try not to get in front of the harvester while it’s not unloading.

**Comment by sjmills** [comment]
We work with what we have or can afford at the time. There is plenty of space between them. The hit testing to the side is simply far too sensitive in this version of CP. Base game helpers don’t do that, and neither should CP.
