### ISSUE TITLE
7.0.0.7 - Course cant be deleted. 

### ISSUE THREAD

**Issue by UberKiller** [Courseplay/Courseplay_FS22#153]
I can't delete the course in the right and all the ones that I create in that field are being overlapped with that old one

![20211227011655_1](https://user-images.githubusercontent.com/22575569/147425514-fbf906d6-cfe3-4121-b388-bb4e6599f6e0.jpg)
![20211227011705_1](https://user-images.githubusercontent.com/22575569/147425515-502163ad-e6f0-41ef-ac7a-bfa7d4bd5237.jpg)

**Comment by dansiegel1109** [comment]
Same, but I figured it was an obvious decision by them to make the file management system as simplistic as possible for now, while working on things we can't do ourselves.  You can delete the files in the modSettings directory (need to quit FS to do so though)

**Comment by UberKiller** [comment]
Oh so just deleting the saved fields solves the problem?

**Comment by UberKiller** [comment]
> Oh so just deleting the saved fields solves the problem?

Noup I deleted all the folders with courses and that one is still there :(

**Comment by dansiegel1109** [comment]
Well I ASS-u-MEd they could be deleted in Windows Explorer if FS is closed (as FS and CP would have open access to those files making them unwritable, hence undeletable, by anyone except them).  Maybe delete the mod and reinstall, saving any other courses you may want to keep first?  That's strange, but I didn't develop it - who knows, there may be a different file with a strange name, to store the last loaded course.  Check out all the file contents, see what you can find.

Unfortunately, course and file management is about the worst thing in CP so far(I guess that's a good thing, just like Giants slow internet speed is my biggest complaint of FS22 atm, so much was fixed in 1.2.0.0), and I would think a low priority for them atm, as a good job would take a bit more time.  Its got super potential with the embedded menus.   However, I would prefer them to work on all of the tiny but greatly impacting bugs with CP's control of the vehicles and implements, else the courses are useless, even if you can't delete courses, overlapping courses, especially when having 2 vehicles on the field (not multi tool, one mulching, another cultivatingf for example), etc.  Lol, its only been out 2 days!  I'm sure it will all be fixed in good time, but still great to have this ticket so they can track and not forget about it.

**Comment by Tensuko** [comment]
I dont understand the problem here. It works just fine for me.
Click delete then click on the course...

**Comment by dansiegel1109** [comment]
I've never seen a delete button on there, but I am still on 7.0.0.5, from the other day (you guys drop patches quick!).  I'll update and re-check to confirm with the OP.

**Comment by UberKiller** [comment]
> I dont understand the problem here. It works just fine for me. Click delete then click on the course...

TEnsuko that's the problem the delete button doesn't delete that course, I can create new ones, multiple ones, all they can be deleted, that one its there since the 0.4 or 0.3 I dont remember with one was

**Comment by Tensuko** [comment]
Oh so you mean one specific course can't be deleted ?
Can you make a screenshot of where it is in the manager ?

We would need to know how you managed to create that bug so we can else prevent or fix it.

**Comment by pvaiko** [comment]
Just open windows explorer and delete that course from there...

**Comment by schwiti6190** [comment]
@UberKiller This seems to me a transition bug between versions and not in the current version ? Those might happen, as we are in the middle of developing CP. Similar bugs happen with early access game, where the save game is broken after a patch and so on. 
You can try to reset the affected vehicles back to the shop or delete the corrupted files in the windows explorer. 
There isn't really anything we could do to fix this bug, if the bug isn't appearing in the current version with a fresh savegame :)

**Comment by Markus33-ITA** [comment]
> I can't delete the course in the right and all the ones that I create in that field are being overlapped with that old one


I don't know how and I don't know why, but when you change the vehicle the previous one remains selected and the track is created on that vehicle. I was working with the 2.5m cultivator. finished the work I delete the track, pass in some places and park. I change vehicle and put on a 9m weeder. I take the vehicle close to the field, open the various menus to generate the course and see the anomaly 2.5m. not wanting to reach 9m with the click of the mouse, I decide to cancel. the button was there but it didn't delete anything. the course was generated with the vehicle I used before. selecting that vehicle, I was able to delete it and the map is clean.

**Comment by UberKiller** [comment]
> Just open windows explorer and delete that course from there...

Before something shit just read the tread -.-

**Comment by UberKiller** [comment]
> @UberKiller This seems to me, as it is a transition bug between versions and not in the current version ? Those might happen, as we are in the middle of developing CP. Similar bugs happen with early access game, where the save game is broken after a patch and so on. You can try to reset the affected vehicles back to the shop or delete the corrupted files in the windows explorer. There isn't really anything we could do to fix this bug, if the bug isn't appearing in the current version with a fresh savegame :)

I deleted all the courses in the Singleplayer folder, are anymore any places the files can be? or it's better to just uninstall the mod (and all the folders associated) and reinstall it with a new version?

**Comment by UberKiller** [comment]
> Oh so you mean one specific course can't be deleted ? Can you make a screenshot of where it is in the manager ?
> 
> We would need to know how you managed to create that bug so we can else prevent or fix it.

I went back to the game to show that the course is not even in the coursemanager, that's why I can't delete it even with no fields loaded it's still there. It's not even showing In the game like the overlay above the fiel
![20211228011306_1](https://user-images.githubusercontent.com/22575569/147517370-2762e96d-30c8-47ce-b1dc-ef76560a1d1c.jpg)
![20211228011313_1](https://user-images.githubusercontent.com/22575569/147517372-58ea84dc-c324-47e6-982b-5dca783b5975.jpg)
![20211228011325_1](https://user-images.githubusercontent.com/22575569/147517373-8c05b59a-13dc-438d-9a49-07f9b5d460b5.jpg)
![20211228011330_1](https://user-images.githubusercontent.com/22575569/147517374-ef336d7a-c604-4241-9d36-c75df1e448d2.jpg)
d

**Comment by Markus33-ITA** [comment]
Hi. Go to each vehicle and open the save route menu and see if there is a cancel button.

**Comment by Tensuko** [comment]
The thing is that I can just generate a new course and the old one is gone...

**Comment by UberKiller** [comment]
I will try to get the savegame without the mod, saving and getting the mod back to see if the course its still there or not

**Comment by UberKiller** [comment]
> I will try to get the savegame without the mod, saving and getting the mod back to see if the course its still there or not

SOLVED, I did that and the old course its no longer there
