### ISSUE TITLE
[BUG_SP] Getting a Message Courseplay has an Error During Course Creation and to Check the Log

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#1531]
**Steps to reproduce**
Currently trying to create a course in game using the Big M Mower to mow a grass field. Have gone onto the field and chosen it as the target, opened up the Course Generator, set my settings that I want to use and then try to generate the course. I then get a message that an error has occurred and to check the log. Have tried changing headland numbers, up and down row directions and each time I try to generate a course to mow the field, I'm getting the same error.

**Courseplay version**
Version used: 7.0.1.14

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8640212/log.txt)

**Map**
Map played on. Calmsden Farm

**Vehicles/ implements involved**
Big M Mower

**Relevant script mods**
Gudiance Steering and Autodrive Installed and are latest versions currently available to public.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8640212/log.txt)

**Comment by Tensuko** [comment]
#1517
