### ISSUE TITLE
[BUG_SP] Harvester unfolds every time save file is loaded or trailer is attached or detached

### ISSUE THREAD

**Issue by billw2012** [Courseplay/Courseplay_FS22#1532]
**Steps to reproduce**
Create new SP save on Elm Creek, buy an X9 and a header trailer, attach one to the other and note that the harvester instantly unfolds.

**Actual behavior**
Once I install version 7.0.1.14 my harvesters (two Deere X9 1100 with NARDI N60-45 trailer and 45ft header) are unfolded when I enter my save game, and any change I do to them, connecting or disconnecting trailer for instance, causes them to instantly unfold. Reverting to the previous CP version fixes the issue.
I also reproduced this in a brand new save on Elm with only CP mod and same equipment (no header necessary).

**Expected behavior**
The harvesters will not unfold except when I tell them to, or as part of normal AI operations.

**Screenshots**
https://imgur.com/a/52LTQje

**Courseplay version**
7.0.1.14 

**Log**
https://pastebin.com/S0hVd9q6

**Map**
Hobo 4X / Elm Creek

**Vehicles/ implements involved**
Deere X9 1100 with NARDI N60-45 trailer and 45ft header

**Relevant script mods**
No mods

**Comment by Tensuko** [comment]
#1511 
Abwarten...
