### ISSUE TITLE
[BUG_SP] HKL LKW fliegt beim Container anhängen durch die Luft

### ISSUE THREAD

**Issue by Gaspode01** [Courseplay/Courseplay_FS22#1533]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Conainer an den LKW anhängen.
Unter Courseplay for FS22 v7.0.1.13 war dieses Problem nicht
Alle mods aus dem Ordner "mods" entfernt, nur "Courseplay for FS22 v7.0.1.14" und "FS22_ScaniaR_ITRunner_pack" im mods Ordner.
Beim anhängesn eines Conainers, fliegt der LKW durch die Luft.

"Courseplay for FS22 v7.0.1.14" gegen "Courseplay for FS22 v7.0.1.13" getauscht, Problem nich vorhanden.

**Actual behavior**
Beim anhängen eines Conainers an den LKW "FS22_ScaniaR_ITRunner_pack" fliegt dieser durch die Luft.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: Courseplay for FS22 v7.0.1.14

**Map**
Elmcreek
auf allen Maps

**Vehicles/ implements involved**
Which vehicle or implement?
LS22 SCANIA R ITR PACK BY AP0LLO v1.0.0.2
Courseplay for FS22 v7.0.1.14

Mod yes/no ?yes

**Relevant script mods**
Courseplay for FS22 v7.0.1.14

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8644546/log.txt)
![LKW](https://user-images.githubusercontent.com/105058573/167240282-be04e810-dae0-4d0c-a4e3-4665af1ddcb2.jpg)

**Comment by Tensuko** [comment]
fixed soon #1511
