### ISSUE TITLE
[BUG_SP] Beim An- und Abhängen des Schneidwerks oder des Schneidwerkwagens klappt der Mähdrescher auf

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#1534]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Fehler tritt mit verschiedenen Mähdreschern auf verschieden Karten auf.

**Actual behavior**
Beim An- bzw. Abhängen von Schneidwerk oder Schneidwerkswagen klappt der Mähdrescher auf.

**Expected behavior**
Der Mähdrescher sollte eingeklappt bleiben.

**Screenshots**
siehe Video

**Courseplay version**
Version used: 7.1.0.14

**Log**
Keine Einträge im Log.

**Map**
LK Rostock / Frühling / NF Marsch

**Vehicles/ implements involved**
NH CH 7.70 / DF Topliner / etc.
Mod yes/no ?
Fehler tritt bei Ingame-Fahrzeugen als auch bei Mods auf.

**Relevant script mods**
Fehler tritt schon bei alleiniger Verwendung der aktuellen CP-Version auf.

https://user-images.githubusercontent.com/76711921/167250214-96b0e928-8c7b-4680-a153-810767015896.mp4

**Comment by Tensuko** [comment]
#1511
