### ISSUE TITLE
[BUG_SP] Could not generate course / Can't fit more headlands in field, using 0

### ISSUE THREAD

**Issue by gSe7eN** [Courseplay/Courseplay_FS22#1535]
**Steps to reproduce**
Join fields 45, 46, and 47 (in my save, this is field CP-4) on the french map. Try to generate a harvest course using any settings with the Claas combine (non modded, from vanilla game) using the 13.8m header. Setting headlines to 1 or 0 generates the error.

**Actual behavior**
"Could not generate course. The log may have more information."
Log attached.

**Expected behavior**
A course to be generated for the harvester to follow.

**Courseplay version**
7.0.1.14

**Log**
[https://gist.github.com/gSe7eN/16c644526f7a06323da5a2748315faec](url)
(cpFields.xml included)

**Map**
built in French map

**Vehicles/ implements involved**
Which vehicle or implement? Lexion 8900 with 13.8m blade
Mod yes/no ? Nah

**Relevant script mods**
AD is installed.

**Comment by dkfiremann** [comment]
Same as #1516 ?

**Comment by gSe7eN** [comment]
I only read English so I'm not sure of the specific bug there, but the error in the log doesn't quite look the same. That error looks like the combine isn't unfolding itself before trying to begin work, which is an error I AM having but isn't the same as this bug.

**Comment by pvaiko** [comment]
Pretty sure same as #1516, can't read your attached log, reopen if it does not work with 7.0.1.15

**Comment by gSe7eN** [comment]
> Pretty sure same as #1516, can't read your attached log, reopen if it does not work with 7.0.1.15

Sorry about that, first time using gist. Here's the log on PB. https://pastebin.com/jAKtSEhP

**Comment by gSe7eN** [comment]
Still an issue in 7.0.1.15

I also tried with various other vehicles and manually setting the width to the combine blade. Still errors.

**Comment by pvaiko** [comment]
This really looks like that those fields are not joined cleanly, there may be some non-field areas left between them, one of the logs shows islands detected. 

You may want to try manually create the field boundaries or find those little islands somewhere.

**Comment by gSe7eN** [comment]
Pvaiko was correct. I deleted the field, redrew it by hand on the map (rather than use a vehicle which would have been the next step) and that allowed me to create headlands.

This was user-error. Thanks, everyone.
