### ISSUE TITLE
[BUG_MP] Anbaugeräte klappen beim an-/abkuppeln auf

### ISSUE THREAD

**Issue by hnsstrk** [Courseplay/Courseplay_FS22#1536]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Anbaugeräte an- oder abkuppeln.

**Actual behavior**
Anbaugeräte klappen beim an-/abkuppeln auf.
Drescher öffnet sich beim ankuppeln des Mähwerks.

**Expected behavior**
Die Anbaugeräte sollten in ihrem aktuellen Zustand (zusammengeklappt) bleiben.
Gleiches gilt für den Drescher. Dieser sollte beim Ankuppeln des Mähwerks nicht aufklappen.

**Screenshots**

**Courseplay version**
Version used: Courseplay for FS22 v7.0.1.14

**Client Log**
https://github.com/hnsstrk/ls22

**Server Log**
https://github.com/hnsstrk/ls22

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Map played on: FS22_WildWest_16x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

- JD 7R 350/196 - no mod
- 9MT (Pflug - Blacksheep) - mod

**Relevant script mods**
Mods like Autodrive or VCA and so on.Name	Version	Author	Filename	Size	Issues	Active	 	 
Wild West 16x by Cazz64	1.3.0.0	Cazz64, OAG	FS22_WildWest_16x.zip	878.17 MB	3	Yes		
AutoDrive	2.0.0.5	AutoDrive Team	FS22_AutoDrive.zip	1.72 MB	1	Yes		
CoursePlay	7.0.1.14	Courseplay.devTeam	FS22_Courseplay.zip	2.64 MB	1	Yes		
Better Contracts	1.2.2.0	Mmtrx	FS22_BetterContracts.zip	0.07 MB	 	Yes		
Claas And Krone Baler Pack With Lizar...	1.0.0.0	Hispano	FS22_Claas_Krone_Baler_Pack_With...	25.64 MB	 	Yes		
Collect Straw At Missions	1.0.0.0	derSchreiner	FS22_CollectStrawAtMissions.zip	0.01 MB	 	Yes		
EnhancedVehicle	1.2.1.0	Majo76	FS22_EnhancedVehicle.zip	0.14 MB	 	Yes		
Headland Management	2.1.0.2	Jason06 / Glowins Mod...	FS22_HeadlandManagement.zip	0.09 MB	 	Yes		
LIZARD Subsoiler 6MT/9MT	1.0.0.0	Blacksheep Modding	FS22_Lizard_MT.zip	3.97 MB	 	Yes		
MAN TGX Forest Semi-Truck	1.0.0.1	HR Forst und Fahrzeugbau	FS22_MAN_TGX_Forest.zip	28.09 MB	 	Yes		
Meridian Storage Yard	1.0.0.0	Malidene Modding	FS22_MeridianStorageYard.zip	1.30 MB	 	Yes		
MoreTrees	1.0.0.0	KR-Softwares	FS22_MoreTrees.zip	0.06 MB	 	Yes		
Parking Spaces	1.0.0.0	CookieCat	FS22_Parking_Spaces.zip	22.31 MB	 	Yes		
Farm Silo Multi XL	1.0.0.0	Digipea	FS22_SiloMultiXL.zip	5.07 MB	 	Yes		
High Pressure Washer Stihl RE581	1.0.0.0	Blacksheep Modding	FS22_Stihl_RE581.zip	2.44 MB	 	Yes		
Tajfun EGV 80 AHK	1.0.0.0	50keda	FS22_TajfunEGV80AHK.zip	4.52 MB	 	Yes		
Vehicle Control Addon	1.1.0.0	mogli	FS22_VehicleControlAddon.zip	0.49 MB	 	Yes		
Air Hose Connect Sound	1.1.0.0	PeterAH (Modding-Welt)	FS22_airHoseConnectSound.zip	0.05 MB	 	Yes		
American Fermenting Silos	1.0.0.0	VertexDezign	FS22_americanFermentingSilos.zip	27.10 MB	 	Yes		
Bednar SWIFTER SM 18000	1.0.0.0	GIANTS Software	FS22_bednarSM18.zip	17.27 MB	 	Yes		
Bourgault 3320-76 Paralink Hoe Drill ...	1.0.0.1	GIANTS Software	FS22_bourgaultSeries3320.zip	65.71 MB	 	Yes		
Bourgault 3420-100 Paralink Hoe Drill...	1.0.0.1	GIANTS Software	FS22_bourgaultSeries3420.zip	54.89 MB	 	Yes		
Bourgault SPS360-40	1.0.0.0	GIANTS Software	FS22_bourgaultSps360_50.zip	20.77 MB	 	Yes		
Bourgault XR770 Harrow	1.0.0.0	GIANTS Software	FS22_bourgaultXR770.zip	17.45 MB	 	Yes		
Bredal F2WS4000	1.0.0.0	MefiuFs	FS22_bredalF2WS4000.zip	4.71 MB	 	Yes		
Bressel Und Lade Shovel Pack	1.0.0.0	VertexDezign	FS22_bresselUndLadeShovelPack.zip	5.13 MB	 	Yes		
CASE IH Magnum 7200 Pro Series	1.0.0.1	GIANTS Software	FS22_caseIHMagnum7240Pro.zip	23.61 MB	 	Yes		
Ground Stains	1.0.0.0	TopAce888	FS22_groundStains.zip	5.01 MB	 	Yes		
Guidance Steering	2.1.6.0	Wopster	FS22_guidanceSteering.zip	0.15 MB	 	Yes		
Hatzenbichler Terminator 18 / TH 1400	1.0.0.0	GIANTS Software	FS22_hatzenbichlerTerminator18.zip	38.43 MB	 	Yes		
Kinze Wagon Pack	1.0.0.0	GIANTS Software	FS22_kinzeWagon.zip	24.31 MB	 	Yes		
Kverneland TLX Geospread	1.0.0.0	GIANTS Software	FS22_kvernelandTLXGeospread.zip	9.60 MB	 	Yes		
New Holland W190D	1.0.0.1	GIANTS Software	FS22_newHollandW190D.zip	26.05 MB	 	Yes		
Placeable Borderstones/Flowerpot	1.0.0.0	AgrarDani	FS22_placeable_borderstones.zip	0.33 MB	 	Yes		
Placeable Silos	1.0.0.0	DD ModPassion	FS22_silos_placeable.zip	2.25 MB	 	Yes

**Comment by Tensuko** [comment]
Update kommt vlt heute noch, bitte Geduld bin gerade bei ein paar tests bei...
