### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by PCGamer330** [Courseplay/Courseplay_FS22#1538]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
When i downloaded the MOD Courseplay it comes up in my downloaded mods menu but when i create a new world it isnt a selectable mod.
**Screenshots**

**Courseplay version**
Version used:  7.0.1.14

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
elmcreek
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
it doesnt work in any vehicle 
**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
no log,
download the correct .zip and place in mods folder, done.
https://github.com/Courseplay/Courseplay_FS22/releases
