### ISSUE TITLE
Multi Tool

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#154]
Is there a selection to generator a course for multitool (using two of the same tool) on the same field at the same time?  I see there is Multitool settings, but I do not see a setting in the Course Generator for selecting how many tools.

**Comment by dansiegel1109** [comment]
Multitool is not supported at the moment even though the settings framework is there.

**Comment by Resandise** [comment]
> Multitool is not supported at the moment even though the settings framework is there.

That's what I figured, but wanted to make sure I was not missing something obvious.  Thanks

**Comment by Tensuko** [comment]
Will come back and I am sure we already got an Issue for this
