### ISSUE TITLE
Cant Select the mod in game

### ISSUE THREAD

**Issue by PCGamer330** [Courseplay/Courseplay_FS22#1540]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
i tried redownloading the mod aswell as updating it and restarting my PC 
**Actual behavior**
A clear and concise description of what happen.
when i open the downloaded mods section in game it shows courseplay as a downloaded mod however when i open my world and it asks me to select the mods i want it doesnt show courseplay on that menu 
**Expected behavior**
i expected the mod to be selectable so i can use it in my game save for filed work 
**Screenshots**

**Courseplay version**
Version used: 
7.0.1.15
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
elmckreek 
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

PLEASE HELP ME I WOULD LOVE TO USE THIS MOD

**Comment by Tensuko** [comment]
What about a logfile and where did you download it ?

"PLEASE HELP ME I WOULD LOVE TO USE THIS MOD" is not any helpful......

**Comment by PCGamer330** [comment]
Sorry about the lack of title and the message at the bottom. 

i downloaded it from github here i saw a link for it from a youtube video. 

What is a logfile ? how would i get that for you ?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by PCGamer330** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8647464/log.txt)

**Comment by dkfiremann** [comment]
From your log :
"Error: Invalid mod name 'FS22_Courseplay (2)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit"
Make sure the name of the file is correct.

**Comment by PCGamer330** [comment]
Thank you so much, it seems to work now. have a great day/night
