### ISSUE TITLE
[Question] field speed and turning speed

### ISSUE THREAD

**Issue by SirSwissOfCheese** [Courseplay/Courseplay_FS22#1541]
Hi, does it have to be the case that when working in the field and turning on the field to the next lane, the field speed is used and not the turning speed? when the field speed is to high, in my case 45km/h then it will not correctly drive backwards in the lane and this happen (screene)

best regards

![grafik](https://user-images.githubusercontent.com/96531039/167307262-93cb92c8-ae16-49c5-aa9b-bb0e71169fdc.png)
![grafik](https://user-images.githubusercontent.com/96531039/167307266-137015c0-17a1-4950-bab9-1f6fd54755a1.png)

**Comment by SirSwissOfCheese** [comment]
no idea because the pictures are so bright

**Comment by Tensuko** [comment]
Drive slower on the filed.
Turnspeed is only the turn manuvers and not between them, so not the full turn.
45km/h field speed for this vehicle, not sure why you would do this.
Set it lower and its fine.

**Comment by SirSwissOfCheese** [comment]
I have the field speed so high because I wanted to drive a little faster when leaving or driving on it. I have them on 30 km/h now and it's fine with it.
