### ISSUE TITLE
Kann man Oliven auch mit CP ernten/bearbeiten?

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/Courseplay_FS22#1542]
Moin, meine Frage steht eigentlich schon oben, bin auf den gedanken gekommen,  da es bei dem Let'sPlayer Gadarol funktioniert hat. Leider hat's bei mir nicht hingehauen daher die Frage, ob sowas geht, falls ja wie und wenn nicht ob man sowas implementieren kann?

Grüße

**Comment by Tensuko** [comment]
Ja, siehe Ingame Anleitung (Hilfe Menü).
