### ISSUE TITLE
[BUG_SP] Plow missing areas after turn

### ISSUE THREAD

**Issue by Symbob** [Courseplay/Courseplay_FS22#1544]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

When creating a new field where no field exists.  Created a custom field then generated course with "Allow create fields" activated on the plow.

**Actual behavior**
A clear and concise description of what happen.

After the tractor turns at the end of the field then drops the plow in to work again, to start its next pass, the tractor steers away from the plowed land momentarily then adjusts position back to where it should be.  This results in areas of unplowed ground at the ends of the fields.  It appears to be worse when creating new fields because of the way the tractor turns.  The tractor has "Only turn on field" enabled but by disabling "Only turning on Field" this changes the way the tractor turns on the end and the problem is less obvious but smaller parts of the field are still left unplowed

**Expected behavior**

With version 7.0.1.14 and before this was not a problem.  The tractor drops the plow and drives straight in the correct position without adjusting it's position so that no areas are missed between passes.  This has only started happening with v7.0.1.15.

**Screenshots**

![fsScreen_2022_05_09_11_05_48](https://user-images.githubusercontent.com/18528850/167400432-1b1e2ecd-0892-4dd6-81ea-bd82e06db4aa.png)
![fsScreen_2022_05_09_11_05_50](https://user-images.githubusercontent.com/18528850/167400441-6a2262a4-1805-44fa-bc2c-1706dc9988a8.png)
![fsScreen_2022_05_09_10_52_26](https://user-images.githubusercontent.com/18528850/167400447-3eba99fc-1919-4697-a348-34eb16dd9de7.png)
![fsScreen_2022_05_09_11_03_26](https://user-images.githubusercontent.com/18528850/167400453-582352ab-20f2-4742-b150-7f0755e42c44.png)
![fsScreen_2022_05_09_11_03_27](https://user-images.githubusercontent.com/18528850/167400458-32eb5604-f552-479a-8431-82171e723088.png)
![fsScreen_2022_05_09_11_03_30](https://user-images.githubusercontent.com/18528850/167400468-6cb22d43-686b-4e25-a09b-7a3e174ab390.png)
![fsScreen_2022_05_09_11_05_46](https://user-images.githubusercontent.com/18528850/167400478-3157b3fc-eebb-4988-b360-2048a3798da9.png)

**Courseplay version**
Version used: 7.0.1.15

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8651152/log.txt)

**Map**
Map played on.

No Mans  Land

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

In game MF 3670 tractor and Kverneland Ecomat plow

**Relevant script mods**
Mods like Autodrive or VCA and so on.

None

**Comment by Symbob** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8652697/log.txt)

**Comment by Tensuko** [comment]
@pvaiko we have that one time jumping PPC target again on the wrong side, even the turn is created correctly, the next PPC is on the wrong offset and then jumps back on the correct one.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8701788/log.txt)

**Comment by bojanh66** [comment]
I have the same problem when plowing fields, worker will miss some spots when turning from row to row.
![FarmingSimulator2022Game 2022-12-14 22-17-25](https://user-images.githubusercontent.com/32069662/207716567-558c6f0d-f2bf-4ba2-8d4b-3aa5f7fbd1b6.png)
