### ISSUE TITLE
[Enhancement] Horizontaler Versatz speichern bei Fieldwork.

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#1548]
### Discussed in https://github.com/Courseplay/Courseplay_FS22/discussions/1546

<div type='discussions-op-text'>

<sup>Originally posted by **Ulanawius** May  9, 2022</sup>
Vielen Dank für die tolle Arbeit an CP. Es ist toll, wie viel schon nach so kurzer Zeit möglich ist.
Aktuell lasse ich drei Mähdrescher mit unterschiedlicher Arbeitsbreite (7,7m / 12m / 13,8m) im Verband arbeiten. Das funktioniert prima, wenn man den Kurs entsprechend berechnet und den richtigen horizontalen Versatz zu jedem Drescher einstellt.
Bei einem Neustart des Spiels ist der Versatz jedoch wieder zurückgesetzt, sodass der Verband erstmal nicht richtig startet. Wäre es möglich, zusammen mit dem Kurs auch den Versatz zu speichern und beim Neustart wieder zu laden?
![Farming Simulator 22 09 05 2022 21_55_50](https://user-images.githubusercontent.com/76711921/167489201-0f908c0d-595b-48b8-bcc3-d380ae387861.png)
![Farming Simulator 22 09 05 2022 21_46_20](https://user-images.githubusercontent.com/76711921/167489224-2569fedf-114c-44ad-a770-e73a2ab4caa2.png)
![Farming Simulator 22 09 05 2022 22_10_22](https://user-images.githubusercontent.com/76711921/167489509-f7cecfd9-6fb2-4fca-9a54-a971c5990098.png)

</div>

**Comment by Ulanawius** [comment]
Das Speichern des Versatzes wäre auch z.B. beim Kartoffelroder EVO 290 hilfreich. Da die Deichsel separat ausgefahren wird (nicht beim Aufklappen des Gerätes), wird der horizontale Versatz mit -0,7m berechnet. Richtig wäre aber -2,5m. Dieser Wert muss immer wieder manuell eingestellt werden, da nach einem Neustart wieder die -0,7m eingestellt sind.
