### ISSUE TITLE
[BUG_SP] Kartoffelroder Ventor 4150 wendet nicht mehr

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1549]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Feldkurs anlegen (bei mir war es ein Kurs mit fünf Vorgewendebahnen, dann hoch/runter) und Roder arbeiten lassen

**Actual behavior**
Kartoffelroder Ventor 4150 wendet nicht mehr, er fährt nur noch rückwärts, bis er irgendwo anstößt

**Expected behavior**
Wende des Kartofffelroders am Ende der Bahn

**Screenshots**

![fsScreen_2022_05_10_10_54_35](https://user-images.githubusercontent.com/16411797/167590007-b43dfae8-7cf9-4818-ab14-1ad3dc47622a.png)

**Courseplay version**

Version used: 7.0.1.15

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8660001/log.txt)

**Map**

Hobo's Hollow

**Vehicles/ implements involved**

Grimme Ventor 4150

**Relevant script mods**
AutoDrive
Courseplay

**Comment by Tensuko** [comment]
Workarround: Wenden auf Feld auschalten.

@pvaiko Das ist irgendwie wieder der reverse part der zu kurz ist, warum das nun wieder, kein Plan.

**Comment by Tensuko** [comment]
Still valid, however with 6 Headlands it should have no problem to turn correct.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9674351/log.txt)
