### ISSUE TITLE
[BUG_SP] 8RT drive to fieldwork LUA Error

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#1550]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Attempt to generate course with 8RT from 8RT pack

**Actual behavior**
with any implement on the 8rt, fails to generate or pathfind. also noticed this with the 9RT.

![20220510104715_1](https://user-images.githubusercontent.com/5993529/167680133-fda13fef-0c3d-437d-9d36-61a680f59cfb.jpg)

**Courseplay version**
Version used: 7.0.1.15

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
PMC undefined 20x20

**Vehicles/ implements involved**
9RT from the 9 r pack from CMG
8RT from 8 r pack

**Relevant script mods**
Courseplay

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8663165/log.txt)

**Comment by Tensuko** [comment]
Thats a Mod Issue then.

**Comment by Commissar0617** [comment]
also occuring with stock 8RT

**Comment by Tensuko** [comment]
Oh, a useful information appeared :)

Any weight attached ?

**Comment by pvaiko** [comment]
Root cause seems to be the same as #1535

**Comment by pvaiko** [comment]
The log you attached does not contain the error on your screenshot, it has errors when generating the course. 

Can you post a screenshot where you generate the course, the field and the field boundary (white lines) clearly visible?

**Comment by Commissar0617** [comment]
> Oh, a useful information appeared :)
> 
> Any weight attached ?

As part of the tractor,  yes. Not an external, as the RT lacks a front 3 point. I tried to replicate again last night... and it's not doing it now, despite me changing nothing.  I'll see if i can get it to do it again.
