### ISSUE TITLE
ISARIA PRO nitrogen sensors inactive (Precision Farming)

### ISSUE THREAD

**Issue by oggimaster** [Courseplay/Courseplay_FS22#1553]
Greetings,

the nitrogen sensors ISARIA PRO Active and Compact (Precision Farming DLC) are inactive while Courseplay is running.
If I activate them before I start the course, they will get deactivated.

I'm sure that feature doesnt exist yet. It could work like the fertilization option on seeders.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues?q=Isaria
