### ISSUE TITLE
[BUG_SP] Vehicle drives off course

### ISSUE THREAD

**Issue by billw2012** [Courseplay/Courseplay_FS22#1554]
**Steps to reproduce**
https://www.dropbox.com/s/mj4bdqz815hgng0/courseplay_issue_repro_save_and_mods.7z?dl=1

Load my save and mods, find the Quadtrac with the Bourgualt FMS CD872-8 attached (8m planter) crashed into a tree, reposition it so it can move freely, then start its courseplay in "last waypoint" mode (check the youtube video link below to see this). 

The general repro is not clear, I have seen this bug reported before but it seems like it must be some very specific set of circumstances to do with path finding. It might be made worse with articulated tractors (quadtrac seems to get it a lot?) on multitool courses. I have seen it probably once an hour or so.

**Actual behavior**
Occasionally a vehicle on a course doing a turn will just continue on a straight line until it hits something. 

**Expected behavior**
Of course for it to remain on the specified course, or navigate the turn in a reasonable manner.

**Screenshots**
![image](https://user-images.githubusercontent.com/1453936/167960933-e9e37607-7415-4c86-93eb-98695b26e795.png)
![image](https://user-images.githubusercontent.com/1453936/167960941-1eb1d7f0-f376-4219-9543-86c2fc3a691b.png)
![image](https://user-images.githubusercontent.com/1453936/167960948-cdc3acea-5250-4320-bd72-6a41ca92c2fa.png)

https://youtu.be/XZvgqa0NT_g

**Courseplay version**
Version used: 7.0.1.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8673889/log.txt)

**Map**
Hobos Hollow 4x

**Vehicles/ implements involved**
Case Quadtrac (vanilla) + Bourgualt FMS CD872-8 (mod)

**Relevant script mods**
None

**Comment by CGPandaX** [comment]
The problem I encounter is that when multiple machines work together, no matter how they are set, they will eventually bump into each other.

The distance setting does not work at all.

**Comment by Tensuko** [comment]
@billw2012 the turn git generated wrong, no idea why that happened.

@CGPandaX 1st this got nothing to do with this issue, 2nd multitool works fine and the distance control does work too. If not on your side you dud something wrong.

**Comment by billw2012** [comment]
Its the last turn on the center rows of a multi-tool course starting on center instead of headlands.

**Comment by billw2012** [comment]
> @billw2012 the turn got generated wrong, no idea why that happened.

What about the driving off in a straight line until crashing? Is that because the maneuver gets aborted or has an error and it just keeps the last AI state which is driving in a certain direction? A good start would be just having the error behaviour be to stop, rather than drive off. I have had them ending up at the map edge or in a river before which makes recovery much more painful than if it just stopped and reported an error!
