### ISSUE TITLE
[Enhancement] Kollisionserkennung für Traktoren

### ISSUE THREAD

**Issue by LAWI-Game** [Courseplay/Courseplay_FS22#1555]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Neues Spiel starten. Ein Traktor als Hindernis. Ein Traktor mit Helfer oder CP arbeiten lassen. 
Start new game. A tractor as an obstacle. Let a tractor work with helper or CP.

**Actual behavior**
Helfer soll vor Hindernis stehen bleiben. Sowohl Giants Helfer als auch CP Helfer rammen Hindernis
Helper should stop in front of obstacle. Both Giants Helpers and CP Helpers ram obstacles

**Expected behavior**
Vor Hindernis stehen bleiben
stop in front of an obstacle

**Screenshots**
Spiel ohne Mods: Helfer steht vor Hindernis:
Game without mods: helper faces obstacle:
![fsScreen_2022_05_12_14_56_52](https://user-images.githubusercontent.com/3209042/168083224-179ff681-12b9-486f-b2ed-559be57330d2.png)

Giant Helfer mit CP im Mod Ordner
Giant helper with CP in the mod folder
![fsScreen_2022_05_12_15_03_52](https://user-images.githubusercontent.com/3209042/168083609-45705414-f387-49d6-a55a-d50a569f269a.png)

CP Helfer rammt Hindernis
CP helper rams obstacle
![fsScreen_2022_05_12_15_17_48](https://user-images.githubusercontent.com/3209042/168083875-b96da2bb-bc49-477e-ad84-ce2736fe3d1c.png)

**Courseplay version**
Version used: 7.0.1.15

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8679368/log.txt)

**Map**
Standard /default

Vehicles/ implements involved
Giants
Mod yes/no ? nur CP

Relevant script mods
keine /none

**Comment by billw2012** [comment]
Oh good, I was considering adding a bug about this as well, but I thought its expected? Would be nice to have the collision detection and resolution that AD has, where it will stop if something is infront, and reverse when it can't move forward. Often AD is working around CPs lack of collision detection, but it doesn't work when running multi-tool, or multiple courses at the same time. I try to have harvest, straw baling, cultivating etc. start as soon as possible, usually they are running at the same time, but the lack of collision detection or resolution means I am having to very often untangle them. I try to use course setup that will avoid it, e.g. start on the field center, and each pass has larger headlands, but there are still many collisions during turns, or when they catch up with each other...

**Comment by Tensuko** [comment]
@pvaiko 
As I said we would need the sensor for tractors as well, but maybe react to vehicles only.
