### ISSUE TITLE
[Feature] Ordnername im Mini HUD

### ISSUE THREAD

**Issue by AlexStephenLytton** [Courseplay/Courseplay_FS22#1557]
**What is the problem this feature/enhancement solves?**
Egal ob man Kurse in Ordnern nach Aufgabe oder Feldnummer speichert, eine Entscheidende Information im Minihud fehlt immer

**Describe the solution you'd like**
In meinem Fall speichere ich die Kurse pro Feld in Ordnern - ideal wäre es, wenn dann im MiniHUD Beispielsweise nicht nur "AB 6m" sondern (Feld 12) AB 6m stehen würde - also Ordnername in Klammern gefolgt vom Kursnamen... Alternativ wären natürlich auch alle anderen zum trennen geeigneten Zeichen / Zeichenkombinationen möglich ;)

**Describe alternatives you've considered**
Eine Zeile Ordnername und eine Extrazeile für den Kursnamen

**Comment by Tensuko** [comment]
Kein Platz dafür und man sollte wissen auf welchem Feld man arbeitet, meinst du nicht ?

Noch mehr Info wird wieder probleme mit langen namen ergeben, daher nein, wird nicht passieren.
