### ISSUE TITLE
 Collision occurs when multiple machines work together

### ISSUE THREAD

**Issue by ghost** [Courseplay/Courseplay_FS22#1559]
1

**Comment by Tensuko** [comment]
And what does this screenshot show me ?
Wrong working witdh so vehciles that drives towords each other colide ?

Symetric lane change on or off ?

**Comment by CGPandaX** [comment]
> And what does this screenshot show me ? Wrong working witdh so vehciles that drives towords each other colide ?
> 
> Symetric lane change on or off ?

Symmetric lane change on, and I tried to turn it off or on, but the end result was the same.

How can I set it to get the correct working mode? How should I set it?Thank you.

**Comment by Tensuko** [comment]
I still wan't to know whats the actual problem?
Distance or that drive towars each other.
For the "correct mode" (depends on how you want them to drive) check the ingame help menu.

**Comment by CGPandaX** [comment]
> I still wan't to know whats the actual problem? Distance or that drive towars each other. For the "correct mode" (depends on how you want them to drive) check the ingame help menu.
So, if I set them to drive towards each other and they collide it's normal to stop working, right?

Or is it normal for them to collide even after I set the distance?

Okay, I didn't say anything.

Thank you for your contempt.

**Comment by Tensuko** [comment]
You still don't make clear where the problem is...
is it that one overtake the other so the distance is not working in your scenario (generaly it is working!) or is it the direct confrontation wich can be changed with the symetric lane change setting.

2 Different Problems
2 Different Solutions

...
