### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by manello-91** [Courseplay/Courseplay_FS22#1560]
Hallo. 
Bei mir startet das Fahrzeug mit neuem kurs nicht wenn ich auf den pfeil drücke

**Comment by Tensuko** [comment]
Und wie soll ich dir jetzt dabei helfen ?

https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by manello-91** [comment]
hab die neuerste version drauf

**Comment by Tensuko** [comment]
Das reicht mir nicht an Info ......

**Comment by Tensuko** [comment]
Keine Info, da können wir auch nichts machen...

Closed due to inactivity.
