### ISSUE TITLE
[BUG_SP] ISARIA crop sensor defaults to on after dark with the message "Crop sensor requires daylight!"

### ISSUE THREAD

**Issue by UltraZippy** [Courseplay/Courseplay_FS22#1562]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Run a tractor with ISARIA crop sensor and wait for daylight to end

**Actual behavior**
When daylight ends the sensor displays the message "Crop sensor requires daylight", stopping the tractor manually and turning the sensor off is overridden when courseplay resumes

**Expected behavior**
Abititly to override the crop sensor behavior to off

**Screenshots**

**Courseplay version**
Version used: 7.0.0.21

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Calmsden Farm 1.2.0.0

**Vehicles/ implements involved**
Massey Ferguson 8S.305 / Dalbo PowerRoll 1230 HD (12.3m)
Mod no

with Precision Farming DLC

**Comment by Tensuko** [comment]
> **Courseplay version**
> Version used: 7.0.0.21

I hope you just typed it in wrong

**Comment by UltraZippy** [comment]
7.0.1.15 now, with my head in my hands.  I'm so ashamed of myself maybe it was lack of coffee.

**Comment by Tensuko** [comment]
Anyway, ISARIA handling is not 100% implemented, so maybe later...

**Comment by BattleHook** [comment]
As far as I was informed : This is a bug by Giants and will fixed next update of Precision Farming DLC. (I issued a ticket at Giants Software feedback, and they informed me accordingly).
