### ISSUE TITLE
[Feature] Method to untangle collisions

### ISSUE THREAD

**Issue by billw2012** [Courseplay/Courseplay_FS22#1568]
**What is the problem this feature/enhancement solves?**
Collisions are happening very often, stopping progress. When managing multiple fields this is a particularly frustrating problem, by far the main one related to CoursePlay (really FS AI in general...).

**Describe the solution you'd like**
I considered a few, but the simplest to implement is just to reverse when a collision occurs. I noticed that the AI will deactivate automatically when it notices it is stuck. Instead of deactivate, just reverse a bit, wait for some time (its important its not the same, I suggest rotate through a set of numbers, so two collided vehicles will each wait different amounts of time), then try and continue the route from the last waypoint. Of course if you can't make progress when reversing either then just stop. It would be VERY nice if it could alert us when this happens with a button to switch to that vehicle, like when a course finishes!

**Describe alternatives you've considered**
1. I did consider a more complex solution based on how train signaling works: break the course into sections, add a method to check for vehicles in those the swept area of those sections, stop any vehicle continuing into the next section if there is another vehicle in it. It can also detect overlap between the swept areas of sections in the same course, and consider these sections also, avoiding the case where backtracking and narrower rows cause section overlap (it happens a lot in non-rectangular fields).
2. Disable the collision for implements! I actually like this, but I imagine the knee jerk reaction might be quite negative as its not "realistic". However given how infrequently farmers in real life are colliding with each other compared to in FS22, I think its still the more realistic option, and certainly should be trivial to implement compared to other solutions (you know like ... solving AI) and provide as an option for people who just don't want this headache.

**Additional context**
I often run multiple courses on a single field at the same time (e.g. limer, fertilizer, planter all running at the same time), multi-tool courses, and use AD for doing chase / auger work, so I see a lot of collisions!

**Comment by Tensuko** [comment]
Both solutions are not realy fitting. The 2nd one will for sure not happen.

It is always better to rather discrube what the actual problem is.
When and where do you have colissions?
Driveing more Helper on some course on the same field will ofc lead into problems.

**Comment by billw2012** [comment]
I described 3 solutions, but am only proposing the first one (reversing when you can't go forward any more, and waiting for a bit before trying again).

> When and where do you have colissions?
There is no configuration I can find where having more than one vehicle on a course won't sometimes collide. 

Some examples:

![image](https://user-images.githubusercontent.com/1453936/168856239-f3bcc08d-0e7a-4ed4-9da7-44895f876276.png)
There the green area is particularly prone to collision between a vehicle on the headland and one on the turn, as the turn is elongated. 

![image](https://user-images.githubusercontent.com/1453936/168856680-b3d0f17a-ab67-4c2e-8cfa-338de5e9f68c.png)
The last row is narrower, vehicles will collide with those still on the previous row, due to this.

![image](https://user-images.githubusercontent.com/1453936/168857521-14f8b2a6-9f40-4f81-ac41-e0c1184301e0.png)
Where it joins itself loops to follow around to get to the start of the rows it (and of course on every turn in the middle).

> Both solutions are not realy fitting. The 2nd one will for sure not happen.
I would appreciate an explanation of why not (however brief)?

**Comment by Tensuko** [comment]
Well, just wait until we got the sensor reworked.
Reversing might be an option, but not sure how we will implement that.
I link your suggestion to this:
#1555

But closing here.
Know what you try to solve, but that way won't work so simple.
Also what you do with working one tool after the other on the same field was never meant to work 100% flawless.

**Comment by billw2012** [comment]
> Also what you do with working one tool after the other on the same field was never meant to work 100% flawless.
Sure, although I am talking about multi-tool in my diagrams only, which presumably IS intended to work without colliding? At least eventually (I write a few mods, I know features don't get completed necessarily).
