### ISSUE TITLE
CP Menü analog LS19

### ISSUE THREAD

**Issue by ChrisBS91** [Courseplay/Courseplay_FS22#157]
Hi 
Erstmal mega dank an Euch, das Ihr CP so schnell in den LS 22 gebracht habt. 

Doch die neue Steuerung über das Helfermenü ist manchmal etwas problematisch. 
In der Übersichtskarte kann man die Feldumgebung nicht sehen (Bäume, Zäune, Gräben ect.), daher ist es immer etwas schwiegig den richtigen Feldkurs zu wählen, damit die Maschienen nicht steckenbleiben. 

- Könntet Ihr alternativ (falls es nicht schon geplant ist) das normale CP Menü wieder integrieren? 
  so kann man dann direkt am Feld anhand der Umgebung den Feldkurs anpassen 

Grüße Chris

**Comment by iljarogoff** [comment]
#70
