### ISSUE TITLE
[BUG_SP]Steinesammler übergibt nicht an AD, wenn voll

### ISSUE THREAD

**Issue by WernerWusel** [Courseplay/Courseplay_FS22#1573]
**Steps to reproduce**
Steinsammler arbeiten lassen bis er voll ist.

**Actual behavior**
Steinsammler bleibt stehen und meldet das er voll ist. CP beendet den Betrieb nicht und schaltet den Steinsammler auch nicht aus, klappt auch den Steinsammler nicht ein und übergibt nicht an AD (Autodrive).

**Expected behavior**
CP sollte den Steinsammler wie jedes andere Tool auch behandeln. Beenden, ausschalten, zuklappen und an AD übergeben.

**Screenshots**
Im ersten Screenshot sieht man, dass das Tool steht aber nicht ausgeschaltet ist (Drehzahl).
![20220516133838_1](https://user-images.githubusercontent.com/102391757/169154113-bd0a7788-749c-423f-b60a-cf9ff84e48d9.jpg)

Im zweiten Screenshot ist der Typ des Steinsammlers zu sehen.
![20220516134904_1](https://user-images.githubusercontent.com/102391757/169154149-8118c51c-a475-4870-b282-941347f72b64.jpg)

**Courseplay version**
Version used:  7.0.1.15

**Log**
[log_steinesammler.txt](https://github.com/Courseplay/Courseplay_FS22/files/8720871/log_steinesammler.txt)

**Map**
Huron County Michigan 16x

**Vehicles/ implements involved**
Siehe Screenshot.

**Relevant script mods**
Div. Mods. Ob da relevante Mods dabei sind ?

**Comment by andremeyer123** [comment]
Kann es nicht bestätigen 
![fsScreen_2022_05_19_10_56_43](https://user-images.githubusercontent.com/70706468/169256006-5a35bd45-5211-435b-8d52-799bbbac3006.png)
![fsScreen_2022_05_19_11_00_32](https://user-images.githubusercontent.com/70706468/169256018-7ff60b4a-94fe-420a-9525-b6ec310ecef0.png)

**Comment by andremeyer123** [comment]
geht alles 
![fsScreen_2022_05_19_11_06_35](https://user-images.githubusercontent.com/70706468/169256988-9ed5a2d8-4327-4b10-b60d-3f0bda9c3dc3.png)
![fsScreen_2022_05_19_11_06_55](https://user-images.githubusercontent.com/70706468/169256993-bebb2533-5f35-43ee-aa4c-4b611b8a898e.png)

**Comment by WernerWusel** [comment]
Mag ja sein  dass die Funktion im Multiplayer gegeben ist. Ich spiele im SP und da funktioniert es nicht. Bei mir funktionieren auch Sachen die bei anderen nicht gehen und umgekehrt. So ist das nun mal.

**Comment by Tensuko** [comment]
Wenn es im MP geht, muss es im SP erst recht gehen.

Wurde AD denn richtig konfiguriert ?

**Comment by andremeyer123** [comment]
so sp geht genauso 
![fsScreen_2022_05_19_13_19_13](https://user-images.githubusercontent.com/70706468/169281663-442d0452-58d1-400f-b881-df108afcfe11.png)
![fsScreen_2022_05_19_13_19_30](https://user-images.githubusercontent.com/70706468/169281670-93a83038-f8c6-4d43-943e-fa9a0f622848.png)

**Comment by Axel32019** [comment]
Euch ist schon klar das ihr mit 2 verschiedenen AD-Versionen diskutiert, oder?
Der Stein-Sammler wird erst in der nächsten Version 2006 unterstützt.
Die Tests mit 2006-RC sehen aber schon gut aus :-;

**Comment by andremeyer123** [comment]
Dann haben wir doch recht cp macht alles was es soll Ad kommt ja erst das Update. (Lacht )
Issue bei ad aufmachen warum es nicht geht  !!!!!!
Spass mus sein :)

**Comment by Tensuko** [comment]
@Axel32019 danke für die Klärung, hab den Überblick verlorgen was seitens AD noch fehlt :)

Also kann hier zu!
