### ISSUE TITLE
[Enhancement] Baler should use turn speed, even it is almost full.

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/Courseplay_FS22#1575]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use a round baler. It has to bee nearly full (99%), so its slows down to 4kph and you have to be at the end of the row.

**Actual behavior**
As intended the vehicle slows down to 4kph, but when there is no enouth material left to finish the bale befor turning, it will use this 4kph for the whole turn manover. 

**Expected behavior**
Use the normal speed for turn manovers.

**Screenshots**
![fsScreen_2022_05_14_11_12_45](https://user-images.githubusercontent.com/37582657/169256882-c8616ac0-5ce7-446a-a138-e8844f8ea0a6.png)
![fsScreen_2022_05_19_10_59_32](https://user-images.githubusercontent.com/37582657/169256904-acd14c27-5a27-4e4f-811b-917359ba7fcd.png)

**Courseplay version**
Version used: 7.0.1.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8727658/log.txt)

**Map**
Dosn't matter.

**Vehicles/ implements involved**
Used the Pöttinger Impress 185VC Pro but should work with every round baller.

**Relevant script mods**
AD 2.0.0.5

**Comment by Tritura2** [comment]
I forgot to tell you, that the situation recorded in the log is a fake situation as this event happens really rare.
I filled the round baler up to 99% by myself and then started it on an empty row.

**Comment by Tensuko** [comment]
fixed
