### ISSUE TITLE
[BUG] Error messages not translated

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#158]
**Steps to reproduce**
1. Create a task
2. Place the target position in the field
3. Look at the CP warning message "Generate a course before starting the job!"

**Actual behavior**
This warning seems hard coded and not refering to a L10N translation

**Expected behavior**
Be able to translate error/warning messages in L10N files

**Screenshots**
![2021-12-27_08-16-16](https://user-images.githubusercontent.com/70093234/147446025-ab20eba9-71da-46b3-b37f-47212ae494c3.png)

**Map**
Elmcreek

**Comment by Lactic68** [comment]
Corrected by @schwiti6190 , thank you :)

**Comment by LuanTavares127** [comment]
How can I could help with brazilian portuguese translations?

[translation_br.txt](https://github.com/Courseplay/Courseplay_FS22/files/7782131/translation_br.txt)
