### ISSUE TITLE
Unable to use IT-Runner/Hooklift for fieldwork

### ISSUE THREAD

**Issue by discord5000** [Courseplay/Courseplay_FS22#1581]
**Steps to reproduce**
Install any of the IT-Runner mods, eg https://www.modhub.us/farming-simulator-22-mods/itrunner-pack-v1100
Attempt to use manure spreader or slurry spreader for fieldwork

**Actual behavior**
When attempting to start a fieldwork course, the hooklift container unloads from the truck or trailer. I assume it is trying to "unfold" at the start of fieldwork like it would with standard equipment.

**Expected behavior**
Container stays on the truck/trailer and work commences.

**Courseplay version**
Version used: 7.0.1.15

**Map**
Any. Elerngrat most recently.

**Vehicles/ implements involved**
Which vehicle or implement? ITRunner, possibly swap body mods.
Mod yes/no ? yes

**Comment by Tensuko** [comment]
Mod Issue, also not supporting mods from that page.

**Comment by discord5000** [comment]
So, these mods are in giants modub now, is it possible to get an option to disable unfolding like autodrive has to fix this?
