### ISSUE TITLE
[Question] Course Generator Return to first point or stopping at the end ?

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#159]
Hi,
In the translation files (line 162/163) it seems that the translated text is not corresponding for the actual feature.
In this case : return to first point is translated into stop at the end.

<text name="CP_vehicle_courseGeneratorSetting_returnToFirstPoint_title" 	text="Stop am Endpunkt"/>
<text name="CP_vehicle_courseGeneratorSetting_returnToFirstPoint_tooltip" text="Stop am Endpunkt"/>

**Comment by Tensuko** [comment]
Oops, will have a look.

**Comment by Tensuko** [comment]
It is basically the same, just the Settingname is a bit missleading. The logic is reversed.
We are also not sure if we need that setting also inside the generator...
Will close this for now and it will be fixed somehow. Thanks for report.
