### ISSUE TITLE
[BUG_SP] CP Menu Bug with Patch 1.5

### ISSUE THREAD

**Issue by tomy852** [Courseplay/Courseplay_FS22#1593]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Start Game 

**Actual behavior**
The CP Menu is hidden and not possible to creat or load course  

**Expected behavior**
worked fine before..

**Courseplay version**
Version used: v7.0.1.15

**Log**
attached

**Map**
Standard HauteBeyleron

**Vehicles/ implements involved**
Which vehicle or implement? all
Mod yes/no ? no

**Relevant script mods**
-
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8762519/log.txt)

**Comment by jonesbradford** [comment]
I cant upload logs, but having the same issue. Im on the Huron County map and it includes all vehicles. I cycles through each to be sure.

**Comment by Tensuko** [comment]
@schwiti6190 
2022-05-24 14:12 Error: Running LUA method 'mouseEvent'.
C:/Users/thwu/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CpCourseManagerFrame.lua:443: attempt to index field 'currentVehicle' (a nil value)
2022-05-24 14:12 Error: Running LUA method 'mouseEvent'.
dataS/scripts/gui/base/TabbedMenu.lua(605) : attempt to perform arithmetic on local 'oldIndex' (a nil value)

**Comment by Dylan-M** [comment]
> 

Not for me. For me it bugs out all the time.

**Comment by timmi4026** [comment]
Bei mir ist es verstärkt bei Claas Fahrzeugen, das das Menü weg ist und nur eins zu sehen ist wo sich Schriften überlagern. In Kombination mit Mulcher kann ich manchmal sogar überhaupt nichts machen, z.b. Kurs laden oder speichern.

**Comment by WernerWusel** [comment]
**Bei jedem 2ten Aufruf** des ESC-Menue ist das Speicher-Icon und das Speichermenue von CP richtig.
