### ISSUE TITLE
[BUG_SP]Crash after latest menu fix.

### ISSUE THREAD

**Issue by patch110** [Courseplay/Courseplay_FS22#1597]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Load map then open ingame map by pressing esc. Highlight an autodrive marker then click visit.
With CP deactivated this doesnt happen.

**Actual behavior**
The game crashes and menu changes to 3 choices which i remember happening once before in CP

**Expected behavior**
To be able to visit marker without game crash

**Screenshots**
![fsScreen_2022_05_24_20_20_34](https://user-images.githubusercontent.com/32200890/170117433-77c08e3b-086e-4795-9e6d-36be5f7684bd.png)

**Courseplay version**
Version used:7.0.1.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8765716/log.txt)

**Map**
Green Valley Nebraska 4x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
CP AD and VCA

**Comment by Tensuko** [comment]
Can't reproduce. Works just fine.
Not sure what state you have, wait for 7.0.1.16 to be finished.

Also no Error in log found what could be related.
