### ISSUE TITLE
[BUG_SP] Menu glitch since 1.5

### ISSUE THREAD

**Issue by Nickeling** [Courseplay/Courseplay_FS22#1599]
**translated with Google**
Hello you hard-working modders.

**Steps to reproduce**
I opened the menu with ESC, then I clicked on the helper menu.
As soon as I selected some other menu icon, the icons from the vehicle menu and from the course manager disappeared.
When I clicked on the vehicle menu or the course manager from the helper menu, both menus overlapped (see screenshot).

**Actual behavior**
Menus overlap and cannot be selected again until you exit the menu.
You can only access the vehicle menu and the course manager if you were not previously in the helper menu.
A Lua error occurs (see log).

**Expected behavior**
No Error and no overlaped Menus.

**Screenshots**
![fsScreen_2022_05_25_00_59_09](https://user-images.githubusercontent.com/106202520/170145759-035dd6ee-1bce-424f-a1f8-c28e1e19d66f.png)
![fsScreen_2022_05_25_00_59_12](https://user-images.githubusercontent.com/106202520/170145778-d7082f22-3a7d-4408-b825-7c9310a22c54.png)

**Courseplay version**
Version used: V7.0.1.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8766737/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
every Traktor, not modded

**Relevant script mods**
No other mods where loaded for the Test.

**Comment by WernerWusel** [comment]
#1598
