### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#160]
**Steps to reproduce**
start CP

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Log**

**Map**
Papenburger_Map

**Vehicles/ implements involved**
Mod no 

**Relevant script mods**
Mods like Autodrive or VCA and so on.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7779001/log.txt)

version last 7.0.0.7

**Comment by Lactic68** [comment]
Hi,
May I suggest to edit your title by adding for example "Papenburger_Map" behind the tag [BUG_SP] please ?

Another question,
Have you tried the same map without mod and only Courseplay ?

**Comment by Manyak007** [comment]
hello yes still same how start CP freezes map :( old version work

**Comment by Manyak007** [comment]
error code is appears when use cotton harvest vanila Module express 635

**Comment by pvaiko** [comment]
This looks like you have some old DebugChannelConfig.xml lying around, remove your old CP installation and reinstall from the zip.

**Comment by Manyak007** [comment]
still same i downloand new yip from this page i use anz cotton harvest and same error code

**Comment by Manyak007** [comment]
2021-12-27 16:52 Error: Running LUA method 'update'.
C:/Users/Radek/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1213: attempt to call method 'getCurrentDischargeNode' (a nil value)
