### ISSUE TITLE
je mehr abfahrer auf einem feld angemeldet sind,um so breiter werden die furchen![BUG_MP]

### ISSUE THREAD

**Issue by OpiGunnar** [Courseplay/Courseplay_FS22#1600]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
.Version used: 7.0.1.15

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared. 1

**Dedicated server or local hosted server**
Dedicated server yes/no ? yes

**Map**
Map played on. thüringen_2.0

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? Ventor
![Screenshot_4](https://user-images.githubusercontent.com/92441322/170254757-dc34e18b-e0ab-4ec5-9793-e851047102b4.png)
![Screenshot_5](https://user-images.githubusercontent.com/92441322/170254776-8831cad3-ca0d-4756-825c-a812903ba64b.png)
![Screenshot_6](https://user-images.githubusercontent.com/92441322/170254783-444a625c-c6ce-434f-a299-8236dc30e42f.png)
![Screenshot_7](https://user-images.githubusercontent.com/92441322/170254800-caa066a5-12f7-4991-ab33-e3eeb87addf6.png)
![Screenshot_9](https://user-images.githubusercontent.com/92441322/170254809-e2c14613-52ef-4073-8b10-6a7275cc4682.png)

**Relevant script mods**
Mods like Autodrive or VCA and so on. AD

**Comment by Tritura2** [comment]
Vernünftige Erklärung was dein Problem ist, wäre garantiert hilfreich. So sind hier nur paar Screenshots zu sehen, anhand derer man nur sehen kann, dass alles so funktioniert wie es soll.

**Comment by OpiGunnar** [comment]
es funzt garnix wie es soll,je mehr abfahrer um so breiter werden die ernter spuren im kurs. steht in der überschrift und man kann es in den screenshots sehen
!

**Comment by Tritura2** [comment]
Die Einstellung, die du meliert hast, gibt an wie viele Fahrzeuge auf dem Feld arbeiten. Also z.B. wv Mähdrescher gleichzeitig fahren. Also z.B. 5 Ernter mit 3m Arbeitsbreite ergibt 15m gesamtatbeitsbreite. Wenn du 5 Abfahrer für einen Häcksler nutzen willst, dann musst du AD nutzen und nicht CP.

**Comment by OpiGunnar** [comment]
ok,das is natürlich ne ganz andere perspektive. bin davon ausgegangen das alle fahrzeuge die auf dem feld arbeiten gemeint sind

**Comment by Tritura2** [comment]
Es gibt im Spiel im Bereich Hilfe auch einen Bereich für CP wo viel ausführlich beschrieben steht. Vielleicht hilft das dir weiter bei den Einstellungen für einen Kurs.
Den Bug hier kannst du denke ich mal schließen. :)

**Comment by Tensuko** [comment]
> es funzt garnix wie es soll

Wenn ich sowas schon lese....

Wie die anderen gesagt haben, lies dir doch erst mal die Ingame Hilfe durch.
Dann ist die frage woher du meinst, dass es ein Fehler ist, wenn du dir das ganz offensichtlich noch nicht mal angeguckt hast.
