### ISSUE TITLE
Courseplay thinks vines are an object and blocks it

### ISSUE THREAD

**Issue by TeeSee64** [Courseplay/Courseplay_FS22#1601]
**Steps to reproduce**
harvest olives with courseplay course

**Actual behavior**
harvest impossible, error message: blocked by an object

**Expected behavior**
harvest olives

**Screenshots**

![courseplay bug](https://user-images.githubusercontent.com/17621946/170307671-4c6c5c6c-0a86-4af6-9430-ddfc2c19eee0.jpg)

**Courseplay version**
Version used: latest: 7.0.1.16

**Vehicles/ implements involved**
Which vehicle or implement? braud 9090x
Mod yes/no ? no

**Comment by Tensuko** [comment]
Oops.

**Comment by alexanderweide** [comment]
confirmed. i have the issue myself this needs a hotfix

**Comment by alexanderweide** [comment]
![Bildschirmfoto vom 2022-05-26 11-58-05](https://user-images.githubusercontent.com/7734241/170465565-e67a6caa-6125-4572-aad3-174f1de6105c.png)

**Comment by Tensuko** [comment]
logfile ?

**Comment by Tensuko** [comment]
Sensor jumps to the back of the tool, just as intended.
![fsScreen_2022_05_26_12_34_59](https://user-images.githubusercontent.com/27344744/170471436-d93a0231-3544-4648-ab7e-9cb7945d21ad.png)

**Comment by Roby1164** [comment]
> Sensor jumps to the back of the tool, just as intended. ![fsScreen_2022_05_26_12_34_59](https://user-images.githubusercontent.com/27344744/170471436-d93a0231-3544-4648-ab7e-9cb7945d21ad.png)

I confirm the problem, with the vineyard, I have not tried with other tools, such as plows or other, I will do it as soon as possible. I also tried to recreate the path, but the result is the same, it sees the vineyard as an obstacle, and it stops, I am attaching my log, to check.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8778391/log.txt)

**Comment by alexanderweide** [comment]
> logfile ?

Sorry we where not able to see a log file, since we don't get a log file anymore on dedi server since latest Farming Simulator patch 1.5. So its plain guessing and testing.  we moved back on the server to previous version. We have tested plows as well as giants plows, and cultivators. the interesting thing is that the blocking happens exactly in the second when the tractor tries to turn. i have the gut feeling that the tractor is seeing the cultivators and plows as a obsticle at the attacher..  since the blocking is not happening on driving forward. There is also no object around in the range of 50 meters except some trees. but no cars or any other vehicle.

**Comment by Tensuko** [comment]
But as you see the tool I show you there is driving reverse and the sensor is moved to the back of the tool just as we want it to happen.

**Comment by alexanderweide** [comment]
> But as you see the tool I show you there is driving reverse and the sensor is moved to the back of the tool just as we want it to happen.

the tractor should not move backwards in my case since we have 8 headlands and jumping over the next field line

**Comment by alexanderweide** [comment]
ah one important thing to notice - the error occurs with and without AI headland turning.

**Comment by Tensuko** [comment]
Then why it should see the plow as an object ?
The Sensor is active the whole line, it wouldn't move at all if that would be the case.
Same for drive forward.
If you are sure he can drive forward, do you have set it to turn on field off to try it out ?



> ah one important thing to notice - the error occurs with and without AI headland turning.

AI turn have no effect on towed implements.

**Comment by alexanderweide** [comment]
> 

We always use turn on the field. Since we cannot turn outside of the field, we have realistic maps with curved fields and alot of trees around the fields..

**Comment by Tensuko** [comment]
So then how are your sure the driver wants to drive forward now?
If it wants to drive forward, he could not be blocked by the attached tool, as the back sensor only is active when drive backwards.

If it is the problem of the front looking tool, it should be blocked the whole time.

**Comment by alexanderweide** [comment]
I have no doubt its the:

"proximity sensor refactored to prevent being slow down by far enough objects and now also turns in the turning direction of the vehicle. This should help with situations like in https://github.com/Courseplay/Courseplay_FS22/issues/1555 and https://github.com/Courseplay/Courseplay_FS22/issues/1320"

**Comment by alexanderweide** [comment]
> So then how are your sure the driver wants to drive forward now? If it wants to drive forward, he could not be blocked by the attached tool, as the back sensor only is active when drive backwards.
> 
> If it is the problem of the front looking tool, it should be blocked the whole time.

good question. i see no reason to drive backwards since courseplay not did it one time before since it dont has to drive backwards. it only needs to turn to the second or third next field lane.

**Comment by Tensuko** [comment]
So it got nothing to do with the towed implements, like you assumed.
I would try to remove the weight at the front and test that.

**Comment by alexanderweide** [comment]
> So it got nothing to do with the towed implements, like you assumed. I would try to remove the weight at the front and test that.

we have tested to remove the weight as well as the frontloader arm. which dosent resovled the situation at all.

**Comment by Tensuko** [comment]
Then only a logfile can help here.
What tractor is it ?

**Comment by alexanderweide** [comment]
as i say again: The tractor moved perfectly in the lane, then stopps as usual. then it starting to turn in the next lane and got blocked 1 second after turning the wheels. 

it happens with the John Deere R6 as well as the John Deere R8 as well as the Class Xerion sattle track. we dont have used other vehicles so far.

**Comment by Tensuko** [comment]
If you can't create an logfile on the sever, download the save and start it in SP with debug active for that vehicle and post the logfile.
Anything else is just guessing.

**Comment by alexanderweide** [comment]
> If you can't create an logfile on the sever, download the save and start it in SP with debug active for that vehicle and post the logfile. Anything else is just guessing.

ok good point i will test this

**Comment by alexanderweide** [comment]
I have loaded our current savegame to the non dedi multiplayer game and tested again with all of our mods and it has happend again. 

I have cleaned my computer specs as well as the computer main path and directory. 

[log (Kopie).txt](https://github.com/Courseplay/Courseplay_FS22/files/8778662/log.Kopie.txt)

![Bildschirmfoto vom 2022-05-26 13-39-40](https://user-images.githubusercontent.com/7734241/170481186-097aff2d-860f-412a-be54-392d01704f8c.png)

**Comment by alexanderweide** [comment]
Our main settings
![Bildschirmfoto vom 2022-05-26 13-43-26](https://user-images.githubusercontent.com/7734241/170481485-e2d4d012-9e11-4056-8fd2-c967a47c53ba.png)

**Comment by Tensuko** [comment]
And where is the active debug in the logfile ?

**Comment by alexanderweide** [comment]
> And where is the active debug in the logfile ?

what active debug? The log is allready spammed full with courseplay stuff?

**Comment by Tensuko** [comment]
This....
![fsScreen_2022_05_26_13_53_21](https://user-images.githubusercontent.com/27344744/170483031-982a5a7d-3c70-4cdd-89a8-75ef7c80b5c8.png)

And not the debug won't get deactivated, only for ModHub Version. The reason is axactly this that we have at least some debug in the log when someone comes up with an Issue.

**Comment by alexanderweide** [comment]
ok i will try again.  with activated vehicle debug 

- thats not the issue here but pls turn the insane logging in courseplay off when it is not activated somewhere also for the non modhub version. Nobody cares shit about modhub anymore since they take "years" to upload and give permission on mods. We allready waiting for mods since over 5 month. And sadly 50% of the mods on mudhub still buggi as hell, best example is the vicon shit from gigants.

**Comment by alexanderweide** [comment]
so here it is
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8778773/log.txt)
![Bildschirmfoto vom 2022-05-26 14-02-21](https://user-images.githubusercontent.com/7734241/170484329-d078d530-dd3b-4b2b-ab71-a7f82cd451be.png)
![Bildschirmfoto vom 2022-05-26 14-02-32](https://user-images.githubusercontent.com/7734241/170484341-0cef833d-bbc7-43d9-a9ab-98352f3b60a9.png)

**Comment by Tensuko** [comment]
> * thats not the issue here but pls turn the insane logging in courseplay off when it is not activated somewhere also for the non modhub version. Nobody cares shit about modhub anymore since they take "years" to upload and give permission on mods. We allready waiting for mods since over 5 month. And sadly 50% of the mods on mudhub still buggi as hell, best example is the vicon shit from gigants.

Wont happen

**Comment by Tensuko** [comment]
Found no Problem.

![fsScreen_2022_05_26_15_06_37](https://user-images.githubusercontent.com/27344744/170493736-afc2cb24-9b4c-4b0a-9bb5-66479ad03d4e.png)

![fsScreen_2022_05_26_15_06_19](https://user-images.githubusercontent.com/27344744/170493721-b1dcbcfa-63bb-40a4-ad4c-fd2ed2c712aa.png)

**Comment by alexanderweide** [comment]
can you please test a reasonable lane jump of 1 or two? you seem to always test a non lane jump which is not used by many farmers especially not on complex fields.

**Comment by Tensuko** [comment]
And now ?
Seems like no Issue.
![fsScreen_2022_05_26_15_19_47](https://user-images.githubusercontent.com/27344744/170495780-db240a44-0286-4c6d-b434-46b5c95582b5.png)

**Comment by Tensuko** [comment]
And again no Issue.
![fsScreen_2022_05_26_15_22_09](https://user-images.githubusercontent.com/27344744/170496200-8f0f9f82-337a-42ae-8514-fbc6d64b46c7.png)

**Comment by alexanderweide** [comment]
then it must be the trees around the field.. the tractor should not be allowed to drive over the field border when it is not allowed... 

alternativly it can also be that the fields not flat like in your examples... collision with the surface?

**Comment by Tensuko** [comment]
The Trees on your pictures are way to far away, to stop the tractor, the object have to be 1.5m away from the sensor origin.
Field with slope:
![fsScreen_2022_05_26_15_39_57](https://user-images.githubusercontent.com/27344744/170499419-9e0c4dfd-9cca-47fb-8f9a-3a64ea72954f.png)

A bit less power for the tractor to pull the tool up
![fsScreen_2022_05_26_15_40_32](https://user-images.githubusercontent.com/27344744/170499518-fa9895c7-d64c-424c-8b3e-8789ae255178.png)

A nice generated Pathfinder turn to stay on field as much as possible (reverse not allowed for towed implements with pathfinder, limited by turn radius)
![fsScreen_2022_05_26_15_40_48](https://user-images.githubusercontent.com/27344744/170499601-58658695-7e1c-4bf9-bb5a-3d6a9e102896.png)

Sensor is all good and does not look into the ground.
![fsScreen_2022_05_26_15_40_54](https://user-images.githubusercontent.com/27344744/170499731-c8bff8e7-6b8d-4323-803c-c88c85b75f58.png)

**Comment by alexanderweide** [comment]
do you test only in single player?i am wondering if the issue is not happening in singleplayer.. i need to test this more on the dedi server. So far i had no issues in single player with the new version.. might be a dedi server issue.who knows.

**Comment by alexanderweide** [comment]
One question in the expert mode settings there are these two degree angle values? could it have been this? We have changed the values since Courseplay had finding correct path errors in the past version? what are the defaults?

**Comment by alexanderweide** [comment]
Resolved for me::!!!! Thank you for your support and help pointing to a reason.

The reason is we have added addional collision triggers in front of all of our machines in order for better Autodrive collision prevention. Those triggers are recognized as a obsticle as you see in the screenshot. 

![Bildschirmfoto vom 2022-05-26 16-05-19](https://user-images.githubusercontent.com/7734241/170504268-fa4e690b-69d7-4dce-beee-7cbf0b5e5ae5.png)


![Bildschirmfoto vom 2022-05-26 16-05-19](https://user-images.githubusercontent.com/7734241/170503936-f086f320-3aaf-4ac4-a229-b50af3b9f215.png)

**Comment by TeeSee64** [comment]
> @TeeSee64 Isse will be fixed in next release soon.
> 
> @alexanderweide Well... If you have problems with ad collision, talk to them. If you mod your vehicles expect issues as we stick to giants standart and modhub.
> 
> Closing.

Thanks!
