### ISSUE TITLE
[Feature] Erlaube manuelle "Rohr ausfahren" während CP aktiv

### ISSUE THREAD

**Issue by Laudern** [Courseplay/Courseplay_FS22#1603]
**What is the problem this feature/enhancement solves?**
Oft passiert es mir bei der Feldarbeit das ich in einem bestimmten Moment gerne manuell das Rohr ausfähren würden. Z.B. wenn der Drescher in eine lange gerade einbiegt und desshalb gerade gut vom Abfahrer (via AD) abgeladen werden kann; oder ich das Rohr gerne einfahren würde, weil der Drescher kurz vor der Wende in die nächste Bahn steht und ich nicht möchte das der Abfahrer (AD) sich jetzt noch annähert.

**Describe the solution you'd like**
Erlaube das manuelle "Rohr aus- oder einfahren" während CP aktiv ist. (Standardmässig mit einem druck auf die Taste "O".)

**Describe alternatives you've considered**
Keine. Wenn nicht, dann eben nicht.

**Additional context**
–

**Comment by Tensuko** [comment]
Das muss über AD dann angepasst werden.
Das Manuell zu erlauben wäre auch ein ein griff in den normalen Helfer.
