### ISSUE TITLE
Ballen transportieren

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1605]
Hallo
Ich wollte Ballen fahren, es werden aber als Beispiel Rundballen als Quaderballen erkannt. Wo dran liegt das ? Oder muss ich mich an Autodrive wenden 
![Rundballen](https://user-images.githubusercontent.com/47453761/170352842-d9ef4c4a-9f6b-48c2-89ae-7261c913c02b.png)

**Comment by Tensuko** [comment]
Ich wüsste nicht, dass es was mit AD oder CP zu tun haben soll.
Sieht mir eher nach einem Bug vom Trailer aus.
Bitte erst mal die anderen Mods anschauen.
