### ISSUE TITLE
[BUG_SP] Case Module Express 635 fährt nach Entladen nicht weiter

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1606]
**Steps to reproduce**
Kurs mit CP generiert, nach dem Entladen eines Ballens bleibt der Case manchmal einfach stehen. Entlässt man dann den CP Fahrer und stellt ihn direkt wieder ein, geht es normal weiter. Passiert aber irgendwie nicht jedes Mal (von ca 10 Ballen ist es 2x passiert), keine Ahnung warum. 

**Expected behavior**
Nach Entladen automatisch weiter fahren.

**Screenshots**
![fsScreen_2022_05_25_17_50_47](https://user-images.githubusercontent.com/96873819/170307103-fdc50c07-6dc6-478a-8a44-f5a467a8cb48.jpg)

**Courseplay version**
Version used: 7.0.1.15

**Log**
[log - Kopie (2).txt](https://github.com/Courseplay/Courseplay_FS22/files/8772853/log.-.Kopie.2.txt)
Anmerkung: Kurs für 2 Fahrzeuge. War immer der linke Fahrer. 

**Map**
NF mit Gräben

**Vehicles/ implements involved**
Vanilla Case Module Express 635

**Relevant script mods**
CP, AD

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.0.1.16

**Comment by throsten** [comment]
Fehler tritt auch mit 7.0.1.16 auf. Wieder der linke Abfahrer.
![fsScreen_2022_05_26_08_18_26b](https://user-images.githubusercontent.com/96873819/170429631-782b476e-6cc1-4901-aa07-a2b3d8a0789b.jpg)


Log: 
[log - Kopie.txt](https://github.com/Courseplay/Courseplay_FS22/files/8776739/log.-.Kopie.txt)

**Comment by throsten** [comment]
Laut Hinweis im Textfeld wird der Case "blockiert".

**Comment by throsten** [comment]
Hab mal den Ballen hinter dem Case weggenommen, währen CP noch aktiv (blockiert) war. Der Ernter will eine Tasche fahren, weshalb er beim Rückwärts-fahren auch "blockiert" ist.

**Comment by Tensuko** [comment]
Schalte mal die Fruchtumfahrung aus.
