### ISSUE TITLE
[BUG_MP] Rocker switching issue when hopper is full from Courseplay to AutoDrive

### ISSUE THREAD

**Issue by Goldenfenix3000** [Courseplay/Courseplay_FS22#1608]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
After filling the rocker's hopper, it stops with stones and does not switch to AutoDrive. After a manual shift, it moves on AutoDrive to the unloading point. After, it returns back to the point where it stopped, and continues cleaning. Grass, hay, straw, according to this scheme, removes without manual switching
**Expected behavior**
After filling the rocker's hopper with stones, it should switch to AutoDrive automatically and move on AutoDrive to the unloading point.
**Screenshots**
![20220526083851_1](https://user-images.githubusercontent.com/106008105/170460131-9b3998c5-7b89-4dcc-9f27-c469ff59c644.jpg)

**Courseplay version**
Version used: 
7.0.1.16
**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared.
1
**Dedicated server or local hosted server**
Dedicated server yes/no ?
yes
**Map**
Map played on.
NF March 4x
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
yes
**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive 2,0,0,5

**Comment by Tensuko** [comment]
Becouse it needs an AutoDrive Update. Need to wait for it.
