### ISSUE TITLE
constant warning message about plant sensors in precission farming at night 

### ISSUE THREAD

**Issue by alexanderweide** [Courseplay/Courseplay_FS22#1609]
hey, 

i constantly get a warning that i need sunlight with the onboard precission farming sensors aka plant sensors.

Courseplay always keep it on, even on plows and other tools such as lime spreaders. 
![Bildschirmfoto vom 2022-05-26 14-02-32](https://user-images.githubusercontent.com/7734241/170485057-4a5ccfa8-408c-4702-a505-7c545f96861e.png)

**Comment by Tensuko** [comment]
Not a CP bug, Giants Helper got the same problem so its Giants Issue.
