### ISSUE TITLE
[Feature] Resume work at last WP

### ISSUE THREAD

**Issue by Manto82** [Courseplay/Courseplay_FS22#161]
Maybe I still didnt find that function or is it really not implemented.

A feature that lets the machine continue the work at the last WP they stopped would be very helpful.
For example, when working with precision seed drills.
The filling quantity is relatively low, especially with the small machines, so that you have to drive manually to refill more often.
The same applies to liming.

**Comment by Tensuko** [comment]
When your tool just stands on that position, just press H.
