### ISSUE TITLE
[BUG_SP]  grapevines blocks Braud 9070L with Proximitysensor

### ISSUE THREAD

**Issue by MRKS97** [Courseplay/Courseplay_FS22#1613]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Start a course with Braud 9070L

**Actual behavior**
with the latest courseplay version 7.0.1.16 the proximitysensor detects the vine as an obstacle

**Expected behavior**
normal harvesting with the Braud

**Screenshots**
![20220526181509_1](https://user-images.githubusercontent.com/70518703/170533556-1f13417c-b9c0-400f-ac05-01b986fb0b6f.jpg)
![20220526182052_2](https://user-images.githubusercontent.com/70518703/170533566-10b1c7be-e678-439b-9be8-8838252284f0.jpg)

**Courseplay version**
Version used: 7.0.1.16

**Log**
https://gist.github.com/MRKS97/9104d7b2cb03cf04685e16a55af93ac5

**Map**
NF March 

**Vehicles/ implements involved**
Braud 9070L

**Comment by Tensuko** [comment]
#1601

**Comment by Tensuko** [comment]
Or in other words, fixed with next Release...
