### ISSUE TITLE
[Question] Quaderballenpresse wartet am ende einer Reihe seit CP v7.0.1.16

### ISSUE THREAD

**Issue by jufcar** [Courseplay/Courseplay_FS22#1615]
Mit CP v7.0.1.15 gabs es den Bug, dass seit v1.5 die Einstellung im Menü meist nicht auswählbar war, daher hab ich die .16 geladen und das läuft seitdem wieder rund, danke dafür.
Jetzt hab ich mir auch eine Quaderballenpresse als Ersatz zu einer Presswickelkombi gekauft und wollte diese auf dem alten gespeicherten Kurs laufen lassen, da das Gras noch mit dem selben alten Kurs gemäht wurde.

Problem:
die Presse wartet am Ende der meisten Reihen. Ich geh davon aus, dass dies daher rührt, dass ihr das nette Feature eingebaut habt, das die Press-Wickelkombi am Ende warten lässt.

Jetzt meine Frage:
Ist das ein Bug? Muss ich einen neuen Kurs erstellen? Oder kann ich das irgendwie für meine Quaderballenpresse deaktivieren?

**Comment by Tensuko** [comment]
Bei mir hat die Quaderballenpresse nicht gewartet.
Bitte reproduzieren mit aktivierten debug und das logfile anhängen.

**Comment by Tensuko** [comment]
Closed due to inactivity
