### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by tomblackdog** [Courseplay/Courseplay_FS22#1616]
Hallo CP-Team,

seit dem Release 7.0.1.16 funktioniert die Rebenbearbeitung nicht mehr richtig. Es betrifft aktuell das Grubbern und liegt meiner Meinung nach an der neuen Kollisionserkennung. Die Fahrzeuge fahren sehr langsam durch die Rebe und bleiben häufig stehen, da angeblich eine Kollision voraus ist. Ich habe es mit 2 Traktoren geprüft und immer das selbe Ergebnis. Es ist unabhängig vom angehangenen Gerät und Fahrzeug. Bisher habe ich mit dem NewHolland T6 175 problemlos gearbeitet. Getestet habe ich noch zusätzlich den Fendt 200V mit selben Ergebnis, er erkennt Kollision und fährt mit max. 5 Km/h  bzw. bleibt stehen.
Ich werde noch die Ernter und Schneider testen und bei Problemen RM geben.
Solltet Sie noch mehr Infos benötigen dann bitte melden.

LG Tom

**Comment by Tensuko** [comment]
Kein Template benutzt, keine Suche....
#1613

**Comment by tomblackdog** [comment]
Hallo Tensuko,

wird also mit 1.01.17 gefixt? Sorry, wie finde ich diese geschlossen Einträge, meine Suche hatte nichts ergeben.
Danke für die schnelle Antwort.

LG Tom

Von: Tensuko ***@***.***>
Gesendet: Freitag, 27. Mai 2022 15:45
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: tomblackdog ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] [BUG_SP] (Issue #1616)


Kein Template benutzt, keine Suche....
#1613<https://github.com/Courseplay/Courseplay_FS22/issues/1613>

**Comment by Tensuko** [comment]
Ja wird es.
