### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by TheOgTSM** [Courseplay/Courseplay_FS22#1618]
**Steps to reproduce**
I get it when generating a route with all the equipment types.

**Actual behavior**
The lines in the generated route are parallel, but not spaced out evenly which leaves bare stripes in the fields. There's a pattern of 2 lines close together followed by a bigger gap and 2 more lines close together. There is unworked land in the space where the lines are further appart. 

On the screenshot I'm using up/down with no headlands  but the bug occurs on all the different generation types.

**Expected behavior**
The lines should be evenly spaced out leaving no ground unworked.

**Screenshots**
https://imgur.com/a/kU4URmA

**Courseplay version**
Version used: v7.0.1.16, although I had this issue last time I tried using courseplay which was around february.

**Log**
https://pastebin.com/pCTSSgJJ

**Map**
Riverview Farm

**Vehicles/ implements involved**
all vehicles and equipent that I have tested (plows, cultivators, lime spreaders and weeders)
no modded vehicles or tools

**Relevant script mods**
none

**Comment by Tensuko** [comment]
Why do you only look on the lanes ?

Thats a graphical overview.
When you have REAL unworked areas, you can reopen this Issue and we can check, but only from look at the lanes, thats nothing.
