### ISSUE TITLE
Eigene Kurse?

### ISSUE THREAD

**Issue by MST050706** [Courseplay/Courseplay_FS22#1619]
Nochmal an die CP Profis hier,

wenn ich nen Kurs aufzeichne beim Schwaden und dann am Ende diesen über das kleine Menü beende dann wird das nur als Feldrandkurs genommen. Kann ich diesen irgendwie so speichern das der Häcksler den Abfahren kann?

**Comment by Tritura2** [comment]
Die Funktion gibt es nicht mehr und wird auch nicht wieder eingeführt soweit ich weiß. Kurserstellung erfolgt nur noch über die Generierung im Feldbereich.

**Comment by MST050706** [comment]
Mhh das ist sehr schade. Nagut

**Comment by haamic** [comment]
@MST050706 
Schau mal hier... #1429
Kann ich dir wandeln

**Comment by MST050706** [comment]
@haamic Könntest du auch erklären wie du den Kurs umwandelst. Ich habe die Wiesen bereits schon bearbeitet und könnte daher erst Kurse zum nächsten Schwaden einfahren welches aber noch ein Stückchen hin ist.

**Comment by haamic** [comment]
@MST050706 
schau dir mal einen Feldkurs und einen aufgenommenen in einem Texteditor an zb notepad++ da kommt man dann selber drauf, was geändert werden muss

**Comment by MST050706** [comment]
@haamic Joo. Ich schaue morgen mal aber wenn nicht kommen ich nochmal auf dich zurück fals ich es nicht hinkriege.
