### ISSUE TITLE
[Feature] Kurse rückwärts?

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1620]
**What is the problem this feature/enhancement solves?**
Seit dem Ballen als Hindernis gesehen werden und der Fahrer davor anhält, funktioniert meine Grasbearbeitung nicht mehr (alleine). Ich lasse den Mäher (z.B. Krone Selbstfahrer mit Schwadablage) auf dem Vorgewende starten, damit er nicht beim Wenden der Bahnen auf ungemähtem Gras fährt. Ein Traktor mit Silage-Ballenpresse auf dem gleichen Kurs bleibt jetzt an Ballen des Vorgewendes stehen, wenn er Bahnen fährt. Der Kurs läuft nicht mehr ohne Eingriffe durch. 

Einen identischen Kurs im Generator zu erzeugen, bei dem Vorgewende und Bahnen vertauscht sind, ist sehr schwierig und passt nie überall richtig.

**Describe the solution you'd like**
Funktion um einen vorhandenen Kurs rückwärts abzufahren bzw. einen neuen Rückwärts-Kurs aus einem vorhandenen Kurs zu generieren.

**Additional context**
Falls es über den Generator läuft, wäre auch eine weitere Funktion cool: Aus einem Kurs mit 2 Fahrzeugen einen neuen Kurs mit nur einem Fahrzeug und doppelter Breite zu erzeugen (z.B. Einseitiger Band-Schwader mit nachfolgender Presse, klappt nur am Vorgewende nicht richtig)

**Comment by 60erjonny** [comment]
Nun, ich versuche "gewisse Probleme" mit den Einstellungen: 
Vorgewende Richtung --> #im Uhrzeigersinn, #gegen den Uhrzeigersinn, 
Starte auf --> # Bahnen, # Vorgewende,... beim Kursgenerieren zu lösen...
Und man kann in den Fahrzeugen einen horizontalen Geräteversatz einstellen...
Probiere hier einfach mal aus...

**Comment by Tensuko** [comment]
Die Ballen werden mit absicht als Hinterniss gesehen, damit man nicht drauf oder drüber fährt.
Starten auf Bahnen mit Schwaderkurs damit die Presse den gleichen Kurs nimmt und erst mal nur auf den Bahnen presst, somit sind keine Ballen im Vorgewende.

**Comment by throsten** [comment]
Das Ballen als nun Hindernis gesehen werden, finde ich gut und soll auch so bleiben. Sinnvolle Verbesserung für Schwaderkurse. Hab nirgends geschrieben, dass das weg soll. 
Aber was ist mit den Mähwerken, die direkt eine Schwad legen? Soll man da jetzt auch erst mit einem Schwaderkurs "die Schwad verschieben" um dann für die Presse einen vernünftigen Kurs zu haben? Für Silageballen braucht es da keinen Schwader-Prozess.

Ich habe versucht einen Vorschlag zu machen bzw. die Diskussion anzuregen. Ist aber anscheinend nicht gewünscht.

**Comment by 60erjonny** [comment]
Stell die Ballenpresse mit den Mähkurs erst auf den ersten Punkt der Bahnen ab und starte mit der Einstellung "nahester Wegpunkt" und arbeite diese ab, mach später dann des Vorgewende...so mach ich es immer...ist zwar nicht automatisiert, aber es ist doch immer noch ein Spiel im Bereich des möglichen...
