### ISSUE TITLE
[Enhancement] (Raupen) Fahrzeug fährt in Schlangenlinie zum ersten Wegpunkt

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#1622]
**Steps to reproduce**
Raupentraktor wie Fendt MT1100, beliebigen Kurs generieren und auf größere Distanz zum ersten Wegpunkt fahren lassen. Alternativ mit AD zum Feldrand und dann Kurs starten lassen. Geschwindigkeiten stehen auf Standard-Einstellung. Gerade Strecken in Feldkursen (auch beim Wenden mit großer Entfernung) werden sauber gefahren. 

**Actual behavior**
Traktor fährt auf geraden Strecken in Schlangenlinie mit sehr niedriger Geschwindigkeit und bremst immer wieder ab. 
Anmerkung: Kurven mit dem Pathfinder funktionieren besser. 

**Expected behavior**
Normale Geschwindigkeit, grade Linie. Wie andere Rad-Traktoren oder die Knick-Lenker auch. 

**Courseplay version**
Version used: 7.0.1.16

**Screenshots**
![fsScreen_2022_05_21_15_56_23b](https://user-images.githubusercontent.com/96873819/170814194-d002bb6b-d383-461e-a68b-251f1a104064.jpeg)
![fsScreen_2022_05_28_09_00_54b](https://user-images.githubusercontent.com/96873819/170814502-0c76672a-6b9e-4c6e-91a5-8507bfbb66b4.jpeg)

**Log**
[log - Kopie.txt](https://github.com/Courseplay/Courseplay_FS22/files/8790652/log.-.Kopie.txt)

**Vehicles/ implements involved**
Fendt MT1100

**Relevant script mods**
AD

Bin mir nicht sicher, ob das ebenfalls ein Bug ist. Hängt an einem Raupentraktor ein langes Anbaugerät mit großem Wendekreis, z.B. ein Güllefass und man fährt mit CP ein Vorgewende auf einem rechteckigen Feld, bleibt das Gespann in den Ecken stehen. Der Traktor steht dann im rechten Winkel zum Fass und kommt nicht voran. CP bricht dann irgendwann ab.  Mit CP6 konnte man noch den Kurvenradius festlegen, das finde ich in CP7 aber nicht mehr. Fehler von CP oder sitzt er vor dem Bildschirm?

**Comment by Tensuko** [comment]
Mit debug an hätte der Screenshot und auch das logfile mehr Infos.

**Comment by throsten** [comment]
![fsScreen_2022_05_28_10_40_14b](https://user-images.githubusercontent.com/96873819/170817983-a5c3d7e4-1ee4-42ee-9cfc-5380a2e8e9bf.jpeg)
Bis zum ersten Knick beschleunigt der Traktor normal, danach nur Schlangenlinien bis zur Kurve vor dem Kursanfang. Log mit Debug aktiviert:
[log - Kopie (2).txt](https://github.com/Courseplay/Courseplay_FS22/files/8790788/log.-.Kopie.2.txt)

**Comment by Tensuko** [comment]
Ja wir versuchen immer den entsprechenden Punkt zu treffen.
Weis nicht ob wir für Raupen eine höhere look ahead distance nutzen können trotz niedriger geschwindigkeit.

Oder @pvaiko hat eine bessere Idee das Fahrverhalten zu verbessern.

Ist trotzdem kein bug, eher enhancement.

**Comment by pvaiko** [comment]
> Ja wir versuchen immer den entsprechenden Punkt zu treffen.

Nein. Pure Pursuit Controller versucht nicht die Wegpunkte zu treffen, er steuert einen Punkt an, der sich im Lookahead Distance vor dem Fahrzeug entlang des Kurses bewegt.

**Comment by Tensuko** [comment]
Mit der neuesten Version noch mal ausprobiert und keine Probleme festgestellt.
Könnte durch einen anderen fix mit verbessert worden sein.

Sollte das Problem bei dir weiterhin bestehen, bitte wieder auf machen.
Sollte das Problem sonst irgendwann erneut auftreten, einfach ein neues Issue aufmachen.
