### ISSUE TITLE
[BUG_SP] The worker crashes into the fence

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#163]
Hi. Reading the topics quickly, I didn't notice this problem. I don't keep in-depth records because I thought it worked well.
I set it sharp instead of smooth so that it worked the ground better without having to fix the corners. The worker gets stuck against the fence and should stop first without crashing. I am attaching the course.
If you want the full log, just tell me.
[MapUS_Field46_EHLOStone.zip](https://github.com/Courseplay/Courseplay_FS22/files/7779573/MapUS_Field46_EHLOStone.zip)
![fsScreen_2021_12_27_10_35_13](https://user-images.githubusercontent.com/96330304/147459016-7002b2f0-4baf-4a6a-86cd-719f10363118.png)

**Comment by rohne83** [comment]
That's not a bug, that's just how it works. It will always try to finish the lane before turning, but the fence is too near for this. What should help in your situation is working the headlands counter-clockwise (not sure though whether counter-clock courses can be created already or this feature will just come back with a future release).

**Comment by pvaiko** [comment]
As @rohne83 said, and counterclockwise should work now. Also, consider using the round corner options, that will not leave anything out.

**Comment by Markus33-ITA** [comment]
I thought it was a bug. thanks for the explanation. I will try to better evaluate the creation of the course to avoid this type of problem
