### ISSUE TITLE
[BUG_SP] machine track in the field

### ISSUE THREAD

**Issue by MilanPali** [Courseplay/Courseplay_FS22#1632]
Hi, I hope this topic doesn't appear again. I don't know if there is a problem with the map or with Courseplay LS22. I stand by the field, generate a route in the field. I have an island in the field with a forest. Courseplay generates a route in the field .... across the island.
In Farming Simulator 2019, the courseplay automatically went around the electric pole, island, lake. We make a map, so whether there is a mistake with us or in the MOD. Thank you for the info, best regards Milan.

--> Otherwise great praise for courseplay ls22. in addition, the little problem works 100% and I'm glad to be able to use Courseplay and Autodrive again. Keep up the great work.

**Comment by Tensuko** [comment]
And why did you completly remove our template and not fill it in ?
Island bypass is active on default, how should I know what went wrong now without a logfile and screenshots ?

**Comment by MilanPali** [comment]
Because I didn't want to translate the form.
Please delete the thread. I'll solve it again, add a logo, photo, etc. When it's time. Thanks.
