### ISSUE TITLE
[BUG_SP] Proximity Sensor sees itself when turn is to narrow

### ISSUE THREAD

**Issue by GTA3Fan** [Courseplay/Courseplay_FS22#1636]
**Steps to reproduce**
Not sure, it seems to be doing it randomally

**Actual behavior**
At random times at the beginning/end of a row or headland, CP claims an object is in the way. 

**Expected behavior**
CP gets to beginning/end of row or headland and continues to next heading.

**Screenshots**
![20220529124110_1](https://user-images.githubusercontent.com/106483338/170887444-6c21af13-7684-4a5e-ab76-64485905d2b9.jpg)
![20220529145854_1](https://user-images.githubusercontent.com/106483338/170887462-0d9ebf3f-1ec1-4a8e-bd4e-9768eafe7748.jpg)
![20220529124645_1](https://user-images.githubusercontent.com/106483338/170887464-dd332678-0708-4db4-8165-46fed526ce3a.jpg)
https://user-images.githubusercontent.com/106483338/170887577-12c51353-4ba3-41fe-8a40-ed3d3df1f6a5.mp4

**Courseplay version**
7.0.1.16

**Log**
https://gist.github.com/GTA3Fan/f0eec0289e33b6e8bd92b2c1086855e6#file-gistfile1-txt

**Map**
Elm Creek Default

**Vehicles/ implements involved**
943 MT
BigPack 1290 HDP + Lizard R90 (mod)

**Relevant script mods**
None that I can think of.

**Comment by Tensuko** [comment]
Blocked by the bale, not itself, also duplicate Issue
