### ISSUE TITLE
CP speichert Fensterpositionen nicht [BUG_MP]

### ISSUE THREAD

**Issue by Yakuza112v2** [Courseplay/Courseplay_FS22#1638]
Version used: 7.0.1.16
CP speichert Fensterpositionen nicht.
Es wäre sehr schön wenn Fenster die verschoben wurden, auch nach dem erneuten Starten des Spiels an der Stelle bleiben würden wo man sie vorher hingeschoben hat.
Da ich AD und noch andere Skripte nutze muss ich die Fenster von CP immer wieder verschieben, da diese nach einem Neustart andere HUD Fenster überlappen.

Mfg
Yakuza112

**Comment by Tensuko** [comment]
#1258

Im SP einmal einstellen und speichern, ist ein MP Problem, könnte bald behoben werden.
