### ISSUE TITLE
CP arbeitet nicht bis zum Ende [BUG_MP]

### ISSUE THREAD

**Issue by Yakuza112v2** [Courseplay/Courseplay_FS22#1639]
**Steps to reproduce**
* Zum Feld fahren
* Saat wählen
* Feld generieren (Anheben spät, Senken früh)
* Starten

CP fährt an den Endpunkt, dieser ist aber zu weit vorne und es bleibt immer ein Stück frei.
Screenshot ist im Anhang.

Version used: 7.0.1.16
Dedicated server: Ja
Map: NF Marsch OG
Mod: MF 7719S + Lemken Solitair 12

**Comment by Yakuza112v2** [comment]
![cp](https://user-images.githubusercontent.com/103038143/171011028-a81bff9b-67cc-4bb6-a711-9d0d6d7032d6.png)

**Comment by Yakuza112v2** [comment]
Geht das auch in freundlich? Vergiss es ich fixe es mir selber!

**Comment by Tensuko** [comment]
Wir haben extra ein Tempalte gemacht mit Infos die wir brauchen...
Ich muss immer wieder nach dem gleichen kram Fragen und das hier war eine einfache Frage.....
