### ISSUE TITLE
Unload Harvesters

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/Courseplay_FS22#164]
I cannot get the unload feature to work.
I know you will tell me the watch Video have done that over and over again. But all the options in autodrive do not match with what you tell us.

I am missing some steps.

I cannot allocate the harvester to the tractor to get autodrive the see it. I have set recorded a course from Field to silo and back. Park tractor in field assign course to autodrive. Then set courseplay to generate course for havesting still no Work.

**Comment by EiksYt** [comment]
The tractor and the combine must have the same course in Autodrive. Look at the picture .
![autoodrive](https://user-images.githubusercontent.com/96645189/147467650-ef52d390-0ca8-4827-acba-bc9a305dc1d5.jpg)

**Comment by Tensuko** [comment]
There is no unload feature yet, that is more a it kinda works when the combine unfold the pipe, AD will come.
How AD dies it, pls look at the AD GitHub and Discord.
