### ISSUE TITLE
[Feature] Silage bunker worker

### ISSUE THREAD

**Issue by lordbanastor** [Courseplay/Courseplay_FS22#1644]
I haven't found this request/question anywhere, so, if I missed it somewhere, please excuse me and point me in the right direction. 

Would you consider creating/implementing this feature in future versions? I liked this a lot back in FS19, because one could left the worker doing this and the silo was filled perfectly, but manually its a mess. 

**What is the problem this feature/enhancement solves?**
Working into compacting silage in bunkers.

**Describe the solution you'd like**
A similar feature as in FS19, where the worker would compact silage inside the bunkers automaticaly.

**Describe alternatives you've considered**
Manual work, so far.

**Additional context**
No additional context.

**Comment by Tensuko** [comment]
Will come later, was answered under discussion already.
