### ISSUE TITLE
[BUG_SP] Ballenwickler Error

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1647]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Ballenwickler auf Feld Starten

**Actual behavior**
Ich möchte Ballen wickeln lassen. Sobald ich CP starte bekomme ich ein Error und cp macht dann nix mehr.

*Courseplay version**
Version used: 7.0.1.17

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8804019/log.txt)

**Map**
NDS

**Vehicles/ implements involved**
Which vehicle or implement?
Orginal Wickler

**Relevant script mods**
Autodrive

In der Cp Version davor ging es noch wunderbar. (Möchte aber nicht ausschließen das auch was anderes den Error verursacht 

)

**Comment by Tensuko** [comment]
BaleCounter wirft Errors.
Aber ja da ist auch einen von uns bei:
2022-05-31 11:45 Error: Running LUA method 'update'.
C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFindBales.lua:340: attempt to get length of local 'objectsToIgnore' (a nil value)
