### ISSUE TITLE
Ausbleibender Ruf vom Drescher nach Abfahrer am letzten Feldarbeitspunkt

### ISSUE THREAD

**Issue by XPiRiJenZ** [Courseplay/Courseplay_FS22#165]
V: 7.0.0.7
Map: Haut-Beyleron
Mods: AD 2.0.0.2
Drescher: Standard Deutz Topliner 4090 mit Standard Schneidwerk

Grüße zusammen!
Am letzten Punkt der Feldarbeit wird der Drescher nicht nochmal mit Hilfe AD-Abfahrer abgebunkert, da dieser nicht gerufen wird.
Vllt könnt ihr das ja wieder mit implementieren :)

**Comment by EiksYt** [comment]
> V: 7.0.0.7 Map: Haut-Beyleron Mods: AD 2.0.0.2 Drescher: Standard Deutz Topliner 4090 mit Standard Schneidwerk
> 
> Grüße zusammen! Am letzten Punkt der Feldarbeit wird der Drescher nicht nochmal mit Hilfe AD-Abfahrer abgebunkert, da dieser nicht gerufen wird. Vllt könnt ihr das ja wieder mit implementieren :)

Hi ,

ja , dass ist mir auch gerade aufgefallen !  Danke für die Top Arbeit !!!!

**Comment by Tensuko** [comment]
Das Rufen ist aktuell nur zufällig durch das 'open pipe'.
Eine echte Schnittstelle zu AD kommt noch.

**Comment by pvaiko** [comment]
https://github.com/Courseplay/Courseplay_FS22/commit/177cb8911c6aaeab61db8c28d3ca669418b6e12c implemented the interface, now waiting for AD to do their part. There's nothing to be done in CP for now.
