### ISSUE TITLE
[BUG_SP] sowing contract

### ISSUE THREAD

**Issue by Zaazik** [Courseplay/Courseplay_FS22#1650]
**Steps to reproduce**
Jus buy sowing tool with fritilithing and try make contrat without fritelizer

**Expected behavior**
Whe you try make sowing contract on field with sowting tool, with fritelizer curse stop and say, tool need refiel

**Screenshots**

**Courseplay version**
Version used: latest totda 

**Map**
elmcreek

**Vehicles/ implements involved**
any sowing tool with fritilizing

**Relevant script mods**
Autodrive and VCA active

**Comment by rohne83** [comment]
in CP vehicle settings, there's a setting for fertilizer function of sowing machines. You just have to deactivate this, then it works without problems.

**Comment by Tensuko** [comment]
Exactly, thanks Rohne :)
