### ISSUE TITLE
CP v7.0.1.17 Will not work with any of the self-propelled sprayers

### ISSUE THREAD

**Issue by frankrexdale** [Courseplay/Courseplay_FS22#1651]
This is on any map and just for self-propelled sprayers with CP v7.0.1.17.

If you have a saved game with a self-propelled spray. Game will not fully load. It gets stuck on trying to determine auto width. 

If you load new game and then try to buy new self-propelled spray. It will give errors and not load vehicle.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

"Always update to the latest build and check if the problem really still exists before reporting issues."

->

https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.0.1.18

And use the Template!!
