### ISSUE TITLE
Proximity sensor vs. Large equipment

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#1652]
Hello guys,

since version 1.16 and new proximity sensor (I guess) I'm experiencing tractor stops with larger tool. CP driver will stop with message that he is blocked by object but only thing there is his own tool. It happens with turn 90deg or more no matter if it is headland or changing rows in the middle. Seeders I was using are 23m and more wide but I guess same issue will be with any tool with higher widths.  Added screenshot with Seedhawk, but I experinced same thing with Bourgault seeders too. As you can see he still have lots of space available for turn to make it with no problems. In all cases I used vanilla  articulated tractors NH T9, Case Quadtrack.  I had no issue like that before 1.16 version.  

![20220530105603_1](https://user-images.githubusercontent.com/33344465/171215746-05726b76-0e95-45c2-b48a-baac920c46f2.jpg)

![20220526114056_1](https://user-images.githubusercontent.com/33344465/171215901-6887a2a0-e546-4bba-b3cf-d3ac4d8f6158.jpg)

**Courseplay version**
Version used: 1.1.1.16

**Map**
Nebraska

Mods : 
https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=240761&title=fs2022
https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=240761&title=fs2022

**Comment by Tritura2** [comment]
I assure you, that they want and need a log file with debug activated. ;)

**Comment by Tensuko** [comment]
Since the other Issue disappeared.... reopen....

**Comment by Tensuko** [comment]
Maybe it just needs a higher turn radius.
I tried this one and had no Issue so far:
![fsScreen_2022_06_01_11_17_31](https://user-images.githubusercontent.com/27344744/171371316-4b0bbe6d-dab6-4953-8acd-75715053b19a.png)

**Comment by pvaiko** [comment]
Try with an articulated tractor.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Also could not reproduce the Problem with same or similar tractors + several big seeders.

**Comment by GungingXD** [comment]
Hello, i have the same Problem here, and no clue what to do to fix it.
I tried different tractors and other big seeders. As soon as the seeder/hoe itself sits behind the tractor, it gets blocked in turns greater than like 90°. Is there any setting, that i could have wrong? In Videos on Youtube, there are plenty of Big Buds and Seed Hawks working fine with Courseplay.

The John Deere 9420R is the Vanilla one. The Seeder and Tank are: 
https://farmingsimulator22mods.com/john-deere-1870-air-hoe-drill-v1-0-fs22/ 
https://farmingsimulator22mods.com/john-deere-c850-air-cart-v1-0-fs22/

![Screenshot 2022-08-16 204342](https://user-images.githubusercontent.com/111386048/184955166-0f19344a-354d-41bb-9506-38a64078356d.png)

**Comment by Tensuko** [comment]
Mod Issue, old collission, bad convert.
Stick to the seed hawk fr giants.

**Comment by GungingXD** [comment]
Even with the giants Seed hawk other tractors like the vanilla t9 or modded Big Bud, i gets blocked.
![Screenshot 2022-08-17 181042](https://user-images.githubusercontent.com/111386048/185189679-21bfd6c9-b397-484b-9618-cd21305f4fd1.png)
![Screenshot 2022-08-17 182032](https://user-images.githubusercontent.com/111386048/185191662-fd390875-92c1-4f43-8cee-26ee43c2963c.png)

**Comment by GungingXD** [comment]
Even with the giants Seed hawk other tractors like the vanilla t9 or modded Big Bud, i gets blocked.
![Screenshot 2022-08-17 181042](https://user-images.githubusercontent.com/111386048/185189679-21bfd6c9-b397-484b-9618-cd21305f4fd1.png)
![Screenshot 2022-08-17 182032](https://user-images.githubusercontent.com/111386048/185191662-fd390875-92c1-4f43-8cee-26ee43c2963c.png)

**Comment by Misamangame** [comment]
Seed Hawk is also bad, just use Bourgault equipment. I just use those and Terminator now, all works fine

**Comment by GungingXD** [comment]
That's a bit dissapointing. The last time i played everything worked fine and now half of my equipment is useless. Is there nothing i could change or edit?

**Comment by Tensuko** [comment]
Tested giants seed hawk and it worked fine

**Comment by Tensuko** [comment]
Might be to tight turn radius with the t9

**Comment by Misamangame** [comment]
Is there one from Giants? One I had from some other sites was broken so I delete it. Did not found Giants one on Modhub thought

**Comment by GungingXD** [comment]
So i tested it again with Version 7.0.1.15 and the turns work fine. As soon as i go above Version 7.0.1.16, the issue comes back. Maybe it has omething to do with this Change: _"proximity sensor refactored to prevent being slow down by far enough objects and now also turns in the turning direction of the vehicle. This should help with situations like in https://github.com/Courseplay/Courseplay_FS22/issues/1555 and https://github.com/Courseplay/Courseplay_FS22/issues/1320"_

I dont know why this problem does not occur in your game. I startet a new Savegame and just activated Courseplay and the Seed Hawk mods.
