### ISSUE TITLE
Reben Kurs (Oliven) erstellen

### ISSUE THREAD

**Issue by FarmerMario** [Courseplay/Courseplay_FS22#1653]
Hallo,
Ich möchte mal fragen,wie ein Kurs eines Olivenfeldes erstellt wird.
Das Feld mit den Reben ist bereits vorhanden.
Wie wird das nun genau gemacht.
So wie ich das mache werden im Kursgenerator maximal 2 Rebenreihen erstellt bzw. erkannt.
Was mache ich falsch?
Kann mir jemand erklären, wie das gemacht wird.
Wenn's geht, Schritt für Schritt.

mfg Farmer Mario

**Comment by FarmerMario** [comment]
Tritura2,
Vielen Dank,für Deine schnelle Antwort.
Ich weiß,wie CP funktioniert.Im Normalfall wird mit dem setzen der Feldposition auch der ganze Feldrand erkannt und angezeigt.
Bei mir wird wie o.g. nur max. 2 Reben erkannt bzw. als Rand angezeigt und nicht das ganze Rebenfeld.
Muß mann eine bestimmte Stelle anklicken.

mfg FarmerMario

**Comment by Tritura2** [comment]
Die Reben sind auf einem bereits bestehenden Feld?
Könntest auch versuchen einen eigenen Feldrand zu Zeichen und schauen, ob es dann besser klappt.

**Comment by Tensuko** [comment]
Das braucht kein Feldrand.
Voraussetzung ist die Reben im korrekten Raster vom LS zu platzieren.

**Comment by Tensuko** [comment]
Schein geklärt zu sein.
