### ISSUE TITLE
[BUG_SP] Drawbar attachment seems to throw off headland corners

### ISSUE THREAD

**Issue by GTA3Fan** [Courseplay/Courseplay_FS22#1654]
**Steps to reproduce**
Seems to be any tractor that the "Trailer Attacher Support" mod and on a "Sharp" Headland
Equip attachment, attach implement, create a headland course. Tractor gets to end and raises implement as to turn but never turns, just goes straight off field.

**Actual behavior**
Tractor gets to end and raises implement as to turn but never turns, just goes straight off field.

**Expected behavior**
Tractor is supposed to turn corner.

**Screenshots**
![20220531141027_1](https://user-images.githubusercontent.com/106483338/171265795-7dcfb8f0-1e79-47b9-a0ed-184b14ff72f6.jpg)

https://user-images.githubusercontent.com/106483338/171267064-20c94fc3-d178-424f-b340-34abd58da4de.mp4
https://user-images.githubusercontent.com/106483338/171267512-7c7dd42f-0851-46aa-ba37-d0a08f6e8a8c.mp4

**Courseplay version**
Version used: 7.0.1.16

**Log**
(https://gist.github.com/GTA3Fan/82307f9185c2e1ecbeac3081b1b5f437)

**Map**
ElmCreek Default

**Vehicles/ implements involved**
Default:
Case IH Steiger Quadtrac 620 
Dablo Mega Roll 2430
Fendt 943 MT

Mods:
Trailer Attacher Support https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=233485
YP-2425A https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=226891&title=fs2022

**Relevant script mods**
N/A

**Comment by pvaiko** [comment]
The reverser AI can't handle this drawbar as the implement is not attached directly to the tractor, we have a check in there for attacher modules (ImplementUtil.isAttacherModule()) but that works only for attacher joints of type semitrailer.

Wondering if that check is necessary, or we can just ignore everything between the the implement and the tractor if it does not have wheels.

**Comment by Tensuko** [comment]
I just checked if this Issue is still valid.
Tested the seeder with both attacher + used the drawbar together with the seeder.
Tried it with NH T8 and the MT 943, both was scuccessful.
Seems like any fix in between solved it.
![fsScreen_2022_07_18_18_13_50](https://user-images.githubusercontent.com/27344744/179555652-8946700b-be48-462f-8769-5a69fc1aae3c.png)
