### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#1655]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
I first started on this map using version v7.0.1.4, and updated to v7.0.1.14, and had no issues util I went to the newer versions (15 - 18).
1. Trying to create any course on a Custom create field, now combines the filed I'm on and the custom field next to it.
2. I can create a new custom field now by manually driving its edge using record, but when I create a course, the field edges are off, by anywhere from a full implement width to half of its width.
4.  Since the Field Margin and control of direction was removed, I've had nothing but issues. I have standard fields, that I can no longer chose the course of directions, it doesn't matter if I used target, and place the direction target, I want a west-to-east course, but CP creates north and south tracks. I really can't understand why field margins and direction control were removed from newer versions; in my case it seems like a step backwards.

**Actual behavior**
A clear and concise description of what happen.
I have several custom created fields, it doesn't matter if the field's boarder was created by rt-click draw, or if I used the record on the HUD, and manually drive around the field edge. 
The problem is with the newer versions of CP, when I try to create a new course on a custom field, its combining the custom field next to it, even though there's a headland of 20' - 40'. So instead of get a course for the field I'm on, it combines and creates a course as if the two fields are one.
I deleted CP-4 and CP-7 from the modSettings folder, and then deleted every course I had made to those two custom fields, and its like some CP file is hidden somewhere, it just keeps remember the old boarders, and keeps combining custom fields. I have too many hours on this map to start over from scratch. Are there files I need to delete from some other folder or than Documents\My Games\FarmingSimulator2022\modSettings?

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 
Started with v7.0.1.4, and progressed through v7.0.1.18

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Pacific NW Farming v1.0.0.2

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Any vehicle or implement, and I'm running mods

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD v2.0.0.5
![FarmingSimulator2022Game_2022_05_31_15_31_10_976](https://user-images.githubusercontent.com/45585444/171293963-1cbc3b69-1c42-4644-8876-b28c2eac3bc9.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8809827/log.txt)

**Comment by HC1Gunner** [comment]
Also, moving to newer versions of CP, when running courses on a custom field (meadows) my vehicle completes it pass, reaching the end of the row (every pass) it stops, and will not turn to start it next pass, the vehicles just stops with CP still being engaged. If I go back to version 7.0.1.4, they problem is not there.

**Comment by Tensuko** [comment]
I have no clue at all what your Problem is....

The only thing from your Screenshot is you selected a field and not the custom one.
There is a global option to select either the custom field or the original field.

Thats my only guess....

**Comment by schwiti6190** [comment]
@HC1Gunner 
Hi there, the settings you mentioned: "Field Margin and control of direction" are available with the expert mode turned on.
And as mentioned above the global setting "prefer custom fields", prioritizes the custom or normal field borders.
Additional you could draw the borders on the in game map to avoid the inwards borders. 
The manual driving records the center postition of the vehicle and not the outer position (left or right), as thats not reliable possible.
I would suggest you check out the in game menu cp help pages, as you might find helpful informations there :)

**Comment by Tensuko** [comment]
Closed due to inactivity.
Not sure what the actual problem is but I am sure the answer is in the ingame help menu.

**Comment by HC1Gunner** [comment]
Those are both custom fields that it wants to join.
The problem on my end comes from changes that were made to newer versions.
Now if you vehicle is sitting on or near a field, when you open the games
main menu, and select to Create a Job, the very second you change the
option in the upper right from FieldWork to CP:  Field Work, CP instantly
puts a border around the field, it never used to do this. You had to use
one of the menu Target options, and manually click on the field.
In my case, my custom fields are large headlands that are not part of the
field they are next to, and they can be purchased separately. In this case
they are grass, so now the later version of CP sees both of the healands as
connected because they are all grass, even though the PDA shows them as
separate fields. With the later versions of CP, now if I create a custom
field by right-click and draw, or if I use the HUD to manually record, CP
pays no attention to the border you just created for the new field, and
when you open the menu going from fieldwork to CP fieldwork, just just
overrides the border you created manually. YOu can see it right in my
screenshot by the blue border that I created, and the white border that CP
overrode with.
I solved the first issue by opening the in-game editor, and painting a
different grass or texture to separate the two open areas on the map that
are purchased separately.

You didn't address my other problems where I use the Select Target
Position, place it on the field in the direction I want to create the
course, but CP pays no attention and creates the course 90 degrees off, I
placed it point east, but I widing up with a course going north/south.

Custom fields that were created with v7.0.1.4 no longer work with v7.0.1.15
or higher, when the vehicle reaches the end of the field, it barely starts
to turn, then just stops, and will not proceed to the next row.

**Comment by Tensuko** [comment]
On general settings is an option to toggle betwwen original and custom border.
