### ISSUE TITLE
Wiki not found

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#166]
Is it only me who is incapable to open wiki.

On [Code]-Page is written down "For more details on how to post a proper bug report, visit our Wiki"... But every time i hit the link in this text or when i click on the [Wiki]-Page manually it routes me back to the [Code]-Page...

**Comment by Lactic68** [comment]
For now, you can probably use the original Wiki : 
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Will copy it over later

**Comment by Keppchen** [comment]
Thank you two
