### ISSUE TITLE
Updated to the latest version 18 and now all my tires & tracks are missing on all equipment.  Can't Play 

### ISSUE THREAD

**Issue by Randal375** [Courseplay/Courseplay_FS22#1661]
Updated to the latest version 18 and now all my tires & tracks are missing on all equipment.  Can't Play.  Didn't change anything else - as soon as I removed 18 by deselecting it all the vehicles returned to normal.  I just hope I can go back to 17 and have it work otherwise the game is bricked.  I'm grateful for your product, but this is a huge issue and makes the game unplayable. 

I tried a few of my other courses and they were all the same thing - no tires on anything.  I tried the clear the shadercache and that didn't do anything.  Please help.

**Comment by Randal375** [comment]
Just a note that I rolled back to 16 and now it is working perfectly.

**Comment by Randal375** [comment]
Just a quick note that this is affected by version 17 & 18.

**Comment by Tritura2** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Tensuko** [comment]
When you download from any Crap Website, no wonder your game us fked up:
Available mod: (Hash: 8f051bccd6fa6db18ff5d91af435c129) (Version: 7.0.1.16) FS22_Courseplay
Available mod: (Hash: da5748380ca9cc12eb69d2b530d83001) (Version: 7.0.1.16) FS22_Courseplay_7_0_1_16

And other Mods show Errors too.

And I do NOT see any 7.0.1.18 Version of Courseplay so my guess is again, mod stealing shit website that tells you its the .18 while its the .16

This is the only correct download location untill we got on modhub and no where else!
-> https://github.com/Courseplay/Courseplay_FS22/releases
