### ISSUE TITLE
[BUG_MP] Linien  der  reben und streucher

### ISSUE THREAD

**Issue by Revan1161** [Courseplay/Courseplay_FS22#1665]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Beim greiren der kurse bei oliven und  trauben  endsteht das ( siehe Screenshots) und geht nicht weg 

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://www.dropbox.com/sh/zr4k6qqc2jr2z9t/AAD4L3sk-keiB5vCQRfN9Gqna?dl=0)

**Courseplay version**
Version used: 7.0.1.8

**Client Log**
Keine log fehler 

**Server Log**
Keine Log fehler

**Player on the server**
Number of players on the server, as the bug appeared.

**Dedicated server or local hosted server**
Dedicated server yes/no ?

**Map**
Haut_Beyleron

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Das ist debug und verschwindet bald...
