### ISSUE TITLE
When using multi tool with 5 machines they fail to move off the headland

### ISSUE THREAD

**Issue by schwyl** [Courseplay/Courseplay_FS22#1669]
What happens is when the machine complete the headland I believe they're too far away from seeing the next waypoint to continue on.

Im running the latest version of courseplay.
![tractors stop](https://user-images.githubusercontent.com/2615447/171896417-2bd8f994-3ba0-40c1-b3f0-11e194ab030c.jpg)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8833456/log.txt)

**Comment by Tensuko** [comment]
At least our safety check worked and they didn't run away :)

**Comment by Tensuko** [comment]
Hmm not sure.
They should be on their own turn, but I am sure I had turns longer then 50m already.... I think....

**Comment by schwyl** [comment]
Anything else I can provide to help out with this?

**Comment by pvaiko** [comment]
I'm a little confused here, those implements have a working width of what, like 3m? Why are these tractors standing about 50 meters apart? Is that worked area the headland? Why is the headland so wide?

**Comment by schwyl** [comment]
They have a working width of 50m which is the max that courseplay can handle. I reverted back 5 releases ago prior to the implementation of that safety check and everything performs as expected. It would be nice if that option was user selectable based on the course versus being on the whole time

**Comment by Tensuko** [comment]
So in conclusion those are self modded to unrealistic 50m ?

**Comment by schwyl** [comment]
Now it does with with anything over 25M modded or not. Like I said i reverted back a few revs and it works fine

**Comment by Tensuko** [comment]
Since those are self moded with unrealistic values, will not do anything here, sry.
