### ISSUE TITLE
[Feature] eigener Feldrandkurs

### ISSUE THREAD

**Issue by Manto82** [Courseplay/Courseplay_FS22#167]
Wenn ich mich recht erinnere gab es im CP für FS19 die Möglichkeit durch abfahren eines Kurses einen eigenen Feldrand zu definieren.
Wäre schick wenn es das auch im aktuellen CP wieder geben würde.

**Comment by rohne83** [comment]
vermute mal das ganze Thema wird auch schon mit #45 behandelt

**Comment by Tensuko** [comment]
Richtig
