### ISSUE TITLE
[BUG_SP] Mower not following the course properly and not generating a course properly

### ISSUE THREAD

**Issue by larry78901** [Courseplay/Courseplay_FS22#1671]
**Steps to reproduce**
Go to F71 on the Elmcreek map with the mower and JCB Fastrac 4220

**Actual behavior**
I generate a course, the working width adjustment is incorrect. I select 10m and it is completely wrong. I set the machine to drive the course, it drives at an offset angle to the course markers aswell.

**Expected behavior**
The machine should drive the course without issue

**Courseplay version**
Version used: 7.0.1.18

**Log**
https://gist.github.com/larry78901/9728fad18077c5b39191421f911daa56

**Map**
Elmcreek
Default map

**Vehicles/ implements involved**
JCB Fastrac 4220
Pottinger 301 AM ED PRO
Pottinger A10 Crossflow
No mods

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Screenshot of the Problem ?

**Comment by larry78901** [comment]
https://i.imgur.com/aoNnRyc.jpeg

**Comment by Tensuko** [comment]
You are working on a multitool course.
Not sure what you did there...

**Comment by Tensuko** [comment]
Read our ingame manual.

**Comment by Tensuko** [comment]
Well, this is wrong usage. The Ingame Menu provides some helpful information to this.
Not a bug or anything.
