### ISSUE TITLE
[BUG_SP]SugarBeet harvester doesn't reverse far enough when starting next row.

### ISSUE THREAD

**Issue by GTA3Fan** [Courseplay/Courseplay_FS22#1672]
**Steps to reproduce**
3 Headlands, Clockwise, Sharp, Up/Down, Skip 1 row, allow drive on fruit, allow turn anywhere

**Actual behavior**
Harvester does its turn (sloppily) but doesn't back up far enough and begins next row while also still turning INTO row.

**Expected behavior**
Possibly a better better turn/pull forward more into row before backing. Backing far enough to get beginning of row.

**Settings**
![20220603165945_1](https://user-images.githubusercontent.com/106483338/171952526-55e3a513-6bea-48c9-82c4-6a6bd10484d3.jpg)
![20220603165948_1](https://user-images.githubusercontent.com/106483338/171952530-4519b667-257e-4a78-b985-6ab98da435db.jpg)
![20220603165956_1](https://user-images.githubusercontent.com/106483338/171952532-bb8f2caa-1d87-4dee-a404-ae6236e56d6c.jpg)
![20220603170004_1](https://user-images.githubusercontent.com/106483338/171952537-a4a631cb-c203-4c88-8817-0b3f10d1f61b.jpg)

**Screenshots**
![20220603164336_1](https://user-images.githubusercontent.com/106483338/171950808-87bc531d-d57f-4fd5-88a2-cd34705a9beb.jpg)
![20220603164352_1](https://user-images.githubusercontent.com/106483338/171950818-51ef575d-3abd-443e-bb02-cda4ab838ef1.jpg)
![20220603164357_1](https://user-images.githubusercontent.com/106483338/171950822-3a664592-b97e-4172-b79a-d38605fd28b2.jpg)

**Courseplay version**
Version used: 7.0.1.18

**Client Log**
https://gist.github.com/GTA3Fan/81aeb75595562bd54d36e0ff3faa4909

**Map**
ElmCreek Default: Enlarged field 52

**Vehicles/ implements involved**
Mods:
Holmer Exxact Terra Dos T4-40 (https://www.fs22modhub.com/holmer-sugarbeet-pack-v1-1-0-1/)
Holmer Exxact HR 12 (Header)

**Relevant script mods**
None

NOTES:
I'm hoping is all related to the above, but is there a way to get it to harvest in a more straight line lol
![20220603160827_1](https://user-images.githubusercontent.com/106483338/171953762-4caa1aab-be46-42d7-bf93-4f9dc82de217.jpg)
t

**Comment by Tensuko** [comment]
Beside the fact that you should not download mods on a mod stealing website.
Its basically a duplicate:
#1549
