### ISSUE TITLE
[BUG_SP]Feldränder unbrauchbar

### ISSUE THREAD

**Issue by tobiasw83** [Courseplay/Courseplay_FS22#1673]
HI,

seit kurzem sind meine ganzen Feldränder verändert.

Sie führen nicht mehr gerade am Feld entlang sind zig schleifen um Bäume etc.

Wie dadurch entstehenden Pfade für die Maschine sind unbrauchbar. 

Habe CP bereits auf die aktuellste Version geupdatet, und alle Mods die ich vor kurzem installiert hab wieder deaktiviert ohne Erfolg.

Wie kann ich die Ränder wiederherstellen oder das Problem beseitigen??

Danke
Tobias
![feldränder](https://user-images.githubusercontent.com/30494066/171957281-5dfc9ce7-138e-4a39-aa06-c98c43853ca2.jpg)

**Comment by Tensuko** [comment]
Screenshot vom Feldrand und logfile.
Behaupte das ist ein Mapproblem.

**Comment by ct177mak** [comment]
ich tippe mal auf NF Marsch 1.9.1 sicher mit altem Save game umgezogen ;) nur eine Vermutung

**Comment by tobiasw83** [comment]
> ich tippe mal auf NF Marsch 1.9.1 sicher mit altem Save game umgezogen ;) nur eine Vermutung

Wie meinst Du das mit umgezogen??

Mein mods Ordner ist nicht umgezogen bzw. Das ganze Spiel.
Tobias

**Comment by Tritura2** [comment]
Er meint, dass du wahrscheinlich die neue Version von der Karte (1.9.1) runtergeladen hast und im Anschluss dein altes Savegame weiterhin genutzt hast und das nun zu Problemen führt.
Versuch es mal mit einem neuem Savegame.

**Comment by tobiasw83** [comment]
Meine Map ist vom 14.2.

**Comment by Tensuko** [comment]
Neues Savegame, CP 7.0.1.19 -> Wie sehen die Feldränder aus ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
