### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by COWMAN892** [Courseplay/Courseplay_FS22#1674]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
not usre if just the set up i had. 2wd7r with modded rake baler. run course

**Actual behavior**
when reaching the end of a windrow of dry hay(not sure of other windrow fruits) driver would start to make a turn but would stop half way as it would be blocked by an object. none in sight

**Expected behavior**
make the turn without stopping

**Screenshots**

**Courseplay version**
Version used: 7.0.1.16

**Log**
hope i did it right

**Map**
Map played on. elmcreek

**Vehicles/ implements involved**
both mods
John Deere 7310R 2wd with duels
Krone BigPack 1290 hdp+ lizardr90

**Relevant script mods**
ive have gps mod but dont have it on that tractor

**Comment by fuggo2** [comment]
I have this too, I play NF Marsch and I just encountered the error. A baler is advancing on the course, when it reaches the bend then a message arrives blocking an object, but there is nothing around it except at the end of the baler which has not yet fallen to the ground. I attach an image with debugging

![fsScreen_2022_06_04_20_04_54](https://user-images.githubusercontent.com/66201069/172020189-d8e9b0d3-905a-4906-937a-07d72dd20841.png)
![fsScreen_2022_06_04_20_05_17](https://user-images.githubusercontent.com/66201069/172020192-6f037ffc-0dfe-4475-8f84-9fdcfbf318d3.png)

**Comment by Tensuko** [comment]
@fuggo2 its the bale. I hard believe anyone in real life would use the baler like that.


@COWMAN892 

Old Version:

> **Courseplay version**
> Version used: 7.0.1.16

No log attached:

> **Log**
> hope i did it right

**Comment by Tensuko** [comment]
Closed due to inactivity.
