### ISSUE TITLE
[Feature] Cotton Harvester

### ISSUE THREAD

**Issue by dansiegel1109** [Courseplay/Courseplay_FS22#168]
**What is the problem this feature/enhancement solves?**
Request to add Cotton Harvesting to CP

**Describe the solution you'd like**
As Giants AI doesn't support Harvesting Cotton in any way, I would like CP to do so.

**Describe alternatives you've considered**
I do need to try out AutoDrive Harvesting, however I know it was more for carting and transport, which I do myself.  

**Additional context**
Hope should be not difficult to implement, maybe simply enable and try it.  Only 2 Harvesters to test.  They are VERY manueverable so low likely hood of course and pathfinding issues for them.  The two harvesters do support different types of drops, probably using the nonStopBaling parameter.  The Case must stop, like a traditional round baler.  The JD can drop on the go, or keep the bale while making another to allow you to drop it off on headlands, like the Vicon Fast Baler, which I am certain uses the nonStopBaling parameter.

**Comment by pvaiko** [comment]
Have you tried it?

**Comment by dansiegel1109** [comment]
In CP, no I have not - I had to uninstall because I have very strange issues with working width in the Guidance Steering mod, which turns out to be a single header.  I thought CP or AD might have been the culprit as those are the only things I've really installed lately, but it didn't help (In fact I haven't harvested my corn and sunflowers since 1.1.0.0, so Giants may be the problem).  I've yet to re-install - I will try, and declare myself an idiot if you guys already support it - I figured it wasn't because Giants AI doesn't support it and its not a major crop, so I guessed that you didn't.

**Comment by ph1go** [comment]
The (John Deere) cotton harvester works fine for me with CP in that it follows a course and drops the round bales when it needs to.

**Comment by dansiegel1109** [comment]
thank you.  I'm and idiot.  I'll reinstall CP and try my Case next game month.  Was nervous because I have a decent amount of cotton and other crops to harvest, and going into November with a mostly rainy forecast.  This will be awesome.

**Comment by Manyak007** [comment]
i test CASE harvest cotton and John deere and problem is here 
![image](https://user-images.githubusercontent.com/96631209/147587828-f280db27-b575-4e8a-bbae-9d174bedeca7.png)

harvest wait on unloand ,Both harvest is vanilla on cotton  test with mod and withous mod and same problem
