### ISSUE TITLE
Simple breadcrumb course.

### ISSUE THREAD

**Issue by dezza69** [Courseplay/Courseplay_FS22#1681]
I pressed enter and the ticket was opened. Sorry - I'd not finished typing...

Anyway...

Issue:
I'm trying to create a simple breadcrumb trail (on the big open paddock behind the animal dealer on Elm Creek) - where I record a track/course in one vehicle which is NOT IN/ON A FIELD, save it and then am able to load it into the same and/or another vehicle which is then able to follow the same path.

Every time I finish recording the path/track, I'm only able to save it as a field. If this option is not chosen the course is lost.

What I'd expect to see:
I'd expect to be able to record a simple track of my own driving, save it and have access to it from another vehicle, and not have to use the course generator and/or make a new field.

Courseplay Version - latest ... x.19, and x.18, etc.

My apologies for being unsavvy enough to probably really not understanding something, like perhaps that "mode" hasn't been implemented yet.

Great work and thank you very much for your Courseplay.

**Comment by dezza69** [comment]
I pressed enter and the ticket was opened.  Sorry - I'd not finished typing...

Anyway...

Issue:
I'm trying to create a simple breadcrumb trail (on the big open paddock behind the animal dealer on Elm Creek) - where I record a track/course in one vehicle which is NOT IN/ON A FIELD, save it and then am able to load it into the same and/or another vehicle which is then able to follow the same path.

Every time I finish recording the path/track, I'm only able to save it as a field. If this option is not chosen the course is lost.

What I'd expect to see:
I'd expect to be able to record a simple track of my own driving, save it and have access to it from another vehicle, and not have to use the course generator and/or make a new field.

Courseplay Version - latest ... x.19, and x.18, etc.


My apologies for being stupid enough to press enter before finishing typing on the github and probably really not understanding something, like perhaps that "mode" hasn't been implemented yet.

Great work and thank you very much for you Courseplay.

**Comment by Tritura2** [comment]
There will be no course recording like this. The recording is just for creating a custom field and not for following this trail.
You can use Autodrive for your requested feature as both mods work together and hand over to one another.

https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.0.6

**Comment by Tensuko** [comment]
Correct.

**Comment by dezza69** [comment]
Thanks for your response(s).  Pretty sure I've done this in previous version(s) of Courseplay as I found it was a fantastic feature and quite useful for mowing then easily collecting grass not on designated fields, and it was something I've been hanging out for with the new version. Ta for the suggestion of Autodrive, but it doesn't seem to be able to do what I'm after.

Oh well.

Regards.

**Comment by dezza69** [comment]
Thank you for your reply.  That's not how I use your software.  For the purpose of what I'm achieving (and for an example) - I do not want to use the course generator as there is a lake and trees on the plot and it's a rather odd shape.  I've done it in previous versions and found - with my playing style - it to be the only feature I used in Courseplay.

I want the vehicle to follow a continuous path and make turns at a speed I've set.  I'm so sure I've done this with Courseplay in both FS17 and FS19, that I'm going to re-install both games to see if I could!

Anyway, thanks for the interaction and apologies for being a pain. Really didn't think this was a big deal and may have been something that was so simple you were getting all the complex stuff sorted before putting the polish and shine on the final product and placing it on the ModHub.

Kind regards.

**Comment by dkfiremann** [comment]
It is true that you could do this in CoursePlay versions for FS17 and FS19. 
But this is NOT a feature of the CoursePlay  version for FS22. It has been rewritten for FS22.

CoursePlay for the FS22 version is focus on Field work using the course generator. 
If you have trees in your field, there is an option to have Course Play make islands to go around trees in fields.  

If you need to drive your tractor on a path that you create, then you need to use AutoDrive for this. 
That is the current split between CoursePlay and AutoDrive. 

Remember this is a Mod for Farming Simulator, it is driven by people using their spare time to make this. 
It is not at polished software by a company.
Giants, that makes Farming Simulator, offend do a lot of changes to the game structure from one version to the next. This can make it hard for modders to convert a mod from one version to the next, and some features might not be possible to remake.

**Comment by dezza69** [comment]
Thank you for your response and feedback about my user feedback.

As someone who with mods on the modhub, I'm fully aware of the effort people put into their mods and changes made by the game devs (etc).

Enjoy your coffee.

Happy Farming!!
