### ISSUE TITLE
Improve the course generation for vines with the new course generator

### ISSUE THREAD

**Issue by Bugatti461** [Courseplay/Courseplay_FS22#1683]
Hallo, habe heute mal versucht Trauben zu Ernten mit Coursplay aber leider hat es nicht Funktioniert außer ich habe was verkehrt gemacht.
CP-Version ; 7.0.1.19
AD-Version : 2.0.0.6
VCA- Version : 9.1.1.2
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8843487/log.txt)
![fsScreen_2022_06_05_21_19_36](https://user-images.githubusercontent.com/64745813/172138272-3620f1a0-a1a6-4b1c-ad42-62c1c1bc1493.png)

Gruß Bugatti461

**Comment by dkfiremann** [comment]
And what did you do? 
Remember to use the template for bugs. 
What are the course settings, how did you make the course?

**Comment by Bugatti461** [comment]
Ich habe auf Rebe gestellt sowie ein Fahrzeug und keine Rebe auslassen.

**Comment by schwiti6190** [comment]
@Bugatti461 The field is to complex for the vine course generation for now. Might improve this at a later time.
For now I would suggest you stick to more rectangle like fields, as this should avoid the problem.

**Comment by Bugatti461** [comment]
Alles klar, danke für Hilfe.

**Comment by Tensuko** [comment]
Looks fixed with the new generator.
