### ISSUE TITLE
Häcksler Abfahrer fährt zu schnell

### ISSUE THREAD

**Issue by Dewey3105** [Courseplay/Courseplay_FS22#1684]
**Steps to reproduce**
Normal CP Konfiguration: Häcksler (Krone Big X1180 mit New Holland 130FB) + Abfahrer (zuletzt JD 8R410+Hawe SUW5000). Bei Abfahrern wurde diverse Zusammenstellung ausprobiert wobei keine Regel festzustellen ist bei welcher Kombination es funktioniert und bei welcher nicht.

**Actual behavior**
Der Abfahrer fährt 1km/h zu schnell, fährt am Häcksler vorbei wodurch der Häcksler nicht mehr überladen kann. Der Häcksler bleibt dann stehen, Abfahrer fährt noch ein wenig weiter, bevor er zurücksetzt und den Häcksler neu anfährt. Dann beginnt das ganze von vorne.

Zusatz: die gleiche Kombination an Abfahrer (Traktor+Anhänger) funktioniert u.U. ein paar Bahnen später ohne Probleme.

**Courseplay version**
Version used: 7.0.1.19

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8843794/log.txt)

**Map**
Bayrischerwald 1.0.6

**Relevant script mods**
AD, CP, VCA

**Comment by Tensuko** [comment]
Und was hat CP mit dem Abfahrer zu tun ?
-> AD
