### ISSUE TITLE
[Question] Unload Bale Loader In Field

### ISSUE THREAD

**Issue by Sim-ian** [Courseplay/Courseplay_FS22#1687]
Hi

Is there a way to unload a bale loader in the field? I'm using the Arcusin Multipack D14 to collect small 120cm bales and want to drop them in the field for collection later by a flatbed trailer but i can't find a way other than manually unloading in the field. which kind of makes the CP bale loading pointless as you have to sit and unload it all the time.

**Comment by Tensuko** [comment]
Only manual.
