### ISSUE TITLE
Old course Still remains on Field

### ISSUE THREAD

**Issue by redrummed1** [Courseplay/Courseplay_FS22#1689]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Field 6 Calmsden Farm, Previous course did not clear from map, cleared all courses from tractors and deleted course from save files. Still did not clear!!

Reverted back to previous version  v7.0.1.16 still did not clear

**Actual behavior**
When I create a new course as you can see in screenshots it just layers on top of course that did not clear, causing FPS stuttering everywhere on map.  When I stop current course FPS returns to a Steady 60.

**Expected behavior**
Only see current course on Job screen

**Screenshots**

**Courseplay version**
Version used: 
v7.0.1.16
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Calmsden Farm
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8853491/log.txt)
![fsScreen_2022_06_07_13_57_48](https://user-images.githubusercontent.com/23707135/172389942-6e7f550f-1cd5-429a-a596-ee2a786b963c.png)
![fsScreen_2022_06_07_13_58_07](https://user-images.githubusercontent.com/23707135/172389949-ca6071c8-8156-43f3-a794-3debc6786daa.png)
![fsScreen_2022_06_07_13_58_17](https://user-images.githubusercontent.com/23707135/172389951-79bd94ba-bc1d-44a8-8940-3bec213451ec.png)
![fsScreen_2022_06_07_14_16_22](https://user-images.githubusercontent.com/23707135/172389954-b5928d9d-4024-4c03-bb2f-541cb6c62f3f.png)

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Happens with all vanilla equipment
**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive

**Comment by redrummed1** [comment]
Solved it for now. In Global settings:  I deactivated "Show all activate courses" and it disappeared.
So there seems to be a bug somewhere when "show all active courses" is active

**Comment by redrummed1** [comment]
Yes on both versions

**Comment by Tensuko** [comment]
Can't reprouce.
Check your vehicles if the course is still loaded in any vehicle.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Pretty sure the course was loaded in any vehicle.
