### ISSUE TITLE
[BUG_SP] Smal patches not harvested at the start of the next row

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/Courseplay_FS22#169]
**Steps to reproduce**
Feld dreschen mit TopLiner (defaultitem)

**Actual behavior**
Kurs mit Vorgewende erstellt, hinterlässt oft kleine unbearbeitete Flecken an den Feldenden

**Expected behavior**
Sollte alles sauber dreschen

**Screenshots**

![fsScreen_2021_12_27_15_29_49](https://user-images.githubusercontent.com/21023840/147481612-49336ce9-8d49-4ddd-bcf2-16966bd0dd41.png)
![fsScreen_2021_12_27_15_33_20](https://user-images.githubusercontent.com/21023840/147481615-2912a4b2-9076-487a-865f-913e7f4e894c.png)
![fsScreen_2021_12_27_15_33_22](https://user-images.githubusercontent.com/21023840/147481616-ca845571-5f24-4d47-88f9-e9eedf3a6b43.png)
![fsScreen_2021_12_27_15_33_27](https://user-images.githubusercontent.com/21023840/147481619-fe9cf59d-e03e-4d64-8111-e2772e71d41a.png)

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7780647/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
no

**Relevant script mods**
 Autodrive & VCA

**Comment by Tensuko** [comment]
Pls try 7.0.0.8
Reopen if Problem persists.

**Comment by iljarogoff** [comment]
Still having those patches
![fsScreen_2021_12_30_12_41_26](https://user-images.githubusercontent.com/21023840/147749024-1854db28-36ab-448f-9b80-496104b4a837.png)

**Comment by pvaiko** [comment]
What is your center setting? Just up/down? Lands? Racetrack?
