### ISSUE TITLE
Grimme Rootster 604 + Grimme Rexor 6300, automatic unload stops before reaching unload point (trailer)

### ISSUE THREAD

**Issue by Truckernoerden** [Courseplay/Courseplay_FS22#1690]
Make a route on a sugarbeet field, with automatic unload. 

A clear and concise description of what happens:

The sugarbeet harvester, finds its way to the unloading point, but stops before it reaches the trailer. The tractor or Rexor, stops besides the trailer. 

![Clipboard03](https://user-images.githubusercontent.com/63363655/172490493-6a87c363-ac2d-47b3-94e2-e5dea1b0813c.jpg)

A clear and concise description of what you expected to happen:

The harvestor should be parked next to the trailer/unloading point. 

Version used: 
Courseplay v7.0.1.19

Log:

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8856838/log.txt)

Map played on:

FS22_BigFieldsXXL10km_zoltanm

Which vehicle or implement?:

Grimme Rootster 604

Grimme Rexor 6300

Mod yes/no ?:

No

Mods like Autodrive or VCA and so on:

Autodrive installed, but not in use.

**Comment by Tensuko** [comment]
Will be fixed in ModHub Version.
