### ISSUE TITLE
Auto drive and courseplay

### ISSUE THREAD

**Issue by Cody4020** [Courseplay/Courseplay_FS22#1691]
If I have both the mods active with no other mods going it will not let me create a field with the plow or disc. If I turn one or the other off, it will. Is there something I'm missing for it to allow me to create field?

**Comment by 60erjonny** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=223946&title=fs2022

**Comment by Tensuko** [comment]
Got nothing to do with CP it might be not shown in F1 Menu cause that Menu is to small.
Turn off Help Menu on AD and CP and it will be shown again.
