### ISSUE TITLE
Skipping Rows with JD 2410 Plow (Mod) [BUG_SP]

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#1695]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course, 2 headland, round corners. start course and let it go

**Actual behavior**
Headlands drive fine, first up/down plows fine, second it just drives down the field but doesn't put the plow down and repeats.

**Expected behavior**
It lowers the plow on each pass.

**Screenshots**
![fsScreen_2022_06_08_18_16_10](https://user-images.githubusercontent.com/96673100/172733381-1ca0379f-e928-4061-bff5-1af0b3f03914.png)
![fsScreen_2022_06_08_18_26_25](https://user-images.githubusercontent.com/96673100/172733855-8da0712b-5b4d-4f32-9793-cb689af846a0.png)
![fsScreen_2022_06_08_18_26_27](https://user-images.githubusercontent.com/96673100/172733857-b3efbd71-ba9b-4a50-bb7b-ddac9f148e00.png)
![fsScreen_2022_06_08_18_26_38](https://user-images.githubusercontent.com/96673100/172733862-e85de7e0-9447-4f16-962d-ba63850701c4.png)

**Courseplay version**
Version used: .19

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8865553/log.txt)

**Map**
Map played on. 

Fox Farms

**Vehicles/ implements involved**
Which vehicle or implement?
Case IH Magnum 400 Powerdrive, Wide tire/weights, 
JD 2410 Plow (Mod)

**Relevant script mods**
 Autodrive (not active for this course)

**Comment by Tensuko** [comment]
Can you also add a complete logfile pls.

**Comment by ArtV-Nef** [comment]
This plow is broken, it has a coup function, which logically should not be there. Delete this mod.

**Comment by Tensuko** [comment]
> coup function

What is that ?

**Comment by ArtV-Nef** [comment]
> What is that ?

plow rotation function )

**Comment by Resandise** [comment]
> 

I will add one next time I use the plow

**Comment by Tensuko** [comment]
> plow rotation function

oh okay.



> I will add one next time I use the plow

How can you add one to the plow when there is nothing to rotate ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Pretty sure it is a mod Issue.
