### ISSUE TITLE
Automatic Headland setting

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#17]
Beside the Number of Headlands (0-X) add the option to generate an automatic number of headlands.
Automatic - 0 - X

It should be calculated like this:
Total length of the Vehicle + Tool * 1.5 (maybe 1.2 is enough) / workingwidth. Rounded up and this should be the number of headlands to provide enough space for a nice turn.

**Comment by pops64** [comment]
I know in FS17 CP the turn calculation was used to determine if it could turn on the field at the end of the lane. Always had a thought of using this to determine the number of headlands needed. Cause turn radius should be taken into account

**Comment by rohne83** [comment]
Strong geometric approach: in best case the working width is larger than the turn radius and the turn has a strong U shape (thin red line). In this case the required headland size would be total length + turn radius + (workingwidth/2).
If turn radius is larger than the working width a so-called omega-curve (thick red line) is needed for turning without reversing. In that case we would even need two times the turn radius.
Plus a small extra for transition the steering
![headland turn](https://user-images.githubusercontent.com/71030138/147372342-61c51cea-798d-4de9-8618-7ca6c23d66f0.png)
.

**Comment by pvaiko** [comment]
It is unfortunately a bit more complicated than this. 
- as @rohne83 pointed out, you need to consider the turning radius
- you can use fishtail (3 point) turns as well
- where you want to start the turn and where you want to end it also depends on the position of the work area relative to the steering node of the vehicle (and not on the length of the vehicle + implements) Also, the position of the work area depends on the implement early/late raise/lower user selection (this is what we call front marker/back marker).
- you also have to consider non-perpendicular headlands

So the width of the headland really depends on a number of factors, and you may end up with a lot more headland than you actually need, using that geometric approach for a combine you'll have 3*turning radius + half work width (as an omega turn in fact needs 3 * r), but by making a 3 point turn, you can get away with 1 * radius + half work width.

@rohne83 we stopped using a geometric approach, instead, we use what is called Dubins path (or Reeds-Shepp when reversing is allowed) to generate the path between two poses (position+direction).

**Comment by jobyrns72** [comment]
Or possibly a full circle pattern?? Im still hoping lol

**Comment by rohne83** [comment]
To make it a bit more complicated, to minimize soil compaction in RL more and more farms start to use only existing tracks - keyword: controlled traffic farming. Of course work widths of all tools have to match each other (either 1 by 1 or at least integer multiples of each other). But at least for the same vehicle on the same field it will only use tracks where it has to drive anyway. Fertilizer sprayer/spreaders are doing this for ages now (just look on the field tracks you can see on google earth/maps/whatever). Also combines turning at row end would always drive into one of the headland lanes and use exactly this one to reach the next row (CP was already doing kind of this approach in FS19 when pathfinder was switched on für turns).

**Comment by coatsy35** [comment]
Would be good to just have a display that tells us what the total length of vehicle and implement is (on the course generator page) so we can at least approximate first time what number of headlands are required

**Comment by Tensuko** [comment]
https://github.com/Courseplay/CourseGenerator/issues/12
