### ISSUE TITLE
[BUG_SP] Course Play worker Blocked by Object

### ISSUE THREAD

**Issue by WMAvant** [Courseplay/Courseplay_FS22#1700]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a fieldwork/harvest course as normal.  Error happens during normal turning steps in the course.

**Actual behavior**
Tractor/Harvester will begin a turn step and come to a stop during turns and the "Blocked by an Object" warning block appears in the top right corner of the screen.  This happens when there is no object in the way.

**Expected behavior**
Turn and continue as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/46088002/173198378-7e30c3d7-e54b-4329-80ac-569b4dc79aa4.png)

**Courseplay version**
Version used: 7.0.1.20

**Log**
<script src="https://gist.github.com/WMAvant/6e4b736be3582081e3810180ed557282.js"></script>

**Map**
Happens on all maps but currently using Midwest Horizons

**Vehicles/ implements involved**
The Squad's John Deere 8110 (Mod) with game Scorpio 550 Rock Picker 
Also any combine with Corn Headers (Mods)
Mod yes.

**Relevant script mods**
Autodrive, Precision Farming, Real Life Numbers active

**Comment by WMAvant** [comment]
Updated Comment:  I went back to previous versions of CP and discovered the issue started with the 7.0.1.16 version and shows up in every updated version after that.  Version 7.0.1.15 does not have the blocked by an object issue in the turns so I would assume something in the 16 version update is causing the error.

**Comment by Tensuko** [comment]
There is no Error in the Code and no bug that starts at any version regarding the blocked by an object.

The question is what object is there.
I would like to see the collision active (F5) those yellow boxed.

As the Tractor is a mid I smell modified colli boxes that are not correct, like we have "issues" in the past about that...

**Comment by WMAvant** [comment]
I am not sure how to get you the collision you are asking for?  I press F5 in the game when the tractor is stopped with the "blocked by an Object" warning but don't see any change or yellow box?  It may be a Mod issue but I can use the mod without any problems on CP Version 7.0.1.15 or earlier.  Attached 

![image](https://user-images.githubusercontent.com/46088002/173202707-73ccec91-03c1-40f6-9fae-cde157b0dc6f.png)

<script src="https://gist.github.com/WMAvant/a0244da604fe2dda5b71e690fe7c44b3.js"></script>

**Comment by Tensuko** [comment]
This is with F5
![fsScreen_2022_06_11_22_46_23](https://user-images.githubusercontent.com/27344744/173204332-f504976f-a25c-48bd-9617-41e9424ede50.png)

**Comment by WMAvant** [comment]
I'm sorry but I press F5 on my computer and nothing happens.  I don't see the boxes like you have in the picture.  Is there another setting or debug option I need to turn as well?

**Comment by pvaiko** [comment]
> It may be a Mod issue 
If you look closely at your screenshot, you can see that the second green line from the left in front of the tractor has a short red section. That means that ray is hitting something where the red section ends. No idea what that is. 

Would probably help to see the logs with debug on but your gists don't show up in a readable format.

**Comment by WMAvant** [comment]
So I figured out my problem with turning on the collisions.  I needed to active the Developer function in the game.xml file.  I have attached a couple for the photos for you to review.

![image](https://user-images.githubusercontent.com/46088002/173241126-18be8a69-f31e-417c-bc1d-14ffe6b3b1a6.png)

![image](https://user-images.githubusercontent.com/46088002/173241420-f58fb58e-d031-4a45-b228-19cba5fe4185.png)

![image](https://user-images.githubusercontent.com/46088002/173241157-ceda1a8a-96c4-404c-a2aa-3f9854017b24.png)

<script src="https://gist.github.com/WMAvant/177b52df342051cc13700fa0013a59fe.js"></script>

**Comment by Tensuko** [comment]
See, that is the collission from FS19 that is at the front there.
![173241126-18be8a69-f31e-417c-bc1d-14ffe6b3b1a6](https://user-images.githubusercontent.com/27344744/173242824-3d9a10bc-2a0b-46ed-9444-7f95ea48ee79.png)
And there it his the colli:
![173241420-f58fb58e-d031-4a45-b228-19cba5fe4185](https://user-images.githubusercontent.com/27344744/173242864-11d6e4a0-bc64-41b4-9bac-8e3303ef0cb5.png)

**Comment by WMAvant** [comment]
So I looked at some of the other tractors that work correctly and moved the collision box down and further back like the other tractors and it is working correctly now. 

Thank you for your help and patience with me.

![image](https://user-images.githubusercontent.com/46088002/173244198-8b99dc5b-95c7-42ea-b88b-115df22a2def.png)
