### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by marc-sdlr** [Courseplay/Courseplay_FS22#1702]
Hello the course generator no longer opens on the field for me, is there a tip?

**Comment by Tensuko** [comment]
Follow the ingame manual.

**Comment by marc-sdlr** [comment]
Ich hoffe das geht auch auf deutsch da ich nicht so gut in englisch bin.
Also ich hatte gestern gespielt und es hat alles perfekt funktionirt heute habe ich LS ganz normal gestartet, aber wenn ich auf dem Feld bin und auf kein kurs drücke um einen kurs zu erstellen taucht nur das normale Helfermenü auf ohne kursgenerator. LG

**Comment by Tensuko** [comment]
Vlt beschreibst du das mal etwas genauer....
Fahrzeuge, Geräte usw usw

-> Ingame Hilfe Menü anschauen hilft auch.

**Comment by marc-sdlr** [comment]
Also jetz geht es alles irgendwie wieder aber ich habe nichts verändert, auser auf der NF marsch erkennt er bei mir feld 4,5,6 nicht muss ich da ein rundkurs einfahren?

Trotzdem großes Dankeschön für die Hilfe. ihr macht super tolle Arbeit LG
