### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1703]
**Steps to reproduce**
Mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen sammeln lassen .

**Actual behavior**
Werden mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen gesammelt, fahren die Rampen aus. Ist der Wagen voll, fahren die Rampen wieder ein, auch wenn die Rampen gar nicht konfiguriert wurden.
Dabei bekomme ich in der Log folgende Fehler von Courseplay gemeldet:

2022-06-13 21:47 LUA call stack:
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (220) : printCallstack
  =[C] (4294967295)
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (156) : format
  =[C] (4294967295)
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (220) : xpcall
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (154) : try
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIBaleFinder.lua (177) : debugVehicle
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIBaleFinder.lua (156) : replaceDriveStrategies
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/tasks/CpAITaskBaleFinder.lua (30) : startCpBaleFinder
  dataS/scripts/ai/jobs/AIJob.lua (209) : start
  dataS/scripts/ai/jobs/AIJob.lua (124) : startTask
  dataS/scripts/ai/AISystem.lua (335) : update
  dataS/scripts/FSBaseMission.lua (1982) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1217) : update

und 

2022-06-13 21:47 :33 [info lp836488] E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua:156: bad argument #1 to 'format' (string expected, got no value)

**Expected behavior**
Die Rampen, die eigentlich nur sichtbar sind, wenn der Wagen auf Autoload Paletten konfiguriert ist, sollten im Helfer beim Laden nicht ausgefahren werden

**Screenshots**

**Courseplay version**
Version used: 7.0.1.20

**Log**

**Map**
Hobo's Hollow

**Vehicles/ implements involved**
[Which vehicle or implement? https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234121&title=fs2022
Mod yes/no ?] Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

AutoDrive
Courseplay
Enhanced Vehicle

**Comment by Tensuko** [comment]
fixed in next update.
