### ISSUE TITLE
Silo verdichten[Feature]

### ISSUE THREAD

**Issue by Menian** [Courseplay/Courseplay_FS22#1704]
Hallo CP Team :)
Im 19er gab es die Funktion Silo verdichten per Schiebeschild mit CoursePlay.
Ich vermisse diese Funktion nun im Ls22. Bis jetzt kann man nur selber "von Hand" das Silo verdichten.
Wäre schön, wenn das wieder möglich wäre.
Ihr seid toll und ich bewundere eure Arbeit!

**Comment by Tensuko** [comment]
Bereits 100 mal beantwortet, findet sich bestimmt unter Suche.
Ist in Planung!
