### ISSUE TITLE
[BUG_SP] Turn radius too small for big implements

### ISSUE THREAD

**Issue by lRainZz** [Courseplay/Courseplay_FS22#1707]
I noticed that, with a 17.8m planter (1775 NT, 24 rows) the turning radius is way too small and it leaves a lot of unplanted areas.

I tried with 1-5 headlands and "turning on field" on/off, but always with the same result. It seems the headland space is not used/considered when making turns. This is the best I could get it to:
Additionally I had to manually unstuck the tractor/planter, because it turned way too sharp and got stuck on itself.

![20220616135450_1](https://user-images.githubusercontent.com/18189542/174069925-f7d384a7-d54c-40b7-aa98-f3e615760eff.jpg)
![20220616142507_1](https://user-images.githubusercontent.com/18189542/174069966-efd5de45-0830-40b3-a23a-6e7e0d0de17d.jpg)

**Comment by Tensuko** [comment]
forces them to 12m, a bit strange is, yours should be driven reverse to adjust to the turn start. Tested with 2 headlands.

**Comment by lRainZz** [comment]
What do you mean by force them to 12m? Then most of it will be planted twice?

**Comment by Tritura2** [comment]
He forced the turn radius to 12m. He wasn’t talking about work wide.

**Comment by lRainZz** [comment]
Ah now I get it. That's in the commit, okay thanks!
