### ISSUE TITLE
[BUG_SP] Ausgeklappte Rampen beim Ballenwagen, Teil 2 (siehe #1703)

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1708]
Steps to reproduce
Mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen sammeln lassen .

Actual behavior
Werden mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen gesammelt, fahren die Rampen immer noch aus.

Dabei bekomme ich in der Log folgende Fehler von Courseplay gemeldet:

2022-06-16 22:36 Error: Running LUA method 'mouseEvent'.
E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJob.lua:110: attempt to index local 'vehicle' (a nil value)

Expected behavior
Die Rampen, die eigentlich nur sichtbar sind, wenn der Wagen auf Autoload Paletten konfiguriert ist, sollten im Helfer beim Laden nicht ausgefahren werden

Screenshots

Courseplay version
Version used: 7.1.0.0

Log

Map
Hobo's Hollow

Vehicles/ implements involved
[Which vehicle or implement? https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234121&title=fs2022
Mod yes/no ?] Yes

Relevant script mods
Mods like Autodrive or VCA and so on.

AutoDrive
Courseplay
Enhanced Vehicle

**Comment by Tensuko** [comment]
Es gibt kein Teil 2 und wird auch kein Teil 3 geben!

Das ist ein Problem das Achim in seinem Script lösen muss.
Wenn wir andere Wickler oder Sammelwagn ausklappen MÜSSEN können wir das nicht von Rampen unterscheiden, ganz einfach.

Da wird von unserer Seite aus nichts angepasst.
