### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Hun73rdk** [Courseplay/Courseplay_FS22#171]
Needs fixing:

Combine/tractor says blocked path on the field or just next to it with nothing in the way at all
Combine/tractor says not reachable just next to the field
Combine starts header while folded
Combine/tractor has to fold every time it wants to resume after it has been canceled and wants to resume
Combine/tractor just turns in circles and cant start working

**Comment by pvaiko** [comment]
Thanks for the feedback, most of this is the Giants helper problem, description of others are way to vague for us to be able to do anything with them.
