### ISSUE TITLE
[BUG_SP] Ausgeklappte Rampen am Ballenwagen der Aguas Tenias Hänger, Teil 3

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#1710]
Ich muss doch leider einen Teil 3 machen, da man mir keine Möglichkeit gab, darauf zu antworten...

Steps to reproduce
Mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen sammeln lassen .

Actual behavior
Werden mit einem Ballenwagen aus dem Aguas Tenias Pack Ballen gesammelt, fahren die Rampen immer noch aus.

Dabei bekomme ich in der Log folgende Fehler von Courseplay gemeldet:

2022-06-16 22:36 Error: Running LUA method 'mouseEvent'.
E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJob.lua:110: attempt to index local 'vehicle' (a nil value)

BIs Version 7.0.17 funktionierte noch alles. Die Ballenwagen des Aguas Tenias Packs laufen NICHT auf dem Script von Achimobil oder dem Universal Autoload. Sie haben wieder ein ganz eigenes Ding, ich vermute mal, wie bei den Ballenwagen aus LS19 wurde es über die Standard Funktionen des Spiels generiert. So wurden die Geräteachsen beim Abladen der Ballen zum verschieben benutzt. Das kann meines Wissens nach weder das Universal Autoload, noch das PalletAutoLoad von Achimobil. Das Problem besteht erst seit Version 7.0.18 oder 7.0.19.
Mir fällt es schwer, zu glauben, dass es an anderen Scripts liegen soll, wenn lediglich an Courseplay Änderungen vorgenommen wurden, Achimobil's Script aber nicht geändert wurde in letzter Zeit

**Comment by Tensuko** [comment]
Du hast immer die möglichkeit auf ein Issue zu antworten.

Du verstehst das Problem aber nicht!

Es gibt kein Rampe ausklappen und Gerät aufklappen, das ist beides die gleiche Funktion -> unfoldImplement!
Was wird dabei nun ausgeklappt, das Gerät oder die Rampe ?
Das lässt sich nicht unterscheiden.

Ich wiederhole:
WIR ändern daran NICHTS.

**Comment by Tensuko** [comment]
Und die von dir genenten Geräte brauchen sehr wohl das script, steht doch da:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234121&title=fs2022

**Comment by Tensuko** [comment]
Von Achim:

> hinzu kommt ich habe nebenbei gefunden warum meine Trailer ausklappen, liegt am trailer. default ist allowUnfoldingByAI anscheinend true und bei den events klappt er dann aus, wenn ich das auf false setze, dann klappt er nicht aus. In meinem test hat er beim starten im CP den Autoloader eingeschaltet und mit dem sammeln angefangen

**Comment by SchorschiBW** [comment]
Hoppla, voll übersehen. Das tut mir tatsächlich leid. Dann werde ich da nochmal schauen müssen.

Hat sich dann wohl erledigt

**Comment by Tensuko** [comment]
Das steht bei uns im Discord, weil wir mit ihm in Kontakt sind.
Daher wenn ich dir das so sage, darfst du das auch glauben.

**Comment by SchorschiBW** [comment]
Du hast mich falsch verstanden. ICh meinte, in welchem Scriptteil das allowUnfoldingByAI steht. Ich habe es nirgends gefunden
