### ISSUE TITLE
Can I enable more options?

### ISSUE THREAD

**Issue by Snoofus** [Courseplay/Courseplay_FS22#1711]
I've been using Courseplay for the last 3 months in FS 22 and I can see I'm missing some vehicle options compared to what I can see people have on youtube. I've attached screenshots of what I have no matter what I'm setting up. Is there a way to enable more options? I also tried new game with Courseplay as the only mod as I was thinking maybe something is clashing with it but still the same
![1](https://user-images.githubusercontent.com/107707342/174343997-d347b41a-90c2-4513-be89-e8a1c07a9760.JPG)
![2](https://user-images.githubusercontent.com/107707342/174344010-67e89056-4402-464d-bc71-b90fc5762b77.JPG)
.

**Comment by Tensuko** [comment]
Global Settings -> Expert Mode (it is also written in the ingame help menu)
