### ISSUE TITLE
Combine unloading when full

### ISSUE THREAD

**Issue by kwguk** [Courseplay/Courseplay_FS22#1712]
Just started with FS22 so forgive my lack of understanding with all things CP. Great to see CP as good as ever!

In 19 when the combine was full and it had stopped waiting for a trailer, when it had unloaded enough it would then restart its work and carry on unloading on the move into the trailer. I have the 'stop when unloading' deactivated but my combine will only restart after its completely empty.

Is there something im missing or is this just what CP does?

**Comment by Tensuko** [comment]
new savegame, default settings, working just fine on 7.1.0.0

![fsScreen_2022_06_18_15_46_27](https://user-images.githubusercontent.com/27344744/174441098-770b54b5-b0d7-4448-8185-c443c3ccac0d.png)

![fsScreen_2022_06_18_15_45_49](https://user-images.githubusercontent.com/27344744/174441007-37239828-4cfa-4cce-bdd2-4c21696e7a46.png)
