### ISSUE TITLE
Seed/Fertilizer not spent using Terrasem C6F

### ISSUE THREAD

**Issue by cschrieber** [Courseplay/Courseplay_FS22#1714]
**Steps to reproduce**
Using Terrasem C6F seeder on Elmcreek field 31
When Courseplay is started, seeds/fertilizer quantities do not decrease while seeding is occurring
The field does otherwise show as being seeded and fertilized.

**Actual behavior**
No seed/fertilizer is spent, but field is now seeded/fertilized.

**Expected behavior**
Seed and fertilizer values should be decreasing while the seeding is occurring.

**Courseplay version**
7.0.1.20

**Log**

**Map**
Elmcreek

**Vehicles/ implements involved**
Terrasem C6F
Mod yes/no ? No

**Relevant script mods**
Autodrive, GPS, Courseplay

**Comment by Tensuko** [comment]
And did you check your ingame setting "AI Helper buy fertilizer"... ?

**Comment by shadow250** [comment]
i have same/similar issue with the 3665 bluedrive on the same map the fertilizer is turned off in courseplay but it gets fertilized without using any with sunflower, with corn its off in courseplay but it fertilizes and uses it from the tank. the helper autofill is off.
it is a stock planter but i do have some mods none that should modify fertilizer.

**Comment by Tensuko** [comment]
@shadow250 that might be the same PF Problem we had in FS19. Not a CP Problem.

Issue closed due to inactivity (question not answered.)
