### ISSUE TITLE
[BUG_SP] wenden auf Feld deaktiviert, trotzdem wird so gewendet

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1716]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
CP-Einstellungen:
![fsScreen_2022_06_21_07_52_59](https://user-images.githubusercontent.com/24860501/174726059-a75e78f1-9aaf-4606-9112-f213d20badb3.png)
![fsScreen_2022_06_21_07_54_19](https://user-images.githubusercontent.com/24860501/174726225-9d31c995-fb21-4f69-b562-1b16191c4821.png)
![fsScreen_2022_06_21_07_54_23](https://user-images.githubusercontent.com/24860501/174726229-829bbdf2-2fb2-478f-9261-982f382ccd4a.png)

**Actual behavior**
A clear and concise description of what happen.
der Traktor wendet nicht nach rechts zur nächsten Bahn, sondern fährt nach links eine 270grad schleife um dan nnac hrechts zur nächsten Bahn zu fahren.
 
**Expected behavior**
der Traktor könnte gleich nach rechts zur nächsten Bahn wenden
![fsScreen_2022_06_21_07_50_39](https://user-images.githubusercontent.com/24860501/174726638-06b8a885-ada8-40b9-b516-9d04b9e97bec.png)

**Screenshots**
![fsScreen_2022_06_21_07_50_39](https://user-images.githubusercontent.com/24860501/174726466-f43364d2-aac7-46ac-8d60-21fd5c2322b5.png)
![fsScreen_2022_06_21_07_50_43](https://user-im
![fsScreen_2022_06_21_07_51_00](https://user-images.githubusercontent.com/24860501/174726490-8b405bdf-0674-4efe-9ff4-2f9a72e3ed8a.png)
ages.githubusercontent.com/24860501/174726482-54b3f48f-fbaf-4934-bb49-333c237866f6.png)
![fsScreen_2022_06_21_07_51_03](https://user-images.githubusercontent.com/24860501/174726495-971411ab-472c-4dc7-af9b-6bfe27b0dfca.png)

**Courseplay version**
Version used: 
7.1.0.0 aus dem Github
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Hobos Hollow

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Claas Xerion

**Relevant script mods**
Mods like Autodrive or VCA and so on.

lg
andreas

**Comment by Tensuko** [comment]
Er macht genau das, was er soll.
Du hast den Pathfinder turn an.
Wenn dieser an ist, wird ganz klar versucht auf dem Feld zu bleiben, unabhängig von der Einstellung wenden auf Feld.
Wenn es dir egal ist, dass er das Feld verlässt, stell beides aus.

Der Pathfinder kommt dann nur noch zum Einsatz, wenn start und endpunkt vom turn zu weit auseinander liegen.

- not a bug.

**Comment by andreasthu** [comment]
ok, danke für diese info
lg
andreas
