### ISSUE TITLE
Ballen laden

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1717]
Hallo
Ist die Funktion über Courseplay mit Sammeln/Wickel Ballen ausgeschaltet. Wenn der Fahrer über Autodrive die Strecke fährt und dann über Course die Funktion Sammeln/Wickel Ballen einschalten soll, macht er das nicht

**Comment by Hendirk** [comment]
![Ballen](https://user-images.githubusercontent.com/47453761/174866091-5efed378-24c9-4195-85ac-13323328889a.png)

**Comment by Tritura2** [comment]
Du musst dich auf dem Feld befinden, damit CP übernimmt. Die vorgefahrenen Strecken von AD für die NFMarsch Map sind dafür etwas unpraktisch, da die meisten Feldpunkte neben dem Feld sind. Wenn du den Punkt etwas weiter auf das Feld legst oder einen zweiten nur fürs Ballensammeln erstellst, dann gibt das keine Probleme.

**Comment by Hendirk** [comment]
Alles klar, vielen Dank für die Info --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 21.06.22, 20:01 schrieb Tritura2 ***@***.***>:

   
  Du musst dich auf dem Feld befinden, damit CP übernimmt. Die vorgefahrenen Strecken von AD für die NFMarsch Map sind dafür etwas unpraktisch, da die meisten Feldpunkte neben dem Feld sind. Wenn du den Punkt etwas weiter auf das Feld legst oder einen zweiten nur fürs Ballensammeln erstellst, dann gibt das keine Probleme.
