### ISSUE TITLE
[Question] is there a way to unload a harvester with a tractor and trailer 

### ISSUE THREAD

**Issue by kiwirobert** [Courseplay/Courseplay_FS22#1718]
im wondering is there a way to unload a harvester with a tractor and trailer and then deliver it to a silo or a building once its full

**Comment by Tritura2** [comment]
No. CP and AD developers work together and so do both mods. You can create routes for transport and delivery using AD. It’s also possible using AD to drive to field “xy” and let CP take over for the field work. I highly recommend to use both mods.

**Comment by kiwirobert** [comment]
> No. CP and AD developers work together and so do both mods. You can create routes for transport and delivery using AD. It’s also possible using AD to drive to field “xy” and let CP take over for the field work. I highly recommend to use both mods.

ok thanks
