### ISSUE TITLE
Ability so SAVE and DRIVE on a custom recorded course.

### ISSUE THREAD

**Issue by SweeperSwift** [Courseplay/Courseplay_FS22#1720]
**What is the problem this feature/enhancement solves?**
It is often better to record my own custom field course; and rather not make use of the CP Course Generator as the Course Generator is often more of a frustration than a help, Especially when it comes to hay making and collection; or when fields have very curvy edges and "interesting" slopes.

**Describe the solution you'd like**
To be able to SAVE my Custom CP Recording that I drive (record) on a field, just like I save a CP "Course Generator" course. And then, of course, be able to load my custom course to any tractor, just like I can do with generated courses that have been saved. I.e. extend the "course recording" feature beyond the ability of only being there to make edges for new fields, so that these can also be driven as often as needed, which is especially useful for highly specialized field work!

**Describe alternatives you've considered**
I have tried Headlands and Circle but it just does not work as well as when I drive my own course recording, especially when wind-rowing and picking up grass, hay, straw using either balers or pick-up wagons!

**Additional context**
I find it So unfortunate that you can only use the course recording feature for mapping out fields; and not make your own custom field courses, simply because you cannot save your 'custom course' as you save your 'field generator' courses!

I can't recall how many times in previous FS games did I drive and record my own custom field course, because the built-in CP "course generator" just happens to miss bits or drive into obstacles or just get it completely wrong from time to time. The same is true in FS22. (Which is mostly down to the nature of some maps and not something the Dev's can really do to CP). Unfortunately, since FS22, saving your custom recording as a course, has been removed! Why? The answer given is because auto-drive is meant to replace this portion of CP. But Auto Drive is not meant for fieldwork, right? Do people not know that, even in real life, being able to 'drive' your own custom recorded course on a field, is still one of the most useful features of ANY field GPS?

Being able to record your own custom course on a field is also one of the most accurate ways to get the job done exactly the way you need it to be done! The ability to do this with course play would be such a relieve because currently there is nothing in FS22 that can do exactly this. CP would be THE mod to best address this rather severe shortcoming.

Thank you so much for your consideration and hope to see this ability enabled in CP real soon! (Actually, it would be great to see it in the Mod-Hub release already as it's an absolute "must-have". I won't be surprised if you get a lot of requests for this feature once it goes live in mod-hub / or even have to take a fair bit of heat for not including this in the first mod-hub release. Anyhows, thank you for a great mod, otherwise :-) Without it I would not have bothered with Farming Simulator!)

**Comment by Tensuko** [comment]
-> #1719
