### ISSUE TITLE
Not consuming seed when there is no Precision Farming variable seed rate configuration[BUG_SP]

### ISSUE THREAD

**Issue by Nielwulf** [Courseplay/Courseplay_FS22#1723]
**Steps to reproduce**
1. Select a seed type that does NOT have a variable seed rate configuration.
     - I was seeing this behavior when planting grass.
2. Generate course.
3. Start Courseplay planting job.

**Actual behavior**
No seed is consumed/used when planting crops with no variable seed rate configuration in Precision Farming or the map.

**Expected behavior**
Seed to be consumed at the standard, non-variable, rate that seed is consumed when manually planting.

**Courseplay version**
Version used: 7.1.0.0

**Log**
https://gist.github.com/Nielwulf/f73470739bdb3432eb4ce8f09ddf2462

**Map**
Stone Valley

**Vehicles/ implements involved**
Which vehicle or implement? 
- John Deere 6250 R
- Kuhn HR 6040 RCS + BTFR 6030
- Kuhn TF 1512
Mod yes/no ? no

**Relevant script mods**
- Autodrive

**Comment by Tritura2** [comment]
Sounds like #1714.

**Comment by Tensuko** [comment]
And why is that a CP Problem when it is "when planting crops with no variable seed rate configuration in Precision Farming or the map." ???

Don't see the Error on CP side, also check Giants Helper -> closed.
