### ISSUE TITLE
[Feature] Warning light should turn on when combine reaches 70% and opens auger. 

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/Courseplay_FS22#1724]
**What is the problem this feature/enhancement solves?**
After last release combine unload auger/pipe opens at 70% fill level. I didnt find any option to change that, but my point is, orange warning lights should turn on automatically when auger is open . And one more idea. There should be option in "quick menu" to turn on/off swath. Cheers

**Comment by Tensuko** [comment]
That is AD who open the pipe early, not us.
Lights go on when full on our side.
Swath control is and will stay in vehicle settings.
