### ISSUE TITLE
[BUG_SP] CP klappt alle Anbaugeräte mit X aus

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#1725]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Schlepper mit Front und Heckgerät was mit X geklappt werden kann und dann CP starten 

**Actual behavior**
CP klappt alles aus obwohl nur das hintere geklappt werden müsste 

**Expected behavior**
Es wird nur das hintere Gerät ausgeklappt und nicht der Arm 

**Screenshots**
![image](https://user-images.githubusercontent.com/78980660/175654491-b5d01cec-441d-48a3-952d-e10e77009a97.png)

**Courseplay version**
Version used: 7.1.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8980253/log.txt)

**Map**
Osada

**Vehicles/ implements involved**
Claas Xerion mit Kaweco Saddle Fass und Frontdock

**Comment by Tensuko** [comment]
Und wie sollen wie unterscheiden, was ausgeklappt werden muss und was nicht ?

**Comment by 0scarZulu** [comment]
In dem ihr eventuell ein Abfrage einbaut das man wählen kann ob alles, nur hinten oder nur vorn.

**Comment by Tensuko** [comment]
Nicht noch ein Setting das man beachten muss..... wir wollen weg von diesem ganzen:
"Du hast vergessen XY richtig ein zu stellen."

Also nein.

**Comment by Tensuko** [comment]
Es gäbe da eine einfahe Lösung.... muss Giants aber einbauen, bzw ha mich würde interessieren was der Giants Helfer macht.
Normal müsste der Xerion in seiner .xml allowUnfoldingByAI false drin haben.
Weil auch der Giants Helfer sollte das Rohr nicht ausklappen.

**Comment by Tensuko** [comment]
Da, siehste, Giants Helfer macht den gleichen Murks -> Giants Bug.
![fsScreen_2022_06_24_23_14_45](https://user-images.githubusercontent.com/27344744/175669460-c9a3f72e-b06c-418f-88ab-ca35a2fbb15b.png)
