### ISSUE TITLE
[Enhancement] Vehicle should drive to the end point with the rear attached tool, not only front

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#1726]
Hallo
Gibt es eine Einstellung das beim Ziel beim mähen auch die letzter Meter mit gemäht werden ?
![Gras](https://user-images.githubusercontent.com/47453761/175786606-6b14f66c-72e3-4fe2-a771-741c1fe19495.png)

**Comment by Tensuko** [comment]
Anheben spät hast du drin ?

**Comment by Tritura2** [comment]
Ja ist an. Das gleiche passiert auch beim Krone Big M

**Comment by rohne83** [comment]
Passiert auch beim Säen und anderen Feldarbeiten mit im Heck angekuppelten Geräten

**Comment by rohne83** [comment]
Dann tritt das nur auf beim Start auf den Feldreihen auf, wie es bei Bodenbearbeitung und normalem Drillen üblich ist. Da hat man abhängig von der Arbeitsbreite solche mehr oder weniger großen Reste an der Seite m Ende übrig:

![fsScreen_2022_06_27_20_22_54](https://user-images.githubusercontent.com/71030138/176029383-e6668755-6e15-4b8a-85e6-d11cd05aca2e.png)

**Comment by Tensuko** [comment]
Ja okay das kann ich nachvollziehen, ist aber was ganz anderes als das oben beschriebene Problem.

**Comment by rohne83** [comment]
Ja, da hat mir meine Erinnerung einen Streich gespielt. Als ich die Issue-Beschreibung gesehen hab, kam es mir direkt bekannt vor, hab aber den kleinen aber feinen Unterschied nicht bemerkt. Kann zur Not noch ein extra Issue aufmachen dafür.

**Comment by coder2000** [comment]
I have similar issues with the Krone Big M mower as shown in this screenshot. I am using a path with sharp corners if that makes a difference.

![20220629222609_1](https://user-images.githubusercontent.com/27944/176586971-238535ef-8000-440e-8272-81b8a5033530.jpg)

**Comment by Tensuko** [comment]
@coder2000 that looks like wrong setting -> lower early and raise late must be set

**Comment by Darianna77** [comment]
Ist bei mir aber auch so. Beim Mähen auf jeden fall immer und beim ansähen manchmal auch. Ich hab aber immer bei jedem Gerät Früh senken und spät anheben an. Er hört dann immer nen Tick zu früh aus. Ich arbeite dann immer noch mal nach. Vielleicht wäre es anders wenn man auf den bahnen startet, das hab ich aber noch nicht getestet. Beim Start im Vorgewände bleibt dann jedenfalls immer was stehn :)

**Comment by Tensuko** [comment]
Also wie auf meinem Bild zu sehen, passt es wenn man im Vorgewende startet.
Mit dem mähen müssen wir uns anschauen was das ist.

**Comment by iljarogoff** [comment]
Ich vermute, CP orientiert sich am Kursende, aber auch bei scharfen Ecken nur am vorderen Anbaugerät. Gerade beim Mähen hat man ja vorne und hinten Geräte hängen.

**Comment by iljarogoff** [comment]
Das ist richtig, sind 2 unterschiedliche Dinge. Dennoch wird, sofern nur das vordere Anbaugerät in die Kalkulation einbezogen wird, das Hintere sowohl beim Kursende, als auch beim Turn zum falschen Zeitpunkt bzw. am falschen Ort aktiviert/deaktiviert. Ist es so, dass vorderes und hinteres Anbaugerät gleichzeitig geschaltet werden oder wird die Divergenz berücksichtigt?

**Comment by Tensuko** [comment]
Geräte anheben auf spät, Geräte absenken auf früh.
Es hat nichts mit turn zu tun!
