### ISSUE TITLE
[Question] Compatibility with dedicated servers

### ISSUE THREAD

**Issue by GiacomoC00** [Courseplay/Courseplay_FS22#1727]
Will it ever be compatible with NITRADO Dedicated Servers?

**Comment by Tensuko** [comment]
It is working on all kinds of Dedicated Server.

**Comment by GiacomoC00** [comment]
![Screenshot 2022-06-26 120502](https://user-images.githubusercontent.com/76397745/175809213-6197e41b-e282-4212-9e38-4f4e9fba7b48.png)
![Screenshot 2022-06-26 120415](https://user-images.githubusercontent.com/76397745/175809214-cd2efc43-5f96-4364-af75-c1064f6eba1b.png)
Can you confirm that I can ignore this error?

**Comment by Tensuko** [comment]
That is not an Error.

**Comment by GiacomoC00** [comment]
Ok, I thought it was an error because I can read "Issues 1". Anyway thank you very much.
![Screenshot 2022-06-26 125448](https://user-images.githubusercontent.com/76397745/175810866-5cf5e41c-b935-4df3-b41a-5565bd81e515.png)
