### ISSUE TITLE
Probleme beim wenden 

### ISSUE THREAD

**Issue by Goofy78** [Courseplay/Courseplay_FS22#173]
Ich habe das Problem, dass der nicht weit genug nach vorn fährt um vernünftig zu wenden.

![fsScreen_2021_12_27_15_54_32](https://user-images.githubusercontent.com/96694308/147484336-4e6f3fd7-2965-4283-9760-c5467585d9d5.png)
![fsScreen_2021_12_27_15_54_49](https://user-images.githubusercontent.com/96694308/147484337-65050a8f-4925-4aff-a6e1-e279c5780485.png)

Und das ist das was dann dabei rauskommt.

**Comment by Tensuko** [comment]
Duplicate #93 bitte vorher schauen ob schon etwas ähnliches da ist.
