### ISSUE TITLE
[BUG_SP] Autoloader übergibt nicht an AD

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS22#1735]
**Actual behavior**
Hallo Problem ist das nachdem CP den Hänger mit Ballenbeladen hat nicht mehr an AD übergibt und somit in einer Endlosschleife hängt. Eine CP Version ging es ohne Probleme. Sobald ich AD von Hand einschalte merkt er auch sofort das er voll ist und fährt Abladen. 

Ich habe nochmal ein zweiten Versuch gestartet mit einem anderen Mod der zum gleichen Ergebniss geführt hat.

![fsScreen_2022_07_02_12_57_44](https://user-images.githubusercontent.com/80832669/176997874-fb95fd69-c8c8-4bdf-99dc-f974c503e518.png)
![fsScreen_2022_07_02_11_53_31](https://user-images.githubusercontent.com/80832669/176997885-53005fc9-67f3-4a09-98b5-24cacad5e5fd.png)
![fsScreen_2022_07_02_12_57_34](https://user-images.githubusercontent.com/80832669/176997902-f423c2ce-f211-4661-b38f-32cac30a05c6.png)

Auf den Bildern ist zu sehen das der Hänger voll ist , aber Cp weiter Versucht Ballen aufzuladen

**Courseplay version**
Version used: 7.1.0.0

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9032778/log.txt)

2ter Versuch mit dem Transportpack von Achimobil:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9032870/log.txt)

**Map**
NDS 2022

**Vehicles/ implements involved**
Which vehicle or implement?
Selbst umgebauter HW 80

2ter Versuch mit dem Transportpack von Achimobil:

**Relevant script mods**
CP: 7.1.0.0
AD 2.0.0.7

**Comment by ct177mak** [comment]
Update AD auf Release 2.0.0.7 schon gemacht ?

**Comment by NeonRider1999** [comment]
Ja habe ich noch gemacht ändert aber leider nix

**Comment by Tensuko** [comment]
AutoLoad Script Problem, nicht CP.
