### ISSUE TITLE
[Feature] ETA of job

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/Courseplay_FS22#1736]
Hi Superawesome people!

**What is the problem this feature/enhancement solves?**
Its mostly a QOL thing, knowing a rough ETA for when a job is finished is nice

**Describe the solution you'd like**
Something like this?
![image](https://user-images.githubusercontent.com/65364380/176996155-b440dd58-5ebe-4617-9d60-ce1317e784fa.png)

**Describe alternatives you've considered**
I've looked thru the CP menu, and i cannot find something like this

**Additional context**

**Comment by Tensuko** [comment]
Already requested - duplicate
