### ISSUE TITLE
[BUG_MP]My friend is unable to join my newly created multiplayer game.

### ISSUE THREAD

**Issue by HandyBobNeedsHelpToo** [Courseplay/Courseplay_FS22#1737]
**Steps to reproduce**
Just create a new multiplayer game, haven't done any more than that.

**Actual behavior**
My mate tried to join my multiplayer game but it says the mod is unavailable so we haven't been able to play at all.

**Expected behavior**
Friend should be able to join as we both have the latest Courseplay zip added to the right folder. Mod works fine when I play alone, but as soon as my mate tries to join it tells him the mod is unavailable. It says ''Courseplay.devTeam Version 7.1.0.0 Unavailable''.

**Screenshots**
-

**Courseplay version**
Version used: v7.1.0.0

**Client Log**
-

**Server Log**
-

**Player on the server**
1, 2nd person can't join.

**Dedicated server or local hosted server**
Local Hosted.

**Map**
Elmcreek

**Vehicles/ implements involved**
No other mods.

**Relevant script mods**
None.

**Comment by Tensuko** [comment]
And where are the logfiles of you and your frined?

This is 100% sure not a CP bug....
So why don't you both check your logfiles and see whats wrong?

**Comment by Tensuko** [comment]
Closed due to inactivity.
I guess this is just a messy mod folder and sone something wrong, with ModHub Version should be no problem.
