### ISSUE TITLE
Beet/Potato harvester do not stop at 95% like combines.

### ISSUE THREAD

**Issue by Derethevil** [Courseplay/Courseplay_FS22#1739]
Problem:
Harvester continues harvesting even if past 95% already when set to self unload or sometimes randomly.
I figured this because of the self unload. It did happen that he lost a few beets, because he got too much momentum and picked up a few more before he were able to stop at 95%, what he usually would do. He just doesn't seem to do that if set to self unload on the nearby trailer.

Solution:
Set a hard stop at what percentage the harvester should stop regardless in which mode he is. So he stops harvesting at the set ammount, which would prevent it completely for goods that have a belt system, continuing to feed into the "basket", even if he already stopped harvesting.

Alternative:
Check if it is really the auto unload to nearby trailer setting itself which does not cause the AI to stop as it usually does if not set to auto unload at 95% and fix it, maybe even set it just a bit lower to prevent the problem.

**Comment by Tensuko** [comment]
I wouldn't be surprised if that is a modconflict -> logfile ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
