### ISSUE TITLE
When removed course from Vehicle, old Vehicle stays selected on Map even when entered an other Vehicle.

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#174]
I created the course for the tlxGeospread tool (Giants mod) and it is not deleted. I clicked on delete and the button disappears but the course doesn't. I have saved, closed the game and restarted but the course always stays there and the cancel button is not there.
Note. Gave me wrong and lower working width and set it to 15m minimum usable (mod modified by me).

![fsScreen_2021_12_27_16_18_14](https://user-images.githubusercontent.com/96330304/147485684-4699d61a-99ce-43b5-b8a1-ac48d4b01c03.png)
![fsScreen_2021_12_27_16_18_25](https://user-images.githubusercontent.com/96330304/147485696-27320788-fed2-4cda-b427-840366db3196.png)

**Comment by Tensuko** [comment]
Did you select the right tool ?
Logfile ?
Any Error ?
We have made a template so your fill in those questions and we can help you faster....

**Comment by Markus33-ITA** [comment]
Log no errors are displayed. it looks like a graphics problem in the game, a glitch. I have made several attempts with the same tool in the same save and no one else has appeared. In a previous backup is not displayed.
And I don't know what caused it. the only annoyance is that it is persistent.

**Comment by Markus33-ITA** [comment]
He did it again. I was about to start using the 51 thousand euro 9-meter weeder. I opened it all and it detected me working 2.5m (before I was cultivating with the cultivator at 2.5m. I canceled the course and changed medium). I canceled the course and the course remained in the field. I redid the course and it gave me the width at 8.9m.

**Comment by Tensuko** [comment]
ok so how and when did you stop the driver ?
When he was still on the way to the field or while on the field already ?

**Comment by Markus33-ITA** [comment]
I did the cultivation work on the 47 with the 2.5m cultivator. I stopped the course at the penultimate strip. the last overlapped the penultimate by a few mm. I deleted the course and went to some places where he had left something. I parked the vehicle and took the MF 3670. I rented the weeder and I went near field 49. I opened the various menus to create the course and I noticed the anomaly. was set at 2.5m. since I didn't want to click up to 9 meters, I decide to delete and do it by hand. I delete the course and the route remains imprinted on the map. there are no lines on the ground. Even reloading the save remains impressed on the map.

**Comment by Tensuko** [comment]
It might be the same reason as in #153
https://github.com/Courseplay/Courseplay_FS22/issues/153#issuecomment-1001762792

Try this. We need exact steps when this happens, sry but this can just happen in that early state, that some things hang up like that.
If you get the same again, pls Inform us with the steps again. Seems to be a hard one to find.

**Comment by Tensuko** [comment]
Just a quick question, you don't have 'show all course on map' on ?

**Comment by Markus33-ITA** [comment]
I always keep the entire track active from start to finish.

to try to understand how to replicate I did many tests. then I came to this conclusion.
I do a job and when I'm done I cancel the course. I change vehicle and I don't know how but the previous one remains selected and creates the route. I did the test with the medium and the 2.5m cultivator and the path that did not cancel is of that medium. now i don't understand why i get on a different vehicle and the previous one stays selected and takes the course on that one.

Now i don't know if there is any way to prevent this kind of error

**Comment by Tensuko** [comment]
> I do a job and when I'm done I cancel the course. I change vehicle and I don't know how but the previous one remains selected and creates the route.

actually, when you change the vehicle, it also should select the one you jumped in....

**Comment by Markus33-ITA** [comment]
in theory it is. I can't tell you where the bug is if Giants or if the CP. I use the CP 7.0.0.7. is to keep an eye on it and study it. if other similar anomalies occur, I answer under this topic

**Comment by Tensuko** [comment]
Found out what happens....
Indeed, only when you removed the course from the vehicle and then switch the vehicle, the selected vehicle on the map is the old one. If you get out of the menu and back in, then the new one is selected. Will have a look at this after our next Release Push.

**Comment by Markus33-ITA** [comment]
tomorrow I will do some targeted tests since now I know how to replicate it. I let you know what turns out

**Comment by schwyl** [comment]
I have kinda the same issue where when I select a vehicle on the World map and then click on the activities it automatically changes my selection on to the last active worker

**Comment by Markus33-ITA** [comment]
I did some tests.
- I create a course, start it, stop it with H, delete it in the menu
- I quit the menu with the ESC key, park the vehicle, get out, get on the new one
- I open the ESC menu, go to the workers menu, select the old vehicle for myself. sometimes you see an icon (vehicle) and sometimes you don't.
- same thing if the course ends regularly without using H.
- if I use TAB instead it works fine from what I've seen. on 5 tests it gave me no problems

**Comment by Markus33-ITA** [comment]
I would always have a half solution if it is feasible.
Add a new button to delete all courses.
- clicking on the button activates a for loop to establish how many courses are generated and assigns an id and a status (0 or 1)
- the courses found with status 0 upon confirmation click on the popup are all deleted
- the courses found with status 1 are not touched and would be the active ones and those that will be active shortly when the worker reaches the field he has to work

**Comment by Tensuko** [comment]
Wow, thanks a lot for all the tests you did!

We will have an eye on this.
You may want to try the latest version too, we did some changes and maybe it prevents this from happening, if not we keep watch out for this.

**Comment by Markus33-ITA** [comment]
yes I try

**Comment by Markus33-ITA** [comment]
I did some tests. I used the stubble chopper and cultivator. Going up and down in different vehicles does not show the bug. the selected vehicle is the correct one. if anyone else wants to try, they get more feedback

**Comment by Markus33-ITA** [comment]
since others do not intervene and I never come back, I close the topic
