### ISSUE TITLE
[Question] Baling Straw, the baler stops to harsh

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#1749]
if i bale straw that baler is stopping to harsh and runs a bit over the swath, letting some straw on the ground.
Is it possible to improve that it is slowing down like in grass? theres perfect

![image](https://user-images.githubusercontent.com/8066324/177393050-436085b5-27f9-4355-9143-b2fb03579a3c.png)

Edit: i just saw it only happens if much material is on the swath, if you have small swaths its working

**Comment by Tensuko** [comment]
I have tried that out and found no Issue with this.
Might be a mod.
https://github.com/Courseplay/Courseplay_FS22/issues/1730
