### ISSUE TITLE
blocked by object error

### ISSUE THREAD

**Issue by FarmingMartin** [Courseplay/Courseplay_FS22#1754]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
ploughing field

**Actual behavior**
tractor stops showing "blocked by object error"

**Expected behavior**
plough field

**Screenshots**
![Screenshot (100)](https://user-images.githubusercontent.com/108955450/178062476-86dd56a6-7ab0-491c-9246-ec7643fa4026.png)

**Courseplay version**
7.1.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Calmsden

**Vehicles/ implements involved**
Ecomat plough base game
Ford TW35  Kings Mod

**Relevant script mods**
 Autodrive

**Comment by FarmingMartin** [comment]
Just rolled back to version7.0.1.15 to get it to work.
see screenshot below
![Screenshot (101)](https://user-images.githubusercontent.com/108955450/178068653-5df468b8-b996-4b75-9b4f-971c1582eab1.png)


All updates after  version 7.0.1.15 give same error.

**Comment by Tensuko** [comment]
Mod Issue, not fs22 collission standard.
Not a CP problem.

**Comment by FarmingMartin** [comment]
Hi thanks, but why does it work on version 7.0.1.15 but not after if it's a mod error and not CP?I am sorry but I don't understand.Sent from my Galaxy
-------- Original message --------From: Tensuko ***@***.***> Date: 09/07/2022  04:41  (GMT+00:00) To: Courseplay/Courseplay_FS22 ***@***.***> Cc: FarmingMartin ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS22] blocked by object error (Issue #1754) 
Mod Issue, not fs22 collission standard.
Not a CP problem.

**Comment by Tritura2** [comment]
Because there were no collision detection in .15 and older for tractors.
With .16 they implemented it and till 7.1.0.0 it was improved and with vanilla everything works fine. Otherwise there would be a lot more bug reports about this problem. When there are reports, there is always a mod involved.

try with a vanilla tractor and you’ll see that this will work without problem.

**Comment by FarmingMartin** [comment]
Hi thanks for the explanation, I now understand why it happens. It also explains why it did not effect another tractor which was working in another field.I will have to swap the problem mod with another Thanks againSent from my Galaxy
-------- Original message --------From: Tritura2 ***@***.***> Date: 09/07/2022  13:49  (GMT+00:00) To: Courseplay/Courseplay_FS22 ***@***.***> Cc: FarmingMartin ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS22] blocked by object error (Issue #1754) 

Because there were no collision detection in .15 and older for tractors.

With .16 they implemented it and till 7.1.0.0 it was improved and with vanilla everything works fine. Otherwise there would be a lot more bug reports about this problem. When there are reports, there is always a mod involved.

try with a vanilla tractor and you’ll see that this will work without problem.
