### ISSUE TITLE
[Question] stone picker issue(maybe) autodrive

### ISSUE THREAD

**Issue by shadow250** [Courseplay/Courseplay_FS22#1756]
i set up a course to pick up stones i used the same settings as the forage wagon as the stone picker works almost the same so the course mostly works except when the picker is full it just stops and says it needs to be unloaded instead of going to the unload course if i click the autodrive power button it does another loop and stops after the picker is full again. im not sure if its an autodrive or courseplay thing so i posted this on the autodrive github too

**Comment by Tensuko** [comment]
You need the correct AD settings.

**Comment by shadow250** [comment]
would you please tell me what they are if you know its not in the manual.

**Comment by schwiti6190** [comment]
@shadow250 You will have to ask the AD devs or the community in their discord https://github.com/Stephan-S/FS22_AutoDrive , as we are not sure how this works on their end :)
