### ISSUE TITLE
[BUG_MP] Synchronization stuck on joining

### ISSUE THREAD

**Issue by TroubledHam** [Courseplay/Courseplay_FS22#1759]
Added Courseplay shortly after it went on Modhub, played with it on server with no detectable issues until on loading in another day my friend started getting stuck on synchronization.

He did manage to connect after I sold all vehicles and implements.
After that I started selling a few at a time to try tonarrow it down to specific vehicles, but did not find any specific broken vehicle(s) before having to stop for the day.

**Steps to reproduce**
No clue, issue presented itself suddenly on resuming another day.

**Actual behavior**
Game fails to finish synchronising with players.

**Expected behavior**
Synchronization finishes and player is able to join.

Courseplay Version: 7.1.0.0

**Logs**
https://pastebin.com/eA8Mqqmg

Host [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9095981/log.txt)

**Players on the server**
2

**Dedicated server or local hosted server**
Local

**Map**
Elk Mountain, Wyoming (slight personal edit to increase snow free areas, removed BGA)

**Vehicles/ implements involved**
Not applicable(?), happens on joining server.
Can provide list of all currently owned if needed.

**Relevant script mods**
Have many, unsure how relevant as it worked without apparent issue at first.

**Comment by Tensuko** [comment]
And why do you think its Courseplay ?
There is no Error from Courseplay in both logs, but callstacks from other mods.
Sometimes, patient is the key (and a clean logfile).

Not a CP Issue.

**Comment by TroubledHam** [comment]
I suppose you could be right but I should probably mention the one important thing I forgot in the original summary is this from the client log:

2022-07-12 19:47 Error: Running LUA method 'packetReceived'.
C:/Users/SIMAS/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/parameters/AIParameterSettingList.lua:303: attempt to perform arithmetic on local 'value' (a nil value)


This is what put me onto Courseplay as the issue, along with the fact it connects fine without it.
