### ISSUE TITLE
[Question] Windrower And Foragewagon 

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/Courseplay_FS22#176]
I'm saving CP for collecting straw with the windrowers.
So, how do I collect the straw with the same CP record as the loading wagon and deliver it to the unloading point?

I wanted to add a picture to the topic, but I don't know where to add it. I found it... Continue, Release....
![fsScreen_2021_12_26_21_46_45](https://user-images.githubusercontent.com/23352267/147488650-97461014-a0cc-4fcf-9c32-b4602e59c892.png)
.

**Comment by SavageCDN** [comment]
I tried this however I could not get a CP field course working with the tractor and loading wagon.  I only got options for pickup and delivery.  Perhaps CP sees loading wagons as just regular trailers?

**Comment by Tensuko** [comment]
Loading Wagons are not implemented yet.

**Comment by huseyinsayar** [comment]
thanks for the answer.
Waiting Impatiently.
