### ISSUE TITLE
[Question] Bunker levelling

### ISSUE THREAD

**Issue by kwguk** [Courseplay/Courseplay_FS22#1760]
In the FS19 version of CP there was the brilliant ability to set a course to level and compact bunkers, I cant find an option in FS22 CP or AD come to think of it.

Simple question...how do you do the same in FS 22?

**Comment by Tritura2** [comment]
A little search would have give the answer. ;) 
#1453 
#552 
#1644

**Comment by Tritura2** [comment]
And a little bit more obvious:

![570610D5-7E0A-404B-8902-51027E7D70D5](https://user-images.githubusercontent.com/37582657/178666628-9ae3a55b-f25e-4b79-a991-6cbc87268f4c.jpeg)
