### ISSUE TITLE
[BUG_SP] Arcusin Forstack 8.12 klappt nach bei voll zusammen

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#1761]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Per Wickeln/Sammeln Ballen auf einem Feld sammeln lassaen mit dem Forstack 8.12

**Actual behavior**
Nach dem der CP Fahrer 3 Ballen gesammelt hat klappt dieser den Arcusin in den Transport Modus

**Expected behavior**
Er entlädt die 3 Ballen nach dem Sammeln und sammelt dann weiter Ballen 

**Screenshots**
![image](https://user-images.githubusercontent.com/78980660/178750384-36296e83-12cf-4a28-bba4-3450b168ffc4.png)

![image](https://user-images.githubusercontent.com/78980660/178750084-1caed21c-b7c6-48ae-b708-69a314a418e8.png)
![image](https://user-images.githubusercontent.com/78980660/178749979-97933023-1b5d-4c7a-b60c-14fc826f4b69.png)

**Courseplay version**
Version used: 7.1.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9102785/log.txt)

**Map**
Zdziechow 

**Vehicles/ implements involved**
Arcusin Forstack 8.12

**Relevant script mods**
Autodrive

**Comment by 0scarZulu** [comment]
Fehler besteht leider nach wie vor

**Comment by SisSim** [comment]
Hi, der fehler das er zusammenklappt ist behoben so wie es aussieht. 
Jetzt ist noch das problem, das er zwar die Ballen absetzt, auf den Boden, aber er entläd diese Ballen nicht.

**Comment by Tensuko** [comment]
Das scheint ein Problem des Tools oder generell es Spiels zu sein.
Da können wir leider nichts machen. Won't fix, gamebug.
