### ISSUE TITLE
[Feature] Improve equipment maneuvers in vineyards and olive groves

### ISSUE THREAD

**Issue by etrigo1** [Courseplay/Courseplay_FS22#1766]
When we put equipment to work in vineyards and olive groves, they need a large area to perform the maneuver. The CP workers should be able to reverse gear so that the maneuvering area is smaller, avoiding a great waste of land just for that.

![image](https://user-images.githubusercontent.com/37108041/179295524-53a28e0f-6bbb-4b9c-9a0c-cefecd558b56.png)

The harvesting machine has a great turning capacity, it would not need such a large area.
5 to 6 meters beyond the end of the field with a little reverse gear the machine can turn as well as most implements.

I also tried to skip one of the queues ( queue yes queue no ) and even so the maneuvering area is large

![image](https://user-images.githubusercontent.com/37108041/179296756-3c3969b4-08df-44ff-bc21-5cf305ec4718.png)

**Comment by Tensuko** [comment]
The "big turning" is needed get a proper aligning in the next row, else the FS Physics plays ping pong with the harvester.
We did that for a reason.
A reverse would need a reverse part at a specific position of the turn, wich is not implemented in any way as turns gets generated and are not programmed in a fix way.

A try with the pathfinder is planed, but other than that, there is not much that we can do or is planed.
We did write it in the manual that enoush space is needed.
