### ISSUE TITLE
Warning if driver stops unexpectantly 

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#1769]
**What is the problem this feature/enhancement solves?**

If a driver hits a tree on the edge of the field it will disable courseplay. this is ok because there should not be a tree.

**Describe the solution you'd like**

I would like to get a warning if a driver stops unexpectantly ( hits a tree that should not be there)

**Describe alternatives you've considered**

**Additional context**

I almost always use many courseplay drivers at the same time. Because of this really like the new "info display" warning me when a driver has finished a task. If there could be a warning if a driver stops unexpectantly this would be very nice. 

Thanks for your hard work.

![Farming Simulator 22 Screenshot 2022 07 16 - 19 46 25 10](https://user-images.githubusercontent.com/85753728/179366824-75850bed-7d22-431c-abcc-4ab89d5c653c.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9126319/log.txt)

**Comment by Tensuko** [comment]
Fixed in next Release.
