### ISSUE TITLE
[BUG_SP] cotton harvest 

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#177]
**Steps to reproduce**
start CP (i downloand last ver in here page. Delete all CP in mod and savegame

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
normal start CP 

**Screenshots**
![mod map](https://user-images.githubusercontent.com/96631209/147488325-92af2d0b-46bc-4b45-a882-7efb15f32916.png)

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7780879/log.txt)

**Map**
Papenburg Map v1.0.0.2 FS22

**Vehicles/ implements involved**
Mod yes and test with only CP v 7.0.0.7

**Relevant script mods**
yes error and only CP and too error

**Comment by Manyak007** [comment]
problem only with cotton harvest normal harvest on grain,corn work 

grass-cutter does not want to create a CP route idk why

**Comment by Tensuko** [comment]
> **Vehicles/ implements involved**
> Mod yes and test with only CP v 7.0.0.7

This doesn't tell us wich vehicle you used...

**Comment by Manyak007** [comment]
> > ****
> > Zapojená **vozidla/nástroje** Mod ano a test pouze s CP v 7.0.0.7
> 
> To nám neříká, jaké vozidlo jste použili...

with mod CP 690 John Deer vanilla cotton harvest withoutsame harvest

**Comment by Tensuko** [comment]
Pls try 7.0.0.8 
Reopen if Error persists.

**Comment by Manyak007** [comment]
is fix with new version
