### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by judg393** [Courseplay/Courseplay_FS22#1771]
Issue 

When playing frequently with course play I find using the mouse a really immersion breaking experience and think that keybinds could be a great alternative. 

**Describe the solution you'd like**

 I'd love additional keybinds to skip through  start points, maybe to show and hide the course (eye function) 

I don't want this to appear in the f1 menu (although I guess this could be toggleable as I think your current option is) 

**Describe alternatives you've considered**
I mean I can use the mouse and I wouldn't have ant that removed but the option to use a keybind is something I'd prefer I know this may be personal opinion but i mightn't be the only one 

**Additional context**

Other mods (like AD) seem to have built in a large amount of key binds that means I don't need to use the mouse to use the mod would be awesome to see CP follow suite if possible 

Thank you for considering this request and apologies if I'm asking for a huge amount of work I really have no idea about coding like this. 

Once again CP is one of the best mods out their imo and congrats for getting to modhub so quickly!

**Comment by Tensuko** [comment]
We will not add any more keybinds as the game is flooded with keybinds already, sry.

**Comment by judg393** [comment]
Ok well thanks for speedy reply it's a shame but I guess it means there's more to conflict/go wrong
