### ISSUE TITLE
[Info] ein recht grosses DANKESEHR ans CP Team

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1776]
ein recht grosses **_DANKESEHR_** ans CP Team,
für den einbau des ingame-editors
nochmals **DANKE**
nun muss ich nichtmehr für einige Kleinigkeiten immer ins notepad++
lg
andreas

**Comment by Tritura2** [comment]
You guys are absolutely amazing. You are doing a fantastic job providing us with such an awesome mod and despite some frustrating comments, are still open to suggestions and new ideas from us. FS wouldn't be as good without you guys. :)

**Comment by Ulanawius** [comment]
I totally agree!!!! Amazing work :-)
