### ISSUE TITLE
[enhancement] More Bale Types for Balecollet Mode

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#1777]
Hello,

woud be nice to have more bale types to choose in the "Bale Collecting Mode", like Hay and Grass, not only wraped and unwraped.

![image](https://user-images.githubusercontent.com/47928255/179507133-70c3d9a9-bfa5-4fcf-bf16-0edf0ed48bb9.png)

TY

**Comment by Tensuko** [comment]
Sry aber wofür?
Grass und Heu auf dem gleichen Feld ergibt für mich keinen Sinn.
Mit Ballentyp ist auch ausschließlich nur der Ballen gewickelt oder ungewickelt gemeint, nicht Fruchtart.

**Comment by blubstar86** [comment]
Habe am Feldrand noch andere Ballen liegen, von einem anderen Feld,  die eben nicht gesammelt werden sollten.

**Comment by Tensuko** [comment]
Sry aber das sehe ich eher als Einzelfall und keine all zu sinvolle Ergänzung.
Wie gesagt, es geht rein um gewickelt oder ungewickelt, so müssten wir noch mehr Filter, in dem Fall fillType hinzufügen, am Ende sogar noch fillType und gewickelt/ungewickelt kombinieren mit noch mehr Möglichkeiten.
