### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by devilboy123** [Courseplay/Courseplay_FS22#1782]
when iam try to set the wrapper off on collecting and wrapper mode it keep st AI work has stopped working unexpectedly tank is full 
![fsScreen_2022_07_19_21_30_23](https://user-images.githubusercontent.com/13384366/179843253-a413947a-c2b9-4438-8b3f-fd6bb0ef8341.png)

**Comment by regs1980** [comment]
Reduce front weight

**Comment by Tensuko** [comment]
Why no use the template ???
Not even a headline.....
Try it again.
