### ISSUE TITLE
[BUG_SP]Ballenpressen mit Quaderballenpresse

### ISSUE THREAD

**Issue by Gram90** [Courseplay/Courseplay_FS22#1783]
Moin,

ich ahbe folgendes Problem beim Ballen pressen.

Ich übernehme den CP Course des Dreschers und lade den in den Traktor zum Ballen pressen.

Wenn der Traktor jetzt in der Ecke ankommt, bleibt er in den meisten Fällen stehen, statt um die Ecke zu fahren und weiter zu pressen.

Getestet mit Standort Traktor und Mod Traktor, getestet mit unterschiedlichen Quaderballen pressen.

Liegt das Problem an mir oder an CP?

Es geht um die Uhrzeit 22:51:26 in der LOG

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9144680/log.txt)
![20220719224009_1](https://user-images.githubusercontent.com/49372643/179846868-9c840f2f-b45f-4a60-9a09-06080339b57c.jpg)

Ich wünsche einen schönen Abend

**Comment by regs1980** [comment]
Der hintere Ballen blockiert das ganze Gespann, da du scharfe Ecken eingestellt hast beim Drescherkurs. 
Am besten nach dem Dreschen mit dem Schwader vorher einmal darüber, mit weichen Ecken.

**Comment by Tensuko** [comment]
So ist es, ist auch bekannt und sind wir ehrlich ich kenne keinen im RL der so die Ecke mit Stroh aufsammelt.

Ja wir müssen uns das anschauen, aber wie gesagt es ist bekannt.

**Comment by Tritura2** [comment]
Workaround:

Den Kurs vom Drescher 2x mal speichern. Anschließend kannst du den 2. mit dem neuen Kurseditor bearbeiten und aus den schrafen Ecken runde/weiche machen, sodass die Presse nicht zurücksetzen muss. Sofern du das Feld nur einmalig mit exakt diesem Drescherkurs bearbeiten willst und im nächsten jahr nicht wieder, reicht natürlich einmaliges speichern und bearbeiten des Kurses.

**Comment by Tensuko** [comment]
Genau, mit dem Kurseditor ist das auch einfach an zu passen :)
