### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/Courseplay_FS22#1788]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Diese zwei mods im modsordner 

These two mods in the mods folder 

https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.1.0.1
https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019

bekommt man diesen fehler

you get this error

Error: Running LUA method 'draw'.
G:/07 Landwirtschaftssimulatoren/Landwirtschaftssimulator 22/mods_Test/FS22_AutoDrive/scripts/Editor/EditorGUI.lua:132: attempt to index a nil value

**Actual behavior**
A clear and concise description of what happen.

Sobald ich bei CP den Editor aufmache bekomme ich von AD folgenden Fehler siehe oben

As soon as I open the editor at CP I get the following error from AD see above

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.1.0.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9156186/log.txt)

**Map**
Map played on.

Whether original or modmap

Egal ob Original oder modmap

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

data/vehicles/valtra/gSeries/gSeries

data/vehicles/horsch/terrano3FX/terrano3FX

**Relevant script mods**
Mods like Autodrive or VCA and so on.

No other mods besides CP and AD.

Keine weiteren mods ausser CP und AD.

Also already reported to AD

Bei AD auch schon gemeldet

https://github.com/Stephan-S/FS22_AutoDrive/issues/630

MFG Mannie313

**Comment by Tensuko** [comment]
Das ist ein AD Fehler, nicht CP.
