### ISSUE TITLE
Bale wrapper not starting says "needs to be unloaded"[BUG_MP]

### ISSUE THREAD

**Issue by csteinsv** [Courseplay/Courseplay_FS22#1789]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Map: Nebraska x 4. After some play time 2-3 seasons or maybe problem with some update.
Any tractor and the 55k bale wrapper that comes std with the game. LOG seems to indicate that 
courseplay mistakes the wrapper for a bale loader. But it used to work perfectly. 
If it helps when the problem started i could buy a new wrapper  and tractor from store and that would work once.
Now that does not help either.

**Actual behavior**
Drive to field and open CP, chose the wrap/collect bales, select the right field and target pos. press start job.
Drives a few "random" laps on the field and then says "Needs to be unloaded"

**Expected behavior**
Locate bales and start wrapping.

**Screenshots**

**Courseplay version**
Version used: v7.1.0.1

**Client Log**
2022-07-21 00:36 :28 [dbg20 lp3960] Magnum 400 PowerDrive/660: Magnum 400 PowerDrive/660: getting working width...
2022-07-21 00:36 :28 [dbg20 lp3960] Magnum 400 PowerDrive/660: Magnum 400 PowerDrive/660: has NO work areas
2022-07-21 00:36 :28 [dbg20 lp3960] SW 4014/-: SW 4014/-: getting working width...
2022-07-21 00:36 :28 [dbg20 lp3960] SW 4014/-: SW 4014/-: has NO work areas
2022-07-21 00:36 :28 [dbg20 lp3960] SW 4014/-: SW 4014/-: could not determine working width
2022-07-21 00:36 :28 [dbg20 lp3960] SW 4014/-: SW 4014/-: using configured tool offset of -2.5, resulting left/right is -2.5/-2.5.
2022-07-21 00:36 :28 [dbg20 lp3960] Magnum 400 PowerDrive/660: Magnum 400 PowerDrive/660: working width is 0.0, left -2.5, right -2.5.
2022-07-21 00:36 :28 [dbg20 lp3960] Magnum 400 PowerDrive/660: Magnum 400 PowerDrive/660: calculated tool offset is -2.5.

**Server Log**
:39 [dbg4 lp778446] Unknown: SEARCHING_FOR_NEXT_BALE: Bale type selected: 1
:39 [info lp778446] Maxxum CVX 115/2268: SEARCHING_FOR_NEXT_BALE: Starting bale collect/wrap
:39 [info lp778446] Maxxum CVX 115/2268: SEARCHING_FOR_NEXT_BALE:  - SW 4014/-
:40 [info lp778447] Maxxum CVX 115/2268: WAITING_FOR_PATHFINDER: Bale loader is full, stopping job.
:57 [dbg13 lp785759] appendEndingTurnCourse: dzVehicleAtTurnEnd: 0.0, dzWorkStart: -4.3, extra 3.0)

**Player on the server**
1 to 4 

**Dedicated server or local hosted server**
Dedicated server yes/no ? Local dedicated server.

**Map**
FS22_Green_Valley_Nebraska_4X

**Vehicles/ implements involved**
ANY one has same error
Mod Moth modded and std tractors 
**Relevant script mods**
Using autodrive and courseplay latest versions not in beta.

**Comment by Tensuko** [comment]
This is not a logfile this is just a copy and paste part...
I want a full logfile.

Also what bale wrapper.

**Comment by csteinsv** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9158680/log.txt)
[logfromserver.txt](https://github.com/Courseplay/Courseplay_FS22/files/9158685/logfromserver.txt)

The Wrapper is the Kuhn SW4014

**Comment by alexx2104** [comment]
Today I got the same problem with bale wrapper. I play in SP.

**Comment by alexx2104** [comment]
Here is a log with active device debugging

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9159739/log.txt)

**Comment by kwguk** [comment]
I had the same problem. So i tried switching back to version7.1.0.0 and the problem was no more. It seems the problem occurs with the latest version.

**Comment by Tensuko** [comment]
Yea I have an Idea whats happening, have to figure that out.

**Comment by kwguk** [comment]
For what its worth, i've tried using various 'autoload' bale trailers instead of the stacker and neither CP or AD seem to like that.  They both work well with the stacker to collect bales and then deliver.
