### ISSUE TITLE
[BUG_SP] CP Ver. 7.0.0.7 Helper would not start, exits with finished message

### ISSUE THREAD

**Issue by TheSoldier91** [Courseplay/Courseplay_FS22#179]
**Steps to reproduce**
Generate a course with 2 headlands, clockwise or counterclockwise, start at headland
working width 2.5m

**Actual behavior**
After generating a course the helper will drive to the startpoint of the cours then exits with finished message

**Expected behavior**
Work at the generated course, headland first

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7781187/log.txt)

**Map**
Haut Beyleron, Singleplayer

**Vehicles/ implements involved**
Vanilla Tractor, MF 3670 with standard implement

**Relevant script mods**
AutoDrive, VCA, dont know wich of the mods are using scripts, see the log

**Comment by Tensuko** [comment]
Is the field even ready to be seeded with that seeder ?

**Comment by TheSoldier91** [comment]
Field is ready, started a new savegame

**Comment by TheSoldier91** [comment]
Tested it again in a new save without any mods except CP, now it works fine.

Got to figure out which mod is causing the problems..

**Comment by Tensuko** [comment]
Okay, thanks for your feedback. If found out, leave a msg.

**Comment by AlexStephenLytton** [comment]
Sieht aus als wäre AIVE das Problem sobald in den Settings Alternativer Helfer auf "An" steht ... sobald er auf "Aus" steht, funktioniert Courseplay wieder einwandfrei
