### ISSUE TITLE
Bale Collection not working in Multimap map

### ISSUE THREAD

**Issue by aesguitar** [Courseplay/Courseplay_FS22#1796]
CP Version 7.1.0.1
Autodrive Version 2.0.0.7

Steps to reproduce:
Mow, Ted, Row, and Bale (large squares) the grass in field 23 using non-modded vehicles/implements.
Drive one the the automatic bale stackers (not an autoload trailer) on to the field with bales
Start the CP Bale Collection task
Immediately get the "Finished Work" display on the HUD

I have tested this in different maps to make sure the feature works with my mod set at all and it does work on other maps as expected.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9167683/log.txt)
<img width="959" alt="Screenshot 2022-07-22 082054" src="https://user-images.githubusercontent.com/6676966/180438882-641300e5-26c1-415c-bd4a-766aa79504fd.png">

**Comment by Tensuko** [comment]
Are those bales vanilla one?

They look so big on the screenshots.

**Comment by aesguitar** [comment]
As far as I can tell. They are 240cm Hay Square Bales. They fit on that stacker and that is a vanilla stacker.

**Comment by Tensuko** [comment]
Does it work when you create a custom field arround your field ?

**Comment by aesguitar** [comment]
It does not.

**Comment by Tensuko** [comment]
Then it is some mod or map Issue and got nothing to do with cp.
