### ISSUE TITLE
[Enhancement] Arbeitslicht Häcksler

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/Courseplay_FS22#1797]
Ist das normal, das das Arbeitslicht am Häckslerrohr ausgeht, sobald ich den CP einschalte.
Die zwei äußeren Lichter links und rechts siehe Bild. Es ist der Standardhäcksler
![fsScreen_2022_07_22_18_08_34](https://user-images.githubusercontent.com/25564472/180597855-c9fdaf04-8f13-4819-8f18-322126eccb5f.png)
e

**Comment by rohne83** [comment]
sollte dann möglichst auch gleich so gemacht werden, dass es auch bei Dreschern und Rodern funktioniert (und ULWs wenn der Mode wiederkommt). Die bunkern zur Zeit auch noch ins Dunkel ab.

**Comment by schwiti6190** [comment]
@xerion8300 , @rohne83 Dies ist ein "Giants Bug", wenn man es so nennen will. Die Möglichkeit besteht, nur muss das in den Fahrzeugen xml richtig eingetragen sein, damit der richtige Light Status ausgewählt wird, so dass das Rohr Licht an gemacht wird.
Schön wäre es, wenn ihr euch an den Giants Support wenden könntet, da es bei deren Helfer genau so ist z.B. Class Jaguar 960.
Einzige alternative wäre es alles einzuschalten aber ob das nacher passt gerade bei Mods sei dahin gestellt.
