### ISSUE TITLE
Courseplay for FS22 v7.1.0.1 läuft bei mir nicht

### ISSUE THREAD

**Issue by FarmerMario** [Courseplay/Courseplay_FS22#1798]
Hallo,
Ich habe mal eine Frage.Bei mir läuft die aktuelle Version nicht.Obwohl diese im Mods Ordner ist.
Siehe Screenshot
![20220723171435_1](https://user-images.githubusercontent.com/98883983/180611557-15061a6d-72f7-4728-8aac-95fea5697a66.jpg)

Bei der Version 7.1.0.0 ist alles in Ordnung.
Woran liegt das?

mfg FarmerMario

**Comment by Tensuko** [comment]
Ja und wie wäre es mal mit einem logfile ?
Ich bin mir sehr sicher wenn ich das sehe das du was falsch gemacht hast....

**Comment by FarmerMario** [comment]
Hier meine log-Datei.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9175287/log.txt)

**Comment by Tensuko** [comment]
Du solltest dein LS Updaten
Version: 1.5.0.0 b17298

Und ich bin mir fast sicher, dass entweder deine alte LS Version heirfür verantwortlich ist, oder du die Datei falsch gezippt hast, was du gar nicht machen musst wenn du es hier runter lädst:
https://github.com/Courseplay/Courseplay_FS22/releases
Available mod: (Hash: 9d5cdc34b93c8eb9d8884af3541919e2) (Version: 7.1.0.1) FS22_Courseplay
Error: Unsupported mod description version in mod FS22_Courseplay

**Comment by FarmerMario** [comment]
Hallo Tensuko,
Danke für Deine Antwort.
Die LS Version war der Fehler.Ich hatte die alte Version geladen,weil ich gleich nach dem Update,Probleme hatte.
Aber wie es aussieht,ist im Momment alles OK.
Danke und lg FarmerMario

**Comment by Tensuko** [comment]
Ok super!
