### ISSUE TITLE
[BUG_SP] Sowing machine not sowing sometimes

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/Courseplay_FS22#180]
**Steps to reproduce**
Use a sowing machine and sit in another vehicle.

**Actual behavior**
Sowing machine does sometimes (it appears random) stop to sow, if you go back into vehicle, it continues as expected

**Expected behavior**
The sowing machine should work uninterrrupted

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/47073128/147495496-c7869cc6-cd8e-4db3-bb8e-ecc2e193fbb4.png)
![Screenshot (6)](https://user-images.githubusercontent.com/47073128/147495501-31b17b0e-43e8-49cc-919b-9241950897a5.png)

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7781213/log.txt)
Unfortunately i wasn't able to turn Debug Channels on
Edit: 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7781222/log.txt)
This log has debug channels on

**Map**
Map played on is the Elmcreek

**Vehicles/ implements involved**
Mod yes, it is the Horsch Pack, but it also happens with the standard sowing machines

**Relevant script mods**
Besides CP there is AutoDrive active

**Comment by Tensuko** [comment]
That is the ingame Horsch, right ?
Field doesn't matter I guess ?

**Comment by StefanBraun2001** [comment]
It is a Non ModHub. It happens on all fields. I noticed it happens more often when you have 2 sowing machines in use at the same time.

**Comment by Tensuko** [comment]
> I noticed it happens more often when you have 2 sowing machines in use at the same time.

Good hind, I try that one out.

**Comment by StefanBraun2001** [comment]
I'm testing it again on a savegame without any mods (except CP) and standard sowing machines to be absolutly certain this happens also with standard sowing machines.

**Comment by StefanBraun2001** [comment]
I'm currently unable to reproduce it with standard machines, but i am almost ceratin i had this issue once with the big Kinze Blue drive sowing machine.

**Comment by StefanBraun2001** [comment]
So, the final test results of my little test: Giants Helper does not have problems with the Horsch Sowing machines, sowing yourself does work as well, the CP-Helper does have this issue with all sowing machines, however, it appears more often with the Horsch ones and sometimes with the standard ones

**Comment by Tensuko** [comment]
ok I have a look.

**Comment by Tensuko** [comment]
Did you had 2 seeder running ?
I wasn't able to reproduce this...

**Comment by StefanBraun2001** [comment]
Yes, there was two Seeders active. One planted sunflower and the other planted "sorghumhirse"

**Comment by RealNeo80** [comment]
have the same in Elmcreek on field 32 with 7.0.0.10

![Sämschine_32](https://user-images.githubusercontent.com/8066324/147783722-737b5d92-4047-42af-adcc-e8462ce47fe9.png)

only 1 sowing machine active, planting barley
no channels on in the log ... but i haven´t supposed this to happen
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7794451/log.txt)

**Comment by Tensuko** [comment]
@RealNeo80 at the side of your fields it looks like the seeder is makeing no contact.
Could not find out whats happening yet, but I keep have a look at this...

**Comment by StefanBraun2001** [comment]
I don't really know since which version, but the issue does not happen again, i'm not able to reproduce it anymore.... Closed
