### ISSUE TITLE
[BUG_SP] Plow with no rotation skips odd/even lines

### ISSUE THREAD

**Issue by ZbynaM** [Courseplay/Courseplay_FS22#1803]
CP is not lowering tool in one direction when plowing with plow without rotation option.

It is related to rotation of plow. Vanilla plows are working as expected (on the same course), in every odd line it rotates plow to "rotated state" and lowers it.

But when plow does not have "rotated state" in every odd line it just run trough without actual plowing. And CP leaves plow in bugged state cause it cannot be lowered not even manually.

Plow "John Deere 2410" v1.2.0.0
CP v7.1.0.1
AD v2.0.0.7

![Untitled](https://user-images.githubusercontent.com/18121342/180648543-88fe6f6e-0c57-4cc5-947c-8f708f3a572f.png)

**Comment by Tensuko** [comment]
#1750
