### ISSUE TITLE
[BUG_SP]cotton harvester leaves course and quits (Callstack)

### ISSUE THREAD

**Issue by shadow250** [Courseplay/Courseplay_FS22#1804]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
have a course with 2 or 4 tools. runs ok till 3 rows to end of course
**Actual behavior**
harvester on right 1 or right2 leaves course and stops
**Expected behavior**
expected to follow course normally
**Screenshots**
![wrong turn](https://user-images.githubusercontent.com/17964517/180664669-ef5dca9e-4df4-4d3b-872c-b2a9db37a066.jpg)

**Courseplay version**
Version used: 7.1.0.1

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9176620/log.txt)

Map played on. no mans land

**Vehicles/ implements involved**
Which vehicle or implement? case stock cotton harvester
Mod yes/no ?no

**Relevant script mods**
Autodrive  installed but not active

**Comment by shadow250** [comment]
found tonight it does the same thing with the stock fendt vario and the stock bredal k165 i think its the same problem but if im wrong let me know.

**Comment by Tensuko** [comment]
Can't be a CP problem then or better said I have high doubts.
Else we would need a logfile from that one too.

**Comment by pvaiko** [comment]
It is a CP problem. @shadow250 do you have a screenshot where the entire temporary turn course is visible?

**Comment by shadow250** [comment]
![wrongturn2](https://user-images.githubusercontent.com/17964517/181023002-5d19dece-a04f-4bd1-8707-ce302530024c.jpg)
![wrongturn3](https://user-images.githubusercontent.com/17964517/181024326-5c33f8c9-e3a7-4bb2-b045-92a9b7841e01.jpg)
 i hope these are useful.

**Comment by Tensuko** [comment]
Its always near the startpoint and seems like always one headland?
Also 2 Vehicle per course ?

**Comment by shadow250** [comment]
that is an accurate observation, also always the right side of the course. and the cotton course did the same with 4 tools. both the right side tools messed up in the same spot.
