### ISSUE TITLE
[Question] CP HUD bei jedem Spielstart ausgeblendet 

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#1806]
Moin zusammen, ich habe das Problem, dass das CP HUD bei jedem Spielstart meines Savegames (ich spiele Singleplayer) ausgeblendet ist. Somit muss es jedes mal neu aktiviert werden. Ist dies das normale und korrekte Verhalten oder ist bei mir etwas "verstellt"?
Das Autodrive HUD bspw. ist immer sofort sichtbar ohne Eingriffe.

**Comment by Tensuko** [comment]
Das ist richtig so, ich verstehe aber oft das Problem daran nicht, du brauchst doch eh den Mauszeiger zum bedienen...
Mauszeiger einschalten und Hud auf machen ist das gleiche -> rechtsklick...
