### ISSUE TITLE
[BUG_SP]CP übergibt nicht an AD wenn Ballensammelwagen voll ist

### ISSUE THREAD

**Issue by Holzotte** [Courseplay/Courseplay_FS22#1812]
Wenn der Ballensammelwagen mit  Autoloadfunktion voll ist, übergibt CP nicht an AD, sondern fährt weiter den Kurs bis zum Endpunkt ab und bleibt dann stehen. 

CP/AD sind auf dem Aktuellen Stand

**Comment by Tensuko** [comment]
Autoload mod auf aktuellem stand ? <- das da
Kein logfile, kein template benutzt.
