### ISSUE TITLE
[BUG_SP] not plowing corectly

### ISSUE THREAD

**Issue by Leon83858** [Courseplay/Courseplay_FS22#1815]
**Steps to reproduce**
![image](https://user-images.githubusercontent.com/23504996/181306879-2b4f0c8c-6666-45e5-89ae-ef88cf7a819b.png)
![image](https://user-images.githubusercontent.com/23504996/181306971-dbe6bf1b-b981-46a8-b771-6872df0c8e22.png)

**Actual behavior**
driver is not holding the way he shuld
![image](https://user-images.githubusercontent.com/23504996/181306747-80f5a479-b939-4788-8921-89a3dc7b337e.png)

**Expected behavior**
holding the plow correctly 

**Courseplay version**
Version used: 7.1.0.1

**Map**
haut beyleron

**Vehicles/ implements involved**
![image](https://user-images.githubusercontent.com/23504996/181307630-a7e3dae7-5ec6-4b0c-a9d1-3fccb84eb879.png)
![image](https://user-images.githubusercontent.com/23504996/181307670-8b31ae18-4cf6-4149-a520-d2d77ee6d18e.png)

**Comment by Tensuko** [comment]
If Headland -> working as intended

**Comment by Tensuko** [comment]
Funktioniert noch so wie es soll, im Vorgewende ist das Absicht.
