### ISSUE TITLE
[BUG_SP] Harvester stops behind trailer when attempting to auto unload

### ISSUE THREAD

**Issue by sam-2401** [Courseplay/Courseplay_FS22#1816]
**Steps to reproduce**
Park Rudolph TDK301 RA next to field with the field to its **right** side. Harvest with Fendt Ideal 8T and PowerFlow 40ft - just to be sure, but I assume the header is irrelevant. Activate auto unload for the harvester and start a course.

**Actual behavior**
The harvester approaches the trailer to unload, but stops about 2m behind it. I have to push the trailer back or - if I left it without a tractor - stop the helper and move the harvester forward manually. This only happens when approaching the trailer from behind. If I park it with the field to its left, the harvester will approach it from the front instead of the back, stop above it and unload correctly.

**Expected behavior**
The harvester should drive 2-3m more meters before stopping.

**Screenshots**
Reacreated for this bug report.
Actual behavior
![20220728043040_1](https://user-images.githubusercontent.com/72743108/181407928-12893186-f7f0-44c4-8a9f-38ba7e992a5a.jpg)
Expected behavior
![20220728043032_1](https://user-images.githubusercontent.com/72743108/181408051-515e806d-1071-4b84-bd4e-66c5cc6b61cd.jpg)
Approaching from front
![20220728043112_1](https://user-images.githubusercontent.com/72743108/181408106-82d9cdcb-9664-430e-895b-da28e2ca4469.jpg)

**Courseplay version**
Version used: 7.1.0.1

**Log**
[[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9204803/log.txt)](https://gist.github.com/sam-2401/9c4a5e0d1378cb15f27da727240bd0b1)
I finished harvesting for this year, but will add a log with debug channels enabled after the next harvest season.

**Map**
Elmcreek

**Vehicles/ implements involved**
Rudolph TDK301 RA
Fendt Ideal 8T
PowerFlow 40ft
all vanilla

**Relevant script mods**
none

EDIT: moved log to Gist

**Comment by Tensuko** [comment]
And what do you think we can see on those dark screenshots?
Debug was on ?

**Comment by sam-2401** [comment]
Those screenshots look just fine on my screen, but maybe these show the issue better.
![20220729071844_1](https://user-images.githubusercontent.com/72743108/181689343-76cadd3b-3889-4a96-a5ab-89717738c2e9.jpg)
![20220729073017_1](https://user-images.githubusercontent.com/72743108/181689333-f74985f6-a86f-469c-a724-1bf0195c2617.jpg)
![20220729071907_1](https://user-images.githubusercontent.com/72743108/181689349-50cca58b-16c7-467e-bba6-ba1e88916232.jpg)
https://gist.github.com/sam-2401/b83c7f3893d7d05a2f3b538aac6adc67

**Comment by pvaiko** [comment]
This should now be fixed, really...
