### ISSUE TITLE
John Deere 4940 spreader false positive object detection

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#1817]
the JD 4940 with spreader box gets a false positive of there being an object in the way when turning. I believe the mods is from custom modding, i can provide the zip if needed. I have no observed this with any other vehicles, but it is consistent with this one. 
![20220727190328_1](https://user-images.githubusercontent.com/5993529/181419485-238a0c6b-8128-447d-87c9-a6f7db63dc9f.jpg)

![20220726220401_1](https://user-images.githubusercontent.com/5993529/181419530-c6fafab9-f8a0-4f4c-85eb-69055ab64bb5.jpg)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9205296/log.txt)

**Comment by Tensuko** [comment]
Mod Issue, they dont stick to giants standard for colission.
