### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by gigilal** [Courseplay/Courseplay_FS22#182]
Hi,

I think its really frustrating that you need to go into the ESC menu to work with courseplay. Is there any other way to simplify this?

It took less time and was really easy when you could just rightclick and get the menu up while inside the tractor :)

**Comment by Redster999** [comment]
I know Tensuko wrote somewhere else in this forum that they were working on a smaller HUD. Along with bugfixing the already released cp I think they are doing something about this

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ
