### ISSUE TITLE
Mehrere Helfer auf einem Feld Problem

### ISSUE THREAD

**Issue by matthiasjost76** [Courseplay/Courseplay_FS22#1820]
Hi,
vielen Dank für Eure super Arbeit und den sehr gut gelungenen Mod.
Ich habe vor Kurzem ein recht großes Feld mit drei Steinesammlern bearbeitet. Das funktioniert auch gut mit der Zuteilung Links / Mitte / Rechts. 
Ab und zu kommen sich die Helfer in die Quere oder ich muss sie aus irgendwelchen Gründen stoppen und sie dann wieder losschicken. Leider merken sie sich ihre Zuordnung zur jeweiligen Fahrspur nicht. 
Ich starte den Job dann neu mit der richtigen Spur und ab dem nahesten Wegpunkt...das geht.
Ist vermutlich aber ein nicht gewünschtes Verhalten...sie sollten auf der richtigen Spur weiterfahren, oder?

Grüße,
Matthias

**Comment by Tensuko** [comment]
Template benutzen....
Ich kenne weder deine Version, noch habe ich jetzt ein logfile von dir.
Auch weis ich nicht wann und warum sie anhalten.
Stellst du die Spur ein, fahren sie auch auf der Spur.

**Comment by matthiasjost76** [comment]
Sorry, der Spiele PC ist gerade 100 km entfernt.
Ich benutze die neueste Version, die mir im Spiel angeboten wird. Die Helfer tun genau das, was sie tun sollen. 
Wenn ich sie aber stoppe und dann wieder losschicke, dann verlieren sie ihre Spur und fahren alle die gleiche Spur ab.

**Comment by Tensuko** [comment]
Ja aber trotzdem....
Links starten, stoppen, wieder auf links starten und fahren trotzdem wo anders ?
Same für Mitte und Rechts....
Kann mir nicht vorstellen dass sie die Einstellung ignorieren, dass nach dem Stoppen die Einstellung nicht mehr stimmt.... könnte sein, bin mir da gerade nicht sicher.

**Comment by matthiasjost76** [comment]
Habs eben ausprobiert mit der latest Version. 
Kurs für 3 traktoren generiert und den ersten auf rechts gestartet. Geht.
Dann helfer über Hotkey für CP Helfer stoppen entlassen. Dann Helfer über den gleichen Hotkey wieder gestartet (nahester Wegpunkt). Er biegt dann auf die Spur, links ab.
Ist nur eine Meldung, ich kann auch total gut so spielen, nur zu Eurer Infomation. Ich such mal eben ein Logfile.

**Comment by Tensuko** [comment]
Was steht im Hud wenn du ihn entlassen hast ?
Springt das Hud auf links oder bleibt es bei rechts ?

**Comment by matthiasjost76** [comment]
Wir kommen der Sache näher. Ich habe das Mini-Gui noch nie benutzt, aber seitdem ich das jetzt das erste Mal getan habe, verliert er die Spur nicht mehr. Ich kann es seitdem nicht mehr reproduzieren.
Spiel nicht gespeichert und wieder geladen.
Helfer aus dem „großen“ LS22 Menü auf rechts gestartet. Gestoppt. Gestartet. Fährt nach links. 
Mini-Gui geöffnet. Steht auf links. Aus dem Mini-Gui auf rechts gestartet. Fährt rechts. Mit Hotkey gestoppt und wieder gestartet. Bleibt rechts. 

Fazit: starte ich ihn aus dem großen Gui zuerst ohne Mini-Gui merkt er sich es nicht, nachdem ich einmal im Mini-Gui war, gehts.

Brauchst du noch mehr Infos?

**Comment by matthiasjost76** [comment]
Habe das Spiel abgespeichert und geladen. Jetzt merkt er es sich auch ohne Mini-Gui direkt beim ersten Mal.
Danke für deinem Support.

**Comment by Tensuko** [comment]
Mit dem großen GUI meinst du das ESC Menü ?

**Comment by matthiasjost76** [comment]
ja, das meine ich.
Ich habe die Sache noch mit einer anderen Maschine, einem anderen Traktor auf einem anderen Feld probiert.
Das Verhalten ist, wie schon beschrieben, gleich. Sobald das Mini-GUI einmal benutzt wurde, merkt er sich es.

**Comment by Tensuko** [comment]
Ok das heist nur beim ersten mal mit dem ESC Menü -> geht nicht
Einmal das mini-hud verwendet -> funktioniert es ?

**Comment by matthiasjost76** [comment]
ja, so scheint es.
