### ISSUE TITLE
[BUG_SP] Stuck on turns and U-turns. 

### ISSUE THREAD

**Issue by DuckinBoots** [Courseplay/Courseplay_FS22#1821]
Version used: 7.1.0.1
Hello. My harvester stuck on turns and U-turns. 
Log :
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9212348/log.txt)
I generate course for one worker.
I guess something wrong with my harvester, because this problem appears only to him. Can you help me solve this?
![fsScreen_2022_07_28_19_06_29](https://user-images.githubusercontent.com/54028622/181585489-f3e24b06-1ca7-44d7-8432-875a3354cdba.png)

**Comment by Tensuko** [comment]
Can't rly tell whats wrong if that is a mod.
Maybe collision is not correct on it, or something else.
Compare it with vanilla Combines.
Log says the FieldWorkProximity detects something.

Mod from ModHub?

**Comment by DuckinBoots** [comment]
It's private mod. Thank you for help. The xml file was missing ai code. My bad. XD

**Comment by Tensuko** [comment]
Oh okay that explains it :)
