### ISSUE TITLE
[Question] Courseplay causing other mods' keybinds in F1 menu to dissapear

### ISSUE THREAD

**Issue by maxresnikoff** [Courseplay/Courseplay_FS22#1822]
When I enable Courseplay, almost all other controls dissapear from the F1 hud menu. 
Eg. I only have Universal autoload and courseplay added to my save game. When I disable courseplay, I can see the controls/keybindings for Universal Autoload. If I enable courseplay, the autoload controls are missing. 
Even using the keybind to autoload doesn't work... So it isn't just that the control is missing in the F1 HUD, it just plain out doesn't work.

**Comment by Tensuko** [comment]
turn the keybinds off from CP and to make it clear, this is not only CP that happens when you have to many keybinds.
