### ISSUE TITLE
[Feature]  Field templates

### ISSUE THREAD

**Issue by venquessa** [Courseplay/Courseplay_FS22#1824]
**What is the problem this feature/enhancement solves?**
When running "full field features", one has to make many passes over the same field with different machines and implements.

Because the course generator memory is attached to the vehicle, not the field, it requires each implements course settings be checked and adjusted for each pass.

Each pass tends to share most of the settings so that multiple passes can be run simultaneously without conflict.

**Describe the solution you'd like**
Maybe a tick box in the course generator: "Use Field Template".  When selected the settings are loaded from a "last used on this field" copy of the course settings, rather than the "last used by vehicle".

Obviously the elements specific to "current implement" can be updated, such as work width and the other hidden params needed.

Optional/Ideal:  The "last used on field" cache copy would include the start point.  When you activate the CP: Fieldwork mode in the map and select the "start at" point, the course generator will open, but use the start point from the "field cache copy", so that all passes generated start in the same location on the field.

All other params not specific to the implement can remain the same.  Same machine/headland count, center setup etc.

If the checkbox is unticked they it will behave as currently and use the last used by vehicle course settings.

**Describe alternatives you've considered**
The ability to manually save a template, presented in the course generator as a drop down of previously saved "templates".  Note, templates would differ from save courses, as they are only saving the generic course generator settings.  A "Save" button would also be required (probably the full CRUD).  This would provide a LOT of flexibility to the templating, allowing farmers to save templates for fields based on what type of crop is in it which would then determine the field work pattern used by all implements.  

This is born through "excessive use".  I've been binge farming a very large map.  It get's tedious when you do not fix vehicles to jobs, but pick the next available tractor that you need to resetup each implement course for each pass.  Between the 8 or 9 passes needed I find I might only change 1 or 2 settings for 1 or 2 passes, the rest are identical, bar work width.
Things I might change are, number of vehicles or whether to do 1 or 2 headlands (to balance tool width), maybe whether to start in centre or headlands.  The rest are the same for each pass.

Failing to adjust a setting like Up/Down versus Racetrack between two implements on a field can lead to horrific pile-ups of implements in the middle of the field!

**Comment by Tensuko** [comment]
Mostly the generator settings are relevant to the implement, not the field.
I know what you talk about, but in that way we won't do that.

Save your course and it doesn't matter wich tractor you use.

If we just use specific settings for template, ppl will come up and ask for more.
I will think about a more general solution for this and not so specific.
