### ISSUE TITLE
[Question] Arbeitsbreite "resetten" bei Selbstfahrern?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1826]
N'abend Leute.
 Bei CP kann man ja mit abhängen/anhängen die Arbeitsbreite zurückstellen.
Wie geht das aber bei Selbstfahrern, wie z.b. dem BigM, Selbstfahrerspritzen, ...?
Die knann man ja nicht abhängen.
Lg
Andreas

**Comment by sam-2401** [comment]
@andreasthu klick mal im HUD auf das Wort "Arbeitsbreite"

**Comment by andreasthu** [comment]
Danke, werd ich machen
Lg
Andreas

**Comment by Tensuko** [comment]
Oder im generator 0 eintragen.
