### ISSUE TITLE
[Feature] Wegpunkt Anzeige per Tastenkombination durchschalten 

### ISSUE THREAD

**Issue by CptRog** [Courseplay/Courseplay_FS22#1827]
Hallo, 

besteht die möglichkeit das wechseln der Kurs Anzeige (Keine Wegpunkte / nur Start Stop / alle Wegpunkte) per Tastenkombination durchzuschalten 

Vielen Dank für diesen tollen Mod!!

**Comment by Tensuko** [comment]
Es wurde schon mal wegen mehr Tastenbelegung gefragt und nein machen wir nicht.
Der LS ist vollgestopft mit keybinds, das wollen wir nicht noch weiter führen.
Mini HUD das Auge zu, draufklicken muss reichen.
