### ISSUE TITLE
Wie lösche ich einen selbst gezeichneten Feldrand wieder aus CP?

### ISSUE THREAD

**Issue by BonaXJ6** [Courseplay/Courseplay_FS22#1829]
Hallo,

ich hatte mal einen selbstgezeichneten Feldrand erstellt. Um ihn versuchshalber zu entfernen, hatte ich nun alle Kurse und den Ordner für dieses Feld gelöscht, doch leider bleibt der Rand bestehen, wie man an der 68 erkennt. Kriege ich den überhaupt irgendwie weg?

![fsScreen_2022_07_31_11_51_19](https://user-images.githubusercontent.com/89728035/182020951-e06c2ac3-25aa-4123-9201-51cc43ca78f0.png)

**Comment by BonaXJ6** [comment]
> Hallo,
> 
> ich hatte mal einen selbstgezeichneten Feldrandkurs erstellt. Um ihn versuchshalber zu entfernen, hatte ich nun alle Kurse und den Ordner für dieses Feld gelöscht, doch leider bleibt der Rand bestehen, wie man an der 68 erkennt. Kriege ich den überhaupt irgendwie weg?
> 
> ![fsScreen_2022_07_31_11_51_19](https://user-images.githubusercontent.com/89728035/182020951-e06c2ac3-25aa-4123-9201-51cc43ca78f0.png)

**Comment by Tensuko** [comment]
Ingame hilfe lesen, da wird alles erklärt.

**Comment by BonaXJ6** [comment]
Sorry, die Hilfe vergisst man schnell, wenn man neue Mods nutzt und alles andere soweit kennt und man sonst die Hilfe nicht mehr benötigt

**Comment by Tensuko** [comment]
Desshalb der Hinweis meinerseits.
