### ISSUE TITLE
[BUG_SP] blocked by object false positive planter

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#1830]
CP flags blocked by object, possibly by its own planter. only happens on headland turns at this point. , but this has been an issue with multiple tractors, including stock 9620R

![20220731105519_1](https://user-images.githubusercontent.com/5993529/182035293-166cb1d4-533c-4e63-b182-542d1f28eaa8.jpg)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9229249/log.txt)

![20220731111822_1](https://user-images.githubusercontent.com/5993529/182035725-fe26126a-2b5e-4fd0-a3ff-cfadfbe2e81a.jpg)

[log1.txt](https://github.com/Courseplay/Courseplay_FS22/files/9229262/log1.txt)

**Comment by nothinfancy** [comment]
I'm also having that same issue.

**Comment by Tensuko** [comment]
Why not used template....
What tool is it?
And I mean not the tractor!

**Comment by nothinfancy** [comment]
![Farming Simulator 22 7_31_2022 4_02_18 PM](https://user-images.githubusercontent.com/102297824/182043173-8bf7b79b-3255-46cf-9143-f01ed30a4ffb.png)

**Comment by nothinfancy** [comment]
![Farming Simulator 22 7_31_2022 4_15_53 PM](https://user-images.githubusercontent.com/102297824/182043576-8d2943a5-41fc-4ea3-b46c-77efb0eb0b7c.png)

**Comment by Tensuko** [comment]
Your last Screenshot is something different, I want to know what tool it is on the screenshots!

**Comment by nothinfancy** [comment]
#1  c850air cart with 1870 air hoe drill.           #2 2660vt jd

**Comment by Tensuko** [comment]
link?

**Comment by Commissar0617** [comment]
https://farmingsimulator22mods.com/john-deere-1870-air-hoe-drill-v1-0-fs22/

**Comment by nothinfancy** [comment]
mod network.com               fs22.com         thanks  Commissar!!

**Comment by Commissar0617** [comment]
https://farmingsimulator22mods.com/john-deere-2660vt-v1-0-fs22/ i think is the 2660... i don't use that one myself

**Comment by nothinfancy** [comment]
sorry guys I'm doing my best.  new to this and learning.

**Comment by nothinfancy** [comment]
sorry guys I'm doing my best.  new to this and learning.

**Comment by Commissar0617** [comment]
im also using the isaria pro active (from prescision farming dlc) on the 3 point rear of the tractors ... because no front 3 point lol

**Comment by Tensuko** [comment]
Those websides are full of stolen mods (inclusive courseplay) not going to support anything frim there.
Pretty surw those tools are bad converts with old and wrong colission.

**Comment by nothinfancy** [comment]
ya the 2660vt.... i think i got that one off of mod-network.com

**Comment by nothinfancy** [comment]
oh?  suggestions?

**Comment by nothinfancy** [comment]
Recommendations?

**Comment by Tensuko** [comment]
Maybe use this one?
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=240761&title=fs2022

if that one makes problems we have a look (last time I tested it was absolute fine)

**Comment by Commissar0617** [comment]
> Maybe use this one?
> https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=240761&title=fs2022
> 
> if that one makes problems we have a look (last time I tested it was absolute fine)

It should work i would think. Switched to a bourgault planter of similar size off the in game mod hub, and didn't have the issue.
