### ISSUE TITLE
Courseplay doesn't pick the field I've outlined.

### ISSUE THREAD

**Issue by Namurian** [Courseplay/Courseplay_FS22#1831]
Courseplay picks the wrong field. I did a field perimeter manually and it doens't pick it. Instead it tries to pick a grape field instead of grass field. As far as I can see there is absolutely no way to manually pick the field I want to use... 
![whatthefuckisthis](https://user-images.githubusercontent.com/62732426/182035722-fccf8ffc-f91d-44ea-9c16-2aac1e6a6fcc.png)

**Comment by Symbob** [comment]
@Namurian Have you got the "Prefer Custom Fields" option in the CP settings activated
![fsScreen_2022_07_31_17_29_21](https://user-images.githubusercontent.com/18528850/182036352-ef097fc7-2910-4dd2-820b-d8c85fa62089.jpg)
?

**Comment by Namurian** [comment]
Didin't have it activated. Thanks!
