### ISSUE TITLE
[Question] Incorrect rotation of Kverneland PW 100-12 with Packomat on Headlands

### ISSUE THREAD

**Issue by szokezoltan95** [Courseplay/Courseplay_FS22#1836]
Maybe there is a setting for that, but in my case, the plow is incorrectly rotated on the headlands, as shown in the attached picture. This way, the Packomats does not cultivate the rows correctly.
![CP_plow](https://user-images.githubusercontent.com/67110675/182381049-26569225-a89b-4243-8428-58c24ecf7f1e.png)
![CP_plow_2](https://user-images.githubusercontent.com/67110675/182381502-30fe0864-0808-4a67-851a-453601229271.png)

**Comment by Tensuko** [comment]
No settings for this and this is working as intended.
Else we would drive outside the field with the plow inward.

You can try to start on the center and not on the headland.
