### ISSUE TITLE
[BUG_SP] wondering if/when you'll be allowing the new coffee Jacto K3500 harvester to work with the new coffee plants on Recanto Da Alvorada Map?

### ISSUE THREAD

**Issue by BillyElliott78** [Courseplay/Courseplay_FS22#1837]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Maybe never?
This is a question so use question template pls and not bug.

We are not focused on single mods for now so maybe anytime in the feature.
