### ISSUE TITLE
Courseplay stops harvester with "Needs to be unloaded" when towed bailer is full.

### ISSUE THREAD

**Issue by DazzaJay** [Courseplay/Courseplay_FS22#1838]
Bug: 
When harvesting, using Snuefelstueck to tow a bailer behind the harvester, the harvester will stop when the bailer reaches 95% full.

![Farming Simulator 22 1_08_2022 9_17_13 PM](https://user-images.githubusercontent.com/3713158/182515982-a3a54b54-f9b2-4079-a9d4-f987db35d223.jpg)

Solution:
Make Courseplay ignore the full% of bailers. as they automatically unload when they hit 100%

Other Notes:
Mods in use: Courseplay, Snuefelstueck, Liftable Bales.

**Comment by Tensuko** [comment]
This is not a bug.
And your request should be more a question and the answer to this is:
Sry but won't happen.

**Comment by DazzaJay** [comment]
This bug didn't exist in FS17 with courseplay. I'm just looking for the same functionality it used to have.

**Comment by Tensuko** [comment]
We are not in FS17 and we are not in FS19 we are in FS22 and CP7.x and I say won't happen and it is not a bug!
