### ISSUE TITLE
[Question] jacto coffee harvester

### ISSUE THREAD

**Issue by BillyElliott78** [Courseplay/Courseplay_FS22#1839]
wondering if/when you'll be allowing the new coffee Jacto K3500 harvester to work with the new coffee plants on Recanto Da Alvorada Map?

The reason I ask is because the new coffee plants are also being used on other maps and would make sense to have courseplay set up to use the new harvester with the new coffee plants.

**Comment by Tensuko** [comment]
We are not focused on single mods for now so maybe anytime in the feature.
