### ISSUE TITLE
[BUG_SP]Standard Helper is not using active Vehicle

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#184]
**Steps to reproduce**
Press H on different Vehicles, or go over the ESC menue

**Actual behavior**
uses everytime the same vehicle if you open the Helper/Helpermap

**Expected behavior**
Opens the Helper with the Active Vehicle

**Map**
Elmcreek, but testet on all others

**Vehicles/ implements involved**
no, tested with a blank, just courseplay activated

*Edit*
it just not opens the active vehicle (the one im sitting in), it opens everytime the last active/selected vehicle

**Comment by Tensuko** [comment]
Logfile ?
Version ?

**Comment by RealNeo80** [comment]
7.0.0.7
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7781886/log.txt)

**Comment by Tensuko** [comment]
Not rly clear what happens here, can you edit your 1st post pls and make it more clear ?

I press H on different Vehicles and go into Esc Menu. - ok

Use everytime the same vehicle if you open helpermap - what same vehicle ?

Opens the helper with the active vehicle - yes that should it do

I couldn't reproduce this, or does it maybe happen only at the start of the savegame and later not anymore ?

Could you try that out and report ?

**Comment by RealNeo80** [comment]
not its over the whole time, if i start a new map, or loading a savegame, if CP is activated

**Comment by RealNeo80** [comment]
scheint mit 7.0.0.8 nun richtig zu funktionieren
seems to work properly with 7.0.0.8
