### ISSUE TITLE
[Enhancement] Multitool Pathfinder turn über headland, wenn headland in die entgegengesetzte Richtung des turns zeigt.

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1840]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
Drescher Kurs. lt screenshot:
zwei Drescher Claas Lexion, ein Vorgewende, 13,5m AB
![fsScreen_2022_08_03_10_00_49](https://user-images.githubusercontent.com/24860501/182557960-1283e638-45eb-4b13-b2d1-e07fc7543df1.png)
![fsScreen_2022_08_03_10_01_22](https://user-images.githubusercontent.com/24860501/182558009-d6c40aaa-ca77-4dfb-a7fe-e594de825e03.png)

**Actual behavior**
A clear and concise description of what happen.
der 1. Drescher, linke seite, zieht nach der -reihe im Vorgewende nach rechts rüber, fährt ums Feld und beginnt wieder auf der linken Seite zu Dreschen:
![fsScreen_2022_08_03_09_55_14](https://user-images.githubusercontent.com/24860501/182558259-c4a10429-2fe0-463a-bfb1-9f14c20dd0a4.png)
![fsScreen_2022_08_03_09_55_34](https://user-images.githubusercontent.com/24860501/182558305-051d4e35-5b18-4bcb-b9d3-0d0593fbc56e.png)
![fsScreen_2022_08_03_09_55_50](https://user-images.githubusercontent.com/24860501/182558328-a27fabfe-ef63-4a9f-83fb-55c075523755.png)
soweit so gut, soll er meinetwegen rechts fahren

aber der rechte Drescher zieht am Reihenende nach Links, fahrt auf der linken Seite des Vorgewendes ums Feld
![fsScreen_2022_08_03_09_57_28](https://user-images.githubusercontent.com/24860501/182559187-b5cc342f-484c-47d5-91d1-b76e6690797b.png)
![fsScreen_2022_08_03_09_57_38](https://user-images.githubusercontent.com/24860501/182577206-e6346926-e324-4e6b-bc66-c53e1c60449c.png)
![fsScreen_2022_08_03_09_57_45](https://user-images.githubusercontent.com/24860501/182577230-29d585bb-1b08-4517-b06a-df5dce7f1ddd.png)

schwenkt dann kurz vor der nächsten Reihe auf die linke Bahn ein
![fsScreen_2022_08_03_09_58_18](https://user-images.githubusercontent.com/24860501/182559306-650c07a1-1715-4ff2-8a72-3e9237496d89.png)

macht aber dann einen zusätzlichen rechts/links schwenk um die rechte Bahn zu erwischen
![fsScreen_2022_08_03_09_58_32](https://user-images.githubusercontent.com/24860501/182577664-1d3c445d-51a4-4a53-b45c-40d4e8872b3b.png)

**Expected behavior**
der Drescher auf der rechten Bahn sollte auch rechts im Vorgewende fahren, und erst zur rechten Bahn einschwenken, nicht schon vorher zur linken.

**Screenshots**
oben dabei

**Courseplay version**
Version used: 
aktuelle main

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9249405/log.txt)

**Map**
Map played on.
Hobos Hollow 4x
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=236591&title=fs2022

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Claas Lexion (von Giants)

**Relevant script mods**
Mods like Autodrive or VCA and so on.

lg
andreas

edit:
fehlende screenshots ergänzt

**Comment by rohne83** [comment]
ist ja an sich erstmal eher nur ein Schönheitsfehler. Problematisch ist nur dass dieser Schlenker beim Einschwenken in die nächste Bahn doch ziemlich viel Zeit kostet, und oft dazu führt dass der Verband mit der Zeit immer weiter auseinanderreißt.
Und generell das Problem dass der Drescher der auf dem Vorgewende die Außenbahn befährt, beim Einschwenken ins Vorgewende auf unregelmäßigen Feldern mit vielen Hindernissen am Feldrand dann doch gerne mal an einem Baum hängen bleibt.

**Comment by Tensuko** [comment]
> ziemlich viel Zeit kostet

Zeit sollte man erst mal außer acht lassen. Funktion -> Verbesserung.


> der Verband mit der Zeit immer weiter auseinanderreißt

Bin gerade nicht sicher, aber glaub der letzte Stand war das der vordere nicht endlos weg kann, bin mir da nicht sicher...

An sich weis ich was da passiert.
Schaut man sich das Vorgewende an, fahren sie entgegen der Richtung der Wegpunkte.
Denkt man sich jetzt den offset kurs links/rechts dazu, haben die Drescher alles richtig gemacht.

Man bräuchte einen invert für das Vorgewende (multitool), wenn man dieses in die andere Richtung befährt.

**Comment by rohne83** [comment]
Eine Behebung dieses Verhaltens könnte zudem Helfen Kollisionssituationen wie im Screenshot zu vermeiden:
![fsScreen_2022_06_01_16_40_27](https://user-images.githubusercontent.com/71030138/182591817-04fc9d9e-e772-4229-9158-a359d7b38cc0.png)

Würde der zweite Drescher auf seiner eigentlichen rechten Bahn (also vom Vorgewende die Außenbahn) befahren, bestünde hier kaum die Gefahr dass er dem ersten fast frontal ins Schneidwerk knallt

**Comment by Tensuko** [comment]
Mit einer so alten CP Version lässt sich nichts anfangen.
Da würden nicht mal das logfile aktzeptieren :)

**Comment by andreasthu** [comment]
Grundsätzlich kann man bei cp ja keine "Wenderichtung" direkt einstellen.
Beim vorgewende geht mit Uhrzeiger oder gegen Uhrzeiger.
Logischerweise nimmt man bei Dreschern den Uhrzeigersinn, da dann das Rohr aussen am Feldrand ist.
Bei Feldmitte "Beete" wird dann quasi immer gegen den Uhrzeigersinn gefahren, da dann das Rohr (bis auf den Durchstich) auch immer auf der abgedroschenen Seite ist.
Meine überlegung wäre das bei der wende (Linkskurve) beide auf der aussenseite (rechts bei dreschern) fahren könnten.
Es gibt aber auch manchmal situationen wo der Drescher nach rechts wendet um einen neuen Durchstich durchzuführen, da könnten beide dann auf der linken spur fahren.
Wäre das technisch möglich?
Oder das beide in der mitte Fahren (dort wo die weiße kurslinie ist wenn man das auge 2x einschaltet)
Lg
Andreas

**Comment by Tensuko** [comment]
Beide einfach auf der Mitte wäre auch eine Option, aber ob das so einfach funktioniert kann ich dir nicht sagen.

Muss man schauen, ist aber eher ein enhancement, da sie theoretisch alles richtig machen, links bleibt links und rechts bleibt rechts, nur nicht in der aktuellen Fahrtrichtung :)

**Comment by rohne83** [comment]
> Mit einer so alten CP Version lässt sich nichts anfangen. Da würden nicht mal das logfile aktzeptieren :)

Fand es trotzdem passen, ist ja eh unabhängig von der Version. Schlichtweg die logische Konsequenz aus dem im Eröffnungsbeitrag geschilderten Verhalten, wenn im spitzen Winkel in die nächste Bahn eingefahren wird. Und tritt damit auch mit der aktuellen Version genau so auf.
Alle auf der Mitte wäre vielleicht naheliegend. Allerdings würde dann zumindest ab drei Geräten die aus Überschneidung der Wege resultierende Kollision aus meinem Screenshot aus rein geometrischen Gründen weiterhin auftreten.
