### ISSUE TITLE
[BUG_SP]CP + AD killen LS22 !

### ISSUE THREAD

**Issue by WernerWusel** [Courseplay/Courseplay_FS22#1841]
Steps to reproduce the behavior.
In AD die Debug-Einstellungen "Fahrzeug" und "Sensoren" aktivieren.
In CP im ESC-Menue einen gespeicherten Feldkurs laden oder einen neuen erstellen.
Mit ESC das Menue verlassen.

A clear and concise description of what happen.
Danach friert das Spiel (LS22) ein und kurz darauf geht´s zum Desktop.

Kein Einfrieren und kein zurück zum Desktop.

Nicht Zielführend.

Version used: CP 7.1.0.2
                     AD 2.0.0.7

Please attach a log with all debug channels active.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9268244/log.txt)

Map played on.
Huron County Michigan

Which vehicle or implement?
Unabhängig davon.

Mods like Autodrive or VCA and so on.
AD, VCA, CP

**Comment by Tensuko** [comment]
Ohne Error in der log können wir da nichts machen.

**Comment by Tensuko** [comment]
Kann es nicht reproduzieren -> kein CP Error.
![fsScreen_2022_08_05_14_45_39](https://user-images.githubusercontent.com/27344744/183080045-eb1125c8-fd2b-4950-a0a5-a3db443b09fd.png)
