### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by elGrappadura** [Courseplay/Courseplay_FS22#1844]
![FS_VehicleBlocked](https://user-images.githubusercontent.com/110739373/183260313-ee5b0f16-780b-4ea9-bcbc-062e62e54f75.png)

Not exactly sure what is happening here. It's a modded tractor (Deutz-Fahr S9-705) and loading wagon (Shuttle 490S byMo), but I've used them successfully with courseplay before (back in march, although on a different map).

Map is Nordfriesische Marsch 4x OG. Courseplay Version is the latest release V7.1.0.2

I can create a course without any problem and it's working fine during straights, but is immediately "blocked" when trying to turn. The same course works fine when using the M450 mower (which funnily also is a lot wider.) I tried playing around with the fruit bypassing and turning on field settings - nothing helps.

**Comment by Tensuko** [comment]
Not a bug, bad convert of the Mod.
Old FS19 colision mask.
When Modder don't stick to vanilla its not our problem.... sry.

**Comment by elGrappadura** [comment]
Alright, thanks for clearing it up!
