### ISSUE TITLE
[BUG_MP]Any fertilization when switching from courseplay to autodrive will cause a total interruption of all ongoing work. For this reason, there are gaps in the fields or departures from the route. This problem does not occur only in a moment. when personally sitting in the designated machine that is currently being switched.

### ISSUE THREAD

**Issue by Vernyj** [Courseplay/Courseplay_FS22#1845]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared.

**Dedicated server or local hosted server**
Dedicated server yes/no ?

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Use template and not post it in the headline.....
