### ISSUE TITLE
[BUG_SP] forage/self loading wagons immediately return to route when given destination with autodrive

### ISSUE THREAD

**Issue by Thunderloon** [Courseplay/Courseplay_FS22#1852]
Cp 7 1 0 2
Autodrive  2 0 0 6
Niedersachsen 22 (NDS Modding 1.6.0.0)
(problem also occurs with just Courseplay and AutoDrive on stock map with no mods at all using stock tractor and forage wagon)

Problem occurs with all tractors and all self loading wagons.

Mowed field, windrowed field then used same tractor carrying windrow course to collect with forage wagon.

When it is full, AutoDrive ordered to take vehicle to silo for unloading.  Upon arrival at unloading input of silage silo (happens on all of them) it starts to unload automatically *which was not ordered* instead of stopping and immediately uses pathfinding to return to working field without any attempt to unload.   This started occurring when code for combines was changed.  It is obviously acting like a combine.  It is obviously using the shared code.

Simple solution:  add control option to toggle "stop while unloading" to loading wagon in the configurations.   
Better solution:  change default "stop while unloading" to "yes" for all vehicles.
Correct solution: Why does it think a loading wagon is a combine harvester?  It can obviously tell the difference in the options page.

**Comment by Tensuko** [comment]
AD problem, not CP.

**Comment by Iwan1803** [comment]
Without any further informations... how should we help?
For me it sounds like wrong AD mode and false expectations.
