### ISSUE TITLE
Green Grapes

### ISSUE THREAD

**Issue by prawler74** [Courseplay/Courseplay_FS22#1856]
Hi

I am playing on Elmcreek Edit by Stevie. He has added Green Grapes to his map. Tried create a course, but it only shows up as a white thin line field.

Tried several fields......
Se the attatched picture, and field 13.

Bjørn

![fsScreen_2022_08_16_14_54_33](https://user-images.githubusercontent.com/64365977/184884689-ca69918c-7d6c-40b3-94b0-00057f74a474.png)

**Comment by Tensuko** [comment]
Mod Issue.
It needs to be the placed vines from Giants. Sry...

**Comment by prawler74** [comment]
Hi. Thats ok. I just needed to know if i was doing something wrong. Keep up the good work

Bjørn
