### ISSUE TITLE
[Feature] Field edge detection like in courseplay FS 19.

### ISSUE THREAD

**Issue by DigbyDark1** [Courseplay/Courseplay_FS22#1857]
**What is the problem this feature/enhancement solves?**
Currently, if fields are close together, Courseplay clumps them all together.

**Describe the solution you'd like**
I would like Courseplay to properly detect the edge of fields, even if not numbered.

**Describe alternatives you've considered**
N/A

**Additional context**
![Courseplayerror](https://user-images.githubusercontent.com/111363340/184890772-72a9f2ee-0ce0-484a-aefc-d9e24c435e7d.png)

**Comment by Tensuko** [comment]
Map Issue, not CP.
Or draw your custom edge.

**Comment by Tensuko** [comment]
Just a side note....
Who tells you this worked in FS19?
Also those fields sure make hughe problems for the generator and the driver.
