### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by bhacker62** [Courseplay/Courseplay_FS22#1858]
Can we not share CP courses in mp while managing the same farm?  When my other farm manager creates a CP course, I am unable to access it and vice versa for him as well.  We are playing on a gameservers dedicated server.  Are the course XML saved locally only or is there a way to share courses?  Thanks

**Comment by Tensuko** [comment]
CP courses are saved localy on purpose.
2 Ways:
- share your course over e.g. Discord.
- load the course in your tractor, your friend jumps in it and saves it for himself.
