### ISSUE TITLE
Die Funktion bei einer Sämaschine Düngefunktion ausschalten funktioniert nicht, trotz das es auf deaktiviert steht wird Dünger verbraucht[BUG_SP]

### ISSUE THREAD

**Issue by Steffen2403** [Courseplay/Courseplay_FS22#186]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Duplicate #63 

https://github.com/Courseplay/Courseplay_FS22/wiki

"2. Check if your problem has already been reported by someone else. If so, contribute to that issue instead of creating a new one."
