### ISSUE TITLE
[Feature] Markierungen auf anderer Höhe wie im LS19

### ISSUE THREAD

**Issue by Gecko774** [Courseplay/Courseplay_FS22#1862]
Hallo,

wäre es möglich für die Fahrmarkierungen eine Möglichkeit wie damals im LS19 einzubauen, sodass diese nicht
über den Traktoren sind sondern auf der Höhe dieser bzw. knapp über der Frucht oder variabel?

Ich benutze CP sehr gerne, fahre aber auch gerne mal im Wechsel (Manuell/Auto) die Routen vom CP erstellten Kurs gerne selbst ab.
Würden die Markierungen & Wegpunkte auf der Höhe der Traktoren sein wie es damals mal möglich war würde das
um einiges leichter gehen :) .

Vielleicht wäre es ja möglich die Option wieder einzubinden, dass man sich die Höhe einstellen kann bzw. zwischen den Höhen wechseln könnte oder dass man zusätzlich nur die kommenden Markierungen sieht, zb. die nächsten 20 Stück zu der bisher vorhanden Möglichkeit das gesamte Feld bzw. Start- Endpunkt anzeigen zu lassen. So kann man dann CP einfach als aktive Fahrhilfe noch benutzen.

MfG

**Comment by Tensuko** [comment]
Du meinst die höhe der Wegpunkte?
Die ist für CP schon immer auf der höhe gewesen...
Glaub du verwechselst das mit AD.

**Comment by Gecko774** [comment]
Hallo,

ja genau die Höhe der Wegpunkte habe ich gemeint.

Ich glaube das war mal in einer Developer Version hier auf Github möglich das man die Höhe ändern konnte, ist aber auch schon etwas länger her gewesen. In den Anfangsmonaten von CP beim 19er.

Aber vom Prinzip her so wie bei AD bzw. den Linien von den GPS Mods wie Enhanced Vehicle, VCA etc. (Bodennähe und evtl. nur einen gewissen Bereich vorm Fahrzeug sichtbar). , sodass man CP noch besser wie bisher als Fahrspurhilfe nehmen könnte. 

MfG

**Comment by Tensuko** [comment]
Nein das gab es nicht wirklich, jedenfals nicht in offener Release Version.
Wenn du einem Weg folgen möchtest, nutze doch VCA oder GPS ?

**Comment by Gecko774** [comment]
![fsScreen_2022_08_20_17_57_35](https://user-images.githubusercontent.com/59656463/185755776-83a3d020-34ba-47b7-b851-d1a82916a6ce.png)

ich hatte jetzt nur in der Schnelle das Bild gefunden.

VCA oder GPS folgen nur geradlinig den Wegen.
Mit Courseplay kann ich zb. die Wege auf nicht rechteckigen Feldern folgen oder Bögen fahren, Vorgewende genau erstellen oder mit am Wichtigsten dann zb. während der manuellen Fahrt umstellen sodass CP übernimmt und den Rest des Feldes macht bzw. auch wieder vollständig in den Selbstfahrermodus wechseln und das restliche Feld mit den generierten Feldlinien fertig mache.

**Comment by Tensuko** [comment]
Das ist nur uralter debug und keine echte funktion und wurde damals auch entfernt weil nicht mehr nötig.
Werden wir für den 22er nicht übernehmen, sry.

**Comment by Tensuko** [comment]
PS: Ob die höhe der Wegpunkte einstallbar sein wird als Einstellung, hängt davon ab wie komplex es um zu setzen ist, aber ist nicht gerade priorität...
