### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Daniel78-art** [Courseplay/Courseplay_FS22#1866]
hallo,

ich wollte mal ein Problem melden mit dieses hydroTrikeXL es ist Original von Giant.
![fsScreen_2022_08_23_10_01_35](https://user-images.githubusercontent.com/72348662/186107649-a6f54e5b-9a36-40f8-99bd-77637fb7d722.png)
![fsScreen_2022_08_23_10_01_42](https://user-images.githubusercontent.com/72348662/186107656-3f54b94c-402a-43b0-ac7b-a279af2d0f7b.png)
![fsScreen_2022_08_23_10_02_23](https://user-images.githubusercontent.com/72348662/186107663-b4bb8d4b-6c21-4235-9bbd-a0aa55c97f37.png)
Das Ding ist permanent am Lenken obwohl es eine grade line ist. 
Hier sind auch ein paar Bilder und die Log auch. 
Vielleicht kann man da was machen.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9400664/log.txt)

MfG Daniel

**Comment by Tensuko** [comment]
Du hast aber ein feature request gemacht ohne überschrift etc.
Für sowas bitte bug report nutzen und ausfüllen.

Ich mach den hier zu, aber ich gucke mir das Fahrzeug mal an und schau was wir machen können.
Also bitte nichts neues aufmachen...
