### ISSUE TITLE
[Question] ÜLW fährt permanent neben Drescher

### ISSUE THREAD

**Issue by JayDi999** [Courseplay/Courseplay_FS22#1867]
Hallo,

der Courseplay ÜLW macht alles wie gewünscht. Wird gerufen bei % Füllstand und fährt zum Drescher und tankt diesen während der Fahrt ab. Wenn der Drescher aber 0% erreicht hat fährt der ÜLW weiter neben dem Drescher bis der ÜLW voll ist oder der Drescher ihn zum wenden stehen lässt und er die eingestellte % bspw 85 zum Abfahren erreicht hat.

Ich kenne es von Courseplay so, dass er abtankt und dann den ÜLW (mit Autodrive) wieder wegschickt. 
Liegt das jetzt an Courseplay am fehlenden wegschicken oder an Autodrive?

**Comment by MeRida2104** [comment]
Liegt am autodrive. Schalte mal das aktive Abladen aus. Dann sollte sich das erledigen und der Abfahrer bleibt stehen wenn der Drescher leer ist.
