### ISSUE TITLE
[Question] Same course, different widths

### ISSUE THREAD

**Issue by kwguk** [Courseplay/Courseplay_FS22#1874]
Been using CP since 13, best mod out there.

Ive often wondered if its possible to run different width implements down the same course at different times. 
For instance if im running a course with 2 combines can i then run only 1 baler on the same course?

If i have a 10m wide mower can i then run a 14m rake down the same course by adjusting the course width?

**Comment by rohne83** [comment]
Of course you can. If you have troubles at the field edge you will have to play around with horizontal offset, and for running just one baler behind 2 combines you will have to engage the baler twice (once on the left course, once on the right one). But everything possible.

**Comment by Tensuko** [comment]
On old repository is a discussion where I tried to explain it, try it out :)
https://github.com/Courseplay/courseplay/discussions/7715

**Comment by kwguk** [comment]
Thats great, many thanks for the solution
