### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by nothinfancy** [Courseplay/Courseplay_FS22#1876]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.
![Farming Simulator 22 8_28_2022 6_55_11 PM](https://user-images.githubusercontent.com/102297824/187097892-54dffffa-e9af-46ed-9e1a-f2b8604c11d4.png)
says needs refueled when starting course...will drive all over the map with no help. just when entering field at start at first way point. just started with last update. 7.1.0.3 both are mods. and over a year-old mods. suggestions and help would be apricated.

**Comment by Tensuko** [comment]
No filled in template .... The mods for fs22 cant be a year old and even then doesnt mean they are correct made. At least a logfile could have helped maybe. Sure a Midco flict or something but not a CP bug.
