### ISSUE TITLE
Course direction in course generation settings

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/Courseplay_FS22#1877]
I can't find course direction option (clockwise/anticlockwise) in course generation page. This option is very necessary for potato harvester since its pipe is on the right side unlike combine harvester. I tested it by Courseplay 7.1.0.3 modhub version.

**Comment by Tensuko** [comment]
Expert settings activated in global settings ?

**Comment by Tensuko** [comment]
No Problem, Question -> Answer :)
