### ISSUE TITLE
[BUG_SP] Pathfinder turn call stack

### ISSUE THREAD

**Issue by DMunkov** [Courseplay/Courseplay_FS22#188]
**Steps to reproduce**
**Actual behavior**
Working on slightly modified field 30 on Haut-Beyleron with seeder implement Amazone Citan, had to stop AI from turning too sharp, put him back on course and then he did an arc into the lake.

**Screenshots**
![2021-12-28 14_50_53-2021-12-28 14_43_43-Farming Simulator 22 png - Picasa Photo Viewer](https://user-images.githubusercontent.com/24708050/147519289-55255048-a7d3-41c1-aec2-9976e3aa7963.png)

**Courseplay version**
Version used: 7.0.0.7

**Log**
[[log.txt](https://gist.github.com/DMunkov/3224c7dca9506f11dfea42b2efd77b52)]

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
No modded implements/vehicles except auto-loader trailer parked on the farm

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
Where did you put him back on the course ?

**Comment by DMunkov** [comment]
Yellow depiction on the screenshot is where the tractor with the implement
were when I clicked “hire an AI worker”

**Comment by Tensuko** [comment]
Try to remove your bugge strautmann trailer.
It produces a callstack wich may lead into some stuff not working anymore.
