### ISSUE TITLE
[BUG_SP] Error: Running LUA method 'loadSharedI3DFileAsyncFinished' - CoursePlot.lua:58: attempt to index a nil value

### ISSUE THREAD

**Issue by Eendas** [Courseplay/Courseplay_FS22#1883]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I don't know how it happenned.

**Actual behavior**
I logged off, then restarted Fs22 and when I want to join my world, loading stops at 85% and in the log.txt it shows this error:
`2022-08-31 14:10 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/nojus/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:58: attempt to index a nil value`

**Expected behavior**
Join my Singleplayer world

**Screenshots**
![image](https://user-images.githubusercontent.com/108664891/187666708-438d0f4e-8aa4-4118-9422-25968bdf871d.png)
![image](https://user-images.githubusercontent.com/108664891/187666741-b0fed9f6-137b-4d51-94d0-e4c82aaf49ca.png)

**Courseplay version**
Version used: 7.1.0.3 (newest from modhub)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9461053/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Nothing. Just Courseplay

**Comment by schwiti6190** [comment]
@Eendas Hi, you've posted the wrong log file, as this one is already cleaned after a restart. 
Could you post the correct log file?

**Comment by Eendas** [comment]
Where can I find all log files?

**Comment by Tensuko** [comment]
Yea but we need the log.txt with the Error in it.
So start your game, load your save, if the Error comes up give us the log.txt else if you do a fresh start of the game, the log.txt will be reset.

**Comment by Eendas** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9461963/log.txt)
New

**Comment by Eendas** [comment]
[savegame1.zip](https://github.com/Courseplay/Courseplay_FS22/files/9462177/savegame1.zip)
Here you go :)

**Comment by schwiti6190** [comment]
@Eendas If you delete this file: CpAssignedCourses.xml, then the savegame will be loadable again. Not sure how it happend, that one vehicle has a course with no waypoints loaded. If the problem appears again let us now with a detailed description what you did before as possible, so we can find out the cause of it. :)

**Comment by Eendas** [comment]
Never mind. I started game and then deleted. It worked. Thank you 🙂
