### ISSUE TITLE
[BUG_SP] Nearest waypoint doesn't work (Workaround discovered)

### ISSUE THREAD

**Issue by Phelms215** [Courseplay/Courseplay_FS22#1885]
**Steps to reproduce**

- Generate a course and start a job at first waypoint.
- Stop Job. 
- Create new job from nearest waypoint. 

**Workaround**
- Generate a course and start a job at first waypoint.
- Stop Job. 
- Hire in game AI & Fire after they start moving
- Create new job from nearest waypoint. 
- works as expected  

**Actual behavior**
Worker ignores nearest waypoint and always starts from first waypoint of course 

**Expected behavior**
Worker to continue from the closest waypoint they are near. 
 
**Courseplay version**
Version used: v7.1.0.3 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. - Green Valley Nebraska 

**Vehicles/ implements involved**
Which vehicle or implement?  Everyone I tried (in game and mods) and every type 
Mod yes/no ? Yes

**Relevant script mods**
Precision Farming

**Comment by Phelms215** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9474838/log.txt)

**Comment by Tensuko** [comment]
You talk about the AI Menu under ESC?

**Comment by Phelms215** [comment]
Either or, in the Worker menu just a normal AI worker (non CP) or in the
game hitting the "hire ai" option not in the menu.

**Comment by Tensuko** [comment]
But not with our HUD ?

**Comment by Phelms215** [comment]
Oh it doesn't matter how I re-engage CP's route. Unless I do the workaround I described where I would start/stop of the default worker first. When I resume (start with nearest waypoint or last waypoint) it will always go back to the first waypoint and start from there. 

I can make a recording later tonight if that would help?

**Comment by Tensuko** [comment]
I rly can't follow you, so a Video would help.
When I use the Job Menu (ESC) and do everything from there, I kinda get the problem, but the point is, when you have your Giants Target near the 1st Waypoint, well, start a Job will always start it by drive to the Giants Target.

When I use the keybind after 1st Create Job task and the HUD is set to nearst it will start on nearest.
So I don't see your problem right now...

I am pretty sure you get into AI Menu with "no course" wich will set the Giants Target at your current position as well as the 1st waypoint position, so it may look like 1st waypoint but it is just that Giants drives to the target and then give over to CP.

But well yea do a Video and I will see if I can spot the problem :)

**Comment by Tensuko** [comment]
Closed due to inacitivty.
Also can't rly follow the problem, explained a bit what might happen, but a Video is necessary here.
Reopen if we got the right informations :)
