### ISSUE TITLE
Zusatztanks nicht absenken

### ISSUE THREAD

**Issue by Cornflix244** [Courseplay/Courseplay_FS22#1886]
Vor allem wenn man einen Zusatztank benutzt fällt auf, dass Courseplay dort eine Option fehlt.
Denn wenn man den Helfer mit z.B. Sämaschine und Zusatztank startet muss man kläglich zusehen, wie er den Zusatztank senkt und nicht vom Fleck kommt bzw. spätestens bei der ersten Kurve von Kurs abkommt (im Falle des Tanks von Kuhn).

Ich könnte mir ein den Treckereinstellungen eine Option vorstellen, mit der man einstellen kann, welche Geräte (vorne/hinten) gesenkt/eingeschaltet werden sollen.

**Comment by Tensuko** [comment]
Nein, keine weitere Option, wenn dann lösen wir das anders, wobei mir die Sache neu ist.
Schau ich mir an...

**Comment by Tensuko** [comment]
So, ich kann dein Problem kein bisschen nach voll ziehen.
Die Vanilla Geräte funktionieren genau so wie sie sollen, der Kuhn Fronttank geht auf der Bahn nach unten
![fsScreen_2022_09_06_18_44_02](https://user-images.githubusercontent.com/27344744/188692276-4e32358e-ab78-4248-b6c4-f779cfded908.png)
und für das Wendemanöver wird er angehoben.
![fsScreen_2022_09_06_18_44_41](https://user-images.githubusercontent.com/27344744/188692285-5d6684e9-2a72-4bd7-bce9-d4b3826b5b6b.png)
Der Lemken Fronttank wird gar nicht erst abgesenkt.
![fsScreen_2022_09_06_18_45_59](https://user-images.githubusercontent.com/27344744/188692293-9c61a1ff-2805-41c2-b97e-a4e386f17e46.png)

Entweder du hast eine alte CP Version, oder du verwendest Mods, die nicht richtig gebaut sind/eingestellt sind.
Jedenfals orientieren wir uns an den Vanilla Geräten und die funktionieren, daher werden wir auch keine Anpassung vornehmen.

**Comment by Cornflix244** [comment]
> So, ich kann dein Problem kein bisschen nach voll ziehen. Die Vanilla Geräte funktionieren genau so wie sie sollen, der Kuhn Fronttank geht auf der Bahn nach unten ![fsScreen_2022_09_06_18_44_02](https://user-images.githubusercontent.com/27344744/188692276-4e32358e-ab78-4248-b6c4-f779cfded908.png) und für das Wendemanöver wird er angehoben. ![fsScreen_2022_09_06_18_44_41](https://user-images.githubusercontent.com/27344744/188692285-5d6684e9-2a72-4bd7-bce9-d4b3826b5b6b.png) Der Lemken Fronttank wird gar nicht erst abgesenkt. ![fsScreen_2022_09_06_18_45_59](https://user-images.githubusercontent.com/27344744/188692293-9c61a1ff-2805-41c2-b97e-a4e386f17e46.png)
> 
> Entweder du hast eine alte CP Version, oder du verwendest Mods, die nicht richtig gebaut sind/eingestellt sind. Jedenfals orientieren wir uns an den Vanilla Geräten und die funktionieren, daher werden wir auch keine Anpassung vornehmen.

Ich glaube wir beide reden hier aneinander vorbei, ich habe mich wahrscheinlich nicht genau genug ausgedrückt.
Das Hauptproblem ist, dass man mit dem heruntergelassenen Zusatztank keine Kurven mehr richtig fahren kann, da der Trecker vorne ein wenig aufgebockt wird. Ja, das ist natürlich nur der Fall bei dem Tank mit Reifenpacker der Fall, but still.
