### ISSUE TITLE
[Question]combine and baler convoy distance

### ISSUE THREAD

**Issue by pierrehicks** [Courseplay/Courseplay_FS22#1887]
So I have a combine and a baler on the same course and I'm trying to see if there is a way to change the distance that the baler follows the combine. At the moment it seems that there is a pre defined distance that they stay apart and while the multitool/convoy settings appear for multitool courses it is not showing when two vehicles have the same single tool course loaded. So I guess I'm asking if that is intentional or if I'm missing something?

**Comment by Tensuko** [comment]
The distance have to be set to the same on both tools.

**Comment by pierrehicks** [comment]
what im getting at is that the option to set the distance does not appear on either vehicle

**Comment by Tensuko** [comment]
Check global settings if the expert settings are active :)

**Comment by pierrehicks** [comment]
they are
