### ISSUE TITLE
[BUG_SP] Krone Big X only drives in circles or remains standing

### ISSUE THREAD

**Issue by Geranimo911** [Courseplay/Courseplay_FS22#189]
**Steps to reproduce**
Chop corn or mow grass with a Krone Big X.

**Actual behavior**
A course was created with a headland and the helper simply stops or drives in a circle.

**Expected behavior**
The helper should run the course normally.

**Screenshots**

Videos:
https://youtu.be/R9d0ZECwh-0
https://youtu.be/YBkzythHnvE

![1](https://user-images.githubusercontent.com/22646939/147521273-a27c1609-08bb-4dc0-a5af-843d28952e45.jpg)
![2](https://user-images.githubusercontent.com/22646939/147521276-af4c5679-ced6-4b01-a6f2-40b0308f0a55.jpg)

**Courseplay version**
Version used: 7.0.0.7 and before

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7782432/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Krone Big X

**Relevant script mods**
AD & VCA and a completely new map with only BetterTimeScale, Courseplay and PowerTools

**Comment by XPiRiJenZ** [comment]
Die Fehlermeldung "Helfer XY wird durch ein Objekt blockiert" kommt ja aus dem Standard-Spiel und hat nichts mit CP zu tun.

Vorschlag von mir wäre, dass man einen CP-Kurs lädt und dann über das neue Mini-HUD "Kurs am ersten Wegpunkt starten" auswählt und den Helfer einstellt.
Hast du das mal getestet?
Das könnte zumindest beim Gras mähen helfen, was bei mir zB ohne Probleme funktioniert.

**Comment by Tensuko** [comment]
Mit 7.0.0.10 sollte er auch einen Weg zum ersten Wegpunkt fahren, wenn dieser weiter weg ist, was es noch mal angenehmer machen sollte.
Bitte probieren und zurück melden, danke.

**Comment by Tensuko** [comment]
Should be fixed, remains Standing, depends, if he turned on all tools he watis for the trailer. It it is still on the way when you press start job.... well.... not rly sure but thats actually the part where Giants should drive.
