### ISSUE TITLE
[BUG_SP] Couple of things noted whilst trying the do Bale Wrapping/Collecting

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#1890]
Have noticed a couple of issues in game with the Courseplay feature of Bale Wrapping and Collecting. The first one is a UI issue where when you go into the Game Menu to create the Wrapping or Collecting task, there is some text that reads "Missing CP_BaleFinderJobParame" before it's cut off.

![fsScreen_2022_09_07_11_12_17](https://user-images.githubusercontent.com/13921716/188853702-c1922109-c8c7-4a9a-bba1-869f9e71c4be.png)

I also then find that when trying to wrap bales with the base game Kverneland 7850C Round Bale Wrapper,  Courseplay has the issue that everytime it drives to a bale it is aligning itself to the wrong place. Instead of actually lining up with the Bale Loading Trigger of the equipment, it's alighing to arm that swings inward to help lift the bale when it's actually in the trigger location. As a result Courseplay does not wrap any bales with this wrapper and just sits then blocked by the bales.

![fsScreen_2022_09_07_11_11_38](https://user-images.githubusercontent.com/13921716/188854625-fee68aad-2ed0-4814-a193-d22549b20380.png)

**Comment by Tensuko** [comment]
Ok that is some missing translation, we will check that.
The other things is an offset Issue. Will fix that.

**Comment by lcc1211** [comment]
I didn't think you could wrap straw bales.

**Comment by Tensuko** [comment]
It is not wrapping straw bales, its the offset that he want to show here.
