### ISSUE TITLE
[BUG_SP] Cotton harvester (Case Module Express 635 Base Game vehicle)

### ISSUE THREAD

**Issue by m0box** [Courseplay/Courseplay_FS22#1893]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Perform cotton harvest route with up/down centre pattern

**Actual behavior**
When performing the up/down part of the course, if the fruit is to the left of the vehicle, on unload the vehicle is blocked by the unloaded bale due to the vehicle wishing to perform the clear fruit manoeuvre to clear the left side for the pipe. Vehicle unloads to rear. When fruit is to the right of the vehicle unloading does not cause the blockage message.

**Expected behavior**
Unload bale and continue

**Screenshots**
![fsScreen_2022_09_08_11_00_44](https://user-images.githubusercontent.com/74186144/189094826-0e8292b0-5d5b-43d5-9cbd-e533cc5cb3ab.png)

**Courseplay version**
Version used: 7.1.0.3.

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9525893/log.txt)

Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. Wild West 16X by Cazz64

**Vehicles/ implements involved**
Which vehicle or implement? Case Module Express 635 Cotton Harvester
Mod yes/no NO

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive and VCA installed but not active at time of the log. Only the Case was running all other operations stopped.

**Comment by Tensuko** [comment]
Should be fixed in one of the next Releases. (Wich will be huge...)

**Comment by Tensuko** [comment]
Just combine issues:
#1779
