### ISSUE TITLE
Plow work width

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#19]
The work width of a plow won't set autoamtically. This is under investigation. Any more Tools where this is not working, pls let us know.

**Comment by kahpe** [comment]
Also Pöttinger Servo 25 plow does not turn when switching direction. Does not actually matter for end result. Steyr 8150 tractor on No Man's Land map, self made field with weird shapes. Haven't tested this much, plowing in progress 😄

**Comment by pvaiko** [comment]
Not clear what this issue is about, the course generator shows different (apparently correct) values for each plow I attach.

**Comment by kahpe** [comment]
Servo 25 shows something like 1.2 (?) meters working width in shop, cp shows something like 2.5(?) meters which seems to be correct and there are no unplowed stripes. Width is incorrect in shop? Not on my computer atm. so cannot check precisely. Headland did not reach edge of the field, but up/down was ok. Sorry for incomplete info.

**Comment by Resandise** [comment]
Krone Bix X 1180 with X-Collect 900-3, I have to set work width to 5.6 m to get it to work right.  Actually work width of 9 m

**Comment by Tensuko** [comment]
> Not clear what this issue is about, the course generator shows different (apparently correct) values for each plow I attach.

Maybe it got fixed now, will try it later.



> Krone Bix X 1180 with X-Collect 900-3, I have to set work width to 5.6 m to get it to work right. Actually work width of 9 m

That is not a plow and doesn't rly make sence. Can you explain that in more detail whats happening in an extra issue with screenshots and logfile ?

**Comment by Resandise** [comment]
> 

Posted new issue https://github.com/Courseplay/Courseplay_FS22/issues/128

**Comment by Tensuko** [comment]
> Not clear what this issue is about, the course generator shows different (apparently correct) values for each plow I attach.

When should it recalculate the workwidth ?

**Comment by S0MY** [comment]
Hello,

I do not know if this helps in the search of the topic "Plow work width", but I noticed the following:

Other working widths are also displayed in the VCA Mod. CP and VCA actually show the exact same widths in the request. 
With VCA you can edit the fields with automatic recognition of the working width without gaps. So I think that the requested working widths are correct.

Other Problem with Plows, like @kahpe in the Post 2 Days ago. When the helper arrives at the end of the track, he doesn't switch the direction of the plow. So one track is skipped and one is doubled. Experienced this with the "Pov 5XL" and "Ecomat". 

Thank you for your efforts and the quick implementation for the LS 22.

**Comment by kahpe** [comment]
Servo 25 rotated once, then stopped rotating in subsequent turns. Is this that FS22 bug still? I thought it was fixed in 1.2.

Also, work width 2,3m from CP works with Servo 25 plow as seen in screenshots. Shop indicates width 1,2m for it.

 CP v7.0.0.9.

![fsScreen_2021_12_29_08_55_12](https://user-images.githubusercontent.com/3214065/147635352-00b9ea54-e8f3-4f0a-b1a1-bbcfdc6c0663.png)
![fsScreen_2021_12_29_08_55_50](https://user-images.githubusercontent.com/3214065/147635360-bc99a49a-c6a7-45cb-918a-c5191bb3aa3d.png)
