### ISSUE TITLE
Taste um nur CP zu starten

### ISSUE THREAD

**Issue by Laudern** [Courseplay/Courseplay_FS22#190]
Wenn man am Feld startet ist man oft nicht sicher ob die Maschine der CP-Spur folgt oder dem Ingamehelfer.

Toll wäre eine Tastenkombination (z.B. Strg+H) mit der man dezitiert den CP-Kurs starten kann.

**Comment by dominiczeth** [comment]
Noch besser wäre es, wenn es eine Tastenkombi gäbe, zum Starten am Startpunkt (Shift +H). 
Das klappt manchmal nicht zuverlässig. 

Eine Anzeige, wenn CP aktiv ist, wäre noch gut ;)

**Comment by EiksYt** [comment]
> Wenn man am Feld startet ist man oft nicht sicher ob die Maschine der CP-Spur folgt oder dem Ingamehelfer.
> 
> Toll wäre eine Tastenkombination (z.B. Strg+H) mit der man dezitiert den CP-Kurs starten kann.

Ich finde genau das wäre eine Top Innovation xD weil H kann Ingame Helfer , AIVE Helfer  oder CP-Helfer sein. 
Wir sehen was kommt . Danke für die Top Arbeit CP-Team  😉

**Comment by Tensuko** [comment]
Schaut euch mal das neue Mini HUD an, welches immer CP startet. (Eventuell muss die Taste erst belegt werden).
Hoffe das schafft erst mal Abhilfe.

**Comment by EiksYt** [comment]
Danke !!! Also für mich macht es in 10 Tests das was es soll. Vielen Dank !!! 😊

**Comment by Laudern** [comment]
Ja, hilft erstmal. Dankeschön!

Trotzdem würd ich den Vorschlag gerne offen lassen.

**Comment by Tensuko** [comment]
Jup, lass ich auf.

**Comment by franky-bb** [comment]
Super Super Super. CP geht in die richtige Richtung. Hab es auf die Einfg Taste gelegt.

**Comment by kaufm30** [comment]
Bei aktivem Mini Hud ist allerdings die Kamera eingefroren.

**Comment by schwiti6190** [comment]
> Bei aktivem Mini Hud ist allerdings die Kamera eingefroren.

Das wird so bleiben da man ja auch die maus benutzten kann zu anklicken der Einstellungen :)

**Comment by Th301** [comment]
@Tensuko : Wie findet man das Mini-HUD? In meinen Key-Bindings kann ich nur Debug-Tasten belegen aber keine für ein HUD :(

**Comment by santaranger** [comment]
> Schaut euch mal das neue Mini HUD an, welches immer CP startet. (Eventuell muss die Taste erst belegt werden). Hoffe das schafft erst mal Abhilfe.

Den CP Worker kann man damit zuverlässig starten, aber wie starte ich zuverlässig den normalen AI Worker, wenn ich einen Kurs geladen habe usw.?

**Comment by Tensuko** [comment]
Pls try 7.0.0.13
Reopen if Issue persists.

**Comment by santaranger** [comment]
In 7.0.0.14, hitting "H" will still start CP if course is loaded. Commit 60e412a had me hoping this was removed and CP is only started using the new hotkey instead.
