### ISSUE TITLE
[BUG_SP] Unable to change horizontal offset

### ISSUE THREAD

**Issue by trakkson** [Courseplay/Courseplay_FS22#1903]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Perform fieldwork with [JD disc plow](https://www.kingmods.net/en/fs22/mods/john-deere-670-series-single-offset-disks)

**Actual behavior**
CP sets incorrect 0.7m offset and doesn't allow me to change it. I assume this is because the implement is treated as a plow. The implement is symmetrical, but is treated as assymetrical, and as such is unusable because I'm unable to change the offset back to 0.

**Expected behavior**
 While I don't expect CP autodetect to be perfect, I think I should at least be able to manually set the offset for the "plow". 

**Courseplay version**
Version used: 7.1.0.3

**Map**
Map played on: Green Valley Nebraska

**Vehicles/ implements involved**
[JD disc plow](https://www.kingmods.net/en/fs22/mods/john-deere-670-series-single-offset-disks) (MOD)

**Comment by Tensuko** [comment]
Not supported mod source.
Also, if the offset is incorect for a "plow" (wich it isn't!) then the mod is faulty.

Try it with individual vehicle configuration: https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.
