### ISSUE TITLE
Show Start/Stop on Map for loaded Courses

### ISSUE THREAD

**Issue by BigNoggin** [Courseplay/Courseplay_FS22#191]
Is it possible to show the start and stop locations when looking at the map when starting worker? I have noticed issues that would be avoided if you were able to start the worker at the start.

**Comment by rohne83** [comment]
would also be helpful for setting proper start/endpoints for the course generator. Especially when starting on fieldrows rather than headland, it's really hard to tell where the actual start point will be then.
