### ISSUE TITLE
Connected thinks its wrapping bales

### ISSUE THREAD

**Issue by kwguk** [Courseplay/Courseplay_FS22#1911]
Using ver7.1.0.4

So im finding that certain tractors or combines both vanilla and modded when you connect them to something you get the wrap/load bales CP box, i havent tested very many machines but id say of the 6 i did half were showing the bale thing.
![20220918143752_1](https://user-images.githubusercontent.com/11178621/190906696-1f54bdfa-60c7-4b01-b9b8-3935921690d7.jpg)
![20220918143758_1](https://user-images.githubusercontent.com/11178621/190906724-15e55ec2-a0d2-4d76-a8eb-6439fd64caf1.jpg)
![20220918142339_1](https://user-images.githubusercontent.com/11178621/190906797-82fa8da5-21ac-455f-ae60-568de2684289.jpg)

**Comment by Tensuko** [comment]
Template?
logfile?
What tools exactly?
Mods? -> Are they from ModHub and correct?

**Comment by kwguk** [comment]
Sorted
It was map specific
