### ISSUE TITLE
[BUG_SP] Error: Running LUA method 'draw' - dataS/scripts/specialization/SpecializationUtil.lua(15) : Error: Event 'onCpDrawHudMap' is not registered for type 'locomotive'!

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS22#1914]
In der CP Version v7.1.0.4 ist mir aufgefallen, dass man den Zug nicht mehr so benutzen kann, wie gewohnt. Folgender Fehlereintrag in der log.txt:

2022-09-19 12:57 Error: Running LUA method 'draw'.
dataS/scripts/specialization/SpecializationUtil.lua(15) : Error: Event 'onCpDrawHudMap' is not registered for type 'locomotive'!

Dieser Eintrag ist sehr oft vorhanden.
Das bedeutet, man kann die Waggons nicht mehr einzeln zum befüllen anwählen. In der CP Version v7.1.0.3 ist alles noch o.k.

**Comment by Tensuko** [comment]
Oh ja das ist dann ein bug, danke fürs melden.

**Comment by GMNGjoy** [comment]
I wanted to add another metric to this ticket - I'm seeing the same issue as above when using CP `7.1.0.4` on the HofBergmann 1.0.0.1 map - the custom bale storages (which are actually enterable vehicles) is causing the same error as reported with `7.1.0.4`, but works as expected with `7.1.0.3`

>  dataS/scripts/specialization/SpecializationUtil.lua(15) : Error: Event 'onCpDrawHudMap' is not registered for type 'FS22_HofBergmann.mapBaleStorages'!
> 2022-09-23 12:44 Error: Running LUA method 'draw'.

I'm guessing that it has to do with the same issue as above; if not, i'll be happy to report as a separate issue.

**Comment by Tensuko** [comment]
Should be fixed in 7.1.1.0
