### ISSUE TITLE
[BUG_SP] - Combines can't generate a course - option missing from worker menu

### ISSUE THREAD

**Issue by stocky789** [Courseplay/Courseplay_FS22#1916]
**Steps to reproduce**
Generating a course with a combine

**Actual behavior**
When you are opening the worker window to create and generate a course in a combine - there is no button or option to generate a course. All other types of field vehicles seem to work but not combines.

**Expected behavior**
A button to appear

**Screenshots**
https://imgur.com/a/I6U1BHv

**Courseplay version**
7.1.0.4

**Map**
Green Valley Nebraska 4x

**Vehicles/ implements involved**
Which vehicle or implement? John Deere SiiD Modding S670 and X9 1100 JHHG Modding
Mod yes/no ? Yes

**Relevant script mods**
Autodrive is enabled

**Comment by Tensuko** [comment]
And where is the logfile?

**Comment by ambu684** [comment]
Experiencing the same issue but started with just combine now seems to be all field work no option to generate course ?

**Comment by stocky789** [comment]
> And where is the logfile?

Dont know how to get one 
But its pretty straight forward to replicate 

You fire up a combine next to the field
You open the worker menu and put your field location and target location down 
You have the CP: Fieldwork option selected up the top right and WAZOOM! Nothing... No button to generate a course 

Everyone I know using this version has the same issue

**Comment by stocky789** [comment]
> Experiencing the same issue but started with just combine now seems to be all field work no option to generate course ?

I haven't had an issue with anything else yet touch wood 
Just the combines

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki#how-to-provide-a-nice-and-sexy-bug-report

You can find it in the following directory:
Windows (7 and above):
C:\Users\[YOUR USER NAME]\Documents\My Games\FarmingSimulator2022\log.txt
Mac:
Mac OS X Download/DVD/Steam-Version:
/Users/[YOUR USER NAME]/Library/Application Support/FarmingSimulator2022/log.txt
Mac OS X AppStore-Version (Mac OS X 10.7 and newer):
/Users/<your username>/Library/Containers/com.focus-home.farmingsim2022/Data/Library/Application Support/FarmingSimulator2019/log.txt
Upload the log:
Go to [Gist](https://gist.github.com/) or [Pastebin](http://pastebin.com/), and add your log content by either using copy and paste, or dragging the log.txt file into the text area (Gist only).
Post the link to your log in the issue.
**You can also drag and drop the log.txt into the comment box.**

**Comment by Tensuko** [comment]
I will have a look...

**Comment by Tensuko** [comment]
Can't reproduce. Everything working just fine.
Thats why I ask for a logfile and I wonder what 

> Everyone I know using this version has the same issue

Have in common, I am sure there is a modconflict and so I tell you to check your mods and remove them one by one.
Start with combine experience in case you got it installed. (logfile....)

![fsScreen_2022_09_21_10_19_34](https://user-images.githubusercontent.com/27344744/191453198-243e8ce2-5098-4e0e-b95c-9500424d1139.png)

**Comment by stocky789** [comment]
> Can't reproduce. Everything working just fine. Thats why I ask for a logfile and I wonder what
> 
> > Everyone I know using this version has the same issue
> 
> Have in common, I am sure there is a modconflict and so I tell you to check your mods and remove them one by one. Start with combine experience in case you got it installed. (logfile....)
> 
> ![fsScreen_2022_09_21_10_19_34](https://user-images.githubusercontent.com/27344744/191453198-243e8ce2-5098-4e0e-b95c-9500424d1139.png)

Yep your right actually - out of curiosity I went into another of my multiplayer servers which is running the Western Australia 4x map and using all Case equipment and its working fine 
I'll try and get a logfile for you tonight for my other map and see what is going on

**Comment by stocky789** [comment]
So i noticed that in the game my combines are stuck on bale collection mod according to the mini hud. I bought different headers and different combines and still have the same issue. It seems to be this map with the latest version. 

Below is a link for the logfile

https://drive.google.com/file/d/1oiEeL9-0QoUaCGzB8pkODV1CP3XvJcok/view?usp=sharing

**Comment by stocky789** [comment]
So it appears to be universal autoload causing it. As soon as I disable that mod it begins to show the course generator. I'm wondering why this exact version of courseplay doesnt like this mod on this map? 

Because on my western australia 4x multiplayer server both these mods are working fine together

**Comment by Tensuko** [comment]
Might need to wait for the latest version.

**Comment by Tensuko** [comment]
https://github.com/loki79uk/FS22_UniversalAutoload

**Comment by stocky789** [comment]
> https://github.com/loki79uk/FS22_UniversalAutoload

That's awesome - thanks man!
