### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by shuoshuo1203** [Courseplay/Courseplay_FS22#1917]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
      The Haystack will stop the car from reversing
**Expected behavior**
   I wish the obstacle detector would move further back and not be blocked by the haystacks
**Screenshots**
   
![@ISA)IXB 7K1AF)B1I~KW0P](https://user-images.githubusercontent.com/48911914/191506352-becd85a9-8329-4b38-9d68-ebe421033127.png)
![CTX`VWP0{Q798392~$B5KRL](https://user-images.githubusercontent.com/48911914/191506364-637fe542-b811-437c-9402-a0422dffe26e.png)
![YO CRUIMVQ0`I2JDZLH57RI](https://user-images.githubusercontent.com/48911914/191506373-6762f087-ddcc-4970-be79-f878a2adb5f5.png)

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by shuoshuo1203** [comment]
I use automatic translation editing, I hope you can understand, thank you, not very use, more inclusive

**Comment by Tensuko** [comment]
#1863

**Comment by Tensuko** [comment]
Workarround:
turn off turn on field.
