### ISSUE TITLE
[BUG_SP] AI Helper cost is counted by Precision Farming even though CP AI Helper cost is set to 0%

### ISSUE THREAD

**Issue by mariokoehler** [Courseplay/Courseplay_FS22#1918]
This is not a big deal, but maybe its easy to fix.

when you use Precision Farming the AI Helper cost is "logged" for each of your fields. And Precision Farming is counting AI Helper costs, even though CP's AI Helper cost is set to 0%.

Not sure if this needs fixing on PF' or CP's side, in any case, like i said, it's not a big deal. I just wanted to make you aware of it.

**Comment by bjklein91** [comment]
It's still going to cost you for help, that just means it's going to cost you 0% on top of what the in-game helper cost

**Comment by Tensuko** [comment]
> It's still going to cost you for help, that just means it's going to cost you 0% on top of what the in-game helper cost

Wrong. 0% is 0% Cost.

@mariokoehler 
So it is just a Number that counts up in the PF Info but you don't pay for anything?

**Comment by Resandise** [comment]
This was the same on FS19 with precision farming.  It part of PF that is the problem, not CP.  PF automatic calculates the AI helper cost regardless if you pay or not.  I doubt CP can do anything about it.  It does it with AD unload if your using AD unload combine instead of CP unload.

**Comment by Thalley** [comment]
I think this is a bug in Precision Farming. The same happens if you are e.g. using your own potatoes as seeds for planting new potatoes, and PF still think you pay for it (making the values reported by PF wildly inaccurate).
