### ISSUE TITLE
[Feature] Eckverhalten Mähdrescher und Ladewagen

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1924]
**What is the problem this feature/enhancement solves?**
der Mähdrescher setzt im Vorgewende bei scharfen Ecken unnötig zuweit zurück,
der Ladewagenfahrer hört anfangs zu früh auf zu sammeln und müsste nach der Wende danach auch nicht soweit zurücksetzen
(Bilder weiter unten)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

der Drescher drischt bis zur Feldkante:
![fsScreen_2022_09_22_18_03_04](https://user-images.githubusercontent.com/24860501/191802775-5e4b60c2-9ed2-4cdd-bfce-5c328446c657.png)

hier sieht man schon den workstart für später an der Feldkante, die wäre aber besser an der Fruchtkante plaziert:
![fsScreen_2022_09_22_18_03_12](https://user-images.githubusercontent.com/24860501/191802800-c7e067f3-efc8-48d2-824b-1866e050e6c3.png)
somit müsste der Drescher nicht soweit zurücksetzen:
![fsScreen_2022_09_22_18_03_24](https://user-images.githubusercontent.com/24860501/191802980-b2f523c9-383d-48e8-9385-935e78ce6004.png)

auch im zweiten vorgewende:
![fsScreen_2022_09_22_18_13_28](https://user-images.githubusercontent.com/24860501/191803147-f5665656-9738-4aeb-8c04-643f3244298e.png)
![fsScreen_2022_09_22_18_13_46](https://user-images.githubusercontent.com/24860501/191803184-84b23ef9-6030-42a9-910c-67c3741d8354.png)
![fsScreen_2022_09_22_18_13_54](https://user-images.githubusercontent.com/24860501/191803240-21a230bb-f0e1-4533-b34b-703eafa53654.png)
![fsScreen_2022_09_22_18_13_56](https://user-images.githubusercontent.com/24860501/191803257-946e6c4a-e357-4da2-8b26-e557eebefead.png)
![fsScreen_2022_09_22_18_14_02](https://user-images.githubusercontent.com/24860501/191803290-e3c08355-8ec5-445b-a3f0-a771cbcaa409.png)
![fsScreen_2022_09_22_18_14_11](https://user-images.githubusercontent.com/24860501/191803302-dc1ec679-3f33-4b94-8dfa-83265db047ac.png)

Der Ladewagenfahrer hört aber zu früh auf:
![fsScreen_2022_09_22_18_29_17](https://user-images.githubusercontent.com/24860501/191803369-48a3cf0f-9948-450c-9222-a14a166da69f.png)
![fsScreen_2022_09_22_18_29_19](https://user-images.githubusercontent.com/24860501/191803388-8cfb520b-2700-4774-966d-a0543f86f427.png)
![fsScreen_2022_09_22_18_29_21](https://user-images.githubusercontent.com/24860501/191803409-ed5c0961-93e0-4310-95f3-df89828973ed.png)
![fsScreen_2022_09_22_18_29_29](https://user-images.githubusercontent.com/24860501/191803417-f4118396-7d7a-46d5-9682-356c69da8030.png)
der könnte auch ohne weiteres bis zur Feldkante vor sammeln (wie der Drescher)
![fsScreen_2022_09_22_18_29_35](https://user-images.githubusercontent.com/24860501/191803532-3eb2216f-a622-4988-9018-0b6433e17c30.png)
dann müsste er nach der Wende nur soweit zurücksetzen:
![fsScreen_2022_09_22_18_29_48](https://user-images.githubusercontent.com/24860501/191803542-ee6cf11d-e6cf-4b42-9b80-9c65f5d5d4e1.png)
und nicht soweit:
![fsScreen_2022_09_22_18_29_53](https://user-images.githubusercontent.com/24860501/191803737-4a49b504-96c2-4234-ac88-8f302203c5d9.png)
und würde nicht soviel Stroh zurücklassen:
![fsScreen_2022_09_22_18_30_01](https://user-images.githubusercontent.com/24860501/191803820-5c32ec8c-1898-49a7-832a-962283f39e6e.png)

nur als anregung
lg
andreas

**Comment by Tensuko** [comment]
Hi Andreas,
sry aber da werden wir nichts dran ändern.

Einzige Idee ist vorher Schwaden, oder die Strohablage nur in der Mitte einschalten (Fahrzeugeinstellung im CP Menü).
Die Geräte arbeiten nun mal so am besten, dass die Strohablage dann nicht 100% passt ist klar.

Wir haben eine Idee für eine etwas andere Lösung um Hinterkopf aber das steht ganz weit hinten an...
Daher noch mal sry, auch wo du dir mit der Dokumentation so viel Mühe gegeben hast, aber da muss ich leider nein sagen.

**Comment by andreasthu** [comment]
Ok, ist ja nur ein request.
Ärgert mich bei den dreschern zwar das die soweit hinten raus fahren, wenn grad ein baum oder so steht, kann ich aber verschmerzen, wen. Ihr das im hinterkopf behaltet.
Freu mich schon auf morgen, da werd ich euren combine unloader mal testen.
Lg
Andreas
