### ISSUE TITLE
[BUG_SP] Unable to generate courses, vehicles stuck in collect/bale mode

### ISSUE THREAD

**Issue by GMNGjoy** [Courseplay/Courseplay_FS22#1925]
**Steps to reproduce**
1. Update / Install Courseplay 7.1.0.4
2. Load in to vehicle (appears random which vehicle) with or without implement
3. CP overlay lists "collecting/wrapping bales", no course
4. Attempt to generate CP course from worker menu
5. CP: Generate New Course button does not appear

**Actual behavior**
Unable to generate courses on multiple tractors / trucks

**Expected behavior**
Expected the ability to generate CP courses

**Screenshots**

`7.1.0.3` CP overlay normal
![fsScreen_2022_09_22_11_47_49](https://user-images.githubusercontent.com/107238894/191827949-d6c6483e-cbc4-431d-86d4-21c86eadaf35.png)
`7.1.0.3` CP: Generate Course button available
![fsScreen_2022_09_22_11_48_16](https://user-images.githubusercontent.com/107238894/191827952-e9908151-931e-4ad1-bd64-16f75ab9e16a.png)

`7.1.0.3` CP overlay stuck in bale mode
![fsScreen_2022_09_22_11_44_11](https://user-images.githubusercontent.com/107238894/191827943-9bf4f7fc-b224-4563-ae77-a6d5f2318b3b.png)
`7.1.0.4` CP: Generate Course button available
![fsScreen_2022_09_22_11_44_42](https://user-images.githubusercontent.com/107238894/191827946-3ec1f2d8-34d1-474d-8d28-f13f08a1c484.png)

**Courseplay version**
Version used: 7.1.0.4

**Log**
[log_cp-7.1.0.4.txt](https://github.com/Courseplay/Courseplay_FS22/files/9628667/log_cp-7.1.0.4.txt)

**Map**
Calmsden

**Vehicles/ implements involved**
MOD: U400 w/ Spreader attachment [https://www.kingmods.net/en/fs22/mods/mercedes-unimog-u400]
MOD: Fendt Vario 1000 w/ basegame seeder (no implements will work with this vehicle) [https://www.farming-simulator.com/mod.php?lang=en&country=hu&mod_id=239614&title=fs2022]

**Relevant script mods**
Autodrive 2.0.0.7 installed 
Enhanced Vehicle

**Comment by Tensuko** [comment]
Did you try to reattch with the U400?

The Fendt is from Custom Modding and I don't know what those guys do with their mods, but we always had problem with their mods.... also in FS19.

**Comment by GMNGjoy** [comment]
Yes - tried attaching / reattaching. Attempted to reset vehicles to shop (both).

> 7.1.0.4
> - Basic universal autoloader implementation.

I'm curious if it may have something to do with the latest changes to do with UAL (as this vehicle has an attachment (not in use currently) that has a UAL config, although the current configuration of the vehicle does not. 

Unknown why the Fendt Vario 1000  from CM same issue, but the U400 may have the issue related to whatever code was added for UAL.

**Comment by GMNGjoy** [comment]
I'd suspect that the CM Vario 1000 (and the U400 for that matter) are having the issue because of `tensionBelts`.

UAL automatically sets up the UAL specialization for any vehicle that has a `tensionBelts` specialization somewhere in it's configurations, only for the currently selected configuration. Since the UAL only works when that specific configuration is active, I would imagine that CP would also have to detect if the configuration was currently active also... and not just that the specialization exists. 

for the Fendt Vario 1000 - the modDesc has this:
```
<vehicleTypes>
        <type name="vario1000" parent="baseDrivable" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua" >
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
			<specialization name="cover" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
        </type>
    </vehicleTypes>
```
... why the hell would they add all of those specializations to a _tractor_? that doesn't make any sense at all.

... which reads to me that they are adding `tensionBelts` specialization to the machine, which is in turn automatically adding a UAL specialization by the UAL scripts. Then, the latest code from CP is looking for that specialization (regardless if it's currently active) and setting that vehicle to bale collection mode.

I suspect that the above would be why the Vario 1000 is already in bale collection mode... even without anything attached.

![fsScreen_2022_09_22_13_10_09](https://user-images.githubusercontent.com/107238894/191841639-c23941f4-6f73-4412-beb1-244d69f894ac.png)


---

For a good example of a non-mod Base-game vehicle where this logic path has an issue:

Welger DK115 - A trailer that has a bale configuration (UAL) and a fill configuration (not UAL)

![fsScreen_2022_09_22_13_15_37](https://user-images.githubusercontent.com/107238894/191842808-e3776caa-3ded-4217-8e7e-4bd68b7a4074.png)

As you can see in the screenshot above - the same issue is happening. UAL (and adding the CP bale collection mode) should _only_ apply when the UAL config is actually currently active.

**Comment by Tensuko** [comment]
Thats something for @schwiti6190 then.

Thanks for the deeper check.

**Comment by schwiti6190** [comment]
@GMNGjoy Hi there,
Thank you very much for your great help at finding the problem. 
With the latest push onto the main branch, the problem should be fixed.
Can you check it out and see if the generation is working now and if the UAL autoload still works?

**Comment by daFreeMan** [comment]
I just tried to create my first course with 7.1.0.4 and ran into the same issue. I'm using a Siid Modding John Deere X9 combine and the Custom Modding 60' Honey Bee header. 

If there's an interim build that I can test out the fix noted above, I'd be more than happy to. Otherwise, I'm reverting to 7.1.0.3 until .5 is released.

**Comment by loki79uk** [comment]
Sorry, I wasn't aware of this issue until today, or I would have replied sooner!

I made a change on UAL so that `self.spec_universalAutoload` is set to nil when the vehicle configuration is invalid.

The `self.spec_universalAutoload.isAutoloadEnabled` flag is now deprecated, and I use `self.spec_universalAutoload == nil` instead.  If this is not compatible with your latest fix, then I am happy to roll back changes.
