### ISSUE TITLE
[BUG_SP] Ladewagen, Kalk/Düngerstreuer, Sähmaschinen,.. fangen IMMER beim ersten WP an

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#1926]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
neues main, combine unloader

**Actual behavior**
A clear and concise description of what happen.
die Kadewagen, Kalk/Düngerstreuer, Sähmaschinen,.. fangen IMMER beim ersten WP an zu fahren wenn sie von AD zum Feld zurückkommen

**Expected behavior**
sie sollten dort weitermachen, wo sie aufgehört haben
(mit dem alten main von vor zwei tagen funktioniert das noch)

**Screenshots**
xxx

**Courseplay version**
Version used: 
aktuelle main mit combine unloader

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. hobos hollow 4x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Ladewagen, Kalkstreuer, Sähmaschine

**Relevant script mods**
Mods like Autodrive or VCA and so on.
CP, AD, 

lg
andreas

**Comment by Tensuko** [comment]
Lieber Andreas, du bist doch nicht erst heute auf GitHub Unterwegs und du kennst dich doch auch mit unseren Debugs aus.
Ein logfile mit den debugs wird hier sicher helfen....

**Comment by andreasthu** [comment]
oh sry tensuko,
dachte das hätte ich.
war aber zwischenzeitlich wieder mit der vorherigen version unterwegs, daher hat es etwas gedauert.
hier die log:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9634492/log.txt)

bei zeile 1777 fängt der Ladewagenkurs an.
bei zeile 1908 ist der Ladewagen voll (wp 2343+2344)
bei zeile 1913 ist "best return is 2340"
danach fährt AD ins Hayloft abladen, kommt zurück
und bei zeile 1916 kommt er zum feld zurück und sucht dem Kurs, beginnt aber wieder bei wp2, anstelle von wp 2340
zeile 2443: 2022-09-23 16:21 :41 [dbg1 lp31084] 6300 CVT/513: WORKING: Starting a course, at waypoint 2 (of 4801).

das ist jetzt mit dem allerneuesten main (23.09.2022 12:18)
wenn ich wieder die ältere version verwende, vom Montag (19.09.2022. 21:22) dann beginnt der Ladewagen wo er aufgehört hat.
lg
andreas

**Comment by Tensuko** [comment]
Super, danke.
Dann können wir uns das angucken.

**Comment by Tensuko** [comment]
#1452

**Comment by Selyria** [comment]
@Tensuko Sind 1926 und 1452 nicht 2 Unterschiedliche Probleme  ?

In 1452 geht es darum das wenn man 2 Sämaschinen hat und diese auf demselben Feld einer links und eine Rechts fahrend nach dem nachladen durch Autodrive nicht wieder zum selben punkt zurückfahren z.b. Die Sämaschine von Links fährt zurück auf die Linke spur aber die Sämaschine die Rechts fuhr fährt auch nach Links.

Hier geht es doch darum das diese am ersten Wp wieder anfangen.

**Comment by Tensuko** [comment]
Ich habe sie nicht ohne Grund zusammen gelegt.

**Comment by andreasthu** [comment]
ist das jetzt eigentlich ein globales Problem, oder hab das nur ich oder einige wenige?
oder ev ein modkonflikt mit AD z.b.?
lg
andreas

**Comment by masneoquil** [comment]
I have the same problem too.

**Comment by Selyria** [comment]
@andreasthu Sollten alle haben die es so nutzen wie wir

**Comment by andreasthu** [comment]
@Tensuko 
Hab mich grad mit dem user felsbrunn im giants forum ausgetauscht.
Er hat diese probleme nicht, bei ihm finden die fahrzeuge den richtigen wegpunkt.
Unser unterschied, er verwendet temporäre Kurse,  ich gespeicherte (da ich mit dem ingame editor immer Kleinigkeiten verändere).
https://forum.giants-software.com/viewtopic.php?f=955&t=152586&start=6660#p1538606
Kann es daran liegen, werden temporäre kurse anders behandelt als gespeicherte?
Lg
Andreas

**Comment by Tensuko** [comment]
Hmm wäre das jetzt alles auf einem MP Server hätte ich eine Vermutung, aber das ist ja nicht der Fall.
Aber danke fürs bescheid sagen das hilft eventuell weiter.

**Comment by MeRida2104** [comment]
Ich habe das gleiche Problem im SP. Es macht bei mir keinen Unterschied, ob der Kurs ein gespeicherter oder ein temporärer ist. In beiden fällen fährt CP zum ersten Startpunkt, nachdem er von AD zum Auffüllpunkt gefahren ist.

**Comment by UnknwnArtst** [comment]
Bei mir das selbe Problem. Tauchte erst mit der aktuellen Version auf. Map ist die „Multimap“ in ihrer aktuellen Version, sowie Autodrive.

Fahrzeug und gekoppeltes Gerät was nachgefüllt werden muss spielt dabei keine Rolle. Sobald AD dazwischen geschaltet ist fängt er immer von vorne an.

Habe auch schon die Einstellungen „letzter“ und „nahester“ ausprobiert. Macht keinen Unterschied.

Auffällig ist nur wenn zb ein Grubber o.ä. hinten dran hängt und CP schickt das Fahrzeug zum nach tanken startet dieser wieder korrekt am letzten Wegpunkt.

**Comment by Tensuko** [comment]
Should be fixed and also fix the MP Issue with left/right.
You got to set the start point to First waypoint when you want to start the course.
Nearest will definitly take the nearest Waypoint!

**Comment by andreasthu** [comment]
Hallo @Tensuko 
bis v 7.1.0.4 war es noch so, das CP (beim anfahren mit AD) von sichaus den ersten wegpunkt genommen hat - egal was im hud eingestellt war -  wenn der kurs frisch geladen bzw generiert wurde und wenn er nachgefüllt hatte, wieder am letzten wegpunkt weitergemacht hat.
nun ist es also so, das man im hud also "erster Wegpunkt" manuell einstellen muss, damit er am ersten wegpukt beginnt?
das ist eine umstellung, weil wenn man nun abspeichert und später das spiel weiterspielt, muss man bei allen cp fahrern die gerade eine Feldarbeit machen im hud von "erster Wegpunkt" auf "nächster Wegpunkt" umstellen bevor man diese startet
(ansonsten fahren sie ja zu wp1 und beginnen von vorne).
wenn man nun mit der arbeit fertig ist, muss man im hud wieder "erster Wegpunkt" einstellen, und sie zum nächsten feld schicken.
ich frage nur, weils nun mit 7.1.1.2 eher komplizierter wurde als einfacher (so wie bei v 7.1.0.4) 
bei 7.1.0.4 hatte ich daher immer "nächster wegpunkt" im hud eingestellt, weil der cp fahrer, wenn er von AD kam, wusste das er bei ersten wp beginnen soll.
lg
andreas

**Comment by MeRida2104** [comment]
Da kann ich Andreas nur beipflichten. Zuvor war es eindeutig einfacher gelöst. Es war völlig egal, ob im Mini HUD "nahester", "erster" oder "letzter" Wegpunkt eingestellt war. Wenn AD zum ersten mal zum Feld fährt, wird immer der erste Punkt genommen. Nun ist es so, dass der Punkt genommen wird, der im Mini HUD eingestellt ist. Auch nach Spielneustart wurde beim erneuten anfahren als Feld der letzte Wegpunkt genommen. Nun wird die zuletzt eingestellte Option genommen.

Bitte ändert das wieder auf den Zustand von 7.1.0.4. Diese Änderung konnte nicht in eurem Sinne gewesen sein. Sie macht die ganze Funktion deutlich komplizierter.

**Comment by MeRida2104** [comment]
@Tensuko kannst du hierzu noch etwas sagen? (siehe Beiträge von @andreasthu und mir). Ich habe noch nicht getestet wie es mit der neuen 7.1.1.3 abläuft, allerdings war auch im Changelog zu dem Thema nichts erwähnt.

**Comment by MeRida2104** [comment]
Das Problem scheint immer noch zu bestehen. Sprich:

1. Szenario: Erste Anfahrt zum Feld. Im CP Mini-HUD ist auf "Nahester Wegpunkt" gesetzt. CP startet beim nahesten Wegpunkt. In 7.1.0.4 wurde immer der Erste Wegpunkt von CP genutzt. Egal was im Mini HUD eingestellt war.

2. Szenario: Erste Anfahrt zum Feld. Im CP Mini-HUD ist auf "Erster Wegpunkt" gesetzt. CP startet beim ersten Wegpunkt. Alles korrekt.

3. Szenario: Erste Anfahrt zum Feld. Im CP Mini-HUD ist auf "Letzter Wegpunkt" gesetzt. CP startet beim ersten Wegpunkt. Alles korrekt.

4. Szenario: Zweite Anfahrt zum Feld. Im CP Mini-HUD ist auf "Nahester Wegpunkt" gesetzt. CP startet beim letzten Wegpunkt. Alles korrekt.

5. Szenario: Zweite Anfahrt zum Feld. Im CP Mini-HUD ist auf "Erster Wegpunkt" gesetzt. CP startet beim letzten Wegpunkt. Alles korrekt.

6. Szenario: Zweite Anfahrt zum Feld. Im CP Mini-HUD ist auf "Letzter Wegpunkt" gesetzt. CP startet beim letzten Wegpunkt. Alles korrekt.

Bedeutet: Seit CP V1.7.0.0 führt die Einstellung "Nahester Wegpunkt" im CP Mini-HUD nicht mehr dazu, dass bei der ersten Anfahrt auch der erste Wegpunkt gesetzt wird. Bei allen anderen Szenarien ist alles beim alten geblieben. Bedeutet: Man muss derzeit explizit darauf achten welchen Wegpunkt-Start man im CP Mini-HUD eingestellt hat. Ansonsten wundert man sich plötzlich, dass nur im Zweifel das halbe Feld bearbeitet wurde. Das kann doch nicht in eurem Sinne sein @Tensuko ?

**Comment by Tensuko** [comment]
CP muss beim ersten start mit AD auf erster WP gestellt werden. Danach funktioniert es wie gewohnt.
Nach save restart auf nahesten, das ist halt so und geht nicht anders. Wir werden daran auch nichts verändern!

Das ist ganz exakt in unserem Sinne.
Warum jetzt so getan wird, als sei es ein Weltuntergang, dass man egal ob von alleine oder mit AD CP gestartet wird darauf schaut, dass das hud auf ersten WP steht kann ich null nachvollziehen.

Vorteil bei uns ist das die ganze AD CP Sache so auch mit multitool fehlerfrei auf dem dedi server funktioniert.

**Comment by Tensuko** [comment]
Zustand vor 1.1.1.4? Also komplett verbuggt im MP mit multitool und immer zum ersten WP ? No way!

**Comment by Tensuko** [comment]
Erster start - erster WP.
CP start mitten auf dem Feld - nahesten.

Thats it.

**Comment by andreasthu** [comment]
Naja, weltuntergang nicht.
wenn ich mit AD zum Feld fahre, und CP mit erstem Wegpunkt starten lasse, funktioniert es so wie es soll -> CP fängt am ersten Wegpunkt zu arbeiten an.
ABER: wenn ich nun den cp helfer unterbreche, wegen was auch immer, und ihn wieder einstelle, will CP natürlich mitten vom Feld wieder den ersten wegpunkt ansteuern, das ist eben blöd, wenn man in dieser situation vergisst, von erster auf nächster oder letzter zu schalten. 
Dasselbe, wenn ich abspeichere und wieder neu lade, dann haben alle cp fahrer natürlich erster Wegpunkt eingestellt. D.h. umschalten auf nächster und startet,  ansonsten fahren sie natürlich zum 1.wp.
Wenn man nun so einen cp fahrer zum nächsten feld schickt aber nicht drauf achtet das da grade nächster eingestellt ist, fängt der dann natürlich nicht am wp1 an.
Es ist nur so, das es bis 7.0.4 eben so war, 
Meine cp fahrer waren im hud alle auf nächster wp eingestellt,  ad fuhr hin, cp erkannte die erste anfahrt und begann bei wp1.
Stoppte ihn ihn und stellt ihn wieder ein, wurde nächster wp aus der hud einstellung genommen.
Fuhr ich mit ad zum nächsten Feld, mit einem neuem kurs, begann cp wieder bei wp1.
So waren wir es eben gewohnt. Wieso dieses funktionierende system umgestossen wurde, ist unverständlich für uns.
Kg
Andreas

**Comment by MeRida2104** [comment]
Natürlich ist das kein Weltuntergang, aber etwas mehr (für uns unverständliche) Komplexität. Wenn das für euch ein Problem löst, das ihr sonst nicht beheben könnt, dann verstehe ich das für meinen Teil sehr wohl. Allerdings würde mich an dieser Stelle ein paar mehr Details interessieren. Ich denke @andreasthu gehts ebenso. "Multitool total verbuggt" verstehe ich nicht. Ich weiß nicht mal was mit Multitool gemeint ist.

**Comment by Tensuko** [comment]
Es ist Null komplexität hinzu gekommen.....
Schickt ihr den Fahrer zum ersten mal zum Feld: Erster Wegpunkt. Danach, solange nichts gestoppt wird. Wird sich der WP gemerkt.
So wie es ohne AD läuft, wenn man CP auf dem Feld wieder starten will, nahester WP danach sollte es auch ganz normal weiter gehen. Daran ist nichts kompliziert es ist sogar logisch und nachvollziehbar.

Das Argument "ist blöd wenn man vergisst..." Ja is blöd aber was sollen wir gegen Vergesslichkeit machen? Mach direkt stop, schalte um auf nahesten und fertig.

Multitool:
Mehr als ein Fahrzeug pro Kurs. Mit Bahnversatz links/rechts. Wenn AD zurück kam wurde immer auf links geschickt. Jetzt funktioniert es endlich.

**Comment by MeRida2104** [comment]
Danke für die Erklärung :) Wenn ihr damit das Problem lösen könnt, dann ist es doch in Ordnung. Ich denke es ist einfach eine gewisse Umgewöhnung nötig. Und der Mensch ist nun mal ein Gewohnheitstier ;)

**Comment by Tensuko** [comment]
Richtig.

**Comment by andreasthu** [comment]
Hallo @Tensuko 
Ich sag jetzt mal DANKE für die v 7.1.1.5
GLG
Andreas

**Comment by Tensuko** [comment]
Bitte.
Es war etwas knifflig, bis mir ein User einen Hinweis gab wie es bei ihm funktioniert. Danach konnte ich das dann anpassen und testen und es hat soweit funktioniert.
