### ISSUE TITLE
[BUG_SP] Überladewagen fährt nach Abladen nicht weiter / Abladeweg wird zu knapp generiert

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1939]
Hallo CP-Team,

zuerst einmal: Riesen Dank für dieses neue Feature! Generell reagiert das ganze deutlich flexibler und schneller als der Drescher-Modus von Autodrive. Ich habe allerdings mehrere Probleme mit dem neuen ÜLW-Feature erkannt, allerdings lassen sie sich nicht so wirklich toll nachstellen. Jedes Mal passiert etwas anderes als das was man zeigen möchte. Einerseits ist das Problem, dass der ÜLW nicht mehr anfährt, nachdem er abgeladen hat. Andererseits wird manchmal der Weg zum Abladetrailer zu eng generiert.

**Steps to reproduce**
Überladewagen im Entlade Drescher Modus fährt Drescher ab. Am Feldrand stehen zwei LKW's mit Anhänger zum abladen

**Actual behavior**
Überladewagen leert sich in Anhänger des hinteren LKW's. Anschließend fährt der ÜLW aber nicht mehr los, obwohl beide Drescher auf dem Feld voll sind.
Manchmal passiert es auch, das der ÜLW in den LKW hineinfährt, statt daneben.
![image](https://user-images.githubusercontent.com/96819380/192545640-d526391e-6bd7-4b69-93b5-0d8e885cd1b1.png)

**Expected behavior**
ÜLW fährt nach Abladen weiter um Drescher wieder abzutanken.

**Screenshots**
![image](https://user-images.githubusercontent.com/96819380/192546921-f41eef05-e340-4beb-9799-feb777fb6391.png)

**Courseplay version**
Version used: 7.1.1.1

**Log**
Muss ich nachreichen. Ist wohl zu groß, da es sich weder auf pastebin noch auf gist uploaden lässt.
![image](https://user-images.githubusercontent.com/96819380/192548321-fa89da35-72ab-45ce-8400-d9b0fed2f59d.png)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Vanilla Fendt 942 mit HAWE ULW 4000

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
> Überladewagen leert sich in Anhänger des hinteren LKW's. Anschließend fährt der ÜLW aber nicht mehr los, obwohl beide Drescher auf dem Feld voll sind.

Die situation mit debug usw, vermute dass er durch den vorderen blockiert wird.


> Manchmal passiert es auch, das der ÜLW in den LKW hineinfährt, statt daneben.

Ganz wichtig: das logfile! Am besten gesondert.
Was für ein Trailer vom LKW ist das?


> Ich habe allerdings mehrere Probleme mit dem neuen ÜLW-Feature erkannt,

Ich lese nur 2 Stück aus deinem Report :)

**Comment by MeRida2104** [comment]
Logfile kommt. Stelle es gerade noch mal nach.

Zum Trailer des LKWs: Das ist der hier: https://forbidden-mods.de/filebase/file/36064-fliegl-ass298-tridem-3-achs-schubboden-auflieger/

**Comment by MeRida2104** [comment]
Hier das Log. War voll beim ersten Mal zu groß für Github, Gist und co.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9656952/log.txt)


Was ist passiert: ÜLW war voll und ist zum Abladen gefahren. Hier wurde der Anfahrtsweg zum Trailer nun korrekt berechnet.
![image](https://user-images.githubusercontent.com/96819380/192555699-8d70d8bc-3310-4b70-a1bf-c638690a1718.png)

Nun fährt der ÜLW aber nicht mehr los (im Hintergrund sehen wir die vollen Drescher):
![image](https://user-images.githubusercontent.com/96819380/192556051-6506dbac-28ac-48f5-9b32-f30ca292b00f.png)
![image](https://user-images.githubusercontent.com/96819380/192556239-25f1db13-79d0-43db-88c8-ca5110840e54.png)

**Comment by MeRida2104** [comment]
Nebenfrage: Gibt es eine Möglichkeit, dass bei wartenden Kolonnen der vorderste Abfahrer gewählt nicht und nicht der hinterste?

**Comment by Tensuko** [comment]
Nein, da wir keine Kolonnen kennen, wir suchen einfach einen Trailer.
Nutze am besten unterschiedliche AD Punkte und lass die 2 LKWs an unterschiedliche Punkte fahren.

**Comment by rohne83** [comment]
> Nein, da wir keine Kolonnen kennen, wir suchen einfach einen Trailer. Nutze am besten unterschiedliche AD Punkte und lass die 2 LKWs an unterschiedliche Punkte fahren.

Problematisch nur wenn man zwar viele Abfahrer braucht, aber am Feldrand einfach nicht der Platz für unterschiedliche AD-Abfahrerpunkt herrscht (so einige große Felder auf der Landkreis Rostock zB). Könnte da langfristig vielleicht ne Lösung sein, das Konzept das ihr zum Anlegen von Mieten vorhabt auch auf ULWs anzuwenden?

**Comment by Tensuko** [comment]
Eventuell könnte man so eine Art validierung machen für AD Abfahrer die ihren Zielpunkt erreicht haben.
Das sollte machbar sein, allerdings braucht AD dafür natürlich eine Anpassung.

**Comment by pvaiko** [comment]
Der Pathfinder hat Probleme mit dem vorderen LKW, mit dem DevHelper könnte man wahrscheinlich die Kollisionboxen sehen. 
Weiss nicht was eine gute Lösung wäre.

**Comment by MeRida2104** [comment]
Leider nicht. Ich versuche es morgen noch in einem Test Savegame noch einmal nachzustellen.

**Comment by Tensuko** [comment]
> Weiss nicht was eine gute Lösung wäre.

Das was ich dadrüber geschrieben habe, dann wäre das Ziel immer der vordere LKW (Wenn mit AD gefahren).
Das heist wir versuchen gar nicht erst den hinteren LKW zu nehmen, wo dann der vordere ein Problem sein könnte.

**Comment by andreasthu** [comment]
> Eventuell könnte man so eine Art validierung machen für AD Abfahrer die ihren Zielpunkt erreicht haben. Das sollte machbar sein, allerdings braucht AD dafür natürlich eine Anpassung.

Die könnte ev so aussehen das der AD abfahrer wenn er am Feld zielpunkt ankommt so eine art signal aussendet "Hey ich bin da und warte auf einen Überladewagen" (meine eigenen, nicht genau abgewogenen Worte :-) )
Und der andere AD abfahrer, der hinter den ersten steht, hat dieses signal noch nicht ausgesendet (weil er ja noch nicht den wartepunkt erreicht hat) und wird deshalb von CP nicht beachtet.
Oder so?
Lg
Andreas

**Comment by MeRida2104** [comment]
> > Eventuell könnte man so eine Art validierung machen für AD Abfahrer die ihren Zielpunkt erreicht haben. Das sollte machbar sein, allerdings braucht AD dafür natürlich eine Anpassung.
> 
> Die könnte ev so aussehen das der AD abfahrer wenn er am Feld zielpunkt ankommt so eine art signal aussendet "Hey ich bin da und warte auf einen Überladewagen" (meine eigenen, nicht genau abgewogenen Worte :-) )
> Und der andere AD abfahrer, der hinter den ersten steht, hat dieses signal noch nicht ausgesendet (weil er ja noch nicht den wartepunkt erreicht hat) und wird deshalb von CP nicht beachtet.
> Oder so?
> Lg
> Andreas

Ich glaub das meinte @Tensuko 😊

**Comment by Tensuko** [comment]
Genau das, nur eben auf Basis der Schnittstellen ausgedrückt.

**Comment by Tensuko** [comment]
> Wünschenswert wäre es, den ÜLW Fahrer, wenn er keinen Abfahrer am Feldrand finden konnte, ihn nicht einfach abzuschalten, sondern ihn in eine Arte Wartemodus zu versetzen.

Das wollen wir nicht, da wir sonst ständig checken müssen ob ein Trailer da ist.
Außerdem geht es hier nicht darum nur in AD über zu laden, sondern auch in einfach nur Trailer, oder sogar Giants der dort wartet.

**Comment by Terrabey** [comment]
![Uploading Farming Simulator 22 03.10.2022 15_55_56.png…]()
Hier ein Bild wie es mit Vertikalem Versatz bei mir Funktioniert hat trotz dessen ist es ein Problem

**Comment by Terrabey** [comment]
![Uploading Farming Simulator 22 03.10.2022 15_55_56.png…]()
Hier ein Bild wie es mit Vertikalem Versatz bei mir Funktioniert hat trotz dessen ist es ein Problem

**Comment by Tensuko** [comment]
Der Versatz hat auch keine Auswirkung auf den Abladepunkt...
