### ISSUE TITLE
[BUG_SP] Vergisst anscheinend den letzten Wegpunkt auf dem Feld

### ISSUE THREAD

**Issue by Goofy78** [Courseplay/Courseplay_FS22#1942]
Mir ist aufgefallen bei der v7.1.1.1, dass Courseplay den letzten Wegpunkt nach dem Auffüllen mit AD "vergisst". Es wird wieder am ersten Wegpunkt gestartet.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9658019/log.txt)

**Comment by Tensuko** [comment]
#1926
