### ISSUE TITLE
[BUG_SP] Distance unit setting not respected

### ISSUE THREAD

**Issue by daFreeMan** [Courseplay/Courseplay_FS22#1946]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Set "Distance Unit" to "Foot"

**Actual behavior**
Look at CP's HUD - it shows "Work width" and "Tool offset horizontal" in "m"

**Expected behavior**
When set to "Foot", it should convert & display in feet

**Screenshots**
![image](https://user-images.githubusercontent.com/11889733/192636112-062f067b-c252-49b9-9a46-344a642b0adf.png)
![image](https://user-images.githubusercontent.com/11889733/192636380-319a3b08-14ed-4645-adb0-a24e27f824e2.png)

**Courseplay version**
Version used:  7.1.1.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9659702/log.txt)

**Map**
Green Valley Nebraska

**Vehicles/ implements involved**
Which vehicle or implement? Claas Arion 660 with Claas Cargos 9500
Mod yes/no ? No
NOTE: This particular combination is base-game. However, it's happening with _all_ tractors/trailers/harvesters and _all_ implements whether base-game or mod.

**Relevant script mods**
AutoDrive 2.0.0.7
UniversalAutoLoad 1.2.2.8

**Comment by Tensuko** [comment]
Working as intended. We made our own setting, see #1848 its part of the 7.1.0.4 changelog.
![fsScreen_2022_09_28_00_06_50](https://user-images.githubusercontent.com/27344744/192646206-7430fc47-1b6e-4494-89b5-a96182e77f9d.png)
![fsScreen_2022_09_28_00_06_49](https://user-images.githubusercontent.com/27344744/192646213-d6358bb3-7ce7-4e72-9893-34f4d03d5734.png)

**Comment by daFreeMan** [comment]
Right. I understand that. My screenshot was too small, I guess. It's from the CP 'Global Settings' - Here's the full screen showing I've got `Distance unit` set to `foot`, yet the CP HUD still shows it in `m`.
![image](https://user-images.githubusercontent.com/11889733/192647736-1c7f5e18-c4c4-49b2-9138-5f7be9ec77f0.png)

**Comment by Tensuko** [comment]
I am on 7.1.1.1 and tested it and it is working just fine.,
Must be a mod conflict and not a CP Issue.
