### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/Courseplay_FS22#1948]
Hallo, 
ich halte Curseplay für ein wirklich gelunges Program. Auch wenn ihr es schon wisst, ich habe folgden Problem Cp fängt immer am ersten wegpungt an nach der übergabe von A.D. C.P Vesion 7.1.1.1

Gruß 
Rudi Bergfeld
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9664299/log.txt)

**Comment by Tensuko** [comment]
#1926

Ich weis noch mal auf das Template hin wo ganz oben drin steht: Read first!
Dort findetst du dieses hier:

How to provide a nice and sexy bug report:

    Always update to the latest build and check if the problem really still exists before reporting issues.

    Check if your problem has already been reported by someone else. If so, contribute to that issue instead of creating a new one.

Und der 2te Punkt erleichtert mir viel Arbeit....
