### ISSUE TITLE
[BUG_SP] Sowing machine JD1775NT - stops too early at end of course

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1949]
**Steps to reproduce**
Sämaschine John Deere 1775NT mit Vorgewände (auf Bahnen starten) Kurs erstellen

**Actual behavior**
Ein kleiner Teil am Feldrand am Ende des Kurses wird nicht gesät

**Expected behavior**
Der Kurse deckt auch den kleinen Teil am Feldrand am Ende des Kurses ab

**Screenshots**
![image](https://user-images.githubusercontent.com/96819380/192810648-8703692a-ec06-49f5-937a-9b9ec9753075.png)

**Courseplay version**
Version used: V7.1.1.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9666197/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Vanilla JD 8RX
John Deere 1775NT Multifrucht (https://forbidden-mods.de/filebase/file/36254-john-deere-1775nt-multifrucht/)

**Relevant script mods**
none

**Comment by andreasthu** [comment]
Hast du zwei oder mehr vorgewende?
Das kommt davon das der kurs etwas zu kurz generiert wird.
Wenn du nur ein vorgewende nimmst passt es mit der länge.
Als workaorund für mehrere vorgewende:
Einfach mit dem ingame kurseditor einen oder zwei kurspunkte dranhängen.
Lg
Andreas

**Comment by MeRida2104** [comment]
Ich habe zwei Vorgewende gewählt. Dennoch würde ich erwarten, dass die Sämaschine soweit gezogen wird, das auch das komplette bearbeitet wird. 

Danke für den Tipp, werde ich beim nächsten Feld mal ausprobieren!

**Comment by rohne83** [comment]
vielleicht den Namen der Sämaschine aus dem Titel entfernen? Das Problem ist nämlich völlig unabhängig von der Sämaschine, sondern liegt wohl am Kurs. Hatte das Problem auch schon mit ganz anderen Sämaschinen (hatte ich zB am 27.6. in #1726 mit angemerkt, nur hatte es dort dann doch nicht ganz zum Thema gepasst).

**Comment by Tensuko** [comment]
Ist egal...

**Comment by pvaiko** [comment]
For the record: iterating here 1 or 2 waypoints further helps, but isn't a clean solution. The problem is that these transitions between the headland passes are smoothed out a bit by the generator and really effects implements with wide working widths.

https://github.com/Courseplay/Courseplay_FS22/blob/4da2bc1f4726980960c2124b0eb8cd0c9edd9514/scripts/courseGenerator/headland.lua#L278

**Comment by Tensuko** [comment]
This should be slightly improoved with 7.1.1.6
However, this is such a tiny bit that would cost us a lot of effort to fix it.
You can use the ingame editor to move the end point forward to solve this.

**Comment by MeRida2104** [comment]
Looks good now :)

![image](https://user-images.githubusercontent.com/96819380/200174876-6e66df44-2c9e-4fb9-9a72-3cc3d27bcbbe.png)
