### ISSUE TITLE
[BUG_SP] Steinsammler - Kurspfad anzeigen/ausblenden im Mini HUD wird ausgeblendet

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1950]
**Steps to reproduce**
Steinsammler aufs Feld schicken und per CP kurs abfahren lassen.

**Actual behavior**
Sobald CP aktiv ist, wird der Button zum verändern der Ansicht des Kurses ausgeblendet. Nur wenn man CP beendet, wird der Button wieder angezeigt.

**Expected behavior**
Button zum verändern der Ansicht des Kurses bleibt eingeblendet, auch während CP aktiv ist

**Screenshots**
Gestoppt: 
![image](https://user-images.githubusercontent.com/96819380/192821755-c09b1bf8-2438-4deb-9200-13fa29219568.png)

Gestartet:
![image](https://user-images.githubusercontent.com/96819380/192821906-55c9e90a-ca4d-4df0-98c3-8e1deb96f953.png)

**Courseplay version**
Version used: V7.1.1.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9666648/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Iconic Stonepicker

**Relevant script mods**
none

**Comment by Tensuko** [comment]
Same: #1951
