### ISSUE TITLE
[BUG_SP] Steinesammler wird nach starten wie ein Abfahrer behandelt? (Einstellungen)

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1951]
**Steps to reproduce**
Ich nutze derzeit einen Steinsammler für die Feldarbeit mit CP. 

**Actual behavior**
Sobald CP aktiv ist, ist die Liste der Fahrzeugeinstellungen von CP (erreichbar bpsw. durch Klick auf den Fahrzeugnamen im Mini HUD) stark verkürzt.

**Expected behavior**
Liste sollte genauso lang wie ohne CP Aktivität sein. In alten CP Versionen war dies auch so. Ggf. ist es auch ein neues Feature, dann wurde dieses aber nicht im Changelog genannt.

**Screenshots**
CP nicht aktiv (Geräte anheben bspw. sichtbar):
![image](https://user-images.githubusercontent.com/96819380/192823214-807db4b1-74c1-4116-9358-d9c9d908109b.png)

CP aktiv (Liste verkürzt):
![image](https://user-images.githubusercontent.com/96819380/192823426-803c9ded-245b-4b2e-854f-50df99bcf524.png)

**Courseplay version**
Version used: V7.1.1.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9666698/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Iconic Stonepicker

**Relevant script mods**
none

**Comment by Tensuko** [comment]
@schwiti6190 scheint so als ob der aktive Steinesammler als Abfahrer erkannt wird, wenn er aktiviert wird....
