### ISSUE TITLE
[BUG_SP] Can Not Get to Course generator

### ISSUE THREAD

**Issue by MOONSPYYT** [Courseplay/Courseplay_FS22#1953]
**Steps to reproduce**
try to create a job/ hire a helper

**Actual behavior**
Not able to get to the course generator, hire a helper, or use a recorded course.

**Expected behavior**
Load the course generator and make a course and be able to use it or record a course and be able to use it.

**Screenshots**
I don't have any screenshots but there is no create job button while the mod is installed.

Version used: 7.1.0.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9680022/log.txt)

**Map**
Tried on two maps: Goldcrest Valley(mod) and Erlengrat

**Vehicles/ implements involved**
 Lizard TWIN-SCREW XBR2 (mod) and HD50F
John Deere X9 1100 and HD50F
BigBud 747 v16 (mod) and 3420-100 paralink hoe drill (mod part 1) + 71300 air cart (mod part 2)

**Relevant script mods**
None

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/releases

Remove this, if you don't know what it does.... it does not allow to use helper.....
Available mod: (Hash: 697be2c3ed7517357c8f32d6cf7b0fa9) (Version: 1.0.0.0) FS22_Survival
