### ISSUE TITLE
[BUG_SP] Shortcut key for Start/Stop and Change mode - stopped working in 7.1.1.1

### ISSUE THREAD

**Issue by Krecik7** [Courseplay/Courseplay_FS22#1961]
**Steps to reproduce**
start Vanilla Haut Baleron, only with CP mod, check shortcut keys, for Start/Stop machine and for Change starting mode, and they both does'nt work :(

**Actual behavior**
this two shortcut keys are ignored, nothing happening in game, I did back to CP version 7.1.0.4 - and keyboard shortcut for On/Off worker is working correctly 

**Expected behavior**
Shortcut keys should start/stop machine (like it was in previous versions), and change working mode (nearest waypoint, first waypoint, last waypoint) as it looks that is implemented. 

**Courseplay version**
Version used: 7.1.1.1 (FS22 version 1.7.1.0)

**Map**
Haut Baleron

**Vehicles/ implements involved**
first standard combine with header on new started map

**Relevant script mods**
all are off

**Comment by Krecik7** [comment]
in 7.1.1.0 is is also not working corectly, On/Off stopped working and Change starting point did'nt do any effects

**Comment by Tensuko** [comment]
Does it work if you turn on show keybind in the global settings?

**Comment by Krecik7** [comment]
On 7.1.1.0 and in 7.1.1.1

When i turn on "Show keybind in F1 menu" in CP configuration, "Hire worker" keybind **started** to work, "Change starting point " still not working, i see it in F1 help, but nothing is going on when i press buttons. 

When i turn **off** "show keybinding in F1 menu" - Hire worker shortcut key is back to dead and stops working

**Comment by Krecik7** [comment]
Other keybinds (except for this two i mentioned) - are working correctly no matter if i have show keybinds in F1 turned On or Off.

**Comment by Krecik7** [comment]
CP 7.1.1.2 with manually added fix from **Schwiti6190** works correctly :-) 
Thanks :)
