### ISSUE TITLE
[Feature] Überladewagen

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/Courseplay_FS22#1962]
Hallo Courseplay Team, 
Ich hätte die Idee das man in Courseplay einen Helfermodus einfügt der dafür da ist das Überladewagen Drescher abladen und dann zu einem Hänger bringt der z.b. an einem Autodrive Punkt steht. Es wäre toll wenn ihr diese Funktion hinzufügt.

**Comment by TobiHH78** [comment]
Da ist wohl etwas an dir vorbei gegangen...

https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.1.1.0

**Comment by Terrabey** [comment]
Ich hätte dann noch eine frage 
Wie mache ich das ganze?

**Comment by MeRida2104** [comment]
https://youtu.be/lPil1D7yjAM
