### ISSUE TITLE
[Question] Frage auf das Problem

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/Courseplay_FS22#1963]
Hallo nochmal,
nachdem sie mir geschrieben haben das es das Feature mit den Umladewagen schon gibt hätte ich die frage wie ich das mache.
Danke noch und schon mal im voraus

**Comment by Tensuko** [comment]
Da es bereits verlinkt wurde, kannst du dir ja einfach mal die Beschreibung von der Release Version durchlesen, da steht wie es geht....

**Comment by MeRida2104** [comment]
Ergänzend noch der Hinweis auf das Tutorial von Holger-70: https://youtu.be/lPil1D7yjAM
