### ISSUE TITLE
[BUG_SP] no path found - send driver to unload in trailer

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#1966]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
attempt to use the yellow button to make it do an unload run while on field 94

**Actual behavior**
says no path

**Expected behavior**

**Screenshots**
![20221002183300_1](https://user-images.githubusercontent.com/5993529/193486665-96e01ba7-2eed-4eaa-970f-57cd6a50b591.jpg)
![20221002202023_1](https://user-images.githubusercontent.com/5993529/193486668-e8a6a4e9-27de-4857-9827-40c5f9c8f2ea.jpg)

**Courseplay version**
Version used: 7.1.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9694035/log.txt)

**Map**
landownunda from cazz 64

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=228874&title=fs2022

**Comment by tn4799** [comment]
Where on the map is your trailer where the auer wagon unloads too?

**Comment by Commissar0617** [comment]
PEBCAK... reading patch notes helps.
