### ISSUE TITLE
[BUG_SP] John Deere 5080E Series VS CP

### ISSUE THREAD

**Issue by etrigo1** [Courseplay/Courseplay_FS22#1976]
Hello, I come to report a CP bug in this specific mod. The mod was updated today but even in the previous version it caused an error.
The error is this and ends up crashing the game.
![image](https://user-images.githubusercontent.com/37108041/194084155-20b7ffa3-cd95-42e7-bdb8-ef5a60ecfd6a.png)

The mod: https://www.farming-simulator.com/mod.php?lang=en&country=pt&mod_id=245270&title=fs2022

**Comment by Tensuko** [comment]
No template used, no logfile added.
Mod issue...
