### ISSUE TITLE
[BUG_SP] John Deere 5080E Series VS CP

### ISSUE THREAD

**Issue by etrigo1** [Courseplay/Courseplay_FS22#1977]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
Only enter in the vehicle

**Screenshots**

![image](https://user-images.githubusercontent.com/37108041/194085874-b3957647-30de-484b-95eb-32e1d5701771.png)

**Courseplay version**
1.7.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9716474/log.txt)

**Map**
Map FR (Original the game)

**Vehicles/ implements involved**
Its Mod
https://www.farming-simulator.com/mod.php?lang=en&country=pt&mod_id=245270&title=fs2022)

**Relevant script mods**
No Autodrive or VCA.

**Comment by Tensuko** [comment]
Your CP Version is 7.1.1.2 not 1.7.1.0 thats the game version...

And dude how many mods do you have that is just insane....

And it does start with a callstack from other mod FS22_exhaustExtension....
