### ISSUE TITLE
[Feature] Add a "reset working width" button when generating courses

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#198]
**What is the problem this feature/enhancement solves?**
If you don't know the actual working width of an implement (if it has been previously changed or if it's not correct for whatever reason), it can be cumbersome to set it correctly. Being able to easily reset the working width of an implement to its original, correct value from this dialog would be useful.

**Describe the solution you'd like**
A little "reset" button at the top of the of the course generator settings dialog next to the work width adjustment.

**Comment by Tensuko** [comment]
It should read the actual working width onAttach.

**Comment by Obsiana2019** [comment]
> It should read the actual working width onAttach.

Version 7.0.0.8 the Attach the Working Width ist 1 meters on. 

Bei allen hinten angehängten Maschinen ist die Arbeitsbreite 1 Meter zumindest bei Grubbern.

**Comment by SaschaLie** [comment]
Beim Drescher auch 1 Meter

**Comment by andreasthu** [comment]
1 Meter,
kann ich so bestätigen.
v 7.0.0.8
lg
andreas

**Comment by BullFlag** [comment]
Not sure if this applies, could be unit conversion issue.    Try change options length units setting to "Kilometers"   ,  avoid "Miles"

**Comment by Tensuko** [comment]
All tools only 1 Meter now ?

**Comment by andreasthu** [comment]
bei mir alle, ja
lg
andreas

**Comment by ph1go** [comment]
> All tools only 1 Meter now ?

I was on v7.0.0.7 when I made the original post but the work widths are all over the place in v7.0.0.8 (a 15m seeder coming up as 6m, the 24m roller coming up under 20) so a "reset work width" button would be even more useful now. :) Even if we could adjust the width with the mouse wheel (for example) rather than having to click 10 times per metre.

**Comment by Tensuko** [comment]
Ok we keep this Issue as Suggestion for a rest button, right now, detach and attach will ask for the correct workWidth, if it does work for all Tools, thats another story as Giants seem to have some stuff changed on that....

**Comment by ph1go** [comment]
> Ok we keep this Issue as Suggestion for a rest button, right now, detach and attach will ask for the correct workWidth, if it does work for all Tools, thats another story as Giants seem to have some stuff changed on that....

I haven't tested if detach/attach works but I just leased 2 rollers (the 12m one and the 24m one) and both widths were wrong immediately after I attached them at the shop. They're both halfway through fields but I'll do some testing before I start on the next ones. It seems to me that the tractors are remembering the widths of the implements that were previously attached, if that's even possible. The 12m roller came up as 6m but that tractor had a 6m wide mulcher on before...

**Comment by Tensuko** [comment]
We just pushed 7.0.0.9 to fix that, sry I should have mentioned this here as well ^^

**Comment by LesMinton** [comment]
I am not sure if its fixed, I am in game right now, and it is showing width in **FEET** instead of meters, but for a 6m implement, the width has to be set for 1.68 ft, in that area. Its very confusing.

**Comment by Tensuko** [comment]
> I am not sure if its fixed, I am in game right now, and it is showing width in **FEET** instead of meters, but for a 6m implement, the width has to be set for 1.68 ft, in that area. Its very confusing.

You may have a look at #128 and there will be another fix for the next Version.

**Comment by Tensuko** [comment]
No button, but field entry. Should do the same for this.
