### ISSUE TITLE
[BUG_SP] Weinberg Reben zurückschneiden

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS22#1981]
Mit der v7.1.1.3 ist es leider nicht mehr möglich, mit CP die Reben zurückzuschneiden. Der Traktor fährt gar nicht mehr an, wenn entsprechender Kurs geladen ist.
In der LOG mit folgenden Fehler:

 2022-10-07 10:26 Error: Running LUA method 'update'.
C:/Users/Admin-PC/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIUtil.lua:163: attempt to call method 'getAIReverserNode' (a nil value)
2022-10-07 10:26 dataS/character/humans/npc/pedestrians/france/npcFR05_m.i3d (10.72 ms)

**Comment by Tritura2** [comment]
Es gibt ein vorgefertigtes Fomular für Bugs. Kannst du das nutzen?
Weil hier kommen gleich die üblichen Fragen auf:
Wie war deine Vorgehensweise? Hast du andere Mods genutzt? Kannst du die ganze Log als Datei Posten? … 🙈

**Comment by Tensuko** [comment]
Richtig, desshalb hier zu und noch mal neu bitte und die log sollte den Fehler beinhalten.
