### ISSUE TITLE
[Feature] Harvester chooses between empty or closest trailer or an already partially loaded one

### ISSUE THREAD

**Issue by lordbanastor** [Courseplay/Courseplay_FS22#1982]
**What is the problem this feature/enhancement solves?**
It's an option for the harvester to choose between an empty wagon/trailer or an already partially loaded one, if more than one trailer is set to the same harvester.

**Describe the solution you'd like**
In FS19 this option was available, and was very useful. There could be two trailers set to the same waitpoint, so the harvester had the option to choose between an already partially loaded trailer to unload the crops. When the loading threshold was reached, the trailer would proceed to unload and the harvester will then choose the next trailer waiting. Without this, the harvester calls for the closest waiting trailer, which creates confusion on the field sometimes. There should be a behavior for when there are more than one harvester on the field as well. 

**Describe alternatives you've considered**
The alternative already exist, which is the way it works now, the harvester calls for the nearby trailer, but it doesn't look for the trailer loading amount as a choosing factor.

**Additional context**
No additional content.

**Comment by Tensuko** [comment]
The harvester chooses the best trailer depending on distance and fill volume. There is an automatisation and we dont add an option for it.

**Comment by Tensuko** [comment]
![fsScreen_2022_10_07_14_23_15](https://user-images.githubusercontent.com/27344744/194552686-dcce59c3-2d44-4bdc-9304-bc687682afb1.png)

**Comment by lordbanastor** [comment]
Weird, maybe something with having two harvesters set to the same waiting point, with two trailers? I am using now two separate waiting points, each harvester pointing to one of them, and one trailer in each point, to avoid this problem. But maybe I test again to see if the problem was my setup course. Thanks!

**Comment by Tensuko** [comment]
What is a waiting point for you?
We don't have a waiting point in FS22

**Comment by lordbanastor** [comment]
Sorry, I wasn't clear with my issue. I meant the loading/unloading points in AutoDrive, using the option "unloader for harvester".

**Comment by Tensuko** [comment]
Oh okay.
But when the distance is way to far we don't take the full one anyway.
We brought im some kind of intelligence that way.
So not sure in wich situation your combines and unloaders where when they called the unloader.

But within a specific distance, the one wich have less free capacity, that one will be called 1st.
Based on the same logic that you have :)

**Comment by lordbanastor** [comment]
Oh, I see. Well, thanks! And keep up with this awesome mod.
