### ISSUE TITLE
[BUG_SP] Überladewagen fährt keine weiteren Anhänger an

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/Courseplay_FS22#1983]
Hallo Allerseits ich habe in der neuen Version 7.1.1.3 bemerkt das beim Entladen des Überladewagen mit der Funktion Drescher entladen gemerkt das der Helfer nur den ersten Anhänger benutzt und nicht die hinteren oder auch bei dem Lode King 3 Segment Anhänger nur 1 Segment verwendet wird.

**Comment by Terrabey** [comment]
Außerdem fährt der Abfahrer nicht mehr weiter wenn der Drescher seinen Motor ausschaltet

**Comment by Tensuko** [comment]
Auch für dich gilt: Template benutzen!

**Comment by Tensuko** [comment]
Und es funktioniert ganz genau so wie es soll
![fsScreen_2022_10_07_17_02_20](https://user-images.githubusercontent.com/27344744/194585118-474a46a1-0668-4776-a5c8-800bf4f32f2f.png)

**Comment by Tensuko** [comment]
Und auch das hier, funktioniert!
![fsScreen_2022_10_07_17_04_43](https://user-images.githubusercontent.com/27344744/194585600-11a00fcf-859f-4cb9-82c3-440d9eefa04e.png)
