### ISSUE TITLE
[BUG_SP] Generator does not switch m/ft.

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#1985]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by tn4799** [comment]
Are you fucking stupid?
You at least have to write whats your problem to get help

**Comment by HC1Gunner** [comment]
Not sure what is going on, I open a new ticket, then was called away, and somehow my new ticket auto-submitted itself without being filled out.

As soon as the game is launched.

The setting under Global for "Foot / Meter" does not stay, I always use Foot, when its set to Foot, the mini CP HUD, and when using the course generator, it will not keep distance displayed in Feet, they revert back to Meter, even though the global settings still show it set to Foot. This happens for every vehicle / implement. On some maps even after resetting the global setting back to Foot, the working width with once again display in Feet, but the offset below it stays in Meters.

Currently using v7.1.1.3, but it's had this same issue going back 5 - 6 versions.

Map:
On Haut-Beyleron, but it happens on "all" maps.

Vehicles/ implements:
It happens with all Vehicles/ implements.

Once the display distance is set to "Foot" and the game is saved, the CP HUD and Course Generator should always display the working width Feet, and never revert back to meters unless it's changed in CP global settings.

AD v2.0.0.7
![CP Feet - Meter 1](https://user-images.githubusercontent.com/45585444/194686304-96f6f3c8-8ab1-4cf3-a10b-19a80848d9f9.jpg)
![CP Feet - Meter 2](https://user-images.githubusercontent.com/45585444/194686308-ad75574d-8925-4fef-ac41-262fbde8093f.jpg)
![CP Feet - Meter 3](https://user-images.githubusercontent.com/45585444/194686309-79d734fc-cf22-4618-b59b-262e52d3a566.jpg)
![CP Feet - Meter 4](https://user-images.githubusercontent.com/45585444/194686310-b162ebec-7253-4f5f-a7bc-998c53a7e604.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9738345/log.txt)

**Comment by Tensuko** [comment]
Might miss the switching in the generator.
