### ISSUE TITLE
[BUG_MP] Unloader not continuing the after unloading into Trailer

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#1986]
**Steps to reproduce**
Dedicated Server
Activate the new unloading mode.

**Actual behavior**
After loading from the Combine, it drives to the waiting trailer.
Unloads itself and then, just waits with the pipe out.

**Expected behavior**
Fold the Pipe Back in and go back to the combine or wait for it to be full agian.

**Screenshots**
Might be related after starting the mode, and it finds the Course to the Combine these show up.
![grafik](https://user-images.githubusercontent.com/29522870/194642734-e828d344-268a-438c-84af-5b2a1c914d14.png)
![grafik](https://user-images.githubusercontent.com/29522870/194642841-45146856-2051-4a48-8091-6858a1eaa846.png)

**Courseplay version**
Version used: 7.1.1.3

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9737177/log.txt)
**Server Log**
Server log is also spammed/overflows, no way to get a log that is not just this a few thousend times, with:

> 2022-10-07 21:57 :06 [info lp103086] [string "dataS/scripts/utils/MathUtil.lua"]:115: bad argument #2 to 'max' (number expected, got nil)
> 2022-10-07 21:57 LUA call stack:
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/CpUtil.lua (220) : printCallstack
>   =[C] (4294967295)
>   dataS/scripts/utils/MathUtil.lua (115) : max
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/controllers/PipeController.lua (250) : clamp
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/controllers/PipeController.lua (191) : moveDependedPipePart
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/controllers/PipeController.lua (26) : updateMoveablePipe
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (265)
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (242) : raiseControllerEvent
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyUnloadCombine.lua (1629) : updateImplementControllers
>   dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
>   =[C] (4294967295)
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/CpUtil.lua (220) : xpcall
>   =D:/home/sid_3118543/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (360) : try
>   dataS/scripts/specialization/SpecializationUtil.lua (19)
>   dataS/scripts/vehicles/Vehicle.lua (1881) : raiseEvent
>   dataS/scripts/network/NetworkNode.lua (129) : update
>   dataS/scripts/network/Server.lua (62) : updateActiveObjects
>   dataS/scripts/BaseMission.lua (1134) : update
>   dataS/scripts/FSBaseMission.lua (1972) : update
>   dataS/scripts/missions/mission00.lua (577) : update
>   dataS/scripts/main.lua (1229) : update

**Player on the server**
1

**Dedicated server or local hosted server**
Dedicated server

**Map**
NF Marsch x4 oG

**Vehicles/ implements involved**
Holmer (Giants MOD)
John Deer 8R 310 + Krone GX 520

**Relevant script mods**
Autodrive and VCA

**Comment by PapaTim68** [comment]
I did a more detailed test in SP. Also got a log this time.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9738971/log.txt)
Also narrowed the start of the Lua Error down to the Unloader extending its pipe.
By accident the combine pushed the waiting trailer and so the unloader never Reached the Trailer, but as soon as the trailer would have been reached and the pip was extended the Error showed up in the log.

**Comment by schwiti6190** [comment]
@PapaTim68 Hi there does this bug only appear with this overloader mod or also with other overloader vehicles/trailers ?

**Comment by PapaTim68** [comment]
I haven't tryed that yet, but I will try later today, when I am back at my PC.

**Comment by PapaTim68** [comment]
I just tested it, and it seems like that it's only coming up on the Holmer Overloader. I tested with Vanilla Vehicles and seems like it doesn't come up. Furthermore, I assume it's due to the Holmer only having one movable part, the nuzzle.

**Comment by Tensuko** [comment]
The Callstack with the Holmer and some other AugerWagons should be fixed.

However the problem with the msg is not sure when and how it happens.
This might get investigated later if it still occoures, since we did some changes to MP.
Might make a new Issue when you find something out :)
