### ISSUE TITLE
[BUG_SP] vehicleConfigurations.xml refers to incorrect directory path

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1987]
I became aware of the possibility that in the vehicleConfigurations.xml the turn radius of vehicles can be specified by the Youtube comment of @rohne83. In this XML is referred to a custom config. I quote from: config/vehicleConfigurations.xml

> "This file is the global configuration coming with your copy of Courseplay. If you
> want your own vehicle config, you can create a file called
> **vehicleConfigurations.xml** in your **modsSettings/Courseplay folder**. Settings defined
> in that file will override the settings defined here"

The path to ModsSettings/Courseplay is not correct. My own vehicleConfigurations.xml in this path was not used. The correct path is modSettings\FS22_Courseplay. If there is a vehicleConfigurations.xml, the values in it will be used correctly by Courseplay.

The reason for this adjustment was that the turning radius of the Bergmann GTW330 and Hawe ULW4000 was calculated to too close. The change in the aforementioned XML means that the turning radius is significantly larger and the transfer wagon thus does not drive into the unloadingtrailer from behind during 180° turning maneuvers. ([Very nice to see in the Youtube video of Holger-70](https://youtu.be/lPil1D7yjAM?t=432))

Maybe you take over these values in your global vehicleConfigurations.xml (as you already die for Bergmann RRW500) 

```
<VehicleConfigurations>
    <!-- Implements -->

        <!--\vehicles\gtw330-->
    <Vehicle name="gtw330.xml"
             turnRadius = "10"
    />

        <!--\vehicles\ulw4000-->
    <Vehicle name="ulw4000.xml"
             turnRadius = "10"
    />

</VehicleConfigurations>
```

**Comment by Tensuko** [comment]
So it is just d scription.

**Comment by pvaiko** [comment]
Pull requests are always welcome though when you recommend changes to the code or configuration. Thank you!

**Comment by MeRida2104** [comment]
> Pull requests are always welcome though when you recommend changes to the code or configuration. Thank you!

Thx for that info. Didn't know before. Pull request is made: https://github.com/Courseplay/Courseplay_FS22/pull/1988
