### ISSUE TITLE
[BUG_SP] v7.0.0.8 Strohablage Einstellungen

### ISSUE THREAD

**Issue by Neotras2552** [Courseplay/Courseplay_FS22#199]
Steps to reproduce
Weizen Ernten mit den Trion 720

Actual behavior
Obwohl in den Einstellungen Strohablage aktiviert ist , legt er das Stroh nicht automatisch ab nachdem er z.b raps geerntet hat.

Expected behavior
Sollte bei Weizen Stroh ablegeben und z.b raps nicht.

Screenshots

Videos:

**Comment by Tensuko** [comment]
#147
https://github.com/Courseplay/Courseplay_FS22/wiki
"2. Check if your problem has already been reported by someone else. If so, contribute to that issue instead of creating a new one."
