### ISSUE TITLE
[BUG_MP] Sync stuck at 99%

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#1990]
**Steps to reproduce**
Probably related to having a Driver running and leaving.
Specifically Unloader.
cpStopAll doesn't work.
Even restarting the Server doesnt help.

**Courseplay version**
Version used: 7.1.1.3

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9739144/log.txt)

**Server Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9739148/log.txt)

**Player on the server**
0

**Dedicated server or local hosted server**
Dedicated server

**Map**
NF Marsch x4 oG

**Relevant script mods**
Autodrive and VCA

**Comment by Tensuko** [comment]
`2022-10-08 13:50 Error: Running LUA method 'packetReceived'.
C:/Users/Tim/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJobCombineUnloader.lua:111: attempt to index local 'vehicle' (a nil value)`

@schwiti6190
