### ISSUE TITLE
[BUG_SP] Auger wagon recognizes combine harvester as unloader

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#1991]
**Steps to reproduce**
combine harvester is empty in a field. Auger wagon is full.

**Actual behavior**
Auger wagon tries to unloud in combine harvester

**Expected behavior**
Auger wagon doesn't try to unload in the combine harvester, but a trailer at the edge of the field or in the field.

**Screenshots**
![image](https://user-images.githubusercontent.com/96819380/194707003-a223bd6d-b3b8-463c-9097-07569144b81b.png)

**Courseplay version**
Version used: 7.1.1.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9739198/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Vanilla Fendt 1050 with Hawe GTW440
Mod combine JD X9 2020 (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228728&title=fs2022)

**Relevant script mods**
none

**Comment by Tensuko** [comment]
Mod Issue.
That combine got the spec "Trailer" wich is wrong (I wonder how it could pass Giants test...).
There is nothing we can do since whe have to look for a trailer.
