### ISSUE TITLE
[BUG_SP] AD->CP startpoint isnt anymore "first point"

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#1994]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
- Load CP course into a vehicle
- Set CP start point to nearest point
- Set AD Field Point (drive to mode)
- Set CP active in AD Hud
- Start AD

**Actual behavior**
- AD drives to Field
- CP takes over
- CP drives to nearest point and start fieldwork 

**Expected behavior**
CP should always start at first point, regardless wat is set in the CP hud. Nearest or first point
I think it startet with 7.1.1.2, before it was working

**Additional Info**
Even if first point is active in CP, he gets stuck on the building, while he was trieing to get to the first WP.
As of my knowledge it was designed to always start at first WP wehn it got sent the first time to field with AD.

**Screenshots**
![1248130_20221010193712_1](https://user-images.githubusercontent.com/47928255/194926481-e86d2beb-0183-4fa8-b3f9-f4fbdcc3aea1.png)
![1248130_20221010193717_1](https://user-images.githubusercontent.com/47928255/194926589-a50b770e-9256-495f-88dd-84c6a63aa462.png)
![1248130_20221010193622_1](https://user-images.githubusercontent.com/47928255/194926956-6ae6eef5-2c45-4b82-af60-86b32991751f.png)
![1248130_20221010193629_1](https://user-images.githubusercontent.com/47928255/194926995-6650bb26-0486-4de0-b078-b7d876a5a042.png)
![1248130_20221010192735_1](https://user-images.githubusercontent.com/47928255/194927065-eeb36a47-7808-4462-8823-87fad773cf66.png)

**Courseplay version**
Version used: 7.1.1.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9748033/log.txt)

**Map**
Vanilla Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement? Every, doesent matter what type. Seeder, spreader, harvester and so on.
Mod yes/no ? Yes

**Relevant script mods**
AD+CP only

**Comment by Tensuko** [comment]
You got to set in to 1st waypoint in the HUD for the 1st run.

**Comment by Tensuko** [comment]
Schickt ihr den Fahrer zum ersten mal zum Feld: Erster Wegpunkt. Danach, solange nichts gestoppt wird. Wird sich der WP gemerkt.
So wie es ohne AD läuft, wenn man CP auf dem Feld wieder starten will, nahester WP danach sollte es auch ganz normal weiter gehen.

**Comment by blubstar86** [comment]
Hey, ich fands vorher eigentlich perfekt gelöst.
Es stand immer auf "nähester Wp".
Wenn AD zum ersten mal zum Feld fuhr wurde trotzdem immer der "erste Wp" angefahren, egal was eingestellt war.
Beim nachfüllen oder abladen wurde dann der "letzte Wp" angefahren.

So musst man wirklich NIE etwas an der Einstellung herumstellen.
Jetzt bin ich nur noch am hin und her schalten.

Ich finds leider verschlimmbessert.

**Comment by regs1980** [comment]
> Ich finds leider verschlimmbessert.

Eher nicht, so muss man auch mal die Augen aufmachen beim Einstellen, Du generierst doch den Kurs, also musst Du eh den Feldpunkt setzen, darunter ist gleich Startpunkt.

**Comment by blubstar86** [comment]
Tensuko, irgendetwas scheint aber trotzdem nicht ganz zu Funktionieren.

Wenn ich ein Savegame Lade, einen bestehen kurs in ein Fahrzeug lade und AD dann zum Feld schicke, dann ignoriert er manchmal/meistens die "Startpunkteinstellung" trotzdem.

Sie steht auf erster, fängt aber am nähesten an, würde ich sagen.
Gefühlt würde ich sagen, es tritt beim ersten Fahrer nach dem Savegame laden auf, sicher bin ich mir aber nicht.

Vielleicht kannst du damit ja was anfangen.

![1248130_20221013121059_1](https://user-images.githubusercontent.com/47928255/195570509-7ed541a4-4a02-4821-97fb-7bba31cd117e.png)
![1248130_20221013121107_1](https://user-images.githubusercontent.com/47928255/195570536-d8f184be-6081-4ea5-a40b-b68a2ff72fef.png)
![1248130_20221013121125_1](https://user-images.githubusercontent.com/47928255/195570562-2f936419-9b66-4ee2-8247-9bcaa51a7075.png)
