### ISSUE TITLE
[Feature] Bunkersilo verteilen und verdichten mit Courseplay ähnlich LS19

### ISSUE THREAD

**Issue by mertchri** [Courseplay/Courseplay_FS22#1998]
Im Singleplayer hat man oft das Problem, dass man zum Beispiel beim Häckseln ständig zwischen Häcksler und der Maschine zum Verdichten des Bunkersilos hin und her pendeln muss um alles sauber zu verteilen und zu verdichten.
Hier würde ich mir die Funktion des automatischen Verdichtens und Verteilens aus dem LS19 wieder zurückwünschen, da diese Funktion sehr gut funktioniert hat und man nicht immer hin und her springen musste.
Vielleicht könnte diese ja schon einmal da gewesene Funktion auch wieder Einzug in LS22 halten.

In single player you often have the problem that you have to constantly commute back and forth between the chopper and the machine for compacting the bunker silo when chopping, for example, in order to distribute and compact everything cleanly.
Here I would like the function of automatic compression and distribution from the LS19 back, because this function worked very well and you didn't always have to jump back and forth.
Perhaps this function, which has already existed before, could also find its way back into LS22.

**Comment by Tensuko** [comment]
Wurde bereits an diversen Stellen (z.B. unter Discussion) erwähnt.
Ist work in Progress, also noch etwas Geduld
