### ISSUE TITLE
[Question] Manuel?

### ISSUE THREAD

**Issue by Namajo** [Courseplay/Courseplay_FS22#1999]
Hello Courseplay Team,

is there a manuel with instructions how to use harvester unloading?

**Comment by TobiHH78** [comment]
But there are a lot of YT videos already out there, showing how it works.
Just search for Courseplay combine unloader and you will find them easily

**Comment by Namajo** [comment]
> Not yet. Check the changelog of Version 7.1.1.0

Thanks. It seems i missed this changelog.
