### ISSUE TITLE
How to start/continue AI Fieldwork

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#2]
First Version:
- create job
- select vehicle
- place target on the map/field with starting location and direction
- generate the course with the settings
- start the job

Later:
- Generate the course in an extra menu
- create job
- select vehicle
- select course
- start the job

How to use continue in the vehicle:
- sit in the vehicle
- use key to stop/start
- use key to toggle start job on 1st/actual/best next WP

That way only 2 keybinds are needed.

**Comment by iljarogoff** [comment]
> How to use continue in the vehicle:
> 
>     sit in the vehicle
>     use key to stop/start
>     use key to toggle start job on 1st/actual/best next WP
> 
> That way only 2 keybinds are needed.

Which are the default keys? There is nothing set in the keybindings.
When using "H", described as "Helfer einstellen (CP)", the FS22-helper is started instead of CP
I can't manage to continue a course from nearest waypaoint after I restarted game. Course is saved and shown on map.
