### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by bibifr** [Courseplay/Courseplay_FS22#20]
Hello dear, 

First for all i want to thanks you for works that seem to be working for people! 

First impression... is ugly as hell... Not realy intuitive, not realy clear as we all used before. I guess it's one of objective to make something news! 
But as hell we do not understand how to make it works! Basicaly CP is most used for Unload combine but how to do that i cannot create a script for it since year i never used tutorial for make works cp but well i guess this time is over.

I know you made a video but better to make some more video whit detail of how to cause actualy im stuck as using it and will just remove untill is clear and intuitive 

A another point Translation To french are not working maybe it's wanted ?? 
Well ill be wait for smoother version :) 

Thanks again for works i wanted to give my opinion.

**Comment by pvaiko** [comment]
How about reading the README?

**Comment by Tensuko** [comment]
The first Minutes of my Video shows exactly how you can start a Fieldwork. Thats CP Main feature.
Ofc a new Version comes with new stuff that you have to learn.

But with the term:

> is ugly as hell...

We can't rly do anything...

> A another point Translation To french are not working maybe it's wanted ??

What do you mean with 'it isn't working' ? We have the Files but ofc it is all written in english, so we hope for our dear translaters to help us out with it.

**Comment by bibifr** [comment]
You still not accept any critic perfect let's go away i don't care about cp
