### ISSUE TITLE
Coursenames only 3 characters?

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#200]
**Steps to reproduce**
Try to save a course in coursemanager. And give a name for the course. Same issue if u try to name a new folder.

**Actual behavior**
Only 3 Characters are allowed. You can't type more in the naming field

**Expected behavior**
Normal name length

**Screenshots**
![image](https://user-images.githubusercontent.com/26980809/147576159-60ca4243-a060-4ec8-bed4-6bf696f974fa.png)

**Courseplay version**
Version used: 7.0.0.8

**Comment by schwiti6190** [comment]
@Keppchen Hi,
I can't reproduce this bug. Are you using any special characters for your course name ?

**Comment by NEA1971** [comment]
I am having same experience - it was working correctly the first 3 or 4 courses for me then suddenly stuck on 3rd character at the next track

**Comment by Keppchen** [comment]
@schwiti6190 no. Just normal Chars. I tried to write Test. But I could only write "Tes" 

Then I thought ok nevermind. Let the folder on "Tes" and try to save the first Course "Feld 30 - Düngen" ...after "Fel" nothing more happens.

**Comment by Tensuko** [comment]
Can you both try to copy your course somewhere as a backup and try it from the start with the newest Version ?
I can only Imagine that something got stuck during the updates.
This is something that can happen...
As I could not reproduce this Error at all with several folders and course saved.

**Comment by NEA1971** [comment]
it works correctly then - the courses are also working still when renamed in windwos-explorer

**Comment by Keppchen** [comment]
I have no courses saved so far. What should I Backup? Settings?

**Comment by Keppchen** [comment]
Fixed...
