### ISSUE TITLE
Mini HUD öffnet nicht[BUG_SP]

### ISSUE THREAD

**Issue by Peicke** [Courseplay/Courseplay_FS22#2000]
Seit dem letzten Update kann das MINI-Hud nicht geöffnet werden. 
Weder mit den Maustasten noch über die Tastenbelegung. 

Es wurde auch versucht ohne andere Mods - leider auch keine Funktion. 

Anbei das LOG. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9764026/log.txt)

**Comment by Tensuko** [comment]
Check einfach mal deine keybinds.
Auch oneDrive kann dafür verantwortlich sein. Frag mal google zum thema oneDrive und FS.

Komplett ohne Mods muss es gehen. Auch kannst du unter modSettings im CP Ordner die .xml datei mal löschen.
