### ISSUE TITLE
[Feature] Unloader unload in a double Trailer

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#2001]
**What is the problem this feature/enhancement solves?**
If you use the new Unloader system with overloading to trailers at the field, it will not work when there are two trailers behind each over connected to one Tractor. The Unloader will endlessly try and fill the first Trailer.

**Describe the solution you'd like**
The unloader recognize that it's two trailers and fill the second when the first is filled.

**Describe alternatives you've considered**
For now, I will refrain from using two trailers and just use one.

**Comment by Tensuko** [comment]
Can't reproduce.

**Comment by PapaTim68** [comment]
Might be again me using the Holmers as Unloaders. Will make some logs and Screenshots later or tomorrow.

**Comment by PapaTim68** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9767236/log.txt)
https://youtu.be/clq4NCNAehc
Managed to do it faster than expected. Here is a log and a short Video Clip.

**Comment by Tensuko** [comment]
Same thing even when the holmer is further away?

**Comment by PapaTim68** [comment]
Yes I noticed it when the holmer just unloaded from a combine on the field and came back to unload into the Trailers.

**Comment by pvaiko** [comment]
Can you try it with a lower field speed, like 25?

**Comment by pvaiko** [comment]
For the record:
1. The unloader does not have special logic to _continue_ to find another trailer when the first trailer is full but there is fruit left in the unloader. Currently only a self unloading combine can do that.
2. In this issue, the unloader isn't repeatedly trying the first trailer, it is trying the second one but drives so fast that can't stop in time. 
3. The trailer's fill node is in the front when empty and we use that, should probably improve on that and either always use the center of the trailer when unloading or limit how far forward we are willing to drive.

**Comment by DemsMani** [comment]
I seem to have the same problem when trying to load the Super-B Trailers (vanilla game). They are very long as they have in total four compartments and even with a low field - speed (15 km/h) it ever only stopped on the last compartment and is then not able to fill the other three.

**Comment by rohne83** [comment]
don't think this is just the Holmer. As I noted in discord I had same issue as in PapaTims video with the Bergmann beet overloader. And also during my first tests with normal grain carts (Bergmann/HAWE) I haven't managed yet to get the overloader to unload into both trailers.
Interesting to know in those regards, what is the current or planned logic for behaviour, if the grain cart still has fruit loaded when its unloading finished due to max capacity of transport vehicle reached (at least of the currently used bin)? Will it search for next trailer/bin or immediately start to listen again for combine calls? Or do you plan to make this dependent on fill level again? In FS19 you introduced a fill level setting to even control this behaviour by the user, but now this is all internal logic.

**Comment by Tensuko** [comment]
We will not introduce more settings then rly needed.
Right now the overloader will wait for the combine to call again.
What we could do is make sure the augerwagon ends up at lower then e.g 10% fixed value.
If there is not enough space to fully empty check if below 10% and wait for combine to call.

**Comment by PapaTim68** [comment]
> Can you try it with a lower field speed, like 25?

It worked once with the Field Speed set to 25. Which has a different problem on Big Fields, having a low Field Speed brings the problem of very slow movement.

I also have to agree with the others that the logic sometimes seems flawed. Especially in the case of having multiple Unloaders. They instantly stop if they don't find a Trailer on the field and have to manually enable the Driver again. Which is especially annoying when the first AD Driver just left and the one in the queue is not yet at the Waiting Point. Also, problematic when one of the Unloaders is currently unloading and the other one thus cant find a course to the trailer. I suggest a fixed timeout and retry to find a way to a trailer again.

**Comment by Tensuko** [comment]
@pvaiko fixed approach spped ?

**Comment by PapaTim68** [comment]
> @pvaiko fixed approach spped ?

An alternative approach could be using turn speed or field work speed? Also Fixed speed is probably easiest.

**Comment by rohne83** [comment]
> We will not introduce more settings then rly needed. Right now the overloader will wait for the combine to call again. What we could do is make sure the augerwagon ends up at lower then e.g 10% fixed value. If there is not enough space to fully empty check if below 10% and wait for combine to call.

Sounds reasonable. Hard to tell what a good fixed value might be here, as it also depends on the capacities of your grain carts and transport trailers. Should definitely be less than 50%, but 10% would be too strict in many cases. If a fixed setting then would rather go for sth in the region of about 20-30% maybe.

**Comment by pvaiko** [comment]
> An alternative approach could be using turn speed or field work speed?

Sure, I was going to change that, currently when we slow down at the end we just use half field speed, which can be too high as we see, so I'll make it some fixed low value.

I'm still considering limiting how far forward in the trailer we allow to discharge.
