### ISSUE TITLE
[BUG_SP] Pre-pruner not working with grapes

### ISSUE THREAD

**Issue by BrkoFarmer** [Courseplay/Courseplay_FS22#2003]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Setting the tractor and pre-pruner - I set the course, choose the "on vine" option, park tractor close to starting marker, and it doesn't do anything, starts the engine and just sits there. If i move tractor far away, it speeds into the vines and gives me obstructed error.

**Expected behavior**
To start pruning.

**Courseplay version**
Version used: 7.1.1.4

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Which vehicle or implement? Tried both vanilla smal tractors, and vanilla pre-pruner

Thanks for help!

**Comment by franky-bb** [comment]
Danke, dass noch jemand Reben mit CP zurückschneidet. Funktioniert bei mir leider auch nicht mehr. Den Fehler hatte ich schon vor einer Woche hier reingeschrieben. Der wurde leider gelöscht, weil er nicht dem Format entsprach. Letzte funktionierende Version ist die v7.1.1.2.
Folgender Eintrag steht in der Log:
C:/Users/Admin-PC/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIUtil.lua:163: attempt to call method 'getAIReverserNode' (a nil value)

**Comment by BrkoFarmer** [comment]
Thanks! Installing older version worked for me!

**Comment by Tensuko** [comment]
And again no logfile or screenshots!
Why do you delete that entry of our template, it stands there for a reason!

**Comment by franky-bb** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9775576/log.txt)

![fsScreen_2022_10_13_12_11_01](https://user-images.githubusercontent.com/35263980/195570880-4140297f-cf01-4c35-a48f-cf022e95782d.png)
