### ISSUE TITLE
[BUG_SP] Vehicle starts at the wrong waypoint after switching from nearest to first while AD activated

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#2012]
**Steps to reproduce**
Set Autodrive to "Pick up and deliver to destination" mode. Activate Courseplay button in AD. In the Courseplay Mini-HUD, set the "Nearest Waypoint" mode (because it may still be set that way from the last fieldwork). Activate Autodrive. Now set the Courseplay mode to "First waypoint". 

**Actual behavior**
Once the vehicle arrives at the destination, it will start at the nearest waypoint.

**Expected behavior**
The vehicle starts at the first waypoint as last set.

**Courseplay version**
Version used: 7.1.1.4

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9792051/log.txt)

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Doesn't matter

**Relevant script mods**
AutoDrive

**Comment by Tensuko** [comment]
So it only happens if you change the startpoint after activation of AD?

**Comment by MeRida2104** [comment]
yes

**Comment by schwiti6190** [comment]
Hi, 
you can checkout the pull request above.
