### ISSUE TITLE
How to refill with autodrive? [Question]

### ISSUE THREAD

**Issue by Horozor** [Courseplay/Courseplay_FS22#2013]
How to refill with autodrive?
The lime spreader simply stops on the field, the courseplay turns off, the autodrive does not turn on. How to set it up correctly?

![image](https://user-images.githubusercontent.com/37561569/195998417-709a6776-bda4-4c3d-b604-783c94b3a9e5.png)

**Comment by Krecik7** [comment]
turn on 'CoursePlay' icon in AutoDrive (upper row, third from right on you image), then it will work as you expect, when CP will be empty then will run AD course to fill up extenstion tool and back to field and run from place where it stopped

**Comment by Horozor** [comment]
@Krecik7 Thank you
