### ISSUE TITLE
[Question] I can't install mod courseplay

### ISSUE THREAD

**Issue by BlitzKrieg-76** [Courseplay/Courseplay_FS22#2014]
what am i doing wrong?? 
I download the mod, put it in the folder and it doesn't appear to select it within the game. am i doing something wrong??
![1](https://user-images.githubusercontent.com/53381846/196002118-c55ce370-0150-4632-82fe-b14a5e60776b.jpg)
![2](https://user-images.githubusercontent.com/53381846/196002119-06893c71-5eae-42ea-b9ac-930b502c2b8b.jpg)
![3](https://user-images.githubusercontent.com/53381846/196002124-fe24ab26-a62d-4059-8030-17142d948973.jpg)

**Comment by Horozor** [comment]
Try change moddesc version to 62 in modDesc.xml inside archive

**Comment by Tensuko** [comment]
> Try change moddesc version to 62 in modDesc.xml inside archive

I dont have to do that...

Need a logfile to check whats wrong.

**Comment by BlitzKrieg-76** [comment]
> Try change moddesc version to 62 in modDesc.xml inside archive

I change version moddesc to 62 and just work. Thanks 👍

**Comment by Tensuko** [comment]
Then you got to update your game...
