### ISSUE TITLE
[BUG_SP] Combine unload not working

### ISSUE THREAD

**Issue by Huskiel** [Courseplay/Courseplay_FS22#2015]
Hey,

the combine unload function doesn't work this tractor [https://forbidden-mods.de/filebase/file/30913-fendt-favorit-800-900/](url).
When i try to use it i only got this:

 `2022-10-16 03:46 LUA call stack:
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (229) : printCallstack
  =[C] (4294967295)
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (49) : pairs
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (64) : closeCover
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (263)
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (240) : raiseControllerEvent
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyUnloadCombine.lua (1629) : updateImplementControllers
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (229) : xpcall
  =C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (360) : try
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1881) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (129) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1134) : update
  dataS/scripts/FSBaseMission.lua (1972) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1225) : update
2022-10-16 03:46 :52 [info lp59554] C:/Users/kevin/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua:49: bad argument #1 to 'pairs' (table expected, got no value)`

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9793464/log.txt)

CP version 7.1.1.4 but same problem in older versions
Map Rostock

Would be nice if someone could help me to get it to work.

**Comment by Tensuko** [comment]
Mod Issue.
If ppl dont stick to giants standart its not our problem.
