### ISSUE TITLE
[Question] Unload Combine job when driving combine manually

### ISSUE THREAD

**Issue by meda22** [Courseplay/Courseplay_FS22#2023]
Please, I am wondering if it is possible to have courseplay worker on unload combine job when I am driving combine manually? I have tried to set it up, but it seems it doesn't work if I drive combine on my own... do I have to make some specific configuration? Or is it implemented in the way that it can work only if also combine is driven by CP worker?

**Comment by Tensuko** [comment]
That won't ever work based on the way how we unload the combine, it was the same in FS19 and so it will be the same for FS22.

Use AutoDrive if you want to drive the combine.
