### ISSUE TITLE
Courseplay on Modhab

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#2026]
Hello, I like courseplay very much. I would like to know if you can please post an updated version on Modhub, where the harvester loader has already appeared and will there be an updated version of this mod on Modhub? I am very grateful in advance for the answer and I apologize if I wrote my question in the wrong place.

**Comment by Tensuko** [comment]
We do that when we think we have a good state here on github, as we always do.

**Comment by goldorel** [comment]
That is, there will be more updates on Gidhub, am I right?
