### ISSUE TITLE
Modhub

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#2028]
Please excuse the question, you told coursplay to have a new version on modhub, that everything depends on us. Please tell me what it takes for a new version to appear on modhub? Thank you very much in advance for the answer

**Comment by Tensuko** [comment]
It does not depend on YOU.
Wait for it and done.
And now stop open new questio issues, we also have a discussion section.

WE, the dev team decide when we make the next nodhub update and we do it when we want to do it.
