### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by NO0DlIEE** [Courseplay/Courseplay_FS22#2029]
Hi
I would like to ask if the mod will be optimized for 3 monitors?
Because it's a little weird to play with him like that.
I have attached a picture so you can see what my problem is.
Yes, what you do helps the game a lot.

**Comment by Tensuko** [comment]
Removed weird links to strange picture website....
You can post pics directly on github with drag and drop.

Beside that, we had some requests about this but we closed all.
Guess we have no option to get it running.

#743
#920
#1015
