### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by descherxx1** [Courseplay/Courseplay_FS22#2031]
Wie ist denn der Stand zum Thema: Silo verdichten. Hab da leider in letzter Zeit nichts mehr zu gelesen und wäre für mich persönlich echt ne gute Hilfe. Denke für andere auch. 
da es in letzter Zeit wieder gute Updates gibt, wollte ich mich da nochmal erkundigen. 

Guter Job bisher, weiter so und besten Dank.

**Comment by Tensuko** [comment]
Es ist fertig wenn es fertig ist.... WIP.
