### ISSUE TITLE
[BUG_SP] unloader called although pipe is in fruit

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2035]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Have a sugar beet harvester (haven't tried out yet with combine) running the first row of a new land (pipe in fruit!) and getting it filled before it finishes this row.

**Actual behavior**
Unloader(s) get called for emptying this harvester at 80% although avoid fruit is turned on for harvesters and unloaders (allow unloading in first headland deactivated, and there it worked as expected - if this info helps).
In screenshot it's the one being at 77%.

**Expected behavior**
Unloaders should ignore this harvester until it has created its pocket.

**Screenshots**
![fsScreen_2022_10_24_16_35_24](https://user-images.githubusercontent.com/71030138/197601086-8872840b-e956-4d9b-97cc-6ae9c5939378.png)
![fsScreen_2022_10_24_16_35_34](https://user-images.githubusercontent.com/71030138/197601119-44c15ce9-d29d-4551-b707-6123b72187ff.png)
![fsScreen_2022_10_24_16_35_41](https://user-images.githubusercontent.com/71030138/197601130-d73ef42d-3400-4ccb-a8f3-2a05eb60472d.png)

**Courseplay version**
Version used: 7.1.1.5 (was also the case at least with 7.1.1.4)

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9854387/log.txt)

**Map**
Landkreis Rostock

**Vehicles/ implements involved**
Vanilla Ropa Tiger sugar beet harvesters. Think this might also happen with combines?

**Comment by Tensuko** [comment]
Could be the field state, not sure

**Comment by pvaiko** [comment]
Even if it made a pocket I doubt that we'd be able to navigate in there through the 3 m narrow harvested swath.

I need the harvester's debug on as it is the harvester who decides when to call the unloader. The unloader drives through the fruit because it did not find a path avoiding it after several tries.

**Comment by rohne83** [comment]
thanks, I just did a quick check with a combine with 10m header and there I couldn't observe this behaviour. So it might indeed have to do with the low working with. For that sugarbeet harvester it's not 3m though but even 4, which is about the same as for many old combines. Haven't done a new check with that harvester though to provide log with its debug enabled as well.

**Comment by pvaiko** [comment]
Closed due to inactivity
