### ISSUE TITLE
[Enhancement] Brent Avalanche Grain Cart lifts pipe too high

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#2036]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use combine unloader from courseplay to unload combine and let it unload into a truck with a Super-B trailer

**Actual behavior**
The unload process starts, but the unload auger of the graincart gets lifted until it is out of the range of the trailer and therefore unloading stops. And maybe as a more cosmetical issue: The tarps do not open during unloading (which would be problematic in RL)

**Expected behavior**
Pipe is not moved during unload so the unloading process proceeds

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://youtu.be/pJwpjHVJGUY

**Courseplay version**
Version used: 7.1.1.5 

**Log**
https://gist.github.com/DemsMani/13e3d5b0cb82aa47e774213c4f81e0c3

**Map**
FS22 Red River Manitoba

**Vehicles/ implements involved**
Fend 942 (Vanilla Game), Super-B Trailers (Vanilla Game), Brent Avalanche Grain Cart (Modhub)

**Relevant script mods**
CP, AD

**Comment by Tensuko** [comment]
Not sure why this mod lift its pipe that high.
Vanilla should not do this.

**Comment by schwyl** [comment]
I use this modded Grain cart without issue

**Comment by Tensuko** [comment]
I dont want to see any links from those mod stealing shit websides!

**Comment by DemsMani** [comment]
I now reduced the rotation angle limit for the auger in the xml of the grain cart. It is of course a workaround, but ok for me. So unlike someone else is using this enhancement, you can also close it if you want.

**Comment by Tensuko** [comment]
Should be fixed with the next Release
