### ISSUE TITLE
Try it again. Oo Really

### ISSUE THREAD

**Issue by wackoamd1** [Courseplay/Courseplay_FS22#2039]
Try it again.

_Originally posted by @Tensuko in https://github.com/Courseplay/Courseplay_FS22/issues/2038#issuecomment-1290521154_

what kind of answer is that , Oo
it doesnt work i am on the latest 7.1.1.5
there is NO help for courseplay in the fs22 help

**Comment by Tensuko** [comment]
1) Template?
2) logfile?

**Comment by Tensuko** [comment]
> there is NO help for courseplay in the fs22 help

![fsScreen_2022_10_25_17_13_13](https://user-images.githubusercontent.com/27344744/197812781-b25e58d2-08f0-4289-ba3a-14c149a91b91.png)


YOU tell ME again there is no help section!
logfile!

**Comment by wackoamd1** [comment]
![20221027115417_1](https://user-images.githubusercontent.com/5446360/198262523-79e19b30-f282-414c-9c99-8fec454a6469.jpg)
![20221027115422_1](https://user-images.githubusercontent.com/5446360/198262529-76b9001b-3705-44b7-bde0-b67242c31671.jpg)
![20221027115425_1](https://user-images.githubusercontent.com/5446360/198262532-23532c52-dee0-4395-899d-6af37480b0c0.jpg)
![20221027115408_1](https://user-images.githubusercontent.com/5446360/198262538-04e25ce3-43a9-4069-b3b1-9be3c8bf0c88.jpg)
![20221027115413_1](https://user-images.githubusercontent.com/5446360/198262539-54ff3b68-be03-4068-b96a-5d226d642b9e.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9878482/log.txt)

like i said NO help

**Comment by Tensuko** [comment]
Ah, you got (Version: 1.1.0.0) pdlc_pumpsAndHosesPack
If you would have posted your logfile at the start, I could tell you that the Version 1.1 of PnH got a bug where it makes some Help entrys disappear, like Precisition Farming and also Courseplay.
Update PnH to 1.2 (or for testing and proove, turn it off) and the entry is back.
