### ISSUE TITLE
i cant hire a CP driver it just hires the ingame ai and i have a course made [BUG_SP]

### ISSUE THREAD

**Issue by JeffJeffery45** [Courseplay/Courseplay_FS22#204]
**Steps to reproduce**
Steps to reproduce the behavior.
made a course could hire cp to do the course tried it out of the field, still wouldn't work went in the field still didnt work tried different fields and still wouldnt work
**Actual behavior**
A clear and concise description of what happen.
made a course and could hire the worker
**Expected behavior**

**Screenshots**
dont have any cause they just hire normal ai worker
**Courseplay version**
Version used: 
latest versio
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
elm creek
**Vehicles/ implements involved**
Mod yes/no ?
no
**Relevant script mods**
Mods like Autodrive or VCA and so on.
nonr

**Comment by Tensuko** [comment]
> **Log**
> Please attach a log with all debug channels active.
> For help with the debug channels,
> please check out the readme at the github front page.

and where is your logfile or Version information ?
