### ISSUE TITLE
Gülle muss aufgefüllt werden[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2043]
Hallo
Was muss ich hier machen, der Wagen ist mit Gülle gefüllt, aber zeigt an muss aufgefüllt werden
![Gülle 1](https://user-images.githubusercontent.com/47453761/198097257-724bb383-8f78-4418-8d13-4f921e3af236.png)

**Comment by Tensuko** [comment]
Sind das Geräte aus dem Standartspiel?
Was hast du noch an Mods?
logfile?

**Comment by Tensuko** [comment]
Hab einfach mal Geräte geraten, bei mir gehts.
Vermute ein Mod conflict.
![fsScreen_2022_10_26_20_31_34](https://user-images.githubusercontent.com/27344744/198107580-fb6183da-7ed2-45b7-97a1-f5a651d15130.png)

**Comment by Hendirk** [comment]
Also genau diese Maschine ist das 


Gesendet von Mail für Windows

Von: Tensuko
Gesendet: Mittwoch, 26. Oktober 2022 20:32
An: Courseplay/Courseplay_FS22
Cc: Hendrik; Author
Betreff: Re: [Courseplay/Courseplay_FS22] Gülle muss aufgefüllt werden[Question] (Issue #2043)

Hab einfach mal Geräte geraten, bei mir gehts.
Vermute ein Mod conflict.

**Comment by Hendirk** [comment]
Hier die Log
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9872918/log.txt)

**Comment by Tensuko** [comment]
Spontan würde ich sagen, schmeiß den mal raus:
FS22_EnhancedDragHoses
Hab sowieso keine Vertrauenswürdige download Quelle gefunden.

**Comment by Tensuko** [comment]
Wegen inaktivität geschlossen.
Da es auch nicht reproduzierbar war, vermute ich hier ein Modissue/Modconflict.
