### ISSUE TITLE
Translation of cs and ct should be reviewed (v7.0.0.8)

### ISSUE THREAD

**Issue by Big-Fool** [Courseplay/Courseplay_FS22#205]
I think the current CH translation of "Courseplay" should be reviewed.
This CH word means "the way to deal with curriculum (school or college)", this kind of weird name will totally mess up new farmers who never heard of the famous Courseplay.

I was starting to play the series of FarmingSimulator (together with CP) since 2012, at that time CP is functionally designed for 'auto drive' and 'auto work', nowadays CP inherited the very beginning, and most focus on 'auto work'.

Wherefore I think it's better to translate "Courseplay" in CH with
cs 自动作业
ct 自動作業
Which means "automatic farming" or "automatic working".

**Comment by Tensuko** [comment]
Thanks for the Feedback. Will change that.
