### ISSUE TITLE
Fahrzeug wird blockiert

### ISSUE THREAD

**Issue by FarmerMario** [Courseplay/Courseplay_FS22#2051]
![20221029144726_1](https://user-images.githubusercontent.com/98883983/198832913-c4019afa-d538-490c-a454-b36beb4c1745.jpg)

Hallo,
Ich weiß nicht,ob das ein Bug ist oder hier irgentwo schon mal gefragt wurde.
Wie auf dem Foto zu sehen ist, wird der Traktor (vorher wurde der Drescher beim Wendemanöver auch schon) von einem Haufen,der beim überladen des Dreschers ensteht, blockiert.
Ich benutze CP v7.1.1.5 .
Nf-Marsch
Bei den vorherigen Versionen wurden die Fahrzeuge nicht blockiert bzw. ich weiß nicht ab wann das aufgetreten ist.

mfg Farmer Mario

**Comment by Tensuko** [comment]
Naja eigentlich gut, dass er hier anschlägt.
Er könnte bei dem großen Haufen auch stecken bleiben...

**Comment by FarmerMario** [comment]
OK das stimmt vollkommen,aber ist es nicht möglich wie bei AD die Kollisionserkennung über Boden einstellen kann.

**Comment by Tensuko** [comment]
Nein, kann man nicht.
Das würde bei uns auch noch zu anderen Probleme führen.

**Comment by FarmerMario** [comment]
Danke für Deine Antwort,
konnte das Problem lösen,in dem ich mir einen Frontschwader-Mod zulegte.
Damit klappt es sehr gut.
Nochmals Danke.

mfg Farmer Mario
