### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by mpochylko** [Courseplay/Courseplay_FS22#2055]
Good day everyone,

Dedicated server, CP is displaying this error when trying to evter game: Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/parameters/AIParameterSettingList.lua:309: attempt to perform arithmetic on local 'value' (a nil value). When the server is reset, everyone can enter the server again.

**Steps to reproduce**
Have courses setup, exit game and try to reenter.

**Actual behavior**
Stuck on syncronization at 23%

**Expected behavior**
Game loads normally.

**Courseplay version**
Version used: 7.1.14

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
N/A, not our server. 

**Player on the server**
3

**Dedicated server or local hosted server**
Dedicated server yes/no ? Yes

**Map**
Morris, MB 

**Relevant script mods**
Autodrive 2.0.07

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9896397/log.txt)

**Comment by Tensuko** [comment]
Non Courseplay related Callstack:
2022-10-30 10:55   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-10-30 10:55 LUA call stack:
  dataS/scripts/mods.lua (423) : printCallstack
  =C:/Users/Pochylko/Documents/My Games/FarmingSimulator2022/mods/FS22_reduceMaintenanceCosts/RegisterSpecialization.lua (80) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (374) : source
  dataS/scripts/mods.lua (875) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (872) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1179) : update
2022-10-30 10:55   Error: Too many arguments for SpecializationManager.addSpecialization. (Arguments should be: name, className, filename, customEnvironment)
2022-10-30 10:55 LUA call stack:
  dataS/scripts/mods.lua (428) : printCallstack
  =C:/Users/Pochylko/Documents/My Games/FarmingSimulator2022/mods/FS22_reduceMaintenanceCosts/RegisterSpecialization.lua (80) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (374) : source
  dataS/scripts/mods.lua (875) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (872) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1179) : update

Available mod: (Hash: 012eaf4ca1f1fad09ab4378d6cbdbe32) (Version: 1.1.0.0) FS22_relightstandalone you may should update this.

Another non Courseplay related Callstack:
2022-10-30 10:56   Warning (C:/Users/Pochylko/Documents/My Games/FarmingSimulator2022/mods/FS22_AFQM_West_EP_Pack/files/EP40.xml): Missing collision mask bit '21'. Please add this bit to component node 'MidMud'
2022-10-30 10:56   Error: Failed to find child 23 from node Box, only 9 children given
2022-10-30 10:56 LUA call stack:
  dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
  dataS/scripts/i3d/I3DUtil.lua (100) : checkChildIndex
  dataS/scripts/i3d/I3DUtil.lua (448) : indexToObject
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/i3d/I3DUtil.lua (444) : iterate
  dataS/scripts/vehicles/Vehicle.lua (829) : loadI3DMapping
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
2022-10-30 10:56   Error: Index not found: 0>8|10|23
2022-10-30 10:56   Error: Failed to find child 1 from node LiftAxle, only 1 children given
2022-10-30 10:56 LUA call stack:
  dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
  dataS/scripts/i3d/I3DUtil.lua (100) : checkChildIndex
  dataS/scripts/i3d/I3DUtil.lua (448) : indexToObject
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/i3d/I3DUtil.lua (444) : iterate
  dataS/scripts/vehicles/Vehicle.lua (829) : loadI3DMapping
  dataS/scripts/i3d/I3DManager.lua (134) : asyncCallbackFunction
2022-10-30 10:56   Error: Index not found: 0>9|4|0|0|1

Same for the EP48.xml of the same pack.

If this Error is a followUp, not sure, the logfile of the Server would be interesting too, but first you should solve the Callstacks of the other mods (throw them out)
2022-10-30 10:56 Error: Running LUA method 'packetReceived'.
C:/Users/Pochylko/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/parameters/AIParameterSettingList.lua:309: attempt to perform arithmetic on local 'value' (a nil value)

**Comment by Tensuko** [comment]
closed due to inactivity
