### ISSUE TITLE
[BUG_SP] MULTIPLE COMBINE, THE LEFT CHANGES COURSE TO THE RIGHT, WHY?

### ISSUE THREAD

**Issue by charlotte507** [Courseplay/Courseplay_FS22#2056]
I have a problem with the use of multiple combines, I select 2 to harvest a field, one on the left and the other on the right, in the headers everything goes well, but in the fields the left always changes course to the right despite that it is selected to go to the left, why does this happen?

**Comment by Tensuko** [comment]
Read the ingame help about symetric lane change.
