### ISSUE TITLE
[BUG] It does not detect the herbicide spreader working width

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#206]
**Steps to reproduce**
purchase a 24 m herbicide spreader to be connected to the tractor. open it and generate the course. gives you 1.1m. 2 out of 2 trials in 2 loaded gameplay.

**Actual behavior**
it does not detect the working width 

**Expected behavior**
I expected it to detect the value of the tool (24m).

**Screenshots**
![fsScreen_2021_12_28_16_52_44](https://user-images.githubusercontent.com/96330304/147584712-c47fe902-a265-46cd-9783-44e493aa52d7.png)
![fsScreen_2021_12_28_16_52_54](https://user-images.githubusercontent.com/96330304/147584746-f7bdf2bf-1a77-4495-abe8-c1891ff134bc.png)

**Courseplay version**
Version used: 7.0.0.8

**Log**
does not give any log errors 

**Map**
MapUS default

**Vehicles/ implements involved**
massey ferguson mf the base one of the MapUS and the herbicide spreader the 24m one that I don't remember the name now but can be seen on the screen

**Comment by Obsiana2019** [comment]
Same with other tools

**Comment by Himiriel** [comment]
Same with all or almost all tools on commit 0ceb349165bd678238c5f19595a8b132938468fa

**Comment by Markus33-ITA** [comment]
I tried it now and it does it also with the fertilizer spreader with partialization and the deutz fahr combine with its wheat blade

**Comment by Tensuko** [comment]
> Same with all or almost all tools on commit [a37075f](https://github.com/Courseplay/Courseplay_FS22/commit/a37075f3e7179a48b013235dc9ef745ab3aab3ab)

What does a text change have to do with the workwidth ?!

**Comment by Tensuko** [comment]
Yea its broken... will have a look.

**Comment by Himiriel** [comment]
Reverting this commit seems to help 901bc4053d676f5d05181a1a6480214f613adad2

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.9 
Right now, detach and attach will ask for the correct workWidth, if it does work for all Tools, thats another story as Giants seem to have some stuff changed on that....

**Comment by Himiriel** [comment]
Fixed for me in 7.0.0.9. Checked on a roller and on a sprayer.

**Comment by viktor25121980** [comment]
Wann wird Courseplay  Weizen von Feld zu Silo wird bringen?
