### ISSUE TITLE
[BUG_SP] Abtankrohr in Frucht mit ungerader Beete Anzahl

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#2060]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Kursgenerieren mit Vorgewende und Beete

**Actual behavior**
Abtankrohr von Drescher/Roder in Frucht bei Beete (Betrifft immer das komplette Beet)

**Expected behavior**
Abtankrohr immer auf der nicht Fruchtseite.

**Screenshots**
![20221028224036_1](https://user-images.githubusercontent.com/47928255/199191017-0442e4bb-65e2-46e9-a546-8fb67eb6e9af.jpg)
![20221029140824_1](https://user-images.githubusercontent.com/47928255/199191355-f7a0bb5a-14c8-4acc-8cc7-0bc28566e8a3.jpg)
![20221030161458_1](https://user-images.githubusercontent.com/47928255/199191744-a82fd2fd-144b-42ce-a3ed-0a4cac27c3ef.jpg)

**Courseplay version**
7.1.1.5
Die Kurse wurden aber auch mit etlichen vorhergehenden Versionen erstellt.

**Log**
Ich glaube das bringt nicht viel, da die meisten Kurse bereits erstellt und gespeichert sind und ich sie nur lade.

**Map**
NF Marsch oG

**Vehicles/ implements involved**
Eigentlich egal welcher.

**Relevant script mods**

Kommentar:
Das ganze ist leider beim Kurserstellen recht schwer bzw. gar nicht zu erkennen, man stellt es erst fest, wenn man den Drescher bei der Arbeit beobachtet.
Es scheint auch so zu sein, dass die Beete sich abwechseln, sprich ein Beet ist richtig, das nächste falsch, dann wieder richtig und dann wieder falsch.
Die Anzahl der Bahnen pro Beet und Vorgewende scheint keinen Einfluss darauf zu haben.
Vorgewende hatte ich immer auf Scharf.

Anbei zwei der Problemkurse.
[50-5,4M-4VGS-B9-CW.zip](https://github.com/Courseplay/Courseplay_FS22/files/9908229/50-5.4M-4VGS-B9-CW.zip)
[17-12,0M-2VGS-B5-CW.zip](https://github.com/Courseplay/Courseplay_FS22/files/9908236/17-12.0M-2VGS-B5-CW.zip)

**Comment by Tensuko** [comment]
> **Log** Ich glaube das bringt nicht viel, da die meisten Kurse bereits erstellt und gespeichert sind und ich sie nur lade.

Kurse wegschmeißen, debug aktivieren und neu generieren. Dann hilft auch das logfile...
Aber ich bin mir zimlich sicher, irgendwo hast du einen Fehler im Generator.

**Comment by blubstar86** [comment]
Ja das hast du natürlich Recht mit der log....
Ich such mal nach einem Feld.

Hast du einen Tipp für mich wie man erkennt ob der Kurs Fehlerhaft ist oder nicht, im Helfermenue erkennt man das nicht wirklich.
![image](https://user-images.githubusercontent.com/47928255/199201229-5bb1f054-1f6b-4a19-8634-e26452c40352.png)


Einstellen kann man auch ungerade Zahlen.
![image](https://user-images.githubusercontent.com/47928255/199200664-e89f01c4-acd1-4c71-a7f6-acd0c2b7f87c.png)

**Comment by blubstar86** [comment]
Frischer Spielstand auf der Elmcreek, nur AD und CP als mods.

Bei der Kursgenerierung hab ich 3 Bahnen pro Beet ausgewählt.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9909231/log.txt)

Beet 1 - richtig
Beet 2 - falsch
Wendemanöver sein Vater :)
![image](https://user-images.githubusercontent.com/47928255/199215843-aeb379ee-30b2-4f56-8915-137d6dcfd751.png)

Beet 3 - richtig
Beet 4 - falsch
Beet 5 - richtig
Beet 6 - richtig

**Comment by Tensuko** [comment]
Reihen pro Beet 7.
Das ist genau das Issue was ich verlinkt habe.
Nutze bitte gerade Zahlen und ich schau mal warum wir die ungerade überhaupt noch drin haben.... #522
