### ISSUE TITLE
[BUG_SP] Combine Self-Unload wrong positioning.

### ISSUE THREAD

**Issue by LuciFearium** [Courseplay/Courseplay_FS22#2067]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Courseplay - Installed 
Lizard Underbelly Trailer - Installed.

Take trailer to field (park anywhere on/off field as long as within range), start harvester and wait for harvester to start self unload to trailer. Harvester should pull to trailer and then reverse directions for combine to unload on the wrong side of combine (pipe is on left side, tries to unload from right side)
**Actual behavior**
A clear and concise description of what happen.

 Self-Unload for Combine tries to unload on the incorrect side of combine. Only happens with Lizard Underbelly Trailer for some reason, base game trailer works fine. Not sure if this is fixable by you or not, because on other fields i've literally had it work fine with this exact Combine/Header/Truck/Trailer combo.

**Expected behavior**

Combine creates path, follows path to correct side of trailer (or rotates correctly) and unloads.

**Screenshots**
First sc is when i first noticed the problem, turned on debugging and tried again. 
![image](https://user-images.githubusercontent.com/61132760/199600384-bada3abb-1fb5-4986-8bae-9a433ee35d56.png)

Second sc is after I turned on the logging feature for all of the channels, just posting again as another example
![image](https://user-images.githubusercontent.com/61132760/199602586-ab129916-a0f8-4d8a-8f58-044e1bb14c64.png)

**Courseplay version**
Version used: 7.1.1.5

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
I really hope this log helps? Im not 100% sure this is the right file but i think it is.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9924155/log.txt)

**Map**
Map played on.
Iowa Plains View

**Vehicles/ implements involved**
Which vehicle or implement?
Base game Case IH AxialFlow 7150
Mod yes/no ?
Lizard UnderBelly Trailer - Mod - 1 Tank, 110,000L

**Relevant script mods**
Mods like Autodrive or VCA and so on.
I think the only one is CP, atleast the only relevant one.

**Comment by Tensuko** [comment]
So if I understand correct, same situation, all other trailers work fine, just that mod trailer not?

**Comment by LuciFearium** [comment]
I got it from the in-game mod hub.
 I know it sounds crazy to ask you guys if its your fault, since it seems like after half an hour and just using an auger wagon in between everything works fine. But I don't know how the trailer itself could be have become a problem after using it for like 3 hours with no problems, then all of a sudden bam it doesn't work consistently. Like, it might work 1 or 2 times but then the 3rd and 4th time it faces the wrong way. So i wasn't sure where to post it first.

**Comment by Tensuko** [comment]
Ok so it can work but it also can ge to the wrong side...
Thats strange.

**Comment by LuciFearium** [comment]
Yeah, i probably didnt make that clear enough at first. That is also why I was pretty sure it might be on the pathfinding? side but I'm obviously no expert and i know very little. Let me know if there is anything else you need of course

**Comment by pvaiko** [comment]
Only thing I can think about is that one of the trailer's fill nodes is pointing in the wrong direction, so depending on the trailer's fill level, if that wrong node is active, the combine drives to the wrong side. 

We assume that all fill nodes are pointing forward.

**Comment by LuciFearium** [comment]
Do you know of any way for me to figure that out?

**Comment by rohne83** [comment]
unzip the mod and open the i3d in Giants editor. Search for a shape named fillNode / exactFillRootNode or sth like that. This shape should be a box at the top of the trailer (in Attributes subwindow you can make it visible if it's not visible yet), its origin (the origin of the arrows) should be amidst it, with the blue arrow pointing forward, the red arrow to the left, and the green arrow up.

**Comment by LuciFearium** [comment]
I know this is not the place to come and have you teaching me this, but from the way you explained it, this seems to be wrong. 
![image](https://user-images.githubusercontent.com/61132760/200091240-862401e6-82dd-4613-8ee3-e3fda5bf2976.png)
I see green going forward, red left, blue down. Does that simply mean that this trailer is just kinda out of the running for using with the unload feature, as it's not what you are expecting?

Also I really appreciate you helping me figure this out, i really enjoy this trailer for no specific reason and was hoping it was a LOT simpler than this to fix for you guys or me.

**Comment by Tensuko** [comment]
No one from us can help you with this.
We don't do modding on objects or models.

**Comment by pvaiko** [comment]
> No one from us can help you with this. 

Well, I brought up the fill node, and although we do not mod vehicles, we have to be familiar with common model characteristics, such as the fill node, which, again, we expect to point forward (the Z, blue axis). And that does not seem to be the case here.

**Comment by rohne83** [comment]
Then it looks like a mod issue here indeed. Seems that x axis of the fillNode is rotated by 90 degrees. This can indeed have strange effects when unloading with CP.
If you're familiar with GE, you can fix this yourself using the Freeze Transformations function, applied on the rotations only of the fillNode. But don't expect detailled GE help here in CP github.

**Comment by LuciFearium** [comment]
I'm not the creator of the mod, so I did reach out to them, but based on what was said here I did look into reaching out to them and seeing what could be done about fixing it. For now I'm probably going to do some basic toying with the trailer and CP to see if I can get it fixed on my end and get it to work as you guys have pointed out that it seems it is unlike other trailers i've loaded in to peek at. Thank you for all the help, sorry for wasting your time!

**Comment by garo73** [comment]
Good news, the modder have fixed it!

**Comment by Tensuko** [comment]
Thats cool! :)

**Comment by Kieruss** [comment]
The fixed mod will be submitted to ModHub shortly. Thanks for tracking down the problem. It was working fine with my testing, but I wasn't aware it was intermittent.

LuciFearium - How did you try to contact me? I haven't heard from you. My Youtube, Facebook, and Discord contact details are available via the "Powered By" link on ModHub, which links to https://fs.mantrid.net/
