### ISSUE TITLE
[Feature] Automatisch Auffüllen von Güllefass am Feldrand 

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#2069]
**What is the problem this feature/enhancement solves?**
Das Gespann oder der selbstfahrer bleiben auf dem Feld stehen wenn sie leer sind und nicht via. Autodrive zum befüllen fahren

**Describe the solution you'd like**
Ähnlich wie beim Drescher und dem selber abtanken. Das Gespann / der Selbstfahrer fahren eigenständig zum Feldrand wo ein Feldrancontainer mit Substrat steht oder ein Zubringer.

**Describe alternatives you've considered**
Alternative ist aktuell selbst zum befüllen fahren oder via Autodrive eine Automation durchführen

**Comment by Tensuko** [comment]
Die Idee haben wir durchaus, aber die priorität ist eher niedrig.
Mal schauen ob uns was einfällt.

**Comment by rohne83** [comment]
Nicht nur Güllefässer. Auch für Düngerstreuer und Sämaschinen wäre das sehr willkommen. Befüllung dann halt in der Regel per ULW, und falls dann noch irgendwie möglich per Radlader (Mist und Kalk können normalerweise nicht mit ULW transportiert werden, sondern nur mit normalen Anhängern und werden von diesen als Haufen am Feldrand abgekippt).

**Comment by Tensuko** [comment]
Genau desshalb, low priority.
Möglichst viel erschlagen können etc.
Ich habe eine Richtung in die es gehen könnte, aber muss man abwarten...

**Comment by 0scarZulu** [comment]
Naja mir würde Gülle erstmal reichen weil es denk ich von der Art ist wie Drescher abtanken nur umgekehrt. Man hat ja den Beladetrigger durch den Zubringer. Mit Radlader und Co wäre dann schon zu viel .. Gülle wäre vollkommen ausreichend

**Comment by Tensuko** [comment]
Wenn dann suchen wir uns was raus, was für die meisten Dinge hilft und die wenigste Arbeit bedeutet.
Kann aber schon sagen, dieses Jahr vermutlich nicht mehr :)

**Comment by NeonRider1999** [comment]
Also ich muss sagen das wäre eine echte Bereicherung. Bringe selber sehr viel Gülle aus und das würde vieles Erleichtern

**Comment by BruderJohn** [comment]
Wollte mal fragen ob dieses Feature bald geplant ist oder wo man da am besten ansetzt dieses Fetature umzusetzten.

**Comment by Tensuko** [comment]
#2179
