### ISSUE TITLE
Translation difficulties

### ISSUE THREAD

**Issue by dimdroid** [Courseplay/Courseplay_FS22#207]
Hello.
The translations lack such parameters as:
"CP_vehicle_courseGeneratorSetting_returnToFirstPoint_releaseDriver" 
"CP_vehicle_courseGeneratorSetting_returnToStartAndReleaseDriver"

I can't figure out how they work.
Don't scold too much. I didn't teach English at school. An online translator was used.

I'm sorry what's wrong.

**Comment by Tensuko** [comment]
Those settings are not used anymore, not sure why they are still in there.
