### ISSUE TITLE
[BUG_SP] Baler gets stuck on the corners of the course

### ISSUE THREAD

**Issue by Green2772** [Courseplay/Courseplay_FS22#2080]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create any course that has 90 degree angles.
Mow the grass and start making bales with BiG Pack 1290 HDP VC. After filling one bale and filling the second one by about 60%, there is a jam at any angle of the course with the inscription "Blocked by an object"

**Actual behavior**
If the unfilled bale is still inside the baler, it gets stuck at the corners of the course.

**Expected behavior**
This does not happen in version 7.1.1.4

**Screenshots**

**Courseplay version**
Version used: 7.1.1.6

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9947042/log.txt)

**Map**
Map Elm Creek
**Vehicles/ implements involved**
FENDT 1038 Tractor and Big Pack 1290 HDP VC Baler
![20221107011709_1](https://user-images.githubusercontent.com/117604979/200200207-d55d0f42-d687-4eef-b441-4f05f31822aa.jpg)
![20221107011739_1](https://user-images.githubusercontent.com/117604979/200200223-c008dc10-3532-4b78-9f74-af616346364c.jpg)
![20221107011750_1](https://user-images.githubusercontent.com/117604979/200200226-acbfa784-b15b-496a-99c4-f566098a1803.jpg)

**Comment by Tensuko** [comment]
#1863
