### ISSUE TITLE
[Question] Bale collect limits

### ISSUE THREAD

**Issue by fudoido** [Courseplay/Courseplay_FS22#2086]
Hey team, playing currently on Landownunda 16x map and noticed that bale collect function is not working all the time, and i wonder if there is any kind of limit for the bales detection.
The field i am working at the moment is field 17, in case you dont know the map, the field takes almost the entire map (16x) from north to south, and about 1/4 size of map from west to east, so its a really big field, straight edges, not an odd shape.
Combine harvesting works fine, but when i restart the helper with courseplay it freezes for some seconds, baler activates straight away with same route as harvester. 
It is only the bale collect feature that seems to fail from time to time, and i think it might be because the field is too big and courseplay has a distance limit to search for bales? 
No error pops out, it just deactivates right after i click to activate, or when autodrive finished driving the course to the waypoint and triggers courseplay, courseplay will deactivate (on this last case, ignoring autodrive also and not triggering it to restart course, stands unmovable at waypoint with autodrive deactivated).
And running latest CP version downloaded from here, not modhub version (which tells me to update since its older than the github version and therefore not matching, requiring the update).

Any feedback on this issue?
Regards, and keep the awesome work :)

**Comment by fudoido** [comment]
oh, just to add, bale collect is not running with a recorded course, autodrive takes it into the field and triggers the automatic collection, no CP course for it.

**Comment by Tensuko** [comment]
logfile with debug active in the vehicle settings.
When it stops, it should say whats happening.
Also.... are all bales done yet?

**Comment by fudoido** [comment]
not all done yet, im harvesting and the baler behind it working, trailer picks up bales easy if they are nearby, its only when they get  further away that it stops operating. i tried to minimize this issue by placing a 2nd waypoint in the other edge of the field and have a 2nd trailer working there. meanwhile baler also made some more bales that CP is able to detect near its initial waypoint, when it gets clear again and the issue replicates, i will try to get the log.
it feels like it is a distance thing, being the field so big, the 2nd trailer and waypoint i created is operating normal, since there are still plenty bales in that side of the field. i am waiting to see if any bales are left somewhere in the middle of the field, that could indicate my suspect of distance issue.

**Comment by fudoido** [comment]
ok, a not so good update...... the landownunda map creator has releaased a new version, but with that came a new savegame also. To avoid conflicts and errors, i deleted the old save and started new, thats the bad part :(
the good part however, is that i can now test this more deeply, because instead of the harvesting mission on that big field, i got a baling mission, so lots and lots of bales pouring out for a fresh test lol.
will try to update the situation and post the log in case of this issue happening again. and my deepest sorry for the delay @Tensuko hope you understand.

**Comment by Tensuko** [comment]
At least you give feedback.
Ok test it and have debug on when issue appears and attach the log then
