### ISSUE TITLE
[Feature] Add a snap keybind for creating custom fields with straight lines

### ISSUE THREAD

**Issue by brown-star** [Courseplay/Courseplay_FS22#2089]
The draw custom fields option is fantastic. I would like to be able to snap straight lines when drawing the boundaries.
Perhaps a keybind to enable snapping and another to increase decrease the angle (0, 30, 45, 60, 90 etc.)

**Comment by Tensuko** [comment]
Combine Issues:
#1871

**Comment by Igi-PL** [comment]
Hi.

You've done a lot of good work with the custom fields.

I'm also having trouble drawing straight lines ( #1871 ), and besides, I'm using a "Fieldcalculator", which makes me want to represent the field as accurately as possible.
I can see on the AI screen that the CP can mark the field boundaries when clicking on a plowed area (when creating a course).

Maybe this mechanism could be used to create precise and/or straight custom field.
