### ISSUE TITLE
[BUG_SP] Grain Cart not finding path to self unload

### ISSUE THREAD

**Issue by Cagcody1** [Courseplay/Courseplay_FS22#2090]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
have tried multiple different tractors, grain carts and truck positions.  This worked on previous version of CP.  

**Actual behavior**
Grain Cart unloads both combines (or one if only one on course).  When grain cart looks for truck to unload, it sits for a minute and then gives an error that no path is found.  I have moved trucks closer and still same error.  Combines can self-unload under CP just fine.  

**Expected behavior**
grain cart finds path to trucks to unload 

**Screenshots**

**Courseplay version**
Version used: Recent Version

**Log**
Attached
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9989373/log.txt)

**Map**
Elm Creek 4x 

**Vehicles/ implements involved**
JD 7R / Kinze Grain Cart

**Relevant script mods**
Trucks are on autodrive but have also tried just parking the trucks with no autodrive active.

**Comment by kobra60** [comment]
I too am experiencing this from time to time.  Demco 22 cart. Michigan 16x Map.

**Comment by Tensuko** [comment]
A few scereenshots about positions and stuff would be helpful.

**Comment by Cagcody1** [comment]
OK I will grab some tonight when I get home from work.   I have tried it in fields 30 and 32.  When watching the pathfinder it just sits there after backing up from the combine and then flashes and then gives the error.

**Comment by Cagcody1** [comment]
OK so I tried to get some screenshots tonight but the error seemed to be random.  At one point (log2) the grain cart had just finished filling up one truck and there was another truck right behind it when it then lost the path and gave the error and exited the helper

.   On another time, the wagon had just unloaded a harvester and then could not find a path (log) to the two trucks waiting.  I will try to do some more tomorrow and try to get screenshots.  

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9993903/log.txt)
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/9993910/log2.txt)

**Comment by Tensuko** [comment]
Just make Screenshots so we have an overview about the field, what combine, what trailer, where does it wait and stuff....

**Comment by BullsEye1005** [comment]
Habe das selbe Problem. Der Fehler tritt aber nur auf wenn mehr als 1 Lkw am Feldrand steht und wartet. Bei nur einem LKW findet der Überladewagen problemlos den LKW

**Comment by Tensuko** [comment]
Und WIE stehen die beiden LKWs da?
Bilder.....

**Comment by Tensuko** [comment]
Stehen die LKW sauber, gar kein Problem....
![fsScreen_2022_11_12_15_44_54](https://user-images.githubusercontent.com/27344744/201479615-8ad9f9e3-1e37-4897-8b18-0a4563c77781.png)
![fsScreen_2022_11_12_15_45_17](https://user-images.githubusercontent.com/27344744/201479618-b4617089-bbda-4c13-89b8-0dbf3f35bd5e.png)
![fsScreen_2022_11_12_15_45_31](https://user-images.githubusercontent.com/27344744/201479628-2be0e4d5-aaea-4a73-9294-db9a594ac649.png)
![fsScreen_2022_11_12_15_45_53](https://user-images.githubusercontent.com/27344744/201479634-54ce55f8-05fe-4ee9-a192-ef370ff39b55.png)
![fsScreen_2022_11_12_15_46_18](https://user-images.githubusercontent.com/27344744/201479639-20d99e4c-8671-4f87-9058-e844419bba17.png)
![fsScreen_2022_11_12_15_48_24](https://user-images.githubusercontent.com/27344744/201479702-dc84e431-dd74-4696-96f3-8ab80f0a2aa1.png)

**Comment by rohne83** [comment]
Also have this issue from time to time. Happens very random (a bit more often when there's more than one unloader waiting, but it's just a higher probability not a direct connection), so quite hard to capture it with screenshot and debug enabled in that moment. But have a few screenshots of such situations, if this helps a bit:

![fsScreen_2022_11_04_21_27_33](https://user-images.githubusercontent.com/71030138/201481982-550bf85f-e694-4367-939b-dcd47978066c.png)
![fsScreen_2022_11_06_16_57_24](https://user-images.githubusercontent.com/71030138/201482012-11df8616-5650-4b88-8662-74b15954553d.png)

**Comment by Tensuko** [comment]
It might be the case, that this auger wagon needs to drive closer, wich would be #2092

But Original Issue is about Kinze Grain Cart so I wonder why it happens there, since that one got a pipe that goes way more to the side so there is much more space for the driver.

**Comment by BullsEye1005** [comment]
Prinzipiell kann der Überlader doch von Grund auf an was weiter weg fahren....Es ist ja noch viel Spielraum da, wenn das Rohr ausgeklappt ist/wird. Du meinst auch, der findet den Weg nicht bei 2 oder mehr wartenden Anhängern wenn die "unsauber" am Rand stehen? Also müssen die Kerzengerade hintereinander stehen , wenn ich das richtig verstanden habe.

**Comment by BullsEye1005** [comment]
Kleines Update:
![20221112212603_1](https://user-images.githubusercontent.com/117856357/201493388-06934f37-bb96-4784-8adc-839ca61de479.jpg)
Erste Bild: Überladewagen findet kein Weg, wenn beide LKWS, in dem Fall, mit AD aktiviert da stehen.

![20221112212631_1](https://user-images.githubusercontent.com/117856357/201493429-305129ce-8f29-43b3-9357-cb7e87a31190.jpg)
Zweite Bild: beim hinteren LKW ist AD deaktivert, und der Überlader fährt den hinteren, aber auch leider sehr nahe mit leichter Kollision,an. Erster LKW steht weiterhin mit aktiviertem AD, und sogar mit 70 % Füllstand.
![20221112213346_1](https://user-images.githubusercontent.com/117856357/201493550-3d98cde1-5d39-4ab5-8513-eb9287c7e4a0.jpg)
Drittes Bild: Kein Weg gefunden, wenn der hintere LKW mit AD aktivert ist aber der vordere LKW nicht.
![20221112213541_1](https://user-images.githubusercontent.com/117856357/201493621-4c9c111f-90c0-45f7-840d-a9b5a0a9e965.jpg)
Vierte Bild: Beide LKW ist AD deaktiviert und überlader fährt nur den hinteren leeren LKW an.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9995876/log.txt)

**Comment by Tensuko** [comment]
"unsauber" heist ungünstig positioniert, aber so sollte es passen.

Was mich jetzt wundert ist das dritte Bild.

> Drittes Bild: Kein Weg gefunden, wenn der hintere LKW mit AD aktivert ist aber der vordere LKW nicht.

Er müsste ganz klar den vorderen LKW als Ziel haben, weil der AD LKW nicht am Zielort angekommen ist.
Was blockiert jetzt den Pathfinder?
Ich vermute jetzt einfach mal die AD Kollision, die ich gerne mal sichtbar hätte, bzw ich muss mal schauen ob ich das morgen oder so reproduziert kriege.

> Vierte Bild: Beide LKW ist AD deaktiviert und überlader fährt nur den hinteren leeren LKW an.

Ist halt der nächst beste LKW, das hat nichts zu bedeuten.

**Comment by Tensuko** [comment]
An der AD Kolli liegt es schon mal nicht, soweit konnte ich das testen.
Müssen uns da etwas überlegen...

**Comment by Cagcody1** [comment]
so finally had some time to play.  Switched over to Green Valley Map.  Was using one of the default large carts and did not seem to have an issue.  Was using 2 trucks and 2 harvesters.   Switched over to Kinze cart and it will fill then state no path after it finished loading up.  Log and screenshot attached.   Took the second truck out of the picture and still got the error.   Will play some more tonight after work to  
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10002448/log.txt)
![20221114055712_1](https://user-images.githubusercontent.com/76058932/201647714-3c72caf3-cc60-45c1-b231-61687a32c850.jpg)

**Comment by franky-bb** [comment]
Es passiert sowohl mit dem Überladewagen, als auch wenn am AD übergeben werden soll. Das Abtankgespann bleibt einfach stehen und kurze Zeit später sogar deaktiviert.

**Comment by Tensuko** [comment]
> Es passiert sowohl mit dem Überladewagen, als auch wenn am AD übergeben werden soll. Das Abtankgespann bleibt einfach stehen und kurze Zeit später sogar deaktiviert.

Das sind 3 komplett unterschiedliche Dinge die du erwähnst, aber leider nicht näher beschreibst.

**Comment by Tensuko** [comment]
Can you pls test this with 7.1.2.0 and give feedback?
It should work much better now as the driver should not drive to close to the trailer anymore.

**Comment by Cagcody1** [comment]
I am attempting to test however now I cant get the menu to load in order to continue the course when I hit the delete key.

**Comment by franky-bb** [comment]
Der Drescher Abfahrer Modus funktioniert jetzt viel besser, als alle anderen Versionen vorher. Der Überladewagen als auch mit einem normalen Anhänger, der mit AD zum Silo fährt, bunkert den Drescher einwandfrei ab. Ich konnte keine Fehler feststellen. Auch ein Deaktivieren der Abfahrers auf dem Feld, konnte ich nicht beobachten. Vielen Dank.

**Comment by Tensuko** [comment]
> I am attempting to test however now I cant get the menu to load in order to continue the course when I hit the delete key.

No problem with the keybind, maybe the game patch did something to your keybinds.
7.1.2.1 is working just fine.
I will close this Issue then.
