### ISSUE TITLE
[Question] Help with this error "Error: Running LUA method 'onSaveStartComplete'. dataS/scripts/field/FieldManager.lua(362) : attempt to index a nil value"

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#2091]
Hello CP devs.
I am in need of your help, because i have this very weird error.
When i try to savegame while CP workers are working, my game hangs while saving (infinite saving) so i have to close the game with ALT + F4.
It doesnt happen always, maybe 4 of 10 times.
Then when i try to start game again, my savegame is deleted.
The problem is, i dont know which mod is causing this error, this is the first time i have got this error.
Since it says FieldManager 362 code, does it have to do anything with CP or maybe with some other mod?
Here is the full log, so i hope you can help me identify what is causing this problem.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9994815/log.txt)

**Comment by Tensuko** [comment]
This is not a CP Error, that is basegame and I guess it got something to do with the map.
So not CP Error.
2022-11-12 11:14 Error: Running LUA method 'onSaveStartComplete'.
dataS/scripts/field/FieldManager.lua(362) : attempt to index a nil value
