### ISSUE TITLE
[BUG_SP] Überladewagen fährt beim Abladen zu nah am LKW/Traktor / Callstack in log

### ISSUE THREAD

**Issue by BullsEye1005** [Courseplay/Courseplay_FS22#2092]
**Steps to reproduce**
Überladewagen fährt zu nah an einem Anhänger zum Abladen, sodass der Schlepper mit dem Anhänger etwas kollidiert. 

**Expected behavior**
Wenn ich das Entladerohr manuell Ausfahre und dann CP aktivere, fährt der Überlader mit ausgeklappten Rohr mit mehr Abstand zum Anhänger. Wenn der Überlader fertig mit umladen ist, klappt er automatisch das Rohr ein und fährt zu den Dreschern zum Abtanken. Soweit zu gut. Jetzt fährt er, weil das Rohr ja eingeklappt ist, wieder zu nah an dem LKW zum umladen.

**Screenshots**
![20221112130426_1](https://user-images.githubusercontent.com/117856357/201473853-2925c956-4ae0-4b9b-a946-b7c0654115b9.jpg)
![20221112130433_1](https://user-images.githubusercontent.com/117856357/201473856-135dceff-ecbf-4d13-a364-7ea4ac06a69e.jpg)

**Courseplay version**
Version used: 7.1.1.6

**Map**
Nordfriesische Marsch OG 4Fach

**Vehicles/ implements involved**
Überladewagen und Schlepper sind Vanilla-Fahrzeuge
HAWE 4000, Tridem. Schlepper Fendt 1050

**Relevant script mods**
AD,CP

**Comment by Tensuko** [comment]
Ich frage mich immer WARUM der part mit der log entfernt wird und die nicht angehangen wird wenn man doch schon offensichtlich debug eingeschaltet hat....
Also bitte, logfile!

**Comment by BullsEye1005** [comment]
sorry ein fehler....
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9995343/log.txt)

**Comment by pvaiko** [comment]
Leider fehlt das Wichtigste in der Log, die Pipelänge und die Trailersuche, war vielleicht nicht eingeschaltet.

Ich bräuchte eine Log mit implement und unloader debugs, die beiden Fälle, also ÜLW fährt zum Trailer mit Rohr zu und nochmal mit Rohr aufgeklappt. Starten reicht es, musst nicht warten bis er da ankommt, beim starten loggt er alles was ich brauche.

**Comment by BullsEye1005** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9996180/log.txt) Log mit eingeklapptem Rohr


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9996205/log.txt) Log mit ausgeklapptem Rohr

**Comment by pvaiko** [comment]
Danke. Das ist ein verstellbares Rohr und CP ermittelt den Rohrversatz beim Starten in der Ausgangsposition wenn das Rohr zu ist, das ist die 2.8 m. Bei aufgeklappten Rohr, rechnet er mit dem aktuellen Versatz, in deinem Fall 3.5 m. @Tensuko, weiss nicht ob wir da was machen können/wollen. 

Der Callstack ist mit dem push oben gefixt, hat nix mit dieser Issue zu tun.

**Comment by BullsEye1005** [comment]
Ich verstehe. Aber....Hat nicht jeder Überladewagen ein klappbares und verstellbares Rohr? Korrigiere mich, wenn ich mich täusche. Kann man den Versatz nicht grundlegend erhöhen? Ich glaube selbst bei 4 meter, wird er, wenn das Rohr in Grundposition ist noch normal abladen, und der Anfahrtsweg wäre mit ausreichendem Abstand zum Anhänger ohne Kollision. Ist nur ein Gedanke, aber ihr seid, was das angeht hier die Profis =)

**Comment by Tensuko** [comment]
Geht aber nicht einfach generell so.
Wir überlegen uns was.
Außerdem, wenn zu weit weg und trailer zu hoch, passt es auch nicht mehr.
Je weiter weg, desto weiter rüber das Rohr + dadurch wird es Flacher.

**Comment by Tensuko** [comment]
Was genau heist zu dicht an den LKW?
Berührt er ihn, bleibt er hängen, oder ist es nur das Rohr ausklappen?
Ich frage, weil wir für das Rohr ausfahren noch etwas angepasst haben. Ich hab das ein paar mal durchlaufen lassen und es sah sehr gut aus.
![fsScreen_2022_11_13_16_53_24](https://user-images.githubusercontent.com/27344744/201606270-ba04da01-cbe1-4fe0-ba37-6d72d8228f51.png)


Einen Mindestabstand für alle ein zu führen, bin ich mir nicht sicher.
Wenn der zwischen 2,8 und 3,5m bei dem liegt, was würde 3,2m z.B. bringen?
Etwas mehr sicherheitspuffer?
Was ist mit anderen ÜLWs?
Die meisten sind sowieso weiter weg.

**Comment by BullsEye1005** [comment]
ja bei dir sieht das ja sehr schön aus....ob das jetzt auch daran liegt ob der Fendt1050, so wie in meinem Fall etwas breiter ist, kann ich auch nicht sagen. Aber mit berühren meinte ich, dass der Schlepper beim ranfahren quasi mit den linken Vorderreifen leicht die Ecke vom Anhänger berührt, sodass der Anhänger dadurch etwas weggedrückt wird aber manchmal wird auch der ganze LKW nach vorne gedrückt, er wird vom Schlepper nach vorne geschoben, bis der ÜLW vorbeipasst. Ich hab es jetzt nicht mit anderen Schlepper und ÜLW getestet.

|Einen Mindestabstand für alle ein zu führen, bin ich mir nicht sicher.
Wenn der zwischen 2,8 und 3,5m bei dem liegt, was würde 3,2m z.B. bringen?
Etwas mehr sicherheitspuffer?|

Guck mal, wenn du dir dein Screenshot anschaust, kann man ja sehr gut sehen, dass das Rohr beim Entladen bestimmt noch locker 1 meter Richtung Fahrrichtung rechts könnte, und er würde immernoch den Anhänger beim Abladen treffen ohne die Höhe vom Rohr ändern zu müssen. Somit wäre aufjedenfall eine Kollision beim Dranfahren auszuschließen. So ist meine These...

**Comment by Tensuko** [comment]
Guck mal was über deinem Beitrag steht....
![guckmal](https://user-images.githubusercontent.com/27344744/201869681-90ce5fb3-93e9-4c58-8c0a-90fbe31c45bf.png)

**Comment by rohne83** [comment]
> Ich verstehe. Aber....Hat nicht jeder Überladewagen ein klappbares und verstellbares Rohr? Korrigiere mich, wenn ich mich täusche. Kann man den Versatz nicht grundlegend erhöhen? Ich glaube selbst bei 4 meter, wird er, wenn das Rohr in Grundposition ist noch normal abladen, und der Anfahrtsweg wäre mit ausreichendem Abstand zum Anhänger ohne Kollision. Ist nur ein Gedanke, aber ihr seid, was das angeht hier die Profis =)

Nein. Der Elmers Haul Master zum Beispiel lässt sich nicht verstellen. Ebenso zB der von Horsch, Kinze, etc. Die können alle maximal die Auslauftülle bewegen. Grundsätzlich sind aber alle ULW-Rohre so konzipiert dass beim Abladen zumindest ein knapper Meter zum Abfahrer bleiben kann. Also etwas weiter weg könnte CP sich durchaus stellen ohne dass es zu Problemen führt.

**Comment by BullsEye1005** [comment]
@Tensuko hatte ich gesehen,ja. Wollte ja nur deine Fragen beantworten...
