### ISSUE TITLE
[BUG_MP] Error: Running LUA method 'packetReceived'.

### ISSUE THREAD

**Issue by Axel32019** [Courseplay/Courseplay_FS22#2094]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Currently observed if CP send AD to refuel.
Overwritten math.sin to catch the error.

**Actual behavior**
LUA callstack error "Error: Running LUA method 'packetReceived'."
see also: https://github.com/Stephan-S/FS22_AutoDrive/issues/728

**Expected behavior**
no error

**Screenshots**
makes no sense - see analysis

**Courseplay version**
Version used: 7.1.1.6, may also appear in earlier versions

**Client Log**
see log excerpt

**Server Log**
see log excerpt

**Player on the server**
not relevant

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
not relevant

**Vehicles/ implements involved**
not relevant

**Relevant script mods**
Autodrive 

**log excerpt:**
... sin x = nil ...
2022-11-12 11:49 LUA call stack:
  =D:/home/sid_3169831/farmingSim_2022/profile/mods/FS22_AutoDrive/scripts/AutoDrive.lua (671) : printCallstack
  dataS/scripts/utils/MathUtil.lua (436) : sin
  =D:/home/sid_3169831/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJob.lua (177) : getDirectionFromYRotation
  =D:/home/sid_3169831/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJobFieldWork.lua (119) : setValues
  dataS/scripts/ai/jobs/AIJob.lua (92) : setValues
  =D:/home/sid_3169831/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJob.lua (251) : readStream
  =D:/home/sid_3169831/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/events/CpJobStartAtLastWpSyncEvent.lua (24) : readStream
  dataS/scripts/network/Server.lua (494) : readStream
  dataS/scripts/network/ConnectionManager.lua (28) : func
2022-11-12 11:49 Error: Running LUA method 'packetReceived'.
dataS/scripts/utils/MathUtil.lua(436) : bad argument #1 to 'cos' (number expected, got nil)

**Analysis**
function AIParameterPositionAngle.new(snappingAngle, customMt)
...
self.angle = nil

initialize angle with nil

function AIParameterPositionAngle:setAngle(angleRad)
...
self.angle = angleRad

seems not called before:

function AIParameterPositionAngle:getAngle()
    return self.angle
end

result in return nil for angle -> Error: Running LUA method 'packetReceived'.

**Comment by schwiti6190** [comment]
@Axel32019 Could you test this again with the latest main branch?

**Comment by Iwan1803** [comment]
I sent a tractor to refuel via AD on my server earlier and the error no longer occurred.
