### ISSUE TITLE
Mehrere Fahrzeuge auf Dedicated-Servern

### ISSUE THREAD

**Issue by PitBullSchweiz** [Courseplay/Courseplay_FS22#2098]
CP 7.1.1.4
Die Kurze mit 2 oder mehr Fahrzeugen funktionieren problemlos im Singleplayer, jedoch nicht auf dem Dedi-Server.

Habe beide Fahrzeuge geschickt (1xLinks und 1xRechts) beide Fahrzeuge fahren genau auf der Kurslinie.

**Comment by Tensuko** [comment]
Versuch es noch mal richtig....(template) und nur so nebenbei, bei mir gehts.

**Comment by PitBullSchweiz** [comment]
Hallo Tensuko

Ich spreche immer noch vom Dedicated-Server (welcher bei Nitrado läuft)
Ich kann das Problem/Verhalten reproduzieren.
Manueller CP-Start funktioniert mit links/rechts
Automatischer CP-Start (via Autodrive) funktioniert NICHT mit links/rechts

PS: Habe CP geupdated und nun auf 7.1.1.6
