### ISSUE TITLE
[BUG_SP] Unloader mode unavailable if more than one fillUnits or attached trailers

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2099]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use any combination of the combinations described below.

**Actual behavior**
Unloader mode only available with one bin or one attached implement. It's not available anymore as soon as you mount another trailer.
This makes this mode unavailable for most swap trailer combinations and many trucks (i.e. the W50 in 3rd+4th screenshot with its own bin + trailer, or the auger wagon in the first+second screenshot which itself is a swap trailer).

**Expected behavior**
Unloader mode should also be available for those combinations.

**Screenshots**
before attach:
![fsScreen_2022_11_13_22_02_44](https://user-images.githubusercontent.com/71030138/201544517-5b03988e-b6a1-4b2b-871c-7e5e9d837435.png)
after attach:
![fsScreen_2022_11_13_22_02_51](https://user-images.githubusercontent.com/71030138/201544533-e5b6d0eb-126e-403e-890c-a121ca4fc759.png)

other combination where unloader mode is unavailable are trucks with swap trailers:
![fsScreen_2022_11_13_14_20_04](https://user-images.githubusercontent.com/71030138/201544566-6b73b977-1e91-4b65-858e-76be7ec4f3aa.png)

or complete swap trailers like this Annaburger HTS 22.79 (was available in FS19 modhub and should be available also for FS22 soon, in this case with auger wagon mounted, but same also with normal tippers):
![fsScreen_2022_11_13_14_16_04](https://user-images.githubusercontent.com/71030138/201544641-21c8cf14-8825-4f6a-81b5-e89a34b47d5c.png)
![fsScreen_2022_11_13_14_15_47](https://user-images.githubusercontent.com/71030138/201544626-283ed12e-790f-4f21-b16e-359df18b402a.png)

**Courseplay version**
Version used: 7.1.1.6

**Log**
this is for the screenshots with the Modhub Mack Grain Hauler Pack
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9998227/log.txt)

**Map**
any

**Vehicles/ implements involved**
Which vehicle or implement? Any towed swap trailer (i.e. Annaburger HTS 22.79 pack which was available in FS19 and is also planned for modhub release soon) or any truck with own bin (various available on modhub, plus a normal towed trailer)
Mod yes

**Relevant script mods**
none

**Comment by Tensuko** [comment]
Not a bug and intended for now, if and when we will change it, I cant say now, but we decided this for some reasons.

**Comment by Tensuko** [comment]
The swap trailer will have to wait when in modhub, wonder whats with HKL.

**Comment by rohne83** [comment]
nothing wrong with the mod. When coupling it directly to a truck (simply changing attacherJoint node position) unloader mode is available:

![fsScreen_2022_11_14_00_10_27](https://user-images.githubusercontent.com/71030138/201549733-c9c00c40-dbc4-4bdf-a252-042a73ee86c5.png)

Think it's not working with the base trailer rather because it's a second attachment.

**Comment by Tensuko** [comment]
You did not understand what I am saying.
When you only attach the BASE (the 1st Screenshot) and it activates the mode, the Base is wrong and got an Issue.
See here:
Base attached from HKL and nothing is active like it have to be.
![fsScreen_2022_11_14_07_26_22](https://user-images.githubusercontent.com/27344744/201590245-767fea19-ae1c-43e0-837f-2884a075e0d6.png)
Only when I attach the 2nd Implement, like you called it is the problem, it will activate the mode.
![fsScreen_2022_11_14_07_26_42](https://user-images.githubusercontent.com/27344744/201590281-19547b13-b68e-4842-92a9-097a1f859f22.png)

So it is working correctly and intended like we want it.
Seems like the Base have some kind of capacity or something else, don't know but it is definitly the Mod.

**Comment by rohne83** [comment]
Ah thanks. That helped much to figure it out.
So it is the vehicleType: if the baseTrailer is of vehicle Type trailer or any custom vehicleType which has trailer as parent, it is not working with CP as seen in my screenshot above (maybe because trailers can have fillUnits?). Workaround currently is to change its vehicleType to hookliftTrailer - not really appropriate here but at least it works with CP then.

**Comment by Tensuko** [comment]
@schwiti6190 maybe you can explain it more in detail, how we sort out if the attached implement is valid for combine unload.
