### ISSUE TITLE
Baler not working in field work.

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/Courseplay_FS22#21]
Hello,
1st "issue" pops up, when I want to do fieldwork with a baler (same course as windrower) I doesnt let me create a job
Is baling not part of fieldwork yet?

**Comment by Tensuko** [comment]
Seems like not :)
Will set it on our todo list! Thanks for the feedback!

**Comment by JDTiger** [comment]
> Hello, 1st "issue" pops up, when I want to do fieldwork with a baler (same course as windrower) I doesnt let me create a job Is baling not part of fieldwork yet?

Does it work, if you load the windrowers course, from saved courses?

**Comment by Bobster82** [comment]
No, I can't select fieldwork, even if I have a course loaded

**Comment by schwiti6190** [comment]
Hi there,
the currently only vehicle + implemnts that work with the giants helper are possible.
This will change of course with one of the next versions :)
