### ISSUE TITLE
[BUG_SP] Vorgewendeüberlappung

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/Courseplay_FS22#210]
Ich weiss nicht ob ich blind bin oder diese Funktion (absichtlich oder nicht) nicht vorhanden ist. Im LS19 konnte man beim Vorgewende bis zu 20% überlappung einstellen. Wird es dies im LS22 auch geben? Oder es existiert schon, wo kann ich es einstellen

**Courseplay version**
Version used: 7.0.0.8

**Comment by Tensuko** [comment]
Das kommt noch wieder rein.

**Comment by DonBolli** [comment]
Diese Information reicht mir vollkommen
