### ISSUE TITLE
Bale Wrapping causes other CP Courses to Fail

### ISSUE THREAD

**Issue by Tarkenaut** [Courseplay/Courseplay_FS22#2100]
**Steps to reproduce**
Engage CP: Bale/Collect wrap while one or more other Courseplay courses are in progress. 

**Actual behavior**
When engaging Bale/Collect Wrap, Other courses seem to stop routing and cause other CP courses in progress to run vehicles off the course. 

**Expected behavior**
Should cause no conflict.

**Screenshots**
Unavailable. Will try to capture. 

**Courseplay version**
Version used: 7.1.1.6

**Log**
Attached. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10007887/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Baler - John Deere 4755 w/ New Holland BigBaler 1290 High Density
Bale Collector - Claas Axion 920 with Arcusin FSX 63.72

Mod yes/no ? No

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
When I already read this, I want to fclose this Issue....
Available mod: (Hash: 33cbf9d5f5aa2dfb6d806463866e5f08) (Version: 7.1.1.6) FS22_Courseplay_7_1_1_6

From where did you download CP ???

**Comment by pvaiko** [comment]
@Tensuko see commit message above how this can be reproduced. Should now be fixed.

**Comment by Tensuko** [comment]
okay, will have a quick look.

**Comment by Tarkenaut** [comment]
@Tensuko - Hey, only had it for a week and just providing some feedback. I'll get better, I promise! <3

**Comment by Tarkenaut** [comment]
> When I already read this, I want to close this Issue.... Available mod: (Hash: 33cbf9d5f5aa2dfb6d806463866e5f08) (Version: 7.1.1.6) FS22_Courseplay_7_1_1_6
> 
> From where did you download CP ???

Lord only knows. Some BS site the first time before I found the git with official releases. I just kept the naming convention for sanity's sake while I figured it out.

**Comment by Tensuko** [comment]
Ok, anyway, should work just fine with the next Release.
