### ISSUE TITLE
[BUG_SP] Unloader path too close to vehicle

### ISSUE THREAD

**Issue by kobra60** [Courseplay/Courseplay_FS22#2103]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Set up truck on edge of field. Have an auger wagon unloading combines.  Once full, it heads to the truck.

**Actual behavior**
Tractor plots the course to the unload vehicle and drives there.  The course is too close to the truck and the tractor runs into the back or if it does manage to get next to it, it's too close to properly unload.  This doesn't happen for the most part with another auger wagon to unload in to.  Sometimes a bit close for it but it always gets by the side.  I've tested with many different combinations of augers and trailers, both base game and mods.  The semi trailers are always too close to work or get hit.

**Expected behavior**
For the auger wagon to line up properly with the trailer to unload into it.

**Screenshots**

**Courseplay version**
Version used: v7.1.1.6

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. Michigan 16x and base game Haut-Beyleron.

**Vehicles/ implements involved**
Which vehicle or implement?  Modded Fendt tractors and tried a Case base game one. Same effect.
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.  Autodrive is active. Dev controls, maize plus, dusty lands.

![Screenshot (61)](https://user-images.githubusercontent.com/36580296/201920292-30256a5e-f552-46e4-812c-1bc94bcdeb61.png)
![Screenshot (62)](https://user-images.githubusercontent.com/36580296/201920329-aad2a43b-659c-48a5-b523-f2584b60033a.png)
![Screenshot (63)](https://user-images.githubusercontent.com/36580296/201920345-620892e1-86ba-4cf5-8aa1-ae5fe882f5f0.png)
![Screenshot (41)](https://user-images.githubusercontent.com/36580296/201920360-ddf7b31b-5958-44be-b49a-ad885991da37.png)
![Screenshot (43)](https://user-images.githubusercontent.com/36580296/201920369-eac091a6-7c78-46d9-847c-f98f01e533fa.png)
![Screenshot (49)](https://user-images.githubusercontent.com/36580296/201920376-0de4c287-48d8-4c83-8748-27013d4802f9.png)
![Screenshot (52)](https://user-images.githubusercontent.com/36580296/201920386-3aab9f8f-7751-443c-8f19-c43925cb43d6.png)
![Screenshot (57)](https://user-images.githubusercontent.com/36580296/201920391-86f5899f-63c5-445a-bdd8-98f0f41edfca.png)
![Screenshot (58)](https://user-images.githubusercontent.com/36580296/201920399-7aa0df04-2e4c-4218-96ec-e9be8e972240.png)
![Screenshot (60)](https://user-images.githubusercontent.com/36580296/201920411-540db0d3-be06-40b8-9849-6ccf1dcc0918.png)

**Comment by kobra60** [comment]
The log was too big to add so I had to zip it.

[log.zip](https://github.com/Courseplay/Courseplay_FS22/files/10012679/log.zip)

**Comment by Tensuko** [comment]
Rule Number one in our Wiki.
Check if you have the latest version:
https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by Tensuko** [comment]
Your screenshots also show so many things that have either been fixed or is part of the next release....

**Comment by kobra60** [comment]
Yep, my bad. Sorry. I now have the 7.1.1.6.  No change with it so will look forward to the next release. Thanks for all you do. Keep up the good work.
