### ISSUE TITLE
not able to create feilds with plows[BUG_SP]

### ISSUE THREAD

**Issue by garthmitchell** [Courseplay/Courseplay_FS22#2109]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
enable cosplays 

**Actual behavior**
not able to create own field with a plow with the mod enabled 

**Expected behavior**
should be able to press y to create feild 

**Screenshots**

**Courseplay version**
Version used: 7.1.03

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
elemcreek 

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
The read first, is not there for fun.
https://github.com/Courseplay/Courseplay_FS22/wiki
I see you use modhub Version, on github we are far ahead.

However, it might be that just the keybind disappeared in F1 when you have many mods with keybinds.
Try it out by just press I think it was Z and try it on your own, then just start CP.
