### ISSUE TITLE
[Enhancement] better alignment with pathfinder allowed to drive in reverse

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2112]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Kurs an einer schrägen Kante, von Kurzer auf Lange Bahn

**Actual behavior**
A clear and concise description of what happen.
es bleiben bei der Wende unbearbeitete stellen zurück

**Expected behavior**
sauber ansetzen, nicht so schräg.

**Screenshots**
If applicable, add screenshots to help explain your problem
Pathfinder darf rückwärts fahren - aktiviert
![fsScreen_2022_11_16_19_23_24](https://user-images.githubusercontent.com/24860501/202264846-dc6f64d0-661e-4537-8610-546ff6367202.png)
![fsScreen_2022_11_16_19_28_01](https://user-images.githubusercontent.com/24860501/202264866-1fd12789-1cec-4440-9cde-3af7b67d11e3.png)
![fsScreen_2022_11_16_19_28_08](https://user-images.githubusercontent.com/24860501/202264887-c2198505-1dcf-4e08-8e2a-114737b981dc.png)
![fsScreen_2022_11_16_19_28_12](https://user-images.githubusercontent.com/24860501/202264917-43cfb8e5-3893-44dc-a558-5a0bc39ff00f.png)
![fsScreen_2022_11_16_19_28_17](https://user-images.githubusercontent.com/24860501/202264948-84df4a09-e962-4509-859b-b1d4833fc2b3.png)
![fsScreen_2022_11_16_19_28_25](https://user-images.githubusercontent.com/24860501/202264977-3d97122c-ccaf-48ca-bad4-aa65780089ac.png)
![fsScreen_2022_11_16_19_28_32](https://user-images.githubusercontent.com/24860501/202265005-aa44a592-78ba-4e8c-a45a-8ad4f8071899.png)
![fsScreen_2022_11_16_19_28_39](https://user-images.githubusercontent.com/24860501/202265040-1fe1f018-bf39-4084-9866-18915ffe685a.png)
![fsScreen_2022_11_16_19_28_44](https://user-images.githubusercontent.com/24860501/202265100-5b18dbd5-2058-422b-9bcb-ad898b2a7730.png)
hier bleibt immer ein unbearbeiteter Fleck übrig weil der cp Fahrer nicht sauber gerade ansetzt
 
stelle ich das aus: (deaktiviert):
![fsScreen_2022_11_16_19_24_41](https://user-images.githubusercontent.com/24860501/202265264-f4ddb505-0b28-498e-a36d-5d3dc2f94dde.png)
![fsScreen_2022_11_16_19_29_12](https://user-images.githubusercontent.com/24860501/202265599-f00941d5-ed6f-4ec7-b3b3-c401a79cfe72.png)
![fsScreen_2022_11_16_19_29_17](https://user-images.githubusercontent.com/24860501/202265630-43d8b858-e43e-4ed3-9591-a82961d00303.png)
![fsScreen_2022_11_16_19_29_19](https://user-images.githubusercontent.com/24860501/202265641-c6add74e-b9be-4e49-b945-6ea826bd2075.png)
![fsScreen_2022_11_16_19_29_24](https://user-images.githubusercontent.com/24860501/202265661-a441d235-6b1b-468a-882f-91ab8ab927f3.png)
![fsScreen_2022_11_16_19_29_32](https://user-images.githubusercontent.com/24860501/202265697-d32f0879-06dc-47c8-a5af-f2a4c352f004.png)
![fsScreen_2022_11_16_19_29_41](https://user-images.githubusercontent.com/24860501/202265706-44ecd531-67ab-4473-978e-7107922c7807.png)
so bleibt kein unbearbeiteter Fleck

**Courseplay version**
Version used: 
v 7.1.2.0, aktuelles main

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Hobos Hollow 4x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Fastrac8330 +Rabe Sturmvogel 900 (mod) grubber

**Relevant script mods**
Mods like Autodrive or VCA and so on.

lg
andreas

**Comment by Tensuko** [comment]
Mal eine doofe Frage... warum nicht 2 Vorgewende?

**Comment by andreasthu** [comment]
Einmal weils nicht notwendig ist,  relativ viel platz rundherum,
Zweitens weils relativ egal ist. Auch bei zwei Vorgewenden setzt der Traktor die Bahn schräg an. Da er genauso um retourgang anfährt.
Lg
Andreas

**Comment by Tensuko** [comment]
Ich frage desshalb, weil diese konstellation so nicht nötig wäre mit pathfinder darf rückwärts fahren.
Ich meine das klappt nur gut bei Dreschern, sicher bin ich mir nicht mehr aber:
"Weil es nicht nötig ist" ist für mich kein Argument.
Wenn es möglich ist und man somit bessere Ergebnisse erzielt (komplett ohne Pathfinder wenden), sollte man das tun...

**Comment by andreasthu** [comment]
Hallo Tensuko
ich denke Pfadfinder darf rückwärts fahren ist standartmäßig aktiviert.
wußte nicht das das nur für Drescher sein sollte.

"Weil es nicht nötig ist" ist für mich kein Argument.
da hast du sicherlich recht, aber ich mach normal nur soviele Vorgewende wie nötig. auf manchen Feldern reicht simples auf/ab,
Bei Düngerstreuern komm ich mit einem Vorgewende aus, bei Güllefässern mit Auslegern brauch ich  normal zwei, Dreschen 2-3, bei Pflügen 4-6,...
kommt bei mir immer auf den Zweck an.

hab da aber nochmal etwas rum- bzw. durchgespielt, wenn der abstand zw TurnStart und TurnEnd enger ist, berechnet cp eine normale Wende in Vorwärtsfahrt:

![fsScreen_2022_11_17_09_38_12](https://user-images.githubusercontent.com/24860501/202400869-efb66444-4c2e-4ea2-b2df-f8b1245a15ca.png)
![fsScreen_2022_11_17_09_38_18](https://user-images.githubusercontent.com/24860501/202400888-53231898-f33c-4da6-be35-4f1b115fa7a1.png)
![fsScreen_2022_11_17_09_38_21](https://user-images.githubusercontent.com/24860501/202400901-0dc4dc51-78f9-4297-a99f-84dc5d819925.png)
![fsScreen_2022_11_17_09_38_28](https://user-images.githubusercontent.com/24860501/202400920-382d520b-de86-4d3f-a4de-c717df667231.png)
![fsScreen_2022_11_17_09_38_33](https://user-images.githubusercontent.com/24860501/202400938-abffc500-4678-4239-b718-d701884732c0.png)
oder greift da der Pfadfinder nicht, und cp macht eine vorprogrammierte Wende?

aber ähnlich unschön sieht es aus, wenn von einer langen Bahn zu einer kürzeren gewechselt wird:
![fsScreen_2022_11_17_09_42_08](https://user-images.githubusercontent.com/24860501/202401792-f930f059-8996-4e15-a646-e84972deb36f.png)
![fsScreen_2022_11_17_09_41_35](https://user-images.githubusercontent.com/24860501/202401595-926b6fe6-3915-4b45-a032-f94eb0a0fea3.png)
![fsScreen_2022_11_17_09_41_39](https://user-images.githubusercontent.com/24860501/202401610-e26d2381-f721-467a-bdc7-4f18de18396f.png)
![fsScreen_2022_11_17_09_41_50](https://user-images.githubusercontent.com/24860501/202401654-2fa27e37-d29a-49f0-bc1c-f3c1868f6b65.png)
![fsScreen_2022_11_17_09_41_54](https://user-images.githubusercontent.com/24860501/202401664-5527916c-33b8-4eb9-874c-210a83288439.png)
![fsScreen_2022_11_17_09_41_57](https://user-images.githubusercontent.com/24860501/202401670-714e234b-a8b8-4f4d-a7dc-bcc8799ab5d5.png)
![fsScreen_2022_11_17_09_41_58](https://user-images.githubusercontent.com/24860501/202401677-8676c179-8ddf-43ef-aed5-bb8b0f80fcbf.png)
![fsScreen_2022_11_17_09_42_04](https://user-images.githubusercontent.com/24860501/202401770-1bb6574a-bcc2-41c0-8804-3b3c5c43c3a8.png)
![fsScreen_2022_11_17_09_42_06](https://user-images.githubusercontent.com/24860501/202401781-03c2e14d-319f-468f-94c6-22a1e9669949.png)
![fsScreen_2022_11_17_09_42_00](https://user-images.githubusercontent.com/24860501/202401751-5023df82-244e-4f2b-95f0-9eda139457fe.png)
![fsScreen_2022_11_17_09_42_02](https://user-images.githubusercontent.com/24860501/202401758-189a873e-2096-4972-a0a3-ff015d8e59d3.png)
![fsScreen_2022_11_17_09_42_10](https://user-images.githubusercontent.com/24860501/202401807-08a0c9c7-fc85-46fe-b0b5-0425c48651b2.png)
da senkt cp den Grubber schon ab, wenn er noch quer zur Bahn steht und kommt in folge eigentlich schon auf die Gegenbahn. 
aber ok, werde Pfadfinder rückwärts für Geräte deaktivieren.
lg
andreas

**Comment by Tensuko** [comment]
Sollte jetzt besser sein
