### ISSUE TITLE
[BUG_SP] Uncoupling shield generates LUA errors

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#2114]
**Steps to reproduce**
Coupling and uncoupling the shield at the front

**Actual behavior**
The game crashes with LUA-errors

**Expected behavior**
No crash

**Courseplay version**
Version used: V7.1.2.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10024936/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Fendt 1050 Vanilla
Holaras MES 500 Vanilla

**Comment by MeRida2104** [comment]
Happens also with all other shields

**Comment by BullsEye1005** [comment]
kann ich bis jetzt nicht bestätigen. Bei mir keine Fehler

**Comment by MeRida2104** [comment]
Mit der aktuellen dev Version von Courseplay wurde es gefixt. Keine lua Fehler mehr beim abkuppeln der Schilder 👍
