### ISSUE TITLE
[BUG_SP] Bunkerfahrer erkennt keine AD-Fahrzeuge

### ISSUE THREAD

**Issue by BullsEye1005** [Courseplay/Courseplay_FS22#2116]
**Steps to reproduce**
Mietenschlepper erkennt keine AD-Schlepper

**Actual behavior**
Der Mietenschlepper erkennt keine AD-Schlepper, es sei man ist in dem ankommenden Schlepper selber drin, und AD ist weiterhin aktiviert. Sofern man in einem anderen Schlepper steigt, Fährt der Mietenschlepper aus seiner Parkposition Richtung Silo. Kommt der AD-Schlepper, ohne das man selber drin sitzt an, fährt der Mietenschlepper nicht in die Parkposition, sondern walzt weiter

**Expected behavior**
Mietenschlepper sollte AD-Fahrer rechtzeitig erkennen und auf Seite fahren.

![Screenshot (4)](https://user-images.githubusercontent.com/117856357/202524824-e1285ba3-dca0-49fb-9663-ff3b2b529510.png)
Mietenschlepper wartet, wenn man selbst im Karrenschlepper sitzt.

![Screenshot (5)](https://user-images.githubusercontent.com/117856357/202524976-0b4c89b2-2209-4ecf-afd0-bc8a32684784.png)
 Habe gewechselt zum Mietenschlepper, und er fängt an weiter zu fahren, obwohl noch AD-Fahrzeuge (unbesetzt) im Silo abladen

**Courseplay version**
Version used: 7.1.2.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10034422/log.txt)

**Map**
Nordfriesische Marsch 4x Fach

**Vehicles/ implements involved**
Vanilla Fahrzeuge, Vanilla Schiebeschild

**Relevant script mods**
AD, VCA,CP

**Comment by Tensuko** [comment]
Versuch bitte mal die 7.1.2.1

**Comment by BullsEye1005** [comment]
Top, macht er jetzt!
Spielt die Richtung vom Zielpunkt, Die  Parkposition eigentlich eine Rolle?

Ich hätte noch ein kleinen Verbesserungsvorschlag, und zwar, dass der das Schild nicht komplett auf den Boden lässt beim Schieben, sondern so 20 - 40 cm über den Boden. Somit lässt der ne kleine Schicht liegen und fährt drüber. So hat man auch gleich den Verdichtungseffekt im Silo. So wie es jetzt ist, schiebt der nur auf aber verdichtet dann kaum was.

**Comment by Tensuko** [comment]
> Spielt die Richtung vom Zielpunkt, Die Parkposition eigentlich eine Rolle?

ja, er steht dann eben so wie du es hingedreht hast, also Pfeilrichtung ist Traktor vorne.



> Ich hätte noch ein kleinen Verbesserungsvorschlag, und zwar, dass der das Schild nicht komplett auf den Boden lässt beim Schieben, sondern so 20 - 40 cm über den Boden. Somit lässt der ne kleine Schicht liegen und fährt drüber. So hat man auch gleich den Verdichtungseffekt im Silo. So wie es jetzt ist, schiebt der nur auf aber verdichtet dann kaum was.

Schild soll auch nur das Zeug nach hinten schieben im Keilsilo.
Das mit der höhe ist so eine Sache.....
Zu tief er bleibt hängen.
Zu hoch und es bleibt eine Schicht liegen.
Müssen wir die nächsten Wochen mal beobachten.
