### ISSUE TITLE
[BUG_SP] AD & CP => Lane in Convoy Course is ignored

### ISSUE THREAD

**Issue by ralphv13** [Courseplay/Courseplay_FS22#2117]
**Steps to reproduce**
1. create vehicle convoy course (with at least 2 vehicles/lanes)
1. configure CP the left lane, AD to drive to field and handover to CP
1. start and see ;)

**Actual behavior**
1. ad starts CP if destination is reached. 
1. CP _always_ use a path straight under the course 

BUT
if i use the CP HUD to start the course, all will be fine !

**Expected behavior**
1. CP should use the configured lane
   7.1.1.6 works flawlessly, since 7.1.2.0 this is bugged

**Screenshots**
![cp_convoy_bug](https://user-images.githubusercontent.com/5366710/202549433-67d230df-b050-4156-83f9-04ab7ec06acf.png)

**Courseplay version**
Version used: 7.1.2.1  

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10035237/log.txt)

**Map**
FS22_NF_Marsch_4fach_oG

**Vehicles/ implements involved**
AXION 870 & Rapid A 800S

**Relevant script mods**
* Autodrive
* Courseplay
(many more  installed but deactivated for this test run)

If you need more infos, data or tests, please tell me. 
Have fun & thanks a lot
Ralph

**Comment by Tensuko** [comment]
AD -> CP lane offset ignored
Player -> CP it works?

**Comment by ralphv13** [comment]
hi,

i did a test with the latest dev (patch included) and i'm sorry to say that it is still buggy and the
behavior is the same like with latest release.

After spending some time with the source-code (first time lua for me, so i might miss a lot) i found out
that when AD is started by the player the method  'CpAIFieldWorker:onCpADStartedByPlayer()' is 
called and `spec.cpJobStartAtLastWp:getCpJobParameters().laneOffset` (line 239) is always set to MIDDLE 
instead of RIGHT/LEFT in my case.

maybe it helps or i was wrong. as i said, never looked into lua code before ;)

cu & thanks a lot
Ralph

**Comment by 1969Tonton** [comment]
I can confirm the wrong behaviour

**Comment by ralphv13** [comment]
reason is, that only '0'/'LANE_CENTER' is a valid entry. The ParameterSettingList isn't in the right state/synced with the given course.

calling 
```lua
spec.cpJobStartAtLastWp:getCpJobParameters().laneOffset:refresh()
```
before
```lua
spec.cpJobStartAtLastWp:getCpJobParameters().laneOffset:setValue(self:getCpLaneOffsetSetting():getValue())
```
solves the issue. but `CpAIFieldWorker:onCpADStartedByPlayer()` is imho the wrong place for this.

**Comment by schwiti6190** [comment]
@ralphv13  Thanks for your help. I will implement this then :)
``cpJobStartAtLastWp`` is only for AD, so updating it there is okay.

**Comment by timmi4026** [comment]
Moin, Bei mir genau das selbe, starte ich manuell, reihen sich beide drillen ein und fahren richtig. Aber... fahren die Drillen dann z.b. Dünger auffüllen und kommen wieder, setzen beide wieder an der Stelle an wo sie waren, aber genau auf der Mittellinie, nicht links und rechts so wie sie es sollen

**Comment by 1969Tonton** [comment]
Hi please check 2132 there you see that it's not working as expected in SP
