### ISSUE TITLE
[Feature] Unloader to fill Distinction Super-B Trailers in one Go

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#2119]
**What is the problem this feature/enhancement solves?**
I normally like to play more with American Style Equipment (even I am from Switzerland) and therefore mainly use the LodeKind Distincion Super-B Trailers. As the Super-B's consist of two trailers with two compartments each, CP always only fills the compartments of one trailer, drives off and only then aligns for the second trailer. 

**Describe the solution you'd like**
It would be nice if the whole truck would be filled in one go as this would be more realistic and of course also be a bit faster

**Describe alternatives you've considered**
Just leave it the way it is, as mentioned it is mainly cosmetical and of course also take more time; but it would be a nice enhancement

**Additional context**
I normally use the Disticion Super-B Trailer from the Vanilla Game and Brent Avalanche Grain Carts (the smaller one from Modhub and the very big one (2596) I unfortunately only found on sketchy mod sites. But I expect it to behave the same with other grain carts.

**Comment by Tensuko** [comment]
Sry but we dont want to touch this mode if it isn't necessary.
