### ISSUE TITLE
[BUG_SP] Walzfahrzeug fährt ausserhalb des Silos

### ISSUE THREAD

**Issue by BullsEye1005** [Courseplay/Courseplay_FS22#2123]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Mietenfahrzeug fährt immer weiter Rückwärts aus dem Silobereich

**Actual behavior**
Walzschlepper schiebt ins Silo, beim Rückwärtsfahren wendet er nicht in den nächsten Schiebebereich, sondern fährt immer weiter Rückwärts, bis er irgendwo gegen fährt. Komischerweise macht der das nicht immer, sondern ab und zu in unregelmäßigen Abständen

**Expected behavior**
Walzschlepper sollte vorm Silo stehen bleiben und mit Versatz in den nächsten Schiebebereich fahren.

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/117856357/202800040-645788b6-2818-4d2f-b390-58886861848f.png)

**Courseplay version**
Version used: Cp 7.1.2.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10044733/log.txt)

**Map**
Nordfriesische Marsch 4x OG

**Vehicles/ implements involved**
Vanilla Fendt1050 mit Holares 5 m Schiebeschild und Heckgewicht 3.3 t
Schiebeschild hängt in der Fronthydraulik

**Relevant script mods**
Cp,VCA, AD

**Comment by BullsEye1005** [comment]
Edit:
Ich weiß wann das passiert, und zwar wenn man selber nicht im Walzschlepper sitzt. Sofern man aussteigt, fährt er weiter rückwärts.
Gruß

**Comment by Tensuko** [comment]
> Ich weiß wann das passiert, und zwar wenn man selber nicht im Walzschlepper sitzt. Sofern man aussteigt, fährt er weiter rückwärts.

Das macht halt gar kein Sinn und kann nicht sein, sonst könnten wir nicht mal unsere tests durchführen.

**Comment by BullsEye1005** [comment]
Ich aktiviere vorm Silo, er pegelt sich ein, schiebt einmal bis zur Silorückwand und fährt immer weiter , leicht in Kurve rückwärts. Halt nur ab und zu und nicht jedes mal.
![Screenshot (7)](https://user-images.githubusercontent.com/117856357/202804061-deff5c26-a60f-4223-9243-d5e0bb3b3c45.png)
 Ich hab da mal was farbig markiert
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10044871/log.txt)

**Comment by Tensuko** [comment]
Kann mit deiner Beschreibung und den Bildern so nichts anfangen.
Mach davon bitte mal ein Video...

**Comment by BullsEye1005** [comment]
Ok, es hat nichts damit zu tun ob im Schlepper sitzt oder nicht. Es passiert wirklich wenn er beim Schieben durchdreht in Silo. Der Rückwärts-Path, oder wie ihr das nennt, bricht ab, oder verschwindet.

Habs leider nur auf Youtube hochladen können.
https://www.youtube.com/watch?v=c_fkCle44UM

**Comment by Tensuko** [comment]
Super, das hilft weiter. Mal schauen was da los ist.

**Comment by BullsEye1005** [comment]
Mal ne andere Frage: Was hat das im Courseplaymenü mit 'Fahrrichtung in den Silo' auf sich? Ist damit die Fahrrichtung des Abfahrers gemeint, ob sie vorwärts oder rückwärts abkippen, oder die Fahrichtung des Walzschlepper ins Silo?

**Comment by Tensuko** [comment]
Bei Walzen kann man sich die Richtung in das Silo aussuchen.

**Comment by Tensuko** [comment]
Versuch mal mit der 7.1.2.2
Wenn es nicht klappt, einfach das Issue wieder aufmachen (reopen).

**Comment by BullsEye1005** [comment]
Hmm hab jetzt zurzeit keine Möglichkeit zu testen, da die Maisernte vorbei ist und das Silo voll.
Vielleicht bekomm ich noch ein Grasschnitt hin um das dann zu silieren, dann teste ich es direkt. Auch ob die Ad-Fahrer warten bis der Walzschlepper auf der Parkposition ist. Wird aufjedenfall ein geiler Release wenn das alles klappt.
Passt jetzt zwar nicht hier hin, aber gestern konnte ich kurz das mit 'Entlade drescher' testen. Jetzt nicht mit einem Mähdrescher sondern beim Rüben roden, mit Holmer Überladebunker hat bis jetzt alles einwandfrei funktioniert. Er fuhr direkt den ersten LKW, obwohl zwei da standen, mit genügend seitlichen Abstand an  und konnte normal Überladen. Richtig geil, saubere Arbeit!

**Comment by BullsEye1005** [comment]
Nach ein paar Tests musste ich festellen, dass der Walzschlepper, sofern er was im Silo durchdreht, immernoch den Rückwärtspath verliert und ins leere rückwärts fährt. Manchmal dreht fährt er aus dem Silo rückwärts eine kurve, sodass er Rückwärts wieder ins Silo fährt.
Gruß

**Comment by Tensuko** [comment]
Startest du ihn im Silo? Wenn ja, fahre ihn aus dem Silo raus und dann starten.

**Comment by BullsEye1005** [comment]
nein, ich starte ihn vorm silo....dann fängt er auch etwas an zu rangieren, bis er in seiner spur ist und fängt an zu schieben.
