### ISSUE TITLE
[Feature] Häcksler Abfahrer Modus

### ISSUE THREAD

**Issue by BullsEye1005** [Courseplay/Courseplay_FS22#2126]
Ich weiß, dass ihr es erwähnt habt, dass es kein Abfahrer geben wird, der dem Feldhäcksler/Chopper zugeteilt ist, aber könnt ihr euch das nicht doch noch überlegen, ein Modus zu erstellen, indem man neben 'Entlade Drescher', 'Entlade Häcksler' auswählen kann? In Sache Autodrive funktioniert es zwar mühselig, aber Courseplay ist schon ein Niveau höher was das angeht. Ihr seid ja Profis und ich glaube in Sachen Abfahrer Wendemaneuver und Selbstfahrersuche und das alles, was das Häckseln betrifft, wird das, denk ich, viel reibungsloser funktionieren. Wäre aufjedenfall eine mega Sache und ist auch nur ne Frage.
Wenn ja, Hätte ich, da ich selbst seit 8 Jahren Häcksler fahre, gute Ideen, wie sich der Abfahrer beim Wendemaneuver in der ersten Bahn, wenn er hinter dem Häcksler fährt, bzw die Eckwendemaneuver am Vorgewende beim Anhäckseln usw verhalten sollte.
Gruß

**Comment by Tensuko** [comment]
Nein.
