### ISSUE TITLE
[BUG_SP] 7.1.2.1 Missing 'nil' in l10n files in Unload Combine task

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#2127]
**Steps to reproduce**
Just try to create a CP:Unload Combine job and try to place the field location cursor.

**Actual behavior**
Missing translation line

**Expected behavior**
Correct translation

**Screenshots**
![2022-11-19_23-25-35](https://user-images.githubusercontent.com/70093234/202874020-13047aaf-0b74-4ffb-af65-0fc6728e78cd.png)

**Courseplay version**
Version used: 7.1.2.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10048069/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Tractor with auger wagon vanilla
Mod yes/no ?

**Relevant script mods**
AD but not relevant

**Comment by Tensuko** [comment]
Fixed in next release.
