### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by FarmerJonas** [Courseplay/Courseplay_FS22#2129]
I cant use CP I dont know why but when i right click in a vehicle then nothing happens, I tryed to change something in the settings but yeah nothing happend then. I dont know what I should do can you help me please

**Comment by Tensuko** [comment]
I need your logfile
https://github.com/Courseplay/Courseplay_FS22/wiki
Read "6. Post the complete game log:"

**Comment by schwiti6190** [comment]
@FarmerJonas Check out the FAQ here: https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ#courseplay-hud-isnt-opening-with-a-right-mouse-click

**Comment by FarmerJonas** [comment]
https://pastebin.com/qxGbvGxC

**Comment by Tensuko** [comment]
log looks okay, if your keybinds isn't broken by a giants patch, it should always work to open the hud with del key, or for right click, read the link that schwiti posted.

**Comment by FarmerJonas** [comment]
I am so thankfull to you guys you helped me really. I wish you a good rest day. :)
