### ISSUE TITLE
Stroh aufsammeln mit dem  Landewagen

### ISSUE THREAD

**Issue by rollmops98** [Courseplay/Courseplay_FS22#213]
Hallo,

Wird es eine Möglichkeit geben, Stroh mit dem Landewagen aufzusammeln? bzw. gibt es das  schon? Bei mir wurde es nicht Angezeigt.

Mit der Ballenpresse funktioniert es schon ohne Probleme. 

Vielen Danke für eure schnelle Arbeit.

CP Version 
7.0.0.9

**Comment by EiksYt** [comment]
> Hallo,
> 
> Wird es eine Möglichkeit geben, Stroh mit dem Landewagen aufzusammeln? bzw. gibt es das schon? Bei mir wurde es nicht Angezeigt.
> 
> Mit der Ballenpresse funktioniert es schon ohne Probleme.
> 
> Vielen Danke für eure schnelle Arbeit.
> 
> CP Version 7.0.0.9

Was die Presse kann , kann der Ladewagen auch 😉 nur abfahren musst du selber ☺️

**Comment by Tensuko** [comment]
Ja es kommt noch....

**Comment by rohne83** [comment]
kleiner Workaround bis der Ladewagen funktioniert: Frontmähwerk vorne an den Traktor ran und Ladewagen manuell anschalten. Dann kann zumindest der Kurs abgefahren und das Stroh/Gras/Heu aufgesammelt werden. Nicht schön, aber funktioniert immerhin. Abfahren dann manuell oder mit Autodrive.
