### ISSUE TITLE
[BUG_MP] Fahrzeugeverband wider Fehlerhaft auf Dedi - Fahrzeuge fahren bei Wideraufnahme nicht in Ihre Spur

### ISSUE THREAD

**Issue by GulliGriff** [Courseplay/Courseplay_FS22#2132]
Nachdem Fahrzeuge vor der Version 7.1.1.6 (bei der es dann funktioniert hat) beim zurück kehren alle in die linke Spur gefahren sind, fahren Sie nun in die Mitte (also auf die Spline) und setzen dort ihre Arbeit fort. Es ist egal um was es sich handelt, Sämaschine oder steinesammler.. sobald sie zurück vom be- oder entladen via AutoDrive kommen, setzten sie nun Ihre Arbeit auf der Spline bzw. Mitte fort und ignorieren Ihre Spur. Dies gilt auch wenn sie vom Hof via Atodrive geschcikt werden, da starten sie ebenso so in der Mitte und nicht in ihrer Spur.
Wir spielen auf nem Dedi-Server. Im SP habe ich es nicht probiert ob es dort auch ist oder korrekt funktioniert.

[log_gulli_server.txt](https://github.com/Courseplay/Courseplay_FS22/files/10050679/log_gulli_server.txt)
[log_gulli.txt](https://github.com/Courseplay/Courseplay_FS22/files/10050680/log_gulli.txt)

ich hoffe ihr findet was um das problem zu lösen.

**Comment by Tensuko** [comment]
7.1.2.3 das gleiche?

**Comment by 1969Tonton** [comment]
Ja bei der Version auch im Single Player

**Comment by daserthomas** [comment]
Selbes Problem im Single Player

**Comment by GulliGriff** [comment]
ja, leider auch mit der aktuellen Version :(

**Comment by Tensuko** [comment]
Im SP kann nicht sein.
Das habe ich gecheckt, das funktioniert!

**Comment by 1969Tonton** [comment]
Bei mir hat es mit der letzten Version nicht funktioniert 7.1.2.3

Bin auf Feld gestartet nach laden der Sähmaschinen sind beide Maschinen nicht mit Versatz weitergefahren

**Comment by Racker2409** [comment]
Kann ich bestätigen. Ich bin am Gras sammeln. Da fährt er, sobald er vom entladen mit AD zurück zum Feld kommt und an CP Übergibt auch nicht den versatz für 1 Lings & 1 Rechts. 
Version 7.1.2.3

**Comment by Tensuko** [comment]
Auch nach einem refill im SP (!!) hat er die richtige Bahn gewählt.

**Comment by GulliGriff** [comment]
ok, ich probiere es noch mal..

**Comment by Tensuko** [comment]
Der erste Teil ist mit AD hinschicken und dann Refill, Teil 2 ist mit CP auf dem Feld starten und Refill.
https://drive.google.com/file/d/12kM3uQuBbDo2pCUhBjLq3IZk0PI7eGIQ/view?usp=share_link

**Comment by GulliGriff** [comment]
der erste stand bei mir zum start am feld der zweite wurde durch AD gebracht und übergeben. der erste fuhr in die linke spur (wie gewollt) der 2. schien sich erst nicht ganz sicher zu sein wohin und ist dann doch wider in die mitte gefahren.
![20221121204714_1](https://user-images.githubusercontent.com/59224815/203146150-61a0b560-816a-4bd8-b5f2-0a9b8cfca6b0.jpg)
es scheint als wolle der erste traktor nach dem entladen mit ad beim anfahren seines punktes wo er aufhgehört hat, erst in die richtige spur (in dem fall links) und fährt dann doch in die mitte :(
https://youtu.be/8F39t5nnZCE

**Comment by Tensuko** [comment]
So und DAS ist jetzt MP ?
Ich hab ja gesagt, im SP funktioniert es wie es soll......

**Comment by Racker2409** [comment]
Hallo Tensuko
Das gleiche verhalten habe ich im SP.

Starte ich manuell fährt er wie er soll. Nach dem Entladen durch AD, und rückkehr zum Feld, gleiches verhalten wie von GulliGriff beschrieben

**Comment by Tensuko** [comment]
Naja siehe meine Videos...
Ansonsten logfile und mach du auch mal eins....

**Comment by Racker2409** [comment]
Komme ich erst am Abend zu. Ich werde aber Testen und berichten.

**Comment by Racker2409** [comment]
https://workupload.com/file/bGwXQczcMEd
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10069447/log.txt)

Ich hoffe das hilf.

**Comment by GulliGriff** [comment]
ja, das war MP ich spiele im Normalfall nur MP und so habe ich den Post ja eröffnet. SP hilft mir leider nicht :( aber da es schon mal geschafft hast zum laufen zu bringen, bin ich guter dinge :)

**Comment by Tensuko** [comment]
So Leute jetzt mal eins nach dem anderen.
Punkt 1) Ja das Issue bezieht sich auf MP (!!)
Punkt 2) Im SP bei MIR funktioniert es, ich kann es im SP (!!) nicht reproduzieren, warum es bei anderen im SP nicht funktioniert, kein Plan, ich muss wissen WIE ihr das macht damit ich das nach voll ziehen kann....
Punkt 3) Erst DANN schauen wir warum es sich im MP so verhält.

Schritt für Schritt alles andere ist ein reines durcheinander.....

**Comment by Tensuko** [comment]
Hat schon mal jemand der das Problem hat versucht, das Fahrzeug zurück zu setzen und dann noch mal zu probieren?

**Comment by 1969Tonton** [comment]
Wie kann man ein Fahrzeug zurücksetzten

**Comment by Tensuko** [comment]
Das ist eine Standartfunktion vom Spiel... auf der normalen Map das Fahrzeug auswählen und auf zurücksetzen klicken, das landet dann beim Shop.

**Comment by 1969Tonton** [comment]
![fsScreen_2022_11_24_14_52_13](https://user-images.githubusercontent.com/118510158/203802002-2aa3e703-8fae-4c3e-aff5-1c25e2bf8265.png)
Anfahrt nach Auffüllen der Sähmaschine

![fsScreen_2022_11_24_14_52_31](https://user-images.githubusercontent.com/118510158/203802237-faab2add-9d95-41e4-891e-6d81267af054.png)
Hier wird anscheinend auf einmal der Pfad neu berechnet

![fsScreen_2022_11_24_14_52_56](https://user-images.githubusercontent.com/118510158/203802442-26b724e6-ffff-4c49-95c7-152ee24bbd4f.png)
Fahrzeug fährt dann ohne Versatz weiter

Spiele im SP hab die Fahrzeuge zurückgesetzt, bei mir funktioniert es also nicht. Log mit beigefügt.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10085173/log.txt)

**Comment by ralphv13** [comment]
@1969Tonton eine kleine Frage zu deiner Meldung: Kann es sein, das vor dem Refill und dem Wiederaufsetzen vom säen der Spielstand gespeichert und LS neu gestartet wurde? Im Log sieht es so ein bisschen danach aus.
Ich vermute dabei irgendwo die Ursache, weil ich vorgestern im SP einmal sowas auch hatte. (Tank Leer, via AD zum Refill, speichern, restart, AD wieder starte -> lane offset in der Mitte)  
Leider bekomme ich es nicht wieder nachvollzogen.

**Comment by 1969Tonton** [comment]
Automatisch speichern kann sein, aber bei der Aktionist die Kombi vom Saen
zum Aufladen wieder zurück aufs Feld ohne einen Neustart

ralphv13 ***@***.***> schrieb am Do. 24. Nov. 2022 um 20:46:

**Comment by 1969Tonton** [comment]
![fsScreen_2022_11_24_21_05_01](https://user-images.githubusercontent.com/118510158/203858071-2551e4b9-48bc-4b41-90d2-e9ce61d79b6d.png)
So sieht es mit der alten Version aus

![fsScreen_2022_11_24_21_05_19](https://user-images.githubusercontent.com/118510158/203858092-bbaab194-b64c-4867-951c-7986a0fe3587.png)
![fsScreen_2022_11_24_21_05_30](https://user-images.githubusercontent.com/118510158/203858110-40aa5b6b-8909-4bd6-ba72-c9ad92abac03.png)
Er setz auf ohne den Versatz zurückzunehmen
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10087075/log.txt)

**Comment by ralphv13** [comment]
Also einer machts korrekt, der Zweite ist zickig?
und du hast den 'defekten' auch schon zurückgesetzt, wie Tensuko oben mal als Tipp beschrieben hat?

**Comment by 1969Tonton** [comment]
Nein, die letzten 3 Bilder sind von einer älteren Version Courseplay wo es funktioniert hat. Ich wollte nur den Moment zeigen wo er die anscheinend die Neuberechung macht. Kann es sein das er dort wechselt von Pfad selber rechnen auf die gespeicherte Route!

Sorry hatte es nicht dazu geschrieben wegen der Version,.

**Comment by Tensuko** [comment]
Es gibt keine Neuberechnung und wie es aus zu sehen hat wissen wir...
Ich muss wissen wie ich den Fehler nachstellen kann. Alles andere hilft nicht.

**Comment by 1969Tonton** [comment]
Keine Ahnung bei mir läuft es leider so, ich kann es mal ausprobieren ob es am Speichern liegt. Oder habt Ihr mir sonst einen Tipp was ich ausprobieren kann.

**Comment by ralphv13** [comment]
wie war das jetzt mit dem Zurücksetzen? Das hatte nichts gebracht? 
(ich persönlich hab nämlich keine Ideen mehr, was ich noch versuchen soll außer, das es an dem Zustand im Spielstand/Vehicles liegt)

**Comment by 1969Tonton** [comment]
Zurückgesetzt habe ich die Fahrzeuge.  Was ich probieren kann ist:
- Nicht automatisch speichern
- Fahrzeuge und Sähmaschinen  neu kaufen
Ich probiere das mal und melde mich

**Comment by 1969Tonton** [comment]
Hi also habe automatisch Speichern ausgeschalten und es funktioniert. Die Fahrzeuge machen was sie sollen.

**Comment by Tensuko** [comment]
Okay also in Richtung speichern gucken.
Das heist es könnte sein, dass durch speichern der lane offset vermurks wird.

**Comment by Racker2409** [comment]
Version 7.1.2.3 / SP
Bei mir hat es leider nicht geklappt. Weder mit zurücksetzen, noch mit Verkauf und Neukauf der Gespanne. Ich habe auch CP komplett gelöscht und alle Altlasten von CP entfernt. Weiter habe ich einen neuen Spielstand erstellt, manuell gespeichert und CP wieder installiert. Fahrzeuge neu gekauft, einen Kurs erstellt und mit AD zum Feld geschickt, die dort an CP übergeben wurden. Beide Gespanne sind dann auch richtig in ihre spuren gefahren. Als sie voll waren und vom abladen wiederkamen, sind sie wieder ohne Versatz in die mittlere spur (also ohne Versatz) weitergefahren.
Ich verstehe nur nicht warum es mit Version 7.1.1.6 reibungslos läuft und mit Version 7.1.2.3 solche zicken macht.

**Comment by Tensuko** [comment]
Kannst du mir ein Savegame machen (am besten Elmcreek) mit der 7.1.2.3 wo genau das passiert, wenn ich AD zum Feld schicke.
Ich muss das irgendwie reproduzierbar haben....

**Comment by Racker2409** [comment]
Kann ich leider erst Morgen machen. Soll ich Debug-Kanäle auch einschalten?

**Comment by Tensuko** [comment]
Das ist egal, es muss passieren wenn ich ihn mit AD zum Feld schicke bzw wenn er nach dem refill wieder kommt.

**Comment by Racker2409** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10096141/log.txt)
[savegame4.zip](https://github.com/Courseplay/Courseplay_FS22/files/10096152/savegame4.zip)

Ich hoffe das ist so richtig.

**Comment by Tensuko** [comment]
Es hat nichts mit der Map zu tun.

Neueste Erkenntnisse dank des Saves von @Racker2409 

Fahrzeuge standen auf dem Feld und wurden von mir mit CP mit den korrekten Lanes gestartet + das CP Icon im AD Hud gesetzt. Bei Wiederankunft, trat genau der Fehler auf.

Anschließend habe ich den Spieß mal umgedreht und die Fahrzeuge mit AD zum Feld fahren lassen (passt) und auch einmal nach dem Gras wegbringen wieder zurück kehren lassen. Kein Fehler!

Aber so können wir schon mal mehr in die Richtung schauen, was da los ist.

**Comment by Racker2409** [comment]
Danke fürs dranbleiben. Jetzt klappt es wieder wunderbar.
Gruß Manni

**Comment by 1969Tonton** [comment]
Wann kommt die neue Version oder kann man die schon runter laden.

**Comment by Tensuko** [comment]
Neue Version ist jetzt da, auch ein schneller test auf dem MP Server hat funktioniert.
Bitte testen.

**Comment by Jarsi11** [comment]
Kurze frage bei mir komme ich nicht von der version 7.1.0.3 weg und wenn ich es lösche und neu installiere geht es auch nicht?

**Comment by Tensuko** [comment]
Das ist ja auch die modhub version und nicht github.

**Comment by Jarsi11** [comment]
Ich habe aber das Problem das egal was ich mache ich kann die github Version herunterladen aber sie wird bei mir als 7.1.0.3 angezeigt

**Comment by Tensuko** [comment]
Dann scheinst du im spiel immer wieder das update aus dem modhub zu machen... Das darfst du natürlich nicht machen.

Hier runter laden und in den mods Ordner packen.
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.1.2.4

**Comment by Jarsi11** [comment]
Hat geklappt danke dir :D
