### ISSUE TITLE
[BUG_SP] Bunker Silo Mode not working with Wheel Loader

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#2133]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use a wheel loader with a blade, ie holaras MES 400, and attempt to start the bunker silo mode.

**Actual behavior**
Game locks up, will not let you stop CP, switch vehicles or anything but quit

**Expected behavior**
The wheel loader to pile and push the chaff into the bunker

**Screenshots**

**Courseplay version**
Version used:  7.1.2.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10052039/log.txt)

**Map**
Map played on.
Michigan  Farms Map

**Vehicles/ implements involved**
Which vehicle or implement?
Volvo L180H wheel loader (Platinum Expansion)
holaras MES 400 (Base) and Lizard Logistics U-Plow (Lizard U-Plow Mod)
Mod yes/no ?

**Relevant script mods**
AD (Not in use)

**Comment by Tensuko** [comment]
Intended.
