### ISSUE TITLE
[BUG_MP] Client hang and crash with attached device after press no course

### ISSUE THREAD

**Issue by HurrycaneBE** [Courseplay/Courseplay_FS22#2134]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
enter a vehicle with attached device - press no course - client crashes

**Actual behavior**
at press of no course , the client goes an 100% load , ram runs full , only possible to kill the task - this happens since giants patch 1.8.2.0

**Expected behavior**
normally CP settings screen will open after scan of field is complete

**Screenshots**

**Courseplay version**
Version used: 7.1.2.3

**Client Log**
https://pastebin.com/y1BGe8qf

**Server Log**
https://pastebin.com/Axtjatit

**Player on the server**
1 - 4
**Dedicated server or local hosted server**
Dedicated server yes/no ?
Dedicated Server - own hardware

**Map**
Hopfach

**Vehicles/ implements involved**
Which vehicle or implement? Valtra and others (Landini with fertilizer and more)
Mod yes/no ? no

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD - actual version , Guidance steering - actual version

This problem has begun with game version 1.8.2.0 , and still persits with the last versions of CP.  PM me if you need more informations.

**Comment by HurrycaneBE** [comment]
Hurry left the game
:57 [dbg14 lp102191] Saved setting: wageModifier, value:100, key: Courseplay.GlobalSettings.GlobalSetting(0)
:57 [dbg14 lp102191] Saved setting: autoRepair, value:0, key: Courseplay.GlobalSettings.GlobalSetting(1)
:57 [dbg14 lp102191] Saved setting: fuelThreshold, value:5, key: Courseplay.GlobalSettings.GlobalSetting(2)
:57 [dbg14 lp102191] Saved setting: brokenThreshold, value:100, key: Courseplay.GlobalSettings.GlobalSetting(3)
:57 [dbg14 lp102191] Saved setting: maxDeltaAngleAtGoalDeg, value:45, key: Courseplay.GlobalSettings.GlobalSetting(4)
:57 [dbg14 lp102191] Saved setting: deltaAngleRelaxFactorDeg, value:10, key: Courseplay.GlobalSettings.GlobalSetting(5)
:57 [dbg14 lp102191] Saved setting: expertModeActive, value:false, key: Courseplay.GlobalSettings.GlobalSetting(0)
:57 [dbg14 lp102191] Saved setting: controllerHudSelected, value:false, key: Courseplay.GlobalSettings.GlobalSetting(1)
:57 [dbg14 lp102191] Saved setting: showsAllActiveCourses, value:false, key: Courseplay.GlobalSettings.GlobalSetting(2)
:57 [dbg14 lp102191] Saved setting: drawOntoTheHudMap, value:true, key: Courseplay.GlobalSettings.GlobalSetting(3)
:57 [dbg14 lp102191] Saved setting: showActionEventHelp, value:false, key: Courseplay.GlobalSettings.GlobalSetting(4)
:57 [dbg14 lp102191] Saved setting: infoTextHudActive, value:true, key: Courseplay.GlobalSettings.GlobalSetting(5)
:57 [dbg14 lp102191] Saved setting: infoTextHudPlayerMouseActive, value:true, key: Courseplay.GlobalSettings.GlobalSetting(6)
:57 [dbg14 lp102191] Saved setting: preferCustomFields, value:false, key: Courseplay.GlobalSettings.GlobalSetting(7)
:57 [dbg14 lp102191] Saved setting: distanceUnit, value:0, key: Courseplay.GlobalSettings.GlobalSetting(8)
:58 [dbg14 lp102191] Saved setting: useGiantsUnload, value:false, key: vehicles.vehicle(108).aiJobVehicle.lastJob.cpJobParameters(0)
:58 [dbg14 lp102191] Saved setting: unloadingStation, value:501, key: vehicles.vehicle(108).aiJobVehicle.lastJob.cpJobParameters(1)
:58 [dbg14 lp102191] Saved setting: useGiantsUnload, value:false, key: vehicles.vehicle(195).aiJobVehicle.lastJob.cpJobParameters(0)
:58 [dbg14 lp102191] Saved setting: unloadingStation, value:4036, key: vehicles.vehicle(195).aiJobVehicle.lastJob.cpJobParameters(1)
  Info: [AD] ADUserDataManager: saved data for 8 users
Game saved successfully.

**Comment by Tensuko** [comment]
No CP Error in your log but your Map already have a Callstack....

**Comment by HurrycaneBE** [comment]
you mean the call stack of slaughterhouse. this is since patch 1.8.2.0 allready. but the production is not in use , and not owned by someone.

**Comment by Tensuko** [comment]
just from pressing on no course?
where do you stay on the map when you press it?

**Comment by HurrycaneBE** [comment]
on field 120 - open CP window -> no course = crash / game hangs

**Comment by Tensuko** [comment]
and if you wait long enough?
couse this is not crashing that is it takes long....

**Comment by HurrycaneBE** [comment]
hmm can test it .. how long wait maximum ? have waited 5 mins last time ..

**Comment by Tensuko** [comment]
for scanning a field thats very long....
what about other fields?
same problem?
I can't rly believe that there is a CP Error for it as I think we would have more ppl with that problem....
