### ISSUE TITLE
Bunker Silo Mode with Agripower Leitwolf spammt Log with Errors[BUG_SP]

### ISSUE THREAD

**Issue by RolfB69** [Courseplay/Courseplay_FS22#2137]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Start the Game with some Chaff in a Bunker Silo, Buy the Snowcat Agripower Leitwolf and try to Start the Bunker Silo Mode

**Actual behavior**
The Snowcat don´t start with work and spamm the Log with Errors. On the same Setting a Tractor with shield works fine.

**Expected behavior**
The Snowcat should work like a Traktor with shield

**Screenshots**
![Snowcat Error](https://user-images.githubusercontent.com/58603270/203297724-281231f3-d0cf-4d1b-944d-232f00db7b8d.jpg)

**Courseplay version**
Version used: 7.1.2.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10066593/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Agripower Leitwolf (witch dosen´t work)
Valtra Q Series with Shield MES400 (witch works fine) 
all Vanilla
Mod yes/no ? For testing with no mods expect CP

**Relevant script mods**
no mods expect CP

**Comment by GulliGriff** [comment]
beim xerion gibt es keine Fehler. scheint etwas mit dem Fahrzeug zu tun zu haben.

**Comment by Selyria** [comment]
Ich habe das gleich auch im Multiplayer wenn ich ihn einschalte bleibt der komplette Server hängen schalte ich ihn aus läuft alles normal weiter

**Comment by Tensuko** [comment]
fixed
