### ISSUE TITLE
[Feature] Bunker Silo Mode - Change size of no go zone

### ISSUE THREAD

**Issue by schwyl** [Courseplay/Courseplay_FS22#2138]
**What is the problem this feature/enhancement solves?**
The no go zone around the bunker is too large

**Describe the solution you'd like**
A way to adjust the size of it.

![nogoaonze](https://user-images.githubusercontent.com/2615447/203657260-161f469f-a4a5-4279-83ba-6681b37ef3dc.jpg)

**Comment by Tensuko** [comment]
Wont change it, may make it adjustable.
We need that distance for unloaders right now.
