### ISSUE TITLE
[Question] K9 Dozer Blade Error, what information is CP looking for?

### ISSUE THREAD

**Issue by antler22** [Courseplay/Courseplay_FS22#2139]
Hello,

I am trying to update this blade to work with Courseplay.  When activating, I get this error on repeat, but looking in the LUA I'm not understanding what information courseplay is looking for.  The blade works fine for me pushing silage but I would like CP to be able to use it.  Can you please advise?

Mod link:  https://fs22.com/farming-simulator-22-mods/implements-and-tools/front-loader/k9-dozer-blade-v1-0/

Error: Running LUA method 'update'.
C:/X/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/controllers/LevelerController.lua:94: attempt to index local 'jointDesc' (a nil value)

Line 94 of the .lua is below
spec.heightTargetAlpha = jointDesc.upperAlpha

There is nothing in the xml with "jointDesc" in the name, but that is also the case for base game levelers.

Thank you.

**Comment by Tensuko** [comment]
Sry but no support for mods from those websides are given. Take a Giants blade and compare it with your mod.
