### ISSUE TITLE
Missing l10n 'input_CP_OPEN_CLOSE_VEHICLE_SETTING_DISPLAY

### ISSUE THREAD

**Issue by Goofy78** [Courseplay/Courseplay_FS22#214]
Da fehlt was :-)
![fsScreen_2021_12_28_21_52_20](https://user-images.githubusercontent.com/96694308/147606226-15429717-6a3b-4a35-aad8-04146cfb0127.png)

Ganz vergessen, es ist die v7.0.0.9

**Comment by Tensuko** [comment]
Nö.
![fsScreen_2021_12_28_22_04_06](https://user-images.githubusercontent.com/27344744/147606938-99acc058-525d-4350-b82a-c0987274627c.png)

**Comment by Goofy78** [comment]
hmm... dann muss ich mal auf Ursachenforschung gehen. Danke trotzdem
