### ISSUE TITLE
MF 1840 baler is being blocked in reversing by its own bale-in-chute

### ISSUE THREAD

**Issue by Thunderloon** [Courseplay/Courseplay_FS22#2146]
v 7 1 2 4   
nuf said I think

Siverrun, field 3 hay baling mission running end to end lines.   when I swing by with the old bale wagon and autocollect the bale off the back of the MF 1840 it starts backing up without hesitation and continues course

**Comment by Tensuko** [comment]
duplicate....

**Comment by Tensuko** [comment]
#1863
