### ISSUE TITLE
[Feature] Kartoffelernter im Modus Drescher selbst abtanken

### ISSUE THREAD

**Issue by Ghost265** [Courseplay/Courseplay_FS22#2150]
**What is the problem this feature/enhancement solves?**
Wenn der Kartoffelernte selbst abtanken fährt und damit dann fertig ist fährt er voll eingeschlagen rückwärts los.

**Describe the solution you'd like**
es wäre besser wenn der Kartoffelernter vorwärts leicht eingeschlagen weg fährt um erstmal abstand zu den abfahrer zu bekommen bevor dann gewendet wird falls dies nötig ist zu wenden.

**Comment by Tensuko** [comment]
Welcher Kartoffelernter, wie fährt er rückwärts weg, was ist das eigentlich Problem.
So kann ich mir nichts drunter vorstellen schon gar nicht was wir verbessern sollen.

**Comment by Ghost265** [comment]
https://imgur.com/a/uuLa8aV

Bild1. Er fährt nicht ab obwohl voll
Bild2. Die Einstellungen dazu
Bild3. Er ramt den Trecker weg
Bild4. Er fährt rückwärts und hängt sich auf

**Comment by Tensuko** [comment]
mh okay..... muss ich mir mal anschauen....

**Comment by Tensuko** [comment]
Das liegt an der größe und komplizierten Modell des Ernters.
Was funktioniert ist, wenn du in den Fahrzeugeinstellungen die Option:
Pathfinder darf rückwärts fahren deaktivierst.
Warum der sich beim rückwärts fahren so anders verhält, kann ich nicht sagen.

Jedenfals klappt das so dann ganz gut.
