### ISSUE TITLE
Beim Einsatz von 5 Dreschern fahren die ersten Beiden das Rohraus alle weiteren Anderen nicht.

### ISSUE THREAD

**Issue by hleithoff** [Courseplay/Courseplay_FS22#2151]
**Steps to reproduce**
Kaufe mehr als 2 Drescher und setze sie auf den gleichen Kurs

**Actual behavior**
Beim Einsatz von 5 Dreschern fahren die ersten Beiden das Rohraus alle weiteren Anderen nicht.

**Expected behavior**
Kein Rohr sollt ausgefahren sein . 
Nur dann wenn der Drescher voll ist und abgetankt werden soll.

**Courseplay version**
Version used:  Latest Version 7.1.2.4

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Vehicles/ implements involved**
Claas Drescher
Mod yes/no ? 
No

**Comment by Tensuko** [comment]
logfile.....

**Comment by hleithoff** [comment]
[gamelog.txt](https://github.com/Courseplay/Courseplay_FS22/files/10123805/gamelog.txt)
Hier das Log vom Dedic

**Comment by hleithoff** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10125723/log.txt)
![Farming Simulator 22 Screenshot 2022 11 30 - 18 24 49 71](https://user-images.githubusercontent.com/59266008/204867024-6b255bc1-5532-4212-9ce7-13073b0dc685.png)
![Farming Simulator 22 Screenshot 2022 11 30 - 18 25 06 85](https://user-images.githubusercontent.com/59266008/204867083-655cda61-8685-43bb-9a73-6fe98ff6c7d0.png)

Hallo ..... CP fährt das Rohr ab dem 3. Drescher aus .... Die AD Einstellungen sind abgeschaltet.
Siehe nun Fehlerfreies Log

**Comment by Tensuko** [comment]
Passiert das bei dir auch im SP?

**Comment by Tensuko** [comment]
Kann es im SP nicht reproduzieren, Server muss ich mal gucken.
![fsScreen_2022_11_30_20_53_33](https://user-images.githubusercontent.com/27344744/204895427-593c6dca-8af2-449d-96c5-ad1861397dea.png)

**Comment by hleithoff** [comment]
Hallo.
Kannst du es bitte mal mit dem CLAAS Lexion 8900 checken?
Hat der das Problem? Das wäre dann Giants Standart.
Gruß Holger

**Comment by hleithoff** [comment]
Hallo.... Kann es mir grade nicht erklären ....
Habe Drescher Nr. 4 Aktiv ... Fehler Weg im SP ........
![Farming Simulator 22 Screenshot 2022 11 30 - 22 41 09 32](https://user-images.githubusercontent.com/59266008/204914702-6f9a2184-009f-4f49-8f59-73331bd3c9e6.png)
![Farming Simulator 22 Screenshot 2022 11 30 - 22 41 19 63](https://user-images.githubusercontent.com/59266008/204914734-81cab815-a7cc-4639-be0f-c35af8c92810.png)

Ich prüfe es Morgen im MP/ Dedic.....
Estmal Vielen Dank...

**Comment by Tensuko** [comment]
Naja im MP auf dem Dedi kann es trotzdem passieren, aber warum..... gibt an sich keinen Grund dafür.
Vlt kommte ich am WE dazu das selber auf dem Dedi zu probieren.

**Comment by hleithoff** [comment]
Hallo .... Habe einkurzen Test auf dem DEDIC gemacht ohne AD ..... Fehler war weg ...... nun sind alle anderen Mods wieder aktiv...
Ich sehe es heute Abend ob es dann auch weg ist.....
Ich melde mich dann.
Gruß Holger

**Comment by hleithoff** [comment]
Hallo .... Das problem besteht leider immer noch auf dem Dedic Server .... mit oder ohne AD (oder anderen Mods)
Diesmal bei der Ernte ..... hatte nur der Erste Drescher das Abtankrohr ausgefahren.... alle Anderen nicht.
[gamelog.txt](https://github.com/Courseplay/Courseplay_FS22/files/10149076/gamelog.txt)
Gruß Holger.

**Comment by Tensuko** [comment]
Ich muss mir das mal in Ruhe angucken, kann dir leider nicht sagen wann ich dazu komme....

**Comment by Tensuko** [comment]
Kann es nicht reproduzieren mit CP 7.1.2.4 und AD 2.0.0.9
Eventuell deine Einstellungen überprüfen.

![grafik](https://user-images.githubusercontent.com/27344744/209320410-e26af2a6-8d75-4688-8183-8a87a832c9d2.png)
![grafik](https://user-images.githubusercontent.com/27344744/209320541-d9253ae7-6c48-4270-81d5-862bf51c86f7.png)
