### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by FarmerJosef** [Courseplay/Courseplay_FS22#2152]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10140184/log.txt)
Ich habe seit Tagen das problem das sich das Hud von Courseplay nicht öffnet weder mit tastertur noch mit Maus.
Habe CP und Autodrive bzw. das Spiel selbst schon neu Installiert, habe es mit und ohne Mods probiert geht nicht auf.

**Comment by Tensuko** [comment]
Erstmal neue Version laden (Version: 7.1.2.3) FS22_Courseplay
7.1.2.4

Und deine log beginnt direkt mit nem Callstack.

FS22_TrailerJointBlock ist verantwortlich wie es scheint.

**Comment by FarmerJosef** [comment]
Habe die neuste Version instaliert
den rest verstehe ich nicht bin kein Computermensch bin alter mann

**Comment by Tensuko** [comment]
In deiner log.txt ist ein Fehler drin, der durch die Mod "FS22_TrailerJointBlock" verursacht wird.
Das kann auch zu dem Fehler führen.

**Comment by schwiti6190** [comment]
@FarmerJosef https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ#courseplay-hud-isnt-opening-with-a-right-mouse-click Das einmal probieren :)

**Comment by FarmerJosef** [comment]
Habe die Mod gelöscht Version 7.1.2.4 instaliert geht nicht ist nicht zu öffnen

**Comment by FarmerJosef** [comment]
Habe ich alles getan linke Maustaste, tasten auch umgelegt ohne Erfolg ihr seht mich ratlos

**Comment by Tensuko** [comment]
Mach mal ein Screenshot von der Situation, in der du das HUD öffnen möchtest.

**Comment by FarmerJosef** [comment]
Wie man im Screenshot sieht steht rechts oben etwas weiss aber nicht was das ist
![fsScreen_2022_12_03_12_45_16](https://user-images.githubusercontent.com/119299516/205439474-e3e7bd6b-e2bc-4510-9520-db45aa5f669b.png)

**Comment by FarmerJosef** [comment]
wenn ich einschalten kommt das Geräte......
wenn ich ausschalte ist das wieder weg

**Comment by Tensuko** [comment]
Das oben rechts ist das Info Panel.
Das ist immer da.

Und wenn du da jetzt rechtsklick drückst oder entf auf der Tastatur (wenn du die Standart Tastenbelegung hast) passiert nichts?

**Comment by FarmerJosef** [comment]
nein passiert nichts ich meine nicht das info pnel sondern das über dem Geld

**Comment by Tensuko** [comment]
Ach.... ja da ist das HUD, das ist bei dir ja ganz komisch verschoben.....
Geh mal bitte in den Ordner:
..\Dokumente\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay
Da machst du die courseplay.xml auf
Da gibt es die Zeile (Bei dir wohl ganz andere Zahlen):
<Hud posX="0.163672" posY="0.046528"/>
Und dann ersetzt du deine Zeile mal mit dieser.
Oder löschst die Datei, das sollte auch problemlos funktionieren.
Dann sollte das HUD eigentlich an der richtigen Stelle auftauchen.

**Comment by FarmerJosef** [comment]
Welche Zeile durch was ersetzen sind bei mir nur Leerstellen

**Comment by FarmerJosef** [comment]
Alles klar funzt wieder habe die koordinaten von meinem Loptop übernommer ist wieder back

**Comment by FarmerJosef** [comment]
Danke für die schnelle Hilfe ohne ging das gar nicht vielen Dank noch einmal

**Comment by Tensuko** [comment]
Kein Problem

**Comment by FirenzeIT** [comment]
Hello, someone can fix mod FS22_TrailerJointBlock?? The author FSSA abandoned this project, someone which can fix the issue.. please

**Comment by Tensuko** [comment]
We will not fix other modders mods.

**Comment by FirenzeIT** [comment]
> We will not fix other modders mods.

ok, but the author abandoned this mod and nothing contact him...
