### ISSUE TITLE
Last position

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/Courseplay_FS22#2156]
Worker does not return to last position worked on field... Current Def version...
Returning from silo worker starts again from the beginning..
Choices does not matter like.. Closest waypoint, First waypoint, and Last position etc...
Straw pickup on field. Even refill seedier/planter and by returning.. starts again from the beginning.
No map issue etc...
Previous Versions worked fine.
Regards

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki
