### ISSUE TITLE
[BUG_SP] Mähdrescher entladen funktioniert nicht richtig.

### ISSUE THREAD

**Issue by Myiamoto86** [Courseplay/Courseplay_FS22#2157]
Gute Nacht, Mensch.

Ich habe einige Mod-Tests durchgeführt, als ich auf die folgende Situation gestoßen bin: Wenn ich die Lastwagen aktiviere, um die Erntemaschinen zu entladen, fahren die Lastwagen den Weg neben der Erntemaschine entlang, aber weg vom Rohr der Erntemaschine.

Wenn die Erntemaschine voll ist, kann der Lastwagen nicht daneben halten, um sie zu entladen.

Zum Entladen funktioniert es nur mit Autodrive, und in den CP-Einstellungen muss ich die Funktion aktivieren, dass der Harvester im Stillstand entladen wird.

Ich habe ein kleines Video gemacht, ich hatte 300 MB. Fotos habe ich auch.

https://drive.google.com/drive/folders/1OLNjxABoyS1f2cbb9dwatYj8EK4hpwaf?usp=sharing

Die CP-Version ist die aktuellste.
![Farming Simulator 22 Screenshot 2022 12 05 - 21 24 27 12](https://user-images.githubusercontent.com/108041428/205779899-d366a6c2-23fb-46b8-b79b-c62562bdbe09.png)

**Comment by Tensuko** [comment]
Kein Ausgefülltes Template, kein logfile, nichts.....

Vom Video her:
einfach den Offset anpassen, dafür ist der da.
Auch das Schneidwerk ist zu breit wie man im Video sieht.
Da könnte man auch mit dem Offset arbeiten im HUD, aber sah schon sehr knapp aus.

Not a CP Issue. User Error, use Offset from HUD to adjust.
