### ISSUE TITLE
Vehicle with trailer specialisation can't start Combine Unloader job with actual trailer attached

### ISSUE THREAD

**Issue by Kieruss** [Courseplay/Courseplay_FS22#2159]
Problem: Vehicle with trailer specialization can't start Combine Unloader job (with actual trailer attached)

Function: CpAICombineUnloader:getCanStartCpCombineUnloader()
Offending line: return not self:getCanStartCpFieldWork() and AIUtil.getNumberOfChildVehiclesWithSpecialization(self, Trailer) == 1

Result: A vehicle with a trailer spec, even if unused in the xml, will return "2", which does not == 1

**Steps to reproduce**
Install Roadrunner truck https://www.farming-simulator.com/mod.php?mod_id=230640
Note that truck without trailer is able to start combine unload job
Attach trailer, and note that only bunker silo job is available

**Courseplay version**
Version used: v7.1.2.4 Latest

I'm not sure why I had "trailer" in the custom spec (maybe from FS19, when it was used as another shop config option?), but it's not actually used currently. Removing that from the vehicleTypes definition corrects the problem, but I think that requiring a single trailer spec (when counting the root vehicle) may be a bug (maybe other vehicles still use it for more configuration options). It appears that additional checks are required (eg. CoverController.lua:49 spits errors, if the check is changed from == 1 to >0), apart from requiring 1 or more trailer specs in all "children"

Edit: That CoverController.lua:49 error is actually still happening, without the trailer spec on the truck, but it's linked to the truck (not trailer), so I'm investigating that, currently.

**Comment by Tensuko** [comment]
Mod Issue.
If the Vehicle have trailer spec, its a problem of the mod.

**Comment by jeffreytoller** [comment]
I realize this is closed, but I agree that checking for the presence of a trailer spec with an equality (==1) instead of an inequality (>0) is artificially limiting.

**Comment by Tensuko** [comment]
It is on purpose.
More then one trailer is not supported.

**Comment by jeffreytoller** [comment]
I see. Thank you for the explanation.

**Comment by Kieruss** [comment]
I've also found an issue where the truck having the **cover** spec causes CoverController:getFillUnits() to spit errors, because self.implement.getAIDischargeNodes returns nil.

So, to confirm, CP doesn't support tractors that use **trailer** or **cover** specs for additional shop options?

Log with no trailer spec, but cover spec
```
2022-12-15 16:15 LUA call stack:
  =C:/FS22/mods/FS22_Courseplay/scripts/CpUtil.lua (229) : printCallstack
  =[C] (4294967295)
  =C:/FS22/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (49) : pairs
  =C:/FS22/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (64) : closeCover
  =C:/FS22/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (263)
  =C:/FS22/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (240) : raiseControllerEvent
  =C:/FS22/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyUnloadCombine.lua (1765) : updateImplementControllers
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/FS22/mods/FS22_Courseplay/scripts/CpUtil.lua (229) : xpcall
  =C:/FS22/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (360) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1886) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1134) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1244) : update
2022-12-15 16:15 :56 [info lp2599] C:/FS22/mods/FS22_Courseplay/scripts/ai/controllers/CoverController.lua:49: bad argument #1 to 'pairs' (table expected, got no value)
```

**Comment by Tensuko** [comment]
Correct.
We dont support wrong or broken mods.

**Comment by DrewCZ** [comment]
CoverController.lua error with ingame overloader:

`2022-12-22 22:50 LUA call stack:
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/CpUtil.lua (229) : printCallstack
  =[C] (4294967295)
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (49) : pairs
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/ai/controllers/CoverController.lua (64) : closeCover
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (263)
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (240) : raiseControllerEvent
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/ai/AIDriveStrategyUnloadCombine.lua (1765) : updateImplementControllers
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/CpUtil.lua (229) : xpcall
  =D:/DataTata/FarmMods22/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (365) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1886) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1134) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1244) : update
`
with ingame Bergmann GTW330
![obrazek](https://user-images.githubusercontent.com/26751314/209232673-042650f7-5330-4017-bb1a-3c8c29c84f86.png)
