### ISSUE TITLE
Keine Funktion von Kursen mit Mod-Traktoren[BUG_SP]

### ISSUE THREAD

**Issue by micknessi** [Courseplay/Courseplay_FS22#216]
**Steps to reproduce**
Versucht. mit Mod-Traktor zu säen, walzen oder grubbern auf Feldern der Erlengrat

**Actual behavior**
Traktor fährt auf Feld, dann erscheint "Helfer hat Arbeit erfolgreich beendet" Dann mit einem Vanilla-Traktor den gleichen Kurs und die gleiche Arbeit erstellt, funktioniert problemlos

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.0.8

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Erlengrat.

**Vehicles/ implements involved**
Mod yes/no ?yes, jeder Update-Traktor aus den herunterladbaren Inhalten

**Relevant script mods**
AD, VCA und AIVE im Spiel, aber nicht benutzt.

**Comment by Tensuko** [comment]
Hast du ein konkretes Beispiel ?
ModHub Link.

**Comment by Tensuko** [comment]
Hab mal den Case Mod von Giatns genommen, klappt, liegt also nicht an alle Mod-Traktoren!

**Comment by Tensuko** [comment]
Can't reproduce. Reopen with a example and a complete filled template pls, thank you.
