### ISSUE TITLE
Silo verdichten 

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS22#2161]
Bunkersilo schieben funktioniert ab dem letzten Update recht gut. Beim Verdichten habe ich noch kein Gerät gefunden, was von CP erkannt wird. Ist es möglich, das 'Verdichten' noch nicht von CP implantiert ist?
Wäre es möglich, das noch einzubauen?

**Comment by Tensuko** [comment]
Was mir noch einfällt, aber auch in der changelog stand bin ich der meinung....
Startpunkt durchschalten bis bunker modus.

**Comment by franky-bb** [comment]
> Was soll ein Gerät zum verdichten sein und in wie weit soll es sich vom normalen fahren unterscheiden? Verdichten ist Fahrzeug selber, Walze, Gewicht. Es ist der gleiche Modus.
![fsScreen_2022_12_09_12_15_54](https://user-images.githubusercontent.com/35263980/206690913-9fe8e027-5784-4fa3-b865-8b7eef79b22a.png)
Mit Schiebeschild lässt sich der Bunkersilo Mode auswählen.

![fsScreen_2022_12_09_12_15_54](https://user-images.githubusercontent.com/35263980/206691173-223484cd-d739-47bd-ab5f-3bef37fac908.png)
Ersetze ich das Schild gegen eine Silowalze, kann ich die Mode gar nicht erst auswählen.

**Comment by franky-bb** [comment]
> Was soll ein Gerät zum verdichten sein und in wie weit soll es sich vom normalen fahren unterscheiden? Verdichten ist Fahrzeug selber, Walze, Gewicht. Es ist der gleiche Modus.

![fsScreen_2022_12_09_12_14_39](https://user-images.githubusercontent.com/35263980/206691617-175154bf-71ea-4952-a781-d5796190df1f.png)
Mit Schiebeschild lässt sich der Mode auswählen und entsprechend editieren.

![fsScreen_2022_12_09_12_15_54](https://user-images.githubusercontent.com/35263980/206691814-51454d8c-6bb6-44af-94d3-4eda79173712.png)
Mache ich nur eine Verdichter Walze dran, kann ich nicht mal den Mode auswählen.

**Comment by Tensuko** [comment]
Das probiert?

>Was mir noch einfällt, aber auch in der changelog stand bin ich der meinung....
>Startpunkt durchschalten bis bunker modus.

**Comment by franky-bb** [comment]
Bekomme es nicht hin. Bin zu blöd 🙄.

**Comment by Tensuko** [comment]
Auf "letzter Wegpunkt" drücken bis der Modus kommt.
Sollte gehen.

**Comment by Tensuko** [comment]
Schild ist halt klar, Walze nicht, desshalb umschalten.
