### ISSUE TITLE
[BUG_SP] Drescher wendet nicht

### ISSUE THREAD

**Issue by NurPech** [Courseplay/Courseplay_FS22#2163]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Weiß ich leider nicht, da nur ein Gerät betroffen ist.

**Actual behavior**
Einer meiner Drescher wendet am Ende der Reihe nicht, sondern fährt nur gerade aus bis er nicht mehr weiter kann. Dabei fährt er bspw. in einen Baum oder ins Wasser.

**Expected behavior**
Der Drescher sollte am Ende der Reihe umdrehen und in die nächste Reihe fahren.

**Screenshots**
Habe ich leider gerade keine

**Courseplay version**
Version used: 7.1.2.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10179930/log.txt)

**Map**
Nordfriesische Marsch. Fehler tritt auf Feld 65 auf

**Vehicles/ implements involved**
Lexion 8900
Mod yes/no ? nein

**Relevant script mods**
AutoDrive, VCA

**Comment by Tensuko** [comment]
Da ist ein Callstack.
Ich würde zu gerne ein Screenshot von deinem Kurs haben da wo es passiert...

**Comment by NurPech** [comment]
Hallo,

Hier ist ein Ende der Reihe:
![20221208193119_1](https://user-images.githubusercontent.com/916273/206538086-602c54e9-5cca-4e61-a898-1c25dcad9c13.jpg)

Bei drei Versuchen kamen nun drei andere Verhaltensweisen raus:
1. Fährt gerade aus
2. dreht ein wenig nach links und fährt dann gerade aus
3. dreht im Kreis

Wenn ich noch andere Dinge geben soll (z.B. das komplette Savegame) tu ich das gerne.

**Comment by pvaiko** [comment]
Ein Savegame würde helfen mit dem Kurs in Drescher geladen, bin sicher die Insel ist das Problem da...

**Comment by NurPech** [comment]
[savegame.zip](https://github.com/Courseplay/Courseplay_FS22/files/10196854/savegame.zip)

Bitte, hier. Auf dem Feld stehen zwei Drescher, beide haben den Kurs geladen.
