### ISSUE TITLE
[BUG] Jacto Hover 500 Zuckerrohr Ernter can't turn in 90° turn

### ISSUE THREAD

**Issue by Swinegel** [Courseplay/Courseplay_FS22#2165]
Es wäre schön den o.g. ernter besser zu unterstützen. Derzeit hat der jacto Probleme beim Richtungswechsel im Vorgewende. 
Statt dem Kurs zu bei einer 90 Grad Wende zu folgen, fährt der Jacto Hover 500 einfach geradeaus weiter. Die 180 Grad Wende in den einzelnen Reihen funktioniert aber problemlos.

**Comment by Tensuko** [comment]
Wie in der changelog, nicht die schönste Lösung, aber besser als wenn er abhaut.
