### ISSUE TITLE
Setting a work width [Feature]

### ISSUE THREAD

**Issue by veghotve** [Courseplay/Courseplay_FS22#217]
**What is the problem this feature/enhancement solves?**

_It takes a bit of time setting different work widths, for example if you are using a work width of 10 meters for planting, and then 36 meters for fertilizing._ 

**Describe the solution you'd like**

_The best way, would be like in Courseplay for FS19, where you can automatically  detect the width_

**Describe alternatives you've considered**

_But another way could be to have preset 5-10-15-20-25-30, for example 
Or hold shift when changing work width to move 5 meters up._ 

**Additional context**

**Comment by Tensuko** [comment]
With 7.0.0.9 you should get the correct working width.
