### ISSUE TITLE
[BUG_SP] Kuhn GA 9531 will not lower rakes until a player comes close

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#2171]
**Steps to reproduce**
Send a worker to the field using Autodrive and let CP retake worker to start the windrow course or start CP worker on your own and run away from the worker 100-200 meters to reproduce the issue.

**Actual behavior**
When CP worker start doing its job, in this case windrowing grass/hay, the tool Kuhn GA 9531 will not lower rotary rakes UNTIL the player comes to the proximity of the tool. So basically, player far away = windrower will not lower rakes, player nearby = windrower will lower rakes.

**Expected behavior**
The tool Kuhn GA 9531 should lower rotary rakes no matter how far away is the player on the map, it should work same as base-game Giants windrowers.

**Screenshots**
here is the video and some screenshot so you can see whats happening
https://youtu.be/x_VBd0Hw0JY 

**Courseplay version**
Version used:  7.1.2.4

**Log**
attached log with all debug channels

**Map**
Old Stream Farm latest version.

**Vehicles/ implements involved**
Which vehicle or implement?
Case Puma from Modhub and windrower Kuhn GA 9531 same from Modhub (but i tried with default base-game tractors and its the same problem)

**Relevant script mods**
Mods like Autodrive or VCA and so on.
I use Autodrive and CP, both latest version.
[log.TXT](https://github.com/Courseplay/Courseplay_FS22/files/10216546/log.TXT)

![FarmingSimulator2022Game 2022-12-13 10-39-25](https://user-images.githubusercontent.com/32069662/207284651-a9bd67b6-cf98-4d7e-9329-0121ce078e09.png)
![FarmingSimulator2022Game 2022-12-13 10-39-38](https://user-images.githubusercontent.com/32069662/207284668-a23daff9-bb2b-4acc-ae28-f0b6633842cd.png)
![FarmingSimulator2022Game 2022-12-13 10-39-55](https://user-images.githubusercontent.com/32069662/207284681-43f6bd83-6217-4cef-a322-6fb66b5790f6.png)
![FarmingSimulator2022Game 2022-12-13 10-40-06](https://user-images.githubusercontent.com/32069662/207284709-eb40923d-5ec3-47f2-82dd-eab108bf2ec4.png)
![FarmingSimulator2022Game 2022-12-13 10-40-20](https://user-images.githubusercontent.com/32069662/207284738-9c804b99-7650-4cd2-bad2-19efb389b252.png)
![FarmingSimulator2022Game 2022-12-13 10-40-39](https://user-images.githubusercontent.com/32069662/207284769-a764415d-3dc8-4451-84f8-dbf2c74f8f55.png)
![FarmingSimulator2022Game 2022-12-13 10-41-03](https://user-images.githubusercontent.com/32069662/207284802-2248bd4f-3f98-4b95-b107-5686c0e529d9.png)
![FarmingSimulator2022Game 2022-12-13 10-41-31](https://user-images.githubusercontent.com/32069662/207284829-8e89e4ac-1619-4d87-b923-6655590aaf5e.png)
![FarmingSimulator2022Game 2022-12-13 10-41-39](https://user-images.githubusercontent.com/32069662/207284860-0f09cc16-c5d4-4af0-8a7a-a7df9a64e5d5.png)
![FarmingSimulator2022Game 2022-12-13 10-42-07](https://user-images.githubusercontent.com/32069662/207284890-9c24e98e-bad4-46d1-8f53-e335983774ed.png)

**Comment by Tensuko** [comment]
This is a very strange bug.....
If that only happens with this mod windrower it should be a mod Issue.
I haven't heard of any other Tools that have this Problem, as many ppl sure send their Driver with AD to start fieldwork and so far never heard of this.

**Comment by bojanh66** [comment]
Yes, i know, i stopped using this mod windrower and back to the base-game windrower.
I was wondering why my worker doesnt windrow my grass fields, unless i come close or tab to the tractor, so after i inspected closely whats going on, here is the demonstration :)

**Comment by Tensuko** [comment]
So with basegame it is working normaly?

**Comment by bojanh66** [comment]
Yes, basegame windrower works perfect, never had an issue.
Only this Kuhn GA 9531 from Modhub is causing the described issue.

**Comment by bojanh66** [comment]
> Well then there is nothing we can do. Mod Issue.

Dear CP team, i want to inform you that i have encountered the same issue with this mod:
https://www.kingmods.net/en/fs22/mods/krone-swadro-tc-930

It is another 9.3 meters windrower and i was hoping it will work, but unfortunately, it has the same identical issue as the windrower mentioned in the 1st post.
Now i am wondering is this a coincidence or CP doesnt work with some specific windrowers ?
Anyway, i am using now only basegame default windrowers because they work without any issue, but i wanted to let you know, in case you want to investigate this issue later on, since its not high priority.
