### ISSUE TITLE
Elm Creek 4k edit map Course Play unable to generate fields

### ISSUE THREAD

**Issue by B9bot1** [Courseplay/Courseplay_FS22#2174]
Elm Creek 4k edit map Course Play unable to generate fields with version 1.0.0.4 of the map. Is there a fix or can Course Play be updated to be able to work with this map?

**Comment by regs1980** [comment]
A link to the map would already be helpful

**Comment by Tensuko** [comment]
We have a Template.
We need more informations.
What is unable to generate fields?
Why should it be a CP problem and not a problem of the map....

https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by B9bot1** [comment]
Link to the mapFS22_ElmCreekEditByStevie4x.zipdrive.google.comSent from my iPhoneOn Dec 14, 2022, at 12:53 PM, Tensuko ***@***.***> wrote:﻿
We have a Template.
We need more informations.
What is unable to generate fields?
Why should it be a CP problem and not a problem of the map....
https://github.com/Courseplay/Courseplay_FS22/wiki
