### ISSUE TITLE
[BUG_SP] Plow missing some area when starting new row

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#2175]
**Steps to reproduce**
Steps to reproduce the behavior.
Make a normal plowing course and worker will miss some spots when going from row to row.

It is quite similar to this issue:
https://github.com/Courseplay/Courseplay_FS22/issues/1544

**Actual behavior**
Worker miss some spots when going from row to row.

**Expected behavior**
Dont miss spots while plowing.

**Screenshots**
Screenshot added.

**Courseplay version**
Version used: latest version 7.1.2.4

**Log**
attached log with all debug channels.

**Map**
Old Stream Farm

**Vehicles/ implements involved**
Case puma and Kverneland Ecomat

**Relevant script mods**
I use Autodrive, but its irrelevant to the CP plowing.

![207716567-558c6f0d-f2bf-4ba2-8d4b-3aa5f7fbd1b6](https://user-images.githubusercontent.com/32069662/207864934-49558e7b-d866-4d7c-b0ed-446fadbe5c2b.png)
[log.TXT](https://github.com/Courseplay/Courseplay_FS22/files/10237142/log.TXT)

**Comment by pvaiko** [comment]
What are your turn settings? Turn on field, use pathfinder, etc.?

**Comment by bojanh66** [comment]
![Untitled](https://user-images.githubusercontent.com/32069662/208240429-bd2ec2ae-3217-41fc-86e7-60aa8a8b5134.jpg)
