### ISSUE TITLE
[BUG_SP] Lizard Underbelly Trailer: the unloader joins the wrong side

### ISSUE THREAD

**Issue by garo73** [Courseplay/Courseplay_FS22#2176]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Everytime if you select the single tank configuration.

**Actual behavior**
the unloader joins the wrong side.

**Expected behavior**
the unloader joins the right side.

**Screenshots**
![Senza nome](https://user-images.githubusercontent.com/25790192/208153211-176d1420-78fe-4b52-825b-e71184da818b.jpg)

**Courseplay version**
Version used: 7.1.2.4

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10247744/log.txt)

**Map**
All.

**Vehicles/ implements involved**
Lizard Underbelly Trailer: https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=239240&title=fs2022

**Relevant script mods**
nn.

**Comment by Tensuko** [comment]
Mod Issue.
See here:  #2067

**Comment by garo73** [comment]
Oh, sorry I haven`t see it... anyway, the modder have fixed it!
