### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by mechanicFS** [Courseplay/Courseplay_FS22#2182]
![fsScreen_2022_12_20_23_11_23](https://user-images.githubusercontent.com/76490045/208748452-3b373cd6-532b-4a2a-b0b1-f48ae18c7ab7.png)
Hello friend! With work in silos, Yana is not determined, writes: No silo was found.

**Comment by Tensuko** [comment]
Becouse you did not place the marker inside the blue lines.
Else they would light up white.
