### ISSUE TITLE
Fendt 1100 MT fährt im zickzack zum Startpunkt[BUG_SP]

### ISSUE THREAD

**Issue by HeavyMetal666** [Courseplay/Courseplay_FS22#2185]
**Steps to reproduce**
Der Fendt 1100 MT fährt wenn er von AD oder manuel gestartet wird und der Startpunkt weiter entfernt ist in Zick Zack quer übers Feld.

**Screenshots**
![fsScreen_2022_12_10_01_37_22](https://user-images.githubusercontent.com/109442353/208951145-cc948fac-dc83-4805-8c70-ac716f828b20.png)
![fsScreen_2022_12_21_16_54_04](https://user-images.githubusercontent.com/109442353/208951267-b801096d-5e45-4093-95b3-c740591b411c.png)

**Courseplay version**
Version 7.1.2.4

**Map**
Elmcreek konnte aber auch auf anderen Maps reproduziert werden

**Vehicles/ implements involved**
Fendt MT 1100 MT und Väderstad NZ Extreme 1425 Vanilla

**Comment by Tensuko** [comment]
Duplicate #1622
