### ISSUE TITLE
CP fährt langsam auf dem feld

### ISSUE THREAD

**Issue by JimmyBeam1990** [Courseplay/Courseplay_FS22#2186]
Moin, 

ich habe nun echt viel google und yt befragt und bin leider nicht auf mein Problem gestoßen..
Bei mir ist es so, ich lasse Gras für die BGA über AD 2.0.0.9 und CP 7.1.0.3 abfahren und ins Silo bringen. Soweit klappt das auch, allerdings ist das Problem, wenn der abfahrer seinen Ladewagen voll hat, fährt er nur noch 1-2 kmh. 

Hat da jemand eine Lösung für?? Oder ist es ein Bug?

**Comment by Tensuko** [comment]
Wenn der Ladewagen voll ist, fährt AD und nicht CP.
Da musst du dann dort mal fragen.
Und hier bei uns entweder Question benutzen oder das Template ausfüllen.

**Comment by JimmyBeam1990** [comment]
Da CP den Kurs weiter fährt, bis zum Ende, und "Play"Button von CP noch grün ist, gehe ich davon aus, dass es CP ist, welches das Problem verursacht?

**Comment by Tensuko** [comment]
CP sollte nicht fahren wenn der wagen voll ist.
Wenn dem so ist, stimmt bei dir etwas nicht.
Ligfile und screenshots bitte.

**Comment by JimmyBeam1990** [comment]
https://prnt.sc/VFyBl9ebCO5n
https://prnt.sc/f0M_CON_ISaZ
https://prnt.sc/TA7Q2zkkmtNx
https://prnt.sc/suXnuLChljbP
https://prnt.sc/Q-zNiHmVPIIO
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10286956/log.txt)

**Comment by Tensuko** [comment]
Auf jeden Fall updaten:
(Version: 7.1.0.3) FS22_Courseplay

https://github.com/Courseplay/Courseplay_FS22/releases

Und bei mir ist der Ladewagen wenn voll wie gewollt angehalten und von AD übernommen worden:
![fsScreen_2022_12_22_14_16_35](https://user-images.githubusercontent.com/27344744/209142483-6163b39a-2323-4b30-98e1-aa615c1e341c.png)
![fsScreen_2022_12_22_14_17_44](https://user-images.githubusercontent.com/27344744/209142554-df768666-d14a-46ae-98f4-a269f01d5590.png)

**Comment by rohne83** [comment]
Möglicherweise irgendein Modkonflikt? Gras aufbereitet kommt meines Wissens von MaizePlus, und auffällig ist auch die Kapazität: Ladewagen kann 56k mitnehmen, tatsächlich in der fillUnit sind aber 149l zusätzlich. Möglicherweise lenkt das den Algorithmus in die falsche Richtung?

**Comment by Tensuko** [comment]
Behaupte es ist die alte Version. Ich hab auch M+aktiv.

**Comment by Tensuko** [comment]
mache hier zu wegen inaktivität
