### ISSUE TITLE
[BUG_SP] Xerion Saddletrack not recognising trailer

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/Courseplay_FS22#2194]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Creating y course for Xerion Saddletrack
Use a Xerion Saddletrack wit trailer not with tank

**Actual behavior**
In combination with Autodrive the Xerion behave like its has a tank mounted and not a trailer attached. 
the Xerion often try to reverse, not considering there is a trailer attached to it, and jackknife.
This happens when the Xerion comes from refilling with autodrive and want to go to the last position on the field. 
The Xerion often reverse even it could just go straight ahead. 
on turning manouvers the Xerion also reverse even pathfinder and pathfinder reverse is disabled. 

**Expected behavior**
If the Kaweko TRrailer is attached,m instead of the Kaweko tank the  Xerion Saddletrack should notice the trailer should reverse like a usual tracktor with trailer attached. . 

**Screenshots**

**Courseplay version**
Version used: latest 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Multimap

**Vehicles/ implements involved**
Xerion Saddletrack
Kaweko manure Trailer for SaddleTrack

Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by rohne83** [comment]
Have you turned off reversing for pathfinder in basic CP settings? Could reproduce reversing with jackknifing from time to time for ST with this trailer, but only as long as that setting was activated.
If that doesn't solve your problem, I think Tensuko might need more info (what are your CP settings, maybe screenshots of specific situation with activated vehicle debug, logfile might also help). Maybe the noReverse option should be added for this trailer to vehicleConfigurations?

**Comment by MADxHAWK** [comment]
Merry Christmas everyone, 

@rohne83 
I have tried different settings, Pathfinder on / off, Pathfinder no revers of/off in all combinations. 
What i have noticed, with the Kaweko tank directly mounted on the SaddleTrack there are no problems. 
With every other Tractor / Trailer implement, no problems when reversing,
Just with the SaddleTrack and the Kaweko Trailer i have problems. 
From what is observed, the Saddletrack reverse like there is the Tank mounted on it. 
So ill guess Coursplay cant differ between the Kaweko mounted tank and the Kaweko Trailer, coursplay threats both the same, as a mounted tank. 
Ill guess it would just be enough to detect the trailer as trailer and not as a mounted tank on the saddletrack.

**Comment by Tensuko** [comment]
It is not like we decide how we detect something, rather then what is set in the xml....

**Comment by Tensuko** [comment]
Okay, I found the problem.

**Comment by Tensuko** [comment]
But I also found the solution and that is to disable the allow pathfinder reverse option.
![fsScreen_2022_12_28_20_42_31](https://user-images.githubusercontent.com/27344744/209864231-054bfe82-3755-46a0-8431-a69ae867d4ac.png)

![grafik](https://user-images.githubusercontent.com/27344744/209864301-aa6395f1-299b-466b-966a-b6dcc2e81e30.png)

**Comment by Tensuko** [comment]
found another way, fixed in 7.1.2.5
