### ISSUE TITLE
[BUG_SP]Mit Ladewagen oder Sämaschine nach übergabe von Autodrive: Courseplay beginnt immer am ersten Wegpunkt

### ISSUE THREAD

**Issue by TheCapnLP** [Courseplay/Courseplay_FS22#2199]
Ich habe seid einigen Wochen ein Problem mit der Übergabe von AD an CP.
Folgendes Szenario. Es soll ein Feld mit einer Sämaschine bearbeitet werden. AD fährt zum Feld und soll an CP übergeben und beginnt am ersten Wegpunkt. Das klappt alles prima.
Irgendwann ist die Sämaschine leer. Das merkt CP und übergibt wieder an AD. AD füllt dann das Saatgut/Dünger auf und fährt wieder zum Feld. Eigentlich sollte CP dann wieder da anfangen, wo die Sämaschine leerging. Das macht es aber nicht. Dafür wird wieder am ersten Wegpunkt gestartet und von vorne begonnen.
Egal ob ich Erster/letzter oder nahester Wegpunkt anwähle, alle Optionen fangen wieder bei Wegpunkt 1 an.

Dasselbe kann auch mit einem Ladewagen reproduziert werden.

Wie ich auch gesehen habe, soll dieser Bug seid Version 7.1.1.5 behoben worden sein. Bei mir wohl nicht.

**Courseplay version**
7.1.2.4                        

**Autodrive Version**
2.0.0.9

![20221226082543_1](https://user-images.githubusercontent.com/121421754/209519389-3e92f5af-6ce8-40fa-a299-985a49c1d74f.jpg)

**Comment by Tensuko** [comment]
Savegame einmal ohne CP laden und speichern.
Dann wieder mit CP laden.

Der bug ist gefixt, er kann bei anderen nicht nicht gefixt sein.
Wenn dann ist da ein Problem und die Lösung habe ich dir jetzt genannr :)
