### ISSUE TITLE
[BUG_SP]  Viele Probleme mit CP Version 7.1.2.4

### ISSUE THREAD

**Issue by ramsesAT** [Courseplay/Courseplay_FS22#2203]
**Courseplay version**
Version used: 7.1.2.4 (now 7.1.1.5, without problems)

**Map**
Haut Beyleron

**Relevant script mods**
AD 2.0.0.9, VCA 1.2.0.0, Gamesaver 1.0.0.0, FieldCalculator 1.1.0.0, SimpleInspector 1.0.1.10, Easy Development Controls 1.3.0.2, Info Display Extension 1.5.0.0, Better Contracts 1.2.6.2, ContractHUD 1.2.1.0, Click to Switch 1.0.0.2, Additional Game Settings 1.1.0.0 etc...

**Steps to reproduce**
I dont know, Version 7.1.2.4 install again? no thx 

**Vehicles/ implements involved**
Various, most moddet (i use Elektro or Methan Vehicles. zb. Mod FSG Electric Tractor Pack) without problems

1-1.) Activated CP Version 7.1.2.4 (26.12.22 10:00 AM)
then

1 Hours later in the Game
1-2.) i could not generate a course at field no. 08. ok is small i do it manuel (mission). may have always been like this, first time had created a course with CP at field 08
here I already thought that the new version (CP) makes mistakes but I can live with the small field. and is also a NPC field
I could set field point and make settings but then I could not generate the course.
in the error message it said, see LOG.txt (no i dont have this log.txt)

4 hours later... its summer june
2.) with 2 combines harvester (Mähdrescher) in the network, the 2nd combine harvester started with AD and drove the middle lane, instead of taking the right lane. Field 26
CP off/on solved the problem and it switched to the right lane. not a problem for me, i start after that all harvester without AD.
finish the field without problems..

20 min later (5-6 vehicles drives wiht CP on fields, at this time)
3.) when autosave (mod), at that moment, the game crashed (1st time) or it froze. game newstart und I then turned off the mod autosave. I had read before here on Github that someone had a problem with it.

30min later
4.) when creating a new course at field 31 the game crashed. 2 times in a row.
but it could have been a coincidence

then i replaced CP version 7.1.2.4 with version 7.1.1.5 again.

I am streaming and unfortunately had no time that day to save the Log.txt file or take screenshots.

I had so many problems at 6-8 hours of play from the time I used the New Version 7.1.2.4 and that while streaming. I just quickly installed the old version back into the mod folder an reboot the pc.
**Play now again without problems**, even the mod autosave I have enabled again.

I never had crashes in the game before. my log.txt has no errors but 4-5 warnings. 
4-5 warnings because of mission vehicles which are missing. not important.

Translated with www.DeepL.com

Ich kann leider nicht mehr dazu sagen oder was daran Schuld war. **Ich weis nur das ich jetzt keine Probleme mehr habe, nachdem ich wieder CP version 7.1.1.5 verwende.** 
Kann natürlich alles auch Zufall sein, ICH habe keine Ahnung...
Ich kenne mich nicht sehr gut aus und möchte das auch nicht testhalber wieder mit Version 7.1.2.4 versuchen aber die Info wollte ich Ihnen geben, auch wenn es nicht sehr genau ist (fehlende Screenshot und Log.txt vom 26.12.).

greeds Ramses@Robert

ps. sorry the mix of languages, my english are not the best.

**Comment by Tensuko** [comment]
why no logfile?

**Comment by Tensuko** [comment]
> Ich kenne mich nicht sehr gut aus und möchte das auch nicht testhalber wieder mit Version 7.1.2.4 versuchen aber die Info wollte

Na dann kann ich hier ja auch zu machen.

**Comment by ramsesAT** [comment]
hallo tensoku,
ja von mir aus schon, wenn es keinen anderen interessiert? ich weiss nur nicht ob sich das problem zb. keinen kurs bei feld 08 zu erstellen zu können löst, wenn es nur mich betrifft ist´s egal (errors oder warnings deswegen waren ja keine in der log.). mit der jetzigen version 7.1.1.5 gehts es nämlich einen kurs zu erstellen bei dem zwergen feld 08. das müsste ja sicher n versions problem sein und die ganzen anderen probleme sind ja auch mit der alten version nicht mehr da. wegen der Drescher und Falsche spur hab ich nicht gekuckt mit "meiner" version.  ich hab 170 Stunden auf der Map und das ohne probleme. erst bis ich 7.1.2.4 "installierte" fing es an. find das auch nicht gerade ne kleinigkeit. es tut mir leid wegen der log.txt. ich war am streamen da kann ich nicht lang was anderes machen. wollt die Log.txt später auslesen. Das dann das spiel zum einfrieren anfängt und ich ohne zu viel nachzudenken das spiel neustartete, da war die log. natürlich weg.

**ich hab gesehen du bist auch auf DC Autodrive. wir können gerne reden wenn es hilft, n problem zu lösen.** wenn die angesprochenen probleme nur ich hab, wie du schon sagtes, kannst du zu machen. ich hab mit der version die ich jetzt verwende kein problem. 7.1.2.4 werd ich sicher nicht nochmals draufmachen. da hab ich viel zu viel schiss das mir nochmals alles abkackt und problem über problem erscheint.

ich wollt auch nicht stören und um hilfe rufen wegen kleinigkeiten... und wenn meine log.txt voller errors wegen def. mod wären, würd ich auch meinen mund halten, wollte nur schreiben was ich mit der version 7.1.2.4 erlebt habe am 26.12.
greeds Robert

ps. danke für deine/eure schnelle reaktion. find das voll klasse wie schnell ihr immer helft, allgemein.

**Comment by Tensuko** [comment]
Naja du sörst ja nicht, nur ist das alles etwas durcheinander ehrlich gesagt.
Ich weis jetzt z.B. nicht was du mit feld 08 meinst, welche Map, was für Fahrzeuge etc etc.
Wenn du richtig ein Problem mit einer Sache hast, fülle doch bitte das Template aus, auch gerne auf deutsch.
Oder AD GitHub auch gerne, aber so ist es mir unmöglich zu helfen....

**Comment by ramsesAT** [comment]
Servus Tensuko,
welche Map hab ich ja gepostet, 1. Post ganz oben. Dachte dadurch wird ja klar sein wo Feld 08 ist.
**Map**
Haut Beyleron

Von diesem Template, welches ich ja verwendet habe,  siehe wieder 1. Post hab ich so viel ausgefüllt wie mir möglich ist/war. Rest hab ich gelöscht. 

Welche Fahrzeuge hab ich auch geschrieben. Es waren verschiedene, meisten natürlich gemoddet. Ich verwende nur Mod welche ich vorher getestet habe bzw. welche von Spielern zb. FedAction oder Holger auch verwendet werden und keine Errors bzw. Warnings verursachen in der LOG. Egal sonst von wem, die kommt wieder runter. Mehr kann ich selbst nicht überprüfen in so ner Log.txt

Auch hab ich geschrieben das ich, wo es halt möglich ist, eTraktoren, eDrescher etc. verwende. auch da hab ich die Mod gepostet.
die Mod ist nur 0,7mb groß, denk die verändert nur bei gewissen Fahrzeugen einige Datein. Aber keine Ahnung dafür bin ich zu unwissend. ^^
eClaas 8000er Serie bei Drescher zb.
und ein paar Traktoren die Vanilla Daten haben bis auf Sound und statt Diesel halt Strom verwenden.
Sind nur 5 Traktoren und 2 Drescher (Drescher sind Baugleich)
Da ja alles mit der alten CP Version problemlos funktioniert hat und es ja immer noch tut, schon ein paar Saisonen lang und so viele kleine Probleme - auf einmal - aufgetaucht sind bzw. bei verwendung von der neuen CP Version, schreib ich das mal Pauschal "mit mehreren Fahrzeugen bei:

**Vehicles/ implements involved**
Various, most moddet (i use Elektro or Methan Vehicles. zb. Mod FSG Electric Tractor Pack) without problems.

Alles genau zu be/schreiben was an dem Tag mit CP alles seltsames passiert ist, da schreib ich nen Roman - was ich ja jetzt schon tu. Das lässt sich anders besser erklären.
Ich kenne CP nur so das es nie Probleme macht, da hab ich mit AD mehr Probleme beim abfahren zb. Deswegen war ich auch so verwundert. Probleme beim verwenden von CP hatte ich nie oder ich passe mich an CP an. Mir ist schon komisch vorgekommen das Autosave, wenn viele CP Kurse aktiv waren Extrem ruckelte, Lags verursachte, bis zum einfrieren vom Spiel. Das ich keinen Kurs erstellen kann, ein Fenster von CP aufpoppt ich soll mal für mehr Info in die Log.txt schaun, hatte ich nicht mal Ls17. Ich hab in die Log gekuckt aber nur nach Errors und Warnings. Da war nichts. Nur n Haufen Daten welche CP erstellt wegen der Länge, der Breite, etc. von Fahrzeugen/Anbaugeräten für Feld 08. Wie schon erwähnt, wollt ich euch das später zukommen lassen. Das im laufe des Tages immer mehr seltsame Dinge mit CP passierten, wusste ich zu dem Zeitpunkt ja nicht.

Schluss für mich war, als ich bei Feld 31 einen Kurs mit CP erstellen wollte und 2 mal das Spiel eingefrohren ist und das während dem streamen. Geht mal gar nicht n Spiel das Pausenlos einfriert wenn ich nur n Kurs für das Feld erstellen will und das im Stream. 
Kann natürlich sein das während des Stream irgendwelche Updates downgeloadet wurden, dann noch CP das rumspinnt es vielleicht dadurch zu Problemen gekommen ist. Zu dem Zeitpunkt hatte ich im Stream auch Probleme mit den Frames viele Ausgelassene bzw. Übersprungene. Hab ich aber beim erstellen des Bug Reports erwähnt. Kann auch Zufall sein, hatte ich geschrieben. Bei LS ist ja alles möglich.

Aber selbst mir war klar das die neueste Version bei mir Probleme macht. Ich hab die CP Version getauscht und ab da funktioniert wieder alles. 

Das witzige daran ist, ich hab bei der neuen CP Version vorher gelesen was gefix worden ist und genau so ein Problem taucht auf einmal bei mir auf? "Falsche Spur im Netzwerk mit 2 Fahrzeugen - Mitte statt Rechts in verbindung mit AD. (nein hab es nicht nochmals versucht zu reproduzieren... ich war im Stream.

Andere finden 1 Problem. Ich hatte gleich mehrere und das an einem Tag. Wie das beschreiben ohne Log.txt, dachte es ist aber wichtig euch dennoch zu informieren, auch ohne Log.txt   ...JaJa ich weiß das es das Wichtigste ist. Dennoch, euch nicht zu informieren war keine Option bei der Menge an "Problemen" bei mir mit 7.1.2.4. 
Besser bisschen Hilfe, als gar keine, dacht ich zumindest.

So jetzt hör ich aber auf, wiederhole mich ja eh schon ganze Zeit. Sorry das schon wieder so viel worden ist....
...und wegen Fehler reproduzieren. Bin 54 und hab vom Skripten oder Fehlersuche etc. wenig Ahnung. Ich versteh recht schnell aber hab mich nie befasst damit.
 Ich hab die letzten Wochen so viel selber getestet um auch nicht mit fehlerhaften Mod zu spielen. Nach Wochen testen und Neustart der Map, mein Erstes richtiges Spiel das ich begonnen habe. Ich will nur in ruhe mal LS22 zocken. 

Das AD mit CP inzwischen Probleme auf dem Feld selber löst ist super aber keine Option für mich, zu viel Zeitverlust. Spiele erst wieder seit ein paar Monaten/Wochen, zuletzt vor 4 jahren LS17. Mir ist noch nicht langweilig genug um auf Fehlersuche zu gehn. Ich will nur in ruhe mal LS22 zocken.
Greeds....
