### ISSUE TITLE
[BUG_SP] lost minihub

### ISSUE THREAD

**Issue by matty2123** [Courseplay/Courseplay_FS22#2205]
As per title was playing had a problem now lost my minihub. If I pressed my left mouse button it would appear now nothing! Pressing delete makes a blinking bit on the right. Nothing in log

**Comment by Tensuko** [comment]
I can't help you like that.
Logfile, screenshot, what about gamepad friendly hud setting ?
etc.....

**Comment by matty2123** [comment]
Close fixed
