### ISSUE TITLE
[BUG_SP] Helper leaves the generated course.

### ISSUE THREAD

**Issue by hitman1812** [Courseplay/Courseplay_FS22#221]
I generate a course and let courseplay start it. During the work with courseplay the helper leaves the generated course and drives in any direction. Happens almost everytime i use courseplay in my savegame.

**Courseplay version**
Version used: 7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7786706/log.txt)

Thats the error message from the log: 

2021-12-29 00:09 Error: Running LUA method 'update'.
C:/Users/xxx1/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/CourseGenerator.lua:230: bad argument #1 to 'ipairs' (table expected, got nil)

**Map**
Haut-Beyleron

**Comment by Corran1327** [comment]
> 2021-12-29 00:09 Error: Running LUA method 'update'. <is this courseplay? 
[#118 ]"
@hitman1812  check for and remove  questionable other mods including " Simdashboard, Freelabour, GPS" all interact with your drivers heading or pay if this fixes the issue I saw this issue and thought of my own problems immediately previous versions of CP, AD, and Free labor (if you have the mod hub version of Free labor it has a conflict with CP)

**Comment by pvaiko** [comment]
Can someone please turn on Debug in the vehicle settings and run this again with 7.0.0.10 (or if you know how to do it, on the latest main branch commit) and post the log?

**Comment by Corran1327** [comment]
Without the original user input on the new version I can try reinstall the mods I mentioned and see if that reproduce the problem I'll post results probably sometime tomorrow

**Comment by hitman1812** [comment]
Sorry for the late reply, but i have been busy with other stuff.
i tried it with version 7.0.0.11 again and with same mods as before.
After generating the course again the helper did the job as planned. 
the log had no errors.
So i hope the bug is solved, but i will retry this again during my next times playing

**Comment by Corran1327** [comment]
So far nothing in the log or reproducible errors so it seems to have been fixed
