### ISSUE TITLE
[BUG_SP] Problem with text 

### ISSUE THREAD

**Issue by michal3110** [Courseplay/Courseplay_FS22#2211]
Hello, in last version have problem with text, I send screen 

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10319580/log.txt)
![Farming-Simulator-22-Screenshot-2022 12 29---14 00 27](https://user-images.githubusercontent.com/97218328/209954900-888af110-368a-4f0e-ac00-75f1915d8766.jpg)

**Comment by Tensuko** [comment]
Oh, will have a look whats wrong.

**Comment by Tensuko** [comment]
Pls redownload the latest Version, I replaced the .zip with the fixed files.
Tested your language and it worked for me.

**Comment by michal3110** [comment]
yes, its fix :) thanks
