### ISSUE TITLE
Kursberechnung Vorgewende

### ISSUE THREAD

**Issue by rellek82** [Courseplay/Courseplay_FS22#2222]
Wird es irgendwann wieder eine Kursberechnung des Vorgewendes geben, wie es schonmal in CP für LS19 gab?
Ich würde mir die Vorgewende NUR an den Kopfenden der Felder wünschen und nicht um den kompletten Feldrand.

Das Bild stammt leider nicht von mir, soll aber meine Vorstellung veranschaulichen.

![103298613-0259f180-49fb-11eb-83e0-0d6011e83eba](https://user-images.githubusercontent.com/57573110/210133792-a5700ae3-9572-43fd-a7b9-3d865ea198c2.jpg)

**Comment by Tensuko** [comment]
Das ist "narrow field" oder "enges feld".
Ja das wird bestimmt wieder rein kommen, aber kann nicht sagen wann.

**Comment by rellek82** [comment]
Danke für die Infos.
