### ISSUE TITLE
[BUG_MP] Mulcher Anfahrt zum Feld mit Übergabe macht Probleme

### ISSUE THREAD

**Issue by timmi4026** [Courseplay/Courseplay_FS22#2223]
Moin, habe vor 1 Std die neue Version 7.1.2.5 aufgespielt und wollte einen Mulcher mit AD zum Feld schicken, der dann bei Ankunft an CP übergibt. Als CP übernommen hat ist folgendes passiert. Er hat am ersten Wegpunkt gestartet und fuhr aus dem Feld hinaus und dann quer drüber. Bild anbei. Dann hat er seine Arbeit abgebrochen.
![Screenshot_48](https://user-images.githubusercontent.com/46847594/210167097-6932196a-248f-4621-97bb-2a40b19c83b9.png)

Nachtrag: Hab es mit der 7.1.2.4 versucht, das selbe Ergebnis, kann das was mit der Schneeplane zu tun haben ?
Nachtrag 2: Es liegt an der Schneeplane, hab vorgespult bis Winter weg war, dann geht es wieder wie es soll.
Ich lass das hier mal drin, falls es tatsächlich ein Bug ist.

**Comment by Tensuko** [comment]
Liegt nicht an CP und ohne logfile geht sowieso nichts.
