### ISSUE TITLE
Combines running folded

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#2224]
Hello guys,

with latest 1.2.5. version my combines running folded. When stop and unfold them they will immedietely fold again when CP is switched on. Vanilla Claas Lexion and modhub JD. Switching back to 1.2.4 is fixing the problem. 

 
![20230101113519_1](https://user-images.githubusercontent.com/33344465/210168106-4d2e06ba-f266-4300-a2cf-f605fe268345.jpg)

![20230101113524_1](https://user-images.githubusercontent.com/33344465/210168107-db79c4b6-35bf-4646-9bc5-fb90694803c8.jpg)

![20230101113933_1](https://user-images.githubusercontent.com/33344465/210168109-680a3edc-0e81-4b47-904d-d36f1390cd68.jpg)

**Comment by manne70** [comment]
Ich habe das selbe festgestellt, das gefaltete Rohr und der Korntank gehen nicht auf. Beim entlehren bleibt das Rohr dann am Abfahrer hängen.

**Comment by Tensuko** [comment]
Will push a hotfix later.

**Comment by Tensuko** [comment]
Should be fixed with 7.1.2.6
