### ISSUE TITLE
langes Rohr des Dreschers ist während Abladen abgeknickt

### ISSUE THREAD

**Issue by Kniescheibe04** [Courseplay/Courseplay_FS22#2227]
Hallo und frohes neues Jahr, meine Frage: Warum ist beim Drescher mit langem Rohr während des Abladens das Rohr nicht vollständig ausgefahren. Es ist abgeknickt, sodass der Drescher nicht abgeladen werden kann.

**Comment by rohne83** [comment]
Mit welcher Version denn? Bei 7.1.2.5 gabs ein Problem diesbezüglich, das mit 7.1.2.6 nen Hotfix bekommen hat.

**Comment by Tensuko** [comment]
Ist behoben mit 7.1.2.6
