### ISSUE TITLE
[Enhancement] Gregoire Besson Prima Pack - use front plows as well (if attached) to get the correct offset

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS22#2228]
Hier im Link kann man geschobene und gezogene Pflüge herunter laden.

[Gregoire Besson Prima Pack](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=260901&title=fs2022)

![screenshot1](https://user-images.githubusercontent.com/35263980/210246194-9182adcd-048a-4fd5-8abf-4c93d96a4e98.jpg)
![screenshot2](https://user-images.githubusercontent.com/35263980/210246210-2f47c673-2055-48a2-b23e-be57bbfec964.jpg)
![screenshot3](https://user-images.githubusercontent.com/35263980/210246225-548895c6-b48f-45ff-92ad-649ccc07479d.jpg)

So richtig bekomme ich CP leider nicht eingestellt, dass der vordere und der hintere Pflug in die Arbeitsbreite eingebunden ist. Kann man das eventuell in CP einbauen, dass es funktioniert? Diese Arbeitsweise ist im realen nicht unüblich.
Man könnte über den Schalter 'Arbeitsbreite' die beiden Pflüge anpassen, leider kann man keinen Versatz in CP einstellen.

**Comment by Tensuko** [comment]
Kann ich mir die Tage mal angucken

**Comment by Tensuko** [comment]
They do turn and everything, but on headland its a problem.
Also the next row doesnt fit like that it just settles after the start but that can be looked at later.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10346745/log.txt)
![fsScreen_2023_01_04_19_50_00](https://user-images.githubusercontent.com/27344744/210628481-1a9ce688-73cf-4e8e-abff-98ac1d2c7ee7.png)

**Comment by franky-bb** [comment]
Wie auf deinem Bild zu sehen, wird die Arbeitsbreite über den gezogenen Pflug bestimmt und der Versatz berechnet. Habe es eben getestet, es funktioniert. Damit es funktioniert, ist es wichtig, eine bestimmte Reihenfolge beim Ankuppeln einzuhalten. Erst der gezogene dann der an der Front. Spät anheben und früh absenkem, ist die beste Option.

**Comment by AN-Vyper007** [comment]
Entschuldigung für den Offtopic:
@Tensuko Wie heißt der Mod, der den/die Helfer so schön über der Minimap anzeigt? Hab beim Recherchieren leider nichts gefunden!

**Comment by Tensuko** [comment]
Also die Arbeitsbreite ja, aber der Offset passt noch nicht ganz.
