### ISSUE TITLE
[BUG_SP] Bunkersilo - isStuck and hasNearbyUnloader

### ISSUE THREAD

**Issue by PhiSch19** [Courseplay/Courseplay_FS22#2231]
**Steps to reproduce**
Fill the Bunker with enough grass so the CP-driver get stuck and drive with an unloader inside the unloading zone.

**Actual behavior**
The CP-Bunker-Driver gets stuck and don‘t drive backwards. Wheels spinning forward the whole time.

**Expected behavior**
If CP-Bunker-Driver gets stuck the driver drive backwards (same behavior as without the unloader).

**Courseplay version**
7.1.2.4

**Map**
Haut Beyleron

**Vehicles/ implements involved**
Which vehicle or implement? Fendt 1050 & MES 500
Mod yes/no ? No

**Relevant script mods**
Autodrive (Unloader)

**Comment by PhiSch19** [comment]
I think it has something to do with the Check AIDriveStrategyBunkerSilo:isTemporaryOutOfSiloDrivingAllowed as there is a not self.siloDriver:hasNearbyUnloader() in line 257. I didn‘t test what happens when you delete this line.

**Comment by Tensuko** [comment]
Actually not.
It should be allowed to drive to park position when unloader is near and is stuck.
If you allow a temporary out of silo with unloader near, thats not what we intended to do.

**Comment by PhiSch19** [comment]
Another possible fix i thought about is in AIDriveStrategyBunkerSilo:setAllStaticParameters() in the isStuckTimer Callback function.

There could be a fix with another if clause, but there I have to less knowledge about FS-Modding and Courseplay.
But something like another check if unloader is near then startDrivingOutOfSilo(). I renewed the PR with this idea, but I think it will need a rework from someone of the CP-team.

**Comment by Tensuko** [comment]
Can you try out the PR from @schwiti6190 ?
#2233

**Comment by PhiSch19** [comment]
I saw it already, I'm currently in the setup phase for a clean test, as I didn't backup my savegame and progressed already, I think I will need 1-2 hours for it.

**Comment by Tensuko** [comment]
Will be part of modHub Update.
