### ISSUE TITLE
[Question] CoursePlay latest version not pushed to Modhub

### ISSUE THREAD

**Issue by IonutDanNica** [Courseplay/Courseplay_FS22#2236]
Hi,

I noticed on modhub an older version of Courseplay is available, is this intended?
I think I just had my game downgrade courseplay, and didn't notice until some feature like estimated completion time were no longer showing.

thanks,
ionut

**Comment by Tensuko** [comment]
If you "update" ingame you get the modhub version and yes that is intended.
A modhub update is in preperation, so have some patience pls.
