### ISSUE TITLE
[BUG_SP] Collect and deliver always stars from the 1st course point after unloading

### ISSUE THREAD

**Issue by edvanbol** [Courseplay/Courseplay_FS22#2237]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course with "collect and deliver" (in my video case it is collecting grass and delivery to silo bunker) or "work and fill" (for example work on field 9, fill manure at manure heap") in AutoDrive. Start from the 1st waypoint. Once the wagon is filled with grass it will unload in silo bunker, then goes to Field AutoDrive point and then goes to 1st waypoint and starts again from beginning

**Actual behavior**
Once the wagon is filled with grass it will unload in silo bunker, then goes to Field AutoDrive point and then goes to 1st waypoint and starts again from beginning despite the "last waypoint" or "closest waypoint" are active

**Expected behavior**
Once the wagon is filled with grass it will unload in silo bunker, then goes to Field AutoDrive point and then goes the last waypoint it was filled up and continues job

**Screenshots**
Actually i don't now how to show it by screenshots, so i've uploaded a video on youtube https://youtu.be/q9YIEbRX0Mo

**Courseplay version**
Version used: 7.1.2.6

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10367101/log.txt)

**Map**
Wild West

**Vehicles/ implements involved**
Claas Axion 870, Claas Cargos
Mod yes/no ? No

**Relevant script mods**
Just CoursePlay, AutoDrive. No other scripts relevant to automation or vehicle control used in that case

**Comment by Tensuko** [comment]
I heard that too but the solution was to start the savegame once without CP and save it, then add CP back in.
From that time on it seems to work again.
It might be that at some Version some setting got stuck and needs this reset.

**Comment by edvanbol** [comment]
Yes, it helped for 100%! Thank you guys for your amazing job! @Tensuko
