### ISSUE TITLE
[BUG_SP] Courseplay harvester closes pipe when tractor passes discharge point

### ISSUE THREAD

**Issue by OddBloke** [Courseplay/Courseplay_FS22#2238]
**Steps to reproduce**

1. Install the "Claas Lexion 600-700 Series From 2012-2015" mod from ModHub
2. Start harvesting with the Lexion 770 with the 8.8m pipe
3. Drive a MF3670 tractor towing a Claas CARAT 140 TD trailer behind the harvester and observe it open the pipe
4. Drive the MF3670 under and past the pipe

**Actual behavior**

The pipe closes as soon as the tractor unit passes the pipe, meaning the trailer is not filled.

* This happens both when driving the tractor manually and when Courseplay is on empty harvester mode.
* The trailer does fill correctly when the harvester is under manual control.
* The pipe does not open at all if the tractor is not towing the trailer.

**Expected behavior**

The pipe remains open and fills the trailer.

**Screenshots**

These screenshots are from before/after moving the tractor past the discharge point of the harvester (which we can see appears to be calculated correctly):
![Farming Simulator 22 07_01_2023 16_59_35](https://user-images.githubusercontent.com/62736/211172039-ed13b456-4b29-4b16-9d83-fee0386f74fc.png)
![Farming Simulator 22 07_01_2023 16_59_44](https://user-images.githubusercontent.com/62736/211172048-ee9846f9-02ab-4f57-8e9a-2404c2b1cf03.png)

**Courseplay version**
Version used: 7.1.2.6

(Also observed on 7.1.0.3.)

**Log**

https://gist.github.com/OddBloke/19d3d9517ca6f6bd8f64fe68000d25a2

**Map**
Attingham Park (latest ModHub version)

**Vehicles/ implements involved**
Which vehicle or implement?
* Harvester: Claas Lexion 770 (from "Claas Lexion 600-700 Series From 2012-2015")
* Tractor: MF3670
* Trailer: Claas CARAT 140 TD
Mod yes/no ?
Harvester is a mod, the tractor and trailer are base content.

**Relevant script mods**
None AFAIK.

**Comment by Tensuko** [comment]
From where is that Harvester?
High doubt it is a CP Issue.
There is an Area next to the Harvester where he opens the pipe when a driver is near, that can be shown with F5.
Guess it is just too small.

**Comment by Tensuko** [comment]
As expected, mod Issue.
That area is totaly wrong.... Wonder why Giants didn't see that.
![fsScreen_2023_01_07_23_40_06](https://user-images.githubusercontent.com/27344744/211172957-20411e4c-f1d0-4851-89c2-d942e6d3676c.png)

Compared to a Vanilla Lexion how it should look like:
![fsScreen_2023_01_07_23_40_19](https://user-images.githubusercontent.com/27344744/211172981-9da39698-0900-4d7e-8b52-613fff143788.png)

**Comment by OddBloke** [comment]
Thanks for the quick response!

> From where is that Harvester?

It's a mod I installed from Modhub, "Claas Lexion 600-700 Series From 2012-2015".

> High doubt it is a CP Issue.
> There is an Area next to the Harvester where he opens the pipe when a driver is near, that can be shown with F5.
> Guess it is just too small.

Pressing F5 doesn't do anything in my game: do I need to install another mod to see this?

**Comment by OddBloke** [comment]
Aha, I see: thanks for the debugging, I'll switch to another harvester!

**Comment by Tensuko** [comment]
For F5 to work, you need to activate the ingame console. Not sure if I activated more but google should tell you how to.
