### ISSUE TITLE
[Feature] Allow dynamic update of Tool offset Horizontal, now it's grayed out 

### ISSUE THREAD

**Issue by Vaupell** [Courseplay/Courseplay_FS22#2244]
**What is the problem this feature/enhancement solves?**
Many tools has the wrong offset, and i am unable to change it. enabling advanced settings also is not enabled. 
Example right now i have a Deutch 8280 TTV with a John Deer 670 ripper, and the offset should be 0m,  but it's 1.3m, meaning it's always off, i am unable to change this, for unknown reasons?

- unable to disable "auto"  :( 

**Describe the solution you'd like**
enable the menu, to let me/us adjust the offset ingame while playing without having to edit xml files.

**Describe alternatives you've considered**
using the ingame helper is doing a better job on "up down rows" than courseplay, but is terrible around edges.

![image](https://user-images.githubusercontent.com/2694539/211603161-e8728e95-b413-46cb-a558-b8faa8dffda6.png)
![image](https://user-images.githubusercontent.com/2694539/211608745-d041a374-0928-4679-8659-e06639bf3d60.png)

**Comment by Tensuko** [comment]
Becouse your tool seems to be reported as a plow, wich is dynamic and intended.
