### ISSUE TITLE
[BUG_SP] Claas Xerion no path to parking position (wheel/steering problem? maybe node problem?)

### ISSUE THREAD

**Issue by AstraThomas** [Courseplay/Courseplay_FS22#2245]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
2 Silagesilos nahe beieinander bauen und dann den xerion mit 4.4m Schild Laufen lassen.
wenn der LKW mit Gras kommt und der Traktor (scheinbar) im rückwärtsgang ist findet er keinen weg zur Park Position und Fährt einfach Rückwärts bis man ihn stopt.

**Courseplay version**
Version used:  7.2
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10386048/log.txt)

**Log**

**Comment by Tensuko** [comment]
Video:
https://drive.google.com/file/d/1RZk5OPVqon40qn1JiIJFHBvb_GqzieMg/view?usp=share_link
log from the Video:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10428291/log.txt)

As Tested with the Fendt 900, forward, backwards, reversed driving, not a problem.
Somehow, the Xerion doesn't want to drive to the parking position.
Problem with the Vehicle again?
I am not sure if Giants had the requested Giants still in the Xerion when they updated it to the aniversery edition....

**Comment by Tensuko** [comment]
Seems to happen only with turned cabine of the xerion.

**Comment by AstraThomas** [comment]
ich Teste den 900er fendt mal und wenn es klappt (oder eben nicht) gebe ich bescheid.
Das Merkwürde ist tatsächlich das xerion das nur tut wenn ein abfahrer kommt. und es ist nicht reproduzierbar (zumindest habe ich noch keine konstate dazu gefunden wann genau es passiert)
