### ISSUE TITLE
Better Blade Adjustment

### ISSUE THREAD

**Issue by Makion65** [Courseplay/Courseplay_FS22#2246]
**What is the problem this feature/enhancement solves?**
The blade currently raises and lowers 0-100% very quickly.

**Describe the solution you'd like**
A gradual progression to raise and lower the blade.

**Describe alternatives you've considered**
Nothing here so far..

**Additional context**
Not looking for a manual way to adjust the blade height, just looking for more consistency.

**Comment by Tensuko** [comment]
duplicate #2221
