### ISSUE TITLE
[BUG_SP]Strohsammler finden nicht mehr den letzten Wegpunkt

### ISSUE THREAD

**Issue by MavericksBastelstube** [Courseplay/Courseplay_FS22#2247]
Kurs wird von den Dreschern geladen. Der / die Strohsammler fahren nach dem ersten Turn nicht auf den letzten
Punkt zurück. Teilweise funktioniert es. Teilweise wird beim Startpunkt wieder gestartet. Ziemlich random.

**Screenshots**
![fsScreen_2023_01_11_19_11_10](https://user-images.githubusercontent.com/103212815/211886175-a9d17ad8-799a-4488-bb86-fbad65fccfe6.jpg)

**Courseplay version**
Version used: 7.2.0.0 (Video mit Vorgänger Version - aber tritt auch mit 7.2.0.0 auf)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
NFMarsch ohne Gräben

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
In Kombination mit AD

Video zeigt Fehler vielleicht besser - oder mache ich bei den Settings was falsch??

https://youtu.be/uAw01YFXD1c

https://youtu.be/L3mCDqAP0Tw

**Comment by Tensuko** [comment]
#2237
