### ISSUE TITLE
Arbeitsbreite immer 1m

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#225]
Sorry I have currently no time to write a full bug report but it's simple:

Since last update the Coursegenerator does not know the working width. It's 1m all the time.

![image](https://user-images.githubusercontent.com/26980809/147618876-c4e443d7-7ea6-4d93-9b12-bddbf950bcb4.png)

**Comment by Obsiana2019** [comment]
Try the last Version 7.0.0.9. 

Versuch die neuste Version, da funktioniert es wieder.

**Comment by Keppchen** [comment]
Oh sorry. Closed and thanks. I thought I'm on the current with 0.0.8

**Comment by Keppchen** [comment]
Beim Bruin 4200 ist es immernoch.

**Comment by Tensuko** [comment]
@Keppchen und welche Version hast du zuletzt benutzt ?
Es gibt vereinzelte Geräte die ihre Arbeitsbreite etwas anders melden und entweder kriegen wir das bald raus, oder unsere vehicle config kommt dann wieder ins Spiel.

**Comment by Keppchen** [comment]
7.0.0.9 nutze ich aktuell.

Mit dieser Version wurde ja behoben dass die Breite IMMER auf 1m steht. 

Aber bei dem genannten Fahrzeug ist es noch so.

**Comment by Keppchen** [comment]
I see... 7.0.0.10 is out now. I will try.

**Comment by Tensuko** [comment]
Haven't found a tool yet that is still set to 1m.
If find one, let us know in a new Issue.
