### ISSUE TITLE
Km/h hoch und runter[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2250]
Hallo

Ich wollte mit Autodrive und Courseplay Gülle ´fahren, wenn der Fahrer auf der Straße fährt, beschleunigt er auf 23 km/h und bremst dann wieder runter und das die ganze Zeit 
Wo dran liegt das 
![Gülle fa](https://user-images.githubusercontent.com/47453761/212393029-0840b6ab-7b49-404d-a06d-3307de369b8d.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10414404/log.txt)

**Comment by Tensuko** [comment]
Da musst du die Jungs von AutoDrive fragen.
