### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by 5g4M** [Courseplay/Courseplay_FS22#2253]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Basically when I try to use the Silo Bunker mode with parking spot enabled , my driver seems to lag out and just keeps on reversing into nowhere or getting stuck somewhere weird.

**Actual behavior**
See above.
**Expected behavior**
My driver going to his assigned parking position and after the silo got loaded return to work like he should do 

**Screenshots**

**Courseplay version**
Version used: 7.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? 
Happens with all the default vehicles aswell as mods.

**Relevant script mods**
Autodrive and VCA

**Comment by Tensuko** [comment]
Logfile?

**Comment by AstraThomas** [comment]
The Same by me!!!!

**Comment by Tensuko** [comment]
> The Same by me!!!!

"Same" is not a helpful information.
I need the SAME requiered information.

**Comment by Tensuko** [comment]
#2245

**Comment by Tensuko** [comment]
Check the other Issue, definitly not "all the default vehicles".
But with the Xerion for example.
If there are more, we need to know wich exactly as our base function is given 100% and its working (tested back then with few vehicles)
![grafik](https://user-images.githubusercontent.com/27344744/212740700-2237f76b-84aa-4965-bfce-db27f5162dd5.png)
