### ISSUE TITLE
[BUG_SP] Combine changes to straw mode when chopped mode is selected

### ISSUE THREAD

**Issue by BattleHook** [Courseplay/Courseplay_FS22#2258]
**Steps to reproduce**
Create Field Course, select workmode Chopping

**Actual behavior**
When starting the course the Combine starts creating straw swath.

**Expected behavior**
When staring the course I expect the combine to chop the straw, not to create a swath.

**Courseplay version**
Version used: 7.2.0.0

**Comment by Tensuko** [comment]
I guess you selected that with the keybind, but for combine with CP, you have to choose it in the vehicle settings as we do overwrite it to have different options for headland and center.

**Comment by BattleHook** [comment]
> I guess you selected that with the keybind, but for combine with CP, you have to choose it in the vehicle settings as we do overwrite it to have different options for headland and center.

Yes, you are totally correct. Thank you for the help. Maybe add this to the CoursePlay generator? That's where I was looking for the option first.

**Comment by Tensuko** [comment]
No, it doesn't belong there and is not a generated setting.
But good you found it.
