### ISSUE TITLE
360 degree turn going from Headland to UP/DOWNs ???

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#226]
Why do CP have the tractor do 360 degree turn when transitioning from headland passes to up/downs?

![fsScreen_2021_12_28_22_12_01](https://user-images.githubusercontent.com/96673100/147626854-b3c6d276-10c7-4a72-8c0e-b2f9cd29811b.png)

![fsScreen_2021_12_28_22_27_35](https://user-images.githubusercontent.com/96673100/147627393-e0df86c0-47d2-4a08-b742-7b11519800fc.png)

**Comment by Tensuko** [comment]
This is correct
