### ISSUE TITLE
[Question] baler blocked by his own bales XD

### ISSUE THREAD

**Issue by wackoamd1** [Courseplay/Courseplay_FS22#2261]
i have set my baler on the same course as my harvester with 2headlands and up down center.
headlands go fine but assoon as the baler gets to the end of the 2nd headland and has to move to the centerlanes it encounters the bales from the headland and just plane stop. with no blocked by warning because the driver is still trying to move but he waits.

is there anything i can do about that or is that somekind of bug which makes the baling with CP not working because i have to shut down CP , move my tractor bailer past the bale on the field until he encounters another bale which i only find out after tabbing to the tractor. try doing that on 10 fields.

quick edit.
it also gets blocked by his own bale on sharp corners where it goes in reverse to take the corner.

**Comment by Tensuko** [comment]
Working as intended, not a bug.
Also see this: #1863
Enhancement for this is planed.
