### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Stagehand87** [Courseplay/Courseplay_FS22#2262]
Hallo,
ich würde mich als LS22-Neuling bezeichnen bzw. was Courseplay und Autodrive angeht.
Nun wollte ich einiges im Spiel automatisieren.
Ich nutze Courseplay 7.2.00 und Autodrive 2.0.0.9
[https://www.youtube.com/watch?v=msBsVLlIw0U&list=PL-UvOFIL55_haWsMeQwfRtzr_jkIASuNZ&index=20](url)
Dank dieses Videos ist es auch einfach und verständlich umzusetzen.
Was mir aber auffiel:

- Ich hatte 3 Drescher im Verband laufen. (Links1, Mitte, Rechts1). Sie begannen ihre Arbeit. Aber nicht im Verband mit eingestellten Abstand, nein sie fuhren, zwar jeder seine Bahn, aber ohne Rücksicht auf den Verband. bzw. überholte Drescher 3, den Drescher 2 am Vorgewende, wenn Drescher 2 zu lange beim Wenden benötigte, oder auf Abfahrer wartete. Somit fiel der Verband meist schon in der  ersten Feldrunde auseinander.

Habe ich irgendeine wichtige, evtl. neue Einstellung übersehen. Oder schlich sich evtl. ein Fehler in die neue Courseplay Version?

MFG

**Comment by Tensuko** [comment]
Die Schritte für Multitool sind:
Kurs mit einem Drescher erstellen der für 3 Arbeitsgeräte generiert wird.
Option A: Kurs kopieren und bei den anderen 2 einfügen.
Option B: Kurs speichern und in den anderen 2 laden (oder copy & paste)

Sollte so ohne Probleme funktionieren. Hatte ich zuletzt als Test für ein Issue probiert und ging und seit dem auch nichts dran geändert.
Wichtig: Es muss immer der gleiche Kurs sein.
Entweder Copy & Paste vom temporären, oder gespeicherten Kurs, oder halt gleichen Kurs laden.

**Comment by Tensuko** [comment]
Frage sollte beantwortet sein.
Ansonsten kann man auch im geschlossenen Issue schreiben.
