### ISSUE TITLE
CP Worker freezes when unloading ends before it reaches its unloading destination in example trailer on field.

### ISSUE THREAD

**Issue by NoIZnowuMniePodpalili** [Courseplay/Courseplay_FS22#2263]
When combine unloads really fast like a Lizard Collosus 9000 sometimes CP worker freezes when combine unloads before he gets to finall unloading position. Mainly when he corrects the position of the combine to the trailer and unloading completes before a stop.

Edit: Sometimes there is also a problem with unloading into the lode king Distinction Super-B with the mentioned Combine. It stops to unload into the first compartment even tho it did before combine stopped moving.

Edit 2: Lastest game version with latest CP version from game modhub.

**Comment by Tensuko** [comment]
Mod Issue.
And if you have a bug report, use ourtemplate and fill all in.
