### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by RFARMS** [Courseplay/Courseplay_FS22#2264]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Loaded into a savegame with autodrive. I opened courseplay then autodrive, opened courseplay again, closed it and then the right mouse button stopped working.
**Actual behavior**
A clear and concise description of what happen.
mini menu doesn't open with right mouse click.
**Expected behavior**
mini menu to open with right mouse click.
**Screenshots**
![20230119073544_1](https://user-images.githubusercontent.com/123046341/213457164-2458a751-bfec-4cb9-8843-42f5b127a973.jpg)
![20230119073547_1](https://user-images.githubusercontent.com/123046341/213457183-1612a728-0b73-4660-b356-1bc6d52c0d79.jpg)
 Just to show that the key bind is there and that it is active in the menu.
**Courseplay version**
Version used: 7.2.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10457183/log.txt)

**Map**
Map played on.
Elmcreek
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.
auto drive

**Comment by Tensuko** [comment]
"mini menu doesn't open with right mouse click."
AutoDrive Editor Mode active?
pretty sure about this, becouse when the AD Edit Mode is active, right mouse click is deactivated so that you can move AD Waypoints without CP opens the HUD.

**Comment by RFARMS** [comment]
The AutoDrive Editor Mode isn't activated and it still will not open up.

**Comment by Tensuko** [comment]
Reinstalling the game won't help as it doesn't overwrite the settings files for mods.

Check ..\Dokumente\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay and there the courseplay.xml

Remove the Line: <Hud posX="0.171094" posY="0.024306"/> and save the file.
Try it again, maybe it just disappeared somehow.

**Comment by RFARMS** [comment]
Yes It fixed the issue, thank you, I apologize for the delay I was away from my computer!
