### ISSUE TITLE
[BUG_SP] Fendt 930 doesn't drive to parking position

### ISSUE THREAD

**Issue by 5g4M** [Courseplay/Courseplay_FS22#2265]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
As I stated some days ago the silo worker seems to fail working proberly , at some point he reverses until he colides with something.

**Actual behavior**
See above

**Expected behavior**
He should do his silo job and should be able to park, he is failing at both r/n

**Screenshots**

**Courseplay version**
Version used: 7.2

**Log**

**Map**
Haut-Beyleron and Elm Creek

**Vehicles/ implements involved**
Vanilla 930 with a vanilla shield for silo

**Relevant script mods**
VCA Autodrive and CP all of them newest version

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10459349/log.txt)

**Comment by Tensuko** [comment]
Screenshots would help here. (A Headline is also nice to have...)

**Comment by Tensuko** [comment]
Can't reproduce...

![fsScreen_2023_01_19_18_51_29](https://user-images.githubusercontent.com/27344744/213521958-792fd0fc-fed6-4c7f-b64c-8097d4c0a4e8.png)

![fsScreen_2023_01_19_18_51_21](https://user-images.githubusercontent.com/27344744/213521939-fcc6e664-4e20-4556-a138-418a05da0d11.png)

**Comment by 5g4M** [comment]
Btw kann ich auf deutsch weiter reden?
deutsch ist etwas einfacher fuer mich als english.

**Comment by Tensuko** [comment]
Jo kannst machen.
Aber ich hab das Problem nie gehabt...
Hast du an den Geschwindigkeiten gedreht?

**Comment by Tensuko** [comment]
Ja.

**Comment by 5g4M** [comment]
Habe das ganze aufgenommen bekommen , da sieht man wie das Silo aufgebaut , die Parkposition und was genau passiert.
https://www.youtube.com/watch?v=zbfvLZZetcs

**Comment by Tensuko** [comment]
Ah.
Das hat nichts mit parken zu tun.
Welche Silos sind das?

**Comment by 5g4M** [comment]
Das ist das Vanilla mittlere Bunkersilo soweit ich weiß ,ich gucke später nochmal genauer nach.
Ich habe gestern noch mit dem Axion probiert, werde später ein Video schicken was dort passiert wenn er parken soll.

**Comment by 5g4M** [comment]
Das Fahrsilo ist aus dem standard spiel und ist das mittlere.
Hier nochmal ein Video was beim Axion passiert wenn er zur Parkposition soll.
https://drive.google.com/file/d/12XfK2eO8aUggY_Z_BiyCL_8udIApl-C2/view?usp=share_link

**Comment by Tensuko** [comment]
Das ist auch noch nicht zum Parken fahren, passiert auch wieder vorher.

**Comment by 5g4M** [comment]
Der Axion 920
Ja das Verhalten ist aber ein anderes,der Fendt hat beim normalen Fahren dieses Rückwärts fahren gehabt und der Axion bringt das Verhalten nur wenn ein Abfahrer abladen möchte.

**Comment by Tensuko** [comment]
Das ist noch VOR dem fahre zur Parkposition.
Es passiert beides bei aus dem Silo raus fahren.

**Comment by 5g4M** [comment]
Trotz allem bleibt noch die Frage warum DAS passiert :S

**Comment by Tensuko** [comment]
Muss ich mir angucken, aber da komme ich glaube ich erst morgen zu.
Ich hatte vor 2-3 Tagen auf der Elmcreek einen Fendt 920 laufen bestimmt eine Stunde lang und ohne Probleme.
Ist halt schwer zu sehen was und warum, aber wie gesagt ich guck es mir an.

**Comment by AstraThomas** [comment]
Genau das Selbe macht der Xerion (#2245) auch. Rückwärtsfahren bis es nicht mehr geht. leider fand ich nie die konstante wann es passiert. 
bei mir lief er auch schon stunden ohne probleme....... und dann einmal hingesehen zack umgedreht, rückwärtsgefahren oder what ever. schrödingers bug..... er existiert nur im moment des hinsehens XD

**Comment by 5g4M** [comment]
Ja genau, bei mir lief das auch schon Stunden ohne Probleme und dann teilweise nicht Mal 10 Minuten ohne Probleme.
Kann auch gerne alles bereit stellen um zu helfen Tensuko.

**Comment by AstraThomas** [comment]
Interessant. ich habe den besagten fendt die ganze nacht durchlaufen lassen. das einzige was passierte ist das er sich festgefahren hat. was erstmal nicht so schlimm ist. aber es scheint das es an den traktoren liegt ob das schieben mit cp funktioniert oder nicht. 
wäre nice wenn ihr euch das mal genauer anschauen könntet. für große silos ist der fendt einfach zu leicht/schwach

**Comment by AstraThomas** [comment]
Korrektur. der Fendt mach auch das selbe wie die anderen traktoren

**Comment by 5g4M** [comment]
Ich habe jetzt auch fast alle Vanilla Grosstraktoren mit verschiedenen Schildern getestet und alle machen frueher oder spaeter bockmist was mich zum kuendigen zwingt :S :D

**Comment by AstraThomas** [comment]
komischer weise. wenn du die neu mietest gehts einige stunden gut. je länger die laufen desto öfter bauen die bockmist

**Comment by Tensuko** [comment]
Kein Plan was bei euch passiert

**Comment by PhiSch19** [comment]
Ich hab das Problem such hin und wieder, aber er fährt dann immer rückwärts irgendwo hin, u.B. wenn man ein paar Silos nebeneinander setzt, landet er hin und wieder mal rückwärts in einen anderen.

Es tritt aber fast immer bei einen der ersten rückwärts Vorgänge auf, wenn er einmal ein paar Minuten läuft, dann läuft es auch.

Was mir aufgefallen ist, es tritt öfter auf, wenn man die Parkposition in einem spitzen winkel setzt, dass interessante daran ist aber, dass man wenn man ihm einfach wieder in eine akzeptable Position bringt, mit einfachen starten fixen kann.

Es tritt auch sowohl mit als auch ohne abfahrer auf. Er bleibt auch bei einem Hindernis dann stehen mit der blockiert Meldung.

So richtig nachvollziehbar ist es für mich aber nicht, nachstellen kann ich es auch nicht.
Hatte es schon mal probiert zum nachstellen, aber man kann den selben spielstand mit denselben cp Einstellungen immer wieder laden, ein paar mal gehts, ein paar mal nicht.

Da es sowohl beim rückwärts raus fahren, beim Spurwechsel als auch beim auf die Parkposition zurückfahren auftritt, habe ich überhaupt keine Anhaltspunkte, was die Ursache sein könnte.

**Comment by 5g4M** [comment]
Ich meine gut ist das wir diesen Fehler entdecken bzw genauer untersuchen , doof ist das niemand genau weiss warum das passiert.
Wir als Community wollen ja auch helfen die Mods zu verbessern!

**Comment by Tensuko** [comment]
Debug modus einschalten, logfiles mit debug posten, Videos aufzeichnen.
Am besten unterschiedliche Situationen.
Irgend etwas löst das aus.
Dieses unendliche rückwärts fahren passiert, wenn der Fahrer den Wegpunkt den er anfahren sollte nicht erreicht hat.

Das hat erst mal nichts mit Parken oder sowas zu tun.

**Comment by AstraThomas** [comment]
dem muss ich tensuko zustimmen. mir ist aufgefallen das die radien die der traktor fahren soll immer sehr eng sind. aber durch den "rückwärtsschwung" kann der traktor meist nicht schnell genug bremsen. muss vlt cp da feiner eingestellt werden? (nur so ein gedanke) 

aber ich werde das morgen mal aufzeigen. 

wenn der debugmodus eingeschalten ist wird es automatisch mit in die log.txt geschrieben? oder gibt es da eine andere datei?

**Comment by Tensuko** [comment]
Wird in die log.txt geschrieben.

**Comment by AstraThomas** [comment]
hier mal ein fehler der oft passiert. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10481776/log.txt)

**Comment by AstraThomas** [comment]
wo kann ich ein video dazu hochladen? hier sagt er mir es wäre zu groß

**Comment by Tensuko** [comment]
YouTube am besten.

**Comment by AstraThomas** [comment]
Hier der Youtubelink.
leider ist nur der fehler mit eingeschaltetem debug[log.txt]eschalten und nicht die rückwärtswendung
https://youtu.be/AxYRx-8jLYw


und daz
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10483376/log.txt)
u gleich nochmal die entsprechende logdatei.

**Comment by AstraThomas** [comment]
was mir grade auffällt. in dem Video von dem anderen Kollegen hier: der Traktor fährt sich ein wenig fest und das schild vorne fängt an zu "sehr wackeln" und genau dann fährt das ding unkontrolliert zurück.  genau wie bei mir (leider nicht in meinem  video sichtbar).  kann es damit zusammen hängen?

**Comment by Tensuko** [comment]
Dein Video zeigt nun wieder etwas komplett anderes. Sorum darf der gar nicht in das Silo fahren, wenn das Schild vorne dran ist....
Kabine gedreht UND das Schild vorne dran?
Was genau hast du da gemacht?
Das kann schon wieder was ganz anderes als Ursache haben...

**Comment by AstraThomas** [comment]
der ist von der spur daneben rückwärts raus gefahren und hat dann im rückwärtsgang in einem bogen gedreht (ohne linie vom debuggung) und ist dann rückwärts in das silo gefahren.
kabine war nicht gedreht da er ja vorher richtig gewfahren ist ich versuche es nochmal zu reproduzieren

**Comment by AstraThomas** [comment]
so ich konnte es reproduzieren.

hier der youtube link: https://youtu.be/n5IKJqU4drs
und hier die log:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10500693/log.txt)

**Comment by Tensuko** [comment]
Nein.

**Comment by AstraThomas** [comment]
ok ihr könnt es nicht reporduzieren...... was können wir tun damit ihr es nachverfolgen könnt?

**Comment by Tensuko** [comment]
Removed = entfernt.
Abwarten, das ist halt etwas tricky und braucht Zeit.

**Comment by AstraThomas** [comment]
achso. okay mein fehler^^

**Comment by Tensuko** [comment]
Improoved in 7.2.0.1 but not sure if overall fixed.

**Comment by AstraThomas** [comment]
ich habe ein test savegame genau dafür erstellt.
ich lasse das mal laufen und werde berichten was passiert und es wieder versuchen mit video aufzunehmen

**Comment by AstraThomas** [comment]
Kurze Rückmeldung.
Leider tritt das problem weiterhin auf. habe es allerdings noch nicht schaffen können ein video aufzunehmen.

**Comment by Tensuko** [comment]
Bis auf den Xerion konnte ich das Verhalten noch nicht feststellen.
