### ISSUE TITLE
[BUG_SP] Precision Farming applieing fertilizer with use fertilizer deactivated

### ISSUE THREAD

**Issue by MysteryMerijn** [Courseplay/Courseplay_FS22#2266]
**Steps to reproduce**
Using KUHN MACIMA 3 TIL and KUHN TF 1512 with fertilizer in the tank (only planter tank) and with the setting "Sowing machines use fertilizer" "Deactivated". Sow a field. This does not consume fertilizer but applies nitrogen.

**Actual behavior**
The nitrogen value increases with seeder/planter use fertilizer setting disabled. This does not consume fertilizer from the tank. With the fertilizer tank empty and the setting deactivated no nitrogen is applied.

**Expected behavior**
Nitrogen value should not increase with the setting on deactivated.

**Courseplay version**
Version used: 7.2.0.0 (ModHub)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Using KUHN MACIMA 3 TIL and KUHN TF 1512

**Relevant script mods**
Precision Farming

**Comment by Tensuko** [comment]
Will be fixed in the next release.
