### ISSUE TITLE
[BUG_SP]   CP-xx appear on existing  field 

### ISSUE THREAD

**Issue by magicmana** [Courseplay/Courseplay_FS22#2267]
some time i  need  to extend some fields , for sample field with 30m of grass around.
i record a single couse around the  field  and  i have a message who ask if i wantuse  the current course for define the  field.
i respond   yes and now i can extend the field using the "create field" on plow.
but the problem is that i have now on the map a field named "3" and "CP-2" at the same location .
![fsScreen_2023_01_19_21_58_06](https://user-images.githubusercontent.com/32802279/213573967-9e762096-0d01-4072-b0fc-95c9d2010946.png)

**Comment by Tensuko** [comment]
Becouse you created custom field borders.
Intended.
You can use them to generate a course on them even the field isn't extended yet.
Read the ingame help about it pls.
It also explains what that record button is for.
If you just want to extend the field, use a plow.

You can also rename or delete them, again, read the ingame help for more information.
