### ISSUE TITLE
[BUG_SP] hallo, mein ladewagen fahrer oder kalkstreuerfahrer fahren nach dem abladen , bzw beladen nicht mehr zum letzten wegpunkt aufm feld wo sie zuvor waren .

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/Courseplay_FS22#2270]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by iceman234de** [comment]
Sind mod fahrzeuge , cp und ad sind die neuesten versionen

**Comment by Tensuko** [comment]
Suche nutzen.
Einmal savegame ohne cp laden und speichern, dann wieder mit cp laden.
Kommt durch eine alte version.
Ist dann behoben.
