### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by wackoamd1** [Courseplay/Courseplay_FS22#2271]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
attach a standard snowplow and no its not a leveler its a snowplow

**Actual behavior**
stupid auto mode (worst option ever in CP) only sets it to silo mode

**Expected behavior**
able to create a course

**Screenshots**

**Courseplay version**
Version used: 7.2.0.0

**Log**
its not a error , 
its just the retarded auto mode .
this is one of the automode problems it does it with other implement modes too. ( lock into a mode)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement? snow plow samasz jump 320
Mod yes/no ? no

**Relevant script mods**
autodrive  and CP

**Comment by Tensuko** [comment]
Do you think a bugreport like this will make us change anything about it?

Beside that, a snowplow on a field?
