### ISSUE TITLE
[BUG_SP] remaining time

### ISSUE THREAD

**Issue by raceking08** [Courseplay/Courseplay_FS22#2273]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
The remaining time not showing up for me on the hud

**Actual behavior**
N/a

**Expected behavior**
N/a

**Screenshots**

**Courseplay version**
Version used: 7.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Welker. Devon

**Vehicles/ implements involved**
Which vehicle or implement? Claas
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
logfile?
Screenshot?

**Comment by Tensuko** [comment]
Closed due to inactivity.
The Remaining time is for all Fieldwork on the HUD 100%
