### ISSUE TITLE
Der Düngerstreuer fährt nach dem auftanken immer erst zum ersten Wegpunkt statt zum letzten[BUG_SP]

### ISSUE THREAD

**Issue by manne70** [Courseplay/Courseplay_FS22#2275]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Ich habe auf der Multimap 22 den großen Bredal zum Feld geschickt um zu Kalken als er lehr war fuhr er mit AD zum Silo um zu  beladen und zurück zum Feld. Am Feld übernahm CP und fuhr nicht zum letzten Wegpunkt sondern zum ersten.
**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
Er solte nach dem auffüllen am letzten Wegpunkt beginnen. Bei den Sähmaschienen
 fuktioniert es.
**Screenshots**

**Courseplay version**
Version used: 7.2.0.0  AD 2.0.0.9

  [##**Log**]

**Map**
Map played on.Multimap LS22

**Vehicles/ implements involved**
Which vehicle or implement?MF 6715 S mit Bredal K165
Mod yes/no ?Nein
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10501345/log.txt)

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
#2270
https://github.com/Courseplay/Courseplay_FS22/issues/2270#issuecomment-1399287885
