### ISSUE TITLE
Fehler MP

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/Courseplay_FS22#2277]

**Comment by Bandesss** [comment]
Wir haben auf der Mountainhill den Fehler`
Was kann das sein ?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10520066/log.txt)
Danke

**Comment by Tensuko** [comment]
Das kann sonst was sein.
Da es keine komplette log ist, kann ich noch weniger dazu sagen.
Keiner der Errors verweist auf CP.
Da kannst du eher Giants fragen.

**Comment by Bandesss** [comment]
Ok weil es kam als wir cP nutzen.
Tue meine log noch ran ok

**Comment by Bandesss** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10521431/log.txt)
