### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/Courseplay_FS22#2278]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Einfach beim Dreschen und Sammeln 

**Courseplay version**
Version used: 

7.2.0.0

**Player on the server**
7

**Dedicated server or local hosted server**
Rootserver

**Map**
MountainHill

**Vehicles/ implements involved**
Drescher

Enhanced Vehicle
Haben den fehler ?
Wir wissen nicht, was es ist 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10520786/log.txt)

Vielen dank für die Hilfe

**Comment by Bandesss** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10521024/log.txt)

**Comment by Tensuko** [comment]
Dafür muss man kein neues Issue aufmachen...
Wie ich es bereits sagte, das ist ein Fehler im Giants Code der da angemerkt wird:
2023-01-27 15:51 Error: Running LUA method 'draw'.
dataS/scripts/vehicles/specializations/Motorized.lua(2240) : attempt to index field 'consumersByFillType' (a nil value)

Das ist ein SimpleIC Error:
2023-01-27 16:59 Error: Running LUA method 'packetReceived'.
F:/Server/FS22_simpleIC/simpleIC.lua:215: attempt to index local 'spec' (a nil value)

Wilde Modkombination:
Available mod: (Hash: 5b03eed0f3996c5264f6dfc3d9397c78) (Version: 1.2.6.2) FS22_BetterContracts
Available mod: (Hash: 8293166e3e54a558006997f87d8f6a4b) (Version: 1.0.0.0) FS22_ContractServiceProvider
Available mod: (Hash: 99f29b0913327fdd96639c47107e7baf) (Version: 1.0.0.0) FS22_Contracts_Plus

Komplett unbekannte Mods:
Available mod: (Hash: 16ce70cf4ae1a54f9fbf9f7aceee4a83) (Version: 1.0.0.0) FS22_4940
Available mod: (Hash: a2c440de48e0c207587b52457de845fa) (Version: 1.0.0.0) FBM22_DeutzSeries9
Available mod: (Hash: 8937b278e211e4d816f214698810ae88) (Version: 1.0.0.0) FBM22_Koeckerling_Allrounder

Kein CP Error.
