### ISSUE TITLE
Course generator[Question]

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/Courseplay_FS22#2279]
Hi, i'm using CP now since available op FS22, something came to me, the course generation modes, there are four of them, up/down, spiral, racetrack and the last one i've lost it. But is this still work in progress?  Or is it final? If it is final, then there could be a problem, the spiralling (for combining and mowin grass, isn't working.

**Comment by Tensuko** [comment]
It is not like we have all patterns for all kind of work.
You should try out 2-3 Headlands and lands to have a good harvesting.
Spiral is a rather spezial way and was an experimental pattern in FS19.

The Generator gets a Version 2.0 with some impovements and maybe more features later.
But that takes some time.

**Comment by dicktimmerman** [comment]
Thanks Tensuko. Was really doudting whether to make a bug report or just a question like this. But, the spiral was really a ood pattern to use.
