### ISSUE TITLE
Feldarbeit nicht für Ladewagen auswählbar

### ISSUE THREAD

**Issue by NEA1971** [Courseplay/Courseplay_FS22#228]
Der Ladewagens kann derzeit (v.7.0.0.9) nicht für Feldarbeit genutzt werden, um einen gespeicherten Kurses zum Einsammeln von Stroh oder Gras/Heu verwenden zu können. Auswählbar sind hier nur "Freie Fahrt" und "Laden und Liefern" für den Giants-Helfer

**Comment by haamic** [comment]
das kann ich bestätigen

**Comment by TheSoldier91** [comment]
Same here 👋🏻

**Comment by Tensuko** [comment]
Issue Nummer 568...
Leute wartet es ab, es ist noch nicht alles integriert...

**Comment by NEA1971** [comment]
@Tensuko - reg' dich wieder ab. Mir geht es hier nicht darum irgendwelchen Druck aufzubauen. Ich weiss nicht, was ihr alles vorhabt, was derzeit funktionieren soll und was ein Fehler ist. Ich wollte hier nur ein "Enhancement" dokumentiert haben, das ich irgendwann gerne gesehen habe. Wenn das nicht mehr gewünscht ist, dann stellt hier doch einfach auf privat und entwickelt wie ihr es für richtig hält - dann geht euch keiner auf den Zeiger. Nichts für ungut.
