### ISSUE TITLE
nun aber CP

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/Courseplay_FS22#2280]
Hallo wir haben doch nun was gefunden 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10522155/log.txt)
Danke für die Hilfe

**Comment by Tensuko** [comment]
Wieder neues Issue und diesmal einfach nur ein Callstack in der log ohne weitere Infos....

**Comment by Tensuko** [comment]
@pvaiko Line 5539
