### ISSUE TITLE
[Question]  is the collision detection changed?

### ISSUE THREAD

**Issue by Orsa1305** [Courseplay/Courseplay_FS22#2281]
i find my self standing a few meters from the field watching the worker do  his thing,  and checking the map, or something else in the menu.
when i get back out there, the worker is stopped, about 10 meters from me, accusing me from blocking him!

first, that's kind of weird, as he isn't suppose, and won't go, out of the field where I'm standing.
i don't think there is any setting for collision detection.

**Comment by Tensuko** [comment]
Do you have a screenshot of this and a logfile would be interesting

**Comment by Orsa1305** [comment]
uhm, not really , as it was just a question :)
but i will try to get a screenshot, occurs more then once a day, and a logfile, from the game?  or is there a special logfile you want?

**Comment by Tensuko** [comment]
Just the log.txt attached here.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Simple answer: No :)
