### ISSUE TITLE
[BUG_SP] Entlade Drescher Modus Funktioniert nicht bei Feld Häcksler 

### ISSUE THREAD

**Issue by steven1134** [Courseplay/Courseplay_FS22#2284]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Kaufe 1 Traktor und Denn HAWE SUW 5000 und stelle ihn mit dem modus Entlade Drescher mit einem Feld Häcksler ein

**Actual behavior**
Der abfahrer Macht einfach nichts

**Expected behavior**
Er sollte zum Feld Häcksler fahren und Seinen Job Machen Drescher Entladen und aam feldrand auf einen Abfahrer überladen

**Screenshots**
![fsScreen_2023_02_01_01_22_01](https://user-images.githubusercontent.com/62439666/215915565-d77d7268-3ca0-445b-82a5-9332b8c8ee14.png)
![fsScreen_2023_02_01_01_22_04](https://user-images.githubusercontent.com/62439666/215915572-0c8dfbcb-e867-4d51-9efd-b477cf8f00d1.png)

**Courseplay version**
Version used: 7.2.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10552131/log.txt)

**Map**
landkreis rostock

**Vehicles/ implements involved**
John Deere 8030 Series(mod)/ HAWE SUW 5000(base game)
Mod yes/no ?

**Relevant script mods**
Autodrive VCA GPS

Meine Frage wehre ob es Bekannt ist das der Überlade modus bei feld Häckslern nicht funtioniert oder ob das ungewollt ist.

**Comment by ct177mak** [comment]
Korrigiert mich aber Häcksler abtanken funktioniert nicht mit CP bis dato ,ich weiss auch nicht ob das überhaupt geplant ist von den Devs diesen Modus zu implementieren.

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/2126
