### ISSUE TITLE
[BUG_SP] Blocked by an object vers 7.2.0.0

### ISSUE THREAD

**Issue by Mchavezv80** [Courseplay/Courseplay_FS22#2285]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I joined two fields and when using the roller the problem occurs. This only happens with ROLLERS 

**Actual behavior**
When the tractor finishes the row and turns around, it seems to detect an unevenness

**Expected behavior**
Continue with the work since there is no object that is blocking the tractor

**Screenshots**
![20230131231732_1](https://user-images.githubusercontent.com/124124599/215962663-ea19e2fa-972b-4f8e-b85c-c8cf17a2c705.jpg)
![20230131221041_1](https://user-images.githubusercontent.com/124124599/215962699-b4b37a89-228c-4efc-b954-bb06d9ade407.jpg)

**Courseplay version**
Version used: 7.2.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10553703/log.txt)

**Map**
ELMCREEK

**Vehicles/ implements involved**
New Holland T7.275HD
Dalbo Power Roll 1230 HD (Roller)

Mod yes/no ? 

both are not a MODS

**Relevant script mods**

I have Auto Drive installed

**Comment by Tensuko** [comment]
Why did you not use at least one Headland?

**Comment by Mchavezv80** [comment]
> Why did you not use at least one Headland?

I'm sorry but I didn't understand your question 

What you mean?

**Comment by Tensuko** [comment]
One round arround the field, then the lanes up and down.
Your driver won't leave the field that way and you won't have problem with higher landscape and stuff.
Wich is odd anyway, I guess it detects something else.

**Comment by Mchavezv80** [comment]
> One round arround the field, then the lanes up and down. Your driver won't leave the field that way and you won't have problem with higher landscape and stuff. Wich is odd anyway, I guess it detects something else.

OK understood.
I try not to use round around because I always have 3 or 4 tractors in the field and if I use that option, the tractors crash into each other.

**Comment by Mchavezv80** [comment]
> One round arround the field, then the lanes up and down. Your driver won't leave the field that way and you won't have problem with higher landscape and stuff. Wich is odd anyway, I guess it detects something else.



The funny thing is that it only happens with the roller, the combine turns well, the seeder too, all work well except the roller

**Comment by Tensuko** [comment]
I will have a look.

**Comment by Tensuko** [comment]
![fsScreen_2023_02_01_16_57_37](https://user-images.githubusercontent.com/27344744/216095263-f0995f46-96e2-47e1-88fb-0838075102e9.png)
btw, turn on field active? Works fine too.

**Comment by Mchavezv80** [comment]
> I will have a look.

Thanks a lot



I'm using the tractors and rollers that come with the game, but the same thing happens with the mods

The funny thing is that it only happens with the roller, the combine turns well, the seeder too, all work well except the roller

> ![fsScreen_2023_02_01_16_57_37](https://user-images.githubusercontent.com/27344744/216095263-f0995f46-96e2-47e1-88fb-0838075102e9.png) btw, turn on field active? Works fine too.

The option "turn on field" is not active

**Comment by Tensuko** [comment]
Just checked and the problem is the map.
The reason why is becouse you leave the field too far with that roller.
Combines don't have to and I guess you have a short seeder.
![fsScreen_2023_02_01_16_59_19](https://user-images.githubusercontent.com/27344744/216095649-5134465d-4f24-412e-b6d9-79f88bd5cba3.png)

**Comment by Tensuko** [comment]
> The option "turn on field" is not active

Then turn it on, thats why we have it to also prevent such problems.

**Comment by Mchavezv80** [comment]
> > The option "turn on field" is not active
> 
> Then turn it on, thats why we have it to also prevent such problems.
> 
> Addition: The sensor have to change the hight to look uphill for example and not look into the the ground. The reason why we also detect to steep ground is, it could be a wall where we don't want to drive into.



ok then the solution would be to turn on the "turn on field" right?

**Comment by Tensuko** [comment]
Yes, you should do that to rather drive on the field.
