### ISSUE TITLE
[Question] driving back to the last point 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/Courseplay_FS22#2286]
Hello I’m using AD to load my tractor with lime etc when AD hands back over to CP I’m finding CP drives odd routes to get back to its last point like towards a tree what can I do to make sure it drives on the field doesn’t matter about crops as it’s harvested

**Comment by Tensuko** [comment]
" I’m finding CP drives stupid routes to get back "

And what do you call "stupid routes" ?

**Comment by matty2123** [comment]
I wrote that a bit harsh it will take a route off field towards a tree or hedge etc

**Comment by Tensuko** [comment]
Need Screenshot with example.
However, we won't adjust much there anyway as there are ofc edge cases.

**Comment by matty2123** [comment]
![91B6BE68-EB7F-46FA-8D32-7D8442821ADC](https://user-images.githubusercontent.com/27097241/217922632-8a47f5c9-9b8d-47a6-a9ab-e2cab6dd9a78.png)
Find attached photos

**Comment by Tensuko** [comment]
Okay should have said with debug on but anyway.
Do you have avoid fruit on or off ?

**Comment by matty2123** [comment]
I can always link debug on if needs be. Avoid fruit is off on this as nothing to destroy

**Comment by Tensuko** [comment]
Turn it on.

**Comment by matty2123** [comment]
Ok will turn on and report back

**Comment by Tensuko** [comment]
Closed due to inactivity.
