### ISSUE TITLE
[BUG_SP] Unable to fix incorrect offset due to "auto" setting

### ISSUE THREAD

**Issue by GMNGjoy** [Courseplay/Courseplay_FS22#2287]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
1. Equip tool: Tool / implement: John Deere 670 Disc 6.5m (https://www.farming-simulator.com/mod.php?lang=en&country=cl&mod_id=233802&title=fs2022)
2. Create CP course
3. Start course

**Actual behavior**
CP detects the offset for the tool incorrectly, moving the offset beside the tool, offset  by 0.7, and locks it from being changed with a setting of "auto" in the UI, and blocks changes from being changed in the vehicle specific settings by locking the input fields.

**Expected behavior**
Ability to change the offset at any time from the UI, regardless... that's why it's there.

The mod is supposed to have an offset animation where it offsets the whole impliment off to the side - but this animation is not working / setup correct. I have attempted to correct this from the mod side (removing the folding / unfolding animation, etc, to no avail. If there is something simple in the mod that can be changed to get this to work, it would be appreciated! From a user perspective - it's unclear why the offset would not only be set to "auto" but also not be able to be changed by the user. I would expect that if CP is determining an offset - that's great, but it shouldn't ever lock the user out of changing that offset.

**Screenshots**
![fsScreen_2023_02_04_11_16_58](https://user-images.githubusercontent.com/107238894/216785980-2f49db00-b5fb-45a4-aca7-54c702fb8282.png)

![fsScreen_2023_02_04_11_24_40](https://user-images.githubusercontent.com/107238894/216785981-de2c4c47-5298-42da-b3c1-c01abc97c3af.png)

**Courseplay version**
Version used: `7.2.0.0`

**Log**
https://gist.github.com/GMNGjoy/68ecb6f5858df03c9cf3df959c186f36

**Map**
Middleburgh, NY

**Vehicles/ implements involved**
Which vehicle or implement?
John Deere 670 Disc 6.5m (https://www.farming-simulator.com/mod.php?lang=en&country=cl&mod_id=233802&title=fs2022)
Mod yes/no ?
yes

**Relevant script mods**
Autodrive is enabled but not in use

**Comment by GMNGjoy** [comment]
Update, after much much research, more than justified for a mod that's not even my own, i've found the following:

Mod Issues:
- there is supposed to be an "unfolding" animation that happens where the device offsets it off to the right. the mod is not setup to have that unfolding happen properly at this time
- the `sizeMarkers` in the i3d were offset by ~0.7 to the left in the i3d file, for an unknown reason; there didn't seem to be a result of changing this, but it was a bit messed up.
- the `sizeMarkers` in the i3d were set incorrectly for most of the tools in that pack. 😢 


CP issues:
1. Courseplay seems auto-adjusts the working area based off the ai `areaMarkers` as defined in the XML. If these are set, it appears to set it to "auto".
2. When there is an animation (regardless if that animation has run), CP will try to adjust the positioning of the `areaMarkers` based off the animation values... but does it's calculation of where the new zone should be poorly, often compensating much too far based on the movement that is happening. (in my case, it's offset by over 1m too far in the right direction; there was also an animation for "folding" that was never running, but courseplay was assuming that it was happening, and adjusting as if it had run)
4. The "auto" setting for offset is not overridable - i'm happy to see it move based on the animation, but if it doesn't actually move properly... i'd like to be able to adjust it.

You can, however... sortof fix it by changing the positioning of the `areaMarkers` in the i3d file as if they are in the intended position that CP will put them in after it auto-moves it... what i mean by that is that when i have the animation working properly, and the tool "offsetting" itself to the side of the tractor (like a bale wrapper), and that resulting "box" is off by about 1meter - and I then adjust the `areaMarkers` to be positioned 1m in the opposite direction in the i3d, it all lines up in the end, and the course completes as it should without missing anything. This change feels like i'm hacking the model to have invalid values just so that courseplay will end up working, which is missing the point. IF CP calculated the movement properly, I shouldn't have to change the i3d at all.

**Comment by Tensuko** [comment]
As you noticed correctly, it is a mod issue wich was mentioned a long time ago in any Issue.
CP is working correct for plows, it is intended.
As that tool is not a real plow with wrong set markers, it is a mod issue.

**Comment by GMNGjoy** [comment]
@Tensuko I'd still consider that the "auto" setting not being able to be overridden a CP issue - the idea behind being able to customize the offset is part of the functionality of CP - and if CP is calculating that offset incorrectly, the user should be able to correct it.

**Comment by Tensuko** [comment]
Not for real plows. It is on purpose!

**Comment by Napo0192** [comment]
> Not for real plows. It is on purpose!

Plow Kverneland PW 100-12 working awfully because of auto offset, is there any wat to fix it? 

![image](https://github.com/Courseplay/Courseplay_FS22/assets/155890623/06a1c613-6374-4e40-bcb2-1da5cb763c64)
