### ISSUE TITLE
[BUG_SP] Auger Wagon not recognised for unloading w/Autodrive

### ISSUE THREAD

**Issue by MrKiel** [Courseplay/Courseplay_FS22#2289]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use a sugarcane harvester (or any harvester without internal storage) alongside an auger wagon to harvest a sugarcane field. E.g. Tractor - sugarcane harvester - auger wagon. Use a manually driven trailer, courseplay trailer, or autodrive trailer to attempt to unload the harvester / auger wagon combination. 

**Actual behavior**
The auger wagon will not unload into trailers alongside this unit, either manually driven or driven by AutoDrive. Additionally, a full auger wagon will not be recognised as a "full combine" and so courseplay will not drive the unit to a nearby trailer to self-unload. The Auger wagon pipe will 'follow' the trailer alongside, but will not unload into it. 

**Expected behavior**
Auger wagon should unload into trailers pulled alongside. 

**Screenshots**

**Courseplay version**
Version used: 7.2.0.0

**Log**
Happy to supply if required

**Map**
Elm Creek

**Vehicles/ implements involved**
Any tractor
SWT 7 Sugarcane harvester
SUW 5000 Auger Wagon

**Relevant script mods**
Autodrive, Courseplay, Autoload

**Comment by Tensuko** [comment]
Only combines are supported by CP unloaders as written in the manual). For AD you got to ask there.

Choppers and sugar cane Harvester are not supported and wont be, sry
