### ISSUE TITLE
[BUG_SP] v.7.0.0.9 Strohablage nicht korrekt

### ISSUE THREAD

**Issue by NEA1971** [Courseplay/Courseplay_FS22#229]
Stroh wird beim Dreschen nicht im Schwad abgelegt
1. Strohablage des Dreschers:
![LS22-Strohablage1](https://user-images.githubusercontent.com/45850108/147638576-7f62bbcc-1716-4702-8c78-b629aa691d98.png)

2. Einstellung in CP
![LS22-Strohablage2](https://user-images.githubusercontent.com/45850108/147638584-c17008ba-9e71-4fc1-9587-9a32660a4e12.png)

**Comment by schwiti6190** [comment]
duplicate of #147
