### ISSUE TITLE
[BUG_SP] Unloader driving to combine even when pipe in fruit

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2292]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Fruit avoidance set to activated in combines and unloader. Btw, and unload in first headland is deactivated.

**Actual behavior**
When leading combine is in first lane of a new land, and the 80% threshold for unloading is in reach, unloader now calculates path and drives to the combine. Resulting in unloader heaving to go through the fruit. And due to this this also results in highly increased risk for colliding with other combines.
Log says "pipe is not in fruit at 889. If it is towards the end of the row, bring it up a bit" - maybe that's the reason for the behaviour. On screenshots you can see that pipe clearly is in fruit at that waypoint, with nearly a km still to go for the combine until this is not the case anymore.

**Expected behavior**
Pipe in/outside fruit should be judged correctly, so unloader will still ignore this combine as long as the pipe is in fruit, and the pocket for unloading has not been created. On headlands it seems to still work, and all combines are ignored as long as pipe is in fruit with above settings.

**Screenshots**

![fsScreen_2023_02_07_10_53_04](https://user-images.githubusercontent.com/71030138/217227627-69b8e13e-7b3b-4fcc-94e5-8af5b3b1fb03.png)
![fsScreen_2023_02_07_10_53_10](https://user-images.githubusercontent.com/71030138/217227753-ebbe6836-3eb2-4881-bda4-340a0efde4ec.png)

**Courseplay version**
Version used: 7.2.0.0

**Log**
Logfile with debug activated for leading combine and unloader.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10674329/log.txt)

**Map**
Landkreis Rostock

**Vehicles/ implements involved**
Which vehicle or implement? Mods Claas Lexion 5300-8900, and Annaburger auger wagon
Mod yes/no ? both yes, but doesn't look like mod issue.

**Relevant script mods**

**Comment by blubstar86** [comment]
Oh thats interesting.

I have noticed when i allow them to go through fruit then my CP unloader always waits till the combine is 95% full and stops to call the unloader, when in first row of lands.

Maybe only the settings switch is just wrong?

**Comment by rohne83** [comment]
seems to be the case only for multitool courses. With only one combine I don't have this behaviour either

**Comment by pvaiko** [comment]
Yeah, our "pipe in fruit" map does not work with multitools.

**Comment by blubstar86** [comment]
So could you allow the unloader to drive through fruit when i choose the setting to allow it?

**Comment by Tensuko** [comment]
We never call an unloader into the fruit because it will stay there and block the combine. It would need more more special movements for the unloader to get out there and that isnt rly necessary. Drive trough fruit is just for the pathfinder not when and where to call the unloader.

**Comment by blubstar86** [comment]
Ok, but the unloader will stay in the fruit anyways when combine pockets are disabled.

So i guess i have to enable pockets again, i disabled them to get the unloader faster to combine when in first headland.

Thanks for the explanation

**Comment by Tensuko** [comment]
Pockets are controlled by avoid fruit in combine.
Call an unloader on first headland is default on and is called unload combine on first headland. That can be turned off when there is not enough space arround the field.

**Comment by kwguk** [comment]
Im getting the same with a single combine cutting in Lands. Its also leaving small bits when it restarts
![20230316172640_1](https://user-images.githubusercontent.com/11178621/225708534-1c034422-62e1-4d7a-bf82-80ebbe708619.jpg)
I seem to remember in previous FS versions the combine would back up a little so it avoided missing any on a restart
