### ISSUE TITLE
[BUG_SP] New course visibility option drifts when restarting course

### ISSUE THREAD

**Issue by Efratror** [Courseplay/Courseplay_FS22#2295]
**Steps to reproduce**
Start and stop courseplay a few times when running a course. It doesn't matter if you use "nearest waypoint" or let autodrive restart the course after hitting a waypoint. For now I've only seen it on courses with multiple tools active(2 tools), but i haven't run single tools for a while.

**Actual behavior**
After a few times restarting the course the "new course visibility option" starts drifting ahead of the current waypoints.

**Expected behavior**
The "new course visibility option" should stay at 20 waypoints a head and 5 in the past.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/19653269/217602419-ece499af-f635-4940-b137-ef93d83fc1b8.png)

**Courseplay version**
Version used: v7.2.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10688168/log.txt)
See the end for relevant courseplay debug info

**Map**
Deer creek

**Vehicles/ implements involved**
Seen it with combines and tractors.

**Comment by Tensuko** [comment]
Can you make a Video of this?
I did a quick test and could not reproduce this.

**Comment by Efratror** [comment]
I will try, but it won't be easy. The fields are big(like 3 hours of running time) and i let the game run unattended. Only stepping in when a driver gets blocked or something like that. Then reposition the driver and start courseplay again. At that time i'm more busy with repositioning than checking the way points. So i don't know the exact moment when it happens.

I've one big field to be done, probably tomorrow. That field i will screen capture in full and replay to see if i can determine a more precise moment.

Is there a debug option that should be activated, that way i can filter out some unimportant stuff for you.

**Comment by Tensuko** [comment]
Just keep debug on.

**Comment by Efratror** [comment]
here you go, the video. It's a bit long by I've added chapters ;)

Video:
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/nMrBv1oYRko/0.jpg)](https://www.youtube.com/watch?v=nMrBv1oYRko)

Log:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10712917/log.txt)

**Comment by Tensuko** [comment]
Thanks, that helps.
I have an Idea on whats happening but have to verify that.

**Comment by Efratror** [comment]
Wonderful. If you need anything more, just let me know.

**Comment by Efratror** [comment]
Hmm just one more thing: The waypoints current/total also seems to be off. See images below. Tractor 1 has more waypoints in total and is like a 100 our so ahead of tractor 2 but they are closer than 100 way points apart from each other.


![Screenshot](https://user-images.githubusercontent.com/19653269/218278418-5104e646-5c48-434b-ae71-09a5f8c62f58.png)

![Screenshot2](https://user-images.githubusercontent.com/19653269/218278404-2e5921b7-ee18-4db7-a384-9e5c0e7da5bb.png)

**Comment by Tensuko** [comment]
Becouse the inner course is shorter than the other.
That is why the display drifts. Not sure how we change that, or even if we do that and turn off this visual mode for multitool course.

**Comment by Efratror** [comment]
Sounds like you are generating courses internally for all the tools? Is it possible to display all these courses in different colors our maybe only display the course belonging to the tool instead of the main course? I would be a bit sad if the visual mode is turned off for multi-tool courses because it makes replacing a vehicle so much easier.

**Comment by Tensuko** [comment]
We have to check on what we do.
Patient.
It is not a top priority Issue.
