### ISSUE TITLE
Wegpunkte[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2298]
Hallo
Was muss ich einstellen damit alle Wegpunkte wieder angezeigt und nicht nur ein Strich
![Wegpunkte](https://user-images.githubusercontent.com/47453761/217888302-8309cf85-16c2-49bb-ba82-9831b3eb5c31.png)
![Weg](https://user-images.githubusercontent.com/47453761/217888527-c6d3e584-7554-45c2-beb3-5ec63bbd8c6d.png)

**Comment by Tensuko** [comment]
Das Auge im HUD stellt die Anzeige um.
