### ISSUE TITLE
Range on wageModifier Vaule?/Suggestion

### ISSUE THREAD

**Issue by pops64** [Courseplay/Courseplay_FS22#23]
What is the range on the wageModifier in settings xml file generated for CP? I don't like paying my workers and when I tried zero FS22 crashed. Bring back the yes no question to this setting would be nice

`2021-12-24 09:10 :01 [info lp487] Loading vehicle configuration from C:/Users/Ryan/Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml ...`
`2021-12-24 09:10 :01 [info lp487] Vehicle configuration file C:/Users/Ryan/Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml does not exist.`
`2021-12-24 09:10 Error: Running LUA method 'loadSharedI3DFileFinished'
dataS/scripts/gui/elements/MultiTextOptionElement.lua(138) : bad argument #1 to 'min' (number expected, got nil)`
`2021-12-24 09:10 Error: failed to create placed resource (ImageAllocation)`
`2021-12-24 09:10 Warning: Texture reallocation failed`

**Comment by Tensuko** [comment]
> Bring back the yes no question to this setting would be nice

Ppl wished for a ranged modifier, so we will keep it, as 0 is off, everything else is on ofc.

So far I had no problems with the wage setting.
Complete logfile ?

**Comment by pops64** [comment]
I tried 0 and that is what caused my FS22 to crash.  Setting it back to one fixed it [log](https://pastebin.com/jFR6iWEf)

**Comment by schwiti6190** [comment]
@pops64 What exactly where you trying to do ?

**Comment by pops64** [comment]
I was trying to set the wages for the worker to zero. `<GlobalSetting value="1" name="wageModifier"/>` I figured that adjusting this value to zero would achieve that. The game would no longer launch after setting this to zero. When set to 1 the game launched fine.

**Comment by Tensuko** [comment]
I got the value down to 0 and can start my game just fine.
Version ? logfile ?

**Comment by pops64** [comment]
Best guess is the vehicle config xml if it still exists is what is making yours launch and mine not. Something in there error checks the nil value. They still don't have the GDN for FS22 so I can't tell for sure.
`2021-12-24 09:10 :01 [info lp487] Vehicle configuration file C:/Users/Ryan/Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml does not exist.
2021-12-24 09:10 Error: Running LUA method 'loadSharedI3DFileFinished'.
dataS/scripts/gui/elements/MultiTextOptionElement.lua(138) : bad argument #1 to 'min' (number expected, got nil)`

This is from the [log](https://pastebin.com/jFR6iWEf) I posted earlier and I retested it again a few days ago and same error. I am on mobile data right now and can't update FS22 to the latest until I am home

**Comment by Tensuko** [comment]
Sry buddy but you seem to be the only one who got into that Issue so far.
Might be a problem of an early version.
When you are back home, try to check newest version.
It shouldn't be an Issue. Maybe also try to remove CP from save, remove CP files from save and then put it back in.

If it stays, reopen Issue, thank you.
