### ISSUE TITLE
[BUG_SP] Ropa Tiger issues

### ISSUE THREAD

**Issue by DMunkov** [Courseplay/Courseplay_FS22#230]
**Steps to reproduce**
Ropa Tiger to harvest sugar beet on field 33 (not sure if that matters).

**Actual behavior**
Set up with 2 headland passes on field 33, does headlands and gets stuck in epileptic seizure (check the video, this was second attempt). 

**Expected behavior**
Field 33 collected

**Screenshots**
![image](https://user-images.githubusercontent.com/24708050/147639850-72fc4ed5-960f-4038-96e8-00c3d978782a.png)
Video: https://www.youtube.com/watch?v=KZNjAkrjO_s

_Edit after another attempt with removing headlands from the course:_ 
Video2: https://www.youtube.com/watch?v=6J0VQBw7ra4

**Courseplay version**
Version used: 7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7787832/log.txt)

_Edit after another attempt with removing headlands from the course:_ 
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/7787860/log2.txt)

**Map**
Haut

**Vehicles/ implements involved**
No nodded implements/vehicles

**Relevant script mods**
N/A

**Comment by Manyak007** [comment]
same problem

**Comment by Tensuko** [comment]
Can someone of you provide me a savegame ? The Course is not needed but a prepared field with the Tiger infront of it. That would be helpful, thanks.

**Comment by DMunkov** [comment]
Hope half of the field would do, I haven't tested with CP since then.
https://www.dropbox.com/s/abu6ld67i2v9zt8/savegame2.zip?dl=0

**Comment by Tensuko** [comment]
Thank you, will have a look when I got time.

**Comment by SAM24986** [comment]
> Thank you, will have a look when I got time.

Den Ropa Maschinen fehlt dieser Eintrag in der xml: `<allowTurnBackward value="false"/>`
Ob die mit "true" als Eintrag dann auch Rückwärts wenden habe ich nicht probiert, so wenden sie aber vorwärts ohne Probleme, allerdings sollte das Vorgewende groß genug sein

**Comment by SAM24986** [comment]
So, jetzt nochmal genauer getestet, schreibt man als Zustand "true", dann kann CP damit nicht um. Dem Helfer aus dem Spiel ist das egal, der dreht auch rückwärts wenn die ganze Zeile fehlt.

**Comment by abredenbals** [comment]
Das selbe problem ("zittern" beim rückwärts fahren und nach einigen Sekunden geht CP aus) besteht auch beim ROPA Panther.
