### ISSUE TITLE
[Question] Horizontal & Vertical Offset Options on Vehicles Greyed Out when a Plow is connected

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#2301]
Simple question really and would be interested to know what is the reasoning behind having the Horizontal Tool Offset and Vertical Tooloffset settings in the Vehicle Settings Menu being Greyed out an Inaccessible only when you have a Plow Attached to your vehicle?

<img width="1920" alt="2023-02-08" src="https://user-images.githubusercontent.com/13921716/217962317-43409a9c-8c9a-488b-b91a-4f5d2aedce7b.png">

For all other tools and pieces of equipment when connected to a tractor these options are available for the player to customise and tweak for whatever reason they may have. Yet the Plow seems to be the only tool where player's can't alter these options, just curious to know if this is intentional behavior or some oversight in the mod and it's been accidentally missed being implemented for tools classed as and recognized as a Plow.

**Comment by Tensuko** [comment]
Becouse it is dynamic calculated on purpose.
For vanilla plows and real plows it is working correct and for that one mod plow from I think vertex or blacksheep (cant remember) as well.
So when a mod doesnt fit its a mod issue and we mostly find that on "plows" so no real plows but cultivator with wrong placed ai markers.
We dont want to change that.
