### ISSUE TITLE
Fehlerhafte Übergabe von AD an CP bei Konvoi Feldarbeit[BUG_SP]

### ISSUE THREAD

**Issue by Uelmer34** [Courseplay/Courseplay_FS22#2307]
Wenn Fahrzeuge per Autodrive zum Feld geschickt werden und per Konvoi Feldarbeit erledigen sollen (Links 1 / Mitte / Rechts 1), dann werden die Spuren nicht von CP angefahren. Stattdessen fahren die Fahrzeuge alle auf der Original CP Spur (Mitte).

**Comment by Tensuko** [comment]
Savegame einmal ohne cp laden und speichern, dann mit cp laden.
War ein bug.
Und das nächste mal template ausfüllen
