### ISSUE TITLE
Grubber senken in der Wende

### ISSUE THREAD

**Issue by SaschaLie** [Courseplay/Courseplay_FS22#231]
Hallo
Mir ist aufgefallen, daß manche Grubber in der Bahnwende schon absenken. Weiß nicht, ob es an den Knicklenkertraktoren liegt, oder an den Grubbern. Auch ein Problem: Alle fahren beim Starten gezielt zu dem Stoppunkt und wollen da anfangen zu Grubbern.
Bild1: Der Grubber Kompaktomat 1570Max mit Knicklenker
![grub2](https://user-images.githubusercontent.com/96572157/147643644-ebb2b608-696f-426d-b433-90e640d4af10.jpg)
Bild2: Der Grubber NZ Extreme 1425 mit Knicklenker. Beide Traktoren fahren die Wende in einem durch ohne Rückwerts zu setzen
![grubber1](https://user-images.githubusercontent.com/96572157/147643728-3938ba4b-ccf6-4e75-8f38-a692d373239b.jpg)
Bild3: Der Grubber Prolander 7500 ohne Knicklenker funktioniert
![Gru3](https://user-images.githubusercontent.com/96572157/147643845-751b30d1-f523-498b-88ab-705291e42625.jpg)
Bild4: Der Grubber Allrounder Flatline 600 ohne Knicklenker funktioniert. Beide Traktoren setzen vor der Wende ein Stück zurück
![Gru4](https://user-images.githubusercontent.com/96572157/147643950-ba12c206-ff9e-480b-854c-a0a8b78a6269.jpg)

CP-Version: 7.0.0.9
Hier die Log zum NZ Extreme 1425: 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7787987/log.txt)
Hier die Log zu den Prolander 7500 & Allrounder Flatline 600:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7788010/log.txt)

**Comment by Tensuko** [comment]
Und ist das Feld hinterher schlecht bearbeitet ?

**Comment by rohne83** [comment]
Versteh auch nicht was hier verkehrt sein soll. Sieht doch alles gut aus. Wenn dir der Grubber zu früh einsetzt kannst das vielleicht noch mit der Einstellung Tool absenken auf spät etwas verzögern, aber besser früher absenken als am Ende unbearbeitete Flächen übrig zu haben.
Und dass ohne Rückwärtsfahrt gewendet wird wenn der Platz dafür ausreicht ist gewollt. Rückwärtsfahrt nur wenn nötig, also wenn zu wenig Platz im Vorgewende bei aktivierter "Wende auf dem Feld".

**Comment by Tensuko** [comment]
Und wenn der Wenderadius zu groß ist, was bei Knicklenkern eben der Vorteil ist...
Ich mach hier zu, Kein Bug und sieht erst mal gut aus.

**Comment by SaschaLie** [comment]
Grubber senken steht auf spät, anheben auf früh. War ja nur ein Hinweis. Hätte ja evtl. ein Fehler sein können.
