### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#2310]
Hallo, bitte helfen Sie, das Problem zu lösen, ich schicke ein Auto mit einem Kalkstreuer mit courseplay auf das Feld, das Auto isst und in der Mitte hält das Feld an und schreibt, dass es blockiert ist, obwohl es auf dem Weg nichts gibt? Vielen Dank im Voraus.
![2023-02-12_23-41-38](https://user-images.githubusercontent.com/116440748/218335987-2b18d2f6-dab0-476e-85a3-5477585976bd.png)

**Comment by Tensuko** [comment]
What vehicle is it? I have to try it on my own.

**Comment by goldorel** [comment]
Hier ist ein Link zu diesem Mod. https://farmingsimulator22mods.com/zil-pack-version-v2-5-fs22/

**Comment by Tensuko** [comment]
Sry but this website is known for stolen mods and bad converted mods.
No support is given. Sry!
