### ISSUE TITLE
[BUG_SP]  Game freezes when closing down map

### ISSUE THREAD

**Issue by Symbob** [Courseplay/Courseplay_FS22#2315]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

Close the savegame

**Actual behavior**
A clear and concise description of what happen.

When closing down the savegame the game freezes displaying a strange image of the map terrain.  This happens when using v7.2.0.1.  The game shuts down correctly if I revert back to v7.2.0.0

**Expected behavior**

The game should close down as normal and return to the Main Menu

**Screenshots**

![20230214_175550](https://user-images.githubusercontent.com/18528850/218825708-11557557-a640-493c-9487-75a52f4c7df8.jpg)

**Courseplay version**
Version used: 7.2.0.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10735728/log.txt)

**Map**
Map played on.

No Mans Land

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

Not specific to any particular vehicles.  In fact once I removed all my mods I only had one vehicle left on the map, which was the in game big Claas combine

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Autodrive installed but disabled

**Comment by timmi4026** [comment]
Genau das gleiche habe ich auch seit der Version 7.2.0.1, die Kamera geht unter die Map und das wars.

**Comment by iljarogoff** [comment]
Hier gleicher Fehler!

**Comment by Tensuko** [comment]
Why on earth did you rename the mods?
Available mod: (Hash: 7ae7a7ff817f81718e788daa9fc6320c) (Version: 2.0.0.9) zzz_autodrive
Available mod: (Hash: 4ffcc0237772be0148a40a5fc148c0f0) (Version: 7.2.0.1) zzz_courseplay

Dont do that!

**Comment by Tensuko** [comment]
The Error is related to the game source, I hadbthat once during infonished release state but should normaly be gone.
Will have a look if I find out whats wrong.

**Comment by iljarogoff** [comment]
Hier noch ein log u. screen, falls es dir weiterhilft.
![fsScreen_2023_02_15_06_21_30](https://user-images.githubusercontent.com/21023840/218981081-279474e5-5056-4e67-9fca-80d1b9fc7432.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10741188/log.txt)

**Comment by regs1980** [comment]
@iljarogoff es liegt nicht an CP, spiele die Map auch und bei mir müsste es ja dann auch passieren. 
Habe sogar alle CP Arbeiter aktiv gelassen bei speicher und schließen.
Der lua Error kommt von der AD RC Version, sonst keine Fehler.

Mein log
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10742048/log.txt)


@Tensuko Was ich komisch finde, ist der log vom TE.

geladene Mods

<img width="807" alt="2023-02-15 11_40_47-C__Users_Bob_Desktop_log txt - Notepad++" src="https://user-images.githubusercontent.com/13314443/219006422-69cb41cc-cb69-4792-90b3-6bcd109f5ba9.png">

Mods, die im Spiel auftauchen aber nicht in der Map verbaut sind.

<img width="1197" alt="2023-02-15 11_40_23-" src="https://user-images.githubusercontent.com/13314443/219006625-3a301542-4408-40b2-835c-1842aa6c8aad.png">

**Comment by iljarogoff** [comment]
@regs1980 
Sobald ich CP aus den Mods nehme, oder durch die 7.2.0.0 ersetze, tritt der Fehler nicht auf. Es passiert ausschließlich mit der 7.2.0.0. Ich hab keine Ahnung wie du drauf kommst, dass es mit AD zu tun hat, zumal ich davon kein RC habe sondern die "offizielle" 2.0.0.9?

**Comment by Tensuko** [comment]
Bleibt mal entspannt, wenn ich Zeit habe schaue ich woran es liegen kann.... Fakt ist ich hatte das auch zwischendurch nur nicht mit aktuellem Stand. Welche Kombi da zusammen trifft muss man sehen.

**Comment by Tensuko** [comment]
Reproduction:
- Open AI Map
- Leave game using the UI

**Comment by Symbob** [comment]
> Why on earth did you rename the mods?
> 
> Available mod: (Hash: 7ae7a7ff817f81718e788daa9fc6320c) (Version: 2.0.0.9) zzz_autodrive Available mod: (Hash: 4ffcc0237772be0148a40a5fc148c0f0) (Version: 7.2.0.1) zzz_courseplay
> 
> Dont do that!

OK sunshine, don't get your knickers in a knot!  It's a historical thing that I've always done since earlier versions of the mod in previous versions of FS!  If you look back at the history of CP you'll see that it was advised to name the mod in this way so that it loaded last.  Having it load before some other mods used to cause conflicts so this was the recommended way of doing it.  I understand that this may not be necessary now but, with all due respect, I'll name mods however I choose and don't appreciate being "told off" for doing otherwise.  What difference does it even make?  You can clearly see that that it's courseplay!! 

Thanks for the fix

**Comment by Tensuko** [comment]
Since FS19 it is nonsen e to rename it.
It can even cause problems!
Things changes and we are not in 2009...

If you name it like you want, dont ask for help with modconflicts. They are often checked by their filename!

**Comment by Symbob** [comment]
I don't come here for help, and I don't get any mod conflicts.  I come here to report bugs to help you guys improve a brilliant mod.  I'll not bother next time because your attitude helps no one.  If you have some good advice to give someone then there's ways to do it without the condescending attitude.
