### ISSUE TITLE
[Feature] Combineunloader Disable fruit avoidance if pathfinder fails

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#2316]
**What is the problem this feature/enhancement solves?**
When playing on large maps the combine unloader (tractor with augerwagon) often fails to find a path to the trailer.
If i disable fruit avoidance it will find a path with no problems. 

**Describe the solution you'd like**
I would like to disable fruit avoidance if the pathfinder fails.

**Describe alternatives you've considered**

**Additional context**
In the log courseplay made a path with fruit avoidance turned off. And a failed attempt with fruit avoidance turned on 

![Farming Simulator 22 Screenshot 2023 02 14 - 21 34 51 89](https://user-images.githubusercontent.com/85753728/218862571-4c97d4d1-0e0d-4dcf-abd6-db9640f5dc60.png)
![Farming Simulator 22 Screenshot 2023 02 14 - 21 35 09 63](https://user-images.githubusercontent.com/85753728/218862573-7d21cedf-fdd0-4cb4-ae79-c499bc2ac714.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10736859/log.txt)

**Comment by Tensuko** [comment]
@pvaiko did we not had this in already?
But I would rather have this in option like:
Avoid fruit on/off/when pathfinder fails or somehow.

**Comment by pvaiko** [comment]
We have it when searching for a path to the combine. When finding path to self unload, we just give up and stop the job. We can add something to retry it once without fruit avoidance.

**Comment by Martin-L45** [comment]
That sounds perfect. It almost always finds a path to the combine with crop avoidance turned on, and if it fails it is usually because the trailer is parked in a bad spot.
