### ISSUE TITLE
Square Headland Corners [Feature]

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2319]
**What is the problem this feature/enhancement solves?**

When using a plough the headland options are not good enough. As the plough tries to turn a corner and misses patches, please see below image. MY corners were set on sharp, which isn't good enough.

![fsScreen_2023_02_15_13_36_12](https://user-images.githubusercontent.com/122838698/219042812-7d84df4e-86c9-4ccf-bd7f-8d65140a1480.png)

**Describe the solution you'd like**

Would like the option to have square corner settings just like a real life tractor guidance system has. This would have to be for any corner over a certain radius I would think. So the machine would pull straight out at the corner, back up change direction and continue. Would also be useful for combine's and forage harvesters - as in real life you wouldn't turn a tight corner with a combine, you'd pull forward to the hedge and then take another run, then turn the machine and carry on. (I drove a combine for 6 years and have done my fair share of ploughing). This would make things more realistic and prevent having to manually finish off a field checking for misses. I do believe your forager and combine mode might actually do some of this as I've witnessed it performing a tight corner just in this fashion last night. But not for other implements it seams. 

![fsScreen_2023_02_15_13_36_121](https://user-images.githubusercontent.com/122838698/219043833-fd6252d8-8944-4d76-ab82-a18469b43a27.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
We see what we can do with the generator 2.0 wich takes more time.
We wont generate course outside the field, but we can check about forced aharp corners.

**Comment by coatsy35** [comment]
Excellent. Love the mod by the way, just started life with FS22 and Courseplay is a must. Forced sharp corners sounds ideal if it's possible.

**Comment by coatsy35** [comment]
> We see what we can do with the generator 2.0 which takes more time. We wont generate course outside the field, but we can check about forced harp corners.

Are you any further towards generator 2.0 as you described it? would love to see forced square corners make an appearance as this would be how most corners would be done and keep things nice and neat and tidy when drilling and cultivating. The off time a field is square it just works so well, so to be able to use it on not so square fields would be brilliant. 

The way a combine now handles corners is fantastic as well btw.
