### ISSUE TITLE
Wie wendet der KI den Pflug?[BUG_SP]

### ISSUE THREAD

**Issue by timme1896** [Courseplay/Courseplay_FS22#232]

**Comment by Tensuko** [comment]
Automatisch

**Comment by timme1896** [comment]
manchmal irgendwie nicht, aber wenn ich das vorgewende auf mindestens vier einstelle klappt es

**Comment by Tensuko** [comment]
Kommt noch ein fix dafür, ist aber W.I.P. dann sollte es hoffentlich klappen.
