### ISSUE TITLE
No headline (maybe unloader questions?)

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#2321]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
Good morning,
I play on Clarkson Map, on the big field N°1
I use 3 harvesters and 4 transporters and I have a few problems:
- The pipe of some overloaders does not lower enough on the trailer and does not empty.  (Picture1) It should be possible to adjust the position of the overloader pipe when emptying (as in FS19)
- When a overloader is emptying, if a second one should arrive, it stops automatically. So I have to restart the courseplay
- After emptying, the overloader does not advance far enough to make room for the 2nd who wants to empty (picture2)
- When a overloader approaches the harvester to unload it and/or trailers to empty, I have a huge FPS loss. The FS19 version was less intuitive, but I think, less greedy in FPS... Besides, I deactivated the "avoid crops" otherwise, it's unplayable ☹

**Screenshots**
![image](https://user-images.githubusercontent.com/36656729/219085898-9b3ff237-e8fb-4566-b655-f066f39b3cb4.png)
![image](https://user-images.githubusercontent.com/36656729/219086000-46fdff16-f335-48fb-a655-ca72b1692a5e.png)

**Courseplay version**
Version used: 7.1.2.6. because with the lastest version, i have the same problem with #2315 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10745114/log.txt)

**Map**
Map played on.
Clarkson map

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
> The pipe of some overloaders does not lower enough on the trailer and does not empty. (Picture1) It should be possible to adjust the position of the overloader pipe when emptying (as in FS19)

Manual teaching won't be added. Wrong position is else a problem of the auger wagon or the trailer.
There might be combinations that doesn't work together.

> When a overloader is emptying, if a second one should arrive, it stops automatically. So I have to restart the courseplay

Same target? Same position? I need more Information about that situation.

> After emptying, the overloader does not advance far enough to make room for the 2nd who wants to empty (picture2)

We advance already far, but in general also with the other problem I think you may have too many unloaders driving in a too high frequenzy.

> When a overloader approaches the harvester to unload it and/or trailers to empty, I have a huge FPS loss. The FS19 version was less intuitive, but I think, less greedy in FPS... Besides, I deactivated the "avoid crops" otherwise, it's unplayable ☹

It is completly the other way round.
The FPS drop in FS19 was WAY harder then in FS22 now and we won't touch it couse the FPS loss compared to the higher time the pathfineder needs is in a good balance with its interval calculation.

**Comment by Crinouche** [comment]
All this is a shame, because for me it works less well than for FS19! :(
Thank you anyway for your answer.
(Sorry, forgot to put a title)
You can close this topic
