### ISSUE TITLE
[BUG_SP] - Drescher selber abtanken / horizontaler Versatz führt zu Kollision 

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#2324]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Problem tritt mit Lexion 650 und mit Lexion 8900 auf. (Vermutlich mit jedem Drescher)

**Actual behavior**
Beim Dreschen im Verband mit zwei verschiedenen Schneidwerken (6,8m und 13,8m) stelle ich einen horizontalen Versatz von -1,7m ein (6,8m links / 13,8m rechts / Kurs ist mit 2x Arbeitsbreite 10,3m berechnet). Der negative horizontale Versatz führt dazu, dass die Drescher mit dem Schneidwerk in den Abfahrer fahren bzw. bei paralleler Anfahrt zu weit links stehen und das Abladerohr nicht den Abladetrigger des Anhängers trifft.

**Expected behavior**
Beim Anfahren des Abfahrfahrzeugs sollte der horizontale Versatz nicht berücksichtigt werden. Ohne horizontalen Versatz funktioniert das Abtanken prima.

**Screenshots**
![Farming Simulator 22 Screenshot 2023 02 15 - 20 29 31 92](https://user-images.githubusercontent.com/76711921/219148062-e99bae4f-f267-4caa-a9e5-1d01a7c156cd.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 31 29 63](https://user-images.githubusercontent.com/76711921/219148069-a29ef175-b174-45a1-9ead-9a14e8dc66a6.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 31 50 34](https://user-images.githubusercontent.com/76711921/219148072-8bd89947-91fd-4b66-849d-deb5782900d1.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 31 52 47](https://user-images.githubusercontent.com/76711921/219148076-3d68704d-021b-4501-9295-d96aa4852388.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 32 02 11](https://user-images.githubusercontent.com/76711921/219148080-d7238e58-d947-4502-adc6-3fbe9a5e65dc.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 38 02 27](https://user-images.githubusercontent.com/76711921/219148084-c2929d10-d672-4cad-a75e-79f05c7a3c05.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 43 19 91](https://user-images.githubusercontent.com/76711921/219148094-a2e45179-fc1c-4860-b55e-01d99938e5fb.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 43 24 07](https://user-images.githubusercontent.com/76711921/219148099-6cf7506b-a02c-48b3-914c-bd884b434f67.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 43 30 58](https://user-images.githubusercontent.com/76711921/219148107-482778d5-7aed-4c01-affa-2f336927bdf9.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 46 54 29](https://user-images.githubusercontent.com/76711921/219148111-4e66976a-add9-4441-a76a-c874d519a567.jpg)
![Farming Simulator 22 Screenshot 2023 02 15 - 20 47 21 92](https://user-images.githubusercontent.com/76711921/219148114-74ca94e4-5d74-40bb-809e-887dad52b65a.jpg)

**Courseplay version**
Version used: 7.2.0.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
MountainHills V6

**Vehicles/ implements involved**
Which vehicle or implement?
Lexion 8900 / Base Game
Lexion 600 / Mod
Mod yes/no ?

**Relevant script mods**
AD / VCA

[log_CoursePlay-Issue.txt](https://github.com/Courseplay/Courseplay_FS22/files/10747268/log_CoursePlay-Issue.txt)

**Comment by Tensuko** [comment]
Selber abtanken ist nicht direkt unterstützt von multitool, aber vlt können wir den offset dafür komplett ignorieren weil das sowieso nicht sinvoll ist.
