### ISSUE TITLE
[BUG_SP] Combine Unload not working

### ISSUE THREAD

**Issue by RFARMS** [Courseplay/Courseplay_FS22#2331]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Went to use unload, it showed up as a option went unhooked from auger cart but then it disappeared from mini menu.
**Actual behavior**
A clear and concise description of what happen.
Cannot use unload combine mod as it goes to silo bunker mode when connected to auger cart.
**Expected behavior**
to be able to use auger cart on unload combine mode.
**Screenshots**
![1248130_20230213214628_1](https://user-images.githubusercontent.com/123046341/219506603-5fe36c2a-8848-43d2-af02-478f304a825b.png)

![1248130_20230213214639_1](https://user-images.githubusercontent.com/123046341/219506659-dc3dda5f-c22f-4396-aff3-4ec77efde762.png)

**Courseplay version**
Version used: 7.2.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. midwest horizion

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
American 2018 series 8rt and brent 1396
**Relevant script mods**
Mods like Autodrive or VCA and so on.
auto drive

**Comment by Tensuko** [comment]
Mod Issue.

I don't know why modder put a capacity into the tractor....

Not a CP Issue.
