### ISSUE TITLE
[Question] was hat bzw fehlt diesem grubber:

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2333]
Hallo Leute
Ich hab da mal ne Frage, und zwar gehts um diesen grubber:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=230799&title=fs2022
Erstmal - mit CP, aktuelle main ausm github, funktioniert der einwandfrei.
Aber wenn ich den mit dem giants helfer fahren lassen möchte, fährt er bis zum Feldende, hebt an und wartet, mit aktivem helfer, auf den sankt nimmerleinstag.
Habs schon durchgetestet, mit leerem modsordner, nur die pdlc's, auf erlengrat, versucht: wendet einwandfrei.
Geb ich CP in den modsordner und versuchs wieder bleibt der giants helfer am feldrand stehen und wartet.
Hab im giants forum auch schon nachgefragt:
https://forum.giants-software.com/viewtopic.php?t=198068
Irgendwas hat der grubber bzw fehlt dem, denk ich, in der xml was das wenden verhindert.
Komme aber nicht drauf was das sein könnte.
Ev hat jemand von euch eine idee bzw lösung.
Cp-log hab ich nicht, da ja der giants helfer aktiv ist, es steht aber kein error, warning oder info diesbezüglich drinnen.
Lg
Andreas

**Comment by Tensuko** [comment]
#2332
Da ist irgendwo was komisch.
Es sollte auch nur passieren wenn du drin sitzt.
Verstehe zwar nicht warum man Giants AI nutzt wenn man eh CP hat, aber gut.
Wir sind schon dran zu schauen was das ist.

**Comment by andreasthu** [comment]
ich danke euch
lg
andreas
