### ISSUE TITLE
Unload combine for mod tractors with tank attached joint 

### ISSUE THREAD

**Issue by trevbarn** [Courseplay/Courseplay_FS22#2335]
Unload combine shows up on tractors from custom modding and siid modding that have Fert tank attached joints without an auger wagon attached. After attaching the auger wagon to these mod tractors, the option for combine unload is no longer available.

**Comment by trevbarn** [comment]
![Screenshot (2) 1](https://user-images.githubusercontent.com/96960827/219871498-18cf6fdc-7d52-439b-b1af-0cd688d7ffa6.png)
![Screenshot (4) 1](https://user-images.githubusercontent.com/96960827/219871503-f543e89a-5af9-4d40-9dbf-df8deae6f1fb.png)

New save on elm creek base game map, only mods active are courseplay v 7.2.0.0, SiiD modding's "8R 8RT 8RX 2020", Siid modding's Challenger MT800 Series, and Custom modding's John Deere 8R series.

**Comment by Tensuko** [comment]
Use template for the next time pls.
And yes this is somehow intended by us and I don't know why modder keep use spec Trailer on their Tractors....
