### ISSUE TITLE
Good afternoon, when I'm playing single player and I'm not using courseplay, the original helper of the game when it reaches the end of the field blocks and stops. this when I'm inside the tractor, outside it works correctly. the courseplay helper works correctly.[BUG_SP]

### ISSUE THREAD

**Issue by Farmvile** [Courseplay/Courseplay_FS22#2336]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pvaiko** [comment]
#2332
