### ISSUE TITLE
Bei „Job erstellen“ erscheint falsche Eingabemaske.[Question]

### ISSUE THREAD

**Issue by roland45** [Courseplay/Courseplay_FS22#2339]
Ab Version V7.2 kann ich keine Vorgewende Einstellungen vornehmen, da immer nur die vereinfachte Einstellungsmaske (wie für Plantagen) erscheint, jedoch nicht die größere Maske mit allen Einstellmöglichkeiten. Lade ich die Vorversionen z.B. V7.1.2.4 gibt es kein Problem. Automatisch erscheint bei normalen Feldern die große Einstellmaske, bei Plantagen automatisch die einfachere Einstellmaske. Ist dieses Problem bekannt, oder mach ich etwas falsch.

**Comment by Tensuko** [comment]
Normale Felder = große "Maske" also der normale Kursgenerator.
Bei Plantagen (z.B. Oliven) die für Reeben.

Wo taucht jetzt die "falsche Maske" auf ?
Bild davon?

**Comment by roland45** [comment]
Ja, bei "Normale Felder" taucht die Plantagenmaske für Reeben auf.  Bild hab ich derezeit nicht zur Hand.

**Comment by Tensuko** [comment]
Ich brauch aber ein Bild davon weil ich es nicht nachvollziehen kann.
Weil an sich passiert es nicht, das heist ich muss wissen was bei dir da passiert.

**Comment by roland45** [comment]
OK, werde mich morgen wieder melden. Danke

**Comment by roland45** [comment]
Habe die V7.2 aufgespielt, aber der geschilderte Effekt ist bis jetzt nicht mehr aufgetreten. Alles funktioniert OK. Werde mich wieder melden sollte die falsche Maske bei mir auftreten und dies auch dokumentieren. Besten Dank!

**Comment by Tensuko** [comment]
Ok wenn es wieder passiert, dann melde dich hier und mach einfach das Issue wieder auf (reopen).
