### ISSUE TITLE
[Question] Log Datei voll mit Debug-Daten ?

### ISSUE THREAD

**Issue by ct177mak** [Courseplay/Courseplay_FS22#234]
Moin @ll

Ist das gewollt das die Log_Datei überquillt mit Debug Daten ? oder kann man das abschalten ?? bin mitlerweile bei fast 1MB Dateigröße.
Dabei habe ich keine Debug aktiv hier .Version ist 7.0.0.9 . Thx und guten Rutsch ins neue  Jahr 2022.

**Comment by Tensuko** [comment]
Gibt schlimmeres.... aber ich guck nach und schalte es aus....

**Comment by ct177mak** [comment]
Dank dir :-)
