### ISSUE TITLE
[BUG_SP] cotton harves wait on unload

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#235]
**Steps to reproduce**
waits for unloading when the wool harvester is full

**Actual behavior**
waits for unloading when the wool harvester is full. classic behavior like a combine harvester with a tube

**Expected behavior**
he should drop the bales of wool on the ground and continue working

**Screenshots**
https://user-images.githubusercontent.com/96631209/147587990-aaeab631-c73d-436f-84ff-4fc6b3d4426d.png
wait on unloand

**Courseplay version**
7.0.0,9

**Log**
no error

**Map**
Papenburger 

**Vehicles/ implements involved**
Vehicles vanilla cotton harvest both test

**Relevant script mods**
Mod yes and no

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki
"1. Always update to the latest build and check if the problem really still exists before reporting issues."

**Comment by Manyak007** [comment]
problem is fix 

I'm sorry I didn't notice that there is a new version 7.0.0.9, I had a version 7.0.0.8 and this problem was in the version  7.0.0.7 7.0.0.8

**Comment by Manyak007** [comment]
![image](https://user-images.githubusercontent.com/96631209/147655570-dd701942-f6cd-4e61-890a-b3fec1ad5846.png)

whether it does not work, he did a few lines correctly and he is waiting for the unloading

**Comment by Manyak007** [comment]
![image](https://user-images.githubusercontent.com/96631209/147657490-29b5cddc-e531-4d39-ade7-61d788529f37.png)

second harvest on cotton same problem this only wait on unloand

**Comment by nogach758** [comment]
Version 7.0.0.9 Gleiche Problem.

**Comment by ph1go** [comment]
> ![image](https://user-images.githubusercontent.com/96631209/147655570-dd701942-f6cd-4e61-890a-b3fec1ad5846.png)
> 
> whether it does not work, he did a few lines correctly and he is waiting for the unloading
> 
> as he has both chambers full of wool so he can't unload it

It's strange that you're having this problem with the John Deere, it works perfectly for me with Courseplay. I've done several harvests with it and it drops the complete bale when the next one is ready inside.

**Comment by schwiti6190** [comment]
dupliate of #168

**Comment by Djinfa** [comment]
Same Problem for me in the Version 7.0.0.10. Harvester are Harvesting until 99% full then stopped and do not unload the Bale.

**Comment by radakar** [comment]
Same for me, using Case haverster on field 30 in elmcreek. At 99% full it stops and do nothing but wait.

**Comment by ph1go** [comment]
This just happened to me for the first time too, although as can be seen from the screenshot, he's done plenty of the field unloading properly. It's like he suddenly thinks he's a grain harvester with a pipe on the left and he has to get in the "grain harvester with a pipe on the left position" and back up and pull out to let a trailer in alongside.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7799431/log.txt)

(line 69164 is where he does the `PULLING_BACK_FOR_UNLOAD` move)

![fsScreen_2022_01_02_17_27_27](https://user-images.githubusercontent.com/30246276/147882422-c8fb10af-f74e-4388-8ae4-4123af31d79e.jpg)

**Comment by Tensuko** [comment]
Fix is on the way.

**Comment by ph1go** [comment]
Fyi @Tensuko this is still an issue for me but only very occasionally.

![fsScreen_2022_01_05_12_37_07](https://user-images.githubusercontent.com/30246276/148211752-8ad4bdfe-e886-4c4f-80f8-a367ac0c3d36.jpg)

**Comment by Tensuko** [comment]
I didn't say this is fixed yet.
Just wait for the Release where we tag this Issue...

**Comment by ph1go** [comment]
Sorry, for some reason I thought it was fixed in v7.0.0.12.

**Comment by Tensuko** [comment]
Should work now with .16
