### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by AngryCoprocoder** [Courseplay/Courseplay_FS22#2351]
I'm playing FS22 on GeForce NOW and the Course Editor doesn't work.
When I click the Course Editor button nothing happens. I did not find anything on the Internet about this.
Is this a feature of the mod in GF NOW, a bug or am I an idiot?

**Comment by Tensuko** [comment]
Did you select a course and the open editor?

**Comment by AngryCoprocoder** [comment]
Apparently, I'm an idiot.
The thing is that I tried to open the Course Editor in this way: ESC > COURSEMANAGER > OPEN COURSE EDITOR
But if I press the 'no course' button instead of the ESC button, the editor works. (like in this video https://youtu.be/Bp9aVtqilUc?t=22)
I don't know if everything should work through ESC.

Second stupid question. Is it possible to remove the blue box "Courseplay" (In the upper right corner.) in the main interface?

**Comment by Tensuko** [comment]
That is the Info Panel where "blocked" or "work finished" appear.
And yes you can turn it off in the global settings.

The Coursemanager can be opened by click on the waypoint counter on the HUD.

I suggest you to read the ingame help for more Informations :)
