### ISSUE TITLE
Neue Funktion

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#2356]
Guten Tag, bitte sagen Sie mir, ob es in 
Courseplay FS22 Funktion damit er beim Entleeren der Sämaschine nicht zur Basis fährt, um mit Samen zu tanken, sondern zum Sämaschinen-Tanker fährt, der auf dem Feld steht, das gleiche gilt für Kalk und Dünger? Vielen Dank im Voraus

**Comment by Tensuko** [comment]
Only in combination with AD.
Ingame help shows what is possible.
