### ISSUE TITLE
[BUG] crazed worker

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#236]
**Steps to reproduce**
I created a path for the red stubble chopper for field 45. I created it as I usually do. I put him to work and he does his business by going wherever he pleases.

**Actual behavior**
He started to work poorly by ending up in the nearby field and crashing into a post

**Expected behavior**
I expected it to start work without problems

**Screenshots**
The purple stripe and the purple spot is the work he did.
![fsScreen_2021_12_29_11_51_12](https://user-images.githubusercontent.com/96330304/147655468-767e98f2-8c0a-4838-85b7-9f9328ce2469.png)
![fsScreen_2021_12_29_11_51_49](https://user-images.githubusercontent.com/96330304/147655481-d4946e40-9275-400d-9b2d-62c6bf7a3748.png)
![fsScreen_2021_12_29_11_53_46](https://user-images.githubusercontent.com/96330304/147655488-06ba7837-1332-4982-b619-95f3a64c01fb.png)
![fsScreen_2021_12_29_11_53_54](https://user-images.githubusercontent.com/96330304/147655497-5a0213ae-b591-4553-b877-0ff760d87533.png)

**Courseplay version**
Version used: 7.0.0.9

**Log**
log cut in 2. in the first there is the crazy operation. I didn't have time to activate all the logs who was already going for mushrooms. in the second he completed the work. I noticed that it starts badly and then recovers.
[https://pastebin.com/yBQQ3Hy0](https://pastebin.com/yBQQ3Hy0)
[https://pastebin.com/TA5aqEU5](https://pastebin.com/TA5aqEU5)

**Map**
US standard

**Vehicles/ implements involved**
claas arion 660 and red stubble chopper

**Comment by Markus33-ITA** [comment]
the bug reoccurred.
I created a path whose starting point was a few tens of meters from the end of the field and the tractor was in the opposite direction. I started the work and the worker went around.
[Course_failedWork.zip](https://github.com/Courseplay/Courseplay_FS22/files/7788874/Course_failedWork.zip)
![fsScreen_2021_12_29_13_35_20](https://user-images.githubusercontent.com/96330304/147663012-ccca63cc-74d7-479d-948f-32727bbef4d0.png)
![fsScreen_2021_12_29_13_35_28](https://user-images.githubusercontent.com/96330304/147663023-419f8e91-fbb4-46d5-a4ed-6d82884ab4f8.png)

**Comment by Markus33-ITA** [comment]
I had put the vehicle roughly in that position.
![fsScreen_2021_12_29_13_48_10](https://user-images.githubusercontent.com/96330304/147664123-61cde184-cf5d-4697-bc48-a11ea06a1ab8.png)
![fsScreen_2021_12_29_13_48_30](https://user-images.githubusercontent.com/96330304/147664161-cb7cde04-5b20-4f5c-b229-21c8aef037bc.png)
![fsScreen_2021_12_29_13_49_13](https://user-images.githubusercontent.com/96330304/147664196-a9364d9a-27fe-4ba0-9600-ca89a544bbab.png)

**Comment by Tensuko** [comment]
Should be improoved soon

**Comment by Tensuko** [comment]
Can you try this with 7.0.0.10 ? Thank you.

**Comment by Markus33-ITA** [comment]
I have to try. I didn't have time last night. Sorry

**Comment by Markus33-ITA** [comment]
Hi. Here I am. I did several tests with different jobs and the error never came back.
