### ISSUE TITLE
Bloqué par un objet[Question]

### ISSUE THREAD

**Issue by millepattes2** [Courseplay/Courseplay_FS22#2363]
Hier, j'ai installé la dernière version de courseplay (kingmods) Quand je lance un travail de champs avec courseplay, la machine s'arrête en fin de ligne et me signale; bloqué par un objet. J'ai essayé avec plusieures machines dans plusieurs champs, même problème

**Comment by Tensuko** [comment]
The only download source for CP is ModHub and github, no where else!

If there is an object at the end of the lane, ofc we report blocking, if not, there is something on the map that cause it.

Use more headland or try to use skip row to prevent drive to close to field border.

**Comment by millepattes2** [comment]
Merci pour votre réponse rapide, j'ai fait quelques tests, c'est le tracteur deutz mh edition qui ne fonctionne pas, l'outil le reconnait comme objet.  Je vais telecharger un autre sur le...... modhub.
Bon week end
________________________________
De : Tensuko ***@***.***>
Envoyé : samedi 4 mars 2023 10:26
À : Courseplay/Courseplay_FS22 ***@***.***>
Cc : millepattes2 ***@***.***>; Author ***@***.***>
Objet : Re: [Courseplay/Courseplay_FS22] Bloqué par un objet[Question] (Issue #2363)


Closed #2363<https://github.com/Courseplay/Courseplay_FS22/issues/2363> as completed.
