### ISSUE TITLE
[BUG_SP] Ventor 4150 lässt beim Einsetzen Frucht stehen

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#237]
**Steps to reproduce**
Kurs anlegen

**Actual behavior**
Vektor fährt beim Wenden sehr weit in die Bahnen

**Expected behavior**
Wendemanöver weiter ausserhalb der Frucht durchführen

**Screenshots**
![Vektor wenden](https://user-images.githubusercontent.com/8066324/147667135-ff91e1f3-a8c1-490d-957a-3d0fb7e7c848.png)

**Courseplay version**
Version used: 7.0.0.9 

**Log**

**Map**
Elmcreek Feld 30

Edit: ausserdem fährt er nicht weit genug zurück und lässt dadurch Frucht stehen
![Vektor_2](https://user-images.githubusercontent.com/8066324/147668090-02aef164-2eba-430d-b86b-3a64489d1e36.png)

**Comment by dominiczeth** [comment]
Du solltest viel mehr vorgewende einstellen bei der Arbeitsbreite und der Geräte Länge. Dann müsste auch das wenden klappen und der lässt dann auch nichts stehen. 
Courseplay versucht immer auf dem Feld zu bleiben.

**Comment by rohne83** [comment]
Sieht so aus als ob du Wende auf dem Feld aktiv hast. Für diese Einstellung ist aber wie dominiczeth schon sagt dein Vorgewende viel zu schmal und der Reihenabstand viel zu eng. Bei dem Fahrzeug brauchst du für eine 180Grad-Wende in die Nachbarbahn locker 40Meter Vorgewende. Etwas weniger Vorgewende brauchst du wenn für die Feldmitte spiralförmig oder Beete nimmst, aber auch dann immer noch gute 30Meter.

**Comment by RealNeo80** [comment]
hab ihm jetzt einfach mal 10 Bahnen Vorgewende gegeben, damit ist zumindest das Fruchtplattfahren besser, das Thema mit dem Einsetzten bleibt aber ... 
![Einsetzen_2](https://user-images.githubusercontent.com/8066324/147671956-76f5498a-2f05-4bc7-a23a-d6d0364d9132.png)
auch mit deaktivierem Wenden auf Feld
![Einsetzen_3](https://user-images.githubusercontent.com/8066324/147672233-c9c41042-9b1b-4969-b258-c86e64789c79.png)

**Comment by Tensuko** [comment]
Das stehen bleiben von der Frucht kommt denke ich daher, dass die WorkArea sehr weit vorne ist,
Mal gucken was wir da machen können.

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.
