### ISSUE TITLE
[Enhancement] Don't turn on Slurry tank during approaching target waypoint or during pathfinder turn.

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#2370]
**What is the problem this feature/enhancement solves?**
Slurry tanks are always activated, when a AI helper is employed, this causes the tanks speed limit to apply.
When driving without applying, the tank therefore is limited to 16kph, even when traveling to the last used waypoint or when turning on the headland.

**Describe the solution you'd like**

Deactivate slurrytanks when not applying slurry
Ignore speedlimit when not applying slurry/ when pathinfinder paths are active (aka traveling to last used waypoint or on headland)/ when applicator is folded

Autodrive is also able to ignore the speedlimit

**Describe alternatives you've considered**
Ignore speedlimit when not applying slurry/ when pathinfinder paths are active (aka traveling to last used waypoint or on headland)/ when applicator is folded

Autodrive is also able to ignore the speedlimit

**Comment by Tensuko** [comment]
Thats not the solution to ignore it.
And it is also not the solution to say AutoDrive can do it.

We just have to make sure not to turn on the slurry wagon when still approaching out target Waypoint.

What we do about turns we will check but tools are meant to stay on in turns, however we can check for longer pathfinder turns to turn it off.

**Comment by rohne83** [comment]
Not sure whether it has affect on the speed, but shouldn't it help to raise/lower the attached tools for slurry application?

**Comment by JDTiger** [comment]
> Not sure whether it has affect on the speed, but shouldn't it help to raise/lower the attached tools for slurry application?

that should be the case, but isn't :P

![Screenshot 2023-03-07 110246](https://user-images.githubusercontent.com/9157835/223389834-3732368d-07ab-46d6-932b-d153ebe54e7c.png)
![Screenshot 2023-03-07 110304](https://user-images.githubusercontent.com/9157835/223389850-736e6ebf-c30c-4414-a505-b1a625ecca55.png)

**Comment by Tensuko** [comment]
> Not sure whether it has affect on the speed, but shouldn't it help to raise/lower the attached tools for slurry application?

The problem here is that those slurry trailer work different then other tools.
Also there is no lifting for them :)

Need to have a look what we can do.

**Comment by pvaiko** [comment]
I think we call the Giants aiImplementEndLine() standard function when we finish a row, whatever it does, looks like it does not change the speed limit.
