### ISSUE TITLE
[BUG_SP] Vidhostice map do not load with CP

### ISSUE THREAD

**Issue by Malandilas** [Courseplay/Courseplay_FS22#2371]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

Add Vidhostice map with required mods + CP
 
**Actual behavior**
A clear and concise description of what happen.

Map do not load with CP (always stuck at 85 % in loading screen). Without CP map is working properly.

**Expected behavior**
Map loads with CP

**Screenshots**

**Courseplay version**
Version used: v7.2.0.2 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Vidhostice
ModHub link: https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=263848

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10912017/log.txt)

**Comment by Tensuko** [comment]
Pretty sure its a map Issue with any of the placed bunkers:
2023-03-07 17:57 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
E:/Inne/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/silo/BunkerSiloManager.lua:10: table index is nil

**Comment by Malandilas** [comment]
Well, i'm not a programmer. I saw a reference to Courseplay in the log file and decided to report it. If you can't do anything with it because it is a map issue, it's a shame.

**Comment by Tensuko** [comment]
Next Update contains a nil check so the map should load.
However, this will not fix the issue with the bunker on the map so it might will not work correct.
