### ISSUE TITLE
[BUG_SP] Tiger 6 XL Aufklappen

### ISSUE THREAD

**Issue by Neotras2552** [Courseplay/Courseplay_FS22#238]
**Steps to reproduce**
Mit den Tiger 6 XL ein Feldkurs erstellen und starten lassen ,Cp klappt das schneidewerk auf ander nicht die maschine

**Actual behavior**
Der Tiger 6 XL Klappt sich nicht aus

**Screenshots**

**Courseplay version**
Version used:  V.7.0.0.9

**Log**.
https://pastebin.com/FnjfUwJL ab 14.30

Mods

Autodrive
VCA.

**Comment by Tensuko** [comment]
Duplicate #230
Seems to be a general Issue with Tiger 6.
