### ISSUE TITLE
[Bug] Plow SPSL9 - offset won't get switched to the other side with  Trailed Lifter attached.

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/Courseplay_FS22#2383]
Sorry to reopen this old and closed topic #1137 , but I would like to know if the team has plans to fix the _bug_ that occurs with the Gregoire Besson SPSL9 and Trailed Lifter when using the Big Bud 747.
Course Play is very important for FS22 and I don't have the ability to help with it.

What happens with the Big Bud 747 when using the Gregoire Besson Trailed Lifter is that the horizontal tool offset remains fixed at 2.1 (instead of auto) and along the way, stripes of 10.5m are left unworked, much larger than the images shown above.
Both the Big Bud and the Gregoire Besson SPSL9 are from Giants, obtained from ModHub.

**Comment by MoslessNeo** [comment]
[<script src="https://gist.github.com/MoslessNeo/96575e2beb0fa8054760a337e8bcd14d.js"></script>](url)

**Comment by MoslessNeo** [comment]
No problem with the other plows in the game. But with this plow from Gregoire Besson SPSL9 and using the Trailed Lifter for the Big Bud 747, yes. I did some tests and I'll share the images and the activated log.

These are the settings:
![img_01](https://user-images.githubusercontent.com/6533809/225694479-24f7ff70-7ede-445b-b55f-27b4fc5ade47.jpg)

This is the behavior at the beginning of CP:
![img_02](https://user-images.githubusercontent.com/6533809/225695335-c7204592-bca1-469d-8ed8-dfc0606c0240.jpg)

This is the log of the first few rounds of plowing.
[Log1](https://gist.github.com/MoslessNeo/96575e2beb0fa8054760a337e8bcd14d)

--
Here is an image of how Course Play works with the set and the log.
![img_03](https://user-images.githubusercontent.com/6533809/225695822-e572a265-52e6-4a4d-93e1-8e0c13e39eb6.jpg)

[Log2](https://gist.github.com/MoslessNeo/e85661e8597a323f4541d890e30dd88a)

I tested it on several maps and without any mods, the behavior is the same. I turned "only turning on the field" on/off, set it to skip 1-5 rows, same effect. This had been fixed in earlier versions, but from some version onwards, it started to appear again. I don't always use plowing. If you could review the code with this information I provided, I would be very grateful.

**Comment by Tensuko** [comment]
Found the Issue.
