### ISSUE TITLE
[Feature] Generate field path only one headland

### ISSUE THREAD

**Issue by k4r3l01** [Courseplay/Courseplay_FS22#2385]
Hello please its will be possible to add feature where i generate path only on headland i wanted this for generate paths on AD 
And if its will be possible to make this without attachment behind tractor so i will set width manually like 5m and course will be generate only on headland and 5m from the edge of field.
Thanks in advace for any answer
and sorry for my bad english

**Comment by Tensuko** [comment]
Even when we have something like this added, you won't be able to transfer that over to AD.

Check Editor options, there is a delete all waypoints untill the end. Make start on center then you can get to what you want but how this will help you I don't know.
