### ISSUE TITLE
[Question]why is this happening

### ISSUE THREAD

**Issue by ZeroTetra** [Courseplay/Courseplay_FS22#2388]
https://ctrlv.cz/I2Af

**Comment by ZeroTetra** [comment]
https://ctrlv.cz/CjgD 
Better image

**Comment by k4talin** [comment]
What is the problem there?

**Comment by Tensuko** [comment]
Have no Idea what you want to show us there.
More overview and a description is needed.

**Comment by ZeroTetra** [comment]
that it makes a point where it doesn't

**Comment by ZeroTetra** [comment]
https://ctrlv.cz/gfcX

**Comment by Tensuko** [comment]
And you think with that little Information we can help you?

**Comment by ZeroTetra** [comment]
i have no idea what you need
