### ISSUE TITLE
CP doesnt find drive thorugh silo anymore [BUG_SP]

### ISSUE THREAD

**Issue by Esstisch** [Courseplay/Courseplay_FS22#2392]
Hello,

first, thanks for creating and supporting CP. Awesome tool.

My issue: 
I created a drive thorugh silo for gras. Traktor 1 (T1) delivers gras in there (done with AD), Traktor 2 (T2) drives through and flatten the gras, done with CP.
First both worked fine, for T2 I used the "silo"-mode of the built-in CP menu (extended ai-menu).

After painting the area around the silo with gravel (I might touched the silo while painting) I saved, closed and started later again.
Now, T1 is still working fine. T2 doenst work anymore. The silo is not shown anymore in the overview map in the extended ai menu and when activating the T2, the silo-mode is not displayed anymore. I didnt change anything else (same Traktor, same equipment).
I wonder, what happend to the silo and if I can make it work again?

Attached you can find the log file. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11011878/log.txt)

I use the CP-Version 7.2.0.0

Here is the placeables file as txt
[placeables_text.txt](https://github.com/Courseplay/Courseplay_FS22/files/11011884/placeables_text.txt)

If you need any further info I am happy to provide them. 

BR

**Comment by Tensuko** [comment]
Will have a look, but painting should normaly have no impact on any silo or the trigger area.

**Comment by Esstisch** [comment]
If you need my savegame let me know how to share it here.
Maybe it would make your analysis easier?

**Comment by Tensuko** [comment]
Attach as .zip and what map you use.

**Comment by Tensuko** [comment]
@schwiti6190 Could it be that the Silo have to be placed on a field to be detected?
I can see the markers but when I place the target in the bunker it doesn't light up.
![grafik](https://user-images.githubusercontent.com/27344744/226399431-9e09e6ba-a568-4b97-8cf0-213518ddd482.png)

**Comment by Tensuko** [comment]
No need your savegame, we found the problem.

**Comment by Esstisch** [comment]
Awesome thanks :)
Happy to get the new version whenever its done!
