### ISSUE TITLE
[BUG_SP] Collecting cotton bales with McCormick Cotton Trailer 5000 (semi) fails

### ISSUE THREAD

**Issue by rgoe** [Courseplay/Courseplay_FS22#2393]
**Steps to reproduce**
"McCormack Cotton Trailer 5000" (ModHub) configured as a semi-trailer,attached to MAN TGS 18.500 (Vanilla) on Elmcreek field 32 (or any other), stops collecting cotton bales after the first bale.

**Actual behavior**
Collecting cotton bales aborts after the first bale. (Log: "TGS 18.500 4x4/221: SEARCHING_FOR_NEXT_BALE: Pathfinding failed three times, giving up")

**Expected behavior**
Collecting cotton bales continues until the trailer is full / no more cotton bales in the field.

**Screenshots**

https://user-images.githubusercontent.com/21224499/226487436-f5d4b264-869b-476e-8a1a-83f7356aedee.mp4

**Courseplay version**
Version used:  7.2.0.5

**Log**
[log_7.2.0.5.txt](https://github.com/Courseplay/Courseplay_FS22/files/11022668/log_7.2.0.5.txt)

**Map**
Elmcreek (to reproduce, but issue showed also on other maps)

**Vehicles/ implements involved**
Which vehicle or implement? 
McCormack Cotton Trailer 5000 from McCormack Cotton Trailer Pack (Modhub)

**Relevant script mods**
CP 7.2.0.5, AD 2.0.0.9, EasyDevControls

**Additional Information**
The problem only occurs when the trailer is configured as a semi-trailer or gooseneck, not as a normal trailer.
The problem seems to have started with v7.1.2.5 (had not used the combination for quite some time), with v7.1.2.4 everything is fine.
Since a message in the logfile reads ("...has no wheels, check if anything...") I investigated the matter as far as I could:
Apparently the cause is somehow related to the ImplementUtil.isWheeledImplement function (ImplementUtil.lua) and here with line 108 "local jointTypeList = { "implement", "trailer", "trailerLow", "semitrailer", "trailerSaddled" }".
If I change this line back to the state of 7.1.2.4 (i.e. delete the entry "trailerSaddled") or if I swap the order of the entries (i.e. "semiTrailer" again as the last list entry) it works again.

**Comment by Tensuko** [comment]
trailerSaddled is for example the Claas Saddletrack, that needs to be kept in.
We will have a look.
Thanks for the report and the 1st check of finding the problem.
