### ISSUE TITLE
Cp drives out of the field after turning

### ISSUE THREAD

**Issue by Onkel2000** [Courseplay/Courseplay_FS22#24]
Hey, if CP tries to turn in a sharp spot, it starts to stutter and CP pulls out of the field. You have to fire helpers. It's on a coustom map. The following appears in the log.

```
2021-12-24 15:16 Warning (script): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2021-12-24 15:16   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-12-24 15:16 LUA call stack:
  dataS/scripts/vehicles/ai/AIVehicleUtil.lua (211) : worldToLocal
  =C:/Users/Eike/Documents/my games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIReverseDriver.lua (67) : getDriveDirection
  =C:/Users/Eike/Documents/my games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (97) : getDriveData
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (550) : getDriveData
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (269) : updateAIFieldWorkerLowFrequency
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1877) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (112) : update
  dataS/scripts/network/Server.lua (59) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1180) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update
2021-12-24 15:16 Error: Running LUA method 'update'.
dataS/scripts/utils/MathUtil.lua(207) : attempt to perform arithmetic on local 'x' (a nil value)
```

**Comment by Tensuko** [comment]
Can you make a screenshot of the situation ?
So we can see the course, the tools used and stuff.

**Comment by Onkel2000** [comment]
The Fendt 1050 is used with a K-12200 cultivator


![20211224160452_1](https://user-images.githubusercontent.com/53871930/147361061-826f0b46-3fa9-49c5-9969-49fe9af8a178.jpg)
![20211224160417_1](https://user-images.githubusercontent.com/53871930/147361064-bd7165dd-5e8d-4338-acf0-3862a6073e9a.jpg)
![20211224160423_1](https://user-images.githubusercontent.com/53871930/147361065-ee910a67-1e72-45e5-ae6f-e4c1dedfc411.jpg)

**Comment by ph1go** [comment]
I'm having the same issue, my worker's done a 360 and now he's completely disoriented and leaving the field...
![fsScreen_2021_12_24_16_46_49](https://user-images.githubusercontent.com/30246276/147363035-4db52038-a8f3-4185-b9b0-8095a8b00a0d.jpg)

**Comment by pvaiko** [comment]
The log folks, we need the log. The entire log.

**Comment by ph1go** [comment]
I've looked back to the time in the log when I posted the above and it's exactly the same log entries as @Onkel2000 had...

    2021-12-24 16:49 Warning (script): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil 
    2021-12-24 16:49   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\base\scripting\lua\LuaScriptSystem.cpp (890): expectedType == Value::VoidType || expectedType == Value::ClassType
    2021-12-24 16:49 LUA call stack:
      dataS/scripts/vehicles/ai/AIVehicleUtil.lua (211) : worldToLocal
      =C:/Users/office/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIReverseDriver.lua (67) : getDriveDirection
      =C:/Users/office/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (97) : getDriveData
      dataS/scripts/vehicles/specializations/AIFieldWorker.lua (550) : getDriveData
      dataS/scripts/vehicles/specializations/AIFieldWorker.lua (269) : updateAIFieldWorkerLowFrequency
      dataS/scripts/specialization/SpecializationUtil.lua (19)
      dataS/scripts/vehicles/Vehicle.lua (1877) : raiseEvent
      dataS/scripts/network/NetworkNode.lua (112) : update
      dataS/scripts/network/Server.lua (59) : updateActiveObjects
      dataS/scripts/BaseMission.lua (1180) : update
      dataS/scripts/FSBaseMission.lua (2006) : update
      dataS/scripts/missions/mission00.lua (582) : update
      dataS/scripts/main.lua (1323) : update
    2021-12-24 16:49 Error: Running LUA method 'update'.
    dataS/scripts/utils/MathUtil.lua(207) : attempt to perform arithmetic on local 'x' (a nil value)

**Comment by Onkel2000** [comment]
> 

Sorry It's also on Elm Creek. At first I thought it would also be because of the Coustom Map. Here is the log file. [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7774951/log.txt)
