### ISSUE TITLE
Rowchange with small rake failed

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#240]
**Steps to reproduce**
CP Helper with Kuhn GA 4731 attached. Normal course. Rectangle field. Only Rows or rows after Headland turns

**Actual behavior**
Helper can't change the row https://youtu.be/GJsj6XzIe2g

**Expected behavior**
Should be clear

**Screenshots**
https://youtu.be/GJsj6XzIe2g

**Courseplay version**
Version used: 7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7789249/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Fendt 718 Vario + Kuhn GA 4731

**Relevant script mods**
AD, GPS

**Comment by Tensuko** [comment]
Can you try out what happens with 7.0.0.10 ? Thank you.

**Comment by Tensuko** [comment]
Seems to be fixed.
