### ISSUE TITLE
[Feature] keep current steering settings for vehicles that can do all wheel steer or front wheel steer only

### ISSUE THREAD

**Issue by FarmerNothing** [Courseplay/Courseplay_FS22#2401]
**What is the problem this feature/enhancement solves?**
Having the vehicle come there quickly and with some implements all wheel steering won't benefit

**Describe the solution you'd like**
Courseplay to keep the steering setting you selected with the ctrl+y key and not use the default steering setting

**Describe alternatives you've considered**
Not have courseplay override the setting

**Additional context**
The Lintrac 130 for example will shake left and right when returning to field, slowing it down

**Comment by Tensuko** [comment]
Then we would have to block crap steering as this is something that we would have to change in turn.
We keep this for a later update, but I think we do it a bit different than in FS19.

**Comment by pvaiko** [comment]
I don't think we do anything with the steering. If the vehicle has crabSteering specialization, there is an optional aiSteeringModeIndex (default 1) which the Giant AI sets when a job is started.
