### ISSUE TITLE
[BUG_MP] [BUG_SP]  - Courses for custom fields

### ISSUE THREAD

**Issue by AgrarOekonom** [Courseplay/Courseplay_FS22#2402]
**Actual behavior**
For a few days now I've had the Giants enging crash again and again when creating courses for self-created field borders. Alternatively, an error message appears with the information that no course could be created and information about this can be found in the log file. This happens in both single and multiplayer mode.

**Expected behavior**
I would like to continue to enter and use individual field courses.

**Screenshots**

Custom Fields:
![1248130_20230322000111_1](https://user-images.githubusercontent.com/120633061/227156166-7927ec77-93c7-47d7-b186-2540fd2217bf.png)

The settings I made:
![1248130_20230322002811_1](https://user-images.githubusercontent.com/120633061/227156228-cad6290e-8131-4696-87a4-7e29f75eb6e6.png)
![1248130_20230322002816_1](https://user-images.githubusercontent.com/120633061/227156233-f2414cb6-f56e-4300-ac10-bf37574fedde.png)

**Courseplay version**
Version used: 7.0.2.5

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
only my self

**Dedicated server or local hosted server**
Dedicated 

**Map**
Calm Lands

**Relevant script mods**
I also tested with a configuration together  with Autodrive, VCA, Revamp... And I also tested if it has any effect if I disable all other add ons. I can reproduce the error in both configurations. However, I have only tested the behavior on this map.

[log.Single.P.txt](https://github.com/Courseplay/Courseplay_FS22/files/11048842/log.Single.P.txt)

This entry is saved in the log file. 

  **dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent**

I did this while the course was being calculated and the Giants Engine was shown in the Task Manager with "no feedback" by clicking with the left mouse button on an empty area of ​​the FS screen. In the farming simulator, the Windows mouse pointer became visible, which also showed me that the system was working.

If I don't provoke this error, the calculation runs through. 

**Possible solution**

_I suspect if you manage to catch the mouse click, the bug should no longer occur._

**Comment by pvaiko** [comment]
This log is when you get an error message that the course could not be generated, right?

I see some weird artifacts in the west and north-east corner of that custom field, have you tried redrawing it?

**Comment by Tensuko** [comment]
You can click on the Field Name and click on edit field.
That opens the editor and you can have a look at the waypoints.

**Comment by Tensuko** [comment]
The reason for the fail in generating a course should be that your corners are crumbly or how to say.
You can solve this with the editor.
For recording a fieldborder with a tractor there will be a pause record button to prevent that problem.
