### ISSUE TITLE
steering only mode

### ISSUE THREAD

**Issue by syfcat** [Courseplay/Courseplay_FS22#2411]
**What is the problem this feature/enhancement solves?**
Current GPS mods like GuidanceSteering/VCA only support straight lines and no headland rows. Courseplay's courses are already amazing and as it turns out very very close to what real gps systems would look like.

**Describe the solution you'd like**
Could the mod add a "steering only" mode, that would *only* automate the steering towards the next waypoint and nothing else (ie let the user deal with driving speed, equipment etc)? This would make it the the best gps mod out there and i believe it is already very close to containing most (all?) of the required groundwork for this.

**Describe alternatives you've considered**
Other mods could try to access courseplay course data, but the responses i get are usually "i don't have time to add something this complex" :(

**Additional context**

The feature would already add great benefit in a very basic state. It would'nt need any corner/turning logic or elaborate pathfinder, just turning the wheels towards the next waypoint would be plenty useful. Instead of dealing with too sharp turns, it could either "stupidly" turn the wheels as much in the direction as possible, or just turn off (both strategies are used in real-world gps systems today). Instead of trying to pathfind the way to the next waypoint when going from headland to field rows, autosteer could just turn off if next waypoint is more than 5m/10m/15m away.

**Nice to have's that would further enhance user experience**

These are by no means essential, but would add some quality of life

- have a configurable button to turn auto steering (starting from closest waypoint) on/off, so user can set custom "gps on/off" button on controller
- automatically turn off auto steer if user manually steers beyond a given angle (ie leave some "wiggle room" of ~ 5° so steering wheel users don't accidentally turn it off all the time if they touch their controller, but can manually intervene by just steering manually like in a real-world gps system

**Comment by Tensuko** [comment]
Not our intention and that question was answered already.
That is where GPS is for and not CP.
