### ISSUE TITLE
[Feature] Driver priority 

### ISSUE THREAD

**Issue by k4r3l01** [Courseplay/Courseplay_FS22#2412]
Hello please its will be possible to add back function from FS19 Driver priority because now i using CP for combine and AD to unload as in FS19 but now is called random driver so i have two drivers on field with 50%+ commodities and its not optimal for combine driver because he must wait until drivers arrive back from unload position

**Comment by Tensuko** [comment]
It is not random and there is a fixed priority that we will keep like it is.
The one with the higher fill level gets called first if he isn't too far away.
