### ISSUE TITLE
[BUG_MP] SIlo Work since last Update not working anymore. No Bunker Silo detected.

### ISSUE THREAD

**Issue by doc-heisenberg** [Courseplay/Courseplay_FS22#2414]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Drive to my Bunker Silo from FED not detected by Courseplay No Job Creation possible

**Actual behavior**
A clear and concise description of what happen.
No Job can be generated for working in Silo ( Bunker Silo) 
No Courseplay Options im Helper

**Expected behavior**
Silo Detection an Courseplay menu for Silo Work
Last Working Version : Courseplay for FS22 v7.2.0.3

**Screenshots**

https://prnt.sc/EkQQ8j8M_NyU
https://prnt.sc/7ZGGu2k5PkmF

**Courseplay version**
Version used:   7.2.0.5

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.
No error in Server Log

**Player on the server**
Number of players on the server, as the bug appeared.  One Player

**Dedicated server or local hosted server**
Dedicated server yes/no ?  Dedicated Server = yes local at home server

**Map**
Map played on.
[NORTH FRISIAN MARCH 4X oG] 2.6.2.0 FedAcion

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? Class Xerion 4500 implement

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AutoDrive 2.0.1.0

https://www.fedaction-letsplay.de/ls22-nordfriesische-marsch/ls22-fedaction-modliste/

**Comment by Tensuko** [comment]
Exactly.
