### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Killingcodgames** [Courseplay/Courseplay_FS22#2418]
My grain cart driver keeps being blocked by an invisible object.

**Comment by Killingcodgames** [comment]
sorry it just randomly started happening to my 8410 it say driver is blocked I can't find the object so im guessing its invisible it's a fs22 model from Mod network anything that might help? i've uninstalled the courseplay and reinstalled it it still pops up.

**Comment by Tensuko** [comment]
What is mod network... As I said, fill in the template, everything else is wild guess.
Reinstall cp wont change anything
