### ISSUE TITLE
[Enhancement] Combine turn - 2nd headland flat corner turns

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2419]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok
**Steps to reproduce**
Steps to reproduce the behavior.
Drescherkurs, mit einem oder mehreren Vorgewenden, scharfe Ecken
wenden am Feld: AUS

**Actual behavior**
A clear and concise description of what happen.
der Drescher braucht einfach viel zuviel Platz, hauptsächlich beim zurücksetzen

**Expected behavior**
der Drescher sollte "kompakter" wenden,
**Screenshots**
siehe hier die wendung:

![fsScreen_2023_03_29_11_13_49](https://user-images.githubusercontent.com/24860501/228515455-1bb65b37-5dea-402d-aa00-b0eba1b557cc.png)
![fsScreen_2023_03_29_11_13_54](https://user-images.githubusercontent.com/24860501/228515605-fc0a8276-f7b6-4b32-a961-2c2747d94781.png)
![fsScreen_2023_03_29_11_14_00](https://user-images.githubusercontent.com/24860501/228515621-95619658-6d7b-49b3-85af-0aef99ad27b9.png)
![fsScreen_2023_03_29_11_14_03](https://user-images.githubusercontent.com/24860501/228515713-c916102b-4682-4fea-9cda-5deee97c09cf.png)
man sieht da sehr gut wieweit der Drescher eigentlich zurückfährt, was ansich nicht notwendig wäre. btw, er drischt grade die ZWEITE Reihe, fährt aber trotzdem fast bis zum Feldrand zurück
![fsScreen_2023_03_29_11_14_08](https://user-images.githubusercontent.com/24860501/228515737-e392ee2b-f63b-4723-acb8-3d18cc494e33.png)
![fsScreen_2023_03_29_11_14_13](https://user-images.githubusercontent.com/24860501/228515779-9eb2e07f-c3bf-4436-a184-e33ef315063f.png)
![fsScreen_2023_03_29_11_14_17](https://user-images.githubusercontent.com/24860501/228515888-9d0952b2-4fef-4889-bbae-458e0f855f4e.png)
![fsScreen_2023_03_29_11_14_21](https://user-images.githubusercontent.com/24860501/228515950-60d21022-90ac-4fa2-87c4-0c7b73b9f538.png)

hier noch die folgende 90grad Ecke:
![fsScreen_2023_03_29_11_14_28](https://user-images.githubusercontent.com/24860501/228517059-8671cb67-4d9d-4ab2-9caa-53acffd14f35.png)
![fsScreen_2023_03_29_11_14_32](https://user-images.githubusercontent.com/24860501/228517077-85ede5c4-02b9-4f66-bc97-20a5a760cd3d.png)
![fsScreen_2023_03_29_11_14_34](https://user-images.githubusercontent.com/24860501/228517349-4d3e8953-375c-4b00-af6a-5981e1c7a646.png)
![fsScreen_2023_03_29_11_14_39](https://user-images.githubusercontent.com/24860501/228517455-b0cfcc2c-8c11-49f5-af25-537f7b6aa7c2.png)
![fsScreen_2023_03_29_11_14_41](https://user-images.githubusercontent.com/24860501/228517524-4172be61-5fec-4ac5-9a12-2a5e3399c577.png)
![fsScreen_2023_03_29_11_14_44](https://user-images.githubusercontent.com/24860501/228517573-5c2edeca-4019-4423-9b00-2ca150d5b126.png)
auch hier, der Drescher fährt viel zu weit zurück, was absolut nicht notwendig wäre
![fsScreen_2023_03_29_11_14_46](https://user-images.githubusercontent.com/24860501/228517841-15cc43dd-3043-4aa6-bcd4-f80981221410.png)
![fsScreen_2023_03_29_11_14_49](https://user-images.githubusercontent.com/24860501/228517880-b64b06f2-7feb-42eb-94fa-8d0550049a07.png)
![fsScreen_2023_03_29_11_14_52](https://user-images.githubusercontent.com/24860501/228517907-88249935-294c-469f-b21d-66eda62ffab9.png)
![fsScreen_2023_03_29_11_14_55](https://user-images.githubusercontent.com/24860501/228517941-666a4029-80c7-43a5-9245-c3df5982625f.png)

**Courseplay version**
Version used: 
v 7.2.0.5 aktuelles main

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Frühling map (im modhub)
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
giants Claas tucano
olimac drago Schneidwerk,
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233716&title=fs2022
oder auch draper stram 900
https://forbidden-mods.de/filebase/file/28991-ls22-draper-stream-900/#overview

**Relevant script mods**
Mods like Autodrive or VCA and so on.
none 

Hallo Leute, ja, sorry, meine 2. diesbezügliche meldung nach einigen monaten. damals spielteich eine 4x map, nun eine nummer kleiner.
und ja, ich kann wenden auf dem Feld aktivieren, aber da wendet sich der Drescher zu tode, sprich mit dem ganzen hinundherschieben, vor und zurück und eine zweite spur freidreschen am Eck,.... da braucht der Drescher für eine Ecke solange wie fürs ganze restliche Feld.
und ich meine noch immer, das der Drescher nicht bis zum Rand derersten Reihe zurücksetzen sollte,
er fängt ja quasi schon hier zum Dreschen an:
![fsScreen_2023_03_29_11_14_49](https://user-images.githubusercontent.com/24860501/228519364-2d82938d-cbd1-4329-8fb8-572e468d3b4f.png)

sollte aber erst hier anfangen damit:
![fsScreen_2023_03_29_11_14_52](https://user-images.githubusercontent.com/24860501/228519582-6627e7d5-dccc-45e9-9e77-6a17e57642c9.png)

freu mich schon auf rückfragen
glg
andreas

**Comment by andreasthu** [comment]
>...t. Gerade auf Maps wie der Landkreis Rostock wo man recht viele Hindernisse am Feldrand hat, führt dieses recht weitläufige Wendeverhalten leider ziemlich oft dann zum Aussteigen des Helfers.

das ist ja genau der grund meines issues
auf kleinen maps braucht der (kleinere) Drescher einfach vielzuviel Platz beim wenden.
auf großen Feldern mit Großem Gerät fällt das eigentlich nicht auf, aber auf kleinen Maps bzw mit viel Deko ums Feld ist es eine katastrophe.
lg
andreas

**Comment by Tensuko** [comment]
Das Ausarbeiten der Ecke, findet nur im ersten vorgewende statt.
Deine Bilder beziehen sich hier alle auf das 2te Vorgewende.
Wir können ja mal das gleiche Ausarbeiten auch auf das 2te oder sogar 3te Vorgewende anwenden.
Meiner Erfahrung nach ist z.B. das Ausarbeiten im ersten Vorgewende auch mit kleinen Geräten sauber und ohne Probleme mit objekten drum herum - ja wenn sie zu dicht sind gibt es Probleme, aber dann sind sie nun mal zu dicht!

Der turn für das erste Vorgewende wurde im 19er genau für sowas gebaut, Karten mit Objekten drum herum.

**Comment by andreasthu** [comment]
das am zweiten Vorgewende war ja nur grade als beispiel.
beim ersten Vorgewende braucht der Mähdrescher ja auch genauso viel Platz.
da wird es sogar noch enger auf der map
lg
andreas

**Comment by Tensuko** [comment]
Das erste Vorgewende ist ein komplett anderes Wendemanöver, außer du hast Wenden auf dem Feld, bzw Fruchtumfahrung im Drescher ausgeschaltet, das ist dann aber User Sache und hat nichts mit dem Code zu tun!

**Comment by andreasthu** [comment]
Fruchtumfahrung ist "aktiv"
pathfinder im Wendemanöver ist "aktiv"
![fsScreen_2023_03_29_16_06_40](https://user-images.githubusercontent.com/24860501/228564483-b8be1479-147a-419a-988f-1c82ac0d0b3f.png)

bei der 1.runde sieht es so aus:
![fsScreen_2023_03_29_16_03_54](https://user-images.githubusercontent.com/24860501/228564710-f3b49b4e-1eb2-42ed-beb9-eac8f690da01.png)
![fsScreen_2023_03_29_16_03_57](https://user-images.githubusercontent.com/24860501/228564722-c1ec302e-ffa1-41c9-a27c-6fb9d8f1d118.png)
![fsScreen_2023_03_29_16_04_00](https://user-images.githubusercontent.com/24860501/228564748-3a9c9f09-60b6-400a-ac6b-40c1f249e30b.png)
![fsScreen_2023_03_29_16_04_03](https://user-images.githubusercontent.com/24860501/228564785-ee7da11b-0a7f-4063-9ff8-0b16c1a29e1a.png)

manchmal muss ich tricksen bei der Wende (mit dem ingame cp-editor gemacht):
![fsScreen_2023_03_29_16_09_59](https://user-images.githubusercontent.com/24860501/228565658-428fdc16-d0e3-49a4-bb75-e53b9f54088c.png)
![fsScreen_2023_03_29_16_10_10](https://user-images.githubusercontent.com/24860501/228565710-7988c87a-9981-41ab-b547-3b43684c6d40.png)
mit der normal generierten Ecke würde er es nicht schaffen, da er ansonsten in den Weinberg reinkäme aber vorher bei der Wende stoppt. weil er unnötig zuweit zurück möchte.

lg
andreas

**Comment by pvaiko** [comment]
Ich kann nur eins sagen: wäre viel einfacher wenn wir ein log hätten, da steht nämlich fast immer drin, warum der Drescher was macht.

**Comment by pvaiko** [comment]
> Fruchtumfahrung ist "aktiv" pathfinder im Wendemanöver ist "aktiv" 

Jetzt noch Wenden auf dem Feld einschalten und es wird funktionieren.

**Comment by andreasthu** [comment]
guten morgen
hallo pvaiko
hier die log vom Tucano + Wendungen
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11108370/log.txt)

ja die wenden am Feld sache,
hab mal auf der Frühling kurz nachgezählt da gibts ca 78 Ecken an den Feldern, 
bei ungefähr 8 hab ich Platzprobleme, davon zwei bis drei so lethal das CP stoppt, die restlichen hab ich irgendwie umschifft, durch änderungen mit dem ingame cp editor.
die wenden am Feld sache ist so zeitaufwändig, bei kleinen Feldern, und nur damit beiden drei ecken es auch klappt, macht er es dann eben auch bei den anderen 75 Ecken.

![fsScreen_2023_03_30_08_12_43](https://user-images.githubusercontent.com/24860501/228747059-fe16ad50-bffd-44db-a891-1c918e3cfa88.png)
![fsScreen_2023_03_30_08_12_47](https://user-images.githubusercontent.com/24860501/228747072-546ef603-940e-4ef3-932c-b55391c1bcb8.png)
![fsScreen_2023_03_30_08_12_57](https://user-images.githubusercontent.com/24860501/228747140-46256e51-f992-4a1f-b832-15accd0be536.png)
![fsScreen_2023_03_30_08_13_06](https://user-images.githubusercontent.com/24860501/228747159-eae3d080-ad3d-46db-b70a-acef9f2e6764.png)
![fsScreen_2023_03_30_08_13_14](https://user-images.githubusercontent.com/24860501/228747184-360ebc16-9c5e-4e71-8cb4-45f6e2997f78.png)
![fsScreen_2023_03_30_08_13_21](https://user-images.githubusercontent.com/24860501/228747201-fd7b4994-02e0-42fb-af69-04b946db34e7.png)
![fsScreen_2023_03_30_08_13_24](https://user-images.githubusercontent.com/24860501/228747233-d6faef17-f48d-4c2d-aa64-31969e693f39.png)
habs versucht, funktoniert ja auch, ist aber im gegensatz zur normalen wende sehr zeitaufwendig. und dann macht er ja diese wende auch wenn sich die normale auch ausgehen würde. cool wäre wenn man einzeln selektieren könnte, normal oder an Feld. aber darum gehts mir eigentlich gar nicht.

mein anliegen wäre nur, das der CP-Drescher bei normalen Ecken viel zu weit zurückfährt:
er kommt zur Ecke, fährt ein stück vorwärts übers Feld raus mit leichtem einschlag nach rechts (vom Fahrer aus gesehen),
dann fährt er rückwärts, mit einschlag nach links:
![fsScreen_2023_03_30_08_11_44](https://user-images.githubusercontent.com/24860501/228748072-fe818d2e-92d8-47b6-a6c7-072c46452978.png)

aber er fährt eben sehr weit zurück, was mMn nicht notwendig wäre um das Dreschen quasi schon am Feldrand beginnen zu können:
![fsScreen_2023_03_30_08_11_49](https://user-images.githubusercontent.com/24860501/228748251-15066368-9cec-43f1-b574-2a7074b7552c.png)
(was ja nicht notwendig ist, da dort ja kein Getreide mehr steht)

es würde reichen wenn er etwas weniger weit zurücksetzt, da er ja erst hier zum dreschen beginnen müsste:
![fsScreen_2023_03_30_08_11_54](https://user-images.githubusercontent.com/24860501/228748439-c70b7df2-b70a-4b6e-a8e1-01c5bb833725.png)

um das ginge es mir eigentlich, somit würden sich etliche (platz)probleme auf kleinen maps, oder maps mit Deko am Feld wegfallen-
lg
andreas

**Comment by Tensuko** [comment]
Lieber Andreas....
Wenn wir eine Funktion haben die genau das Problem mit dem Platz behebt und die für genau DAS gebaut wurde, dann ist das Argument "habs versucht, funktoniert ja auch, ist aber im gegensatz zur normalen wende sehr zeitaufwendig" für uns von keinerlei Bedeutung...

Wenn es so geht, wird von unserer Seite aus nicht daran geändert!

Das Zeitargument ist sowieso unerklärlich für mich.
Guckst du CP ständig beim fahren zu?
Ist es das wofür du Helfer benutzt?
Für mich sind Helfer da um Aufgaben zu übernehmen, damit ich mich um andere Dinge kümmern kann, dabei spielen ein paar Sekunden mehr Zeitaufwand keine Rolle, hauptsache die Arbeit wird möglichst zuverlässig und sauber erledigt.

In wie weit anheben und absenken eine Rolle spielt, weis ich nicht, das ich das bei Dreschern immer auf default lasse. (Anheben früh, absenken spät).

**Comment by rohne83** [comment]
> Das Zeitargument ist sowieso unerklärlich für mich. Guckst du CP ständig beim fahren zu? Ist es das wofür du Helfer benutzt? Für mich sind Helfer da um Aufgaben zu übernehmen, damit ich mich um andere Dinge kümmern kann, dabei spielen ein paar Sekunden mehr Zeitaufwand keine Rolle, hauptsache die Arbeit wird möglichst zuverlässig und sauber erledigt.

Kann nur für mich sprechen, aber bei mir ist die Antwort definitiv ein klares ja. Ist auch nix verwerfliches dran, CP (und auf der Straße AD) fährt in der Regel deutlich besser als ich das mit der Tastatur jemals könnte. Zumal ich eh Karten mit großen Feldern präferiere, wo vielfach ohnehin im Konvoi gearbeitet wird, was manuelles mitmachen weitgehend ausschließt. Allein mit dem Überwachen zwangsweise immer mal wieder nötigen Babysitten ist man da trotzdem mehr als genug beschäftigt.
Grundsätzlich find ich das bisherige System der Bearbeitung der Vorgewendeecken durchaus vernünftig und realitätsnah. Das zeitaufwändige Maneuver mit mehrfacher Rückwärtsfahrt wird ja soweit nur auf der ersten Vorgewendebahn durchgeführ. Ab der zweiten ist es unnötig und da wird auch korrekterweise auf die zeitsparende Variante geswitcht (und das sollte bitte auch so bleiben!), auch wenn Wenden im Feld aktiviert ist.
Problematisch sehe ich einzig die Situation aus Andreas Eröffnungsbeitrag im fünftem Screenshot, dass bei dem zeitsparenden Maneuver doch übertrieben weit zurückgesetzt wird und der Helfer selbst von der zweiten oder dritten Vorgewendebahn sich schnell mal außerhalb des Feldes wiederfindet. Etwas platzsparender sollte das durchaus möglich sein, hoffe ich.

**Comment by Tensuko** [comment]
Normal sollte der turn ab dem zweiten headland so nicht sein, wenn man die entsprechenden settings drin hat. Wenn ich heute Zeit finde, gucke ich mir das kurz an, wie das verhalten entsprechend war je nach setting. Aber ich habe auf der IIT V3 schon mit dem kleinen NH Drescher auf kleinen Feldern gearbeitet und mit den standart Einstellungen keinerlei Probleme gehabt, auch so ein starkes verlassen des Feldes kam nicht vor.

**Comment by andreasthu** [comment]
Danke das du dir das ansiehst.
Lg
Andreas

**Comment by pvaiko** [comment]
>  ab dem fünften Screenshot, dass bei dem zeitsparenden Maneuver der inneren Bahnen doch übertrieben weit zurückgesetzt wird

Das ist mir auch aufgefallen, und wahrscheinlich auf die flache Winkel zurückzuführen.

**Comment by Tensuko** [comment]
Bei einem kleineren Drescher ist das eben durch die Arbeitsbreite bedingt, genauso wie bei Geräten die lang sind und eine kleine Arbeitsbreite haben.

![fsScreen_2023_03_31_15_08_25](https://user-images.githubusercontent.com/27344744/229128522-62c1c2c7-858d-48e1-b0a6-e2793439628d.png)


![fsScreen_2023_03_31_15_05_10](https://user-images.githubusercontent.com/27344744/229127888-34ad60e5-c3fe-493d-87de-dc83aa701db0.png)

![fsScreen_2023_03_31_15_05_00](https://user-images.githubusercontent.com/27344744/229127860-880b7f95-ee22-46ae-b418-0d75d1f3bbdc.png)

Dafür soll es ja neue Optionen im Generator 2.0 geben, das dauert eben noch.

**Comment by pvaiko** [comment]
For the record: what I'd like to enhance here is the CombineHeadlandTurn() with flatter turn angles, this turn type does not follow a generated course, instead it operates with relative positions/angles to the turn end/start points to decide when to change direction and this just does not work very nice at low angles.

**Comment by pvaiko** [comment]
Wer Lust hat kann #2429 testen...

**Comment by andreasthu** [comment]
> Wer Lust hat kann #2429 testen...

Danke, werd ich mal machen 
Lg
Andreas

**Comment by andreasthu** [comment]
> Bei einem kleineren Drescher ist das eben durch die Arbeitsbreite bedingt, genauso wie bei Geräten die lang sind und eine kleine Arbeitsbreite haben.
> 
> ![fsScreen_2023_03_31_15_08_25](https://user-images.githubusercontent.com/27344744/229128522-62c1c2c7-858d-48e1-b0a6-e2793439628d.png)
> 
> ![fsScreen_2023_03_31_15_05_10](https://user-images.githubusercontent.com/27344744/229127888-34ad60e5-c3fe-493d-87de-dc83aa701db0.png)
> 
> ![fsScreen_2023_03_31_15_05_00](https://user-images.githubusercontent.com/27344744/229127860-880b7f95-ee22-46ae-b418-0d75d1f3bbdc.png)
> 
> Dafür soll es ja neue Optionen im Generator 2.0 geben, das dauert eben noch.

Guten morgen
Ich glaub, das man da hinten angehängte Geräte bei Ecken nicht mit Dreschern (Schneidwerk vorne) vergleichen kann:
Bei Grubbern,  Spritzen, Düngen,... fährt cp an der ecke ja nicht bis ganz vor, sondern stoppt ja schon die "Arbeitsbreiten-Breite" davor, wendet, und setzt dann ganz zurück,  wie auch an deinem ersten Bild zu sehen. 
Und da liegt glaub ich der Denkfehler bei den Drescher Wendungen. 
Der Drescher fährt ja bei der Ecke bis ganz durch, erntet das Getreide in der Lane "fertig".
Danach setzt er zurück, und zwar so wie ein z.b. Grubber und zwar bis ganz zum ende. Was ja beim Drescher nicht notwendig ist, da diese 9m schon vor der Eckwende weggedroschen wurden.
Aber der Drescher setzt eben -nicht notwendigerweise- eben diese 9m trotzdem mehr zurück und beginnt daher mit dem dreschen nach dem eck um 9m zu früh. Das müsste eben nicht sein und so könnte man bei der wende eben genau diese 9m einsparen welche der drescher eben nicht zurückfahren müsste und bei engen ecken eben 9m mehr platz hätte .
(9m weil ich grade ein 9m SW habe, bei anderen SW breiten eben andere weite denken)
Lg
Andreas

**Comment by andreasthu** [comment]
> Wer Lust hat kann #2429 testen...

danke @pvaiko 
habs mal bei der 135grad Feldecke versucht:
1) Vorgewende aussen:
![fsScreen_2023_04_02_10_22_19](https://user-images.githubusercontent.com/24860501/229341433-9405d8c7-c9b3-49bc-8e80-67b6e41494e1.png)
![fsScreen_2023_04_02_10_22_24](https://user-images.githubusercontent.com/24860501/229341435-62559c53-e72c-4cb2-984b-1335cc8208e1.png)
![fsScreen_2023_04_02_10_22_30](https://user-images.githubusercontent.com/24860501/229341443-528b4d18-2804-45a6-b986-593fb6951c4d.png)
![fsScreen_2023_04_02_10_22_33](https://user-images.githubusercontent.com/24860501/229341446-5a9f9521-1625-4a8d-8cd4-3b971b548aa2.png)
![fsScreen_2023_04_02_10_22_34](https://user-images.githubusercontent.com/24860501/229341461-669e0312-50cc-4243-897b-cf39624f5fac.png)
![fsScreen_2023_04_02_10_22_35](https://user-images.githubusercontent.com/24860501/229341474-9dd71762-0808-4b5e-99e0-ded0b02de011.png)
![fsScreen_2023_04_02_10_22_37](https://user-images.githubusercontent.com/24860501/229341479-2c6e4bd5-95ad-45dd-8e21-28e083b18c15.png)
![fsScreen_2023_04_02_10_22_40](https://user-images.githubusercontent.com/24860501/229341487-5f0d5ec8-5f34-4f18-86ee-64316044bf54.png)

und auch beim 2. Vorgewende:
![fsScreen_2023_04_02_10_23_09](https://user-images.githubusercontent.com/24860501/229341510-222f1ca9-e928-4b82-bb13-2837f991097b.png)
![fsScreen_2023_04_02_10_23_11](https://user-images.githubusercontent.com/24860501/229341516-16f57fa9-fead-4d2c-bba9-e9e0933cec37.png)
![fsScreen_2023_04_02_10_23_14](https://user-images.githubusercontent.com/24860501/229341522-216d6843-4bb3-4659-9300-70082ac54d71.png)
![fsScreen_2023_04_02_10_23_17](https://user-images.githubusercontent.com/24860501/229341538-aba1bb15-384b-4979-bdcd-7f2345415b68.png)
![fsScreen_2023_04_02_10_23_19](https://user-images.githubusercontent.com/24860501/229341543-d117aed6-ece5-41ac-be3e-4398f91ff87d.png)
![fsScreen_2023_04_02_10_23_21](https://user-images.githubusercontent.com/24860501/229341550-9378d2b5-821d-49c7-8b78-bcef01a052aa.png)
![fsScreen_2023_04_02_10_23_23](https://user-images.githubusercontent.com/24860501/229341553-2c5e6885-16e8-4e61-809a-559707819bba.png)
![fsScreen_2023_04_02_10_23_25](https://user-images.githubusercontent.com/24860501/229341559-4a361eb0-42f4-447e-a6a1-9d409ae4313a.png)
![fsScreen_2023_04_02_10_23_28](https://user-images.githubusercontent.com/24860501/229341564-090c7975-49e8-4fc0-a1ee-2e575fdea6be.png)
![fsScreen_2023_04_02_10_23_31](https://user-images.githubusercontent.com/24860501/229341577-9bb4e18f-7733-4771-a122-ef0c1e877c9d.png)
super, danke
der Drescher setzt nur bis zur Getreidekante zurück, nicht mehr bis zur äusseren Bahnkante.
so wärs auch bei 90grad Ecken ideal, den Dreschen nur bis zur Getreidekante zurücksetzen zu lassen.

lg
andreas
