### ISSUE TITLE
Agrisem VehicleConfigurations.xml-XML Name Change

### ISSUE THREAD

**Issue by urbanswelt** [Courseplay/Courseplay_FS22#2421]
Hi,

https://github.com/Courseplay/Courseplay_FS22/blob/52c38e0e1fb0c20f4da9c6bb48a5a656b481ec34/config/VehicleConfigurations.xml#L251

The Name has changed to --> cultiplowPlatinum8m

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2138928/228643742-8030baf4-bee0-48c6-bd7a-ca0f3ef4896d.png">

**Comment by Tensuko** [comment]
Thank you, changed it.
Will be part of the next Release :)
