### ISSUE TITLE
The 'empty when over' setting is ineffective

### ISSUE THREAD

**Issue by asasd1212** [Courseplay/Courseplay_FS22#2425]
"Even if the 'empty when over' setting is at 40%, joint harvesting using agricultural machinery will only occur when the crop level reaches 85%."

**Comment by Tensuko** [comment]
Well, as I tested the last 5hours our unloader, it is indeed active.
Do you have an example as a machine that isn't working ?

**Comment by rohne83** [comment]
The empty when over setting only applies to the unloader's filllevel. It's when the unloader will handover to AD/Giants helper for the way to the silo/sellpoint, or drive to field edge if you use an auger wagon. Combine chasing always tries to have the rendezvous point at 80% combine fill level.
