### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Magma4121** [Courseplay/Courseplay_FS22#2428]
I have an issue with the map on Attingham Park with courseplay.

When I load into my game save the map doesn't load and I have tried resolving the issue but haven't found why.

![image](https://user-images.githubusercontent.com/129594505/229285443-96282e32-6569-41d1-a444-e4318c2e7a89.png)

Version used: 7.205

Error: Running LUA method 'draw'
dataS/scripts/gui/hud/Ingamemap.lua(703
)

Attingham Park

**Comment by Tensuko** [comment]
No log no help.
That Error is game related script, seems like a bug in the map.
