### ISSUE TITLE
[BUG_SP]Mähdrescher abtanken

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#243]
Hallo
Kann der Abfahrer Traktor den Mähdrescher ab tanken oder ist das noch nicht möglich

**Comment by Onkel2000** [comment]
Der Drescher kann es selber wenn du es in den einstellungen aktivierst. Stell einfach ein Anhänger neben das Feld. funktioniert wirklich gut.

**Comment by Tensuko** [comment]
Das Abtanken über AD sollte funktionieren, wenn du Rohr immer Ausfahren und Während des Abtanken stehen bleiben aktivierst.
Das ist eine Schnittstelle die eher einfach so funktioniert.

Eine Echte Schnittstelle zu AutoDrive, wird noch kommen.
