### ISSUE TITLE
[InfoFromDev] Translation updates (30.09.23)

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#2437]
Information for our translator:
We updated some translaions and we thought it would be better to inform you this way then delete your hard work and make you do it all over again.
So here are the (for now) small changes:
Course editor: (should be line 582)
```
Old: By clicking on the name you will get the option to either delete or rename it.
New: By clicking on the name you will get the option to either delete, rename or edit it with the Editor.
```
Extended Job Menu: (should be line 454)
```
Old: For generating a course and starting the courseplay jobs, you will need to create the job CP: Fieldwork or CP: wrap/collect bales, similar to the Giants helper.
New: For generating a course and starting the courseplay jobs, you will need to create the job CP: Fieldwork, CP: wrap/collect bales, CP: Loader or CP: Bunker silo similar to the Giants helper.
```

**Comment by KCHARRO** [comment]
In row 70

 <text name="CP_baleFinder_balesLeftover" text="Bales left:"/>

Are you referring to the remaining Bales to be collected?....

**Comment by Tensuko** [comment]
Yes :)

**Comment by KCHARRO** [comment]
Ok.... Thanks....

**Comment by Tensuko** [comment]
Update.
Bale collect and wrap.
Old (Line 622):
`Stay on the field and just start the driver from the HUD with wrap/collect bales or use the AI Map to send him to a field to start the job.`
New (Line 622+623):
`With the target-icon on the HUD, you need to select the field, where you want to collect or wrap the bales. After that you can start the driver near the field.
You can also use the AI Map to send him to a field to start the job.`

**Comment by Tensuko** [comment]
Old (Line 221):
`Combine will call the unloader on the first headland.`

New (Line: 221):
`Combine will call the unloader on the first headland, even when he have to drive outside of the field. If turned off, the combine first creates a pocket before calling an unloader.`
