### ISSUE TITLE
[Feature] CP und Normaler helfer

### ISSUE THREAD

**Issue by HansGeorg95** [Courseplay/Courseplay_FS22#244]
**Wenn man Cp Helfer einstellt und danach den normalen Helfer will er immer zum CP course
**
Wenn ich einen course mit cp generieren und später normale feldarbeit machen will er immer zum cp Feld zurück fahren. Weil der course noch geladen ist.

Es wäre cool wenn man zwischen Helfer cp & normal Helfer umschalten 

Course löschen sich nach Beendigung der Arbeit oder es gibt ne extra Taste um alle course aus dem Fahrzeug zu löschen.

Keep up the amazing work greatest mod ever in LS
Thank u so much..

**Comment by Tensuko** [comment]
Das wird noch angepasst, siehe #190
