### ISSUE TITLE
Problem with pipe offset when offloading combine[BUG_SP]

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#2440]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Use courseplay to unload combine

**Actual behavior**
A clear and concise description of what happen.
In the V7.2.1.0 version the offloader does not drive in the correct position. I need to set 4m offset and it offloads in the front of the augerwagon
This is not a problem in V7.2.0.5

**Expected behavior**
Drive in the correct position

**Screenshots**
V7.2.1.0
![Farming Simulator 22 Screenshot 2023 04 08 - 12 37 35 80](https://user-images.githubusercontent.com/85753728/230716952-5cf8d6aa-b7b4-4299-9fb0-0beba384beb0.png)
V7.2.0.5
![Farming Simulator 22 Screenshot 2023 04 08 - 12 34 26 79](https://user-images.githubusercontent.com/85753728/230716955-198d31c4-3297-4cc7-a171-d58841102d0a.png)

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the  github front page.

[logV7210.txt](https://github.com/Courseplay/Courseplay_FS22/files/11183021/logV7210.txt)
[logV7205.txt](https://github.com/Courseplay/Courseplay_FS22/files/11183022/logV7205.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**

Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
At the front is normal and correct, the unloader will drive further to the depending on the fillvolume of the trailer. Wonder if we have this missing for the auger wagon. Will check on that.
