### ISSUE TITLE
Universal Autoload and CP

### ISSUE THREAD

**Issue by kwguk** [Courseplay/Courseplay_FS22#2441]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Loading the game with just AL and CP in mod file

**Actual behavior**
wont load beyond 60%

**Expected behavior**
Load the game

**Screenshots**

**Courseplay version**
Version used: latest version

**Log**
[log.txt - Shortcut (2).zip](https://github.com/Courseplay/Courseplay_FS22/files/11183109/log.txt.-.Shortcut.2.zip)

**Map**
vanilla Haut Beleyron

**Vehicles/ implements involved**
None

Mod yes/no ?
Only CP and Autoload

**Relevant script mods**
none

Ive tried on several maps and get the same result

**Comment by Tensuko** [comment]
Pls upload your logfile as .txt

**Comment by kwguk** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11183479/log.txt)

**Comment by Tensuko** [comment]
Your logfile contains more then just cp and al and a lot of mods with errors and you have a repeating callstack that does not lead to CP.
Clean up your mod folder first.
