### ISSUE TITLE
[BUG_SP] Unloader drives too close to combine and collides with 7.2.1.0

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#2442]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Updated to 7.2.1.0 and now my unloader always drives into the combine and is unable to unload. When going back to 7.2.0.5 it works again

**Actual behavior**
The unloader tries to unload on the go, but always is stuck behind the header. As soon as the combine is completely full, the unloader tries to drive forward, but get's stuck on the header

**Expected behavior**
Normal unloading like it did with 7.1.0.5

**Screenshots**
![Farming Simulator 22 08_04_2023 23_20_41](https://user-images.githubusercontent.com/99053368/230743532-89aaf0d3-2232-4e37-a07d-345a35314a78.jpg)
![Farming Simulator 22 08_04_2023 23_21_13](https://user-images.githubusercontent.com/99053368/230743542-12f740cf-ead8-436c-8e96-71be42bd0c0a.jpg)

**Courseplay version**
Version used: 7.2.1.0

**Log**
(https://gist.github.com/DemsMani/a7d0fdc415abc2c0b7c816cf5a865658)

**Map**
Morris

**Vehicles/ implements involved**
Lexion 8900 (Modhub), Quadtrac (Vanilla) Brent Avalanche 2596 (third party)

**Relevant script mods**
Autodrive (no active driver in test)

**Comment by Tensuko** [comment]
Looks like the extended pipe doesnt get count in.
