### ISSUE TITLE
[BUG_SP] Combine folds auger in extended position when CP is started with extended auger

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#2443]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
When the auger of the combine is extended and cp is started again (for example after a collision), the outer link of the auger folds in, leaving no option anymore to do anything

**Actual behavior**
When pressing the cp start button with the auger extended, the outer link just folds in immediately

**Expected behavior**
As it worked before, the outer link of the auger should stay unfolded

**Screenshots**
![Farming Simulator 22 08_04_2023 23_23_01](https://user-images.githubusercontent.com/99053368/230743743-5185e737-318c-4a24-8963-860f166af2b0.jpg)

**Courseplay version**
Version used: 7.2.1.0

**Log**
(https://gist.github.com/DemsMani/a7d0fdc415abc2c0b7c816cf5a865658)

**Map**
Morris

**Vehicles/ implements involved**
Lexion 8900 (Modhub)

**Relevant script mods**
Autodrive (no active driver during test)

**Comment by yann-mrt** [comment]
It is not isolated case, this happen to me as well with V 7.2.1.0, everything was find with V 7.2.0.5.

**Comment by Tensuko** [comment]
No one said anything different...

**Comment by knoxville73** [comment]
Hi,

I know the same issue with an another combine
