### ISSUE TITLE
[BUG_SP] Fehlende „Zielposition“ führt zu LUA Call Stacks

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/Courseplay_FS22#2444]
**Steps to reproduce**
Abfahrer auf dem Feld parken, über das Fadenkreuz das Menü öffnen. KEINE „Zielposition“ eingeben, Abladen auf dem Feld aktivieren, Position zum Abladen auswählen, Job starten.

Es gibt auch ein YouTube Video, wodurch mir aufgefallen ist, dass es an der fehlenden „Zielposition“ liegt.

https://youtu.be/N_lsJyEzmBg
Bei 5:25 Minuten geht’s los.

**Actual behavior**
Es kommt zu LUA Call Stacks

**Expected behavior**
Der Abfahrer starte seine Arbeit oder man kann den Job erst starten, wenn man eine „Zielposition“ angegeben hat.

**Screenshots**
Werde ich Dienstag Abend hochladen, leider keine Zeit mehr gehabt.

**Courseplay version**
Version used: 7.2.1.0

**Log**
Werde ich Dienstag Abend hochladen, leider keine Zeit mehr gehabt.

**Map**
Elmcreek

**Vehicles/ implements involved**
FENDT 1000 VARIO
KRAMPE BIG BODY 750 S

**Relevant script mods**
AD

Es tut mir leid, dass noch keine Log und Screenshots da sind. Habe durch die Feiertage keine Zeit mehr gehabt und erstelle den Report nun vom Handy, wo mir die Daten nicht zugänglich sind.
Werde es aber nachliefern.

**Comment by Tritura2** [comment]
Und schöne Ostern euch allen :)

**Comment by Tensuko** [comment]
> Und schöne Ostern euch allen :)

Danke Gleichfals :)

Callstack und LUA Error:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11185153/log.txt)

Fehlt wohl nen check denke ich.
