### ISSUE TITLE
Error beim Rübenmiete abladen

### ISSUE THREAD

**Issue by Momo13092022** [Courseplay/Courseplay_FS22#2448]
Absturz durch Log Error,

Abfahrer eingestellt auf ,,Abladen auf dem Feld,, nach dem ,,Job starten,,  Absturz siehe Log 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11190346/log.txt)

**Comment by Tensuko** [comment]
Template nicht benutzt und duplicate: #2444
