### ISSUE TITLE
CP Häcksler BigX1100 ---- CP Abfahrer

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2450]
Ich fahre auf der FS22_DondiegoMap und möchte mit einem Häcksler BigX1180 Standard mein Feld 14 abernten.
Hierzu möchte ich den Abfahrer AXION 960 TERRA TRAC mit "CP" abfahren lassen!
Leider fährt der Abfahrer nicht los!
Mit der Rübenernte geht das nur mit dem Häcksler nicht!
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11210841/log.txt)

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/2284

**Comment by Tensuko** [comment]
Häcksler abfahren ist von CP nicht unterstützt!

**Comment by hermannbrauer** [comment]
lass das von AD machen! damit bekommst du was du willst... Abfahrer im AD wie beim Drescher...
