### ISSUE TITLE
Im Verband wartet Drescher 1 nicht auf Drescher 2

### ISSUE THREAD

**Issue by Blaubaer12** [Courseplay/Courseplay_FS22#2453]
Wenn ich 2 Drescher im Verband dreschen lasse wartet Drescher 1 ( linke Spur ) nicht auf Drescher 2 ( rechte Spur ) obwohl das laut dem Tutorial von Mario Hirschfeld gehen soll. Getestet mit verschiedenen Dreschen sowohl auf Standart- als auch auf Modkarten mit den letzten CP Versionen einschließlich Version 7.2.1.0

**Comment by Tensuko** [comment]
Das was Mario im Tutorial sagt, ist nicht immer das was gewollt ist.
Der vordere Drescher wartet nicht auf den hinteren Drescher und das soll so auch nicht sein.
