### ISSUE TITLE
[BUG_SP]-Tractors with Trailed Implements Fail to Align at top of New Row

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#2454]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Using either a vanilla or mod New Holland 130 tractor using vanilla roller/mod roller (or other trailed implement)

**Actual behavior**
CP fails to properly align itself before working in a new lane leaving portions of each lane undone. Instead it executes the turn and veers too far to the right. When it reverses, it doesn't straighten out correctly until it has moved forward several meters.

**Expected behavior**
CP should drive the tractor further into the new lane and aligning itself before reversing into position at the start work position.

**Screenshots**
Link to video showing issue: https://youtu.be/LRWtTdulphA 

**Courseplay version**
Version used: 7.2.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11235964/log.txt)

**Map**
Iowa Planes

**Vehicles/ implements involved**
New Holland 130-90 tractor & Guttler Mayor 820 roller. 
Mod yes/no ?
Yes
**Relevant script mods**
None

**Comment by Tensuko** [comment]
> Using either a vanilla or mod New Holland 130 tractor using vanilla roller/mod roller (or other trailed implement)

I have my doubt about this...
![grafik](https://user-images.githubusercontent.com/27344744/232132442-8dc5f8ca-50de-40b1-9467-7c1d23b61df2.png)

Same for the bigger roller:
![grafik](https://user-images.githubusercontent.com/27344744/232133527-ee9bb006-75df-40b7-b656-43f64d863de1.png)


Wich Tractor and wich Roller did you use there?

**Comment by lcc1211** [comment]
Sorry, I gave you to wrong tracto
![Roller](https://user-images.githubusercontent.com/24764870/232135389-ebddfff9-f84d-4d48-9cb5-269cd0c363db.jpg)
r: AgroStar 6.61 but the roller is as identified in the text as Guttler Mayor 820 roller. I didn't include this this screenshot before, but here is the same course near completion.

**Comment by Tensuko** [comment]
Then it is the same I just tested (from ModHub) and the same roller, no Issue at all.
You changed any settings?

**Comment by Tritura2** [comment]
17 mph for a turn might be a lite bit to fast 😅

**Comment by lcc1211** [comment]
> Then it is the same I just tested (from ModHub) and the same roller, no Issue at all. You changed any settings?

Since I reported it? No. I haven't changed settings as far as code or scripts. I did have it turning at 7.5MPH but slowed it down to 5.6 for the turns. This is the only time I used a trailing implement with this one.

**Comment by lcc1211** [comment]
> 17 mph for a turn might be a lite bit to fast 😅

17MPH? I don't have CP set that high for turns. Field speed is set at 20.5 and turn speed was at 7.5, but lowered to 5.6.

**Comment by lcc1211** [comment]
Since CP Mods can't replicate the issue using the same equipment I will close the issue.

**Comment by Tensuko** [comment]
Well okay but indeed I wonder why your tractor turns at 17MPH in your video, it might overshoot the turn wich easy lead to this problem.

**Comment by lcc1211** [comment]
> 17 mph for a turn might be a lite bit to fast 😅

Ah. I get why you think I was doing that speed. The tractor was, but if you look at the video around 2 minutes 20 seconds, you'll see my settings in CP are only set to about 1/3 of that at 5.5, so CP was ignoring the limit I set.

**Comment by lcc1211** [comment]
> 

Check the video at about 2:20. My settings show the limit set for turns to only about 1/3 of that. CP ignored that limit for the turns and sped up on the turn.

**Comment by Tensuko** [comment]
Okay the problem is something else here.
The speed that we use is fieldSpeed for that part of the turn.
Reason probably is the pathfinder turns wich can get very long thats why fieldspeed makes more sence here.
Will figure something out.
