### ISSUE TITLE
BGA Bunkers CP markers v7.2.1.1[BUG_SP]

### ISSUE THREAD

**Issue by Horozor** [Courseplay/Courseplay_FS22#2455]
After the last update, dev markers appeared in the bunkers
Start point, Height point, Width point
I hope you understand what I mean

![image](https://user-images.githubusercontent.com/37561569/232162583-63ad67d3-203d-4c21-ae93-771fd2a49ddf.png)

**Comment by AUZ001** [comment]
I too can confirm this is happening

**Comment by ollybe** [comment]
Ich kann das ebenso bestätigen.

**Comment by BauerPaul** [comment]
bei mir genau das selbe

**Comment by mrmg89** [comment]
habe auch das problem

**Comment by ZincStoat** [comment]
Applied this change manually and the stray labels are no longer present
https://github.com/Courseplay/Courseplay_FS22/commit/df06e4e3b5def6a3c3c93c603d6fb25a0696abed
