### ISSUE TITLE
[BUG_MP] Unable to join server after update to 7.2.1.1/7.2.12

### ISSUE THREAD

**Issue by Dewe03** [Courseplay/Courseplay_FS22#2463]
**Steps to reproduce**
Updated from 7.2.1.0 to following 2 versions. Server starts just fine but in the moment someone tries to join you get stuck at 99% and 
Serverlog shows error. Client log stays clear. 
After downgrading from 7.2.1.1 or 7.2.1.2 back to 7.2.1.0 everything just works fine again.

**Courseplay version**
Version used: 7.2.1.1 & 7.2.1.2

**Server Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11240227/log.txt)

**Player on the server**
0.

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Somewhere in Thuringia III

**Relevant script mods**
Autodrive, Enhanced Vehicle, SimpleIC...

**Comment by Tensuko** [comment]
Strange, on that part nothing was changed.

You may try the following:
- make a backup of your savegame
- start your game without CP and save it
- add the latest CP Version to your save and try it again

If the Issue still exists, we have to look deepter into this.

**Comment by Dewe03** [comment]
Tried just as you have written above.
Problem is the same.

**Comment by newbie-near-cologne** [comment]
I made some more test and use also only the minimal mods we need for the used mod map. I also tried to start the game without CP, join, save the game, and then install the latest CP version V7.2.1.2 -> same behaviour if you wanna join it stops at 99%.

Additional I tested with the standard map Elmcreek and all necessary mods for the used mod map, then you can join so it is something in the mod map which trigger the failure of CP V7.2.1.2.

Courseplay version
Version used: 7.2.1.2

Server Log
[ITALIA Emilia Ext MP_only necessary mods_no CP_Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260192/ITALIA.Emilia.Ext.MP_only.necessary.mods_no.CP_Server.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_1_2 after save game without CP_Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260199/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_1_2.after.save.game.without.CP_Server.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_0_5 after Client cant join with CP V7_2_1_2_Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260194/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_0_5.after.Client.cant.join.with.CP.V7_2_1_2_Server.Log.txt)

Client Log
[ITALIA Emilia Ext MP_only necessary mods_no CP_Client Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260191/ITALIA.Emilia.Ext.MP_only.necessary.mods_no.CP_Client.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_1_2 after save game without CP_Client Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260198/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_1_2.after.save.game.without.CP_Client.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_0_5 after Client cant join with CP V7_2_1_2_Client Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260193/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_0_5.after.Client.cant.join.with.CP.V7_2_1_2_Client.Log.txt)

Player on the server
0

Dedicated server or local hosted server
Dedicated server yes

Map
ITALIA Emilia Ext MP

Relevant script mods
No script mods -> see log which mods we used

**Comment by newbie-near-cologne** [comment]
I found now the way to activated all debug channels, so here some additional Logs with debug activated:
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_1_2 alle debug channels activated_Client cant join_Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260774/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_1_2.alle.debug.channels.activated_Client.cant.join_Server.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_1_2 alle debug channels activated_Client cant join_Client Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260772/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_1_2.alle.debug.channels.activated_Client.cant.join_Client.Log.txt)


Here the logs with all debug channels activated and working V7.2.0.5:
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_0_5 alle debug channels activated_Client join_Server Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260804/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_0_5.alle.debug.channels.activated_Client.join_Server.Log.txt)
[ITALIA Emilia Ext MP_only necessary mods_with CP V7_2_0_5 alle debug channels activated_Client join_Client Log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11260803/ITALIA.Emilia.Ext.MP_only.necessary.mods_with.CP.V7_2_0_5.alle.debug.channels.activated_Client.join_Client.Log.txt)

**Comment by schwiti6190** [comment]
Could you try it again with the current main version?

**Comment by Dewe03** [comment]
I downloaded the 7.2.1.3 and updated our server. Everything works just fine. No more errors in the server- or clientlog

**Comment by newbie-near-cologne** [comment]
> @newbie-near-cologne Could you try it again with the current main version?

Testet it and it works without a failure and I can join on the with the mod map. Thanks to you guys. Great support.

Sorry for late answer
