### ISSUE TITLE
[Feature] Improvement of work using smooth curves

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#247]
**What is the problem this feature/enhancement solves?**
using soft curve machining does not work well with some tools. it leaves important pieces unworked and I would like to request a reevaluation on the code. I also reduced the working width, otherwise the area not worked was more.

**Describe the solution you'd like**
I would like it to work better leaving fewer unworked areas

**Additional context**
[Course_work49.zip](https://github.com/Courseplay/Courseplay_FS22/files/7790062/Course_work49.zip)

![fsScreen_2021_12_29_18_47_49](https://user-images.githubusercontent.com/96330304/147690027-8337b602-a22c-4f8f-8771-59839cab2b24.png)
![fsScreen_2021_12_29_18_47_56](https://user-images.githubusercontent.com/96330304/147690047-4d890aa6-1899-438f-ae2b-0cdb4e6f84ab.png)
![fsScreen_2021_12_29_18_49_02](https://user-images.githubusercontent.com/96330304/147690072-a793ea7c-a4a6-4c3d-af81-46e3320cc4c7.png)

**Comment by Tensuko** [comment]
The only option that will come back is overlap on headland for up to 20% to make that less. More won't be done there, sry.
We found some interesting papers about that, its rly interesting, pls read:
![round pattern](https://user-images.githubusercontent.com/27344744/147690660-abdf2097-693f-489f-ad1b-1c2c0e20e9b9.png)
![round corners](https://user-images.githubusercontent.com/27344744/147690668-0a91d560-20b0-4a26-bd0f-57905360ce0d.png)

**Comment by Markus33-ITA** [comment]
Ok thanks for the articles. so i have to change Angle Difference and Delta angle relax? if so, how? decreasing the values ​​should work better, right?

**Comment by Tensuko** [comment]
Try it out :)
