### ISSUE TITLE
Probleme bei Rübenmiete, muss ich da noch etwas einstellen? [Question]

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#2472]
Damit ich es etwas besser erklären kann, heute mal in Deutsch...
Ihr macht echt einen super Job und das neue Feature mit der Rübenmiete und der Courseplay für die Maus ist genau das was ich noch gesucht habe, daher schon mal danke dafür. Ich habe aber noch so meine Probleme damit, besonders beim erstellen der Rübenmiete. Irgendwie fährt der Unloader nach dem abladen nicht weiter (sieht so aus als ob er eine Kollision mit dem Haufen hat). Erst wenn ich manuell weg fahre und CP wieder starte fährt er wieder zum Roder. 
Gleichzeitig fährt er bei jedem neuen Abladevorgang etwas weiter rechts, so dass der Haufen nicht in die Länge, sondern eher diagonal grösser wird. Ich habe mal ein Video dazu aufgenommen: https://youtu.be/wKA9XzfN3o4 
Und falls es hilft, hier noch das log file: https://gist.github.com/DemsMani/f757dea88e8557b62a1483ab376c43b2

Daher meine Frage: müsste ich hier noch andere Einstellungen vornehmen, bzw. kann man das mit der Kollision allenfalls ausschalten (habe aber keine Schaltfläche gefunden). Und um die Miete in die richtige Richtung zu kriegen, kann man irgendwo selektieren dass er immer in der gleichen Spur fährt zum abladen und nicht bei jedem Vorgang weiter nach rechts rückt?

**Comment by Tensuko** [comment]
Man sollte am besten einen normalen Trailer verwenden und keinen Überladewagen um das zut Seite driften zu vermeiden.
Da müssen wir uns noch etwas überlegen, wie wir das gleichmäßiger kriegen für den Überladewagen.
In unseren tests sind die Haufen nicht so groß geworden daher gab es auch kein weiter rüber wachsen das Haufens.
