### ISSUE TITLE
[BUG_SP] Kinze 4905 BLUE DRIVE

### ISSUE THREAD

**Issue by GoharZ-97** [Courseplay/Courseplay_FS22#2477]
**Steps to reproduce**
Attach the above mentioned sprayer/seeder and fill only the seed tank. 

**Actual behavior**
A text appears saying "Needs to be filled up"

**Expected behavior**
Well actually planting crops without herbicide.

**Screenshots**
![bruv](https://user-images.githubusercontent.com/37845630/233469408-94206907-c1fd-42d8-9d77-522b14c2edcf.png)

**Courseplay version**
Version used: 7.2.0.5

**Log**
https://gist.github.com/GoharZ-97/0a3109d8c99370eb6f4642f263a3f772

**Map**
Elm Creek

**Vehicles/ implements involved**
Kinze 4905 BLUE DRIVE
Mod: no 

**Relevant script mods**
No

**Comment by regs1980** [comment]
CP settings, deactivate fertilizer function of the seed drill.

**Comment by Tensuko** [comment]
Exactly.
