### ISSUE TITLE
[BUG_SP] Cant create Course for Mulching on a very Big Grape Field 

### ISSUE THREAD

**Issue by Evilchicken98** [Courseplay/Courseplay_FS22#2478]
**Steps to reproduce**
Traktor + Mulcher setze Zielpunkt klicke Feldposition an
Tractor + Mulcher set finishpoint klick on Fieldposition
Mehrmals reproduziert wenn das Spiel nicht Abstürzt erstellt es lediglich einen Kurs für normale Feldarbeit ich komme auch nicht in das Rebenmenü.
Reproduced several times if the game doesn't crash it just creates a course for normal field work I can't get into the vine menu either.

**Actual behavior**
Kann keinen Kurs für Rebenbearbeitung Mulchen erstellen es lädt ungefahr 10min lang mit Standbild und endet dann mit 2023-04-21 01:28 Error: Running LUA method 'mouseEvent'.
not enough memory.
Cant create Course for Mulching on a very Big Grape Field it loads 10min with frozen screen and ends with 2023-04-21 01:28 Error: Running LUA method 'mouseEvent'.
not enough memory.

**Expected behavior**
Das CP einen Kurs für die Rebenbearbeitung erstellt.
Get CP to create the right Course for Vineyardwork.
Habe es auf der Elmcreek erfolgreich testen können.
I was able to test it successfully on the Elmcreek.

**Screenshots**
![Map Gnadenthal](https://user-images.githubusercontent.com/122698222/233522428-5242a2e8-e967-49f1-ad16-2e842652149c.jpg)
Feld Trauben 23. 19ha, 24. 11ha, Etwas verkleinert per Landscaping. Sind die Felder vll. einfach viel zu Groß?
Field Grapes 23. 19ha, 24. 11ha, Made them smaller via Landscaping. Are the fields maybe too big?

**Courseplay version**
Version used: 7.2.0.5 Modhub

**Log**
[log nr.1.txt](https://github.com/Courseplay/Courseplay_FS22/files/11291584/log.nr.1.txt)
[log nr.2.txt](https://github.com/Courseplay/Courseplay_FS22/files/11291585/log.nr.2.txt)

**Map**
Gnadenthal 1.3.0.0 but changed by me via GE removed Buildings and Trees.

**Vehicles/ implements involved**
Standard Case Maxxum und(and) Fendt 200 V Vario.
Standard Mulcher Salek Mul-1000. Mod Mulcher Lopez Garrido TGA 2200 (Modhub) Arbeitsbreite vergrößert auf 3,5m.(Workingwith extended to 3.5m).
CP erkennt die Arbeitsbreite beim Lopez nicht es funktioniert aber trotzdem. Habe es auf der Elmcreek getestet er kommt durch die Reben durch.
Habe mich noch nicht damit befasst wie ich die Mods auf Helfer anpasse.
CP does not recognize the working width on the Lopez, but it still works. Tested it on the Elmcreek its getting through the vines.
Haven't dealt with it yet how to adapt the mods to helpers.

1.Test Case mit Lopez Mulcher Zielpunkt gesetzt Feldposition gesetzt 7min geladen Kursmenü für normale Feldarbeit geöffnet kurs generiert Menü geschlossen Spiel ist eingefroren und abgestürzt (Programm reagiert nicht-Programm Schließen) siehe Log nr.1
2.Test Fendt mit Salek Mulcher Selbes Ergebnis wie beim ersten Test Spiel ist nicht abgestürzt! Trotzdem Falsche Kursart berechnet. Spielstand beendet Spiel abgestürzt. Log Nr.2
1.Test Case with Lopez Mulcher Target point set. Field position set. loaded 7min. Only got the coursemenu for normal field work. Course generated menu closed Game froze and crashed (program does not respond-program close) see log nr.1
2nd test Fendt with Salek mulcher. Same result as in the first test game did not crash! Nevertheless, the wrong course type was calculated. (Left the savegame Game crashed.) Log #2

**Relevant script mods**
Autodrive 2.0.1.0

**Additional info**
Ebenfalls habe ich getestet 4 Reihen auf Feld 24 vom Rest zu trennen und einen Kurs für die 4 zu berechnen endete im Spielabsturz.
Auch habe ich 2 sehr kurze Reihen auf keine Feldfläche gebaut nach 10 min Laden ebenfalls kein Rebenmenü und den oben genannte Error.
Also, I tested separating 4 rows on field 24 from the rest and calculating a course for which ended in the game crashing.
I also built 2 very short rows on no field area after 10 minutes loading also no vine menu and the error mentioned above.

Ist das was ich versuche einfach zuviel für Spiel, Hardware, Spielstand?
Der Spielstand ist leider auch sehr über viele Fahrzeuge viele Placeables usw.
Nutze CP jetzt noch nicht mal einen Tag lang und habe noch fast keine ahnung davon lediglich ein paar tutorials gesehen.
Kann das Irgendwie gefixt werden?
Is what I'm trying to do just too much for the game, hardware, save?
Unfortunately, the save is very overloaded many vehicles, many placeables and so on.
Haven't used CP for even a day now and have almost no idea about it, just watched a few tutorials.
Can this be fixed somehow?

**Comment by Tensuko** [comment]
#1683
