### ISSUE TITLE
[Question] How to show the full route on the field?

### ISSUE THREAD

**Issue by tintong** [Courseplay/Courseplay_FS22#248]
Hello,

In FS19 there is a way to show the full path, not just the start and end.
Is this possible in the new FS22 please?

Thanks

**Comment by Snigyman** [comment]
Its There. Settings with tractor options and it's first on top.

**Comment by Tensuko** [comment]
Exaclty, Vehicle Options, 1st Option.

**Comment by tintong** [comment]
Thank you.
Sorry, been a long day travelling :(
