### ISSUE TITLE
[BUG_SP]Slurry Tank gets activated while driving to target.

### ISSUE THREAD

**Issue by VJH01** [Courseplay/Courseplay_FS22#2480]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Creat a field course for  slurry and AD course to fill up the slurry tanker. Also the ouput of slurry musst be doubled! (Hint: You have to activate the double outpunkt on the slurry tanker and the slurry attachment!)

**Actual behavior**
After refiling and arriving by the field AD gives over to Courseplay and Courseplay will drive to the last position on the field. But the speed is limited to 8km/h, changing the settings makes no difference. After arriving on the last position he starts again working.

**Expected behavior**
I would expect that he drives faster then 8km/h on the field, if he wants to go to the last point. In my settings i have field speed = 20km/h. I think the field speed is wrongly limited by the working speed (8km/h) of a slurry tanker with double output. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96574322/233768950-91344dcd-bbfa-4153-9d73-454bdca61530.png)

**Courseplay version**
Version used: 7.2.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11300491/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Fendt 942
Veenhius Integral 30000
Samson SBH4 36
Goma front tank Mod

**Relevant script mods**
AD 2.0.1.0

**Comment by Tensuko** [comment]
Because its active. Known Issue.

**Comment by Tensuko** [comment]
We found out that this also happens if Giants AI use free drive, so this is more a Giants Issue.
We will get in contact with them and hope for a solution.
