### ISSUE TITLE
When compacting the silage comes out of the bunker

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#2484]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Compact Bunker

**Actual behavior**
when compacting, the silage comes out of the bunker.
Couldn't we go back and forth on the silo (as in FS17 - FS19)
We can't move back with Courseplay anymore?

**Expected behavior**
Silage should not come out of the silo when compacting
I'd rather do forwards - backwards on the silo, like in FS 17 /FS 19.
Couldn't we go back and forth on the silo (as in FS17 - FS19)
We can't move back with Courseplay anymore?

**Screenshots**
Before compacting begin (picture1)
![image](https://user-images.githubusercontent.com/36656729/233854225-cfb9151b-6e7f-4068-94a7-77eed88d5a31.png)
After compacting at 100% (picture2)
![image](https://user-images.githubusercontent.com/36656729/233854329-6ede3e96-81e1-457f-a3e1-93c9ecfb0a0f.png)

**Courseplay version**
Version used: 7.2.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11304346/log.txt)

**Map**
Map played on. Clarkson

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Welcome to FS Physics.
Won't fix.

**Comment by Tensuko** [comment]
Explanation:
This have nothing to do wich CP.
The compacting in FS22 works different then in FS17 and FS19.

**Comment by Crinouche** [comment]
OK and for the reverse gears with courseplay?

**Comment by Tensuko** [comment]
???

**Comment by Crinouche** [comment]
I just wanted to know why we can no longer create reverse then forward movements with Courseplay?
2 interests in generating personal itinerary:
- To compact the bunker silo. We go on the pile of silage and go back and forth.. This prevents the silage from coming out of the silo.
- To make routes in the narrow fields that I could record, in order to make the various interventions. In the photo, I generated a course on a narrow custom field. Courseplay generated only one headland and a lot of small round trips, whereas 2 headlands, on the length, are enough. For this reason, a personal itinerary who go from point A to point B would be good. And we could do it on a loop or just once...
This is why I asked this question.
![image](https://user-images.githubusercontent.com/36656729/233929175-dfa85056-39a8-4ba7-836a-810e143f9e6e.png)

**Comment by Tensuko** [comment]
Because we do not want it.
