### ISSUE TITLE
[BUG_MP] lua fehler

### ISSUE THREAD

**Issue by Boomchy** [Courseplay/Courseplay_FS22#2490]
2023-04-25 09:50 dataS/character/humans/npc/pedestrians/generic/npcCommon09_m.i3d (32.75 ms)
2023-04-25 09:51 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:51 :29 [info lp434448] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:51 :53 [dbg10 lp435538] appendEndingTurnCourse: dzVehicleAtTurnEnd: 0.0, dzWorkStart: -4.2, extra 6.0)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:52 :08 [info lp436233] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:52 :11 [info lp436398] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:52 :15 [info lp436563] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:52 :19 [info lp436727] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update
2023-04-25 09:52 :22 [info lp436891] C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua:1072: bad argument #2 to 'max' (number expected, got nil)
2023-04-25 09:52 LUA call stack:
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : printCallstack
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (1072) : max
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (803) : findBestWaypointToUnload
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (436) : callUnloaderWhenNeeded
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (276)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/PurePursuitController.lua (263) : notifyListeners
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCourse.lua (384) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (107) : update
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyCombineCourse.lua (182) : update
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (255) : update
  =[C] (4294967295)
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (258) : xpcall
  =C:/Users/ls21/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (364) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1887) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1141) : update
  dataS/scripts/FSBaseMission.lua (1985) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1257) : update

**Comment by Tensuko** [comment]
Bitte noch mal richtig ausfüllen, danke.
