### ISSUE TITLE
[Feature] Inselerkennung bei selbst erstellten Feldgrenzen ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2492]
**What is the problem this feature/enhancement solves?**
kann man bei selbst eingefahrenen/eingezeichneten Feldgrenzen auch Inseln aus der Bearbeitung entfernen?
 
**Describe the solution you'd like**
wenn ich ein Feld bzw eine Wiese umfahre, die innerhalb einige Bäume hat, ignoriert CP diese.

**Describe alternatives you've considered**
das man z.b. eine "Äußere" Feldgrenze (cp-1) und eine "innere" Feldgrenze (cp-2) abfährt/aufzeichnet, so wie am unten eingefügtem Bild und das cp danach bei der Kursberechnung die Fläche von cp-2 nicht bearbeitet
**Additional context**
![fsScreen_2023_04_25_19_04_39](https://user-images.githubusercontent.com/24860501/234350935-11e3d427-2b2f-4420-a082-3dfc4c7c583d.png)

lg
andreas

**Comment by Tensuko** [comment]
Nur im Editor, automatisch wird es nicht geben.
Steht auch schon unter Discussion.
