### ISSUE TITLE
[Question] Multiple overloaders using multiple Combines on large fields

### ISSUE THREAD

**Issue by AUZ001** [Courseplay/Courseplay_FS22#2493]
Can this be done?
Is there a tutorial on how to go about using multiple tools on large fields with CP in FS22?

It would be great if each overloader (chaser-bin) can find and chase a combine and stay within a defined radius or set radius so the overloader is in close proximity of the combine when it needs it.

At the moment, the overloader sits at one end of the field whilst the combine sits at the other end of the field waiting to be unloaded.

It appears the 2nd or 3rd overloader will not begin or target any combine until the 1st overloader is completely filled.
It would be more feasible to have multiple overloaders working simultaneously if at all possible?

This is by no means a complaint, I praise the developers for such a great mod. I am just hoping to get some guidance or tips on the best way to tackle this issue with large fields and multiple tools.

Thanks in advance,

AJ

**Comment by Tensuko** [comment]
It works like it is now.
There is no plan to change anything to this system.
If the combine is set to an unloader and the enxt combine needs one it will call another unloader.
The priority is always to get an Unloder full to be ready agin asap.
