### ISSUE TITLE
Differnt default keybind for course generator or a clear course option

### ISSUE THREAD

**Issue by pops64** [Courseplay/Courseplay_FS22#25]
I haven't looked at my keybindings but by default Start Job and Course Generator share the same key bind. AKA you can't redo the course generator without first clearing the course. And there doesn't seem to be a button for that either. You can use the mouse to click on the course generator but the point still stands. 

![fsScreen_2021_12_24_09_52_23](https://user-images.githubusercontent.com/10678220/147360319-999a3c1c-1694-4804-91bb-a36bfbef5b39.png)
.

**Comment by Tensuko** [comment]
You are right, will have to find a solution for this.
As far as I know, the keybinds are set by Giants UI System.
@schwiti6190 might know whats wrong.

**Comment by schwiti6190** [comment]
Will be fixed with the next version :)

**Comment by Keppchen** [comment]
Uff das ging leider nach hinten los (Meine Meinung)... 

Am Controller mit A den Kursgenerator öffnen? Damit lassen sich andere Menüpunkte auf die man mit Controller navigiert und die man bisher mit A angewählt hat nicht mehr öffnen und man muss die Maus nehmen. Und bei geöffnetem Kursgenerator wird dieser mit A geschlossen? Widerspricht nicht nur dem gewohnten Verhalten dass B Fenster schließt, sondern verhindert auch innerhalb des Kursgenerators das Anwählen eines Punktes mit A.

Also A sollte meiner Meinung nach nur für das "Anklicken" ausgewählter Punkte sein und keinesfalls als KeyBinding hinterlegt werden.

**Comment by schwiti6190** [comment]
Yes your righta complete overhole for controller/keybindings is in the working :)
