### ISSUE TITLE
Forage harvester - Full grain tank [BUG_SP]

### ISSUE THREAD

**Issue by ghod90** [Courseplay/Courseplay_FS22#250]
**Steps to reproduce**
Setup forage harvester (krone x1180)for a grass field
Add silage additive 
Attach trailer
Generate course and hire worker 

**Actual behavior**
Forage harvester moves to start point starts mower and complains that grain tank is full with trailer empty.
Attempted with auto drive controlling a trailer as well same behavior with trailer on a second vehicle. Giants worker can harvest the field as expected with a trailer nearby/attached.

**Expected behavior**
Harvester follows course and stops when full or worker pulled trailer moves away (as giants worker will) 

**Screenshots**

**Courseplay version**
Version used:  7.0.0.8

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Krone X1180 with and without a trailer and xdisc 620 header

**Relevant script mods**
Autodrive also used for testing trailer nearby

**Comment by Tensuko** [comment]
#109
