### ISSUE TITLE
[BUG_SP] had to revert to x.x.1.0 to get bale wrapper to not complain about being too far from the field

### ISSUE THREAD

**Issue by Thunderloon** [Courseplay/Courseplay_FS22#2502]
xx.1.3 (and prior) "CP: too far from field" in non-course mode with a bale wrapper
that's pretty much it... reverted to x.x.1.0 and hasn't complained since
bale collectors worked fine in newest version so its pretty obvious someone's tripped over a gerund or something

**Comment by Tritura2** [comment]
> Bale collector/wrapper now works the same way, as the combine unloader in terms of markers.
The field position is now saved into the vehicle and will not be reset to the vehicle position, when started by the hud!
The position has to be set everytime in the ai menu!
This fixes problems with AD restarting and also has the advantage that you don't need another AD Target on the field to start the driver.

**Comment by Tensuko** [comment]
Read the changelog!
