### ISSUE TITLE
grape course freezes game

### ISSUE THREAD

**Issue by JayJay2809** [Courseplay/Courseplay_FS22#2504]
**Steps to reproduce**
create a path for grapes on a field

**Actual behavior**
game freezes and have to close it with task manager

**Expected behavior**
creates a course to harvest/ maintan the grapes

**recording/mods list**
https://youtu.be/RANsJ4enL_g

**Courseplay version**
version 7.2.0.5

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
elmcreek

**Vehicles/ implements involved**
landini rex 4-120 GT
Mod no

**Relevant script mods**
n

![20230430191135_1](https://user-images.githubusercontent.com/132220408/235366986-16c8992b-180e-400d-9692-10823a5656e8.jpg)
![20230430191124_1](https://user-images.githubusercontent.com/132220408/235366988-9f54ff2d-8db4-434c-b48f-7c42a8b99fcb.jpg)
![20230430191127_1](https://user-images.githubusercontent.com/132220408/235366989-97596d26-603a-4f51-bf9f-797493f4ad96.jpg)
![20230430191131_1](https://user-images.githubusercontent.com/132220408/235366992-5e3eaa22-0be8-421b-b52d-1248d76903d9.jpg)
![20230430191133_1](https://user-images.githubusercontent.com/132220408/235366993-421597b4-b026-4b1d-bff9-28f8319c0303.jpg)

**Comment by Tensuko** [comment]
Logfile when this happens, else we cant do anything...

**Comment by JayJay2809** [comment]
cant find the log file been trying to find it for the pas 5 hours and still cant find it

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by JayJay2809** [comment]
tried didnt work

**Comment by Tensuko** [comment]
You are in the complete wrong folder.....
Read it again. Its documents mygames.... Not game folder itself.

**Comment by JayJay2809** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11368155/log.txt)

**Comment by Roby1164** [comment]
> [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11368155/log.txt)

First from the video you attached, you don't see anything, i.e., it shows that you haven't created any CP workpath, for that grape head.

The log you have attached is useless, since you started the game, and closed it even before it finished loading, while it needs to start completely and get to the moment it crashes,, so I think, from what you say, when you start working the grape field.

**Comment by JayJay2809** [comment]
well i just recreated it and waited for it to unfreeze it took about 50 min

**Comment by Tensuko** [comment]
Can you post your savegame here?
Put it into a .zip and just attche it like the log.txt
Need to check something.

**Comment by NathanS-8500** [comment]
Should I be concerned about doing a grape harvest course myself?

Asus Gaming laptop
i7 core processor
8 GB of RAM
CPU runs in the range of 2.60 GHz

**Comment by JayJay2809** [comment]
maybe i am running

custom pc build
intel i9-9900 3.60GHz
NVIDIA RTX 2070 super 
16GB ram
might have done it wrong with the zip file pls let me know if it is
[savegame4.zip](https://github.com/Courseplay/Courseplay_FS22/files/11373973/savegame4.zip)

**Comment by Roby1164** [comment]
> Can you post your savegame here? Put it into a .zip and just attche it like the log.txt Need to check something.

I also tried, with its save, actually, in this case it crashes as soon as you press on no course, but I don't understand what the problem is, since in my save, despite having many more mods, and also the modded map, it doesn't crash, but in its log, you see that Warning " Performing emergency garbage collection pass - memory went from 227019 KB to 482480 KB in less than one frame " and the error " Failed to create Pipeline State 23. This can have different reasons :
  - Input signature expects to read an element, but the declaration doesn't provide a matching name. " and also the subsequent lua errors, which worry me, but I don't understand what they refer to...

**Comment by Tensuko** [comment]
I would try to move away from the grapes and click on no course, then see what happens if try to select the grape field. The more manual way. Is it "no course" or is it the selection or maybe the grape field. If too big it might be a problem that we have an Issue for already.

**Comment by Roby1164** [comment]
Ok found the problem, the problem is in field 36, which I'm sorry but you have to delete it and do it all over again.

**Comment by Roby1164** [comment]
> 

No, he planted those vines, in fact the field is still seen as cultivated with sunflowers, which is why he has to remove the vines, plow, and then reposition the vines.

**Comment by JayJay2809** [comment]
![20230502193505_1](https://user-images.githubusercontent.com/132220408/235742280-aa866064-02bf-461b-92c6-36c11a1ea433.jpg)

**Comment by Roby1164** [comment]
> ![20230502193505_1](https://user-images.githubusercontent.com/132220408/235742280-aa866064-02bf-461b-92c6-36c11a1ea433.jpg)

Yes ok, but I advise you to remove the vine, plow and then put them back.

**Comment by JayJay2809** [comment]
thats what i did

**Comment by Tensuko** [comment]
It might be too big already.
See #1683
https://github.com/Courseplay/Courseplay_FS22/issues/1683#issuecomment-1147388739

**Comment by Roby1164** [comment]
I repeat, as mentioned, you must eliminate all the vine, and create it correctly. In the photo I am attaching, as you can see, after eliminating the rows, the problem no longer exists. You have to be careful when positioning the vine, it's better to stay further inside the field, to avoid overshooting, and creating problems like this.
![Screenshot_14](https://user-images.githubusercontent.com/24955554/235914349-94ff7e53-e5ed-4e82-9427-da1ad81f987c.jpg)

**Comment by JayJay2809** [comment]
yes it works thanks for helping me with this i will close the issue now :)
