### ISSUE TITLE
[BUG_SP]Game crashes when I try to generate a course on EdgeWater Sask

### ISSUE THREAD

**Issue by Randy12144** [Courseplay/Courseplay_FS22#2508]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
On EdgeWater Sask im trying to generate a harvest course with a 8.5m header around the bigger half of field 1. I have tried with 2 headlands, no headlands and the game crashes everytime.

Also the field selector tends to merge field 1 and the adjacent field to the east depending on where I place the field selector. I have also tried to create a custom field and use that instead to generate the course with the same issue.

**Actual behavior**
Game crashes as soon I click to generate a course

Smaller half of field 1 worked perfectly

**Expected behavior**
Course generation

**Screenshots**

**Courseplay version**
Version used: 7.2.0.5 and tried with 7.2.1.3

**Log**
Please attach a log with all debug channels active.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11378855/log.txt)
Log File dosen't seem to have much past me selecting the field
For help with the debug channels,
please check out the readme at the github front page.

**Map**
EdgeWater Saskatchewan

**Vehicles/ implements involved**
New Holland CH7.70  8.5m header, base game

**Relevant script mods**
I have AutoDrive 2.0.1.0 and VCA installed

**Comment by Tensuko** [comment]
No Error in logfile.
What do you call a game crash?
When a game crashes, it will close and you land on desktop.
Course generation can take some time depends on the sice and complexity of the field -> patience!

So I need a logfile when the "crash" happened, or more details like how the field looks like (screenshot?) etc.

**Comment by Randy12144** [comment]
The game freezes until it eventually goes unresponding and forces me to close the game back to desktop. And thats the log file i get after im back on desktop. It stops logging the moment i click generate course.

I will get a screenshot shortly

**Comment by Randy12144** [comment]
I did have to wait quite a while but it eventually worked

**Comment by Tensuko** [comment]
A freeze is not a crash.
You might need some patience!
And yes during course calculations there is no response and even it goes with no response windows msg it will get back and work just fine.

Not a bug. Closed.
