### ISSUE TITLE
[Feature] Slurry/Seed Refill or Field side Pickup Mode

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#2509]
**What is the problem this feature/enhancement solves?**
When using CP with and without AD in Conjunction to do seeding or Slurry Work.
 I thought it would be nice if there was an easy way to have the Driver refill its "consumbales" like Seeds, more interestingly Slurry or Digest from the field side. Instead of using AD to drive back to the farm to refill.

**Describe the solution you'd like**
There are two things that come to mind to help with this are: 
1) An Option for the driver to search the field and its direct surrounding for opportunities to refill. This may work similarly to how a Combine can unload itself into a trailer waiting at the field edge, but reversed, or how a transfer wagon can unload at the field edge. 
For slurry specifically, this could be done by having either a big tanker deliver slurry to the field side via AD/BaseGame Helper or by using one of the Game's Field Edge Tanks to refill itself.
2) This one would be more complex, a new Mode prompting the Driver to drive onto the field next to another working helper and use the Attached Tank or Transfer wagon to deliver seeds or slurry to the waiting Fieldworker.

**Describe alternatives you've considered**
Currently, the only other way to achieve this idea would be a rather Janky AD course setup, putting multiple Waypoints right next to each other.

**Additional context**
I am not 100% sure which side/mod this the better to post this seems to be rather on the border between CPs and ADs work areas.

Grüße
PapaTim68

**Comment by Tensuko** [comment]
Duplicate
#2069
