### ISSUE TITLE
[Feature] Check implement down before continuing after turn

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#251]
**What is the problem this feature/enhancement solves?**
When using the Dalbo Powerroll 1230 roller for example, it takes a long time for the implement to start working, after lowering started. In those cases it would be good, if CP stopped and waited for the lowering to finish, before continuing.

**Describe the solution you'd like**
Check for implement lowering complete before ending turn

**Describe alternatives you've considered**
option to disable lifting in turns

**Additional context**
. ----.

**Comment by Tensuko** [comment]
Do you have a screenshot of the turn when he starts to work ?
Also try to change to lower early.

**Comment by JDTiger** [comment]
Video of the turn, lower early is activated

https://youtu.be/lsUxm5kmIlw

**Comment by jacquesbrele** [comment]
I have the same problem on the same roller 😅

**Comment by StefanBraun2001** [comment]
Same problem. However on headlands it works as intended since the driver waits for the tool to lower completly.

**Comment by Markus33-ITA** [comment]
I confirm and even at the beginning of the course he does not wait for the complete opening.

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
