### ISSUE TITLE
[BUG_SP] Combine Unloading using auger wagon sometimes does not work

### ISSUE THREAD

**Issue by zhaojk19** [Courseplay/Courseplay_FS22#2511]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Single player, mod map Iowa Plain View, new farmer start mode

**Actual behavior**
A clear and concise description of what happen.
I use 6230R tractor which is initally given in new farmer mode, connect it to an auger wagon to use "conbine unload" mode, then it shows a message:"Gaint unloader not available"
![20230504130032_1](https://user-images.githubusercontent.com/67081407/236118082-6a43d360-2d50-4303-8016-fc4db5bb3fef.jpg)
![20230504130039_1](https://user-images.githubusercontent.com/67081407/236118208-0a27a66a-0041-4b99-a9cc-987bbbf65261.jpg)

**Expected behavior**
I borrowed a new 6230R tractor from shop, same procedure, start work, ui is different:
![20230504130304_1](https://user-images.githubusercontent.com/67081407/236118347-87868c82-453c-48fc-a24a-3d9e3fda67df.jpg)
It looks like that the condition on the right hand side is different.
By the way I'm Chinese, “关闭”means closed and deactivated，“开启” means activated

**Screenshots**

**Courseplay version**
Version used: 7.2.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on: Iowa Plain View V1.2

**Vehicles/ implements involved**
Which vehicle or implement? John Deere 6230
Mod yes/no ? no mod

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Only use CoursePlay and Autodrive.

**Comment by Tensuko** [comment]
A logfile and a screenshot from the HUD would be interesting.
The 6230 is vanilla?
The Giants Unload is only available with Trailer.
Basically, when you use a normal Trailer, you can:
- Unload the combine
- When Trailer full, jsut stop
- When Trailer full, hand over to AutoDrive
- When Trailer full, hand over to Giants

Auger Wagons however should not be able to hand over to Giants.
Why it does work with a new Tractor, not sure.
Did you use a Trailer on the original R 6230 before and used Giants unload?

Becouse when I see this Screenshot, it seems like the Giants Unload function is active, even its gray am I right?
![grafik](https://user-images.githubusercontent.com/27344744/236122005-adeb2600-492b-49c3-9536-a5c0d9c32bc1.png)

That might be the reason why this message comes up.

**Comment by zhaojk19** [comment]
> 
Thank you for answering my question！
1.6230R is a type of tractor from John Deere

2.Did you use a Trailer on the original R 6230 before and used Giants unload?  
put a trailer on: yes, couple of times. use Giant unload helper?never, only autodrive and courseplay.

3.it seems like the Giants Unload function is active, even its gray am I right?
I think this is right! its activated and still gray, that's exactly the reason of that message.

I don't really know how to submit the logfile to you
Why it works on a new tractor? I don't know but I think there might be two reasons:1.wrong setting by the new farmer mode initializatiion. 2. the old tractor have a history using a trailor. the first one can be ignored whereas the second one might need a bug fix.

**Comment by Tensuko** [comment]
I think at some point the tractor got the giants unload setting to active, thats not default and thats why the new one works.
We will try to find a solution for this when attaching an auger wagon.
Workaround: attach a trailer and turn off the blue wheel on hud if its on or check job menu to turn it off.
Then it should work again.

For logfile it is written on the wiki page.

**Comment by zhaojk19** [comment]
ok now I know the reason
I connect the old tractor to a trailor and deactivated the gaint unloader. Then I connect this old tractor to an auger wagon and it works well, problem solved.
The mistake I made is that I think using Courseplay to unload the harvester and send silo to some place has nothing to do with gaint unloader. It turned out that I'm wrong. Courseplay unload the harvester and send the mission to gaint unloader, that's why the gaint unloader is always activated when using a trailer.
Thank you so much! I think this bug report can be closed now.

**Comment by Tensuko** [comment]
We keep it open and figure out a way that the trailer setting is not relevant for auger. :)

**Comment by Tensuko** [comment]
Should not lock up, however in my tests I could generate a course, but there is no 100% guarantee it will work.
There will be a rework for vines soon or later...
