### ISSUE TITLE
[BUG_SP] Unloader collides with potato harvester after unloading. 

### ISSUE THREAD

**Issue by Symbob** [Courseplay/Courseplay_FS22#2518]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Harvest a field with CP helper.  Create unloading course for CP unloader plus transport course to be used by AutoDrive.

**Actual behavior**
After unloading the harvester the unloader tractor collides with the harvester when attempting to return to the Target Position.  Eventually it will attempt to reverse away from the collision and try again but by this time the harvester, which has been "Blocked by an object" has stopped and the CP helper gives up control of the harvester.  I didn't have this issue in earlier versions, and I believe it has only become a problem since CP now takes the unloader back to the Target Position before handing over to AutoDrive to do the transport course.  In earlier versions CP handed over to AutoDrive as soon as the trailer was full.  The other strange thing is that the "Avoid Fruit" option doesn't seem to work now either, because CP creates a route across the fruit to get to and from the harvester.  Perhaps if the unloader was avoiding the fruit it would turn away from the harvester instead of towards it?

**Expected behavior**
I would expect the unloader to not collide with the harvester.  Maybe wait longer for the harvester to move away before attempting to drive to the target position, or detect the harvester and stop before colliding with it.
I would also expect the unloader to avoid driving on fruit when this option is selected.

**Screenshots**

Avoid Driving in Fruit is activated

![fsScreen_2023_05_08_18_47_05](https://user-images.githubusercontent.com/18528850/236919376-4a1d10b6-4298-4a84-bf63-d52dd92de812.png)

CP plots course through fruit to harvester
![fsScreen_2023_05_08_18_46_52](https://user-images.githubusercontent.com/18528850/236919678-efad0c3a-76d8-4696-9cc8-1610ab741753.png)

Unloading as expected
![fsScreen_2023_05_08_18_39_28](https://user-images.githubusercontent.com/18528850/236919814-a6cbe7a3-c4ed-48fa-83fa-dbbf4e51a009.png)

Unloader stops when full but plots course to the Target Position through fruit
![fsScreen_2023_05_08_18_48_31](https://user-images.githubusercontent.com/18528850/236920079-11773b2d-6169-40f7-8c8e-0867e5c76836.png)

Unloader starts driving to Target Position before Harvester has had time to clear the area.
![fsScreen_2023_05_08_18_48_34](https://user-images.githubusercontent.com/18528850/236920454-ed3dae87-cc8c-4b99-8b74-5d690382cfbe.png)

Unloader collides with harvester
![fsScreen_2023_05_08_18_48_40](https://user-images.githubusercontent.com/18528850/236920546-bd6790e6-f22b-4013-82ce-3cd1a8a86ea4.png)

Unloader reverses and has a second attempt at reaching Target position.  CP gives up control of the Harvester
![fsScreen_2023_05_08_18_49_01](https://user-images.githubusercontent.com/18528850/236920717-0b370b45-77db-421d-b3ba-6a90d1268b0e.png)

**Courseplay version**
Version used: 7.2.1.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11424477/log.txt)

Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
No Mans Land

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

Giants Grimme Varitron 470 Terra Trac from Modhub
in game Fendt 942 Vario (but the same thing happens with other tractors too)

**Relevant script mods**
Mods like Autodrive or VCA and so on.

CP & AutoDrive

**Comment by Tensuko** [comment]
The problem with trough the fruit is that he tries to create a course arround but gave up too fast I guess.
Need to tweak this.
Why he ramed the harvester, is a qood question, the sensor should have avoid this.

**Comment by Tensuko** [comment]
Not sure if that is rly a problem anymore.
My last potato harvest with this haverster was flawless.
Could be an edge case, closing.
