### ISSUE TITLE
[Feature] Change the Way Combines Return to Fruit in Field

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#2519]
**What is the problem this feature/enhancement solves?**
Using a combine with a large header, and the header is "in the fruit" CP currently stops the combine, reverses it back & away from the fruit. This part is excellent and allows the tractor to pull right up and offload. However, when the combine returns to the fruit, it typically misses a portion on the far right of the header.

**Describe the solution you'd like**
I'd like the combine to move back to the fruit as it does now, but instead of immediately lowering the header and continuing on, the combine should reverse about 5 meters, lower the header and then carry on. From my experience this would eliminate the majority of the fruit being left behind.

**Describe alternatives you've considered**
It is really hit or miss and I'm not sure which header size generally works best because it seems to also depend on how agile the combine is, but generally, I don't see fruit left behind by headers that are under 10 meters in width.

**Additional context**
This is how CP does it now: https://drive.google.com/file/d/1VQf4eUN1ndCsPugc7SqmvBiaskFNl1vC/view?usp=share_link
This is my suggestion: https://drive.google.com/file/d/1u4FleNrv4cxMrUocICD-oq-QLM1JyThr/view?usp=share_link

**Comment by Tensuko** [comment]
What Combine, what header.
Example Screenshot?

**Comment by lcc1211** [comment]
Basically, the larger headers of 10+ meters. I'm trying to upload a video and link here so you'll see an example.

**Comment by lcc1211** [comment]
In the links I added above, I'm using the Modhub version of the Class Convio 1380 header (13.8M) with the Class Lexion 8900 combine. However, the combine and header are agnostic here as width of the header seems to be the determining factor. To be sure of this, I also used a smaller header of 7.6 meters which left no fruit behind. I also used the Modhub New Holland 10.90 with the 14.7M draper header and it also leaves fruit behind.

**Comment by Tensuko** [comment]
Not that simple as you imagine, but I get your Idea.
Will figure something out.

**Comment by pvaiko** [comment]
Moving back a little further may help, you can adjust the constant at https://github.com/Courseplay/Courseplay_FS22/blob/88956b6980ec85982137f8bbe19c10403ea7532e/scripts/ai/AIDriveStrategyCombineCourse.lua#LL137C1-L137C1

**Comment by leo32128fs** [comment]
> Recuar um pouco mais pode ajudar, você pode ajustar a constante em https://github.com/Courseplay/Courseplay_FS22/blob/88956b6980ec85982137f8bbe19c10403ea7532e/scripts/ai/AIDriveStrategyCombineCourse.lua#LL137C1-L137C1

The line I need to change is this >>> self.pullBackDistanceStart = 2 * AIUtil.getTurningRadius(self.vehicle)

**Comment by Tensuko** [comment]
Yea and try it out if that does help you.

**Comment by lcc1211** [comment]
I'll try adjusting in increments of 1 and see if there is a best number. Bare with me since my friends and I are playing a marathon session, so it will most likely be a day or 2.

**Comment by lcc1211** [comment]
I apparently do not know what I'm doing. I unzipped the CP file and updated the line you highlighted. Then I zipped it back up and put it back in the MOD folder. I got the prompt asking if I wanted to overwrite the CP file and I selected YES. However, when I try to launch FS, it tells me CP is missing.

**Comment by pvaiko** [comment]
No need to zip it back up, you can just put the unzipped folder under mods so you have everything unzipped in mods\FS22_Courseplay and make the changes directly there.

**Comment by lcc1211** [comment]
I'm sorry to report that upping the number to 2, 3 and 4 made no difference. The combine still moves up to near the work start line and turns in sharply missing the same bit of fruit.

**Comment by pvaiko** [comment]
Thanks for checking it out. We'll figure out something else.

**Comment by coatsy35** [comment]
Any chance when it creates the unloading pocket, it can stop before it reverses to empty the straw out - like what happens now at the end of a run which is great. As currently when creating pockets it creates "arcs" of straw each time

**Comment by lcc1211** [comment]
> Any chance when it creates the unloading pocket, it can stop before it reverses to empty the straw out - like what happens now at the end of a run which is great. As currently when creating pockets it creates "arcs" of straw each time

Isn't it better to avoid large piles of straw, though?

**Comment by coatsy35** [comment]
> > Any chance when it creates the unloading pocket, it can stop before it reverses to empty the straw out - like what happens now at the end of a run which is great. As currently when creating pockets it creates "arcs" of straw each time
> 
> Isn't it better to avoid large piles of straw, though?

IRL when I was driving a combine, you would back up and lay the straw over the row a little way until it stopped coming out so you didn’t create a pile for the baler. However since CP has decided no to do that and just stop at the end of a row so it doesn’t make arcs out the end of the row (like it did a few months ago) it would be good if it did the same when creating a pocket. Unless they wish to make it more realistic and make it back up to overlay instead as an addition which would be cool, but might not be possible
