### ISSUE TITLE
[Question] Combine Harvester issue?

### ISSUE THREAD

**Issue by tintong** [Courseplay/Courseplay_FS22#252]
Hello,

Not sure if this is a bug or just me not understanding it yet. Sorry.

I'm using the Claas Trion 750 to do a contract on Haut-Beyleron for field 18.
I've set CP to start in the top right corner.
The settings I decided to use are:

2 x headlines going in circle
then up and down
Rest are default.

When I drive close to the starting point, and click on start job it always comes up with Helper AI x blocked by an object.

There is nothing else on the field or in the area.

Any tips please?

Thanks

[Edit]

So after waiting about 5 mins, the combine has started to do the task.
Did I do something wrong?

**Comment by 60erjonny** [comment]
Giants is strange every now and then.
But: Do not start a corner. Always try to generate the course on a straight line ...

**Comment by tintong** [comment]
Thanks.
I moved the start beacon further down the field, but still close to the edge.
I had the same result but then it did start moving after 5 minutes.

Just not sure if that is how it's meant to be in terms of where to put the start beacon?

**Comment by 60erjonny** [comment]
That always comes to the field on ... Try it further ...
Are you sure that you also start CP and not the standard helper ...?

**Comment by tintong** [comment]
Ok.
I use the Esc menu and in there to start CP, not the key combination.

**Comment by 60erjonny** [comment]
Yes ist ok...This field has already annoyed me ... sorry

**Comment by tintong** [comment]
How come it's annoyed you?

**Comment by Tensuko** [comment]
Just don't start at corners, it was never a good Idea (unless you don't use headland)

**Comment by alex2ruote** [comment]
Just get out of the vehicle and the "object" will disappear.

**Comment by nlcoredump** [comment]
Seems to be a problem with the in-game object detection by giants.  I had the same problem, vehicles being blocked by object.  If you switch to a helper the giants engine seems to register the player as blocking object.  This was happening even without the courseplay-mod available.   Switching to different vehicle or exiting vehicle and walking away seems to help.  Probably difficult to fix in the courseplay mod as i think that is not the part causing the blockage.

**Comment by Tensuko** [comment]
I think that question got answered, I hope Giants do something about this in the feature so we don't have to tweak this.
