### ISSUE TITLE
Was muss ich machen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2520]
Hallo
Ich wollte Courseplay auf den Feld die Ballen sammeln lassen und dann kommt die Meldung: CP zu weit weg vom Feld obwohl er auf den Feld drauf ist
![CP](https://github.com/Courseplay/Courseplay_FS22/assets/47453761/98ef8e33-9bae-4052-8767-05f1b790657a)

**Comment by Tensuko** [comment]
Changelog lesen!
Bale collector/wrapper now works the same way, as the combine unloader in terms of markers.
The field position is now saved into the vehicle and will not be reset to the vehicle position, when started by the hud!
The position has to be set everytime in the ai menu!
This fixes problems with AD restarting and also has the advantage that you don't need another AD Target on the field to start the driver.
