### ISSUE TITLE
[BUG_SP] Gamecrash while creating Olivefield path

### ISSUE THREAD

**Issue by BastoriusvonderNordsee** [Courseplay/Courseplay_FS22#2521]
**Steps to reproduce**
I can try to create the path again, but the game will crash everytime.

**Actual behavior**
I have a quite big Olivefield. I want my worker to spray it, but when i click on the field for creating the path, the game freezes and will not move ever again. I have to stop the game in task manager.
On my Grapefield everything works fine.

**Expected behavior**
I expect CP to create the outer lines of the olive field.

**Screenshots**
![Screenshot (10)](https://github.com/Courseplay/Courseplay_FS22/assets/133128385/80cc1520-99ee-41a3-99f0-62ede0e71bd4)

**Courseplay version**
Version used: v.7.1.2.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11442798/log.txt)

**Map**
Nomansland

**Vehicles/ implements involved**
Mach 4R
Mod yes (Antonio Carraro Pack)

**Relevant script mods**
No mods relevant to recreate the problem.

**Comment by Tensuko** [comment]
One of those Issues will answer it.
https://github.com/Courseplay/Courseplay_FS22/issues?q=Reben

**Comment by BastoriusvonderNordsee** [comment]
Thank you, but no one has a real solution except #2504. And that did not work for me. I deletet the field, painted over it, plowed it new and paintet over it again. Then I placed new Olivetrees in straight lines but when i try to create the path the game still freezes and nothing comes after. After 30 minutes I closed the game in task manager.
Same warning: "Performing emergency garbage collection pass".

**Comment by BastoriusvonderNordsee** [comment]
@Tensuko - nach weiterem testen: Feldgröße hat keinen Einfluß auf ein erfolgreiches Kurserstellen. Habe das Feld kleiner gemacht und es wird trotz dessen kein Kurs erstellt.

**Comment by Tensuko** [comment]
Form des Feldes ist Rechteckig und möglichst flach ?

**Comment by BastoriusvonderNordsee** [comment]
> Form des Feldes ist Rechteckig und möglichst flach ?

Ist sehr flach, rechteckig, nun auch nur 5 Reihen breit und nicht sehr lang. Leider freezt das Spiel immernoch. Ich hab 64GB RAM, und keine schlechte CPU. Die Auslastung des PCs fährt auch nicht übertrieben hoch, denke das sich da was anderes einschleicht. Noch Ideen? 
Danke dir schonmal frühzeitig!

**Comment by Tensuko** [comment]
Hat nichts mit cpu oder ram zu tun, ist meistens die game engine.

**Comment by Tensuko** [comment]
Es ist ungewöhlich das er bei einem kleinen rebenfeld probleme macht.
Hast du die Reben korrekt im Raster gesetzt? Die schnappen ja so zusammen, das ist wichtig.
Sonst mach mal ein Screenshot von deinem Feld.
