### ISSUE TITLE
[BUG_SP] Balers with windrower doesnt wait at 1st waypoint to unfold

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#2523]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
create baling course and start worker.

**Actual behavior**
when i start worker on a mowed field with this mod : https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=234272&title=fs2022, worker will start driving tractor instead of waiting to unfold windrow and then start.

**Expected behavior**
wait to unfold windrower then start worker.

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Mod Issue.
