### ISSUE TITLE
[Feature] Server Disable

### ISSUE THREAD

**Issue by Veldian78** [Courseplay/Courseplay_FS22#2530]
**Ability To completely Hide/disable CP on a server for local**
Was thinking maybe the ability for people who do not like/use CP that are on servers that have CP, to be able to disable or completely hide CP and have it save so when they login again it don't show back up...
 
 I have looked into removing it from the server but I know some people like using it and I use it myself for when harvesting, to make things faster/easier for me from time to time... But have a few people that play on my server that don't like it and also one person that's disabled that has a hard time cause it won't stop popping up, have disabled the keybinds but it keeps popping up after I have disabled it and in the screen cause of the size of Hud she needs to see things

**Comment by Tensuko** [comment]
Will not happen.
The benefit is too low.
Info Panel can be turned off and also the mouse activation can be turned off.
But there won't be a player based hud on/off save.
