### ISSUE TITLE
[BUG_SP] freeze while creating job on grape field (similar as bug #2504)

### ISSUE THREAD

**Issue by dakoblas** [Courseplay/Courseplay_FS22#2535]
I have the game freeze up when trying to use courseplay on grape orchards on specific maps/fields.  I use courseplay with grapes in other maps/fields and it works fine.  In this case, I have had the problem consistently on haut-beyleron, field 38.
I set up a test game, a new save with only courseplay active (no other mods) to test, and was able to reproduce the issue.  

I read the issue bug # 2504  (https://github.com/Courseplay/Courseplay_FS22/issues/2504) (now closed), and attempted to use the workaround there, but it did not work.  I tried a number of different combinations of plowing, painting over and re-creating field with plow, re-placing vines in various positions on the field, and consistently had the issue.  I was unable to come up with a working work-around.

**Steps to reproduce**
1. Create a small grape orchard in field 38 (haut beyleron) (EDIT: with the vines facing in the north-south orientation)
2. Drive tractor onto grape field
3. open AI menu and try to create a courseplay job

**Actual behavior**
The game freezes prior to the field becoming highlighted, and has to be "end-tasked" in order to recover.  I have let it run while hung for several minutes on multiple attempts, but always end up closing via windows "end task" button.  

**Expected behavior**
I expected the grape field to be highlighted, allowing me to then open the course generator.  This is the usual behavior of any other field.

**Screenshots**

The grape orchard I created to test:

![fsScreen_2023_05_14_12_48_41](https://github.com/Courseplay/Courseplay_FS22/assets/1000637/7365480f-af42-4e81-a5e5-e80a7b7d8327)

Tractor parking on grape field:

![fsScreen_2023_05_14_12_49_22](https://github.com/Courseplay/Courseplay_FS22/assets/1000637/b2687816-9d22-469a-a4e2-08680275a111)

View from the map:

![fsScreen_2023_05_14_12_49_53](https://github.com/Courseplay/Courseplay_FS22/assets/1000637/cda604d5-423e-4f9b-b940-99dbd136da99)

AI helper screen where freeze happened:

![fsScreen_2023_05_14_12_49_58](https://github.com/Courseplay/Courseplay_FS22/assets/1000637/cbc58ffc-6d5d-4639-9e40-2d78fd7ae7c6)

**Courseplay version**
Version used:  

7.2.1.3

**Log**

https://gist.github.com/dakoblas/7e96937fb053ca211c00e553fa854e93

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11472835/log.txt)

**Map**

Haut-Beyleron, field 38

**Vehicles/ implements involved**
Which vehicle or implement?

Fendt 211 V Vario (grape tractor)
TMC Cancela TPN 140 (grape mulcher)

Mod yes/no ?

no

**Relevant script mods**

The only mod active is courseplay.

This is the savegame where I reproduce the issue.  This is a new save of haut-beyleron, farm-manager.  Courseplay is the only mod ever enabled on this savegame.  This saves was made just prior to creating the grapes shown in the screenshots.

[savegame4.zip](https://github.com/Courseplay/Courseplay_FS22/files/11472850/savegame4.zip)

**Comment by dakoblas** [comment]
I was doing some more testing and found something possibly interesting.  It seems that this freeze only occurs when the vines are placed North-South.  East-West facing vines actually seem to work ok...

This is the same size grape field as in the previous testing, only this time facing E/W instead of N/S as in the main bug report.

![fsScreen_2023_05_14_15_41_28](https://github.com/Courseplay/Courseplay_FS22/assets/1000637/95098592-04c4-446c-b668-9532bbc5083d)

Hopefully this is useful data.

**Comment by justinradomski** [comment]
Having the same issue here but with an olive orchard. I have two identically sized fields right next to each other. 28  rows wide each, but one is grapes and the other is olives. They are both north/south oriented. 

Interesting thing is that I can select the field for the grapes without any issues, but the moment I click on that olive field, the game locks up and I can't even end task on FS22 because task manager won't come up. Only way out is a full reboot.
