### ISSUE TITLE
[BUG_SP] John Deere Harvester just doing circules when starting the course

### ISSUE THREAD

**Issue by UberKiller** [Courseplay/Courseplay_FS22#254]
**Steps to reproduce**
Create a couse and press start job

**Actual behavior**
https://clips.twitch.tv/GlamorousSparklingRedpandaM4xHeh-2k1aHbTFEThJkcrj

**Courseplay version**
Version used: v7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7790772/log.txt)

**Map**
No Mans Land

**Vehicles/ implements involved**
Mod yes. John Deere S550 (2014)

**Relevant script mods**
Autodrive

**Comment by pvaiko** [comment]
Sorry, at this time we do not fix mod issues. Please reopen if you can reproduce this with a Giants vehicle.
