### ISSUE TITLE
[BUG_SP] Heap too powerful

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#2544]
**Steps to reproduce**
harvest a 55Ha Field and build a loooong heap of sugarbeets, then try to create a pickup job.

Heap in this case is ~680m long and contains 7.314.000l of sugarbeet

heap was fully recognised, until about 3.500.000l-4.500.000l of Sugarbeet were piled up

**Actual behavior**
Only a small part of the heap is found by CP, not the total stretch

**Expected behavior**
Heap is fully recognised

**Screenshots**
![Screenshot 2023-05-20 224208](https://github.com/Courseplay/Courseplay_FS22/assets/9157835/83d9859a-a4a0-40fa-a561-65014eac5374)
![Screenshot 2023-05-20 224213](https://github.com/Courseplay/Courseplay_FS22/assets/9157835/f677169e-a395-4936-b2d7-800c11788e96)

**Courseplay version**
Version used: 7.2.1.4

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11523190/log.txt)

**Map**
Monette Farms (Modhub)

**Vehicles/ implements involved**
Ropa Euro Maus, base game

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Autodrive and guidance steering used, heap created with guidance steering, perfectly straight

**Comment by schwiti6190** [comment]
@JDTiger Just to make sure, what happens when you just start the driver with  3.500.000l-4.500.000l of sugarbeet ?
The second image with the maker might just be unfortunate placement, as the margin of error is greater with those 4k and bigger maps.

**Comment by JDTiger** [comment]
sorry, should have attached something about that first.

I cut the heap at various positions, and found the max I could get it to recognize the heap at around fillLevel: 2879095.24

I never moved the startingpoint and the heap is perfectly straight east/west.

**Comment by schwiti6190** [comment]
@JDTiger You can try it again with the current main version. 
The max heap length should now be 5 times larger than before.
This will probably be the limit by design, as a bigger range might lead to problems with the detection, not sure though.

**Comment by JDTiger** [comment]
Works now, thank you very much
