### ISSUE TITLE
[Feature] transfer Waypoints in ingame Editor?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2547]
**What is the problem this feature/enhancement solves?**
Es wäre schön, im ingame kurseditor auch die transfer wegpunkte optisch zu sehen.
(Also das dritte "true" ->  - - true -)
Wenn ich ingame den kurs verändere, sehe ich nie, ob das transfer wegpunkte sind.
**Describe the solution you'd like**
Könnte man bei den gelben/roten/grünen dreiecken ev ein symbol dazu mit einblenden?
Und ev sogar per schaltfläche dazu- bzw. wegschalten?
**Describe alternatives you've considered**

**Additional context**

Lg
Andreas

**Comment by Tensuko** [comment]
Das sind die gleichen Wegpunkte, daher gibt da keine extra Wegpunkte, daher gibt es auch nichts zu verschieben.

**Comment by Tensuko** [comment]
Falsch kommuniziert.... wieder offen....

**Comment by Tensuko** [comment]
Sind doch schon lange sichtbar....
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/52f1e969-63ba-4839-8712-b3e26bb4dfb4)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/6f04797a-f370-4937-9fee-5150db2623cb)

Die Wegpunkte liegen übereinander.
Anders einfärben werden wir die aber nicht.

**Comment by andreasthu** [comment]
Ach sorry,
Ich meinte nicht ingame beim cp Fahren, sondern im ingame CP-Editor.
So das man einen wegpunkt als transitwegpunkt zuweisen oder entfernen kann. So änlich wie ich einen turnstart/end machen bzw löschen kann.
Lg
Andreas

**Comment by Tensuko** [comment]
Das wird es nicht geben.

**Comment by andreasthu** [comment]
Ok, schade, dann mach ichs weiterhin mut dem notepad+
