### ISSUE TITLE
[BUG_SP] Falciatrice

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#2562]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Quando genero un percorso noto che la falciatrice lascia dei pezzi indietro
**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.2.1.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Shire Farm
**Vehicles/ implements involved**
Which vehicle or implement? Falciatrice
Mod yes/no ? No

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Roby1164** [comment]
In che senso lascia i pezzi indietro ??? Riesci ad allegare qualche foto??
Poi dipende dal tipo di campo, se è piano o no, se intendi sulle svolte, allora puoi regolare la larghezza di lavoro, in modo da far sovrapporre di più le file...

**Comment by Trivelleitor** [comment]
No io intendo quando fa la retromarcia la falciatrice krone b m450 avendo le lame laterali che scendono più tardi rispetto a quella frontale, lascia qualche pezzo indietro quando riparte. Per le foto nessun problema adesso entro in partita e vedo se riesco ad allegartele.

**Comment by Trivelleitor** [comment]
![20230528182738_1](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/9b3f3ddc-fe73-4cb5-b3b2-3e5fea96575e)
![20230528183155_1](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/28106296-5438-4853-ab88-992bc1db172f)
![20230528183209_1](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/e34b4e27-9225-45f9-9bb8-12e17d328e43)

**Comment by Roby1164** [comment]
Ci dovrebbe essere un'impostazione che, permette di abbassare prima gli attrezzi, ma credo che quel problema è di difficile risoluzione, perchè la Krone ha quel difetto, di alzare/abbassare separatamente le lame, ma non è un bug del CP.

**Comment by Trivelleitor** [comment]
Quindi in questo caso di questo attrezzo non me ne faccio niente e farei meglio a venderlo, comprarmi gli attrezzi per trattore separati (quello frontale e quello posteriore) direttamente dalla sezione falciatrici? Se si con quello il problema, usando anche il CP lo risolvo?

**Comment by Roby1164** [comment]
No, non è che non te ne fai niente, ed anche con il trattore con i due attrezzi separati, ce sempre lo stesso problema.

**Comment by Tensuko** [comment]
@Roby1164 
Whats the problem here?

**Comment by Trivelleitor** [comment]
Ciao, scusa per il ritardo nelle risposte ma a causa di impegni non ho potuto continuare la discussione, come ultima cosa volevo chiederti come faccio a risolvere questo problema con l'utilizzo del cp se puoi darmi qualche soluzione? Grazie in anticipo e scusa per il ritardo

**Comment by Roby1164** [comment]
> @Roby1164 Whats the problem here?

The problem that the Chrone, raising the blades separately, leaves pieces of lawn at the end of the section, but the same problem is present if the tractor is used with the blades positioned one forward and one behind, I don't think it's a CP problem. I don't have the opportunity to test at this time.

**Comment by Tensuko** [comment]
This is done by Giants.
Also some ppl want it like that.
The only thing that can be done here is to change to lwoer the tools early and raise them late.
For mowing grass I also suggest to change the corners to round at least or smooth.
Yes you have less coverage but to be honest.... The amout on grass you harvest compared the the amount you leave behind and have a faster mowing and less stress with corners is worth the "loss".

@Roby1164 thanks for helping out :)

**Comment by Trivelleitor** [comment]
@Roby1164 puoi tradurmi in italiano
