### ISSUE TITLE
[Feature] Clear Unloading Area after Unloading Auger Wagon

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#2568]
**What is the problem this feature/enhancement solves?**
Multiple times, a similar situation as in the screenshot below. The Holmer Auger Wagon unloaded into the Trailer and then stops and waits to be called by one of the Combines, blocking the second Auger Wagon from unloading.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/29522870/f23ac30e-a1bc-46d3-a050-77a0e2de4e92)

**Describe the solution you'd like**
Since we have the two markers to be set for the unloader to work, my Idea was it would be nice if the Auger is empty and waiting to be called. Let it drive to the Target position (Ziel Position) and wait for a call from a Combine. In this way, a “Parking” Position can be established out of the way of all Other Participants in the Operation.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/29522870/e2fa47c8-50d0-4a9d-9534-fb8bb01b541c)

**Describe alternatives you've considered**
My current alternative approach would be to have only one Auger wagon on the field, severely limiting the Usability of the Auger wagon mode. The other alternative would be to use an AD setup for combine unloading, but I actually like the way it works, if it works.

**Comment by Tensuko** [comment]
@schwiti6190
Just like when the trailer gets full it drives to the target position, here we should drive to the target position after empty.
This could get complicated due to the "try look for another trailer to empty to".

**Comment by rohne83** [comment]
Tricky topic. Always forced to drive to this parking position could make it very annoying if you managed to have several unloading points at your field (sometimes this would really be recommended, especially on larger fields and high fruit yields to keep ways for overloader short). Ways to this parking spot might be extremely long then at least from one of the overloading points.

**Comment by Tensuko** [comment]
Thats true.
Doesn't make much sence for overloading.
Will find another solution.

**Comment by Tensuko** [comment]
@pvaiko can't we just call the function to make space and let it drive forward a bit more?
It should do it on the field already in idle state.

**Comment by AUZ001** [comment]
A more complex solution would maybe be to have the Unloader drive back into the proximity of the combine that is the fullest on the field - if possible this would be so beneficial ;)

**Comment by rohne83** [comment]
> > A more complex solution would maybe be to have the Unloader drive back into the proximity of the combine that is the fullest on the field
> 
>     * if possible this would be so beneficial ;)

Not necessarily. Coz that combine can still have plenty of free space, so that next rendezvous point might be in a completely different land. Rather keep it simple, make use of the current function and stay close to the overloading point.

**Comment by AUZ001** [comment]
"proximity" is the key word here, 
if there was a way to have the overloader check every 30 seconds and move into the fullest combine's "proximity" would be much more efficient and beneficial for everyone. just not sure if it can be done.

**Comment by Tensuko** [comment]
This wont happen at all.

**Comment by AUZ001** [comment]
yep I know, 

I just like mentioning it.

**Comment by pvaiko** [comment]
@PapaTim68 do you happen to have the log with debugs from this situation? Wondering if our blocking detection was triggered.

**Comment by PapaTim68** [comment]
Sadly, no I dont have any logs for that specific situation. Since the Dedicated Server is still in the harvest period I should be able to provide logs from Similar Situations, soon. In general I can say that the first Auger Wagon will typically wait there at that exact position for some time untilthe second one arrives and tries to unload getting stuck. The second one might then drive back and forth sometimes, but cant find a point to unload even so the would be long enough to unload a little bet further back.

Most of the time we have to babysit the situation to get the Unloading started properly.

Just as a side note I just realized, not sure if intentional but the second Truck and Trailer are not recognized until the first one is driven away by auto drive to unload into the silo.

I will try to get logs of the situation as soon as possible.

**Comment by Tensuko** [comment]
Somehow in my test, the 2nd Holmer was sent backwards instead the 1st one forward.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11636612/log.txt)

**Comment by pvaiko** [comment]
> 

That's exactly what it should be doing with the current implementation, but it was not mentioned in the original issue description, that's why I wanted to see the log.
