### ISSUE TITLE
[Feature] Include fruit avoidance in unloader ETE calc.

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#2569]
**What is the problem this feature/enhancement solves?**
Currently the ETE seems to be calculated from the distance to the rendevous point as the crow flies.

When harvesting a field using lands, there is fruit between the unloader and rendevous point, if the unloader sits at the starting point.
This results in the unloader taking longer then expected to reach the combine and causing the combine to stop and wait for the unloader.

EDIT: Additionally, maybe consider a lower speed (maybe 70% of max speed) for unloaders in the ETE calc as well, since not every tractor trailer combo will be able to travel at the maximum set speed at all times.
Its better to be early then late

**Describe the solution you'd like**
Run the pathfinder algorithm, when the rendevouspoint is established for the first time/ changes significantly.

**Describe alternatives you've considered**
Increase the margin of error for the combine fill level, to account for unforseen longer routes to the rendevous

**Additional context**
![Screenshot 2023-06-01 175357](https://github.com/Courseplay/Courseplay_FS22/assets/9157835/8c4cf1ff-28c7-4867-b08d-c7f4c56379de)

**Comment by Tensuko** [comment]
That just makes it more complicated then needed.
If the unloader is too late, it recalculates to a new, better rendevous point.
We could consider to lower the % target to 70% but I want to test arround with that 1st.

However if you 1st calculate a path to where (?) to check the time and then calculate the path to drive there, how many possible calculations would you want to do to figure out on wich way the unloader will be at the correct point at the correct timing.

It would need a constant pathchecking. Performance = 404 :)

**Comment by JDTiger** [comment]
what I thought of when I posted the Idea:


The combine estimates when it is at 80%. it comes out at waypoint 2622.

The unloader uses pathfinder to check its time to reach waypoint 2622.

now the combine constantly checks if waypoint 2622 is still valid for 80% filllevel
If it is, do nothing

If it estimates the 80% mark has shifted by more then 10 waypoints, use pathfinder to estimate unloader time at new waypoint.

continue until combine ETE at rendevous=Unloader ETE at rendevous
call unloader



That way you would limit the performance impact, since pathfinder only runs when something significantly changes.

**Comment by rohne83** [comment]
That's why I always try to locate the overloading points near the short edges of the field. The overloader won't have those fruit blocks in its way then, and the calculations are much more appropriate.
Basically the best % for the combine filllevel at rendezvous point will depend on many factors. Fill unit size of your combine and your overloader and even your unloaders, as well as the speed by which it increases (depending on fruit yield and working speed). When harvesting barley with 3 combines and 1 overloader I'd also welcome the rendezvous point at 70%, for most other fruits the current 80% is quite perfect, while for soybean I'd even go up to nearly 90%...

**Comment by Tensuko** [comment]
The 80% fill mark won't change that much as it is the combine almost constantly filling up.
It is only the path of the unloader that he won't reach fast enough or too early.
For both we have implemented recalculations that fits for the situation without haveing too much impact on performance for constat recalculations.

Won#t change anything here, unless like in another Issue, the rendevous point is at a wrong position (e.g. pipe in Fruit).
