### ISSUE TITLE
[BUG_SP] Windrower starting work much behind starting point

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2571]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Engage CP for windrower, with starting point set to first waypoint. For the screenshots it was handed over to work by AD, but think this also happened when engaging manually.

**Actual behavior**
CP worker starts swathing several dozen meters behind the first waypoint, thus leaving much hay unswathed.

**Expected behavior**
Windrower should start its work at the correct starting point.

**Screenshots**
![fsScreen_2023_06_01_11_18_37](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/dfe09ae0-dd8f-4f1a-9e57-72467039c1c5)
![fsScreen_2023_06_01_11_18_42](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/36106c09-af7d-4b71-ad13-7e2262d27383)

**Courseplay version**
Version used: 7.2.1.4

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11628066/log.txt)

**Map**
Landkreis Rostock

**Vehicles/ implements involved**
Deutz 7250 TTV with Kuhn GA 15131 windrower (both vanilla)

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Can't reproduce.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/3e121448-1167-43b7-a3dd-a85033cfc2a9)

![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/12bda1e4-1643-4897-bcf7-1a8cea364c3c)

Same for start with AutoDrive.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/5c5118f2-ba41-42a4-bb19-ab83df8663c9)

AD always starts CP at "last waypoint" - that is fixed and won't be changed as it finaly is working correct.
The last waypoint is always the 1st if the course is started for the first time, just as it is needed.
The only disadvatage is, if the driver was started once at any position and then is resent to the course, it may start at the wrong point if you want to start it at the 1st point.

Try to save the course and reload the course again.

**Comment by rohne83** [comment]
Interesting... Now with that in mind I cannot reproduce it either :D
