### ISSUE TITLE
Drescher - Rohr ausgefahren auf vorgewende [Question]

### ISSUE THREAD

**Issue by SirGarnet** [Courseplay/Courseplay_FS22#2575]
Wenn ich das Vorgewende mähen lassen, kommt der Drescher immer wieder auf die Idee das Rohr auszufahren. Jedoch bleibt er damit immer wieder im Baum hängen, wenn es sich um das erste Vorgewende handelt. Gibt es eine Möglichkeit dies zu unterbinden oder es evtl. als Feature hinzu zufügen damit dies auf dem 1. Vorgewende unterlassen wird und nur im Stehen abgeladen wird?

Vielleicht mache ich auch nur was falsch...

**Comment by Tensuko** [comment]
Hast du auch AD in Benutzung?

**Comment by rohne83** [comment]
CP klappt das Rohr ja gar nicht aus wenn kein Trailer in der Nähe ist, das passiert nur wenn AD in Benutzung für den Abfahrer.
Sehr wahrscheinlich dieses Verhalten hier: https://github.com/Stephan-S/FS22_AutoDrive/issues/572
Eventuell muss auch die CP-AD-Schnittstelle angepasst werden, aber grundsätzlich erstmal ein AD-Problem.
Aber wenn CP eh den Drescher steuert, kann man in den meisten Situationen lieber den CP-Abfahrer verwenden, dann hat man das Problem gar nicht erst.

**Comment by Tensuko** [comment]
Das ist nicht die Schnittstelle, da CP und AD in der hinsicht nicht zusammen arbeiten.
Aber es ist eben dieses einfache überschreiben der Funktion durch AD.
Da würde ich mir eher wünschen, dass diese nur aktiv ist wenn das CP Icon beim Drescher im AD Hut aktiv ist.

**Comment by SirGarnet** [comment]
> Hast du auch AD in Benutzung?

Ja habe ich, ich könnte zwar andersherum dreschen, jedoch hab ich dann immer das Rohr im Feld. Also liegt es am überschreiben von AD, das ist natürlich schade. Wie ich gelesen habe, kann dies wohl mit 100% Entlade-Level in AD überschrieben werden. jedoch braucht der Abfahrer dann schon eine Weile über große Felder.

Wäre schon echt gut, wenn CP sich im Vorgewende von AD nicht überschreiben lassen würde und selbständig merkt, dass es noch im ersten Vorgewende ist. Eine Tasche mäht und das Rohr raus hängt.

**Comment by Tensuko** [comment]
Das können wir nicht entscheiden ob CP "überbschrieben wird".
Da sollte man lieber sagen, AD lass die Finger von unserem Drescher.

Eine Tasche baut CP wenn du in den Fahrzeugeinstellungen das Rufen vom Abfahrer im ersten Vorgewende ausschaltest, ob AD dann trotzdem noch dran rum pfuscht weis ich nicht.

Fakt ist wir können nichts dagegen machen.
