### ISSUE TITLE
[BUG_SP] auger wagon print a error message when starting  task

### ISSUE THREAD

**Issue by magicmana** [Courseplay/Courseplay_FS22#2576]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
when i try to use a auger wagon on the map "The Romboz Road" on field 48
(https://www.kingmods.net/en/fs22/mods/19547/the-romboz-road)
the auger wagon don't  start and send an error message (auger wagon  too  far...)

**Screenshots**

![fsScreen_2023_06_03_10_20_34](https://github.com/Courseplay/Courseplay_FS22/assets/32802279/db3551fb-b77c-4202-b585-cf4cc77958b2)

**Courseplay version**
Version used:  7.2.1.4

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11642169/log.txt)

when  i  read logs  i see that coursplay scan the field 52 (the previous field where  the auger wagon was  used )
but now  the auger wagon work  on field 48

i tryed to create course at different position on  the  field 48 but each time courseplay scan field 52.

i tried to reset tractor and   auger wagon               : not working
i tred to reload the  game                                       : not working
i tried  to buy the same  tractor and auger wagon :   working

**Comment by Tensuko** [comment]
Read the ingame help for how to set up unloader for Combine.
