### ISSUE TITLE
[BUG_SP] IA doenst work with Precision Farming DLC

### ISSUE THREAD

**Issue by saLLadEXx7** [Courseplay/Courseplay_FS22#2584]
Hello everyone, I'm using the Courseplay mod with the Precision Farming DLC. When I try to set a course in the field and press the Ctrl + H shortcut, the worker simply stands still. I thought it was only happening with fertilizer, but I tested it with a plow as well, and the worker doesn't move.

Before posting this topic, I searched to see if I could find anything related, but I couldn't find anything, or maybe I searched incorrectly.

Could someone help me with this bug? I would like to use both mods in my single-player campaign.

Thank you in advance.

**Comment by Tensuko** [comment]
Pls use our template when post an Issue, there are too many informations missing.

**Comment by saLLadEXx7** [comment]
I found the problem. I was creating the template to share here, and when I checked the log, it showed a conflict with the "No Wage Payment" mod.

**Comment by Tensuko** [comment]
Alright :)
