### ISSUE TITLE
[BUG_SP] Piccin Advanced Auto - remove lateral offset for this implement.

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/Courseplay_FS22#2587]
**Steps to reproduce**
To test, simply set the working width to 6.6m and start the course. The lateral offset will be on auto, and it will begin shifted, which will affect your work and leave unworked stripes.

**Actual behavior**
Courseplay is automatically calculating the lateral offset for this implement, but it doesn't need to do that because it's similar to another model, Piccin Advanced Mod BT 11.
I believe you can incorporate this improvement in a future mod update.

**Expected behavior**
The CP should not calculate lateral offset for this implement.

**Courseplay version**
v7.2.1.4

**Vehicles/ implements involved**
Piccin Advanced Auto

Mod link:
https://www.farming-simulator.com/mod.php?lang=en&country=pt&mod_id=241822&title=fs2022

**Comment by Tensuko** [comment]
There is nothing we can remove.
The modder have to correct his mod.
This is no real plow but is set as one and the markers seems to be set wrong.
An example of a correct working "plow" with no offset is this one:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226965&title=fs2022

Mod Issue - Won't fix.
