### ISSUE TITLE
"Blows" the New Holland CR Intellisense harvester off course[BUG_SP]

### ISSUE THREAD

**Issue by vitalii2011** [Courseplay/Courseplay_FS22#2589]
**Actual behavior**
https://drive.google.com/file/d/1G6UA-Vy2xVBCxfuloQvqDtHK4Vh13F40/view?usp=sharing
- The assistant has no problem. With the same combine and equipment.
- With a vanilla harvester with the same equipment, there is no problem.

**Courseplay version**
Version used: 7.2.1.4

**Log**
https://gist.github.com/vitalii2011/048ccc18390781230ed076632452ffbc

**Map**
Elmcreek

**Vehicles/ implements involved**
- https://www.farming-simulator.com/mod.php?mod_id=252777
- FS22_Cressoni_Schneidwerk_14m
- https://www.farming-simulator.com/mod.php?mod_id=264237

**Relevant script mods**
no

**Comment by Tensuko** [comment]
If Vanilla works and this mod doesn't then it is a mod Issue!

**Comment by vitalii2011** [comment]
The standard assistant drives the combine smoothly, while the assistant from Courseplay - as in the video. But the problem with the harvester?

**Comment by Tensuko** [comment]
Exactly.
We cant keep change our mod because some single mods are not made correctly.
You can try use the vehicle config and give the header and combine an offset of 0.
Check our Wiki page on github for it.

**Comment by vitalii2011** [comment]
Understood. Thanks for clarifying.
