### ISSUE TITLE
[BUG_SP] Waypoints

### ISSUE THREAD

**Issue by L3eth** [Courseplay/Courseplay_FS22#2590]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
When i started to use it, i couldn't see the waypoints the AI is taking.

**Actual behavior**
Well i had reinstalled FS22, and then i updated courseplay, and when i started to use it, i couldn't see the waypoints the AI is taking, i checked every settings and i can't see where the problem is.

**Expected behavior**
Well i expected it to show the way points of the couse the AI is gonna take.

**Screenshots**
https://gyazo.com/715c093335c1af4eb7c0de5f17f081b7

**Courseplay version**
Version used: v7.2.1.4

**Map**
Played on: "Camsden"

**Comment by Tensuko** [comment]
For sure no CP bug:
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/15a9ce4c-21e5-4f91-bd2a-4a6f9f0ba226)
Where is your logfile?

**Comment by L3eth** [comment]
Ohh, sorry i just couldn't figure it out before but i got i now. :)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11779905/log.txt)

**Comment by Tensuko** [comment]
Can you try with only CP in your mods folder?

**Comment by Tensuko** [comment]
Closed due to inactivity.
