### ISSUE TITLE
[BUG_SP] Combine Header Stops Gathering Fruit Just Before Combine Stops

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#2592]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Harvest any field on Iowa Plains

**Actual behavior**
When the combine stops while harvesting and the tipper is called to offload, the combine's header stops but the combine is still in motion leaving strips of unharvested fruit all over the field. It does happen on smaller fields, but happens a lot on larger fields.

**Expected behavior**
The headers should continue moving until the combine stops, or ideally, just after the combine stops.

**Screenshots**
![Example](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/85f59f5d-5031-4b41-b81d-b419cf97479e)
![Example2](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/6449fd9f-6234-40a5-bde1-d5c77dcdbcd8)

**Courseplay version**
7.2.1.4

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11782104/log.txt)

**Map**
Iowa Pla

**Vehicles/ implements involved**
Which vehicle or implement? Claas Lexion 8900 with 1380 Combio Header
Mod yes/no ? Yes, but same results with vanilla equipment.

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
Never had this happen.
Your BetterContracts throws a Callstack, not sure if this will cause some game stuttering, but I don't have anotehr explanation.
Also we implemented a slow down for the last %.

**Comment by lcc1211** [comment]
I completely uninstalled the BetterContracts mod, but CP still stops the spinning of the header about a meter before the combine stops.

**Comment by Tensuko** [comment]
Did you test complete Vanilla as I said?

**Comment by Symbob** [comment]
I also find this happens, but mainly on fields with slopes.  If the combine is facing downhill it will leave these unharvested strips.  It doesn't do it when facing uphill.  I could be wrong, but I've always assumed it was because the combine creeps forward slightly when stopped to unload facing downhill.  When it starts harvesting again it has crept passed a small amount of crop.  The steeper the slope the more crop gets missed.  Perhaps a work around would be to have the combine reverse backwards a few metres after unloading, and before it starts harvesting again?

I'm also using the same harvester and header, but I've seen this happen with other harvesters too.

**Comment by Tensuko** [comment]
No driving backwards.
I will see when and why this happens and may adjust the slow down.

**Comment by dkfiremann** [comment]
What is your values for tool settings for raising and lowering ?

**Comment by Tensuko** [comment]
There are no values for raising and lowering.

**Comment by Tensuko** [comment]
22Ha Field with Tucano and 7.8m work width.
Never had the situation and my combine had to stop many times (map is big and only one unloader).
Field is also not flat at all.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/163ad24b-5e1b-40f4-bfaf-4a40dcbb8825)

**Comment by Tensuko** [comment]
Still not able to reproduce this.
No Idea whats going on on your side.
When you can record a video of this happening with a complete logfile with debug turned on, then reopen this Issue pls so we can have a closer look.
Might be some edge case.

**Comment by JDTiger** [comment]
Hey, I have the same problem, just investigated it some more:

It seems to me, that the combine drives on, before the header is spun up and lowered. this can be solved by waiting a seconds between starting the combine and header and driving forward.

Equiptment used: 
Claas 8900 https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=228187&title=fs2022
John deere HD50 header https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=267222&title=fs2022


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12445039/log.txt)
https://youtu.be/rP04z92faxQ

**Comment by Tensuko** [comment]
Must be a mod issue / mod conflict.
Look at whats happening, he starts driving while lowering the tool.
I don't have that happening.

**Comment by Symbob** [comment]
@Tensuko Could it be an issue with the Claas Lexion 8900?  The only common factor between all of us that are having the problem is that we are using the same harvester.  In your test you used a different harvester. I've been too busy at work over the past few months to play FS but as soon as I get a chance I'll do a bit more testing.

**Comment by lcc1211** [comment]
@Symbob @Tensuko I've had the issue with other mods. For instance, yesterday I was using John Deere HD45X 13.7 meter header with the John Deere S670 (2015) combine and it happened with it as well. I think it happened with a Rostelmash and the 9 meter header as well.

**Comment by lcc1211** [comment]
Using John Deere HD45X 13.7 meter header with the John Deere S670 (2015) at about the 31 minute mark.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12448681/log.txt)
I couldn't get the video because the recording was corrupted, but here is a screenshot.
![LeftBehind](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/09fdb3b3-f4d3-4beb-91ff-69978b62a369)

**Comment by Tensuko** [comment]
I need a video to see whats happening...
As I said in that one video the combine starts driving while still lowering.
I have this never happened to me.

**Comment by lcc1211** [comment]
So it seems the majority of the time this happens is when the co
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12458353/log.txt)
mbine nears the end of a row and CP calls the tipper. Go to the 7 minute mark of the video. https://youtu.be/2UTdEUQgWjU

**Comment by Tensuko** [comment]
Still weird.
Why he wouldn't keep collect fruit when the harvester is still on and the header down?

**Comment by lcc1211** [comment]
> Still weird. Why he wouldn't keep collect fruit when the harvester is still on and the header down?

There is a short time where the header stops spinning. Check it at the roughly 7:20 to 7:30 mark. It is a couple of seconds long.

**Comment by lcc1211** [comment]
It also happens when using the potato harvester. The most common denominator seems to be that when the harvester nears the end of the field and calls the vehicle offloading, a portion of the fruit can be missed. Could CP just not stop the header? Could that be a solution?
![PotatoLeftBehind](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/81718b1e-edae-4940-9a4e-1eb46f5e9ef8)

**Comment by Tensuko** [comment]
When I cant find the problem, we cant make a solution.

**Comment by Tensuko** [comment]
Also I would like you to try it with remove some of your script mods to make sure there is no influence from other mods.

**Comment by Tensuko** [comment]
Found this happening now for the very first time.
Thats very strange and hard to catch.
Reopen, but can't say when this will be solved.

**Comment by lcc1211** [comment]
I've been watching when this happens. Nearly (but not quite) 100% of the time it happens when the combine is nearing the end of a row and calls the tipper. usually the fill level isn't all that high. I've seen it as low as 35%. If you intentionally adding this as a function, perhaps the fix is to just remove that option.

**Comment by Tensuko** [comment]
I now had this happening in a blocked situation:
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/21b53365-8e82-42ec-911d-3ee729124075)

Maybe together with fuel save? Not sure...

**Comment by lcc1211** [comment]
Turning fuel save off? Maybe. I'll give it a try.

**Comment by Tensuko** [comment]
@lcc1211 if you know how to grab a Branch, you can try out this one:
https://github.com/Courseplay/Courseplay_FS22/pull/2822

**Comment by lcc1211** [comment]
@Tensuko I'm afraid that is not something I know how to do.

**Comment by Tensuko** [comment]
[FS22_Courseplay.zip](https://github.com/Courseplay/Courseplay_FS22/files/12776939/FS22_Courseplay.zip)
