### ISSUE TITLE
Auto-Attach Draper header

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2593]
**What is the problem this feature/enhancement solves?**
This feature Removes a level of tedium that could easily be removed 

**Describe the solution you'd like**
On Draper headers (the ones that are the header trailer themselves) the Combine should detach from the trailer point and drive around to the Harvesting point and attach... then start the course

**Describe alternatives you've considered**
If you can not code in a detach/attach function there could be a header on the field already and the combine could see the header and drive to it ready to be attached

**Comment by Tensuko** [comment]
Won't happen.
Way to complicated.
