### ISSUE TITLE
[BUG_SP] Unfold ITRunner trailes or trucks.

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/Courseplay_FS22#2594]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use truck with ITRunner version or trailer ITRunner for example for take the bales on the field.

**Actual behavior**
Click "Play" and directly CP unfold the tipper leaving the trailer on the ground.

**Expected behavior**
Click "Play" and directly CP run around in the field for take the bales.

**Screenshots**
I don't think it is necessary... you will only see one ITRunner unfolded.
![fsScreen_2023_06_22_13_24_27](https://github.com/Courseplay/Courseplay_FS22/assets/12070061/bdbee1ab-1525-46e9-ab5b-39ece82527e6)

**Courseplay version**
Version used: 7.2.1.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
https://farming-simulator.com/mod.php?&mod_id=245814

**Vehicles/ implements involved**
Which vehicle or implement?
https://farming-simulator.com/mod.php?&mod_id=263010
https://farming-simulator.com/mod.php?&mod_id=229759
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Yes, use Autodrive and EnhancedVehicle

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11833353/log.txt)

**Comment by Tensuko** [comment]
Mod Issue.
If those parts should not be unfolded by the AI, they need the XML Entry to disallow fold by AI.

**Comment by Vanquish081** [comment]
The AI no Unfold when you send to place in the map.

**Comment by Tensuko** [comment]
Becouse the send to have no fold commands.
