### ISSUE TITLE
How to view filters while defining custom field?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/Courseplay_FS22#2596]
A major difficulty I face when I create custom fields is the impossibility of viewing the current crop status filters.
For example, I often want to, for example, lime or herbicide parts of land that I have recently unified, where only certain stretches are left pending:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/11199752/475dd30c-8e2a-4575-b51d-ad107b6b6f6b)

But, when defining the custom field, I lose this view, which makes it very difficult to get the dimensions right:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/11199752/0c985bee-e987-4d5f-b1a2-c6fcdb7ffb55)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/11199752/92aca12c-8db6-457d-9d31-989652899d02)

Is there any way to facilitate this process?

**Comment by Tensuko** [comment]
But thats becouse the AI Map of the basegame doesn't have field informations.
That got nothing to do with CP.
And we will not change that basegame behaviour.
