### ISSUE TITLE
[BUG_SP] CP Helper no longer drives off during bale wrapping.

### ISSUE THREAD

**Issue by Farmer200** [Courseplay/Courseplay_FS22#2598]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

I have with the new version the problem that a course with hay bale wrapping the bale wrapper goes down the speed goes up but no longer starts. Also, the unhooking of the bale wrapper no longer works only resetting the tractor disconnects.

**Actual behavior**
A clear and concise description of what happen.
The helper no longer drives off. In the previous version it still works after I tried the last version. Delete course and regenerate does not change anything. Starting and saving without CP and then using CP again also does not.
**Expected behavior**

**Screenshots**
![2023-06-28 20_58_29-Farming Simulator 22](https://github.com/Courseplay/Courseplay_FS22/assets/138059424/b48cf760-f39c-46c3-aad5-dd899df3be50)
![2023-06-29 16_28_53-Farming Simulator 22 mit CP](https://github.com/Courseplay/Courseplay_FS22/assets/138059424/d58b9e1a-248c-4cb4-b428-86c4ba7dc0e6)

**Courseplay version**
Version used: [7.2.1.5]

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11906861/log.txt)

**Map**
Map played on.
FS22_Somewhere_in_Thuringia_III 

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes 

**Relevant script mods**
Mods like Autodrive or VCA and so on.  yes

**Comment by Tensuko** [comment]
Can't reproduce.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/6bb86106-4a8e-4b28-bc9c-adcc3b72809c)

**Comment by Mannie313** [comment]
Habe ich auch @Tensuko. Er bleibt wenn er den ballen nach hinten zum wickeln ablegt geht cp aus

**Comment by Farmer200** [comment]
Very strange exactly the combo I just tried on the Emlcreek only with CP without MODs and it does not work. The new Fendt Rotana goes. WAITING_FOR_LOWER: waiting for all tools to lower
Everywhere what must open goes.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11923033/log.txt)
![2023-06-30 22_26_02-Farming Simulator 22 gehen]
that go
(https://github.com/Courseplay/Courseplay_FS22/assets/138059424/4cca5718-1a75-4bc4-a120-3d7153442878)

**Comment by Twetch** [comment]
I have same issue in v7.2.1.5 only with round baler ,if you let it go from start,than it work until, there is sharp turn or you stop CP ,than it stop and can't be resumed from closest point.In v7.2.1.4 all works fine.

**Comment by Tensuko** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11929487/log.txt)

**Comment by Tensuko** [comment]
Should now work with 7.2.1.6
