### ISSUE TITLE
Reset info panel position[Question]

### ISSUE THREAD

**Issue by Bovrinox** [Courseplay/Courseplay_FS22#2599]
The info panel in my save has  disappeared, and i cant seem to get it back! I had moved its position, and have used other UI mods since, so I suspect it has been shoved off screen or something. Is there a way to reset its position to see if it comes back?
Thanks in advance!

**Comment by Tensuko** [comment]
In the folder: ..\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay
open the: courseplay.xml
Delete: <HudInfoTexts posX="0.713151" posY="0.851158"/>

That should reset it do default.

**Comment by Bovrinox** [comment]
Hmm. That hasn't fixed it, strangely. Time to start removing mods until it comes back haha!

Thanks for the fast response, hope you are enjoying your weekend.

**Comment by Tensuko** [comment]
Is the global setting still active then?
Show Info Panel.

**Comment by Bovrinox** [comment]
yeah I tried toggling it off and on again, but it didn't help. It is working on other saves, just not this particular one so I think it might be a mod conflict or something

**Comment by Bovrinox** [comment]
I think i found the conflict, eventually. I disabled all mods apart from courseplay and then slowly activated them ( I have a lot lol).
For some reason, the contractHUD mod has started conflicting with the courseplay info panel on this save, but only this one. It has never been a problem before, and isn't affecting any other save than this particular one of mine!
I don't even have the info panel in the same pace that the contract hud occupies, so I don't get it at all!
