### ISSUE TITLE
Thank you very much for the new version!!!

### ISSUE THREAD

**Issue by jeffersondarsy** [Courseplay/Courseplay_FS22#26]
Dear courseplay team, 

thanks a lot for the new version for the farming simulator 22. 

Now the game is complete and in addition with auto drive the fun can really start.

GUYS THANKS!!!!

**Comment by iljarogoff** [comment]
Yes, thanks a lot for CP. Will test it these days and give feedback. I hope the CP HUD will follow, it is way more intuitive than the ingame helper menu

**Comment by serVer1900** [comment]
Donation is out. Thank you very much for this fast an good job. Please ignore stupid and negative comments. 99% of people think your work is great. Together we will bring Courseplay for FS22 on the next level.
