### ISSUE TITLE
[Question] How to handle the Giants "Target position" marker in CP courses

### ISSUE THREAD

**Issue by santaranger** [Courseplay/Courseplay_FS22#260]
Where am I supposed to put the target field marker, when I already have a loaded course? It feels like I shouldn't have to put down the marker at all, the driver should just drive to the first/nearest wp and start. When the driver gets stuck and I fix them manually, I have to put down a new marker or else they will drive to the original marker again (?) when I hit "Start job".
Also when creating new coures without headland, it feels wrong to put the target marker inside the field.
Feels like I'm missing something. Like the keybind there used to be to start/stop the CP course and nothing else.

**Comment by Snigyman** [comment]
When you want continue on course, hit H where he stops working and he will drive from there.

**Comment by Tensuko** [comment]
The Giants pointer is used to:
A) 'Select the Field Area'
B) To make it possibleto send the driver there.
Also we have the Mini Hud, where you need to assign a key to.
Del is a good choice actually.

**Comment by santaranger** [comment]
Mini Hud looks good. Must be a newer feature. "H" does seems to work as well.
Thanks for the hints.

**Comment by santaranger** [comment]
Hmmm, "H" key does seem to hire a usual worker, though, not CP worker.

**Comment by Snigyman** [comment]
> Hmmm, "H" key does seem to hire a usual worker, though, not CP worker.

Can be different in the new version, but for me, it works perfectly, when i want CP goes from nearest point.
But, sometimes happend, when i hit H normal worker will assaign, cause i must select CP worker and then works good.

Sry for my english, im not good as can be. :)
