### ISSUE TITLE
[BUG_SP] Forstmulcher nur "Silo verdichten"

### ISSUE THREAD

**Issue by Koppi1994** [Courseplay/Courseplay_FS22#2600]
Hallo zusammen,

die Forstmulcher (egal ob Mod oder Vanilla) werden als Gerät zur Siloverdichtung erkannt. Somit ist ein Fräsen eines abgeernteten Waldstücks mit CP (V 7.1.2.5) nicht möglich.

Anbei die Log.txt des Testspielstands auf der Silverrun Forrest, ohne Mods außer CP.

Vielleicht kann mir auch jemand sagen, wie man die Geräte einer anderen Kategorie (z.B. Grubber) zuweist.

Gruß Koppi

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11929366/log.txt)

**Comment by Tensuko** [comment]
Forstmulcher sind auch nicht unterstützt.
Für Geräte umbauen bitte in Discords oder so fragen.
