### ISSUE TITLE
[BUG_SP] Courseplay worker, being blocked by object on turns

### ISSUE THREAD

**Issue by ctroyer98** [Courseplay/Courseplay_FS22#2602]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
A simple course with dry fertilizer application, or any tillage tool

**Actual behavior**
When I start a course the course starts fine, until the worker comes to a corner and then proceeds to say "blocked by an object." This happens on multiple different maps, with multiple different mods. Both pull behind and non pull behind.

**Expected behavior**

**Screenshots**
![fsScreen_2023_07_01_12_12_34](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/4019a5bd-4046-4983-a80c-e18cf2319d5d)![fsScreen_2023_07_03_11_55_09](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/232e11bd-74e1-40c4-93a8-2a6586710547)

![fsScreen_2023_07_03_11_54_48](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/1b12b105-3b90-40c7-a5e1-10d94a583c39)

**Courseplay version**
Version used: 7.2.1.6 (Have also tried the 2 previous versions)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11938555/log.txt)

**Map**
Map played on.
UMVR (have also had it happen on West by Wisconsin, Ashton corners)

**Vehicles/ implements involved**
Which vehicle or implement?
Multiple, Mobility 1000, 
Mod yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
No other script mods

**Comment by Tensuko** [comment]
Pretty sure the mod got the old triangle colission.
Hit F5 ingame and post a screenshot.

**Comment by ctroyer98** [comment]
> Pretty sure the mod got the old triangle colission. Hit F5 ingame and post a screenshot.

![fsScreen_2023_07_03_13_13_27](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/026a59d1-51f6-4d2e-9399-898cbdbaf2b8)
![fsScreen_2023_07_03_13_13_29](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/0ae87987-302a-4a20-b0b2-d116f57af189)
![fsScreen_2023_07_03_13_13_30](https://github.com/Courseplay/Courseplay_FS22/assets/138510711/13878ab7-f4b5-43fa-8c65-383615ad44ec)

**Comment by Tensuko** [comment]
Jep, its the old colli -> Mod Issue.
![250626362-026a59d1-51f6-4d2e-9399-898cbdbaf2b8](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/e983d16d-e900-4cd9-b2be-9396ccb34832)

**Comment by RubberDuck01** [comment]
Sorry to post to old issue, but how to fix this? Any info is much appreciated!
