### ISSUE TITLE
[BUG_SP] Feldkurs um Insel nur für das Vorgewende

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/Courseplay_FS22#2603]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Feldkurs Berechnen lassen um eine Feldinsel herum (Kreis)

**Actual behavior**
Wenn ich einen Feldkurs berechnen lasse, dann wird zwar grundsätzlich nur für das Vorgewende ein Feldkurs um die Insel berechnet. Die Feldbahnen gehen durch die Insel hindurch

**Expected behavior**
Berechnung der Kurse um die Insel auch für die Feldbahnen

**Screenshots**
![Farming Simulator 22_2023 07 04-10 38](https://github.com/Courseplay/Courseplay_FS22/assets/16411797/964e6c9e-a52f-4e94-9a0d-fdd274a14b2b)

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Karpatenlandschaft, gilt aber für alle Maps

**Vehicles/ implements involved**
Drescher, Pflüge, Grubber, Tiefenlockerer, gilt für alle Geräte

Mod yes/no ?
Ja und nein
**Relevant script mods**
Autodrive,

**Comment by pvaiko** [comment]
Ist das nicht ein Duplikat von #812? Hast leider kein Log zugefügt, mit Debug wäre der Fall klar.

**Comment by pvaiko** [comment]
Duplicate of #812
