### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2606]
**What is the problem this feature/enhancement solves?**
The amount of headland runs required is not always obvious or known for an implement

**Describe the solution you'd like**
Suggest the number of headland rows the field should have based on the implement & vehicle combined length if this is possible? This is maybe something that can't be done, but I think it would be a nice touch to offer this if possible. Then the correct headland can be used for pulling into a row without obstruction.

Forgot to add title - Suggest number of headland rows required for length of vehicle + implement being used

**Comment by Tensuko** [comment]
Idea already exists #17

The working width must be wider then the lenght.
E.g. 6m work with and 20m vehicle length should be arround 4 headlands.

**Comment by coatsy35** [comment]
Hadn't see that idea. Would be good if it could ever happen as a user has no idea what the length is, where as the game does, so a suggestion based on length would be excellent.
