### ISSUE TITLE
Have Combine auto connect to draper header

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2607]
**What is the problem this feature/enhancement solves?**

When Combine goes to a field with a draper header its stuck until you mannualy have to connect it to the harvesting side 

**Describe the solution you'd like**

For the combine to automaticly connect to the harvesting side

**Describe alternatives you've considered**

have it just drive to the combine side ready to be attached

**Additional context**

**Comment by Tensuko** [comment]
That won't happen. To complicated.
