### ISSUE TITLE
[Question] Combine Unloading Issue Topic on AD Github

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2608]
@Tensuko @pvaiko 

Have you seen this topic on AD? Having issues with combine unloading - where AD just stops on route to the combine on large fields, they are asking about if CP can communicate the unloading pocket behaviour to AD

https://github.com/Stephan-S/FS22_AutoDrive/issues/929

**Comment by Tensuko** [comment]
Answered in the Issue.
