### ISSUE TITLE
[BUG_SP] Shovel width calculation causes call stack

### ISSUE THREAD

**Issue by vSoRx** [Courseplay/Courseplay_FS22#261]
**Steps to reproduce**
Versuche das spiel zu starten

**Actual behavior**
Ich lade den bestehenden Spielstand mit Courseplay und bekomme bei jedem gerät einen LUA Fehlercode und muss Geräte verkaufen, damit der LUA nicht auftaucht. Bei einem neuen spielt stand passiert das nicht. Erst war es der Lemken 9/500 dann das John Deere Gewicht EZ1700 und jetzt ist es jedes andere Gewicht.

**Courseplay version**
Version used: 7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7793618/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Mod yes

**Relevant script mods**
Mods like Autodrive

**Comment by pvaiko** [comment]
2021-12-30 16:34 Error: Running LUA method 'update'.
C:/Users/Marv/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/WorkWidthUtil.lua:190: attempt to index a nil value

**Comment by rgoe** [comment]
Seems to be the same issue I'd encountered - #262 - he also has the frontloader tool loaded giving me this error.

**Comment by vSoRx** [comment]
No, I didn't use a front loader or something similar that the LUA error came before I was in the game with a charge level of 85% and it always showed me the LUA after trying to load the lemken 9/500 and then he started my weights Report to.

**Comment by vSoRx** [comment]
here I have a new log and tried to reproduce the error

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7793716/log.txt)

**Comment by rgoe** [comment]
Line 567 of your first log reads (and still present in your second log)
"2021-12-30 16:34 data/vehicles/albutt/frontloaderRoundBaleFork/frontloaderRoundBaleFork.i3d (6.47 ms)"
and thats exactly the tool giving me this error. Try selling it and reload to see if the error still persists.

**Comment by vSoRx** [comment]
okey sold the front loader attachment and now it works. thanks for the quick reply ^^

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
