### ISSUE TITLE
[BUG_SP] Frontloader attachment gives "WorkWidthUtil.lua:190: attempt to index a nil value"

### ISSUE THREAD

**Issue by rgoe** [Courseplay/Courseplay_FS22#262]
Hi there,
having attached the Albutt frontloader roundbalefork (found in frontloader tools) to a frontloader when loading a savegame, loading stops and FS gives an error:
"C:/Users/User1/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/WorkWidthUtil.lua:190: attempt to index a nil value"
(Also it might crash when leaving the game via menu with the tool attached leaving same error message in the log  + LUA callstack (2nd attached logfile).)

My "assumption" is:
The roundbalefork is of type "dynamicMountAttacherShovel", therefore it has the "shovel"-specialization inherited from the type - but there is no <shovel> definition inside the implements xml-file meaning there is also no workingWidth definition. Because of the "shovel"-specialization CP is searching for the width definition but cannot find it, therefore running in an error.

**Steps to reproduce**
Load savegame with mentioned tool attached to frontloader or alternatively buy tools ingame and attach, then leave game via menu option.

**Actual behavior**
FS throwing an error, loading stops:
"C:/Users/User1/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/WorkWidthUtil.lua:190: attempt to index a nil value"

**Expected behavior**
No error/crash.

**Courseplay version**
7.0.0.9 from release section

**Log**
1st log - CP activated on an existing savegame.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7793660/log.txt)

2nd log - New savegame, CP debug channels turned on, tools bought & attached, game exited via menu => error+LUA callstack, Alt F4 to quit.
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/7793661/log2.txt)

**Map**
Elmcreekt

**Vehicles/ implements involved**
Massey Ferguson 3670
Quicke Q7M Frontloader
Albutt Roundbalefork 
(All vanilla from game, no mods besides CP loaded)

**Relevant script mods**
CP

**Comment by Tensuko** [comment]
Duplicate
