### ISSUE TITLE
[BUG_SP] Silo leveling going outside the corridor silo

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#2621]
**Steps to reproduce**
Place a corridor Silo and than setup a course to level it. CP Worker push too long outside it.

**Actual behavior**
Sillage going outside silo. This was not the case with 7.2.0.5 version.

**Expected behavior**
Sillage not going outside a corridor silo

**Screenshots**
![f_steamlibrary_steamapps_common_farming_simulator_22_x64_farmingsimulator2022game exe_Screenshot_2023 07 12_-_22 07 56 39](https://github.com/Courseplay/Courseplay_FS22/assets/70093234/9237c82e-bbcd-4764-9180-2aa45cd4dfa5)

**Courseplay version**
7.2.1.6

**Log**
[Log_SillageOutsideSilo.txt](https://github.com/Courseplay/Courseplay_FS22/files/12038063/Log_SillageOutsideSilo.txt)

**Map**
Vanilla maps

**Comment by Tensuko** [comment]
Vanilla Silo but what shield is this?

Beside that.... I rly have to ask this.... why would anyone want to push the chaff in a drive through silo to the end?
I mean sure we have a look but isn't that counter intuitive for a drive through silo?

**Comment by Lactic68** [comment]
Hi,
The shield is from this [mod](https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=257556&title=fs2022). The tractor is used for compaction and the user probably wanted to be sure that the tractor will not be stucked when driving through.

**Comment by Tensuko** [comment]
Yea but a shield is to push it to the back and create a heap.... that is the opposide of "make sure the tractor will not be stucked" :)

**Comment by dylboy92** [comment]
hi i get this to with base game tools. i get you made this for a wedge silo but would be great if it worked for open bunkers to.

**Comment by Tensuko** [comment]
We might adress this in the next FS.
For FS22 we will not change this, sry.

My suggestion is to use shields only for U Shaped Bunkers.
