### ISSUE TITLE
Früher Wenden/Aussetzen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2624]
Hallo
Was muss ich einstellen damit der Fahrer nicht so weit ins Vorgewende fährt sondern früher umdreht. Ich habe drei Vorgewende um das Feld herum eingestellt und er fährt bis zur ersten am Knick ran und bleibt dann mit den Maschinen an den Bäumen hängen
![Pressen](https://github.com/Courseplay/Courseplay_FS22/assets/47453761/84233bf9-f540-4516-a9f2-8532fd06dfd6)

**Comment by Tensuko** [comment]
Ich sehe nur 2 Vorgewende.
Und das setting dafür ist anheben früh/spät und absenken früh/spät.

**Comment by Tensuko** [comment]
Ach und darf ich noch etwas anmerken....
Deine Kombination macht gar keinen Sinn, außer du hast am BigX rum gepfuscht.
Der kann auch Schwadablage dann fällt das andere komische Gebilde komplett weg.
