### ISSUE TITLE
[BUG_SP] Fahrer wendet am Ende des Kurses um 180°

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#263]
**Steps to reproduce**
Hab das bei mehreren Kursen beobachtet. Gemeinsamkeiten die mir aufgefallen sind: Mit 7.0.0.8 generierte Kurse mit Vorgewende, Start auf Bahnen. Vorgewende 2x clockwise. Verschiedene Geräte, verschiedene Breiten, verschiedene Felder. 

**Actual behavior**
Fahrer wendet am Kursende um 180°, arbeitet dann noch mal ein paar Meter und bleibt dann gegen die Fahrtrichtung stehen

**Expected behavior**
Am Ende einfach stehen bleiben, ohne zu wenden

**Screenshots**
Generierter Kurs war "clockwise" und so ist er auch gefahren. 
![InkedfsScreen_2021_12_30_14_06_06](https://user-images.githubusercontent.com/96873819/147766184-e1dd4bee-c5ea-464a-a3e5-d3eb29f1ce93.jpg)

**Courseplay version**
Version used: 7.0.0.8

**Log**
Please attach a log with all debug channels active.
For help with the debug channels, please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7793667/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Mod yes/no ?
Verschiedene Standard-Traktoren und Geräte, z.B. MF 8S.305 und Dalbo MaxiCut 600, siehe Log. 

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Verschiedene Mods und AD installiert, jedoch nicht aktiv beteiligt.

Ist mein erster Bug Report. Das mit den Debug Channels verstehe ich (noch) nicht.  Falls das kein Bug, sondern ein Feature ist, verstehe ich es ebenfalls nicht. Gruß throsten.

**Comment by Tensuko** [comment]
@pvaiko Wenn man einen Kurs mit start auf Feldreihen generiert, wird der Startpunkt um 90° gedreht und am Ende entsteht dieser turn.

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
