### ISSUE TITLE
Callstack when starting equipment

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#2637]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

Start elmcreak with only CoursePlay in modfolder
Create course with green combine and start from first waypoint.
Create course with seeding tractor and start from first waypoint.
This creates the call stack

**Actual behavior**
A clear and concise description of what happen.
Creates callstack

**Expected behavior**
No callstack

**Screenshots**

![Farming Simulator 22 Screenshot 2023 07 19 - 19 28 37 87](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/9d4cf5f5-6d56-4a2c-97c7-2490c0b33510)

![Farming Simulator 22 Screenshot 2023 07 19 - 19 29 16 10](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/f8d3a216-6128-4fd8-906f-b33d26d70d7b)

![Farming Simulator 22 Screenshot 2023 07 19 - 19 29 28 37](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/006918f2-6683-4b4f-b311-d412a1ea1242)

**Courseplay version
**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
elmcreak

**Vehicles/ implements involved**
Starting equipment in elmcreak map
Which vehicle or implement?
Mod yes/no ?
No mods except Courseplay

**Relevant script mods**
Mods like Autodrive or VCA and so on.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12098447/log.txt)

**Comment by Tensuko** [comment]
Should be fixed now.
