### ISSUE TITLE
[BUG_SP] - New Header Attach Function causes problem with towed combine

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#2638]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

Thanks you very much for the great work on this script. :-)

**Steps to reproduce**
Issue apears on Erlengrat map without any other mods and on Court Farms map with several other mods. I tried different tractors too.

**Actual behavior**
1# Option "Automatic header attach" OFF:
When starting Courseplay an error message "Schneidwerk ankuppeln deaktiviert" is shown and CP quits.

2# Option "Automatic header attach" ON:
CP unmounts the combine from the tractor.

**Expected behavior**
Combine works as normal tool as in CP version 7.2.1.6.

**Screenshots**
1#
![Farming Simulator 22 Screenshot 2023 07 19 - 21 53 11 89](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/38ea74fa-5db7-4402-9acc-b1ff468890b2)
![Farming Simulator 22 Screenshot 2023 07 19 - 21 53 31 97](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/34797007-0ccc-4926-bcd9-3aeab8088148)
2#
![Farming Simulator 22 Screenshot 2023 07 19 - 21 53 40 44](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/b6ea1ba5-9bfa-4573-ba2a-09d1c25b235d)
![Farming Simulator 22 Screenshot 2023 07 19 - 21 54 11 99](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/31acab63-39a5-419f-8fd2-ae006142315d)

**Courseplay version**
Version used: 7.2.1.,8

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12099795/log.txt)

**Map**
Erlengrat & Court Farms

**Vehicles/ implements involved**
Which vehicle or implement? DeutzFahr M66T - converted from LS19
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Issue appears with other mods on and off.

**Comment by Tensuko** [comment]
Wich Mod is this?

**Comment by Ulanawius** [comment]
Base game tractor. The combine I have converted from LS19 M66T (Modhub). No Errors / Only some warnings. I have already played several hours without any problems.

**Comment by Horschde** [comment]
Hello, i also have these problems, but in a different constellation. I have a potato harvesting mission and also a tractor from the base game and the towed harvester Ropa Keiler. When starting CP, the same message appears as mentioned above: "Schneidwerk ankuppeln deaktiviert" and does not start with the course. If I activate the function, the harvester is detached and CP is terminated.
![Farming Simulator 22 Screenshot 2023 07 20 - 18 58 57 53](https://github.com/Courseplay/Courseplay_FS22/assets/86984457/3a902915-7677-4aaa-8b4e-d2ce4bebdbfa)

**Comment by Tensuko** [comment]
Update soon.
