### ISSUE TITLE
have courseplay run through a folder of courses and do that folder on autopilot[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2642]
**What is the problem this feature/enhancement solves?**

the problem is loading courses each time the machine completes one we manually have to load another

**Describe the solution you'd like**

a different type of course folder titled Auto Folder or something to that extent then make and save courses to that folder and it will run through them based on a frequency set by the user

**Describe alternatives you've considered**

generating multiple courses and having them in a playlist and it runs through them once 

**Additional context**

**Comment by Tensuko** [comment]
This will not happen, sry!
Mentioned many times already...

**Comment by FrozenStorm1029** [comment]
will there be anything like it?

**Comment by Tensuko** [comment]
No...

**Comment by FrozenStorm1029** [comment]
are there any mods like that?

**Comment by Tensuko** [comment]
No.... There cant be and wont be.....
