### ISSUE TITLE
[Feature]Good afternoon, is it possible to create a course direction in the dump in the coursplay program. since there are non-rotating plows of the type of PSKOV or PLN, so that the tractors would drive in a corral clockwise. If it is implemented it will be very fine. Thank you in advance.

### ISSUE THREAD

**Issue by nik163** [Courseplay/Courseplay_FS22#2644]
**What is the problem this feature/enhancement solves?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
Could you pls use the template and not the headline for your description and descripte it more precise on what you would like to have as I have no Idea.....
Make new Issue pls.
