### ISSUE TITLE
Falsches Feld

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2648]
Hallo
Folgendes Problem
Der Abfahrer soll mit den Ballensammler zu Feld 47 fahren, fährt aber immer wieder zu Feld 40 hin.
Das Problem ist bei den anderen Felder da gleiche
![Falsches Feld](https://github.com/Courseplay/Courseplay_FS22/assets/47453761/0db3c869-405a-406e-98cc-f23b7f6a702b)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12131704/log.txt)

**Comment by Tensuko** [comment]
Feld über das Ziel Icon im HUD gewählt?

**Comment by Hendirk** [comment]
Feld wurde über Autodrivekurse ausgewählt 
Was ist Icon und HUD

**Comment by Tensuko** [comment]
Bitte mal die Anleitung zu CP ingame lesen.
AD Ziel hat nichts mit CP zu tun.

**Comment by Hendirk** [comment]
ok ich schau dort mal

**Comment by Tensuko** [comment]
Closed due to inactivity.
