### ISSUE TITLE
Plowing

### ISSUE THREAD

**Issue by nik163** [Courseplay/Courseplay_FS22#2649]
I would like to see such a method of movement as vsval in the course generator. since non-revolving plows are used. In the generator of courses there is a method of movement in a vsval / waddling, it is not suitable for plowing with non-revolving plows.

**Comment by Tensuko** [comment]
I have no Idea what you are talking about...
Why not descripe your problem, your Idea, how it should work.
Vsval what is that? What do you want to waddle??

**Comment by Tensuko** [comment]
Closed due to inactivity.
