### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by siggiiii** [Courseplay/Courseplay_FS22#2651]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
Beim laden in die Karte verschwindet beim betreten der Karte im Menü jegliche Feldnummern, Positionen etc. Das Problem tritt jedoch nicht bei allen Karten auf, liegt ein Fehler in der kompabilität vor oder ein Fehler mit der Mod?
**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 
neuste Version
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Landersum
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Ohne logfile kann ich dazu nichts sagen.

**Comment by Tensuko** [comment]
Closed due to inactivity.
