### ISSUE TITLE
[Feature]Priorisierung der Anbaugeräte

### ISSUE THREAD

**Issue by SAM24986** [Courseplay/Courseplay_FS22#2652]
Hallo.
Ich benutze zur Saateinbringung unten auf den Bildern zu sehendes Gespann. Das funktioniert mit CP soweit auch richtig gut, bis es zur letzten Runde des Vorgewendes kommt. In der Regel lasse ich beim Säen 4 Bahnen Vorgewende machen, um der Maschine den nötigen Raum zum Wenden zu geben. Bei Feldern mit riesigen Grasstreifen rund herum ist das nicht nötig, auf der Ostseeküste z.B gibt es diese aber nicht.
Bei der Vorwärtsfahrt zur Feldecke hin wird die Workarea des vorderen Anbaugeräts genutzt, bei der Rückwärtsfahrt nach der Wende in die Ecke allerdings auch. 
Durch die Kollision des hinteren Anbaugerätes wird daher eine Blockiermeldung ausgelöst, man muss den Helfer entlassen und wieder einstellen damit er dann am nahesten Punkt wieder anfängt.

Meine Frage ist ob man ob man die Wende bei bebauten Feldumrandungen anders gestalten könnte, wie ich das unten auf dem Bild mal illustriert habe.
screenshots
![fsScreen_2023_05_29_12_19_02](https://github.com/Courseplay/Courseplay_FS22/assets/59346694/23af1b63-908b-4470-a119-3899113a551d)
![fsScreen_2023_07_16_17_12_56](https://github.com/Courseplay/Courseplay_FS22/assets/59346694/0346c354-961d-478c-afa1-90d424aedfe0)
![fsScreen_2023_07_16_17_13_17](https://github.com/Courseplay/Courseplay_FS22/assets/59346694/0e7c0ca4-1cd0-45fb-81d3-81277d9b8064)
![Wende](https://github.com/Courseplay/Courseplay_FS22/assets/59346694/75159e3e-62c1-481c-b0c6-ed2b50a2405e)

**Comment by Tensuko** [comment]
Den turn werden wir dafür nicht umbauen.
Was geplant ist, vorgewende zu mischen das heist z.B. genau für sowas das erste vorgewende rund zu machen und die danach eckig.
Wenn kein Platz dann kein Platz.

**Comment by SAM24986** [comment]
Aber er muss nach der Wende bei der Rückwärtsfahrt das Feld ja nicht mehr verlassen da er bei der Anfahrt den Bereich mit dem vorderen Gerät bereits bearbeitet hat. Würde ja auch reichen dass er nach der Wende dann das vordere Gerät nicht berücksichtigt wird sondern nur das hintere

**Comment by Tensuko** [comment]
So funktioniert das aber nicht.

**Comment by SAM24986** [comment]
Ah ok, war auch nur so ne Idee, weil ich dachte vllt einfacher als den turn umzuschreiben.
Aber alles gut.
