### ISSUE TITLE
[BUG_SP] Unloaders ignoring some of the combines randomly

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2655]
**Steps to reproduce**
Situation: 4 combines, 2 auger wagons on quite large field (75ha)

**Actual behavior**
First the combo worked quite well, but on later rows the unloaders started to ignore at least one of the combines randomly (means did not drive to it to rendezvous at 80% fill level) and only unloaded this one again once it was completely full. In log we have this message quite often when this happens: Pipe may be in fruit at waypoint xy, we have no reliable information as multitool active, rejecting rendezvous.
This message comes from the fix for #2373, so maybe it results from this fix. But not sure, so I rather created new issue. Interestingly this new issue only happens from time to time, sometimes it works correctly and all combines get unloaded, sometimes not. Kind of unpredictable which combine and which unloader refuses the call, seems to be always varying. Haven't observed this issue before when I was using just two combines and one overloader.
Interestingly the above log message was even thrown by the leading combine which cannot have any fruit on pipe side that moment and also not in the next row (as depicted in screenshot, leading combine was still several hundred meters away from row end, had another row to go in the same land, but still threw the log message and was ignored by the second overloader). Wondering why this piece of code was entered at all, as we are far from any row turn.

**Expected behavior**
As long as any unloader is availabe, they should drive to the combines to rendezvous at 80%.

**Screenshots**
![fsScreen_2023_07_24_21_04_29](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/e0b94f49-6310-42fc-a8bd-efc5b52e3edd)
Here the Quadtrac successfully unloaded the 3rd combine (vehicle debug activated for this one until overloading started) of the convoy, got full and drove off to the unloaders at field edge. The Fendt 936, completely empty, standing nearby ignored the first (and also the second combine as you can derive from filllevels in simpleInspector window). Vehicle debug activated for the first combine during this situation, right when I made the screenshot.

**Courseplay version**
Version used: 7.2.1.8

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12149373/log.txt)

**Map**
Landkreis Rostock

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
N/A

**Comment by pvaiko** [comment]
With multitool, we calculate at which waypoint will we be at 80% and if at that moment, the pipe would be in fruit at that waypoint, we reject the rendezvous (as we don't know if there will be fruit there by the time we get there, because of multitool, as the message is also saying)

Does that explain what you see?

**Comment by rohne83** [comment]
No, because as said this even happens for the leading combine. That's the one in screenshot, even right that moment there's no fruit on pipe side along its way for the next ~2 rows (each with a length of nearly 1km).
And also for the 3 other combines (with distances of 60-100m most of the time) sometimes it works correctly, and sometimes not.
Can upload the savegame if needed to reproduce.

**Comment by pvaiko** [comment]
Upload it.

**Comment by rohne83** [comment]
I've thrown out all non-Modhub mods (except for the map of course), and replaced my private Annaburger auger wagons by HAWE ULW 3500TR from modhub with about same capacity. Behaviour is still the same: 3rd combine in the convoy reaches 80% and is successfully unloaded by the Quadtrac, while all others get ignored by Fendt as well as by Quadtrac. They only get unloaded once completely filled. Interestingly after turn into next row all four combines get unloaded successfully again (at least when i checked last time).

[savegame8.zip](https://github.com/Courseplay/Courseplay_FS22/files/12172269/savegame8.zip)
[FS22_Lk_HRO_4fach.SampleModMap_CP_Courses.zip](https://github.com/Courseplay/Courseplay_FS22/files/12172278/FS22_Lk_HRO_4fach.SampleModMap_CP_Courses.zip)

**Comment by pvaiko** [comment]
> I've thrown out all non-Modhub mods (except for the map of course)

... and the combines.

**Comment by pvaiko** [comment]
What I wanted to try is to make the area we check under the pipe smaller as it may return a false positive for fruit, by changing the 5, 3 to 1, 1 in this line:
https://github.com/Courseplay/Courseplay_FS22/blob/86d2c485541b5346a040093b6d1f1aa9ff01db80/scripts/ai/AIDriveStrategyCombineCourse.lua#L1014

**Comment by rohne83** [comment]
> > I've thrown out all non-Modhub mods (except for the map of course)
> 
> ... and the combines.

For the combines you need "CLAAS LEXION Model Year 2023" by Gefd25 (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=252639&title=fs2022) and the headers are from "Claas Vario Pack" by Mlody98, both on modhub. I only added realistic sounds to my versions but apart from that am using exact same mods as on modhub.

I recently continued this savegame. Finished that field, gave back 4th combine and 2nd overloader, and harvested barley on field 44. With 3 combines and just one overloader I couldn't reproduce the issue a single time. From time to time I also used a second unloader (going directly to the silo, but on field it behaves like the normal overloader), also without issues.
So could there be any issue with the course, with the number of combines, number of overloaders (unlikely after the last field but wouldn't rule it out completely) or the combination of these?

**Comment by pvaiko** [comment]
Oh sorry, looks like I still not understand when the game complains about a missing mod and when it offers to download it. 

In any case the above commit seems to help with the "above log message was even thrown by the leading combine which cannot have any fruit on pipe side that moment" problem.

**Comment by rohne83** [comment]
Tested in the provided savegame again, and now it looked good. All four combines got served at the right time.
