### ISSUE TITLE
[BUG_SP] implement too narrow turn on 180 degree turn

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2656]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
John Deere 7270R & Vaderstad Rapid A 800S - Giants drilling any field without using lands, especially on angled work and obstacles.

**Actual behavior**
When turning on a headland the tractor follows the path and turns too tight for a longer trailed implement (such as a vaderstad Rapid A 800S or KV PW100 -12 Plough. The Lemken Solitair 12 does not do this, I assume due to shorter machine and the turning pivot being further forward), often the drawbar crashing into the tractor, then the implement does not come into the run straight although the tractor does. This also happens when driving around an obstacle on the circular path

**Expected behavior**
Longer tractor and implements not to collide and turn in a wider circle before returning to work. The turn path loop needs to be larger and more offset and utilise more headland runs to turn so the drill and tractor do not collide and come into the centre path straighter (in my example videos I have 5x headland paths turned on, but it's trying to turn the vehicle inside three runs). The vehicle could go all the way out to the outermost headland path and turn, as the width of the implement would still turn inside the field but give the tractor a lot more chance to be straight before entering the centre path, this would work better for longer implements and also work for shorter ones. Or could the path adapt depending on the turning point of the implement?

Could the turn path calculations use the turning point of an implement if it's trailed? instead of the turning point of the tractor (as it appears to do now) which could be kept for mounted implement use? Similar to how IRL GPS asks if the implement is trailed or mounted and then changes its behavior based on this choice? 

**Screenshots**

Coming into and out of field centre
https://youtu.be/QaRWjT3qvFo
https://youtu.be/1cvDjVdNg4k

Around obstacles 
https://youtu.be/8-Tj_IsT_pQ

![fsScreen_2023_07_24_21_10_51](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/9828213c-93f0-4283-bd1b-89f029672167)

![fsScreen_2023_07_24_21_27_36](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ce8990d2-c11e-4f80-a836-45735cc7c5eb)

![fsScreen_2023_07_24_21_25_48](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/a4b8319e-5cde-451e-8639-0db812ea4c11)

Lemken Drill that doesn't do it as badly - as it's shorter and has a different turning point
https://youtu.be/RI1rcqU7NX0

**Courseplay version**
Version used: V7.2.1.8

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12152366/log.txt)

**Map**
The Oaks - Field 65

**Vehicles/ implements involved**
John Deere 7270R & Vaderstad Rapid A 800S - Giants

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
There is no turning point on anything.
There is a turn radius that does not match here for the tractor or implement. I rather think its the tractor but I will have a look on what it is.

**Comment by coatsy35** [comment]
I will look at other implements or combinations when I get a chance tomorrow. However the KV PW 100-12 made by giants definitely does it , especially on angled headlands. Is there any kind of flag these all have in common I.e something that could say use a wider turn? Is it the length that’s an issue

**Comment by pvaiko** [comment]
We have something we call the tight turn offset which should have been applied here, but I don't see it in the log. That would do exactly that, to force the tractor on a wider radius. At least at the row end turn that should be working, unless the tractor has an articulated axis or a crawler specialization. 

Looks like you have a 7RSeries mod, can you try with a vanilla tractor?

**Comment by coatsy35** [comment]
> We have something we call the tight turn offset which should have been applied here, but I don't see it in the log. That would do exactly that, to force the tractor on a wider radius. At least at the row end turn that should be working, unless the tractor has an articulated axis or a crawler specialization.
> 
> Looks like you have a 7RSeries mod, can you try with a vanilla tractor?

I will do this later today.

**Comment by Tensuko** [comment]
I don't see a problem here at all.
There is no colission.
![fsScreen_2023_07_25_12_23_41](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/33fda6e7-d233-4e7f-986c-ff785314cc82)
The tools are made to be able to have this narrow turning with the hinch there.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/6b35c806-03e2-448f-afe9-9f171705821e)

If you think this now becuse the driver doesn't stick to the lane, let me tell you the tractor is not driving "on the lane".
My log data.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12160029/log.txt)

**Comment by Tensuko** [comment]
There is even a tool for this to have other implements have a more narrow turn/more space.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/49889e67-3ec4-4d97-8000-c0d7ef9d446c)
![fsScreen_2023_07_25_12_37_47](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/52d738b5-f2d4-4320-baaf-c3b58230287e)
![fsScreen_2023_07_25_12_40_34](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/25ce6ea7-35b3-453d-b229-ce278a1ee0a8)

**Comment by coatsy35** [comment]
Maybe I should rephase the title then to "longer implements need a larger turning path so they turn onto the row straighter", due to their ground contact point being so far back they do not follow the path as good as the tractor. My point still stands, the path needs to be larger and or go out further to allow such an implement to turn properly a 6m drill like the Vaderstad should be able to turn back into a row without issue instead it currently turns back in on an angle. 

> We have something we call the tight turn offset which should have been applied here, but I don't see it in the log. That would do exactly that, to force the tractor on a wider radius. At least at the row end turn that should be working, unless the tractor has an articulated axis or a crawler specialization.

Please try a Giants KV PW100-12 plough as that often jams against the tractor as it turns so tight and then the tractor can't drive, especially on angled headlands.

**Comment by coatsy35** [comment]
> We have something we call the tight turn offset which should have been applied here, but I don't see it in the log. That would do exactly that, to force the tractor on a wider radius. At least at the row end turn that should be working, unless the tractor has an articulated axis or a crawler specialization.
> 
> Looks like you have a 7RSeries mod, can you try with a vanilla tractor?

Exactly. IRL you would turn a lot wider and further out so you made sure your implement was going to pull into the row straight. You obviously have a system for this in CP but not working in my example.

**Comment by cyr123** [comment]
For the issue of trailed implements not being straight after the turn and bits being missed I've found that I get the best result with *fewer* headlands, this forces CP to back up as part of the turn which will straighten up the implement. 

It would be really nice if CP could automatically detect if the implement isn't straight at the start point of a row, and automatically move forward to straighten it and then back up to the starting point.

**Comment by coatsy35** [comment]
> For the issue of trailed implements not being straight after the turn and bits being missed I've found that I get the best result with _fewer_ headlands, this forces CP to back up as part of the turn which will straighten up the implement.
> 
> It would be really nice if CP could automatically detect if the implement isn't straight at the start point of a row, and automatically move forward to straighten it and then back up to the starting point.

I agree, as CP actually does a really good job of backing up and pulling forward straight when for instance a square corner is performed. So it either needs far bigger turning circles for longer trailed implements utilising more of the headland depth or a way to backup if it is not straight.

**Comment by pvaiko** [comment]
https://github.com/Courseplay/Courseplay_FS22/commit/a83bf3fbe38584c33ba366c174343a3725507f9f should now re-enable the wider turns with towed implements.

**Comment by coatsy35** [comment]
> [a83bf3f](https://github.com/Courseplay/Courseplay_FS22/commit/a83bf3fbe38584c33ba366c174343a3725507f9f) should now re-enable the wider turns with towed implements.

That's great. I have tried numerous implements tonight and the worst is definitely the Rapid 800 drill. Larger 12m items seam not too bad, but I assume that is due to their usually shorter overall length. The Vaderstad drill is pretty long for only 8m wide. I also found when testing some large ploughs used a large wide path and other use the smaller path, so hopefully it will help there too 😎

Some pics of different implements of similar width and their path size tonight, bottom one even wider but using a smaller path than the 6m ones!

![fsScreen_2023_07_25_21_48_10](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/08beac92-f820-4faa-8c62-06c290d5ab81)

![fsScreen_2023_07_25_21_47_38](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/7518ae66-9916-464b-8ef7-4fd54e3a5500)

![fsScreen_2023_07_25_21_47_05](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/a9ca2599-bc26-46f8-bf37-2a6308131a6e)

![fsScreen_2023_07_25_20_59_41](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/487fd877-3054-49f3-bbe1-82cbf1b1cf54)

**Comment by Tensuko** [comment]
The not working tight turn will be fixed in the next release.
We will not adjust anything more on the turns here, as I don't see super bad colissions.
If you are not happy about your tools turning too narrow even they do just fine, there is always a user based vehicle configuration where you can adjust the turn radius:
https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.

**Comment by coatsy35** [comment]
That's great to know. Thank you.

**Comment by coatsy35** [comment]
> [a83bf3f](https://github.com/Courseplay/Courseplay_FS22/commit/a83bf3fbe38584c33ba366c174343a3725507f9f) should now re-enable the wider turns with towed implements.

I have installed the new update and now the turning path still looks small on that drill, then half way round it expands and the shrinks back again to small. Can't recall seeing this before. Is it something to be concerned with? Please see video below.

https://youtu.be/33oN2Q1Qtdk

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12176994/log.txt)

**Comment by Tensuko** [comment]
This is how it should look like.

**Comment by coatsy35** [comment]
Ok no problem. Still confused why a 6m long drill has small path. I'll create a customer setting for that item, although not sure that's possible with a giants built in implement? your help file talks about doing it from mods which I understand. Can it be done for built in machines?

**Comment by Tensuko** [comment]
All machines, you just need to know the tool.xml file name.
Look in cp mods file there is one with a lot of pre adjusted tools.
Might need to update the wiki page for the latest features but the basic one are still up to date.
