### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Chaserjim** [Courseplay/Courseplay_FS22#2658]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Unload and deliver SUGAR BEET 
Delivery waypoint for sugar beet is wrong waypoint at farmers market.

**Actual behavior**
When selecting the unload combine and deliver to johnsons farmers market, the produce is taken to the wrong delivery location. 

**Expected behavior**
There are 2 delivery locations at the farmers market based on what you are delivering. I expect when I select unload combine and deliver , that the produce type is iterated over and determined where , if multiple deliver spots at a single ocation , to deliver. 

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Misamangame** [comment]
And again not related to CP whatsoever....

**Comment by Tensuko** [comment]
No log no version, this is fixed already but no idea what version you got.
