### ISSUE TITLE
[Question] CP für mod "Variable Weinreben Breiten" ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2659]
Guten Morgen
ich habe gerade festgestellt. das CP für den mod Variable Weinreben Breiten
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=243312
keinen kurs generieren kann.

Ausgangssituation, variable Weinreben 2,00m Abstand:
![fsScreen_2023_07_26_06_34_42](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/f3dc45b8-f22d-4bcd-b2c8-f1c69ffd0057)

im Kursgenerator-Menü erkennt CP nur eine Reihe
![fsScreen_2023_07_26_06_35_10](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/b235a745-caa1-4378-b687-29acd6af18db)

nach Kurs Generieren wird kein Kurs generiert, und nur eine Reihe erkannt:
![fsScreen_2023_07_26_06_35_33](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/fbfc46d9-fa5c-478c-815f-d6a3c98a622a)

mit den Standard Weinreben von giants (3,00m weite) macht cp es anstandslos:
![fsScreen_2023_07_26_06_33_43](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/42bd5278-e637-42f9-b1a9-f15232dd6580)
![fsScreen_2023_07_26_06_34_15](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/2b4ca4b3-2bee-4104-ab56-4085dee3cf0d)
![fsScreen_2023_07_26_06_34_28](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/6dc3f0b1-7498-470d-a590-21c17492b9d8)

gibt es eine Möglichkeit das diese mod irgendwann unterstützt wird?
lg
andreas

**Comment by Tensuko** [comment]
Wissen wir noch nicht, aktuell nur vanilla.

**Comment by andreasthu** [comment]
Sorry nochmal fürs reopen,
Mir ist da grade am letzten Bild aufgefallen, das Cp für 6 Reihen Weinreben auch 6 Arbeitsreihen erechnet.
Müßten es fürs z.b. Grubbern oder Mulchen dann aber nicht 7 Arbeitsreihen sein?
D.h. nach dem Letzten Kurspunkt hier 
https://user-images.githubusercontent.com/24860501/256118941-6dc3f0b1-7498-470d-a590-21c17492b9d8.png
Müsste CP eigentlich noch eine Rechtskurve machen und die letzte Reihe noch einmal ganz aussen zurückfahren.
Kg
Andreas
