### ISSUE TITLE
Huge unworked patch when switching from headland to rows

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/Courseplay_FS22#266]
**Steps to reproduce**
create a course with 2 headlands

**Actual behavior**
after finishing the headland and going for the row work, the first turn is just a U-turn instead of a 3-point-turn (as usual when turning between rows)

**Expected behavior**
making a 3-point-turn

**Screenshots**

![fsScreen_2021_12_30_18_34_49](https://user-images.githubusercontent.com/21023840/147775440-3dc5a55b-cd49-401e-9f01-0067efdd2ce6.png)
![fsScreen_2021_12_30_18_36_50](https://user-images.githubusercontent.com/21023840/147775444-5d020568-5749-4947-b7bd-8d869096005f.png)
![fsScreen_2021_12_30_18_43_52](https://user-images.githubusercontent.com/21023840/147775842-be440bf1-4f52-45ce-b170-02fa4821853c.png)

**Courseplay version**
Version used: 7.0.0.9

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7794005/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Mod yes/no ? NO

**Relevant script mods**
AD and VCA

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki
"1. Always update to the latest build and check if the problem really still exists before reporting issues."

**Comment by iljarogoff** [comment]
I always update directly from git, so I thought I have the most recent one :)
I will test 7.0.0.10 later 👍

**Comment by Tensuko** [comment]
Great, thank you :)

**Comment by Tensuko** [comment]
Seems to be still there, so duplicate #335
