### ISSUE TITLE
CP wird nicht in der Mod Liste erkannt![BUG_SP]

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2660]
CP wird nicht mehr im Modmenu erkannt!
Updated 13 hours ago by [pvaiko](https://github.com/pvaiko)

**Comment by Tensuko** [comment]
logfile?
Halte ich für ein Gerücht, das es nicht erkannt wird!

**Comment by KarlGutenberg** [comment]
Was nicht im Menü steht, kann auch nicht in der Log stehen!
![Screenshot (20)](https://github.com/Courseplay/Courseplay_FS22/assets/78603817/c429bcb1-f0a9-4130-8492-43f59ce2855a)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12171161/log.txt)

**Comment by Tensuko** [comment]
Mein Lieber Herr....
Es steht ALLES in der log!
"Available mod: (Hash: 3b6e3a913220e9226c38cc9e5834cd19) (Version: 7.2.1.8) Courseplay_FS22
Error: Unsupported mod description version in mod Courseplay_FS22"

Version: 1.10.1.1 b25105

Du hast eine zu alte LS Version! Updaten!

**Comment by KarlGutenberg** [comment]
Danke! 
Normalerweise mach Giants selber ein Update bei mir!
