### ISSUE TITLE
[BUG_SP] Not found in mod list  v7.2.1.9

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/Courseplay_FS22#2661]
hy!
I downloaded the new version, copied it into the mods folder, but the game can't find it! I searched manually, but it's not there.

Test:
The game sees an advanced version.

**Comment by Tensuko** [comment]
Again someone without logfile...

Read the changelog!
Increase modDesc Version to 76 (Game Version 1.11.0.0)
