### ISSUE TITLE
Implement includement

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/Courseplay_FS22#2662]
Can you please add fixed tool offsets for  WM-185 Mähwerk 1.0.0 ?

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234107&title=fs2022

thx in advance

**Comment by Tensuko** [comment]
You can do this for yourself.
https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.
