### ISSUE TITLE
[Question] Unloader searching for trailer in farmlands

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#2663]
Hi Courseplay team

When using a augerwagon to offload the combine. It seems like when it is full it is looking for a trailer in the farmland connected to the field not the field boundaries.
This causes some issues on a lot of maps. As many maps includes the main farm in the same farmland as the nearest field (where you usually store unused trailers)

Is this correct?
Would it be not better if it was using the field boundaries? 

The map i am playing on i had to change the farmlands in Giants Editor to fit the fields. To stop the augerwagon going to the farm.
This is not a huge issue for me as it is not a big deal the change the farmlands. But i believe it can cause some issues for a lot of players.

The pictures are from Elmcreak just to show you whats going on.

Thank you for your hard work on this mod. 

![Farming Simulator 22 Screenshot 2023 07 27 - 21 23 48 29](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/60a9a486-62de-46b5-a1f2-5ed6eea82515)
![Farming Simulator 22 Screenshot 2023 07 27 - 21 24 44 80](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/01dfc5e9-804d-4ed8-a3ec-8941d755a171)
![Farming Simulator 22 Screenshot 2023 07 27 - 21 24 58 20](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/ea626980-5cef-4d2e-adb6-e0da4f50f227)
![Farming Simulator 22 Screenshot 2023 07 27 - 21 26 45 58](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/806aee54-bed7-4198-ba92-8146da67f025)
![Farming Simulator 22 Screenshot 2023 07 27 - 21 27 03 56](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/53017b8a-193a-454c-8dff-810896c36bb6)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12187685/log.txt)

**Comment by Tensuko** [comment]
It is the field boundaries + 20m, not the farmlands.

**Comment by Martin-L45** [comment]
Thats what i thought.
I just tried another setup in field 73 on elmcreak

The pictures show the trailer parked well beyond 20meters from the field border. but just as i move it within the farmlands area the unloader can find it.

This might be something on my end. But you can easily recreate in field 73. 
Take a look and if you think it is ok we can just close the question.

 
![Farming Simulator 22 Screenshot 2023 07 28 - 08 37 36 20](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/205a0887-db33-4e20-bf8e-814525556f99)
![Farming Simulator 22 Screenshot 2023 07 28 - 08 38 00 63](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/00fb3ca3-d4a8-4895-82c3-d50f10835c55)
![Farming Simulator 22 Screenshot 2023 07 28 - 08 38 37 22](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/d04c4668-384f-4af3-902d-03d4703824ee)
![Farming Simulator 22 Screenshot 2023 07 28 - 08 38 44 67](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/5e78e083-c75e-42e1-853f-03237aaaceba)

**Comment by Tensuko** [comment]
Will have a look at this.

**Comment by Martin-L45** [comment]
Awesome I cant ask for more than that.

If there is something about this. It might be causing part of the problems on the Huron Michigan 16x map Issue #2372
On this map the farmlands cover multiple fields and and farmyard

![Farming Simulator 22 Screenshot 2023 07 28 - 09 38 10 19](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/7db329cd-d598-4a97-9bec-b0b18d04f9e4)
![Farming Simulator 22 Screenshot 2023 07 28 - 12 39 22 40](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/72855a16-36cf-4a69-b8e8-aeded13fe4b8)

**Comment by Tensuko** [comment]
@pvaiko kannst du mal schauen?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12193988/log.txt)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/980bb219-5d79-4c4c-86c9-d0838d5d8888)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/116ea752-5396-4582-90dd-ed4e05b8b601)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/5a795bee-1eaf-42c2-9271-b9e2dd005680)
