### ISSUE TITLE
[BUG_SP] Bug automatic tool offset calculation

### ISSUE THREAD

**Issue by schwiti6190** [Courseplay/Courseplay_FS22#2666]
**Steps to reproduce**
Automatic work width calculation for Grimme Evo 290

**Actual behavior**
The tool offset uses the wrong marker for calculation:
`offset = left - width / 2`
For this implement left has to be replaced by the right marker.

**Expected behavior**
` if left < 0 then 
     offset = right - width / 2
end`
Might be as simple, as changing the marker if the offset is on the left side, but not sure.

**Courseplay version**
Version used: master

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12207935/log.txt)

**Comment by pvaiko** [comment]
@schwiti6190 There is an AIImplement.aiMarkersInverted flag, isn't that useful?

**Comment by schwiti6190** [comment]
Not really worth the effort in the end
