### ISSUE TITLE
[BUG_SP] you can't see the worker's auxiliary lines

### ISSUE THREAD

**Issue by karolus2277** [Courseplay/Courseplay_FS22#2669]
mod version 7.2.0.5
games version 1.10.1.1

I can't see the auxiliary lines
after the game update i can't see the help lines of the employee
I was looking for a newer version of the mod but I couldn't find it anywhere. I downloaded it from the official farming simulator 22 website
this error occurred after game update 1.10.1.0
I thought it was a temporary problem with this particular vase, so I waited for the next update but nothing changed

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12208142/log.txt)

**Comment by Tensuko** [comment]
The latest version is always on github.
7.2.1.9 with FS 1.11

**Comment by Tensuko** [comment]
I now had time to look at your log.txt
You realy need to clean up your mods folder.
FS19 Mods are not supposed to be in there, as well as mods with Errors or diplicates with (1) in the name.
And unzip in the name.... well... guess what you have to do.
