### ISSUE TITLE
[BUG_SP] Challenger Raupe +  Lemken Titan 18 zuckelt nur um die Kurve beim Wenden (Wenderadius nicht aktiv?)

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#267]
Wollte gerade Elmcreek Feld 38 mit der MT738 + Titan 18 Pflügen lassen, aber CP hat anscheinend ein Problem bei der Kurvenfahrt wenn eine Raupe vorne dranhängt. Der fährt an bremst fährt an, bremst, bis er um die kurve ist und wieder arbeiten darf, dann fährt er mit Feldgeschwindigkeit durch bis zur nächsten Wende,

Alternativ hab ich den NH T7.315HD drangehängt mit dem isses wesentlich besser, zwar immernoch minimal, aber das is zu verschmerzen.

gekürztes Log: 
[log_gekürzt.txt](https://github.com/Courseplay/Courseplay_FS22/files/7794110/log_gekurzt.txt)

Log2: Die Ecken des Vorgewendes funktionieren auch nicht richtig. Beim um die Ecke fahren fährt die MT irgendwann auf den Pflug (Edit: 7.0.0.10 die Ecke ist jetzt besser, aber noch sehr hakelig) 
![MT1](https://user-images.githubusercontent.com/8066324/147780895-b2db12e9-7169-4749-8b5c-da97a8bd40ad.png)
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/7794243/log2.txt)

Edit2: 2 Bilder gelöscht, da ich den Sinn verstanden habe, da er beim erneuten rumfahren das ausgelassene Stück gepflügt hat.
wurde ausgelassen, da es sonst doppelt bearbeitet worden wäre

**Comment by dominiczeth** [comment]
Mal eine Idee in den Raum geworfen: ich denke der Lenkradius ist das Problem. Das war im 19er schon so bei Raupen, da half es den Lenkradius zu erhöhen.

**Comment by RealNeo80** [comment]
deswegen hab ich den Wenderadius schon auf 15m

**Comment by rohne83** [comment]
Scharfe Vorgewendeecken und enge Feldreihenwenden mit Rückwärtsfahrt sind aufgrund des Geräteversatzes und ungünstig gelegenen Lenkpunkts sowieso alles andere als einfach beim Pflügen. Bekommt ja schon ein Mensch kaum anständig hin, wie soll das dann ein einfaches Skript auf Basis von ein paar Formeln wirklich zuverlässig hinbekommen? Wenn dann noch ne Raupe dazukommt die praktisch auf der Stelle wenden kann wird es alles andere als einfacher.
Da kommst am besten mit Reihen überspringen (ich weiß, das Feature gibts noch nicht) oder kreisförmig für die Bahnen und weiche oder runde Vorgewendeecken, und den Rest halt manuell nacharbeiten. Das sollte CP auch beim pflügen relativ zuverlässig hinbekommen.

**Comment by RealNeo80** [comment]
Naja das ausfahren der Scharfen ecken im script is einfach zu kurz, der schafft es nicht das gerät grade zu ziehen, bzw hab ich auch den eindruck dass wendekreis keine funktion hat, das muss ich aber nochmal testen. 

Und ganz so schlimm is das in Wirklichkeit net wenn man fahren kann ;) aber ja für jemanden ders nicht oft macht is ein Aufsattelpflug schon ne Herausforderung

**Comment by Tensuko** [comment]
Wenderadius ist glaub ich noch nicht drin, aber es würde auch helfen wenn wenden auf Feld aus ist (meine ich).
Ansonsten ja Abwarten.

**Comment by RealNeo80** [comment]
Feld wenden war aus. Ja ich seh das eher nur als "Bug Sammlung" als das ich da sofort eine Lösung erwarte ;)

**Comment by dominiczeth** [comment]
> Feld wenden war aus. Ja ich seh das eher nur als "Bug Sammlung" als das ich da sofort eine Lösung erwarte ;)

Ja so sehe ich das hier generell. Guck Mal wie oft das CP Team hier Updates raus haut, und die machen das nur in ihrer Freizeit. Ich sehe jeden Report eher als Hinweis anstatt als "fixt das sofort!" ;)

**Comment by Tensuko** [comment]
Funktioniert bereits, ich mach daher hier zu.
