### ISSUE TITLE
Problem with save[Question]

### ISSUE THREAD

**Issue by SajferoS** [Courseplay/Courseplay_FS22#2671]
Hello, I have a problem with CP because when I create a new field and save it, everything is ok, but when I turn on others or a new save on the same map, this field is also saved and when I delete it on the new save, it automatically disappears on the first save, is it there any option to make the new field only saved on a given save and not on each of the same map?

**Comment by Tensuko** [comment]
Becosue Custom Fields and Courses are saved per map, not savegame.
This will not be changed.
