### ISSUE TITLE
[Feature] Use actual field polygon for field limits on combine unloading mode

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2673]
**What is the problem this feature/enhancement solves?**

When using the unload combine mode the trailer often strays outside of the field and into hedges or stuck behind trees when unloading the first run of the field and even when trying to find its way out of the field, even when using AD for the journey to empty.

**Describe the solution you'd like**
The trailer to stay inside the actual field polygon

**Describe alternatives you've considered**
Can't think of any

**Comment by Tensuko** [comment]
There is no way to have the driver stay on field with fruit.
It will stay like it is.
You can try turn off avoid fruit.
