### ISSUE TITLE
[BUG_SP] Low Loaders unfold when Bale collecting using Universal Autoload

### ISSUE THREAD

**Issue by armyf35** [Courseplay/Courseplay_FS22#2677]
**Steps to reproduce**
1. Create some bales on a field
2. Get a low loader that can unfold (DTS 5.9 | Steel Drop Deck | Renown Drop Deck)
3. Get a truck
4. Attach to low loader
5. Target field with the bales created in step 1
6. Drive near/into the field
7. Start Courseplay driver

**Actual behavior**
Driver first unfolds the trailer before attempting to pickup bales. Since these are low loaders (And using Universal Autoload to load bales) not bale loaders, there is no physical part needed to pickup bales. In the case of the DTS 5.9 specifically, legs are dropped at the rear of the trailer which causes it to slide around since the rear wheels are off the ground.

**Expected behavior**
The driver should not unfold low loader trailers when bale loading since this can cause steering issues and/or needlessly increase the length of the trailer.

**Screenshots**
![1](https://github.com/Courseplay/Courseplay_FS22/assets/7518618/8ca3a6dc-93f3-4f25-a063-7a016a8da041)
![2](https://github.com/Courseplay/Courseplay_FS22/assets/7518618/df2d80e7-cc9b-4d4e-8b51-a5f6b0c2a4a9)
![3](https://github.com/Courseplay/Courseplay_FS22/assets/7518618/9f8bb9f0-9fe5-4a4e-be92-79824dd3db34)
![4](https://github.com/Courseplay/Courseplay_FS22/assets/7518618/90c38cdd-3dcc-4ff0-8345-31b38d571e91)
![5](https://github.com/Courseplay/Courseplay_FS22/assets/7518618/b18b3836-71cf-424d-b75d-550e0d598103)

**Courseplay version**
Version used: 7.2.1.9

**Log**
[log.txt](https://gist.github.com/armyf35/059d9c0e7dc51356138fb30d9954097c)

**Map**
Tested on Elmcreek

**Vehicles/ implements involved**
- Low Loaders (Tested with all four base game loaders, the "Transportwagen TP 500S" cannot fold and therefore has no issue)
  - DTS 5.9
  - Steel Drop Deck
  - Renown Drop Deck
  - Low Loader 4A (Platinum Expansion)
  - Low Loader 3A (Platinum Expansion)

**Relevant script mods**
- Universal Autoload (1.4.1.0)
- Easy Development Controls (1.3.0.2)

**Comment by Tensuko** [comment]
The problem is that those tools would need allowAIFold = false or whatever the function was.
As they are vanilla tools we figure something out.

@schwiti6190 we might need a disallowUnfold bool for the vehicle config.
We have this problem mostly with mods, but when this also happens with vanilla tools, a vehicle config might be the best solution to not overcomplicate any checks of vehicle type.

**Comment by armyf35** [comment]
Yeah, this felt like a odd edge case where some added functionality to base game vehicles by Universal Autoload caused some odd behavior.

Just checked the two low loaders added in the Platinum Expansion and they have the same issue.

I'll look into submitting a PR as well, was pretty late and figured getting it reported is the most helpful first step.
