### ISSUE TITLE
[BUG_SP]Wendemanöver mit dem Holmer Terra Variant 585

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2683]
Guten morgen liebes cP Team

**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
Wendemanöver mit dem Holmer Terra Variant 585 mit aufgesatteltem Annaburger XM3 Miststreuer

**Actual behavior**
A clear and concise description of what happen.
bei einer Kursgenerierung, 18m breit, 1x Vorgewende, Pathfinder an, Pathfinder darf rückwärts fahren an, verfranzt sich der Holmer gegen ende des Turns und beginnt die nächste Bahn komplett falsch ausgrichtet und muss erst in die Spur finden:
![fsScreen_2023_08_04_06_44_44](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/154fa4c9-0eae-48f7-b3ef-64bb998997d5)
![fsScreen_2023_08_04_06_44_52](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ad669b08-6384-40e3-80ac-47788405e07e)
![fsScreen_2023_08_04_06_45_00](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/5e7de32d-3253-4f70-b788-3e8e3b714810)
![fsScreen_2023_08_04_06_45_05](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/318e76dd-3b7e-44bf-8140-03cb690f1596)
![fsScreen_2023_08_04_06_45_07](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d3464fce-d07f-49b9-931c-0255299ff06a)
![fsScreen_2023_08_04_06_45_08](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d6f3c416-117d-4fdb-b3ca-cd53b018de46)
![fsScreen_2023_08_04_06_45_10](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d018da85-c021-461a-8f53-5611cbf6b573)
![fsScreen_2023_08_04_06_45_11](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/7e1536b1-38b1-4e02-8f87-cc0c4b1f700a)
![fsScreen_2023_08_04_06_45_13](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/39482ccb-9712-4acc-a0ce-d9581bf26e8b)
![fsScreen_2023_08_04_06_45_15](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/5366935d-7d98-48be-99ed-301a34540dcf)
![fsScreen_2023_08_04_06_45_16](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/fd492c08-3228-49fc-b54b-8e48fc0a1b38)
![fsScreen_2023_08_04_06_45_19](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/cae37c05-f4ba-414c-ad0f-a8ecd83e8a2c)
![fsScreen_2023_08_04_06_45_21](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/30636efc-15ab-4421-a986-f10c56bb32fc)
![fsScreen_2023_08_04_06_45_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/62517d05-b51b-432a-b7fa-9c4db3ada8bb)
![fsScreen_2023_08_04_06_45_28](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/4356832f-831e-4e83-b6c0-f5e8d7734065)

so sieht die Reifenspur aus:
![fsScreen_2023_08_04_06_46_22](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/90f585ae-e91e-40c1-a0c1-89adca2d3250)

**Expected behavior**
der TV585 mit XM3 sollte nach der Wendung gerade ausgerichtet in der Bahn stehen.

der Holmer mit dem aufgesatteltem Güllefass und dem Bomech tracPack bringt die wendung problemlos zustande:
![fsScreen_2023_08_04_06_46_52](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/1644841f-444e-4f3e-b82e-e13cb79fb986)
![fsScreen_2023_08_04_06_46_58](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/0fc43cb6-7894-4484-997f-231cdd0037cf)
![fsScreen_2023_08_04_06_47_08](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/bd42f83d-e46b-4910-8300-cb87f96c4925)
![fsScreen_2023_08_04_06_47_18](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/491779ef-085f-46c7-8e56-5deba9bd1954)
![fsScreen_2023_08_04_06_47_22](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/45989cdc-29c1-4113-ad4e-4896de730ff4)

**Screenshots**
siehe oben

**Courseplay version**
Version used: 
modhub-version 7.3.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12257201/log.txt)

**Map**
Map played on.
beim Beispiel Elmcreek, aber prinzipiell auf jeder map

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Holmer Terra Variant 585 mit aufgesatteltem Annaburger XM3 Miststreuer
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=241853&title=fs2022
Giants mod Holmer Pack

**Relevant script mods**
Mods like Autodrive or VCA and so on.
cp

btw: warum pfadfinder an in der Wendung:
![fsScreen_2023_08_04_06_48_45](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/b8ff8609-5edd-4534-b9db-e7a5e0c95082)

lg
andreas

**Comment by pvaiko** [comment]
This is happening because the Annaburger XM3 has an AI reverser node defined in xm3.xml: 
`<toolReverserDirectionNode node="aiSizeMarkerBack" />`

None of the other attachment in the Holmer Pack has this set, which is how it should be, as they are not towed implements and do not need a reverser node at all.

This is an issue with the Annaburger XM3 mod, not a Courseplay bug.

**Comment by andreasthu** [comment]
Ok, 
This means, when i commend this line out, he should turn better?
I will give it a try.
Lg
Andreas

**Comment by andreasthu** [comment]
> This is happening because the Annaburger XM3 has an AI reverser node defined in xm3.xml: `<toolReverserDirectionNode node="aiSizeMarkerBack" />`
> 
> None of the other attachment in the Holmer Pack has this set, which is how it should be, as they are not towed implements and do not need a reverser node at all.
> 
> This is an issue with the Annaburger XM3 mod, not a Courseplay bug.

Thank you for your info, with outcomment the line now it works
`    <ai>
        <needsLowering value="false" />
        <areaMarkers leftNode="aiMarkerLeft" rightNode="aiMarkerRight" backNode="aiMarkerBack" />
        <sizeMarkers leftNode="aiSizeMarkerLeft" rightNode="aiSizeMarkerRight" backNode="aiSizeMarkerBack" />
        <allowTurnBackward value="true" />
        
        <agentAttachment jointNode="moduleJoint" width="3" height="4.4" length="8.9" lengthOffset="-0.2"/>
    </ai>
`

![fsScreen_2023_08_06_16_59_55](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/4d5dad4a-b8e7-4a5b-822a-0d267be1ff3e)
![fsScreen_2023_08_06_17_00_12](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/b4c5b2d0-076d-474f-a79e-9480c4c1b7ff)
![fsScreen_2023_08_06_17_00_16](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/3c913dd8-e17c-4775-8cfa-e148de46eb1b)
![fsScreen_2023_08_06_17_00_20](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/05dbf665-078c-4f00-8adf-4f048e096cdb)
![fsScreen_2023_08_06_17_00_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d1757b08-ea10-4267-b008-fbd3900b53bd)

lg
andreas
