### ISSUE TITLE
[Feature]am Kursende Bremsen anstelle des ausrollens?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2684]
Guten Morgen liebes Cp-Team

**What is the problem this feature/enhancement solves?**
Bei Kursen mit schnellen Anbaugeräten rollen die Fahrzeuge bei Kursende mehrere Meter aus.
![fsScreen_2023_08_04_07_20_04](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a49480cd-ba8e-48b8-9441-a8eadeb16712)
![fsScreen_2023_08_04_07_20_11](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/eda7220f-b8a2-474b-9b17-d818779db75b)
![fsScreen_2023_08_04_07_20_16](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a5dc2f3b-9934-4dc2-9d19-aded3756fc36)
![fsScreen_2023_08_04_07_20_19](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/b1ae9920-e847-4681-afbf-1675fb3769b5)

**Describe the solution you'd like**
Die Fahrzeuge könnten am Kursende Bremsen, somit würden sie schneller stehen bleiben

**Describe alternatives you've considered**

**Additional context**
siehe oben

lg
andreas

**Comment by Tensuko** [comment]
@schwiti6190 das ist das was wir neulich zwischendurch mal hatten.
Kann das auch vom LS kommen?
Wie macht Giants das?

**Comment by Tensuko** [comment]
Also ich finde es schon faszinierend, dass dein Fahrzeug gegen Kursende nicht langsamer wird.
Ich habe eben versucht das nach zu stellen und meiner bremst schon mal gegen Ende auf 8km/h runter (7.3.0.0)

**Comment by andreasthu** [comment]
Ist das dann eine einstellungssache?
Turnspeed ist bei mir 15km/h, Rückwärts 12km/h.
Btw, Feldende ist "spät" und Beginn auf "früh" gestellt.
Sry, hab nicht gewusst das das zusammenhängt.
Wäre aber trotzdem gut, wenn sie aktiv bremsen könnten. Manchmal endet der Kurs vorm Bach und dann rollen sie baden.
Lg
Andreas

**Comment by Tensuko** [comment]
> Btw, Feldende ist "spät" und Beginn auf "früh" gestellt.

Es gibt keine Einstellung für Feldende und das was du eigentlich meinst, hat damit nur was zu tun, wie weit er raus fährt.

Zum abbremsen bis zum Kursende wird hier Turnspeed verwendet, aber wir haben eine Bremse eingebaut, kommt irgendwann mit der nächsten Version.

**Comment by andreasthu** [comment]
Danke dir sehr.
Lg
Andreas
