### ISSUE TITLE
[BUG_SP] drive direction change doesn't work after cancel of courseplay track

### ISSUE THREAD

**Issue by RuppMartin001** [Courseplay/Courseplay_FS22#2686]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

I have courseplay 7.3.0.0 together with Autodrive and VCA in a game.
I created a course in courseplay for tractor with mower device. 
An offset for the device is necessary because it is no butterfly mower device.
The tractor is driven into the fence of the field on map "Hof Frühling".
Courseplay was not able to resolve the conflict. Therefore I have to cancel the route.
Then the behaviour of the tractor is very strange.
If I try to drive backward with the tractor it it not possible.
Gear shows correctly "-1" but the tractor tries to drive only in forward direction.
I tried it three times and it doesn't help to leave the tractor.
All other tractors are working. But I doesn't used courseplay with them.
I have to end the game because the tractor is no longer working.

**Actual behavior**
A clear and concise description of what happen.
See "Steps to reproduce the behavior."
After canceling the course the tractor can no longer drive in backward direction.
Gear shows minus befor the choosen gear. So the game seems to know that there is a change of the drive direction.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.3.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
I will do that in the next coment.
I am afraid to lost all written text in this field (session timeout).

**Map**
Map played on.
"Hof Frühling"

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Tractor: Steyr 8150 - No mod.

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Yes, I use also Autodrive and VCA.

**Comment by Tensuko** [comment]
Bug of tractor.
I can reproduce this without cp involved by use of change direction key (basegame) the gear will be locked at backwards and there is no way back unless i start any helper that forces the tractor back to normal.

Same tractor.
