### ISSUE TITLE
[BUG_SP] 2 Helfer auf einem Feld

### ISSUE THREAD

**Issue by Gillios** [Courseplay/Courseplay_FS22#269]
Ich habe das Problem das ich aktuell einen Krone Big M mit einem geladenen Kurs auf dem Feld habe, der mäht, habe den gleichen Kurs mit meinem Ladewagen geladen, jedoch kann ich den Helfer nicht starten.

Es kommt im Log immer eine kleine Meldung die lautet:

2021-12-30 22:19 :19 [dbg4 lp501699] 1050: Could not start cp helper.

Spiele auf der neusten Version von CP.

Des weiteren hat er bei dem Krone Big M als Arbeitsbreite nur 1m erkannt.

Trotzdem nochmal vielen dank für die bisherige Arbeit und einen Guten Rutsch :)

**Comment by Tensuko** [comment]
Weil Ladewagen noch nicht funktioniert.
Bitte abwarten...
