### ISSUE TITLE
[Feature] Possibility to reverse drive direction on outer head land.

### ISSUE THREAD

**Issue by dieterdewachter** [Courseplay/Courseplay_FS22#2694]
When you are using an implement with a horizontal offset and you have a field with fences on the sides of it. It will drive into these fences.

A possible fix would be to be able to reverse the driving direction on the outer head land.
When we for example mow in real life with a single mower on the back.
We first do two headlands with the mower faced into the field and leave the outer headland to drive on it.
When we mowed those headlands we turn around and mow the outer headland with the mower faced out of the field.
This way you will have no collision with objects around the field.
The same feature could be implemented when you drive around obstacles.

Please feel free to add additional info or questions if you don't really know what I mean.
Thanks in advance to the whole team!

**Comment by Tensuko** [comment]
Just change the startdirection to counter clock wise on the course generator.
Might need to turn on the expert setting.
Mixed headlands will add unnecessary complexity to the generator and the settings.
