### ISSUE TITLE
[Question]CP 7.3.0.0 is not working.

### ISSUE THREAD

**Issue by Unddann** [Courseplay/Courseplay_FS22#2695]
Hello everyone. I have a problem with CoursePlay 7.3.0.0. When I have this version in the mods folder, CoursePlay no longer appears in the game when installed. When I have version 7.2.1.8 in mods folder everything works. Does anyone have this too? Also, I can't load CoursePlay from Modhub via the game. It does not appear in the overview.

**Comment by Tritura2** [comment]
A logfile would help

**Comment by Tensuko** [comment]
Pretty sure you are running an old FS Version.

**Comment by Unddann** [comment]
A log file is difficult. I didn't start the game completely. The new version does not appear on the first page of the LS22. When I try to start the game I get a warning that CP is not installed. If I drag version 7.2.1.8 to mods folder everything works.

**Comment by Tensuko** [comment]
Logfile.....
Just post it...

**Comment by Unddann** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12274542/log.txt)

**Comment by Tensuko** [comment]
Farming Simulator 22
  Version: 1.9.1.0 b23678

Just as I said.... old FS Version... Update your game.

**Comment by Unddann** [comment]
Oh dear, thanks a lot for your help
