### ISSUE TITLE
[BUG_SP]Harvester do not use combine turn on 1st headland.

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#2696]
**Screenshots**
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/19fc0549-bcf1-4afe-8787-75dea7c14e4c)

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12282563/log.txt)

**Vehicles/ implements involved**
Potato and Beet Harvester.

May need a special turn manuver for them, but can try our existing one.

**Comment by pvaiko** [comment]
This isn't a bug, this is how it is explicitly implemented, as the log also says:
2023-08-07 18:00 :52 [dbg1 lp11848] Ventor 4150/213: WORKING: This is a potato or sugar beet harvester.
2023-08-07 18:00 :52 [dbg1 lp11848] Ventor 4150/213: WORKING: Headland turn but this harvester uses normal turn maneuvers.

**Comment by coatsy35** [comment]
Are there any tips to setting these up? been doing a lot of potatoes, however It usually misses the first part of each run as it does a fish tail turn and doesn't turn in tight enough. Could it do a lightbulb like towed implements? is there a way to force it to do something else in the turn?

**Comment by pvaiko** [comment]
> Are there any tips to setting these up? been doing a lot of potatoes, however It usually misses the first part of each run as it does a fish tail turn and doesn't turn in tight enough. Could it do a lightbulb like towed implements? is there a way to force it to do something else in the turn?

If you mean the 180 turn at the end of the row, you can try to enable turn on field but not leaving it enough room on the field, so do 1-2, maybe 3 headlands.

Also, it really should not miss anything, not sure if there's an issue about it (this issue is about the headland turn), if not you can create one with screenshots and log.
