### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Benni34** [Courseplay/Courseplay_FS22#2698]
Hallo wird es eigentlich eine Version geben die ohne Autodrive Funktioniert.Ich Blicke bis Heute da nicht richtig durch
Courseplay wahr für mich Angenehmer zu nutzen ohne Autodrive

**Comment by Tensuko** [comment]
Nein wird es nicht.
AutoDrive Tutorials angucken, so schwer ist es nicht.
