### ISSUE TITLE
[Question] Unload Combine - gives lua error

### ISSUE THREAD

**Issue by lazystudent3** [Courseplay/Courseplay_FS22#2699]
Good evening,

While playing on 'No mans land' map, I did encounter a problem. 
When I click start work for my worker to "Unload Combine", I get Lua error (screenshot) instantly. I tried it on multiple vehicles and trailers, outcome did not change. I also disabled every mod to check it, then I got another error, so My question is : 
Do I have to delete mods from game folder for it to count as testing it on clean game or simple disabling every mod but courseplay will do the trick?

I play on Courseplay 7.3.0.0 with multiple mods. I don't know what I am doing so before I post BUG or something like that, I wanted to ask question, maybe someone will slap me with answer like " Dude just do this " and boom, its solved.

First or second time posting so I hope i did not make a fool out of myself. 

![screen](https://github.com/Courseplay/Courseplay_FS22/assets/74244333/1f38418b-6f87-4cc9-ab45-1c1cf0aaa391)
[fs22log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12296701/fs22log.txt)

**Comment by Tensuko** [comment]
You may want to update AutoDrive.
https://github.com/Stephan-S/FS22_AutoDrive/releases

Beside that, I am not sure what this can cause this.
I haven't seen any mod in your log that messes arround with the covers.



@schwiti6190 you may have an idea?

**Comment by pvaiko** [comment]
What trailer is this? (next time filing a bug report make sure to include this information as requested in the template)

**Comment by lazystudent3** [comment]
> What trailer is this? (next time filing a bug report make sure to include this information as requested in the template)

I posted it into "Question" because I was not sure about it being BUG and I am trying to fix it in free time, by changing mods etc.
I didn't post a trailer and tractor model, simply because I tested it on different combinations of vehicles and trailers (modes, vanilla, moded + vanilla)

**Comment by rohne83** [comment]
> What trailer is this? (next time filing a bug report make sure to include this information as requested in the template)

That for sure is the HW80 by Aaa Modding, available on Modhub (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=229524&title=fs2022).

**Comment by pvaiko** [comment]
I'm sorry, I missed that part in your issue, we certainly don't have this problem with vanilla vehicles, I have not seen it on any map either, and that HW80 is a popular one so it is unlikely to be causing it.
