### ISSUE TITLE
Debug Settings

### ISSUE THREAD

**Issue by spatze90** [Courseplay/Courseplay_FS22#27]
Hello in the Courseplay version you can see the debug points when driving the course.
![fsScreen_2021_12_24_16_15_40](https://user-images.githubusercontent.com/70569464/147361832-06353d52-5faf-4601-ab22-59204481963b.png)

**Comment by Amarozo** [comment]
Yeah, i guess everyones got that (bug?). It's a little annoying, but not as much as ingame helper. Is there any solution in code to turn it off?

**Comment by spatze90** [comment]
yes exactly ^^ for screenshots it's annoying, but I think it will be fixed

**Comment by pvaiko** [comment]
should be fixed by 7.0.0.2
