### ISSUE TITLE
[Feature] Unload graincart with Autodrive

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#2702]
**What is the problem this feature/enhancement solves?**
I'd like the full graincarts to all run on the same tracks (simulating Controlled Traffic Farming). therefor I'd like the full graincarts to drive down an AD courseline in the middle of the currently combined set of lands and around the field to the unload point.

After unloading, I'd like to have them prepositioned on the middle of the current lands.

This would also solve another problem I have, wich is Courseplay not finding a way to the Motherbin or driving to a wrong trailer.

**Describe the solution you'd like**
Add an option to hand over a full graincart to Autodrive instead of searching a unloadpoint with Courseplay

**Describe alternatives you've considered**

**Additional context**
![Screenshot 2023-08-10 093155](https://github.com/Courseplay/Courseplay_FS22/assets/9157835/495ae27d-3ef7-4e44-a678-36c435448c82)

**Comment by Tensuko** [comment]
Sry but that wont happen.
You would have to use AD for everything then.
