### ISSUE TITLE
Zu viel Abstand beim ÜLW [BUG_SP]

### ISSUE THREAD

**Issue by Ostfriese76** [Courseplay/Courseplay_FS22#2704]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
Beim Arbeiten mit dem ÜLW für Kartoffeln ist der Abstand zum Abfahrer zu groß und daher findet kein überladen statt

**Expected behavior**

**Screenshots**
![fsScreen_2023_08_12_17_31_14](https://github.com/Courseplay/Courseplay_FS22/assets/76483134/900f3e22-f921-4fdb-82e1-9bb4ed4b6849)

**Courseplay version**
Version used: 7.3.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12327947/log.txt)

**Map**
Map played on. MF-Marsch ohne Gräben

**Vehicles/ implements involved**
Which vehicle or implement? ÜLW-Kartoffeln
Mod yes/no ?no

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive

**Comment by Tensuko** [comment]
Das Problem ist der rote Trailer. Der hat einen Fehler.
Mit einem anderen Trailer ist das kein Problem.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/a9af258d-4245-4d3e-aa10-76c0381eba35)

**Comment by Tensuko** [comment]
Noch ein weiteres Beispiel.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/07a85a8e-c19f-4a41-a7a5-40cff83880e4)

Kleine Anmerkung:
Dein ÜLW ist modifiziert!
Kapazität start erhöht.
Ist aber nicht der Grund, es ist der rote Trailer der den Fehler hat.

**Comment by Ostfriese76** [comment]
Danke für die freundliche und schnelle Hilfe. Der ÜLW wurde von HOT modifiziert und der Trailer stammt aus dem Grimme-Pack.

**Comment by Tensuko** [comment]
Ich weis mit dem grimme pack, aber leider schwer da was zu bewirken. Vlt kann ich mir das mal genauer angucken und dem modder sagen aber braucht halt zeit.
