### ISSUE TITLE
FS22_Courseplay Version: 7.3.0.1 Fehler in der Log

### ISSUE THREAD

**Issue by webwibo** [Courseplay/Courseplay_FS22#2706]
**Steps to reproduce**
Starte einen Spielstand mit Courseplay Version: 7.3.0.1
Keine weiteren Mods aktiv im Spiel.
**Actual behavior**
Fehlermeldung in der Log :
Error: D:/wibo/Dokumente/My Games/FarmingSimulator2022/pdlc/FS22_Courseplay/scripts/specializations/CpAIWorker.lua:548: attempt to index global 'CpAIBaleFinder' (a nil value)

**Expected behavior**
Keine Fehlermeldung in der Log

**Courseplay version**
Version used: 7.3.0.1 von heute
mit Version 7.3.0.0 tritt der Fehler nicht auf

**Map**
Department Haut Beyleron 4 fach DLC
meine Testmap (leere Map zu testen

**Relevant script mods**
Nur Courseplay aktiv beim Spielstart

**Comment by Tensuko** [comment]
Ist bereits gefixt, kommt dann mit dem nächsten Release.
