### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sanyahun1994** [Courseplay/Courseplay_FS22#2707]
jonapot töbjátékos mod hoz nem tudok csatlakozni a haverom hoz mert aszt irja nem sikerül csatlakozni a töb játékos mod hoz ojankor mia kell csinálni ?

**Comment by pvaiko** [comment]
> Can't connect to a multiplayer mod, it says "Could not connect to the multiplayer mod", what can I do now?

Mod? He probably means game?

**Comment by sanyahun1994** [comment]
igen vanak modok csak nem sikerül a haverom hoz belépni ösem tud hozám 99%
nál megálneki

Peter Vaiko ***@***.***> ezt írta (időpont: 2023. aug. 14.,
H, 20:52):

**Comment by Tensuko** [comment]
If your game is stuck at 99% loading, pls attach your logfile so we can see the error.

And if possible, pls write in english.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Need a logfile when report problems, can't help without.
