### ISSUE TITLE
[Question] Baumwollballen werden nicht mit cp Automatisch geladen

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/Courseplay_FS22#2708]
Ich habe heute eine Baumwoll mission gehabt. alles ganz normal wie bei Grasmissionen eingestellt und CP sagt: Das ziel befindet sich nicht auf dem Feld.

Ich habe alle möglichen stellen versucht. Aber er lädt die ballen nicht automatisch mit dem FS22_UniversalAutoload.

Es gab keine Fehler in der Log.

MFG Mannie313

**Comment by Tensuko** [comment]
Zielicon im Hud auf das Feld gesetzt?

**Comment by Mannie313** [comment]
ok werde ich beim nächsten mal machen. aber beim Silage oder Heuballen sammeln brauch ich das nicht machen. Autodrive fährt aufs feld und übergibt an CP und funktioniert.

**Comment by Tensuko** [comment]
Wenn es das erste mal ist und immer das gleiche Feld, dann ja!
Ansonsten wird der Feldmarker immer benötigt.
Das stand auch so in der changelog und sollte so auch in der Anleitung beschrieben sein.
