### ISSUE TITLE
[BUG_SP] Inital State in Combine Unloader creates a no path found condition

### ISSUE THREAD

**Issue by pops64** [Courseplay/Courseplay_FS22#2710]
When resuming a combine unloader on field unload that is above the trailer fill level it will create a no path found condition. The idle state is set first time this code is ran. Then the idle state will be set again while waiting on pathfinder. Logic downstream that checks to see if a path is found includes a state check which fails because it is looking for the waiting for pathfinder state. I put debug prompts in the code to determine this and it printed three times. Log https://pastebin.com/HnXGQ6dg. ```self:debug('I am setting idle")``` was placed before line 390

https://github.com/Courseplay/Courseplay_FS22/blob/b2574c51a371eafa630f8afe26df45172a60eecf/scripts/ai/AIDriveStrategyUnloadCombine.lua#L385-L391

**Comment by pvaiko** [comment]
Please follow the issue template, especially steps to reproduce, actual behavior and expected behavior.

**Comment by pops64** [comment]
See my pull. The code snippet will create multiple timers calling that function. Which will cause combine unloader to be reset to idle state if combine unloader change the idle state already.

**Comment by Tensuko** [comment]
Pls be more clear in your reproduction.
Start a Trailer with more then 85% fill level.
Then start the combine unloader?
What field job? Do I need a combine to run on the field?

**Comment by schwiti6190** [comment]
Based on your findings this solution would probably be better 
`lua
        if not self.startTimer then
            --- Only create one instance of the timer and wait until it finishes.
            self.startTimer = Timer.createOneshot(50, function ()
                --- Pipe measurement seems to be buggy with a few over loaders, like bergman RRW 500,
                --- so a small delay of 50 ms is inserted here before unfolding starts.
                self.vehicle:raiseAIEvent("onAIFieldWorkerStart", "onAIImplementStart")
                self.state = self.states.IDLE
                self.startTimer = nil
            end)
        end
        self:setMaxSpeed(0)`

**Comment by pops64** [comment]
Yes that would also work as that would prevent multiple timers from being created. Or using a CPtemporay object set for 100 ms
