### ISSUE TITLE
[Feature] Additional Plough Turn Path Option

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2715]
**What is the problem this feature/enhancement solves?**

When ploughing on angled work the turning path is not long enough to come back onto the next run straight, the plough lowers to early and not in line. 

**Describe the solution you'd like**
An option on trailed ploughs to make the turn path longer or some such so the path goes past the next run further and then turns and enters the path. The implement should be straight to the path before it enters the path and lowers.

**Describe alternatives you've considered**
Using a mounted plough but that doesn't really fix the issue.

**Additional context**

https://youtu.be/KQBNQ4fXevg 

![fsScreen_2023_08_19_14_43_15](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/53314387-337c-486d-992c-3696c132b90b)

![fsScreen_2023_08_19_14_43_40](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/70e6dd2a-5d3e-482f-8bff-b5ba241e419d)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12385977/log.txt)

**Comment by Tensuko** [comment]
Next Release will have improovement of the lowering, but the turn won't be increased.
