### ISSUE TITLE
[BUG_SP] Überlade Wagen fährt nicht ab wenn man denn Drescher Selber Fährt 

### ISSUE THREAD

**Issue by Flo3098** [Courseplay/Courseplay_FS22#2716]
Servus wollte das cp mich abfahrt mit ein überlade wagen und dann auf ein Anhänger am Rande des Feldes überlade  habe dann alles hergerichtet und habe dann cp auf das Feld Eingestellt und dann gestartet und dann habe ich angefangen zu Dreschen wie ich dann auf 80% wahr sollte cp los Fahren und mich abladen aber es machte nix  habe Helfer neu gestartet und machte wieder nix  

Bin dann von der ModHub Version 7.3.0.0 auf die GitHub Version 7.3.0.1 umgestiegen aber das gleiche macht nix 

habe dann mal in meine Loge Reingeschaut aber die war sauber nix mit Errors von cp her

**Comment by Tensuko** [comment]
CP Abfahrer können auch nicht Spieler gefahrene Drescher abtanken. Das wird es auch nicht geben. Das kann nur AD.
