### ISSUE TITLE
[BUG_SP] Problems with the BRIELMAIER and AEBI CC 66

### ISSUE THREAD

**Issue by tomy852** [Courseplay/Courseplay_FS22#2717]
**Steps to reproduce**
Use the BRIELMAIER or AEBI CC 66 and Mowing manually (no Courseplay course made)

**Actual behavior**
The Player dont hold it correct with Hands and when leave game still "inside" Vehicle the Game crashes

**Courseplay version**
Version used: v7.3.0.1

**Log**
Log and Screenshot attached

**Map**
Erlengrat

**Vehicles/ implements involved**
Which vehicle or implement? BRIELMAIER, AEBI CC 66 
no Mod 

**Relevant script mods**
none 

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12389102/log.txt)
![fsScreen_2023_08_20_21_52_05](https://github.com/Courseplay/Courseplay_FS22/assets/51209411/d4cb585c-421c-4ef8-8dbe-a10ba31133b4)
![fsScreen_2023_08_20_21_48_07](https://github.com/Courseplay/Courseplay_FS22/assets/51209411/9c5585cc-11bf-41c2-84dc-c35a9e412bd0)

**Comment by Tensuko** [comment]
We know, the animation was buged when drive them with CP, so we had to turn off the animation.
Need to have a closer look how we fix this. I know this also happens when player use them now.
