### ISSUE TITLE
[Feature] Slurry innovation

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/Courseplay_FS22#2719]
**What is the problem this feature/enhancement solves?**
would it be possible to add an option so that kits that need a continuous supply of slurry could load themselves at the edge of the field? a similar option as a combine harvester when unloading

**Describe the solution you'd like**
the set drives to the edge of the field where the tank is already waiting for it and can be loaded

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Tensuko** [comment]
Duplicate #2069
