### ISSUE TITLE
[Question] Workers wage issue

### ISSUE THREAD

**Issue by thorpey** [Courseplay/Courseplay_FS22#272]
Hello,

Not sure if this is a bug or just me not understanding it yet. Sorry.
I set the worker's wage to 0% but in some cases I still pay for the job. 
It happened to me in different jobs and with different tractor/machine.

I'm using version 7.0.0.10 but this issue happend with v7.0.0.7 too.

Am I wrong with the configuration?

Thanks

[edit]
This happend when i use my John Deere 7R 270 attached with a PowerRoll1230 HD but it not happened with my John Deere 7810 with the same PowerRoll.

**Comment by Tensuko** [comment]
Check the logfile if CP starts when you press H.
We think about change the keybind, but for now, use the Mini HUD to make sure CP is driving and not Giants Helper.
And yes, Giants Helper is also able to follow our Waypoints :)

**Comment by thorpey** [comment]
Thank you so much for the answer and the solution. 
When i used 7R the CP couldn't start with H button and that's why i paid. 
Starting the job with HUD solved the issue.

Maybe change the H button with something else would help. Anyway thank you again.
