### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SnakeManPMC** [Courseplay/Courseplay_FS22#2720]
Tried to help courseplay developers by providing easy steps to reproduce a bug with a savegame I created (took a while to get that almost mod free savegame done and bug report written), all I got as reply was disrespect towards PMC website. If a dev don't want to fix bugs and keep on advertising features that don't even work... fine, no more bug reports from me then.

**Comment by Tensuko** [comment]
Pls use our template (logfile missing, screenshot might help as well).
I removed that unknow link to farming-simulator . org -> what is that?! Not going to touch it!

You can upload logfile and savegame here on github just by drag and drop them, same for screenshots.

**Comment by Tensuko** [comment]
Logfile...
