### ISSUE TITLE
Weird Behaviour of Semi Trailers

### ISSUE THREAD

**Issue by chibchibi** [Courseplay/Courseplay_FS22#2721]
I have seen the behaviour on Field 10 on Elmcreek Map. I tried to farm Sugar beet with Sugar Beet Harvester (controlled by Couresplay) and MAN TGS 18.500 4x4 and Krampe SB II 30/1070 Trailer (controlled by Courseplay).
I only own Field 10 and no other Field in direct proximity.

The MAN TGS was set to unload the sugar Beet on the Field.  At First i tried a unload position directly south of the field. Next i tried a position near the north edge of the Field. 
The First Unload on the Field worked fine, but after that, the helper has Problems to find a path to the sugar beet. And if it finds a path. It does not reverses straight in front of the sugar beet heap (Because the helper drives not far enough to straighten truck and trailer).   

In general Coursplay seems to have a Problem to Control this Vehicle Combination (MAN TGS + Krampe SB II) or in General with Semi Trailers ?. If i use the exact same Helper Configuration for a JD Tractor with Brantner Z18051/2 XXL it has no Problems to reverse to the Sugar Beet Heap. 

Is there a general Problem with Semi Trailes ? Or are there any Gameplay Options that could effect this behaviour ?
I ll try to add additional Images as soon as i can start the Game next time.

I use Courseplay 7.3.0.0 installed via Ingame Modhub. (I also use Autodrive, but not in this case)

**Comment by Tensuko** [comment]
I have not tried that combination, I will have a look but won't have a high priority.
However, pls use our tamplate for a bugreport. 
Will close this Issue but keep that one in mind and have a look.
