### ISSUE TITLE
[Question] Mähdrescher Abfahrer Prozent

### ISSUE THREAD

**Issue by ole22143** [Courseplay/Courseplay_FS22#2724]
Wo kann ich einstellen ab wann der abfahrer zum Mähdrescher fährt?

**Comment by Tensuko** [comment]
Gar nicht, das ist ein von uns festgelegter wert der sich als bester Punkt rausgestellt hat.
Klar bei zu großen Feldern kann es nicht so gut klappen, dann heist es aber mehr Abfahrer und verteielter fahren lassen mit z.B. AD.
