### ISSUE TITLE
[Feature] Auto hide "Info Panel" when empty

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#2727]
**What is the problem this feature/enhancement solves?**

Would love to see the "Info Panel" automatically hiding when it's empty.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I know that you can turn it off in the settings, but i like to know if there is something going on with the CP helpers.

![image](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/2d9c7970-5267-4c2f-adff-4bbffcf06332)

**Comment by Tensuko** [comment]
Only with a 3rd setting "auto hide" as you then can't drag it arround when there is no msg.

Drag only arround with info msg is not a good solution.
