### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2729]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Field 18 the Oaks, 12m header and 3 headland passes with sharp corners.

**Actual behavior**
It can't handle the turning path for first headland on the corner show in the screenshot below. The path tries to reverse the combine outside of the field boundary and gets stuck.

**Expected behavior**
Create a path as normal like what happens on other corners

**Screenshots**
![fsScreen_2023_08_27_14_59_05](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/545aad01-b4fa-44be-9a4d-8109273180cd)
![fsScreen_2023_08_27_14_59_09](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/995dd64e-bf1c-4553-a58d-065ed42222b1)
![fsScreen_2023_08_27_14_59_20](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/45759c1d-2df8-45fa-9374-27612434faef)

**Courseplay version**
7.3.0.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12448139/log.txt)

**Map**
The Oaks

**Vehicles/ implements involved**
Ideal 8T & 12m Header

Mod yes/no ?

**Comment by Tensuko** [comment]
Physical limitation.
Object on the way - can't drive there.

Use teh course editor to adjust the course there or wait for the new course generator to have round corners on the 1st headleand and the rest sharp.

I wonder if you wait long enough he will rescure itself?

**Comment by coatsy35** [comment]
> Physical limitation. Object on the way - can't drive there.
> 
> Use the course editor to adjust the course there or wait for the new course generator to have round corners on the 1st headleand and the rest sharp.
> 
> I wonder if you wait long enough he will rescure itself?

No amount of waiting will fix it unfortunately. Sorry my mistake, I assumed the path would not let it go outside the field boundary. Not see that happen before on a corner.

**Comment by Tensuko** [comment]
Does it write being blocked when performing the turn?

**Comment by coatsy35** [comment]
> Does it write being blocked when performing the turn?

Just watched my video back and yes it does flash up blocked by an object briefly, which would be the tree. Please close this thread. Sorry my mistake.
