### ISSUE TITLE
Random Question for Translating

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#273]
This might be more of a GitHub issues, but is there a way to auto translate the post in issues so I don't accidently create an issues that is already created because I don't know when some of the issues are in what appears to be German? or other languages.

**Comment by Tensuko** [comment]
You can use browser extensions. But for github I dont know.
But yea ti is better if issues are in english ofc.
If there is an existing issue in german, and you create the same thats totaly okay. Sometimes I keep the new one and close the old tp keep the english one.
Hope that helps.

**Comment by Resandise** [comment]
Thanks
