### ISSUE TITLE
[Question] IS the dual wheels causing this?

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2730]
I have a contract which supplies a dual wheel 7310R. However most of the time it won't unload from the combine. If I stop courseplay it will unload. I'm thinking it's due to proximity with dual wheels? Don't have the issue with other combines working with single wheeled tractors. 

![fsScreen_2023_08_27_15_54_53](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/22c9c4e0-d2cb-4934-b6d1-3454237f1525)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12448254/log.txt)

**Comment by Tensuko** [comment]
Give it some more offset to the side, should be the proximity sensor. Its looks very close to me.

**Comment by coatsy35** [comment]
> Give it some more offset to the side, should be the proximity sensor. Its looks very close to me.

Thank you. Just having a bad day today, didn't even think of that.
