### ISSUE TITLE
[Question] Fliegl ASW271 Trailer Won't Perform Combin unload

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2731]
I have a contract with a JCB Fastrac 4220 & Fliegl ASW271 trailer both from Giants. However I cannot create a combine unloading job for it? how do I fix this? is there something I'm missing?

![fsScreen_2023_08_27_17_42_33](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/e1ea9d0e-09e2-482c-9665-419a5e58f2db)

**Comment by Tensuko** [comment]
Thats due to its configuration of a manure spreader, that spec is active even its not configured.
Yeah its stupid but thats how Giants does it.... Can't switch the mod by toggle the start position?

**Comment by coatsy35** [comment]
How do you mean toggle the start position? I’m not sure what you mean

**Comment by Tensuko** [comment]
"nearest waypoint" on the HUD.

**Comment by Tensuko** [comment]
Actually, when I buy that trailer....
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/82f5bb26-aa54-43c8-beb0-7a75d9151ccc)
Just fine with combine unload.

**Comment by Tensuko** [comment]
With manure spreader I get the field work option.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/36321028-e4d0-42f3-802c-84e03f28935b)

And after change back again the combine unload.

**Comment by coatsy35** [comment]
Hmmm. I’ll try later when I’m near my PC. Not sure what’s causing it to not work. Have seen it with other trailers occasionally. Like the tandem Giants trailers, can’t recall the name, the ones that are green and 4 wheel which you two behind each other often giving in contracts. When they are together it won’t work. I’ll have to investigate further

**Comment by Tensuko** [comment]
That trailer where you connect 2 parts is intended as it is the same like having 2 trailers wich is not supported!

**Comment by coatsy35** [comment]
Ah ok. I hadn’t realised that. When I get a contract like that I use AD for the combine as it handles two trailers fine.

**Comment by coatsy35** [comment]
> Actually, when I buy that trailer.... ![grafik](https://user-images.githubusercontent.com/27344744/263549865-82f5bb26-aa54-43c8-beb0-7a75d9151ccc.png) Just fine with combine unload.

Weirdly I've just come back to my game and opened the save and the trailer now has combine unload ability. Must remember that for the future, exiting and reloading seems to have fixed it. Thanks for the pointers
