### ISSUE TITLE
[Question]Traubenernte, Stop bei Reihenende?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2733]
Hallo Leute
ich habe mir ein Trauben Feld angelegt, wo der Braud Ernter pro Reihe ca 45% des Tanks anfüllt.
d.h. nach zwei Reihen hat er ca 90% seines Bunkers voll.
nun beginnt er die dritte Reihe und bleibt nach einiger Zeit mitten im Weinberg stehen, da sein Bunker voll ist.
somit muss man da rückwärts aus der Reihe fädeln zum abkippen.
wäre es möglich, eine Abfrage bei Reihenende einzubauen ob im Bunker des Ernters genug Platz für die nächste Reihe ist ?
wenn ja, Wendung und noch eine Reihe ernten, wenn nein Stop und warten.
oder könnte man eine maximale Bunkerfüllmenge (in Prozent) einstellen, damit der Ernter nach Reihenende wartet wenn diese überschritten wurde?
(wenn möglich, auch für Oliven bitte)
lg
andreas

**Comment by Tensuko** [comment]
Das abtanken vom Ernter usw wird sowieso noch mal angepackt, aber denke nicht vor dem rework des Kursgenerators.
Stelle mir da auch einen check vor, aber muss man sehen. Eine einstellbare Füllmenge wird es aber nicht geben.
