### ISSUE TITLE
[BUG_SP] Horizontal trailer correction

### ISSUE THREAD

**Issue by Kuro-Lai** [Courseplay/Courseplay_FS22#2734]
Hello,
it seams the horizontal trailer correction is not working correkt.
The automatic correction(when you attach the trailor) create the right value that the square is under the tool working space.
I have always to set the correction by hand to a value that the trailerworkspace is outside of the actual path and tool and the tractor path is on the line. Shown in the screenshot.

![20230829170135_1](https://github.com/Courseplay/Courseplay_FS22/assets/59888091/813c1e4f-da08-4090-8786-83db5bea7157)

**Comment by Tensuko** [comment]
Bitte in zukunft das Template ausfüllen!

Du hast als selber den Offset eingestellt weil der automatische falsch ist?
