### ISSUE TITLE
No waymarkers shown

### ISSUE THREAD

**Issue by Miesii03** [Courseplay/Courseplay_FS22#2735]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Just started to game and every course does not show waymarkers

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**
loading or creating a course shows the markers on the minimap, but not in the world. 

**Screenshots**
Screenshot has been added below

**Courseplay version**
Version used: 7.3.0.0 and 7.2.0.5.

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
<script src="https://gist.github.com/Miesii03/48bb1a2d97095f117af9ef9ec7e42f38.js"></script>

**Map**
Map played on.
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement? Every Vehicle and Machinery
Mod yes/no ? No Mod

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive installed, but not used. Worked fine before, never used Autodrive, just installed it ages ago.

![Farming Simulator 22 Screenshot 2023 08 29 - 20 30 40 08](https://github.com/Courseplay/Courseplay_FS22/assets/49359414/327d2818-ed0c-43cb-b7d2-e5c604407176)

![Farming Simulator 22 Screenshot 2023 08 29 - 20 52 28 46](https://github.com/Courseplay/Courseplay_FS22/assets/49359414/8b19d7bd-f928-4f32-8d67-41311855c084)

**Comment by Tensuko** [comment]
Your logfile isn't attached correctly. Can you pls reupload it?

**Comment by Miesii03** [comment]
https://gist.github.com/Miesii03/78be882c2aef60becd4fdbd3311bbcf3
This is the Log of the main Game from /Documents/My Games/FarmingSimulator2022.

**Comment by Tensuko** [comment]
Well, all I can tell you is that it doesnt come from cp (more ppl would have this problem) but you got a lot of experimental mods in your mods folder, many many warning, callstack and an error. You should clean up your mods folder.

May consider also renew your shader chace by deleting the files in that folder.

**Comment by Miesii03** [comment]
I have now tried to start a game with only cp installed and it still didnt show me the wayponits. I even uninstalled it and downlaoded it again through the Modhub.

**Comment by Tensuko** [comment]
Did you try to delete wahts inside "..\My Games\FarmingSimulator2022\shader_cache" ?
You game will lag for a while due to rebuild the shader, but it cam be worth it.

**Comment by Miesii03** [comment]
yes, that fixed it, thank you!
