### ISSUE TITLE
[BUG_SP]Error Message. AI worker B not readt to Drive. Topliner not in Transort Mode

### ISSUE THREAD

**Issue by Evadtheawesome** [Courseplay/Courseplay_FS22#274]
**Steps to reproduce**
I set a new course and got to the start job command and the harvester folded and error message appeared. 
Same happened 5 times including 
a. Turn of autodrive. (It turned back on autonimously)
b. Made 3 different courses.

**Actual behavior**
I produced a course using usual method but when I hit start job the harvester folded and the error message was returned.

**Expected behavior**
I expected the harvester to move to first waypoint and commence harvest.

**Screenshots**

**Courseplay version**
Version used:  7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elem Creek.

**Vehicles/ implements involved**
Mod /no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7795524/log.txt)

I am sorry If this is my error but I have spent some time trying to understand the error messages. I have been a longtime usere is FS19 and love your work.

**Comment by Tensuko** [comment]
Giants foes drive to the target only in transport mode . This is not a CP Issue.
But I keep an eye on it when it happens and we will get in contact with Giants.
To start CP you can use Hbor the mini Hud.
For combine, I would drive by myself due to the header.
