### ISSUE TITLE
[Question] How to fix/stop missing island bypass paths

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2741]
On larger fields with pylons I often have missing island bypass paths. Is there way to easily fix these? or it is something wrong with the item in the map that causes them to not be recognised?

![fsScreen_2023_08_31_22_34_15](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/9f0ae5b4-bfea-4437-b7d6-35c0d31f89c9)

![fsScreen_2023_08_31_21_28_57](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/70dd3fe2-603b-4f2c-a4f9-da08eb820ef4)

**Comment by Tensuko** [comment]
use the paint tool and make them a little bigger

**Comment by coatsy35** [comment]
Perfect. Didn't know it detected them on size of greenery. Thanks
