### ISSUE TITLE
[Question] "No path found"  in bale collecting

### ISSUE THREAD

**Issue by Orsa1305** [Courseplay/Courseplay_FS22#2744]
Not sure if i do something wrong, hence the question :)

sometimes i get this error when collecting bales right from the start, other times it is after it collected a few bales.
did i mis a setting?
version 7.3.0.2

**Comment by Tensuko** [comment]
The reason could be that the bale it tries to collect have an angle where it lies not parrallel to your tractor + the offset of your tractor + wagon is too narrow.
That means the pathfinder will have a traffic conflict.
What can help is if you increase the offset in the hud.
This depends on the tractor and the tool.
The wider the combination is, the more it can happen.

I hope you can follow me :)

**Comment by Orsa1305** [comment]
I will try, thanks

**Comment by InsaneCamel25** [comment]
I had that Same Problem with the Roundbalecollektor. The Standard Offset was 1,6m. After i changed the offset to 2.6-2.7 the Problem was solved.

**Comment by Orsa1305** [comment]
i can confirm that changing the offset worked.
thanks to both of you.

**Comment by Orsa1305** [comment]
wat trying to close the ticket but failed.
