### ISSUE TITLE
Probleme mit Ziehbaren maschinen beim vorgewende (Tools zu lang, Gespann fährt nicht weit genug vor) 

### ISSUE THREAD

**Issue by Goofy78** [Courseplay/Courseplay_FS22#275]
Das Problem besteht weiterhin. Zumindest bei mir. Auch mit der v7.0.0.10
![fsScreen_2021_12_31_09_05_47](https://user-images.githubusercontent.com/96694308/147811403-f2579013-0e9b-42a1-b40e-0aaf92ffc1af.png)

![fsScreen_2021_12_31_09_06_04](https://user-images.githubusercontent.com/96694308/147811413-74e39985-c917-4df3-bb7c-dec2b4b75a0b.png)

**Comment by RealNeo80** [comment]
hängt denke ich hier mit dran #267 mal abwarten biss der Wendekreis implementiert ist

**Comment by jacquesbrele** [comment]
Have the same problem with the Amazone Seeder (15m). He can't make the turn and get stuck in the seeder 😅

**Comment by pvaiko** [comment]
A log would have been great (with Debug in vehicle settings activated), so I can see the implement/turn parameters.

**Comment by Goofy78** [comment]
Sorry... 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796597/log.txt)

**Comment by Clouseau219** [comment]
Habe mit der Amazon Citan das gleiche Problem:

![LITTLEBIGIV-2021-12-31 17_17_21-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/147832221-381feaa5-b017-4e32-a193-4113e3bb7590.png)
[211231_01_log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796623/211231_01_log.txt)

Video dazu: [https://youtu.be/mKkGaQGMO6U](https://youtu.be/mKkGaQGMO6U)

**Comment by Goofy78** [comment]
**Naja.-.. wie soll ich es sagen, es ist mit der v7.0.0.11 auch nicht anders.**

![fsScreen_2022_01_02_12_35_23](https://user-images.githubusercontent.com/96694308/147874538-89dfe669-519b-4fa9-84c2-ca9e92843b73.png)

![fsScreen_2022_01_02_12_34_53](https://user-images.githubusercontent.com/96694308/147874534-04057ae6-2b3b-4de8-a31d-6b071ae44a28.png)

![fsScreen_2022_01_02_12_35_02](https://user-images.githubusercontent.com/96694308/147874537-278b7bfa-e10a-4d6e-b471-be1f1c6e8905.png)


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798982/log.txt)

**Comment by Tensuko** [comment]
Wie gesagt, reopen Issue.

**Comment by Tensuko** [comment]
Mein Fehler...
VehicleConfiguration.xml
Zeile 136
`<Vehicle name="koralin9840"` -> `<Vehicle name="koralin9840.xml"`

Hab beim kopieren das .xml nicht mitgenommen...
Dann funktioniert es auch.... sry ist mit der nächsten Version definitiv gefixt (eben selber probiert).

**Comment by Goofy78** [comment]
Das hatte ich selber schon korrigiert, hat aber nichts gebracht.

**Comment by Playlord75** [comment]
Hey hab mir grade die 7.0.0.11 runtergeladen und das Problem ist leider immer noch da
![fsScreen_2022_01_03_01_15_14](https://user-images.githubusercontent.com/71101944/147893021-4c146883-cfba-4276-9f0d-19d3e1883c6b.png)

**Comment by pvaiko** [comment]
Duplicate of #303

**Comment by pvaiko** [comment]
The Koralin should work with the vehicle configuration. As long as you see steering length 0 in the log, it won't work, and setting `implementWheelAlwaysOnGround` in the vehicle config XML will fix that.
`2022-01-02 12:34 :49 [dbg13 lp5368] 7R 350: (HeadlandTurn): r=6.4, w=8.4, steeringLength=0.0`

**Comment by Goofy78** [comment]
This is with the new version v7.0.0.11 fixed

The same also with the fixed version.


2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: (HeadlandTurn): Start generating
**2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: (HeadlandTurn): r=6.4, w=8.4, steeringLength=0.0**
2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: start angle: 89.9, end angle: 1.6 (from 3.1 and 0.0)
2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: Corner: start: 89.9 end: 1.6 alpha: -91.6 dir: -1
2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: Corner: startAngle: -90.1, endAngle 1.6 avg 135.7
2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: Corner: 856.6 -449.8, startAngle: 89.9, endAngle 1.6
2022-01-03 05:25 :52 [dbg13 lp6740] 7R 350: Corner: r=6.4 d=6.2

**Comment by pvaiko** [comment]
State on main branch with the Koralin:
`2022-01-03 10:00 :07 [dbg13 lp511444] T6.125: (HeadlandTurn): r=6.4, w=8.4, steeringLength=7.3`

**Comment by Goofy78** [comment]
Keine Ahnung was falsch läuft, ich komme immer aufs selbe Ergebnis

2022-01-03 19:04 :36 [dbg13 lp5508] 7R 350: (HeadlandTurn): r=6.4, w=8.4, steeringLength=0.0

**Comment by Goofy78** [comment]
Ich habe den Übertäter gefunden. Es lag an AIVE... Ohne AIVE läuft es. 

**2022-01-03 21:04 :05 [dbg13 lp4328] 7R 350: (HeadlandTurn): r=6.4, w=8.4, steeringLength=7.6**

Danke für die Hilfe :-)
