### ISSUE TITLE
[BUG_SP] Potato Harvester Row End Turn Path

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2751]
As requested by @pvaiko I'll try and get better pics later, had to to snip screenshots as my screenshot button not working on the screen I access my computer by.

**Steps to reproduce**
Giants Ventor 4150 Potato Harvester, 12 headland rows. Field 3 the Oaks. Harvester set to lower early and lift late.

**Actual behavior**
Harvester does a very tight fishtale turn at the end of a row and often misses fruit and strays off the crop

**Expected behavior**
Turn clearly to realign itself with the run and not miss any fruit

**Screenshots**
![Screenshot 2023-09-05 122748](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/b720da39-ae71-489c-8536-b1be37c00be1)
![Screenshot 2023-09-05 123347](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ee4d3281-e404-4b23-a1be-520ec54724c5)

**Courseplay version**
Version used: 7.0.3.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12522941/log.txt)

**Map**
The Oaks

**Vehicles/ implements involved**
Which vehicle or implement?
Giants Ventor 4150 Potato Harvester

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by coatsy35** [comment]
Possibly better screenshots and log!

![Screenshot 2023-09-05 123736](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/031f3cd2-1cfb-4a43-9235-48eddbaf0423)
![Screenshot 2023-09-05 123747](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/111388c1-6a74-4826-b0bf-99a0fd641e8e)
![Screenshot 2023-09-05 123758](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ec4a1e0a-c899-4fb8-918c-b1c8663fe3cd)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12522994/log.txt)

**Comment by coatsy35** [comment]
Also does some weird things when making a pocket, although I imagine there is not really a potato harvester pocket.

**Comment by coatsy35** [comment]
Got chance to get some better video and screenshots for you plus log.

Video of missing start
https://youtu.be/LuvhyOecs6M

![fsScreen_2023_09_05_21_36_35](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/828b63ec-5f14-4cd8-9ac7-5bdad5f9a143)

Good video of pocket gone wrong
https://youtu.be/_krlHeWK0zg

![fsScreen_2023_09_05_21_42_39](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/8343e731-c6f7-4231-902b-1237adc1a392)


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12528202/log.txt)

**Comment by Tensuko** [comment]
I wonder how it behaves with turn on field off and disallow pathfinder to drive in reverse.
Just to see what it does when no reverse driving is involved.

**Comment by coatsy35** [comment]
I will try when I next have time to test with root crops, they are my least favourite due to how slow they are!
