### ISSUE TITLE
[Question] Vehicle Offset Horizonal Value Not saving between sessions

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2752]
Is this a bug or am I missing something? I have a few vehicles where every time I reload my save game I have to change the horizontal value back as they are not saving. Vertical values are saving however. Not a big issue, just something I keep doing and forget to ask about.

**Comment by Tensuko** [comment]
Duplicate Issue #1548
We have this in mind.

**Comment by Tritura2** [comment]
It isn’t fixed, but there is an other issue open already mentioning this problem (in German). So as Tensuko told you, they 
> have this in mind.

**Comment by coatsy35** [comment]
> It isn’t fixed, but there is an other issue open already mentioning this problem (in German). So as Tensuko told you, they
> 
> > have this in mind.

Ok. I thought that's what the update was referring too. It's not a big issue so I can wait :D
