### ISSUE TITLE
[Feature] unofficial Chopper support (by former FS17 CP Developer pops64)

### ISSUE THREAD

**Issue by pops64** [Courseplay/Courseplay_FS22#2754]
I would love to see chopper support in CP. If I have enough interest I can continue development of my fork

You can find it here https://github.com/pops64/Courseplay_FS22/releases/latest It is now separated from official CP so ensure official CP is disabled as there is no safety check currently programed in and unknown things may happen if both are enabled

**Comment by zinni97** [comment]
I would be very interested as I have already been testing the fork before. I think it was a hige improvement over AD handling it chopper unloading. Bummer that it won't make it into the official version but either way I'd definitely be on board and use it!

**Comment by lcc1211** [comment]
I'd like this as well. I don't use AD for this as it is just easier for me to drive the tractor following along behind.

**Comment by regs1980** [comment]
Actually, you can close this.
They don't even manage to fix the existing bugs and already want to integrate new features.
This was a nice try but it will never work properly.
