### ISSUE TITLE
interaction with moving tool for fieldwork

### ISSUE THREAD

**Issue by m4ttyofficial** [Courseplay/Courseplay_FS22#2756]
**Steps to reproduce**
use a specific implement

**Actual behavior**
so there is this mod of a plow that can work both in the furrow and on land, you can switch between modes with a moving tool AXIS_FRONTLOADER_ARM however once you turn on the course play it switches automatically to the on land mode whatever thing you do this doesn't happen with the ermo plow mod that you can find on modhub that has this different modes however that plow you can change between them with ctrl + y. course play can feel that the plow has changed mode but it automatically switches to the on land mode (last screenshot). edit just found out: when you start the work with the in furrow mode (it automatically switch back to the other mode)  then you save and quit and re open the game it will be in the correct mode 

**Expected behavior**
it should keep the selected work mode
**Screenshots**
![immagine](https://github.com/Courseplay/Courseplay_FS22/assets/144387925/c79a1767-9509-47f8-a35e-e79a2566c851)
![immagine](https://github.com/Courseplay/Courseplay_FS22/assets/144387925/657e0c2f-b373-463f-9fc4-a42f49f76c29)
![immagine](https://github.com/Courseplay/Courseplay_FS22/assets/144387925/80f5e250-067f-4806-8072-3b984bc14451)
![immagine](https://github.com/Courseplay/Courseplay_FS22/assets/144387925/64846f92-5d63-4a9f-8201-4bae400ccf4b)

**Courseplay version**
Version used: latest on mod hub  7.3.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12553669/log.txt)

**Map**

every map

**Vehicles/ implements involved**
plow
Mod yes

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Well, this is not a bug.
It is normaly not intended to have tools move to a spot (that would need spezial handling per tool).
From where is that tool and do you know other mods that work like that one?

**Comment by pvaiko** [comment]
And, does it work correctly with the Giants helper?

**Comment by m4ttyofficial** [comment]
> Well, this is not a bug. It is normaly not intended to have tools move to a spot (that would need spezial handling per tool). From where is that tool and do you know other mods that work like that one?

it's a conversion from fs 2019 it didn't have this problem with course play in fs 19 tho

**Comment by m4ttyofficial** [comment]
> And, does it work correctly with the Giants helper?

yes with the giants helper the plow remains in the selected mode

**Comment by Tensuko** [comment]
Is it on modhub?

**Comment by m4ttyofficial** [comment]
> Is it on modhub?

no it's private it wasn't on the modhub in fs 19 too but it's made by a good modder

**Comment by m4ttyofficial** [comment]
> Well, this is not a bug. It is normaly not intended to have tools move to a spot (that would need spezial handling per tool). From where is that tool and do you know other mods that work like that one?

similar mods is the rabe plow from the modhub and the ermo from the mod hub although that works with ctrl + y to change mode

**Comment by Tensuko** [comment]
Then I would suggest you to change that mod that it works with ctrl + y too.

**Comment by Tensuko** [comment]
We discussed about this internaly.
We do not want to do changes on the code logic to support this pirvate tool especialy if other options do exist, as you mentioned :)
So pls understand that for one private tool we can't put effort in code changes and testing.

**Comment by m4ttyofficial** [comment]
> Then I would suggest you to change that mod that it works with ctrl + y too.

i tried i asked around how know one seems to know how to do it

**Comment by m4ttyofficial** [comment]
> We discussed about this internaly. We do not want to do changes on the code logic to support this pirvate tool especialy if other options do exist, as you mentioned :) So pls understand that for one private tool we can't put effort in code changes and testing.

ok but this problem wasn't a thing in fs 19 with courseplay
