### ISSUE TITLE
[Question] Could combine corners be applied to beet harvesters?

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2759]
Just been harvesting some beet and noticed the Giants Ropa harvester does not use the corner function that combines use, so you end up with fruit left in the corner and often blocked by object warnings as they can't back back far enough.

![fsScreen_2023_09_09_16_08_12](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/07dd76ba-48dc-4212-81da-131a25755cdb)

**Comment by Tensuko** [comment]
#2696
