### ISSUE TITLE
[Feature] Kursgenerator Einstellungen mit Mausrad ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#276]
**What is the problem this feature/enhancement solves?**
die Kursgenerator Einstellungen nur mit dem draufklicken auf die Schaltflächen dauert lange (z.b. die arbeitsbreite)

**Describe the solution you'd like**
es wäre schön und intuitiver (mMn), wenn man in den Kursgenerator einstellungen die Werte auch mit dem Mausrad verstellen könnte, nicht nur mit dem draufklicken auf die Schaltflächen

lg
andreas

**Comment by Tensuko** [comment]
Arbeitsbreite versuchen wir noch für alle Geräte hin zu kriegen, da muss sich was geändert haben....
Mut dem Mausrad ja gucken wir uns an.

**Comment by RealNeo80** [comment]
in dem Zuge vielleicht auch gleich direkt eintragbar machen draufklicken, zahl eingeben, Enter drücken fertig

**Comment by freiser77** [comment]
@andreasthu , @Tensuko : Ich würde mir auch wünschen, die numerischen Werte direkt eingeben zu können. Z.B. 12.0 bei Arbeitsbreite :) Hier nervt das Klicken besonders, weil ich 120x klicken muss.

**Comment by Tensuko** [comment]
Werte direkt eintragen kommt, aber Mausrad ist leider nicht möglich.
Daher machen wir hier zu.
