### ISSUE TITLE
[Feature] Height control for sprayers

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#2760]
**What is the problem this feature/enhancement solves?**
Sprayers are to low and hitting crops

**Describe the solution you'd like**
Automatic height adjustment, so sprayers dont touch the crops

**Additional context**
(yes, screeshot is a bit older)
![20230713151856_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/cd540603-72bc-49b8-88fb-262777b8b0cd)

**Comment by Tensuko** [comment]
Does Giants  Helper control the hight of sprayers?

**Comment by polosubtil** [comment]
Yes, it does, pressing H to use the Giant helper will set the boom at the same height every time, even if you manually raise/lower it before hiring it.

**Comment by schwiti6190** [comment]
The sprayer is from the precision farming mod?
If yes than I can't reproduce different behaviour between giants helper and CP regardless of what the desired outcome is.
Both switch the target height to the same position on start instantly, but the animation for that seems kinda buggy on giants part.

**Comment by blubstar86** [comment]
Yes its the one in the Precision Farming DLC.

But no, Giants helper cant handle the height too.

As you mentioned they get back to start height right after when you hire a helper (Giants or CP) with the glitchy animation.

Ofc the this feature would have only a visual effect.

**Comment by schwiti6190** [comment]
As a conclusion I would suggest you could report the bug to giants, as this a problem with the model and not really a problem related to courseplay
