### ISSUE TITLE
[BUG_SP] Plough Won't Start Path

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2761]
Bit of feedback. On this path with crawler and the KV PW100 plough it got stuck and wouldn't start the path. Not sure why. Log below and pics. Sorry not a full bug report post, need to go sleep

![fsScreen_2023_09_10_22_50_49](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/12b367c2-5314-406c-88ee-9a2993ba2b1a)
![fsScreen_2023_09_10_22_51_14](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/86dbd489-018f-4cde-bea4-1545612aa802)
![fsScreen_2023_09_10_22_51_32](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ce686503-8e59-42ca-866b-e86bc460b7a3)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12570729/log.txt)

**Comment by coatsy35** [comment]
I just loaded in a saved game and tested it last night. I have no custom plough configurations so it's using the CP default settings. I assume it will use the new turn radius when I create a new course - this field was in the middle of being ploughed. I'll test further. I love the new updates to ploughs, just seamed odd when this one stopped and refused to do anything until I forced it on

**Comment by pvaiko** [comment]
> I have no custom plough configurations so it's using the CP default settings. 

The log says you do, this is the standard config, setting the Titan 18 radius to 7.5 m:

2023-09-10 20:31 :48 [info lp3053] Loading vehicle configuration from C:/Users/Dan/OneDrive/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/config/VehicleConfigurations.xml ...

... and then comes this:

2023-09-10 20:31 :48 [info lp3053] Loading vehicle configuration from C:/Users/Dan/OneDrive/Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml ...

setting it to 9 m, for instance, it is all in the logs...

**Comment by pvaiko** [comment]
Oh, and BTW, that 14 m radius may be coming from your second, custom vehicle config file:

```
2023-09-10 20:31 :48 [info lp3053] Reading configuration for pw10012.xml
2023-09-10 20:31 :48 [info lp3053] \__ raiseLate = true
2023-09-10 20:31 :48 [info lp3053] \__ noReverse = true
2023-09-10 20:31 :48 [info lp3053] \__ implementWheelAlwaysOnGround = true
2023-09-10 20:31 :48 [info lp3053] \__ turnRadius = 14.0
2023-09-10 20:31 :48 [info lp3053] \__ lowerEarly = true
```

**Comment by coatsy35** [comment]
Weird. I've never sett any custom settings or altered them files. I'll clear them all out and start a fresh. Thank you.

**Comment by pvaiko** [comment]
If you don't want any custom settings, just delete the one under modSettings.

**Comment by coatsy35** [comment]
I've now done that. Just reloaded by save and it's using the new turning circle on the PW100 c/w Crawler tractor. However the ends or now not as neat as they were. Try ploughing a field with any twin track tractor and the Giants KV PW100, it's like it pulls too far wards the work before it pulls straight, meaning the ends of the run lean towards the last worked ground. 


![fsScreen_2023_09_11_18_26_27 - Copy](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/29595b11-2beb-4c38-979d-157c22634a96)

![fsScreen_2023_09_11_18_26_55](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/995437d1-61c8-4f3c-85f8-140e55d1b4ec)


[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12578888/log.txt)

**Comment by pvaiko** [comment]
Do you have the raise late/lower early set?

**Comment by coatsy35** [comment]
> Do you have the raise late/lower early set?

It is set on raise late, lower early. I have not altered this setting between updates. I didn't want to adjust anything. Unfortunately the contract has just moved onto the headlands now so I can't test. but I'll try a test map with different settings if you advise I should change them

**Comment by pvaiko** [comment]
No, no need, but if you have a screenshot with the headlands to see what really is missed, that's great.

**Comment by Tensuko** [comment]
Those small gabs come up when the tools is not 100% aligned.
But also when the work width is rly tight, sometimes 0,1 less work width can help there.
Thats just the hard lines of how giants does the work on the grid.
Not sure how much we can increase here.

**Comment by pvaiko** [comment]
I think that's because of our tight turn offset if I understand correctly what @coatsy35 says, but not sure. We can dial back on that one, or make the lead into the row a little longer.

**Comment by coatsy35** [comment]
Making the lead slightly longer would help I think, plus slightly less offset, giving a little more time to get on course. I assume there is not a setting I can adjust to try that anywhere and it's a calculation? the longer the implement like this plough or the huge Besson plough the worse this would be I imagine. Will try with largest plough mod when I get a min.

Filmed the same field on a test map for you. Does this help? Might need a min for youtube to encode to HD

https://youtu.be/HGeCAu0yos4

**Comment by coatsy35** [comment]
Biggest plough does the same. drawbar is not straight to the path line when it pulls into work. Just needs a tweak I think and it''ll be perfect.

![fsScreen_2023_09_11_20_39_25](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/4731585e-1900-4137-a1f5-4d4a52917988)


![fsScreen_2023_09_11_20_41_16](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/71847dc5-c3b4-4976-a50f-c1c5455ae046)

**Comment by coatsy35** [comment]
There are still issues going on with this it appears. I haven't ploughed since the posts above, but I've just captured this ploughing a good sized field. The turning into work on an angled headland is a mess and even on the straight ends it looks messy as it's now not straight and on the ins (The outs are nice and straight), It used to create nice straight ins and outs on straight headlands. The turning circle still is not right I feel, the leads need to be way longer when the headland is angled in my mind at least twice the length it is now if it's possible to have the different on an angle trajectory?

**Comment by pvaiko** [comment]
Not sure what you mean by messy but as long as we don't miss anything (after the headlands are done) and don't lower the plow way too early I'm fine.

**Comment by Tensuko** [comment]
Looks perfect to me, like my fields too.

**Comment by coatsy35** [comment]
> Not sure what you mean by messy but as long as we don't miss anything (after the headlands are done) and don't lower the plow way too early I'm fine.

OK. I have my ploug hset to Late/Late as usual. There are tiny triangles left which it didn't use the leave , hence my post but if that's how it is now, that's fine. I just didn't know if you would consider it a problem or not. Hard to see in all the pics below but it they are there, I've highlighted some of them

![fsScreen_2023_10_31_15_41_34](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ca95fa47-44b6-4b2a-bd18-d19768b545aa)

![fsScreen_2023_10_31_15_39_14](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/9cd7ffe2-473c-47ac-a34c-dfbfd9394da9)

![fsScreen_2023_10_31_15_34_46](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/1c5a3453-4862-49cf-b8f2-0ccc075a5fc2)

**Comment by Tensuko** [comment]
Raise late and lower early!
Late/late wont do it!

**Comment by coatsy35** [comment]
> Raise late and lower early! Late/late wont do it!

Yes it was on that, I don't know why I wrote it down wrong! Any more to add to this, using the Giants KV PW100 tonight, I logged and screenshotted this. Something is amiss somewhere and I can't figure it out. 

![fsScreen_2023_11_05_19_08_05](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/a1eb2acd-1101-4840-8542-8a393ab22f3a)
![fsScreen_2023_11_05_19_08_22](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/a857fd2f-1fdc-4809-99eb-977b6b25715c)
![fsScreen_2023_11_05_19_08_44](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/35b82578-73d6-49ed-83e9-02bd51b5f967)
![fsScreen_2023_11_05_19_08_50](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/908f1363-9241-4b3a-b89f-b6b5113f4e57)
![fsScreen_2023_11_05_19_08_53](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/77d94fee-5933-4861-8462-be15b0f6ca0d)
![fsScreen_2023_11_05_19_09_00](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/1949f95b-a2a5-42ba-9d10-2e674527bbf3)
![fsScreen_2023_11_05_19_09_11](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/3cca72b3-fd2d-4cf9-a448-f39c4d63329e)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13260573/log.txt)

**Comment by coatsy35** [comment]
Just confirmed, this is a wheel tractor only issue I believe. Twin track and Quadtrac plough perfectly, so I assume fixing one issue earlier in this thread might have altered the wheel tractor settings? - sorry I should have realised sooner, most tractors I own are wheeled. I just had a large contract and noticed a quadtrac was ploughing perfectly, so I tried a twin track challenger and it was also fine, I then put my Fendt 1050 on it and it started veering off like a wheel tractor is using a different offset maybe?, all with the same course, in the same field with the same plough. I also think the KV PW100 is the worst at this, I will test further when I get another field to plough and test all three using the PW 100

**Comment by pvaiko** [comment]
I've seen this before, sometimes when the tractor starts the row and the plow is not well aligned, it takes very long time until the plow moves where it should be. Other times it rights itself out within a few meters. No idea what is causing it, or it has anything to do with wheels or tracks.

**Comment by coatsy35** [comment]
> I've seen this before, sometimes when the tractor starts the row and the plow is not well aligned, it takes very long time until the plow moves where it should be. Other times it rights itself out within a few meters. No idea what is causing it, or it has anything to do with wheels or tracks.

I'll keep playing to see if I can find an exact cause. But it looks like wheels only so far.

**Comment by coatsy35** [comment]
Definitely worse with the Giants PW100. I'm thinking the built in CP turning radius setting is wrong, I'll have a play in the next few days. Switch to a quadtrac and that was an improvement, definitely worse with wheeled tractors.

![fsScreen_2023_11_10_22_13_22](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/b827495d-63b0-4917-9ce0-b30952b4f589)
![fsScreen_2023_11_10_22_13_32](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/f0e91c38-2ed5-4a84-b626-fb9c0a390fb4)
![fsScreen_2023_11_10_22_19_55](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/b5798cf0-6a3f-4b88-95ba-27582c4fc217)
![fsScreen_2023_11_10_22_20_07](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/227d2d08-99b7-44ca-8f14-907e58411585)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13323496/log.txt)

**Comment by coatsy35** [comment]
I can't find a good radius for wheeled or twin track machines.15 gets sort of there but bits are still left. I know this isn't hugely important but as the KV PW100 12 plough is used more than any other on contracts it would be good if this can be revisited in the future and this issue reopened rather than closed.  From my testing I think the lead in needs to be longer and the the tractor needs to align slightly further away from the ploughing so that pass doesn't start with a curve to it. Could a lead length setting be put in the config file to override if needed? or is it calculated rather than a set value?
