### ISSUE TITLE
[BUG_SP] Unable to log in to the server

### ISSUE THREAD

**Issue by MishanyaKV** [Courseplay/Courseplay_FS22#2767]
Good afternoon to everyone, when trying to log on to a dedicated server, the game freezes at 99% and syncs with players at 29%, although there is no one on the server.I deleted the mods in which I saw errors and it didn't help.Before that, there were such errors in the console Error Running lua method PacketReceived /draw/KeyEvent.Please help me solve my problem.  I tried 4 different versions 7.3.0.0-7.3.0.3.. I play on the Zarya map

![2023-09-14_16-51-16](https://github.com/Courseplay/Courseplay_FS22/assets/121101290/29f1bea4-82b0-4846-aa7d-2ac0f6e4b9bb)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12609719/log.txt)

**Comment by regs1980** [comment]
All mods out.
Leave Giants, CP and the map mods in the folder. 
Start and join the server.

**Comment by MishanyaKV** [comment]
I deactivated all mods as you said.Or was it necessary to start a new game on this map?I left the map, CP and mods from the Giants.The game immediately gives the error unable to connect to a network game.Here it writes in the server log.

Error: Unable to start game server: Could not save settings for gameserver start

**Comment by Tensuko** [comment]
Your log have Errors and it also says a lot of mods are getting loaded.
(Version: 0.52 Beta) AAA_HiredHelperTool is one of those mod I would throw out!

So there is something wrong on your mods/server/game/savegame.

Maybe try load without CP, save and start again with CP.

**Comment by Tensuko** [comment]
Try it with mod by mod or do small packs so you my find out what mod caused it to fail.

**Comment by MishanyaKV** [comment]
Thanks to everyone, I found a broken mod.The topic can be closed
