### ISSUE TITLE
[Question] Bale collection on path

### ISSUE THREAD

**Issue by SirGarnet** [Courseplay/Courseplay_FS22#2768]
Hi,

I'm not using the bale collect mode because it takes to long. I copy the mower path to the baler and later to the collector. With a fitting offset. But when the trailer is full, there is no handover to autodrive. The tractor just stopps at the last bale.

Any chance of changing this? Is this a bug?

Kind regards
Flow

**Comment by Tensuko** [comment]
AD is set up correctly?

**Comment by SirGarnet** [comment]
Define correctly :)

CP: 7.3.0.0
AD: 2.0.1.2

Load and deliver with cp-handover active, I will try Pick-up-mode in a second.

Here a screenshot:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/3258297/132d2047-fcb9-451c-8f19-4ebbc74c793f)

**Comment by Tensuko** [comment]
ja irgendwie erkennt er nicht das er voll ist im fieldwork mit ballen sammeln... mh

**Comment by SirGarnet** [comment]
Was ich auch festgestellt habe, der Ballenwickler hält an beim wickeln und das ist auch gut so. Jedoch der Sammelwagen hält nicht an und schiebt ab und an ballen umher während der Ladeprozess noch läuft.

**Comment by niklas123dj** [comment]
Moin,

ich habe das Problem, das der Ballenwagen, wenn er voll ist, die Sammeleinrichtung nicht wieder hochfährt, wenn er wieder in den AD wechselt.
Gruß Niklas
