### ISSUE TITLE
[BUG_SP] Drescher wendet zu eng

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/Courseplay_FS22#277]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
Drescher wendet auf einer Bahn zu eng, So dass selbst mit frühen absenken und späten anheben er oft was am Bahnanfang stehen lässt. In Gegenrichtung fährt er weiter ins Vorgewende.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Lexion 8900 / Mod=ja

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive ist an und VCA ist geladen aber nicht aktiv.

![LITTLEBIGIV-2021-12-31 11_37_53-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/147819145-11e367f2-48de-4fde-a890-233aca524a4b.png)
![LITTLEBIGIV-2021-12-31 11_41_32-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/147819160-d2fb2507-312a-4692-a9a1-c96d4002e4a8.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7795958/log.txt)
![LITTLEBIGIV-2021-12-31 11_49_42-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/147819286-936aff40-9fc3-4813-abef-d10a775c4f49.png)

**Comment by Clouseau219** [comment]
Kleiner Nachtrag, habe das ganze nochmal mit komplett aktivierten DebugLevels gemacht
Was ich noch bemerkt habe, bei den zu engen Wendemanöver kommt auch kurt die Line für das geradeaus Kurs, verschwindet aber dann gleich wieder und dann kommt der Kurs welcher zu eng ist.

![zu enger Bahnwechsel_vorletzter Bahnwechsel im Log](https://user-images.githubusercontent.com/16350763/147820570-8a0de618-32a9-433c-a113-4e3a0e6c804e.png)
![Ok-Bahnwechsel_letzer Bahnwchsel im Log](https://user-images.githubusercontent.com/16350763/147820575-f634b6d6-39ed-4c4d-a52d-033b41d90be4.png)
![OK-Bahnwechsel2_letzer Bahnwchsel im Log](https://user-images.githubusercontent.com/16350763/147820582-c533b21e-b1e9-4117-88ac-9d34413faf05.png)
[211231_02_log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796033/211231_02_log.txt)

**Comment by Clouseau219** [comment]
Noch ein Log und ein Video
[https://youtu.be/CE3cO-3nDew](url
[211231_03_log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796075/211231_03_log.txt)
)

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
