### ISSUE TITLE
[Question]lag screen

### ISSUE THREAD

**Issue by marsellebar** [Courseplay/Courseplay_FS22#2771]
hello i got this screen sun as i try to open map or create new rute i have lest fs22 version
![image](https://github.com/Courseplay/Courseplay_FS22/assets/145196046/d3528f6f-dce0-42ae-94d2-7c8b8d5d1472)

**Comment by Tensuko** [comment]
attach a log file pls.
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen with logfile attached like written on the wiki page.
