### ISSUE TITLE
[BUG_SP] Courseplay fails to detect silo rear wall

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#2772]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Don't really know what could cause it, the identical silos next to the one being filled are recognized just fine and the problematic silo worked until I restarted the game.

**Actual behavior**
Courseplay does not find the rear wall of the filled silo, and blocks the street behind the silo for incoming unloaders

**Expected behavior**
Courseplay finds the rear wall and does not block the street for unloaders

**Screenshots**
https://youtu.be/riQxsXmAgFo

**Courseplay version**
Version used: v7.3.0.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out 
the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12643273/log.txt)
**Map**
Loesshuegelland

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Yeah I also found this happening, but it is very unclear when and why this happens...
Unless the 2nd big area checks for passing by vehicles is a problem, its not a big deal.
That area we also have be rebuild soon or later.

Not sure how we figure that out, but maybe we find a way.

**Comment by JDTiger** [comment]
Yeah, thats my problem, the rear box goes completly across the road the unloaders are using to reach the silo, so for every unloader the siloworker has to move to the waitingposition up to three times, or he never works the silo because there is always a driver in one of the zones

**Comment by Tensuko** [comment]
Okay, got it.
