### ISSUE TITLE
[BUG_SP] 3-zug-wende mit Grubber fehlerhaft

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2775]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
wende mit Grubber, Amazone cenio4000
Benutze Pfadfinder im Wendemanöver - aktiv
Pfadfinder darf rückwärts fahren - aktiv
wenden auf dem Feld - deaktiv

**Actual behavior**
A clear and concise description of what happen.
wenn der Traktor NH T7.315 mit dem Amazone cenio am Bahnende wendet, bleibt manchmal ein großes Stück unbearbeitet
aber nur, wenn der Traktor bei beginn der wende zur unbearbeiteten Seite einschlägt:
![fsScreen_2023_09_18_16_25_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/7e140b80-cfc4-4acb-a144-0bdb995080d9)
![fsScreen_2023_09_18_16_25_27](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/152c6e77-1681-41fa-aa44-7e1855e16b70)
![fsScreen_2023_09_18_16_25_30](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/8bd49295-846c-419a-883d-07b10600db70)
![fsScreen_2023_09_18_16_25_34](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/16d35897-8f48-4b10-a382-0e8536122dcd)
![fsScreen_2023_09_18_16_25_36](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/8c80ca20-b4dd-4869-8107-3f7b158ccf2a)
![fsScreen_2023_09_18_16_25_39](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/c83a1432-2336-4a84-8077-60b879a1d9e3)
![fsScreen_2023_09_18_16_25_42](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/830b016c-faec-45f3-a296-84fef51554b0)
sieht man am letzten und vorletzten Bild. das da sehr viel stehenbleibt.
auch eine änderung auf 2 Vorgewende bringt keine Besserung.

wenn der Traktor hingegen zuerst auf die bearbeitete Seite einschlägt, passt es beim Anfang der nächsten Bahn:
![fsScreen_2023_09_18_16_26_01](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ca039b46-93c4-40a5-87fd-dfbc4efde0b5)
![fsScreen_2023_09_18_16_26_04](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/81a47569-1936-4caf-af99-ea2adaf3d551)
![fsScreen_2023_09_18_16_26_08](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/3bb7fb9a-a274-42b2-a7af-647d96a8c4b4)
![fsScreen_2023_09_18_16_26_10](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/1243d02e-21a9-4185-bf7f-e5bd2826e1b4)
![fsScreen_2023_09_18_16_26_15](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/aade7ff1-f81b-4f15-8e94-32cf2bc15a6c)
![fsScreen_2023_09_18_16_26_18](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/39fe7d4c-7ef3-4c75-8c30-2df6eae4c4dc)
 

**Expected behavior**
eine gerade Ausrichtung wäre wünschenswert

**Screenshots**
siehe oben
**Courseplay version**
Version used:  aktuelle main vom github

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
vulkan islands

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
cenio grubber zum Pflug umgebaut

**Relevant script mods**
Mods like Autodrive or VCA and so on.
-

lg
andreas

**Comment by Tensuko** [comment]
"cenio grubber zum Pflug umgebaut" <- Mod Issue!

**Comment by Tensuko** [comment]
Mit einem korrekt gebauten "Pflug" in der Art, gibt es keinerlei Probleme:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226965&title=fs2022
