### ISSUE TITLE
[BUG_SP] Courseplay does not support operation Crop Sensor

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/Courseplay_FS22#2776]
Hello! Many people use this mod (The Precision Farming DLC), started with FS-19. Which includes a soil scanning sensor. In FS-19, the Coursplay preliminarily supported the work of tractor drivers with this sensor. No, unfortunately, in FS-22, when this sensor is turned on, there is no "Work in the field" mode, there is no exception to the rules. And scanning the field is not possible. A huge request is to add an opportunity to work with this sensor to the course game mod. Thank you for your work!

I apologize for my English, I write with the help of a Google translator.

Link to the mod - https://www.farming-simulator.com/dlc-detail.php?dlc_id=fs22precisionfarming

![img-2023-09-19-11-26-38](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/d8b8eaf1-0187-4975-ac9a-bc1f02acce37)

**Comment by Tensuko** [comment]
How do you know it is not turned on?
What does the giants helper do?

**Comment by Blackmankot** [comment]
> Откуда вы знаете, что он не включен? Что делает помощник giants?

From personal experience. I can't generate a course to scan the field. Because there is no "work in the field" mode and there is no working width. Hiring from Giants is also not possible to use.

Here is an example of correct interaction:

![img-2023-09-19-13-20-37](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/075149ed-f704-42ad-a705-494f2bb6b03b)
![img-2023-09-19-13-22-26](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/cf6e6a0d-3bc9-4ae6-b588-76acf8125b78)


An example when it is not possible to use the equipment:

![img-2023-09-19-13-24-10](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/731738c7-897e-4de0-87a6-72d6ffd5e33f)
![img-2023-09-19-13-28-06](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/250fe368-2e46-4dff-bc7c-dfafc579a8ce)
![img-2023-09-19-13-28-59](https://github.com/Courseplay/Courseplay_FS22/assets/26131714/659db6ae-705a-4fdd-b907-945cfb6b11ba)

**Comment by Tensuko** [comment]
The Sensor without any tool doesn't make sense.
It is not used anymore for scanning the ground, but for scanning the small flowers of the fruit while applieing fertilizer.

So you have to attach a tool.
That have changed on PF for FS22.

**Comment by Blackmankot** [comment]
> The Sensor without any tool doesn't make sense. It is not used anymore for scanning the ground, but for scanning the small flowers of the fruit while applieing fertilizer.
> 
> So you have to attach a tool. That have changed on PF for FS22.
> 
> In case you want to scann the ground, the normal scanner for it works with CP. (probing)

By the burning, I did not know this innovation... I see, thank you very much!
