### ISSUE TITLE
[BUG_SP]Pathfinder reverse turn misses row start

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2777]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
sorry, aber ich kann das thema #2775 nicht mehr öffnen, es ist kein mod konflikt, es funktioniert mit dem original giants amazone cenius 4000 Grubber genausowenig:

**Steps to reproduce**
Steps to reproduce the behavior.
wende mit Grubber, Amazone cenio4000
Benutze Pfadfinder im Wendemanöver - aktiv
Pfadfinder darf rückwärts fahren - aktiv
wenden auf dem Feld - deaktiv

**Actual behavior**
A clear and concise description of what happen.
wenn der Traktor NH T7.315 mit dem Amazone cenio am Bahnende wendet, bleibt manchmal ein großes Stück unbearbeitet
aber nur, wenn der Traktor bei beginn der wende zur unbearbeiteten Seite einschlägt:

![fsScreen_2023_09_19_08_55_38](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/37cf1601-7d04-45f8-94d9-19a86159d122)
![fsScreen_2023_09_19_08_55_41](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/9065aedc-68c4-4b98-ad7d-47e3fd4d69ce)
![fsScreen_2023_09_19_08_55_45](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/e8b8726b-5a0f-437b-b7f0-a480ee3af17a)
![fsScreen_2023_09_19_08_55_49](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/781985b1-61cb-412b-9c43-9fcebff40e42)
hier bei Bild 4+5 ersichtlich liegt mMn das Problem, das der Traktor nicht genügend weit zurückfährt, somit kommt er mit der Vorwärtskurve nicht rechtzeitig zur Bahn
![fsScreen_2023_09_19_08_55_51](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a52cad9f-ff8d-4b2e-9649-24fd9da38d42)
![fsScreen_2023_09_19_08_55_53](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/e9a376cc-85b6-42ba-986c-f8aede33a24e)
![fsScreen_2023_09_19_08_55_55](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ef67d11e-3086-4df8-963b-d312c60c563f)
![fsScreen_2023_09_19_08_55_58](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/2c38250d-7e28-4f03-894b-4d624dd50466)
![fsScreen_2023_09_19_08_56_01](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/87e55db4-b9a4-4346-883d-f2a6ddcc415d)

Beginnt die AI Wende zum bearbeiteten Teil, passt der Ansatz:
![fsScreen_2023_09_19_08_56_20](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/3b7debe3-cdef-47cc-8a65-b02f96cccfb3)
![fsScreen_2023_09_19_08_56_26](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/621ccb9a-ceeb-4d40-8a01-bcffe218ebe1)
![fsScreen_2023_09_19_08_56_31](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/7b34279d-c3bb-42e9-97f4-3cf4b7e7544f)
![fsScreen_2023_09_19_08_56_34](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/54e5eb38-4481-48d8-9eb3-a52dd1645530)

das ist so aber erst seit einiger zeit, vorige Woche war der Bahnansatz immer sauber

**Expected behavior**
eine gerade Ausrichtung wäre wünschenswert

**Screenshots**
siehe oben

**Courseplay version**
Version used: 
aktuelle main vom github

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12656841/log.txt)

**Map**
Map played on.
vulkan islands

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
alles original giants fahrzeuge,
- NewHolland T7.315
- Amazone Genius 4000 Grubber

**Relevant script mods**
Mods like Autodrive or VCA and so on.

lg
andreas

**Comment by Tensuko** [comment]
Ich habe das mit dem Tool probiert und keien Probleme gehabt...

**Comment by Tensuko** [comment]
Hänge bitte mal dein savegame an mit dem Kurs geladen in dem Traktor.

**Comment by andreasthu** [comment]
Hallo Tensuko
hier mal das savegame15 und der CPordner von modsSettings:
[Tensuko.zip](https://github.com/Courseplay/Courseplay_FS22/files/12658646/Tensuko.zip)

der New Holland steht schon richtig auf Feld5, der John Deere auf Feld 29+30
Kurse sind eingestellt und der Giants Grubber Amazone ist angehängt.
zusätzliche mods werden nicht gebraucht.

und hier ein dropbox link, zusätzlich mit der map drinnen:
https://www.dropbox.com/scl/fi/vk7exi7r3rsb7ic7m1y2b/f-rTensuko.zip?rlkey=68gg4b3uulvoi4mhrqlg856r8&dl=0
(abload.de funktioniert leider nicht mehr)

lg
andreas

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/a0b7a678-421b-4450-b326-6cd757ae522b)

**Comment by Tensuko** [comment]
Habs glöst, paar Fahrzeuge aus der vehicle.xml geschmissen.

**Comment by Tensuko** [comment]
Also davon ab, dass ich nicht verstehe warum du wenden auf dem Feld aus hast (damit sollte es funktionieren), konnten wir es jetzt rausfinden wann es passiert.

**Comment by andreasthu** [comment]
Danke euch sehr
lg
andreas

**Comment by andreasthu** [comment]
Hallo @Tensuko 
sorry, aber mit dem aktuellen main von cp ist es wieder drinnen:
![fsScreen_2023_10_08_10_00_29](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/f43054d1-2bd8-425c-a1d3-10b96a475bf6)
![fsScreen_2023_10_08_10_02_14](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/196ba2f1-2ea2-46f0-80f3-92ea44322488)
ich weiß nicht, k.a. oder bin ich zu kleinlich, aber ich denke, das wenden sollte schon relativ lückenlos funktionieren.
ist aber eher bei kleinen Arbeitsbreiten, 3-4m, je breiter desto weniger Lücken.
lg und sorry
andreas
