### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by SirGarnet** [Courseplay/Courseplay_FS22#2779]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**

1. Turn AD help off
2. Switch vehicle and back to prev. vehicle (to take effect)
3. Create a course on a field and start it
--> AD Help is shown again in F1 menu and AD option is ignored

**Actual behavior**
The option of AD to hide help in F1 menu is ignored

**Expected behavior**
CP courses should not influence help option of AD 

**Screenshots**
See: [https://github.com/Stephan-S/FS22_AutoDrive/issues/980#issuecomment-1726383816](https://github.com/Stephan-S/FS22_AutoDrive/issues/980#issuecomment-1726383816)

**Courseplay version**
Version used: 7.3.0.0
AD Version: 2.0.1.2

**Client Log**
_not needed_

**Server Log**
_not needed_

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server: no

**Map**
NF Marsch

**Vehicles/ implements involved**
tried several field work equipment & vehicles

**Relevant script mods**
AD: 2.0.1.2

**Comment by Tensuko** [comment]
I have my doubt that CP does influence any AD Settings.
The question is more:
Why do I have to get out of a vehicle to get the option active.
When I turn it off in AD, I have to leave the vehicle and re-enter it to have an effect of that setting!

And I can tell you I never had it back active after that on my entire savegame.
