### ISSUE TITLE
[Feature] Ballentyp-Auswahl für weitere Ballenwagen/Trailer!?

### ISSUE THREAD

**Issue by Oberlump** [Courseplay/Courseplay_FS22#2781]
Ggf. ist mein Request totaler quatsch, aber wenn es für Courseplay möglich ist, wäre es Klasse, wenn auch Mods / Mod-Ballenwagen/Trailer die Option zur Auswahl des Ballentyps erhalten könnten.

Aktuell nutze ich z. B. [dieses](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233456&title=fs2022) Autoload Stock Trailer Pack. Courseplay erkennt zwar, dass damit Ballen geladen werden können (und lädt diese auch), wenn aber zwei Typen (gewickelt und ungewickelte) auf dem Feld sind, klappt das natürlich ohne die Auswahl des Ballentyps nicht. Und diese Auswahl fehlt leider (wieso auch immer?).

![ballentyp](https://github.com/Courseplay/Courseplay_FS22/assets/70055950/6d8d2d0e-d984-4c9f-820c-eac2f95a5c78)

**Comment by Tensuko** [comment]
Da es sich dabei um autoload mod handelt, wird es das so nicht geben
Wir unterscheiden nur zwischen vanilla gewickelt und ungewickelt, keine expliziten Ballentypen, das ist was anderes.

**Comment by Tensuko** [comment]
Wird sowieso nicht klappen, weil wenn müsste das script das filtern sonst wird der ballen auch eingesammelt wenn z.B nur gewickelt gewählt ist. Liegt also in der Hand des Modder vom script.

**Comment by Oberlump** [comment]
Aber wo ist der Unterschied zu einem Stock/Vanille-Trailer? Da klappt es doch auch wunderbar, dass Courseplay nur die gewählten Ballen anfährt und auflädt (sobald der erste geladen ist, können ja eh keine anderen mehr geladen werden).

**Comment by Tensuko** [comment]
Weil es ein externes script ist!
Wir haben keinen einfluss darauf was das externe acript einsammelt!

**Comment by Tensuko** [comment]
So ist es.
