### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by PatrickStar178** [Courseplay/Courseplay_FS22#2782]
Hello, I have been experiencing that my combine stops at 95% percent when using courseplay, the map I'm on right now is modded but its done it for most of the other modded maps this one is called Little Mountain Country.

You should be able to reproduce the issue by doing the cp fieldwork and then using a combine harvester.

I do use a lot of mods, but none that are really scripted like courseplay or anything.

Usually when it happens is when I start on a field and then by the time it gets roughly to around 95% percent they end up backing up for no reasons and waiting to be unloaded.

And now I'm having another issue on the map where the field generating seems to be a bit off so my seeder was planting in the right way but too far over.

**Comment by Tensuko** [comment]
95% is a fixed value by us and not a bug.
And next time, use the bug template pls.

**Comment by PatrickStar178** [comment]
See what template there was no template provided? Lmao not my fault and yes
but why is it a fixed value

**Comment by Tensuko** [comment]
For several manuvers like pockets.
When you hit new issue you select bug report there is a template to fill in.

**Comment by PatrickStar178** [comment]
Pretty sure I did that but I guess I wasn’t supposed to delete some of it
