### ISSUE TITLE
OXBO Fertilizer [BUG_SP]

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#2787]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
AXBO fertilizer on any map, create a course to fertilize grapes.

**Actual behavior**
A clear and concise description of what happen.
OXBO fertilizer, create a course, vehicle starts forward, sprayer turns on for a micro-second, then the OXBO stops, CP still showing its engaged.

**Expected behavior**
I realize this is a new DLC, and the CP team will need some time to sort this out.  The OXBO covers (4) rows, so its start point needs to be adjusted to allow for the multiple rows. If its on the vine, and CP can't be code to create a course for every (4) rows, then I guessing you will have to the rows to skip option and add a 4 to its menu.

**Screenshots**

**Courseplay version**
Version used: 
v7.3.0.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12678864/log.txt)

**Map**
Map played on.
Adelshoven, and Haut Beyleron

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
OXBO DLC, fertilizer option.

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD was loaded as a mod. but not in use.

**Comment by Tensuko** [comment]
Known Issue, not sure whats wrong with this tool.

**Comment by HC1Gunner** [comment]
TY, not sure why it starts and immediately stops. But because it covers (4) rows, code is going to have to be added just for this tool. I know officially Giants doesn't support mods, but I know that QA department uses both CP and AD. Not sure if the tool can be configured has both a harvester and sprayer has something to do with it or not. Sorry Giants has thrown you another curve ball.

**Comment by HC1Gunner** [comment]
I kind of somewhat blame this on Giants, every base game vehicle and mod I use all work with CP, then Giants goes adds a new tool that doesn't work with one of the most popular mods out there.
I've been messing around, I have yet to figure out what's causing to not to work.

**Comment by Tensuko** [comment]
We reported it to giants but.... We will see.

**Comment by HC1Gunner** [comment]
I found two other problems, when using the OXBO as a grape harvester, there is nothing shown in the HUD for the hopper (bin) quantity. It also loses a ton of grapes. I ran the NH Braud right next to it, on a single pass the OXBO had 98L, while the NH had 398L. I swear, sometimes it's like their QA depart doesn't test everything they release. I tried this on two base game maps with zero mods installed. Zero log errors. I sent everything to them, with screenshots.

**Comment by Tensuko** [comment]
One harvesert mode is overloader so it doesnt have a capacity.

**Comment by HC1Gunner** [comment]
Not sure I follow you're reasoning, I was using the configuration with the OXBO that has a pipe, but all combines all have pipes, and their quantity is always shown, same goes for all overload auger wagons.

**Comment by Tensuko** [comment]
So? Giants cant create a harvester where this is not the case?
Spoiler: the carrot harvester will work the same, pipe with no fill volume. Just like a chopper with forced unload.

**Comment by HC1Gunner** [comment]
All the Ropa and Holmer root harvesters, and the combines that harvest all the rest of the crops, have bins, pipes (they overload), and they all show their own quantities. Guess I not quite getting why grape harvester with a pipe is any different. No try to be argumentative, just don't see were the difference is.

**Comment by Tensuko** [comment]
The tools simply dont have a fill volumen, also IRL.
Thats it.

**Comment by Tensuko** [comment]
Reported the problem to Giants, waiting for a fix...
