### ISSUE TITLE
[BUG_SP] penultimate point incorrect from AD to CP first WP in reverse 

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2788]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
mit einem 3punkt Gerät von AD zum 1. Wegpunkt imRückwärtsgang anfahren
z.b. Claas und der Einböck Striegel, aber auch Grubber, Sämaschinen,...

**Actual behavior**
A clear and concise description of what happen.
wenn AD zu CP übergibt und der 1. Wegpunkt angefahren wird, ist der Vorletzte Wegpunkt bei anfahren versetzt:
![fsScreen_2023_09_21_08_26_50](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/04d56960-5001-4cb5-8ea9-fed7aec5c5b7)
![fsScreen_2023_09_21_08_26_57](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/527d14b3-72d5-4d52-b2eb-c280a3c6a86c)
![fsScreen_2023_09_21_08_26_50](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/c62cc235-befc-455b-ba00-22373492d033)
![fsScreen_2023_09_21_08_27_02](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/6a079faa-a484-41fa-918e-cd92a0dc6f61)
![fsScreen_2023_09_21_08_27_09](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ad952bdc-0036-404b-9af6-80c06a0d0daf)

hier sieht man gut, das der punkt"12" nicht in Linie ist und infolge den Traktor aus der Bahn bringt:
 ![fsScreen_2023_09_21_08_27_12](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/4a8dddd5-91b9-45cf-a808-03c549b1d659)
![fsScreen_2023_09_21_08_27_14](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d1375808-8af3-4e3c-badc-557daa0310c3)
![fsScreen_2023_09_21_08_27_17](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/eaa0c197-2e76-4798-89c0-8f893555f376)
![fsScreen_2023_09_21_08_27_20](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/bba11f12-d045-4149-8912-b30fe8057289)
![fsScreen_2023_09_21_08_27_22](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ac093f62-a0b5-40ab-a391-b894ebbfd294)
![fsScreen_2023_09_21_08_27_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/8691e87c-763d-464e-9e5d-c66157c233fb)

er erfängt sich zwar etwas, aber startet dennoch ca. 1m neben der Spur.
was bei geräten vom 3 oder 4m arbeitsbreite eher ungünstig ist:
![fsScreen_2023_09_21_08_27_41](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a33e544d-ca62-4618-882b-d1cdf18f67bd)

**Expected behavior**
Korrektur des vorletzen Punktes oder deren Löschung

**Screenshots**
siehe oben

**Courseplay version**
Version used: 
aktuelles 7.3.1.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12681112/log.txt)

**Map**
Map played on.
vulkan islands

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
claas arion600
einboeck pneumaticstar900
KEINE modfahrzeuge

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD +CP

sorry das ich schon wieder arbeit mache
lg
andreas

**Comment by Tensuko** [comment]
Und gibt es ein Problem bei der Bearbeitung wenn er fertig ist mit dem Feld?...

**Comment by Tensuko** [comment]
Nur mal so.... Warum hast du bei dem anderen issue mit wenden auf dem feld = aus gearbeitet. Das wäre komplett unnötig gewesen, dann hätten wir die änderung nicht machen müssen die jetzt zu diesem problem führt.

**Comment by Tensuko** [comment]
Wenden auf dem Feld an ist das exakt gleiche Wendemanöver für 3-Punkt Geräte und das dauert nicht länger.

![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/e75b4ead-dccc-44a9-aaf8-871dfcdd9223)

Aber egal wir gucken das wir das gefixt kriegen.

**Comment by andreasthu** [comment]
Ah ok, das wusste ich nicht das das bei 3punkt das gleiche manöver ist.
Aber wenn ich dann z.b. den steinsammler, gülllefass oder Miststreuer drann habe müsste ich das dann ja wieder abschalten, und wieder aktivieren bei 3punktgeräten. Was hätte das für einen sinn dann bzw wäre das eine Einstellung die man dauernd ändern müsste?

Ich dachte nur, das bei closed beiträgen das nichtmehr kommt, bzw dachte ich das da selten wer nachschaut.

schönes ackern
Lg
Andreas

**Comment by Tensuko** [comment]
Man sollte am besten immer die passende Einstellung für das Gerät verwenden.
Was es ffür einen Sinn hat? Dafür sind die Einstellungen da...
Aktuell halt pro Taktor gespeichert, es gibt Pläne solche Einstellungen pro Gerät zu speichern, aber die stehen aktuell sehr weit unten auf der TODO Liste.
