### ISSUE TITLE
Problem mit Abfahrern [BUG_SP]

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2789]
Folgende Videos angefügt, um das Problem besser zu erkennen!

Das Problem habe ich nur auf der FS22_DondiegoMap
Abfahrer fährt nicht im CP Modus ab!
Abfahrer fährt im AD Modus vor dem Drescher!
Danke für euer stetiges Bemühen und für eure Arbeit.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12683038/log.txt)

Video dazu
https://youtu.be/dRmCtoqW1gk
https://youtu.be/gzYeo9Qamt0
https://youtu.be/9GAlmice3r4

**Comment by regs1980** [comment]
Die Videos sind im privat Modus, musst du schon freigeben das man auch die Probleme sehen kann.

**Comment by KarlGutenberg** [comment]
Sorry mach ich sofort!

regs1980 ***@***.***> schrieb am Do. 21. Sept. 2023 um 13:22:

**Comment by regs1980** [comment]
Wieso fahren deine Abfahrer in der Frucht und warum mäht der Drescher so das er das Rohr immer in der Frucht hat?
Hattest du beim CP Abfahrer den Feld- und den Zielpunkt angegeben?

**Comment by KarlGutenberg** [comment]
Wieso fahren deine Abfahrer in der Frucht und warum mäht der Drescher so das er das Rohr immer in der Frucht hat? 
Kann ich nicht sagen, warum das so ist, Fruchtumfahrung ist aktiviert.

Hattest du beim CP Abfahrer den Feld- und den Zielpunkt angegeben?
Ja habe ich! Drescher sowie Abfahrer.

**Comment by regs1980** [comment]
> Ja habe ich!

Wird wohl an deinem Mod Traktor liegen, habe es jetzt mit einem Axion 960, JD 8R 410, fastrac 8330 und einem Fend 1050 es reproduziert und den CP Zielpunkt direkt auf den AD Feldpunkt gelegt. 
Hat alles wunderbar geklappt. 
Was ich eher glaube ist, das du diesen Punkt
![2023-09-21 15_58_44-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/b8ccc377-c585-440f-9ae0-f3a1275e3e87)
nicht gesetzt hast, weil dein Traktor genau auf den AD Punkt zurückfahren will,
![2023-09-21 15_57_11-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/ef5c2aa1-fbf8-416a-ae0b-3ed2323ae601)
wenn ich den Punkt manuell setze, fährt er nie genau auf den Punkt, sondern daneben. 

> Kann ich nicht sagen, warum das so ist, Fruchtumfahrung ist aktiviert.

Dein Drescher fährt gegen den Uhrzeigersinn, dadurch kommt auch AD nicht klar.

**Comment by KarlGutenberg** [comment]
Ich habe den Punkt gesetzt!
Aber ich versuche es mal mit deinem Traktor!
Ich sende dir dann noch ein Video!
Danke erst einmal


regs1980 ***@***.***> schrieb am Do. 21. Sept. 2023 um 16:03:

**Comment by regs1980** [comment]
Bei 1:40 in dem Video hast du den Zielpunkt nicht gesetzt 
https://www.youtube.com/watch?v=9GAlmice3r4

**Comment by KarlGutenberg** [comment]
https://youtu.be/gN8u84eG1mI
hat so weit geklappt! Ich hoffe, dass der Zielpunkt jetzt richtig ist!
Danke vorerst

**Comment by Tensuko** [comment]
Ich nehme das dann mal als gelöst an...

**Comment by KarlGutenberg** [comment]
Ja danke

Tensuko ***@***.***> schrieb am Do. 21. Sept. 2023 um 17:04:

**Comment by regs1980** [comment]
@KarlGutenberg So jetzt noch mal für dich, um deine Mod-Traktoren zu benutzen, musst du auch noch einen Zielpositionspunkt setzen und nicht wie du die ganze Zeit nur den Feldpositionspunkt. 
Machst du dieses nicht fahren die Mod-Traktoren wieder zum CP Aktivierungspunkt zurück und versuchen an AD zu übergeben, das schaffen die Vanilla Traktoren aber nicht deine Mod-Traktoren, die werden dann in eine Endlosschlaufe gesetzt zwischen AD und CP. 
Daher ist es ratsam, einen Zielpositionspunkt zu setzen, der etwas weiter weg vom AD Punkt ist.  

Noch was zu deinem Drescherkurs, wenn du ihn generierst, es gibt die Option in Uhrzeigerrichtung und entgegen. 
Bei einem Drescher mit dem Rohr auf der linken Seite sollte man im Uhrzeigersinn den Kurs erstellen, dann fährt der Abfahrer auch nicht in der Frucht herum.

![2023-09-21 17_17_03-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/124819c5-4fe6-43e2-b028-d3fc3c8c58bb)

**Comment by KarlGutenberg** [comment]
Ich glaube ich habe dich jetzt verstanden,
Du meinst nicht nur der Drescher braucht ein Zielpunkt sondern der Abfahrer
auch?
Richtig? Ich versuche es nochmals!
Danke

regs1980 ***@***.***> schrieb am Do. 21. Sept. 2023 um 17:47:

**Comment by regs1980** [comment]
Der Drescher braucht kein Zielpositionspunkt, wenn du mit AD ihn zum Feld fahren lässt.
Dieser braucht er nur, wenn du ihn mit dem InGame Helfer zum Feld schicken willst.
Nur der Abfahrer braucht einen, wenn du ihn zu einem gewissen Feldpunkt schicken willst, bevor er an AD übergibt und bei Mod Traktoren würde ich das immer machen sicher ist sicher.

**Comment by KarlGutenberg** [comment]
Ja hat geklappt auch mit mod Traktor!!
Danke für deine Hilfe!

regs1980 ***@***.***> schrieb am Do. 21. Sept. 2023 um 17:58:

**Comment by KarlGutenberg** [comment]
Nach eine Frage:
Warum fährt der Abfahrer, wenn er mit AD gesteuert wird immer vor dem
Drescher?
Siehe Video? Weil linksrum?


regs1980 ***@***.***> schrieb am Do. 21. Sept. 2023 um 17:58:

**Comment by regs1980** [comment]
Du arbeitest entgegen gesetzte Richtung, sodass das Rohr und der Abfahrer immer in der Frucht ist, AD versucht dem Drescher aus dem Weg zugehen, was nicht möglich ist.
Erstell einen Drescherkurs wo das Rohr in Richtung Feldkante zeigt beim Vorgewende und schon ist alles gut.

**Comment by KarlGutenberg** [comment]
Danke für dein tip ich versuche es mal!


regs1980 ***@***.***> schrieb am Fr. 22. Sept. 2023 um 15:28:
