### ISSUE TITLE
[BUG_SP] Multitool Harvester Unloading is unreliable for small tool width harvesters

### ISSUE THREAD

**Issue by aesguitar** [Courseplay/Courseplay_FS22#2796]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

1. Large field planted with potatoes.
2. Build a 2 tool course to harvest - tool width 13.1ft
3. start the course
4. Assign an auger wagon to handle unloading in field
5. harvesters fill up, auger goes to unload, traffic jam

**Actual behavior**
A clear and concise description of what happen.

When the harvesters are close to one another for unloading, a couple of issues have happened. 
 - The harvesters end up too close together for the auger wagon to even get to the discharge port.
 - The auger wagon can get to the discharge port, but the harvesters are too close together for it to move forward and clear the harvester
 - The harvester doesn't continue on when empty
 - the auger wagon doesn't move on when the harvester is empty

Turning courseplay off/on for the harvester or tractor w/ wagon does not correct the issue. I have the manually move one or the other somehow.

**Expected behavior**

- The auger wagon should find the best way to clear itself out of the route of the harvesters
- the harvester should continue on when empty
- the harvest should "close pipe" when empty regardless of the proximity to a wagon, perhaps include a timeout before the pipe can be re-extended below a certain threshold (like under 10% and just unloaded, wait 45 seconds or travel 100m before pipe can extend)
- deconflict themselves when unload is needed and tool widths are narrow like for root crops

**Screenshots**
![Screenshot 2023-09-23 080742](https://github.com/Courseplay/Courseplay_FS22/assets/6676966/19989bfa-af7c-4b9b-88d2-969375c766c3)

![Screenshot 2023-09-23 080825](https://github.com/Courseplay/Courseplay_FS22/assets/6676966/b6614e98-4644-4a38-97e1-7c1fef8f9d7b)

![Screenshot 2023-09-23 080938](https://github.com/Courseplay/Courseplay_FS22/assets/6676966/6e630285-25e8-4325-af8e-f7e034dde5a0)

<img width="1781" alt="Screenshot 2023-09-23 082202" src="https://github.com/Courseplay/Courseplay_FS22/assets/6676966/67905043-1939-4a99-ba74-19fd9c710885">

**Courseplay version**
Version used: 7.3.1.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

https://pastebin.com/ftY9NrhP

**Map**
Map played on.

https://www.kingmods.net/en/fs22/mods/26190/idaho-map

**Vehicles/ implements involved**
Vanilla case tractor. Modded harvest and auger wagon.

<img width="1326" alt="Screenshot 2023-09-23 081957" src="https://github.com/Courseplay/Courseplay_FS22/assets/6676966/342acd82-2436-4c4b-a8e1-7ff07264a10c">

<img width="434" alt="Screenshot 2023-09-23 082052" src="https://github.com/Courseplay/Courseplay_FS22/assets/6676966/12258117-9a36-45e6-b24f-d880d0151545">

Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.
 
Autodrive is installed, but not controlling vehicles in this log and screenshots.

**Comment by Tensuko** [comment]
Use another pattern for the center line.
Best working one is Lands.

This situation - won't fix.
