### ISSUE TITLE
[Feature] Cotton harvesting in rain

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/Courseplay_FS22#2801]
**What is the problem this feature/enhancement solves?**
I just ran into a problem while a cotton harvesting contract was running and it started to rain. When I switched back to the cotton harvester (John Deere CP690 - base game machine) sometime later, I saw a warning about harvesting in rain might result reduced yield. That is exactly what happened and it made the contract fail.

**Describe the solution you'd like**
My suggestion is to modify the behavior of cotton harvesters controlled by CP, to make them stop during rainy weather, similar to regular harvesters.

Game mode: Single player
CP version: 7.3.1.0
Map: Elm Creek Edit 4x V1.0.0.9 by Stevie

**Comment by Tensuko** [comment]
The Problem is that the cotton harvester is not completly a harvester, but also a baler.
Thats could be a bit tricky...

**Comment by RedMonster-HUN** [comment]
What if the change is based on the machune's output? - (cotton bale)

**Comment by Tensuko** [comment]
That doesnt work like that, its about the specs and how we have to handle them so they work correctly, wich was a struggle with the cotton harvesters.
