### ISSUE TITLE
[Enhancement]Unloader drives reverse when combine drives reverse on 2nd headland.

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2802]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
CR10.90 Combine c/w 45ft Header

**Actual behavior**
When coming up to a corner and the unloading stops, the tractor and trailer park in the way for the corner turn.  Getting this on every sharp corner

**Expected behavior**
The trailer stops sooner or the trailer backs up after stopping.

**Screenshots**
![fsScreen_2023_09_24_14_25_45](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/55aa3c5a-d838-4381-afaa-4653a0989291)

**Courseplay version**
Version used: 7.3.1.2

**Log**
Didn't have logging on

**Map**
The Oaks

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Unloader driven by CP or AD ?

**Comment by coatsy35** [comment]
> Unloader driven by CP or AD ?

should have said all driven by CP

**Comment by Tensuko** [comment]
logfile is always requiered btw.

**Comment by coatsy35** [comment]
More to add. With Log this time :D 

When a trailer is filled to the empty point and the combine is in the pocket on the first headland run, the combine could do with pausing a little longer and letting the trailer drive forward and past the combine before it moves out of the pocket. Otherwise if using the may AD routes that are available from say the AD guy, the trailer follows the route around the outside of a field, but in doing so drives right behind the header trying to go forward as the combine sets off before the trailer can drive forward again, then when the combine hits sharp corner, there is a crash as the combine backs up and then hits the trailer. Had this happen a lot too.

![fsScreen_2023_09_25_22_29_52](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/66aa51db-4608-4223-a1bf-3f006e4e71f9)

 
![fsScreen_2023_09_25_22_30_18](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/20b2dbd9-98ff-4ac0-9e7a-f09e46b14a04)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12719625/log.txt)

**Comment by Tensuko** [comment]
Your pics: unload combine on first headland must be deactivated so it creates a pocket and not call the unloader on the fly.

**Comment by coatsy35** [comment]
The combine is deactivate to unload on the headlands in them pictures

**Comment by Tensuko** [comment]
The unfolded pipe is becouse thats the normal giants function. Will keep it as well.

AD have to adjust this if they drive.

We won't wait for no reason at some point as this is rly just an edge case.

Back to original topic now!
Will check what the unloader do when doing a turn on 2nd headland and then adjust/fix it.

**Comment by Tensuko** [comment]
Can't reproduce.
https://drive.google.com/file/d/16olqZDyjDJx7s8WO5qSBCa5dqPhod5zb/view?usp=sharing
The unloader just backs up fine when the combine is reversing to make room.
No Idea how you did end up like that.
The unloader could not be further at the back while unloading so that the combine sensor is not hitting the unloader...

Make a Video of your corner situation with debugs on on both vehicles.

**Comment by Tensuko** [comment]
Closed due to inactivity.
