### ISSUE TITLE
[BUG_SP] Giants Unloader Randomly Unavailable

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#2805]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I'm not sure how to reproduce since it is so random. However, I've completely shut down FS and restarted just to have it suddenly crop up again.

**Actual behavior**
After creating a course where CP unloads the combine and drives it to the sell point, CP will stop running on the tractor doing the offloading. Attempting to restart shows a message saying Giants unloader is unavailable. I attempted to create a new course only to get the same message. Initially, I was able to do 2 fields with no issue, but then each new field eventually fails with the same message.

**Expected behavior**
I expect the tractor to offload the combine and drive to the sell point when full.

**Screenshots**
If applicable, add screenshots to help explai
![GiantsUnloaderErrorMessage](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/c60e52af-70a8-42a1-a4b7-6cc41ad71830)
n your problem.

**Courseplay version**
7.3.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12709781/log.txt)

**Map**
Iowa Plains

**Vehicles/ implements involved**
Which vehicle or implement?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12709771/log.txt)

Mod yes/no ? Both vanilla. First tractor I couldn't restart was the vanilla Massey Ferguson 6718 with a mod Broughan tipper (from Modhub)

The 2nd was the Volvo F16 485 truck with the Demmler SKM 209 mod tipper (from ModHub)

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
Might be can't find a path or anything, but I need steps to reproduce this.
When I do it I can't get the Error to happen...

**Comment by lcc1211** [comment]
I haven't seen the issue again, but it happened when I stopped the vehicle that was offloading the combine and then restarted.

**Comment by mixedbyte** [comment]
You can reproduce this if you start several unloaders without a combine in between. If you start combine and unloader then combine unloader you can start many, but with just starting all combines first then all the unloaders it will fail. fails on 3rd for me.
