### ISSUE TITLE
[Question]Turning on Debug Channels - Farbe?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#281]
```
Turning on Debug Channels
When there's an issue, you can turn on debug channels so Courseplay will log a lot of information we need for troubleshooting. You can bring up the debug channel menu by pressing Shift+4, then use Shift+1 and Shift+3 to select a channel, and then Shift+2 to toggle the selected debug channel (green is on).
```
Hallo Leute
Ich habe extrem schwierigkeiten zu sehen ob ein debug channel an oder aus ist (Farbenblind, rot-grün-schwäche).
Wäre es möglich, da etwas besser unterscheidbare Farben zu nehmen?
Oder wie kann ich die farben selber für mich ändern?
Lg
Andreas

**Comment by Tensuko** [comment]
Wenn du die 7.0.0.10 hast sollten einige channel an sein und du musst nur unter den Fahrzeugeinstellungen debug aktiv schalten. So war das von uns jetzt gedacht. 

Aber was wären für dich denn besser passende farben ?

**Comment by andreasthu** [comment]
Hallo Tensuko, 
Dann werd ich die 7.0.0.10 nächstes Jahr mal probieren.
Mit 7.0.0.9 waren das grün und orange (glaub ich), und für mich fast nicht zu unterscheiden.
Es könnten z.b. eine blasse und eine kräftige Farbe sein, .. oder hellgrün/dunkelgrün, z.b.
K.a. Farbempfinden ist nicht einfach zu erklären.
Ich versuchs mal, in Ls22 spiele ich mit standardfarben (weil mit dem farbenblindmodus nur 4 wachstumsstufen abgebildet werden) in ls19 hatte ich den fabenblindmodus an.
Wenn ich auf den wachstumskalender gehe, sehe ich da seitlich rechts 8 verschiedene grüntöne, hell bis dunkel, die kann ich gut erkennen, weil die gleich nebeneinander liegen.
Wenn ich mit diese farben auf der karte selber ansehe auf den feldern und zwischen den feldern ist die pda map, oder ich sehe mir z.b. Feld 1 und 15 an, kann ich n8cht nicht sagen, ob diese das gleiche grün haben oder unterschiedliche, oder welches der 8 grüntöne die genau haben.
Aber ich kann sehen obs eher am anfang ist, blass, oder schon dem ende zugeht, dunkler/kräftiger, aber ob das jetzt  6, 7 oder 8 ist - keine ahnung.
Ist echt schwer das zu beschreiben.
Lg
Andreas

**Comment by Tensuko** [comment]
Ist ok Andreas. Wir schauen mal.

**Comment by andreasthu** [comment]
ist schon ok,
finde die einstellung in den settings sehrgut
btw, habe für mich in der CPdebug.lua die Farben geändert
ab zeile 100 sieht es so aus:
```
		if self.channels[channelIx].active then
			setTextColor(0, 1, 0, 1)
		else
			-- setTextColor(1, 1, 0, 1)
			setTextColor(1, 1, 1, 1)
		end
```
d.h. die inaktiven sind bei mir nun weiß, besser zu unterscheiden.
lg
andreas

**Comment by Tensuko** [comment]
Ah super.
Das heist weiß inaktiv und grün aktiv wäre für dich ok ?

**Comment by andreasthu** [comment]
ja klar,
wobei ich nur 2 farben probiert habe schwarz und weiß (0001 und 1111).
schwarz fiel raus weil der untergrund meist dunkel ist.
aber es kann auch jede andere kontrastreiche Farbe sein.
Kräftiges, dunkles Rot könnte ich auch von dem aktivstatus-Hellgrün unterscheiden.
hab da grad den Farbcode aber nicht.
lg
andreas

**Comment by Tensuko** [comment]
Ok, danke dir fürs probieren.

@schwiti6190 was meisnt du dazu ?

**Comment by andreasthu** [comment]
Danke fürs umfärben
lg
andreas
