### ISSUE TITLE
[BUG_SP]Proximity Sensor looks into the ground.

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#2814]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Not sure how this happened.

**Actual behavior**
The one half of the sensor looks into the ground.

**Screenshots**
![fsScreen_2023_09_29_10_46_05](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/19b5d2d9-edb0-4bc1-a85c-2e0daf7f3e86)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/af30cd9f-24fc-49f5-a1a6-fd8967a9855a)

**Courseplay version**
Version used: 7.3.1.3 - actual Main

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12762686/log.txt)

**Comment by pvaiko** [comment]
Dunno, it got loose because you hit something with the left side of the tractor? Bend it back, fix it with duct tape, whatever. 

Can you reproduce it? Rays are individually controlled to be parallel with the terrain, could it be a map issue?
