### ISSUE TITLE
Radlader fährt vorm Silo

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2819]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by KarlGutenberg** [comment]
https://youtu.be/luuBhOiHrmk

**Comment by KarlGutenberg** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12774285/log.txt)
Sorry, hab ich da was falsch gemacht?

**Comment by Tensuko** [comment]
Naja du hättest das alles auch ausfüllen können statt extra beiträge aber okay, ich gucke gleich mal wenn das Video verarbeitet wurde.

**Comment by KarlGutenberg** [comment]
Sorry Danke dir!!

Tensuko ***@***.***> schrieb am Sa. 30. Sept. 2023 um 10:50:

**Comment by Tensuko** [comment]
Komplett falscher Modus.
Bitte lese dir die Anleitung im Spiel durch oder unter courseplay.dev (unten links kannst du die Sprache ändern).

**Comment by regs1980** [comment]
Du hast weder im Hud auf Silo Modus noch hast die Schaufelhöhe angepasste zwecks Kante am Silo.

**Comment by Tensuko** [comment]
Eventuell hilft dir das Tutorial auch weiter:
https://youtu.be/ReLkdjfuHas?si=oe1wviOSReul8U4T

**Comment by KarlGutenberg** [comment]
Falscher Modus?

**Comment by KarlGutenberg** [comment]
Ja, was bin ich auch dumm,
Modus : erster wegepunkt, nächster wegepunkt …..etz.
Danke dir für die schnelle Lösung!

Tensuko ***@***.***> schrieb am Sa. 30. Sept. 2023 um 10:57:

**Comment by KarlGutenberg** [comment]
Aber mit dem schiebeschild kann ich keine höhe einstellen, da haut er auch
vor der kante

Tensuko ***@***.***> schrieb am Sa. 30. Sept. 2023 um 10:57:

**Comment by Tensuko** [comment]
Ganz anderes Problem.
