### ISSUE TITLE
[BUG_SP] Small batch left at obtuse angle corner

### ISSUE THREAD

**Issue by AyakawaSakura** [Courseplay/Courseplay_FS22#282]
**Steps to reproduce**
Set headland on a field with obtuse angles.

**Actual behavior**
Helper left a small batch at the corner.

**Expected behavior**
Helper clear the corner.

**Screenshots**
![Inked20211231213504_1_LI](https://user-images.githubusercontent.com/30264706/147826187-c02fc9b1-312d-4077-a500-06af46d42890.jpg)
![Screenshot 2021-12-31 214258](https://user-images.githubusercontent.com/30264706/147826296-7e6ed6eb-ed8e-4ec1-bf2e-fbf0cc1487ce.jpg)

The batch has been circled out.

**Courseplay version**
Version used: 7.0.0.10

**Log**
No error logged.

**Map**
Elmcreek

**Vehicles/ implements involved**
Axion 960 Terra Trac(Large Tractor)
Rapide 450 Trailed(Spader)

**Relevant script mods**
None

**Comment by Tensuko** [comment]
Round corners...

![round pattern](https://user-images.githubusercontent.com/27344744/147826834-6efc0cb5-842f-458f-85c9-e8b7b6e81c09.png)

![round corners](https://user-images.githubusercontent.com/27344744/147826833-e4abe3c7-1fe5-4b8e-bc27-32830aaf2cc0.png)

**Comment by AyakawaSakura** [comment]
> Round corners...
> 
> ![round pattern](https://user-images.githubusercontent.com/27344744/147826834-6efc0cb5-842f-458f-85c9-e8b7b6e81c09.png)
> 
> ![round corners](https://user-images.githubusercontent.com/27344744/147826833-e4abe3c7-1fe5-4b8e-bc27-32830aaf2cc0.png)

I am pretty sure that I have set the sharp corner in the course generator. Is sharp corner available in FS 22?
