### ISSUE TITLE
[Bug_SP/Enhancement]Do not detect the wrong side of the silo and add shield hight adjustment (like shovel)

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2821]
Siehe Video!
Radlader funktioniert jetzt
Der Traktor schieb und fährt, irgendwohin!
Mache ich jetzt schon wieder was falsch?

https://youtu.be/_PLBCBi_eWU
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12774692/log.txt)

**Comment by Tensuko** [comment]
An sich richtig gemacht, aber das er hängen bleiben nun ja das ist eben das Problem mit den Kanten, vlt überlegen wir uns da auch etwas, ansonsten bleibt nur Boden anpassen.
Das er ab und zu mal die falsche Seite erkennt ist bekannt.

**Comment by KarlGutenberg** [comment]
Es wehr gut, wie beim verladen ein Höhenregler mit ein zu bauen!
Danke dir erstmal und warte auf das nächste Abdate.

Tensuko ***@***.***> schrieb am Sa. 30. Sept. 2023 um 17:31:

**Comment by Tensuko** [comment]
Schildhöhe wurde eingebaut, falsche Seite erkennen müssen wir sehen, hängt vlt hiermit zusammen:
#2772 Daher mache ich hier zu.
