### ISSUE TITLE
OXBO 6030 Sprayer

### ISSUE THREAD

**Issue by TheMarcoSGU** [Courseplay/Courseplay_FS22#2823]
Hi,
I dont know if you already found out whats the problem with the OXBO 6030 sprayer, but i have a idea what is wrong:
The sprayer goes directly when you unfold it in the woking modus (sprayer down).  Courseplay press now V when the sprayer should start to work, but then  the sprayer lift and goes in idle (i dont know how to call it), then it cant spray anymore.
I hope this could help a little

**Comment by Tensuko** [comment]
It is a Giants bug and was reported, nithing we can do about it.
You may also report it so they know it is something they should fix.
