### ISSUE TITLE
[Question]log: An object has been blocking us for a while at 0.5 m

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2824]
Hallo Leute
manchmal hab ich ein Problem auf vulkan islands, das cp geblockt wird und nicht weiterfährt, obwohl scheinbar nichts in der nähe ist:
 
![fsScreen_2023_10_01_09_08_53](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/906faa39-4015-426d-bb28-5f02367283b3)
![fsScreen_2023_10_01_09_08_57](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/8123cf85-51a3-407e-8f00-d5d5a02c72ff)
![fsScreen_2023_10_01_09_09_02](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/590ac173-64b3-473a-8105-003101131add)
![fsScreen_2023_10_01_09_09_09](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/fe189d52-d6a0-4ea2-9969-5ac87e4f2561)
![fsScreen_2023_10_01_09_09_18](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a35c55c5-6df8-4f2b-8e5e-0d97a43b626b)
![fsScreen_2023_10_01_09_09_22](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/9612f9ea-5b17-4d65-a82f-66fd59d1bf18)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12776588/log.txt)

an der Straße kanns nicht liegen, das bit 5 ist deaktiviert:
![ge](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/884a618a-a3dc-44d7-97bf-a395e65f68c8)

an was könnte das liegen?
(bitte nicht gleich schließen, ich weiß das es ein mod-issue ist, würde nur gerne wissen was es sein könnte damit ichs beheben kann)
lg
andreas

**Comment by Tensuko** [comment]
Und welche Geräte sind das?

**Comment by andreasthu** [comment]
in diesem Fall die Kuhn HR 6040 RCS + BTFR 6030 Kreiselegge/Sämaschine mit dem Kuhn TF 1512 Fronttank.
hatte ich aber auch schon mit der Dalbo12,3m Walze ...
lg
andreas

**Comment by pvaiko** [comment]
Warum sind die Proximity Controller Rays nur in dem ersten und letzten Bild sichtbar?

**Comment by andreasthu** [comment]
@pvaiko
was ist der Proximity Controller Rays?

hier mit diversen geräten, mit sichtbaren collis:
![fsScreen_2023_10_01_15_01_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/539734c7-4910-4322-bc6d-f15ad0b69edd)
![fsScreen_2023_10_01_15_03_00](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/b334181f-9595-466c-8b4c-4f85fb2bd48b)
![fsScreen_2023_10_01_15_04_24](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/72c4c768-6a55-4b43-b03c-f7a63125c3fb)
es wird scheinbar "eine große box" um den Traktor erzeugt, schalte ich CP aus, ist diese box auch weg
lg
andreas

**Comment by pvaiko** [comment]
> Warum sind die Proximity Controller Rays nur in dem ersten und letzten Bild sichtbar?

Um meine Frage zu beantworten: weil die nicht in jeder Frame gezeichnet werden. Das muessen wir ändern, auch irgendwie blockierende Objekte sichtbar machen.

**Comment by pvaiko** [comment]
> @pvaiko was ist der Proximity Controller Rays?

Die grüne Linien vor dem Fahrzeug. Wenn die gelb/rot werden dann ist ein Hindernis da wo die enden. Siehst do so was?

**Comment by andreasthu** [comment]
nein, die blinken, ev sind sie beim drücken der screenshat taste grade weg

btw, hab hier noch den dropbox link
https://www.dropbox.com/scl/fi/vk7exi7r3rsb7ic7m1y2b/f-rTensuko.zip?rlkey=68gg4b3uulvoi4mhrqlg856r8&dl=0
(von meinem vorigen problem)  da sind die cp-kurse, map und savegame drinnen
wenns hilft
lg
andreas

**Comment by andreasthu** [comment]
Proximity Controller Rays sind grün, trotzdem blockt da was:
![fsScreen_2023_10_02_09_15_14](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/15420d83-2164-430d-932c-5a9a44c33689)
lg
andreas

**Comment by Tensuko** [comment]
There must be something.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/a217e5da-c1f8-4cd1-8361-c4b99dd9f138)

**Comment by andreasthu** [comment]
habs jetzt mit der walze getestet:
![fsScreen_2023_10_02_18_40_14](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/14425353-bd3f-4396-90dc-744967041fcb)
stoppt auch, aber an anderer stelle. alle strahlen grün und gleich lang.
btw was ist der weiße punkt vor dem 2.u3. rechtem strahl?
wenn ich den abfahrer entlasse ist er weg:
![fsScreen_2023_10_02_18_42_32](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/7fbfe849-c230-4225-940f-a6a4d66d3dfd)

es gibt, während cp aktiv ist, auch eine große collibox um das Fahrzeug:
![fsScreen_2023_10_02_18_40_31](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/37a1ee1e-d801-4e21-998e-a0377af9793c)
ev stört diese Box die Bäume am linken Rand?
entlasse ich den cp-fahrer ist die box auch weg:
![fsScreen_2023_10_02_18_47_08](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ac15955e-7ed6-4e48-99df-d9659f0bbc4a)
hab keinen schimmer, keine colli da in der nähe und trotzdem ein stop
lg
andreas

**Comment by pvaiko** [comment]
CP erstellte keine collision boxes. Das sind die von Giants, und soweit ich weiss, dienen dazu, den Verkehr zu stoppen.

**Comment by Tensuko** [comment]
Und wenn die das Problem wären, würde sich kein CP Fahrer von der Stelle bewegen.

**Comment by Tensuko** [comment]
Loch unter der Straße in der Landschaft.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/9fc99c86-77bb-47dd-92f3-6f1b6b25f862)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/bb482a19-ad61-4065-b1ac-1b6e77b80b59)

**Comment by andreasthu** [comment]
Na im ernst?
Das gibts doch nicht, aber dann weiß ich zumindest wie ich es beheben kann.
Lg
Andreas

**Comment by Tensuko** [comment]
Ich nehme mal an, dann ist das für dich erledigt.
