### ISSUE TITLE
Could you / is it possible to change the trigger for tractor drive to combine?

### ISSUE THREAD

**Issue by marcelmmx** [Courseplay/Courseplay_FS22#2825]
Hi, I have noticed that when a tractor is waiting to unload a combine - it waits for the pipe to unfold to start driving. I have had countless issues with this - if the the combine unfolds the pipe while on the headland it usually gets stuck on a tree/power pole or other object. This also happens frequently when driving around poles in the middle of the field. Would it be possible to tie this action something else - like active havester beacon? That would also be more realistic - nobody in real life extends the pipe to request a cart driver. Thanks for considering my suggestion.

**Comment by Tensuko** [comment]
That is not CP, that is AD.
`
function AutoDrive:combineIsCallingDriver(combine)	--only for CoursePlay
	local openPipe,_ = ADHarvestManager.getOpenPipePercent(combine)
	return openPipe or ADHarvestManager.doesHarvesterNeedUnloading(combine, true)
end
`
For me personaly I removed that one from AD code in ExternallInterace.lua in Line 211-214

**Comment by marcelmmx** [comment]
Thank you, that solves my problem.
