### ISSUE TITLE
[BUG_SP] Helper stalls after finishing first row

### ISSUE THREAD

**Issue by AyakawaSakura** [Courseplay/Courseplay_FS22#283]
**Steps to reproduce**
The course is east-west direction. Helper stops doing anything after finishing the first row.

**Actual behavior**
Helper stalls after finishing first row. Log shows `C:/Users/*****/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/pathfinder/State3D.lua:224: bad argument #1 to 'ipairs' (table expected, got nil)`

**Expected behavior**
Helper enters turning.

**Screenshots**
![20211231225024_1](https://user-images.githubusercontent.com/30264706/147829105-e8791054-16b0-4fe2-8cb5-26eab2324c67.jpg)

![20211231224622_1](https://user-images.githubusercontent.com/30264706/147829118-5e283bf4-e333-43f3-8899-617b2fa99273.jpg)
These boxes flashed for a second and disappeared.

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796455/log.txt)

**Map**
Elm creek

**Vehicles/ implements involved**
Axion 960 TERRA TRAC(large tractor)
MEGA 1200L(Sprayer)

**Relevant script mods**
None

**Comment by AyakawaSakura** [comment]
Update:
After disabling most of the vehicle mods It looks like the helper will not stall again. I am not sure which vehicle mod is causing the problem(they shouldn't).

**Comment by AyakawaSakura** [comment]
I thought it was a mod conflict but it is not. I disabled all mods except courseplay but this problem still exists. But this time the helper keeps going forward until it is blocked by a tree. Here are the screenshots and the log file.
![20211231232354_1](https://user-images.githubusercontent.com/30264706/147830421-456fbf9b-1628-4a10-b575-fac8212c1901.jpg)
![20211231232356_1](https://user-images.githubusercontent.com/30264706/147830424-c8ee09f0-c03f-4c88-9b34-b899d3b77b97.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796517/log.txt)

**Comment by RealNeo80** [comment]
Dismiss AI Helper, seems that you start the Giants Helper instead of CP Helper, try to go over the CP Menu to start the helper and test it

**Comment by AyakawaSakura** [comment]
> Could it be that you start the Giants Helper instead of CP Helper, try to go over the CP Menu to start the helper and test it

thanks for the reply. For both tests I started the helper from the new mini hud so it should be the cp helper running.
I started from the first waypoint in the first test, and the helper stalls after finiahing the first row. Then I disabled most of the mods and tried again. The helper finished the first and second rows, then drove forward aftee the third row. I tested multiple time by driving the vehicle manually to the middle of the third row and start from the nearest waypoint from the mini hud. The problem occured every try.

**Comment by Tensuko** [comment]
That is our pathfinder. It tries to find a path to turn.
You should do one headland and problem should be gone.

**Comment by pvaiko** [comment]
Or activate "turn on field".

**Comment by AyakawaSakura** [comment]
Update:
Regenerating the course with one headland and activating "turn on field" solves the issue. But I am not sure if the solution is from regenerating the course with one headland because I can recall that this issue occurred on one-headland course. I will try providing the log and screenshots if that appends.

**Comment by AyakawaSakura** [comment]
Update:
The problem re-occurred on a headland course. The helper drove forward after it finished a row. This happened after the headland is finished. The problem reoccurs after I drive the vehicle to the middle of the row where the problem happens and start the work from the nearest waypoint.


Screenshots:
![20220101110607_1](https://user-images.githubusercontent.com/30264706/147843186-00e05dd8-a5cd-4649-9b3f-bc41f058ad41.jpg)
![20220101110610_1](https://user-images.githubusercontent.com/30264706/147843187-55a2c2f0-8d5e-4ec2-b2c7-2086b1ccf527.jpg)
![20220101110616_1](https://user-images.githubusercontent.com/30264706/147843189-54b35182-faeb-49cc-ad6f-e9a37890b1b3.jpg)
![20220101110706_1](https://user-images.githubusercontent.com/30264706/147843190-1b4d36cb-66f3-4838-b72c-ab6b4b9360fd.jpg)
Here shows the handland course.
![20220101110712_1](https://user-images.githubusercontent.com/30264706/147843191-23811a4c-4360-4292-a111-1c8d3034e8e0.jpg)
Turn on field is activated.

Vehicle involved:
MF3670(Medium tractor)
ChopStar 5-90 + Row-Guard(Weeder)

Log:

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7797344/log.txt)



Mod:
Only CP is loaded

**Comment by AyakawaSakura** [comment]
After one problem occurs on the row, it seems that rest of the rows with the same direction as the problematic row are affected by this bug. The helper keeps going forward while showing a "glitching" behavior. Heres a figure to help understanding.
![Screenshot 2022-01-01 113358](https://user-images.githubusercontent.com/30264706/147843394-d922e250-79e4-43b8-b048-7f1ec13c620c.jpg)

Here is the log with multiple tries:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7797349/log.txt)

Vehicle affected:
MF3670(Medium tractor)
ChopStar 5-90 + Row-Guard(Weeder)

**Comment by AyakawaSakura** [comment]
Also I discovered that once the bug occurs, it also affect the unfinished rows with the same direction. Here is a figure:
![Screenshot 2022-01-01 114350](https://user-images.githubusercontent.com/30264706/147843491-378a8f8b-8aa4-43a2-8aa4-38c6f8970b39.jpg)

**Comment by AyakawaSakura** [comment]
Generating a new course does not help. The helper cannot enter turning at the location where the bug occurs before. Here is the log
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7797355/log.txt)
:

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
