### ISSUE TITLE
[Question] Hintergrundfarbe Texteingabefeld / Text Input Field Background Color

### ISSUE THREAD

**Issue by Onkel2000** [Courseplay/Courseplay_FS22#2831]
Hallo,

Ich habe eine Frage, da ich sehr Seheingeschränkt bin. Wäre es für euch irgendwie möglich den Hintergrund des Texteingabefeldes z.b. beim Kurs speichern, etwas dunkler zubekommen, so dass sich die helle Schrift besser abhebt? Es ist wirklich nur dort ein Problem für mich.

Mehr Infos dazu im AD Github, da ich dies dort auch angesprochen habe. Sie haben eine tolle lösung gefunden. Vielleicht habt ihr auch eine Idee.

https://github.com/Stephan-S/FS22_AutoDrive/issues/991

LG

**Comment by Tensuko** [comment]
Wir schauen mal was wir da machen können.

**Comment by pvaiko** [comment]
I think this would be relatively easy, we already have our own GUIProfile.xml where all these things are defined, we could overwrite the text input box background color with that, depending on some config value for instance. I don't have the bandwidth to figure this out now, @schwiti6190 is more comfortable with the GUI anyway...

**Comment by schwiti6190** [comment]
@Onkel2000 Hallo,

du kannst dir diesen Mod anschauen mit dem kannst du die Hintergrund Farben der Dialoge(z.b. Texteingabefelder usw) änderen.
Das betrifft dann aber auch alle Dialoge vom Giants Spiel und evtl. andere Mods. 
Eine reine Courseplay Lösung würde ich ungerne einbauen.

[FS22_ColorCorrection.zip](https://github.com/Courseplay/Courseplay_FS22/files/12840475/FS22_ColorCorrection.zip)

Mit folgenden Befehlen kannst du die Farbe oder nur das Alpha(Durchsichtigkeit des Hintergrunds) anpassen:

`ColorCorrectionChangeColor 0 0 0 0` <- Zahl von links nach rechts: Rot(0-255) Grün(0-255) Blau(0-255) Alpha(0-1)
`ColorCorrectionChangeAlpha 0` <- Alpha(0-1)
`ColorCorrectionRestoreColor` <- Setzt alles wieder zurück
`ColorCorrectionGetCurrentColor` <- Gibt die aktuellen Farben von den Dialogen aus
 
Gerne Feedback ob dir das soweit geholfen hat :)

**Comment by Onkel2000** [comment]
@schwiti6190 Hey, hast du für micht jetzt extra ein Mod gemacht? Ich werde es nacher  auf jedenfall testen, und werde berichten. Danke schon,al für Eure Mühe! :)

**Comment by Onkel2000** [comment]
@schwiti6190 Also ich habe denn change Color Befehl in der Konsole, mit verschiedenen Werten ausprobiert. Ich gehe davon aus, dass 0 0 0 0 tiefes Schwarz ist. Da mir die RGB Webseite bei Schwarz 3 3 3 raus kam.

Es erschien dann auch immer ein Fenster mit einem Sample Text. Aber es gibt keinerlei veränderung. Mach ich etwas falsch?

**Comment by Onkel2000** [comment]
@schwiti6190 Genau damit hab ich es auch versucht. Leider bleibt beim Kurs speichern Textfeld, alles wie es ist.

Hier einmal die [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12844203/log.txt)

**Comment by schwiti6190** [comment]
@Onkel2000 Ich sehe gerade das die Farbe schon standartmäßig Schwarz(0 0 0) ist nur nicht mit niedrigeren Alpha.
Würde es dir sonst eher helfen die Text Farbe anzupassen?

**Comment by Onkel2000** [comment]
@schwiti6190 Kein Problem, lass dir Zeit. Vielen Dank für deine Mühen! :)

**Comment by schwiti6190** [comment]
[FS22_ColorCorrection.zip](https://github.com/Courseplay/Courseplay_FS22/files/13078039/FS22_ColorCorrection.zip)

Damit wird das Farben ändern von text inputs deaktiviert.
Der Befehl lautet: `ColorCorrectionToggleInputTextHighlighting`

**Comment by Onkel2000** [comment]
@schwiti6190 Tausend Dank dir! Es funktioniert, endlich kann ich wieder Kurse speichern.
Wirklich vielen Dank, dass du dir für mich solche gedanken gemacht hast und es umgesetzt hast. ;)

**Comment by schwiti6190** [comment]
@Onkel2000 Gerne :)
Wenn sonst nochmal was ist gerne wieder melden.
