### ISSUE TITLE
Shovel top-hight adjustment

### ISSUE THREAD

**Issue by Empgor** [Courseplay/Courseplay_FS22#2832]
We run in an issue using the wheel-loader for filling a cow-stable bunker i.e. with hey.
There is no problem with picking up hey and finding the unload trigger.
But the helper will always lift the shovel to its maximum and can't enter the stable, due to collision with the stable roof.

Since there is already a low-hight adjustment, i would request a top-hight adjustment aswell.

Alternatively this function could somehow be limited to the selected unloading station.

I didn't find any similar request or already existing issue.
But if there is feel free to move or delete.

**Comment by Empgor** [comment]
![cp_issue_2832](https://github.com/Courseplay/Courseplay_FS22/assets/147033528/b9f3f9db-8cc7-4b1c-bffc-a9d351f450cd)

**Comment by Tensuko** [comment]
We want to collect those requests here: #2783

**Comment by Empgor** [comment]
Should I comment my request in the mentioned #issue? Or is your reference enough?
Because it's marked as closed

**Comment by Tensuko** [comment]
Think like this is enough, we can look up the linked one
