### ISSUE TITLE
[BUG_SP] Slurry spreaders charging for slurry during headland turns

### ISSUE THREAD

**Issue by Dustinc95** [Courseplay/Courseplay_FS22#2835]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Attach slurry implement. Select either "buy" or "cow barn(if using cows)" in game settings-AI workers. Generate course with sharp headlands. Start courseplay.

**Actual behavior**
During the sharp headland turns while slurry injectors are raised you will still deplete storage /be charge for slurry.

**Expected behavior**
If slurry injectors are raised then fill level should not change.

**Screenshots**

**Courseplay version**
Version used: 7.3.0.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12838279/log.txt)

**Map**
Spruce Mountain Farm

**Vehicles/ implements involved**
Which vehicle or implement?
Oxbo 5105+Trac-Pak
Mod? No, But official DLC

**Relevant script mods**
Precision Farming

**Comment by Dustinc95** [comment]
Disabling the Ai buy/storage options and manually filling the slurry spreader does not deplete fill level.

**Comment by Tensuko** [comment]
The problem might be that this is the Giants bug.
As some ppl and I found out that, even the Giants Helper does charge for seeds and stuff while not even working.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/76f2f59c-8de0-4704-8cb9-c9480d35c3fe)
