### ISSUE TITLE
[BUG_SP]harvester harvesting between generated route

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#284]
**Steps to reproduce**
wait until the full bunker in the combine is then emptied and connected exactly between the generated route

**Actual behavior**
-

**Expected behavior**
drive along the generated route

**Screenshots**
![image](https://user-images.githubusercontent.com/96631209/147833926-17fbfabe-0b97-4635-99f5-16b0083ed991.png)

**Courseplay version**
7.0.0.10

**Log**
not error

**Map**
Papenburger_Map last ver.

**Vehicles/ implements involved**
harvest x9  mod 

**Relevant script mods**
Mods like Autodrive,CP

**Comment by Manyak007** [comment]
the error probably only occurs with the line

**Comment by Matzenie** [comment]
Hello, 
I have had the problem twice with the X9, wanted to test it again with an Ideal before I report it. The error occurs after unloading in the first headland. The Harvester drives a bay. After that, he can no longer get back on track.

DE:
Hallo, 
ich habe das Problem jetzt auch 2x gehabt mit dem X9, wollte es nochmal mit einem Ideal testen bevor ich es melde. Der Fehler entsteht nach einem Abtank-Vorgang im ersten Vorgewende. Dabei fährt der Drescher ja eine Bucht. Danach kommt er nicht mehr zurück in die Spur.

**Comment by hanrahs** [comment]
I have had this problem also, using other harvesters (definitely the JD 790, another one as well but I can't recall which it was)

**Comment by disturbed-simulations** [comment]
I've had this issue using the large claas combine, also on the first headland

**Comment by jobyrns72** [comment]
Same problem here. Gets to 95 percent then back up then gets over but doesn't cut out the pocket then after it is unfilled cuts in between the rows

**Comment by Tensuko** [comment]
Newest Version and logfile with turned on debug for that vehiclle (scroll down in the vehicle settings).
