### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mikeatworkgp** [Courseplay/Courseplay_FS22#2841]
hallo, ich spiele gleichzeitig auf zwei unterschiedlichen karten und habe CP und AD auf beiden karten. Auf einer karte beim  rechts click auf die Mouse taste geht immer CP an auch wenn ich in AD in der Modifikation Modus bin. Auf der andern karte aber nicht, kann mir jemand helfen? danke

**Comment by Tensuko** [comment]
sind das 2 verschiedene mods Ordner?
logfile?

**Comment by mikeatworkgp** [comment]
nein ein einziger ordner

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/12871703/log.txt)

**Comment by tn4799** [comment]
schick am besten auch noch deine input bindings.xml.
und verwendest du auf beiden karten die gleichen mods? falls nein, was sind die unterschiede bei den mods?

**Comment by Tensuko** [comment]
Warum ist die .zip von CP nicht normal benannt?
Available mod: (Hash: 06abe1e6ea42e3d440a4e90fa159ac50) (Version: 7.3.1.2) Courseplay_FS22

Download Quelle da und nirgendwo anders (maximal modhub)
https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by mikeatworkgp** [comment]
ich habe den ersten download von der taste Code gemacht deshalb ist der name anders
[inputBinding.txt](https://github.com/Courseplay/Courseplay_FS22/files/12903046/inputBinding.txt)
