### ISSUE TITLE
Multiple Trailers For Trucks[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2844]
**What is the problem this feature/enhancement solves?**
Trucks dont really get used as much as they could be... this enhancement make it so trucks can run more trailers such as the Distinction super-B road train trailer

**Describe the solution you'd like**
much like the setting to add the automatic cutter attach on a combine there could be a setting on a truck to add more trailers

**Describe alternatives you've considered**
an alternative could be having Courseplay detect if there is a dependent implement like the power harrows and seeders

**Additional context**

**Comment by Tensuko** [comment]
Won't be supported due to not able to drive in reverse.

**Comment by FrozenStorm1029** [comment]
not for field work but just like the loader setting for combine unloaders

**Comment by Tensuko** [comment]
Thats exactly what I said.
Combine unload or Loader unload is not supported with multiple trailer for that reason.
