### ISSUE TITLE
[Question] When using another Mod with courseplay

### ISSUE THREAD

**Issue by schwyl** [Courseplay/Courseplay_FS22#285]
I'm using FS22 Peterbilt 379 dump truck v2.0.0.0 mod.

My only option for workers is the GOTO. Now what is this mod missing that allows it to work with courseplay and the Giants AI?

I don't want you to fix it but maybe point me in a direction so that I may try to fix it myself

Cheers

**Comment by Tensuko** [comment]
The question is what you want to do ?
We only have Fieldwork for now and you need tool attached.

**Comment by schwyl** [comment]
I apologize.

Im trying to figure out what is missing from the mod that allows the AI to perform load and deliver functions.

Was hoping you knew what direction to point me to

**Comment by alex2ruote** [comment]
That's what Autodrive is for. Courseplay is dedicated to fieldwork.

**Comment by schwyl** [comment]
> That's what Autodrive is for. Courseplay is dedicated to fieldwork.

With both auto drive  and courseplay installed It doesn't give me the option to create a load and deliver.

**Comment by alex2ruote** [comment]
Autodrive is its own thing, at the moment isn't working with Courseplay yet. There are videos on YouTube explaining how it works, which is not through the helper interface.

**Comment by Tensuko** [comment]
Courseplay right now is only Fieldwork + we stay on the field for now. Later ofc stuff like Loading wagon and refill.

**Comment by schwyl** [comment]
Sorry,

Maybe these two pictures will show what im asking

![nonmod](https://user-images.githubusercontent.com/2615447/147841951-7a898456-c1e1-45e9-89c2-f6f36d6f1eeb.jpg)
![peter](https://user-images.githubusercontent.com/2615447/147841952-f0246e40-10c1-4640-b430-49db0a02652c.jpg)


The first picture is with stock truck and trailer and the second one is from a mod. What is missing from the mod that won't allow it to be used like the non modded one

**Comment by haamic** [comment]
This is the internal Giants helper. This has nothing to do with CP or AD. The MAN is supported and the load and deliver mode is offered. The Peterbilt is probably not supported.  What is missing from the mod so that the mode is displayed, I can not say. Here it is only about CP and its possibly still existing errors.

**Comment by schwyl** [comment]
Yes im aware this isnt a CP issue or anything but I was hoping with the knowledge of CP they would be able to direct me to a document that I could explore and figure out why some mods work with AI out of the box and Others dont
