### ISSUE TITLE
Silo laden

### ISSUE THREAD

**Issue by Maritn76** [Courseplay/Courseplay_FS22#2850]
Hallo zusammen, 

ich habe eine frage zum Laden von Silage zu einer BGA. Der Radlader läuft schlecht hält den Kurs nict und ich muss immer wieder den Kurs neu setzen. 

Meine frage ist, gibt es da nur bestimmte Silos die man benutzen kann?

**Comment by Tensuko** [comment]
Zu wenig Infos um dir da genauer helfen zu können

**Comment by Maritn76** [comment]
Das Problem ist das der Radlader nicht den Kurs speichert und ich muss immer wieder den Kurs neu einfahren Gesendet mit meinem iPhone Am 13.10.2023 um 19:23 schrieb Tensuko ***@***.***>:﻿
Zu wenig Infos um dir da genauer helfen zu können

**Comment by ct177mak** [comment]
eingefahren wird da schon mal garnix ,Zielpunkt setzen ,den Punkt welches Silo angefahren wird ,und wo abgeladen werden soll ,sei es ein Anhänger der in der Nähe ist oder ein Abladepunkt z.B BGA Bunker oder sowas.

**Comment by Tensuko** [comment]
Anleitung lese! Nichts wird da eingefahren.
