### ISSUE TITLE
[Question] how do i get to it?

### ISSUE THREAD

**Issue by SMINEKID** [Courseplay/Courseplay_FS22#2852]
is it a file i open, is it a website!?!?! pls tell me!!!! and if its a file i need to download and open, then how am i gonna open it?!?!?!? bc IDK!!?!?!?!?!

**Comment by Tensuko** [comment]
And IDK what you talk about!!!???

**Comment by SMINEKID** [comment]
WDYM!?!??!

**Comment by SMINEKID** [comment]
im just asking how i play it! is it a link? is it a file i need to download? JUST HOW DO I START PLAYING IT?!?!!?!?!?!?
