### ISSUE TITLE
[BUG_MP] Play/Start job Button not working

### ISSUE THREAD

**Issue by Anubisss161** [Courseplay/Courseplay_FS22#2855]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Open Hud
Select CP fieldwork
Generate Course
Press Start Job

**Actual behavior**
Nothing Happens

**Expected behavior**
Fieldwork Begins

**Screenshots**
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/88384659/33eb424c-da07-459b-a62d-4b3931486ef5)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/88384659/b044b95c-55cc-4c84-924c-f51ed5df412f)
Start job AND the play button dont work
**Courseplay version**
Version used: 7.3.00

**Client Log**
[Log](https://pastebin.pl/view/238782f5)

**Server Log**
Please attach a log from the server with all debug channels active, 

**Player on the server**
3 Players

**Dedicated server or local hosted server**
Dedicated

**Map**

no mans land

**Vehicles/ implements involved**
Which vehicle or implement? Module Express 635
Mod yes/no ? N

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
@schwiti6190 
Error in log, not sure if new version will fix that.
2023-10-15 00:35 Error: Running LUA method 'update'.
C:/Users/povod/OneDrive/Dokumenti/my games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CourseDisplay.lua:251: attempt to index field 'course' (a nil value)

**Comment by schwiti6190** [comment]
@Anubisss161 This bug is probably fixed with the current github release
