### ISSUE TITLE
[BUG_SP] Kurserstellung mit eigenem Feldrand bricht ab

### ISSUE THREAD

**Issue by X-TheUser-X** [Courseplay/Courseplay_FS22#2856]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Feldrand selbst im Editor erstellt und abgespeichert, dann versucht damit einen Kurs zu generieren. 

**Actual behavior**
Es kann kein Kurs generiert werden.

**Expected behavior**
Mit dem selbst erstellten Feldrand sollte CP einen Kurs erstellen, um dann damit arbeiten zu können.

**Screenshots**
[https://ibb.co/jVXmh6t](url)

**Courseplay version**
7.3.1.2

**Log**
> 2023-10-15 04:30 :00 [info lp21789] Scanning field 0 on Frühling 2K23, prefer custom fields true
2023-10-15 04:30 :00 [info lp21789] FieldScanner: Could not trace field edge, limit search to field 0 and retry
2023-10-15 04:30 :00 [info lp21789] Custom field found: CP-1
2023-10-15 04:30 :00 [info lp21789] T25 T/355: disabling island bypass on custom field
2023-10-15 04:30 LUA call stack:
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/CourseGeneratorInterface.lua (99) : printCallstack
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/headland.lua (319) : __index
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/track.lua (148) : linkHeadlandTracks
  =[C] (4294967295)
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/CourseGeneratorInterface.lua (98) : xpcall
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/jobs/CpAIJobFieldWork.lua (199) : generate
  =[C] (4294967295)
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (252) : xpcall
  =C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CpAIFrameExtended.lua (245) : try
  dataS/scripts/gui/elements/ButtonElement.lua (762) : raiseCallback
  dataS/scripts/gui/elements/ButtonElement.lua (475) : sendAction
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (612) : mouseEvent
  dataS/scripts/gui/base/Gui.lua (666) : mouseEvent
  dataS/scripts/events.lua (26) : mouseEvent

**Map**
Frühling 2K23

**Vehicles/ implements involved**
[https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=248144&title=fs2022](url)

**Relevant script mods**
VCA

**Comment by Tensuko** [comment]
Screenshot vom Feldrand?

**Comment by Tensuko** [comment]
Bitte direkt hier posten und nicht über solche Links.....

**Comment by Tensuko** [comment]
Vermute das gleiche Problem wie hier: #2808
Duplicate.
