### ISSUE TITLE
Strautmann Magnon Pickup Wagon ?

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#286]
How come I can't use CP to create a course, or load a saved course for a tractor towing a pickup wagon. If you open Create Job, CP isn't listed as an option. Tried to use a JD 7R and Strautmann Magnon wagon, CP was available as an option. Essentially in 17 and 19 using CP, you could be in any type of vehicle, and load a course you had saved, didn't matter what the course was originally created for. When I try to load my saved course used to mow a grass field, to use the pickup wagon, I got the below error.

"Target location is not a course" .

**Comment by rohne83** [comment]
Afaik as of now it's only possible for vehicles/implements where also Giants helper is available. This will change of course back to what we're used to, but will ofc need some time.

**Comment by Tensuko** [comment]
Pickup Wagon are not supported yet. Will come later.
