### ISSUE TITLE
[BUG_SP]Courseplay not folding at the end of the course or for refueling. Info text also not cleared with Autodrive.

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/Courseplay_FS22#2865]
Hallo,
ich Spiele auf der NF Marsch ohne Gräben Version 3.7.1 . Ich habe das Problem das immer wen eine Sämaschine leer ist AD losfährt  zum nachladen ohne das Gerät vorher zusammen zu klappen. Ich dachte es ist ein Mod schuld  ich habe das auf der Erlengrad versucht  ohne Mods (nur mit CP und AD) das selbe  Problem. Könnt ihr mir sagen was ich da ein stellen muss?

**Comment by RudiBergfeld** [comment]
Entschuldigung
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13033664/log.txt)

**Comment by Tensuko** [comment]
In AD Geräte einklappen aktiviert?
Bei mir gehts und ich habe nichts groß eingestellt in AD.

**Comment by webwibo** [comment]
Hallo zusammen und vielen Dank für eure Bemühungen CP immer auf den neuesten Stand zu bringen.
jetzt habe ich nach dem Update auf CP 7.3.1.3 folgende Probleme festgestellt:

Ein Problem mit Sämachine die nicht einklappt wenn CP an AD übergibt (wie im Post oben geschrieben)
Ein Problem mit Güllefässern, die ihre Schleppschläuche nicht einklappen bei der Übergabe von CP nach AD.
getestet mit:

 Pöttinger Terrasem C6F          Sämaschine
 New Holland T 7.275 HD
 
 Claas Axion 860
 Veenhuis Premium integral 20000 Güllefass mit Bomech MultiProfi Güllefass
 
 Landbauer x 8.631
 Farmtech polycis1550 Güllefass.

Bei den Güllefässern werden die Schleppschläuche nur angehoben.
 
Ad Version ist AD 2.0.1.4
Map Department Haut Beyleron  4 fach ohne Ampeln

mit der CP Version CP 7.3.1.2 tritt der Fehler nicht auf.

**Comment by Tensuko** [comment]
Sind das alles mods?
