### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Legion68** [Courseplay/Courseplay_FS22#2868]
Warning: Duplicate l10n entry 'CP_ai_taskDescriptionUnloadingToTrailer' in 'C:/Users/User/Documents/My Games/FarmingSimulator2022/pdlc/FS22_Courseplay/translations/translation_de.xml'. Ignoring this definition.

**Comment by tn4799** [comment]
What is your Question?

**Comment by Legion68** [comment]
Steht doch da Warnung in der Log Datei

**Comment by Legion68** [comment]
> Steht doch da Warnung in der Log-Datei



> Was ist deine Frage?

Steht doch da Warnung in der Log-Datei
