### ISSUE TITLE
Plow should not be rotated on headland turns

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#287]
**Steps to reproduce**
Create course with 4 headlands sharp passes, start course

**Actual behavior**
First headland row goes fine, when turns on first turn, it turns the plow into folded position. then the plows stays when going down the side.

**Expected behavior**
Plow Rotates and lowers properly

**Screenshots**

![fsScreen_2021_12_31_22_48_47](https://user-images.githubusercontent.com/96673100/147844236-0d1c93cc-8a10-43ff-a9d7-5fcc1d0ded31.png)

**Courseplay version**
Version used: 7.0.0.10

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7797386/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Fendt 1050 / Kverneland PW 100 - 12

**Relevant script mods**
AD

**Comment by Resandise** [comment]
Just an FYI, after the plow acted up, I used the same tractor and put on a Subsoiler, but the offset did not reset, so it started pulling the subsoiler with the plow's offset.  I did not notice until it was half way though the field.  Had to restarted it, since it left lines all over the place.

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.

**Comment by Nevsix** [comment]
Tut mir leid, dass ich hier in deutsch schreibe aber ich kann nicht so gut Englisch schreiben :/

Ich habe mit der 7.0.0.12 noch immer das Problem, dass er ab und zu nicht den Pflug drehen will. Ich hatte ein Feld angefangen und mitten drin die Version geupdatet. Nach der 3. Bahn hat er es dann hinbekommen jedoch die letzte Bahn hat er wieder nicht gewendet.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7804454/log.txt)
