### ISSUE TITLE
[BUG_SP]left the course

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2871]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Cut 6 lands with 45ft header on field 67 The oaks

**Actual behavior**
combine proceeded to the next lands block and lost it's path. Repeated this twice now on this field, the same happened last harvest.

*Also seeing unloaders drive into telegraph poles in the field, they don't appear to detect them and move around them when heading to a combine to unload on a straight path - although I didn't have logs on at that point and haven't been able to capture it again, but I've seen it happened 3 times tonight when I came back to the field

**Expected behavior**
Combine continues to the last land block

**Screenshots**
![fsScreen_2023_10_19_21_45_08](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/a4b9deb6-5ce4-432a-8fd1-50fe95e67755)

![fsScreen_2023_10_19_21_45_14](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/32373bf9-0663-4c2e-ae98-89c13dd39c27)

![fsScreen_2023_10_19_21_45_37](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/8ce220d6-5bee-460d-a836-3f90f1fc8c02)

**Courseplay version**
Version used: 7.3.1.3

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13047694/log.txt)

**Map**
The oaks

**Vehicles/ implements involved**
Which vehicle or implement? Giants CR10.90 & Giants Superflex Draper 45ft header
Mod yes/no ? no

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Poles problem cant be fixed.

Left the course -> need the log with debug.

**Comment by coatsy35** [comment]
> Poles problem cant be fixed.
> 
> Left the course -> need the log with debug.

Ok I understand about the poles now. The left the course picture is the path problem in the log attached where it can’t move to the last block. All three pics are the same issue

**Comment by Tensuko** [comment]
Okay, but that is very strange. It should have a normal pathfinder turn to the next row.

**Comment by coatsy35** [comment]
Yes agreed. It finishes the block and then can’t find the route to the next block, it heads towards it and then says the left the course eventually before it gets to it

**Comment by Tensuko** [comment]
Are the pics after each other? Like the first one is just before the last? If so then the island is the problem.

**Comment by coatsy35** [comment]
Yes the pictures are in order

**Comment by Tensuko** [comment]
The reason depends on this issue -> #2605
Closing.
