### ISSUE TITLE
[Feature]  I believe i speak for alot of people when i say we NEED this :)

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2873]
**What is the problem this feature/enhancement solves?**

I'm frustrated Because the Truly wonderful people at the Courseplay dev team add all the amazing stuff for wheel loaders and other bucketed machines to load and level silage bunkers. And yet we have no forage harvester unloader?

**Describe the solution you'd like**

Add a feature to select the type of unloader such as combine , loader or forage

**Describe alternatives you've considered**

A possible alternative is having the normal combine unloader detect what type for fruit can be loaded in different types of trailers and have it correspond with the type of combines

**Comment by JDTiger** [comment]
That is (unofficially) beimg worked on. Works quite well but is not up to the standart of the CP team

https://github.com/Courseplay/Courseplay_FS22/issues/2754

**Comment by Tensuko** [comment]
Also on todo on our list, but later.
Duplicate, closed.
