### ISSUE TITLE
Unloading Tiger 6XL, loader doesn't reverse to find clear path when blocked [BUG_SP]

### ISSUE THREAD

**Issue by simonIOW** [Courseplay/Courseplay_FS22#2874]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Set the unloader to collect from combine on field.

**Actual behavior**
Unloader sits just behind combine, rather than alongside.  

**Expected behavior**
Unloader recognises it is blocked, and reverses to try again

**Screenshots**
<img width="1280" alt="Screenshot 2023-10-20 074433" src="https://github.com/Courseplay/Courseplay_FS22/assets/39086148/7423ec1f-62ef-440c-93c1-1f2f4ea9d728">

**Courseplay version**
Version used: 7.3.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by simonIOW** [comment]
I don't know if it's linked (probably not :) ) but seeing similar behavior of vehicles getting blocked elsewhere too.  I might drop this one into the wheel loader list!

<img width="1280" alt="Screenshot 2023-10-20 221147" src="https://github.com/Courseplay/Courseplay_FS22/assets/39086148/03a8eecf-0030-4714-874f-da1e8f64c997">

**Comment by rohne83** [comment]
Quick fix: set tool offset horizontal to a low value (i.e. sth like -1m). The unloader will drive more to the left then and thus won't get blocked, and everything runs smoothly.

**Comment by Tensuko** [comment]
Can you describe how this situation happened?
I can't get this to happen.
My unloader drives perfectly under the convayer.

**Comment by simonIOW** [comment]
Unloader follows behind combine, but when the combine stops. the unloader sits behind it.

Even when cancelling, moving the unloader, and starting the job again, it would follow the same behavior.

It had done half the field without an issue, then it started doing this.

The log says it's moving away from other vehicle, but it just sits there, so is there a corrective action needed?

I did try adjusting horizontal offset, but made no difference.  For me I think the issue here is not that it's not unloading, it's that it doesn't react to being blocked.

**Comment by Tensuko** [comment]
It should notice that he is not in a good position to unload.
Then try to drive there again but he is maybe too close already and try to unload again.
Would need a logfile with debug on when this is happening and post it here https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by simonIOW** [comment]
https://gist.github.com/simonIOW/f15136d4cd392b007e0d86cdb8906840

<img width="1280" alt="Screenshot 2023-10-27 165729" src="https://github.com/Courseplay/Courseplay_FS22/assets/39086148/951ab9fd-3cf6-461c-ade7-3ae0710c2378">

**Comment by Tensuko** [comment]
How does the HUD of the unloader look like in that situation?

**Comment by simonIOW** [comment]
Focus is on the combine, not the unloader, my bad.

I'll get a video done :)

**Comment by Tensuko** [comment]
Before I forget this: Pls use the latest Version 7.3.1.5

**Comment by simonIOW** [comment]
Hi.

First video shows how it gets stuck against the combine.
[https://clipchamp.com/watch/abEs7me1k02](url)

The combine has obviously found a spot the unloader doesn't like on the course.   I've moved the unloader manually to get it to try again...
[https://clipchamp.com/watch/Czv1qfpmHcS](url)

The log shows it's know's its blocked and "MOVING_AWAY_FROM_OTHER_VEHICLE" but it doesn't actually move anywhere. 

Hope this helps.

**Comment by rohne83** [comment]
Without any offset for the unloader it will never unload those harvesters due to the angle of the conveyor. Have you tried with some offset for the unloader to the left, i.e. -1m?

**Comment by simonIOW** [comment]
Tried it with the offset, it then occasionally sits outside of the range of the harvester, so tend to keep it at zero.  The question is about the fact the loader states when blocked that its "MOVING_AWAY_FROM_OTHER_VEHICLE" but it doesn't actually move anywhere .
