### ISSUE TITLE
[BUG_SP]Warning: Duplicate l10n

### ISSUE THREAD

**Issue by Legion68** [Courseplay/Courseplay_FS22#2875]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Warning: Duplicate l10n entry 'CP_ai_taskDescriptionUnloadingToTrailer' in 'C:/Users/User/Documents/My Games/FarmingSimulator2022/pdlc/FS22_Courseplay/translations/translation_de.xml'. Ignoring this definition.

**Comment by tn4799** [comment]
Das ist nur eine Warning, die macht nichts aus. einfach ignorieren.
Und by the way, ne warning ist definitiv KEIN bug

**Comment by Legion68** [comment]
Kenn mich hier nicht so Richtig aus  wo was rein geschrieben werden soll
