### ISSUE TITLE
[Question] Unable to select mod in save or new career

### ISSUE THREAD

**Issue by skibxskatic** [Courseplay/Courseplay_FS22#2877]
Hi,

I tried searching for this issue and couldn't seem to find a good enough keyword to find any matches. I'm sure this question gets asked all the time. I downloaded the github version of this mod and put it in my mods folder but it doesn't show up at all as a mod that's selectable. Is there a specific config I need to update before FS22 will detect this mod? Youtube videos of installation does not include a step like this.

**Comment by 60erjonny** [comment]
What is the name of the file you have loaded?

**Comment by skibxskatic** [comment]
i haven't renamed the file. i downloaded and stuck the entire zip into the mods folder in the same way the other mods folders are. 

all other mods are available to be selected in-game except courseplay.

**Comment by Tritura2** [comment]
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.3.1.3

Download the file FS22_Courseplay.zip from the link above. Make sure not to change the name and that you are using the newest game version. So maybe check if there is an update you didn't install for the game.

**Comment by Tensuko** [comment]
You need to have LS Version 1.12 as well!

**Comment by skibxskatic** [comment]
yep. that's what it was. i didn't have it updated. thanks y'all.
