### ISSUE TITLE
Implement width[BUG_SP]

### ISSUE THREAD

**Issue by disturbed-simulations** [Courseplay/Courseplay_FS22#288]
**Steps to reproduce**
Select miles as unit in setting

**Actual behavior**
If using miles as the unit in game the auto width fails to correctly set the width.  When the width is set correctly courseplay generates a course for an implement that is much wider than the amount set.

**Expected behavior**
Correct implement width

**Screenshots**

**Courseplay version**
7.0.0.10

**Log**
No errors in log

**Map**
Elm creek

**Vehicles/ implements involved**
Base game seeders and mowers tested so far

**Relevant script mods**
Autodrive and VCA  installed

**Comment by RealNeo80** [comment]
should be related to this one i think #225

**Comment by Tensuko** [comment]
#128
fixed soon
