### ISSUE TITLE
[Question] LINER 4900 BUSINESS Work width wrongly detected

### ISSUE THREAD

**Issue by PapaTim68** [Courseplay/Courseplay_FS22#2881]
Moin,

I noticed that the Vehicle Config System was added.

Since you have some default values for vanilla and modded Vehicles in some cases.
So I wanted to mention that the working width of the CLAAS Liner 4900 windrower is wrongly detected in the folded state as 2.9 meters, although it is supposed to be 14.9 meters.
I thought this would be the perfect use case for the new Vehicle configs.

Kind regards,
Tim

**Comment by Tensuko** [comment]
It is only in the folded state like other tools.
Not rly want to add all to the config.
You can create your own config, read our wiki page on how to do this.
