### ISSUE TITLE
Filling of seeders and spreaders of fertilizer or lime in the field

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#2882]
Hello dear developers.Thank you so much for such a chic mod and for the work done. Please tell me if you can make the seeders and spreaders of fertilizers or lime refuel in the field, so that they look for equipment on the edge of the field where you can refuel with seeds, lime or fertilizers and drive up to the equipment that refuel with seeds, lime or fertilizers that stand on the edge of the field and refuel there, as for example this is done with a trailer with a screw conveyor in the field, which is looking for a trailer and goes to it, or for example to a silo loader, which is looking for a trailer and goes to it. Thank you very much in advance.

**Comment by Tensuko** [comment]
Similar request #2069
