### ISSUE TITLE
[BUG_SP] Multiple Tool Corner Collision

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#2883]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
2x CR10.90 combines and 2 x 45ft NH Headers. Multipath course set for 2 tools, 2 headlands each and 6 lands

**Actual behavior**
When the lead combine needed to create a pocket just after the corner, there was not enough slowdown on the following combine to stop and wait before the pocket was created, meaning the two combines collided and couldn't move.

**Expected behavior**
Following combine slows down sooner or detects the lead combine sooner and stops a greater distance before the corner turn

**Screenshots**
![fsScreen_2023_10_22_12_04_58](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/3cc95bf2-f134-4e4d-b7e5-64875fb57837)

**Courseplay version**
Version used: 7.3.1.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13063037/log.txt)

**Map**
The Oaks

**Vehicles/ implements involved**
Giants CR10.90 and Giants 45ft NH header

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
The only solution is to increase the distance in the vehicle settings.
