### ISSUE TITLE
[Feature] Reduce lenght of variable target node

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#2884]
**What is the problem this feature/enhancement solves?**
Combine/Harverster can't always unload in trailer with variable target node, start at front and stop and end.

**Describe the solution you'd like**
Reduce the lenght of the variable target node, 20% in front and 20% in back, so only the middle 60% are used.

**Describe alternatives you've considered**
I tried to use the vertical offset, but this does only help for either the start or end point, but not for both.

**Additional context**
This happens very often to me.
Sometimes its just very close, but works.

![20230913191056_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/9e9e9676-b5f0-434b-9d73-53e2cce0228f)
![20230629231559_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/4bc75c27-4b1c-466a-bf90-e0309d95c150)
![20230629232057_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/67c2e71f-54ef-4b20-b3f0-d5ed947a897b)
![20230701135559_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/2914624a-8751-4f2e-a635-7f2880c4a114)
![20230701183004_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/9db10380-7149-40f3-b5cb-48ce67d31e37)
![20230805205432_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/b7c8d6f7-cade-4bd1-bd2e-b877db10ff3c)
![20230826132746_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/538055dc-9144-4f52-857b-0eb91a08a853)
![20230826210709_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/74661d79-e279-4d70-8ace-85ad9691fdbb)
![20231014181722_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/bf96af09-4d49-4a91-ac53-d085623b5ef8)
![20231020195603_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/6194d92d-e150-433a-8956-1b251d555210)
![20231020200028_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/e0469584-52e0-472f-b49e-165bbe57d657)
![20231021111936_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/850ced7e-28cf-4743-a953-0803c0569cdd)

**Comment by Tensuko** [comment]
Wow that are many pictures, the 1st would have been enough :)
I know exactly what you mean. Should try to do this.

**Comment by blubstar86** [comment]
yeah sorry, i just wanted to point it out that it happens a lot to me

**Comment by coatsy35** [comment]
Will these changes mean we can unload into two trailers pulled together when this goes live?

**Comment by Tensuko** [comment]
Not 2 trailers, wait for changelog description.

**Comment by Tensuko** [comment]
Just for Documentation:
https://github.com/Courseplay/Courseplay_FS22/commit/d68f21767bb5d83d7564ed8937b63b79106a661b
