### ISSUE TITLE
[Feature] Wrong Fruit Type For Seeding Mission

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#2885]
**What is the problem this feature/enhancement solves?**
If you do a seeding mission (especialy when you start AD driver and handover to CP, then you wont see the fildwork start) with the wrong fruit type selected in the seeder, then he keeps doing his work, but doesent realise hes doing wrong :)

**Describe the solution you'd like**
Stop CP-Worker with message in Info-Panel "wrong fruit type"
Like the same it is with combines and the rain message.

**Describe alternatives you've considered**

**Additional context**
![20231013195320_1](https://github.com/Courseplay/Courseplay_FS22/assets/47928255/7749f5a0-fbec-44a1-b156-4842e62f2c9b)

**Comment by Tensuko** [comment]
Uhm not sure if we can do that.
What does the Giants helper do if you try that?

**Comment by blubstar86** [comment]
Giants Helper:
- same message
- continues working with wrong fruit

so mission could also fail with giants helper :/

**Comment by Tensuko** [comment]
Then it is not sure if we will implement a solution, as we use a lot of giants functions.

**Comment by Tensuko** [comment]
We talked about that internal and we decided to not implement a solution for this, sry.

**Comment by coatsy35** [comment]
That would have been a great idea! I run into this alot and it's quite annoying. I guess it conflicts with other things?

**Comment by Tensuko** [comment]
Found a way, will be part of next update.
