### ISSUE TITLE
Pallet Trailer Load For Pallet Forks [Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2886]
**What is the problem this feature/enhancement solves?**

Production Pallets overloading

**Describe the solution you'd like**

Much like the Silo load mode I propose that there be a pallet load mode. I don't know how hard it will be to code in but you could have the machine with the pallet fork recognize there is an area that had a set number of pallets and there is a flatbed or low loader near by to load onto

**Describe alternatives you've considered**

at a production point having the pallet fork detect the spawn area of the pallets and having it detect a set area to unload them weather that be just a clean flat area or a trailer of some sort

**Additional context**

**Comment by FrozenStorm1029** [comment]
and maybe it could implemented for bales?

**Comment by Tensuko** [comment]
Die to pallet physics that will be impossible.
For Bales it is kinda the same.
Won't happen.
