### ISSUE TITLE
Bale stacker with Bale Grapple Front Loader[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2887]
**What is the problem this feature/enhancement solves?**

I believe this feature would be very beneficial as it means there is less micromanaging with bale trailers filling up so quickly

**Describe the solution you'd like**

Using any Front loader with a bale grapple you should be able to set a unloading area where the front loader can unload the bales

this allows for many things to happen. Such As

This Stops the need for micro-managing the bale trailer as when it fills up it just stops the worker and nothing gets done

This allows all bales to be stacked neatly waiting for the auto-loading trailer to come by and fill up entirely before leaving

Although the pathfinding is great for the current bale loading setup its not always the most reliable 

And finally as mentioned above this greatly reduces the amount of player input  and micro-managing of the whole task
 
**Describe alternatives you've considered**

Having the option for the auto loading trailer to have an off field unloading area, kind of like the on field unloading area for the augers

**Additional context**

i just think that the current way bale collection is implemented into Courseplay is too expensive especially with any decent flatbed/low-loader costing more than a bale grapple and front loader in addition to this it also gives the players more options when getting bales off the field and ready to be sold

P.S PLEASE ADD THIS ALSO THANK YOU. IT MEANS ALOT TO ME THAT YOU ADDED AUTOMATIC HEADER ATTACH ON THE COMBINES

**Comment by Tensuko** [comment]
Due to bale physics this wont be added too....

**Comment by FrozenStorm1029** [comment]
will anything similar be added

**Comment by Tensuko** [comment]
No.
We have implemented universal autoload from loki, there you can use super cheap trailers to load bales.
