### ISSUE TITLE
[BUG_SP] symmetric lane change setting is not working

### ISSUE THREAD

**Issue by WeAreV3N0M** [Courseplay/Courseplay_FS22#2889]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Unknown reason behind bug so not sure how to reproduce

**Actual behavior**
I have accepted a cotton harvesting job with two Case IH Module Express 635 harvesters (base game) And loaded a previously generated course that was generated for two machines. After the harvesters reached the end of first row (not counting headlands) both machines changed to the other side of the path for the next row. They turned from left side to right in next row and from right side to left. I tested it with symmetrical lane change turned on and turned off, it seemed to have no effect at all.

**Expected behavior**
With symmetrical lane change turned on, the machines should remain on the same side of the path all the way to the end. If started on the left side, after turning the worker should continue on left side.

**Courseplay version**
Version used:  7.3.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elm Creek Edit 4x V1.0.0.9 By Stevie

**Vehicles/ implements involved**
Case IH Module Express 635
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13073636/log.txt)

Mod yes/no ?
no

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by RedMonster-HUN** [comment]
Just tested it with the John Deere machine. There is no difference between symmetrical lane change turned on or turned off.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13074055/log.txt)

**Comment by Tensuko** [comment]
It is generally broken somehow.

**Comment by rohne83** [comment]
```
Expected behavior
With symmetrical lane change turned on, the machines should remain on the same side of the path all the way to the end. If started on the left side, after turning the worker should continue on left side.
```

Nope, that's the behaviour for default asymmetric lane change, to be used for lands or spirals mode. With symmetric lane change (rather for updown or racetracks) the offset should of course always change at every turn. In my eyes that works as desired.

**Comment by JDTiger** [comment]
Important addendum I found out:

When switching the lane change and/or Implement raise/lower you have to reload the course for the change to apply

**Comment by WeAreV3N0M** [comment]
If I set one machine to go on left side and the other machine to the right, and then both try to go on right side (after me triple checking their CP settings are identical) that's everything but desired.
Also not desired if the workers behave the same way with symmetrical lane change turned on or turned off.
Both of the things mentioned above happened during testing and Tensuko saw my log.

**Comment by Tensuko** [comment]
Guys just wait for it.
It was easy confirm and we have a look at it.
