### ISSUE TITLE
how do i generate cources for my fields

### ISSUE THREAD

**Issue by Lonebull94** [Courseplay/Courseplay_FS22#289]

**Comment by RealNeo80** [comment]
Go to the giants helper menu over ESC, then Press create Job. 

![generator](https://user-images.githubusercontent.com/8066324/147846854-99c5029c-7dc6-4119-a9fc-6730b76ad606.png)

In this menue you can switch to a CP: Field Work helper, if you have selected this set the start point on the field you like to create the course, then click on CP open close Course Creator in the bottom of your screen. Now your Course generator openend and you can make the settings for the course. Then click Return or in the bottom on Generate Course. The course should be now shown on your field, and automatically loaded in the vehicle you are inside. 

![saving](https://user-images.githubusercontent.com/8066324/147846855-ae9bd715-b140-4363-adf4-48d997b5b0e0.png)

After this you can go the the next menue to save the course. Also from there you can load courses or organize them. But be aware, as long as you don´t save the course, its only temporarly in this one vehicle

**Comment by Tensuko** [comment]
Temporary course is also saved so after game restart, you still have it in your vehicle unless you remove it from the vehicle.

Thanks @RealNeo80 for explain this :)
