### ISSUE TITLE
[Feature] Allow plows to create fields

### ISSUE THREAD

**Issue by BippyMiester** [Courseplay/Courseplay_FS22#2894]
**What is the problem this feature/enhancement solves?**
When creating a new field, I can obviously define a custom field, so once that is complete, I could have courseplay just create the field for me.

**Describe the solution you'd like**
A simple toggle on the courseplay job creation, if a plow is attached to allow field creation.

**Describe alternatives you've considered**
I have used the Guidance System "GPS" mod, and I have created the fields manually but theres no automatic way to create the field.

**Additional context**
This feature request is fairly straight forward and simple. No additional context needed.

**Comment by Tensuko** [comment]
You know that the basegame have a toggle for plows?
Just toggle it before you start CP.
Not going to implement a duplicate function.
