### ISSUE TITLE
[BUG_SP] Multiple Instances of Active Worker created when switching to and from Autodrive work

### ISSUE THREAD

**Issue by BippyMiester** [Courseplay/Courseplay_FS22#2895]
**Steps to reproduce**
Create a job with Courseplay on a field. For this instance I did a Liming job. Set Autodrive to Load mode. Select your field. Select the area where you store your Lime as the load point. Select Lime. Click on the Courseplay Icon in the Autodrive HUD. Click the Enable/Start button on Autodrive.

**Actual behavior**
Whenever the work switches from Courseplay back to Autodrive to refill the spreader, Courseplay doesn't get rid of the active worker in the ESC menu under the AI Workers tab. This causes the worker wage to increase by 100% for every worker, draining your funds.

Even when I manually get rid of the worker by clicking the play button on Courseplay it doesn't get rid of all the workers. Just 1 of them. The only way to get rid of all the workers is to exit the game and reload the save.

**Expected behavior**
When the Courseplay job is put on pause to refill the spreader, it should get rid of the active worker, switch to Autodrive, and then resume the work once the Autodrive has driven back to the field.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4575704/7a2c8870-814d-4073-bf4f-f74de57cb526)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4575704/1b851e88-8e22-48c4-b936-60155f2a2081)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4575704/f20f8314-254d-4c07-a82a-344d14ebccde)

**Courseplay version**
Version used: 7.3.1.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13120106/log.txt)

**Map**
No Man's Land

**Vehicles/ implements involved**
Xerion 5500 - Alex Blue Mod Shop
Wagnon CFS 530 D0 with the Lizard T100 Windrow by Hispano
K165 Spreader
Hirschfeld Scorpio 9500XL By Cassy Blair
Speed-Tiller 475 by Adub Modding

**Relevant script mods**
Autodrive - Latest Version

**Other Information**
This issue could possibly be related to running multiple Courseplay workers at the same time. Logs have all vehicles running Courseplay with debug mode enabled. Excuse the messy logs file.

I also noticed that sometimes whenever the switch between Courseplay and Autodrive happened, both of them were being enabled at the same time. Meaning the "switch" didn't really happen as Courseplay wasn't actually turning off. This happened, for example, would happen when a Stone Picker or Forage Wagon was full, and needed to be dumped. It could have been related to this as well? Maybe.

The issue first appeared on the tractor named 5500-4. This tractor was one of the tractors spreading lime. I renamed the tractor using the Advanced Farm Manager mod.

**Comment by BippyMiester** [comment]
Also, just a side note that this could be an issue with Autodrive, and has nothing to do with Courseplay. If thats the case, i'll go ahead and post over there on their Github.

**Comment by BippyMiester** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4575704/2f3a4434-5d9d-43b4-ba0f-65345e6f3a71)

This is what happens after about an hour of playing. Multiple tractors, all having the same issues.

**Comment by Tensuko** [comment]
It seems to appear randomly since a long time.
Not sure when and why this happens.
It is not always the case.

**Comment by BippyMiester** [comment]
I've been watching this intensely since I first posted about this... I've noticed that it happens when it switches over to autodrive, but its switching over to the "pickup target" (The top selection) and not the "load target" (The middle selection). Like for example... the spreader runs out of lime... needs to be refilled. When it switches over, it goes to the field waiting point, which then triggers Courseplay, instead of going to the silo thats holding the lime.

So my question is, is this intended? Meaning, should a tractor when it needs to be refilled, go to the field waiting point first, and then go to the silo? Can't Courseplay just switch over to Autodrive, and instruct autodrive to just go to the silo first?

**Comment by BippyMiester** [comment]
Also, another note. This issue doesn't happen with items that don't need to be unloaded or loaded. So think rollers, mowers, etc.

The refuel and repair functionality works as intended and isn't affected by this issue.

**Comment by schwiti6190** [comment]
This might be a bug with the latest released version and could be fixed with next version

**Comment by BippyMiester** [comment]
> This might be a bug with the latest released version and could be fixed with next version

I did notice that this was happening more with the latest version... I don't think I was really having this issue before hand. At least that I noticed. But with this new version, I thought I might have been crazy and I couldn't actually "prove it", so I didn't want to really hypothesize this and just blame the update... But it does make sense.

**Comment by BippyMiester** [comment]
I reverted back to the previous version, and I haven't experienced the issue yet. But I'll still do more testing and report back.

**Comment by BippyMiester** [comment]
Alright so after a day of testing, it still is happening. I thought at first that it wasn't happening anymore even with the previous 7.3.1.2 version, but after letting the game run and do its thing, it still is occurring. So, even with the previous version it still happens. Hopefully a fix comes out soon.

**Comment by BippyMiester** [comment]
> Does this happen only with this mod or also with others? I have now watched two hours on my server the workers that are regularly passed to AD and the active list was always deleted. Hence the question if it is also the case with others.

I don't know what you mean by does it happen only with this mod? Like how could another mod have this issue? This is a courseplay issue... Could be an Autodrive issue, but that has yet to be determined by the devs.

Now if you're asking if I'm having any issues with other mods such as modded tractors or modded implements and their compatibility, then I get the question. I have about 500 other mods enabled. I have done the testing however **with only autodrive and courseplay enabled to rule out any false positives**. I've also tried multiple tractors and implements. I've also done extensive testing with modded implements as well. It happens with both modded and unmodded vanilla implements and tractors.

Also, this bug is specifically for singleplayer as noted in the title of this issue. I have not done any testing in mutliplayer as I don't use a server for any of my games. Nor do I use a LAN server either. This is only singleplayer testing in this issue. So, if you're not having it happen, its probably due to you being in multiplayer.

**Comment by Tensuko** [comment]
What he mean is if this does happen only in combination with other mods.
Thats is indeed a good question as it could be a mod conflict.

**Comment by BippyMiester** [comment]
> What he mean is if this does happen only in combination with other mods. Thats is indeed a good question as it could be a mod conflict.

Can confirm that it does happen with only AutoDrive, Courseplay, and Official DLC's enabled only.

**Comment by Tensuko** [comment]
Since you are testing so much, did you update to the latest version 7.3.1.5?

**Comment by BippyMiester** [comment]
I have not. I did not see that it was updated. Will test more after work today.

**Comment by Friendlyx** [comment]
hi, I notice strange behaviour of autodrive today too. I reverted CP back to a backup version I had from Sep.  7.3.0.2 and have no such problem with that version.

**Comment by schwiti6190** [comment]
@BippyMiester Please let us now if this problem reappears. Until then this issue will be closed.
@Friendlyx Seems to me you've got a complettly different Issue, which should be an auto drive bug.

**Comment by BippyMiester** [comment]
@schwiti6190 

I've started a new playthrough on a different map with the latest version of CP. Haven't had the issue come up just yet. Maybe its fixed? Idk. I feel as though i'm too new in the playthrough for serious testing. But I'll continue to test and report if it happens again. Thx

**Comment by mas1701** [comment]
I wonder why this issue was closed. The bug still exists in 7.4.0.2 with most up-to-date AD. Was it fixed later?

If there is no solution yet, it might be a temporary workaround to provide a way to reset all registered courseplay helpers and their corresponding entries in the Giants active helpers list, for example by an additional key combo. This of couse should then only be used when no real CP worker is active so not to kill them instead.

The bug is especially annoying on MP games and dedicated servers, because the current workaround is re-starting the whole server / MP game (and thereby kicking all players).
