### ISSUE TITLE
[Feature] Wiki

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#290]
@Tensuko theoretisch könnte man doch das Wiki nutzen um so basics zur Verfügung zu stellen, oder? Würde bestimmt einigen helfen

sowas ähnliches wie [hier](https://courseplay.github.io/courseplay/de/index.html), das lief doch auch direkt über Github.

**Comment by Tensuko** [comment]
Absolut richtig!
Ich muss nur die Zeit dazu finden.
Leider ist das Bilder nutzen im Wiki etwas schwieriger als im Issue.
Aber ja ich schreibe es mir mal auf, dass ich unser Wiki weiter ausbaue!

**Comment by RealNeo80** [comment]
@Tensuko kann ich dir was helfen?
