### ISSUE TITLE
Häcksler fährt nicht mehr los [BUG_SP]

### ISSUE THREAD

**Issue by Hartmut88** [Courseplay/Courseplay_FS22#291]
Leider fährt nun der Häcksler nicht mehr los. Angeblich hat dieser einen vollen Korntank...
Ich stehe aber mit dem Abfahrer daneben. In der letzten Version von CP hat das funktioniert.. habt ihr da irgendwas geändert?

**Comment by RealNeo80** [comment]
öhm ja, meine Glaskugel is gerade kaputt, gehts vielleicht ein bisschen genauer? @Tensuko ist Häckseln eigentlich schon integriert?

**Comment by dominiczeth** [comment]
Zuletzt gab es einen Bug, dass das Soliermittel als Korntank erkannt wird. Wenn der Soliermittel Behälter voll ist sagt CP, Korntank voll.

**Comment by Tensuko** [comment]
Häcksler soll gehen, mit Siliermitteltank gibts noch nen Bug, aber ich kann nur hierrauf verweisen und bitten die Templates zu nutzen.
Lesen:
https://github.com/Courseplay/Courseplay_FS22/wiki
