### ISSUE TITLE
[Question] Forage harvester setup

### ISSUE THREAD

**Issue by WeAreV3N0M** [Courseplay/Courseplay_FS22#2915]
I'm trying to figure out how to properly set up Forage harvester with two semi trucks to harvest a field, but no luck so far.
The harvester keeps stopping like it was waiting for truck, and trucks won't start (I assume they are waiting for call)
Can anyone help in this matter?

I use CP and AD to control workers
CP version: 7.3.1.4
AD version: 2.0.1.2

**Comment by Tensuko** [comment]
For CP it is just the same as any Harvester.
For AD, both the forage harvester and the unloader must have the same target on AD HUD and ofc the harvester mode active.
FFor more questions about AD Setting, pls ask on AD Discord or AD GitHub as I am not that much into AD Modes.

**Comment by WeAreV3N0M** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/4c9b5e68-fe7a-4237-821c-68a9440390cc)
Semi in place, nothing in front of harvester but it won't start for some reason

**Comment by WeAreV3N0M** [comment]
@Tensuko pls?

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/3f16e647-363d-461b-a25a-e64890640ba2)

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/f985b8eb-e869-4e84-89d3-54dc59fa7e25)

**Comment by Tensuko** [comment]
Harvester and Trailer same target, Trailer combine unload mode.
Works just fine.

**Comment by WeAreV3N0M** [comment]
Somehow they started to work after I toggled the CP button in AD hud. Never realized that button had such use.

**Comment by Tensuko** [comment]
No need that button but as long it works for you now...

**Comment by WeAreV3N0M** [comment]
Not sure what was the key change but seems to be fine now

**Comment by WeAreV3N0M** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/2e579264-55be-459c-9714-6a79ca13c536)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13224918/log.txt)

@Tensuko could you pls look into this log sometime later? It is so weird that the harvester always stops at the edge of field and won't go further even if the semitruck is within unload range. In middle of field there is no problem with it, always happens at the edge.

**Comment by WeAreV3N0M** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/e38f2426-b84b-49bd-8e7f-031861290c1d)
Same situation, slightly different vehicle positions, harvester won't start chopping.

**Comment by Tensuko** [comment]
Not a CP Problem.

**Comment by WeAreV3N0M** [comment]
I don't think it makes any difference but gonna give it a shot

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/08d7c08b-39a5-440b-b8e9-da42d94b9197)
Did test some different center patterns thats why it looks so messy, but all worked fine.
Ask on AD how they do best set it up.

**Comment by WeAreV3N0M** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/e5b87ed9-c103-4d5e-a5f1-e69ad5fc00df)
No AD involved this time. Harvester gets "stuck" on row end just before beginning next row. Header down, drove the semi next to it but nothing.

**Comment by WeAreV3N0M** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13230753/log.txt)

**Comment by Tensuko** [comment]
Looks like trailer too far at the front, also sometimes it seems to try to chop grass and mixed stuff may have a problem too.

**Comment by Tensuko** [comment]
Still not a CP problem and might be basegame and or mod conflicts, I dont know.
You got to fill gure it out by yourself.

**Comment by WeAreV3N0M** [comment]
The mixed input problem could explain why the harvester kept stopping along the first lane. Header cut down a little grass too.
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/d37b5aef-bb0f-4fdf-81bb-1bcf47723d98)

**Comment by WeAreV3N0M** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/54554640/eec330fb-2ba9-4fbb-9575-854d1e076e63)
I purchased a small field to see if field ownership status makes a difference. There is rape on this field probably in a too early growth state so header cannot cut it down, giving zero input. 
Could it be that lack of input results in harvester to stop working?
