### ISSUE TITLE
[Feature] Add support for different saves using the same map

### ISSUE THREAD

**Issue by BippyMiester** [Courseplay/Courseplay_FS22#2917]
**What is the problem this feature/enhancement solves?**
So, I have two saves currently using the same map. My courses for save 1 is showing up in save 2. This isn't good as my fields are not the same.

**Describe the solution you'd like**
I'd like the ability for the courses to be per save and not per map. This would be useful for those who are using the same map for two different playthroughs. I.e. one save is used for multiplayer, the other singleplayer.

**Describe alternatives you've considered**
I can backup and restore the courses when I want to switch saves, but that takes time and it should be fluid per save.

**Additional context**
N/A

**Comment by Tensuko** [comment]
Not going to do this.
Our system is on purpose to save the course per map and not per save.
Won't fix, sry.

**Comment by WeAreV3N0M** [comment]
@BippyMiester just create different folders for your courses on different maps.
For example:
Field 1 in save 1: S01F01 harvest 9m
Field 1 in save 2: S02F01 harvest 12m
This way all your folders for save 1 will be at the top of your folder list in alphabetical order.
