### ISSUE TITLE
[BUG_SP] Elmcreek Feld 25 generiert nicht sauber

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#292]
ich hatte das jetzt beim Grubbern und Dreschen, dass er aussen was stehen lässt

![Elmcreek_25](https://user-images.githubusercontent.com/8066324/147849437-a0a0ad0e-bf55-4d92-8531-fb96dd75f4bb.png)

**Comment by Tensuko** [comment]
Das ist mir bei einigen Feldern auch aufgefallen, aber das kann auch am Feld liegen.
Wenn diese Pflanzenreihe außerhalb der Feldgrenze liegt.
Das gab es im 19er auch schon.
Dafür müsste man sich die Fielddefinitions mal anschauen.

**Comment by RealNeo80** [comment]
@Tensuko  bitteschön
[cpFields.txt](https://github.com/Courseplay/Courseplay_FS22/files/7797728/cpFields.txt)

**Comment by StefanBraun2001** [comment]
Da könnte die alte LS19er Funktion "Überlappung Vorgewende" Abhilfe schaffen. Im LS19er war das ja eine recht große Hilfe, wenn der Kursgenerator nicht überall scharfe Ecken generiert hat und bei runden Feldern.

**Comment by pvaiko** [comment]
Überlappung gibt es jetzt auch, nur noch nicht einstellbar, fix 7%. Aber nicht am Feldrand, war auch in FS19 nicht.

**Comment by Tensuko** [comment]
Should be fixed with 7.0.0.11
Reopen if Issue persists.
