### ISSUE TITLE
No new course play is being allowed to be made on mapsBUG_SP]

### ISSUE THREAD

**Issue by Stabernor** [Courseplay/Courseplay_FS22#2922]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Stabernor** [comment]
![Screenshot 2023-11-01 143515](https://github.com/Courseplay/Courseplay_FS22/assets/149599315/f41e3079-983f-4aef-9e11-84ec10bdff86)
![Screenshot 2023-11-01 143515](https://github.com/Courseplay/Courseplay_FS22/assets/149599315/149d66ce-63b2-489a-acbc-577933b528db)

**Comment by Stabernor** [comment]
when you go to select open course editor, nothing happens. This is happening across all maps

**Comment by Tensuko** [comment]
Fill in the template.
No Idea what you expect here to happen.

**Comment by Tensuko** [comment]
Just for the record:
Editor opens just fine.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/dff5f620-e177-45e1-bb69-f7d057c90fc7)

**Comment by Stabernor** [comment]
How do I get that up then? As when I do it through the menu as I always do like shown in my screenshot it doesn't allow me to create a new course.Sent from my Galaxy
-------- Original message --------From: Tensuko ***@***.***> Date: 01/11/2023  16:23  (GMT+00:00) To: Courseplay/Courseplay_FS22 ***@***.***> Cc: Stabernor ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS22] No new course play is being allowed to be made on mapsBUG_SP] (Issue #2922) 
Just for the record:
Editor opens just fine.

**Comment by Tensuko** [comment]
Creating a new course is not done in the course manager!
Pls read the ingame help for how this works.

**Comment by Stabernor** [comment]
Well it use to be! Hence my query. But not to worry manage to work it out my self. And FYI doesn't say how to create the course the new way In the information board! Tells you how to setup etc but doesn't say you have to go to field and select the workers option then select field work and then select course creator as when I was on last it was all done through the CP option on the menu. Why is the option on here still then if its no longer the way you can do it. Surely this button should now be removed if it's now redundant Sent from my Galaxy
-------- Original message --------From: Tensuko ***@***.***> Date: 01/11/2023  16:59  (GMT+00:00) To: Courseplay/Courseplay_FS22 ***@***.***> Cc: Stabernor ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS22] No new course play is being allowed to be made on mapsBUG_SP] (Issue #2922) 
Creating a new course is not done in the course manager!
Pls read the ingame help for how this works.

**Comment by Tensuko** [comment]
Nothing have changed.
I have no Idea how you used to do it, but it was never made through the course manager, NEVER.
Always the AI Map, else create job OR click on no course on the hud.

**Comment by Stabernor** [comment]
Well was once because that's how I use to do it hence why I'm asking the question. So what does the 'open course editor' do then on the course manager if it's not for creating courses then? This was before the update where you now press delete instead of right clicking on the mouse as that's now not working even though its on the keyboard control as an option!Sent from my Galaxy
-------- Original message --------From: Tensuko ***@***.***> Date: 01/11/2023  17:30  (GMT+00:00) To: Courseplay/Courseplay_FS22 ***@***.***> Cc: Stabernor ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS22] No new course play is being allowed to be made on mapsBUG_SP] (Issue #2922) 
Nothing have changed.
I have no Idea how you used to do it, but it was never made through the course manager, NEVER.
Always the AI Map, else create job OR click on no course on the hud.

**Comment by Tensuko** [comment]
It was NEVER to create a course.... As the name said, it is to EDIT an existing course and it is all written in the help menu.
There was never anything changed. That it was to create an acutal course, thats have always been the course generator.

https://courseplay.github.io/Courseplay_FS22.github.io/#CP_help_page_courseManager_title

https://courseplay.github.io/Courseplay_FS22.github.io/#CP_help_page_editor_title
