### ISSUE TITLE
[BUG_SP]Здраствуйте а ви не знаете как у меня так получилось не отображаються линии в курсплее і как ето исправить

### ISSUE THREAD

**Issue by nuchay** [Courseplay/Courseplay_FS22#2925]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
@Gonimy-Vetrom can you help out here pls? :)

**Comment by Gonimy-Vetrom** [comment]
@nuchay Привет. Какие именно линии исчезли?

**Comment by Tensuko** [comment]
Sry but since I get no answer to this, I have to close this.
Pls reopen the Issue if there is any feedback.

Thanks @Gonimy-Vetrom for helping anyway :)
