### ISSUE TITLE
ERROR: Running lua update

### ISSUE THREAD

**Issue by Sav19** [Courseplay/Courseplay_FS22#2926]
when opening the save game I get an lua error that stops me from loading my game.

CpVehicleSettings.lua:444:bad Argument #1to 'min' (number expected.got,nil)

![Screenshot 2023-11-03 083220](https://github.com/Courseplay/Courseplay_FS22/assets/33447815/b700de3b-ee57-494d-a3af-dfb2ebb3a5a6)
 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13245334/log.txt)

i'm using cp 7.3.15

the error pops up after it loads the terrex 5500 dolly from JR Brown

**Comment by Sav19** [comment]
I also get the following error on a different map with cp 7.3.0.0 after loading the franna AT_40 from alexscomo mods

CpVehicleSettings.lua:409:bad Argument #1to 'min' (number expected.got,nil)

![Screenshot 2023-11-03 090734](https://github.com/Courseplay/Courseplay_FS22/assets/33447815/bfd3f45f-3aad-4ef8-9ff5-ef1669a5a09f)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13245512/log.txt)

**Comment by Tensuko** [comment]
Mod Issues, won't fix.
Sry.
