### ISSUE TITLE
Unloader not moving after unloading on field.

### ISSUE THREAD

**Issue by PatrickWende** [Courseplay/Courseplay_FS22#2927]
Hi CoursePlay Devs,

I am using CoursePlay to unload a beet harvester with a tractor and a tipper trailer. I setup CoursePlay to unload on the field. While unloading the trailer is being raised of the ground as a result of the growing pile of beets behind the trailer. After unloading and lowering the tipper the tractor will not set off to unload the beet harvester. I have either have to stop CoursePlay, drive the tractor forward a few meters and start CoursePlay again, or use something like superstrength to pull the tractor forward, after which the tractor sets off again for unloading the harvester. When I watch a youtube video from for instance Holger-70  everything works seamless. Am I missing something or do I need to file a bug report?

Thanks in advance,

Patrick

**Comment by Tensuko** [comment]
What version did you use?
Will try that later if there is a problem.

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/47b0f5e0-fe32-4815-9d89-36560fb5d911)
Works just fine.
As you see, the 1st 2 heaps are not flat, that means the trailer unloaded in one go.
The flat part is a bigger trailer that moves forward to unload more stuff.
Affter unloading done, the trailer folds back and the unloader drives to its idle position.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/1d8622de-363c-45f4-af80-01ab41703f34)

**Comment by SuBerPL** [comment]
I have the same problem too. Added some screenshots.
The CP employee hangs up after unloading, does not move to the waiting place and does not approach the combine harvester when it is full.

Additionally, with a reloading trailer, the stack turns in the opposite direction and crooked. Maybe the mode is not adapted to this type of trailers, but all other rear unloading trailers make very low piles, which translates into their length.

The stack visible in the screenshots has already been corrected, but you can see exactly where the employee unloads
![1](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/6cb5483d-2145-4591-91b5-34e53e84f3b5)
![2](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/9ded7e72-d4d0-44f8-a536-898359c4a027)
![3](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/440654cc-658c-45b5-aee8-c72af7eb69f5)
![4](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/050e2f3e-8ee0-478a-b5e3-e77ba0463f84)
![5](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/123f6fac-e779-4491-a38b-40668b6b923f)
![6](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/8d0303a1-5a9f-4774-9d04-4865fe642209)
![7](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/fa0258e1-8940-4a03-8189-e28eb1198109)
![8](https://github.com/Courseplay/Courseplay_FS22/assets/32776608/33a91f8a-36c6-4d69-94e8-e55ce16b8949)

**Comment by Tensuko** [comment]
@SuBerPL
becouse it is not supposed to work in that 90°
Its idle position would be on that heap, wich he can't drive there.
Would need to figure out a better position for that case, but it is not the same problem.

**Comment by PatrickWende** [comment]
Hi Tensuko,

It appears that the problem was on my side. I tried with a different trailer and no more problems, the one i used (Penta DB50) must have been a bad conversion. Should have tried a different trailer in the first place. Thanks for looking into the issue and thanks for putting all this effort in CoursePlay for all of us.

Regards,

Patrick
