### ISSUE TITLE
Startpunkt wird falsch gedreht

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#293]
Hallo Tensuko!
Zunächst meinen tiefen Respekt und Dank für Deine Leistung!
Aktuell habe ich relgelmäßig das Problem, dass der Startpunkt im Helfermenü ausgerichtet ist, jedoch dann im eigentlich Kurs um 90° gedreht ist! Das führt dann immer zu irren Fahrten der Geräte

**Comment by Tensuko** [comment]
Wiki und Templates bitte beachten, so kann ich damit nichts anfangen, sry.
