### ISSUE TITLE
Fahre gegen Häcksler oder Mähdrescher

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2930]
hallo 
Warum fährt der Abfahrer gegen Häcksler oder Mähdrescher 
![Häcksler](https://github.com/Courseplay/Courseplay_FS22/assets/47453761/cc09b81b-fcb6-4376-94bb-5442bb904f66)

**Comment by Tensuko** [comment]
Da du AD fahren läst als Abfahrer, bist du hier falsch, frage bei AD nach.
