### ISSUE TITLE
[Question]LUA call Stack bei Abfahren von der Rübenmaus

### ISSUE THREAD

**Issue by Knalli83** [Courseplay/Courseplay_FS22#2933]
Hallo
ich habe das problem das sobald der Abfahrer an die Maus fährt, sofort der LUA call stack kommt!!
habe schon versucht nur mit CP und AD also ohne ander MOD´s zu spielen aber das ergebnis ist das gleiche!! was mache ich falsch bzw gibt es eine Lösung??
![lua Call stack](https://github.com/Courseplay/Courseplay_FS22/assets/149924489/c600eb1a-89f7-438b-86eb-3606799a7c4a)
en??

**Comment by Tensuko** [comment]
fixed in next release
