### ISSUE TITLE
[Feature] Turn radius option under vehicle settings

### ISSUE THREAD

**Issue by Knowen** [Courseplay/Courseplay_FS22#2935]
**What is the problem this feature/enhancement solves?**
Sometimes the calculated turn radius is not correct, and this results f.e. into a tractor with an auger wagon crashing into the truck waiting on the side of the field.

**Describe the solution you'd like**
An option to change the turn radius, like the tool offset option in the mini hud. If it's only the tractor display the turn radius of itself. Once a tool gets connected display the calculated turn radius.

Thanks for the great mod!

**Comment by coatsy35** [comment]
Good idea. Would love to be able to adjust this from ingame instead of external. Would also be nice if settings were remembered per implement, I think that has been suggested before and something that might come one day. However I think there are issues as offset can't even be remembered between games as yet.

**Comment by Tensuko** [comment]
I am a bit against that, as this is a setting that is once fixed, it never needs to be changed.
Thats why the vehicle settings file is a good place for that.
Also you can reload that file on the fly with the command cpVehicleConfigurationsReload that will make it easy to change a value and reload it, as said, once found out a nice radius, you will never touch it again.

If we implement that, it will be under vehicle settings, not on the HUD, as there is no space in any mode and its a setting, like I said.... no need to keep change it....

The other problem is that it would need to be a setting per tool, wich is something we want to do at a very later state.
Something that in our current system how we get the radius without a setting is done in the vehicle setting .xml wich is a big advantage.

So this will not come any time soon.
I keep it in mind but closing for now, once we will have that new system running, we can recheck new possibilitys of adjusting tools characteristics with ingame settings.
