### ISSUE TITLE
Headland management ploughing [Question]

### ISSUE THREAD

**Issue by Bram1455** [Courseplay/Courseplay_FS22#2936]
Hello,

Courseplay for FS19 had an option for headland management when ploughing to first plough the whole field up and down, and then when ready finaly plough both headlands. The option was called 'small field'.

In FS22 i tried to set up this same course but i does not seem to be available. Options are up&down, spiral, racetrack and fieldsections. Not one of these options will instruct te helper to first plough the field completely up&down. 

In this case the helper will always start like with cultivating at the point minus the size of your headlands, while at the end the helper will finisch by working around the field completing the headlands and the outher space of the field. 

Can someone help me with this or is it just not an option anymore like it was at FS19?

**Comment by Tensuko** [comment]
It was narrow field.
It will come back with Generator 2.0 wich is WIP and will take a few more weeks/months.
