### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#2937]
I'm using a small tractor with AWS to do my grape vines, course skips (2) rows. With any tool connected to the tractors 3pt it comes to the end of the row, and easily does a tight turn, but...
As soon as I connect the Hardi Mercury sprayer on behind, it comes the end of the row, needs to make a left turn, then starts a slight right turn, sweeps way out from the vines about 50 - 70 feet. With this small of trailer, there is just no need to be making such a wide turn. It acts like at have 15m planter on behind. All these fricken map designers put grape vines on their map with very little clearance at the ends. Hence it won't run a course with the sprayer. 
I see the dingbats at Giants have done nothing to fix the Oxbo, I noticed that if you have configured as sprayer, even if you own the land, I can't get it to unload liquid fertilizer onto the ground.

**Comment by Tensuko** [comment]
The wide turn is needed to get a correct allignment.
We have future plans to improove thi vine handling but only togther with the new generator.

The Oxbo is indeed still bugged and I also don't get any feedback, sadly...
