### ISSUE TITLE
Headland overlap setting to apply to individual vehicles

### ISSUE THREAD

**Issue by matt-screed** [Courseplay/Courseplay_FS22#2938]
I'm not sure if it's feasible or not, but I think it would be helpful if individual vehicles sharing a course could overlap each other the same way a single one will overlap itself in subsequent passes.  

Maybe I'm a little OCD, but it bugs me when planting a field and using two or three implements, they always miss a spot between them when cornering.  I've tried other methods of avoiding this, from adjusting the actual width of the implement to a smaller value to using a smaller planter/seeder to fill in the gaps.

**Comment by Tensuko** [comment]
Its just physics. Would need sharp corners.
I don't know what you mean with apply to individual vehicles, as a course got nothing to do with the vehicle.
The only thing matters is the working width and turn radius when useing round corners and not smooth.
Also the type of tool, attached with 3-point or towed, both behave very different, even towed depends on how long the draged tool is and so on.

Per vehicle or better say per tool is something that is planed for the future but thats still a long way to go.

Here some documentation:

![round pattern](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/bd2b2aff-5c87-4720-b2fb-6e94e11c2879)

![round corners](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/f5503032-1b33-4c5c-99d0-ea12d2d79d41)

**Comment by matt-screed** [comment]
thanks for the quick reply, and you are correct, i meant overlap between tools.  as an example, with 2  20m seeders (total width 40m) and a headland overlap of 25% was selected, courseplay would calculate the headlands with a width of, say, 35m. This would allow a 5m overlap between tools.  i realize this would set the outer tool running outside the field, but that could be corrected with the field size adjustment (last parameter in the course config screen.

I know none of this is trivial and i appreciate all the work you put into this.

Malcolm Langille

**Comment by Tensuko** [comment]
There are ways to get there but I get your problem.
Thats multitool means one course but more then 2 vehicles on that course.
Play arround with work width and offset and stuff.

I don't know any other solution right now, will have to figure something out.
