### ISSUE TITLE
[BUG_SP] DLC Volvo wheel loader not path finding in silo load mode

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2939]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

Have Volvo LM 845 with volvo universial bucket lm841 do silo load mode

**Actual behavior**
A clear and concise description of what happen.

The problem is it keeps stopping "No Path" and there is a clear path for it i have turned off avoid driving in fruit 

**Expected behavior**

pathfind to the trailer

**Screenshots**
![Screenshot (32)](https://github.com/Courseplay/Courseplay_FS22/assets/69712685/780f2c94-5af2-47d7-9971-13966195ee26)

**Courseplay version**
Version used: 7.3.1.3

**Log**
Please attach a log with all debug channels active.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13304545/log.txt)

For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. Alma Missouri

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

DLC: Volvo LM845 With the Volvo Universal Bucket LM841

**Relevant script mods**
Mods like Autodrive or VCA and so on.

i have autodrive installed but was not using it for the unloader

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/releases

https://github.com/Courseplay/Courseplay_FS22/wiki

Always update to the latest build and check if the problem really still exists before reporting issues.

**Comment by FrozenStorm1029** [comment]
i did it still doesnt work

**Comment by Tensuko** [comment]
ok I will have a look

**Comment by schwiti6190** [comment]
@pvaiko Could you explain to me the why the PPC might shut off the driver with the following message: ``vehicle off track, shutting off Courseplay now``?

**Comment by pvaiko** [comment]
> @pvaiko Could you explain to me the why the PPC might shut off the driver with the following message: `vehicle off track, shutting off Courseplay now`?

It wandered off course more than 50 meters. In other words, the current waypoint is more than 50 meters, so would probably shut off if you start the course while far away from the closest waypoint.

**Comment by FrozenStorm1029** [comment]
Btw i tried on a few diffrent maps and and materials and its still not path finding... i thought it might have been the map because alma missouri being a new map it might have some issues with that type of stuff then i tried some other materials like (iron, wood chips , silage, hay, TMR,) and still nothing worked i hope that helps even a little bit

**Comment by KCHARRO** [comment]
Just yesterday the same thing happened to me, on the Zielonka map, when picking up Carrots from the ground, the same thing happens as described here.
 One question: Does this only happen with this loader?

**Comment by Tensuko** [comment]
Seems like that. Haven't tested it yet, will see when I have time to check why this one have that problem.

**Comment by FrozenStorm1029** [comment]
hey im using the newest version of courseplay however the issue isnt fixed
for piles without the bunker silo

**Comment by Tensuko** [comment]
Will check that later.
