### ISSUE TITLE
Problem mit Coursplay-Start

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#294]
Hallo Tensuko!
Regelmäßig, wenn ich das Gerät nicht wirklich an den Startpunkt eines Kurses stellen, passiert es,
dass das Gerät diesen Startpunkt nicht findet und dann wild durch die Gegend fährt!

**Comment by Tensuko** [comment]
Siehe das andere Issue, Wiki und Templates beachten, danke :)

**Comment by MisterGeniusj007** [comment]
Sorry, der alte Mann und das Lesen!
Trotzdem vielen Dank für Deine Geduld und Arbeit!
