### ISSUE TITLE
[BUG_MP] Hidden HUD shows CP notification overlay

### ISSUE THREAD

**Issue by MeRida2104** [Courseplay/Courseplay_FS22#2944]
**Steps to reproduce**
Hide Game-Hud via the console (gsHudVisibility) or, for example, Easy Dev controls 

**Actual behavior**
The Courseplay notification field is still displayed 

**Expected behavior**
The Courseplay notification field is hidden, like the rest of the HUD content of the game

**Courseplay version**
Version used: 7.3.1.5

**Comment by MeRida2104** [comment]
Client log (is in Singleplayer the same behavior than mentioned above)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13326069/log.txt)

**Comment by Tensuko** [comment]
turn it off in the cp global settings
