### ISSUE TITLE
[BUG_SP] IT Runner Manure spreader unfolding when starting course

### ISSUE THREAD

**Issue by dennis10V** [Courseplay/Courseplay_FS22#2948]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Make a course, then start the course. Then it will happen

**Actual behavior**
When starting a course with a manure spreader. The IT-Runner will unfold the whole carrier. So the tractor starts driving the fortis manure spreader starts spreading but unfolded. So the spreader trailer itself is driving on the ground.

**Expected behavior**
The manure spreader trailer should stay folded on the IT-runner when spreading manure.

**Screenshots**
![1](https://github.com/Courseplay/Courseplay_FS22/assets/105552196/fa208fd4-bc99-4ca7-9488-05c1f81242b2)
![2](https://github.com/Courseplay/Courseplay_FS22/assets/105552196/acfe0dc1-cee5-49e0-ab72-d032664f24f5)
![3](https://github.com/Courseplay/Courseplay_FS22/assets/105552196/29576d0b-ad6e-483a-a506-2c8bf2a44055)
![4](https://github.com/Courseplay/Courseplay_FS22/assets/105552196/ce851a58-59d4-4842-984a-5b906e414ba6)
![5](https://github.com/Courseplay/Courseplay_FS22/assets/105552196/0ce0d290-d0d1-482c-8aa4-b038de124ae8)

**Courseplay version**
Version used: 7.3.1.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Wild West 16x

**Vehicles/ implements involved**
Fendt 926, IT-Runner Pack (Fortis 2000, 26.33 HD)
Mod yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Link to the mod pls.

**Comment by Tensuko** [comment]
You can add it by yourself, I wouldn't add it to the mod anyway if not from ModHub.
https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.
Give the Platform (not the manure spreader) the disableUnfolding in the vehicle config.
