### ISSUE TITLE
Question: CP HUD kann nicht mehr geöffnet werden

### ISSUE THREAD

**Issue by EsstischII** [Courseplay/Courseplay_FS22#2949]
Hi there,

I played for some time and saved the game and closed it. Everything was perfect. I didnt change anything.
After restarting I cannot open the CP HUD anymore, neither by mouse nor by keyboard. I change the assigned key and it didn't work either.
I checked the CP global settings accordingly to the wiki.

I didnt change anything.

After searching the web I tried a couple of things, deleting most of the mods I used etc.
Nothing seems to help.

I can still create and start jobs in the general menu.

Here is my log: 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13339647/log.txt)

Help is very much appreciated, big fan of your work!

**Comment by Tensuko** [comment]
Entweder du hast die Option mit Mauszeiger öffnen deaktivert, die Tastenbelegung für Rechtsklick rausgeschmissen, oder das Fenster ist durch was auch immer vorschoben (ist mir z.B. noch nie passiert...)

Im letzten Fall:
..\Dokumente\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay
courseplay.xml
Die Zeile <Hud posX="0.241016" posY="0.027083"/> löschen. (Deine Zahlen sehen sehr wahrscheinlich anders aus).

**Comment by EsstischII** [comment]
Danke für die schnelle Hilfe. 
Das Löschen der Datei war die Lösung.
Woran kann das liegen? Ich hatte einen zweiten Ordner der mod**s**Settings hieß... Den habe ich ebenfalls gelöscht.

**Comment by Tensuko** [comment]
modsSettings ist ein Fehler von der Mod "AutoLoadWood" da ist ein S zu viel im Pfad, desshalb wird da ein quasie 2ter gemacht.
Woher es kommt keine Ahnung, andere mods, irgendwas umstellen, kein Plan.
Läuft ja wieder.
