### ISSUE TITLE
Eigene Kurse aufzeichnen

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#295]
Hallöchen Tensuko!
Ist es im CP-LS22 möglich und, wenn nicht, vorgesehen, wieder eigene CP-Kurse zu erstellen!
Zum Beispiel, um auf Nicht-Feldflächen Gras zu mähen?

**Comment by Tensuko** [comment]
Nein ist nicht vorgesehen.
Und Was heist Nicht-Feldflächen ?
Schon mal den Zielpunkt einfach auf eine Wiese gesetzt ?
Auf der Erlengrad hat es funktioniert.

**Comment by MisterGeniusj007** [comment]
Sorry, aber das hatte ich mir noch nicht getraut!
Werde ich aber ausprobieren!
Mit Nichtfeldflächen sind zum Beispiel die die Felder umgebenden schmalen Grünstreifen gemeint, die man auch mähen kann ...
Und da man ja faul ist, konnte man im 19er da einfach nen Course fahren und diesen dann wiederverwenden!
