### ISSUE TITLE
[Feature] Addition to Silo Load mode

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#2953]
**What is the problem this feature/enhancement solves?**

when it comes to moving piles without the need for a designated trigger point. It seems inefficient to load material into a trailer just to relocate it a short distance using a tractor or other equipment. The use of wheel loaders or telehandlers in real-world farming often involves moving material directly on-site without the intermediate step of loading into a trailer.

**Describe the solution you'd like**

Having a Bucketed Machine move a pile (ie. like the field unload for a auger) but for a bucketed machine 

it starts as the silo load mode and then you can have an "unload on field" option for bucketed machines

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
I don't understand the use of it.
What do you actually want to do?
Load e.g. silage from a silo and dump it on the ground ???
For what and why?

**Comment by KCHARRO** [comment]
Apparently, what it suggests is to make CP move material from one point to another nearby without using a trailer, with the loader itself, from a pile or a bunker to another point defined by the user. (either a discharge trigger, or on the ground).

**Comment by Tensuko** [comment]
a trigger is already possible, but I don't know why to throw it on the ground....

**Comment by schwiti6190** [comment]
@FrozenStorm1029 Thanks for you're input, but for now we won't be exploring this idea.
This feature seems to be pretty niche and would take a decent chunk of work.
If you've got a good selling point for this feature, than I might consider exploring this idea in the future.
