### ISSUE TITLE
Abfahrer findet keinen Weg[Question]

### ISSUE THREAD

**Issue by MacRama1** [Courseplay/Courseplay_FS22#2954]
Hallo CP Team,

so gut wie immer sagt der Abfahrer dass er keinen Weg findet nachdem er den Drescher abgetankt hat.
Das liegt daran das er gleich nach dem zurücksetzen nach einem Weg sucht obwohl der Drescher noch nicht auf seiner Bahn ist.
Könnte man das nicht so einrichten das der Abfahrer erst wartet bis er vom Drescher ein OK bekommt sobald er wieder auf seiner Bahn ist.

Gruß Mac

![fsScreen_2023_11_15_15_11_01](https://github.com/Courseplay/Courseplay_FS22/assets/99003248/5f6ead03-e8a4-4fa9-9c06-2068da3d463d)

![fsScreen_2023_11_15_15_11_16](https://github.com/Courseplay/Courseplay_FS22/assets/99003248/b0e0c0fa-5888-44d0-90c1-4814ba1651d8)

![fsScreen_2023_11_15_15_11_23](https://github.com/Courseplay/Courseplay_FS22/assets/99003248/34ddcaf9-a0e7-439c-a9be-107642e4c5db)

**Comment by Tensuko** [comment]
Viel Interessanter ist wo er hin will.
Oft liegt es daran, dass dort was im Weg ist.
Davon mal Bilder wenn es geht bei "Tageslicht" -> "gsTimeSet 10" (wenn Konsole aktiv)

**Comment by MacRama1** [comment]
Nun, er ist voll und will zum LKW am Feldrand, der ist auf der Minimap Sichtbar....

**Comment by rohne83** [comment]
Screenshot vom LKW in just jenem Moment bei Tageslicht wäre hilfreich

**Comment by regs1980** [comment]
@MacRama1 Drescher Kurs erstellen mit Feldmitte Beete/Lands, dann klappt das auch mit dem Abfahrer. 
Dieser dreht dann nämlich links ab (wo jetzt deine Frucht im Weg steht) und muss nicht ewig warten auf den Drescher bis der wieder angefangen hat. 
Feldmitte Hoch/Runter ist nicht ratsam für einen Drescher.
Probier es aus.

**Comment by MacRama1** [comment]
> @MacRama1 Drescher Kurs erstellen mit Feldmitte Beete/Lands, dann klappt das auch mit dem Abfahrer. Dieser dreht dann nämlich links ab (wo jetzt deine Frucht im Weg steht) und muss nicht ewig warten auf den Drescher bis der wieder angefangen hat. Feldmitte Hoch/Runter ist nicht ratsam für einen Drescher. Die rückwärts Fahrtgeschwindigkeit kann man auch erhöhen, 5 km/h ist zu wenig. Probier es aus.

Danke, ich probier es es bei der nächsten Ernte...

**Comment by regs1980** [comment]
> Aber wie ist es dann mit 2 Dreschern, übernimmt dann jeder jeweils 1 Beet?

Quatsch, es wird ein Drescher Kurs erstellt, mit einer linken und rechten Seite. 
Findet man auch in der Hilfe für CP im Spiel.
