### ISSUE TITLE
Drescher kann nicht entladen werden[Question]

### ISSUE THREAD

**Issue by MacRama1** [Courseplay/Courseplay_FS22#2955]
![fsScreen_2023_11_15_23_16_06](https://github.com/Courseplay/Courseplay_FS22/assets/99003248/6830501c-c49a-4c9b-8844-46b31eaab761)

Hallo CP-Team,

grundsätzlich ist die Idee gut daß der Abfahrer sich neben die Frucht stellt und auf den Drescher wartet. (Ich liebe diese Funktion)
Leider hat sie kleine Mängel. 
Eines davon ist auf dem Screenshot zu sehen.
Der Abfahrer wartet am Rand auf Drescher 2,  der fährt aber nicht weiter weil er 75m Abstand zu Drescher 1 einhält um nicht zu dicht aufzufahren.
Augenscheinlich fährt der CP Abfahrer den Drescher an, welcher am dichtesten dran ist.
Vielleicht habt ihr eine Idee wie sich das verbessern lässt, evtl. würde es funktionieren wenn zuerst der vollere bzw. stehende Drescher angefahren wird. Ich habe keine Ahnung vom Scripten und weiß deshalb nicht wie aufwendig das wäre, da seid Ihr die Profis.

Ein anderes Ding mit dieser Wartefunktion, (davon habe ich leider kein Screenshot) ist folgendes...
Der Abfahrer wartet auf den Drescher am Fruchtrand, in der Zwischenzeit ist der Drescher aber schon voll und fährt nicht mehr weiter.
Das bemerkt der CP-Abfahrer leider nicht und wartet nach wie vor an derselben Position.
Hier wäre es vllt. sinnvoll das der Abfahrer nach einigen Sekunden Wartezeit nochmal prüft wo der Drescher ist oder das der Drescher bescheid gibt das er nicht mehr weiterfahren kann. 

Gruß Mac

**Comment by regs1980** [comment]
@MacRama1 Wieso ist der rechte Drescher schneller als der andere und mit welcher Feldmittenstrategie arbeiten die Drescher das Feld ab?

**Comment by Tensuko** [comment]
Drescher rufen die Abfahrer und da Drescher 2 den rufen konnte weil keine Frucht im weg ist wie bei Drescher 1 kam es zu dieser Situation.
Man müsste eine höhere Rufpriorität haben, was leider nicht so einfach ist.

Die Frage von regs ist gut, weil am besten fährst du bei Dreschern wenn du als Feldmitte "Beete" verwendest. Bei hoch/runter müsste man noch den symetrischen bahnenwechsel beachten damit ein Drescher nicht links und rechts Frucht hat.

**Comment by MacRama1** [comment]
Der symetrische bahnwechsel ist bei beiden Dreschern aktiv und hoch/runter.
