### ISSUE TITLE
[Q45FT cutter harvest problemuestion]

### ISSUE THREAD

**Issue by millepattes2** [Courseplay/Courseplay_FS22#2957]
Bonjour, quand je recolte avec une barre de coupe 45ft, la moissonneuse s'arrête, vide la paille en fin de ligne puis recule et reste bloquee sur le tas. Donc en fin de chaque ligne, il faut debloquer la moissonneuse. Les ouvriers AI vident en reculant et ne restent pas bloqués mais je préfère courseplay. Ca fait longtemps que j'ai ce problème et je me suis quand même décidé de vous en faire part.
Salutations

**Comment by regs1980** [comment]
Utiliser les tournières et utiliser un autre centre de champ comme les plates-bandes/campagnes.

**Comment by schwiti6190** [comment]
@millepattes2 If this issue is still happing, than feel free to reopen this issue and let us now with images and a log what exactly is the problem.
@regs1980 Thanks for trying to help with the language :)

**Comment by millepattes2** [comment]
Sorry, but I didn't have any harvesting to do when you responded, here is a photo of the problem Issue "#2957"
The harvester is stuck on the pile.
It stops at the end of the line, unloads then moves back. It should unload by reversing
Happy New Year 2024 to the whole team
![Capture d’écran (1)](https://github.com/Courseplay/Courseplay_FS22/assets/126943613/fad5639d-c92e-40e4-bf03-c5faca429af9)
