### ISSUE TITLE
[Question]Falsche Fahrbahn

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#2958]
hallo

Ich fahre mit 2 Helfern

Der zweite fährt anstatt rechts die linke fahrbahn, was muss ich einstellen
![Falsche Fahrbahn](https://github.com/Courseplay/Courseplay_FS22/assets/47453761/00e1b0e5-24ec-4ab2-b55a-9966bde3de3c)

**Comment by andreasthu** [comment]
meines wissens nach gibt es symmetrischen und asymmetrischen Bahnwechsel.
hast du bei beiden Fahrzeugen die gleiche Einstellung ?
lg
andreas

**Comment by Hendirk** [comment]
Hab ein auf links und ein auf rechts eingestellt --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.11.23, 08:46 schrieb Andreas ***@***.***>:

   
  meines wissens nach gibt es symmetrischen und asymmetrischen Bahnwechsel. hast du bei beiden Fahrzeugen die gleiche Einstellung ? lg andreas

**Comment by Tensuko** [comment]
Wie andreas schrieb, symetrischer Bahnenwechsel tauscht je nach an oder aus jede 2te Bahn das links/rechts.
Das ist so gewollt. Andere Bahn und es passt wieder.
