### ISSUE TITLE
[BUG_SP]LUA CALL Stack mit Valtra G135 u SWADRO S 350 HIGHLAND

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#2959]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Ein Schwaderkurs mit Valtra G135 und SWADRO S 350 HIGHLAND (Seitenschwader aus dem Hay und Forage dlc)
(Kurs im anhang)

**Actual behavior**
A clear and concise description of what happen.
der Valtra fährt anstatt der wende einfach geradeaus, lua callstacks in der log
ich habe beides (ai beim wenden aktiv und deaktiv) versucht 

**Expected behavior**
eine wende wäre schön

**Screenshots**

![fsScreen_2023_11_18_06_43_46](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a84204e4-84ef-43b7-91b2-c31589652a99)
![fsScreen_2023_11_18_06_43_51](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/255747e2-c692-4a81-bdda-b71df7ab1730)
![fsScreen_2023_11_18_06_44_44](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/99a21acc-1c21-4de9-b857-70c6be43c707)
![fsScreen_2023_11_18_06_44_47](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/efba4e0f-071a-4a56-a2d1-9c00d80376a4)

**Courseplay version**
Version used: 
7.4.0.0 (aktuell)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13399147/log.txt)

**Map**
Map played on.
Neu-Minibrunn von Topace888

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Valtra G135(giants)
Krone SWADRO S 350 HIGHLAND (giants-dlc)

**Relevant script mods**
Mods like Autodrive or VCA and so on.
nicht verwendet

[w15_3,5m.Schwaden.txt](https://github.com/Courseplay/Courseplay_FS22/files/13399158/w15_3.5m.Schwaden.txt)
hier noch der Cp-Kurs:
es ist die erste Wende, also so ca. ab zeile 20
es passiert eigentlich bei sehr schrägen Kanten, ab 45grad Feldkantenschräge
ist die Stirnseite bei 90grad oder ähnlich funktioniert die wende

lg
andreas

**Comment by regs1980** [comment]
Die Gradzahl des Winkels ist zu klein. 
Editor öffnen und den Punkt etwas weiter nach hinten versetzen, sodass die Gradzahl sich vergrößert, dann klappt es auch mit der Wende.
![2023-11-18 08_13_54-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/28ceded5-1122-4770-b381-93aeca9f437c)
![2023-11-18 08_14_07-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/216d8a0a-9d76-4a22-a395-d70efccad39d)

**Comment by andreasthu** [comment]
Hallo @regs1980 
Ja genau, wenn die Feldkante schräg zuläuft.
Am südlichen ende der Wiese habe ich genau eine 45° schräge Feldkante (mit GPS gepflügt) und da tritt dieser bug ebenfalls auf. 
Ich werd es später mit deinem workaround versuchen, verlängere aber ev die strecke nach der wende als die erste zu kürzen.
Lg
Andreas

**Comment by andreasthu** [comment]
hallo
das ist ein schmaler Grat, manchmal funktioniert es, manchmal nicht.
auf deinem Beispielfoto kann ich es bestätigen, auf der südseite hingegen ergibt es trotzdem eine Geradeausfahrt mit lua callstack
und dabei habe ich den winkel verkürzt (einen wp gelöscht)
![fsScreen_2023_11_18_12_48_45](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/e3cbd3bc-eef4-4df5-a018-2ef90b9cd847)
![fsScreen_2023_11_18_12_48_49](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/3396190f-c88f-4ea4-8b8a-52f17707ce50)

und sogar eine fast rechtwinklige situation versucht (zwei wp gelöscht):
![fsScreen_2023_11_18_12_43_03](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/53f2374c-de57-441a-ac27-ca4edc9872ff)
![fsScreen_2023_11_18_12_43_06](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/341fbb45-6d70-4505-b440-b0f949ea08d9)

und trotzdem ein lua callstack ohne wende.
kann es sein, das es nicht der winkel ist, sondern der abstand von turnstart zu turnend?
lg
andreas

**Comment by andreasthu** [comment]
interessant
mit dem reform mounty 110 funktioniert es normal:
![fsScreen_2023_11_18_14_02_56](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/de0800dd-1189-474e-b2a2-f3b29ae1777d)
![fsScreen_2023_11_18_14_02_58](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/5e1bbd27-310d-41f1-8745-43784f9445f9)
![fsScreen_2023_11_18_14_03_02](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/48c83fbe-0e46-4680-b4e9-e5160adc6c64)
![fsScreen_2023_11_18_14_03_09](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/31ecf73b-2d0d-402d-b4f6-9a6758b7b0a4)
lg
andreas

**Comment by regs1980** [comment]
Das wäre die nächste Frage von mir gewesen, mal einen anderen Schlepper testen.

**Comment by Tensuko** [comment]
Teste bitte mal den kleinen Pöttinger Schwader.

**Comment by andreasthu** [comment]
Hallo @Tensuko 
guten morgen
hab den Pöttinger TOP 342 und den Kuhn GF 8712 probiert
mit allen drei Schwadern hat der Valtra G135 Probleme
der Mounty hingegen wendet normal.

was ist "Teste bitte mal den PR" ?

lg
andreas

**Comment by andreasthu** [comment]
hab den "PR" gefunden
scheint erstmal zu funktionieren:
![fsScreen_2023_11_20_08_32_37](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/6d977dc7-385d-425c-beab-a35ebd0f7b1c)
![fsScreen_2023_11_20_08_33_51](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/2b9c3a43-134e-44d2-9448-fca663f56f5a)
danke,
lg
andreas
