### ISSUE TITLE
problems with startpoint

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#296]
Hallo!

1. I create a course in the helpermenu-courseplay!
2. Than I will start the courseplayhelper via the courseplay-HUD!
3. There I chose the option: start the course at the FIRST Point!
4. But than the machine starts to drive to the FIRST Point and change the driving-direction!!

![Screenshot 2022-01-01 162946](https://user-images.githubusercontent.com/53146565/147854149-97b5684a-f180-437e-9cb7-dd861e4aecda.png)
![Screenshot 2022-01-01 162848](https://user-images.githubusercontent.com/53146565/147854151-5610f7c4-389e-4815-9119-fb78d6d2fd35.png)
![Screenshot 2022-01-01 162453](https://user-images.githubusercontent.com/53146565/147854152-2a556837-fb11-4802-bdd9-b62233fba586.png)

**Comment by 60erjonny** [comment]
Let the course fully ads. Did you generate the course clockwise or counterclockwise?

**Comment by Tensuko** [comment]
Why did you clear our template ?
There is all that we need to know and no logfile again...

Try it again, sry but this is frustating...

**Comment by RealNeo80** [comment]
but its correct how its working ....

**Comment by MisterGeniusj007** [comment]
-> Tensuko: Sorry about the Dont-Using of Your template!
-> RealNeo80: The Course is okay! But if I start the using of the course by starting at the FirstPoint of the Course, the machine changes the direction an is working not on the field but over the hole map!
My pictures are in the wrong series!!!
Sorry about!

-> I will try to report these error once again and by using Your template

**Comment by RealNeo80** [comment]
for me its looking that you starting from the false side :P
if you retry, please put all debug channels on

**Comment by Tensuko** [comment]
> Edit: what i found out, sometimes if you are too far from the Startpoint, CP is doing some strange things ;)

That should be gone in 7.0.0.10 if startpoint is too far.
Will have a look for the startpoint problem.

**Comment by MisterGeniusj007** [comment]
Thank You Tensuko!
Now I think You understood my little problem!!
