### ISSUE TITLE
Use default map zoom after savegame start

### ISSUE THREAD

**Issue by FalPos** [Courseplay/Courseplay_FS22#2962]
Mir ist aufgefallen das bei der Verwendung von CP nach jedem Starten eines Savegames die PDA-Map stark herangezoomt dargestellt wird. Man muss dann jedes Mal neu herauszoomen. Das ist auf Dauer ziemlich nervig. Nutzt man CP nicht (Mod deaktiviert) dann wird die PDA-Map korrekt dargestellt. 
Ich weiß nicht, ob dieses Problem schon einmal angesprochen wurde, ich konnte zumindest nichts finden.

**Comment by Tensuko** [comment]
Kann ich nicht bestätigen, wenn ich irgend eines meiner savegames lade, bin ich normal reingezoom, nicht die vergrößerte zoomstufe.
Ich vermute hier einen modconflict.
Da wird die zoomstufe auch nicht speichern, ist das eher unwahrscheinlich, dass es ein CP Fehler ist.

**Comment by FalPos** [comment]
Ich schaue mir das nochmal an, allerdings haben andere User auch mit diesem Problem zu kämpfen. Ich hatte nur festgestellt, wenn man CP deaktiviert, dann wird die Karte wieder normal dargestellt.
