### ISSUE TITLE
[Feature] Vertical height of pipe improvements, specifically to articulated pipes (Panther, Tiger, T4-40)

### ISSUE THREAD

**Issue by realskudd** [Courseplay/Courseplay_FS22#2963]
**What is the problem this feature/enhancement solves?**
When harvesting beets with one of the self-propelled machines (Tiger, Panther, T4-40, etc.) in conjunction with an AutoDrive unloader, the harvester will usually lower the pipe as much as possible, despite the height of the unloader's trailer.

**Describe the solution you'd like**
It would be great if either the CoursePlay harvester would detect the height of the unloader, or allow for setting a specific vertical height for that vehicle's pipe.

**Describe alternatives you've considered**
Sure, using shorter trailers would help, but on fields where there's a slope, it can cause the pipe to be lower than the sides of the unloader's trailer. Basic geometry.

**Additional context**

**Comment by Tensuko** [comment]
It does detect the hight of the unloader.
Example where it is a problem?
Ofc as you already wrote, with a slope on the field it will be tricky to get it right.

**Comment by realskudd** [comment]
https://i.imgur.com/bb60Sca.mp4

Tractor: 8280 TTV
Trailer: TMK 273
Map: Haut-Beyleron
Field: 22

**Comment by realskudd** [comment]
I've tried playing with the AD "Pipe Offset", but I've found that 2m is too much, 1.75m is too little and produces the behavior in the video clip above.

**Comment by realskudd** [comment]
This shows what the CP driver does with the pipe articulation:

![image](https://github.com/Courseplay/Courseplay_FS22/assets/4642150/c6c8271d-22d8-4c0e-8614-e2278d22fca5)

**Comment by realskudd** [comment]
If I try to drive the unloader myself, the pipe tip is fully extended until I drive up to it, then it lowers. I'm able to get under it before it lowers fully, but then the harvester is unable to unload as the pipe is fully lowered and now is unable to determine the unload target.  Further, it traps the trailer under the pipe and I have to stop the harvester and extend the pipe myself.

**Comment by realskudd** [comment]
At this position it is able to unload.
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4642150/3abfb174-73af-4136-85b2-405bb9e03c07)

**Comment by realskudd** [comment]
Bleh, even with a shorter trailer on more level ground, it happened:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4642150/79bf9ae6-2d76-414d-ae07-6a45152bad00)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/4642150/5b126485-df1d-4414-be4e-75a1d10e89d0)

**Comment by realskudd** [comment]
As the unloader approached, the harvester dropped the pipe so low that hit the cab of the tractor then the front of the trailer.

**Comment by Tensuko** [comment]
Always a Trailer with that extra extension on top.
I wonder how that looks when you take a normal trailer without that extra on top.
Like that one, even with a slopw it have enough space.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/5f3db8f0-6edf-4dc1-bd1e-b8679f13d825)
Or a taller one.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/9de8babd-6784-49d8-8bc7-5d6a98022131)

**Comment by realskudd** [comment]
What's the outlook on getting this in a release?

**Comment by Tensuko** [comment]
Release will come later, just wait for it.
