### ISSUE TITLE
[Question] Courseplay (7.3.0.0) can't connect to Server

### ISSUE THREAD

**Issue by Ergolden** [Courseplay/Courseplay_FS22#2964]
My question is that I'm not able to use courseplay in fs22 because when i try to load into a game that involves courseplay it doesn't
let me connect.

While loading into a game with courseplay it pops up an error box that says Courseplay(7.3.0.0): for help, bug reports or patch notes please visit: http://github.com/Courseplay/Courseplay_FS22. then if you hit ok, it still try's to load the game and then it says sorry it can't connect to server.

Any help is greatrly appreciated

**Comment by Tensuko** [comment]
That is way to less information.
I would wait for Version 7.4.0.0 to come into modhub.
(Or load it from here: https://github.com/Courseplay/Courseplay_FS22/releases )
If Problem still exists, I need a logfile from Server and your Client.

https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
