### ISSUE TITLE
main Updated 37 minutes ago by Tensuko[BUG_SP]

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#2967]
CP startet leider nicht!
Leider kann ich keine Log einfügen, da ich den Butten nicht angezeigt bekomme!
In der Log wird der Error
Error: Unsupported mod description version in mod Courseplay_FS22
angezeigt!

**Comment by Tensuko** [comment]
Weil du dein Spiel nicht geupdated hast!
