### ISSUE TITLE
[BUG_SP] Salary setting problem

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#297]
Up to 7.0.0.9 the function was usable, and the percentage of the salary could be set, now with 7.0.0.10, the data is not displayed, by clicking on the arrows, it actually changes the data, but it is not displayed, so it is not clear what is set. In the courseplay.xml file, in the saving folder, there is the entry wageModifier, which shows the selected setting.
7.0.0.8
![Screenshot_2](https://user-images.githubusercontent.com/24955554/147854379-7fe2ba94-2096-4291-8319-0d135f4c88e4.jpg)
7.0.0.10
![Screenshot_4](https://user-images.githubusercontent.com/24955554/147854380-92625e16-94ee-4348-86b7-7d9fc5d5a31a.jpg)

**Comment by Tensuko** [comment]
Yea the Number is gone, the function is still there, but this needs to be fixed, totaly agree.

**Comment by RealNeo80** [comment]
i see the numbers in 7.0.0.10

**Comment by Tensuko** [comment]
I also don't see it, thats a bit strange...

**Comment by RealNeo80** [comment]
![image](https://user-images.githubusercontent.com/8066324/147860408-24603bac-c6bb-4b26-a567-538fdd7d2ded.png)

**Comment by Roby1164** [comment]
Found a possible problem:
In the GlobalSettingsSetup.xml file, as seen in the picture, there are empty spaces between the items. I removed the gaps, and now everything is back to work ....
![Screenshot_2](https://user-images.githubusercontent.com/24955554/147870418-9d10ffca-bb3b-4ca9-ac5e-645f9bea16e7.jpg)
Here is the menu after editing:
![Screenshot_4](https://user-images.githubusercontent.com/24955554/147870466-4d7d3b53-0a73-4c3b-bfab-7ffff0e59d95.jpg)

**Comment by RealNeo80** [comment]
its interesting, my global settings are different from yours, if you look on unit, in mine its before the default value, and you are correct there are no spaces in mine

![image](https://user-images.githubusercontent.com/8066324/147872289-bf16282a-09a2-483e-861d-4c683cc6b0ec.png)

**Comment by Roby1164** [comment]
The formatting is also different.
In mine, there is first the default and then the unit, in yours it is the other way around !!!!
However, it seems to me that with 7.0.0.11 the problem has been fixed.

**Comment by Tensuko** [comment]
@RealNeo80 
One is text, one is XML View...

**Comment by Tensuko** [comment]
Also it is fixed on main now.

**Comment by Roby1164** [comment]
Opening with edge or other browser does not guarantee to display correct formatting. But just go to the file in the folders here on the Github, and viewing it you see the error.
Now I have entered a request for correction, since precisely by eliminating the spaces present, the problem is solved. Then, because some download the file, and the error does not happen, while others do, I don't know why it happens ...

**Comment by schwiti6190** [comment]
@Roby1164 Is this fixed with the latest version ?

**Comment by Roby1164** [comment]
> @Roby1164 Is this fixed with the latest version ?

Yes....
