### ISSUE TITLE
Improving Dewulf equipment [if possible]

### ISSUE THREAD

**Issue by 37cee** [Courseplay/Courseplay_FS22#2972]
First of all, i love your work. I am very grateful for the time you invest in this without this mod i would care much less about FS as i do.

I am aware you might have run into this and you might be working on this. This is my feedback of the function of Courseplay (CP) + Autodrive (AD) in combination with the Harvesters, that are part of the "premium" DLC. And yes iknow, that you can't change anything, when AD is the culprit. 

General note: Consider this more of a Feedback, what i ran into using the new Premium DLC. All harvesters had their working width and offset adjusted , the generated course was "spiral & no headlands"

Dewulf P3CL Profi & GCCI 
Both work up to the unloading. 
- I don't think those are worth touching, But in theory it might be possible, to make CP unload and automatically buy boxes.

Dewulf P3K Profi & GKIIS
CP knows how they work, once the tool distances are set up correctly. The default position of the pipes are not ideal, especially on the P3K. When used in combination with an AD, the Unloader does not drive up far enough to toggle the unloading. (Maybe this is due to the default pipe positions, but it did not look like that on the GKIIS).
- I assume there is nothing you can do about this, but i don't know enough about the interaction between both mobs. 

Dewulf GBC
The harvesting itself works, after width and offset are corrected. But there are 2 problems i ran into, which might be adjusted on the CP side.
1. AD approaches the harvester at ~85% fill level. Once the Unloader is close CP raises the bunker to the unload position, but does not stop. CP continues driving and lowers the Bunker again, once AD stops, the bunker is lowered again and the veggies are harvested, again.
- here i would like to see, that CP either refuses to raise the bunker until it is at 100% or that CP stops once the bunker gets raised.
2. Once the harvester is at 100% fill level CP stops and raises the bunker, as intended. Once the bunker is empty, CP does not lower the bunker and remains stationary. The bunker has to be manually lowered, before CP can continue. Weirdly when CP stops before reaching 100% fill level, it seems to be able to lower the bunker after unloading (this happened like twice on a field).
- CP should lower the bunker , after unloading 

Dewulf ZKIVSE
This harvester stops early, when closing the field edge. About 2 - 3 meters of veggies remain, when it send the unloader away to engage the turn, but since it wont drive unless an unloader is close, the harvester stops. [i can work around this by removing a headland] The default "pipe" position is fairly low, which makes moste medium sized tractors not somewhat problematic. Like with the other bunkerless harvesters in the DLC, the Unloader doesn't drive up far enough, but in this case it is just enough. 
- Possibly change the turning behaviour & pipe position.

**Comment by Tensuko** [comment]
This is a rather long process but we have that on TODO.

**Comment by 37cee** [comment]
Good to hear. Thanks for the reply.

**Comment by martin8883** [comment]
Hi,
I would ask you to enable "drop to ground" (configurable) for the harvesters without unloader near to it. It´s another type of strategy to load them afterwars from ground.
Regards
Martin

**Comment by Tensuko** [comment]
Wont do that.

**Comment by jozobecka** [comment]
and i have problem when pipe on Dewulf ZKIVSE is too low any fix?

**Comment by Tensuko** [comment]
Wait for next release.

**Comment by Tensuko** [comment]
ZKIVSE is now supported, however, don't use too high Trailers.
The other tools I may check at a later point if we can get them running easy, if that will be the same trouble like we had with that big Harvester, we will skip them...
