### ISSUE TITLE
Plowing the land with 3 plows.

### ISSUE THREAD

**Issue by sasemykin** [Courseplay/Courseplay_FS22#2979]
I tried different variants of plowing with three plows (3.5 meters) The most suitable was shuttle plow, but the problem is in the left tractor (if you go counterclockwise), it is not correctly on the path of plowing, because of which there are places not plowed.

**Comment by Tensuko** [comment]
I need more infos and screenshots.
Dont know when and where you have problems and how you made the course.
Plowing in a curve with a low radius will always cause problems due to simple physics.

**Comment by sasemykin** [comment]
The other field is doing well.
Thank you!
