### ISSUE TITLE
[Question]后期还会跟自动驾驶联动吗？比如字段收获秸秆 AD运回干草棚

### ISSUE THREAD

**Issue by Fanxiangshuo** [Courseplay/Courseplay_FS22#298]
Will it be linked with automatic driving in the later stage? For example, the field harvest straw ad is transported back to the hay shed

**Comment by Fanxiangshuo** [comment]
你们的工作非常牛逼 ， 3Q

**Comment by RealNeo80** [comment]
you can use [Autodrive](https://github.com/Stephan-S/FS22_AutoDrive) for this, its more driving, Coursplay is dedicated to fieldwork

**Comment by Tensuko** [comment]
CP and AD will work together later when we have fixed most important bugs for Fieldwork, I think will start with that then.
