### ISSUE TITLE
[BUG_SP] Giants AI gets stuck and can't turn around when Courseplay mod enabled

### ISSUE THREAD

**Issue by tcirwin** [Courseplay/Courseplay_FS22#2982]
**Steps to reproduce**
1. Start Zielonka map with v7.4.0.0
2. Rent Deutz-Fahr Series 7 TTD medium tractor, BTC 50H disc harrow
3. Start cultivating near southwest corner of field 52 , heading west
4. Hire regular Giants AI worker
5. Wait for the worker to get to the west end of the field

**Actual behavior**
Giants AI worker stuck at the west end of field; doesn't turn around. 

Might be related to size of implement - other bigger cultivators work fine such as Terradisc 10001T. Issue is reproducible on multiple fields with various different implements such as a potato planter or subsoiler.

**Expected behavior**
Giants AI worker turns the disc harrow around and starts cultivating going east

**Screenshots**
![Screenshot (311)](https://github.com/Courseplay/Courseplay_FS22/assets/785638/55aa0fbd-9827-45e7-8263-ba6210d09a10)

**Courseplay version**
Version used: v7.4.0.0

**Log**
https://pastebin.com/fzHgfGrC

**Map**
Zielonka

**Vehicles/ implements involved**
Which vehicle or implement? Deutz-Fahr Series 7 TTD medium tractor, BTC 50H disc harrow
Mod yes/no ? Only Courseplay

**Relevant script mods**
None enabled

**Comment by Tensuko** [comment]
Known Issue that we cant fix as we dont know what it causes.
It does not always happen if we try that.

To be honest I dont know why use giants helper if you have courseplay. It can do the same task in the same way.

**Comment by andreasthu** [comment]
a little work fix:
get out of the tractor.
the turn bug is only when the giants ai helper work and you are tabbet in.
lg
andreas

**Comment by tcirwin** [comment]
@Tensuko Thanks for the reply. I appreciate all of the work on this mod.

> It can do the same task in the same way.

I use Courseplay often for bigger jobs or when multiple tractors need to follow the same path such as for baling. But for simple tasks it's easier to start Giants AI because there is zero input needed. So in my case I use both Courseplay and Giants AI quite a bit.

> It does not always happen if we try that.

I am not sure exactly what you mean, but the bug is 100% reproducible every time, and is reproducible on several different fields.

**Comment by tcirwin** [comment]
Thanks @andreasthu , getting out of the tractor working fixes the issue. I'll use that as a workaround and close the issue since it's a known problem.
