### ISSUE TITLE
[BUG_SP] Sprayer saying it needs filling even though it's full.

### ISSUE THREAD

**Issue by Haus-Master** [Courseplay/Courseplay_FS22#2985]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki  - READ

**Steps to reproduce**
Steps to reproduce the behaviour - Fill sprayer and attempt to start course.

**Actual behaviour**
A clear and concise description of what happens - Vehicle travels to start point, unfolds sprayer, as soon as it's about to start the course flashes up the message "Needs to be refilled", folds sprayer.

**Expected behaviour**
A clear and concise description of what you expected to happen - Vehicle travel to start point, unfold sprayer, start and complete course, fold sprayer, give finished work message.

**Screenshots**
![fsScreen_2023_11_29_18_46_46](https://github.com/Courseplay/Courseplay_FS22/assets/152433509/3cc80909-d34b-4210-ae71-88dccafb9fad)

**Courseplay version**
Version used: 7.4.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on - Saxthorpe Farm

**Vehicles/ implements involved**
Which vehicle or implement - Any tractor, Kubota XMS218 sprayer, and other sprayers.
Mods - Yes

**Relevant script mods**
Autodrive installed.

**Comment by Tensuko** [comment]
And why no logfile?
Pretty sure its a mod conflict or something, I use sprayer myself and it works just fine.

**Comment by Haus-Master** [comment]
![fsScreen_2023_11_29_21_52_47](https://github.com/Courseplay/Courseplay_FS22/assets/152433509/b992529d-6ef0-49e4-b249-792dc78cf1ed)


Is console log okay? This is the second after I get the message. I'm using weedspot spraying, if that makes any difference? (I doubt it will). Also if it is a mod conflict do you have an idea of what it could be? can provide the Log.txt from my FS222 folder if needed.

**Comment by Haus-Master** [comment]
Works without weedspot spraying on the sprayers but doesn't when that addition to the sprayer is added. Without weedspot the sprayer works fine and completes the course fine. With it on I get the needs to be refilled message, this happens no matter what I have loaded in the sprayer (Herbicide or Liq' Fert').

**Comment by Tensuko** [comment]
"Works without weedspot spraying on the sprayers but doesn't when that addition to the sprayer is added."
What is weedspot spraying?
The one from PF?
It doesn't have anything to do with AI Driving, spotsprayer works fine with CP as well since I use the JD one from PF on my savegame...

**Comment by Haus-Master** [comment]
"The one from PF? It doesn't have anything to do with AI Driving, spotsprayer works fine with CP as well since I use the JD one from PF on my savegame..."

No not even that one works with spot spraying.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13506101/log.txt)

**Comment by Haus-Master** [comment]
No, not even the one from PF, just tried it.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13506122/log.txt)

**Comment by Tensuko** [comment]
Oh shit, must got broken at any stage... We have a look.

Anyway, some tips for your logfile:

This does not belong in the mods Folder:
- FS19_Komatsu_PW98_FSM

Then I read stuff like this:
2023-11-29 21:47 Available mod: (Hash: 90e99485dedc8c599277caa8a177031c) (Version: 1.0.0.0) FS22_zzFillLevelWarningForageWagon
2023-11-29 21:47 Available mod: (Hash: 84cf2ee428d65419a3d186c2950b3364) (Version: 1.0.0.0) FS22_zzzzzzFilllevelwarning

Or this:
R5.2.1_K03y_1preset

You got over 2200 Mods, thats way too many!
There are a lot of mods with Errors and some produce a callstack wich can cause anything to not work correctly.

**Comment by Haus-Master** [comment]
I'll 100% be cleaning out my mods don't worry. Thanks for the help and thanks for your time have a good day.

**Comment by dominik199818** [comment]
remove pumps'n hoses addon <3 it worked for me
