### ISSUE TITLE
[BUG_SP] Courseplay does not work in single game (DX11)

### ISSUE THREAD

**Issue by dedMishko** [Courseplay/Courseplay_FS22#2986]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Launching saved game.

**Actual behavior**
Game crash, when exit

**Expected behavior**
Game will be work.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/152767641/7d639908-6626-4ddb-9744-d6851c9ec1f5)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/152767641/695e7fbc-cb98-4d0a-8004-e8e7652b3b43)

**Courseplay version**
7.3.0.0: 

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13538230/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
-
No other mods

**Relevant script mods**
-

**Comment by schwiti6190** [comment]
@dedMishko Hello could you try again with the newest version here: https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.4.0.0 ?

**Comment by dedMishko** [comment]
Thank you. That's all right!!

**Comment by dedMishko** [comment]
The previous version still remains in my library of FS 22 mods (Steam version),
And even the game offers me to update the new version to the old one))
