### ISSUE TITLE
[QUESTION] when renaming, do not show empty line, but existing name? - beim Umbenennen, keine leere Zeile anzeigen, sondern bestehenden Namen ?

### ISSUE THREAD

**Issue by haamic** [Courseplay/Courseplay_FS22#299]
Hello,
would it be possible that when renaming the old name is in the change line and not a completely empty input line?
If only a small spelling mistake is to be corrected, the complete name does not have to be entered again.
Would be nice if you could implement it that way. Thanks
++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
wäre es möglich, das beim Umbenennen der alte Name in der Änderungszeile steht und nicht eine komplett leere Eingabezeile?
Wenn nur ein kleiner Schreibfehler korrigiert werden soll, muss nicht der komplette Name neu eingegeben werden.
Wäre schön, wenn ihr das so einbauen könntet. Danke

**Comment by Tensuko** [comment]
Nein, das geht nicht soweit ich weis. Ich kann die Frage wetierleiten, mache hier aber trotzdem zu.
