### ISSUE TITLE
[Question] how to set grain cart to unload combine before its full

### ISSUE THREAD

**Issue by newride** [Courseplay/Courseplay_FS22#2994]
Is there something i am missing with the grain cart feature. When i set it up it will only unload the combine when the combine gets full. If i remember right in previous versions there was a setting it the options that you could set the unload at like 50% and the grain cart would unload the combine when it filled to 50%.

**Comment by Tritura2** [comment]
This option doesn't exist any more. I think the combine is calling an unloader depending of calculations when it would be full. You can only set a percentage for the unloader itself.

**Comment by Tensuko** [comment]
The unloader will drive to the combine based on a calculation and tries to reach the combine when it hits 80%.
That values is fixed and will not be changed.

You can only tell when the trailer drives off to sell stuff.

**Comment by S-eler** [comment]
@newride  - you can always use AutoDrive for this, and there on AD level you can configure harvester to recall unloader even  on 0%. AD unloader also works on-the-go, unloading harvester during harvesting.
