### ISSUE TITLE
[BUG_SP] Unable to create spiral counterclockwise (both headland and center)

### ISSUE THREAD

**Issue by S-eler** [Courseplay/Courseplay_FS22#2996]
**Steps to reproduce**
Try to create course for base-game towed beet harvester (pipe on the right side). I was trying with "field posititon" marker on every corner, before it, after it, small-large distance - many attempts. I was unable to achieve course where i was able to have counterclockwise spiral center. For normal, left side piped harvester it's possible to create clockwise headland and clockwise center spiral (usually marker on the end of short side of field). Here unfortunately, every attempt create clockwise center part

**Actual behavior**
as mentioned above

**Expected behavior**
as mentioned above - to be able to create full counterclockwise course. At this moment, i'm 99% sure that it's impossible.

A dream woud be to have an additional setting in expert mode, "Spiral-clockwise" and "spiral-counterclockwise" - especially due to fact that spiral mode is used almost only for tools with pipe to unload on the go, and sometimes pipe is on the wrong, right side ;]

**Comment by Tensuko** [comment]
All part of the new generator.
Just wait for it.
It will still take a while.

A complete template is also needed as the generator also gives debug informations.
But anyway, wait for it....
