### ISSUE TITLE
Suggestion: pipe-Side detection/selection

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#30]
Some vehicles(the Grimme Ventor potatoe harvester) have the pipe on the right side.

it would be nice, if there was a way to generate headlands and lands, so that the pipe of these harvesters also would stay on the harvestet side.

Either by selecting an option, or detecting the side of the pipe of the vehicle.

**Comment by rohne83** [comment]
Similar for spirals pattern. The working direction (clockwise/counterclockwise) seems to be dependent still on the location of the start point, as was the case in FS 19. So in many cases the spiral field rows will be worked in opposite direction as the headlands.

**Comment by Tensuko** [comment]
Does it also not work, if you place the target point from the AI Menu in the right direction ?
If not, we have to get that option running ofc.

**Comment by JDTiger** [comment]
Did not work for Headlands and Land-Mode, might work for spiral, didn't test that one

**Comment by pvaiko** [comment]
This will be partly resolved with #72

**Comment by JDTiger** [comment]
Hey,
Sorry for the late reply.

Generating the Headlands now works, with pipes on the right side.
But the Coursegenerator still generates the lands with the pipe inside the fruit, despite setting course start direction and headland direction counter clockwise.

Harvester used was the Grimme Ventor.

**Comment by pvaiko** [comment]
Need more details and all logs, as it works fine for me. Note that the direction of the lands only depends on which side the pipe is and CP correctly finds the pipe on the right side of the Ventor.

![image](https://user-images.githubusercontent.com/2379521/151663730-67a025d3-f296-40eb-9410-bd4b3b61cfcb.png)

**Comment by JDTiger** [comment]
Hey, here the log and screenshots:
![Screenshot 2022-01-29 151255](https://user-images.githubusercontent.com/9157835/151664422-8cd0bfdc-0bc8-4368-92f0-bfb0579da722.jpg)
![Screenshot 2022-01-29 151304](https://user-images.githubusercontent.com/9157835/151664419-0d7f14c4-d653-4792-86c8-4d466fd38c2a.jpg)
![Screenshot 2022-01-29 151210](https://user-images.githubusercontent.com/9157835/151664423-479f40a8-0175-40b2-a9ec-742c91169d86.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7963859/log.txt)
