### ISSUE TITLE
[Feature] Tastenbelegung für "Fahrzeugdebug" aktiviert bzw deaktiviert

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3004]
**What is the problem this feature/enhancement solves?**
es wäre schön, wenn man den Fahrzeug debug auf eine Taste legen könnte,
so muss man nicht jedesmal ins menü, ganz runterscrollen, den debug aktivieren, und wieder rausgehen,
wenn man mal wissen möchte, an was die wendung hängt

**Describe the solution you'd like**
tastenzuweiung für Fahrzeug debug

**Describe alternatives you've considered**

**Additional context**

lg
andreas

**Comment by Tensuko** [comment]
Unnötige Tastenbelegung.
Wird nicht gemacht.
