### ISSUE TITLE
[Question] Custom Vehicle Configs not loading and I'm not sure why

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3006]
I have a file called VehicleConfigurations.xml located in My Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay In it i have my vehicle settings as below, however it is not reading those settings in game and using CP's defaults instead. What might i be doing wrong? I have tried the console command inside FS22 of cpReadVehicleConfigurations but it says command not found? so I can't test loading different settings.

<Vehicle name="pw10012.xml"
             implementWheelAlwaysOnGround = "true"
             turnRadius = "9.5"
             raiseLate = "true"
             lowerEarly = "true"
    />
</VehicleConfigurations>

**Comment by coatsy35** [comment]
I assume it should be cpVehicleConfigurationsReload (Which is what the console help command lists). When I do that it reloads them and picks up the custom file, however it doesn't alter the in game settings? Do I need to enable something extra to always load custom settings on game start? If I alter CP's Vehicle Config file the changes appear in game as I want, I just don't want to have to update CP's file each time there is an update and would rather use the custom file.

**Comment by Tensuko** [comment]
"however it doesn't alter the in game settings"
What do you mean by that?
What do you expect to happen?
What config did you put there?
Attach your config file so we can see what you did there.

**Comment by coatsy35** [comment]
As you know i've had some issues with the big KV plough that nearly every contract uses (KV PW100 12), so I thought i'd play around with the different turn radius and see how that affected things (it needs to be far bigger than 7.5 and then it starts to to turn correctly). So initially I altered the CP VehicleConfig file and upped the radius to 16. I was happy with that but when CP gets updated it overrides the file obviously, so I created a custom one following the Wiki, but it doesn't override the CP one. My own little test was that I put a custom width in there as well, so when I connected the plough to a tractor I got the correct width rather than 0.5m when folded. (When I put the width in the CP config along with the higher turn radius it changed the instant I reloaded the game and connected the plough to the tractor) so I set the CP back to default and used a custom config, and it never loads the width or new radius. Maybe I have my file incorrect.

My file below - I've dropped it back to a .txt file as GitHub doesn't allow users to upload XML it appears 

[VehicleConfigurations.txt](https://github.com/Courseplay/Courseplay_FS22/files/13629241/VehicleConfigurations.txt)

**Comment by coatsy35** [comment]
Yes. I’ve tried reloading as well. Reload command does read out the contents of the custom file. As I said works fine if I edit the CP file. Perhaps something has broken on custom. Hopefully someone on here can test and let me know if it’s just me

**Comment by Tensuko** [comment]
Current Main, successfull overwrite:
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/8bc7c484-95b0-4572-9811-afb50cc0538d)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/29aff6d9-9021-4612-ada4-c9c498bf13f7)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/3d343c0f-b0c9-4eb8-a0b1-b2f24d9679a8)

Must be on your side. I hope you just changed the file type to .txt for upload only and not have it named .txt in your folder?
(I have to ask such questions...)

Are you sure the .xml file of the tool is correct?
We have some tools in there from FS19, wich .xml name have changed, there is also a command to read out the .xml names for the tools + vehicle.

Not a CP bug, closing.

**Comment by coatsy35** [comment]
Hi, 

yes I just changed it to .txt to upload here. I will double check through the XML when I get back from a few days away. I copied the section out of the CP config file so nothing has changed with the XML file name as altering h settings in CP’s file works just not in the custom config file. I must have something else wrong, I’ll retrace my steps when I get a min.

**Comment by dennis10V** [comment]
Hello,

I have encountered the same issue, I am using Mac but can't get the file to overwrite the vehicle configs. code should work:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<VehicleConfigurations>
    <Vehicle name="itRunner2633HD.xml" disableUnfolding="true" />
    <Vehicle name="potatoHarvester.xml" noReverse=“true” />
</VehicleConfigurations>
```

it is in the right folder and it has the correct name. don't know what I did wrong.

**Comment by coatsy35** [comment]
Yeah, I’ve never got them to work since my original post. I have to edit the main file (in the zip) if I want to change anything.

**Comment by Tensuko** [comment]
> Hello,
> 
> I have encountered the same issue, I am using Mac but can't get the file to overwrite the vehicle configs. code should work:
> 
> ```
> <?xml version="1.0" encoding="utf-8" standalone="no"?>
> <VehicleConfigurations>
>     <Vehicle name="itRunner2633HD.xml" disableUnfolding="true" />
>     <Vehicle name="potatoHarvester.xml" noReverse=“true” />
> </VehicleConfigurations>
> ```
> 
> it is in the right folder and it has the correct name. don't know what I did wrong.

Attach your log.txt pls after you started your savegame.
