### ISSUE TITLE
[BUG_SP] Combine start the wrong way around

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#301]
**Steps to reproduce**
Created a field on No Mans Land, generated a course, selected 'Start at: First Waypoint', and start the combine.
The combine goes to the first point, but the wrong way around.

After first point is reached, the combine is completely lost and starts 'combining' somewhere else.
This happens on different fields, also after restarting FS22.

**Screenshots**
Here you see it goes to the start position the wrong way around.
![2022-01-02 00_24_20-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/147862390-13b4bf01-de3c-48d2-beec-67d983496707.jpg)

Here you see the combine going somewhere where no CP track is. (stopped the combine before making the screenshot, but it was harvesting).
![2022-01-02 00_30_53-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/147862400-77fd61fc-72be-49a2-8798-1f3e85bf6278.jpg)

**Courseplay version**
Version used:  v7.0.0.10

**Log**
https://gist.github.com/JustDen1234/8b4080b42bfd488af736858c9c9cdda0   (newer log file, old one had not enough info)

**Map**
No Mans Land

**Vehicles/ implements involved**
Combine: Rostselmash Nova 330 (start combine on map)

**Relevant script mods**
- Autodrive v2.0.0.2
- AIVE
(both not activated during this issue)

**Comment by RealNeo80** [comment]
@Tensuko so it seems that theres really something wrong with the startpoints. I generated a course for a stonecollector and it was 90° rotated, so it worked only if the vehicle was standing directly on the start point. if the Vehicle was more far, it tried to get the point with 90°.  it worked, but lost the first meters collecting, because auf going out of the 90°

Course generating and everything should in the log, it was field 46 .. should be round about 00:45 in the log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798378/log.txt)

**Comment by BullFlag** [comment]
Here's another example of only the [Start](url) point rotated 90.  This is on CP 7010 with Lizard MT 6m Subsoiler.    The first start point is rotated 90 degrees IF SHARP turn is used.  The smooth turn selection did NOT show a 90 rotated start point.   Even the First Demo Video showed  the rotated start point 90  at 5m 25sec, but it didn't enter from the side for some reason.    Hope this help

https://user-images.githubusercontent.com/23723361/147862857-b6a4b40a-6aa6-4fbc-8a46-7b89472db39f.mp4

s

**Comment by Tensuko** [comment]
@JustDen1234 
Did you place the start point in the direction in wich the start points point at now ?

@RealNeo80 
I could not reproduce this, this is a bit strange...

@BullFlag 
And what Version did you use ? ...

**Comment by JustDen1234** [comment]
@Tensuko:

> @JustDen1234 Did you place the start point in the direction in wich the start points point at now ?

During generation, I selected the combine, then set it to start at the start point with the direction shown with the red arrow (see image below)
![image](https://user-images.githubusercontent.com/68871402/147874847-9475568b-9e0c-4830-901b-13155cc43af1.png)

I have the complete savegame and all mods zipped, and i can zip the CS routes uploaded [here](https://github.com/JustDen1234/FS22_Issues/tree/main/CP_Issue_20220102)

**Comment by pvaiko** [comment]
This log does not appear to have Courseplay in it at all.

**Comment by JustDen1234** [comment]
@pvaiko What do you want me to do, I do not understand what you are asking.

**Comment by pvaiko** [comment]
The log you attached (https://gist.github.com/JustDen1234/4930d9b3a0294165788bd1284a1fca05) appears to have no entry from Courseplay, like Courseplay wasn't even installed or loaded when this log was created.

We need logs from the problem, with the debug activated for the vehicle.

**Comment by JustDen1234** [comment]
okay strange. Because I did activate logging, it is the log.txt file after I closed FS22. I will try to look at it.

**Comment by JustDen1234** [comment]
@pvaiko are these the debug settings you need?
![image](https://user-images.githubusercontent.com/68871402/147876079-e3b56ef5-e76a-40a3-8ef2-4201d4fbfea3.png)

**Comment by JustDen1234** [comment]
New log file [here](https://gist.github.com/JustDen1234/8b4080b42bfd488af736858c9c9cdda0)

**Comment by pvaiko** [comment]
Yes, this has the information I needed. However, does this still happening with 7.0.0.11? 502789d9 should have solved this...

**Comment by BullFlag** [comment]
My video clip upload yesterday was on CP v7.0.0.10      Now on CP v7.0.0.11 the Start "Arrow" Icon is oriented correctly, but the Tractor + subsoiler still is NOT entering straight down the expected track.      Both the Video and Log are using the lastest CPv7.0.0.11 Hope this helps

[log_CPv70011_VideoSmoothTurns.txt](https://github.com/Courseplay/Courseplay_FS22/files/7799542/log_CPv70011_VideoSmoothTurns.txt)

https://user-images.githubusercontent.com/23723361/147884629-7131c200-6e30-482a-9db0-9005bfd2993d.mp4

**Comment by Tensuko** [comment]
Becouse giants drives to the target guys... And you Video shows you placed that target to much inside of the field.
You can create the course and even before click on start job, place the target in front of the start and also next to the field so you have a better approach to your 1st waypoint.

**Comment by BullFlag** [comment]
Thanks, So the Target should NOT be placed on the field ....but next to the field, in front of the target.      I'll give that a try !

**Comment by Tensuko** [comment]
At least for starting the job. The smaler the work width, the more to the border you need to place it if you want him to send to the field and start. Ofc for generating the course you need to have it on the Field.

**Comment by JustDen1234** [comment]
> Yes, this has the information I needed. However, is this still happening with 7.0.0.11? [502789d](https://github.com/Courseplay/Courseplay_FS22/commit/502789d9a3a56fa187600020ec8efa229b2ff55d) should have solved this...

Installed 7.0.0.11, removed the course, and generated it again. Now it works like it should !
Thanks. Keep up the great work !!!
