### ISSUE TITLE
[BUG_SP] Silo Laden 

### ISSUE THREAD

**Issue by TheOnlyChappell** [Courseplay/Courseplay_FS22#3010]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

cant reproduce without mods

**Steps to reproduce**
Silo laden Modus. Volvo Radlader aus der Prem. Version

**Actual behavior**
Gestern hat es ganz normal geklappt, alles super. Heute hört der Helfer direkt auf, wenn ich ihn einstelle. Log zeigt nur an wie weit die Anhänger vom Silo weg sind.

**Expected behavior**
Normale Silo Laden funktion.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/105115808/fc5463d5-67ea-49d8-ac61-dbaef4c79f4c)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/105115808/3186ec8a-cc6d-4ae9-8375-f2c2b7872bc9)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/105115808/7de77522-88e3-427e-9314-0edaa963a502)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/105115808/a83d32b4-c4df-4aa4-9da2-cae5acece57a)

**Courseplay version**
Version used: 7.4.0.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13637094/log.txt)

**Map**
NF Marsch 4fach

**Vehicles/ implements involved**
Volvo Radlader Premium Version

**Relevant script mods**
Autodrive
Maize+

**Comment by Tensuko** [comment]
Radlader mal wo anders hin gestellt und gestartet?

**Comment by TheOnlyChappell** [comment]
Moino, jo, bin schon über den kompletten Hof.. Auch schon einen anderen getestet.. Es ist auch nichts anderes als gestern, außer, dass mein Pc neugestartet ist. Ansonsten keine Veränderung..

**Comment by TheOnlyChappell** [comment]
Yo, habs gefunden..
![image](https://github.com/Courseplay/Courseplay_FS22/assets/105115808/7cdf5555-68a6-4c2c-a04e-7b637c4df7e5)

**Comment by Tensuko** [comment]
Was heist "habs gefunden" ?

**Comment by TheOnlyChappell** [comment]
Das Problem. Das Silo ist in der placeables.xml leer, deswegen hat er den Helfer direkt entlassen.

**Comment by Tensuko** [comment]
Also kein CP Problem.

**Comment by TheOnlyChappell** [comment]
Nein
