### ISSUE TITLE
[BUG_SP] John Deere CP690 Stop in pre-unload

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/Courseplay_FS22#3011]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a route for a field.
Use this machine for harvest cotton in this field.
Wait a full bale of cotton.

**Actual behavior**
The CP690 stop when have the bale back.

**Expected behavior**
The CP690 must unload fully the bale or continue with the bale in your back tray.

**Screenshots**
![fsScreen_2023_12_11_23_11_08](https://github.com/Courseplay/Courseplay_FS22/assets/12070061/4656ef6c-cdbd-44ca-920e-1a74d4947a0d)

**Courseplay version**
Version used: 7.4.0.0

**Log**
Log with debug mode ON
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13649246/log.txt)

**Map**
Zielonka

**Vehicles/ implements involved**
John Deere CP690

**Relevant script mods**
Autodrive 2.0.1.4
EnhancedVehicle 1.2.2.0

**Comment by Tensuko** [comment]
I did let it run on current main branch (next Version 7.4.0.2) and it works without any problems.
So this might get solved with the next release.
