### ISSUE TITLE
[BUG_SP] leitwolf agripower lacks option to start on nearest waypoint

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/Courseplay_FS22#3014]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/5993529/233dec22-01bb-4f92-bb7b-f6610466f59e)

using this because CP is thinking straw piles are a collision. wanting to start midway because im avoiding length issues with the straw pile. it only has an issue when the leveler is attatched.

**Comment by Tensuko** [comment]
Won't fix.
This is not a tool for fieldwork!
