### ISSUE TITLE
[BUG_SP] Pathfinder Reversing and Jack Knifing Multiple Joint Implements (Air Drill) and Getting blocked

### ISSUE THREAD

**Issue by tjpegram** [Courseplay/Courseplay_FS22#3015]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Using an air drill with a 2 track tractor (JD 8RT for example) generate a course with2 headlands and up/down field center, start on headlands. 

**Actual behavior**
Driver decides to reverse on some turns, particularly on an angled course, and gets the drill "jack-knifed" and thinks its then blocked by an object ending its course. Also seem to be unable to prevent pathfinder from reversing, that option seems to have gone missing since I updated to 7.4.0.0

**Expected behavior**
Driver should not have to reverse to make turn on a field with 2 headlands, or if it does it should not get blocked if the drill gets kinked/jack knifed. 

**Screenshots**
![Screenshot_1](https://github.com/Courseplay/Courseplay_FS22/assets/42901657/73e79177-3bdf-4b3a-b258-dcf4784589bd)

**Courseplay version**
Version used: 7.4.0.1(Latest as of posting)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13678314/log.txt)

**Map**
UMRV

**Vehicles/ implements involved**
Which vehicle or implement? 8RT 410, Case precision disk 60ft, In game Hatzenbichler Air drill 18m
Mod yes/no yes

**Relevant script mods**

Mods like Autodrive or VCA and so on.
Autodrive in game, not being used when it happens

**Comment by Tensuko** [comment]
Which mod is it?
You have to turn on field to off.
This is normal turn and if that setting is on it can do reverse.
Nothing to fix here.
If that mod is on modhub I could add it to vehicle config.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Turn off turn on field and it is fine.
If it gets blocked during a forward turn, it should be a bad convert with the old colission and is then a mod issue.
