### ISSUE TITLE
[BUG_MP] Funktion Siloverteiler

### ISSUE THREAD

**Issue by Basti31894** [Courseplay/Courseplay_FS22#3021]
Ich habe das Problem mit der neusten Version von CP kann ich, wenn ich ein Sioloverteiler (kein Schild) dran habe, die Funktion der Siloarbeit nicht mehr auswählen. Es steht nur noch Siloladen zur Verfügung.

**Comment by Tensuko** [comment]
Bitte komplettes template ausfüllen und ich vermute mal wenn dann ist das kein MP problem.
Bitte neues Issue, so ist das zu wenig Infos.
