### ISSUE TITLE
[BUG_MP] Wahrscheinlich auch SP / Siloarbeit nicht auswählbar

### ISSUE THREAD

**Issue by Basti31894** [Courseplay/Courseplay_FS22#3023]
**Steps to reproduce**
Siloarbeit lässt sich nicht auswählen

**Actual behavior**
Bei Schiebeschildern kann ich die Siloarbeit einstellen. Bei Verteilern steht leider nur die Funktion des Silo Ladens zur Verfügung

**Expected behavior**
Beides sollte auswählbar sein. Bzw. der Verteiler kann ja kein Silo Laden.

**Screenshots**
![Unbenannt](https://github.com/Courseplay/Courseplay_FS22/assets/88288152/872ada65-9f6d-42c0-ae39-63a7ff2c9e54)
![Unbenannt1](https://github.com/Courseplay/Courseplay_FS22/assets/88288152/c58ad419-89dd-4a1a-a9fc-f7e3d5fe42c0)

**Courseplay version**
Version used: 7.4.0.1

**Player on the server**
Immer

**Dedicated server or local hosted server**
Dedicated

**Map**
Osteeküste

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Warum wieder keine log oder Info welche Mod das ist...
Also welche Mod und woher, dann können wir gucken.

**Comment by Tensuko** [comment]
Wie man sieht, ein Modproblem. Mit dem Siloverteiler funktioniert es wie es soll.
https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=242708&title=fs2022
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/69ebf6b9-c309-4eee-aa7c-18ae84c3910d)
Vermutlich hat dein Verteiler falsche eigenschaften.

-> Mod Issue. Won't fix.
