### ISSUE TITLE
[BUG_SP] Does not try to find a new detour (blocked by object in the way)

### ISSUE THREAD

**Issue by iCrashMix0** [Courseplay/Courseplay_FS22#3024]
**Steps to reproduce**
First prepare the grass field with mowing etc. until the baler comes into play. I would recommend buying the following baler (no mod or DLC): Pottinger - Impress 185VC Pro. And it doesn't matter which tractor or mower you want/need to buy. I have taken the following: See the "Vehicles/ implements involved" section and download the mod via ls22.

**Actual behavior/Expected behavior**
If the baler has to be baled promptly, the vehicle stops just before the turn. The bale has been pressed out and the vehicle wants to turn, drives back a little and stops because a bale is in the way, I get a message that the vehicle has been blocked by an object and then nothing happens. I have to remove the bale manually, then the vehicle drives back a little and then the vehicle turns around without any problems. I don't understand why the vehicle can't drive forwards and then turns instead of driving backwards. My suggestion would be that if the vehicle is driving backwards and there is an object blocking it, then the vehicle should at least drive forwards instead of just standing around and doing nothing but collecting money.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/110557043/bf457f1a-7b61-47b0-ba59-15278514fc60)

**Courseplay version**
Version used: v7.4.0.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13757304/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/110557043/d258bd46-dc93-45c2-8252-e16b64fe0f5e)
Mods were used, but even without mods the transformers cause such problems as can be seen in the picture.

**Relevant script mods**
Autodrive was completely deactivated.

**Comment by Tensuko** [comment]
turn on field off = no reverse then he does it.
