### ISSUE TITLE
Courseplay

### ISSUE THREAD

**Issue by Markus4479** [Courseplay/Courseplay_FS22#3025]
Im Menü von Courseplay bekomme  ich beim Vorgewende 
nicht gegen den Uhrzeigersinn angezeigt und ich frage mich warum das so ist

**Comment by schwiti6190** [comment]
Hallo, versuche das mal: https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ#any-setting-is-missing-in-the-course-generator-or-another-setting-window

**Comment by Markus4479** [comment]
Danke hat funktioniert
