### ISSUE TITLE
I have 2 features id like added[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3026]
**What is the problem this feature/enhancement solves?**

Bunker silo loading for forage wagons and making heaps with wheel loaders

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
Sry but both won't be done.
Creating heaps with a wheel loader makes no sence.
Loading a bunker with a loading wagon you should try to do on your own and see what happens + that is unrealistic.
