### ISSUE TITLE
Drescher entladen automatik umschaltung

### ISSUE THREAD

**Issue by SliderRyder** [Courseplay/Courseplay_FS22#3027]
Ich dachte mir folgendes : 
Wenn ich Felder von einem Mähdrescher ernten lasse, aktiviere ich im Vorgewende gerne das ,,Drescher fährt selbst abtanken" , um zu vermeiden, dass der Abfahrer in Bäumen, Zäunen etc hängen bleibt,

In den Feldbahnen lasse ich den Abfahrer jedoch gerne aufs Feld fahren, um Zeit zu sparen.

Feature: ,,Drescher fährt selbst abtanken im Vorgewende" - und schaltet nach dem Vorgewende zurück auf ,,fährt nicht selbst abtanken".
Ähnlich wie bei der Strohablage ,,im Vorgewende deaktiviert"

Lg

**Comment by Tensuko** [comment]
Eine Automatik dafür werden wir nicht einbauen, zumal wir das abtanken des Dreschers dann auch entsprechend so umbauen müssen, dass dieser den Drescher ignoriert wenn selbst abtanken an ist.
Da desshalb eh manuelles eingreifen nötig ist, ist es auch kein Problem mal eben ein Settung um zu schalten.

Wenn die normalen Einstellungen drin sind, sollte auch kein Abfahrer irgendwo hängen bleiben da zum abtanken im ersten Vorgewende eine Tasche gebaut wird.

Die umbauerarbeiten dafür wären zu hoch, sry werden wir nicht machen.
