### ISSUE TITLE
[BUG_SP] Headland Turn with Long/Wide Implements

### ISSUE THREAD

**Issue by vSoRx** [Courseplay/Courseplay_FS22#303]
**Steps to reproduce**
Beim ansäen mit der sähmaschine

**Actual behavior**
er versucht zu wenden aber trifft nicht die richtige Linie und dreht sich im kreis

**Expected behavior**
Habe einen Kurs erstellt mit 2 Vorgewende (scharf) und er findet seinen Path nicht mehr und nur noch im kreis (aber nur an so scharfen kanten wo er rückwärts zurück setzen muss)

**Screenshots**
![fsScreen_2022_01_02_02_27_22](https://user-images.githubusercontent.com/23118994/147863766-dd12eac9-7e30-4163-b6a7-3c89f8386473.png)

![fsScreen_2022_01_02_02_26_59](https://user-images.githubusercontent.com/23118994/147863762-97059740-b491-4c68-85f7-c60cf08f6ab2.png)

**Courseplay version**
Version used: 7.0.0.10

**Log**

**Map**
Erlengrat

**Vehicles/ implements involved**
Mod no 

**Relevant script mods**
Mods like Autodrive

**Comment by Tensuko** [comment]
Already fixed on .11 for this Tool

**Comment by Resandise** [comment]
I'm still having this same issue with .12

![fsScreen_2022_01_03_17_28_56](https://user-images.githubusercontent.com/96673100/147991367-997d7224-c9d0-4692-a2f9-fd81950447da.png)

![fsScreen_2022_01_03_17_29_04](https://user-images.githubusercontent.com/96673100/147991373-50b67578-26d8-46dc-b1d3-a6fd8396cf02.png)

![fsScreen_2022_01_03_17_31_13](https://user-images.githubusercontent.com/96673100/147991433-7bd6fd55-d081-4d06-921c-812953c15bfe.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7804541/log.txt)
