### ISSUE TITLE
[Question] Has something changed for combine unloading on the move to fail so often?

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3031]
Got an issue with a my combine in that quite often - probably 90% of the time, when my trailer draws up to the combine, the tractor slows down, the pipe comes out and then before the tractor speeds up the combine puts the pipe away. This keeps repeating until the combine is 95% full and then stops and unloads. Unload on the move is turned on and I am using CP for the unloading and I've tried various different tractors and trailer combinations. Never had this before but there have been a few updates since I last had a long stint at playing. I've attached my log of the tractor and trailer and a video of it happening on youtube below.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13781645/log.txt)

https://youtu.be/rQTgAE_Yl6Y

![fsScreen_2023_12_27_21_13_37](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ce00e473-6713-44e4-9990-4c2dca16cd0d)

**Comment by Tensuko** [comment]
On our side, nothing was changed.
Try AD none RC Version or remove the pipe controller from AD and try again.

**Comment by coatsy35** [comment]
> On our side, nothing was changed. Try AD none RC Version or remove the pipe controller from AD and try again.

Hmmm, I have already removed the following from ExternalInterface.lua

`function AutoDrive:combineIsCallingDriver(combine)	--only for CoursePlay
	local openPipe,_ = ADHarvestManager.getOpenPipePercent(combine)
	return openPipe or ADHarvestManager.doesHarvesterNeedUnloading(combine, true)
end`

AD hasn't been updated since August and I have used it ok since then which was when I removed the above code. Sometimes it works. Any other suggestions?

**Comment by Tensuko** [comment]
Will have to check that.
Oh I might have an Idea but will have to test that first.

**Comment by coatsy35** [comment]
> Will have to check that. Oh I might have an Idea but will have to test that first.

Thank you. Appreciated
