### ISSUE TITLE
Mowing stops when snow is disabled

### ISSUE THREAD

**Issue by pjirsa** [Courseplay/Courseplay_FS22#3038]
Snow is disabled, month is September and I see info message: Waits for snow to clear.

Looks like breaking change was introduced with fix for issue #2812 

https://github.com/Courseplay/Courseplay_FS22/blob/72b2d72ea17d2cdf152c8a7c26e58f3651f6c361/scripts/ai/controllers/MowerController.lua#L15C1-L15C1

**Comment by Tensuko** [comment]
What is the weather state in the game?

**Comment by pjirsa** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/2207109/26c8b39a-c19e-49b9-b9eb-644e8800f7d7)

Let me know if there is a better way to get weather info

**Comment by pjirsa** [comment]
I commented out the `getDriveData()` function in MowerController and it resolved the issue. However, this most likely re-introduces the issue in #2812.

**Comment by Tensuko** [comment]
I don't know what settings you have set for the game.
Can you give me your savegame and maybe also attach the logfile?
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Tensuko** [comment]
Pls try out https://github.com/Courseplay/Courseplay_FS22/pull/3039

**Comment by pjirsa** [comment]
This resolves the issue.
Thank you so much!
