### ISSUE TITLE
[BUG_SP] FS22 hangs when loading SP game with courseplay after another game without courseplay

### ISSUE THREAD

**Issue by jwenting** [Courseplay/Courseplay_FS22#304]
**Steps to reproduce**
- log in on an MP server and play around some
- log out and load an SP game with courseplay selected as a mod
- FS22 hangs during load at 23% (may be a different percentage for different maps).
- kill FS22 from task manager

Verify courseplay is the culprit:
- remove courseplay from mod folder
- repeat first 2 steps
- FS22 loads the SP game normally

Reproduced with several FS22 builds of courseplay, up to and including 7.0.0.10

**Actual behavior**
FS22 hangs during load at 23% (may be a different percentage for different maps).

**Expected behavior**
FS22 loads the SP game normally

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elmcreek and Haut-Beyleron

**Vehicles/ implements involved**
installed but not relevant

**Relevant script mods**
VCA installed on SP but not related to the problem

[log - Copy.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798600/log.-.Copy.txt)

**Comment by Tensuko** [comment]
(Version: 7.0.0.3) FS22_Courseplay ...
https://github.com/Courseplay/Courseplay_FS22/wiki
-> "1. Always update to the latest build and check if the problem really still exists before reporting issues."
-> https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by jwenting** [comment]
7.0.0.10 WAS the latest when I filed this.
