### ISSUE TITLE
[BUG_SP] Silage compacting mode does not work with K9 Dozer Blade

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#3043]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use the K9 Dozer Blade (on modhub since about a week) with the corresponding Steiger tractor for silage compacting. As soon as I press the start CP button, the tractor does not do anything and the game does not react properly anymore (not fully frozen)

**Actual behavior**
As described, cp does not start the silage compacting

**Expected behavior**
Silage compacting works the same way as with other blades

**Screenshots**

**Courseplay version**
Version used: 7.4.0.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13799299/log.txt)

**Map**
County Line

**Vehicles/ implements involved**
[Which vehicle or implement?
[(https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=282265&title=fs2022)]
[(https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=255981&title=fs2022)]

**Relevant script mods**
AD, CP

**Comment by Tensuko** [comment]
Prevent Error, but mod Issue is till there, won't fix as it is an Issue of the mod, not CP.
