### ISSUE TITLE
Problema generazione percorso

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3044]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
ampliato un campo con aratro, generato un percorso, accorgimento durante il lavoro che non era coerente con il campo

**Actual behavior**
Dopo aver ampliato il campo con un aratro ho generato un percorso per raccogliere i sassi e mi sono accorto che la parte ampliata non era inclusa

**Expected behavior**
Anche dopo l'ampliamento il percorso generato comprendesse il nuovo pezzo

**Screenshots**
![Farming Simulator 22 01_01_2024 15_21_20](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/415bcca1-4090-4259-bca7-92b2d1038e8d)
![Farming Simulator 22 01_01_2024 15_20_56](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/fa7f7323-5a79-409d-b692-d7bdb7005e42)

**Courseplay version**
Version used: 7.4.0.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Backs County, PA

**Vehicles/ implements involved** John Deere 6250R + lizard stone picker trailer - fast2
Which vehicle or implement? lizard stone picker trailer - fast2
Mod yes/no ? Yes

**Relevant script mods**
No

**Comment by Tensuko** [comment]
Pls write in english and fill in the complete template.

**Comment by Trivelleitor** [comment]
What's wrong?

**Comment by Tensuko** [comment]
That I don't understand your question/problem.

**Comment by Trivelleitor** [comment]
OK, so I expanded a field with the plough on the map I quoted you, then having to remove the stones I generated a path with the cp and the part of the field I had expanded did not take it into account as you can see from the pictures. To write to you in English I use a translator as I am Italian so I hope I can make myself understood.

**Comment by Tensuko** [comment]
Ok, now I understand it :)
Can you make a screenshot of how it looks like when you mark the field?
When you select the field with the icon, a white border should appear arround the field.

**Comment by Trivelleitor** [comment]
Yes I had attached the 2 pictures above (the second one has what you asked for in theory)

**Comment by Trivelleitor** [comment]
Sorry I hadn't read the last bit so I've redone them for you, I'll also take the opportunity to point out another problem: sometimes when I select the field it also takes the one next to it.
![Farming Simulator 22 01_01_2024 20_24_13](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/5fb4262c-d83e-4609-bd6e-748224dc5ed0)
![Farming Simulator 22 01_01_2024 20_24_00](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/0d5bd503-28f3-4aed-b065-3eceff744ce6)

**Comment by Tensuko** [comment]
If it takes the one next to it, the field is too close together.

To expand your field, did you use a normal plow or any mod?

Actually, as you see the corner is detected correctly, just together with your field next to it.

You can also check out the ingame help to read about how to draw or record your own field border.

We will change something about the field border detection at a later state, but that will take a few month still.

Nothing we can fix now.

**Comment by Trivelleitor** [comment]
The plough is a mod, but I don't think it's the problem right? Also, how does the talk of drawing the field work?

**Comment by Tensuko** [comment]
Read the ingame help. It should be written in your language.
