### ISSUE TITLE
[BUG_SP] Mode SHOVEL

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#3045]
Good morning,

First of all Happy New Year 2024 and thank you for your work.

I have a problem with "shovel mode"
Photo 1 the tractor advances into the bunker to load.
Photo 2 the tractor is moving backwards and has not completely loaded the bucket (modified to 25,000 liters)
Photo 3 after unloading the little silage it had in the bucket, the tractor stops and indicates "waiting to be unloaded" even though its bucket is empty and the trailer is not full.
photo 4-5-6-7-8 it's the same. the tractor reverses with the empty bucket. and stops.
I tried with different buckets, then positioning the bucket at different heights, in different bunkers, but the problem remains the same.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13804949/log.txt)

![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/d0c2d06e-e123-4e19-aecd-b90e038b6d67)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/5e1e9460-1393-4b00-8b22-5624915bbf07)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/2835e8b9-8be4-4a38-808a-3bd750a61864)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/6b0270f7-7caf-4b56-b021-85641dd6c8a1)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/44bce618-f652-4537-84df-c13569de58f1)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/fa50dc1a-1a66-462e-b969-c277cd486158)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/033bbe95-c83d-4410-8371-f44c8e49cbff)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/b55cd2b3-7aed-41d2-b6b9-cb9c42b98c73)

**Comment by Tensuko** [comment]
Happy new year.
The game is not made to get this modified shovel full.
The heap is somewhat "hard" and at some point we have to drive reverse. This is intended and will not be changed.

**Comment by Crinouche** [comment]
OK, but I have the same problem with normal excavators, from the basic set, of 2000 or 3000 liters.
The loader is not filling the shovel.

**Comment by Tensuko** [comment]
Then you have some other problem with the silo or with a mod.
It is definitly not a cp problem.
On our testsave and on my savegame it works perfectly.

**Comment by Crinouche** [comment]
Hello Tensuko,

I don't think the problem comes from a mod.
Indeed, at the start of emptying the bunker, everything works correctly. It is when we arrive towards the end of the bunker that the tractor does not advance far enough to load the bucket. I tried with several buckets, removing all the mods, but it doesn't work.
I seem to have seen a number on this problem indicating that the bunker could not be completely emptied. Except that in my case, there are still 1.5 million liters of silage to empty manually.

Isn't it possible to make the tractor move closer to the back wall, to empty the bunker a little more?
THANKS,

**Comment by Tensuko** [comment]
Closer to the wall isn't possible.
It is a bit strange that for that bunker it is still that far away.
With Vanilla Bunkers it looks like that and thats the most we can do:
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/2c0e7736-2101-408f-9337-c09b772f981b)
