### ISSUE TITLE
Combine not driving lua error

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/Courseplay_FS22#3046]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
just start courseplay

**Actual behavior**
Combine is powering up but does not move.

**Courseplay version**
Version used:  7.4.0.1 latest developement version from github 01.01.24

Multiplayer:
local hosted server

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?   
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=272409&title=fs2022
Claas Lexion 410-460

Error:

2024-01-02 10:39 Error: Running LUA method 'update'.
mods/FS22_Courseplay/scripts/ai/tasks/CpAITaskFieldWork.lua:44: attempt to call global 'AIDriveStrategyCombineCourse' (a nil value)

**Comment by Tensuko** [comment]
Complete logfile pls.

**Comment by Friendlyx** [comment]
ok will do in the evening. have to exchange courseplay again

**Comment by leo32128fs** [comment]
> Arquivo de log completo pls.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13809907/log.txt)



I had the same problem, and I redid the test on an original map and only CP

**Comment by Tensuko** [comment]
Fixed on Main.

**Comment by Friendlyx** [comment]
thx
