### ISSUE TITLE
[BUG_SP] Auger wagon interrupts the combine harvester's path at the end of the field.

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/Courseplay_FS22#3052]
**Steps to reproduce**

![FarmingSimulator2022Game_2024_01_03_20_55_45_717](https://github.com/Courseplay/Courseplay_FS22/assets/6533809/95244ae1-d872-4f30-be9d-fd7c5f0fadb4)

This happens when the combine harvester is too full, and the overflow is too far away, arriving just before the combine harvester maneuvers at the end of the course. Strangely, when the combine harvester completes the straight path and begins to turn, the tractor, instead of remaining stationary, makes a small maneuver towards the combine harvester, resulting in a collision. Both come to a halt because the tractor is blocking the combine harvester from continuing its course.

![FarmingSimulator2022Game_2024_01_03_20_56_02_974](https://github.com/Courseplay/Courseplay_FS22/assets/6533809/f3dcf1ac-e33c-425d-a0f7-d9166c064db6)

This could easily be avoided by enabling the combine harvester to stop at the grain unloading point.

However, I believe that the developers, upon analyzing the logs, can make a small modification to the code and resolve this issue.

The machines can harvest for many hours without any problems. The only inconvenience is when this happens, and everything comes to a standstill.

**Courseplay version**
Version used: 7.4.0.1 and 7.4.0.2

**Log**
[Log](https://gist.github.com/MoslessNeo/277dcb1ddd417f363e514d377831b7c5)

**Map**
Lowe Farm

**Vehicles/ implements involved**
Original game vehicles

**Comment by Tensuko** [comment]
@pvaiko if we drive reverse here untill we are behind the combine, just like in a pocket, the combine should be in the turn already, the rest should be handeld by the proximity sensor. Or do you have a better Idea?

**Comment by pvaiko** [comment]
Not sure why the unloader does not stop. Looks like that little turn it is making is because it did not stop at the turn start and now targeting the turn end waypoint. It should absolutely stop at the turn start wp and not trying to follow the turn.

**Comment by rohne83** [comment]
When unloader stops at row end together with combine to finish unloading I always see the tractor turning its wheels a bit already. For the equipment that I use that never was an issue, but to me it looks like in the situation depicted above is about the same behaviour, just with more severe results.
