### ISSUE TITLE
[Feature] Show time remaining in gamepad friendly menu

### ISSUE THREAD

**Issue by jbiblio** [Courseplay/Courseplay_FS22#3053]
**What is the problem this feature/enhancement solves?**
The time remaining is shown in the normal CP menu, but not in the gamepad friendly menu.

This makes it difficult to check the time that is needed to complete a job.

**Describe the solution you'd like**
- Add the time display to the gamepad friendly menu as well
- Or maybe show it in the help menu, in the jobs' overview (where you manage all jobs, I'm not sure about the name), or near the speed indicator.

**Comment by Tensuko** [comment]
Sry but that is not an interactive menu and not enough space to do that.
For the next FS, I have an Idea for that problem, but we have to see if that is possible.

**Comment by jbiblio** [comment]
What a pity, but I'm looking forward to LS24, too 😉.

Thanks nonetheless!
