### ISSUE TITLE
[Question] Drescher abtanken.

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Courseplay/Courseplay_FS22#3054]
Wo finde ich die xml datei den ich die Drescher bei abtanken stehen bleiben ändern/umschreiben kann?

Mich nervt immer das ich jedes mal die Mietgerät immer wieder den Erntemaschine beim abtanken stehen bleiben umstellen, weil wir voll konzentrieren sind und ganz schnell vergessen umzustellen wenn wir ruhe neben drescher fahren und zack haut er ab weil standard auf deaktiviert ist. Wir wollen das standard auf aktiviert umschreiben.

Ich würde im xml was ändern ohne das ich ständig umstellen muss..

Ich hoffe das ihr verstanden was ich meine :)

**Comment by Tensuko** [comment]
VehicleSettingsSetup.xml

**Comment by KeineEndeDerLegende** [comment]
habs gefunden aber wie ändere ich genau oder was muss ich da was eintragen?

**Comment by Tensuko** [comment]
Wenn du nicht weist was du da tust, ist es nie eine gute Idee da etwas zu ändern.
Für "stopForUnfold" musst du ein defaultBool="true" einfügen.
