### ISSUE TITLE
[Feature] Reverse Order of Course Waypoints

### ISSUE THREAD

**Issue by mnicklisch** [Courseplay/Courseplay_FS22#3056]
In the FS19 version of courseplay we had a feature to reverse the order of waypoints of a generated course (drive the course from finish to start), as seen here: https://github.com/Courseplay/courseplay/issues/4639

I think this feature is quite useful in certain situations. Would it be possible to add this feature to the current version of Courseplay again?

Thanks.

**Comment by Tensuko** [comment]
Already on the feature list for the new generator.
Just that takes a while longer to be part of the release.
