### ISSUE TITLE
Wenden auf dem Feld nicht mehr möglich[Question]

### ISSUE THREAD

**Issue by AstraThomas** [Courseplay/Courseplay_FS22#3059]
Hallo.
Ich habe seit langem feste feldkurse zum  abarbeiten auf meiner karte. diese werden immer wieder abgefahren. 
seit dem letzten update wendet nichts mehr auf dem feld. die ladewagen fahren in bäche und wälder und bleiben entsprechend hängen.  all das obwohl wenden auf dem feld aktiv ist.
schwader fahren irgendwolang. neu erstellte kurse haben manchmal so lange wege das cp die meldung bringt "hat den kurs verlassen".

ist das bereits bekannt?

Lg

**Comment by dkfiremann** [comment]
You might see #3048. 

It should be fixed on next update.

**Comment by Tensuko** [comment]
@AstraThomas 
Nö, wenn das niemand anständig meldet, woher auch.
Davon ab spiele ich ja selber und habe nichts davon bemerkt.

**Comment by rohne83** [comment]
Ist mir in letzter Zeit aber auch aufgefallen. Ich hatte alle Bäume die an meinen Feldern Probleme gemacht haben gefälllt, und dann lief es über mehrere CP-Versionen hervorragend. Seit der 7.4.0.2 bleiben meine Arbeiter wieder desöfteren an Bäumen hängen - die zuvor nie Probleme bereitet haben. Teilweise wird beim Wenden sogar trotz gegenteiliger Einstellungen schamlos aus dem Feld raus gefahren. Also irgendwas scheint sich da an den Wendemaneuvern geändert zu haben, was nicht nur positive Effekte nach sich zieht. Müsste man sich mal die Arbeit machen, mit Fahrzeugdebug die konkreten Wendemaneuver an gleicher Kursposition mit unterschiedlichen CP-Versionen zu vergleichen. Vor Allem natürlich da wo neuerdings das Feld verlassen wird.

**Comment by Tensuko** [comment]
Bitte ein richtiges bug report issue dazu machen mit entsprechenden debug und logfile.
Sonst lässt sich da nichts machen.

Es bezieht sich eher auf den Pathfinder, statt den normalen Wendemanövern.
