### ISSUE TITLE
[BUG_SP] Drescher fährt nach Abtanken im Vorgewende (mit AD) nicht mehr auf Kurs 

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#306]
**Steps to reproduce**
Ist bisher 2x passiert, einmal mit älteren Version von Courseplay, einmal mit der Aktuellen. Keine Ahnung, was AD gemacht hat, sehe nur das Ergebnis. 

**Actual behavior**
Drescher macht auf erstem Vorgewende eine Tasche und wartet auf Abfahrer. Nach dem Abtanken durch AD fährt der Drescher "zwischen" den Wegpunkten weiter, quasi grade aus der Tasche. 
![fsScreen_2022_01_02_07_28_36](https://user-images.githubusercontent.com/96873819/147868524-08860720-314a-4950-9560-409d89709fec.jpeg)

**Expected behavior**
Drescher sollte aus der Tasche zurück auf den Kurs fahren. Fährt man manuell zurück und startet den Drescher an der Stelle (ohne Tasche) neu, fährt er auch korrekt auf dem Vorgewende weiter. 
![fsScreen_2022_01_02_07_30_31](https://user-images.githubusercontent.com/96873819/147868577-36321d83-4922-444a-ba63-f255199a2d38.jpeg)

**Courseplay version**
Version used: 7.0.0.10

**Log**
[log - Kopie.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798690/log.-.Kopie.txt)

07:17 wurde der Kurs generiert, 07:18 sind die Log Einträge

**Map**
Elmcreek

**Vehicles/ implements involved**
Axial-Flow 9250

**Relevant script mods**
AD in v2.0.0.2 aktiv als Abfahrer.

**Comment by rohne83** [comment]
Das Problem wurde doch schon gemeldet:  #133
