### ISSUE TITLE
[BUG_SP] Unloader drives off field when driving to unload harvester

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3062]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
Apologies for being  late with feedback. But sometimes boring stuff like work get in the way of our favorite hobby...
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
When driving to offload combine on the first headland on irregular shaped fields it disregards the field border. 
In version 7.4.0.1 it takes a similar path but not the same. 

**Expected behavior**
Stay in the field

**Screenshots**
Version 7.4.0.2
![Farming Simulator 22 Screenshot 2024 01 10 - 18 09 34 32](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/fa12ed9e-3322-4696-b5e1-412c403c3933)
Version 7.4.0.1
![Farming Simulator 22 Screenshot 2024 01 10 - 18 28 33 90](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/5ffee17a-18c0-4ef2-9a0f-e384272f294f)
FieldBorder
![Farming Simulator 22 Screenshot 2024 01 10 - 18 25 42 06](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/ace276f8-17a0-4f95-b6c2-622af188b385)

**Courseplay version**
Version used: 
Latest version 7.4.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13890899/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Martin-L45** [comment]
Not to spam the issue... But here is a setup on elmcreek with no mods installed. The unloader drives off field. it will reach the combine and offload but i should still stay inside the border.
![Farming Simulator 22 Screenshot 2024 01 10 - 19 11 04 59](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/35cabeb1-570e-47dc-bd2c-9701c11d285f)
![Farming Simulator 22 Screenshot 2024 01 10 - 19 10 40 04](https://github.com/Courseplay/Courseplay_FS22/assets/85753728/9899efc2-2f9b-42e4-ba4e-7d14eab3394e)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13891412/log.txt)

**Comment by Martin-L45** [comment]
maybe i am mistaken. But i added the changed file from #3048 and that solved the problem when driving to first waypoint. But the issue is still there when unloading combine. i think this is more like #3059

**Comment by Tensuko** [comment]
Got nothing to do with turn on field.
Will try to replicate your situation on elmcreek, even that was my testing for the update we have on the line.

**Comment by Martin-L45** [comment]
Would it be useful if i upload a zipped savegame? I saved my test from last night.

**Comment by Tensuko** [comment]
Sure.

**Comment by Martin-L45** [comment]
https://www.mediafire.com/file/n4pje478m41nz1s/savegame3.zip/file
