### ISSUE TITLE
[BUG_SP] Plough rotation not saved when saving and exiting a game

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3067]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Save game and exit  whilst ploughing

**Actual behavior**
When you reload the game the plough wants to turn over before carrying on the course

**Expected behavior**
The plough maintains (saves it's rotation side) its previous rotation and carries on as it was before saving and exiting the game.

**Screenshots**

![fsScreen_2024_01_15_12_50_40](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/03bd0856-8c79-42d4-a7c8-0b05650c19b6)

**Courseplay version**
Version used: 7.4.0.2

**Log**
No

**Map**
Any map

**Vehicles/ implements involved**
Giants MF8.305S
Giants Lemken Titan 18

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pvaiko** [comment]
I don't know how to reproduce this. Need the exact steps and the log.

**Comment by coatsy35** [comment]
I’m at work atm. However it doesn’t always do it. If you in the middle of a run when you save and exit. Quite often when you resume, if wants to turn the plough over the other direction to condition. Also did you see my tag on the turning circle post about the angled runs and turning so tight there are very large gaps with the big KV plough

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen with the requiered informations.
