### ISSUE TITLE
[BUG_SP] The course generator rounds the corners of the headlands even though they are set to sharp.

### ISSUE THREAD

**Issue by Freghette** [Courseplay/Courseplay_FS22#3070]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki check

**Steps to reproduce**
Create a custom rectangular polygonal concave field. Generate a course for this field with the following parameters:

- number of headlands = 1 or more;
- headlands corner = sharp.

Example: FS22_Courseplay\CustomFields\Map_Name\ [F55.rename.txt](https://github.com/Courseplay/Courseplay_FS22/files/13956829/F55.rename.txt) 
![Fig.1 A rectangular polygonal concave field on the map with a one headland course](https://github.com/Courseplay/Courseplay_FS22/assets/94172336/41de6f76-079e-4665-9a14-7dd0aeaa9cd4)

**Actual behavior**
One of the headland corners of the generated course is rounded.

**Expected behavior**
All headland angles of the generated course are right (pi/2).

**Screenshots**
![Screenshots_CP](https://github.com/Courseplay/Courseplay_FS22/assets/94172336/5d51dbcb-667f-4038-acf8-e8cb25d0055c)

**Courseplay version**
Version used: 7.4.0.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13957222/log.txt)

**Map**
Zielonka (let it be, but the issue can be reproduced on any map).

**Vehicles/ implements involved**
- Axial-Flow 9250;
- Case IH 3162 TerraFlex Draper 45FT;
- [it seems it could be any vehicle, irrelevant];

Mod: no.

**Relevant script mods**
None.

**Comment by Tensuko** [comment]
Forced sharp is a feature of the new generator but it is not finished yet. Got to wait for it.
Other then that the course looks good and I wonder if the course will cover 100%

**Comment by Freghette** [comment]
No, it does not cover all pixels. In my experience, smooth corners mean uncovered points. So I just get rid of the smooth ones and set the turn maneuver waypoints.
This can be seen in the screenshots above. But here’s a clip that illustrates it more clearly: the harvester will never process the points (circled in yellow in the screenshot), because it follows the course not by the center of the header, but by the center of the entire harvester.

https://github.com/Courseplay/Courseplay_FS22/assets/94172336/ac625e4a-2472-45d6-b488-a11a699d64e4

![3070.Fig2](https://github.com/Courseplay/Courseplay_FS22/assets/94172336/4fb97173-b299-4a21-8b77-7a124fed0d47)

How the vehicle follows its course is another topic, am I right? Should I create a new issue?

**Comment by Tensuko** [comment]
No, as this is how the vehicle drives!
