### ISSUE TITLE
[Feature] Wait for all combines to finish before unloading the unloader.

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#3072]
**What is the problem this feature/enhancement solves?**
If there are multiple combines on a field and the first one finishes, the unloader will empty that combine and then go and unload itself, regardless of whether or not it actually needs to (based on the "empty when over" setting). This can lead to an unnecessary delay when subsequent combines finish the course. 

**Describe the solution you'd like**
If there are still active combines after the one currently being unloaded and if the fill level of the unloader is below the "empty when over" setting, make the unloader wait (like normal behaviour when unloading) rather than going to unload itself.

**Describe alternatives you've considered**
Stopping the unloader as it's unloading the first combine and then starting it again right after works...

**Comment by Tensuko** [comment]
@pvaiko maybe a check is enough if there are more combine on the field of the unloader that are still working?
Just before go to unload, unless the unloader is full.

**Comment by pvaiko** [comment]
Yeah, that should work.
