### ISSUE TITLE
CP conflict with Follow Me

### ISSUE THREAD

**Issue by myself-nate** [Courseplay/Courseplay_FS22#3073]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Add both CP and Follow Me to a savegame.

**Actual behavior**
In CP, you can't access the Create Job in AI menu to create the route.

**Courseplay version**
Version used: 7.4.0.2

**Comment by Tensuko** [comment]
Not enough information.
Why removed most of our template?
No log no help.
If FollowMe thinkers arround with the AI Job, they should fix it.
