### ISSUE TITLE
[Question] Convoy mode? 

### ISSUE THREAD

**Issue by dozerjz** [Courseplay/Courseplay_FS22#3076]
How do i activate the convoy mode?  I am using 2 combines, (modded X9's), and convoy used to work and combine 2 would slow down/ stop if it got too close.  For some reason with 7.4.0.2 it is not working.  Am I missing something?  I am hoping this is my error.

**Comment by Tensuko** [comment]
Pls read the ingame help menu or check courseplay.dev for Help about this section.
For bug report, use bug template and fill all in.
I have not heard that this isn't working and we did not touch it.
