### ISSUE TITLE
[Feature] Custom work width (more precise)

### ISSUE THREAD

**Issue by antler22** [Courseplay/Courseplay_FS22#3077]
**What is the problem this feature/enhancement solves?**
With RCR growing in popularity, so is the need for exact working widths that match different planter setups.  I have a tillage tool that creates rows similar to RCR, so it is important to have the tillage lines be in exactly 30ft widths with this implement.  After, I would use a 60ft planter to plant the field and it would line up perfectly on the strips.  Today if I enter 30 ft into the working width it corrects to 30.2ft or 29.8ft, I assume because of rounding from 9.1 to 9.2 meters.

**Describe the solution you'd like**
I believe the work width is in meters, and just converted to a foot value for US users.  So, allowing the input range to go to three decimal places allowed "0.000" so that one could input 30ft or "9.144" meters.  

**Describe alternatives you've considered**
Tried using a 60ft course with a 30ft offset, and for the implement I want to use the offset defaults to "Auto" and cannot be changed.  

**Additional context**
VCA does this nicely, I requested this some time ago on their page and the turnaround was fairly quick.

**Comment by Tensuko** [comment]
30 or 30.2 doesn't sound like a big difference, especially if you consider the size ingame.
9.1 or 9.2 to speak in meter is barely noticable.
Also we have overlaps anyway.
Won't fix that.
