### ISSUE TITLE
[BUG_SP] Pathfinding issue: Helper takes a long turn

### ISSUE THREAD

**Issue by AyakawaSakura** [Courseplay/Courseplay_FS22#308]
**Steps to reproduce**
On field 58+59+60+61+62+63, helper takes a long turn to reach a point which is near him.

**Actual behavior**
helper goes a long turn.

**Expected behavior**
helper finds a shorter way to the designated point.
**Screenshots**
![20220102155031_1](https://user-images.githubusercontent.com/30264706/147869594-b7922757-a539-4698-90e2-46ef656420ea.jpg)

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798757/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Valtra 8750 (medium tractor)
TS 1520/M3 (Weeder)

**Relevant script mods**
Enhanced vehicle(loaded, no function activated)

**Comment by pvaiko** [comment]
@AyakawaSakura I'll need a savegame and this course to reproduce it.

**Comment by AyakawaSakura** [comment]
> @AyakawaSakura I'll need a savegame and this course to reproduce it.

Sorry the save is gone and I cannot reproduce the issue. Please close the issue. If this problem happens again I will reopen it.
