### ISSUE TITLE
[BUG_SP] Bale Collector does not collect large round bales

### ISSUE THREAD

**Issue by mpupedis** [Courseplay/Courseplay_FS22#3080]
**Steps to reproduce**
Create 180cm Round Bales of any type on a field.
Use the Anderson RMB2000 bale collector/trailer with any tractor.
Use bale wrap/collect function (no course)

**Actual behavior**
The tractor starts and the bale collection arm is lowered.  A message appears on the screen stating "No Path Found", and Courseplay stops.

**Expected behavior**
Courseplay collects the bales from the field.  The function works correctly for smaller round bales (tested 150cm).

**Courseplay version**
Version used: 7.4.0.2

**Log**
[180cm Round Straw log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14033069/180cm.Round.Straw.log.txt)

**Map**
Elmcreek, Field 34.

**Vehicles/ implements involved**
Fendt Favorit 515
Anderson RMB2000

**Relevant script mods**
Courseplay 7.4.0.2
Easy Dev Controls 1.3.0.2

**Comment by Tensuko** [comment]
Try to increase the offset, if you have a to wide tractor, the colision will hit the bale and the pathfinder cancels.

**Comment by Tensuko** [comment]
Could be, but as long as this simple adjust help its not a bug.
