### ISSUE TITLE
[Question] Ballenschieber senken?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3081]
Hallo Leute
ich habe vor der Traktor (MF 8s) mit der Ballenpresse (MF 2370 ULTRA HD) einen Ballenschieber montiert:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=250367&title=fs2022
wenn ich damit mit AD zum Feld fahre, danach an CP übergebem klappt CP die Presse aus senkt sie ab schaltet sie ein.
der Ballenschieber jedoch bleibt oben und ist dann dementsprechend zu hoch.
senke ich ihn ab, ist alles gut, jedoch auf der fahrt zum nächsten Feld bleibt er gerne mal an Geländekanten hängen.
ich habe die balePusher.xml auch schon modifiziert:
needs lowering eingetragen:
`	<ai>
        <agentAttachment width="1.3" height="2" length="2.5" lengthOffset="1"/>
        <needsLowering value="true"/>
    </ai>
`
attachable geändert und attacher joint controlauskommentiert:

```
	<attachable>
        <inputAttacherJointConfigurations>
            <inputAttacherJointConfiguration name="$l10n_configuration_inputAttacher3Point" price="0">
                <!-- <inputAttacherJoint node="0>0" topReferenceNode="0>1" jointType="implement" isControllable="true" lowerRotLimitScale="0 0 0" upperRotLimitScale="0 0 0" lowerTransLimitScale="0 0 0" upperTransLimitScale="0 0 0" upperRotationOffset="3" > -->
                <inputAttacherJoint node="0>0" topReferenceNode="0>1" jointType="implement" isControllable="false" lowerRotLimitScale="0 0 0" upperRotLimitScale="0 0 0" lowerTransLimitScale="0 0 0" upperTransLimitScale="0 0 0" upperRotationOffset="3" >
                    <distanceToGround lower="0.5" upper="0.7" />
                </inputAttacherJoint>
            </inputAttacherJointConfiguration>
        </inputAttacherJointConfigurations>
    </attachable>

    <!-- <attacherJointControl maxTiltAngle="25"> -->
        <!-- <control controlFunction="controlAttacherJointHeight" controlAxis="AXIS_HYDRAULICATTACHER1" invertControlAxis="true" mouseSpeedFactor="0.3" iconName="IMPLEMENT_ATTACHER_TRANS" /> -->
        <!-- <control controlFunction="controlAttacherJointTilt"   controlAxis="AXIS_HYDRAULICATTACHER2" invertControlAxis="true" mouseSpeedFactor="0.3" iconName="IMPLEMENT_ATTACHER_ROTX" /> -->
    <!-- </attacherJointControl> -->


```

aber auch das brachte nicht den gewünschten effekt.
als workaround hab ich die 
`                    <distanceToGround lower="0.5" upper="0.7" />
` 
auf 0,7m upper gestellt, damit der Ballenschieber die Quaderballen grade noch so erwischt, wenn er gehoben ist.
gibt es eine möglichkeit das ich das ändern kann, das cp den schieber senkt, wie z.b. ein Frontmähwerk, oder denkt cp das wäre ein Gewicht und lässt es grundsätzlich oben?
lg
andreas

**Comment by regs1980** [comment]
@andreasthu Den Amazone T-Pack U in die VehicleConfigurations.xml mit ignoreBaleCollisionForward="true" eintragen und schon hast du einen perfekten Ballenschieber. 
Das Gerät anhängen, mit V absenken und dann die Ballenpressen hinter dem Traktor anhängen.

**Comment by andreasthu** [comment]
@Tensuko 
Und welche zwei ballenschieber sind das?
Habe gerade die changelog durchgelesen aber nicht gefunden.

@regs1980 
Hab ja eh schon einen der halbwegs funktioniert, bzw dann zwei andere die offiziell unterstützt werden.
Außerdem würde ich mit dem T-Pack U ja den Schwad vor der Presse zusammendrücken.

Lg
Andreas

**Comment by andreasthu** [comment]
hallo Leute
bin wieder am pc und hab die 
config/VehicleConfigurations.xml  gecheckt
da gibts ab zeile 567 folgenden eintrag:

```
    <!--Mod: BalePusher-->
    <Vehicle name="balePusher.xml"
            ignoreBaleCollisionForward = "true"
    />

    <!--Mod: LizardBalePusher-->
    <Vehicle name="EYM_balePusher.xml"
            ignoreBaleCollisionForward = "true"
    />

```
sind das diese zwei Ballenschieber?
der, den ich habe ist aus dem modhub und die zip heißt   
FS22_LizardBalePusher.zip
die xml 
balePusher.xml
ist das jetzt einer von den beiden?
aber eigentlich hab ich ja kein problem mit der collisionserkennung, 
sondern das das sich die Fronthydraulik beim Pressen nicht absenkt und der Schieber oben bleibt

lg
andreas

**Comment by Tensuko** [comment]
Dann ist das eventuell einer (nennt jeder ja einfach balePusher.xml), aber da der eventuell wie ein gewicht ist, werden wir den definitiv nicht zum absenken bringen (eine weitere config macht hier auch keinen sinn) denn Gewichte will man nicht absenken.

Wie schon geschrieben, senke den selber ab, eine andere Lösung wird es von uns nicht geben, es gibt schließlich keine spec "balepusher".

Diese sind das:
https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.2.0.4

**Comment by andreasthu** [comment]
Ja genau
`Added [Bale Pusher](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=250367&title=fs2022) and [Bale Pusher](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=248461&title=fs2022) to the config as first bale pusher.`
Davon hab ich den ersten, wie im obersten beitrag verlinkt, und den hab ich so modifiziert das er keine mousecontrol hat, sondern mit x heben und senken geht.
Und upper niedriger gesetzt.
Aber ja, er funktioniert 
Lg.andreas
