### ISSUE TITLE
[Question] Field Position Resetting

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3084]
Would it be possible in a future version to automatically reset the field position once one has been set? I give an example below.

When you first couple a tractor to a trailer and send it to a field, on load and deliver with AD and CP as the unloader, it goes to the field and works without setting a field position. Then when the field is finished and you have moved the combine to the next field, if you just change the field the tractor is going to on AD, it will drive there but the tractor errors out stating that it is not close to the field.

Would it be possible for the field position to be reset in this scenario, rather than having to manually set the next field position each time on the courseplay menu?

**Comment by Tensuko** [comment]
There is no way to tell the field is finished for this.
So no, that won't happen.
I think about some other solution, but not any time soon.
