### ISSUE TITLE
Warte auf Abfahrer bei Silo Laden / Waiting for driver  [BUG_SP]

### ISSUE THREAD

**Issue by EsstischII** [Courseplay/Courseplay_FS22#3085]
Hi there, 

really love the load silo feature! Unfortunately, I have an issue with loading automatically... I hope you can help?

Problem: Wheel loader should load silage from wedge silo into trailer. When the trailer is full, it is driven away with Autodrive and a second trailer moves up.

**Actual behavior**
After starting the CP order, the first trailer is loaded as planned. Then the message “Waiting for driver” appears and the wheel loader stops moving, even though another trailer is standing in exactly the same place.

I have tried different forks and shovels, always the same problem. Sometimes it works that 2 or 3 trailers are loaded, but eventually there is always a point where the error message appears.

**Expected behavior**
Das solange Anhänger beladen werden, bis keine Silage mehr vorhanden ist.

**Screenshots**

**Courseplay version**
Version used: 7.4, latest

**Log**
https://gist.github.com/EsstischII/014ed2f6433a9e681c53dee13d60d414

**Map**
NF Marsch Singleplayer

**Vehicles/ implements involved**
No mod vehicles, all standard
![Screenshot 2024-01-27 234516](https://github.com/Courseplay/Courseplay_FS22/assets/150723539/a6a516b2-14af-4b97-86e3-0072244e03a4)

**Relevant script mods**
Autodrive & CP

**Comment by Tensuko** [comment]
Can you show a screenshot of how you marked the area?

**Comment by EsstischII** [comment]
![Screenshot 2024-01-28 113842](https://github.com/Courseplay/Courseplay_FS22/assets/150723539/016fbc75-a466-4253-9380-195b78a33956)
![Screenshot 2024-01-28 114013](https://github.com/Courseplay/Courseplay_FS22/assets/150723539/b666838c-1142-43b7-a3f5-443b8c396041)

Here are 2 screenshots.
The one showing how I made the Autodrive routes including the targetpoint, and the other one showing the "create a job" interface for "Silo Laden".
I tried various spots to place the blue rectangle where the loader should find the trailer but the result is always the same: It finds the trailer for the first time and sometimes for 2nd and 3rd but then at some point it doenst find any trailer anymore and just waits.

**Comment by EsstischII** [comment]
Oh and I realized, there is a second issue: The loader usually tries to load from one narrow line (not sure whats the right word) of the silo. That leads to facing a very steep wall of what has to be loaded. That again leads to the issue, that the loader gets nothing or just a very small amount of stuff in his shovel as it seems, that with the CP job the shovel is not pushed into the pile but bounces back from it, if the surface of the pile is to steep.

In the screenshot it is marked with the blue arrow. The loader is only pushing in there instead of vary the direction...
![Screenshot 2024-01-28 120639](https://github.com/Courseplay/Courseplay_FS22/assets/150723539/75a28922-b9a1-4f37-8428-6e79bb190236)

**Comment by Tensuko** [comment]
The 2nd Issue is a Giants Problem.
Can't do much then try to set the shovel to a lower position.

**Comment by EsstischII** [comment]
oh okay. I cannot lower the shovel as it bounces from the silos very first edge and prevents the loader from getting in the silo... 
Couldnt figure how to build it differently. "Landschaftsbau" / "Bodenanpassung" etc didnt work....
But never mind :)

How about the first issue? Sorry for confusing the thread... Do you need any futher info? It is still labeled with waiting for user?

**Comment by Tensuko** [comment]
Need to try this out.
So far I only loaded into BGA directly and not let wheel loader load up many trailers in row.

**Comment by EsstischII** [comment]
Thanks for looking into it.
Do you want my safe game?
Let me know if I can assist you.

**Comment by schwyl** [comment]
One thing I've found is unless you using a silage shovel on the front wheel loader, weird stuff happens when unloading silage from the silo.

**Comment by Tensuko** [comment]
"weird stuff happens when unloading silage from the silo."
that doen't help at all.....

**Comment by rohne83** [comment]
Interestingly, for me unloading silage into trailer chains works without problems with latest CP versions. Using silage fork (the vanilla one with 8000liters) on these occasions. Once the first trailer is filled up, AD drives him to its target point, CP shovel driver waits, other AD drivers move up, and after some seconds of waiting CP shovel driver continues its work. So basically its working as it should be. Must be anything user specific why it won't work.
I only have to reengage the driver sometimes when dumping into the truck as its trailer has a collision on top which sometimes causes a bit of trouble for my shovel driver.
![fsScreen_2024_01_09_16_25_01](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/0d9cd104-216e-4e71-8994-956a0d4bb291)

**Comment by regs1980** [comment]
@EsstischII Ich schreibe das jetzt mal in Deutsch.
Der AD Fahrer muss weiter weg vom Silo, dass der CP Lader mehr Platz hat zum Arbeiten.
Zu deinem Silo Problem, das ist nicht das Original von Giants, sondern ein geändertes von Fed. 
Das erkennt man gut daran, dass die Silage über die obere Kante hinaus geht und das Original nur 3 Millionen Liter Fassungsvermögen hat, deines ist halb leer und noch 2,6 Millionen Liter drin. 
Wie @rohne83 schon erwähnt hat, lieber die Silagegabel benutzen, das geht besser.

**Comment by EsstischII** [comment]
Thx for the ideas & suggestions.
So I tried another setup:
![Screenshot 2024-02-01 214046](https://github.com/Courseplay/Courseplay_FS22/assets/150723539/941cff31-82f5-40a7-9ce8-a85b44da686d)

1. Waiting for driver still happens sometimes, but way less then before. The distance for the loader to turn around seemed the problem. After increasing the distance it got better. 
2. The silo: I hope its not me :D but I choosed a different one know. I guess it is not modified? Or are all silos modified by FED? The wall in the middle of the 2 silos seems to be a problem as the loader always gets stuck there without any given reason... The other wall isnt an issue at all. So seems its not a good idea to build them next to each other...
3.  The loader: As you can see in the image... A shovel is filled and unloaded into the trailer. The loader then lowers the shovel and instead of driving backwards it drives forward right into the trailer and pushes the trailer 1 or 2m... after a few seconds the loader stops and then finally drives backwards and turns around... I tried again with increased distance to the silo but it happend sometimes with any given distance... 
Probably you know about this? :) 

In general it feels, the autoload job is not efficient at all for big silos if the loader has to drive so far and turn around etc...

**Comment by rohne83** [comment]
3. yes with the fork the shovel driver often has a strange path calculation for the way back to the silo, as it most often adds a short forward section which leads to this collision with the trailer. But so far it's mostly short enough that the process itself doesn't get interrupted because of this and work can continue - so it's not a gamebraking bug.

**Comment by Tensuko** [comment]
AI is not to make things asap, but to do a task for you so you dont have to do that.

**Comment by Tensuko** [comment]
Ich würde das ganze Thema jetzt nicht mal mehr als Bug betrachten.
Es scheint ja generell zu funktionieren und es waren nur ein paar Anpassungen nötig.
Ich schließe das Thema daher ab.
Sollte noch mal was sein, bitte neues Issue aufmachen.

Generell gilt aber: KI = nicht schneller oder sonstiges, es ist eine Unterstützung, eben ein Helfer!
