### ISSUE TITLE
Amazon Citan 15001 Mod funktioniert nicht mehr

### ISSUE THREAD

**Issue by Swinegel** [Courseplay/Courseplay_FS22#3086]
Hallo Team,

wir nutzen den Mod der Amzon Citan 15001 C Direktsaat Maschine. 
(https://farmingsimulator22mods.com/amazone-citan-15001-c-direct-seeder-roller-v1-0-fs22)
oder
(https://farmingsimulator22mods.de/amazone-citan-15001c-mario-hirschfeld-edition-v1-0-0-1)

Diese bietet die Möglichkeit nur Saatgut zu verwenden ohne Dünger.

Unter CP 1.21.9 funktioniert die Maschine einwandfrei. 
Mit CP 1.3.1.5und höher wird bei Aktivierung die Amazone ausgeklappt und abgesenkt, dann erscheint der Fehler: "Gerät muss aufgefüllt werden". Danach wird die Amazone zusammengeklappt und CP deaktiviert sich.
Die Amazone ist nur auf Saatgut konfiguriert und gefüllt.

Wäre super wenn ich mal nachschauen würdet warum es nicht mehr geht und das Problem beheben würdet.

Vielen Dank im Voraus und für ihre echt spizenmäßige Leistung. 1a mit Sternchen :-)

**Comment by Tensuko** [comment]
Von dieser Seite werden wir keine Mods unterstützen.
Diese Seiten klauen die Mods andere und veröffentlichen sie da um klicks zu bekommen und mit der Werbung geld zu verdienen wovon die modder nichts sehen.
-> no support!
