### ISSUE TITLE
[Feature] Pro Seed Mod Integration

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3088]
**What is the problem this feature/enhancement solves?**
Integration with pro seed, similar to how the new VCA update does it in auto mode, see video below.

**Describe the solution you'd like**
Have integration/work with ProSeed in auto mode. Would be especially good if multiple tools could follow the pattern in convoy mode and share when they need to tramline or not. Would need a hook to let PS know that CP has moved to the next path on headlands as there is no lifting up and down to trigger it. Would need to stop ProSeed from changing tracks when lifted up if on the same headland path i.e. still on outer path if using square corners (as currently it changes to the next ProSeed pass each time it is lifted at a corner. 

**Describe alternatives you've considered**
Use pro seed in semi auto mode, but it requires a lot of management especially if you have lots of tractors seeding in different fields across the map

**Additional context**
There is a really nice video showing this working in the latest VCA update, would be really good to have this type of linking with CP so that fields can have correct tramline patterns automated like much of Europe uses. This would work really well with what you have coming for the new course generator and how nice the field corners look on it. 

https://www.youtube.com/watch?v=xl5K7JP0I5U

**Comment by Tensuko** [comment]
Wont do that as mentioned many times.

**Comment by Tensuko** [comment]
Nothing more ten what we have done here #2362
