### ISSUE TITLE
[Question] How I do create my route.

### ISSUE THREAD

**Issue by pallexx818** [Courseplay/Courseplay_FS22#309]
I want to create my own field, and for this I have to create an annular route, how can I do this?

**Comment by rohne83** [comment]
You cannot create custom courses right now. CP automatically detects field borders and creates the courses within those. Not sure, but I think it should be enough if you manually plow the borders, and have CP create the fieldcourse for plowing the rest within those borders.

**Comment by RealNeo80** [comment]
should work, i created on elmcreek one field out of 48/49 and cp is recocknizing it very fine for the courses
