### ISSUE TITLE
drescher abtanken und abfahrt mit dem giants abfahrer

### ISSUE THREAD

**Issue by Waldschrad1** [Courseplay/Courseplay_FS22#3090]

**Comment by Waldschrad1** [comment]
wenn ich den Drescher abfahren will und den ki abfahrer aktiviere und den ziehl ort eingebe z.B Agrahandel bekomme ich immer zei fehlermeldungen
![fsScreen_2024_01_28_14_49_17](https://github.com/Courseplay/Courseplay_FS22/assets/118614777/9dd2fbfd-be6f-4e92-a544-dfa99ca96aa6) 
![fsScreen_2024_01_28_17_02_16](https://github.com/Courseplay/Courseplay_FS22/assets/118614777/ecd66255-ca9e-4d70-8450-e4d799e98060)
au
![fsScreen_2024_02_04_14_26_08](https://github.com/Courseplay/Courseplay_FS22/assets/118614777/64087624-725a-4d87-9652-96adf180d8b6)
ch 
![fsScreen_2024_02_04_14_37_17](https://github.com/Courseplay/Courseplay_FS22/assets/118614777/c1d8e81d-9147-4a18-b8c9-19fa38e18714)
wenn ich den kurs zeichne ist das so oder selbst einfahre ist das.
der schleper macht garnix oder tank nur ab fährt dan zum startpunkt aber nicht weiter

dann habe ich noch eine log eintrag
Error: Invalid mod name 'Courseplay_FS22-main'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

**Comment by Waldschrad1** [comment]
achso der lkw im ersten bild wenn der beim drescher abtankt und dannanscliessen zum ziel silo fahren soll setzt er den container ab und fährt auch nur bis zu einem gewissen punkt und nicht weiter

**Comment by Tensuko** [comment]
Ich weis gar nicht wo ich da anfangen soll.....

Also erst mal so lädt man CP nicht runter.
Dort findest du die .zip die du runter laden musst und in deinen Mods Ordner packst, kein zippen kein gar nichts, einfach copy and paste rein packen.
https://github.com/Courseplay/Courseplay_FS22/releases

Dieses wilde gebilde wo CP-1 steht: Es gibt kein Kurs aufzeichnen mehr, das ist ein Feldrandkurs den du da aufgezeichnet hast.
Siehe dazu die Ingame Anleitung oder courseplay.dev Webseite.

Drescher abtanken geht nur wenn CP den Drescher fährt und dann den Abfahrer mit CP oder AD entsprechend einstellen.
Wenn der Giants Helfer zum Abladepunkt fahren soll und das nicht kann, liegt das nicht an uns. Da kannst du dich bei Giants bedanken für den schlechten Helfer.
Ansonsten dafür auch CP und AD Kombination, siehe Anleitung und Tutorials auf YouTube.

Und das nächste mal bitte unsere Vorlage ausfüllen!
