### ISSUE TITLE
[BUG_SP] CP helper still buys fertiliser when turning on headland and blocked by object, when AI worker set to buy fertiliser

### ISSUE THREAD

**Issue by Symbob** [Courseplay/Courseplay_FS22#3092]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
In settings have AI helper set to Buy fertiliser and use CP helper to spread fertiliser

**Actual behavior**
If the AI helper is set to Buy fertiliser the CP helper will continue to use fertiliser when turning on headlands and when blocked by an object.  When blocked by an object the animation stops but the fertiliser spreader sound can still be heard and the money will continuously go down and the CP helper continues to buy fertiliser.  When turning on headland, both the animation and the sound will stop but the helper still continues to buy fertiliser while he completes the turn manoeuvre.  If the AI helper is set to the "Off" option for fertiliser (so is not buying fertiliser) things work correctly and fertiliser is not being used when turning or blocked by an object.  I've not yet tested this for seeds and other items that the AI helper can be set to BUY.

**Expected behavior**
The AI helper should not continue to buy fertiliser when turning on headlands and when blocked by an object.

**Screenshots**
The best way to see this would be with a video but unfortunately I'm not able to make that but here are  some screenshots of the CP helper.  One is taken as it starts the turn manoeuvre and the second is taken as it finishes the turn manoeuvre.

![fsScreen_2024_02_04_21_23_38](https://github.com/Courseplay/Courseplay_FS22/assets/18528850/8f459f84-9f40-48df-b07f-f34931a7d814)

![fsScreen_2024_02_04_21_24_21](https://github.com/Courseplay/Courseplay_FS22/assets/18528850/f0d75a66-84fa-40c5-9d8c-9b82b620caaf)

If you look at my money in the top right corner you can see that the CP helper has used £466 of fertiliser while just completing his turn manoeuvre .  In one instance I left my PC for a while and when I came back all my money had gone because the CP helper had become blocked by an object and continued to buy fertiliser all the time it was blocked.

**Courseplay version**
Version used: 7.4.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14158632/log.txt)

**Map**
Map played on.

Giants Haut-Beyleron

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

In-game Deutz 8280 TTV tractor with Amazone ZA-TS 3200 fertiliser spreader but I've tried this with other spreaders and the result is the same.

**Relevant script mods**
Mods like Autodrive or VCA and so on.
All mods removed except for CP

**Comment by regs1980** [comment]
This is a not yet fixed Giants bug not a CP bug.

**Comment by Tensuko** [comment]
Exactly. Giants bug and also confirmed by Giants.

**Comment by Symbob** [comment]
OK thanks for letting me know.  I also tested this using Giants AI helper before submitting the issue, and their helper works OK.  The Giants helper does not continue to buy fertiliser when turning on the headland, so this only happens with a CP helper.  If this is a Giants bug then it will never be fixed as it doesn't happen with a Giants helper.

Thank you for your help

**Comment by Tensuko** [comment]
It does happen with giants helper, just not in their turn, only when drive from A to B and that is what we do here.
So yes it is a Giants bug only and it ia confirmed by Giants.

**Comment by Symbob** [comment]
I see, now I understand.  Thanks for the explanation.
