### ISSUE TITLE
[BUG_SP] Impossible to use cultivator with sowing feature as it can't be disabled

### ISSUE THREAD

**Issue by ByFe** [Courseplay/Courseplay_FS22#3094]
**Steps to reproduce**
Get the cultivator  "Finer 6 SL" from the "HORSCH Agrovation" pack and try to cultivate a field.

**Actual behavior**
The cultivator "Finer 6 SL" from the "HORSCH Agrovation" pack can't be used with courseplay as the sowing functionality can't be disabled and courseplay helper complains about requiring to refill the machine.

**Expected behavior**
The sowing functionality should be optionally disabled via configuration as it is possible when using sowing machines without fertilizer.

**Courseplay version**
Version used: 7.4.0.2

**Vehicles/ implements involved**
Finer 6 SL (HORSCH Agrovation)

**Comment by Tensuko** [comment]
> The cultivator "Finer 6 SL" from the "HORSCH Agrovation" pack can't be used with courseplay as the sowing functionality can't be > disabled and courseplay helper complains about requiring to refill the machine.

Did you check the vehicle settings menu?!

**Comment by ByFe** [comment]
Sure, that the first thing I checked. There is no option in vehicle settings menu (as it is when using a sowing machine with fertilizer function)
As I am writing this... maybe it's a special problem with this attachment as it has an additional tank to be mounted at the front to be used for sowing. As I was testing this I did not have it attached as I just wanted to cultivate a field. Could that be the problem why it is missing the option in the menu?

**Comment by ByFe** [comment]
If I use the PNEUMATICSTAR 900 from Einböck the option is shown in the vehicle configuration and seeding can be disabled.
I think the problem arises from the fact, that the HORSCH cultivator seeding functionality has to be bought optionally via the shop?

**Comment by Tensuko** [comment]
I think we found out that this tool have a bug so that we cant make that work.
I know that we checked the tools and all worked fine except some and then found the problem.
So not a CP Problem sadly again a game bug.

**Comment by ByFe** [comment]
That's sad, but anyway thanks a lot for your time and effort and for all the work on the mod in general - still love it and you can't blame the mod for the bugs introduced by the giants developers themselves (or others)!
