### ISSUE TITLE
worker stops 60-100% of contract at turns[BUG_SP]

### ISSUE THREAD

**Issue by w3armachine52** [Courseplay/Courseplay_FS22#3096]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen. at 60-100% stops at turns and sits there forever till i move them

**Expected behavior**
A clear and concise description of what you expected to happen. continue to finish field without needing me to move to next point

**Screenshots**

**Courseplay version**
Version used: 7.4.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. umrv

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? yes renault 103 kubota spreader modded

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Fill it in correctly and give more informations.
Also correctly attach your log.

If that mod is NOT on modhub, there won't be any support given!
