### ISSUE TITLE
Unload sugar beet auger wagons in the field

### ISSUE THREAD

**Issue by Findus97** [Courseplay/Courseplay_FS22#3097]
**What is the problem this feature/enhancement solves?**
I like to work with the Homer Terra Variant 585 and the MB35 bunker or the Bergmann RRW 500 when harvesting sugar beets, but this kind of equipment is not working properly when making heaps in the field.

**Describe the solution you'd like**
Being able to create heaps in the field with these kinds of auger wagons.

**Describe alternatives you've considered**
I am aware of the possibility of using regular trailers.

**Additional context**
A similar "problem" was mentioned in #2927.

![20240206142713_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/6ce81b0b-9039-410e-aee9-d250ad8c7a8a)
![20240206142630_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/a5b7d9bb-e5e9-4945-ab14-9d8f8c11a2da)

**Comment by Tensuko** [comment]
> this kind of equipment is not working properly when making heaps in the field. 

Would love to know whats not working "properly" ...

**Comment by Findus97** [comment]
If I set up the helper, they start unloading the harvester, drive to the unloading point, and unload, but they don't unload the harvester again. I will post a picture later. I thought that it is known that the auger wagons don't work in this mode.

**Comment by Tensuko** [comment]
They actually do work, but that would need a bug report then with a logfile...

**Comment by Findus97** [comment]
> They actually do work, but that would need a bug report then with a logfile...

Okay. If you say they work, then it is definitely a problem on my side. Thanks for the quick reply!
