### ISSUE TITLE
[BUG_SP] Unload sugar beet auger wagons in the field

### ISSUE THREAD

**Issue by Findus97** [Courseplay/Courseplay_FS22#3098]
**Steps to reproduce**
Use the Bergmann RRW 500 (or the Holmer Terra Variant with MB35) to unload a sugar beet harvester and unload in the field.

**Actual behavior**
The trailer works fine for one round. After unloading the second time, the tractor with the RRW 500 isn't moving to the harvester.

**Expected behavior**
Find a path to the harvester and unload it after the second round.

**Screenshots**
![20240210213936_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/015cbc7d-2564-400a-a0fb-212f82df2d9a)
my settings
![20240210214123_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/ccba0029-6d9b-4e91-b5d8-a19152372873)
first round
![20240210214200_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/92f821db-2b14-4f71-8a78-a36ea609688a)
End of the first round works great.
![20240210215240_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/e9c6f198-5ab6-4a0c-974f-810af292ce8c)
second round
![20240210215336_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/b76fe814-3a29-47d0-8aaa-fba63828d770)
now the tractor isn't mooving anymore
![20240210215833_1](https://github.com/Courseplay/Courseplay_FS22/assets/159523739/0faef64f-b8e1-4af9-b44b-2f1dacb06285)
Additional view from the harvester.

**Courseplay version**
Version used: 7.4.0.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14230521/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Bergmann RRW 500 (Basegame)
Holmer Terra Variant (Modpack) Similar behavior.

**Relevant script mods**
Mods like Autodrive, Easy Development Controls (same results without)

Additional context
A similar "problem" was mentioned in #2927.
And I had created #3097

**Comment by Tensuko** [comment]
Yeah that need a general enhancement.
Can't tell you when we get to this.

**Comment by Tensuko** [comment]
Should work better now, but its not perfect yet.
Hard to find a good solution for this, but we keep an eye on it.
