### ISSUE TITLE
AD Punkte als Kurs Anfang

### ISSUE THREAD

**Issue by Neotras2552** [Courseplay/Courseplay_FS22#31]
Hallo, also ich hätte dort ein Vorschlag, könnte man nicht als kurz Anfang ein AD Punkt nehmen bedeutet wenn ich Fahrzeug XY mit Anbaugeräte (wobei das Anbaugerät Ausschlag gebend ist) zum AD Punkt "Feld 31" schicke , das er dann automatisch ein vorgefertigte Route lädt welche man vorher erstellt hat, und er automatisch von AD zu CP wechselt?

**Comment by Tensuko** [comment]
Die Schnittstelle zu AD ist noch in Planung. Wir müssen erstmal die Funktionalität sicherstellen.

**Comment by Tensuko** [comment]
Erst mal zu, Schnittstelle kommt später.
