### ISSUE TITLE
[BUG_SP] Game hangs when buying a Poplar pallet.

### ISSUE THREAD

**Issue by Truckernoerden** [Courseplay/Courseplay_FS22#310]
Steps to reproduce:

   Buy a tractor, the tree planter, and then buy the pallet of poplar.
   FS22 hangs during load at 22% (A slight difference in percentage for different maps). You have the possibility to look around the tractor with the camera, but nothing else.
   Kill FS22 from task manager or Alt + F4

Verify courseplay is the culprit:

    Remove courseplay from mod folder.
    Repeat the first step.
    No problem with hanging.

Reproduced with several FS22 builds of courseplay, up to and including 7.0.0.10

Actual behavior
FS22 hangs during load at 22% (A slight difference in percentage for different maps).

Expected behavior
FS22 runs normally when buying a pallet of poplar.

Courseplay version
Version used: 7.0.0.10

Map
Tested on Elmcreek and Haut-Beyleron + several modded maps.

Vehicles/ implements involved:
Any tractor, the tree planter, and a pallet of poplar.

**Comment by Tensuko** [comment]
When you use our template, why there is no logfile ?

**Comment by Truckernoerden** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798870/log.txt)

**Comment by Truckernoerden** [comment]
Sorry. I forgot to attach it.

**Comment by Truckernoerden** [comment]
Found out myself what the problem was.
It was the Autorepair mod, that wanted to update.
