### ISSUE TITLE
[BUG_SP] Harvest stuck on "Silo Work"

### ISSUE THREAD

**Issue by Mr-Anivex** [Courseplay/Courseplay_FS22#3100]
Using the newest version of Courseplay, and the newest version of FS22. I've used this harvester before with courseplay and never had an issue, but today when I go to set a course on a field, there is no CP-Fieldwork option, only CP-SiloWork, which is not what I'm trying to do. I've tried different things like setting a target and driving the harvester to the field itself instead of getting it there with autodrive, but all that really seems moot because I can't get it to set the course in the first place. 

I've also tried saving and reloading, but that didn't seem to work either. Just not sure what to do here, I don't even know what silo work is.

**Comment by Tensuko** [comment]
Pls create a propper bug report by fill in our template.

**Comment by Mr-Anivex** [comment]
You need a better template.

**Comment by Tensuko** [comment]
The template shows everything that we need and you only have to fill that in!
If you don't want to fill that in, then don't expect any help.

Version missing.
And I don't even know what tool you talk about.
