### ISSUE TITLE
[Question] Creating a mod vehicle with shovel AND manure sprayer node

### ISSUE THREAD

**Issue by Sam-D03** [Courseplay/Courseplay_FS22#3103]
Hello! I'm coming to the end of developing a rather creative mod based on a real vehicle, the Bemad GreenCargo. This machine has a shovel node for loading manure from heaps, and then a trailer with a SPRAYER node on the back for spreading manure on fields.

In courseplay, it's seeing the vehicle as a SHOVEL vehicle and not allowing the normal sprayer fieldwork options to be selected. Is there a way I can define my vehicle to use the sprayer behavior by default instead of the shovel behavior? Maybe something I can add to the vehicle's XML file? Thanks!

![Screenshot 2024-02-01 224607](https://github.com/Courseplay/Courseplay_FS22/assets/46273185/319f695c-bf91-4d3c-a058-074eb1e79982)
![Screenshot 2024-01-31 040849](https://github.com/Courseplay/Courseplay_FS22/assets/46273185/625a5de7-4f59-454d-b9b5-93baa8fa5363)

**Comment by Tensuko** [comment]
You got to make it work with Giants Helper, then it should also work with CP.
Try that, if you are at that point and still have issues, you an reopen this Issue.
