### ISSUE TITLE
How to disable the ""should autodrive generate a route" popup at the start of the game?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/Courseplay_FS22#3105]
Every time I enter the game, I get this popup:
![image](https://github.com/Courseplay/Courseplay_FS22/assets/11199752/ed247983-e57e-406c-8617-12692b03ae93)
How to disable it?

**Comment by Tensuko** [comment]
Ask AutoDrive, not us. We have nothing to do with that.
