### ISSUE TITLE
i´m unable for seeing the lineguides

### ISSUE THREAD

**Issue by blindial** [Courseplay/Courseplay_FS22#3108]
i was gaming with CP and AD and I don´t know the reason but I lost the guides of both mods.
I had uninstalled all my mods and I start only with CP, with the option "see all points" activated of course. But I only can see the first and last point. It seems like I had disabled any "visual" option. I don´t know
I had reinstalled the game, the mods, upload, etc. Rigth control either do nothing. And the green "eye" isn´t the problem.
Any idea?
 First of all thanks and in my humble opinion this is the best mod of FS.

**Comment by Tensuko** [comment]
Delete the shader cache folder.
