### ISSUE TITLE
Red ?debug? line visible when auger unloading

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#3109]
Hello, I don't have debug tools activated and yet I still see red line when auger is unloading into parked vehicles. Is there any other menu what I'm missing or is it intentional? It is actually visible from other vehicles as well, not only one which unloading.  

![20240218211218_1](https://github.com/Courseplay/Courseplay_FS22/assets/33344465/de41be08-6671-4f7e-8849-0a82d2632154)

**Comment by Tensuko** [comment]
Thats a forgotten debug. Should be fixed in the next release. I keep an eye on that.
