### ISSUE TITLE
[Question] Full integration with AD

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#311]
When you have complete integration with AD, now, the seeders and fertilizers, when they have finished the product, no way that they go by themselves, using the AD, to load up and then resume work in the field, as it was done in FS19 ....

**Comment by RealNeo80** [comment]
#298 will done wenn the major bugs are solved in CP

**Comment by Tensuko** [comment]
As said many times, the connection with AD is fully planed.
