### ISSUE TITLE
[Feature] Unloading harvester in the headland

### ISSUE THREAD

**Issue by Joko-Ger** [Courseplay/Courseplay_FS22#3110]
**What is the problem this feature/enhancement solves?**
The harvester stucks in the tree with the pipe on the first line of the headland, because it calls the unloader at 60% fill limit and goes on driving.

![Problem Vorgewende](https://github.com/Courseplay/Courseplay_FS22/assets/99117003/5bd77568-b83d-421f-8484-86534abad02a)

**Describe the solution you'd like**
If the harvester is on the first line of the headland, it should drive a little bit into the second line and stop to call the unloader.

**Describe alternatives you've considered**
An alternative would be not to call the unloader at 60%, but only if the harvester is on the first line.

**Comment by Tensuko** [comment]
AD Problem, not our Problem.

**Comment by Tensuko** [comment]
If you use our unloader and remove that code part I mentioned on that AD issue you would not have that issue as we create pocket for unloading unless you toggle a setting to do unloading on first headland.We have API for that AD could read to work the same way with our combine bit they seem to not want that.
