### ISSUE TITLE
[BUG_MP] Plow Issue and Generator Issue

### ISSUE THREAD

**Issue by Buddersnaps** [Courseplay/Courseplay_FS22#3111]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

After Generating a course I leave the tractor and the plow no longer continues to make a new field, I do have create new field on.

Version used: 7.4.0.2

**Client Log**
There is nothing in the log

**Server Log**
There is nothing in the log

**Player on the server**
1

Dedicated server yes

**Map**
Map played on.    No mans land

All vehicles and plows

**Comment by Tensuko** [comment]
Logfiles are ALWAYS needed...
