### ISSUE TITLE
How to unload trailer after combine finishing the route?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/Courseplay_FS22#3112]
Using autodrive and courseplay, I created a route for a trailer to receive the combine seeds and unload them into a silo.
This works, but in the end, when the combine finishes the entire field, the trailer is stopped, with a partial load.
How can I configure it so that the trailer is sent to the silo at the end of the combine job in the field?

**Comment by Tensuko** [comment]
If you use CP Combine unloader, it will do a last combine unload and after that, it should drive to the target point and had over to AD for a last unloading into your silo.
If you use AD Combine unloader, I don't know how they do that.

**Comment by rogeriodec** [comment]
I didn't know there are both. 
Could you show how to set it up?
