### ISSUE TITLE
[BUG_MP] Lua Fehler beim starten einer Rote Beete Mission mit KI Fahrzeugen

### ISSUE THREAD

**Issue by timmi4026** [Courseplay/Courseplay_FS22#3114]
Hallo habe folgenden Fehler in der Log bekommen beim starten einer Mission für Rote Beete mit geliehenen Fahrzeugen der KI.

2024-02-28 12:03 Error: Running LUA method 'draw'.
C:/Users/Herbe/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpHud.lua:196: attempt to index local 'spec' (a nil value)

Log liegt bei.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14433048/log.txt)

**Comment by Tensuko** [comment]
Konnte ich jetzt nicht reproduzieren, allerdings gibt es demnächst ein Update, welches das für dich auch beheben könnte.
Ich behalte das Issue mal offen und wenn die neue Version da ist, dann versuchst du das bitte noch mal.

**Comment by timmi4026** [comment]
ok mach ich.

**Comment by Tensuko** [comment]
Versuch mal bitte die neue Version ob das noch immer so ist.
Ich konnte das nicht reproduzieren.
