### ISSUE TITLE
[Question] How to enable fertilizing while using subsoiler?

### ISSUE THREAD

**Issue by nborzunov** [Courseplay/Courseplay_FS22#3115]
I am using a subsoiler Bednar FB3000-TO6000-PT6000 with a fertilization option. It works perfectly using regular FS AI, but CoursePlay AI does not fertilize the soil when using this subsoiler. "AI buying fertilizers" is turned on in settings, and fertilization is also turned on in CoursePlay settings for this vehicle. Is there any way to fix it?

UPD: the fertilizer is consumed during the work, but the field is not fertilized after that

**Comment by Tensuko** [comment]
So if you drive the field will be fertilized?
Need to check that myself.

**Comment by Tensuko** [comment]
Seems to be a Giants bug, since the Giants Helper also doesn't turn the tool on.
