### ISSUE TITLE
[Question] SP Drescher fährt Rohr während des Abladens ein.

### ISSUE THREAD

**Issue by Icke09** [Courseplay/Courseplay_FS22#3116]
Mahlzeit
Ich benutze zurzeit CP 7.4.0.2 in Kombination mit AD 2.1.0.4.
Der Drescher wird durch CP gesteuert, der Abfahrer über AD. 
Das Problem ist Folgendes:
Der Drescher ruft den Abfahrer bei der gewünschten %-Zahl. Das Überladen startet und der Drescher beginnt das Rohr sofort wieder einzufahren, wenn er die oben genannte %-Zahl unterschritten hat, Drischt weiter und fährt das Rohr wieder beim Erreichen der gewünschten Prozentzahl aus. Der Drescher kann somit nicht vollständig entleert werden. Das beschriebene Szenario tritt bei mehreren Mod-Dreschern aus dem ModHub auf.
Beim Standard John Deere T560 wird zwar vollständig überladen, jedoch fährt der Drescher sein Rohr nicht wieder ein wenn er leer ist, sodass der Abfahrer permanent nebenher fährt.
Im Grunde handelt es sich ja um 2 Probleme. Eine Lösung für das erste Problem wäre wichtiger.
Die Frage ist ja wieso CP denkt der Drescher wäre leer. Er nimmt ja quasi den Ruffüllstand also Wert 0= Korntank leer an.
Für mich wäre interessant, auf welche Parameter CP da im Mod zu greift, damit ich sie zwischen Standard und Mod Maschine abgleichen kann..
Hat jemand vllt. ähnliche Probleme?

**Comment by Tensuko** [comment]
Abfahrer über AD -> AD Problem.
