### ISSUE TITLE
[Feature] Option for Slurry Double Application Rate

### ISSUE THREAD

**Issue by Bulldozer9837** [Courseplay/Courseplay_FS22#3117]
**What is the problem this feature/enhancement solves?**
The is an option for a double application rate of slurry within the game, but courseplay does not seem to adjust to this, and I was unable to find a setting to make it work. 

**Describe the solution you'd like**
Add a setting or a check for if the double application rate is enabled to apply it to the field. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tensuko** [comment]
Won't add that.
Doesn't seem to be a basegame feature.
If so, Giants AI have to make that too, else we won't do that either.

**Comment by Tensuko** [comment]
Where is that setting???

**Comment by Tensuko** [comment]
But it does work with CP.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/0acaebca-69dc-4eac-a61a-b3a9ea401041)
Just toggle it like you would normaly do and it will put out the double amount.
1st patch Giants normal amount, 2nd patch Giants double amount, 3rd patch (sideways) CP with double amount.
No need an extra setting to do this.

**Comment by Bulldozer9837** [comment]
Thanks for the response, I tried throughly with all the different options selected and it doesn't work for me. but if it works for you when using courseplay then I guess it is a problem with my game or system.

Sorry.

**Comment by Tensuko** [comment]
Default cp settings, open the F1 Menu, turn on the double rate and it just worked for me.
