### ISSUE TITLE
[Feature] Automatic filling of slurry tanks

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#3119]
**What is the problem this feature/enhancement solves?**
The problem at the moment is that the vehicles with slurry tankers or self-propelled vehicles are left standing in the field when they are empty.

**Describe the solution you'd like**
When the device is empty, it should drive to the edge of the field where there is a vehicle to fill it. Similar to emptying the combine harvester.

Thank you and best regards

**Comment by Tensuko** [comment]
Duplicate (in german, but anyway) #2069
