### ISSUE TITLE
[BUG_SP] Bale-Pressing is like babysitting

### ISSUE THREAD

**Issue by NikGro** [Courseplay/Courseplay_FS22#3121]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Wrap Bales.

**Actual behavior**
Tractor as well as baler regularely get stuck on bales laying around.

**Expected behavior**
Maybe enable pathfinder even when working on the course an not only on "driving-nodes" (as long as a baler is attached) so it can drive around bales.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/62887841/ee3f28b0-1f2a-4243-a212-d4e9a1a4d95e)

**Courseplay version**
Version used:  v7.4.0.2

**Log**
https://gist.github.com/NikGro/d750988882f9de5cece747ed7c47bcba

**Map**
Iowa Plains View

**Vehicles/ implements involved**
Vanilla Fendt Vario 724 + Vanilla Fendt Baler

**Relevant script mods**
Autodrive installed & active, not in use for this task

**Comment by NikGro** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/62887841/8c254086-9cbb-419f-8499-388c41316cd6)

Average baling operation

**Comment by Tensuko** [comment]
Wrapping bales should be done with start on the lanes or wait for new generator where you can switch direction, so no bales on the headland are in the way.
Driving with 2 Balers and have that  pathfinder turn over the headland can easy lead into that one situation.

Won't fix. Do proper work like start on lanes, eg mowing with swath or use swath also start on lanes so you copy that course.
Or be fast enough and collect the bales on the headland 1st.
