### ISSUE TITLE
[BUG_SP] Default Ai Stops working

### ISSUE THREAD

**Issue by MassGax** [Courseplay/Courseplay_FS22#3123]
Using Fs 22 Platinum edition
Map Zelionka No mods (only courseplay version 7.4.0.0)
Fresh start I buy a John Deere 8RT 310 default configuration and  cultivator Lemken Koralin 9-840, then i buy field 88 use H for default ai to start cultivate near field 51 first pass when ai reach the edge Ai just stop there i need to dismiss and turn press H again and same thing happens again at the other end.Using courseplay to create a course and use is Ai other problem happens when it reach the edge next to field 51 it turns to position then reverse and wont stop reversing all do way to field 32 or hit something.I Remove courseplay and Default Ai works fine.

Here Default Ai Stoped
![fsScreen_2024_03_08_05_43_55](https://github.com/Courseplay/Courseplay_FS22/assets/162667946/8c51d3ee-4009-4818-96a6-fd7161c1c928)

Here Courseplay reserving
![fsScreen_2024_03_08_05_49_45](https://github.com/Courseplay/Courseplay_FS22/assets/162667946/c9cc8e3a-aca4-475e-86d5-137cfe4ea200)

**Comment by Tensuko** [comment]
See this and also for the next time fill in our bug report.
Won't fix.
Just use Cp then, it is super fast and easy to get a course running.
If there is a turn issue, 1st get the latest CP Version and try again, else make a propper bug report.
