### ISSUE TITLE
mini HUD

### ISSUE THREAD

**Issue by VikPilaf** [Courseplay/Courseplay_FS22#3125]
Hi guys, when I start the game the mini hud screen doesn't appear. How do you get it out?

**Comment by Tensuko** [comment]
Right mouse click is default.
Else it is del key on keyboard (default as well).
If it still does not appear, check the courseplay.xml under ..\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay and delete the line <Hud posX="0.167577" posY="0.020833"/> (Numbers could be different).

**Comment by VikPilaf** [comment]
solved thanks
