### ISSUE TITLE
[Question] Harvester mode feedback

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3128]
Just like to say thank you to the team for the new forager mode, it's brilliant to see this in CP 😎

When the forager resumes when a new unloader is present, it starts up and misses a slither of crop in front of the cutter head, perhaps it could backup a little bit after it has filled the trailer ready to start the next trailer?

![fsScreen_2024_03_10_15_45_15](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/57dae780-2ef0-42a7-8a48-f07bc4d3e5f2)

Lastly, would it be worth changing the name on the CP panel to Harvester rather than Combine? when I first loaded the new version up I was cycling through the operations looking to find forager, then realised I had to treat it just like a combine, it's only a small thing but Harvester would cover any type of harvester i.e. forage harvester, combine harvester, root crop/vegetable harvester as it now does more than just combine.

![fsScreen_2024_03_10_15_35_144](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/d1c63b19-2533-42d4-b834-5712f6575cdc)

**Comment by Tensuko** [comment]
We will not perform back up manuvers with harvesters.
On my test, that never happened, it could be due to fule save or something like that.
Will investigate that.

The text we can change, I don't rly care if whats written there.

**Comment by pvaiko** [comment]
> When the forager resumes

Which one exactly?

**Comment by coatsy35** [comment]
> > When the forager resumes
> 
> Which one exactly?

To be fair it is a mod, and I haven't had chance to use another forage harvester yet. I can live it it, it just looks untidy that's all - it's not a huge issue, I just thought you'd like to know.

This is the mod:
https://skywalker-farms.itch.io/fs22-new-holland-s2200 I was cutting with the maize/corn header. It's a nice popular older self propelled forager mod.

**Comment by Tensuko** [comment]
I rly don't want start support mods from other sides then ModHub for Reasons (Giants does at least test the mods a bit...)

**Comment by coatsy35** [comment]
> I rly don't want start support mods from other sides then ModHub for Reasons (Giants does at least test the mods a bit...)

Fair comment! I have noticed that if the harvester stops due to trailer change it leaves a strip. If it stops when you exit the game and then resume on the next playthrough, it doesn't leave a strip which is weird.
