### ISSUE TITLE
Errata concezione delle misure

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3129]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Ho controllato le misure presenti nello shop con quelle generate

**Actual behavior**
Quando genero il percorso per fare lo sfalcio dell'erba, la larghezza viene impostata molto più piccola rispetto a quella effettiva dell'attrezzo

**Expected behavior**
La stessa misura tra quella dell'oggetto e quella generata

**Screenshots**

**Courseplay version**
Version used: 7.4.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
North East End

**Vehicles/ implements involved**
Which vehicle or implement? Case IH Magnum 340 cvxdrive + pottinger novacat 301 am ed pro + pottinger novacat a10 cross flow
Mod yes/no ? No

**Relevant script mods**
Nessuna
![Farming Simulator 22 10_03_2024 18_14_54](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/5e60e36b-b998-4aeb-b230-aa6373af812c)
![Farming Simulator 22 10_03_2024 18_14_42](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/e5b4d021-b488-4c8f-b2a0-722e17f1e97c)
![Farming Simulator 22 10_03_2024 18_14_21](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/04fb0688-d01d-4f7d-9ac4-0a471ebd465b)

**Comment by Roby1164** [comment]
Le misure che leggi nello shop, non è detto che siano corrette, CP prende i dati da una stringa diversa, da quella che mostra le misure nello shop. Controlla se con gli attrezzi originali del gioco, funziona correttamente, con misure corrette....

**Comment by Trivelleitor** [comment]
Non capisco. Volevo precisare che gli attrezzi sono originali e non moddati, e se puoi spiegarmi in maniera diversa la tua risposta che non ho capito cosa intendi.

**Comment by Roby1164** [comment]
Ok se non sono mod allora è da vedere altro, ma controlla che esegui i passaggi corertti, sembra che CP prenda un dato (3m)  non corretto, quindi a capire da dove lo prende, fai prove con altro trattore, ecc.

**Comment by Trivelleitor** [comment]
Essendo un trattore non mio ma solo in prestito mi risulta difficile fare questa prova, comunque se dovesse capitarmi un altro contratto simile al limite aggiornerò il thread

**Comment by Trivelleitor** [comment]
Adesso che mi fai pensare il trattore è composto da due attrezzi di cui uno ha la misura di 3,1 m. Può essere che prenda il dato di quello? Se si come faccio a fargli prendere il dato più grosso?

**Comment by coatsy35** [comment]
> Now that you make me think, the tractor is made up of two implements, one of which measures 3.1 m. Could it be that he takes the data from that? If so, how do I get him to get the bigger data?

Unford the tool, take it off unfolded, attach it again and it will show the correct width.

**Comment by Trivelleitor** [comment]
Già provato non funziona

**Comment by Tensuko** [comment]
> > Now that you make me think, the tractor is made up of two implements, one of which measures 3.1 m. Could it be that he takes the data from that? If so, how do I get him to get the bigger data?
> 
> Unford the tool, take it off unfolded, attach it again and it will show the correct width.

No need to re-attach, just click on the width text on the hud to read the width.

**Comment by Trivelleitor** [comment]
Ok, ma non esiste la possibilità di farlo in automatico?

**Comment by Tensuko** [comment]
Not for all tools, so no.
You can only add that into your own vehicle config file.
https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.
