### ISSUE TITLE
Sprayer needs refilling issue returned, when using spot spraying.

### ISSUE THREAD

**Issue by Haus-Master** [Courseplay/Courseplay_FS22#3130]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
purchase sprayer with spot spraying addon. attempt to start a course.

**Actual behaviour**
Start course, unfolds implement, "Needs refilling message appears", folds implement and stops course.

**Expected behaviour**
Completes course.

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/152433509/8c6481b5-bf55-4ae8-aa17-9449c4acea01)

**Courseplay version**
Latest - 7.4.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14551913/log.txt)

**Map**
Saxthorpe

**Vehicles/ implements involved**
Case Magnum CVX 145 - Mod
Kverneland iXter B18 - Mod

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Vanilla Tractor and the PF JD sprayer is working?

**Comment by Tensuko** [comment]
Addition: As you see here in the old Issue, it was the same topic....
#2985

There is no bug fixing linked from our side, also when I check our release notes, nothing mentions that there is a bug fixed.

I will try it out later at home but I have only the JD Sprayer and did all the work with the last Version...

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/bfdcb311-bb30-4053-9a64-ea5d43e93468)

**Comment by Haus-Master** [comment]
> Can't reproduce with Giants default Equipment (PF DLC JD Sprayer) ![grafik](https://private-user-images.githubusercontent.com/27344744/311819879-bfdcb311-bb30-4053-9a64-ea5d43e93468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTMzMTgsIm5iZiI6MTcxMDE5MzAxOCwicGF0aCI6Ii8yNzM0NDc0NC8zMTE4MTk4NzktYmZkY2IzMTEtYmIzMC00MDUzLTlhNjQtZWE1ZDQzZTkzNDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIxMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwODg3NDM3YjVlZmNlMzQ0MTA3NmFiY2IzMzllOWRmZjkwNGIzYjc1NjQ5MzVhNTk1MmJiN2E2NTk4NmNlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U31McoC2tV-t1F85pSWaip737LFx4e4fe2u74Fqg5LU)

Is this done with spot spraying enabled?

**Comment by Haus-Master** [comment]
It works with "see & spray" on the JD from Precision Farming but does not work with any mod that uses "Weed spot spraying".
I raised this issue previously on here, apparently it was noted down and it was either fixed or started working fine.

**Comment by coatsy35** [comment]
Works on the Amazone Panterra mod if that’s helps. Not sure what the difference is between the different spot sprayers

**Comment by Tensuko** [comment]
> > Can't reproduce with Giants default Equipment (PF DLC JD Sprayer) ![grafik](https://private-user-images.githubusercontent.com/27344744/311819879-bfdcb311-bb30-4053-9a64-ea5d43e93468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTMzMTgsIm5iZiI6MTcxMDE5MzAxOCwicGF0aCI6Ii8yNzM0NDc0NC8zMTE4MTk4NzktYmZkY2IzMTEtYmIzMC00MDUzLTlhNjQtZWE1ZDQzZTkzNDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIxMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwODg3NDM3YjVlZmNlMzQ0MTA3NmFiY2IzMzllOWRmZjkwNGIzYjc1NjQ5MzVhNTk1MmJiN2E2NTk4NmNlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U31McoC2tV-t1F85pSWaip737LFx4e4fe2u74Fqg5LU)
> 
> Is this done with spot spraying enabled?

Spot Spraying is always active on this (just tested if weed on/off is a difference, so I added weed with easy dev).

> Works on the Amazone Panterra mod if that’s helps. Not sure what the difference is between the different spot sprayers

Then this is a mod Issue and not a CP Issue if JD and another mod is working fine.

**Comment by dominik199818** [comment]
remove pumps n hoses addon
it worked for me
