### ISSUE TITLE
[Feature] Save Course Metadata instead of courses

### ISSUE THREAD

**Issue by n1cname** [Courseplay/Courseplay_FS22#3132]
**What is the problem this feature/enhancement solves?**
When working with different implements I can't remember the best settings for each one. I try a new cultivater with "-0,2 Field Range, 18% head line overlap, etc", but this leaves some spots uncultivated. Next season I want to use "20 % head line overlap". I would have to write it down off game (Excel or txt file or similar).
second example: The harrow usually starts on the headlines first, but after seeding beets I want to run it rows fist, because this is how I seed them.

**Describe the solution you'd like**
I want to save not only the course waypoints but an editable set of metadata / creation data for the course, so I can recreate and change it easily on the next run.

**Describe alternatives you've considered**
Save the metadata outside of FS22.

**Additional context**

Thanks a lot considering this request. And big thanks for the great work so far!

**Comment by coatsy35** [comment]
I think they already have something similar to this on their future plans list. The ability to save implement settings, so possibly it could allow altering of them settings in game and out of game

**Comment by Tensuko** [comment]
Planed to save settings in the tool, not the vehicle.

To be honest, some of you take stuff to sirious.
I get always on the field, open the generator and by experience I set some settings.... some even need to be adjusted by field pattern and not by tool so.....

Anyway, planed but far in the future.
