### ISSUE TITLE
[BUG_SP] auger wagon debug line always visible

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#3135]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
unload auger wagon

**Actual behavior**
small optical issue only: red debug line appears (maybe from PipeController?) even when debug set to off. 

**Expected behavior**
if debug off, the line should be invisible

**Screenshots**
![fsScreen_2024_03_10_13_34_32](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/a5215682-588c-4b7b-ab23-32118ca616be)

**Courseplay version**
Version used: 7.4.1.0

**Log**
N/A

**Map**
N/A

**Vehicles/ implements involved**
N/A

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
Damn it, I rly forgot about that :D 

@schwiti6190 cab you have a look pls ? :D
