### ISSUE TITLE
After unload operation in Haut-Beyleron map game freezes [BUG_SP]

### ISSUE THREAD

**Issue by Visionaires** [Courseplay/Courseplay_FS22#3145]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Step one: Have combine harvest field 9 during contract.
Step two: Get starter tractor and trailer near the same field as combine.
Step three: Set up job for tractor trailer to unload combine at 85% and deliver goods to Le Jardin des Fermiers Farm Shop. After unloading the game freezes

**Actual behavior**
While delivering goods to Le Jardin des Fermiers Farm Shop in Haut-Beyleron Map during the unload and deliver CP job, after the trailer unloads the game freezes.

**Expected behavior**
After unloading I thought the tractor and trailer would either stay until combine needs emptying again or to move back to the field that the combine is on.

**Screenshots**

**Courseplay version**
Version used: 7.4.1.0

**Log**

[logFS22.txt](https://github.com/Courseplay/Courseplay_FS22/files/14616258/logFS22.txt)

**Map**
Elegrant

**Vehicles/ implements involved**
Which vehicle: Tractor Valtra 8750 with trailer: Welger DK 115
Mod no 

**Relevant script mods**
Nothing

**Comment by Visionaires** [comment]
After more testing this is not specific to Le Jardin des Fermiers Farm Shop. It seems to freeze/crash anytime the CP deliver job unloads at any destination on this map. I will start testing other maps (base game maps)

**Comment by Tensuko** [comment]
Can you try out this Version?
[FS22_Courseplay.zip](https://github.com/Courseplay/Courseplay_FS22/files/14618972/FS22_Courseplay.zip)

**Comment by Visionaires** [comment]
Testing now

**Comment by Visionaires** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/163547328/62e18a20-ce70-4d39-8eeb-2fe48faa5c75)
 Starting to get this now

![image](https://github.com/Courseplay/Courseplay_FS22/assets/163547328/20a64f07-0478-4e02-9a75-d165dc00f985)
Could be unrelated going to clear all the jobs and try again

**Comment by Visionaires** [comment]
> Can you try out this Version? [FS22_Courseplay.zip](https://github.com/Courseplay/Courseplay_FS22/files/14618972/FS22_Courseplay.zip)

Doesn't look like its freezing anymore
