### ISSUE TITLE
vehiclesettings.xml missing after fresh reinstall of mods [BUG_SP]

### ISSUE THREAD

**Issue by Mantic0re** [Courseplay/Courseplay_FS22#3148]
I was playing SP on western wilds map with too many mods.  I made a custom field and 2 fieldwork courses in CP.

1. The fieldwork course has lots of missed areas despite 1m reduction in working width so I deleted the fieldwork courses.  
2. The button/option to create a new fieldwork course was not appearing so I deleted the custom field and made a new field. 
3. now when trying to create a new fieldwork course I get an error indicating logs might help. 
4. Logs indicate /Documents/My Games/ FS2022/modsettings/FS22_courseplay/vehicleconfigurations.xml does not exist.
5. I copied the xml from the courselplay zip in the mods folder into.../my games/FS2022/modsettings/fs22_courseplay
6. I get the same error mesage - logs indicate same issue in step 4 even though I've added missing file (I'll try to attach screenshot)
7. Validate game file integrity
8. Delete everything in /my games/ FS2022/mods and /my games/ FS2022/modsettings
9. Reinstall courseplay from the in-game modhub feature.
10. Error now triggers on map load (not on courseplay create fieldwork course) with courseplay version number 7.4.0.0 and github address for bugs. 
11. Log still shows the error in step 4.  

I really appreciate any help you can provide.  
I can see the file that is missing in the correct directory.  Could one of these .xml files be missing some index or reference?  
I'm not a programmer and don't know how to use devtools but I will try if you need more information.  

![Courseplayhelp](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/10ec9e51-c96b-4ed5-86c5-37cd042c2202)
[Courseplayhelplog.txt](https://github.com/Courseplay/Courseplay_FS22/files/14620655/Courseplayhelplog.txt)

**Comment by regs1980** [comment]
@Mantic0re 
Take another close look at the file you have inserted there.

**Comment by Mantic0re** [comment]
I see that now.  Where can I get this missing file?  It doesn't generate from verifying game files or from in-game mod-hub download

**Comment by Tensuko** [comment]
vehicleConfigurations.xml not VehicleSettingsSetup.xml.....

**Comment by Tensuko** [comment]
But I think you mix a lot stuff here.

**Comment by Mantic0re** [comment]
ok.  I see that now.  
I'm out of my element and don't understand what I'm reading.  

These facts remain true: 

1. The problem did not resolve when I reinstalled the mod in-game.
2. I still get messages to submit a bug report upon loading a map/session
3. I'm asking for help.

**Comment by Mantic0re** [comment]
![Courseplayhelp2](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/c5eff209-b93f-4ede-85fd-f96460f418f0)

**Comment by Tensuko** [comment]
> 1. The fieldwork course has lots of missed areas despite 1m reduction in working width so I deleted the fieldwork courses.

Thats the right way to change the width and make a new course.

> 2. The button/option to create a new fieldwork course was not appearing so I deleted the custom field and made a new field.

The custom field got not much to do with that normaly.
You got to place the fieldmarker to the correct spot and the field area would be marked "white".
Then you should be able to generate a course (or show a screenshot of your problem).

> 3. now when trying to create a new fieldwork course I get an error indicating logs might help.

That can mean so many things, also change settings for the generator, we also don't know how your field look like.

> 4. Logs indicate /Documents/My Games/ FS2022/modsettings/FS22_courseplay/vehicleconfigurations.xml does not exist.

That got nothing to do with any course generation and is not an Error.

> 5. I copied the xml from the courselplay zip in the mods folder into.../my games/FS2022/modsettings/fs22_courseplay

Thats the wrong way, read it up here for waht it is: https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.

> 6. I get the same error mesage - logs indicate same issue in step 4 even though I've added missing file (I'll try to attach screenshot)

That one was cleared.

> 7. Validate game file integrity

Not needed...

> 8. Delete everything in /my games/ FS2022/mods and /my games/ FS2022/modsettings

No one said you had to do that...

> 9. Reinstall courseplay from the in-game modhub feature.

Thats just getting the modHub Version file again.

> 10. Error now triggers on map load (not on courseplay create fieldwork course) with courseplay version number 7.4.0.0 and github address for bugs.

Also that is not an Error thats an Info Window....

> 11. Log still shows the error in step 4.

Again, more Information on the actual Error, screenshots from the field and stuff are needed.

**Comment by Mantic0re** [comment]
hmm...
I guess I did skip over what the problem is. 

I cannot create any fieldwork courses in Courseplay. 

I have posted what happens and what I have done to try to address the problem.

**Comment by Mantic0re** [comment]
![fsScreen_2024_03_15_18_12_45](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/0f072929-b7e7-4f08-babf-98525a3a906d)

**Comment by Tensuko** [comment]
We don't need an XXL Screenshot of the Error, that we know....
We can't know how your marked field looks like and your tool that you use and the settings of the generator that you try.....

**Comment by Mantic0re** [comment]
![fsScreen_2024_03_16_12_47_56](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/29ece20e-4812-41b5-8802-f0ac7b3c589c)
![fsScreen_2024_03_16_12_47_47](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/e1a25f9f-ec2f-4871-a1ee-9b33f2dc11a3)
![fsScreen_2024_03_16_12_47_43](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/2d557242-fc68-49e4-bb9e-a27c311b67fa)

Field created by right clicking on the overhead map in editor mode.  (same method used every time)
Using the Pottinger novacat mower set.
Pottinger

**Comment by Tensuko** [comment]
Try to draw it like this with the small green marked gap.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/d3280246-cd3d-4bac-b397-7f9c8ab086b5)

It sounds wrong at 1st, but we have (or had) an issue somewhere, where the same problem occurse, when there is a tiny overlap.
So rather do a small gap (can also be at a corner I think). That should not influence the generated course (best is on the side).

**Comment by Mantic0re** [comment]
![fsScreen_2024_03_16_19_47_35](https://github.com/Courseplay/Courseplay_FS22/assets/29669704/3454e440-c95d-4c62-ba16-4fe0326fed7c)
 
It created a course for me with a gap on the side. 

I didn't have it aligned perfectly so the course had a slight turn.  

Thank you for your help.

**Comment by Mantic0re** [comment]
It is interesting that a small gap is less problematic than a slight overlap.
