### ISSUE TITLE
Can't generate Courses on Map FS22_BigFieldsXXL10km_zoltanm

### ISSUE THREAD

**Issue by chroboss** [Courseplay/Courseplay_FS22#315]
**Steps to reproduce**
Set field and direction and starting coursegenerator, but no course ist generated. No errormessage appears.
Error message in Logfile is:` C:/Users/rolfc/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/courseGenerator/geo.lua:600: too many results to unpack`

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
FS22_BigFieldsXXL10km_zoltanm

**Vehicles/ implements involved**
All, mod and vanilla
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7799033/log.txt)

**Relevant script mods**
Autodtrive, VCA, advancedGameplaySettings, PowerTools

**Comment by mcNETDev** [comment]
Have the same problem
In version 7.0.0.11 is exactly the same error.

Also used the same map.

**Comment by Ursus95** [comment]
Same problem, with 7.0.0.11 and the same map.

I think the problem is with the map, probably the fields are not properly done or something.

**Comment by pvaiko** [comment]
As @Ursus95, most likely a map problem.

Sorry, this time we can focus on standard maps/equipment only.

**Comment by chroboss** [comment]
Thanks for verry quick respponse !   I'll contact the mapper.

**Comment by Ursus95** [comment]
> Thanks for verry quick respponse ! I'll contact the mapper.

Did you managed to contact the modder?

**Comment by chroboss** [comment]
@Ursus95  I've tryed. I wrote a comment on his FBM account. Waiting for his reaction...
