### ISSUE TITLE
[BUG_SP] course generator sometimes generate no straight line inner field.

### ISSUE THREAD

**Issue by OldFamous** [Courseplay/Courseplay_FS22#3151]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Generate field course with 2 headlands wich start on the headlands

**Actual behavior**
Some times the inner line's are slightly crooked. 
The fields are rectangular, headlands generated nice and straight.
Some time's If I line up my vehicle again with the field border it generates the course correct.
Straight headlands and straight inner field.
Sometimes I can generate course again again and again and it will not get the innerfield straight.

**Expected behavior**
If you generate course with start on headlands and your field is rectangular the inner field line's also follow's the straight lines off the headlands
**Screenshots**
![fsScreen_2024_03_17_09_27_56](https://github.com/Courseplay/Courseplay_FS22/assets/5245750/26fc70f3-9822-48bb-a7ad-ef9699a53cd6)

The field left is how I expect.
The field right is how its generate some time's.

**Courseplay version**
Version used: 7.4.0.2
Right now I see there's a new version so I will try that out too

**Log**
https://pastebin.com/XW43DeAm

Iam aware of my long log but because the failure in generating course not always happen I decided to post now my full log with al mods.

If you need it I will test it again without mods and upload new log.

**Map**
several maps

**Vehicles/ implements involved**
harvesters and implements not just one
Mod yes/no ? Yes

**Relevant script mods**
I have autodrive but not using it on that time's

**Comment by Tensuko** [comment]
Try direction longest edge.
It is all due to field borders.
Not a bug.

**Comment by OldFamous** [comment]
I checked how I generated my last course, generated with longest edge.
Now Id generated the course again(new one, same settings) and now is everything straight.
![fsScreen_2024_03_17_11_33_09](https://github.com/Courseplay/Courseplay_FS22/assets/5245750/d67fadce-819d-408b-a29c-8d69a600efdf)

Reset course and drive 1 meter with harvester, generated same course same settings and now the innerlines are slightly crooked again.

![fsScreen_2024_03_17_11_33_30](https://github.com/Courseplay/Courseplay_FS22/assets/5245750/5a7edbbe-3ece-4891-88f4-61287cb9d1cb)

tested also a third time, first generated course straight,no movement with harvester just immediatly reset course and generated again, gives crooked line's again. (no screens)

**Comment by OldFamous** [comment]
My bad indeed I think..
I read your answer again and now if tested with manually direction, always straight lines till now!

I think sometimes manually is better and sometimes longest edge.

Thanks for your help!
