### ISSUE TITLE
[Frage] Courseplay starten 

### ISSUE THREAD

**Issue by ChrisP87** [Courseplay/Courseplay_FS22#3153]
Hallo, 

eine Frage, wir haben mit mehreren Freunden einen Server zu laufen und jeder bewirtschaftet sein eigenen Hof (Lohner Status gibt es untereinander)
Courseplay kann ja nur gestartet werden wenn man die Hofrechte hat, kann man das so einstellen das jeder CP starten kann ?

LG Chris

**Comment by Tensuko** [comment]
Nein, nur mit entsprechenden Rechten -> Giants AI Standarts.
