### ISSUE TITLE
[BUG_SP] the autoloader will avoid harvests even if the option is disabled

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#3155]
Hello,

I have the same problem as #2993, but this time it's with self-loaders and bale trailers.

The tractor avoids the crops to reach its last loading point, even though I have deactivated “avoid crops”
  the problem is the same with a trailer to load the bales

When the self-loader is full, the tractor will not avoid the crops (and that's what I want)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14641188/log.txt)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/c6f7c040-1f8d-4405-ab54-3f3d66ccd602)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/45f9f6a6-fde5-4f4b-9cca-150414150360)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/dbca080c-97f5-4b73-89b7-f53e4bdac0da)

**Comment by Tensuko** [comment]
What do you mean with "self loaders" ?
And why is it a problem for bale trailers, they always have to do calculations anyway.

**Comment by Crinouche** [comment]
Self loader or autoloader : i don't know the good translation in english, it's the trailer in my pictures

For bale trailers, this is a problem because sometimes the tractor has to detour several meters to get around a crop being harvested when a bale is right in front, on the other side of the crop. As soon as possible, I will post a photo to illustrate

**Comment by Crinouche** [comment]
NO, also trailers that load bulk fodder, like the one in the photo
