### ISSUE TITLE
Allgemeine Frage

### ISSUE THREAD

**Issue by KarlGutenberg** [Courseplay/Courseplay_FS22#3157]
Hallo! Ich habe gesucht, aber keine Lösung gefunden!
Frage: Wie bekomme ich diese Zielposition gelöscht!
Ja ich weiß, ich kann diesen auf ein anderes Feld setzen, aber manchmal
fahre ich zu abholen los, aber der Traktor fährt leider zum letzten Feld!

![Zielposition](https://github.com/Courseplay/Courseplay_FS22/assets/78603817/1dff2d65-aae2-46f0-969a-7f23c07e6c1e)

Sorry, ich weiß nicht, wo ich das sonst fragen kann!

**Comment by Tensuko** [comment]
Ich verstehe leider das Problem gerade nicht.
>  aber manchmal fahre ich zu abholen los, aber der Traktor fährt leider zum letzten Feld!

Was heist fahre zum abholen los, da musst du schon genauer beschreibung was du machst und was das Problem ist.

Oder du beschreibst was du machen möchtest, eventuell gibt es dafür einen besseren Weg?

**Comment by KarlGutenberg** [comment]
Also! Wenn ich auf dem Feld 7 fertig bin und auf Feld 8 neu anfange, zeige ich mein Abfahrer mit der Feldposition, dass ER auf Feld 8 abfahren soll! 
Der Abfahrer, wenn ich die Zielposition nicht gesetzt habe, aber erst zum Feld 7 fährt!
Ich fahre mit Autodr. zum Feld 8 und CP übernimmt dann!
Ich hatte mal gelesen o. auf Video gesehen, dass ich eine Zielposition nicht brauche!?
Wenn CP, wenn der Abfahrer voll beladen hat, auf dem Feld schon, dass er abfahren möchte!
AD übernimmt dann schon auf dem Feld und kann dann die nächstmögliche Abfahrt nehmen!
Das geht leider nicht, wenn ich die Zielposition setze!
Wenn ich einmal die Zielposition gesetzt habe bekomme ich sie nicht wieder weg!
Auch wenn ich ein neues Spiel starte ist die Zielposition an der letzten stelle!

**Comment by rohne83** [comment]
Weg bekommst du die Zielposition nicht. Wenn du willst dass der volle Abfahrer nicht erst noch mit CP zurück zur Zielposition fährt, sondern direkt auf dem Feld schon an AD übergibt, dann setz einfach die Zielposition mindestens 20m außerhalb des zu bearbeitenden Feldes. Wohin ist egal, sobald die Position weiter als diese 20m vom Feldrand weg ist berechnet CP keinen Kurs dorthin, und AD übernimmt schon das Verlassen des Feldes.

**Comment by KarlGutenberg** [comment]
Hallo und Danke Dir für diesen Tip!
Ich habe mal die Zielposition weit weit weg gesetzt und brauche mich jetzt nicht mehr darum kümmern! Danke nochmals.

**Comment by coatsy35** [comment]
Would be quite nice to turn target position off for some vehicles so that you only have to select field position as I always use AD for the leaving of the field

**Comment by KarlGutenberg** [comment]
Das wehre super,da ich auch überwiegend mit AD abfahre.

coatsy35 ***@***.***> schrieb am Di. 19. März 2024 um 21:08:
