### ISSUE TITLE
[BUG_SP] unloading at row end stops too early

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#3158]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Combine calling CP unloader short before row end.

**Actual behavior**
With v 7.4.1.0 the unloader follows combine to the end of row, but once arrived there it immediately backs up independently of combine fill level so unloading can't be finished. Earlier on this same field I had same situation with combine still at more than 90% filllevel when unloader backed up. This is especially problematic for multitool courses when first combine empties at row end before starting a new land, but this unloading is ended too early.

**Expected behavior**
Unloader should stay next to the combine until unloading finished completely (combine emtpy or unloader full) before he backs up. Guess this is unwanted side effect of "the unloader and combine will drive the full row and not stop close to the end of the row." (release notes of current version)

**Screenshots**
![fsScreen_2024_03_19_18_21_03](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/46b6bacb-23c9-48bf-a04d-572b3e3837fc)
combine which is unloaded is the last one of the list, with 18% filllevel right that moment. Auger wagon already driving backwards here.

**Courseplay version**
Version used: 7.4.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14654667/log.txt)
situation in screenshot appeared at 18:20:56

**Map**
N/A

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
@pvaiko but it does not figth with our old function where we waited for the unloader just before then end of the row?
Because I just had a similar situation (sadly no log active), there was the combine short before the row end and then they drove to the end of the row, but stopped unloading.

**Comment by pvaiko** [comment]
> situation in screenshot appeared at 18:20:56

Thanks for including this, makes my life a lot easier. 

Next time please also have the combine debug on, it is interesting to know what the combine is doing as they are working together with the unloader.
