### ISSUE TITLE
[BUG_SP] restarted combine misses fruit after unloading started

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#3159]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Combine getting full and stopping. Unloader reaching the combine for unload, and both start to move again.
Issue itself doesn't happen always but quite regularly.

**Actual behavior**
In most situations the header is lowered the same moment that the unloader arrives at the combine, and activated once combine starts moving - then everything is good. But in other situations the header remains up when unloader arrives and only lowered once the emptying combine starts to move on - in these situations fruit is left, as header is turned on too late.
This behaviour is quite new, started to occur with 7.4.0.2 I think. Cannot remember that I had this issue before that.

**Expected behavior**
Header should always be activated again in time, so that fruit is never missed.

**Screenshots**
![fsScreen_2024_03_20_17_03_04](https://github.com/Courseplay/Courseplay_FS22/assets/71030138/cc51e28a-4dde-470d-9689-2d4593b54cd2)

**Courseplay version**
Version used: 7.4.1.0 (could be observed with previous version already)

**Log**
N/A

**Map**
N/A

**Vehicles/ implements involved**
Combine + unloader

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
The big problem here is to catch the reason.
I harvested a big field of sunflower yesterday and nothing was left.
If that is a timing problem, it will be hard to catch, or we have to throw delay timer at everything or something similar.
Can you try to catch that problem in a video with debug active and maybe dev active as well? (I think you know the command)

**Comment by coatsy35** [comment]
Same problem I had with that older forager mod I think. When it got full and stopped to change trailer it left a small amount

**Comment by Tensuko** [comment]
> will try. What exactly do you mean with dev active?

See DC pm.
