### ISSUE TITLE
[Question] sugar cane harvest combine unload

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/Courseplay_FS22#3161]
Hello I was wondering if the newly added combine unload support for choppers would sugarcane harvesters be included in that?

**Comment by Tensuko** [comment]
We did not try that.
You can try it out, but when it is not working I have to tell you that we will not add this.
It is barely used and the effort to get this running is very high.
As you might see we still have some adjustments to do for normal combine unloading, so there is also no time for sugar cane.
Sry.

**Comment by jobyrns72** [comment]
No worries I very much understand. That's why I asked because I did test it out and it recognized the harvester but didn't pull enough up beside it to start the unload process since the pipe shoots down instead of out like a chopper. I totally understand.
