### ISSUE TITLE
изчезла часть мода[Question]

### ISSUE THREAD

**Issue by marian2134** [Courseplay/Courseplay_FS22#3165]
у меня не отображает путевие точки и изчезла часть настроек
![fsScreen_2024_03_23_10_57_16](https://github.com/Courseplay/Courseplay_FS22/assets/164553156/6c128ed5-576f-46c8-9874-0296f9a01acb)
![fsScreen_2024_03_23_10_56_59](https://github.com/Courseplay/Courseplay_FS22/assets/164553156/1a45adb0-da4a-4b3e-bc70-2293f9f4c8f7)

**Comment by Tensuko** [comment]
No waypoints:
delete files in
...\Dokumente\My Games\FarmingSimulator2022\shader_cache
you game will lag and stutter for a while, but thats normal, it will be back to normal fast.

Some settings missing:
CP global settings -> expert mode active?
