### ISSUE TITLE
[BUG_SP] forage trailers do not work with forage harvester mode

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#3168]
loader trailers (like those in the photo) do not work in forage harvester mode
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/6e7bb520-b6c6-4171-867e-aa0499e04d02)

**Comment by Tensuko** [comment]
You know how to make bug reports.
And here I ask as well, is this a mod ???

**Comment by Tensuko** [comment]
Vanilla: Works just fine.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/8ab61b70-61da-4160-b60b-435c85940712)
