### ISSUE TITLE
[Question] Kursplanung funktioniert nicht?

### ISSUE THREAD

**Issue by BigBlackBahamut** [Courseplay/Courseplay_FS22#317]
Beim Rückwärtsfahren mit der großen Saatmaschine von Amazon kommt es beim Rangieren mit Probleme. Muss man da noch etwas einstellen oder ist es einfach nur noch ein Bug?

**Comment by BigBlackBahamut** [comment]
Bemerke gerade das bei der großen Amazon CP spinnt. Er fährt gerade Rückwärts im Kreis und findet nach längerer Zeit wieder den Kurz.

**Comment by Tensuko** [comment]
Welche Version hast du probiert ?

**Comment by BigBlackBahamut** [comment]
die 7.0.0.11

Erst schiebt er die Amazon regelrecht wie ein Acht auf dem Feld:

![20220102152646_1](https://user-images.githubusercontent.com/59480223/147879397-e5a59eb8-75e5-49d2-a7c1-e1e5a6f625ad.jpg)

Dann in die andere Richtung:


![20220102152717_1](https://user-images.githubusercontent.com/59480223/147879418-1d36fa5b-a937-460d-bb2e-cd523e76356e.jpg)

**Comment by Tensuko** [comment]
Hat mir Kursplanung nichts zu tun was du da meinst.
Siehe hier #275

**Comment by Tensuko** [comment]
Also ich habs eben mit der Amazone getestet (90° und 180°) kein Problem.

**Comment by BigBlackBahamut** [comment]
Ja, leider geht es unter 90° da es eher ein Trapez-Feld ist. Aber OK. Behalte das mal im Auge. Danke für die schnelle Antwort.
