### ISSUE TITLE
[BUG_SP] Plough Turning Circle

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3173]
Sorry to start new issue on this, I've just had loads of contracts that use this plough and twin track tractor combination and It never works right. so much so I can't use the combination on my own land as it's doesn't cover everything correctly. I think @pvaiko had some ideas last time but I can't find the right thread. The Lemken as we all know works fine, but contracts often give this plough and if you download any larger ploughs you get the same issue i.e. the Gregoire Besson SPSL 9 for large American maps. And before @Tensuko asks yes it's on raise late and lower early :D 

**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use a JD 8RT & KV PW100-12 to plough a contract. Width set at 5.9m and 9 headlands 

**Actual behaviour**
Plough turning circle is not correct. I have tried various turning radius overrides but all end up with gaps. 

**Expected behaviour**
Plough to turn out wider and then come back in straight so gaps between runs are not left

**Screenshots
![fsScreen_2024_03_24_20_46_56](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/14154f51-cc75-4c5d-8c40-39ec32e31629)
![fsScreen_2024_03_24_20_47_24](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/03c42ce1-cf9f-47b7-8be3-a73a38e29497)
![fsScreen_2024_03_24_20_47_40](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/b97acae7-8f9d-4dec-a75a-16f252d9cb5c)

**Courseplay version**
Version used: 7.4.1.1

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14736799/log.txt)

**Map**
Saxthorpe

**Vehicles/ implements involved**
Gants JD 8RT 340 & Giants KV PW 100-12

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by kwguk** [comment]
For what its worth i had a similar discussion on the AD Discord page on Tensuko's CP thread. I found that for an articulated plough such as the largest Gregoire Besson and you set the width to 7m and have 'use pathfinder in turns' on and 'use pathfinder in reverse' off it all works fine. I was using KarlFarms Quadtrac rather than a JD 8RT.

**Comment by Tensuko** [comment]
Should should sort out mods.
I see callstacks and a lot of Errors....

And if I try this with default settings for fresh bought vehicles, it is not happening like that.
Yea a bit and I may have an Idea why.

> Expected behaviour
Plough to turn out wider and then come back in straight so gaps between runs are not left

Thats not the solution.

> Actual behaviour
Plough turning circle is not correct. I have tried various turning radius overrides but all end up with gaps.

If you tried different turnRadius, how can be the turning circle the problem?

Let us do the work in figure out the problem.....

**Comment by coatsy35** [comment]
Sorry about the call stack errors. Was using a save with every mod I have. Needs tidying up. On my todo list to eliminate them all!

I am describing the radius but I believe I am thinking offset perhaps. When it turns it moves over to far towards the ploughed land so when it pulls straight it has too far to come back. You can see from the pictures but I’m not explaining it very well. 

Thanks for looking.

**Comment by pvaiko** [comment]
I understand that the turn we generate is not optimal, but apart from that, I remember having issues with this plow: it takes ages until it rights itself out and moves to the proper position, it is being dragged half-sideways way too long after a turn. Not sure what causes this, just the geometry or something is wrong with it, I think it does the same thing when pulling manually and you start with the wrong angle.

**Comment by Tensuko** [comment]
With tight turn off (my test was set to 1) and 5.8m instead of 5.9m it was super clean. Maybe even with 5.9m but for that I have to do more testing without tight turn.

**Comment by coatsy35** [comment]
> With tight turn off (my test was set to 1) and 5.8m instead of 5.9m it was super clean. Maybe even with 5.9m but for that I have to do more testing without tight turn.

What do you mean by tight turn?

**Comment by coatsy35** [comment]
> I understand that the turn we generate is not optimal, but apart from that, I remember having issues with this plow: it takes ages until it rights itself out and moves to the proper position, it is being dragged half-sideways way too long after a turn. Not sure what causes this, just the geometry or something is wrong with it, I think it does the same thing when pulling manually and you start with the wrong angle.

It's due to wheels staying on the same spot when the tractor turns it's radius IMO, the turn radius for that plough means that when it comes out of work, it pivots exactly around the wheels if you watch it. The wheels - therefore the plough is too near the existing work after the turn, the wheels on larger ploughs are further towards the rear of the plough, which means they need to move further away from the work in the turn before ploughing recommences (over by the relative offset of the wheels/pivot point when in work I think?)

**Comment by Tensuko** [comment]
> > With tight turn off (my test was set to 1) and 5.8m instead of 5.9m it was super clean. Maybe even with 5.9m but for that I have to do more testing without tight turn.
> 
> What do you mean by tight turn?

Thats code internal and was only for pvaiko

**Comment by Tensuko** [comment]
> > I understand that the turn we generate is not optimal, but apart from that, I remember having issues with this plow: it takes ages until it rights itself out and moves to the proper position, it is being dragged half-sideways way too long after a turn. Not sure what causes this, just the geometry or something is wrong with it, I think it does the same thing when pulling manually and you start with the wrong angle.
> 
> It's due to wheels staying on the same spot when the tractor turns it's radius IMO, the turn radius for that plough means that when it comes out of work, it pivots exactly around the wheels if you watch it. The wheels - therefore the plough is too near the existing work after the turn, the wheels on larger ploughs are further towards the rear of the plough, which means they need to move further away from the work in the turn before ploughing recommences (over by the relative offset of the wheels/pivot point when in work I think?)

Thats only for that plow and that turn radius.
Thats too much set for this exact tool.
Let us figure it out and find a solution.....

**Comment by coatsy35** [comment]
> > > I understand that the turn we generate is not optimal, but apart from that, I remember having issues with this plow: it takes ages until it rights itself out and moves to the proper position, it is being dragged half-sideways way too long after a turn. Not sure what causes this, just the geometry or something is wrong with it, I think it does the same thing when pulling manually and you start with the wrong angle.
> > 
> > 
> > It's due to wheels staying on the same spot when the tractor turns it's radius IMO, the turn radius for that plough means that when it comes out of work, it pivots exactly around the wheels if you watch it. The wheels - therefore the plough is too near the existing work after the turn, the wheels on larger ploughs are further towards the rear of the plough, which means they need to move further away from the work in the turn before ploughing recommences (over by the relative offset of the wheels/pivot point when in work I think?)
> 
> Thats only for that plow and that turn radius. Thats too much for only this exact tool. Let us figure it out and find a solution.....

Thank you. I guess there is no way to tell how far along the length of an implement the ground contact point is and then alter the turn radius for it, if it's longer than a certain length? I guess it works for the Lemken as it's "relatively" short so it's turn does not need to be as offset and isn't really noticeable. 

Thank you for looking though

**Comment by pvaiko** [comment]
>  I guess there is no way to tell how far along the length of an implement the ground contact point is 

We know that, is logged as the "tow bar" length if the AI Driver general debug flag is enabled.

**Comment by coatsy35** [comment]
@pvaiko Does anything you have done on the upcoming update help/fix when entering work on the angled bits? Is it possible for the tractor to recognise it's on an angle and travel further down the field before turning back on itself to the next pass? as turning as per a straight end is no good and doesn't work with long trailed kit either. 

![fsScreen_2024_04_06_18_10_03](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/e84ff0e7-ff64-4cff-8625-6e13d0462a7d)
