### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3182]
Noticed this a few times, just managed to capture it with log on today. Not sure why it happens. It just fires a bit of chaff at the trailer, then stops. It physically won't unload until the trailer gets right next to the header driven manually. I had three unloaders on this job, perhaps it was due to that? although there were no others in the field at the time.

**Steps to reproduce**
NH FR920 Mod Forager and Giants JD 7810

**Actual behaviour**
The JD 7810 with Marshall trailer will not unload from the forager. The same trailer on a 4220 JCB Fastrack will unload

**Expected behaviour**
Tractor and Trailor unload forager

**Screenshots**

![fsScreen_2024_03_30_22_18_44](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/b9464346-f399-4cbd-b118-8b10f9f2dcb5)
![fsScreen_2024_03_30_22_19_22](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/840b8d52-3f78-422e-8d6d-644e17998659)

Had to drive far forward just to the side of the header for it to target the trailer and I drive manually.
![fsScreen_2024_03_30_22_19_57](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/365cf5fd-f112-4d1c-ba09-50084028da1d)

Also noticed that the unloader drivers very close to the forager with wide maize headers on. Pictures of CP driving tractor very close to a forager with a wide header (does the same on all wide giants maize headers), then a picture of it driving further away with a narrow header. Surely it should drive outside the width of the header just like IRL and like combines do?

![fsScreen_2024_03_30_16_27_32](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/f334c527-07a4-4df8-84d8-1d3731f1fb76)

![fsScreen_2024_03_30_16_27_32](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/d66006fc-0124-463a-b92b-f473a3a30114)

**Courseplay version**
Version used: 

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14813490/log.txt)

**Comment by Tensuko** [comment]
Giants system. Not ours.
Wont fix.

**Comment by coatsy35** [comment]
> Giants system. Not ours. Wont fix.

Are you saying it’s a known issue with their 7810?
