### ISSUE TITLE
[Question] I can't do stuff (?)

### ISSUE THREAD

**Issue by Sahilnijjar11** [Courseplay/Courseplay_FS22#3184]

**Comment by coatsy35** [comment]
Press delete on your keyboard?

**Comment by Tensuko** [comment]
First, don't write in capslock
Second, the headling is not to write the question in it.
Thrid, More information then just I can't do XY....
Did you read the ingame help?
Do you have CP correctly installed?
Attach your logfile. Read here how to do this: https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Sahilnijjar11** [comment]
No its open the mini ui.

**Comment by Tensuko** [comment]
If you can't give us a description what is not working, no one can help you.
Step by step, what do you try to do and what does not work, also attach your logfile.

https://github.com/Courseplay/Courseplay_FS22/wiki
