### ISSUE TITLE
[Question] How to switch Courseplay modes while utilizing a multi-implement/trailer?

### ISSUE THREAD

**Issue by farmingsimman** [Courseplay/Courseplay_FS22#3185]
Hi, I am using a lizard tandem trailer to be able to pelletize straw in conjunction with a loading trailer. I do this by hooking up the lizard tandem trailer to my tractor, and hooking up a pelletizer and loading trailer next to it, to the tandem trailer. From here, I'd ideally like to copy the course from a wind rower, which I can, and paste it to the tractor to be able to use the pelletizer to pelletize the straw swath. However, when connecting the loading wagon with the pelletizer, courseplay seems to default on a combine/transport mode. 

Is there any work around or way to manually make it to a regular course mode i.e - like I'm just running a baler?

Thanks. 
![image-3](https://github.com/Courseplay/Courseplay_FS22/assets/165847494/040b9178-59f8-43ab-81fa-3d5b67796a1d)

**Comment by Tensuko** [comment]
That wont work and will not be fixed as it make our system way to complicated. Also like this you will have problems with the pipe.
Why not use a normal combine unloader with a small trailer? One tractor drives the premos and one the trailer, just make the trailer small enough to fit under the pipe
