### ISSUE TITLE
Beetroot harvesting: Harvester doesn't call refueler

### ISSUE THREAD

**Issue by Dewey3105** [Courseplay/Courseplay_FS22#319]
**Actual behavior**
Harvester (=Claas Arion 660+Grimmer Rootster604+Grimme FT300) is harvesting beetroot on Hipcreek no. 75. As soon as Rootster is filled up with 100% it stands still but doesn't opens the pipe. Has to stop helper and do it manually.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.0.11

**Map**
Hipcreek

**Vehicles/ implements involved**
No, all contract rental vehicles

**Relevant script mods*
Autodrive 2.0.0.2
![Bild1](https://user-images.githubusercontent.com/96864667/147880261-df545bef-a7b2-4891-b4df-e103d48c13c5.png)

**Comment by Tensuko** [comment]
This is not officially supported yet.
It works randomly due to pipe open, pls wait untill we work activly on this.
Thanks you :)
