### ISSUE TITLE
[BUG_SP] Turning on Slurrytanker right after launching CP, not after unfolding boom

### ISSUE THREAD

**Issue by S-eler** [Courseplay/Courseplay_FS22#3196]
**Steps to reproduce**
spreading digestate with Autodrive and Courseplay. Plan auto drive route (field-enty and fill-point), plan course play, launch worker.
**Actual behavior**
After emptying slutty tanker, course play is turning on Autordrive, autodrive than run to fill point, refill tanker, and drives to field, where courseplay worker take action. Unfortunately, both CP and AD are not turning of slurry tanker (just folding boom). AD is able to drive with full speed, but just after transition from AD to CP, CP is limiting driving speed to 16kmph (limit during spreying). And is driving with this speed to the point it ended previous round.

![cp slurry](https://github.com/Courseplay/Courseplay_FS22/assets/121870418/5ccce738-8c6a-4e0b-9a9c-6d172522c409)

**Expected behavior**
CP driver will turn off slurry tanker if not spraying at given moment, and turn on  while unfolding booms - in this way he can drive with full speed to the middle-starting point. It's a big difference on big fields.

**Courseplay version**
Version used: v7.4.1.1

**Map**
western wilds, but problem exist on all maps

**Vehicles/ implements involved**
InGame slurry tankers - for 100% involving Samson PG II 35 with SBH4 36 boom, but also on PFW 180000 Maxine Plus (where boom is integrated with tanker)

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Thats a Giants Issue and Giants does refuse to fix this.
We can't fix that without destroying other stuff, we did try that (AutoDrive as well).

Won't fix.

**Comment by S-eler** [comment]
Ok, I understand. Just strange that AD is capable of driving with full speed with tanker on, and CP not - I was assuming that this somehow can be manages. Pity. Thanks for response!
