### ISSUE TITLE
Forage And Logging Questions? [Question]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3199]
Firstly i would like to ask if The feature for the Forage unloader to dump directly into a forage bunker will be implemented?
 
 Secondly will the be ANY features for logging like some listed below?

 Tree Harvesters
 Stump Grinder that targets stumps
 Tree Planter
 For wheel loaders using the claw to transport/bundle long logs together and maybe dump them into a log trailer
 for the claw loaders in the wood working section, using the said claw automaticly to load in to the back of its self
 
 or just a load and deliver logs function for the logging trucks

**Comment by Tensuko** [comment]
> Firstly i would like to ask if The feature for the Forage unloader to dump directly into a forage bunker will be implemented?

Maybe at some point, but not any time soon.

Logging will never be implemented, logs are way too dynamic.
Since loading is only by autoload and street drive, this is not part of CP Jobs, Maybe AD can implement an autoload log transport system.
