### ISSUE TITLE
Combine Unloader handover to AutoDrive when using Auger Wagon[Question]

### ISSUE THREAD

**Issue by wakka79** [Courseplay/Courseplay_FS22#3202]
Hi team, 

Some help required please. I am using multiple auger unloaders on multiple harvesters on very large fields (Western Australia x16 map) I cannot for the life of me make the unloaders work well and find the path across the paddock when full to where my autodrive trucks wait on the side of the field. 

Is there anyway that you could make the Combine Unloader handover to Autodrive when full so that they can utilise the field paths that I have on the field boundries?

**Comment by Tensuko** [comment]
Nope, will not do that.
Auger will have no handover to AD.
