### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by asusv8** [Courseplay/Courseplay_FS22#3203]
**Steps to reproduce**
server wont start

**Actual behavior**
the server errors out saying that /scripts/specializations/CpVehicleSettings.lua:454: bad argument #1 to 'min' (number expected, got nil)

**Courseplay version**
Version used: 7.4.1.1

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible. https://pastebin.com/9cPbLim8

**Dedicated server or local hosted server**
Dedicated server yes/no ? yes local host

**Comment by Tensuko** [comment]
Available mod: (Hash: 3e3dbe4a880a31976c0cb19cefb55669) (Version: 7.4.1.1) fs22Courseplay

don't know what you did and from where you have that Version.

Use the original release from our release side!
https://github.com/Courseplay/Courseplay_FS22/releases

A mod conflict can also be a problem, but first try the official release.
