### ISSUE TITLE
Unloader refuse to go faster than 6mph.   Unloader call percent does not function.

### ISSUE THREAD

**Issue by mountainboomer** [Courseplay/Courseplay_FS22#3204]
I have tried multiple auger wagons and multiple tractors and after a while they all refuse travel any faster than 6mph.

I have also set the call unloader to many different levels and the unloaders seem to ignore it.  The unloaders do not move until 95 percent.

I am using a temporary course for the harvester.  Move the combine helper (unloader?) to the field.  Select the field.  Courseplay says combine.  I hit the arrow to make it green

**Comment by Tensuko** [comment]
Use our template and fill in all requested informations in order to help you.
