### ISSUE TITLE
Combine helper (unloader) drove in to deep water multiple times.

### ISSUE THREAD

**Issue by mountainboomer** [Courseplay/Courseplay_FS22#3205]
Havesting a field with a pond in the middle.  Harvester circled it properly.  Unloader decided the fastest route with through the middle of the pond requiring reset.  Happened multiple times.

**Comment by mountainboomer** [comment]
Single player.  Not sure how multi got tagged.

**Comment by Tensuko** [comment]
Same here, use our template!
