### ISSUE TITLE
[Feature] kürzeste Seite auswählen beim Kurs generieren

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#321]
**What is the problem this feature/enhancement solves?**
bei manchen Kursen kann es sinnvoll sein, die Kurse entlang der kürzsten Seite zu generieren. z.B. wenn die Maschine einen so hohen Wendekreis hat, dass in längsrichtung Hindernisse (Bäume o.ä.) im Weg sind

**Comment by Tensuko** [comment]
Verstehe ich nicht.
Hast du ein konkretes Beispiel mit einem Bild oder einer Zeichnung ?

**Comment by RealNeo80** [comment]
ich möchte den Kurs in Pfeilrichtung generieren, da ich sonst mit dem Titan18 z.b. in den Bäumen links hängen bleibe, wenn ich automatisch oder länge Seite generiere

![image](https://user-images.githubusercontent.com/8066324/147886721-c75b9100-4ff5-4127-8877-27600a4f1e5d.png)

**Comment by Tensuko** [comment]
#139
