### ISSUE TITLE
[BUG_MP] LUA Error 1091 Ropa Maus cant be unloaded by CP/AD Driver

### ISSUE THREAD

**Issue by TschecheNr1** [Courseplay/Courseplay_FS22#3210]
We are playing on a dedicated Server running CP Version 7.4.1.1. and get the Error: 
"D:/home/sid_4450564/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyUnloadCombine.lua:1091: attempt to call method 'hasAutoAimPipe' (a nil value)
2024-04-24 19:50 Error: Running LUA method 'update'."
![LUA Fehler 2](https://github.com/Courseplay/Courseplay_FS22/assets/168019635/040c4c97-c889-4a0d-8a83-b47deb5431be)
![LUA Fehler 1091](https://github.com/Courseplay/Courseplay_FS22/assets/168019635/003eb40c-a297-460a-b452-6c8bcf1fa77a)

This error occurs when trying to unload the Ropa Maus with an automated CP Driver. It does not depend on Field position or which Vehicle is used for the Unloading process. The Driver cant find the pipe of the Maus and is always trying to create a course, which causes massive problems in performance including  complete Servercrash.

**Comment by regs1980** [comment]
The same problem will be solved with the next version.
https://github.com/Courseplay/Courseplay_FS22/issues/3193
