### ISSUE TITLE
[Question] APV spreader not working with CP

### ISSUE THREAD

**Issue by dcisionmusic** [Courseplay/Courseplay_FS22#3214]
Hey, I´m just curious, if there is an option, that if I use the Köckerling Vector for cultivation, to use the APV spreader for sowing catch crops at the same time. If i start the CP helper, it starts cultivating, but turns off the APV spreader. Is there a fix for that, or a setting to fix this?

**Comment by Tensuko** [comment]
I don't even know what tool that is...
Tool Name, basegame or mod ? etc...

**Comment by dcisionmusic** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=226029

It´s a cultivator which has the option to sow catch crops at the same time.

**Comment by Tensuko** [comment]
This active ? (seed option)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/538f4518-481a-44e1-b60b-3dfe0838c9c6)
It is in the vehicle settings.

**Comment by Tensuko** [comment]
Works just fine
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/28fe0a3c-4d65-4b90-a0e0-faabb0c44ef0)

**Comment by dcisionmusic** [comment]
That was what I´ve been searching for. Didn´t see it before. Thank you :)
