### ISSUE TITLE
More effecient farming[Question]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3216]
Will there be a way to que fields for a combine and simmilarly will there be a way to pair an unloader with a combine

**Comment by Tensuko** [comment]
Won't do that.

**Comment by coatsy35** [comment]
> Won't do that.

Why that? Is it too complicated? It’s needed for large maps and especially forage harvesters. Are you considering it for FS25? Would be good to see a precall waiting near the combine and then when that unloader has filled, the next unloader is called nearer. Especially important for forage harvesters, but equally so for combines and earth fruit harvesters on bigger fields.

curious really as to why this is off the cards

**Comment by Tensuko** [comment]
We dont want to.
More reason is not needed.
You can programm that and make a pull request then we see if we can add your feature :)
