### ISSUE TITLE
[BUG_SP] Still seeing bale collecting no path found occasionaly

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3218]
Thought you'd want this log as there are still issues with bale collecting some times. 

**READ FIRST**

**Steps to reproduce**
Tractor and bale collector

**Actual behavior**
Occasionally the bale collector has no path found when it is in fact near a bale and still a good amount in the field.

**Expected behavior**
Collect the bales

**Screenshots**
![fsScreen_2024_04_29_22_28_39](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/d1a682c4-60a7-4aa4-a2d5-543bf608ad96)

**Courseplay version**
Version used: 7.4.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/15155233/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Adjusted the offset?

![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/16c9e822-16c2-437f-a0e3-2586037f2935)

**Comment by coatsy35** [comment]
I did try a bit, I'll run it for longer wit ha larger offset and report back

**Comment by Tensuko** [comment]
I take it as solved, as this is mainly the problem.
