### ISSUE TITLE
4WD Tractors CP: silo work only 7.4.1.2

### ISSUE THREAD

**Issue by jdld053** [Courseplay/Courseplay_FS22#3219]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
Latest version of CP has all my 4WD tractors in CP: Silo Work and cannot get in Fieldwork mode
**Steps to reproduce**
When I create a course now with a 4wd tractor, will not do field work. I have 5 tractors with same issue. The front wheel assist tractors (smaller) do not have issues. I can go back to previous version of CP and work just fine.

**Actual behavior**
Will not sow or plant crops or cultivate fields in Silo work mode

**Expected behavior**
Expect Big tractors to drive CP: fieldwork with big drills and cultivators 

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/47405552/c25298dd-f15a-40cb-b2fa-399073665f4e)

**Courseplay version**
Version used: 7.4.1.2

**Log**
Do not have one

**Map**
Lincoln Creek

**Vehicles/ implements involved**
Which vehicle or implement? 9RX 640, 9R 570, CIH 715, 620, 580
Mod yes, but as stated, will work with previous CP versions

**Relevant script mods**
Mods like Autodrive or VCA and so on.
None

**Comment by Tensuko** [comment]
> **Log**
> Do not have one

https://github.com/Courseplay/Courseplay_FS22/wiki

Will check that anyway but ALWAYS post a log....

**Comment by Tensuko** [comment]
No problem selecting fieldwork with 4WD Tractors.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/e65cf5ba-cbdf-413b-bef8-306c95e1c190)

**Comment by Tensuko** [comment]
But you know you can click on the "silo work" to toggle it? Did you try that?

**Comment by Tensuko** [comment]
Can't follow any of your issues.
@regs1980 your issue seems completly different, pls don't mix it up, rather make an extra one, thanks.

**Comment by Tensuko** [comment]
This one from modHub also works fine.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/a2957a57-bf02-431e-8bbf-56f63b64b835)

If you mod is from any other source, no support will be given, sry!
If modders can't stick to Giants standarts, it is not our problem, we can't support everything....
