### ISSUE TITLE
Mini Hub not displaying

### ISSUE THREAD

**Issue by Nateoclock83** [Courseplay/Courseplay_FS22#3221]
"Hi there! I was playing earlier and everything, including the mini hub, was working perfectly. I saved my game and exited as usual. However, a few hours later when I returned to play again, the mini hub wouldn't activate with the right-click. I can still hire drivers through the main menu, but not from the mini hub. Has anyone else encountered this problem or know how to fix it? I've already tried reinstalling the mod, but it didn’t resolve the issue.

**Map**
The Missouri River Bottom

**Comment by Tensuko** [comment]
Go into the modSettings folder (same location as mods folder)
Inside is a courseplay folder, there should be a courseplay settings file with a HUD position written in it.
Delete the line and save it. The hud should appear again in the default position.

Don't know when and how it happens that the HUD moves outside the screen. Super rare bug.

**Comment by Nateoclock83** [comment]
Hi Tensuko,

Thanks for your input. I’ve been searching extensively for the mini hub position coordinates in the config files and even tried deleting values that I thought were the correct ones, but it turns out they weren’t. I’m usually quite adept at navigating these files, but I can’t seem to find the correct spot for the hub position in the folder. Here is the current file I'm working with, which I downloaded from the official site.
[Courseplay_FS22-7.4.1.2.zip](https://github.com/Courseplay/Courseplay_FS22/files/15162951/Courseplay_FS22-7.4.1.2.zip)

**Comment by Tensuko** [comment]
Download only from here:
https://github.com/Courseplay/Courseplay_FS22/releases
FS22_Courseplay.zip

**Comment by Nateoclock83** [comment]
I went ahead and deleted my course play files and downloaded it from the link your provided and tested and still don't have the mini hub?

**Comment by Tensuko** [comment]
Attach your logfile pls.
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Nateoclock83** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/15165580/log.txt)

**Comment by Tensuko** [comment]
There are a lot of Errors in your log, also some that directs to basegame files.

But anyway, CP looks okay.
So you sit in a tractor and click right mouse click or del key and no hud comes up?
Also no mouse cursor?
That actually can't be unless you have a mod conflict with anything.
Try a clean savegame with only CP active.

What you also can do is delete the CP folder in modSettings folder....
I will check that later if there is some bug when you never had CP running and this is your 1st version or something like that.

**Comment by Tensuko** [comment]
No problems with a fresh settings.xml from CP.
Must be something on your side.

**Comment by Nateoclock83** [comment]
I tried a new save game with only course play installed and still get nothing. Now I don't even get the mouse cursor. But I still get the menu when I toggle "delete" key

**Comment by Tensuko** [comment]
Thats nearly impossible.
Checked your keybinds?

**Comment by Nateoclock83** [comment]
![image](https://github.com/Courseplay/Courseplay_FS22/assets/168501313/742b3742-0ce1-45c3-a920-13af75061301)

**Comment by Nateoclock83** [comment]
Figured it out! It looks like the gamepad-friendly hub was activated in course play settings by mistake. I've deactivated it, and now the mini hub is appearing as it should. I really appreciate your help and patience with this.

**Comment by Tensuko** [comment]
Oh okay! Gald it works now :)

**Comment by AgroWillem** [comment]
Got today the same issue: gamepad-friendly hub was activated. I de-activated it and it works again. Thanks!
