### ISSUE TITLE
[BUG_SP] Forage harvester + wagon gets stuck in turns

### ISSUE THREAD

**Issue by eniac1986** [Courseplay/Courseplay_FS22#3223]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a forage harvester course on a cornfield. Let courseplay handle the forage wagon tractor. 

**Actual behavior**
The forage wagon drives close enough to the harvester to collect the material at least on a straight part of the course.
But in every sharp turn the forage harvester stops. it seems like the forage wagon is just a little bit too far away. 
but if i manually drive the forage harvester and let courseplay handle the wagon it works just fine. if seems like the required distance from the harvester to the wagon seems to be messed up. 

**Expected behavior**
the harvester is supposed to keep on going if the wagon is in range.

**Screenshots**
![Bildschirmfoto vom 2024-05-01 17-43-27](https://github.com/Courseplay/Courseplay_FS22/assets/67465768/bf7e658c-af5b-4d1a-9048-203231ef9b97)

**Courseplay version**
Version used:  7.4.1.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/15178714/log.txt)

**Map**
HobosHollow_4x

**Vehicles/ implements involved**
Which vehicle or implement?
Claas 980G
Fendt 926 Vario
Krone TX 560 D

Mod yes/no ?
yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive, VCA

**Comment by Tensuko** [comment]
Did you configure the long pipe for the Claas harvester? If yes, try the short one.
Sounds wrong, but there is a reason behind it, a bit too complicated to explain....
throw distance, rotation limits and stuff.... trust me :)

**Comment by eniac1986** [comment]
With the standard length pipe, the bug is gone. 
Thanks for the quick answer. :D
