### ISSUE TITLE
Tela sobreposta do AD - AD overlay screen [BUG_SP]

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS22#3229]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Conforme imagem abaixo, voces podem notar que o hud do AD, nao some quando abrimos a tela do CP, poderiam verificar pra nos esse detalhe, pois sempre temos que estar movendo pra poder ver as opcoes, e nao é somente nessa tela do CP que isso ocorre. Agradeço.

As per the image below, you can notice that the AD hud does not disappear when we open the CP screen, could you check this detail for us, as we always have to be moving to be able to see the options, and it is not only on this CP screen that this occurs. I thank.

**Screenshots**

![Captura de tela 2024-05-05 092512](https://github.com/Courseplay/Courseplay_FS22/assets/8292001/1ca8f9cd-6fd4-43df-abd4-9f65d22cbb49)

**Courseplay version**
7.4.1.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/CourseGenerator/files/15213017/log.txt)

**Map**
Map played on.

Qualquer mapa.

Any map.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Not a bug.
Not our problem.
We will not force close the AD screen.

**Comment by erksartori** [comment]
Concordo que nao seja um bug, e nenhum momento eu disse que seria um problema de voces, eu so gostaria que voces verificassem como pode ajudar nesse caso. pra ficar melhor pra ambos. 

I agree that it is not a bug, and I never said that it would be your problem, I would just like you to check how it can help in this case. to make it better for both.
