### ISSUE TITLE
[BUG_SP] Worker doesn't stop at End of Course.

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#323]
It doesn't happen consistently so it's difficult to reproduce. It didn't matter this time but previously it happened with a cultivator driving into a seeded field with the implement down. You can see it still thinks it's following a path in the first screenshot and in second is where it stopped (and you can see the mulched grass behind).

**Courseplay version**
Version used: V7.0.0.11 and previous versions

**Log**
(right at the end)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7799589/log.txt)

**Map**
Elmscreek

**Vehicles/ implements involved**
Nothing modded, I've seen it with the 6m TMC Cancela mulcher and the Kompaktomat 1570 cultivator.

![fsScreen_2022_01_02_19_18_00](https://user-images.githubusercontent.com/30246276/147885743-1127900b-c5d9-4e2d-9758-bae9b4b2aac5.jpg)
![fsScreen_2022_01_02_19_18_07](https://user-images.githubusercontent.com/30246276/147885754-13a02002-2385-45fa-a454-4125cf492928.jpg)

**Comment by Tensuko** [comment]
One more Headland, maybe also skip rows ?

**Comment by ph1go** [comment]
> One more Headland, maybe also skip rows ?

Two headlands is fine for turning for the interior rows. It does everything perfectly in the field, it just carries on in a straight line for ~30m at the very end of the course. It's like it just doesn't realise the course has finished.

**Comment by Tensuko** [comment]
So the problem is only he doesn't stop at the stop point ?

**Comment by ph1go** [comment]
> So the problem is only he doesn't stop at the stop point ?

Yes, exactly. The field work is perfect, you can see the stop point in the screenshots and that he is past it.

I found another screenshot I took yesterday (but no log) of it also happening with the big Amazone seeder...

![fsScreen_2022_01_01_18_40_23](https://user-images.githubusercontent.com/30246276/147887015-8ded6198-617c-4909-8abd-f685d2ac2c39.jpg)

**Comment by Tensuko** [comment]
Can't be the tool. Must be somethiing else what happens there.
Would like to know if that happens without the mods that plays with speeds and stuff.

**Comment by ph1go** [comment]
Hmm, like AutoDrive? I don't know which other ones out of the following could interfere...

FS22_advancedGameplaySettings
FS22_AIVehicleExtension
FS22_AutoDrive
FS22_cultivatorFieldCreator
FS22_EnhancedVehicle
FS22_flieglDPWpack
FS22_Great_KrampePack
FS22_InfoMessageHUD
FS22_real_clock
FS22_TO_sks30_150
FS22_VehicleCameraAutoZoom
FS22_VehicleExplorer

AIVehicleExtension is disabled in all implements (even combines now Courseplay is out), EnhancedVehicle can lock differentials and stuff but nothing to do with speed.

**Comment by ph1go** [comment]
[Here's a video](https://streamable.com/ymqauq) of it just happening again... You can see him "working" straight past the stop point.

**Comment by Tensuko** [comment]
> EnhancedVehicle can lock differentials and stuff but nothing to do with speed.

Still can influence the Vehicle behavior.

**Comment by ph1go** [comment]
[Here's another video](https://streamable.com/btdid4), he went much further this time than I've seen before. I'm rolling a field at the moment, I'll reload with that mod disabled and see what happens (although if it doesn't do it, it won't be conclusive because it was already not doing it every time...).

**Comment by Tensuko** [comment]
But when one of those Mods CAN cause this, we need to know it.
Else we can't do anything and look at our code for hours and can just say, this can't happen...

**Comment by pvaiko** [comment]
That's our bug...

**Comment by pvaiko** [comment]
Should work with the latest main branch. 

When you load a savegame, check the end of your courses. If the Stop sign is not where it should be (for instance on the neighboring field) you have to regenerate that course.

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.

**Comment by ph1go** [comment]
He fails to reach the end of the course now. :) I scrapped all the old courses so this is a new one, made with v7.0.0.12.

I see `2022-01-04 10:17 :52 [dbg4 lp177570] 9620 RX: WORKING: adding offset (-13.1 front marker) to make sure we do not miss anything when the course ends` in the log (line 48755), but...

![fsScreen_2022_01_04_10_26_28](https://user-images.githubusercontent.com/30246276/148037863-836c2a70-c6ea-4870-8361-3fd4e8b4f664.jpg)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7806646/log.txt)

**Comment by pvaiko** [comment]
Oops. Looks like our QA department needs to improve :). This last push should now really solve it...

**Comment by Tensuko** [comment]
> Oops. Looks like our QA department needs to improve :). This last push should now really solve it...

Thank you :D 

Pls try 7.0.0.13
Reopen if Issue persists.
