### ISSUE TITLE
[Feature]Save custom routes, as under FS19

### ISSUE THREAD

**Issue by BoxerHUN** [Courseplay/Courseplay_FS22#3232]
Hello.
I would like to ask if it will be possible to save traffic routes (movements on the farm, marching to fields, etc.) in the future? In my opinion, AutoDrive can only partially bring the knowledge and precision of CoursePlay.

My request in this regard is to be able to save individual routes, as under FS19, CoursePlay v6.5

Thanks.

**Comment by Tensuko** [comment]
Wont add this.
