### ISSUE TITLE
[BUG_MP]CP behält den eingestellten Arbeitsmodus nicht, nach Wiedereintritt auf einem Server

### ISSUE THREAD

**Issue by regs1980** [Courseplay/Courseplay_FS22#3233]
CP behält den Arbeitsmodus nicht bei im HUD. 

https://drive.google.com/file/d/1GmbVX3hgA8OJ3bQ96GzmlLRlvpvOlAS-/view?usp=drive_link

https://drive.google.com/file/d/1fwPI735it1ni_hqgzDOAI8hKzi-ZLV1G/view?usp=drive_link

[log_2024-04-30_07-39-26.txt](https://github.com/Courseplay/Courseplay_FS22/files/15231757/log_2024-04-30_07-39-26.txt)

Selbst wenn man den CP Helfen abschaltet, muss man erst das angehängte Gerät abhängen und wieder anhängen, sodas CP den tatsächlichen Arbeitsmodus für das Gerät wieder erkennt.
Auch versuche den Modus zu ändern, mit einem Maustastendruck ist nicht möglich, es muss erst abgehängt und wieder angehängt werden. 
Sehr gut verdeutlicht sich das beim Ballensammelwagen, dieser arbeitet zwar die Aufgabe ab, die eingestellt worden ist, aber man kann halt nichts einstellen während dessen, da der richtige Modus nicht im HUD einstellbar ist.

**Comment by Tensuko** [comment]
Kannst du den Branch mal ausprobieren ?
https://github.com/Courseplay/Courseplay_FS22/pull/3238

**Comment by regs1980** [comment]
Fix behebt den Fehler noch nicht.

https://drive.google.com/file/d/1C7sk-oC3fnUMiTfLfgvVwFV3KCssqm4j/view?usp=drive_link

**Comment by regs1980** [comment]
Nein, ist unverändert.

**Comment by regs1980** [comment]
Leider auch noch nicht.

https://drive.google.com/file/d/1gCoAKKlHkS-fhMgSD5HWmYu6d6dDWXMR/view?usp=drive_link

[log_2024-05-20_14-07-49.txt](https://github.com/Courseplay/Courseplay_FS22/files/15377192/log_2024-05-20_14-07-49.txt)

**Comment by regs1980** [comment]
Auch hier https://github.com/Courseplay/Courseplay_FS22/pull/3238/commits/980b413ba883e69ddf2719ba2f601cf421c1763a keiner Verbesserung.
Auch das inaktive Ballensammelwagen Gespann behält nicht die Einstellung, somit wird auch nicht der Offset gespeichert und man muss ihn permanent neu einstellen. 

https://drive.google.com/file/d/1vNBy8kTYSmBxpFp6DoI1kVQwjzIK2I2N/view?usp=drive_link

**Comment by regs1980** [comment]
Wenn es bei euch auf dem Server funktioniert und hier nicht, stelle ich mir die Frage woran es noch liegen kann.

https://drive.google.com/file/d/1VOcLum7oblfBEovxNs7bOcZ1CohEfvkI/view?usp=drive_link

**Comment by regs1980** [comment]
Jetzt wird es langsam interessant, der Ballensammelwagen behält schon mal den Arbeitsmodus, nur nicht den eingestellten Ballen Aufnahme Versatz.
Wender, Schwader und Grubber wechseln aber immer noch den Modus.

**Comment by Tensuko** [comment]
Von Wender schwader und co höre ich jetzt das erste mal...

**Comment by regs1980** [comment]
Die Videos nicht angeschaut?

**Comment by Tensuko** [comment]
Sicher das du die neueste Version hast?
[FS22_Courseplay.zip](https://github.com/Courseplay/Courseplay_FS22/files/15446794/FS22_Courseplay.zip)
Wenn der Fehler wieder auftritt, bitte in die console mal das eingeben:
printVehicleVariable spec_aiFieldWorker.aiImplementList

**Comment by regs1980** [comment]
Habe die Version getestet, selbes Ergebnis im Video.
Auch die Parameter in der Konsole habe ich eingegeben.

https://drive.google.com/file/d/14exj9LJaTSJenLzWjvxUQZTBDh4AMkZ1/view?usp=drive_link

[log_2024-05-26_14-58-08.txt](https://github.com/Courseplay/Courseplay_FS22/files/15447569/log_2024-05-26_14-58-08.txt)

**Comment by coatsy35** [comment]
Is this why in SP when I return to my bale collectors after starting a new save game, they are no longer in collecting mode? or has that been addressed for a future update?

**Comment by Tensuko** [comment]
This should not be the case for SP but I may have a look. It is a stupid timing issue that we have here and we try to find a fix for that.

**Comment by Farmer200** [comment]
Ich kann das auch bestätigen. Ich bin nur im SP unterwegs. Nach dem Neustart ist die Einstellung weg.

**Comment by Tensuko** [comment]
Ok

**Comment by Tensuko** [comment]
@regs1980 kannst du noch mal bei dir auf dem Server den Branch ausprobieren?
-> https://github.com/Courseplay/Courseplay_FS22/pull/3238

**Comment by regs1980** [comment]
Wender, Schwader und Grubber Arbeiter zeigen nach dem Wiederverbinden mit dem Server immer noch Siloarbeit Modus, der Ballensammelwagen, da stimmt der Modus aber der Offset wird nicht gespeichert, den man manuell gesetzt hat.
