### ISSUE TITLE
Please fix the problem with the loader.

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#3235]
Hello dear developers. I have already written about the problem of loading with a loader, where it was previously written that the path was not found, I just seemed to understand what the reason was. When I removed some of the coal, the loader started loading everything and there was no mistake. Will you be able to increase the loading radius or change how much the loader can work with? Thank you in advance.
![Снимок экрана 2024-05-07 160319](https://github.com/Courseplay/Courseplay_FS22/assets/116440748/81422d72-eb80-4768-84f2-7b391ccd27bc)
![Снимок экрана 2024-05-07 160344](https://github.com/Courseplay/Courseplay_FS22/assets/116440748/c65faaf7-b2f4-4d95-a8ac-6eb1f793d546)
![Снимок экрана 2024-05-07 160441](https://github.com/Courseplay/Courseplay_FS22/assets/116440748/279540f9-ed64-44fe-aea0-54352cd2afe9)
![Снимок экрана 2024-05-07 160525](https://github.com/Courseplay/Courseplay_FS22/assets/116440748/8df62734-1d79-417a-8a50-0c28baa23d12)

**Comment by Tensuko** [comment]
As I already said, the map or the strang heap is the problem.
We can not fix that, sry.

**Comment by Tensuko** [comment]
savegame? I may have a final look but no guarantee we can do anything about it.
