### ISSUE TITLE
Problema generazione campo

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3236]
Buonasera,
con il generatore automatico del courseplay mi unisce due campi in 1, per cui seguendo la vostra giuda ho creato il mio campo personalizzato, ora volevo sapere come faccio generare un percorso senza che vengano presi insieme i 2 campi. Allego immagine per chiarimenti
![Farming Simulator 22 07_05_2024 21_37_48](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/0a3c8aa3-2a57-4111-ac35-852e9530dbf2)

**Comment by Tensuko** [comment]
English pls :)

**Comment by Trivelleitor** [comment]
Here the message in English:

Good evening,
with the automatic courseplay generator I combine two fields into 1, so following your guide I created my custom field, now I wanted to know how I can generate a courseplay without the 2 fields being taken together. I attach an image for clarification

**Comment by Tensuko** [comment]
> (global settings, prefer custom field on)

This.

**Comment by Trivelleitor** [comment]
I cannot find this option

**Comment by Trivelleitor** [comment]
I activate the otpion but nothing change. What's the problem?
![Farming Simulator 22 08_05_2024 21_45_06](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/a281a207-f691-4a71-9329-a1512d93977b)

**Comment by Tensuko** [comment]
Seems like marker not inside the blue field line.

**Comment by Trivelleitor** [comment]
Oh, i'll try this evening

**Comment by Trivelleitor** [comment]
I'll try but nothing change:
![FarmingSimulator2022 64bit 09_05_2024 18_59_08](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/f9ab0a9f-e72f-4885-a30e-cc2c15b360b1)

**Comment by Tensuko** [comment]
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/211a72df-0e32-47e3-8821-6f41dbe96272)
Prefer custom field = active (CP global settings)
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/1dede851-743e-469d-b2f5-2aac60df60d0)
Outside the custom field.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/d039109e-42c5-4033-b821-39d22b73b9a6)
Inside the custom field

Works just fine.
Maybe the overlap is the problem?
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/d3d7610d-b30b-4d58-8819-e3ac2aa57cd0)

**Comment by Trivelleitor** [comment]
Idk, you think overlay is the problem?
I'll try

**Comment by Trivelleitor** [comment]
Yea, now work thx for the help
![FarmingSimulator2022 64bit 09_05_2024 20_41_19](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/5e61edd7-faac-4ee1-8ae7-73eacef9fae8)
