### ISSUE TITLE
[Feature] - Einstellen der Überlappung der Standardreihen und des Vorgewendes - Dont know how to say in English

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#324]
**What is the problem this feature/enhancement solves?**
Often the Harvester isn't harvesting exactly the rows

**Describe the solution you'd like**
In the CP-LS19 there was a possibility to make a Overlaying of the up-and-down-rows and the Headland

**Describe alternatives you've considered**
puh ---- don't know how

**Additional context**

**Comment by RealNeo80** [comment]
ist in 7.0.0.11 drin

**Comment by ph1go** [comment]
If you want to the rows to overlap as well, surely you can just reduce the work width a bit when you generate the course so Courseplay thinks the implement is less wide than it really is (so the rows will be closer together).

**Comment by MisterGeniusj007** [comment]
Thank You all so much!
Not ween by using Your great Coursplay!
Sorry!!!!!!

**Comment by Tensuko** [comment]
Seems to be cleared.
