### ISSUE TITLE
Transfer trailer is not emptied[BUG_SP]

### ISSUE THREAD

**Issue by Domi11212** [Courseplay/Courseplay_FS22#3240]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Loaded with forage harvester, then bunkered into a transfer trailer using courseplay.  Use AutoDrive to unload the waiting trailer. The transfer trailer drives to the trailer (also recognizes it as a destination) but does not unload the transfer trailer.

**Actual behavior**
The transfer trailer is not emptied when loaded (with chopped material) with Coursplay.
.

**Expected behavior**
The transfer wagon would have to reload onto the wagon

**Screenshots**
<a href="https://ibb.co/7JfBQg4"><img src="https://i.ibb.co/7JfBQg4/fs-Screen-2024-05-10-17-41-18.png" alt="fs-Screen-2024-05-10-17-41-18" border="0"></a>

**Courseplay version**
Version used: 7.4.1.2

**Map**
Multimap

**Vehicles/ implements involved**
JCB Fastrac (no) + SUW5000 (no) / Claas 960 Terra Trac +Bergmann HTW65 (no)
Mod yes/no ?

**Relevant script mods**
Autodrive

**Comment by Domi11212** [comment]
[[](https://pastebin.com/RhS41GVE)](https://pastebin.com/RhS41GVE)

Here the logs.

**Comment by Tensuko** [comment]
#3198
Will be fixed in the next Release.
