### ISSUE TITLE
Cannot generate field courses 

### ISSUE THREAD

**Issue by Tigger86** [Courseplay/Courseplay_FS22#3243]
Hello,
I have no idea about this game myself.
My son likes to play it and unfortunately he can't generate a course.
I'll post the log here... I hope it helps.
i had to reinstall the game and then reinstalled existing mods.
Please help.
otherwise he will give me hell
[gistfile1.txt](https://github.com/Courseplay/Courseplay_FS22/files/15306225/gistfile1.txt)

**Comment by Tensuko** [comment]
Would need more Informations.
What map, what field, a screenshot of the selected field, etc.

**Comment by Tigger86** [comment]
Okay, sorry  
The map is Hof Bergmann v1.4 
Actually it used to work.
Yesterday I played briefly myself... First it was still there and when I wanted to generate the next field, I could only select silo work.
You can see the field number on the photo.
I also made a short video.

Thanks again [[

https://github.com/Courseplay/Courseplay_FS22/assets/87924122/4db03f14-11ad-4d2f-895c-741c5d9c3842

![20240517_151750](https://github.com/Courseplay/Courseplay_FS22/assets/87924122/cdbcf443-590e-4898-b4fd-df82fd6f52ec)
](url)

**Comment by Tensuko** [comment]
Can not generate a course and not having fieldwork is completly different problem........

What tool is it ?

**Comment by Tensuko** [comment]
Is the header attached?

**Comment by Tensuko** [comment]
Wir können das auch auf deutsch klären,  aber ich brauch halt Infos.
Es gibt übrigens auch eine ingame Anleitung und wenn euch da etwas fehlt an Infos können wir das auch noch nachträglich einfügen...

**Comment by Tensuko** [comment]
Ohne Info kann ich nicht weiterhelfen.... Mache hier zu, man kann aber nach wie vor schreiben.
