### ISSUE TITLE
[Feature] Tool front/rear offset setting

### ISSUE THREAD

**Issue by jjerhub** [Courseplay/Courseplay_FS22#3246]
**What is the problem this feature/enhancement solves?**
When using some tools the effective area is sometimes less appropriate at the point where courseplay thinks it is than somewhere else.   EG Amazone fertilizer spreader sometimes leaving gaps due to the cone shape, or a rock picker with swept arms leaving a gap between where the arms were and where courseplay thought the arms ended.  This would help solve for appropriate settings easier instead of trying to adjust field margin and tool width/offset and other things.  In the case of the rock picker, I'm actually not sure how it's issue could be worked around presently.

**Describe the solution you'd like**
Implement a tool "front/rear offset" such that you can adjust where courseplay is looking for a segment to complete application/use.

**Describe alternatives you've considered**
Setting field margin.  Setting tool width.

**Comment by Tensuko** [comment]
That would throw off so many other things.
Won't do that.
I don't see any benefit in doing that.

Cone shape -> raise late, lower early.
Stone picker maybe the same, not sure if I know what tool you talk about.

Field margin is a side offset, So you rather ran into an issue where you might not had the "right" solution.

**Comment by jjerhub** [comment]
Hopefully this won't re-open the ticket, but I suspect it will, so, sorry.
I still wanted to clarify.

Re: Cone shape, I always use lower early raise late and still have
the issue.  Yes, the stone picker has a cone shape.  I am specifically
using a modded picker for a wider swath, but was having the issue with the
base game stone picker.  The Elho brand stone pickers, are what I've used.
Scorpio 550 and 710 (the modded one).  Honestly, I forgot there was a brand
other than Elho when I was writing the ticket.

I understand that field margin is a zone size change/side offset, but I was
trying to use that and the implement width to cause overlap to alleviate
the issue, but the issue occurs in the center of the machine, so that
hasn't really worked.

Thanks for taking the time to reply to my ticket though.

**Comment by Tensuko** [comment]
You can try headland overlap too.
But if the problem still exists with raise later and lower early, its a mod issue.
it will raise the tool with the end of the work area and lower it with the starts, that means even with a cone shape it will hit the biggest width for the lanes.
