### ISSUE TITLE
Fertilizer Machine gets activated to late on a turn

### ISSUE THREAD

**Issue by Zwox89** [Courseplay/Courseplay_FS22#325]
**Courseplay version**
7.0.0.12

**Log**
https://pastebin.com/nDFY3WLf

**Map**
US

**Vehicles/ implements involved**
Mod No

**Relevant script mods**
Autodrive (But not involved)

![image](https://user-images.githubusercontent.com/96999699/147889983-b3a8645e-e856-42a2-ac0d-348c3ce6a828.png)

Hello!

On the picture, you can see that there are 2 spots where it's not fertilized.
The issue is that the machine gets activated too late. The turn is fine, and he even sets back, but then starts driving without activating the machine.

Edit: It only happend on this side. On the other side of the field it worked just fine.

**Comment by Zwox89** [comment]
![image](https://user-images.githubusercontent.com/96999699/147890684-735c42ec-3249-4cdb-8484-adf1d2e42b0a.png)

Probably the same on this field

**Comment by Tensuko** [comment]
Vehicle options:
Rais and lower implement settings.
Try raise on late and keep lower on late too.
Should work.

**Comment by Zwox89** [comment]
> Vehicle options: Rais and lower implement settings. Try raise on late and keep lower on late too. Should work.

will come back to this when i have time for it prob. tomorrow

**Comment by Zwox89** [comment]
![image](https://user-images.githubusercontent.com/96999699/148122945-21affc0f-c093-4a50-b945-ef7330e635c3.png)
![image](https://user-images.githubusercontent.com/96999699/148122970-2bf9a54f-8397-4c2a-bf0e-4569210253d2.png)

It did not the trick

**Comment by Tensuko** [comment]
hm okay, dann hilft nur headland erst mal.

**Comment by Tensuko** [comment]
Hab es eben mal mit der .20 probiert und anheben auf spät und absenken auf früh.
Sah gut aus, bitte mal testen, sonst wieder aufmachen.
