### ISSUE TITLE
Issue when changing width [BUG_SP]

### ISSUE THREAD

**Issue by Bothamgames** [Courseplay/Courseplay_FS22#3252]
Hello,

I'm having this issue where with the Mower and Wind rower, when I change the working width of the course play to the correct width, and I then start the course play, for some reason the mower and wind rower only do the first few metres then it raises the machinery and carries on the course without using the equipment. 
![1](https://github.com/Courseplay/Courseplay_FS22/assets/13056008/443b4bca-ea21-4a02-8f04-44e9c0fd49be)

**Comment by Tensuko** [comment]
You should just let it run and watch what happens.
Got one headland for the course?
