### ISSUE TITLE
[Feature]Dewulf ZKIVSE abfahren?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3253]
**What is the problem this feature/enhancement solves?**
der Dewulf ZKIVSE ruft keinen zweiten Abfahrer, wenn der gerade zufüllende Kipper fast voll ist,
erst wenn der erste voll ist und wegfährt, setzt sich der zweite vom AD-wartepunkt aus in bewegung
somit hat der ZKIVSE ziemlich lange standzeiten wenn er auf den nächsten abfahrer wartet.

**Describe the solution you'd like**
der zweite Abfahrer sollte ab einem bestimmten Füllstand des ersten Abfahrers zu diesen fahren.

**Describe alternatives you've considered**
ev einen manuellen schalter um den Abfahrer zum drescher fahren zu lassen
(ähnlich dem, mit dem man in CP hud den Drescher-abfahrer wegfahren lassen kann) 

**Additional context**

lg
andreas

**Comment by rohne83** [comment]
Das ist ja im Prinzip das gleiche wie beim Häckseln, auch da wird zur Zeit noch kein zweiter Abfahrer gerufen. Denke mal dass die Jungs das schon auf dem Schirm haben (wurde damals in den Release-Notes zum Häcksler-Abfahrer auch explizit erwähnt dass zZ noch kein zweiter gerufen wird), ist halt wohl eher eine Frage der Priorität.

**Comment by Tensuko** [comment]
Ja, diesbezüglich mehr wie ein Häcksler zu sehen und nciht wie ein Drescher.
Working as intended, siehe changelog.
