### ISSUE TITLE
[Question] Schaufelhöhe abkippen beim Silo laden ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3254]
Hallo CP Team

wieso habt der Telelader bzw Frontlader die Schaufel beim abkippen vom Silo laden so hoch an?

![fsScreen_2024_05_25_07_04_28](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/e90ea53d-0671-4ca5-a709-f11651b46c9d)
![fsScreen_2024_05_25_07_04_30](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/52ee4ebd-5ea9-4362-a43c-47140ac9348b)
![fsScreen_2024_05_25_07_04_32](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ab820433-3d78-4d31-a540-34e94c6825da)
![fsScreen_2024_05_25_07_04_33](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/cd8b8e66-5b61-49c6-a301-eea466b82db5)
![fsScreen_2024_05_25_07_04_35](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/3e94b368-5048-4413-ad22-ed5d8d832487)
![fsScreen_2024_05_25_07_04_38](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/60b96c2f-8b3e-431f-a1f9-f5b10de6ea07)
![fsScreen_2024_05_25_07_04_41](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/a84473e5-6e38-4286-80ee-73aa692eeb0e)
![fsScreen_2024_05_25_07_04_44](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ba735cfe-929c-4feb-9318-7c5929af963e)
![fsScreen_2024_05_25_07_04_47](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/05a48b64-80b8-4a9a-a71c-704d68292c64)
![fsScreen_2024_05_25_07_04_48](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/ae21ab34-c707-4da4-a389-b2ab39fabe2b)
![fsScreen_2024_05_25_07_04_51](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/0144fce1-94b0-426f-8c86-f94320f77c57)
![fsScreen_2024_05_25_07_04_54](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/cc60f75f-ba12-4f68-9f84-1e82f8f2e51a)
![fsScreen_2024_05_25_07_04_59](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/6d94d4bb-cd64-44ec-b0f3-ae53346a5a11)

die exactfillrootnode ist ganz am boden:
![ge1](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/bd2f652b-93d5-4d51-8af2-9dbb7daa9d10)

und auch der aitrigger ist nicht hoch:
![ge2](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/16704285-15fa-403b-a8c0-3abadd462615)

der Telelader müsste nicht so hoch heben, kann man das einstellen, bzw von was hängt die abkipphöhe ab?
dann könnte ich die silotrigger ändern.

lg
andreas

**Comment by Tensuko** [comment]
Höhe überall gleich und nicht jeder trigger ist so niedrig, denke nur mal an BGA Trichter, was die hauptfunktion von dem Modus ist.
Nein ist nicht einstellbar und wird auch nicht angepasst.

**Comment by andreasthu** [comment]
Ah, ok.
Ich hab gedacht die hubhöhe orientiert sich an einer colli vom Kipper oder Abladestelle.
Und nach einem Fehler (in der xml und i3d) der Schaufel und Abkipptrigger gesucht. Aber nichts gefunden.
Also er hebt quasi immer maximum hoch vorm abkippen.
Lg
Andreas
