### ISSUE TITLE
[Question] combine unloader CP - AD Übergabe klappt nicht immer. 

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3258]
Hallo Leute.
Normal, wenn ich den CP Drescher per CP Abfahrer abtanken lasse, schaltet er sobald er voll ist auf AD um, AD sucht sich den AD "Kursring" ums Feld (AD einstellung nähester punkt) steuert den an und fährt zur Verkaufsstelle.
Nun ist es mir schon ein paarmal passiert das der volle CP Abfahrer aber nicht an AD übergibt, sondern in irgendwelchen Kurvenbahnen übers Feld torkelt, und nach einiger Zeit an den AD Kurspunkt zusteuert, an dem er zu beginn von AD an CP übergeben wurde. 
Nur blöd das dort meist ein zweiter Abfahrer wartet, und der CP Fahrer in diesen reinfährt und daher beide blockiert sind. 
Die CP einstellung "zum Startpunkt zurückkehren" ist deaktiviert.
Manchmal klappt die cp-ad übergabe, manchmal eben nicht.
Welche cp Einstellung ist dafür verantwortlich?
(Hab die log vorhin versehentlich überschrieben. Aber es standen keine cp relevanten Daten drinnen.
Beim nächstenmal häng ich sie mit an.)
Lg
Andreas

**Comment by Tensuko** [comment]
CP Abfahrer fährt immer zurück zum Zielpunkt bevor an AD übergeben wird. Working as intended.
Zum Startpunkt zurück hat mit dem Abfahrer nichts zu tun.
Es gibt dafür keine Einstellung.

Warum AD manchmal direkt übernimmt? Kein Plan, vlt weil dann zufällig der Zielpunkt in der nähe ist oder es konnte kein Weg gefunden werden oder sowas, man weis es nicht.

**Comment by andreasthu** [comment]
> CP Abfahrer fährt immer zurück zum Zielpunkt bevor an AD übergeben wird. Working as intended.
---
Das ist aber nicht optimal, 
Da der erste Fahrer ja den AD punkt nicht erreichen kann, da dort ja der zweite Fahrer steht. Somit blockieren sie sich gegenseitig.
Wäre es nicht besser, das AD direkt übernimmt und sich den Weg vom Feld zu der Fanglinie sucht und direkt wegfällt?
So wie z.b. beim Saatgut nachholen?
Somit wird der kürzeste weg vom Feld gesucht, und nicht erst quer übers Feld zum Startpunkt gefahren. 
Lg
Andreas

**Comment by Tensuko** [comment]
Das ist perfekt und wurde sich sogar für Ballen sammeln gewünscht weil AD an Ballen fest hängt. Zudem wird so bei einigen Feldern mit nur einer Ausfahrt kein Rundflug um das Feld gemacht.
Wir haben das auch extra eingebaut und es wird auch so bleiben.

**Comment by Tensuko** [comment]
Und sette dien Zielmarker halt nicht direkt beim AD Punkt dann sind die neuen Abfahrer auch nicht im weg.

**Comment by andreasthu** [comment]
Finde ich jetzt persönlich als falsche Entscheidung.
Mag sein, das es beim Ballensammeln so besser funktioniert
(ich koppel immer den Lizard Ballenschieber vorne an, der richtet die Ballen dann sogar entsprechend aus fürs aufladen, und beim Feld rausfahren schiebt er andere Ballen einfach aus den Weg),
Aber fürs Drescher Abfahren m.M.n der falsche Weg.
Niemand fährt in RL übers ganze Feld zurück zum Startpunkt, wenn wenige Meter neben dem Feld ein Weg ist.
Wäre es möglich eine Auswahl-option zu bekommen, übergabe an AD sofort wenn voll oder erst nach Ankunft am Startpunkt?
So ähnlich wie Düngefunktion bei der Sämaschine, oder Saatoption beim Striegel?
Lg
Andreas

**Comment by Tensuko** [comment]
Nein. Da wird es nichts geben.

**Comment by Tensuko** [comment]
Und nur so als tip von rohne...
Pack den zielmarker irgendwo auf ein anderes Feld, dann hast du was du willst.

Wir werden das aber nicht umbauen, wir haben das aus gutem grund drin. Man kann es nicht jedem recht machen.

Und den mist den man bei AD hat mit 1000 Dingen einstelle wie abstand vom trigger, colli, feldausfahrt etc etc werde ich bei CP nicht zu lassen. Keine unnötigen settings wenn es funktioniert.

Zielmarker weit genug weg vom AD Wegpunkt und du hast keinen konflikt mehr. AD übergabe an CP wartet immer am AD Punkt und AD sollte nach ankunft CP am Zielmarker den nächsten passenden AD WP nehmen und nicht zum ziel fahren.

Davon ab diese ehrenrunden von AD bei dieser Fanglinie gehen mir z.B. auf den Sack... Komplett unnötig einmal um das ganze feld... Kein witz immer wieder gehabt statt den kürzesten weg zur ausfahrt auch wenn er dafür 180° in die andere Richtung gucken müsste.

**Comment by regs1980** [comment]
@andreasthu 

> (ich koppel immer den Lizard Ballenschieber vorne an, der richtet die Ballen dann sogar entsprechend aus fürs aufladen, und beim Feld rausfahren schiebt er andere Ballen einfach aus den Weg)

AD schiebt keine Ballen aus dem Weg, wenn die Kollisionskontrolle an ist, da bleibt dein Gespann lustig auf dem Feld stehen.
Daher hatte ich mir das auch gewünscht, dass CP beim Ballensammelmodus erst zum Zielpunkt fährt, wenn man einen gesetzt hat auf dem Feld oder in unmittelbarer Nähe, bevor er dann an AD übergibt. 

> Aber fürs Drescher Abfahren m.M.n der falsche Weg.

Das ist Quatsch, wenn beide über CP gesteuert werden und der Abfahrer noch nicht an AD übergeben hat, besteht immer noch die Möglichkeit das der CP Fahrer bei Kollision den Stau auflöst. 
Bei AD ist das nicht der Fall, ist AD auf dem Feldrandkurs ein gelockt, besteht keine Möglichkeit mehr eine Kollision aufzulösen, da AD nicht zurückweicht und somit kann es passieren das beide Fahrzeuge ewig stehen und auf einem Server der 24/7 läuft, macht es sich nicht gut, wenn man 5 Stunden später in das Spiel schaut und sieht das AD den Drescher schon im Vorgewende gestoppt hat, weil er ihn nicht rückwärts fahren lassen will, um eine Tasche zu mähen.

Wie schon gesagt den Zielpunkt mehr als 20 m weg vom Feld und schon übergibt CP direkt an AD.

Da AD immer den kürzesten Weg sucht kann, es auch sehr oft passieren, dass er eine extra runde auf dem Feldrandkurs dreht bis zur Ausfahrt, die er für richtig hält.
Das fällt bei CP aus.
Noch was zu AD Feldrandkurs mal löschen und dann auf Standard oder hinter Zielpunkt stellen, da wirst du deine Freude daran haben, da AD ab einer gewissen Entfernung nicht mehr die Auswahl berücksichtigt, wenn ein AD Punkt in der Nähe ist, dann fährt er den eher an, ist da ein Graben oder eine Böschung bleibt AD hängen, herzlichen Glückwunsch gut gemacht.  

> Niemand fährt in RL übers ganze Feld zurück zum Startpunkt, wenn wenige Meter neben dem Feld ein Weg ist.

Doch gibt es, Feldränder sind öffentlicher Eigentum und das kann sehr teuer werden, wenn man die mutwillig zerstört und das macht man, wenn man versucht, mit einem Traktor vom Acker zu kommen.
Auch diverse Gräben, Bäume usw. sind hinderlich für schnell mal vom Acker auf die Straße. 
(RL):
Bei mir auf einigen Feldern stehen selbst die LKWs auf der Vorgewende Fahrgasse zur Erntezeit, weil es bauartbedingt nicht möglich ist, sie am Feldrand zu positionieren.
