### ISSUE TITLE
[BUG_MP] Multipack D14 not collecting bales

### ISSUE THREAD

**Issue by Allerek** [Courseplay/Courseplay_FS22#3260]
**Steps to reproduce**
1. Install Courseplay 7.4.12(didnt check earlier versions)
2. Make bale  using MF1840
3. Attach  Multipack D14 to your tractor
4. Give worker a job to collect these bales

**Actual behavior**
A worker will go to the shop instead of collecting the bales

**Expected behavior**
Just collect the bales

**Screenshots**
-

**Courseplay version**
7.4.12(didnt check earlier versions)

**Client Log**
-

**Server Log**
-

**Player on the server**
1/2

**Dedicated server or local hosted server**
Local

**Map**
Erlengrat

**Vehicles/ implements involved**
MF1840
Multipack D14

**Relevant script mods**
Autodrive installed

**Comment by Allerek** [comment]
Will add logs if it will be really required, just give me a sign.

**Comment by regs1980** [comment]
@Allerek 

Your target point is at the workshop, you have to bring it closer to the field, or you start CP via HUD button, then you only need to set the field point.

**Comment by Allerek** [comment]
> @Allerek
> 
> Your target point is at the workshop, you have to bring it closer to the field, or you start CP via HUD button, then you only need to set the field point.
> 
> ![2024-05-30 21_54_41-Watch Farming Simulator 22 2024 05 30 - 20 30 10 02 _ Streamable – Mozilla Firef](https://private-user-images.githubusercontent.com/13314443/335361293-e023c14c-783a-4001-b8c8-218c9e82a105.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDEzNTAsIm5iZiI6MTcxNzEwMTA1MCwicGF0aCI6Ii8xMzMxNDQ0My8zMzUzNjEyOTMtZTAyM2MxNGMtNzgzYS00MDAxLWI4YzgtMjE4YzllODJhMTA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIwMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWZlYTgyZWQ4Y2M5MjhkNzExNDQyMGM4MDUyN2VkN2Y0NjY3OGQzMzRlNDNmNmIxYmJlODVjNmVkODYxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wuxeoPofEwRZKPz61XrPv3q9MJbLhFafjvasUDGRQ28)

I thought starting points set itself automatically after selecting field position, might be nice to add option to automatically move start point when clicking on the field.

**Comment by regs1980** [comment]
Everything is described in the game help and also here.

https://courseplay.github.io/Courseplay_FS22.github.io/

**Comment by Tensuko** [comment]
> > @Allerek
> > Your target point is at the workshop, you have to bring it closer to the field, or you start CP via HUD button, then you only need to set the field point.
> > ![2024-05-30 21_54_41-Watch Farming Simulator 22 2024 05 30 - 20 30 10 02 _ Streamable – Mozilla Firef](https://private-user-images.githubusercontent.com/13314443/335361293-e023c14c-783a-4001-b8c8-218c9e82a105.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDEzNTAsIm5iZiI6MTcxNzEwMTA1MCwicGF0aCI6Ii8xMzMxNDQ0My8zMzUzNjEyOTMtZTAyM2MxNGMtNzgzYS00MDAxLWI4YzgtMjE4YzllODJhMTA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIwMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZWZlYTgyZWQ4Y2M5MjhkNzExNDQyMGM4MDUyN2VkN2Y0NjY3OGQzMzRlNDNmNmIxYmJlODVjNmVkODYxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wuxeoPofEwRZKPz61XrPv3q9MJbLhFafjvasUDGRQ28)
> 
> I thought starting points set itself automatically after selecting field position, might be nice to add option to automatically move start point when clicking on the field.

Those points have different functions, wouldn't make much sence to move them with the same click.

**Comment by Tensuko** [comment]
Should be cleared.
