### ISSUE TITLE
Güllescheibenegge wird nicht aktiviert

### ISSUE THREAD

**Issue by SeriouZ12** [Courseplay/Courseplay_FS22#3261]
**Steps to reproduce**
Einen Spielstand mit dem Horsch Agrivation DLC, Precision Farming & Courseplay starten. Die Scheibenegge Horsch Joker 8 RT mit Gülleverteiler kaufen, an ein Güllefass hängen und starten. Die Scheibenegge wird beim Starten nicht aktiviert, das Güllefass schon. 

**Actual behavior**
Eine Kombination aus Gülleselbstfahrer oder Güllefass mit der Horsch Joker 8 RT & Gülleverteiler schaltet die Scheibenegge als Gerät nicht an und verbraucht nicht die richtige Menge. Andere Güllegrubber wie die Samson Scheibenegge & der Zunhammer Grubber werden angeschaltet & bringen die richtige Menge nach Precision Farming aus.

**Expected behavior**
Die Horsch Joker 8 RT sollte wie die anderen Gülllegrubber auch angeschaltet werden. Ich vermute einen Zusammenhang mit der Gerätekategorie. Die anderen Geräte sind in der Kategorie Güllesfässer und die Joker ist unter Scheibeneggen. 

**Screenshots**
Oben links zu sehen das die Scheibenegge nicht eingeschaltet wird, die anderen schon.
![image](https://github.com/Courseplay/Courseplay_FS22/assets/63880274/0ea9cb51-e57c-4d1e-ab3f-c7a761436346)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/63880274/2a580d4d-b0e5-40bb-be14-3fd399ccdabd)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/63880274/53e24c2c-a492-4ab0-9eb5-2433348e358e)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/63880274/d99af170-92a7-4af1-9c39-0c14d6f81464)

**Courseplay version**
Version used: 7.4.1.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Erlengrat/Unabhängig

**Vehicles/ implements involved**
Horsch Joker 8 RT (Agrovation DLC)
Güllefass/Selbstfahrer Güllefass

Mod yes/no ?
DLC
Precision Farming

**Comment by regs1980** [comment]
@SeriouZ12 
Du hast noch ein Zusatz Mod im Ordner, der die Ausbringmenge erhöht oder irgendwas anderes, wo der Horsch Joker 8 RT noch nicht eingetragen ist.

Normal ist eine Ausbringmenge +190kg N/ha für Gülle und Gärreste nicht, das sind Werte für Fest- und Flüssigdünger, aber nicht für Gülle und Gärreste.

![2024-06-01 14_06_11-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/b4d7fbdc-b6dc-46a7-a8eb-21b5690f21ea)
![2024-06-01 14_26_27-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/b2c6c9da-5e5c-4e40-8153-804290aa9587)
![2024-06-01 14_26_35-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/8d603df3-8ba9-4121-902e-b5760a374888)

Standard Map: 
Erlengrat 

Geräte Vanilla:
OXBO AT5104 LNMS + Bomech Trac-Pack
Vervaet Hydro Trike 5x5 + Horsch Joker 8 RT

https://drive.google.com/file/d/10dwtHHC4ylwoH1cfwLn83Ct67NEKKg-M/view?usp=drive_link

**Comment by SeriouZ12** [comment]
Aaah ich wusste das ich, was vergessen hab. Jetzt mit Log. 
[log.txt](https://github.com/user-attachments/files/15522276/log.txt)
In der Log ist das Video nicht drin, sondern die Kombis aus den Screenshots

Aber du hast schon gezeigt, was ich meine. Achte mal oben links auf die Ausbringmenge. Beim Trac Pak zeigt die etwas an, bei der Joker nicht. Du siehst mit der Joker auch auf der Precision Farming Map nicht das Gülle ausgebracht wurde, mit dem Trac Pack schon. 

Ich hab auch noch ein Video gemacht, um den Mengen Unterschied zu zeigen. Mit von Hand angeschalteter Joker werden 4000L auf einer Bahn verbraucht. Wird Sie nur gesenkt, so wie CP oder der Helfer das macht, werden nur 1800L verbraucht.

https://drive.google.com/file/d/1c-h99iT9_5oXpkI0ib_kFA6rPYd3BhrD/view?usp=drive_link

**Comment by regs1980** [comment]
Stell mal das Gespann auf dein Feld und drück mal H für den Giants Helfer, mach dieser das selbe, was er auch macht, dann muss man das bei Giants melden.

**Comment by SeriouZ12** [comment]
Jup der Giants Helfer macht das gleiche. Dann ist das doch ein Gesamtproblem der Scheibenegge wie das da eingetragen ist..
