### ISSUE TITLE
[BUG_MP] Cant get past 85% while starting server

### ISSUE THREAD

**Issue by kriszhun49** [Courseplay/Courseplay_FS22#3263]
I downloaded the latest of the CP mod and i started up the server it got stuck on 85% loading after i removed the mod it worked perfect

**Comment by regs1980** [comment]
Server log.txt

**Comment by Tensuko** [comment]
Fill in the template, else we cant help.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Make new Issue and fill in the template pls.
