### ISSUE TITLE
[BUG_SP] CP 7.4.1.2 - Bale wrapping - starting point not in field

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#3264]
**Steps to reproduce**
i'm using a fendt 1050 and the vanilla Khun bale wrapper

**Actual behavior**
when starting work, it says "Starting point not in field"
but i am in the fild

**Expected behavior**
driver start working and balling bales

**Screenshots**
![fsScreen_2024_06_02_12_11_32](https://github.com/Courseplay/Courseplay_FS22/assets/58886243/5aaf816f-d2ff-4648-a22f-57ebf5da1c0d)

**Courseplay version**
Version used: 7.4.1.2

**Log**
[log.txt](https://github.com/user-attachments/files/15524881/log.txt)
log attached with debug activated
just start the game, go to tractor, click start working, then message on the screenshot appears.
i quit

**Map**
Vanilla Zielonka

**Vehicles/ implements involved**
Fendt 1050
Khun bale wrapper

**Relevant script mods**
Autodrive 2.0.1.6

**Comment by regs1980** [comment]
@Chico0008 

Read the CP help in the game or on the CP help page.

![2024-06-02 12_45_17-Courseplay_Courseplay_FS22_ Courseplay for Farming Simulator 2022 – Mozilla Fire](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/d741d5ad-6407-4178-b244-d8929e55eb18)

It describes everything that needs to be done.

If your knowledge of CP is still from 2023, then you should urgently read up on it, CP is evolving and becoming more efficient.

**Comment by Tensuko** [comment]
Use the hud target icon to get on the ai map and place the field marker.
