### ISSUE TITLE
[BUG_SP]  attempt to perform arithmetic on field 'targetX' (a nil value)

### ISSUE THREAD

**Issue by yourpo31** [Courseplay/Courseplay_FS22#3265]
**Steps to reproduce**
Im using vanila Panther 2, MF 7715 (2), MF 7716 (2), JD 4755, JD 7810, MF 3670, JCB FASTRAC 4220, FLIEGL TMK 273, WELGER DK115(4), 

**Actual behavior**
I have 3 contracts on a field 38,39,69 for harvesting. When im making all of my vehicles work with CP it freeze my game at somepoint (don't understand what im doing to make it freeze), i have all the sounds, but i can't do anything and have to alt+f4 my game. (My CPU not going higher than 35% and RAM is about 40%) so its not about my PC.

**Expected behavior**
Fixing on freezing game

**Courseplay version**
Version used: 7.4.1.2.

**Log**
[log.txt](https://gist.githubusercontent.com/yourpo31/16b7c55435a3571778b23e8ed555ae25/raw/79abde1295e1913ccbf23c6f770588de789b5b30/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Panther 2, 
MF 7715 (2), 
MF 7716 (2), 
JD 4755,
JD 7810,
MF 3670, 
JCB FASTRAC 4220, 
FLIEGL TMK 273, 
WELGER DK115(4)
Mod no ?

**Relevant script mods**
Autodrive - turned on, but didn't use in those case

P.S. i tried to find this bug in completed topics, but didn't see anything about this. Also only 1 topic in steamcommunity about same thing. Its my first bug report and post in github, so im sorry if i did a mistake. Did read the wiki and tried to do my best.

**Comment by Tensuko** [comment]
Report looks good :) we will check whats going on.

**Comment by yourpo31** [comment]
@Tensuko So we are waiting 7.4.1.3 patch for fix, right?

**Comment by Tensuko** [comment]
Jep, comes soon.
