### ISSUE TITLE
[Feature]Functionality with Twine add on

### ISSUE THREAD

**Issue by Drmattymd** [Courseplay/Courseplay_FS22#3266]
When using courseplay with a baler and the twine addon, twine is not consumed, 

**Describe the solution you'd like**
I would like courseplay to recognize twine in the baler and consume it while baling as intended.

**Describe alternatives you've considered**
Perhaps twine could be activated/deactivated in the settings menu similar to fertilizer with seeders/planters

**Comment by Tensuko** [comment]
Wont fix, sry.
