### ISSUE TITLE
Target is not on field [BUG_SP]

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/Courseplay_FS22#3267]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I am playing the Carpathian map. I am on field 10 trying to pick up round bails 125. In the posted video I am only able to pick up with the Auto bail trailer is I move the trailer myself. Courseplay does not did not do it. I know this has been discussed and seen in german as a repeat issue but did not see a fix.

**Actual behavior**
when I click arrow to pick up bales it says "Not of field"
**Expected behavior**
with the vehicle on the field it is suppose to pick up bails automaticaly Note: I also have this same problem when try to use bale wrapper"
**Screenshots**
I have posted a video on this https://youtu.be/mVTaCdDTmCQ
**Courseplay version**
Version used: 
7.4.1.2
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Carpathian

**Vehicles/ implements involved**
Valtra Valment 8750 Tractor and the Farmtech DPW 1800 Autoload Trailer.
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. I am using autodrive with courseplay

[log.txt](https://github.com/user-attachments/files/15528699/log.txt)

**Comment by Tensuko** [comment]
Read the ingame help. You have to mark the field on the AI Map.
Use the target icon to get there quickly.

**Comment by Tensuko** [comment]
>  I understand that the auto bale collecting should start by being on the field to where it detects the bales and start collecting

Not where you are on, but where you placed the target at.

And it is the FIELD position, not Target (wich you did click in the video).

**Comment by Gibbanator** [comment]
Thank You. I was running around beating my head trying to figure this out. Placing the "Field Position" marker on the field instead of the "Target Position" made all the difference.
