### ISSUE TITLE
[BUG_SP]Abfahrer im Weg, Drescher prüft nicht ob Weg frei ist.

### ISSUE THREAD

**Issue by Natsu83** [Courseplay/Courseplay_FS22#327]
**Steps to reproduce**
In der ersten Vorgewenderunde entladen führt zur Kollision zwischen Drescher und Abfahrer.

**Actual behavior**
Wenn der Drescher im ersten Vorgewende fährt und dort voll wird, fährt er erst rückwärts und dann fährt er vorwärts eine bucht ins Feld, damit der Abfahrer den Drescher abtanken kann. Sobald das Abtanken fertig ist fährt der Drescher wieder los und fährt einen zu engen Radius, wodurch der Drescher in den Abfahrer fährt.

**Expected behavior**
Der Drescher sollte ein Stück weiter vor fahren, eh er wieder in das erste Vorgewende einfährt

**Screenshots**
![carcrash](https://user-images.githubusercontent.com/38187285/147890653-df01eeaf-c2ea-473a-96eb-9072fdd748f8.jpg)

**Courseplay version**
Version used: 7.0.0.11

**Log**
Habe leider gerade keinen Zugriff auf die Log, da ich an einem anderen Rechner sitze. Wenn gewünscht, kann ich die log nachreichen.

**Map**
Alle Maps

**Vehicles/ implements involved**
Ja und Nein. Verhallten lässt sich sowohl mit Vanilladrescher als auch mit Moddrescher reproduzieren.

**Relevant script mods**
Autodrive 2.0.0.2.

**Comment by Tensuko** [comment]
Abfahrer = AutoDrive ?
Wenn ja, Kommunikation ist noch nicht implementiert.

**Comment by Natsu83** [comment]
Abfahrer ist Autodrive. Sorry, hatte ich vergessen zu erwähnen.

**Comment by pvaiko** [comment]
Sorry, CPs own unloader is not yet migrated to FS22 and, also, communication with AutoDrive is not implemented yet. Also, the CP combine driver waits a bit (I think 5 seconds) extra before returning to work to let the unloader leave the scene...
