### ISSUE TITLE
[Enhancement] Cut vehicle name lenght to prevent its written over the Icons.

### ISSUE THREAD

**Issue by vitalii2011** [Courseplay/Courseplay_FS22#3273]
Sometimes they are difficult to click:
![fsScreen_2024_06_02_13_22_05](https://github.com/Courseplay/Courseplay_FS22/assets/41552153/a5511ba1-e889-4c6c-8c99-23c73effc58a)
![fsScreen_2024_06_02_13_21_45](https://github.com/Courseplay/Courseplay_FS22/assets/41552153/15c6a544-1dde-4df0-9a00-300cd1d457ed)

**Comment by Tensuko** [comment]
We could only cut the name, but not change any position on the HUD.
We used up all space.
