### ISSUE TITLE
[Feature]Need default Vehicle Settings for all new acquired/leased/contract given vehicles

### ISSUE THREAD

**Issue by harokyang** [Courseplay/Courseplay_FS22#3276]
I personally like to set Reverse Speed for my vehicles to 10 kph
But the current Vehicle Settings only apply to individual vehicle
Every time I accepted a contract and lend vehicle for the job, I have to change all setting for the new vehicle

I hope we can globally set some default parameter value for any new vehicle we get from shop or contractor

**Comment by Tensuko** [comment]
We have choosen our defaults for reasons.
An option to set your own is not intended and will not be added, sry.
