### ISSUE TITLE
[Feature]Request Copy/Paste course function for controller UI

### ISSUE THREAD

**Issue by harokyang** [Courseplay/Courseplay_FS22#3277]
In non-controller UI, we have the copy/paste button for mouse clicking to quickly duplicate course for other vehicle
But in controller UI, there is no such function, and have to use the course manager to store and load course for other vehicle

Please add such function so I won't need to touch keyboard/mouse to make a multi tools team

**Comment by Tensuko** [comment]
The space for that UI is super limited, I don't think we can fit it in there.
I only have future plans for next FS for better controller support, but not for FS22 anymore.
Don't know if we can make a keybind for it without breaking limited functions for it.

**Comment by S-eler** [comment]
Hi, quick question - I'm new to FS, never played before FS22, and when I start with FS22, auto drive and course play were already available on modhub. What's your strategy with supporting FS22 - as soon as next gen farming will pop-up, all resources will be shifted to port CP from FS22 to FS2X?

**Comment by Tensuko** [comment]
Yes, we are a small team and can focus on only one version. At one point we will make a final Version for FS22 and stop development for it when we start our work for the next fs.

**Comment by Tensuko** [comment]
Dont think we add this in fs22.
Will find a solution for next fs.
