### ISSUE TITLE
I tried to generate a problem and ended up popping up several.  Unload harvester, but don't wait for it to run out.[BUG_SP]

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS22#3282]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Programar para o trator com a carretinha, ir descarregar a colheitadeira 

Program for the tractor with the reel, go to discharge the harvester

**Actual behavior**
Esta configurado para a colheitadeira parar para descarregar. porem o trator vai descarregar e antes de acabar de esvaziar a colheitadeira, ele sai.

 It is configured for the harvester to stop to discharge. But the tractor will discharge and before you finish emptying the harvester, it leaves.

Porem , ao fazer a gravação do problema, aconteceu varios erros, assim poderam verificar outros erros que ocorreram nesse video.
Agradeço.

However, when recording the problem, there were several mistakes, so they could check other errors that occurred in this video.
I thank.

**Expected behavior**
Que o trator aguardasse acabar de descarregar a colheitadeira.

That the tractor would wait for the harvester to discharge.

**Screenshots**

https://www.youtube.com/watch?v=4peEnGVC1Po

**Courseplay version**
Version used:  7.4.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/15753919/log.txt)

**Map**
Map played on.
Hault-Beyleron Original

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

Originais

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by erksartori** [comment]
Agora sim esse video mostra o problema com mais clareza. Esta no final do video.

Now this video shows the problem more clearly.,It's at the end of the video.

https://youtu.be/BPGIVdrdJAs

[log.txt](https://github.com/user-attachments/files/15754033/log.txt)

**Comment by regs1980** [comment]
This looks more like an AD problem, not a CP.
AD has interrupted the loading, so the combine harvester has continued its work. 
To avoid something like this, they let the driver work via CP.
There will also be an AD version coming soon, with a revised harvester mode.

**Comment by coatsy35** [comment]
Is this where you need to do as @Tensuko says on here https://github.com/Courseplay/Courseplay_FS22/issues/2825 I always do this on each new AD version. Which they fixed it a long time ago, but AD development is nowhere near as active as CP so I understand

**Comment by erksartori** [comment]
Chamado Aberto no AD: Trailer does not wait to unload the entire harvester #1136
