### ISSUE TITLE
[BUG_MP] The ball collection trolley does not close so that it cannot reach the destination point.

### ISSUE THREAD

**Issue by regs1980** [Courseplay/Courseplay_FS22#3284]
The problem was already known here, and it was not fixed before release. 

https://github.com/Courseplay/Courseplay_FS22/issues/3247#issuecomment-2138886764

**Courseplay version**
Version used: 7.4.1.3

**Server Log**
[log_2024-06-09_17-16-33.txt](https://github.com/user-attachments/files/15764706/log_2024-06-09_17-16-33.txt)

**Video**

https://drive.google.com/file/d/1eRpIibVsR8lieC4UcBSaF8JWEOS0XQsw/view?usp=drive_link

**Player on the server**
1

**Dedicated server or local hosted server**
Dedicated server yes ?

**Comment by Tensuko** [comment]
Should be the same in SP I guess.

**Comment by regs1980** [comment]
In the SP, he drives to the target point with the bale lifter unfolded and then folds it up before handing it over to AD.

https://drive.google.com/file/d/1l-o70uqyWOY5gnBOmwwMZeuuNWVfuzHD/view?usp=drive_link
