### ISSUE TITLE
[Feature] Rückwärtsfahren nach abladen am Zieltrigger

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3285]
Hallo Tensuko

**What is the problem this feature/enhancement solves?**
der Telelader setzt nach dem Abkippen nicht weit genug zurück und bleibt manchmal am Lagersilo hängen

**Describe the solution you'd like**
der Telelader sollte nach dem Abkippen der Schaufel etwas weiter zurücksetzen.

**Describe alternatives you've considered**

**Additional context**
hier ein Überblick der gegebenheiten:
![fsScreen_2024_06_10_13_30_25](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/e117b7a4-97ca-407b-8525-763fe7d1e79b)

zurückfahren aus dem Silo und anfahren des Lagersilos funktioniert immer gut:

abkippen auch, obwohl der Telelader sehr hoch hebt und manchmal oben an dem Dach hängenbleibt:

aber dann setzt der Telelader nur kurz zurück und senkt die Schaufel ab:

und da bleibt er manchmal beim vorwärtsfahren am Lagersilo hängen:
![fsScreen_2024_06_10_13_32_01](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/d40b77b7-196c-4ed8-8aee-bfe45f8c5f27)

oder beimvorwärtsfahren, bei der anfahrt zum Silo in der linkskurve bleibt er auch gerne hängen:

wäre es möglich das der Telelader nach dem ankippen etwas weiter zurücksetzt?

und ja sorry, aber könnte man die abkipphöhe nicht auch manuell einstellen - so ähnlich wie beim Aufladen mit dem "versatz Schaufelhöhe".
es kommt sehr selten vor das beim abladen die maximale schaufelhöhe notwendig ist.

edit:
wäre es möglich, die Schaufelbreite auch unter 3m einzustellen, die Bressel und Lade L67 hat nur 2,4m

lg
andreas

**Comment by Tensuko** [comment]
Versuch das mal mit dem Branch ob das hilft.
https://github.com/Courseplay/Courseplay_FS22/pull/3294

**Comment by andreasthu** [comment]
Danke euch,
werds heute abend mal versuchen.
Lg
Andreas

**Comment by andreasthu** [comment]
Guten Morgen
dieser branch hat bei mir erstmal keine änderung des Rückwärtsfahrens gebracht:
![fsScreen_2024_06_19_05_42_05](https://github.com/Courseplay/Courseplay_FS22/assets/24860501/62f95d54-320d-4410-b91b-dc882fe34a24)
lg
andreas

**Comment by Tensuko** [comment]
Soll es auch nicht, aber der Radius sollte angepasst sein das dieser nicht mehr so eng ist.

**Comment by Tensuko** [comment]
![fsScreen_2024_06_21_12_45_53](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/327e6d8b-792c-41fe-bfeb-7c7db688cc11)
![fsScreen_2024_06_21_12_46_02](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/5ebf2882-c3f4-445c-8280-f0e39aa45f84)
Bei mir fährt er erst sauber rückwärts, bevor der Pathfinder läuft.
Setzen mal deine Marker neu.

**Comment by Tensuko** [comment]
Marker:
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/e9cf28be-26c2-4dce-8c85-91be8e8122e0)
Distance die er rückwärts fährt bevor der Pathfinder läuft und irgendwie oder irgendwo um die Kurve fährt.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/6e9623f5-e3d1-493c-b1c4-84063374ca9a)

**Comment by andreasthu** [comment]
Ok, werds heute abend mal mit anders gesetzten Punkten versuchen.
Obwohl, hab schon einige probiert.
Selbst den Zielpunkt mehrere Meter weiter hinten.
Lg
Andreas

**Comment by Tensuko** [comment]
Der Zielpunkt hat darauf keine Auswirkung.
Ladepunkt und Abladepunkt (Trigger) sind entscheident.

**Comment by Tensuko** [comment]
Closed due to inactivity.
