### ISSUE TITLE
CP not working on mac (FS22 Apple Store Version)

### ISSUE THREAD

**Issue by Rioufa** [Courseplay/Courseplay_FS22#3286]
Hi,

Downloaded CP and placed it in the mods folder, it doesn't work and is not even appearing in the mod list when starting the game.

I am using FS22 bought on the Apple Store, mods folder file location is different than the one you you have when using a game directly bought from Giants website. Could be the reason CP is not working?

Thanks.

**Comment by Tensuko** [comment]
Pls fill in the template in order to help you, that include the most important file (log.txt)

**Comment by Tensuko** [comment]
Closed due to inactivity. Make a new issue and fill in the template.
