### ISSUE TITLE
[BUG_SP] Combine harvester and bale collector (autoload) are blocking each other.

### ISSUE THREAD

**Issue by Joko-Ger** [Courseplay/Courseplay_FS22#3288]
**Steps to reproduce**
Create a course which is used by harvester and bale collector with 2 meter offset.

**Actual behavior**
The bale collector and the harvester use the same course. The bale collector is set to a 2-meter offset. Whenever the combine harvester and the bale collector meet on the inside, the combine harvester stops and does not continue until the Courseplay course is ended. This only happens when the combine harvester and the bale collector meet on the inside, not on the outside.

**Expected behavior**
The combine harvester should proceed the course and not be blocked by the bale collector.

**Screenshots**
![CP Bug](https://github.com/Courseplay/Courseplay_FS22/assets/99117003/260c71ab-a9e2-4342-9984-bfc2e4cd5574)

**Courseplay version**
Version used: 7.4.1.3

**Map**
NF Marsch OG

Which vehicle or implement?
Harvester Header (Mod): Draper 3162 (FS22_ZIM_3162_TerraFlex_45FT)
Collector (Mod): DPW 1800 Autoload, Autoload Stock Trailer Pack (FS22_AutoloaderStockPackjw)

**Relevant script mods**
Autodrive: Yes, but not used in this moment

**Comment by Tensuko** [comment]
Not a bug.
This is more a question of how you set it up.
Sadly I dont see the blocking in this picture.
You should also use the lands (Beete) pattern for Harvester.
Working with many different tools on the same course is risky and not rly intended.

**Comment by Joko-Ger** [comment]
Here a screenshot of the blockings

![Uploading CP Bug2.png…]()

**Comment by Tensuko** [comment]
Sadly also no logfile like requested in the template.

**Comment by Joko-Ger** [comment]
Which log do you need? The log.txt of the game or another one?

**Comment by Tensuko** [comment]
Turn debug on (vehicle settings), let it run till blocking  then attach rhe log.

**Comment by Joko-Ger** [comment]
I tried to reproduce the error and now it doesn't happen again... Perhaps it depends on a specific field course.

As soon as it happens again I attach the log file.

Thanks for your support!

**Comment by Tensuko** [comment]
Alright, just hit "reopen" and we have a look.
