### ISSUE TITLE
[BUG_SP] Panther wendet nicht richtig in die Bahnen

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#329]
**Steps to reproduce**
Kursgenerierung mit Vorgewende und dann fahren lassen

**Actual behavior**
beim drehen in den bahnen zuckelt der Panther beim Rückwärtsfahren nur noch und beendet nach einiger Zeit den Helfer

**Expected behavior**
sauber in die Bahnen wenden

**Courseplay version**
Version used: 7.0.0.11

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7799933/log.txt)

**Map**
Elmcreek Feld 57

**Relevant script mods**
AD / VCA, nicht relevant

**Comment by TheSoldier91** [comment]
Selbes Problem.
Feld 48 haut beyleron

**Comment by bmsbwd** [comment]
selbiges beim Tiger. Scheinbar kommt CP nicht so gut mit den abknickenden Fahrzeugen klar.

**Comment by SAM24986** [comment]
Den Ropa Maschinen fehlt dieser Eintrag in der xml: <allowTurnBackward value="false"/>
Ob die mit "true" als Eintrag dann auch Rückwärts wenden habe ich nicht probiert, so wenden sie aber vorwärts ohne Probleme, allerdings sollte das Vorgewende groß genug sein

**Comment by SAM24986** [comment]
So, jetzt nochmal genauer getestet, schreibt man als Zustand "true", dann kann CP damit nicht um. Dem Helfer aus dem Spiel ist das egal, der dreht auch rückwärts wenn die ganze Zeile fehlt.

**Comment by Tobias80** [comment]
Gleiches Problem -auch mit Version 7.0.0.12

**Comment by Tensuko** [comment]
Hat auch niemand gesagt, dass es behoben sein soll. Wäre hier dann mit einem Commit oder Update verlinkt!

**Comment by Achimobil** [comment]
So war das auch nicht gemeint. Ich weiß nur das bei vielen Änderungen sich andere Meldungen erledigen und wollte bestätigen, dass dies hier nicht der Fall ist.

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.18
Reopen if Issue persists.
