### ISSUE TITLE
[BUG_SP] Bale Collector Arcusin Multipack D14 does not unload

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/Courseplay_FS22#3290]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I realized the issue after updating to CP 7.4.1.3. Switched back to CB 7.4.1.2 and automatic unloading by CP worked again. Switched back to 7.4.1.3 and unloading stopped working again.

**Actual behavior**
During bale collecting with CP version 7.4.1.3 the Arcusin Multipack D14 does not unload after reaching 14 bales.

**Expected behavior**
Bale collector should unload bales and continue collecting (as with CP 7.4.1.2)

**Screenshots**
CP 7.4.1.2 unloads and continues collecting
![2024-06-13 21_02_32-Farming Simulator 22](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/0557a7f9-4c87-4f7d-8728-16b95c9aa188)
CP 7.4.1.3 stops job without unloading bales
![2024-06-13 21_15_36-Farming Simulator 22](https://github.com/Courseplay/Courseplay_FS22/assets/76711921/8ab0095b-523f-4709-bcf9-caae862229b3)

**Courseplay version**
Version used: 7.4.1.3

**Log**
[Log_CP_20240613.txt](https://github.com/user-attachments/files/15827794/Log_CP_20240613.txt)

**Map**
Hallig Petrus

**Vehicles/ implements involved**
Arcusin Multipack D14
Deutz D06 Series
Mod yes/no ?
yes

**Relevant script mods**
Autodrive, VCA, EV

**Comment by Tensuko** [comment]
Well, he does unload, but he drives to the target point and then finish the work.
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/d21b8275-00a7-44a1-a5e1-cefe739a6803)
Need to exclude that tool from that function.
