### ISSUE TITLE
mini hud nicht mehr verfügbar

### ISSUE THREAD

**Issue by MysticKnight1** [Courseplay/Courseplay_FS22#3291]
ein schönen guten abend ich hab mal ne frage bei mir wird das MINI HUD nicht mehr angezeigt wird auch in der tastenbelegung nicht mehr angezeigt was angezeigt wird ist das mini GUI mehr aber auch nicht woran könnte es liegen 
danke schön im voraus

meine version 7.1.4.3

Mfg MysticKnight1

**Comment by Tensuko** [comment]
Ich wei jetzt nicht was du meinst.
Wir haben das hud, das info panel und ai menü.
Was fehlt jetzt?
Logfile?
In mod settings ordner, cp ordner, settings.xml löschen.
Warum das in der tastenbelegung weg ist würde nur heißen du hast beim mods runterladen was falsch gemacht.

**Comment by MysticKnight1** [comment]
hallo vielen dank für deine schnelle antwort ich schicke mal das mini hud was ich meine das mini hud finde ich für mich persönlich besser 

![yhfu832udag91](https://github.com/Courseplay/Courseplay_FS22/assets/97942128/ff757bea-c825-4fac-9bdc-a53100c07e1b)

das aktuelle was wir jetzt haben find ich nicht so schön

![maxresdefault](https://github.com/Courseplay/Courseplay_FS22/assets/97942128/4710392e-aed9-4b41-8376-9aa9a8e5a53a)

**Comment by MysticKnight1** [comment]
anbei noch die logdatei
[log.txt](https://github.com/user-attachments/files/15874368/log.txt)

**Comment by MysticKnight1** [comment]
bei bild 1 das mini hud ist nicht mehr da kann es auch per tasten kombi nicht aktivieren

![fsScreen_2024_06_17_18_55_32](https://github.com/Courseplay/Courseplay_FS22/assets/97942128/390efec1-24e7-4d1b-bf7d-54ba8faf8bf3)

das ist das HUD was er mir anzeigt
![fsScreen_2024_06_17_18_59_32](https://github.com/Courseplay/Courseplay_FS22/assets/97942128/1c5e23c3-f722-4fdf-a5a3-bc7a3b9982d4)

**Comment by Tensuko** [comment]
Das was du da an hast ist das gamepad hud. Cp globale einstellungen und das da ausschalten.

**Comment by MysticKnight1** [comment]
ich danke dir es hat funktioniert macht weiter so 
ihr seit ein gutes team mein größten respekt für eure leistungen 

Mfg MysticKnight1
