### ISSUE TITLE
[Question] Game crash when generating course

### ISSUE THREAD

**Issue by fzzhd123** [Courseplay/Courseplay_FS22#3292]
I am getting my game crashing when I am trying to use courseplay to create a new field on a custom field I drew on the map (Griffen Indiana). I am not sure what is going on, any insight is appreciated. I have attached the log for refence. 
[log.txt](https://github.com/user-attachments/files/15845686/log.txt)

**Comment by Tensuko** [comment]
Game wont ever crash, you need patience on some fields!
For custom field it is important that you have no overlapping from the start over the end. Better is to have a small gap.

**Comment by fzzhd123** [comment]
Thank you for your help! It looks like my start and end point overlapped, and that got it working :)
