### ISSUE TITLE
[Question] Is there anyway I can limit how for the silo worker goes?

### ISSUE THREAD

**Issue by Gerbooo** [Courseplay/Courseplay_FS22#3296]
Is there anyway I can limit how far the silo worker goes into the bunker silo to prevent this from happening:

https://github.com/Courseplay/Courseplay_FS22/assets/49808070/0e501a33-ab4a-4c93-ac1b-c50b18b492fa

I already increased the bunker silo collision as sean but I dont want that because now turning with a wheel loader is hard :(

**Comment by Tensuko** [comment]
There is no limit.
What Bunker is it?

**Comment by Gerbooo** [comment]
> There is no adjustable limit, it comes from the Bunker itself. What Bunker is it?

This one:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=233730&title=fs2022

**Comment by Gerbooo** [comment]
I kinda fixed it by moving siloInerHeight in Giants editor the game detected that the silo stopped outside of the actual silo. So i change that this is the result:

![Fix game](https://github.com/Courseplay/Courseplay_FS22/assets/49808070/86e7ec54-b881-4158-95ee-11a16f15ce78)
![Fix i3d](https://github.com/Courseplay/Courseplay_FS22/assets/49808070/ead6074e-c208-49bf-86ec-563a1f68e7d0)

**Comment by Gerbooo** [comment]
Well nvm it worked until courseplay was to dumb to notice that if he can't go anyfurther it may be to steep. So it kept trying until the whole leveler was over the back and threw everything over it

**Comment by Tensuko** [comment]
Then it is too high as well. Never had that problem in the bunkers I use.
(Using the one from Kastor).
