### ISSUE TITLE
[BUG] Start problem in a world

### ISSUE THREAD

**Issue by AltF4Quit** [Courseplay/Courseplay_FS22#3298]
I only start the game with CoursePlay and this error occurs no matter which version of CoursePlay I select.
No mods or maps installed.

![Bild_2024-06-16_171417310](https://github.com/Courseplay/Courseplay_FS22/assets/118925246/0ecf4bff-24c5-4ee7-9a2d-4311c86b6667)

[log.txt](https://github.com/user-attachments/files/15858813/log.txt)

**Comment by Tensuko** [comment]
Hast du eigentlich gelesen was da steht?
Wo ist da eine Fehlermeldung???
Schon mal einfach auf ok gedrückt?
Was passiert dann?

**Comment by AltF4Quit** [comment]
Dann Crasht das Game

**Comment by Tensuko** [comment]
Laut deiner log crasht da gar nichts. Mal mit geduld versucht?
An CP liegt es jedenfals nicht, sonst hätte jeder das Problem.
