### ISSUE TITLE
[Feature]kleiner technischer Fehler Titan18

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#330]
er Pflügt die erste Furche Falsch rum, man Pflügt immer von der ungepflügten Feldseite weg, weil sonst würde das letze Schar ja keine Furche machen, und die erste aufs ungepflügte Feld werden.

die folgenden Bahnen stimmen und der Pflug wird auch richtig gewendet

![image](https://user-images.githubusercontent.com/8066324/147892773-a6b99db7-58dc-49ba-9f98-c5b315808c74.png)

**Comment by Tensuko** [comment]
To much effort for that smal detail, sry.
Won't change that.
