### ISSUE TITLE
[Feature] center up&down - equalising track on the end

### ISSUE THREAD

**Issue by S-eler** [Courseplay/Courseplay_FS22#3300]
**What is the problem this feature/enhancement solves?**
When we creating most typical course:
start on headland, than up&down without row skip
and the field wide is not even to multiply tool range, we have one "additional" narrow course. At this moment, this narrow track is first to be driven after headline, like on scheme below:
<img width="399" alt="image" src="https://github.com/Courseplay/Courseplay_FS22/assets/121870418/e174bc8f-d015-44fb-9ef7-f16974bcb55f"> so it's covering the headland.
it would be more logic for me, to create this course as the last one, like below:
<img width="450" alt="image" src="https://github.com/Courseplay/Courseplay_FS22/assets/121870418/8b9080dc-a721-48ff-8317-6b4a0f079f64">

First logic reason, is that a driver (without earlier gps mapping) will not now exactly how many meters it will be, so it's more obvious to start working normally, for full implement range. But more important reason for me it's that if we have more than one tool on the job, they colide on early stage, just after first one complete headland. If the "narrow track" will be the last one, there is no chance for it.

**Comment by coatsy35** [comment]
I’m fairly certain they plan to fix this in the next generation of course generator.

**Comment by rohne83** [comment]
can be closed, as this is exact duplicate to https://github.com/Courseplay/CourseGenerator/issues/5
