### ISSUE TITLE
[BUG_SP] AI Worker refill set to location doesn't use up resource or cost anything

### ISSUE THREAD

**Issue by AndreLemay** [Courseplay/Courseplay_FS22#3305]
**Steps to reproduce**
1. Set AI Worker Refill - Slurry setting to a location (e.g. Biogas plant, cow barn)
2. Create CP Fieldworker job with slurry tank attached 
3. Start job while remaining in the tractor while the AI drives it around
4. Observe amount of slurry/digestate remaining in the tank (I was using digestate)

**Actual behavior**
The amount of digestate stayed constant while the AI worker was spreading it, in the same way it does when the setting is set to "Buy", but no money was being deducted.

**Expected behavior**
The tank should be used up as the worker continues, and then the worker should go to refill at the biogas plant.

**Courseplay version**
Version used: 7.4.0.0

**Log**
https://gist.github.com/AndreLemay/b18a870cdd2da6150c1fa91a691667ec

**Map**
Elmcreek

**Vehicles/ implements involved**
Claas Axion 930 Terra Trac with PFW 18000 MaxxLine Plus
No vehicle/tool mods installed.

**Relevant script mods**
None I can think of. Only other mods I have installed are Universal Autoload, Map Objects Hider, the 4 Real Dirt mods, Full Refund, and Free landscaping tools.

**Comment by Tensuko** [comment]
We dont have a refill option...
And is your setting set to "no" or use from barn for the buy option?

**Comment by Tensuko** [comment]
will consume
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/f5d2a50c-bf1c-4b4c-9456-0ba264083721)
all set to off
![grafik](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/1c6ec0b1-ca1f-4b76-8ae9-722b97e9f100)

working just fine, can't reproduce.

Pretty sure you have set it to use from a barn or something else.

But its not a CP issue.

**Comment by AndreLemay** [comment]
The first repro step clearly states that you must set the AI Worker Refill to use from a location.

I'll try disabling CP to see if this is a base game bug or not.

**Comment by AndreLemay** [comment]
Can confirm, same happens with CP disabled.
