### ISSUE TITLE
Transfer of bale collector to AD does not always work

### ISSUE THREAD

**Issue by Meditos7719** [Courseplay/Courseplay_FS22#3306]
Since the last update, the transfer from AD to Coursplay no longer works. Or rather, to the bale collector. AD drives to the point on the field, but then there is no transfer or both programs switch on. Even if it works, the bale collector drives to the last point of a field that I previously worked on and waits there. No message or anything else. It just stands there and does nothing. It only works with restrictions if I first drive to the destination with AD, then switch it off and only then activate the bale collector. Before the update, everything was fine.

**Comment by Tensuko** [comment]
Did you set both marker, field and target?

**Comment by Meditos7719** [comment]
Yes, I did everything, even in the middle of the field. The AD point is in the field. I made sure that it was very far in the field. Every now and then it passes, but when it is full it no longer passes it back to the AD. And a bale collector ignores the field and destination point completely. It simply drives to the old field where the marker was before. It does not want to take over the new point. But when I look at the map, both points are exactly inside the field. On top of that, I keep getting the message that it cannot find a way. Even though it is standing in front of a bale and in the middle of the field. I will test it on a standard map because it is my own map and it still has an error, but this is normally just a graphical problem. As I said, I have been working with AD and CP for a long time. And before the update everything was fine. It is OK if there is an error every now and then. but now it hardly works anymore and has to intervene again and again.
________________________________
Von: Tensuko ***@***.***>
Gesendet: Freitag, 21. Juni 2024 15:19
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work[BUG_SP] (Issue #3306)


Did you set both marker, field and target?

**Comment by Tensuko** [comment]
The AD point doesn't have to be in the field.

So you did download 7.4.1.3 from release page?

**Comment by Meditos7719** [comment]
Yes. a few days ago and I know that he shouldn't be in the field. I just thought to make sure that CP finds the field. CP is up to date. and I've had problems ever since.
  

  

  

  
  
  
  
  
>

**Comment by regs1980** [comment]
Screenshots and perhaps also a video of how you set up the ball collector.
Everything you write looks like an operator error and not a CP error.

**Comment by Meditos7719** [comment]
https://youtu.be/gnFq2BCGTvQ

I have uploaded a 30 minute video for you. Only 2 bale collectors were used. I have set it up as requested and keep showing the log file. An hour has passed and both bale collectors are still at the same point. With the square collector I noticed that it has loaded a course. But that is not possible because I only used this vehicle for collecting. But the course is on the field of the 2 collectors with the round bales. Strange. So what am I doing wrong? How can I do something wrong if I have set everything up and the program still doesn't switch?
________________________________
Von: regs1980 ***@***.***>
Gesendet: Freitag, 21. Juni 2024 18:38
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)


Screenshots and perhaps also a video of how you set up the ball collector.
Everything you write looks like an operator error and not a CP error.

**Comment by regs1980** [comment]
For the first collector, the tractor still has an old course saved, which you have to delete first, otherwise it will keep driving to the field from the course.

![2024-06-22 00_05_48-2024 06 21 19 49 32 - YouTube – Mozilla Firefox](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/94228406-6488-4553-b9e4-3d3322023cd5)

For the second collector, activate vehicle debug and set the target point close to the field boundary.

![2024-06-22 00_12_57-Farming Simulator 22](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/1d89089c-9e86-44dc-b472-993ada2a9365)

Then make a short video of it until it stops and upload the log here.

**Comment by Meditos7719** [comment]
LS22-Fehler<https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=8h9Z8P>

I've saved it for you on OneDrive because the video is longer than expected due to the long calculations.
When I delete the course from collector 1, it now starts correctly. But as with collector 2, it no longer passes back to AD. The error also occurs from time to time with other vehicles, CP does not switch on AD and the vehicles just stand there until I switch off CP and switch on AD. Then everything is OK again. But the error does not always occur. But 90% of the time I have to intervene and since I don't get an error message and only pay attention to it when I get to the vehicle, a lot of time passes. I hope I have done everything to your satisfaction.
________________________________
Von: regs1980 ***@***.***>
Gesendet: Samstag, 22. Juni 2024 00:26
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)


For the first collector, the tractor still has an old course saved, which you have to delete first, otherwise it will keep driving to the field from the course.

2024-06-22.00_05_48-2024.06.21.19.49.32.-.YouTube.Mozilla.Firefox.jpg (view on web)<https://github.com/Courseplay/Courseplay_FS22/assets/13314443/94228406-6488-4553-b9e4-3d3322023cd5>

For the second collector, activate vehicle debug and set the target point close to the field boundary.

2024-06-22.00_12_57-Farming.Simulator.22.jpg (view on web)<https://github.com/Courseplay/Courseplay_FS22/assets/13314443/1d89089c-9e86-44dc-b472-993ada2a9365>

Then make a short video of it until it stops and upload the log here.

**Comment by Tensuko** [comment]
Couldn't see the problem in that video and too bad there is no logfile about that issue so we can see whats happening.
If the Error does not always happen, we need video and logfile from when the problem occourse, else we can't do anything....

**Comment by Meditos7719** [comment]
Everything on the link is FS22 error. There is a video and a log file. I can't send you 300 MB. You have to see that or compression doesn't work. Everything is as you asked for. I'm sorry if your email program doesn't show the link as it should. For me it is underlined in blue
But to make it easier for you, I will break down the link for you. Maybe you will find it then

https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR

LS22-Fehler<https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR>

The Same of the link
________________________________
Von: Tensuko ***@***.***>
Gesendet: Samstag, 22. Juni 2024 12:18
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)


Couldn't see the problem in that video and too bad there is no logfile about that issue so we can see whats happening.
If the Error does not always happen, we need video and logfile from when the problem occourse, else we can't do anything....

**Comment by Meditos7719** [comment]
And another thing. It really annoys me when CP stands in front of the pallets and can't find a way out. Does the scanner only reach 1 meter?
________________________________
Von: Gerhard Pucher (Meditos77) ***@***.***>
Gesendet: Samstag, 22. Juni 2024 12:35
An: Courseplay/Courseplay_FS22 ***@***.***>
Betreff: AW: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)

Everything on the link is FS22 error. There is a video and a log file. I can't send you 300 MB. You have to see that or compression doesn't work. Everything is as you asked for. I'm sorry if your email program doesn't show the link as it should. For me it is underlined in blue
But to make it easier for you, I will break down the link for you. Maybe you will find it then

https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR

LS22-Fehler<https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR>

The Same of the link
________________________________
Von: Tensuko ***@***.***>
Gesendet: Samstag, 22. Juni 2024 12:18
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)


Couldn't see the problem in that video and too bad there is no logfile about that issue so we can see whats happening.
If the Error does not always happen, we need video and logfile from when the problem occourse, else we can't do anything....

**Comment by Meditos7719** [comment]
________________________________
Von: Gerhard Pucher (Meditos77) ***@***.***>
Gesendet: Samstag, 22. Juni 2024 12:35
An: Courseplay/Courseplay_FS22 ***@***.***>
Betreff: AW: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)

Everything on the link is FS22 error. There is a video and a log file. I can't send you 300 MB. You have to see that or compression doesn't work. Everything is as you asked for. I'm sorry if your email program doesn't show the link as it should. For me it is underlined in blue
But to make it easier for you, I will break down the link for you. Maybe you will find it then

https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR

LS22-Fehler<https://1drv.ms/f/s!ArY7SE4Ki-putcMzTrNtosIGv2skug?e=dXdVsR>

The Same of the link
________________________________
Von: Tensuko ***@***.***>
Gesendet: Samstag, 22. Juni 2024 12:18
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: Meditos7719 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Transfer of bale collector to AD does not always work (Issue #3306)


Couldn't see the problem in that video and too bad there is no logfile about that issue so we can see whats happening.
If the Error does not always happen, we need video and logfile from when the problem occourse, else we can't do anything....

**Comment by Tensuko** [comment]
> And another thing. It really annoys me when CP stands in front of the pallets and can't find a way out. Does the scanner only reach 1 meter?

No Idea what you talk about...

**Comment by Meditos7719** [comment]
mistranslated. in front of the bale, hay bale, straw bale is in the field and CP can't find the way even though the vehicle and the bale are only 10 meters away.
  
he just switches off. 100 of the bales are still on the field and it switches off. like as if he said. My developers don't want to work so much and that's why I'm switching off now. I dont want to anymore.
  

  

  
  
  
  
  
>

**Comment by Tensuko** [comment]
So jetzt wechsel ich mal auf deutsch....
Erst mal fangen wir an hier über 2 Dinge zu reden:
- Das er den Weg nicht findet unter gewissen umständen.
- Das er vor einem Ballen den Weg nicht findet.

Unterm strich sind das beides "Probleme" vom Pathfinder und beides können wir nur genauer ansehen, wenn wir eine anständige log mit debug haben in der die Probleme auftraten und am besten Videos dazu haben.

Alles andere geht halt nicht.
Das es vor kommen kann ist halt so und da nützt es auch nichts, wenn der Ballen 10m vor ihm liegt, es wird einen Grund geben warum es nicht ging und sowas steht in der log!

**Comment by Meditos7719** [comment]
Ich wollte euch nur darauf hinweisen das es ein fehler gibt der entsteht wenn die übergabe ist. Und das steht auch in eurer log so. Weil das komando nicht mehr da ist, das der anhänger oder fahrzeug voll ist. Duese zeile steht nicht mehr da.
  

  

  

  
  
  
  
  
>

**Comment by Tensuko** [comment]
Wir schauen mal... ich mache hier zu, so wird das ja offenbar nichts.

> Früher nutze ich nur cp. Jetzt weis ich nicht einmal wie man von a zu b kommt.

Siehe Ingame hilfe, da ist nichts kompliziert und man muss auch nirgendwo hin und her schalten.

**Comment by regs1980** [comment]
@Meditos7719 @Tensuko 
Kommen wir mal zum eigentlichen Thema zurück.

Laut Log von ihm ist es dasselbe Problem, was im MP auch schon vorliegt. 
Ich habe jetzt nach einigen Test herausgefunden, dass es am Ladezustand liegt, ist der Anhänger voll, fährt das Gespann nicht zum angegebenen Zielpunkt für die Übergabe an AD.
Dieses Problem ist im SP und auch im MP.

SP voller Anhänger bleibt stehen, mit der Meldung.

![2024-06-22 20_30_07-LS22-Fehler – OneDrive – Mozilla Firefox](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/726a5d16-d1bf-486f-a44b-a8c9b912e7da)

https://drive.google.com/file/d/1ohjxrfNCwFB706PLajDD1DwAvsRi5L11/view?usp=drive_link

[log1.txt](https://github.com/user-attachments/files/15938149/log1.txt)

SP mit ein paar Ballen auf dem Anhänger bleibt nicht stehen.

https://drive.google.com/file/d/1THXgo5u4ZFnNYVZlS4yVMi6Clt6EqNKG/view?usp=sharing

[log2.txt](https://github.com/user-attachments/files/15938168/log2.txt)

MP mit ein paar Ballen auf dem Anhänger bleibt nicht stehen.

https://drive.google.com/file/d/1XVpDrnOLSHV10dWAbZjjxsp0FynhQiLR/view?usp=drive_link

Das ist dann auch die Lösung für das Problem https://github.com/Courseplay/Courseplay_FS22/issues/3284
