### ISSUE TITLE
Issue HUD Display[BUG_SP]

### ISSUE THREAD

**Issue by Jaisalmer152** [Courseplay/Courseplay_FS22#3307]
![CP ISsue](https://github.com/Courseplay/Courseplay_FS22/assets/173494644/9fdcfe1f-4821-48fb-a180-0f684f223b6b)
**READ FIRST**

Display issue with the HUD. Doesn't display full hud 

Could you kindly support me in finding a solution? Updated to latest CP version and FS22 version

With thanks

**Comment by regs1980** [comment]
What you see there is just the mini HUD.
FS22 Keyboard settings/assignment, check under which key combination the opening and closing of the CP HUD is stored.

**Comment by Tensuko** [comment]
It is the info display where stuff like finished work and stuff is shown.
Read the ingame help about it.

**Comment by Jaisalmer152** [comment]
![CP ISsue 2](https://github.com/Courseplay/Courseplay_FS22/assets/173494644/7c1be54b-7732-4e04-bc4b-e7c031f01755)

I've tried various settings w/o success

The issue appeared out of nothing

**Comment by elferia** [comment]
Hi

I had the same issue.

All you have to do is disabling HUD for gamepad 😄
