### ISSUE TITLE
[BUG_SP]CLAAS AXION 5000 All-wheel steering mode with a trailer/equipment, struggle to follow the calculated route

### ISSUE THREAD

**Issue by harokyang** [Courseplay/Courseplay_FS22#3309]
**Steps to reproduce**
Drive a CLAAS AXION 5000
Tow something heavy like a DEMCO 2200 auger wagon, or KINZE 4905 planter
Let Courseplay to do the work, enable debug view, you can see Courseplay try to follow the calculated route but eventually off the chart

**Actual behavior**
Courseplay should be able to follow the calculated route
Because I can successfully drive the same turn of the calculated route in Front-Wheel steering mode myself

**Expected behavior**
Courseplay should drive CLAAS AXION 5000 in Front-Wheel steering mode when towing something
The All-Wheel steering mode is only good for turning if drive alone or attached with something with no wheel

**Screenshots**
<img width="996" alt="CLAAS AXION 5000 + DEMCO 2200(Wheel)" src="https://github.com/Courseplay/Courseplay_FS22/assets/34699358/f5c0fb1c-d917-4864-a907-9bee191f0451">

**Courseplay version**
Version used:  7.4.1.3

**Comment by harokyang** [comment]
Additional test shows that the weight of the trailer impact heavily on turning
I have 2 tests with the auger wagon empty or full
In Front-Wheel steering mode, the turning is almost the same for both empty and full wagon
In All-Wheel steering mode, the turning is much much much harder with full wagon than with empty wagon

**Comment by Tensuko** [comment]
The fill level of the trailer doesnt matter at all for the course calculation...

But when the trailer hits the back wheel it blocks the tractor more with a full trailer.
However, we dont make a difference in the steering mode for turn radius and that wont change for fs22.

Will not fix it.
Use all wheel turn mode and if the radius is too small, then use our vehicle config (discribed on the wiki page).

**Comment by harokyang** [comment]
I followed the wiki and added the xml
But nothing changed for the generated course

```<VehicleConfigurations>
    <Vehicle name="data/vehicles/claas/xerion5000.xml"
			 turnRadius = "5"
    />
</VehicleConfigurations>```

Here is the game log about the xml reading
2024-06-23 17:48 :02 [info lp4986] Loading vehicle configuration from E:/Users/harok/Documents/My games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml ...
2024-06-23 17:48 Warning: Loading file with invalid case 'E:/Users/harok/Documents/My games/FarmingSimulator2022/modSettings/FS22_Courseplay/vehicleConfigurations.xml'.
2024-06-23 17:48 :02 [info lp4986] Reading configuration for data/vehicles/claas/xerion5000.xml
2024-06-23 17:48 :02 [info lp4986] \__ turnRadius = 100.0

I tried radius with 5, 10, 30, 50, 100
They all generated the same radius course

**Comment by dkfiremann** [comment]
Have you tried without data/vehicles/claas/ ?
Wiki only says the xml filename, not a path. 
Make sure that the filename match the xml filename that is also in your zipped mod. 
![image](https://github.com/Courseplay/Courseplay_FS22/assets/25283454/e3d75acb-7435-4632-8b6e-8181aa92817b)

**Comment by Tensuko** [comment]
You did it wrong.
Dont add the path, xml only!

**Comment by harokyang** [comment]
> You did it wrong. Dont add the path, xml only!

Thanks, it's working now
I need to increase the turnRadius from 8 to 13 to manage the course

**Comment by harokyang** [comment]
For anyone who may encounter this issue and find this ticket here
I finally solved the issue by attached a weight in front of Xerion 5000
Never thought the weight could also help in towing a self-wheeled trailer
A single 1.5t weight is enough to provide turning grip against a fully loaded auger wagon
