### ISSUE TITLE
Problem mit ziehbaren Maschinen im Vorgewende mit der 7.0.0.11 ist immer noch vorhanden

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/Courseplay_FS22#331]
hey habe mir habe mir grade die 7.0.0.11 runtergeladen und das problem mit dem wendem im vorgewende ist weiterhin vorhanden eventuel nochmal die alte issues davon reopen 
![fsScreen_2022_01_03_01_15_14](https://user-images.githubusercontent.com/71101944/147893130-67ee4e9d-5a4b-4aef-989e-2fe0b9e3f579.png)

**Comment by Tensuko** [comment]
Das habe ich bereits um issue erklärt, das ist geräteabhängig und für dieses ist es eingetragen
