### ISSUE TITLE
[Question] Wenderadius

### ISSUE THREAD

**Issue by BthatKing** [Courseplay/Courseplay_FS22#3310]
Hallo, 

kann man den Wenderadius für Gespanne im Spiel ändern?
Falls nicht, wie ändere ich das?

Meine Schlepper crashen immer wieder in die AD Abfahrer, weil der Radius zu gering ist.

![20240623220835_1](https://github.com/Courseplay/Courseplay_FS22/assets/156541112/3fe49575-657a-4c74-8c4a-ed5545cf3c70)

**Comment by Tensuko** [comment]
Ingame nicht.
Welcher ÜLW ist das?

**Comment by BthatKing** [comment]
Der hier 

https://forbidden-mods.de/filebase/file/42198-ls22-hawe-ulw4000-als-crawler-version-mit-bandfahrwerk/

**Comment by regs1980** [comment]
@BthatKing 
erstell dir mal eine https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file mit 

<Vehicle name="ulw4000.xml"
             turnRadius = "10"
/>
Es geht auch 12, da der auch ein Kettenlaufwerk hat, was bestimmt nicht mitlenkt.
Einfach mal ein paar Werte probieren. 

Ist bei der ULW 4000 im Spiel auch ein Problem, wenn du einen Fendt 1000 Vario oder einen CLAAS XERION 5000 davor hängst.
Bei mir klappt es mit 10, er fährt nicht mehr gegen den zweiten Abfahrer.

**Comment by Wobby1** [comment]
Doch das Bandlaufwerk lenkt (Nachlaufachsen Funktion ) ein aber BthatKing hat auf meine gleiche Nachfrage auch den INGAME HAWE mit Rädern verwendet und das Gleiche Phänomen festgestellt... ich selber habe das mit mehreren verschiedenen Gespannen getestet.
- Fendt 1050 mit Krampe Bandit 800 , Fliegl ASW288 , HAWE INGAME Überlader , SaddleTrac Shuttle
- auch der Saddle ohne Trailer aber mit Shuttle oben drauf fuhr in dien Räder des Abholers ...

**Comment by Tensuko** [comment]
Es ist halt ein zu kleiner turn radius.
Siehe Wiki für eigene vehicle config.
Für den 22er werden wir da nichts mehr anpassen.

Was mich bei den ganzen Gespanne interessieren würde.... wenn man die mit Giants von A nach B fahren lässt, wie lenken die?
Wie auch immer, ich mache hier erst mal zu, können aber weiter hier schreiben.

**Comment by Wobby1** [comment]
> Es ist halt ein zu kleiner turn radius. Siehe Wiki für eigene vehicle config. Für den 22er werden wir da nichts mehr anpassen.
> 
> Was mich bei den ganzen Gespanne interessieren würde.... wenn man die mit Giants von A nach B fahren lässt, wie lenken die? Wie auch immer, ich mache hier erst mal zu, können aber weiter hier schreiben.

Was  heisst denn das ? "Wie lenken die ?" Die Trailer oder wie die GIANTS Helfer das regeln und ob das klappt ? Ich hab das ja auch mit dem CLAAS Saddle Trac und einem Shuttle das ich gabut habe oben drauf getestet da hat man ja nur den Radius vom SaddleTrac ...

**Comment by BthatKing** [comment]
Kann man nicht einfach den Wenderadius für alle Fahrzeuge auf einmal ändern, statt jedes Fahrzeug einzeln aufzulisten?

**Comment by BthatKing** [comment]
Ich meinte damit, dass dann ich einfach z.B. 30m als Standart festlegen kann.

**Comment by regs1980** [comment]
> Ich hab das ja auch mit dem CLAAS Saddle Trac und einem Shuttle das ich gabut habe oben drauf getestet da hat man ja nur den Radius vom SaddleTrac ...nach Informationen anderer User die das auch festgestellt haben war das mit v7.4.1.2 noch alles ohne Probleme ..

Also ich habe das jetzt mal getestet mit folgenden Mods.

InGame Vanilla

CLAAS XERION 4200 SADDLE TRAC
CLAAS XERION 5000
Fendt 1050 Vario
Hawe ULW 4000

Custom Mod

[HAWE ULW4000 als Crawler Version](https://forbidden-mods.de/filebase/file/42198-ls22-hawe-ulw4000-als-crawler-version-mit-bandfahrwerk/)
[SaddelTrac 4200 Shuttle Pack](https://forbidden-mods.de/filebase/file/41963-fs22-multi-saddeltrac-4200-shuttle-pack/)

Verwendete VehicleConfigurations.xml.

![2024-06-25 22_47_24-C__Users_Administrator_Documents_My Games_FarmingSimulator2022_modSettings_FS22_](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/0f483cc8-d6e6-47e0-bda0-7029d26e5942)

Erkenntnis aus dem Test der Vanilla Hawe ULW 4000 braucht keinen größeren Turn Radius mehr, ist sogar besser geworden.

Video zeigt Gespanne mit verschiedenen Geschwindigkeiten. 

@Wobby1 
Leider sieht man auch in dem Video, dass dein Mod das Problem ist, er braucht einen größeren Turn Radius mit dem Kettenlaufwerk als die Original-Plattform. 

https://drive.google.com/file/d/1NdisoIcCGBjw1AfNxdAoDrB9gZuO31Qe/view?usp=drive_link

Zu deinem SaddelTrac 4200 Shuttle Pack, das Video habe ich nur so gemacht, weil ich mal wissen wollte, ob es funktioniert, keine Ahnung, warum der den wartenden LKW so komisch anfährt. 

https://drive.google.com/file/d/1QJeyy-7zvPIi4HSSaUVP6IsSOR--5Kxn/view?usp=drive_link

**Comment by Tensuko** [comment]
Alles auf einen wert und du hast nur noch Platzprobleme. Das wäre der Supergau.
