### ISSUE TITLE
[BUG_SP]Bale Loader no longer finish job and report "Need to Unload" after capacity full

### ISSUE THREAD

**Issue by harokyang** [Courseplay/Courseplay_FS22#3313]
**Steps to reproduce**
CP 7.4.1.3
Use a tractor with the RBM2000 to do a CP bale collection job in Field 71 in Elmcreek
There are more than 24 bales to collect

**Actual behavior**
After 24 bales loaded, the vehicle stays idle, engine still running, collect arm still unfolded
CP UI shows the job is still in progress (green arrow), in debug mode shows a course to the outside of field
But nothing will ever happen, not even send a message about "Need to Unload"

**Expected behavior**
Before upgraded to 7.4.1.3
Use the 7.4.0.0 version in modhub
If bale loader is full, it will fold the collect arm, stop the cp job, and raise a "Need to Unload" event to warning you about it

**Screenshots**
![image](https://github.com/Courseplay/Courseplay_FS22/assets/34699358/b5a8ba4a-927d-426c-ba93-8d29cc774d97)

**Courseplay version**
Version used: 7.4.1.3

**Log**
[log.txt](https://github.com/user-attachments/files/15987049/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Vanilla Massey Ferguson MF 7726S + Anderson RBM2000

**Relevant script mods**
AutoDrive 2.0.1.6

**Comment by harokyang** [comment]
If all bales in field collected before capacity full
Then the vehicle can successfully exit the field, fold the arm, stop engine and report job finished

**Comment by MacedonskyAlex** [comment]
I have the same problem

**Comment by coatsy35** [comment]
Does weird things when starting a new field as well at the moment. It plots a course at the far side of the field and then goes to places where there are no bales and generally get stuck, when you stop it and start it again it will be ok until the next time it enters the field and it repeats. Some more data and lot for you below

![fsScreen_2024_07_24_14_31_44](https://github.com/user-attachments/assets/b6e75360-9596-4d31-bb32-7510d2a35436)
![fsScreen_2024_07_24_14_32_28](https://github.com/user-attachments/assets/4e6a9231-be01-4fa7-a697-0ab0a6b338d0)

[log.txt](https://github.com/user-attachments/files/16362874/log.txt)

**Comment by regs1980** [comment]
@coatsy35 
This looks more like a generated course that is still in the vehicle and was not removed before the bale collection trolley was attached.

**Comment by coatsy35** [comment]
> @coatsy35 This looks more like a generated course that is still in the vehicle and was not removed before the bale collection trolley was attached.

It’s not one I’ve set. This is a new map and new tractor. It does try to switch to fieldwork instead of collecting in this version of CP a lot but thats known issue apparently

**Comment by erksartori** [comment]
Também estou com esse problema, ele carrega todos os fardos que cabe na colheitadeira, e fica parado, ele não esta dando sequencia, eu tenho que ir lá, desligar o CP e ativar o AD manualmente.

I'm also having this problem, it loads all the bales that fit in the harvester, and it stops, it's not working, I have to go there, turn off the CP and activate the AD manually.
