### ISSUE TITLE
Collision detection[Question]

### ISSUE THREAD

**Issue by falcon470** [Courseplay/Courseplay_FS22#3316]
Whats the best setting for this, i see fs19, fs22 and off, but the setting says something about advanced collision detection is that off by default id really like to have it working if possible

**Comment by Tensuko** [comment]
You are at the wrong github repository.
Your question belongs to autodrive and that I can't answer you.

**Comment by falcon470** [comment]
wow thanks for the quick reply, i apoligize i just realized that myself, brain defaulted to courseplay
