### ISSUE TITLE
[BUG] Course editor is broken on existing saves

### ISSUE THREAD

**Issue by MulleDK19** [Courseplay/Courseplay_FS22#3317]
**Steps to reproduce**
Add Courseplay to an existing save and attempt to open the course editor.

**Actual behavior**
The course editor won't open, and after clicking the button to open the editor, any attempt to open the Shift+P buy menu will destroy the game.

**Expected behavior**
It works..

**Courseplay version**
Version used: 7.4.0.0

**Log**
[log.txt](https://github.com/user-attachments/files/16039801/log.txt)

**Map**
Any

**Vehicles/ implements involved**
Any

**Relevant script mods**
Only Courseplay

**Comment by Tensuko** [comment]
Pls update to the latest github Version and try again:
https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by MulleDK19** [comment]
> Pls update to the latest github Version and try again

Same issue.

**Comment by MulleDK19** [comment]
Video

https://github.com/Courseplay/Courseplay_FS22/assets/3169809/80e35abe-5540-4a63-96b8-bdb59af4324c

**Comment by Tensuko** [comment]
With all my mods active.
https://drive.google.com/file/d/1xY9BnhqX7S3smrZoekYLRSbL7X-Z154A/view?usp=drive_link

**Comment by Tensuko** [comment]
Found the Error.

**Comment by MulleDK19** [comment]
> Found the Error.

Cool. Any ETA on a fix, or any workarounds to get it running on an existing save in the meantime?

**Comment by Tensuko** [comment]
Did you try save and reload savegame?

**Comment by MulleDK19** [comment]
> Did you try save and reload savegame?

Nope, that worked. Thanks.

**Comment by lirarn13** [comment]
I have the same problem. What was wrong?

**Comment by Tensuko** [comment]
Will not address this in FS22, but ofc will make sure it works on FS25.
Please understand this.
And there is a workarround for that so its okay I guess.
