### ISSUE TITLE
[Question] Dropped Something on Keyboard And the Text in the attachment popped up.

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#3319]
I tried to google the answer but everything thinks I have debug mode on which I don't. How do I turn this off? I looked in setting and deactivated anything I didn't know about, but it is still there.
![20240629160105_1](https://github.com/Courseplay/Courseplay_FS22/assets/24764870/3835648a-6cc7-4836-841b-a5d6cb4146e5)

**Comment by Tensuko** [comment]
Ctrl+3 iirc.
Check F1 Menu. It is our adv. debug menu.

**Comment by lcc1211** [comment]
Thank you. Left shift - 4 but it didn't show until I right-clicked the mouse.
