### ISSUE TITLE
[Feature] Fieldwork Support for Forage Harvester w/ Pickup Header 

### ISSUE THREAD

**Issue by SilverWheelz** [Courseplay/Courseplay_FS22#332]
**What is the problem this feature/enhancement solves?**
As of now, both CP and Giant's Helper don't support the forage harvester + pickup header combo. Pressing H will bring you to the helper but the only available job is "GoTo".

**Describe the solution you'd like**
Be able to generate/load courses with a Forage Harvester w/ a pickup header so it can pickup windrows and I can drive alongside it with a semi and trailer. Was planning to load the course I used to make my windrows or simply use the same workwidth as the windrower to align the pickup header with the windrows.

**Describe alternatives you've considered**
Use a forage wagon or bale and wrap the grass.

**Additional context**
![Screenshot (482)](https://user-images.githubusercontent.com/94125770/147896202-5d572895-863c-4186-bbf7-03aed59b7148.png)

**Comment by Shentar1** [comment]
If I may jump in on this, I have also noticed that a forage wagon cannot be used for this type of fieldwork either, might be worth a look

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.
