### ISSUE TITLE
windrower settings problem

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3320]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Try to generate a job, but appear an error

**Actual behavior**
When i try to create a job, appear an error

**Expected behavior**
A job

**Courseplay version**
Version used: 7.4.1.3

**Map**
Bucks Country PA

**Vehicles/ implements involved**
Claas arion 660 with agco 650 and kuhn ga 15131

Mod yes/no ?
No
![Farming Simulator 22 30_06_2024 11_43_19](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/584e06cc-7328-4af6-a957-84ddf62a11c7)
![Farming Simulator 22 30_06_2024 11_48_34](https://github.com/Courseplay/Courseplay_FS22/assets/66116155/e7b313e1-4360-4d05-89a3-636b0b713840)

**Comment by Tensuko** [comment]
No log, can't help.
Also a screenshot where I can see the field would be helpful to see what it looks like.
Some fields are just impossible or there is something wrong with the field shape.

**Comment by Trivelleitor** [comment]
Ok, if i change headland corners from sharp to smooth it works. Why?

**Comment by Tensuko** [comment]
That means the generator can't find sharp turns in the corners of the field.

**Comment by Trivelleitor** [comment]
Ok, so what can i do?

**Comment by Tensuko** [comment]
Dont use sharp turns.
