### ISSUE TITLE
[BUG_SP] Error: Running LUA Method 'Update

### ISSUE THREAD

**Issue by ThomasLear** [Courseplay/Courseplay_FS22#3322]
Hello,

I recently started using the Phiber Dash Trailer with the Seed Tender attacher mod. When I purchase both in game, I get an error regarding CoursePlay around the LUA Update. Full Error code below along with links to mods. 

 Error: Running LUA method 'update'.
C:/**Redacted**/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpVehicleSettings.lua:444: bad argument #1 to 'min' (number expected, got nil)

Trailer Mod: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=290976&title=fs2022

Seed Tender Mod: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=241288&title=fs2022

Thanks,

TL

**Comment by Tensuko** [comment]
Mod Issue.
