### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Rioufa** [Courseplay/Courseplay_FS22#3323]
**Actual behavior**
Course play downloaded and installed in mod folder, but unable to see it appearing in the mod selection page before starting the game and not appearing in the game menu afterward. Playing on Mac OS Ventura 13.4, with FS22 Apple Store version.

**Courseplay version**
Version used: latest one downloaded from server v 7.4.1.3

**Log**
Attached

[log.txt](https://github.com/user-attachments/files/16049534/log.txt)

**Comment by Tensuko** [comment]
Farming Simulator 22
  Version: 1.12.0.0 b26426
Your game version is too old.
Update your game!

Beside that, not sure if this will even work on a Mac.
