### ISSUE TITLE
Einsammeln von Stroh, Gras, Heu usw. mit Courseplaykurs

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#333]
Bei LS19 konnte man früher mit einem Traktor plus Ladewagen das Stroh usw. einsammeln, wenn man den Kurs vom Drescher aus dem CP nahm.
Wäre es auch möglich, dass es auch im neuen Courseplay eingebaut wird ?
Bis jetzt macht ihr Entwickler eine SUPER Arbeit. Danke Euch dafür...

**Comment by haamic** [comment]
Das ist doch jetzt schon möglich. Wenn der Drescher Kurs gespeichert ist, kannst du den auf den Traktor laden und mit dem LadeWagen nutzen. Allerdings sind Ladewagen momentan noch nicht von Cp unterstützt. Wenn du das kopieren meinst eines existierenden Kurses auf einem Fahrzeug, wie es früher möglich war, weiß ich nicht, ob dies überhaupt noch möglich ist, ist ja vieles neu und anders geworden.

**Comment by StefanTreutler1974** [comment]
Das wäre doch mal very nice, wenn Courseplay die verschiedene Ladewagen unterstützen könnten.

Gesendet von Mail für Windows

Von: Farmer_DD
Gesendet: Montag, 3. Januar 2022 08:15
An: Courseplay/Courseplay_FS22
Cc: StefanTreutler1974; Author
Betreff: Re: [Courseplay/Courseplay_FS22] Einsammeln von Stroh, Gras, Heu usw.mit Courseplaykurs (Issue #333)

Das ist doch jetzt schon möglich. Wenn der Drescher Kurs gespeichert ist, kannst du den auf den Traktor laden und mit dem LadeWagen nutzen. Allerdings sind Ladewagen momentan noch nicht von Cp unterstützt. Wenn du das kopieren meinst eines existierenden Kurses auf einem Fahrzeug, wie es früher möglich war, weiß ich nicht, ob dies überhaupt noch möglich ist, ist ja vieles neu und anders geworden.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StefanTreutler1974** [comment]
Was ich damit meinte ist, dass der Ladewagen lädt und wenn er voll das dann der Abfahrer mit Autodrive zum entladen fährt.

**Comment by haamic** [comment]
Das wurde schon öfters hier von den Entwicklern geschrieben. erst muss Cp nahezu fehlerfrei sein, Danach kommt die Anbindung zu AD

**Comment by Th301** [comment]
Moin zusammen,

vielleicht bin ich (mal wieder) zu blöd, aber irgendwie habe ich nicht rausgefunden, wie man die Kurse speichert und lädt.
Wenn ich auf "Kurs Speichern" klicke, dann passiert irgendwie nichts. Die Buttons ändern sich und es kommt ein "Activate" Button. Aber eine Abfrage wie der Kurs heißen soll oder so kommt nicht.

**Comment by xCrushedIcex** [comment]
Ladewagen füllen ohne abfahren sollte aber recht einfach zu implementieren sein. Ist ja im Prinzip das gleiche wie Ballen pressen. 
Vielleicht kommt es ja mit einer der nächsten Versionen :)

**Comment by Tensuko** [comment]
Das wurde schon x mal gefragt und x mal beantwortet das es wieder kommt ...
Einfach mal abwarten und nicht immer fragen wann kommt dies oder das

**Comment by StefanTreutler1974** [comment]
Dann werden wir mal abwarten und Tee trinken. Dementsprechende Bewertung folgt.
