### ISSUE TITLE
Debug progress of Course Generator (large custom fields)

### ISSUE THREAD

**Issue by thobck** [Courseplay/Courseplay_FS22#3331]
s there any way of debugging while Course Generator is calculating? Happens to me, on large custom fields I am creating with plow, the course generator take much time (several hours) to respond and sometimes I have no option other than cancel this process because I don´t know if it stuck.

**Comment by Tensuko** [comment]
There is no debug while running. How could it debug if lua is busy with calculation? Patience is the key. Several hours I dont think so.
