### ISSUE TITLE
[Question] Radlader fährt gegen Anhänger

### ISSUE THREAD

**Issue by Onkel2000** [Courseplay/Courseplay_FS22#3333]
Hallo,

der Radlader der das Silo entleert, fährt nach kurzer Zeit, nach dem Abkippen in denn Anhänger, vorwärts gegen denn Anhänger. Dies passiert auch wenn er mehr Platz zum Wenden hat.
Meine Frage ist, wieso macht er das? Ist das ein fehler von mir?

CP Version: 7.4.1.3
Ich habe mal ein kleines Video davon gemacht, ich hoffe man sieht dies gut.Vielleicht könnt ihr mir Tipps geben. Alle Fahrzeuge + Zubehör sind in diesem Fall keine Mods. 

[log.txt](https://github.com/user-attachments/files/16256311/log.txt)

https://www.youtube.com/watch?v=y69vfKGxqgw

LG

**Comment by Tensuko** [comment]
Is halt super knapp.
Die länge der Gabel mit zu berechnen für den pathfinder ist zu kompliziert weil es von der position von dieser abhängt.
Ist leider pech.
Stell den Trailer seitlich hin das könnte besser sein.
