### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by JacoVerm** [Courseplay/Courseplay_FS22#3334]
I am currently experiencing an issue when trying to plow a newly created field using Courseplay on a dedicated MP server hosted on GPortal on No Mans Land Map

Drawing the custom field and saving works fine, then generating the field for the worker also works fine, the problem is when the working is busy plowing, the ground does not actually get plowed. When you sit in the vehicle while the working is working then everything works, but when you leave the vehicle then the field does not get plowed.
Sometimes it will look like the field is plowed, but as soos as you try to plant on it manually the field resets back to normal grass in small blocks as soon as the planter touches it.
We also have issues with the server not saving properly and losing hours of play time but not sure if the issues are related

We are using the latest versions of No mans land as well as Courseplay

**Comment by Tensuko** [comment]
We have no influence in "plow create field" setting. So this can't rly be an Issue of CP.
Also fill in the template! logfile is a must have.
