### ISSUE TITLE
geräte heben/senken

### ISSUE THREAD

**Issue by OpiGunnar** [Courseplay/Courseplay_FS22#3335]
Warum stellen sich die funktionen gerät senken / heben immer wieder auf spät / früh um,obwohl ich als admin das für den server umgekehrt haben möchte . jede art des speicherns wird schlicht ignoriert,nach jedem relogg stehet es wieder auf gerät früh heben und gerät spät senken,nervt etwas :-(

lg opi

**Comment by Tensuko** [comment]
Bug.... haben mit der aktuellen version ein paar MP Probleme.

**Comment by OpiGunnar** [comment]
ah,ok, hab noch die 7.4.0.0 drauf.ich teste ;-)

**Comment by Tensuko** [comment]
Hmm bei der modhub ist das nicht bekannt.
Aber dir ist klar, dass es pro Fahrzeug und nicht pro Gerät gespeichert wird?

**Comment by OpiGunnar** [comment]
ähm ..... ok,das is mir nu neu
