### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by rudger-wolvram** [Courseplay/Courseplay_FS22#3337]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Unsure, but, I created a long narrow olive orchard near the map boundary on the east side. About 25 acres.
Custom fields drawn around it are ignored for some reason.
Place vehicle on field or select field with mouse via Field Position option.
Wait for CP to detect field.
Field is drawn as 1 row diagonal from SE to NW corner.

**Actual behavior**
Field is drawn as what appears to be a 1 row diagonal from SE to NW corner and doesn't detect the field in its entirety.

**Expected behavior**
The field is detected properly and can be set up with courses.
This is the only field on the map that does this and may be a literal edge case with Vine detection. All other fields near the border are standard fields.

**Screenshots**
The first screenshot is what happens when you select CP Work and it detects the field you're on.
![FS22_Courseplay_BugSS1](https://github.com/user-attachments/assets/ed460d50-e307-4909-bc5a-a06d4d41a94c)

This one, I created a custom field, selected inside it with field position, CF is ignored. Also, that break in the middle of the field was my attempt as shrinking it down to see if that was the problem.
![FS22_Courseplay_BugSS2](https://github.com/user-attachments/assets/cda59345-8447-41e7-9cc2-a283cae63c74)

Just showing where the edge of the map is in relation to the field, in case that could be an issue.
![FS22_Courseplay_BugSS3](https://github.com/user-attachments/assets/05bf2c1a-01c3-4fff-b360-09f0cc435a0d)

**Courseplay version**
Version used: 7.4.1.3

**Log**
Field causing problems. It appears corner detection is broken somehow.
2024-07-22 16:38 :33 [info lp3571946] Scanning field 0 on Clarkson US 4x, prefer custom fields true
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Start scanning field 0 at 1958.3/471.2
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Field edge found at 1990.0/537.0 after 366 steps
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Inserted a corner waypoint (12, -90.5°), -3.6 ahead of the last
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Inserted a corner waypoint (23, -89.4°), -2.5 ahead of the last
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Inserted a corner waypoint (138, -83.7°), 0.0 ahead of the last
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Inserted a corner waypoint (152, -90.5°), -3.7 ahead of the last
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Field contour with 254 points generated, total rotation -362.1°
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Field contour simplified, has now 254 points
2024-07-22 16:38 :33 [courses lp3571946] Mach 2R/771: FieldScanner: Intermediate points added, has now 254 points
2024-07-22 16:38 :34 [courses lp3571946] Mach 2R/771: VineScanner: Found a vine node within 0.31m
2024-07-22 16:38 :35 [courses lp3571946] Mach 2R/771: VineScanner: Found 499 columns to the left.
2024-07-22 16:38 :36 [courses lp3571946] Mach 2R/771: VineScanner: Found 499 columns to the right.
2024-07-22 16:38 :44 [courses lp3571946] Mach 2R/771: VineScanner: Found 998 number of lines for a width of 3.00
2024-07-22 16:38 :44 [field work lp3571946] Mach 2R/771: Found vine nodes, generating a vine field border.
2024-07-22 16:38 :44 [courses lp3571946] Mach 2R/771: VineScanner: vineOffset: -0.000000

Log from Grape orchard in middle of map that works properly.
2024-07-22 16:42 :42 [info lp3580067] Scanning field 0 on Clarkson US 4x, prefer custom fields true
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Start scanning field 0 at 141.1/1539.5
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Field edge found at 176.5/1613.0 after 409 steps
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Inserted a corner waypoint (11, -36.7°), -0.2 ahead of the last
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Inserted a corner waypoint (34, -72.2°), -1.7 ahead of the last
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Inserted a corner waypoint (170, -21.8°), -1.3 ahead of the last
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Inserted a corner waypoint (184, -85.9°), -3.0 ahead of the last
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Field contour with 285 points generated, total rotation -365.5°
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Field contour simplified, has now 285 points
2024-07-22 16:42 :42 [courses lp3580067] Mach 2R/771: FieldScanner: Intermediate points added, has now 285 points
2024-07-22 16:42 :44 [courses lp3580067] Mach 2R/771: VineScanner: Found a vine node within 0.90m
2024-07-22 16:42 :44 [courses lp3580067] Mach 2R/771: VineScanner: Found 12 columns to the left.
2024-07-22 16:42 :44 [courses lp3580067] Mach 2R/771: VineScanner: Found 13 columns to the right.
2024-07-22 16:42 :44 [courses lp3580067] Mach 2R/771: VineScanner: Found 25 number of lines for a width of 3.00
2024-07-22 16:42 :44 [field work lp3580067] Mach 2R/771: Found vine nodes, generating a vine field border.
2024-07-22 16:42 :44 [courses lp3580067] Mach 2R/771: VineScanner: vineOffset: -0.000000

**Map**
Clarkson US 4x

**Vehicles/ implements involved**
Tractors, Harvesters, doesn't matter, it happens with any vehicle, modded or not. This occurs before the vehicle comes into play.

**Relevant script mods**
Have many mods, however, this appears to be pure CoursePlay, it's dealing with field detection before any other mods would touch it (e.g. Autodrive, followme, etc.)

Full mod list from directory names.
FS22_150kWBGA.zip
FS22_3point_gooseneck_hitch.zip
FS22_4940.zip
FS22_980K.zip
FS22_adjustWorkingSpeed.zip
FS22_Agrodaje.zip
FS22_alpineFarmbuildings.zip
FS22_AmericanFarmhouse.zip
FS22_AnimalProducts_AutoShipping.zip
FS22_Autoload_Belt.zip
FS22_AutomaticWateringSystem.zip
FS22_Average_Wooden_Shelter.zip
FS22_A_ProductionRevamp.zip
FS22_BackRoadsCounty4x.zip
FS22_BaleAndVehicleShelter.zip
FS22_BalerHitchPack.zip
FS22_BAMS.zip
FS22_BandeiranteVirtuos1300.zip
FS22_Bavarian_Farm_Pack.zip
FS22_BigBud_Pack.zip
FS22_BigDisplay.zip
FS22_Brickramp.zip
FS22_Bridges_Package.zip
FS22_BuildingsOfNorway.zip
FS22_bunkerSiloSet.zip
FS22_BunkerSiloUtilities.zip
FS22_BuyableManure.zip
FS22_BuyableSlurry.zip
FS22_buyProductionInput.zip
FS22_Calmsden.zip
FS22_CarpathianCountryside.zip
FS22_caseIHMagnum7240Pro.zip
FS22_CaseIH_340_400TSE_FL.zip
FS22_CaseIH_Trident5550.zip
FS22_CeresMaster3570.zip
FS22_claasDirectDisc600.zip
FS22_claasDiscoPack.zip
FS22_Claas_Jaguar900_Type502.zip
FS22_Claas_Krone_Baler_Pack_With_Lizard_R90.zip
FS22_Claas_Xerion.zip
FS22_Clarkson.zip
FS22_Collect900_Poplar_SugarCane.zip
FS22_colorConfigurator.zip
FS22_colossusHarvester.zip
FS22_ConsumablePurchaseStation.zip
FS22_Courseplay.zip
FS22_cultivatorFieldCreator.zip
FS22_CutBales.zip
FS22_D6N.zip
FS22_D6N_crossplay.zip
FS22_DashboardLive.zip
FS22_DroneDelivery.zip
FS22_dropdeckTrailer53Ft_AutoPack_crossplay.zip
FS22_EasyDevControls.zip
FS22_EmptyPalletProduction.zip
FS22_Engine_Starter.zip
FS22_EnhancedDragHoses.zip
FS22_exhaustExtension.zip
FS22_ExtendInputHUD.zip
FS22_ExtraLargeSheepBarn.zip
FS22_FasterConveyorBelts.zip
FS22_fellaGrasslandEquipment.zip
FS22_FieldCreator.zip
FS22_FlieglTimberRunnerAutoload.zip
FS22_FloodLightPole.zip
FS22_FollowMe.zip
FS22_foragePickup.zip
FS22_ForageStrawPickup.zip
FS22_ForestryBridges.zip
FS22_FreeLandscapingTools.zip
FS22_FrontierMap.zip
FS22_FrontLifter.zip
FS22_GL860_MultiPlanter.zip
FS22_GothicStyleBarn.zip
FS22_granary.zip
FS22_grass_mod.zip
FS22_halfTimberedFarm.zip
FS22_HM400.zip
FS22_horseman.zip
FS22_IncreaseLightRange.zip
FS22_IslandBasernMF.zip
FS22_JohnDeere3765.zip
FS22_johnDeere9R4213Pack.zip
FS22_kinzeMultiFruitPlanterPack.zip
FS22_KroneSwadro2000.zip
FS22_kvernelandEnduroPro5000F.zip
FS22_kvernelandIXterB18.zip
FS22_LacotecLHII.zip
FS22_Large_Shed.zip
FS22_LazyAcres.zip
FS22_limitedPalletsFix.zip
FS22_Lizard2630TillagePack.zip
FS22_LizardApache.zip
FS22_LizardHotRod.zip
FS22_LizardStonePicker.zip
FS22_Lizard_Adapter5R.zip
FS22_Lizard_Gucio_N026.zip
FS22_Lizard_LightSaber.zip
FS22_Lizard_MaverickX3.zip
FS22_Lizard_MaxTandem.zip
FS22_Lizard_PCP6000.zip
FS22_lizard_rumblerVan_crossplay.zip
FS22_Lizard_TandemSeries.zip
FS22_Lizard_Trailed_Windrower.zip
FS22_LogBridgePack.zip
FS22_LumberStorage.zip
FS22_marangonFoldbar.zip
FS22_MF_FrontHydraulic.zip
FS22_mini_BGA.zip
FS22_MKII_Conveyor_Pack.zip
FS22_mobileBridge.zip
FS22_mobileWorkshop.zip
FS22_MorePower.zip
FS22_MPAgro_LinhaZ.zip
FS22_mrhMultipurposeSheds.zip
FS22_MultiCropGreenhouses.zip
FS22_Multifruit_Buying_Station.zip
FS22_netWrap_addon.zip
FS22_newHolland8340.zip
FS22_newHollandTX32.zip
FS22_NewLands.zip
FS22_nitroBoost.zip
FS22_noMansLand.zip
FS22_NoNeedToRoll.zip
FS22_ObjectStorage.zip
FS22_OldBrickBarn.zip
FS22_OldTimeShedPack.zip
FS22_Old_Shed01.zip
FS22_paintAndTerraformAnywhere.zip
FS22_Pigfood_Buying_Station.zip
FS22_PlanET_BGA_Modular.zip
FS22_ProductionRevamp_Productions.zip
FS22_productionsLimitIncreaser120.zip
FS22_Provitis_mp122Ocea_Twin.zip
FS22_Quadro_Pro_Baler_Pack.zip
FS22_Rake_Lizard_R90.zip
FS22_RanchHouse.zip
FS22_realDirtColor.zip
FS22_realDirtColorTracks.zip
FS22_realDirtFix.zip
FS22_realDirtParticles.zip
FS22_RealMower.zip
FS22_RearHitch.zip
FS22_RedBarnPack.zip
FS22_Rennebu.zip
FS22_RM_Subsidy.zip
FS22_SaltStorage.zip
FS22_Scorpio710.zip
FS22_sellEverything.zip
FS22_SeppiM_MultiplaS9.zip
FS22_series9R.zip
FS22_SilageBoss.zip
FS22_SilageFork.zip
FS22_SiloStorageDistribution.zip
FS22_SlurryBuyingStation.zip
FS22_SmallWoodStorage.zip
FS22_Snuefelstueck.zip
FS22_SpawnPalletsStacked.zip
FS22_stalkBusterPack.zip
FS22_strawHarvestPack.zip
FS22_Strumyk350L.zip
FS22_SuperPerson.zip
FS22_SuperShopSorting.zip
FS22_SwatherPack.zip
FS22_T4_40_Multi_Harvester_Pack.zip
FS22_tardisLoader.zip
FS22_TelehandlerPalletFork.zip
FS22_terraDosT4_40.zip
FS22_terraFelis3Evo.zip
FS22_The_Forgotten_Hills.zip
FS22_The_Old_Stream_Farm.zip
FS22_ThreepointAdapter.zip
FS22_TH_Farm.zip
FS22_TLX3500_Series.zip
FS22_TLX_Phoenix.zip
FS22_TLX_Phoenix_WF.zip
FS22_TLX_X52_Enclosed.zip
FS22_torion1914.zip
FS22_TrailerAdapter.zip
FS22_TrailerJointBlock.zip
FS22_Trailer_Support.zip
FS22_TreeBGone.zip
FS22_Tree_Devourer.zip
FS22_UFO_10m3_lightMaterialBucket.zip
FS22_UltimateBalingPack.zip
FS22_UndergroundFarmhouseCompound.zip
FS22_UndergroundGrainStorage.zip
FS22_UniversalAutoload.zip
FS22_UniversalAutoloadModhubAddon.zip
FS22_UpgradableFactories.zip
FS22_Valtra_Pack.zip
FS22_VehicleControlAddon.zip
FS22_VineyardPack.zip
FS22_WaterHydrant.zip
FS22_WirelessWasher.zip
FS22_WolfAgripower.zip
FS22_woodenCladdingBuilding.zip
FS22_WoodenShed.zip
FS22_WoodProduction.zip
FS22_WoodShelterSet.zip
FS22_wsvsPlanterDfBd.zip
FS22_wsvsSowingDfBd.zip
FS22_wsvsSprayerDfBd.zip
FS22_wsvsSpreaderDfBd.zip
FS22_wsvsTractorComDfBd.zip

**Comment by rudger-wolvram** [comment]
I just noticed the second and third screenshots are messed up and I didn't see a method for updating that part of the post, so here they are in a comment.

This one, I created a custom field, selected inside it with field position, CF is ignored. Also, that break in the middle of the field was my attempt as shrinking it down to see if that was the problem.
![FS22_Courseplay_BugSS2](https://github.com/user-attachments/assets/59fc003d-f480-4e21-87c8-545a4e7a3b8c)


Just showing where the edge of the map is in relation to the field, in case that could be an issue.
![FS22_Courseplay_BugSS3](https://github.com/user-attachments/assets/af6e58a6-3465-471f-87fa-bf04057386b3)

**Comment by rudger-wolvram** [comment]
Save Game if needed.
[savegame1.zip](https://github.com/user-attachments/files/16340540/savegame1.zip)

**Comment by Tensuko** [comment]
Original vanilla placement with no biggee fab mod for the vines?

**Comment by adaukas1** [comment]
I have been having the same issue. I hope a fix comes soon

**Comment by Tensuko** [comment]
There wont be a fix for this soon.

**Comment by Tensuko** [comment]
It could be because the grass land is not rly a field.
There wont be any changes to that for fs22.
Make a test on a new save with same map.
Mow the grassland once ( if you havent done it before) and then place vines again. Or try it on an actual field.

**Comment by rudger-wolvram** [comment]
> It could be because the grass land is not rly a field. There wont be any changes to that for fs22. Make a test on a new save with same map. Mow the grassland once ( if you havent done it before) and then place vines again. Or try it on an actual field.

Will try that. Now that I think about it, the Grape field I referenced was plowed first so I could CP fert and lime first, the Olive one I just created it in the grass without plowing first. 

I have the Grass Mod that allows you to place growing/mowable grass and when you mow it it becomes a field. I'm not sure if you were referencing that mod and method specifically, but I'll try that first, then manual plowing if that doesn't work and update ASAP.

**Comment by rudger-wolvram** [comment]
Got it working, after @Tensuko mentioned that it wasn't really a field I went back and remade the whole thing. But in the process of remaking it I remembered that I did create a field there with a plow. What I didn't do however, was make sure the end's and edges of the Olive orchard were within that field (e.g. that last end placeable for it hung past the field a meter or 2 or on the straight edges the edge of the orchard passed the field edge).

I'm closing this as resolved because while it is a "bug", it's an inherent one with how FS22 does fields and orchards and the limitations CP has with being able to reliably read and apply that data together. Perhaps adding a small blurb to the readme/howto regarding orchards and CP needing the placed orchards to be fully within existing/custom field boundaries and that just placing them on straight grassland can or will cause CP field detection to fail due to an inherent flaw in how FS22 presents the field information to CP. i.e. put something in there so that hopefully this "bug" doesn't get reported again.. hopefully.

For example, in this section of the courseplay website https://courseplay.github.io/Courseplay_FS22.github.io/#CP_help_page_vineWork_title

Add something like this (in italic) to this paragraph on that help page.
Working on vines is a bit more complex than working on a normal field. To have the best result, the vines should all be next to each other within the default grid. The end and start of each vine, should also be approximately the same length. If the vines are on an existing field, you can open the generator the direct way like normal. If they are not on a field, you have to go over the AI Menu and place the field marker on the vines. _If the vines are on a field but extend beyond its boundaries, it may generate an invalid field that custom field markers won't work on. Insure that existing field orchards are within field boundaries._

**Comment by Tensuko** [comment]
Since we planing to change the vine generation (don't think it will happen for FS22, but who knows) this might be addressed anyway....
So not putting efford in something that we will change anyway.
