### ISSUE TITLE
[Question] dewulf zkivse pipe height bug

### ISSUE THREAD

**Issue by nmartinyuk** [Courseplay/Courseplay_FS22#3338]
Related to https://github.com/Courseplay/Courseplay_FS22/issues/2963
Looks like you don't include height of the tractor, because I had the situation where the tractor was higher than trailer and dewulf zkivse pipe height was for the trailer only, and the tractor was constantly hitting the pipe when loading the trailer, while the trailer fitted perfectly under the pipe.
Please let me know if I'm right or wrong. Thank you.

**Comment by Tensuko** [comment]
Correct, wont change that.
Use a smaller tractor.
