### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by waterormelon** [Courseplay/Courseplay_FS22#3339]
Steps to reproduce
Using precisionfarming and CP, Harvester is X9 1100 with HD50F , trailer  is 942 vario with GX520. Rapeseed is awaiting harvesting. The trailer uses Combine.

Actual behavior
When the trailer is aligned with the harvester, the harvester continuously extends the pipe and retracts.

Expected behavior
The harvester should keep extending the pipeline, as there is still rapeseed in its inventory at this time.

Courseplay version
Version used: v7.4.1.3

Log
[log.txt](https://github.com/user-attachments/files/16359726/log.txt)

Map
AKFarmland

Vehicles/ implements involved
Harvester is X9 1100 with HD50F , trailer  is 942 vario with GX520.
Mod yes/no ?
yes.
Relevant script mods
none

**Comment by waterormelon** [comment]
Steps to reproduce
Using precisionfarming and CP, Harvester is X9 1100 with HD50F , trailer  is 942 vario with GX520. Rapeseed is awaiting harvesting. The trailer uses Combine.

Actual behavior
When the trailer is aligned with the harvester, the harvester continuously extends the pipe and retracts.

Expected behavior
The harvester should keep extending the pipeline, as there is still rapeseed in its inventory at this time.

Courseplay version
Version used: v7.4.1.3

Log
[log.txt](https://github.com/user-attachments/files/16359726/log.txt)


Map
AKFarmland

Vehicles/ implements involved
Harvester is X9 1100 with HD50F , trailer  is 942 vario with GX520.
Mod yes/no ?
yes.
Relevant script mods
none

**Comment by Tensuko** [comment]
Must be any mod issue or user error.
Sry to say that but there is no cp related reason that this happens.
Can the trailer even load the fruit?
Is the pipe extension area of the harvester correct?

**Comment by waterormelon** [comment]
> Must be any mod issue or user error. Sry to say that but there is no cp related reason that this happens. Can the trailer even load the fruit? Is the pipe extension area of the harvester correct?
Maybe I didn't describe it clearly. When stationary, the harvester and trailer can unload normally. But when the harvester and trailer move forward at the same time, the pipeline of the harvester will retract after unloading for a period of time (not fixed), and then immediately extend again, and then repeat this process. All of this happened after I added the Precisionfarming DLC to my save. There was no such issue before this. I tried using the game's built-in AI,  the pipeline still tried to retract, but immediately extended to ensure the continuous loading of rapeseed.

**Comment by Tensuko** [comment]
PF have no impact on this. Could be something else.
A video can help.

**Comment by waterormelon** [comment]
> PF have no impact on this. Could be something else. A video can help.

video: https://www.veed.io/view/f0fde578-1c44-4592-82d9-c5444a7702ba?panel=share
log:
[log.txt](https://github.com/user-attachments/files/16362977/log.txt)

**Comment by Tensuko** [comment]
Video is private, upload it on google drive or something like that.

**Comment by waterormelon** [comment]
> Video is private, upload it on google drive or something like that.

Sorry, here it is.  https://drive.google.com/file/d/1E_lsmgJnqtVqz4Vq3n01I70CLAwrkVJc/view?usp=drive_link

**Comment by Tensuko** [comment]
Yep, mod issue.
1st that insane speed is not a good idea, that wont work and 2nd the trailer area of that combine seems to be way too small. Use F5 to check the area and compare it with vanilla combine. Or best check GE.
