### ISSUE TITLE
[BUG_SP] Bale collector not remembering mode in SP saved game loading

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3340]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Have a tractor and bale collector collecting bales when you save and exit the game

**Actual behaviour**
When you load the save game the mode has changed to fieldwork instead of Bale collect/wrap

**Expected behaviour**
Collectors and wrappers to remember the mode they  were in like previous version of CP did

**Screenshots**

**Courseplay version**
Version used: 7.4.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Any

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
No

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Known issue #3233
