### ISSUE TITLE
[Feature] option to force „combine type sharp turn”

### ISSUE THREAD

**Issue by S-eler** [Courseplay/Courseplay_FS22#3341]
**What is the problem this feature/enhancement solves?**
Most of tools are performing sharp turn in the way that way stop working before reaching corner, and making „corner area” from new course, after turn, starting outside of the field. But combine harvester is working properly - finishig current path at the enf of the field, and making turn on alteady worked ground. In-game Hardi Rubicon has got working line at front of it, just like header on the harvester, and it should work in same way. Some other tools could also work in this way (if working area is closer to front of vehicle, than it’s end.

**Describe the solution you'd like**
Not sure, potentially instead of one option for „sharp” turn create two options:
1) sharp-front tool;
2) sharp-towed

**Describe alternatives you've considered**
Additional option corner-first/corner-after-turn

**Additional context**
Maybe in FS25? ;)

**Comment by Tensuko** [comment]
That wont work with any tool as combine move Nd turn completly different with back wheel.
