### ISSUE TITLE
[BUG_SP] The tractor doesn't go to the exit. It remains frozen

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#3342]
Once the trailer is full, the tractor does not go to the starting point to then pass the relay to AD.
I tried with several trailers, on different maps, but the problem is always the same, the tractor does not move.

With version 7.4.1.2, it worked well because the trailer, once full, passed the relay to AD directly.
#3247 changed everything

**Screenshots**
![image](https://github.com/user-attachments/assets/a2564785-783c-4696-893e-583a29ad990c)
![image](https://github.com/user-attachments/assets/f9d3667a-1bac-4913-a0b2-56616a2bb348)

**Courseplay version**
Version used: v7.4.1.3

**Log**
[log.txt](https://github.com/user-attachments/files/16402608/log.txt)

**Map**
Map played on: Elmcreekx4 by Steevie

**Comment by regs1980** [comment]
The error has been known for weeks and there was no need to open a new issue.
You could have posted it here.
https://github.com/Courseplay/Courseplay_FS22/issues/3313#issue-2375052095

**Comment by Crinouche** [comment]
Sorry. I hadn't seen this post.
Yet I am vigilant about it.
Sorry again...
