### ISSUE TITLE
[Question] How to turn off warning on boot?

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [Courseplay/Courseplay_FS22#3343]
So I tried looking in the open and closed area and I am either not using the correct terms or it's not been asked? Sorry if this is a duplicate. How does turn off the report bugs to github popup you get when launching into a game? It's kind of an annoyance because it stops my character from auto entering the server.

**Comment by Tensuko** [comment]
It only open once when you have a new version.
Cant be stopped and we wont change that.
So if you change cp version in your savegames or on server it will always pop up.
