### ISSUE TITLE
[BUG_MP] Kontostand springt auf 0

### ISSUE THREAD

**Issue by ChrisKeng** [Courseplay/Courseplay_FS22#3345]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Können wir nicht

**Actual behavior**
Kontostand geht auf 0, sobald Courseplay gestartet wurde, jedoch nicht immer und bei Farm ID 3... Einmalig bei Farm ID 2

Ich weiß nicht, ob es FarmID abhängig ist, jedoch hatte ich das ganze bei meinem Hof (FarmID 1) garnicht.

FarmID 3 ist oft davon betroffen.

Wir können dies jedoch nicht wirklich reproduzieren, da es sporadisch auftaucht

**Courseplay version**
Version used:  7.4.1.3

**Client Log**
Meine Log: 
[log.txt](https://github.com/user-attachments/files/16461672/log.txt)
Logdatei des Kollegen, auf wessen Farm das passiert: 
[log.txt](https://github.com/user-attachments/files/16461674/log.txt)

**Server Log**
[log_2024-08-01_21-11-51.txt](https://github.com/user-attachments/files/16461675/log_2024-08-01_21-11-51.txt)

**Player on the server**
3

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Deutschland Map

**Vehicles/ implements involved**
Which vehicle or implement?
Verschiedene Anbaugeräten, größtenteils Standard, da Geräte für Missionen ausgeleiht wurden

**Relevant script mods**

**Comment by ChrisKeng** [comment]
Der Fehler tauchte in der Log im Zeitraum von 22:07 und 22:10 auf (War gerade nicht am PC, als dies wohl passierte)

**Comment by Tensuko** [comment]
Wie ist eure Einstellung für CP Lohn?
Ist automatische Reparatur bei CP aktiv?
Was machen diese Mods?
FS22_Configure_Maintenance
FS22_EnhancedLoanSystem
FS22_extendedFinances

Sind potentielle Fehlerquellen.
Was passiert mit der ModHub Version von CP wenn ihr die drauf habt?

Ihr habt auch 2 mods für Leasing drauf, nicht das die sich auch beißen.

**Comment by ChrisKeng** [comment]
CP Lohn ist bei 50%
Automatische Reparatur ist bei CP deaktiviert

FS22_Configure_Maintenance verringert nur die WArtungskosten, der Mod ist auf dem Modhub und habe diesen ebenfalls seit einigen Servern (1-2 Jahre) aktiv ohne Probleme

FS22_Enhanced LoanSystem ist ein erweitertes Kreditsystem, ebenfalls seit einigen Servern aktiv, hatten wir anfangs auch im Verdacht, aber nach dem deaktivieren trotzdem das Problem

FS22_ExtendedFinances ist der Mod, der einmal im jahr anhand der Feldflächen eine Subvention bezahlt (ebenfalls Modhub und ebenfalls lange online)

Wir haben zur Zeit die Version, die wir sonst seit Anfang des jahres auf unserem Land of Italy Server hatten, jetzzt auch auf den SEver gemacht (7.4.0.2) Problem kommt trotzdem wieder.


Ich hab jetzt nur noch die 2 Mods für Leasing in Verdacht. Jedoch was erstaunlich ist, es steht nichts in den Finanzen, es kommt auch keine Benachrichtígung im Spiel, dass das Geld weg geht... und es passiert nur beim Kollegen auf Farm 3....

Wir hatten Courseplay in Verdacht, da es (nachdem wir ein komplett neuen Spielstand angefangen habe) zwei mal bei ihm innerhalb von paar Minuten nach Start von Courseplay passiert ist.

Jedoch konnten wir es gestern ausschließen... sonst wäre es bei mir auf dem Hof sowie dem anderen Kollegen auch so...


Ich versuche das ganze mit den Leasingsystem nun

**Comment by Tensuko** [comment]
Dann ist es definitiv kein cp problem.
