### ISSUE TITLE
[BUG_SP] Korrektes Einfahren in die Bahn nach Vorgewende

### ISSUE THREAD

**Issue by bmsbwd** [Courseplay/Courseplay_FS22#335]
**Steps to reproduce**
Planen und abfahren eines Kurses mit im Screenshot gezeigten Parametern

**Actual behavior**
Kurs wird richtig geplant, allerdings wird beim Einfahren in die erste Bahn nach dem Vorgewende nicht in der Bahn  angesetzt sondern im Einfahren in die Bahn.

(die Traktorposition im Bild ist nach dem CP-Kurs und nur um den Screenshot zu erstellen. Also nicht relevant :)

**Expected behavior**
Der Fahrer sollte nach dem Vorgewende nochmals zurück setzen und die Feldbahn noch im Vorgewende korrekt anpeilen und dann auf der Bahn starten.

**Screenshots**
![CP-Kurs](https://user-images.githubusercontent.com/10153289/147918269-9b2e95ca-943b-47cc-8971-7e16cc40818b.jpg)
![CP-Kursgenerator](https://user-images.githubusercontent.com/10153289/147918271-a9ca1d64-7623-4c08-b016-7b7467d024d1.jpg)
![CP-Problem](https://user-images.githubusercontent.com/10153289/147918275-ccb7b305-460a-4169-b326-ed617135ef6c.jpg)

**Courseplay version**
Version used:  .11

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7801318/log.txt)

**Map**
Niemandsland

**Vehicles/ implements involved**
Fend 1050 und Einzelkorn Azurit 9, beides Vanilla

**Relevant script mods**
Nope, aber siehe angehängte Logdatei

**Comment by 60erjonny** [comment]
Versuche mal den Kurs nicht an der Ecke zu beginnen, sondern an einer langen Seite...

**Comment by iljarogoff** [comment]
> Versuche mal den Kurs nicht an der Ecke zu beginnen, sondern an einer langen Seite...

Nein, ich hab den Kurs (Issue #266) mittig an einer langen Kante gestartet mit gleicham Ergebnis.

**Comment by Tensuko** [comment]
@bmsbwd 
Bitte einmal für das Fahrzeug mit dem Gerät in den Geräteeinstellungen ganzn unten debug aktivieren und dann den Kurs fahren lassen. Kurs vlt noch mal genau so generieren, damit die daten auch mit rein kommen und dann das logfile anhängen, danke.

**Comment by bmsbwd** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7802346/log.txt)

Einmal das Log. Musste das Feld 3x neu starten weil die Jahreszeit nicht gepasst hat... Fehler war trotzdem reproduzierbar:

![CP_Problempunkt_debug](https://user-images.githubusercontent.com/10153289/147941032-1ff8e4a1-394f-422c-86e2-2b333a23dfce.jpg)

die Bahn später hat er's nicht korrigiert....

![CP_eine Bahn später_debug](https://user-images.githubusercontent.com/10153289/147941080-855eddb5-10d3-45d9-b384-0a150e7975d1.jpg)

hab das Feld nicht zuende gepflanzt weil unterwegs das Saatgut ausgegangen ist.

**Comment by bmsbwd** [comment]
Bis zum Blauen Pfeil fährt er mit ausgehobenem Gerät und setzt es am roten Pfeil wieder ein:
![CP_Problempunkt_debug](https://user-images.githubusercontent.com/10153289/147941664-45a6d3cf-2b02-4cd9-b922-5d489d67862f.jpg)

**Comment by Tensuko** [comment]
Pls try 7.0.0.12
If still have problems, pls reopen and report.
