### ISSUE TITLE
CP:Siloarbeit instead of CP:Feldarbeit [BUG_SP]

### ISSUE THREAD

**Issue by FredyKyong** [Courseplay/Courseplay_FS22#3350]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Get into tractor (Hürlimann XL Pro 250) get Seedingtrailer (Kverneland Optima RS) hooked on with Q

**Actual behavior**
All courses deleted from tractor. Selecting "New Job"
New Job gives me:
"Freie Fahrt"
or
"CP: Siloarbeit"
I had this with a different tractor and trailer also once in another game play

**Expected behavior**
I want CP: Feldarbeit

**Screenshots**
Attached

**Courseplay version**
Version used: I tried 7.4.1.0 and now I tried 7.4.1.3
No cure, no difference

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
I dont get this. I am not a dev, just a player. Log.txt attached below as well.

**Map**
FS22, Silverrun Forest

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes

**Relevant script mods**
Autodrive 2.0.1.6

![Screenshot 2024-08-08 183534](https://github.com/user-attachments/assets/38829239-abf7-4d3f-aacc-63c931f7bc8c)

**Comment by Tensuko** [comment]
Mod Issue then.
If it only happens with specific tractors, it is a problem of the tractor.

**Comment by FredyKyong** [comment]
Different tractors, different trailers.

Log.txt does not show a mod conflict

**Comment by Tensuko** [comment]
>Log.txt does not show a mod conflict

Log will never show conflicts!

![grafik](https://github.com/user-attachments/assets/a652889a-15b8-400b-9203-f92af45ad177)

**Comment by FredyKyong** [comment]
Undocket the Hurliman tractor and attached a Claas Axion 870. Same problem

**Comment by FredyKyong** [comment]
Seems the Kverneland Optima trailer? Attached another trailer and is working atm. But the the Kverneland Optima always worked well. Strange

**Comment by Tensuko** [comment]
Von was für einem Trailer redest du???

**Comment by FredyKyong** [comment]
Sähmaschine Kverneland Optima RS

**Comment by Tensuko** [comment]
Dann sag bitte seeder/implement/tool, weil Trailer ist was komplett anderes :)

So und auch diese Kombi geht.
Liegt als an irgend einer Mod von dir, das musst du aber selber rausfinden welche es ist.
![grafik](https://github.com/user-attachments/assets/56da91b7-63a1-4ee9-afa0-1c24a8e2136c)

**Comment by FredyKyong** [comment]
Ok. checke ich nochmal

**Comment by FredyKyong** [comment]
Ich hab die Farmod Kverneland Optima, nicht die rote aus dem Shop. Vllcht das Problem

**Comment by Tensuko** [comment]
Das kann sein, aber auch das -> Mod Issue :)

**Comment by FredyKyong** [comment]
Supi. Werf ich gleich in Papierkorb das Ding. Werde es mit der roten Kverneland aus dem Shop probieren.

**Comment by FredyKyong** [comment]
Gut. Ich habe jetzt zwei Kverneland Optima RS Mods probiert. Überall das selbe Problem.
Ich habe den Kverneland Optima RS Mod aus dem Shop probiert, selbes Problem.
Mit verschiedenen Traktoren versucht, selbes Problem.

Scheint dann doch nicht der Hänger Mod zu sein.
