### ISSUE TITLE
[BUG_SP]making custom field with path creator freezes game

### ISSUE THREAD

**Issue by thebikwirm** [Courseplay/Courseplay_FS22#3351]
**Steps to reproduce**
launch game and select cp field job 
then select custom field and open course settings
using base game mower and tractor

**Actual behavior**
game freezes and becomes unresponisve

**Expected behavior**
to make course and not freeze

**Courseplay version**
Version used: 7.4.1.3

**Log**
[log.txt](https://github.com/user-attachments/files/16568401/log.txt)

**Map**
aussie no mans land, 

**Vehicles/ implements involved**
Which vehicle or implement?
base game mowers and tractor

**Relevant script mods**
Mods like Autodrive or VCA and so on.
auotodrive, vca, a shit load
[modsforestry.csv](https://github.com/user-attachments/files/16568395/modsforestry.csv)

**Comment by thebikwirm** [comment]
it works but takes ages
have made fields of similar size before without these issues

**Comment by thebikwirm** [comment]
can confirm that it doesnt like the bypass setting

**Comment by thebikwirm** [comment]
its seems to be field size but its not that big
ive done bigger and its worked fine

**Comment by Tensuko** [comment]
island bypass is not working with custom fields, also you HAVE to make sure that you have no overlapping of the start and the end point of the course, rather have a gap.

**Comment by thebikwirm** [comment]
oh right
is there a way to edit cusom fields?

**Comment by Tensuko** [comment]
jup, read ingame help, it is all explained there :)
