### ISSUE TITLE
[BUG_SP] Harvester gets blocked around the unloading trailer while it has a ton of space to turn

### ISSUE THREAD

**Issue by Move2win** [Courseplay/Courseplay_FS22#3352]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Enable the harvester to self-unload, and wait until it gets stuck around the unloading target trailer.

**Actual behavior**
Harvester gets stuck on the trailer.

**Expected behavior**
Harvester can reverse and successfully unload without getting blocked.

**Screenshots**
![1126](https://github.com/user-attachments/assets/a08966b0-663a-42f6-9c8b-b4bac1720782)

**Courseplay version**
Version used: v7.4.1.3

**Map**
PV Canyon Crossing ([https://trello.com/b/ZdyWgZme/mods-by-dajnet](https://trello.com/b/ZdyWgZme/mods-by-dajnet))

**Vehicles/ implements involved**
Harvester Topliner 4090H
Mod yes/no ? NO

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
It basically works 
![grafik](https://github.com/user-attachments/assets/102bb137-3aea-4e0f-8a5d-9ca2757c625f)

It can happen sometimes, that the generated path is a bit too close to the trailer.
Won't fix that. (At least not in FS22 anymore)

**Comment by Move2win** [comment]
> It basically works ![grafik](https://private-user-images.githubusercontent.com/27344744/356856456-102bb137-3aea-4e0f-8a5d-9ca2757c625f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTk5MDUsIm5iZiI6MTcyMzM1OTYwNSwicGF0aCI6Ii8yNzM0NDc0NC8zNTY4NTY0NTYtMTAyYmIxMzctM2FlYS00ZTBmLThhNWQtOWNhMjc1N2M2MjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA3MDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNmU4MDc5OGZjMzUxZGU0YjJhMTA5NDZmZDkxMjVhOGExODczNzE5NmI5MDE2NWFjZTk3YWQ0MmM5M2QwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HNb7vYcItrtqQlBL9GjpNDu9g5Lfigf2oZpFvm79y_U)
> 
> It can happen sometimes, that the generated path is a bit too close to the trailer. Won't fix that. (At least not in FS22 anymore)
> 
> Next time add your logfile like written in the template!

It does work, at least for some time, not really stable. If only it could reverse a little bit, it would work perfectly.

**Comment by Tensuko** [comment]
I have the plan of a traffic conflict solver, but there was no time to do that, so this will be something to address in the next FS at a later point.
