### ISSUE TITLE
[BUG_SP] CP doesn't recognize map default silo

### ISSUE THREAD

**Issue by Move2win** [Courseplay/Courseplay_FS22#3353]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Under 'Silo work' mode, try to select the map default silo.

**Actual behavior**
The map default silo can't be select, no blue outline is shown. (see screenshots)

**Expected behavior**
The silo can be recognized and selected.

**Screenshots**
You can see the map default silo in the background beside the grass silo.
![屏幕截图(1127)](https://github.com/user-attachments/assets/766cb0ed-ab37-42ab-8047-06c9de69f7d4)

This silo doesn't get recognized as no blue outline is shown, not like the grass silo beside it.
Also, if it has a blue outline, this silo icon is totally covering it, I don't know if it has anything to do with it.
![屏幕截图(1128)](https://github.com/user-attachments/assets/0f157d4b-7bd9-447e-b7eb-92d144bc1eb3)

**Courseplay version**
Version used: v7.4.1.3

**Map**
PV Canyon Crossing ([https://trello.com/b/ZdyWgZme/mods-by-dajnet](https://trello.com/b/ZdyWgZme/mods-by-dajnet))

**Vehicles/ implements involved**
Silo NL16-22 - 2000
Mod yes/no ? No

**Relevant script mods**
N/A

**Comment by Tensuko** [comment]
This is no bug! This is not how it works! Read the ingame help!
The mod you have there is also for pushing chaff in a bunker silo and/or compacting.
So no Idea what you plan to do.

**Comment by Move2win** [comment]
> This is no bug! This is not how it works! Read the ingame help! The mod you have there is also for pushing chaff in a bunker silo and/or compacting. So no Idea what you plan to do.

I'm trying to set it up to automatically load from the harvester and unload to the silo, but that's not what "Silo work" means?

I saw the harvester can "Call unload" when nearly full, I thought "Silo work" is corresponding to that...

**Comment by Tensuko** [comment]
Not like that. As said, read the ingame help pls.
