### ISSUE TITLE
[BUG_SP] Courseplay breaks savegame after playing for awhile

### ISSUE THREAD

**Issue by Wreyth** [Courseplay/Courseplay_FS22#3356]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

Read

**Steps to reproduce**
Steps to reproduce the behavior.

star a new game play for awhile save game go to load game back up and game won't load with courseplay error in log and hangs at 85%

Error: Running LUA method 'update'.
F:/FS22 Mod Folder/FS22_Courseplay/scripts/specializations/CpVehicleSettings.lua:453: bad argument #1 to 'min' (number expected, got nil)

**Actual behavior**
A clear and concise description of what happen.

See above

**Expected behavior**
Savegame to load and be able to play

**Screenshots**
![image](https://github.com/user-attachments/assets/70972b07-9d0b-4531-9126-9bcfe7ea6a93)

**Courseplay version**
Version used: Current most recent github release

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

my log is more then the characters will allow but only mention of courseplay is the error above

**Map**
Map played on. Green Mountain but happening with all my maps

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive latest github version

all mods and courseplay and everything load just fine when starting a new game but courseplay crashes the load when loading a saved game.

**Comment by Wreyth** [comment]
and yes i have tried unloading mods 1 by 1 on anything that was updated since the last time it worked fine and nothing has changed. if i unload courseplay save loads just fine but won't load now with courseplay on.

**Comment by Wreyth** [comment]
but i can start a brand new game with everything including courseplay loaded just fine

**Comment by Tensuko** [comment]
If that would be a CP Issue, more ppl would have that problem.
No logfile, no help.

**Comment by Zbamo** [comment]
https://pastebin.com/D0C8cPpu 

Heres mine im having the same issue, wont load after 85%. Worked one day and the next it did not. old and new version of CP does this.

**Comment by Wreyth** [comment]
as i stated i have unloaded all the mods 1 by 1 and still after awhile it won't load from save with same error on different maps.

![image](https://github.com/user-attachments/assets/4ce75f28-0ae0-42b3-924e-767a644e936e)

[log.txt](https://github.com/user-attachments/files/16633060/log.txt)

**Comment by Tensuko** [comment]
> as i stated i have unloaded all the mods 1 by 1 and still after awhile it won't load from save with same error on different maps.
> 
> ![image](https://private-user-images.githubusercontent.com/4178217/358470911-4ce75f28-0ae0-42b3-924e-767a644e936e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODQ3OTksIm5iZiI6MTcyMzc4NDQ5OSwicGF0aCI6Ii80MTc4MjE3LzM1ODQ3MDkxMS00Y2U3NWYyOC0wYWUwLTQyYjMtOTI0ZS03NjdhNjQ0ZTkzNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDUwMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ3MDA1NmQ2ZGQzODA5MzJmYWFlMTM1NDZkYjZkMWMyYThiNTdiMGVhYmRiMmM2YzUwNzRlMzFmMzUzMjNkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JoHtWBFWchkEV-M4IuSLJGlFw3O28AYqJKY6BmT8ABY)
> 
> [log.txt](https://github.com/user-attachments/files/16633060/log.txt)

So you started your game 680 times to check every mod? Sry but I don't belive that!
Would take about 2040min if every try takes 3min wich would be 34hours.
Even if you say it is only 2min it is still 22,5 hours.....

Your log contains a lot of mods with errors and from the name of your mods, a lot of them are from any weird source with untested mods!

The Error appears after loading this:
Real Dirt Color successfully applied to LIZARD 53' DROPDECK TRAILER AUTOLOAD BALES

That means it have to do with this. Could also be real dirt.

It is NOT from CP, it is any of your mods that creates a conflict!

**Comment by Tensuko** [comment]
> https://pastebin.com/D0C8cPpu
> 
> Heres mine im having the same issue, wont load after 85%. Worked one day and the next it did not. old and new version of CP does this.

404 not found.

**Comment by Wreyth** [comment]
found the workaround and issue (at least for me)..... delete any saved courses in the saved courses folder .... soon as i deleted the 2 i had created it loaded just fine.

Documents\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay\Courses


> > as i stated i have unloaded all the mods 1 by 1 and still after awhile it won't load from save with same error on different maps.
> > ![image](https://private-user-images.githubusercontent.com/4178217/358470911-4ce75f28-0ae0-42b3-924e-767a644e936e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODQ3OTksIm5iZiI6MTcyMzc4NDQ5OSwicGF0aCI6Ii80MTc4MjE3LzM1ODQ3MDkxMS00Y2U3NWYyOC0wYWUwLTQyYjMtOTI0ZS03NjdhNjQ0ZTkzNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDUwMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ3MDA1NmQ2ZGQzODA5MzJmYWFlMTM1NDZkYjZkMWMyYThiNTdiMGVhYmRiMmM2YzUwNzRlMzFmMzUzMjNkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JoHtWBFWchkEV-M4IuSLJGlFw3O28AYqJKY6BmT8ABY)
> > [log.txt](https://github.com/user-attachments/files/16633060/log.txt)
> 
> So you started your game 680 times to check every mod? Sry but I don't belive that! Would take about 2040min if every try takes 3min wich would be 34hours. Even if you say it is only 2min it is still 22,5 hours.....
> 
> Your log contains a lot of mods with errors and from the name of your mods, a lot of them are from any weird source with untested mods!
> 
> The Error appears after loading this: Real Dirt Color successfully applied to LIZARD 53' DROPDECK TRAILER AUTOLOAD BALES
> 
> That means it have to do with this. Could also be real dirt.
> 
> It is NOT from CP, it is any of your mods that creates a conflict!

----------------------------------------------------------------------------------------------------------------------------------------

ever heard of mod loaders? you can set loaded mods in different folders and i have several 1 with no mods but what i put in there.

found the workaround and issue (at least for me)..... delete any saved courses in the saved courses folder .... soon as i deleted the 2 i had created it loaded just fine.

Documents\My Games\FarmingSimulator2022\modSettings\FS22_Courseplay\Courses

**Comment by Wreyth** [comment]
so no need to be rude or an ass about it ..... it IS CP and it is the saved courses that caused the issue.

**Comment by Tensuko** [comment]
Seems to not work And if I check what the games DOES load as mods, your mod loader seems to ignore that too.

**Comment by Wreyth** [comment]
that log file was with the mods loaded that i started a new game on today .... saved and reloaded that same save several times throughout the day. ran it multiple times ..... then all the sudden not loading with courseplay. the only thing i did between saves was save a course and load that course on another default fs22 machine did the course and had several autosaves including a manual save and went to reload the game and no longer loads even going back several hours worth of saves.

even tried unloading all the mods minus autodrive and paid dlc and it was still throwing that error..... i don't know if it had to do with the saving a course from a harvester and loading it on a tractor with a baler to pickup the straw swath or what ..... i just know it loaded fine several times then all the sudden that error again.

so you can either try to help fix it as obviously i am now not the ONLY person with that issue. or you can keep having an attitude like your crap don't stink and there is no possible way anything YOU ever coded could possibly be having a issue and it's every other persons, modders, players fault.

i didn't come to you before exhausting everything else i could think of because yes i am a modder as well and sometimes my stuff breaks just like everyone else and sometimes weird random conflicts arise that weren't there previously.

i also have 3 other people i play with regularly that are now having the same issue that recently came back to the game but haven't added any new mods.

seems to me if it loads fine with other mods ... plays for hours and reloads the saves just fine then randomly all the sudden with no changes to anything or mods added  it randomly breaks the save. then there is something randomly causing an issue in CP. only consistent thing i have seen is it seems to be after saving a course and loading a course on another in game machine.

and yes i will try to grab a log with all those mods unloaded and not loaded up on game start when i can as it's doing the same thing. again the log i posted to you is with the same mods that have been working fine for months and not with them unloaded. 

i am more then willing to help solve the issue with you but i am not gonna sit here and deal with an attitude of your crap don't stink and blame everyone and everything else. just be civil as i am trying to be and lets figure out whats causing it.

**Comment by Wreyth** [comment]
also i am wondering if it was something in a recent giants update that is the issue as like i said i have ran the same mods for months with zero issue till recently

**Comment by Zbamo** [comment]
> > https://pastebin.com/D0C8cPpu
> > Heres mine im having the same issue, wont load after 85%. Worked one day and the next it did not. old and new version of CP does this.
> 
> 404 not found.

https://pastebin.com/xQY8361C

**Comment by Tensuko** [comment]
> again the log i posted to you is with the same mods that have been working fine for months and not with them unloaded.

There is a difference in "loaded the mods in the savegame" and "load the mods when the game starts"
That means: if you have tool X for even years in your savegame, but never bought it and saved it, it will all work just fine.
Once you have that tool and save your game, becouse that tool got an Issue, you have a corrupt save in terms that something CP expect is not available for that tool.
And since we build our mod based on vanilla, the issue does not come from CP and MUST be a tool with a broken feature.
We will never support all mods and will ofc never care for issues that appear due to broken mods.

Show me that issue with NO other mods, and I will check for it.

The Error occures here:

`--- Generates speed setting values up to the max possible speed.
---@param setting AIParameterSettingList
---@param lastValue any
---@return table values
---@return table texts
---@return any correct current value after max speed adjustment
function CpVehicleSettings:generateSpeedSettingValuesAndTexts(setting, lastValue)
    local maxSpeed = self.getCruiseControlMaxSpeed and self:getCruiseControlMaxSpeed() or setting.data.max
    local values, texts = {}, {}
    for i = setting.data.min, maxSpeed, setting.data.incremental or 1 do 
        table.insert(values, i)
        table.insert(texts, i)
    end
    return values, texts, math.min(lastValue, maxSpeed)
end`

Exactly to `return values, texts, math.min(lastValue, maxSpeed)`

You can check your mods for speed value.
That Code didn't change for the last 17 month, you can check the git blame list.
So you want to tell me that in the last 17 month, there was a bug that make this happen and no one had this?
By the amount of mods existing?
And just by the amount of untested mods you have from so many different sources it is VERY possible that the issues coms from a mod!
BTW the same goes to @Zbamo you have similar mods from non modhub sources and I expect the same problem.

Won't fix! -> Mod Issue!
If you like it our not, we will NOT support any broken mods.

**Comment by Zbamo** [comment]
I mean the new courseplay update is a non-modhub source is it not? I get them directly from the itch.io modder. All I know is on the 13th it loaded and on the 14th it didn't. Im going to do some more testing.
