### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#3358]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

I'm having an ongoing issue that happens on any map, where I'm using a Holmer T4 root crop harvester.
I have the harvest set to unload at 40%, at this point the vehicle with its trailer is triggered and leaves the edge of the field at its wait point.
The unloading vehicles comes up behind the harvester and rides on its butt, and never maneuvers to the harvester's side to unload.
It waits until the harvester gets full, then it will pull beside and unload.
Herein lies another question, why does every type of harvester have its pipe out, then right before its gets full, it retracts the pipe, and then extends the pipe once its comes to a stop. All this does is confuse the chase vehilce trying to unload, as it stops dead on the field, then is triggered again once the harvester is stop and extends the pipe, this just delays the process. You need to figure out a way that when harvesters have their pipe extended, and then the become full enough to stop, the pipe does not retract right before becomes full, but instead just stays extended.
Sometimes I have the exact same issue with combines,  where the chase vehicle rides on the combines butt and will not drive to the side under the pipe.

CP v7.4.1.3
Map- Wild Wild West 16x 
Mod - FS22_JDHeaderHD50fCutterbar
![FarmingSimulator2022Game_2024_08_21_15_15_30_734](https://github.com/user-attachments/assets/3cc6da7d-f589-4311-bc17-fda0471e80ae)

Mod file is 50 MB

https://drive.google.com/file/d/1gsZNKtOaMoB2w4Ap_XGwM8kHEnljGh07/view?usp=sharing

**Comment by Tensuko** [comment]
Mod Issue.
Seems like pipe is not set up correctly.
You can try use the offset setting on the HUD for this.
But as I can't see much like its blocked or not and you have add no logfile I can't tell much more about it.

Try Vanilla and see what happens?
Not a CP issue 100% sure.

**Comment by HC1Gunner** [comment]
I sent a google drive link to the log file, it was over your limit of 25mb.

**Comment by Tensuko** [comment]
Thats not a complete logfile and the AD spam in there is insane, pls make one without AD debug and only CP debug active.
And complete log means for the start of the log.
