### ISSUE TITLE
[BUG_SP] Tipper Not Getting to Pipe

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/Courseplay_FS22#3359]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Any map with any combination of tipper/combine

**Actual behavior**
Your combine is going up and down the field. Say the tipper it north of the combine. Tipper is called and guesses where the combine will meet it. Stops there, but the combine is filled before that point, so the tipper just sits there and so does the combine.

Combine is south of the tipper and is pointing south. The combine is heading north and is north of the tipper. If the combine gets full before tipper gets there and stops the tipper stops short. 

If the tipper is facing south but is north of the combine and the combine stops, the tipper will to a u-turn and stop short. They both just sit there.

**Expected behavior**
I would expect the tipper to wait a short time and if it isn't being filled, look for the combine and move/adjust until the tipper is below the pipe.

**Screenshots**
![Screenshot 2024-08-21 194206](https://github.com/user-attachments/assets/337d5926-109c-4dac-a394-ae82d9674557)

**Courseplay version**
7.4.1.3

**Log**

[log.txt](https://github.com/user-attachments/files/16700988/log.txt)

**Map**
Big Flats, Texas for this one, but same on Iowa Plains.

**Vehicles/ implements involved**
Which vehicle or implement? Multiple vanilla and mod and combos, but for this one all vanilla: Claas Lexion 8900. Mack Super-Liner x69, Krampe SKS30/1050
Mod yes/no ?

**Relevant script mods**
I think CP is the only vehicle script.

**Comment by Tensuko** [comment]
Normaly after a while it should notice that he is not loading and drive there again hmm.
Will have a look at this but as you may noticed, fixing stuff takes a while right now.
Can't tell you when we get to this.

**Comment by lcc1211** [comment]
FYI, version 7.4.1.1 does readjust the tipper if it misses. So the change happened in the one of the next 2 versions.

**Comment by Tensuko** [comment]
Does it still happen with 7.4.2.3?

**Comment by lcc1211** [comment]
I put a few hours in yesterday on a very large field to see if it happened. It still happened with the combination I used earlier, but I switched to tractor/tipper and it seems that mostly fixed it. I only had it happen one time on a field where it was happening multiple times. I'd say its 99% better.

**Comment by Tensuko** [comment]
Alright, thanks for the feedback.

**Comment by Tensuko** [comment]
Will have an eye on it, but for now if most combinations work, its okay.
