### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by mobilemarrow78** [Courseplay/Courseplay_FS22#3362]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

all the time it happens

**Actual behavior**
A clear and concise description of what happen.

after i reset vehicals back to shop, my cursors dissipers while in the wold map menu and when i click the screen shakes and only way to exit the menu is to press escape

**Expected behavior**

not what is happening now and just allows me to use my mouse again 

**Screenshots**

not able to do that 

**Courseplay version**
Version used: just downloaded newest 
[Courseplay for FS22 v7.4.1.3](https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.4.1.3)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/16738432/log.txt)
<script src="https://gist.github.com/mobilemarrow78/2cf44d4a4b93da3606aa0df9eca0ccb3.js"></script>

**Map**
Map played on.
Elm Creek

**Vehicles/ implements involved**
Which vehicle or implement? 
all
Mod yes/no ?
yes but tried with no mods and verified files in epic launcher issue goes away when courseplay is disabled and or unstalled
**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
No log, no help.

**Comment by mobilemarrow78** [comment]
ah shoot i thought i added that !! adding now

**Comment by Tensuko** [comment]
FS19 mods, doesn't work anyway:
Available mod: (Hash: 6bd9d88836e2195ae6d02e05a5d01298) (Version: 1.0.0.0) FS19_FrontLifter
Error: Unsupported mod description version in mod FS19_FrontLifter

Reduce Maintenance Cost throws a callstack.

I can't see any more Error.

Recreate the issue and then post the logfile so I can see the Error.

**Comment by mobilemarrow78** [comment]
ok new same save unstalled and deleted thoes mods
[log.txt](https://github.com/user-attachments/files/16739857/log.txt)      MODS
[log.txt](https://github.com/user-attachments/files/16739868/log.txt)      1 mod courseplay

**Comment by Tensuko** [comment]
Still no error in the log.

As I said, recreate the error THEN post the log.

**Comment by mobilemarrow78** [comment]
No I did.  If I disable course play the issues goes away.

**Comment by mobilemarrow78** [comment]
ok soooo instead of resetting tractor while inside! and getting the issue i hop out and then reset and theres no issue.. any idea?

**Comment by Tensuko** [comment]
If the mouse disappear and stuff, that will mostly only happen if an Error occurs and is written in the log, there is no error in the log and so I can't tell you what happens.

I try to reproduce this and all works just fine.
So I guess this is somehow a mod issue somewhere else.

**Comment by mobilemarrow78** [comment]
i jumped on my alt computer copy and paste the mods to that computer as well, still got same results, i also tried 3 different monitors still same

**Comment by mobilemarrow78** [comment]
i dont see how its a mod issue somewhere else as when i only use ur mod it happens
no big deal just trying to figure it out i also did start a new save and still happens

**Comment by mobilemarrow78** [comment]
any way i can invite u to join discord? or mayabe send a video?

**Comment by mobilemarrow78** [comment]
here is my save game 
https://gist.github.com/mobilemarrow78/00174ce849f40a1bdc0260f3b7be863a

**Comment by Tensuko** [comment]
This is not how to post a savegame, you got to .zip it.
A video would help from the start of the game, to the issue that happens and how you exit your game.

**Comment by mobilemarrow78** [comment]
I compressed the save folder to a .zip would let me upload here and or gist. I tried winrar too. Obv I'm doing something wrong. Also I can record it. Where would I upload it to?
