### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by venominc831** [Courseplay/Courseplay_FS22#3368]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Add CP 7.4.1.3 to server. Start server. Play. Save game and exit. Restart Server.

**Actual behavior**
Server hangs up when server restarts. This error shows in the logs:
D:/home/sid_1265339/farmingSim_2022/profile/mods/FS22_Courseplay/scripts/specializations/CpVehicleSettings.lua:453: bad argument #1 to 'min' (number expected, got nil)

**Expected behavior**
Server does not hang up and restarts as normal. 

**Screenshots**
![image](https://github.com/user-attachments/assets/83e4cabb-b723-4286-b5b9-96acd8ae2456)

**Courseplay version**
Version used: 7.4.1.3

**Client Log**
server won't start to get into game. 

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared.
[log_2024-08-27_16-00-57.txt](https://github.com/user-attachments/files/16769724/log_2024-08-27_16-00-57.txt)

**Dedicated server or local hosted server**
Dedicated server yes/no ? Yes

**Map**
Canadian Rockies

**Vehicles/ implements involved**
N/A

**Relevant script mods**
Mods like Autodrive

**Comment by Tensuko** [comment]
Wild guess of faulty mod:
NV22_SilveradoHD

Try remove this.

Also.... Do you even check the mods you add?

Available mod: (Hash: 25082bef7a6cd43d9689c2962adfc88d) (Version: 1.0.2.1) FS19_AugerMaster
Error: Unsupported mod description version in mod FS19_AugerMaster
Available mod: (Hash: 61de37d53a9d93605139e5b634f93797) (Version: 1.1.0.0) FS19_LR_John_Deere_1890_40FT
Available mod: (Hash: 8efeddba18e362edbdb6193878c0d6f3) (Version: 0.9) FS19_Mining_Semi_Trailer
Error: Unsupported mod description version in mod FS19_Mining_Semi_Trailer

**Comment by venominc831** [comment]
Coming in after someone else. about 100 mods on that server are getting removed today already. However, after removing the nv22_silveradoHD, server does the same thing with the same message.

**Comment by Tensuko** [comment]
Okay, was just a shot in the dark.
But it definitly means that one vehicle value is a problem.

**Comment by venominc831** [comment]
Ok, I'm going through and deactivating vehicles to find the problem. I appreciate the help in pointing me in the right direction. I really like your mod.

**Comment by venominc831** [comment]
Pretty sure I just narrowed it down to something within FDR Logging Pack. I'm trying to investigate to figure out which mod. Thanks.
