### ISSUE TITLE
[Question] Scharf anstatt weich

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/Courseplay_FS22#337]
Hi, gibt es eine Möglichkeit CP zu sagen dass er bei der Kursgenerierung (scharf) solche Ecken auch scharf generiert?

![LITTLEBIGIV-2022-01-03 13_30_10-Window](https://user-images.githubusercontent.com/16350763/147930756-7c76ea44-1cdb-462f-b75e-1bbcd439f52f.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7801911/log.txt)

**Comment by Tensuko** [comment]
Hast du denn Ecken auf scharf gestellt ?

@pvaiko Finde den Eintrag in der log nicht wie die Ecken eingestellt sind.

**Comment by Clouseau219** [comment]
Ja, habe den Kurs mit scharf generiert. 
![LITTLEBIGIV-2022-01-03 13_41_06-Window](https://user-images.githubusercontent.com/16350763/147931682-c71b2bc7-8ed5-48a4-bd54-2904e2a1b0b1.png)

Die rot markierte Ecken fährt er weich, oben Rechts kann ich noch verstehen, aber unten links nicht.
![LITTLEBIGIV-2022-01-03 13_43_03-Window](https://user-images.githubusercontent.com/16350763/147931969-fc5f7c44-00c7-4adb-957b-510b30acb935.png)

**Comment by pvaiko** [comment]
@Clouseau219 hast vergessen zu erwähnen dass es hier eine Mod Map ist. Passiert das gleiche mit der original Haut-Beyleron?

**Comment by Gillios** [comment]
Das gleiche Problem habe ich bei der orginal Elmcreek aber auch bei diversen Feldern. Scharf eingestellt fährt sie aber weich.

**Comment by pull2play** [comment]
I see this issue on Elmcreek. I haven't tested it everywhere, but I've seen this happen on Field 57 - northeast and southeast corners and on Field 30 - southwest corner.

**Comment by Clouseau219** [comment]
> @Clouseau219 hast vergessen zu erwähnen dass das hier eine Mod Map ist. Passiert das gleiche mit der original Haut-Beyleron?

Es handelt sich dabei um die Orig. Haut-Beyleron, nur mit angepasster maps_growth.xml für einen schnelleren Wachstum der Feldfrüchte.

**Comment by Tensuko** [comment]
Pls try 7.0.0.13
Reopen if Issue persists.
