### ISSUE TITLE
Generazione percorsi

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3373]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

Ho disegnato il campo a mano perché a causa della vicinanza con un altro campo il generatore automatico non funzionava. Quando provo a generare i percorsi mi lascia uno spazio dove non viene eseguito il lavoro

**Actual behavior**
Nella generazione del percorso viene lasciato uno spazio interno al campo dove non viene lavorato

**Expected behavior**
Lavoro completo su tutto il campo

**Screenshots**
![Farming Simulator 22 31_08_2024 12_09_10](https://github.com/user-attachments/assets/0480ac1f-ec2b-4a30-bfaf-02d84767a182)
![Farming Simulator 22 31_08_2024 12_09_01](https://github.com/user-attachments/assets/d00fdfcc-ff1b-4bc4-a467-3bdf26cc9f00)

**Courseplay version**
Version used: 7.4.1.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Bucks County, PA

**Vehicles/ implements involved**
Claas Arion 660 + dalbo powerroll 1230 HD
Mod yes/no ? No

**Relevant script mods**
No

**Comment by Tensuko** [comment]
I can see nothing on your screenshots.
Anyway, wait for next Release and try it again.
Also next time write in english pls!
