### ISSUE TITLE
[Question] ist es möglich mit Courseplay und Anhänger in die Goweil LT zu entladen?

### ISSUE THREAD

**Issue by zinni97** [Courseplay/Courseplay_FS22#3375]
Ich habe versucht Courseplay dazu zu bringen mit Anhänger rückwärts in die LT Master zu entladen, habe es aber nicht herausgefunden und auch keine Tipps oder Anleitung gefunden. Im Wiki steht auch nicht spezifisches dazu, ist es möglich oder muss das entladen mit autodrive gelöst werden? 

Danke für eure Antwort! Und danke für den geilen Mod sowieso!

**Comment by Tensuko** [comment]
Direkt mit einem Anhänger ist das aktuell nur mit AD möglich.
Ansonsten kann die Göweil wie ein Trailer im Silo Schaufeln Modus benutzt werden. z.B. Rübenschnitzel von einem Haufen in die Göweil per Radlader.

**Comment by zinni97** [comment]
Alles klar, danke für die Antwort!
