### ISSUE TITLE
[BUG_SP] Weird course at the end point

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3378]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

When generating a course with start at center selected. The vehicle does not end up where i set the marker(the previous version did)
There is also some erratic course generation around the endpoint.
  
**Expected behavior**

**Screenshots**
![Farming Simulator 22 Screenshot 2024 09 01 - 19 20 42 35](https://github.com/user-attachments/assets/39a30bc7-7392-488c-a9d9-192872e2d547)

Different field same issues

![Farming Simulator 22 Screenshot 2024 09 01 - 19 37 14 18](https://github.com/user-attachments/assets/193412dc-6729-4d16-a4e1-fa04094f8ce9)
![Farming Simulator 22 Screenshot 2024 09 01 - 19 38 30 47](https://github.com/user-attachments/assets/b58c1676-901e-43af-9a44-2ea1553d0dcf)

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/user-attachments/files/16829897/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pvaiko** [comment]
> When generating a course with start at center selected. The vehicle does not end up where i set the marker(the previous version did)

This is by design, there were many complaints about the previous behavior. So now, when you select a start location, the course will start as close as possible to that location. We are not going back to the old behavior.

**Comment by pvaiko** [comment]
> Map played on.

That's not very helpful. We need to know which map is this.

**Comment by Martin-L45** [comment]
I did not mention the map because it is a custom map. I have never had any issues with the old course generator on this map.
I will try to find a map on modhub with large irregular fields and retest to see if the problem can be replicated.
regarding the starting point, i liked the old feature. But I'm sure i will get used to the new one just fine. And i really like the extra features in the new generator.

**Comment by Martin-L45** [comment]
Here is the same issue on Alma Missouri from modhub.
Let me know if you need more info

[log.txt](https://github.com/user-attachments/files/16837577/log.txt)
![Farming Simulator 22 Screenshot 2024 09 02 - 14 36 19 37](https://github.com/user-attachments/assets/1a51a6fe-2149-43f9-8535-8790e51be80e)

![Farming Simulator 22 Screenshot 2024 09 02 - 14 39 25 44](https://github.com/user-attachments/assets/685d53da-299b-4a52-84ca-fbb4bc61a7fc)

![Farming Simulator 22 Screenshot 2024 09 02 - 14 39 30 02](https://github.com/user-attachments/assets/c4e88ace-298a-462b-946e-bd2a5cda47f2)

**Comment by Tensuko** [comment]
I will try to reproduce this and try to find the cause, thanks!

**Comment by Martin-L45** [comment]
I tried your fix on both maps. And it seems to have solved the problem. 
Awesome work guys...
