### ISSUE TITLE
[BUG_SP] Multiple tools broken 

### ISSUE THREAD

**Issue by nitroSkirata** [Courseplay/Courseplay_FS22#3379]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Generate a course with 3 tools, then try to start any vehicle.
Only the center one starts, the rest stay where they are with the log error:
Courseplay_FS22/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)

**Actual behavior**
Only the center one starts, the rest stay where they are with the log error:
Courseplay_FS22/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)

**Expected behavior**
All vehicles work

**Screenshots**
(https://youtu.be/suxX4fvXptg)
**Courseplay version**
Version used: 7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/16830171/log.txt)

**Map**
Map played on.
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Topliner combine
 
Mod yes/no ?
No

**Relevant script mods**
Mods like Autodrive or VCA and so on.
None

**Comment by bbielcentennial** [comment]
I am having the same issue, tested with potatoes and carrots with 3 combine courses that were working on previous version.

**Comment by Snigyman** [comment]
I have the same problem, when i want start or generate course with two vehicles, i recive same error.

**Comment by pvaiko** [comment]
Sorry about this folks, looks like we somehow completely missed testing the multitools.

**Comment by Maestro-Ralf** [comment]
I have the same problem.If there is more than 1 tool .

**Comment by Rambo99** [comment]
I confirm the existence of the problem. 
2024-09-03 11:37 Error: Running LUA method 'update'.
C:/Users/User_name/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)

**Comment by anothergene** [comment]
Ditto with two.  Same error.

**Comment by CrazyCarrot911** [comment]
I can create tools with 2-5 tools but they all do not work as intended. One problem is the tool offset, I need to manually offset left and right tool from middle tool so the didnt overlap by like 90% (!). Another issue is with the large Giant plow. You cannot create a multi tool course that doesn't have funny loops and circles, also reaching beyond field borders, if you have more than 2 tools and 2 headlands or 3 or more tools... the lanes also overlap by like 90%, can manually adjust with offset but that's not working when the plow changes sides :(

**Comment by CrazyCarrot911** [comment]
Tobi,
I had the same "not starting" for some multi-tools. I had to reload the game to get them moving....but that only led to the next problem. Wrong course/offset kind of thing. 
Best is to not use Multi-Tool until fixed or revert back to the previous version, which I did as I need Multi-Tool quite often
