### ISSUE TITLE
[BUG_SP] Bale Unloader No Path (mode not selected after restart)

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3381]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Giants Fendt 930 & Anderson RBM2000 and collect wrapped bales

**Actual behavior**
Can't find a path to bales

**Expected behavior**
Find path to bales

**Screenshots**
![fsScreen_2024_09_01_20_31_10](https://github.com/user-attachments/assets/c62bafc0-b778-4c44-b5e0-ab891b9f6f39)

**Courseplay version**
Version used: 7.4.2.0

**Log**

[log.txt](https://github.com/user-attachments/files/16830247/log.txt)

**Map**
Vintage Oaks

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by coatsy35** [comment]
Another log and screenshot for you

![fsScreen_2024_09_01_22_17_24](https://github.com/user-attachments/assets/e8955b3b-8f07-4eff-9a5b-d47506f2f54d)

https://drive.google.com/file/d/1zvEBta0cH6qAT8_N1h-iLCyjrixSjjm0/view?usp=drive_link

**Comment by Tensuko** [comment]
Played with offset because of wide tractor?
If tractor to wide with too small offset, bale collide with it while pathfinder calculates.

**Comment by coatsy35** [comment]
> Played with offset because of wide tractor? If tractor to wide with too small offset, bale collide with it while pathfinder calculates.

I will retest. I did test a different offset the last time I loaded the save. Will try more and report back.

Also, have you any plans to fix the remembering course play vehicle state when loading a saved game? i.e. when you load back in the vehicles that were bale collecting/unloading default back to Fieldwork. It used to remember the state and broke a while back, not sure which update.

**Comment by Tensuko** [comment]
It is fixed.... At least on MP it would be weird if not for sp.

**Comment by coatsy35** [comment]
> It is fixed.... At least on MP it would be weird if not for sp.

Just loaded my save back in from last night and my two bale collectors were back in field mode when sitting in the middle of a field of bales. It's not a huge issue, but thought I'd mention it.
