### ISSUE TITLE
[BUG_SP] Last run tail joining headland

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3385]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Unknown

**Actual behavior**
The tail leading to the headland on some fields is at an angle, meaning that field operations miss a triangle 

**Expected behavior**
The tail from the last run is straight to the headland

**Screenshots**
![fsScreen_2024_09_01_23_25_54](https://github.com/user-attachments/assets/3f178d62-741a-48fa-8df2-6fdf221506ba)

**Courseplay version**
Version used: 7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
???
Mark what you talk about. I dont see a problem.

**Comment by coatsy35** [comment]
apologies I should have been clearer. The angled line circled in red causes the tractor and implement to adjust as it comes out of the row, instead of coming out straight like all the other rows. This then leaves a triangle of unfinished work (circled in green), when the field is completed, I have not competed the field yet in the image. 

![363522987-3f178d62-741a-48fa-8df2-6fdf221506ba](https://github.com/user-attachments/assets/81eb70cb-7851-49b7-a8d5-1c55dde01d43)

**Comment by Tensuko** [comment]
Thats a low priority right now.

**Comment by pvaiko** [comment]
Did you give it a chance to actually finish that headland? It looks like it start the third pass but did not finish. I'd love to see how it looked like after it went around the field.

**Comment by coatsy35** [comment]
> Did you give it a chance to actually finish that headland? It looks like it start the third pass but did not finish. I'd love to see how it looked like after it went around the field.

Couldn't get my video to work so here are the series of screenshots

![fsScreen_2024_09_02_20_03_55](https://github.com/user-attachments/assets/84c7eaea-d59d-4f12-a133-d6d204a358a8)
![fsScreen_2024_09_02_20_04_08](https://github.com/user-attachments/assets/aaa8ff83-ea86-45c1-b701-47d94336438c)
![fsScreen_2024_09_02_20_04_23](https://github.com/user-attachments/assets/28ebb0ac-a0bf-4998-a2e6-310cfa02fdb1)
![fsScreen_2024_09_02_20_04_37](https://github.com/user-attachments/assets/fae1d28d-86af-4d30-bda3-9c751ce7b454)
![fsScreen_2024_09_02_20_04_44](https://github.com/user-attachments/assets/3797929b-ddd7-42eb-adb3-02158ce786b9)
![fsScreen_2024_09_02_20_04_48](https://github.com/user-attachments/assets/52bb73b8-08b8-4952-8c55-0b1a5f602ae2)
![fsScreen_2024_09_02_20_04_52](https://github.com/user-attachments/assets/b64bdd7e-3412-408a-a92f-af18c5ff0917)

**Comment by pvaiko** [comment]
See? Much better. :)
