### ISSUE TITLE
[BUG_SP]Courseplay crashes the game when generating a new course

### ISSUE THREAD

**Issue by Rambo99** [Courseplay/Courseplay_FS22#3386]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
1. Attached a stone picker (modded, ELHO Scorpio 710, (mod name - Elho Scorpio 710 Stone Picker) to the tractors (2 pieces, Fendt 1000 Vario, non-modded), one for each tractor), loaded the old course for two stone pickers, assigned each to its own side (left 1, right 1), sent to the field using autodrive.
2. The tractors arrived, autodrive transferred control to courseplay.
3. Courseplay did NOT work. Tried to start manually. Arrived at the starting point, started. The result is the same.
4. Delete the course from the settings for each tractor.
5. Open the course generator. Set the required parameters.
6. Try to generate a course.
7. The game crashes to the desktop without any error message.

When returning to version 7.4.1.3 of CoursePlay, nothing like this happens.

**Courseplay version**
Version used: Latest 7.4.2.0

**Map**
Nordfriesische Marsch ( https://www.fedaction-letsplay.de/aktuelle-projekte/ls22-nordfriesische-marsch/ , version 4.4 non ohne) 

**P.S.**
 Unfortunately, I was stupid and did not save the game log, but immediately restarted the game, because of which the log was overwritten with a new one. I will try to repeat the error and post the log later.

**Comment by JDTiger** [comment]
See here https://github.com/Courseplay/Courseplay_FS22/issues/3379#issue-2499632294 for your first issue of the tractors not starting their work

**Comment by Rambo99** [comment]
> See here [#3379 (comment)](https://github.com/Courseplay/Courseplay_FS22/issues/3379#issue-2499632294) for your first issue of the tractors not starting their work

It starts about the same, only when trying to generate a new course the game crashes to the desktop. I will probably post the error logs tomorrow. Since today I am already 200 km from my home computer.

**Comment by Tensuko** [comment]
Duplicate then #3379 
In all my years of CP, the game never crashed to desktop on course generation....
That would be a new issue with logfile and pls fill in the complete template.

**Comment by Rambo99** [comment]
> Duplicate then #3379 In all my years of CP, the game never crashed to desktop on course generation.... That would be a new issue with logfile and pls fill in the complete template.

It was not possible to reproduce the problem again. When trying again, the computer first "froze" (thought) for 20-25 seconds, after which it generated a course with rounded edges, a U-turn loop in the middle of the field and a piece of "oncoming traffic" on the initial approach from the "headland" to the "passages" ("snake"). During further experiments with course generation, the "snake" (passages) disappeared, only the "headland" remained. As a result of the experiments, it was possible to get rid of the "turn loop", but there is no piece of "oncoming traffic" (it remained). Additionally, it was possible to find out that even on the course generated by CP 7.4.2.0 on 2,4,6 and so on (any even, multiple of 2) number of vehicles, courseplay does not work. I am attaching the game log files to the message.
[game_CP_7-4-1-3_log.txt](https://github.com/user-attachments/files/16846279/game_CP_7-4-1-3_log.txt)
[game_CP_7-4-2-0_log.txt](https://github.com/user-attachments/files/16846281/game_CP_7-4-2-0_log.txt)
