### ISSUE TITLE
[QUESTION] Turning Titan 18 / or attached trailed implements

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#339]
@pvaiko 

Hi Peter, 
is it possible to smooth or regulate the steering angle if the Tractor is driving backwards? As is saw in my tests, the tractor is steering to fast and so it can not control the attached implement. I think if you regulate the steering angle it will help to drive backwards more smooth with attached trailed implements

**Comment by pvaiko** [comment]
I'm already working on a better reversing algorithm, similar to what is presented in this paper (https://www.kth.se/polopoly_fs/1.602293.1600689194!/AmroThesis.pdf), it will come, sooner or later ...
