### ISSUE TITLE
[BUG_SP] Grosse Probleme mit V 7.4.2.0

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS22#3390]
Grosse Probleme mit V 7.4.2.0
Was leider nicht mehr geht:
- Im Vorgewende ausgeblendete Strohschwaden. Man kann nur noch für das ganze Feld Strohschwaden anlegen oder ausblenden.
- Aus alten CP Versionen angelegte Kurse für mehrere Maschinen funktioniert nicht mehr. Der Traktor startet nicht. 
Das Problem bei der ganzen Sache ist, man kann auf keine frühere Version von CP zurückgreifen. Beim Laden vom Spiel bleibt es einfach hängen und startet nicht.

**Comment by franky-bb** [comment]
Wenn man eine ältere Version von CP (v7.4.1.3) benutzen will kommt in der Log folgender Eintrag:

2024-09-03 10:31 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/frbir/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:58: attempt to index a nil value

**Comment by franky-bb** [comment]
Beim Starten eines Kurses mit mehreren Traktoren kommt bei der v7.4.2.0 folgender Log Eintrag:

2024-09-03 11:17 Error: Running LUA method 'update'.
C:/Users/frbir/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)

**Comment by Tensuko** [comment]
Also erst einmal ist das ja nicht dein erstes issue, daher solltest du wissen wie es richtig geht.
"Grosse Probleme mit V 7.4.2.0" ist keine anständige Überschrift!
Des weiteren hast du dir nicht die bereits gemeldeten Probleme angeguckt, so wie es im Wiki drin steht.
Und zu guter letzt, unser Template nicht ausgefüllt!

> Im Vorgewende ausgeblendete Strohschwaden. Man kann nur noch für das ganze Feld Strohschwaden anlegen oder ausblenden.

Was soll das sein? Strohschwaden kann man nicht ein oder ausblenden... -> Richtiges Issue erstellen, bitte.

Alles rund um Multitool gibt es ein Issue zu.



> Wenn man eine ältere Version von CP (v7.4.1.3) benutzen will kommt in der Log folgender Eintrag:
> 
> 2024-09-03 10:31 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'. C:/Users/frbir/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:58: attempt to index a nil value

Vermutlich weil du noch Kurse aus der neue Version geladen hast, oder mit einer neuen Einstellung gespeichert hast die es in der alten nciht gibt. -> Savegame ohne CP laden, speichern, alte CP Version wieder rein packen und dann musst du halt auf das Update warten.

**Comment by franky-bb** [comment]
Vielen Dank für deine Info:
‘Savegame ohne CP laden, speichern, alte CP Version wieder rein packen ‘
Hat funktioniert. Bin 67 –> was soll man ohne LS mit CP sonst machen.
Nochmals Danke.
MfG Frank
