### ISSUE TITLE
Unable to load previous version of Courseplay

### ISSUE THREAD

**Issue by newell2000** [Courseplay/Courseplay_FS22#3392]
I am not please with version 7.4.2.0 and would like to go back to a previous version.  However, FS22 will freeze up when loading the mods.  I have tried this with versions 7.4.1.3 and 7.4.0.0.  How do I resolve this issue?  Your help will be greatly appreciated.  Thank you.

**Comment by Roby1164** [comment]
Did you create new paths with the new version? I think they are the ones that create the problem, the only solution is to delete those paths, save and change the CP to the previous version. Or, if you have not done too much work, go back to the backup of the game, before the change of the new CP, put the old one back, so everything starts again.

**Comment by newell2000** [comment]
Thank you.
