### ISSUE TITLE
[BUG_SP] CP / Spiel hängt sich auf

### ISSUE THREAD

**Issue by miheki72** [Courseplay/Courseplay_FS22#3393]
Hallo, 

aktuelles CP hängt sich auf , wenn ich einen Kurs mit Tiefenlockerer erstellen will. Unabhängig von Headland , Vorgewende oder Start auf Bahn, Ecken. 

Aktuell mit Standard John Deere Traktor und Standard Agrisem 4m Tiefenlockerer auf Mod Map Nordfriesische Marsch ohne Gräben

**Comment by Tensuko** [comment]
Kein Template ausgefüllt -> closed.
