### ISSUE TITLE
[BUG_SP] Headlands for course generator on custom fields

### ISSUE THREAD

**Issue by falcon470** [Courseplay/Courseplay_FS22#3394]
**Steps to reproduce**
On elm creek combine all fields in the top left that is 4,5,6,7, and try to select headlands in course generator.

**Actual behavior**
Error, works without headlands

**Expected behavior**
Expect it to work like normal fields and generate headlands, to follow the course

**Courseplay version**
Version used: latest

![20240903110005_1](https://github.com/user-attachments/assets/f8fba49a-231f-4385-8ad0-f181f0fe8d3c)

**Comment by Tensuko** [comment]
Why no logfile?
When you select that field, what will be marked, the field outline or the custom field outline?
What are the settings you used?
Again... That would be in the logfile with debug active!

**Comment by falcon470** [comment]
ok wasnt wanting to go into that for an issue i thought might be common knowlage ill post the log file as soon as i find it

**Comment by falcon470** [comment]
[log.txt](https://github.com/user-attachments/files/16851311/log.txt)

**Comment by falcon470** [comment]
if you saw the recent log ignore it i read your post again debug activated doing it again

**Comment by falcon470** [comment]
this log should do it

**Comment by falcon470** [comment]
[log.txt](https://github.com/user-attachments/files/16851363/log.txt)

**Comment by Tensuko** [comment]
That seems to be an issue with the custom field.
How does the start and end point of the custom field border look like?
I think it is where the shop icon sits.... can't see it.

**Comment by falcon470** [comment]
let me move that back and take another screen shot

**Comment by falcon470** [comment]
![20240903115314_1](https://github.com/user-attachments/assets/47f80169-e87c-4362-99d8-f81ede32f258)

**Comment by Tensuko** [comment]
Uhm.... I miss the big white square on your screenshot....
![grafik](https://github.com/user-attachments/assets/e5a5b979-9dd9-48bb-b2da-14651af44c26)

**Comment by falcon470** [comment]
trying to find that on menus i only seem to get that when i generate it hows it supposed to look? i tried making an unbroken chain but i thought i had to completely connect it let me try finding that

**Comment by Tensuko** [comment]
I also have it when going crazy and drive a sculpture with 60km/h and get a course.
![grafik](https://github.com/user-attachments/assets/be8c7f29-68cc-47ae-9444-d75396e59af5)
No overlapping, just end a bit before it.

**Comment by falcon470** [comment]
hmmm judging from your end point i my have had the wrong idea i had the endpoint overlap the start point when i generate it but you seem to just have them close, mines also not displaying that stuff on screen when i generate a course

**Comment by falcon470** [comment]
let me do it again gonna try to copy what you did there

**Comment by falcon470** [comment]
thats exactly the issue if you overlap the start and end points it wont generate end points this fixes it

**Comment by Tensuko** [comment]
Ok I then just see if I make a not to that in the help menu.
Thanks for quick testing, closing the issue.

**Comment by falcon470** [comment]
ty
