### ISSUE TITLE
[Question] Bale Collection with Universal Autoload Trailer

### ISSUE THREAD

**Issue by BradyMoran** [Courseplay/Courseplay_FS22#3395]
Not sure if this is a bug or something I can correct in my settings. When using a universal autoload trailer with ramps to collect bales, the worker "unfolds" the trailer, lowering the ramp prior to starting the course. This causes the ramps to drag on the ground and the trailer slide around a lot. With these trailers, unfolding is not necessary for the loading process. Is there a way for courseplay to only unfold the trailer if required, such as with in game bale loaders? Or can we have a setting to toggle the folding behavior of trailers?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.

disableUnfolding
