### ISSUE TITLE
[BUG_SP] Convoy doesn't work ?

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#3397]
Hello,

I tried to start harvest with a course for 4 combines course was nicely created, but any of my 4 combines wont start. CP arrow was green but combine was standing still. I always set them in the farm and let them AD drive to field where with CP they attached cutter and stopped. When I drove him manually on the field and start CP it also went green but combine went just straight not following a course at all. Course for only 1 combine worked without problems. Did not tested any other equipment so far.

**Steps to reproduce**
Set up course with more then 1 machine and start

**Actual behavior**
CP arrow was green but combine did not moved

**Expected behavior**
Combine will start to move

**Courseplay version**
Version used: 7.4.2.0 

**Log**
[log.txt](https://github.com/user-attachments/files/16853856/log.txt)

**Map**
Back Roads County 4x

**Vehicles/ implements involved**
in-game Case combines (big ones 9xxx)

**Comment by nitroSkirata** [comment]
Already reported and is being worked on:
https://github.com/Courseplay/Courseplay_FS22/issues/3379
