### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3398]
**What is the problem this feature/enhancement solves?**

Its not really a Problem But I don't understand why excavators with a bucket attached can do the silo load mode
I think this would be beneficial for fill types that are heavier than most wheel loaders can handle and the balanced part to this feature is that all though the excavator is less likely to flip it holds less there for increasing the amount of time needed to transport material from one place to another additionally excavators can reach more harsh terrain such as the side of a hill and be more stable 

**Describe the solution you'd like**

For excavators to have the silo load mode with a bucket attached

**Describe alternatives you've considered**

I'm not sure as to weather there are alternatives for this

**Additional context**

**Comment by Tensuko** [comment]
Wont work and wont happen.
