### ISSUE TITLE
[BUG_SP]Pathfinder turn doesn't take headland to drive to the next start of the row and after game restart, transition WP seems to change into a turn WP.

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3399]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

When moving to the next part of the field the tool does not stay inside the field border.

**Expected behavior**

The vehicle and tool stay in the field. If possible follow the headland track

**Screenshots**

![Farming Simulator 22 Screenshot 2024 09 04 - 14 16 44 47](https://github.com/user-attachments/assets/55104fe6-e727-4ea0-ae32-5a6131c4f7e7)
![Farming Simulator 22 Screenshot 2024 09 04 - 14 16 44 47](https://github.com/user-attachments/assets/6a3c2037-b16a-407b-9b21-8843729ab392)

![Farming Simulator 22 Screenshot 2024 09 04 - 14 16 04 25](https://github.com/user-attachments/assets/b1388b86-972c-4e67-a12e-2a1ed5d5d07d)

**Courseplay version**
Version used: 

7.4.2.0 with fix for #3388

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/16870310/log.txt)

**Map**
Map played on.
Alma Missouri

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Ingame 9rx and 1775nt planter

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Can you give me a savegame with the course loaded?

**Comment by Martin-L45** [comment]
Its starting to get a bit weird. The behavior of the tractor changes after i save and restart the game.   
Before save

![Farming Simulator 22 Screenshot 2024 09 05 - 13 52 55 72](https://github.com/user-attachments/assets/14fdec7f-a7de-40a4-a996-0c4dbcc249ca)

![Farming Simulator 22 Screenshot 2024 09 05 - 13 53 02 41](https://github.com/user-attachments/assets/8d63edfc-825e-45b0-bc0d-ec14d6286548)

After save

![Farming Simulator 22 Screenshot 2024 09 05 - 13 54 43 42](https://github.com/user-attachments/assets/8d85174c-8727-4121-b6f6-b308d8564ccb)
![Farming Simulator 22 Screenshot 2024 09 05 - 13 55 31 48](https://github.com/user-attachments/assets/8d165e0a-7ef5-4d5f-b86a-f860c9a75588)

link to savegame
https://www.mediafire.com/file/iijakummsaxm1gr/savegame.zip/file

**Comment by Martin-L45** [comment]
Different equipment similar issue. The vehicle behaves different after save and restart.

Before save
![Farming Simulator 22 Screenshot 2024 09 05 - 14 21 55 41](https://github.com/user-attachments/assets/03b7702b-3c6a-4132-acf0-57a7d55cbec0)
 
![Farming Simulator 22 Screenshot 2024 09 05 - 14 50 00 77](https://github.com/user-attachments/assets/22c14835-5dcf-413c-86ff-ce9d45478c87)

After save and restart. The vehicle is forced into a reverse course. Even when reverse is not allowed. 
xml has <allowTurnBackward value="false"/> on both seeder and aircart

![Farming Simulator 22 Screenshot 2024 09 05 - 14 52 17 78](https://github.com/user-attachments/assets/80dc7660-0835-4aca-89fb-4e485f858b10)

![Farming Simulator 22 Screenshot 2024 09 05 - 14 52 47 26](https://github.com/user-attachments/assets/c97957a6-0564-41e2-b022-cc4d311d81f0)
![Farming Simulator 22 Screenshot 2024 09 05 - 14 53 35 14](https://github.com/user-attachments/assets/e584d0de-6520-49bf-931a-3e56cdb9aa4a)

**Comment by Tensuko** [comment]
Pretty sure you just catched a different waypoint with start at nearest since the target is a completly different position.

**Comment by Martin-L45** [comment]
I´ll try again. and make sure it catches the right track.

**Comment by Tensuko** [comment]
You don't have to, this does not help us anyway.

**Comment by Martin-L45** [comment]
I did it anyway 😊 
Same result as before. Vehicle is forced into a reverse course.
Let me know if you need anything from me.

**Comment by Tensuko** [comment]
@pvaiko 
![grafik](https://github.com/user-attachments/assets/24c3d75f-8a5b-44b8-bebb-b5c90078bc65)
![grafik](https://github.com/user-attachments/assets/6d3fdfb7-85f6-4f23-a5a2-2c4c8753efba)
Seems like a Waypoint changed to a turn after restart, that means saveing the course is faulty, maybe transition WP is broken?

**Comment by Tensuko** [comment]
@Martin-L45 This is your "not respect field border"?
![grafik](https://github.com/user-attachments/assets/df827b83-61eb-454c-8a0e-480470712c64)

**Comment by Martin-L45** [comment]
Yes. It seems to only check for the size of the tractor. not the Working width of the tool it is pulling.

**Comment by Tensuko** [comment]
> Yes. It seems to only check for the size of the tractor. not the Working width of the tool it is pulling.

Got nothing to do with that.

**Comment by pvaiko** [comment]
>  Seems like a Waypoint changed to a turn after restart, that means saveing the course is faulty, maybe transition WP is broken?

Yeah, I'll check that, we are screwing up something when loading the course from the savegame.

**Comment by pvaiko** [comment]
> Yes. It seems to only check for the size of the tractor. not the Working width of the tool it is pulling.

Yes, when switching from one block to the other, we just use the pathfinder and definitely ignore the working width. We aren't using the headlands in this case (unlike in turns where the other row is far away), just plain old pathfinding.

**Comment by pvaiko** [comment]
I have to correct myself: we do use the headland, actually, the originally generated connecting path as a 'preferredPath' for the pathfinder, so the pathfinding should apply a negative penalty for anything close to this connecting path.

As a result, the pathfinder course should be around/close to the headland.

**Comment by Martin-L45** [comment]
@pvaiko 
I have been trying your fix. But i have run into a issue. The tractor gets stuck in this position. It seems to have found a path but i will not drive.

![Farming Simulator 22 Screenshot 2024 09 09 - 17 50 18 66](https://github.com/user-attachments/assets/5603dbb1-b00d-4834-ba04-4c216b7b8940)

[log.txt](https://github.com/user-attachments/files/16933102/log.txt)

**Comment by Tensuko** [comment]
Just wait untill we are done...

**Comment by pvaiko** [comment]
> @pvaiko I have been trying your fix. But i have run into a issue. The tractor gets stuck in this position. It seems to have found a path but i will not drive.

Pull request is still **Draft**, meaning we are still working on it. Wait until it is ready for review.

**Comment by Martin-L45** [comment]
Understood ( i didn't see it was a draft. My mistake)

**Comment by Tensuko** [comment]
You can now try out current main if you want.

**Comment by Martin-L45** [comment]
I have just tried every setup i had issues with before. And now i can not get it to fail!!
I must admit this issue got a lot more complicated than i expected when i first opened it.
Awesome work guys.
