### ISSUE TITLE
Feldkurs wird nicht überschrieben

### ISSUE THREAD

**Issue by Alaxsxag** [Courseplay/Courseplay_FS22#34]
Der erste benutzte Feldkurs kann weder gelöscht noch überschrieben werden. Es bleibt immer der erste angelegte Feldkurs in der Anzeige und dieser wird dann auch immer benutzt...

**Comment by Tensuko** [comment]
Das sollte problemlos funktionieren. Im AI Menü das Fahrzeug auswählen:
![fsScreen_2021_12_24_22_12_59](https://user-images.githubusercontent.com/27344744/147372382-f6bb7b89-7859-4de9-98ae-94a42ed130cb.png)
Und im Kursgenerator Kurs aus Fahrzeug löschen:
![fsScreen_2021_12_24_22_13_03](https://user-images.githubusercontent.com/27344744/147372391-a4924c01-82f4-4c63-bfcb-9f86717b9453.png)

Gerade eben getestet :) Funktioniert.
Vorschlag wie es anders gehen sollte ?
Neuen Kurs generieren sollte auch immer den alten überschreiben, da man ständig neu generieren kann ohne den alten vorher raus zu werfen. Und auch das eben probiert.

Bitte mal die neueste Version laden und bei weiteren Problemen bitte mal das logfile anhängen.

**Comment by Alaxsxag** [comment]
Ich habe den Fehler gefunden. Liegt am Geräte-Mod (hier Pflug). Habe nun mehrere Pflüge getestet und jeder verhält sich anders.

Einer lässt mich den alten Kurs nicht überschreiben, ein anderer fährt nicht los und meldet am Bildschirm "Gerät xyz befindet sich nicht im Transportmodus." - obwohl Pflug zugeklappt ist.

**Hätte ich mir ja aus Erfahrung mit LS19 denken können: checke immer erst die mods die du selbst installiert hast.**

Hat sich also erledigt.
