### ISSUE TITLE
Drescher lässt bei Einstellung "Beete" Getreide auf Feldreihen stehen

### ISSUE THREAD

**Issue by hlwilly27** [Courseplay/Courseplay_FS22#340]
Hallo,

Wenn der Drescher das Feld mit der Vorauswahl Beete bearbeitet, lässt er immer am anfang einer bestimmten Spur einige meter Getreide stehen. Die erste Fahrt ins "Volle" wird noch sauber bearbeitet bei der nächsten Spur ist das nicht mehr der Fall.
Drescher und Schneidwerk sind Original Giants.
Auf den Bildern sollte klar sein was ich meine.

Vielen Dank für die tolle Mod.

Grüße Daniel

![Screenshot (4)](https://user-images.githubusercontent.com/69896665/148031907-b9402f5b-81f7-4a91-9f99-945272725a04.png)

![Screenshot (3)](https://user-images.githubusercontent.com/69896665/148031758-3bf0eadf-6fc0-4183-bff6-8a8b96fca0a4.png)

![Screenshot (2)](https://user-images.githubusercontent.com/69896665/148031645-8119843c-10fe-4214-b8d2-9ffb8ad066a6.png)

**Comment by hlwilly27** [comment]
Version 7.0.0.12

Die Bilder sind in Reihenfolge von unten nach oben zu Betrachten.

**Comment by Tensuko** [comment]
debug im Fahrzeug aktivieren (ganz unten) und laufen lassen -> logfile!

**Comment by hlwilly27** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/69896665/148190277-334bc816-3bc6-4335-90bd-76567d9ffd00.png)
![Screenshot (9)](https://user-images.githubusercontent.com/69896665/148190467-1c0675fe-b3b0-405b-ba11-9bfa525d815c.png)
![Screenshot (10)](https://user-images.githubusercontent.com/69896665/148190631-9ea8078e-97e9-4839-9c25-6b3148a3004d.png)
![Screenshot (11)](https://user-images.githubusercontent.com/69896665/148190830-4979c1ac-cff4-4b00-91d4-191544964015.png)
![Screenshot (12)](https://user-images.githubusercontent.com/69896665/148191022-b75b43bc-2856-4543-89c2-39ba7a7810e1.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7813587/log.txt)

**Comment by hlwilly27** [comment]
Der Drescher fährt auch das Rohr bei den voreingestellten 70% nicht mehr aus, dass der AD Abfahrer starten kann.

**Comment by Tensuko** [comment]
Mit AD ist noch nichts aktivies implementiert. Soweit sind wir noch nicht....
Es klappt nur weil der Drescher das Rohr aus klappt wenn er voll ist und stehen bleibt.

**Comment by Tensuko** [comment]
@pvaiko scheint ein Problem zu sein wenn wir mit dem Pathfinder nen turn generieren, der einen reversepart enthält. Mit dem größeren JD getestet, da ist es nicht vorgekommen, war wohl kein reverse nötig.
![fsScreen_2022_01_05_22_18_53](https://user-images.githubusercontent.com/27344744/148291047-a1e66aef-f667-41b9-9bae-8d0fe3238830.png)
![fsScreen_2022_01_05_22_19_11](https://user-images.githubusercontent.com/27344744/148291053-5ff92eb5-5a99-4ad4-b219-4d3d51a38ea7.png)
Lexion debug:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7817862/log.txt)

**Comment by Tensuko** [comment]
Pls try 7.0.0.13
Reopen if Issue persists.

**Comment by rohne83** [comment]
Ich denke, der Issue müsste nochmal geöffnet werden (hab keine Rechte zu), da es leider noch nicht zu 100% gefixt ist. Beim Anstechen des 2ten, 3ten, 4ten, etc Beets gibts zwar mittlerweile keine Probleme mehr. Aber beim Einfahren vom Vorgewende ins erste Beet bleiben am Anfang immer noch ca 5-10 Meter unbearbeitet.
![fsScreen_2022_01_08_21_44_03](https://user-images.githubusercontent.com/71030138/148677494-3a2c0b6a-c1c3-4ae1-b0a3-a54cc55e8ce0.png)

**Comment by rohne83** [comment]
Nachdem es zwischenzeitlich gefixt war, tritt es jetzt in der Version 7.0.0.20 erneut wieder auf. Immerhin bei weitem nicht so viel wie früher, es fehlt vielleicht ein knapper Meter. Temporär als Workaround vielleicht auch mit größerer Vorgewendeüberlappung vermeidbar, aber trotzdem:
![fsScreen_2022_01_20_20_15_02](https://user-images.githubusercontent.com/71030138/150415656-fc341564-307e-417f-b675-bcd7d3ae323d.png)
![fsScreen_2022_01_20_20_21_25](https://user-images.githubusercontent.com/71030138/150415728-7f570531-8231-4d8f-9b0b-469dba295859.png)

**Comment by pvaiko** [comment]
Should now really be fixed on main.
