### ISSUE TITLE
[Question] Gerade Feldkanten beim Vorgewende?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3400]
Hallo Leute
ist es normal, das beim neuen Kursgenerator  (ab 7.4.2.0) die Vorgewende so "unruhig" generiert werden?
mir ist aufgefallen das vorallem bei schrägen Feldkanten die Kurslinien extrem "gezackt" aussehen:
![fsScreen_2024_09_04_16_39_35](https://github.com/user-attachments/assets/fe13fadf-9048-4dde-9cc0-07ef122360eb)
 ![fsScreen_2024_09_04_16_40_13](https://github.com/user-attachments/assets/4d38c0c4-171b-4f82-b119-4909fe93009c)

aber auch bei geraden Feldkanten, d.h. 90grad oder 0grad sind sie nicht schnurgerade:
![fsScreen_2024_09_04_16_39_39](https://github.com/user-attachments/assets/b5e6e7e2-d4a3-43c7-8456-696c6589256b)

bei z.b. 3 Vorgewenden dupliziert sich das ganze noch:
![fsScreen_2024_09_04_16_41_28](https://github.com/user-attachments/assets/d69aa7d5-06b8-4acd-acee-56926af166ef)
![fsScreen_2024_09_04_16_41_39](https://github.com/user-attachments/assets/68a49702-32f9-4136-a972-91b6d650fbbe)

hat das damit zu tun, das die waypoints nun gefühlt den halben abstand haben (vorher 5m)?

Bei breiten, gezogenen Geräten wird sich das nicht so stark auswirken, der Challenger MT743 (Raupenfahrwerk) mit 6m Grubber auf dreipunkt zuckt aber ganz schön links/rechts beim arbeiten.

kann man die Spur nicht etwas glätten oder den Punktabstand erhöhen? 

lg
andreas

**Comment by Tensuko** [comment]
Hat mit der feineren Feldranderkennung zu tun. Kanns auch wieder hoch drehen dann ist aber wieder das Problem, dass manchmal 2 Felder zusammen erkannt werden die getrennt sein sollen.

Weis ich noch nicht ob ich das ändere. Maximal etwas reduzieren aber mehr wird nicht passieren.

**Comment by andreasthu** [comment]
Hallo Tensuko.
Alles klar,
Habs gestern nochmal durchprobiert - aber ich komme damit nicht klar.
Somit stell ich für in der fieldscanner.lua wieder von
self.normalTracerLookahead = 2.0
Auf
self.normalTracerLookahead = 5.0

Lg
Andreas

**Comment by Tensuko** [comment]
Kannst auch mal mit 3 probieren

**Comment by andreasthu** [comment]
Hallo Tensuko.
Werd mal schaun, 
Btw, wie ist das nun eigentlich wenn ein Miststreuer, Güllebomber per AD nachschub holt und mit CP beim letzten punkt weitermacht?
Beim alten cp kursgenerator war der punktabstand ja 5m, wenn cp 5 punkte vor dem letzen punkt wieder anfängt, waren da 25m überlappung.
Da der punktabstand im innenfeld nun 10m ist, ergibt das eine 50m überlappung. Doch recht viel und bei kleinen Feldern/Maps viel unnötiger verbrauch.
Am vorgewende ist der Abstand nun ja 2m, d.h. die überlappung würde da 10m (5x 2m) betragen.
Oder wird das im kursgenerator 2.0 anders geregelt?
Lg
Andreas

**Comment by Tensuko** [comment]
Der Punkteabstand in metern spielt keine Rolle, da wir nicht in metern arbeiten sondern in Wegpunkten.....

**Comment by andreasthu** [comment]
Ja eh, genau das mein ich.
Ich hab zwar keine Ahnung wieviele Punkte die überlappung ist (ich schätze 5), aber da beim vorgewende der punktabstand nun mit 2m generiert wird, cp aber in der Feldmitte einen 10m punktabstand generiert, ist die überlappung in der Feldmitte nun 5x länger als am Feldrand.
Lg
Andreas
