### ISSUE TITLE
Der Mähdrescher macht Siloarbeit

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/Courseplay_FS22#3403]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared.

**Dedicated server or local hosted server**
Dedicated server yes/no ?

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by RudiBergfeld** [comment]
Hallo,
ich habe festgestellt der Mähdrescher macht nur Siloarbeit in der Version 7.4.2.0 Wenn das zu ändern ist wie kann ich das einstellen. 
[log.txt](https://github.com/user-attachments/files/16904527/log.txt)
 Gruß

Rudi Bergfeld

**Comment by regs1980** [comment]
@RudiBergfeld 
Funktioniert doch alles korrekt so wie es sein soll.
https://drive.google.com/file/d/1q7NOQTzljhSVNguCMd9jSxAik20O8FvN/view?usp=drive_link

In der InGame Hilfe ist einiges beschrieben oder halt hier https://courseplay.github.io/Courseplay_FS22.github.io/#

**Comment by Tensuko** [comment]
Und das Template ist nicht zum Spaß da...
