### ISSUE TITLE
[BUG_SP]  Ballen sammeln/wickeln 

### ISSUE THREAD

**Issue by lexion780** [Courseplay/Courseplay_FS22#3404]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**
![fsScreen_2024_09_06_11_52_51](https://github.com/user-attachments/assets/1f4a980c-3a61-4bbb-a377-b1d3cefbe4e3)

**Courseplay version**
Version used: 7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/16906336/log.txt)

**Map**
Kandelin

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Er sammel ein und bleibt einfach stehen. Mit der Version Courseplay for FS22 v7.4.1.1 läuft es 1a da haben wir keine probleme.
Was können wir machen? 
MFG

**Comment by regs1980** [comment]
@lexion780 
Hast du den Zielpunkt mit angegeben, sodass er erst zu ihm hinfährt, bevor er an AD übergibt oder mehr als 20 m vom Feld gesetzt, so wird direkt zu AD übergeben.

**Comment by Tensuko** [comment]
Welches Autoload ist das?
Von Loki oder Achim?

**Comment by lexion780** [comment]
Zielpunkt hab ich an gegeben.  Neben dam AD punkt gemacht. Das ist der
 https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233456
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=228819&title=fs2022
das ist der Autoload.

**Comment by Tensuko** [comment]
Versuch mal bitte einen Ballensammler von Giants und probiere es damit aus.

**Comment by lexion780** [comment]
Hab es mit dem Arcusi FSX 63.72 von Gaints versucht. Damit läuft es 1a.

**Comment by Tensuko** [comment]
Dann ist das ein Problem mit AutoLoad, das werden wir erst mal nicht mehr anfassen, vlt später mal.

**Comment by lexion780** [comment]
ok. Danke
