### ISSUE TITLE
[BUG_SP] Vorgewende Ecken - aktiviert/deaktiviert

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3408]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
generiere einen kurs auf einem langen schmalen Feld mit einem breiten Gerät (Düngerstreuer) mit der einstellung
"vorgewende Ecken aktiviert"
"Anzahl runder Ecken 1"
"Eckenradius 5"
(z.b. map Somerfeld norden mitte, rechts der BGA)
![fsScreen_2024_09_08_06_51_25](https://github.com/user-attachments/assets/92821d4f-f3eb-4539-8a37-1c0a4f552e03)

**Actual behavior**
A clear and concise description of what happen.
der nördliche Teil wird nicht bearbeitet
![fsScreen_2024_09_08_06_53_02](https://github.com/user-attachments/assets/84824f74-e928-4c65-8fc1-a0468f3f2dfe)

hier die einstellungen
![fsScreen_2024_09_08_06_52_46](https://github.com/user-attachments/assets/d770a870-5136-4478-ab85-636771c5288f)
xpected behavior**
![fsScreen_2024_09_08_06_52_51](https://github.com/user-attachments/assets/43d9ff12-2187-4e16-bc6e-2eaf9e8babbf)
![fsScreen_2024_09_08_06_52_53](https://github.com/user-attachments/assets/b1ea8920-8c13-49c7-b63f-c25ef184106d)

**E

bei "Vorgewende Ecken deaktiviert" wird der Kursbis zum feldende im Norden berechnet (so sollte es auch bei aktivierten Vorgewende Ecken sein):
![fsScreen_2024_09_08_06_53_45](https://github.com/user-attachments/assets/267eb09f-81d6-4aed-bd78-1e8ac71a8fe8)

**Screenshots**
siehe oben

**Courseplay version**
Version used: 
aktuelle 7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Somerset (modhub)

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
NH T6.175 / Knerneland Düngerstreuer

**Relevant script mods**
Mods like Autodrive or VCA and so on.
CP, AD

lg
andreas

**Comment by Tensuko** [comment]
Wie willst du auch mit der Arbeitsbreite da oben arbeiten können. Wont fix.

**Comment by andreasthu** [comment]
Versteh ich nicht.
(Das wont fix)
Wieso sollte er da nicht arbeiten können?
Macht cp ja mit scharfen Ecken auch, siehe letztes bild.
Mit runden Ecken fährt er ja auch in den schmale. Bereich rein, der übrigens über 40m hat, nur nicht bis ganz hoch zum ende.
Jedoch sollte er bis ganz hoch fahren.
Lg
Andreas
