### ISSUE TITLE
[Bug] Cluster of White/Yellow boxes dancing on screen before field turn

### ISSUE THREAD

**Issue by ConductorWon** [Courseplay/Courseplay_FS22#341]
Hello, I have noticed with some attachments, mostly the sprayers, you will get this white/yellow cluster of boxes that dances around on the screen for a few seconds while the vehicle calculates its turn, first, it will do it over the vehicle, and then it does it at the destination of the turn. it's only for a split second most of the time but sometimes it can last up to 5. I have noticed that after this happens the turn of the vehicle is strange and erratic, it will get there eventually but not before doing crazy moves.
![20220103234927_1](https://user-images.githubusercontent.com/76677480/148033679-d89149c6-8c55-4271-b106-2a60e1815707.jpg)

**Comment by Tensuko** [comment]
We have Templates and it would be nice if they are being used, specialy the Informations thats we need.
