### ISSUE TITLE
[BUG_SP] Bale wrapper doesn't see bales on field 

### ISSUE THREAD

**Issue by zinni97** [Courseplay/Courseplay_FS22#3412]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior. 
Square bales and vanilla bale wrapper Kuhn SW 4014

**Actual behavior**
A clear and concise description of what happen.

Bale wrapper won't find bales on field, unfolds tool, searches for bales, HUD says 0 bales on field, folds tool again. 
Bale collector does find the same bales on the same field, issue is only with wrapper!
Setting for wrapped/unwrapped or all bales doesn't make a difference. 

**Expected behavior**
Find unwrapped bales and wrapping 

**Courseplay version**
Version used: 7.4.2.0

**Map**
Map played on.
Hopfach

**Vehicles/ implements involved**
Which vehicle or implement? 
Mod yes/no ? 
all Vanilla, wrapper Kuhn SW 4014

**Relevant script mods**
Mods like Autodrive or VCA and so on
AD yes but irrelevant I'd assume

**Comment by Tensuko** [comment]
Are you sure you have set the correct field as a target?

**Comment by zinni97** [comment]
I just realised I accidentally changed the bale size to the bigger size before baling, the bigger size is not supported by the wrapper, so of course it can't find it. Total user error on my part, sorry! With the proper bale size it works as expected. 
Issue can be closed/deleted, sorry again.
