### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by JimmyBeam1990** [Courseplay/Courseplay_FS22#3414]
![grafik](https://github.com/user-attachments/assets/6528ec5f-bc74-40cf-8f10-eaa72b006bc4)

offensichtlich vergisst CP bei der berechnung der Wendemöglichkeit das anbaugerät und bleibt somit oft an bäumen am feldrand stecken.

Map: Eifel Terralife plus
Autodrive, VCA, Enhanced Vehicle sind aktiv
wird die log benötigt?
CP Version: 7.4.2.0

**Comment by JimmyBeam1990** [comment]
![grafik](https://github.com/user-attachments/assets/c5bcf081-4993-4726-87fc-33de6996948e)
![grafik](https://github.com/user-attachments/assets/423c9122-f274-4479-b7d8-c7a93d8f3e43)

**Comment by Tensuko** [comment]
Template nicht ausgefüllt. Sieht mir außerdem nach entweder falscher selbst gemachter config aus, oder mod issue.

**Comment by JimmyBeam1990** [comment]
Ich habe nichts an irgendeiner config oder ähnlichem herumgebastelt, einfach hier heruntergeladen und gestartet. 
nun die Template ausgefüllt.

**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki 
-> Habe ich die letztenntage gelesen, hat keinen Erfolg gebracht

**Steps to reproduce**
Steps to reproduce the behavior.
-> Kurs auf dem feld 35 auf der Map "Die Eifel TerraLifePlus" anschließend kurs starten und feststellen das er nicht das machtwas er soll

**Actual behavior**
A clear and concise description of what happen.
-> Wie im ersten und im letzten bild zu sehen ist, erstellt CP beim wendevorgang auf dem vorgewende einen riesen kreis welcher auch ausserhalb des feldes erstellt wird und es scheinen objekte nicht berücksichtigt zu werden.


**Expected behavior**
A clear and concise description of what you expected to happen.
-> Naja Das CP bei seinem errechneten wendevorgang die am Feldrand stehenden bäume und Objekte berücksichtigt und vorallem die arbeitsbreite des geräts mit einbezieht um nicht an irgendweinem objekt stecken zu bleiben.

**Screenshots**
If applicable, add screenshots to help explain your problem.
-> Oben zu sehen oder hier ein neues 


![Screenshot_1](https://github.com/user-attachments/assets/8cddfae8-e2ef-45f2-9598-24cf40279aa1)

**Courseplay version**
Version used: 7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/16923008/log.txt)


**Map**
Die Eifel TerraLifePlus
[https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=296767&title=fs2022](url)

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? JA

->Fendt Favorit 800/900 Pack [https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=253277&title=fs2022](url)
-> Quivogne Pack ( 15m Walze aus dem pack ) [https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=279995&title=fs2022](url)


**Relevant script mods**
Mods like Autodrive or VCA and so on.
Könnten der Log entnommen werden, aber ja Autodrive, VCA, Enhanced Vehicle und viele scripte mehr sind vorhanden.

**Comment by Tensuko** [comment]
Tool oder Traktor hat einen turnRadius = 40.5 das kann nicht auf das Feld passen.
Wie vermutet -> Mod Issue.

Guck dir das an: https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.
