### ISSUE TITLE
[BUG_SP] Several Left the course, Stopped

### ISSUE THREAD

**Issue by viniciuspir** [Courseplay/Courseplay_FS22#3415]
Hello, after last update I started to have the issue of Left the Course, Stopped. I got the problem with seeders, sprayers and spreaders. Using headland, up/down, racetrack, I tried many functions but no result, I always need to redirect the tractors to the closest waypoint. Sometimes it continues till the end, sometimes I got the message again.

**Comment by Tensuko** [comment]
Template not filled in.
