### ISSUE TITLE
[BUG_SP] Kurs für 2 oder mehr Maschinen funktioniert nicht

### ISSUE THREAD

**Issue by kleinerblauer** [Courseplay/Courseplay_FS22#3416]
**Steps to reproduce**
Einen Kurs für 2 oder mehr Geräte MIT Vorgewende berechnen lassen und starten.

**Actual behavior**
Die Geräte starten, fahren aber nicht los.
Fehlermeldung "C:/xxx/xxx/xxx/Dokumente/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)

**Expected behavior**
Das Gerät fährt den Kurs ab.

**Courseplay version**
7.4.2.0

**Log**
[log.txt](https://github.com/user-attachments/files/16927652/log.txt)

**Map**
Log ist von Elmcreek, ist aber auf allen anderen Karten ebenso.

**Vehicles/ implements involved**
Alle Erntemaschinen (andere noch nicht versucht). Mod und kein Mod.

**Relevant script mods**
Alle anderen Mods wurden entfernt.

**Comment by nitroSkirata** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/3379
