### ISSUE TITLE
[BUG_SP]  all vehicle   not start task   in multi on  map ALPENBERGLAND with  courseplay 7.4.2.0

### ISSUE THREAD

**Issue by SamuelVauloup** [Courseplay/Courseplay_FS22#3421]
Hello i have a  problem on  map  ALPENBERGLAND. 
(  https://fs22.com/farming-simulator-22-mods/maps/alpenbergland-16-fach-v1-0/ )
I   have the problem with all my vehicle on all field.
When  i try  to  use one on   multi  ,  they don't move and   generate each time  an error in log file  : 

`2024-09-12 07:40 Error: Running LUA method 'update'.
C:/Users/saveus/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/Course.lua:1454: attempt to call global 'calculateHeadlandTrack' (a nil value)
2024-09-12 07:40 dataS/character/humans/npc/pedestrians/generic/npcCommon09_m.i3d (102.43 ms)`

When i create course with  only  one  vehicle   i haven't  this problem.

This  bug appear   only with  this current version ( 7.4.2.0);   on  previous  version i used  (7.4.1.3)  i haven't  this problem.

(I tried  on a fresh savegame  with only  courseplay and  map file    , and  i have  the same problem).

regards

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/3379

**Comment by Tensuko** [comment]
And next time use our tamplate!
