### ISSUE TITLE
[BUG_SP] Even row width isn't even

### ISSUE THREAD

**Issue by BJ-Hawk** [Courseplay/Courseplay_FS22#3423]
**Steps to reproduce**
Try to create any CP fieldwork course on any field using the "Even row with" enabled

**Actual behavior**
Doesn't evenly distribute the working width across the lanes

**Expected behavior**
Evenly distributes the working width across the lanes

**Courseplay version**
Version used:  1.4.2.0

**Log**
[log.txt](https://github.com/user-attachments/files/16998972/log.txt)

**Map**
Zielonka

**Vehicles/ implements involved**
Any vehicle

**Relevant script mods**
Autodrive and EV installed

**Comment by Tensuko** [comment]
Screenshots?

**Comment by BJ-Hawk** [comment]
![Screenshot 2024-09-14 103740](https://github.com/user-attachments/assets/f38a48c5-7c7a-4cf4-8a08-a92da7ae58ab)
![Screenshot 2024-09-14 103756](https://github.com/user-attachments/assets/18a3bda5-272e-45b8-8c33-3a6bd47b7923)

**Comment by Tensuko** [comment]
Narrow field will be fixed in next release, known issue.
