### ISSUE TITLE
[Feature] Option to choose a point/corner of the field where to generate course start

### ISSUE THREAD

**Issue by BJ-Hawk** [Courseplay/Courseplay_FS22#3424]
**What is the problem this feature/enhancement solves?**
Solves the problem of different tools creating different start position, with no way of controlling the start position it's impossible to follow behind with different course, i.e. mowing, raking, windrowing without waiting for one to finish.
Also solves problem with CP/AD interaction, where AD ends and CP starts on the other side of the field.

**Describe the solution you'd like**
An option to choose a starting position of a course, either by utilizing the "Target Position" or by a setting in Course Generator using 8 cardinal directions.

**Comment by Tensuko** [comment]
Thats exactly what the position does.
it is jsut not 100% accurate.

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/8d92b48f-8c35-4d49-82f1-248274aa601d)
![grafik](https://github.com/user-attachments/assets/5b134f6f-b063-4fe9-9a3b-58e8d172893b)
![grafik](https://github.com/user-attachments/assets/cdd7edab-4f14-4d77-8e58-7f7e72048b4a)
![grafik](https://github.com/user-attachments/assets/e6100376-7382-4a8b-bbc2-4db47395db44)

**Comment by BJ-Hawk** [comment]
Ah, okay, the "Field Position" determined it, not "Target Position", i get it. Might be good idea to put it in the help menu.

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/13ee8576-169a-4f92-82a5-8a74b42ecff1)

**Comment by BJ-Hawk** [comment]
Okay, delete this thread, I'm just blind, I was looking for it in the "Course generator basics" and other Course generator chapters...
