### ISSUE TITLE
[BUG_SP] Kurs Probleme seit letzten Update 

### ISSUE THREAD

**Issue by Waldmeister52** [Courseplay/Courseplay_FS22#3425]
Hallo zusammen !

Hab seit dem letzten Update das Problem das die Kurse (wie beim grubbern) wo mehr wie 1 Fahrer konfiguriert wurden nicht geht. Der CP Fahrer bleibt einfach stehen. 

Liegt das am Update ? 

beste Grüße :)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

#3379

Schon bekannt, Wiki lesen, Template bitte benutzen.
