### ISSUE TITLE
Terralife + courseplay

### ISSUE THREAD

**Issue by squall39** [Courseplay/Courseplay_FS22#3426]
Hello, will courseplay be compatible with terralife because the current version does not recognize any cultivation and spraying of it so never starts the work?

**Comment by Tensuko** [comment]
???
Courseplay doesn't check any state of the field and also doesn't care.

**Comment by squall39** [comment]
example on the photo it does not recognize the treatment of weeds and carbolim
![fsScreen_2024_09_14_17_50_04](https://github.com/user-attachments/assets/28696761-9119-4922-b9bb-fac355a0e204)

**Comment by Tensuko** [comment]
What does the msg say?
As said, CP doesn't care about what is on the field....

**Comment by squall39** [comment]
needs to be replenished while the tool is full

**Comment by Tensuko** [comment]
Does the normal helper work?

**Comment by squall39** [comment]
yes

**Comment by Tensuko** [comment]
TerraLife issue then.
