### ISSUE TITLE
Horizontal offset  when using 2 combines /implements etc

### ISSUE THREAD

**Issue by TMac063** [Courseplay/Courseplay_FS22#3427]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create a course with headlands while using two combines or accessories

**Actual behavior**
When using two or more combines or implements next to each other while harvesting or farming I've noticed a horizontal
offset that hasn't been there before (see attachments). I think this came with the new version of CP. 
Did I miss some adjustments in CP that need to be made?

**Expected behavior**
No offset. The shown course line depicts the middle between both combine headers/ implements with the right side (outer lane) or left side (inner lane) of the headers/ implements just about touching the course line

**Screenshots**
see attachments

**Courseplay version**
Version used: 7.4.2.0

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared. -1-

**Dedicated server or local hosted server**
Dedicated server yes/no ? yes

**Map**
Nordfriesische Marsch V 4.2.0.0

**Vehicles/ implements involved**
Which vehicle or implement? NH CR 10.90 with NH Header
Mod yes/no ? no

**Relevant script mods**
Autodrive 2.0.1.6 in use
![CP 2 Drescher Problem](https://github.com/user-attachments/assets/8d01edeb-bd16-4653-bec4-25a66c825102)
![CP 2 Drescher Problem_2](https://github.com/user-attachments/assets/69072968-1a38-4d5a-a98b-06309cf67686)
![CP 2 Drescher Problem_3](https://github.com/user-attachments/assets/ade5e76b-c576-45f2-9209-21098947342b)
[log.txt](https://github.com/user-attachments/files/17005317/log.txt)
[Server log.txt](https://github.com/user-attachments/files/17005318/Server.log.txt)

**Comment by Tensuko** [comment]
Duplicate #3379
