### ISSUE TITLE
Cant Generate course

### ISSUE THREAD

**Issue by matty2123** [Courseplay/Courseplay_FS22#3432]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
try and generate course

**Actual behavior**
nothing happens

**Expected behavior**
a course to generate

**Screenshots**

**Courseplay version**
Version used: 7.4.2.0

**Log**
[log.txt](https://github.com/user-attachments/files/17007085/log.txt)

**Map**
losshugelland

**Vehicles/ implements involved**
tractor and vanilla roller

**Relevant script mods**
autodrive active

**Comment by pvaiko** [comment]
This is one of those issues where I'm really tempted to just close it with as much explanation as the person who created it provided...

**Comment by Tensuko** [comment]
And thats what I do...

**Comment by matty2123** [comment]
Ain’t that what the log provides? Been using cp for a while now. Here’s a detailed description to make it a little easier for you guys to understand. Let’s start I drive my tractor to field 22 I then open the cp menu I then select all the options I want for cp where to start etc etc I then press SPACEBAR to GENERATE!! It  DOESNT GENERATE a course instead just had a white outline round the edge. It then puts ERRORS IN THE LOG (HINT HINT :) ) I can’t explain anymore than that jeez
