### ISSUE TITLE
Nova versão  - o que aconteceu [BUG_SP]

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS22#3436]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Cria novas rotas

**Actual behavior**
Ao criar novas rotas ele esta fazendo curvas fora do campo, neste caso o campo tem espaço fora mas e o campo que nao tem? 

**Expected behavior**
Como era na versao anterior, estava perfeito.

**Screenshots**
Nesta imagem podem verificar que foi criado uma curva para simplesmente mudar de faixa.
![image](https://github.com/user-attachments/assets/6085069f-fc9d-4888-9027-3b7f9f6fb4f9)

**Courseplay version**
Version used:  7.4.2.0

**Log**
[log.txt](https://github.com/user-attachments/files/17013175/log.txt)

**Map**
Map played on. neste exemplo Matopiba, porem ocorre em qualquer mapa

**Vehicles/ implements involved**
nao depende do veiculo ou implemento

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Should be fixed in next release, pls wait for it and do us a favor and translate your stuff in english.
