### ISSUE TITLE
Account 

### ISSUE THREAD

**Issue by mattyk2123** [Courseplay/Courseplay_FS22#3438]
Hello I come in peace matty2123 I appeared to have sent 2 message and unfortunately my account has been blocked please may it be reinstated apologies for any offence that occurred.

**Comment by Tensuko** [comment]
If you accept that we need more informations when we ask for it and not tell US what informations are enough!

An answer like "we cant read the log" is disrespectful, repeating the same msg is trolling. We dont accept that.

We take a lot of our free time to create this mod. I think we can ask for some help finding the issue to help you have a better xperience. We dont have the time and the mood to guess around what could be the cause, or what you could have done, while a few hundred of our users dont have a problem....

Will check your account ban tmr...

**Comment by mattyk2123** [comment]
Yeah I’m very sorry for the inconvenience I have contributed to Courseplay before and I respect you guys! On 16 Sep 2024, at 20:30, Tensuko ***@***.***> wrote:﻿
If you accept that we need more informations when we ask for it and not tell US what informations are enough!
An answer like "we cant read the log" is disrespectful, repeating the same msg is trolling. We dont accept that.
We take a lot of our free time to create this mod. I think we can ask for some help finding the issue to help you have a better xperience. We dont have the time and the mood to guess around what could be the cause, or what you could have done, while a few hundred of our users dont have a problem....
Will check your account ban tmr...

**Comment by pvaiko** [comment]
> Hello I come in peace matty2123 I appeared to have sent 2 message and unfortunately my account has been blocked please may it be reinstated apologies for any offence that occurred.

Apologies accepted. 

Please read the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines). Disrespectful, denigrating comments are unacceptable, will be reported and users banned.

**Comment by Tensuko** [comment]
Your account has been unblocked.

I highly suggest you to wait for our next release and then check if your issue persists.
If that is the case, fill in our template with the steps you did, settings you did, screenshot of the marked field and so on.
And also turn on vehicle debug, before you generate the course so we get more informations.
