### ISSUE TITLE
[BUG_SP] Can't use multiple tools

### ISSUE THREAD

**Issue by rollinghills** [Courseplay/Courseplay_FS22#3441]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
I have been trying to run multiple tools with newest version of courseplay but they don't stay offset an I can't adjust them to be where they should be. It has happened with cultivating tools an now plowing tool.
**Steps to reproduce**
Steps to reproduce the behavior.
Do fieldwork with 2 tools 
**Actual behavior**
A clear and concise description of what happen.
Both tractors drive right down the middle like it's only suppose to be 1 tool
**Expected behavior**
The tools should be offset like they are intended to be.
**Screenshots**
![IMG_0489](https://github.com/user-attachments/assets/d5ba8ce8-9603-4092-afbc-17fdb754d9cf)

**Courseplay version**
Version used: 
v7.4.2.0
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
UMRV
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
John Deere 8rt/John deere 2410
It is a modded setup
**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive installed but not using for fieldwork atm

**Comment by regs1980** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/3379#issue-2499632294
