### ISSUE TITLE
[BUG_SP]Turning speed setting

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#3444]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
It seems to me that there is a problem in the settings. If you adjust the speed of the turn, and I think it is referred to the field work, nothing changes, no matter what speed you set. To make the speed reduce, I had to vary the driving speed, but this also reduces the speed in the transfers. This leads to the problem that some vehicles, especially the modded ones, which are unable to perform correct turns, but doing them at maximum speed, risk unwanted collisions and exiting the path calculated by CP initially.

**Expected behavior**
The turning speed must be adjusted correctly by the parameter in the CP settings panel, and not tied to the driving speed, as it is now.

**Screenshots**
![Screenshot_2](https://github.com/user-attachments/assets/d2926090-26d6-4f2b-a975-7822f7302341)

**Courseplay version**
Version used: 7.4.2.1

**Log**
[log.txt](https://github.com/user-attachments/files/17083463/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. Yes

**Comment by Tensuko** [comment]
Turn speed set to 2:
![grafik](https://github.com/user-attachments/assets/397bb10d-92fd-48cd-8c90-6c5148478e1c)
works as intended.

**Comment by Tensuko** [comment]
> This leads to the problem that some vehicles, especially the modded ones, which are unable to perform correct turns, but doing them at maximum speed, risk unwanted collisions and exiting the path calculated by CP initially.

Those kind of modded vehicles are not our problem.
When the setting works as intended with vanilla game vehicles, there is no bug on our side.
Turn radius can also be a cause of this.

**Comment by Tensuko** [comment]
This for example is a pathfinder turn, the same way we do a transition, ofc we use the driving speed for this due to its longer distance.
![grafik](https://github.com/user-attachments/assets/7afb3e4c-fcf8-4c7e-9f45-23dad396209c)


However we control the speed during a curve and reduce the speed.
Mods with to less of an radius and too high of a speed and acceleration ofc will have problems, but then you got to adjust the drive speed on the field.

No bug, won't change anything, sry!
