### ISSUE TITLE
Bereich verkleinern

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/Courseplay_FS22#3449]
Wenn ich das Silo verdichte ist der Erfassungsbereich so groß, das auf der Straße die Fahrzeuge stehen bleiben.
Erst wenn der Helfer in die Warteposition fährt können die Fahrzeuge wieder fahren.
Kann man den Erfassungsbereich irgend wo einstellen. Roter Bereich
![fsScreen_2024_09_21_17_05_12](https://github.com/user-attachments/assets/115e1493-94e9-45ee-8660-3af0fea28a4d)

**Comment by Tensuko** [comment]
Kann man aktuell nicht.
Ich glaube auch nicht, dass wir für den 22er noch etwas anpassen werden in der Richtung...
Für den 25er werden wir uns etwas besseres überlegen.

**Comment by xerion8300** [comment]
Wenn Sie mir sagen wo man das Einstellen kann würde ich es selber machen.

 

Von: Tensuko ***@***.***> 
Gesendet: Samstag, 21. September 2024 17:12
An: Courseplay/Courseplay_FS22 ***@***.***>
Cc: xerion8300 ***@***.***>; Author ***@***.***>
Betreff: Re: [Courseplay/Courseplay_FS22] Bereich verkleinern (Issue #3449)

 

Kann man aktuell nicht.
Ich glaube auch nicht, dass wir für den 22er noch etwas anpassen werden in der Richtung...
Für den 25er werden wir uns etwas besseres überlegen.

**Comment by Tensuko** [comment]
Müsste ich raussuchen....
Eventuell kann @schwiti6190 das eher sagen.

**Comment by Tensuko** [comment]
Ich kümmere mich drum.

**Comment by schwiti6190** [comment]
Hallo @xerion8300,

sry das ich es jetzt erst schaffe.
Die beiden Werte: `
CpBunkerSilo.UNLOADER_LENGTH_OFFSET = 50
CpBunkerSilo.UNLOADER_WIDTH_OFFSET = 20
` aus https://github.com/Courseplay/Courseplay_FS22/blob/95b897459eeebf40b8a370078d3f23fbf1ba5c23/scripts/silo/BunkerSiloWrapper.lua#L256
kannst du verkleineren, diese Werte gelten dann aber auch für alle Silos.
