### ISSUE TITLE
where do I release the multitool

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS22#3450]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I downloaded the new version 7.4.2.1 and I couldn't find where it releases the multitool, could you please show me?

**Screenshots**

![image](https://github.com/user-attachments/assets/cc599cab-9945-4090-bcfb-875f862e3c16)
![1248130_20240921152852_1](https://github.com/user-attachments/assets/0d48a6f8-c25e-443e-8e3f-c019b11d211a)

**Courseplay version**
Version used: 7.4.2.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/user-attachments/files/17085402/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
I don't know what you want.

**Comment by erksartori** [comment]
In previous versions I could specify how many tractors would work on the field 2, 3, 4, 5... then when I ordered the route to be generated it gave the option of placing the tractor to follow to the right, the tractor to the left and the tractor in the center if it was odd (3, 5, 7...). In this version there is no option to inform how many tractors will work on that route.

I know that in my language it is complicated for you, but I take the photo in sequence, so that it is easy to see. But I will try to do something that can help.

**Comment by Tensuko** [comment]
Ok I tell you... go into CP global settings and turn on expert mode.
btw max multitool is 5 :)

**Comment by erksartori** [comment]
OK, question? Why was this expert mode created? Wouldn't it be better if it was already activated, since there are important things that everyone uses. But it worked. Thanks and I'm sorry.

**Comment by Tensuko** [comment]
For force ppl learn how stuff works before they go all crazy with the settings and don't know what they do.
Also less settings means easier to setup your 1st course.
If you know how everyhing works, fine, if you don't you have a hard to time figure it out.
I also thought about an unlock system......
