### ISSUE TITLE
[BUG_SP] Case IH Magnum 7200 Pro series - cant select bale collect/wrap mode

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#3451]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
attach any bale collecting trailer to Case IH Magnum 7200 Pro series (Giants) and you wont be able to select bale collect/wrap mode

**Actual behavior**
cant select bale collect/wrap mode with Case IH Magnum 7200 Pro series (Giants)

**Expected behavior**
to be able to select bale collect/wrap mode

**Screenshots**

**Courseplay version**
Version used: 7.4.2.1

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Case IH Magnum 7200 Pro series (Giants) official Giants tractor from Modhub with any bale trailer/loader
Mod yes/no ? yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Other vehicles (so far) do not have this problem, only this tractor (and its one of my favorite).
Here is the link to the mod, so you guys can test it.
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=223846&title=fs2022

**Comment by Tensuko** [comment]
No Problem selecting the mode.
![grafik](https://github.com/user-attachments/assets/d62c131d-1d62-4641-93f5-cf77fe04304a)

**Comment by bojanh66** [comment]
now it works after reloading the game, i dont know what could cause this issue, but i am glad it works.
problem solved.

**Comment by andreasthu** [comment]
Hallo Tensuko
hab das auch mit dem Arbeitsmodus
jetzt grade, mit dem MF 7s.210 und dem Arcusin FSX63.72 kann ich den Arbeitsmodus auf "Ballen sammeln/Wickeln" ändern.
gleichzeitig aber hab ich ein zweites Gespann im einsatz, JohnDeere 6250R mit Arcusin FSX63.72, da bleibt "CP: Feldarbeit" und kann durchdraufklicken oder der Tastenbelegung (CP aktueller ausgewählten job ändern) nicht auf Ballen sammen/wickeln umgestellt werden.
auch 3maliges speichern - spiel beenden - neuladen bringt nix. mit dem MF gehts, mit dem JD nicht.
lg
andreas

**Comment by bojanh66** [comment]
I have the same bug with different tractors and different bale loaders, it doesnt matter if its a mod or basegame tractor/trailer, it seems like this bug is random ?

**Comment by Tensuko** [comment]
We have a look

**Comment by Tensuko** [comment]
No Problem at all.
All tested, can all select bale collect.
If you have an actual way to reproduce this, make an Issue with Template and maybe Video with debug and post the log.
![grafik](https://github.com/user-attachments/assets/6c693fb5-e5cb-421d-8224-c9173a99763a)

**Comment by andreasthu** [comment]
@bojanh66 
Reproducable, can you test this please:
Attach your balewagon, then save, end and load the savegame.
The modi cant switch.
De-attach the balewagon, save, end and laod again, the modi are switchable in my game.

The modi "freeze" in the state who is aktiv when attach by saving.

Lg
Andreas

**Comment by bojanh66** [comment]
@andreasthu 
Yes, this is the correct way to reproduce this issue, thank you.
I can confirm this.
@Tensuko  can you please test this and confirm the issue ?

**Comment by Tensuko** [comment]
ok I will check on that way
