### ISSUE TITLE
[BUG_MP] Error loading i3d file combine in shop

### ISSUE THREAD

**Issue by Niedzwiedz980** [Courseplay/Courseplay_FS22#3454]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
When previewing the combine in the shop, the i3d file of the machine in question does not load and an error appears in the log
2024-09-23 17:56 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
F:/FS22/mods4/FS22_Courseplay/scripts/specializations/CpHud.lua:403: attempt to index field 'availableClientJobModes' (a nil value)

**Screenshots**
![Zrzut ekranu 2024-09-23 180406](https://github.com/user-attachments/assets/a08eda6e-2228-457b-925b-a1b487b45d0b)

**Courseplay version**
Version used: 7.4.2.1

**Log**
[log.txt](https://github.com/user-attachments/files/17100648/log.txt)

**Map**
Szpakowo Map
Map played on.

**Comment by Tensuko** [comment]
Should be MP only.

**Comment by Niedzwiedz980** [comment]
[log.txt](https://github.com/user-attachments/files/17101320/log.txt)
