### ISSUE TITLE
[Question]multitool kurs in die neue cp 7.4.2.1 transferieren?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3460]
Hallo Leute.
Ist es irgendwie möglich, alte multitool kurse (vor 7.4.2.0) in die neue 7.4.2.1 version zu transferieren?
Hintergrund ist, das ich einen großen weingarten habe, einige ha, mit dem mod, der 2,3m reihenabstand zulässt.
Daher habe ich mir dafür "manuel" (im ingame kurseditor) Kurse fürs grubbern/mulchen, spritzen und Blattschneiden für jeweils 2 Traktoren gemacht.
Kann ich da was machen bzw wie funktioniert das neue multitool system?
Lg
Andreas

**Comment by Tensuko** [comment]
Nein, wird es auch nicht geben weil es nicht geht. Das Prinzip ist ganz anders jetzt.

Für Reben kannst du es ja mal so versuchen ob es jetzt automatisch geht.

**Comment by andreasthu** [comment]
Nein, geht nicht automatisch mit den mod reben, Habs schon versucht. Nur mit den giants 3m reben.
Wie ist denn das prinzip jetzt aufgebaut?
Denn dann würd ich mir die kurse wieder manuell per ingame editor machen können/müssen.
Lg

**Comment by Tensuko** [comment]
Siehe changelog und ingame hilfe.
Am besten baust du dir komplett eigene Kurse für jede mp spur. Anders gehts eh nicht.

**Comment by andreasthu** [comment]
ja ok, hab ich mir auch schon gedacht.
2. option wäre auf 7.4.2.0. zurückzugehen,
aber da gibts ja ein problem mit den wenden der normalen helfer.
scheinbar vergisst oder übersieht ein alleingelassener cp helfer am reihenende ziemlich oft das   headlandTurn="true", rowEnd="true" oder rowStart="true" und wendet mit bearbeitung im bogen 
lg
andreas
