### ISSUE TITLE
Save/Load game very slow

### ISSUE THREAD

**Issue by pvaiko** [Courseplay/Courseplay_FS22#3461]
> Island bypass should only matter when you generate.
> 
> Would be great if we could compare apples to apples, if you now have two 40 km long courses you did not have with 7.4.1.3, that may skew the results a bit...

I don't have any saved courses on game since updating Courseplay to current version. I deleted all old 7.4.1.3 as wondered if too much old info was causing the game to take so long to load and save. I now have literally just the one course created and saved on the map and it's still causing the game to load and save slow. If I disable Courseplay in the mod menu before loading, the loading and saving goes back to normal pretty much.

The map I'm playing on is Flatout Farm and can be downloaded from Author's Google Drive Link: https://drive.google.com/file/d/1OaMceN3iVUpeNYSfsorqND8uR-aEH6e9/view

My save game:
[savegame13.zip](https://github.com/user-attachments/files/17135351/savegame13.zip)

Harvesters I'm using on the Course are from the Giants ModHub https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=253608&title=fs2022

_Originally posted by @cwattyeso in https://github.com/Courseplay/Courseplay_FS22/issues/3457#issuecomment-2374658665_

**Comment by pvaiko** [comment]
For the record: that savegame has some courses with 25k waypoints, which, because the way we now store multitool courses, end up as 75k per vehicle in a 2 multitool config. This clearly does not scale well.

**Comment by cwattyeso** [comment]
Yeah I was guessing it's probably that Potato Harvesting Course on Field 19 which is taking up way too many resources. Hopefully when it's completed I can delete the course and never need to do such a thing like it again on that Map and Save. It's just something that could potentially be an issue for people on large maps with root crops as traditionally all the root crop harvesters are narrow width, so require looks of lines and waypoints to complete a field.

**Comment by pvaiko** [comment]
@cwattyeso can't load your savegame it is complaining about a missing FS22_DD_Production_Silo

**Comment by cwattyeso** [comment]
Okay you need this mod then @pvaiko 

[FS22_DD_Production_Silo.zip](https://github.com/user-attachments/files/17164137/FS22_DD_Production_Silo.zip)

**Comment by pvaiko** [comment]
Looks like there are more mods missing than that, just give it go, it's on main already anyway.
