### ISSUE TITLE
[Question] graincarts not working properly 

### ISSUE THREAD

**Issue by Prycekeen** [Courseplay/Courseplay_FS22#3462]
I have 4 combines going and 5 graincarts and the carts will not unload the combines.  Sometimes the carts say path not found other times the graincarts will go but itll take them 10 minutes to figure out where to go.  Last time i used them it worked fine and I have changed nothing any help is appreciated

**Comment by Prycekeen** [comment]
to add the fields are very large and the map is north Dakota hastings

**Comment by Tensuko** [comment]
So the course is the same as before 7.4.2.0?

**Comment by Prycekeen** [comment]
I dont have courses saved the last courseplay i had before this one was from march of this year.  i always just make a new course everytime i go to a different field.  Not great at explaining tech stuff.

**Comment by Tensuko** [comment]
So what is your CP Version?

**Comment by Prycekeen** [comment]
7.4.2.1 is what I was using thought that was the issue so I went back to 7.4.2.0 but it’s still doing the same thing

**Comment by Boogietr0n** [comment]
I have experienced this, but only on large fields where the graincart may not be seeing the combine. Once they are near each other again, it seems to 're-sync' and continue working again, at least for me.

**Comment by Prycekeen** [comment]
i can start the grain carts right next to the combines and they don't do anything its weird lol also my game crashes everytime i try and make a new course which is odd

**Comment by Boogietr0n** [comment]
Might be a good opportunity to make sure no other vehicle scripts are installed, or try removing courseplay, run game, save, then reinstall courseplay. I have had to do that a few times too.

**Comment by Prycekeen** [comment]
its aslo on a server.  But what do you mean other vehicle scripts?

**Comment by Tensuko** [comment]
Can you test 7.4.2.3?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Based on another issue, it works again.
