### ISSUE TITLE
[BUG_SP]Driver does not start multitool course, when he have to drive to the start 1st (only when copy and paste the course)

### ISSUE THREAD

**Issue by mpupedis** [Courseplay/Courseplay_FS22#3463]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use two plows to plow a Contract field (Field 11 on Elmcreek).
Setup a Multi-tool course.
Drive vehicles to field (Autodrive, for simplicity)
Start Courseplay on arrtival.

**Actual behavior**
First tractor drives towards the start of the course, then stops and unfolds the plow.  It never completes the final turn to start the course.  Same behavior with the second tractor.  On one field (Field 68 on Elmcreek), with a three tool course, the first tractor would start, but the other two would just stop at the course start.

**Expected behavior**
The tractors start the course as planned.

**Screenshots**

**Courseplay version**
Version used: 7.4.2.1

**Log**
[log.txt](https://github.com/user-attachments/files/17141936/log.txt)

**Map**
Elmcreek (vanilla)

**Vehicles/ implements involved**
Class Axion 870 (x2)
Ecomat plow (x2)
Mod yes/no No, both vanilla.

**Relevant script mods**
Autodrive, Better Contracts, Courseplay, FS22_kvernelandIXterB18 (needed for Better Contracts custom vehicle list)

Please let me know if you need any additional information.

**Comment by Tensuko** [comment]
Wait for 7.4.2.2

**Comment by mpupedis** [comment]
@Tensuko The fix works for the first driver sent on the course.  The second driver still stops, unfolds the plow, and just sits there.  If I manually drive them to the starting point, the second driver takes off without any issue.  The same error appears in the log file as before:
2024-09-28 21:35 Error: Running LUA method 'update'.
C:/Users/xxxxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua:66: attempt to index field 'beforeTurnStartWp' (a nil value)

**Comment by Tensuko** [comment]
Just try it and yes.... thats strange why only on start the 2nd one....
