### ISSUE TITLE
[BUG_SP] Error with multiple vehicles

### ISSUE THREAD

**Issue by Joan-Bunny** [Courseplay/Courseplay_FS22#3464]
If I generate a CP course with several vehicles, everything is fine. The first vehicle starts moving, the second vehicle does not start moving and an error appears in the log:
Error: Running LUA method 'update'.
C:/Users/Johanna/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua:66: attempt to index field 'beforeTurnStartWp' (a nil value)

The error came with version v7.4.2.0 and is now still in version v7.4.2.1

**Comment by Tensuko** [comment]
Template....
