### ISSUE TITLE
[BUG_SP]Ballen sammeln/wickeln

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3465]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
zu #3451 

**Steps to reproduce**
Steps to reproduce the behavior.
Ballensammler Arcusin FSX63.72 (z.b.) an JD 6250R oder an MF 7s.210 schon

**Actual behavior**
A clear and concise description of what happen.
Ballensammler Arcusin FSX63.72, CP-modus Ballen; sammeln/wickeln funktioniert an JD 6250R nicht, an MF 7s.210 schon

**Expected behavior**
Ballen sammeln/wickeln sollte zum auswählen sein

**Screenshots**

MF, Ballensammler **AN**gehängt, modus korrekt
![fsScreen_2024_09_26_17_25_35](https://github.com/user-attachments/assets/836a616a-c1ad-4ce3-ab46-2eca30d2dc24)

MF, Ballensammler **AB**gehängt, modus korrekt
![fsScreen_2024_09_26_17_25_59](https://github.com/user-attachments/assets/88d438cc-01bc-40e3-b05d-4a59d4113d85)

MF, Ballensammler wieder **AN**gehängt, modus korrekt
![fsScreen_2024_09_26_17_26_09](https://github.com/user-attachments/assets/2ad1719f-29bd-415e-8ae1-320378333bee)

JD, Ballensammler **AN**gehängt, modus  NICHT korrekt
![fsScreen_2024_09_26_17_26_17](https://github.com/user-attachments/assets/20fdab32-31ea-4783-834e-9b1ae90d4182)

JD, Ballensammler **AB**gehängt, modus korrekt
![fsScreen_2024_09_26_17_26_30](https://github.com/user-attachments/assets/5e3d7676-7044-4e2a-9e77-76aec6846b42)

JD, Ballensammler wieder **AN**gehängt, modus NICHT korrekt
![fsScreen_2024_09_26_17_26_37](https://github.com/user-attachments/assets/75e081ad-82ba-4a9a-97cf-e79a0097735c)

durch klicken der linken Maustaste auf Ballen: sammeln/wickeln bzw CP: Feldarbeit kann ich im MF durch beide wechseln, im JD nicht.
 
funfact:
siehe letzten satz, grad nochmal probiert, jetzt grade ist der CP arbeitsmodus "fest", d.h, im MF ist Ballen sammeln/wickeln aktiv -  im JD Feldarbeit - und ich kann nun im MF auch nicht mehr durch draufklicken durchschalten. :-(
immerhin ist es der richtige modus.

**Courseplay version**
Version used: 
7.4.2.1, aktuelles main
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/user-attachments/files/17151754/log.txt)

**Map**
Map played on.
somerset USA

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Giants models, keine mods
Arcusin FSX63.72
JD 6250R
MF 7s.210

**Relevant script mods**
Mods like Autodrive or VCA and so on.
CP, AD, (siehe log)

lg
andreas

**Comment by Tensuko** [comment]
Can't reproduce
![grafik](https://github.com/user-attachments/assets/aebba3bc-7d77-4c3e-92be-b4aa11a1b739)

**Comment by andreasthu** [comment]
😀 das ist der Vorführeffekt.
Ich hatte vor ein paar tagen, dienstag glaub ich, auf den Feldern mit genau denselben Gespannen Heuballen geborgen. Das war mit v7420, da hat alles funktioniert wie es sollte.
Nun hab ich (vom gleichen Graschnitt) die gewickelten gegärten Silageballen holen wollen, mittlerweile mit v7421, geht es (bei mir teils) nichtmehr.
Ansonsten keine neuen mods in den letzten tagen installiert.
Lg

**Comment by Tensuko** [comment]
Kann so leider rein gar nichts machen.
Solange es generell geht und ich es so ausprobiere und modi funktioniert, werden wir da nichts anfassen.
Wenn du rausgefunden hast, was es auslöst, melde dich gerne wieder, aber ansonsten ist das nur probiere und eventuell wieder andere dinge kaputt machen....

**Comment by andreasthu** [comment]
Ok,
Aber wieso schließt du es dann?
Das "Phänomen" haben doch einige cp user hier.
Lg

**Comment by Tensuko** [comment]
Mach halt wieder auf sobald es eindeutig reproduzierbar und nachverfolgbar ist.
Ansonsten liegt nur unbstätigter kram rum.

**Comment by andreasthu** [comment]
Guten morgen Tensuko
ich habs mal probiert,
modsordner in mods_aaaa umbenannt, neuen mods ordner erstellt.
da drinnen nur CP, AD und die Somerset map.
spiel gestartet und save geladen:
den arcusin beim JD angehängt, nun kann zw Feldarbeit und Ballen gewechselt werden.
in den MF gestiegen, da bleibt es fest bei Ballen - keine möglichkeit auf Feldarbeit zu wechseln.

hab den mods ordner wieder gelöscht, mods_aaa wieder zurück umbenannt und das spiel mit allen mods gestartet.
das gleiche wie vorher, hab den arcusin wieder am JD angehängt und kann auch da durch Ballen und Feldarbeit wechseln.
der MF bleibt nun auf Ballen fixiert.

gestern war der MF auf ballen, und der JD auf Feldarbeit fixiert.
keine ahnung an was es da hängt.

btw, ich hab da keinen "reopen" o.ä. button

lg
andreas

**Comment by andreasthu** [comment]
REPRODUZIERBAR
wenn der arcusin bei spielstand angehängt ist, ist die einstellung fixiert.
Wird der arcusin erst im laufenden spiel angehängt kann man die modi normal durchschalten.
Getestet mit mods und ohne mods.
Und dann mehrfach, d.h. hab mindestens 10x neu gestartet mit verschiedenen kombinationen und konfigurationen.

Ist der modus Ballen beim speichern aktiv, ist nach dem speichern, beenden und neustarten nur ballen möglich,
Ist Feldarbeit als modus gewählt, geht nach dem neustart nur Feldarbeit.

Als workaround erstmal alle Ballenwagen abhängen vorm spiel beenden.

Lg
Andreas
