### ISSUE TITLE
[BUG_SP] 7.4.2.1 Beta Generating new courses in large fields

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/Courseplay_FS22#3467]
I installed cp 7.4.2.1 beta.

I like to play with big equipment on the "Western Australia 16x" map.
When I want to create a 3-vehicle course with the Borgault 27.4 weeder on field 22, the system freezes.
My system has ddr 4 48 gb ram installed. Will the problem be fixed in the future?
How many hectares of fields does CP support?

**Comment by Tensuko** [comment]
Bug reports -> use tamplate
Or use Question.

Patient is the key.
Ram, CPU, GPU, all that doesn't matter.
Its the LUA Engine in FS that makes it slow.

**Comment by pvaiko** [comment]
If you have no islands on those fields, deactivate island bypass.

**Comment by huseyinsayar** [comment]
I updated cp to 7.4.2.2. Unfortunately, there is an island in the field... But when I turned off island creation, it created it very quickly. It still freezes.

**Comment by Tensuko** [comment]
Some fields and depending on settings, the game will "freeze". Thats normal and can't be changed.
It keeps work in the background, only the UI and stuff can't be controlled.
