### ISSUE TITLE
[Enhancement] Combine selfunload, check if trailer got the same filltype

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#347]
**Steps to reproduce**
Drescher auf selbst abtanken und bei den Anhängern am Feldrand einen mit anderer Frucht

**Actual behavior**
Drescher fährt selbst abtanken, möchte aber anscheinend in einen bereits mit einer anderen Frucht gefüllten Anhänger entladen

**Expected behavior**
Drescher sollte die falsche Frucht erkennen und diesen Anhänger nicht anfahren.
Erweitertet Wunsch: Die Anhänger werden von vorne nach hinten der reihe nach befüllt.
PS. Der Drescher sollte auch kurz warten bis er sein Stroh entleert hat bevor er sich auf den weg macht um sein Getreide abzuladen.

**Screenshots**
![Screenshot (66) cut](https://user-images.githubusercontent.com/47928255/148097700-1d3487aa-7dc7-4d56-aa6c-71d6ce734d82.png)

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Frankreich

**Vehicles/ implements involved**
Nein, keine Mod-Fahrzeuge

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Well, actual Version is .11 but anyway, haven't touched this.
I must say your smal Road Train looks rly colorful.
Will see if we can improove this.

**Comment by blubstar86** [comment]
additional:

If the trailer has like 2000L capcity left and the combine comes to unload in this specific trailer, he is only filling the 2000L and returns back to fieldwork with whatever he has left in its Grain tank, instead of unloading it into another trailer.

**Comment by Tensuko** [comment]
Check if there is another valid trailer to fill in the rest if combine is still over X % or something like that.
For like 5% we don't need to cross the field for unload.

**Comment by Tensuko** [comment]
Can you try if that is still an Issue in 7.0.0.21 ?
If there is still a problem, pls reopen that Issue.

About that continue, we keep that in mind.

**Comment by blubstar86** [comment]
Hey, yep, same problems in .21

- dosent wait for straw swath -- starts instand drive to trailer when combine full
- keeps targeting trailers with wrong fruit
- returns to fieldwork when target trailer is full but combine isnt empty, even if another empty trailer is available
![Screenshot (68)](https://user-images.githubusercontent.com/47928255/150633009-a816c4f4-087a-4b5f-b016-c044c07597d4.png)
![Screenshot (69)](https://user-images.githubusercontent.com/47928255/150633017-31fd8432-c0bf-472d-88c5-bd8580a60ece.png)

**Comment by blubstar86** [comment]
@Tensuko , im not sure how i can reopen this issue
