### ISSUE TITLE
Boom Height of Self Propelled and Trailed Sprayer

### ISSUE THREAD

**Issue by leo32128fs** [Courseplay/Courseplay_FS22#3470]
Hello good evening, I would like you to clear up this doubt for me, if it is possible to make the bars of the Self-Propelled and Drag Sprayers work at angles adjusted by the player, I would really like this feature, it would help a lot, because there are some that are completely lowered or completely raised, clear up this doubt for me, I have attached some prints as an example! Thank you in advance!!

![Captura de Tela (2)](https://github.com/user-attachments/assets/c2ec9c34-b7f4-4a7f-a8fd-dd84bd78f174)
![Captura de Tela (3)](https://github.com/user-attachments/assets/3b77d86a-fab5-431c-92b4-dd51523ff027)
![Captura de Tela (4)](https://github.com/user-attachments/assets/d531f8b8-5189-44f8-9ac4-ef811d654c1b)

**Comment by Tensuko** [comment]
That should be controled by giants and we have no intention to control this.
