### ISSUE TITLE
[Question] Courseplay doesnt detect correct working width of Claas Disco Pack mowers

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#3471]
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=229254&title=fs2022

Rear mower has 10m working width, but CP doesnt detect it at all. 
Would it be possible to fix this ?

**Comment by Tensuko** [comment]
Use the hud or the vehicleconfig.
Thats what we made that for.
