### ISSUE TITLE
[Question] Bale wrapper Kuhn SW 4014 as mod doesnt work

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#3475]
Ich nutze den Ballenwickler aus dem Better contracts Mod. Das ist eine Kopie des Giants Wickler Kuhn SW 4014, der auch 240cm Ballen wickelt. Mit CP 7.4.1.3 (und früher) hat der noch funktioniert. Mit CP 7.4.2.1 lässt sich der Modus nicht mehr von "Feldarbeit" auf "Sammeln/Wickeln" umstellen. Der Giants Wickler geht mit 7.4.2.1.

Ist das ein Fehler von CP oder des Mods? 

Courseplay version
Version used: 7.4.2.1

Vehicles/ implements involved
Giants Kuhn SW 4014

[Better contracts Kuhn SW 4014](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=234921&title=fs2022)

Relevant script mods
Autodrive etc.

**Comment by Tensuko** [comment]
Fixed in next release.
Suche benutzen bitte.
