### ISSUE TITLE
[BUG_SP]Course around small islands are lost after save/reload game

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/Courseplay_FS22#3477]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

Before save game
[log.txt](https://github.com/user-attachments/files/17175601/log.txt)

![Farming Simulator 22 Screenshot 2024 09 28 - 18 45 49 07](https://github.com/user-attachments/assets/e9a3ba99-ed44-458f-aacb-c035c31f7fec)

After reload game

[log.txt](https://github.com/user-attachments/files/17175606/log.txt)

![Farming Simulator 22 Screenshot 2024 09 28 - 18 47 33 27](https://github.com/user-attachments/assets/513f650d-5d58-44e2-a8dd-03dbdf685734)

**Courseplay version**
Version used: 
7.4.2.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Snigyman** [comment]
I have the same problem. In addition, when I generate a route for two harvesters, the harvester that generated the route detects islands in both the left and right lanes, but if I upload this route to the second harvester, the route without islands in both the left and right lanes is uploaded.

**Comment by Martin-L45** [comment]
I just tried your last pull request and it works perfectly. Saves and reloads the small islands with no issues.
Awesome job

**Comment by pvaiko** [comment]
Thanks for checking. We are awesome at fixing what we screwed up earlier :)

**Comment by Martin-L45** [comment]
you might have screwed it up. But every time you fix it gets better than it was before.
Did you fix the problem when the combine creates a pocket for unload? Because now it works fine... #3481

**Comment by pvaiko** [comment]
> Did you fix the problem when the combine creates a pocket for unload? Because now it works fine... #3481

Haven't looked at it yet, hoping it was caused by waypoints too far away. We moved them closer now, so if that caused it might as well be fixed.

**Comment by Martin-L45** [comment]
I tried multiple combines on Elmcreek and my modded combines on my normal game map. Haven't seen any issues. 
I think it is good👍
