### ISSUE TITLE
[BUG_SP] Vehicle reverses uncontrollably 2

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3478]
Some new problems very similar to https://github.com/Courseplay/Courseplay_FS22/issues/3469

**Video links**
1: https://youtu.be/HvPG1J16agc
2: https://youtu.be/ZpX9crWdO6k

**Courseplay version**
Version used: 7.4.2.2

**Log**
[log.txt](https://github.com/user-attachments/files/17176006/log.txt)

**Map**
Krumbach

**Vehicles/ implements involved**
Fendt 943 MT with Rostselmash K12200

**Relevant script mods**
Autodrive etc.

**Comment by Tensuko** [comment]
Just for ducomentation:
The path seems to short to do proper aligment
![grafik](https://github.com/user-attachments/assets/8e441a08-7f56-4d37-9c07-7a201f2bd5c8)

[log.txt](https://github.com/user-attachments/files/17178979/log.txt)
