### ISSUE TITLE
[BUG_SP] Düngerstreuer - Breite wird nicht erkannt beim Kurserstellen und setzt sich zurück

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#348]
**Steps to reproduce**
Düngerstreuer kaufen - Breite auf 21m stellen - Kurs generieren (Breite auf 41m) - Kurs auf 21m generiert - Kurs start - Breite wieder auf Max

**Actual behavior**
Die Eingestellte Breite beim Streuer wird vom Kursgenerator nicht automatisch erkannt. Und beim Starten des Helfer setzt sich die eingestellte Breite auf Default zurück

**Courseplay version**
Version used: 7.0.0.12

**Map**
Erlengrat

**Vehicles/ implements involved**
Standard Fahrzeuge und Geräte

**Relevant script mods**
nein - standard

**Comment by Tensuko** [comment]
> Und beim Starten des Helfer setzt sich die eingestellte Breite auf Default zurück

Was genau heist das ?
Die Breite die im Generator bzw im Mini Hud steht, oder die Streubreite die man eingestellt hatte (F1 Menü)?

**Comment by 0scarZulu** [comment]
Wenn ich beim Streuer 21m einstellne würde er die bei manueller Fahrt ausbringen. Ersten erkennt CP die eingestellte Workarea nicht und die Streubreite beim Geräte wird zurück gesetzt. DIe Breite die im Generator steht ist ja die, welche ich mühselig manuell einstelle und dann den kurs generiere.

**Comment by andreasthu** [comment]
ich kann dasselbe berichten.
ich würde gerne ein 30m breites Feld mit 2 x 15m Streuen - einmal hin und wieder zurück.
nicht mit 1x 42m und viel verlust.
manuell (auch mit gps) geht das, der giants-helfer stellt die arbeitsbreite aber immer auf maximum (42m)
wenn ich nun am Düngerstreuer 15m Arbeitsbreite einstelle erkennt cp aber immer noch 42m Arbeitsbreite.
dann stelle ich im kursgenerator die arbeitsbreite manuell auf 15m und lasse einen cp-kurs generieren.
funktioniert wunderbar 
aber sobald ich den cp-helfer starte, stellt cp bzw giants die Arbeitsbreite wieder auf 42m um und der 15m kurs hin und zurück wird mit 42m Streubreite abgefahren.
Lösungsansätze:
1. ev sollte cp die "manuell eingestellte" Arbeitsbreite erkennen, damit man nicht von 42m 270x auf - (minus) klicken muss um den 15m Kurs zu generieren.
2a. sollte der cp-helfer die manuelle arbeitsbreite beim Einstellen/Streuen nicht verstellen.
oder aufwändiger und für vorgespeicherte kurse sinnvoll:
2b. sollte der cp-helfer die kursarbeitsbeite erkennen und den streuer darauf einstellen (oder die nächsthöhere mögliche AB).

lg
andreas

**Comment by Tensuko** [comment]
Muss ich mir im debug angucken, was da passiert wenn man die Breite vom Streuer verändert.
Warum die Streubreute beim Helfer zurück gesetzt wird kann ich nicht sagen, aber das finden wir bestimmt raus.

**Comment by throsten** [comment]
2b wäre schon cool...

**Comment by Tensuko** [comment]
Pls try 7.0.0.13
Reopen if Issue persists.
