### ISSUE TITLE
[Question] Default setting for Center Direction

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3482]
Just an observation but should the centre direction be defaulted to anticlockwise for new users? as most will be using lands for combines etc... and currently clockwise is the wrong way around and the pip is towards the fruit. I keep having to change it for each combine harvester. Perhaps there are more common tools that need it setting to clockwise though? No big issue just thought it would be more user friendly if it did what might be most commonly used as default 

![fsScreen_2024_09_29_18_07_16](https://github.com/user-attachments/assets/a0c9f294-9bfe-4ca6-a8a2-fff05fd8e73f)

**Comment by Tensuko** [comment]
Changed for next Version.
