### ISSUE TITLE
[Feature] Save courses in Savegame folder so Steam Cloud transfers between devices.

### ISSUE THREAD

**Issue by Boogietr0n** [Courseplay/Courseplay_FS22#3486]
**What is the problem this feature/enhancement solves?**
I play on two computers, one is a laptop at my desk and one is my gaming PC in the living room. I frequently switch between the two devices. Being able to save courses between devices would be a dramatic improvement, allowing me to save courses, custom fields, other courseplay information between devices and per savegame and hopefully have it transferred between devices with Steam Cloud.

**Describe the solution you'd like**
Save Courseplay data in savegame folder, so it is saved with Steam Cloud.

**Describe alternatives you've considered**
Currently I use google drive as a source of truth to accomplish this, by saving data at the end of a session and uploading, then downloading again on the next machine I use. 

**Additional context**
As far as I am aware, Steam Cloud saves all data in the savegame folders. If this is not the case, then please accept my apologies. I have been using courseplay for years now, self taught, and I could easily be missing a simple feature that may already exist!

Thank you!!

**Comment by Tensuko** [comment]
We dont save them in savegame on purpose.
