### ISSUE TITLE
[BUG_MP] John deere CP690 Skip a row

### ISSUE THREAD

**Issue by jdunn1019** [Courseplay/Courseplay_FS22#3487]
Hello.. 

So i maded the courseplay and   headleaded worked then the second row its skip.. This is on MP 

here is a picture
![screenshot_2024_10_01(cottonsskipaline](https://github.com/user-attachments/assets/d60f4295-263d-4fbb-bca8-794100589777)

idk if its a bug or not i just letting u guys know about it thanks

**Comment by Tensuko** [comment]
Could be the course bug, wait for next update pls.
