### ISSUE TITLE
[Question] Target Position Rotation

### ISSUE THREAD

**Issue by mpupedis** [Courseplay/Courseplay_FS22#3488]
When using the Target Position for Bale Loading or Combine Unloading, the driver tries to align with the mark in the opposite direction of the rotation.  Am I just thinking of the wrong usage of the Target Position rotation?

**Comment by Tensuko** [comment]
Arriving = arrow direction.
Leaving = agains the arrow direction (180°)
Also should have an offset when leaving so no colission with someone waiting there.

Can't do it the other way and makes the most sence.
