### ISSUE TITLE
[BUG_SP] Editing course on multitool

### ISSUE THREAD

**Issue by Snigyman** [Courseplay/Courseplay_FS22#3493]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior. 

When i try edit course with two or more vehicles, this won´t work.

**Actual behavior**
A clear and concise description of what happen.

Course editor with 2 or more vehicles didn´t work. Error with LUA mouse event.
**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.4.2.3

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

![20241003205019_1](https://github.com/user-attachments/assets/0ba148d3-72e5-44d7-af42-041a7af35135)

**Comment by Tensuko** [comment]
@schwiti6190 
This would need a pop-up on "edit course" when it is a multitool course to select the lane you want to edit....
