### ISSUE TITLE
[Question] Ballen Sammeln, Am Feldrand abladen

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/Courseplay_FS22#3496]
Hallo Zusammen,

ich habe mal eine Frage, die einer von euch Profis mir bestimmt beantworten kann.

Ist es noch möglich, dass ich mit dem Arcusin AutoStack auf dem Feld Ballen sammeln kann und anschließend die gesammelten Ballen am Feldrand abladen kann?
Ich würde gerne mit dem AutoStack die Ballen auf dem Feld sammeln und am Feldrand eine "Ballenmiete" anlegen und diese anschließend dann abholen.

**Comment by Tensuko** [comment]
Das ist aktuell nicht möglich und wird vermutlich auch nicht mehr im 22er verfügbar sein.
Wir haben das aber auf dem Zettel.
