### ISSUE TITLE
[BUG_SP] Plow does not reverse after first corner in field center (multi-tool)

### ISSUE THREAD

**Issue by mpupedis** [Courseplay/Courseplay_FS22#3497]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Start a multi tool course with headlands, working center first.  When the tractor makes the turn after the first pass, the plow direction is not reversed.  In multi-tool, this applies to both tractors.

**Actual behavior**
Plow direction is not reversed, leaving a small unplowed strip in the field.

**Expected behavior**
Plow direction is reversed after the first pass to maintain a consistent direction of plowing and provide complete coverage.
**Screenshots**

Images show the outside (left) track of the multi-tool course, but both tractors had the same behavior.
![image](https://github.com/user-attachments/assets/e8f063e8-7cd9-4b54-ab81-a3e08bf76969)
![image](https://github.com/user-attachments/assets/ccafb2aa-881d-4514-9cb1-43c75e4202ee)
![image](https://github.com/user-attachments/assets/5aaafe30-c5fc-4a10-8bf7-92f00a93fd74)

**Courseplay version**
Version used: 7.4.2.3

**Log**
[log.txt](https://github.com/user-attachments/files/17262382/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Claas Axion 870 (x2)
Ecomat plow (x2)

Mod yes/no ?
No, all vanilla

**Relevant script mods**
Autodrive, Better Contracts, Courseplay

**Comment by mpupedis** [comment]
This looks like it might have a relation to the starting direction.  I plotted another course on the same field, but it started in the northeast corner.  With that course, the plow rotated as expected.  The original course, starting in the southwest did not have the proper rotation at the end of the first row.

**Comment by Tensuko** [comment]
Was that course an older one or new generated with the latest version?

**Comment by mpupedis** [comment]
New course generated with 7.4.2.3.

**Comment by Tensuko** [comment]
Works just fine on Main.
Plow is rotating and there is nothing left inbetween.
You may wait for next version but I don't see why this should happen.
