### ISSUE TITLE
Side discharge windrowers

### ISSUE THREAD

**Issue by thenormal007** [Courseplay/Courseplay_FS22#350]
When generating a course for baler after using a side discharge windrower you have to use double the working width of the windrower. The problem is that on headlands side discharge windrower does not turn around and go once clockwise and than anticlockwise like it does on up/ down rows. What actually happens if you have headland overlap on is that most of the windrow is windrowed again and again until you reach the final headland.

What would be nice is to be able to set the course for baler once that would collect all the grass. 
For this i would suggest the ability to  interchange clockwise and anticlockwise runs between headlands....

Another solution would be the ability to set a different working width for headland runs.

**Comment by Tensuko** [comment]
Did you play arround with offsets ?

**Comment by thenormal007** [comment]
No, but my guess is that it would leave the windrows nicely set but than the problem is that you would need another working width just for headlands, since i had to double the working width for up and down rows.

**Comment by thenormal007** [comment]
Okay i went back and tried it with 0 offset and it actually still takes half of the windrow. This could create a problem if you choose to have a lot of headland passes.

**Comment by thenormal007** [comment]
Okay i just wish in the future i could make more than one headland pass, but i am sure you have your hands full already.
