### ISSUE TITLE
[Question] how did you guys do it?

### ISSUE THREAD

**Issue by clavicus-zz** [Courseplay/Courseplay_FS22#3504]
the latest build with the "follow field edge" is absolutely magical. i can't believe it. this shit is so impressive.

**Comment by Tensuko** [comment]
The story started with "I had this idea while mowing grass" :)

While it is crazy what is possible, it is also sensitive and not all setting combinations do work.

Examples what can work:
![grafik](https://github.com/user-attachments/assets/772891cb-7a46-4527-8464-e1a4371e96d6)
![grafik](https://github.com/user-attachments/assets/271be5f5-43a4-4991-8e2f-69ddb1bc06cc)

If you ask for the technical side, only @pvaiko can answer that :)

**Comment by clavicus-zz** [comment]
I've already done some amazing ones myself, not as impressive as yours but it keeps surprising me. The "first headland round" is another AWESOME feature. so cool! i was wondering how courseplay would do in fs25 but with features like this it's clear i won't ever be using ingame AI. i've had the H key unmapped in fs22 since my first week using courseplay.
ill send you a screenshot of a really tricky field on hof bergman that is really taking advantage of the field edge option

**Comment by clavicus-zz** [comment]
this isn't that field i mentioned but come, this is so damn cool. 
![image](https://github.com/user-attachments/assets/09cda5d2-cb03-416c-ac4a-bbac252a4e7f)

**Comment by Tensuko** [comment]
Looks great :)

**Comment by clavicus-zz** [comment]
![image](https://github.com/user-attachments/assets/ab2d5d86-9df1-4371-a63f-f6b74faf8f24)
another much more helpful layout!, over and out Tensuko, just wanted to make sure you guy(s) were getting all the praise you should for this incredible mod

**Comment by clavicus-zz** [comment]
closed as perfect
