### ISSUE TITLE
[BUG_SP] Incorrect course when using two or more tools

### ISSUE THREAD

**Issue by VitaliyYa** [Courseplay/Courseplay_FS22#3506]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**

1. Open course generator
2. Multiple tools: 2
3. Number Of Headlands: 0
4. Generate a course

**Actual behavior**
The generated course does not start from the edge of the field; there is an offset of half the tool's width. If you select 3 tools in the course generator, the offset will equal the tool's width.

If Number Of Headlands is 1 or more, the course is generated correctly.

**Expected behavior**
If two or more tools are selected and Number Of Headlands = 0, the course should start from the edge of the field.

**Screenshots**
![Screenshot 2024-10-06 111316](https://github.com/user-attachments/assets/5deddb65-4a29-47b8-bcd0-119b36bcc559)

![Screenshot 2024-10-06 110728](https://github.com/user-attachments/assets/510835f8-46cd-455b-8015-af553d30f01c)

**Courseplay version**
Version used: v7.4.2.3 and v7.4.2.2

**Log**
If necessary, I will provide it.

**Map**
Haut-Beyleron map and others

**Vehicles/ implements involved**
Plows, cultivators, combines 
Mod yes/no yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. Disabled.

**Comment by Tensuko** [comment]
That could be due to field width not exactly devidable by 2x9m width.
Should be shifted inwards the field ofc.
