### ISSUE TITLE
Loading huge heaps

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS22#3508]
**What is the problem this feature/enhancement solves?**
Loading huge heaps
**Describe the solution you'd like**
Hello, dear developers. Thank you very much for your work and development, I want to wish you further success in development. I have a suggestion, can you please make an infinite number for the loader so that it can load any heaps of bulk materials, any size from small to huge, or reduce visibility so that it can load huge heaps of bulk materials in small pieces? Thank you very much for your help.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
There is no way to do "endless".
We have to set a limit, sry.
