### ISSUE TITLE
[BUG_SP] Course with "Narrow Field" setting is not generated correctly

### ISSUE THREAD

**Issue by Oberlump** [Courseplay/Courseplay_FS22#3509]
Courseplay: 7.4.2.3
Map: Nordfriesische Marsch
Vehicle: John Deere X9 1100

When generating a field course with the "Narrow field" option activated (see screenshot), the headland is not created on the narrow side, but on the long side and the tracks are therefore always "short" (see screenshot 2).

Am I missing something and/or doing something wrong? The same problem also occurs with a manually created field edge course. The same problem also occurs with a different thresher (Claas Lexion 8900) and a working width of e.g. 13.8 m.

![fsScreen_2024_10_07_17_59_22](https://github.com/user-attachments/assets/70150073-e72d-4a1f-a6ba-cf13fe7be752)
![fsScreen_2024_10_07_17_59_37](https://github.com/user-attachments/assets/0bcbca6d-a18b-47dc-80e8-1fea6d1919c6)

**Comment by Tensuko** [comment]
That is just my mistake in the help section.
Place fieldmarker on the side where the headland should be and it does work correctly.

**Comment by Oberlump** [comment]
> That is just my mistake in the help section. Place fieldmarker on the side where the headland should be and it does work correctly.

Works fine, thank you! :)
