### ISSUE TITLE
[BUG_SP] Reversing with Terradisc 10001T is bouncy

### ISSUE THREAD

**Issue by ConductorWon** [Courseplay/Courseplay_FS22#351]
**Steps to reproduce**
Running a fieldwork course with the Terradisc + T8.350 Genisis tractor on field 39

**Actual behavior**
Whenever the tractor reverses it overcorrects its steering when the implement begins to stray from the target path, especially when it is doing its final reverse to line up for the next row. It ends up with the tractor being basically sideways at the end (it sways back and forth getting there, ends up missing partial sections of the course

**Expected behavior**
Straight reverse with minor course corrections until lined up properly

**Screenshots**
[Video](https://gyazo.com/651c60744acda3a98dcdb66aa4a462f9)

**Courseplay version**
Version used: 7.0.0.12

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7810092/log.txt)

The debug didn't save anything in the debug prints folder

**Map**
Elmcreek

**Vehicles/ implements involved**
Vanilla Terradisc + T8.350 Genisis

**Relevant script mods**
Enhanced Vehicle Control but it was deactivated

**Comment by Tensuko** [comment]
Your reverse speed is way to high!
Thats no wonder....
Improovement of reverse driving is incomeing anyway...

**Comment by ConductorWon** [comment]
This is the only implement I have this issue on and I have all of my tractors set to 15 reverse, the rest of the implements (all around the same size) perform flawlessly, that's why I thought it was a bug
