### ISSUE TITLE
[BUG_SP] The vehicle ignores sharp turns after detecting a collision.

### ISSUE THREAD

**Issue by Beesmaster** [Courseplay/Courseplay_FS22#3512]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
It's my first bug, so i'm sorry in advance when i some reported wrong. 
**Steps to reproduce**
When the vehicle encounters a collision, it attempts to find an alternative route to return to its course.

**Actual behavior**
When it finds a way to return to the course, the vehicle ignores sharp turns from that moment onward.

**Expected behavior**
When the vehicle finds an alternative route, it should not ignore sharp turns on the course, because certain areas may be missed during the operation; for example, the baler might not collect all the grass.
**Screenshots**
Screenshots below
![image](https://github.com/user-attachments/assets/6196a566-7684-4ec4-95c2-5997e2195d06)
![image](https://github.com/user-attachments/assets/1ed5d0c9-ccb1-4489-84e6-c3e0cc7777ac)

**Courseplay version**
Version used: 7.4.2.3 (the problem start form 7.4.2 version)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
I'm not sure what part of log describe a ignoring point's. 
**Map**
Map played on: Szpakowo

**Vehicles/ implements involved**
Which vehicle or implement? URSUS 4 Pack from kasztan and Samasz hay rake
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. N/A

**Comment by Tensuko** [comment]
A complete logfile would have been helpful here.
Just upload the log.txt

**Comment by Tensuko** [comment]
[log.txt](https://github.com/user-attachments/files/17330953/log.txt)
![fsScreen_2024_10_10_17_55_48](https://github.com/user-attachments/assets/bebe52a4-f71e-44c7-b94d-1b8fc6c87c9f)
![fsScreen_2024_10_10_17_56_20](https://github.com/user-attachments/assets/af124c79-d8b2-4712-8187-7d819e21a2e3)

**Comment by Beesmaster** [comment]
[log.txt](https://github.com/user-attachments/files/17333469/log.txt)
Please find the log in the attachment. To ensure that the problem includes the log, I placed the CASE 7250 PRO with Meprozet on the field, and the issue was repeated.

**Comment by Beesmaster** [comment]
Hello Team,

Today, the issue occurred again during the round ballers operation. The machine's behavior was exactly as previously described. Attached are the log and a screenshot showing where the bug appeared again. As you can see in the log, I stopped the machine and restarted it. Since then, it has been working correctly. It seems this bug only occurs during round ballers operation, as I don’t recall encountering it during other tasks, like plowing, when the machine was blocked.


[log.txt](https://github.com/user-attachments/files/17534432/log.txt)
![bug ignoring sharp corners](https://github.com/user-attachments/assets/f16c8751-c0fe-4680-b522-0aab56edb169)

**Comment by Tensuko** [comment]
So it is only during baling?
Nothing else?

**Comment by Beesmaster** [comment]
Today, I noticed this issue again during baling. I will test it with other tasks and keep you updated.

**Comment by Beesmaster** [comment]
So, I confirm that the problem still exists. I tested vehicles during baling, plowing, and cultivation of the field. I used two different tractors and three machines. The problem occurs when the vehicle tries to turn on the field for the next path. As I reported during version 4.3 (maybe something happened during the repair of other bugs?), this issue persists.

This confirms the issue during plowing. The vehicle fails to lift the plow and turn it.

![1](https://github.com/user-attachments/assets/7be49df5-3323-4005-af92-2cef9eb22ec6)
![2](https://github.com/user-attachments/assets/4b98e08c-3020-4948-bcfd-612b7704c591)

And also the confirmation durin the cultivation field:

Normal behavior,
![3](https://github.com/user-attachments/assets/78a7fce3-2911-4373-8919-42e781d2eee9)

Blocking machine by the balle. 

![6](https://github.com/user-attachments/assets/d0d40737-d27f-43d3-a4f0-ea5e5ef82456)

Beahvior after the vehicle find alternative path:

![7](https://github.com/user-attachments/assets/2ae6bbb3-6994-4cc8-b593-eb4b0271a91c)
![8](https://github.com/user-attachments/assets/e34effd1-805d-4606-ac9a-cfd0b688d7b0)

Log: 
[log.txt](https://github.com/user-attachments/files/17535342/log.txt)

**Comment by Beesmaster** [comment]
Additionally, this issue seems very similar to what I found. The vehicle behavior is identical.

https://github.com/Courseplay/Courseplay_FS22/issues/3391

However, I'd like to confirm that the courses generated on my screen are indeed new. I want to be sure all courses are freshly created.

**Comment by pvaiko** [comment]
> Log: [log.txt](https://github.com/user-attachments/files/17535342/log.txt)

For the record: what happened here is that the ProximityController keeps calling the blocking object listener of the RecoveryTurn (instead of calling it once only) while the pathfinder is still running and this throws off the logic. As far as I can tell, has nothing to do with the latest changes.

**Comment by Beesmaster** [comment]
Hi Pvaiko. 
Of course, that was only my suggestion. Maybe I was lucky and didn't notice that in the previous version of CP. One thing I'm pretty sure of is that the problem wasn't in 7.3. If you want, this evening I can test 7.3 if that would be helpful.

**Comment by pvaiko** [comment]
I think it never worked properly if the pathfinding took longer than 4 update loops, but don't waste your time with it, if you want, test the pull request.

**Comment by Beesmaster** [comment]
Hello Team,

I tested the pull request, and now everything works properly. When the vehicle encounters a blockade while turning, it finds an alternative path and continues to operate correctly. There’s only one area for potential improvement: finding an alternative path during plowing. Currently, while the vehicle searches for a new path, the plow remains down and does not switch to the opposite side. However, once the vehicle reaches the next turn, it resumes working correctly, so this is a big improvement.

Attached is a screenshot showing how the vehicle finds an alternative path during plowing, along with the log.
![image](https://github.com/user-attachments/assets/89224d18-cd89-4208-875f-c6ef0e2752b7)

[log.txt](https://github.com/user-attachments/files/17548027/log.txt)
