### ISSUE TITLE
[BUG_MP] Plow dont work while not in drivers seat.

### ISSUE THREAD

**Issue by JMases** [Courseplay/Courseplay_FS22#3514]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
 
**Steps to reproduce**
Use tractor from Massey Ferguson Small Classics with plow PN2-300 on a own created non numbered field. Start Courseplay as normal than leave drivers seat to do something else. After a while it looks like its plowing but when taking place in the drivers seat again it respawns as before plowing. 

**Actual behavior**
when sitting in drivers seat it works perfect. when leaving drivers seat and coming back later on it looks like it has been plowing the field but after a while it respawns as before plowing.

**Expected behavior**
Plowing should not respawn as before plowing. 

**Courseplay version**
Version used: 7.4

**Player on the server**
1 - 6 players. 

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
No Mans Land

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes

**Relevant script mods**
Autodrive
Massey Ferguson Small Classics

**Comment by Tensuko** [comment]
Doesn't sound as a CP Issue, since we do not modify plow or not plow.
Mod Issue or conflict somewhere else.
Also what version exactly?

I don't have that problem on my MP tests.

**Comment by JMases** [comment]
Had the same problem since i started using courseplay for AI. Tried on 3 different maps and with courseplay as only mod. 
Using version 7.4.0.0 on courseplay and basegame version 1.14.0.0.
Its hard do describe the fault. Field looks plowed until you get in the drivers seat and follows the first pass and then it respawns as it was before plowing. 
Also if you sitting in drivers seat it plows and jumping out of tractor it stops plowing and when you get in again it starts plowing. Tractor is moving at all time.

**Comment by Tensuko** [comment]
Don't know why that should happen, rly....
Have you tried to set plow on create field?

**Comment by JMases** [comment]
yea, it feels like it should not happen but it works with normal AI when trying on another map. 
Yes, plow is on create field.

**Comment by Tensuko** [comment]
logfiles?

**Comment by JMases** [comment]
[log_2024-10-09_13-58-06.txt](https://github.com/user-attachments/files/17329425/log_2024-10-09_13-58-06.txt)
Serverlog from yesterday. The new fields was plowed from around 14:00-23:00 and didnt make any input or faults in log.

**Comment by Tensuko** [comment]
We have to check that in FS25.
Sry for not having a solution for this in FS22.
Or maybe in a later quick fix update, but since this is MP, I don't think we will update this in FS22.
