### ISSUE TITLE
[BUG_SP] Volvo LM845 not loading 

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3515]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
use volvo lm845 loader to unload a silo
**Actual behavior**
A clear and concise description of what happen.
it says no path found
**Expected behavior**
i expected the volvo LM845 to load the trailer from the silo
**Screenshots**

**Courseplay version**
Version used: 
7.4.2.3
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/user-attachments/files/17320359/log.txt)
**Map**
Map played on.
Elm Creek
**Vehicles/ implements involved**
Which vehicle or implement?
Volvo LM845 and the universal bucket LM841 
Mod yes/no ? Not a mod
[log.txt](https://github.com/user-attachments/files/17320359/log.txt)

**Relevant script mods**
Mods like Autodrive or VCA and so on.

no auto drive i do have VCA however it wasnt active at the time of this error

i have vca but its not in use at the time of the breakage

**Comment by FrozenStorm1029** [comment]
it also just breaks and continues to reverse after 1 unload of the bucket
[log.txt](https://github.com/user-attachments/files/17320455/log.txt)
here is the log for that too

**Comment by Tensuko** [comment]
Screenshots of your situation pls!

**Comment by Tensuko** [comment]
I made some adjustments to the Loader and it works fine now.
![grafik](https://github.com/user-attachments/assets/fd75fed2-c395-42ab-b18c-9cfb89cc6065)
This is how to set it up.
![grafik](https://github.com/user-attachments/assets/48bf7ba9-b92b-4b86-a9b0-6be4afb8d7df)
