### ISSUE TITLE
[Feature] Posibility to make wage cost settings for CP worker on MP an admin only setting.

### ISSUE THREAD

**Issue by JMases** [Courseplay/Courseplay_FS22#3516]
**What is the problem this feature/enhancement solves?**
It would be nice for a option that gives the admin the posibility to chose if the wage cost setting for CP worker can be used by everyone or just the admin on MP.

**Describe the solution you'd like**
I want to be able to force a everyone to have a wage cost for CP workers on my MP server.

**Comment by Tensuko** [comment]
We will not make any setting Admin only.
