### ISSUE TITLE
[Feature]Addding easily accessible swath switching option for combine harvesters

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/Courseplay_FS22#3519]
**What is the problem this feature/enhancement solves?**
There should be easier access to the option of turning on the straw swath for combines after setting the course

**Describe the solution you'd like**
the simplest solution would be to move up the "enable/disable swath" function in the CP settings. adding the option to enable swath in min GIU would be the coolest solution but it probably involves more editing.

**Describe alternatives you've considered**
Maybe it is also possible for CP not to change the settings of the chopper in the combine?
I mean that the combine harvester will behave appropriately to whether the straw swath was on or off before the course was started.

**Additional context**
I came up with this idea mainly because I started using the "Straw harvest" modification a lot, but it was annoying for me to switch between swath on and off, depending on the field I was collecting straw in. I know that the option could be left on, but in small fields I wouldn't want to collect this straw. This is the only reason why it bothers me that this switch is buried so low in the settings 
I know that probably everyone is already waiting for the new version of the game, but maybe with a little effort we could still change something

**Comment by Tensuko** [comment]
Hud is full, that is nothing you have to switch always on the fly. So sry that will not be done.
We will revisit the vehicle settings anyway, if we will do anything for the setting order in FS25 we will see.

**Comment by coatsy35** [comment]
What would be a cool option for FS25 would be to chop the headlands and swath the centre just like people do IRL. Also easier for avoiding baling on headlands. Would just be a cool little option

**Comment by Tensuko** [comment]
> What would be a cool option for FS25 would be to chop the headlands and swath the centre just like people do IRL. Also easier for avoiding baling on headlands. Would just be a cool little option

You should check that option and (not sure) read the ingame help.... Thats part of the option since ages....
