### ISSUE TITLE
[BUG_SP] US Field 32 weird Course gets generated

### ISSUE THREAD

**Issue by Zwox89** [Courseplay/Courseplay_FS22#352]
Courseplay version
7.0.0.12

Log
https://pastebin.com/JwZ6H5tQ

Map
US

Vehicles/ implements involved
Mod No

Relevant script mods
Autodrive (But not involved)

![image](https://user-images.githubusercontent.com/96999699/148125556-0a5a8014-af10-4ea8-81ad-e59ff138ddf2.png)
![image](https://user-images.githubusercontent.com/96999699/148125661-7c822ad3-796a-46a7-88ee-01bcc57067f9.png)

For some reason on field 32 on the US map, the course gets generated really bad and weird. It also runs into the trees on top of the course so its basically not usable. That's the only field i noticed it so far.

**Comment by StefanBraun2001** [comment]
I think one or two headlands should do the trick. I'm always using a few headlands (depending which machine is in use), so the machine has a area without obstacles to make a nice turn without reversedriving and avoid obstacles near the field borders.

**Comment by rohne83** [comment]
The field generation is absolutely correct. To have a field with such a shape worked completely (and that's what the course generator's aim is) there's no way than to go outside the field borders or add headlands. That's one of the reasons why there are headlands at all.

**Comment by Tensuko** [comment]
Improovements will come from time to time but yea, I suggest you at least one headland here.

**Comment by pvaiko** [comment]
Actually, this is a bug. Let me fix it folks.

**Comment by pvaiko** [comment]
(I mean @rohne83 is correct, but I think there is a bug in the calculation of how far beyond the field edge we need to drive)

**Comment by Tensuko** [comment]
Alright.
