### ISSUE TITLE
[BUG_SP] Attachment bug after getting stuck while turning

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3521]
**Actual behavior**
If the vehicle getting stuck while turning on the headland and find itself a new way and continues with the course, then the vehicle doesn't raise it's attachments at the next turn and continues with a round turn at the next corner and does, for the rest of the course, not raise it's attachments.

It does happen with the same vehicle and the same attachments on the same course 100% repeatable.

**Expected behavior**
The vehicle should raise it's attachments at the corner, make a turn and then lower its attachments again and continue with the course.

**Video link**
https://youtu.be/2f_M28j0ZFI

**Courseplay version**
Version used: V7.4.2.3

**Log**
[log.txt](https://github.com/user-attachments/files/17347575/log.txt)

**Map**
Krumbach

**Vehicles/ implements involved**
It happens with different vehicles and attachments.

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
duplicate
#3512
