### ISSUE TITLE
[BUG_SP] Chalk with Bredal K105 and 18m width has a gap between the tracks

### ISSUE THREAD

**Issue by Crizz0** [Courseplay/Courseplay_FS22#3522]
**Steps to reproduce**
- Map Elmcreek
- Use chalk with the Bredal K105 with the attached "wider pouring" of 18 meter
- Create a course with: activated corners, 2 Vorgewende, activate the new "dynamic smaller track"
- Let the CP field work bring the chalk to the field

**Actual behavior**
- When you start with the tracks and not the "Vorgewende", the first line is good, the second has a gap of circa 1 meter to the last one. See:
![fsScreen_2024_10_12_15_18_25](https://github.com/user-attachments/assets/cf3673c2-6b5b-46f2-af2b-6d1067fe28b1)

**Expected behavior**
The tracks should consider the 18m width of the machine and do not leave a 1m gap in between two tracks. 

**Screenshots**
![fsScreen_2024_10_12_15_17_46](https://github.com/user-attachments/assets/ed37d8f2-1c06-4a20-aae6-118c3e27ba0b)

**Courseplay version**
Version used: 7.4.2.3 

**Map**
Map played on: Elmcreek

**Vehicles/ implements involved**
Fendt Vario 728 Gen7 from Schnibbl Modding in Version 1.0.0.1
Bredal K105 with wider attachment

**Relevant script mods**
Autodrive 2.0.1.6

**Comment by Farmer200** [comment]
Hast du die gleichmäßige Bahnenbreite aktiviert? Ich hatte das gestern auch. Ohne hatte ich keine Probleme.

Have you activated the uniform web width? I had that yesterday too. I had no problems without it.

**Comment by Crizz0** [comment]
Ja, hatte ich. Ohne geht es auch. Mit konnte ich es auf Feld 10 mit geringerer Arbeitsbreite lösen.

Yes, I did use it. Without I do not have this issue. On field 10 I solved it be decreasing the working with from 18 to 16m.

**Comment by pvaiko** [comment]
Oh crap. I forgot to adjust that when I was working on another bug.

**Comment by Crizz0** [comment]
Thank you. Will try it :) 😀
