### ISSUE TITLE
What am I doing wrong 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/Courseplay_FS22#3528]
Hey guys I must have loads of hours on cp but for the life of me can’t generate a course lately.. I’m using a map with custom fields I update cp everytime you update it so my current version is 7.4.2.4. I’m getting “can’t not generate course log may contain more information”  but can’t see anything obvious in there I can provide log but not showing much unless there is a debug setting..  I’m confused with all the options now I tried the island thing on and off if I’m lucky I may get just the headland.

**Comment by Tensuko** [comment]
Add a screenshot and you may used dots so your text is more readable.
As we do not know anything abour your settings, field marker, how the field looks like and so on, there is no way anyone can help you.

**Comment by matty2123** [comment]
I will get some Shots and report back.. I’m not very good at writing apologies
Sent from my iPhone

On 14 Oct 2024, at 11:53, Tensuko ***@***.***> wrote:

﻿

Add a screenshot and you may used dots so your text is more readable.
As we do not know anything abour your settings, field marker, how the field looks like and so on, there is no way anyone can help you.

**Comment by matty2123** [comment]
![Screenshot (1)](https://github.com/user-attachments/assets/b0483c94-32d3-4f62-8249-61a63d6014ba)
![Screenshot (2)](https://github.com/user-attachments/assets/65f0c578-7797-4fb3-9ff1-e5c9fda1f6cd)
![Screenshot (3)](https://github.com/user-attachments/assets/bc1ab432-0623-4372-b138-a9c5e7859777)
![Screenshot (4)](https://github.com/user-attachments/assets/69966024-9aca-4573-80bc-1889797df6c9)
![Screenshot (5)](https://github.com/user-attachments/assets/da873412-4544-4430-9832-3b7a46da508d)
[log.txt](https://github.com/user-attachments/files/17363093/log.txt)

@Tensuko hope there is enough information for help

**Comment by Tensuko** [comment]
Turn that off.
![grafik](https://github.com/user-attachments/assets/c3d3fb45-0756-4fa0-9212-0979c5eb70ac)
As our help menu says:
![grafik](https://github.com/user-attachments/assets/6925f02b-db84-43e9-a3dc-40fbd22c1e0d)

**Comment by matty2123** [comment]
Thanks all sorted I’m all good now appreciate your help and time.


On 14 Oct 2024, at 12:42, Tensuko ***@***.***> wrote:

﻿

Turn that off.
grafik.png (view on web)<https://github.com/user-attachments/assets/c3d3fb45-0756-4fa0-9212-0979c5eb70ac>
As our help menu says:
grafik.png (view on web)<https://github.com/user-attachments/assets/6925f02b-db84-43e9-a3dc-40fbd22c1e0d>
