### ISSUE TITLE
[BUG_SP] Helper don´t overgive to autodrive wehn he needs Manure or somting

### ISSUE THREAD

**Issue by Panzerknacker1337** [Courseplay/Courseplay_FS22#3529]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
Helper emty -> over given to autodive

**Expected behavior**
Helper emty -> over given to autodive

**Screenshots**
![image](https://github.com/user-attachments/assets/4ca14c9a-c977-4010-b617-7bff978867ed)

**Courseplay version**
Version used: 
7.4.2.4

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
Nothing

**Map**
Map played on.
NF Marsch

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
any vehecal

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Turn off wait for refill in vehicle settings.

**Comment by PatrickWende** [comment]
Had the same problem, turning off refill was the solution for me. Sometimes it's the simple things... Thanks all for this awesome mod.

**Comment by Tensuko** [comment]
Changed it to default off.
