### ISSUE TITLE
[Feature] Reverse driving could be enhanced

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/Courseplay_FS22#353]
**What is the problem this feature/enhancement solves?**
I noticed the reverse driving is a bit weird now. Instead of moving at a even speed, he does drive a bit backwards, stops then (or slows down to very slow), countersteers and drives backwards again and it repeats

**Describe the solution you'd like**
The driver drives backwards at a constant speed (e. g. 6 km/h) and countersteers while driving, like it was in FS19. 6 km/h should be a suitable reverse driving speed for the most equipment which drives on own wheels.

**Additional context**
It is not urgent, since reverse driving does work fine for now.

**Comment by Tensuko** [comment]
Already working on that. Have patient pls....

**Comment by Tensuko** [comment]
Should be better now with .13
