### ISSUE TITLE
[Question] cooperation for load spreader

### ISSUE THREAD

**Issue by DrewCZ** [Courseplay/Courseplay_FS22#3533]
Hi there. I'm very interested about cooperation when AI is used for lime or fertilize missions. Is there possible to set up a work mode for auto refill when overload is standing on/near the field?
When I try set this on pic, it doesn't work, ai only waits on the field with open cover. Thank you. 
![obrazek](https://github.com/user-attachments/assets/8e44dbc7-a1b5-4697-8cab-0c349da52416)

**Comment by Tensuko** [comment]
Planed, and for modhub will come a manual refill, but automatic refill is only planed for fs25.
Time is running :)
