### ISSUE TITLE
[Question] Baler wont reverse because of unloaded bale

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#3534]
Would it be possible to fix this ? Maybe make baler to ignore any collisions on bale so it can reverse (push bale) ?
![Untitled](https://github.com/user-attachments/assets/babe56c1-2e5f-4c45-88f7-ca7bada1a89f)

**Comment by Tensuko** [comment]
Just turn off turn on field so he won't drive in reverse.
Maybe turn on use pathfinder for a better turn without reverse.
There is no other way.
Will not ignore bales.
