### ISSUE TITLE
[Enhancement] Harvester drive too far into its pocket, so the unloader have to drive forward too much and hits the fruit.

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#3536]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Run combine on first headland lane, let it get full to create a pocket.

**Actual behavior**
The pocket creation is much worse now than it was with 7.4.1.3 and earlier versions.
1. Pocket is very short so that unloader hardly fits next to the combine. In earlier versions combine stood in the pocket further too the back (see screenshot 1). This might especially be problematic when AD is used for the unloader.
2.  When driving back into the lane after unloading, the combine uses too narrow turns, resulting in fruit being left unharvested. In Screenshot 2 this is for 10.8m header, but saw the same also for 12.3m header

**Expected behavior**

**Screenshots**
1. pocket very short:
![fsScreen_2024_10_16_19_09_46](https://github.com/user-attachments/assets/b384309f-441b-420f-a7e1-9adaafe0cebb)

2. fruit left when driving back:
![fsScreen_2024_10_16_19_10_33](https://github.com/user-attachments/assets/03d0ae8c-02b9-42ce-b075-dc0aab9abf60)

**Courseplay version**
Version used: 7.4.2.4

**Log**
not sure whether needed, but still here it is: 
[log.txt](https://github.com/user-attachments/files/17400397/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
Lexion 8900-5300 pack from modhub
Any tractor with auger wagon

**Relevant script mods**
n/a

**Comment by Tensuko** [comment]
Too narrow, not too short, but yea... Will check.

**Comment by Tensuko** [comment]
Lol now I know what you talk about.... the part where the unlaoder will hit the fruit again (thats not the pocket).

Well that is definitly not a bug.

But can check if we can enhance this.
We wanted to make sure the longer harvester are straight.

I will have a look what I can change on that.

**Comment by rohne83** [comment]
That was quick, cool. Not to forget the 2nd point please. But I think if combine stands further back it will also drive back to its lane a few meters back, and thus not risking to leave crops unharvested.

**Comment by Tensuko** [comment]
He won't miss crops now.
