### ISSUE TITLE
[Wiki] Cleanup VehicleConfigurations page

### ISSUE THREAD

**Issue by blubstar86** [Courseplay/Courseplay_FS22#3537]
Since we are almost leaving FS22, maybe you can do a little cleanup on the Wiki page for the VehicleConfig.

Some of the settings are duplicatet in the list and maybe also some others are missing, but i dont know if there are missing ones.

Maybe keep only the one list with the descriptions what the settings actually do there.

If you want to keep both lists on the page, please consider make them both in the same order.

This is oc low priority, but maybe nice to leave FS22 CP clean.

![image](https://github.com/user-attachments/assets/ee7d37bc-8cb2-4fbb-a004-667705beeec7)

**Comment by Tensuko** [comment]
Yeah I will update that later.

**Comment by Tensuko** [comment]
Done.
