### ISSUE TITLE
Unloader reversing slowly

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#3538]
Hello,

with last update I'm experiencing very slow reversing when unloader with auger unloading into Lodeking double trailers.  He is moving by very small "jumps" but eventually reach the destination and unload. Don't know what version I used with last harvest, but for sure it was reversing "normally" before. Maybe some new settings which I missed ?

https://youtu.be/o8sIiwQWww0

**Courseplay version**
Version used: 7.4.2.4.

**Log**
[log.txt](https://github.com/user-attachments/files/17409497/log.txt)

**Map**
Saint Edward 

**Vehicles/ implements involved**
9620RX / Demco dual grain cart
Mod no 

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Position correction, not sure why it struggles there.
Is that reproducable or when does this happen?
I mean we have a template on purpose....

**Comment by Misamangame** [comment]
> Position correction, not sure why it struggles there. Is that reproducable or when does this happen? I mean we have a template on purpose....

Should be reproducable, it did for me everytime when unloader aproached trailers from same direction like truck and trailer is. If he came from different direction (opposite truck and trailer) and did unloading with forward movement it worked with no probs.

**Comment by Tensuko** [comment]
Works just fine.
As said, its correction.
Why so slow on your side I rly don't know.
![grafik](https://github.com/user-attachments/assets/f177e7de-4d51-4c02-a924-2c1d0f3b0533)

1km/h with 2 different tractors, filling up the whole truck works without any hick up.
What I will do is correcting the turn radius for that auger wagon.

Have you changed any speeds in the vehicle settings?

**Comment by Misamangame** [comment]
> Works just fine. As said, its correction. Why so slow on your side I rly don't know. ![grafik](https://private-user-images.githubusercontent.com/27344744/377519386-f177e7de-4d51-4c02-a924-2c1d0f3b0533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzg5MTAsIm5iZiI6MTcyOTE3ODYxMCwicGF0aCI6Ii8yNzM0NDc0NC8zNzc1MTkzODYtZjE3N2U3ZGUtNGQ1MS00YzAyLWE5MjQtMmMxZDBmM2IwNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE1MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2EyY2JjNTYzYzMyMmNkOTljZDMwNDEzMmZiYjEyZTA0ZmIxMDQ5YmE3NmZmNzNiNTc3ODIzNDdjNGIxZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OLC9qWjEN1JxeMKZ7Q1pV0w7Sn3zf2qssSQFV1lqpSA)
> 
> 1km/h with 2 different tractors, filling up the whole truck works without any hick up. What I will do is correcting the turn radius for that auger wagon.
> 
> Have you changed any speeds in the vehicle settings?

yes in vehicle setting I have max speed on fields set for 40km/h.  Not fiddling with radius or anything else.
How I can recognise what is correct turn radius?

**Comment by Tensuko** [comment]
Well, it is very slow, indeed.
I don't know why it is that slow on your side.
Since it basically works, we could only check to enhance this, but that would be for FS25 then.
Sry that I don't have a better solution for you now. Change the trailer might help.
