### ISSUE TITLE
Loading hangs at 85% when mod selected [BUG_SP]

### ISSUE THREAD

**Issue by mcbonanno** [Courseplay/Courseplay_FS22#354]
**Steps to reproduce**
Occurs on every load when courseplay mod is enabled.  Disabling only courseplay mod, save loads consistently.  Disabling all mods except courseplay still causes load to freeze at 85%

**Actual behavior**
On loading, progresses until 85% then hangs.  Log file has multiple errors

**Expected behavior**
Should continue loading

**Courseplay version**
Version used: 7.0.0.12

**Log**

https://gist.github.com/mcbonanno/47cc0510890839edc63c0fd077d4846e.js

**Map**
France map

**Vehicles/ implements involved**
Several mods, but loading fails with all mods disabled

**Relevant script mods**
Guidance steering

[gistfile1.txt](https://github.com/Courseplay/Courseplay_FS22/files/7811166/gistfile1.txt)

**Comment by pvaiko** [comment]
Attach a log with all mods except Courseplay disabled.

The link you have under Log is unreadable, and the gistfile1.txt log I see has many other mods enabled.

**Comment by mcbonanno** [comment]
Hello,

Thanks for taking a look so quickly.  I have attached the log file now with all mods (except courseplay) deselected

Please let me know what else I can do to help
[log no mods.txt](https://github.com/Courseplay/Courseplay_FS22/files/7811324/log.no.mods.txt)

**Comment by pvaiko** [comment]
There's something weird with this Torion, what is attached to that Big Bag Lifter?

```2022-01-04 19:53 :52 [dbg20 lp1752] TORION 639: getting working width...
2022-01-04 19:53 :52 [dbg20 lp1752] TORION 639: has NO work area.
2022-01-04 19:53 :52 [dbg20 lp1752]   BIG BAG LIFTER - DUAL: getting working width...
2022-01-04 19:53 :52 [dbg20 lp1752]   BIG BAG LIFTER - DUAL: has NO work area.
2022-01-04 19:53 :52 [dbg20 lp1752]     Seeds: getting working width...
2022-01-04 19:53 :52 [dbg20 lp1752]     Seeds: has NO work area.
```

**Comment by mcbonanno** [comment]
![Torion](https://user-images.githubusercontent.com/77419563/148149323-7f30c623-aa3c-40b2-8f5f-eec9d645f0d6.png)

This seems to have fixed it.  I loaded the game and disconnected the lifter and two bags of seeds.  I was then able to load the game with courseplay enabled.  Both bags of seeds were full at 1000 (if that helps)

**Comment by Axel32019** [comment]
Hello @pvaiko , We changed all getAttachedImplements() calls like you did, especially the recursive functions will run in endless loops - migth also be helpful for CP :-)
