### ISSUE TITLE
[BUG_SP] "ungerade" Vorgewendeberechnung

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#3540]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
ok

**Steps to reproduce**
Steps to reproduce the behavior.
Kursberechnung mit Vorgewende, folgende Einstellungen:

![fsScreen_2024_10_18_07_49_06](https://github.com/user-attachments/assets/d3ea0875-2735-4aff-8bc1-964360bf8827)
![fsScreen_2024_10_18_07_49_12](https://github.com/user-attachments/assets/6b8e1971-28d1-4ef7-aa43-ef10367b1a09)

**Actual behavior**
A clear and concise description of what happen.
die Vorgewende werden nach Ecken, Kurven,... sehr unregelmäßig bzw komisch kurvig berechnet: 
![fsScreen_2024_10_18_07_49_16](https://github.com/user-attachments/assets/440967c0-dde2-43f7-a3b4-16f90e6f88d0)
![fsScreen_2024_10_18_07_49_32](https://github.com/user-attachments/assets/3afc5330-ef7a-4c0c-b295-cdaacf83025b)
![fsScreen_2024_10_18_07_49_50](https://github.com/user-attachments/assets/f0b8669c-7d21-46a4-b622-1a9e20724832)

auch bei eckigen Feldern:
![fsScreen_2024_10_18_07_53_33](https://github.com/user-attachments/assets/2271c3d9-5292-4815-b06a-ae0c0d41fa3e)
da werden die Ecken irgendwie nach aussen gezogen:
![fsScreen_2024_10_18_07_54_09](https://github.com/user-attachments/assets/a95a9fee-1abc-4a4e-9dd7-85ead3b9d624)
![fsScreen_2024_10_18_07_54_16](https://github.com/user-attachments/assets/e1189aad-3108-463b-be30-7c860c52b547)
![fsScreen_2024_10_18_07_54_35](https://github.com/user-attachments/assets/fe3c234d-d32b-47de-9579-06ef225710f9)
![fsScreen_2024_10_18_07_54_57](https://github.com/user-attachments/assets/956c7ae7-6bb5-4c10-9544-d4f19d075de7)

auch bei schrägen Feldkanten:
![fsScreen_2024_10_18_07_55_18](https://github.com/user-attachments/assets/019624fd-c6de-4587-907d-c99d1dca4e05)
das Feld wurde komplett gerade (mit gps) erstellt/gepflügt

edit:
und auch sonst sind die Vorgewende nicht gerade, obwohl das Feld komplett gerade (mit gps) erstellt wurde:
![fsScreen_2024_10_18_07_54_16](https://github.com/user-attachments/assets/d0528f6d-9f8e-47de-a1b8-6e55beac185d)
![fsScreen_2024_10_18_07_54_35](https://github.com/user-attachments/assets/f2920344-562d-4c51-9977-3b0a95f7e401)

 
**Expected behavior**
bei den Vorgewenden geradere Bearbeitungspfade

**Screenshots**
siehe oben

**Courseplay version**
Version used: 
7.4.2.4 aktuelles main

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/user-attachments/files/17428996/log.txt)

**Map**
Map played on.
St.Kalle aus dem modhub

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?
diverse, Giants und Modfahrzeuge

**Relevant script mods**
Mods like Autodrive or VCA and so on.

lg
andreas

**Comment by Tensuko** [comment]
Original Version oder mit deinen Anpassungen bei den scan steps?

**Comment by andreasthu** [comment]
habs mit 
self.normalTracerLookahead = 3.0
und
self.normalTracerLookahead = 5.0
 versucht. beides male so berechnet.
die kurse der screenshots oberhalb sind mit 
self.normalTracerLookahead = 3.0
berechnet worden.
sieht man am letzten Bild oben z.b. sehr gut. da ist die 4m Arbeitsbreite und die wegpunkte am vorgewende sind enger beisammen
lg

**Comment by andreasthu** [comment]
schade, aber danke
lg
andreas
