### ISSUE TITLE
7.4.2.4

### ISSUE THREAD

**Issue by Legion68** [Courseplay/Courseplay_FS22#3544]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Legion68** [comment]
Bei Version 7.4.2.4 wird in der Log  Roter Fehler angezeigt  ( ist nur CP im Mods Ordner )
Bei Version 7.4.2.3 ist die Log Fehlerfrei
Habe das schon etliche male geschrieben  und wird jedes mal wieder gelöscht 
![Screenshot_4](https://github.com/user-attachments/assets/c9d84c26-7c96-486f-bd47-7d88bd52391d)

**Comment by Tensuko** [comment]
Ja, weil A) Template nicht benutzt
B) Schon lange erlerdigt wenn du suchen würdest. Also auch hier wieder zu damit.
