### ISSUE TITLE
[BUG_SP]CP Fehler in der Log

### ISSUE THREAD

**Issue by Legion68** [Courseplay/Courseplay_FS22#3545]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Legion68** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/171ba9f9-7d3b-4e05-937e-a622de882b4b)

Jedes mal wird  das wieder gelöscht 
Entweder mit Absicht oder ihr kennt den Fehler und  Schreibt dazu lieber Nichts 
Aber wegen jeden anderen kram da Beine ausreisen

**Comment by Tensuko** [comment]
Ich schreibe dazu was und es wird nciht gelöscht!!!
Es wird geschlossen weil das schon lange erledigt ist, wenn du die Suche benutzen würdest und deine Maisl checken würdest!!!!
