### ISSUE TITLE
CP

### ISSUE THREAD

**Issue by Legion68** [Courseplay/Courseplay_FS22#3546]
Fehler in der Log Datei
![Screenshot_4](https://github.com/user-attachments/assets/ca798335-dbb9-4c59-8264-d060fc3ca1a5)

**Comment by Legion68** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/92e9887a-3439-4c89-ab19-585479e429d5)

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/0bed8f70-9f83-4291-ba87-f6c89418f2c5)

**Comment by Tensuko** [comment]
Lese deine Mails!
Das ist schon lange erledigt!
Benutze unsere Templates!
Lese dir Wiki durch!
Und unterlasse diese sgespame ansosnten ist heir bald schluss!

**Comment by Legion68** [comment]
Wie erledigt ?

**Comment by Tensuko** [comment]
Bug ebhoben für die nächste Version, also abwarten!

**Comment by Legion68** [comment]
> Bug ebhoben für die nächste Version, also abwarten!

Ok Danke schon mal
