### ISSUE TITLE
[BUG_SP] Slurry tanker at 100%: Courseplay complains: please refill

### ISSUE THREAD

**Issue by Crizz0** [Courseplay/Courseplay_FS22#3547]
**Steps to reproduce**
Pick a truck and a slurry tanker, create a course at field with a 100% full tanker and start the course. 

**Actual behavior**
The helper will not start to spread it. It just waits at the edge of the field and "need refilling is displayed".

**Expected behavior**
The helper should spread the field with the slurry. 

**Screenshots**
![fsScreen_2024_10_19_13_31_17](https://github.com/user-attachments/assets/29e15f32-de8f-4e93-ba12-34be0d54d0db)

**Courseplay version**
Version used: 7.4.2.4 

**Log**

**Map**
Elmcreek

**Vehicles/ implements involved**
MF 7S.210
Fliegl PFW 18000 MaxxLine Plus

**Relevant script mods**
Autodrive 2.0.1.6

**Comment by Tensuko** [comment]
Teste bitte mal diese Version.
[FS22_Courseplay.zip](https://github.com/user-attachments/files/17445301/FS22_Courseplay.zip)

**Comment by Crizz0** [comment]
Hi,

habs nochmal probiert. Mit 3373 Litern GÜlle im Fass.

v7.4.2.4 => bitte auffüllen

Danach gespeichert, Spiel beendet, im Mod-Verzeichnis deine .zip reingepackt => Spiel gestarter und geladen => wieder ausprobiert: bitte auffüllen. Danach neuen Course erstellt, ebenfalls "bitte auffüllen".

**Comment by Tensuko** [comment]
Dann brauch ich dein logfile.
Weil ich kann das nicht reproduzieren.
Debug einschalten, laufen lassen, log.txt hier anhängen (nicht text kopieren!)

**Comment by Crizz0** [comment]
[log.txt](https://github.com/user-attachments/files/17445538/log.txt)

**Comment by Tensuko** [comment]
Also ich kann es leider gar nicht nachvollziehen...
Stell mal in den Fahrzeugeinstellungen das um:
![grafik](https://github.com/user-attachments/assets/930ce95a-8bb9-4a02-8f9b-b72a431a13d2)
Wenn eine Einstellung davon funktioniert und die andere nicht.... tja weis auch nicht, bei mir gehen beide :)

![grafik](https://github.com/user-attachments/assets/c260814b-07b5-41b3-b92b-45340458c56f)

**Comment by Crizz0** [comment]
Hi,

danke für deine Mühe. Ich hab das mal geändert, das geht beides nicht.

Habe auch mal den Traktor gewechselt und ein anderes Fass probiert sowie einen neuen Kurs auf einem neuen Feld. Geht nicht, er macht alles (ausklappen, anfahren, Motor dreht hoch) und dann: muss gefüllt werden. 😕

**Comment by Tensuko** [comment]
Hast du mal komplett ohne CP mit dem normalen Helfer versucht?
Nicht das CP da rein gretscht, ansonsten setze mal dein Fass zurück..... ist dann zwar leer, aber vlt hat da ja etwas Schluckauf :)

**Comment by Crizz0** [comment]
Ich hab das Problem wohl. Der KI-Helfer war in den Einstellung so konfiguriert, dass er sich aus dem Schweinestall "nachfüllen" soll, und obwohl das Fass voll oder 1/6 voll war, kam dann immer die Meldung, dass es nicht geht. Egal ob Helfer oder CP-Helfer:
![Gülle-Setting](https://github.com/user-attachments/assets/8d30c85c-89ad-43db-9068-de229aec1aab)

Da der Schweinestall eben wirklich 0L Gülle drin hatte. Wenn ich das auf "Kaufen" oder "Aus" stelle, geht alles wie es soll und vorher ging. 

Von daher, kannst du das Issue hier wohl schließen.

Danke für deine Zeit.

**Comment by Tensuko** [comment]
Ah alles klar, danke für die Rückmeldung.
