### ISSUE TITLE
[BUG_SP]The multi-tool does not work in the vineyards.

### ISSUE THREAD

**Issue by Maestro-Ralf** [Courseplay/Courseplay_FS22#3550]
**Actual behavior**
The multi-tool does not work in the vineyards, it gives an error and crashes the game.I checked without mods on the standard map Elmcreek .Errors in the logs .

**Courseplay version**
Version used: 7.4.2.4

**Log**
[log.txt](https://github.com/user-attachments/files/17454559/log.txt)

**Map**
Elmcreek.

**Comment by Tensuko** [comment]
We have to turn that option off for FS22....
We ran into an unexpected complication with that vine multitool that we can't finish in time.
So we turn it off and reactivate it in FS25 with a better solution.
Sry for that....

**Comment by franky-bb** [comment]
So we turn it off and reactivate it in FS25 with a better solution.
Super super super.
