### ISSUE TITLE
[BUG_SP] fail to handover to AD if implement is empty

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3551]
**Steps to reproduce**
Take a seeder or fertilizer spreader or lime spreader and if implement is empty it says "need refilling" and it don't handover to AD to refill.

**Actual behavior**
It does not handover to AD.

**Expected behavior**
If implement is empty, it should handover to AD to refill.

**Courseplay version**
Version used: Latest possible downloadable code as of writing this bug report.

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Remark**
Handover to AD functions correctly if a loading wagon is used and if it is full it successfully handed over to AD to empty.

**Comment by Tensuko** [comment]
No bug, see #3529

**Comment by gsShooter** [comment]
Is there a new setting for that?
