### ISSUE TITLE
[Question] anything that can be done about 4 wheel steered vehicles?

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#3554]
Amazone Pantera (Modhub) is not able to keep to its path in turns of CP courses. Pretty sure this is because CP always turns off the 4 wheel steering. With 4 wheel steering the vehicle has a very narrow turn radius (just 4.5m), and seems this one is used for calculating the path. But without, the turn radius is extremely large (looks like even more than 20m) and even AD has problems to keep the vehicle on course. 2nd headland lane is not really an option with 36m boom and would still leave the issue for AD.
If possible those kind of vehicles should always use the 4 wheel steering in turns, or at least don't change the steering mode set by the user. A solution here might also help for i.e. sugarbeet harvesters.
![fsScreen_2024_10_22_15_27_40](https://github.com/user-attachments/assets/55b9198b-7c61-450e-ba64-201faab0ec60)

**Comment by Tensuko** [comment]
The problem with keep user mode is that it will drastically change the turn behavior and turn radius, just as you see.
Not a fan of having user change stuff like that.
For that tool, no Idea. I say it is a mod issue when I see what big turn radius it seems to have with that normal steering
Wonder how on earth could that tool even drive on the street with that steering.
