### ISSUE TITLE
Why cant i get it to unload my combine?

### ISSUE THREAD

**Issue by Kehlun** [Courseplay/Courseplay_FS22#3555]
hi,

i was doing a parsnip harvest and wanted to drive the harvester and have courseplay unload me as i go however i cant seem to be able to find the setting or mode in the courseplay tab to do this. it only allows fieldwork, deliver, load and deliver and followme mod mode.
can you help me with some kind of guide to get this to work for me?
thanks in advance.

kind regards,
Kehlun.

**Comment by Tensuko** [comment]
CP cant unload a player driven combine. You have to use AD for that.
