### ISSUE TITLE
[BUG_SP] "attempt to perform arithmetic on a nil value"

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3557]
**Steps to reproduce**
It only happens sometimes in specific situations, mostly if the headland is finished and the worker tries to find the first row to continue the up and dow passes on the field.

**Actual behavior**
After finishing the headland, the worker sometimes stops and in the log is a remark that says "attempt to perform arithmetic on a nil value"

**Expected behavior**
If the headland is done, the worker should continue with the "rows".

**Video link**
https://youtu.be/CeCyCBGqlvo

**Courseplay version**
Version used: latest downloadable version as of writing this bugreport

**Log**
[log.txt](https://github.com/user-attachments/files/17512982/log.txt)

**Map**
Krumbach

**Vehicles/ implements involved**
Combine with header (Case Axial-Flow 9250)
Mod no

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
[FS22_Courseplay.zip](https://github.com/user-attachments/files/17523987/FS22_Courseplay.zip)

Can you test this version in your specific situation?

**Comment by gsShooter** [comment]
I can try, but in your version the change from pvaiko is not included, the code is the same as before.

**Comment by gsShooter** [comment]
1. test: I have tried your version and it does not work.

2. test: I have manually edited you're version and put the fixes in that pvaiko made and this time it works.

**Comment by Tensuko** [comment]
Oh, I must have changed the wrong copy.
But okay thanks for testing :)
