### ISSUE TITLE
Salary still pays despite being set to 0

### ISSUE THREAD

**Issue by Philj030** [Courseplay/Courseplay_FS22#356]
**Steps to reproduce**
ON the  Global Settings page set the CP driver wages to 0%

**Actual behavior**
Even though set to 0% when running CP the drivers are still paid wages

**Expected behavior**
If set to 0% I would expect that it would not pay them wages

**Screenshots**
Hard to attach a screen shot that shows a continuous decrease of money

**Courseplay version**
Version used: 2.0.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.  - NDH_NYR

**Vehicles/ implements involved**
Mod yes/no ?    Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. None being used only CP being used at the time

**Comment by RealNeo80** [comment]
Version used: 2.0.0.2 is AutoDrive Version ;) maybe your Autodrive is paying Salary

**Comment by SilverWheelz** [comment]
Encountered this a few days ago too. It happened after I used H to resume the course. It's as if the default helper is being used but the generated course is still followed. A quick workaround for this is to stop the helper and resume it via the "start job" button on the helper menu.

**Comment by Tensuko** [comment]
H starts cp only when you started it once with start job (cp fieldwork) use mini hud. Salary setting is working.

**Comment by Philj030** [comment]
Thanks that helped :) it does work it was the Giants AI taking over :(  what is the mini HUD - I am able to start it by going back in and clicking create job and start job (and it restarts at the nearest waypoint) it then basically closes the implement does a circle and restarts - is there an easier way?
