### ISSUE TITLE
[BUG_SP]The course in the vineyards has stopped being created.

### ISSUE THREAD

**Issue by Maestro-Ralf** [Courseplay/Courseplay_FS22#3561]
**Actual behavior**
The course on the vineyards has stopped being created. It does not give out obvious errors, but you can see a couple of entries in the log. I am attaching the log.

**Courseplay version**
Version used: 7.5.0.0

**Log**
[log.txt](https://github.com/user-attachments/files/17532838/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**

Mod no

**Comment by Tensuko** [comment]
Too less informations.

**Comment by Tensuko** [comment]
Is fixed, re-download release.
