### ISSUE TITLE
[Question] Handle over to AD broken or miss I a new feature?

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#3562]
Actual behavior
If CP runs i.e. for seeding, fertilizing, bringing manure or lime to the field, it runs till the attachement is empty. In previous versions, CP could handle over to AD for a refilling course. Now the vehicle stops with still active CP and asks for refill. 

![image](https://github.com/user-attachments/assets/4518b62c-3fe1-4610-ab94-f4759a677a38)

In the past it works with the options I had choosen (if I remember correct). Was there an update / new feature that I have to choose different parameter now? Or is this a bug between CP and AD?

To the situation in the picture: If I deactivate CP and activate AD manually, the driver refills and restart the course at the last point (as in older versions). I can deliver more data, if needed. 

Courseplay version
Version used: 7.5.0.0 (same at v7.4.2.4)

Vehicles/ implements involved
All

Mod
CP, AD and more

**Comment by Tensuko** [comment]
You missed a new feature -> change refill from wait to deactivated.
