### ISSUE TITLE
[BUG_SP] Failed to continue with the headland after finished with the rows

### ISSUE THREAD

**Issue by gsShooter** [Courseplay/Courseplay_FS22#3563]
**Steps to reproduce**
In my specific case it happens every time when the worker has finished the rows and trys to continue with the headland.

The course is a course from a swather, with the swather it functions correctly, but when I take the same course for the loading wagon, the worker finishes the rows and when he tries to continue with the headland it prints "work finished" and stops.

**Actual behavior**
The worker fails to continue with the headland after he has finished the rows and stops.

**Expected behavior**
The worker should continue with the headland after he has finished the rows.

**Video Link**
https://youtu.be/jwS9mJs4ioI

**Courseplay version**
Version used: 7.5.0.0

**Log**
In the first log the game hung and i had to Alt + F4 to get it to close. 
[log.txt](https://github.com/user-attachments/files/17534115/log.txt)

The second log is from the video I shared.
[log.txt](https://github.com/user-attachments/files/17534118/log.txt)

**Map**
Krumbach

**Vehicles/ implements involved**
Which vehicle or implement: Fendt 724 + loading wagon
Mod: no

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
No path found/unpatient.

**Comment by Tensuko** [comment]
2024-10-26 21:48 Error: Running LUA method 'update'.
C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/tasks/CpAITaskFieldWork.lua:28: attempt to index field 'vehicle' (a nil value)
How ever that came up...

**Comment by Tensuko** [comment]
Or this.... Oh no....

2024-10-26 21:55 Warning (script): Unknown entity id 319550 for 'object' in method 'localToWorld'.
2024-10-26 21:55 LUA call stack:
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua (503) : localToWorld
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (118) : drawDebug
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (257) : update
  =[C] (4294967295)
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (262) : xpcall
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (307) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1912) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1148) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1299) : update
2024-10-26 21:55 Warning (script): Unknown entity id 319550 for 'object' in method 'localToWorld'.
2024-10-26 21:55 LUA call stack:
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua (504) : localToWorld
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (118) : drawDebug
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (257) : update
  =[C] (4294967295)
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (262) : xpcall
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (307) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1912) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1148) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1299) : update
2024-10-26 21:55 LUA call stack:
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (262) : printCallstack
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua (505) : __add
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/AIDriveStrategyFieldWorkCourse.lua (118) : drawDebug
  dataS/scripts/vehicles/specializations/AIFieldWorker.lua (257) : update
  =[C] (4294967295)
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/CpUtil.lua (262) : xpcall
  =C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CpAIFieldWorker.lua (307) : try
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1912) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (163) : update
  dataS/scripts/network/Server.lua (62) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1148) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1299) : update
2024-10-26 21:55 :30 [info lp31750] C:/Users/Gideon/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/turns/TurnContext.lua:505: attempt to perform arithmetic on local 'cy' (a nil value)

**Comment by Tensuko** [comment]
Wasn't able to reproduce this.

**Comment by gsShooter** [comment]
So far it has only happened with this course and with the vehicles/ tools i mentioned, but I can reproduce this every time.

**Comment by Tensuko** [comment]
Is the course new generated with 7.5.0.0 ?

**Comment by gsShooter** [comment]
No

**Comment by Tensuko** [comment]
I have another report in DC, but I can't make it happen x.x

**Comment by gsShooter** [comment]
Do you need my savegame or what can I do to help you to recreate this?

**Comment by gsShooter** [comment]
Here is the savegame for testing.
I have positioned the used equipment for you already at the problem point.
[savegame_to_test_Krumbach.zip](https://github.com/user-attachments/files/17535429/savegame_to_test_Krumbach.zip)

**Comment by Tensuko** [comment]
Do you know how to test pull requests? If so, can you try it out if it works?

**Comment by pvaiko** [comment]
I tested it with @gsShooter 's savegame.

**Comment by gsShooter** [comment]
I dont know how to test pull requests, but I manually changed the code in my version and tested it and so far it worked for me.
