### ISSUE TITLE
[BUG_SP]Attatcher Probleme mit einigen Mods

### ISSUE THREAD

**Issue by Losthope24** [Courseplay/Courseplay_FS22#3568]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I try out some new miningmods from RGC, the having Conveyors and some Mobilewashplants

**Actual behavior**
If you attach the mods I use (see below), such as the conveyor belt, to a truck, this works. But as soon as I want to take it down again, a Lua error comes and the game crashes. The same applies to the hopper feeders, which can be moved with a wheel loader, but unloading again the Lua error. 

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.4.2.3 

**Log**
FS22_Courseplay/scripts/specializations/CpVehicleSettings.lua:466: bad argument #1 to 'min' (number expected, got nil)

**Map**
My own created.

**Vehicles/ implements involved**
Mod yes ? New created Mods:
FS22_Astec_Stacker_Conveyor
FS22_Astec_Hopper_Feeder
FS22_Portable_HopperFeeder
FS22_Portable_Conveyor
**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD, SimpleIC, InteractiveControl,

**Comment by Tensuko** [comment]
Old version.
Mod Issue.
Wont fix.
