### ISSUE TITLE
Skip Row doesn't appear to work with lands

### ISSUE THREAD

**Issue by Ashtoruin** [Courseplay/Courseplay_FS22#357]
I don't like how skip row works with up down and I'd prefer to use it with lands

Ideally it would just be a boolean true/false (Not entirely sure how well it would work with numbers other than exactly half of what lands are set to)

while false: Default behavior as now (useful for combines w/ grain carts)

while true: Start on the 1st row, then move to N/2 +1 
example with lands of 6 rows the order would be 1, 4, 2, 5, 3, 6 (Useful for any large implements)

**Comment by Tensuko** [comment]
Ofc it does not work, becouse it wont make sence...

**Comment by Ashtoruin** [comment]
So you're just going to close this as a feature you'll never consider? Why doesn't it make sense to offer a skip-row sort of feature for the internal rows on lands? Rather than working X rows starting in the middle, it would make sense to start on the first row and then one of the middle rows... And then loop on that until you're done with that land then go to the next land.

**Comment by Tensuko** [comment]
Becouse lands was created to have Combines pipe always point outside of the fruit for each land.
If you skip rows, you will have pipe in fruit again.
So no, won't add this.

**Comment by Tensuko** [comment]
Try Racetrack, maybe this is want you want to do.
