### ISSUE TITLE
[Feature] Hold shift for +5m on tool width

### ISSUE THREAD

**Issue by thekalbb** [Courseplay/Courseplay_FS22#3575]
When using modded equipment and it has the wrong width setting in code, manually setting the width in the CP menu will require ALOT of mouse clicks as the width only changes by 0.1m.

I have a piece of equipment that shows up as 36m, but in reality its 7m - Mama Mia, dats a spicy amount of clicks!

Soloution 1: Make the option for width a textfield, instead of button clicks.
Soulution 2: Make it so that holding a modifier key will change the clicks to +5 instead.

(Also, whatever happned to the AI using beacons and lights?)
Thanks

**Comment by Tensuko** [comment]
Why do you use clicks? Just use the mouse wheel or in generator settings klick on the width and type it in.

**Comment by thekalbb** [comment]
ah cool, dittent know you could click inside it
