### ISSUE TITLE
Ideal settings

### ISSUE THREAD

**Issue by AngelInBlack480** [Courseplay/Courseplay_FS22#3576]
### Version

7.5.0.0

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

What is an ideal settings to generate a course so that there won't be any/as little as posible misted spots on the field? 

### Screenshots

![1248130_54](https://github.com/user-attachments/assets/1b7101c2-2f20-4fc4-961c-a98527b31285)

**Comment by Tensuko** [comment]
Use Sharp corner active.
For Combine you can set round corners to 0.
