### ISSUE TITLE
more than one tractor

### ISSUE THREAD

**Issue by farmerbub** [Courseplay/Courseplay_FS22#3577]
### Version

7.5.0.0

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

after the new update i can no longer add more then one tractor or harvester to the course ive looked everywhere 
Before the update if i remember correctly it was below work width but i no longer see it? please help 

### Screenshots

![Screenshot 2024-10-30 233113](https://github.com/user-attachments/assets/9db7e625-1291-4f03-a959-e46fde0f25eb)

**Comment by Tensuko** [comment]
Turn on expert mode!
It is all written in the ingame helpmenu.

**Comment by farmerbub** [comment]
Thanks that was the issue!
