### ISSUE TITLE
baler question

### ISSUE THREAD

**Issue by iAlreadyExist** [Courseplay/Courseplay_FS22#3578]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

more later

### What is your question?

hello is it only me having this problem when baler finish with headlands on the first row he enters but it doesnt lower the picup and then when he goes to next one is fine.

https://www.youtube.com/watch?v=65jJ3E47foA

### Screenshots

baler question

**Comment by Tensuko** [comment]
No Problem with baler.
Looks like a mod and then I can only guess its a mod issue.

**Comment by iAlreadyExist** [comment]
on the last row is doing the same think it doesnt lower with the previous version of courseplay which was on mod hub before the update i didnt had such problem.

**Comment by iAlreadyExist** [comment]
> No Problem with baler. Looks like a mod and then I can only guess its a mod issue.

on the last row is doing the same think it doesnt lower with the previous version of courseplay which was on mod hub before the update i didnt had such problem.

**Comment by Tensuko** [comment]
We did not touch lower and raise functions. Is the course new?

**Comment by iAlreadyExist** [comment]
> We did not touch lower and raise functions. Is the course new?

yes i made it with the latest from yesterday but it did have same issue from the latest  [7.5.0.0]

**Comment by Tensuko** [comment]
If modder don#t stick to vanilla, it is a mod issue.
