### ISSUE TITLE
[Question] Courseplay_FS22-main.zip ändern?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#358]
Hallo Tensuko
wäre es möglich, die zip bei CODE -> download zip von
Courseplay_FS22-main.zip
auf
FS22_Courseplay-main.zip
zu ändern?
wenn man neue runterlädt, entpackt, den Inhalt des ordners packt, wäre der Name dann für den modordner leichter anzupassen.
lg
andreas

**Comment by rohne83** [comment]
Du solltest doch eh besser die zip aus der Releases-Sektion laden. Die ist auch schon komplett richtig gepackt und kann genau so wie sie ist in den Modordner geschmissen werden.

**Comment by 60erjonny** [comment]
@rohne83 ...ja schon...aber es gibt doch immer wieder, ein paar neugierige und experimetfreudige User hier...:-)

**Comment by Tensuko** [comment]
Git app nutzen oder... Warum wird das releas nicht geladen ???
Closed!

**Comment by andreasthu** [comment]
> Dann hat man die Möglichkeit, das git hier direkt zu synchronisieren -> s. TortoiseSVN Ein Mod, sofern nicht im Multiplayer, kann auch als Verzeichnis im Modordner liegen. ![grafik](https://user-images.githubusercontent.com/21023840/148199972-617e7bd2-4700-49c0-97cf-1d572d8f90dd.png)
> 
> Vor Spielbeginn ein SVNUpdate des Ordners durchführen, dann hat man die absolut aktuellste Version :)

Was ist das, wo gibts das?

Wo gibts die git-app?

Lg

**Comment by Tensuko** [comment]
Ich benutze zum Arbeiten mit unseren repositories GitHub Desktop.

**Comment by Tensuko** [comment]
Aber wie ich bereits sagte..... Release laden ist doch 100mal einfacher ?
https://github.com/Courseplay/Courseplay_FS22/releases
![release](https://user-images.githubusercontent.com/27344744/148211641-362e6c6d-d914-4131-8a2c-b6ce1294093f.png)

Verstehe es nicht warum sich so viele dagegen wehren und die weit aus komplizierteren weg wählen...
runterladen -> mods Ordner -> fertig....

**Comment by andreasthu** [comment]
ja schon klar, mach ich doch eh, wenns einen neuen release gibt.
manchmal lad ich die "zwischenschritt-änderungen" eben auch runter.
aber schon gut, alles klar, danke.
lg
andreas

**Comment by Tensuko** [comment]
Wie gesagt, GitHub Desktop und mit der Funktion vor Git auseinander setzen wie es funktioniert, ist dann nur nicht gezippt, was für SP egal ist.
