### ISSUE TITLE
Multiple tools

### ISSUE THREAD

**Issue by Ausfarmsim** [Courseplay/Courseplay_FS22#3585]
### Version

7.5.0.0

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

When I start a course I can’t seem to find anywhere that allows me to use 2 tools on the same course. (Eg. when wanting to use 2 plows I can’t find no. Of tools) do I need to download next version up?

### Screenshots

No screenshots as I’m not near computer

**Comment by coatsy35** [comment]
Turn on advanced settings in the CP menu

**Comment by Ausfarmsim** [comment]
> Turn on advanced settings in the CP menu

Ok I’ll try that tonight, that’s in down the bottom like where you select map, precision farm map etc?

**Comment by Tensuko** [comment]
CP global settings.

Please read the ingame help.......
