### ISSUE TITLE
Field_course-for-3-tractors _ created-only-one-route

### ISSUE THREAD

**Issue by Isayash** [Courseplay/Courseplay_FS22#3586]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

SP (Singleplayer)

### What happened?

EN: Field_course-for-3-tractors _ created-only-one-route-for-one-tractor
CZ: Pole_kurz-pro-3-traktory _ vytvořena-jen-jedna-trasa-pro-jeden-traktor

### How can we reproduce this?

EN: Previous full version of Courseplay (7.4.0.0) vs current full version of Courseplay (7.5.0.0).
CZ: Předchozí plná verze Courseplay (7.4.0.0) proti současné plné verzi Courseplay (7.5.0.0).

### What did you expect to happen?

EN: In the previous full version (simpler) it created a route centerline with side selection, now side selection is not available for multiple machines on the route.
CZ: V předchozí plné verzi (jednodušší) vytvořil středovou linii trasy s možností volby strany, nyní není volba strany dostupná pro více strojů na trase.

### Attach your log.txt!

[log_2024-11-05_11-06_Wymark-CA.txt](https://github.com/user-attachments/files/17631784/log_2024-11-05_11-06_Wymark-CA.txt)

### Screenshots

![Fs22_Wymark-CA_CoursePlay-3tractors](https://github.com/user-attachments/assets/ad1824d9-58f5-4654-824d-5deaa9744818)

**Comment by Tensuko** [comment]
Each lane have its one course now.
Not a bug and intended. Read the help menu.
