### ISSUE TITLE
Multi tool not working

### ISSUE THREAD

**Issue by Casperubbesen** [Courseplay/Courseplay_FS22#3587]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Multi tool option not showing up

### How can we reproduce this?

It hapens every time i try have tried multiple versions of the mod both 7.5 and 7.5.0.1
I tried multiple maps and with courseplay as the only mod

### What did you expect to happen?

I expected it to show up

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/17635800/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/cc89bd14-662b-4792-9cef-3c7cf5fe5a01)

**Comment by Tensuko** [comment]
Turn on expert mode!
Read the ingame help!

**Comment by Casperubbesen** [comment]
Thank you
