### ISSUE TITLE
Courseplay startet nicht bei mehreren Fahrzeugen auf einem Feld

### ISSUE THREAD

**Issue by UltimateWisdome** [Courseplay/Courseplay_FS22#3588]
### Version

7.5.0.1

### Spielversion

1.14.0.0

### SP/MP

MP (Multiplayer)

### Was ist passiert?

Hallo,
wie im alten Courseplay erstelle ich einen Kurs für 2 oder 3 Fahrzeuge und speichere diesen ab. Dann lade ich den Kurs in allen Fahrzeugen und wähle die jeweile Lane aus. Wenn ich den Kurs mit "am ersten Wegpunkt" nun starte, fahren alle Fahrzeuge auf die Startposition, halten keinen Abstand zu einander und öffnen das Arbeitsgerät. Dann passiert nichts mehr.

Grüße Tobi

### Wie können wir diesen Fehler nachstellen?

Hallo,
wie im alten Courseplay erstelle ich einen Kurs für 2 oder 3 Fahrzeuge und speichere diesen ab. Dann lade ich den Kurs in allen Fahrzeugen und wähle die jeweile Lane aus. Wenn ich den Kurs mit "am ersten Wegpunkt" nun starte, fahren alle Fahrzeuge auf die Startposition, halten keinen Abstand zu einander und öffnen das Arbeitsgerät. Dann passiert nichts mehr.

Grüße Tobi

### Was hätte passieren sollen?

Fahrzeuge bearbeiten das Feld im vorgegebenen Abstand

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/17637872/log.txt)

### Screenshots

![fsScreen_2024_11_05_21_12_32](https://github.com/user-attachments/assets/a8cdb36e-6b40-43e3-8a38-be9d83ea5985)

**Comment by Tensuko** [comment]
Das gucken wir uns im 25er noch mal genauer an.
Bis dahin versuche es mal mit dem nahesten WP zu starten.

**Comment by Tensuko** [comment]
#3581

**Comment by UltimateWisdome** [comment]
@Tensuko Hallo, ja das funktioniert. In Kombination mit Autodrive gehts auch so
