### ISSUE TITLE
Add a load implement on field for bucketed machine

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3589]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

Currently, refilling implements requires manual intervention. A better solution would be to enable bucketed machines to automatically detect the implement's location on the field, find the corresponding fill type, and deliver it to the implement on the field.

### If applicable, how would the user interface look like for this enhancement?

In the silo loading mode, the "unloading at" section currently offers two options. I suggest adding a third option, "implement/machine," which would automatically detect the target machine on the desired field and unload the material into its implement.

### Is there an alternative?

Auger wagons could benefit from an option to automatically detect their fill type and drive to the needed implement. This would be especially useful with mods that allow lime and seeds to be filled in auger wagons.

### Screenshots

N/A

**Comment by Tensuko** [comment]
An other solution is planed and issue for this does exist already.
