### ISSUE TITLE
Stop Punkt eines Kurses örtlich zuordnen

### ISSUE THREAD

**Issue by Omat1998** [Courseplay/Courseplay_FS22#3590]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### Um was geht es bei deiner Frage?

Kurserstellung

### Wie lautet deine Frage?

Moin,
in früheren Versionen war es möglich durch die Feldposition den Start- bzw. Stoppunkt festzulegen. Damit meine ich, dass, je nachdem in welcher Ecke des Feldes die Feldposition platziert wurde, dort der Start- oder Stopppunkt des Kurses lag.
Seit der 7.5.0.0 (evtl. aber auch schon ein paar Versionen früher, muss ich noch testen) funktioniert das Kurserstellen so nicht mehr. Wenn auf dem Vorgewende gestartet werden soll, dann wird der Startpunkt noch da generiert wo die Feldposition platziert ist. Bei der Möglichkeit, dass das Vorgewende zum Schluss gemacht werden soll wird der Stopppunkt allerdings willkürlich irgendwo auf dem Vorgewende gesetzt.
Ist nun kein Game Breaking Bug, allerdings stört es auf großen Feldern schon, dass man den Schlepper erst immer aus der letzten Ecke abholen muss 😄 .

Viele Grüße ans Team,
Omat 1998

**Comment by Tensuko** [comment]
Das ist nicht mehr möglich.
Einfach im Fahrzeug einstellen "zurück zum starpunkt".
Das ist von der gesamten dauer und Strecke das gleiche.
