### ISSUE TITLE
Add mod compatibility

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/Courseplay_FS22#3592]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

Sp or both MP yes :),

Hello, noticed no one reported to this mod issue related to CP.
I would ask to say you if it can be possible to add a mod compatibility related to this one : FS22_cutters_supportVehicle.zip ?
DL here : https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=278935&title=fs2022

I think its a good think to add it if possible because, It can avoid to block the way with AD if there only one way u know because the trailer if normal trailer is stay on the way that block other vehicle that can come to work with the combine as example.
The error log show (**with attach cutter auto in CP** you know) : 
`Error: Running LUA method 'update'.
mods/FS22_Courseplay/scripts/ai/controllers/AttachableController.lua:12: attempt to index local 'implement' (a nil value)`

And so with this mod if this could be taken into account the trailer auto disapear from the way when attached then it would free up the road for others vehicle approaching, what do you think ?

Best regard

### If applicable, how would the user interface look like for this enhancement?

None

### Is there an alternative?

 Yes ,the CP as default makes us do more manual maneuver to make this trailer go away with auto attach cutter enabled, or need to configure AD routes much more destinations (like the special combine dest !) for maneuver without block the network and configure fine tune AD and his avoidance solutions options. Or maybe more again using the default worker (to go to) with the combine that I never use this way.

### Screenshots

![1](https://github.com/user-attachments/assets/34591b91-fabe-4d6a-81be-03cbf368a234)

**Comment by Tensuko** [comment]
Reasons why not:
- we are at the end of fs22
- - if the modder would stick to giants stadards like other cutters have, it would already work.

**Comment by Anonymous-any** [comment]
> * if the modder would stick to giants stadards like other cutters have, it would already work.

I think you not been understand, if he made it this mean all cutters like you say are not with the trailer function ! right ok
Salut

**Comment by Anonymous-any** [comment]
Hi what this answer, for sure I know my english look bad but I will never understand more with this ???
Regard

PS: I add you @Tensuko Fs22 maybe come to end but before Fs25 fix their starting bugs Fs22 have a few time again before really end like you say ;)

**Comment by Tensuko** [comment]
What do I not understand?
"if he made it this mean all cutters..." <- what all cutters?
"Are not with the trailer function" I don't understand it.

**Comment by Anonymous-any** [comment]
Well so you said me "if the modder would stick to giants standards like other cutters have, it would already work."
Ok After that I think to myself You didn't good understand the request, but for you better understood I put the link of the mod that make auto-trailers in all default cutters in game.
But we're not going to talk about it anymore since it doesn't seem to interest you as an idea...

*) "Are not with the trailer function" I don't understand it. <- That is my vision to talk about the mod I purpose you to take in account...
So for now the question for you : 
What are the defaults cutters in game that you say "like other cutters have ?"

And also that limit the choice of cutters to my view point if some have the trailers automatic ? with the CP option (but its a good option !!)
