### ISSUE TITLE
Trailer doesnt have Unload Combine option

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/Courseplay_FS22#3594]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

I use this trailer mod:
https://forbidden-mods.de/filebase/file/35608-ls22-fliegl-asw288-schubboden-multi-trailer/#overview

The problem is, i dont have Unload Combine option, but only Fieldwork.
Is this problem with mod, does mod creator need to change something in trailer.xml or its up to CP ?
It happens only with this trailer mod.

### Screenshots

![Untitled](https://github.com/user-attachments/assets/b0bd41ff-56f7-4429-9240-a25b3d8aaf37)

**Comment by Tensuko** [comment]
Mod Issue.
We will not care for none midhub mods!
