### ISSUE TITLE
Sharp corner nodes not always present

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3595]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When I plot a course with sharp corners. I am not always seeing the node to turn the corner sharp.

### How can we reproduce this?

Vintage oaks. Field 182. 6.3m Header. 1 tool, 6 headlands. Round corner 1, corner radius 5. headland direction clockwise. Lands.

### What did you expect to happen?

When a sharp corner is present the node to stop the machine and turn the corner should be present. 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/17692266/log.txt)

### Screenshots

![fsScreen_2024_11_10_16_53_48](https://github.com/user-attachments/assets/37636d22-245d-471a-8120-b3717f110d26)
![fsScreen_2024_11_10_16_53_58](https://github.com/user-attachments/assets/0b4d439d-f04b-4a40-9b5f-42c9eaae58a8)

A screenshot of a corner with lots of sharp corners with no nodes
![fsScreen_2024_11_10_16_58_14](https://github.com/user-attachments/assets/83696a40-7967-4b86-8025-cf5053b90f2f)

**Comment by Tensuko** [comment]
Sharp corners active?
Doesn't look like that.
log.txt does not contain the field generation as debug.

Won'f fix for FS22 anyway.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Will have a look at everything in FS25 anyway.
