### ISSUE TITLE
2 oder mehr  Fahrer auf einem Feld nicht einstellbar  

### ISSUE THREAD

**Issue by Proolemo** [Courseplay/Courseplay_FS22#3598]
### Version

7.5.0.1

### Spielversion

1.14.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

ich kann keine 2 oder mehr Fahrzeuge auf einen Feld Kurs generieren. 

### Wie können wir diesen Fehler nachstellen?

im Kurs Editor fehlt die Einstellung Fahrzeuge auf dem Kurs . 
![20241115190145_1](https://github.com/user-attachments/assets/7e3482b6-e8f7-4e45-a8a1-ef566468d8a4)

### Was hätte passieren sollen?

im Kurs Editor 2 Fahrzeuge auf dem Kurs einstellen, als Auswahl Fenster kommen. 

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/17779296/log.txt)

### Screenshots

![20241115190145_1](https://github.com/user-attachments/assets/b9e2dc4d-8d5b-4e9f-a211-6f57b4826a2d)

**Comment by Tensuko** [comment]
Expertenmodus einschalten -> Globale Einstellungen.

**Comment by Proolemo** [comment]
Danke für die schnelle Antwort, die Einstellung hat funktioniert
