### ISSUE TITLE
Bale counter not showing in HUD(remaining bales on field)

### ISSUE THREAD

**Issue by manikanta2304** [Courseplay/Courseplay_FS22#3599]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

more later

### What is your question?

i am using bale collect or wrap mode , bale count doesnt showing in HUD? any idea 

### Screenshots

![fsScreen_2024_11_16_16_53_15](https://github.com/user-attachments/assets/2717c658-566c-4f44-813d-3f46706417d7)

**Comment by Tensuko** [comment]
In Fieldwork mode there is not a bale counter.
You got to switch the mod again.

We know we have some HUD Issues and hope in fixing them for FS25.

**Comment by manikanta2304** [comment]
You got to switch the mod again. what this means?

**Comment by Tensuko** [comment]
Den Modus... Da steht Feldarbeit, bei Feldarbeit gibt es keinen counter.
