### ISSUE TITLE
Missing 'CP_infoText' in l10n_nl.xml

### ISSUE THREAD

**Issue by jawisss** [Courseplay/Courseplay_FS22#36]
A small issue when starting the game (for only Dutch users?). See the image below.

In the log file there are a few more;
  Warning: Missing l10n 'input_CP_DBG_CHANNEL_SELECT_PREVIOUS' in mod 'FS22_Courseplay'
  Warning: Missing l10n 'input_CP_DBG_CHANNEL_SELECT_NEXT' in mod 'FS22_Courseplay'
  Warning: Missing l10n 'input_CP_DBG_CHANNEL_TOGGLE_CURRENT' in mod 'FS22_Courseplay'
  Warning: Missing l10n 'input_CP_DBG_CHANNEL_MENU_VISIBILITY' in mod 'FS22_Courseplay'

Thank you guys for your hard work!

![image](https://user-images.githubusercontent.com/95639912/147368882-c81edd9d-af27-44d4-b0e6-a7e3228e051c.png)

**Comment by PaulRoelofs1982** [comment]
I have exactly the same. And what is the solution? Set the language settings to English?

**Comment by Markus33-ITA** [comment]
you need to add the variable in the language file. just take it from the english file and add it

**Comment by jawisss** [comment]
> I have exactly the same. And what is the solution? Set the language settings to English?

The easiest way to fix it yourself is delete the file translate_nl.

**Comment by Manyak007** [comment]
CZ same but i translate on my langue and now is good

**Comment by schwiti6190** [comment]
The input texts will be fixed and in english with the next up comming version :) Then you can change them in the tanslation files :)

**Comment by Bobster82** [comment]
I will try and translate NL this weekend (xmas might slow me down :P )
