### ISSUE TITLE
[BUG_SP] Cource generation failed with 'Can't fit more headlands in field, using 0' -> 'attempt to index local 'course' (a nil value)'

### ISSUE THREAD

**Issue by IseOlen** [Courseplay/Courseplay_FS22#360]
**Steps to reproduce**
Try generating CP course with default values on the field that was created by player. Using tractor with sprayer attached.
Map=Erlengrat
No Mods (except CP).
 
Attached: 
savegame: https://www.dropbox.com/s/uvdman3bn6l27cd/savegame4.zip?dl=0
cpFields.xml : https://pastebin.com/Tt37WW3D
gamelog (with debugging enabled) : https://pastebin.com/ErAgiatJ
screenshot: https://pasteboard.co/EbuQgwRNXsUg.png

**Actual behavior**
After pressing "CP:Generate Fieldwork Cource" couple of seconds game freezes and then nothing. 

**Expected behavior**
A course should be created. If no course can be created some message about the reason of failure would be nice.

**Courseplay version**
Version used: 7.0.0.12

**Comment by pvaiko** [comment]
Not sure how you created this field, but sorry, there's not much we can do about it, this little nook between the two animal pens just won't work:
![image](https://user-images.githubusercontent.com/2379521/148311504-56d1811b-2f4e-4687-a1d9-36499fc1ee2d.png)

**Comment by IseOlen** [comment]
Animal pens were added on the existing field - I suppose that is the reason. Will fix this, thanks!
Please consider adding some sort of message in case course generation failed - with probable causes if possible.

**Comment by FarmerMoe** [comment]
I have run into the same issue on the "Elm Creek Edit by Stevie" map. The solution I found was to make sure that there was a delimiting border around the new field. In my case, I simply painted a grass border around the outside of the fields in question.

**Comment by IseOlen** [comment]
Painting borders will fix this, yes. Pity my suggestion to have some sort of warning/info message was not taken into dev. Atm user has no clue why course was not generated.
