### ISSUE TITLE
Werden zwei Kurse erstellt

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#3601]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

Hallo
Wollte 3 Mähdrescher auf ein Feld fahren lassen, Habe ein Kurs generiert und dann den Kurs von Drescher zu Drescher kopiert.
Das Problem ist: Wenn der Kurs vom zweiten zum dritten Mähdrescher kopiert wird, wird für den dritten Drescher ein neuer Kurs erstellt.  Habe ein Bild mit zugefügt.
![Courseplay](https://github.com/user-attachments/assets/6fa1f2b4-304b-4fde-8d56-2d6632da0816)

### Screenshots

![Courseplay](https://github.com/user-attachments/assets/17acc9f0-36bb-48e2-874d-66aeb4d092a9)

**Comment by Tensuko** [comment]
Ich kann dir nicht so ganz folgen.
Bei einem Multitool Kurs werden jetzt immer pro Fahrzeug ein einzelner Kurs generiert, welcher dann umgeschaltet wird durch links mitte rechts.
Demnach gibt es dann auch eine andere Anzeige.
Also wenn du auf alle 3 Drescher den Kurs kopierst und dann umschaltest, wird der entsprechende Kurs von der Bahn geladen.

**Comment by StahlGERwitter** [comment]
Ein Video-Tutorial wie das nun funktioniert wäre toll. Ich bekomme das überhaupt nicht mehr auf die Reihe Felder mit mehreren Fahrzeugen gleichzeitig bearbeiten zu lassen. Und gerade wenn man auf 4-Fach Maps spielt  (NF-Marsch) ist das katastrophal... LG

**Comment by Tensuko** [comment]
Steht doch alles in der Anleitung oder wo kommst du nicht weiter.
Grundsätzlich hat sich da nichts geändert außer das die kurse jetzt angezeigt werden.

**Comment by StahlGERwitter** [comment]
Expertenmodus musste aktiviert werden, das brauchte man bei 7.4.xxx nicht

**Comment by Tensuko** [comment]
Ah also hast du das gar nicht erst gesehen, ok.
Dann klappt es ja jetzt hoffentlich :)

**Comment by StahlGERwitter** [comment]
Nein ich hatte das nicht gesehen und auch nirgends gelesen. Aber nun funktioniert alles wie gewohnt 👍🏻 danke euch
