### ISSUE TITLE
Calling Tractor

### ISSUE THREAD

**Issue by Trivelleitor** [Courseplay/Courseplay_FS22#3602]
### Version

7.5.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Vehicle settings

### What is your question?

If i use harvester manually can i ask a tractor for unloading? If yes, how?

### Screenshots

Not necessary for me.

**Comment by Tensuko** [comment]
That is not possible with courseplay.
There is an Idea to get this working, but that is a lower priority, especially that we have to convert CP to FS25.
