### ISSUE TITLE
Multiplayer loading stuck 99% with courseplay error

### ISSUE THREAD

**Issue by Mocskos1230** [Courseplay/Courseplay_FS22#3604]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

MP (Multiplayer)

### What happened?

As soon as I join my friend's server, the loading stops at 99%, while it works perfectly for him. In the log, I find many Courseplay errors, which might be the source of the problem. I am attaching the log file.

### How can we reproduce this?

-

### What did you expect to happen?

Succesful join

### Attach your log.txt!

[log másolata.txt](https://github.com/user-attachments/files/17836600/log.masolata.txt)

### Screenshots

-

**Comment by Tensuko** [comment]
Bretty sure some mod conflict.
When your friend can join, I doubt it is cp.

**Comment by Tensuko** [comment]
Will check your log tmr.

**Comment by Mocskos1230** [comment]
alright, thank u very much if u check it.

**Comment by Tensuko** [comment]
When I search for courseplay, I don't see a single courseplay related error in your log.
But I see a lot of duplicate mods with (1) in the name, way too many mods with conflict potential and some of them throw errors.

I highly suggest you to clearn up your mods folder. Maybe clear it, or make a seperate one and download only the mods from your server in hope there are not that many mods...

But there is rly no indication of a CP Error, so it is a mod conflict or error in another mod.

**Comment by Mocskos1230** [comment]
ah, there is no courseplay error in this one, and during the last attempts before this there was always an error in courseplay, the reason I didn't check it was because I thought it would be included in this one too.. it wasn't in this one, lol sry
