### ISSUE TITLE
lua call stack and cant join to the server

### ISSUE THREAD

**Issue by Mocskos1230** [Courseplay/Courseplay_FS22#3606]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

MP (Multiplayer)

### What happened?

Hi, the log I attached the other day didn’t include the Courseplay error, but this one does, and it appears many times. Please take a look at it. What’s bothering me is that, from one day to the next, I can’t connect to the server because the loading gets stuck at 99%.

### How can we reproduce this?

while joining to the server

### What did you expect to happen?

-

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/17851577/log.txt)

### Screenshots

-

**Comment by Tensuko** [comment]
That can all come from other mods... Must check later.

**Comment by Tensuko** [comment]
2024-11-21 21:16 WARNING: static shape 'lightTrigger' is marked COMPOUND
These are not compatible settings and may cause a crash; COMPOUND flag will be removed
dataS/scripts/vehicles/specializations/AttacherJoints.lua(1711) : attempt to index local 'jointDesc' (a nil value)

That comes from any other mod.
Seems like that causes the callstack.

So any mod is not proper configurated. Can't tell you wich one.... Remove one by one and see.

**Comment by Mocskos1230** [comment]
Thank you
