### ISSUE TITLE
Combine Courses? [Question] [Suggestion]

### ISSUE THREAD

**Issue by Savatar1942** [Courseplay/Courseplay_FS22#361]
Back in 19 we had the option to combine 2 courses together, for instance harvest field 19 & 20, is there an option for this planned? So we dont actually have to combine the fields by plowing out the roads in between

**Comment by Tensuko** [comment]
You could not harvest 2 fields in row in 19.
But we have something better in mind. Let us get other stuff working first then we have a look at such features.
