### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by FrozenStorm1029** [Courseplay/Courseplay_FS22#3614]
### Version

7.5.0.1

### Game Version

1.14.0.0

### SP/MP

SP (Singleplayer)

### What happened?

So i was using the pumps and hoses DLC when it suddenly froze my character and would only hold the W key no matter what key i actually pressed 

### How can we reproduce this?

Use Pumps And Hoses DLC and Precision Farming(Vanilla) and Courseplay

### What did you expect to happen?

i expected it to work normally as courseplay does

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18121078/log.txt)

### Screenshots

N/A

**Comment by Tensuko** [comment]
"So i was using the pumps and hoses DLC when it suddenly froze my character and would only hold the W key no matter what key i actually pressed"

Sry but that is way too less information.
What do you mean with "using P&H DLC" ?
I see the Error in the log but I need to know what you did there.

It is unlikely that we will fix this for FS22 but maybe I can help you anyway.

**Comment by FrozenStorm1029** [comment]
well using the drag line hoses putting slurry on the field and id be happy to provide the info your need if you ask... im just not sure what info to give

**Comment by FrozenStorm1029** [comment]
is there anything i can do to fix this

**Comment by Tensuko** [comment]
No.
I would check that myself but whenever I am on PC I do ofc stuff for FS25 so dont know when I can check this.
