### ISSUE TITLE
[Feature] Separate key binding for "H" key

### ISSUE THREAD

**Issue by santaranger** [Courseplay/Courseplay_FS22#363]
**What is the problem this feature/enhancement solves?**
Currently, When pressing "H" and a CP course is loaded, the CP worker will hire (as indicated by the help tooltip). It is impossible to hire a regular worker when a course is loaded. This is annoying especially when I'm unaware that a course is loaded.

**Describe the solution you'd like**
Have a separate keybind for hiring a CP worker vs. regular worker.

**Describe alternatives you've considered**
No alternative found, I keep pressing "H" to start working on a field, only to find that the hired worker starts chasing to where I had my last course on a different field.

**Additional context**
-

**Comment by Tensuko** [comment]
H is only when a cp fieldwork was started before.
Anyway, duplicate #190
