### ISSUE TITLE
[BUG_SP]Can't upload the file to the Server because it's corrupted.

### ISSUE THREAD

**Issue by Woogielicious** [Courseplay/Courseplay_FS22#364]
If i try to upload the last version i get everytime Error from Upload that the file is corrupted? If i try it with FTP i get the Error too. Any suggestions?! 

![image](https://user-images.githubusercontent.com/21121442/148224977-a5a76e7a-2f39-44e1-83b8-355d18d3271e.png)

**Comment by Redster999** [comment]
I believe its because its not compatible to servers yet. 
![image](https://user-images.githubusercontent.com/95174660/148226187-2c9bacdc-47e5-49c9-9da5-c5d287f46a6f.png)

**Comment by Woogielicious** [comment]
oh ok, one of my guys from server was saying it can be used in mp now.
