### ISSUE TITLE
[BUG_SP]Dunno how to name that bug

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/Courseplay_FS22#366]
My poor english will not help with explaining the problem so i recordet short video. Issue shows itself when tractor comes to headland

https://user-images.githubusercontent.com/53440728/148252480-52384822-65b0-4a59-b7d3-501d0dd85f6e.mp4

Dont really know what to say more. This dont show on every pass, just once in awhile . Dosnt matter what type of implement is attached, seeder plow , or combine.  I noticed that when I was drivingin  other tractor, and these white squares showed in front of the  Nh T6 when doing field work

**Courseplay version**
Version used: 7.0.0.12

**Log**
I turn on debug channels and vehicle debug but dont know where to find those files. I can add that later

**Map**
Haut Beyleron

**Vehicles/ implements involved**
New Holland T6/ Power Roll 1230

**Relevant script mods**
CP, AutodDrive, Vehicle Insopector

**Comment by Geradsralf** [comment]
I saw such white or yellow squares, too. I think it is the path of the vehicle which has been defined, because the vehicles always run exactly the positions of the squares. I think normally we shouldn`t see it. I will post a log file when I see it again.

**Comment by Tensuko** [comment]
Thats pathfinder debug, is turned off for next release.
