### ISSUE TITLE
[BUG_SP] Startpunkt stimmt bei Bahnen zuerst nicht

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#367]
Normal hätte aber der Startpunkt auf der linken Feldseite sein müssen und nicht rechts
![image](https://user-images.githubusercontent.com/8066324/148272196-c94cddb1-7ded-483a-8571-d04d63660748.png)

**Steps to reproduce**
neuen Kurs generieren mit Bahnen zuerst

**Actual behavior**
Startpunkt wird vom Vorgewende aus berechnet

**Expected behavior**
Startpunkt wird von Bahnenseite aus berechnet

**Courseplay version**
Version used: 7.0.0.12

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7817094/log.txt)

**Map**
Elmcreek Feld 11

**Comment by Tensuko** [comment]
Der ist doch auch nicht rechts ?
Ingame Bild ?

**Comment by Tensuko** [comment]
Jetzt weis ich was du meinst. Nein das ist dann ja auch der Stoppunkt den du setzt. Anders gehts nicht. Won't fix.

**Comment by RealNeo80** [comment]
hm ok, versteh ich, weil du rückwärts generieren musst, da du sonst keinen Fixpunkt findest von wo du die Bahn berechnen kannst. Das heißt eigentlich erst die Felder berechnen, und dann AD Feldziele definieren dass das Zusammenpasst

**Comment by Tensuko** [comment]
Hat mit den AD Wegpunkten erst mal nichts zu tun...
Auch wenn der Punkt von AD sonst wo ist, wenn du da wo du bist sagst, CP Starte am ersten Wegpunkt, bauen wir uns einen Pfad zum startpunkt. Das klappt ja schon.
