### ISSUE TITLE
Düngerüberwachung bei Sämaschinen ausschalten können

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#368]
die Möglichkeit im HUD die Düngerüberwachung auszuschalten, damit der Helfer nicht stehen bleibt wenn der Düngertank leer ist.

Wenn ich das Saatgut ohne Dünger legen möchte ist das mit CP nicht möglich, da der Helfer motzt, dass der Tank leer ist.

**Comment by Tensuko** [comment]
Stimmt nicht, Düngefunktion bei Saatmschine ausschalten im Fahrzeug menü!
Wenn Es damit nicht geht -> Bugreport.
