### ISSUE TITLE
Hud und silo verdichten

### ISSUE THREAD

**Issue by ppeell** [Courseplay/Courseplay_FS22#37]
Guten Abend und frohe Weihnachten.  
Meine frage wird es den CP auch mir hud irgend wann geben? Und auch die Funktion die silos zu verdichten.
Mfg

**Comment by Tensuko** [comment]
Hud vielleicht in zukunft. Silo verdichten ist geplant.

**Comment by ppeell** [comment]
> Hud vielleicht in zukunft. Silo verdichten ist geplant.

Ok vielen dank. Und super arbeit an euch . Weiter so.
