### ISSUE TITLE
lacotec lh 2 bug 

### ISSUE THREAD

**Issue by thenormal007** [Courseplay/Courseplay_FS22#370]
**Steps to reproduce**
Use tractor mounted forage harvester lacotec lh 2 with kemper 345 plus to chop maize silage.

**Actual behavior**
The driver does not move from the position when starting the course and weird numbers are displayed near tractor (very small):
![Posnetek zaslona (18)](https://user-images.githubusercontent.com/97110199/148273293-2025bf3e-0e57-4ed1-ad88-d6a6722da2ea.png)
Also my camera is unable to move.

 If I tab to other vehicles parts of the hud go missing and eventually the game freezes.
![Posnetek zaslona (19)](https://user-images.githubusercontent.com/97110199/148273555-3831b415-03ce-4d59-9412-c056b49ef47e.png)

**Expected behavior**

I expected to be able to use tractor mounted forage harvester like you can use forage harvesters with courseplay.

**Courseplay version**
v7.0.0.12

**Log**
https://gist.github.com/thenormal007/72a5f55d2587a2858d2860ce6dab22b0

**Map**
Elmcreek field 38

**Vehicles/ implements involved**
JD 7R, lacotec lh2, kemper 345 plus

**Relevant script mods**
No mods apart from courseplay.

**Comment by pvaiko** [comment]
next release will include the fix
