### ISSUE TITLE
Best [Feature/Enhancement]

### ISSUE THREAD

**Issue by LONEWALKER1998** [Courseplay/Courseplay_FS22#371]
Hey man love yore work just one thing I would change...

Use the old interface as on Fs 19 worked so much easier and more convenient to setup fieldwork..

PS.. keep up the good work

**Comment by LONEWALKER1998** [comment]
![Uploading 16414112429158909430951694321033.jpg…]()

**Comment by Tensuko** [comment]
Read Wiki, won't happen!
