### ISSUE TITLE
[Question] Probleme mit "Vorgewende"

### ISSUE THREAD

**Issue by Zwox89** [Courseplay/Courseplay_FS22#377]
Kann mir jemand sagen ob das ein Bug ist oder ich zu blöd bin es richtig einzustellen?
Beim ersten versuch biegt er einfach ab?!
Beim zweiten versuch hört er einfach auf zu spritzen?!

Youtube Video weil Datei zu groß
https://youtu.be/57KfuzyZam0

Version v7.0.0.12

Log https://pastebin.com/NkzAniPJ

**Comment by Tensuko** [comment]
Hast wohl nicht am ersten WP gestartet.
Somit fährt er den connection track und geht dann in die erste Bahn.
Kannst auch das mini HUD nutzen und da am ersten WP starten lassen.
