### ISSUE TITLE
Amazone Citan beim rückwärts fahren, fährt etwas kompliziert.

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/Courseplay_FS22#378]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.
CP hat immer wieder Probleme mit der Citan beim rückwärts Fahren. Sowohl die std. Citan, die Citan aus dem Seeding Options Pack vom [ModHub](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226833&title=fs2022&filter=console oder andere Citans Mods
)
**Expected behavior**

**Screenshots**
![LITTLEBIGIV-2022-01-06 12_08_02-](https://user-images.githubusercontent.com/16350763/148374193-c2785457-7740-489a-bf13-be8055bacaed.png)
[YouTube Video](https://youtu.be/LAGL79Tif2M)
**Courseplay version**
Version used: 7.0.0.12

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7821322/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?
Fendt=yes / Citan=no

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive not involved

**Comment by Tensuko** [comment]
Naja Problem würde ich nicht sagen...
Es ist sauber bearbeitet, sieht aber nicht schön aus das stimmt schon.
Eventuell wird es mit der nächsten Version besser.

**Comment by Clouseau219** [comment]
Besonders heftig ist es mit der:
[FS22_ZIM_Citan_15001_Direct.zip](https://github.com/Courseplay/Courseplay_FS22/files/7822866/FS22_ZIM_Citan_15001_Direct.zip)

**Comment by Tensuko** [comment]
Weil der nicht in der VehicleConfig eingetragen ist und das kommt auch nicht fix mit rein. Können nicht jede Mod eintragen.
Denke für Mods wird es wieder eine eigene unter modSettings\Courseplay geben.

**Comment by Tensuko** [comment]
Versuch mal die .13
Aber mit Vanilla Saatmaschine!

**Comment by Clouseau219** [comment]
> Weil der nicht in der VehicleConfig eingetragen ist und das kommt auch nicht fix mit rein. Können nicht jede Mod eintragen. Denke für Mods wird es wieder eine eigene unter modSettings\Courseplay geben.

Ist mir schon klar dass Ihr nicht alle Mods berücksichtigen könnt. Erwarte ich auch nicht :)
Vielen Dank für tolle eure Arbeit !!!!

> Versuch mal die .13 Aber mit Vanilla Saatmaschine!

Werde ich machen. Wird Zeit dass Giants endlich mal eine große Direkt Saatmaschine zur Verfügung stellt.
Vermisse den Amazone Condor 15001 :(
Die Kuhn mit 6m ist ja ein Witz :(

**Comment by Clouseau219** [comment]
Hi,
also ein schneller Test mit der 7.0.0.13 hat als erstes gezeigt, dass er die Arbeitsbreite von der Vanilla Citan nicht erkennt, er zeigt nur 1,9m an.
Wenn ich die Arbeitsbereite (15m) bei der Kurserstellung eintrage fährt er an den Ecken nicht weit genug zurück und lässt was stehen:
![LITTLEBIGIV-2022-01-06 17_27_18-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/148416862-05f6d215-1276-4db2-a8c4-130c497f15dd.png)
_FS22/files/7823362/log.txt)

Ansonsten schaut das Rückwärtsfahren besser aus:
[YouTube](https://youtu.be/VQiC5LfLsAE)

[log.txt](https://github.com/Courseplay/Courseplay

**Comment by Clouseau219** [comment]
Also mit 7.0.0.16 schaut soweit alles super aus, sogar mit der Mod Citan.
Danke nochmal !!!
Ihr macht wirklich ein tollen Job und ich finde es super dass Ihr uns so in die Entwicklung mit einbindet und uns die Möglichkeit zum testen bietet  !

**Comment by Tensuko** [comment]
Mit der 16 wird auch weit genug rückwärts gefahren ?

**Comment by Clouseau219** [comment]
Ja, teste gerade das erste Feld, aber bis jetzt hat CP jede Ecke gut gemacht.

![LITTLEBIGIV-2022-01-06 20_51_01-Farming Simulator 22](https://user-images.githubusercontent.com/16350763/148443524-dc4d2e78-e6fb-4c9b-b88d-77f24efdf2b1.png)

**Comment by Tensuko** [comment]
Ja hat bei mir auch gerade geklappt.
Supper dann ist das ja jetzt erledigt in der Hoffnung das es so bleibt :)
