### ISSUE TITLE
[BUG_SP] Save game won't start (self driven sprayer cause Error)

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#379]
**Steps to reproduce**
Load save game

**Actual behavior**
As per topic, game won't start

**Expected behavior**
Game should start, it worked fine with 7.0.0.12

**Screenshots**

**Courseplay version**
7.0.0.13

**Log**
log attached

**Map**
Elmcreek

**Vehicles/ implements involved**
N/A

**Relevant script mods**
Autodrive, VCA, VehicleInfo
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7823197/log.txt)

**Comment by patrilln** [comment]
i have the same issue but i dont have a self driven sprayer

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7823527/log.txt)

**Comment by pull2play** [comment]
Issue persists. Same error.
