### ISSUE TITLE
[BUG_SP] Width detection broken, reset to 1.9 after attaching an implement

### ISSUE THREAD

**Issue by Himiriel** [Courseplay/Courseplay_FS22#381]
Worked fine in 7.0.0.12, broken in 7.0.0.13. Reverting this commit fixes the issue: d5cdedb82b57477cf10440495741ce3582dab5f3

**Steps to reproduce**
1. Attach an implement (tested on "Kompaktomat 1570 Max" 15m shallow cultivator and "PW 100-12" 6m plow)
2. Open "Generate course" menu

**Actual behavior**
You will see that working width parameter is set to 1.9m

**Expected behavior**
Working width should be about 16m if you attached "Kompaktomat 1570 Max" cultivator or about 6m if you attached "PW 100-12" plow

**Screenshots**
Incorrect width
![Incorrect width](https://user-images.githubusercontent.com/5014678/148422290-0b86e955-5301-4ed3-ae9d-e55873821e0a.png)

Correct width
![Correct width](https://user-images.githubusercontent.com/5014678/148423372-0c071587-e7d7-4e1a-8d65-b69484733ca6.png)

**Courseplay version**
Version used: 7.0.0.13

**Log**
[log_incorrect.txt](https://github.com/Courseplay/Courseplay_FS22/files/7823577/log_incorrect.txt)
[log_correct.txt](https://github.com/Courseplay/Courseplay_FS22/files/7823599/log_correct.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Tested on "Kompaktomat 1570 Max" 15m shallow cultivator and "PW 100-12" 6m plow

**Relevant script mods**
No mods, disabled everything except Claas DLC and Courseplay and started new map.

**Comment by Tensuko** [comment]
Should work again now.

**Comment by Himiriel** [comment]
Yes, seems to be working again in 7.0.0.15. Thanks!
