### ISSUE TITLE
[BUG_SP] Weird Steering at Corners

### ISSUE THREAD

**Issue by TheSoldier91** [Courseplay/Courseplay_FS22#384]
**Steps to reproduce**
only tested Field 38, Haut Beyleron
trying to cultivate the field

Course generated with:
3 headlands
sharp edges
clockwise
autowidth

**Actual behavior**
Weird steer generating in general at corners
steering causes not cultivated spaces

**Expected behavior**
sharp edges with turning on field, push backwards to turn

**Screenshots**
![20220106190146_1](https://user-images.githubusercontent.com/60544088/148430157-971ea698-790d-4edd-9f34-b6facf02456e.jpg)

![20220106190409_1](https://user-images.githubusercontent.com/60544088/148430187-9a0884af-b9f7-46f6-8081-5931bdbfde07.jpg)

**Courseplay version**
Version used: 7.0.0.15

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7823866/log.txt)

**Map**
Haut Beyleron
**Vehicles/ implements involved**
Claas Axion 870, Smaragd 9/500K Cultivator

**Relevant script mods**
Several tractors, Buildings, AutoDrive

**Comment by pvaiko** [comment]
Wow. This does not seem to be our most successful release :)

**Comment by Tensuko** [comment]
> Wow. This does not seem to be our most successful release :)

We should have skipped the 13 :)

**Comment by pvaiko** [comment]
Look at the bright side, we have an awesome turnaround time...
