### ISSUE TITLE
Scharfe Wende im Vorgewende funktioniert nicht mehr

### ISSUE THREAD

**Issue by Stummerl** [Courseplay/Courseplay_FS22#385]
Die "Scharfe" Wende im Vorgewende macht macken. Siehe Videos.
Kurs war bei beiden Versuchen exakt der gleiche.

Die letzte Version 7.0.0.12 funktionierte einwandfrei.
https://youtu.be/m3E7MGBeiQM

Ab Version 7.0.0.13 begannen die Schwierigkeiten. Ist auch mit Version 7.0.0.15 nicht behoben.
https://youtu.be/DKzSSu3SqPs

Hoffe das mit dem Link funktioniert.

**Comment by Tensuko** [comment]
#384

**Comment by Tensuko** [comment]
Und warum wieder das Tamplate nicht benutzt ?

**Comment by Stummerl** [comment]
Asche auf mein Haupt 😔
Ich gelobe Besserung.
