### ISSUE TITLE
[BUG_SP]  minor bug = workers cost even it is set to 0%

### ISSUE THREAD

**Issue by koeder2** [Courseplay/Courseplay_FS22#386]
**Steps to reproduce**
FS22 steam version 1.2.0.2 (26574/56365)
reproducable in existing savegame (elmcreekand haut-beyleron) and new savegame in erlengrat) at any machine

**Actual behavior**
I have set the CP driver wage to 50% (also on a test basis to 0%), but 100% is always calculated. 
it is also shown hourly as wage costs.
it seems that the fs22 helper will be payed - but driving with courseplay.

**Expected behavior**
it will no workers cost billed

**Screenshots**
i found no pssibility to upload it directly in this post, so i choosed wetransfer to share files because i didn't know better
logs and screenshots: https://we.tl/t-jVTZSurlsa (automatic delete on 14.01.2022)
screen

**Courseplay version**
Version used: 7.0.0.12

**Log**
i found no pssibility to upload it directly in this post, so i choosed wetransfer to share files because i didn't know better
logs and screenshots: https://we.tl/t-jVTZSurlsa (automatic delete on 14.01.2022)

**Map**
any map

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
none (only realtimeclock active)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by Tensuko** [comment]
How did you start your driver ?
With 7.0.0.12 and press on H it will start the normal Helper if you did not start a job as CP:Fieldwork before.
With 7.0.0.16 you have to set an extra key (check your keybinds) or use the mini hud to start CP.

**Comment by Philj030** [comment]
Tensuko how do i see the mini hub? and can you set a standard key bind of ctrl+H to restart CP? so that its always there?

**Comment by Tensuko** [comment]
We can set it to default, but you can set it like you want.
The Mini Hud is the same, add a keybind, I am not sure if we already set it to "del" as default.

It is rly hard to find a proper keybind, since so many keybinds are used already.

**Comment by koeder2** [comment]
hello tansuko

while i wrote this post is 7.0.0.16 released.
in 7.0.0.16 seems it is no longer.

in 7.0.0.12 i generated the course it is showed my in display all waypoints.
startet it over "H" (in "F1" active in german it is like "hire helper (CP)") - so i understand it starts the courseplay-helper
even restart of courseplay / fs22 didn't solve the issue. - start over start job in helper menu not done.
in 7.0.0.16 i make my specific CP start stop and it worked good
