### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Foody1986** [Courseplay/Courseplay_FS22#388]
Hallo erst mal ein sehr großes Lob an die Entwickler von Courseplay, vielen dank für diesen Mod! Ich habe festgestllt das mann mit den ganzen Ladewägen ob Mod oder Standart keine Feldarbeit Kurse erstellen kann. Wäre net wenn ihr das fixen könnt.Vielen dank schon mal im vorraus.MFG

**Comment by koeder2** [comment]
wird aktuell noch nicht unterstützt
not supported yet

**Comment by Tensuko** [comment]
Duplicate
