### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Foody1986** [Courseplay/Courseplay_FS22#389]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: v7.0.0.16

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on. Haut Beyleron

**Vehicles/ implements involved**
Mod yes/no ? Jes

**Relevant script mods**
Mods like Autodrive or VCA and so on.   Jes

Hallo erst mal ein sehr großes Lob an die Entwickler von Courseplay, vielen dank für diesen Mod! Ich habe festgestllt das mann mit den ganzen Ladewägen ob Mod oder Standart keine Feldarbeit Kurse erstellen kann. Wäre net wenn ihr das fixen könnt.Vielen dank schon mal im vorraus.MFG

**Comment by koeder2** [comment]
#388
ladewagen ist noch nicht implementiert soviel ich weis
bitte in englisch schreiben, es wird vor allem englisch-sprachig entwickelt
und obitte keine posts doppelt machen...

**Comment by Tensuko** [comment]
Kein Bug, Template nicht benutzt und wurde schon oft gesagt, es kommt noch, bitte abwarten.
