### ISSUE TITLE
Courseplay -Log

### ISSUE THREAD

**Issue by Tobias80** [Courseplay/Courseplay_FS22#39]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7775062/log.txt)

Hi Hab mal meine LOG angehängt.
Hab damit Probleme -Courseplay kann den Kurs generieren -jedoch findet er "das Feld nicht"

**Comment by kampsheider** [comment]
Hallo zusammen und frohe Weihnachten.
Danke erstmal an die Ersteller von Courseplay. 
Läuft schon fast gut. Nur habe ich eben gemerkt das wenn Courseplay ein Feld fertig hat, das sich dann das Spiel aufhängt.
Außerdem will Courseplay wenn er anfängt den Kurs zu fahren, den Dräscher zuklappen. Auch das Mähwerk. Klapp nicht wenn schon Weizen im Tank ist. Auch will er bei der Option " nächster Wegpunkt " immer zum Startpunkt fahren aber nie den nächsten Punkt nimmt.
Aber schon mal meinen größten Respekt das es so schnell geschafft wurde Courseplay zu erstellen.
Vielen Dank

**Comment by Hades446** [comment]
Hallo zusammen
also ich finde ja Courseplay auch gut nur muss man bei euch erstmal studieren um überhaupt mal durch zu steigen wie man das aktualisiert und zweitens könnt ihr euch mal bitte entscheiden welche man runterladen soll und welche nicht weil alle scheinen ja nicht zu gehn. Da kommen eine Version nach der anderen und das innerhalb von einere Stunde sa man bitte an welche Version jetzt funzt und welche nicht und vorallem wie man sie aktualsiert wäre sehr nett.
