### ISSUE TITLE
Welche ist die funktionierte Version von Courseplay?[Question]

### ISSUE THREAD

**Issue by Hades446** [Courseplay/Courseplay_FS22#390]
Ich würde ganz gerne mal wissen welche eine Funktionierende Version von Courseplay ist? Gibt ja von 7.0.0.1 bis 7.0.16 die müssen ja im Minutentakt kommen. Lad ich es mir runter lege es in den Modordner findet er rein gar nichts schon komisch, wäre es möglich mir das mal eine passende Antwort drauf zu geben. Und vorallem wie aktualisier das Teil das würde mich auch mal interessieren.

**Comment by Tensuko** [comment]
Die neueste ?!
Runterladen und ersetzen wie jede andere Mod auch... die nicht ausm ModHub kommt....

**Comment by koeder2** [comment]
hallo Hades446

ich bin nur ein normaler nutzer (hab mich heut angemeldet um ein bug zu posten)
es gehen allgemein alle Versionen - hast du nachdem du den mod in den Modordner verschoben hast fs22 neu gestartet?
ich habe heute version 7.0.0.12 (aktuellste version zum herunterladen - aktuallisiert vor 3 Wochen) installiert.
ein bug gefunden / geposted und schon war 7.0.0.16 (6 minuten) draußen

Hinweis: FS22 ist noch in der (frühen) Betaversion - also an normales arbeiten mit courseplay ist noch nicht zu denken ;)
es wird an allen stellen gearbeitet und deswegen gibt es ständig neue versionen.

**Comment by Hades446** [comment]
Hallo Ichhabe mir fast alle Versionen runter geladen und sobald ich das Spiel starte ist nichts im Modordner rein gar nichts, ich frage mich wasich falsch mache   Gesendet von Mail für Windows Von: koeder2Gesendet: Donnerstag, 6. Januar 2022 20:35An: Courseplay/Courseplay_FS22Cc: Hades446; AuthorBetreff: Re: [Courseplay/Courseplay_FS22] Welche ist die funktionierte Version von Courseplay?[Question] (Issue #390) hallo Hades446ich bin nur ein normaler nutzer (hab mich heut angemeldet um ein bug zu posten)es gehen allgemein alle Versionen - hast du nachdem du den mod in den Modordner verschoben hast fs22 neu gestartet?ich habe heute version 7.0.0.12 (aktuellste version zum herunterladen - aktuallisiert vor 3 Wochen) installiert.ein bug gefunden / geposted und schon war 7.0.0.16 (6 minuten) draußenHinweis: FS22 ist noch in der (frühen) Betaversion - also an normales arbeiten mit courseplay ist noch nicht zu denken ;)es wird an allen stellen gearbeitet und deswegen gibt es ständig neue versionen.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Hades446** [comment]
Dazu müsste ich erstmal eine Finden die normal funzt und erst gar nicht im Modordner erscheint. Soviel zu ersetzen   Gesendet von Mail für Windows Von: TensukoGesendet: Donnerstag, 6. Januar 2022 20:27An: Courseplay/Courseplay_FS22Cc: Hades446; AuthorBetreff: Re: [Courseplay/Courseplay_FS22] Welche ist die funktionierte Version von Courseplay?[Question] (Issue #390) Die neueste ?!Runterladen und ersetzen wie jede andere Mod auch... die nicht ausm ModHub kommt....—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
