### ISSUE TITLE
[BUG_SP] Kursgenerator generiert keinen Kurs mehr auf selbst erstellten Feldern (seit 7.0.0.10)

### ISSUE THREAD

**Issue by Gibbs9019** [Courseplay/Courseplay_FS22#391]
**Steps to reproduce**
Kursgeneration auf selbst angelegten Feldern

**Actual behavior**
Der Kursgenerator friert ein und generiert keinen Kurs wenn der Startpunkt auf einem selbst erstellten Feld liegt. (hat vor Version 7.0.0.12 noch funktioniert

**Expected behavior**
-

**Screenshots**
-
**Courseplay version**
7.0.0.16

**Log**

**Map**
Elmcreek

**Vehicles/ implements involved**
Standard 8R John Deer und andere

**Relevant script mods**
AD and VCA sind installiert, waren es aber bei Version 7.0.0.10 auch und da hat es funktioniert

**Comment by Tensuko** [comment]
Do you have a savegame on a standart map with a combined custom field ?
One of the 3 maps, doesn't matter.

**Comment by pvaiko** [comment]
How about a log first?

**Comment by Gibbs9019** [comment]
Just got a course without a headland, because in the log it said it couldnt find one with.
I think the equipment has to large of a working width for the field in use. With smaller equipment it worked. So just disregard the issue then.
