### ISSUE TITLE
[Question] Ausblenden ??

### ISSUE THREAD

**Issue by Goofy78** [Courseplay/Courseplay_FS22#394]
Keine Ahnung obs nur mir aufgefallen ist, aber wäre es möglich das noch auszublenden? 

![IMG_E8767](https://user-images.githubusercontent.com/96694308/148446521-44cf5cdd-d5d6-4d47-82dc-476c1141eaf0.png)

**Comment by Zwox89** [comment]
Das ist seit dem neuestem Update. Wird wohl ein Bug sein

**Comment by Tensuko** [comment]
Ne das ist schon länger drin, sollte dann mit der nächsten Version weg sein.
