### ISSUE TITLE
[BUG_SP] Fieldwork option un-available for forage wagons

### ISSUE THREAD

**Issue by clubpetey** [Courseplay/Courseplay_FS22#395]
**Steps to reproduce**
Enter tractor, attach forage wagon, go to "Active Workers" screen, select "Create Job"

**Actual behavior**
No "CP: Fieldwork" option.  I'll note that I do not get the standard game "Fieldwork" option either. Also, both the Fieldwork and CP:Fieldwork options exists for balers like the Vicon FastBale.

**Expected behavior**
I should get the "CP: Fieldwork option".  I am guessing that forage wagons aren't supported with the standard game AI which is why the options don't show up, but since CP has loadable courses, it should be available here.  The stop-when-full mechanics are already in place for combines, so not sure why Balers work and forage wagons don't.  Just tracing the path with the tractor would be helpful.  Maybe there should be a new "CP: Path" work options that just follows a given path with the selected vehicle.  There was something like this in the FS19 version.

**Screenshots**
n/a

**Courseplay version**
Version used: 7.0.0.12

**Log**
[log.txt](https://pastebin.com/0aFxBxJX)

**Map**
Erlengrat, but bug isn't map-specific

**Vehicles/ implements involved**
Any Forage Wagon - doesn't work
Mod: Vicon FastBale - does work

**Relevant script mods**
None

**Comment by Tensuko** [comment]
This is not a bug, it is not implemented yet! Pls use search function......
