### ISSUE TITLE
[Question] Fahrerlohn bei 0%

### ISSUE THREAD

**Issue by Andi-ger** [Courseplay/Courseplay_FS22#396]
Hallo, 
ich habe das Problem das mir trotz einstellung auf 0% Lohn abgezogen wird.
Ich habe darauf  geachtet das ich auf jedenfall CP Feldarbeit ausgewählt und gestartet habe.
Was  mache ich Falsch ?

Ich benutze version 7.0.0.15

Bild aus dem Spiel
![image](https://user-images.githubusercontent.com/78974049/148459125-f67de9de-67ca-4833-9b39-8ed619c1b110.png)
Bild vom log
![image](https://user-images.githubusercontent.com/78974049/148460323-0697074d-4187-4a8d-805b-d99696afdbc8.png)

Mit besten Dank im Vorraus

**Comment by Sacred-Shadow** [comment]
Wird wirklich dauerhaft Lohn abgezogen oder wars nur ne einmalige Zahlung?

**Comment by Andi-ger** [comment]
Hallo,
ja es wird ein beständiger Lohn Abgezogen sobald ich den Job starte.
Das Geld "tickt" beständig nach unten (ohne extra Ausweisung). Sobald ich den Job stoppe hört es sofort auf.  Ich habe es mit allen möglichen  Situation getestet. 
Mit 
- Drescher
- beim Düngen
- Grubben
...

**Comment by Tensuko** [comment]
Und wie hast du den job gestartet ?

**Comment by Tensuko** [comment]
Und so postet man keine log....
Siehe Wiki!

**Comment by Andi-ger** [comment]
Hallo Tensuko,

zuerst muss ich mich dafür entschuldigen dich mich so wenig Informationen gefragt zu haben.
Ich habe es nochmal neu  generiert und Schritt für Schritt dokumentiert.

Zuerst wähle ich mein Drescher und gehe auf 

1. Job erstellen.
![Bild 1](https://user-images.githubusercontent.com/78974049/148523474-0920d1f0-7cc7-45ba-a752-c21947dd93de.png)

2. Dann wähle ich die Zielposition 
3. und gehe dann auch CP:Öffnen/Schliessen Kursgenerator

![Bild 2](https://user-images.githubusercontent.com/78974049/148523503-a95c3e7b-e4ae-418d-bff7-ff55dd66a292.png)

Hier führe ich die Notwendigen Einstellungen aus 
und gehe dann auf
4. CP: Generiere Feldkurs
und im anschluss auf 
5. CP:Öffnen/Schliessen Kursgenerator
![Bild 3](https://user-images.githubusercontent.com/78974049/148523518-c7713b15-938a-4a14-8941-344423f41bd5.png)

Hier wähle ich einfach 
6. Job starten
![Bild 4](https://user-images.githubusercontent.com/78974049/148523529-607a6e75-b80b-4cc3-b95d-ccff3b1482ed.png)

und natürlich die LOG File nun richtig. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7827935/log.txt)

Ich hoffe ich habe nun alles zusammen.

Danke für die Geduld

**Comment by Tensuko** [comment]
@Andi-ger 
Wenn alle so eine 'Anelitung' dafür machen würden wäre unsere Arbeit oft leichter :)
So und trotzdem wird Lohn abgezogen ?

**Comment by Tensuko** [comment]
Kann ich nicht reproduzieren, dir sind aber diese Einstellungen bewusst ?
Krafststoff wird halt ständig verbraucht und auch gekauft.
![fsScreen_2022_01_07_20_56_22](https://user-images.githubusercontent.com/27344744/148599915-f61004d5-e1ad-499d-8ad1-d69eac7737df.png)

**Comment by Andi-ger** [comment]
@Tensuko

Ich darf mich an dieser Stelle für deine Hilfe bedanken, diese Einstellungen sind in Vergessenheit bei mir geraden, 
und es war wie du schon richtig vermutet hast der Kraftstoff der nachgekauft wurde. 
Ich fühle mich ein wenig dumm :-(.

DANKE für den tollen und netten Support.

Andi
