### ISSUE TITLE
Incorrect unit conversion [BUG_SP]

### ISSUE THREAD

**Issue by double07killor** [Courseplay/Courseplay_FS22#398]
CP_Fieldwork width in feet is wrong, for a 6m subsoiler I need to set the width to a bit less than 2ft, so I believe the conversion from ft to meters is backward 3.28m for every ft instead of the other way around

**Courseplay version**
Version used: 7.0.0.13

**Map**
Elm Creek

**Vehicles/ implements involved**
No Mods, JD 9RX, biggest subsoiler

**Relevant script mods**

**Comment by PeanutthaKid** [comment]
Confirming. 1 meter is 3.28 ft.  A 6m implement would be 19.68 ft

**Comment by Tensuko** [comment]
#128 and dont use 0.0.13 we are at .16 with hotfixes for workwidth

**Comment by PeanutthaKid** [comment]
Still no fix on .16
