### ISSUE TITLE
UI Text Bleeds over end of Course Generation Dialog

### ISSUE THREAD

**Issue by clubpetey** [Courseplay/Courseplay_FS22#399]
**Steps to reproduce**
Open Course generation dialog.  

**Actual behavior**
Right-hand "tooltips" for the settings bleeds off the end of the blue background. I am guessing you may need an ultra-wide monitor/resolution to see this bug.  I am using 3840x1600

**Expected behavior**
Text should be shifted over to the left to fit within dialog background, or whitespace around selectors should be shrunk

**Screenshots**
![image](https://user-images.githubusercontent.com/2221486/148472792-6082e4a1-801d-4ab7-86a4-16dbb38d31f3.png)

**Courseplay version**
Version used: 7.0.0.12

**Log**
n/a

**Map**
Erlengrat

**Vehicles/ implements involved**
n/a

**Relevant script mods**
n/a

**Comment by throsten** [comment]
Maybe an addition which is visible in that picture also:

Since some lines were added the frame is not high enough. Its only a little bit, but the belowest field is a little hidden. You can scroll down with the mouse weel, so no problem to reach the field. But increasing the box hight a bit could solve that easily. And space would be there...

**Comment by Tensuko** [comment]
@schwiti6190 we may need to expand it to the original size.... was worth a try....

**Comment by ve3jec** [comment]
Happens at 3440 x 1440 as well.

**Comment by schwiti6190** [comment]
Could one of you post a screenshot of the settings menu, global setting or vehicle settings ?
I can't select a bigger resolution than 1920 x 1080 on my setup.

**Comment by clubpetey** [comment]
You will need an Ultra-wide or 4K monitor for bigger resolutions to show up.

Here's my display settings:
![image](https://user-images.githubusercontent.com/2221486/148678819-d2232348-feee-4f91-b459-e9d02e70e764.png)

Vehicle Settings: 
![image](https://user-images.githubusercontent.com/2221486/148678906-4803d1d7-2460-410c-915c-dbbe8cb6d5ef.png)

Global Settings:
![image](https://user-images.githubusercontent.com/2221486/148678918-611d0ff9-9995-43c4-98b0-ea6dab87c690.png)

**Comment by schwiti6190** [comment]
Oh man these layouts are really small. Our layout are based on these. Will have a look, but it's not a high priority :)

**Comment by Elite82pt** [comment]
I have the same issue...reason: also ultrawide monitor
