### ISSUE TITLE
Arbeitsgeschwindigkeiten max. 5km/h

### ISSUE THREAD

**Issue by Porter76** [Courseplay/Courseplay_FS22#40]
Beim ersten Versuch von Feldarbeit alles OK. Beim zweiten Versuch folgendes Problem: Alle Arbeitsgeschwindigkeiten lassen sich max. bis 5 km/h einstellen. Auf dem Weg zum Feld aber normale Geschwindigkeiten! Verschiedene Werkzeuge ausprobiert. Mache ICH was falsch?

**Comment by rohne83** [comment]
dürfte doch das selbe sein wie bei https://github.com/Courseplay/Courseplay_FS22/issues/28

**Comment by Porter76** [comment]
Update: Habe einiges ausprobiert. Offensichtlich nur wenn man Feldaufträge mit Maschinen aus dem Gebrauchtfahrzeugmarkt nutzen will! Bei allen anderen Maschinen funktioniert es gut, bis man die Gebrauchten einsetzen will. Danach geht nichts mehr!

**Comment by Tensuko** [comment]
Ich mach hier zu, so das wir alles in einem Issue behandeln können. Danke.
