### ISSUE TITLE
[BUG_SP] Ft measurement is incorrect. Continuation of issue #128

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#400]
**Steps to reproduce**
Have game set to Miles, attach an implement and began course generation

**Actual behavior**
Course generator has work width set to 2.35 ft, when course is generator, it uses a 7.7 m

**Expected behavior**
Expect a 8m Subsoiler to convert to 26.22 Ft, not 2.35 ft

Might suggest using imperial Yards instead of Ft.  1 yard = 0.9144 meters or 1 meter = 1.09 yards  vs 1 meter = 3.28 feet or 1 foot = 0.3048 meters

**Screenshots**
![fsScreen_2022_01_06_21_49_57](https://user-images.githubusercontent.com/96673100/148488814-dd6f5126-07d0-455f-be9f-497fa2f8f0a6.png)
![fsScreen_2022_01_06_21_50_18](https://user-images.githubusercontent.com/96673100/148488820-288e85ec-10fe-4c1e-8783-ee17a54ababc.png)
![Calculator](https://user-images.githubusercontent.com/96673100/148488827-c160bdfc-4077-4135-bdea-bc87d8f75bcd.PNG)

**Courseplay version**
Version used: 7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7826235/log.txt)

2022-01-06 21:54 Generating course, clockwise 1, width 7.7 m, turn radius 6.8 m, headlands 3, startOnHeadland 1
2022-01-06 21:54                    headland corner 2, headland overlap 7, center mode 1
2022-01-06 21:54                    row direction 5, rows to skip 0, rows per land 6

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Not moded

**Relevant script mods**
AD and Guidance Steering

**Comment by Tensuko** [comment]
This is not reopen, this is new issue and we pushed another fix wich will come in next release, see in old issue.
