### ISSUE TITLE
[Question] "Mini Hud"

### ISSUE THREAD

**Issue by Zwox89** [Courseplay/Courseplay_FS22#401]
Morgen!

Ich les öfter was von einem "Mini Hud" und das man das aufrufen könnte. 
Problem ist, ich kanns nicht aufmachen. 
![image](https://user-images.githubusercontent.com/96999699/148525034-771aabe2-4d0d-47ed-abc5-3dea3f587716.png)

Ich hab es zu F8 gebunden. (Falls es dieses Hud überhaupt ist)

![image](https://user-images.githubusercontent.com/96999699/148525354-2ead7604-5312-493a-aa77-ebcd591e64cf.png)

Es wär sogar bei den Hilfen dabei. Aber es passiert einfach nichts.

**Comment by Tensuko** [comment]
Versuch mal die entf Taste zuzuweisen. Und ein logfile könnte auch helfen.

**Comment by Zwox89** [comment]
Okay bei entf funktionierts
