### ISSUE TITLE
[BUG_SP] Bredal K165 auto with to 30 meters.

### ISSUE THREAD

**Issue by velendier** [Courseplay/Courseplay_FS22#403]
**Steps to reproduce**
Bredal K165 spreader with extension and spreading discs auto with to 30 meters wide. 

**Actual behavior**
Bredal K165 spreader with extension and spreading discs auto with to 30 meters wide. 

**Expected behavior**
A working with of 18 meters. 

**Screenshots**
![20220107050116_1](https://user-images.githubusercontent.com/97285382/148528209-91fb4ed0-652c-4842-8b35-bab86e4b5390.jpg)
![20220107050554_1](https://user-images.githubusercontent.com/97285382/148528213-ea74174b-01c9-4ffc-af0e-549cfc7f7caa.jpg)

**Courseplay version**
Version used:  7.0.0.15

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
elm creek

**Vehicles/ implements involved**
class axion 960 bredal k165. it happens an all tractors, and no they are not modded

**Relevant script mods**
autodrive.

**Comment by Tensuko** [comment]
18m is for lime
30m for fertilizer
VCA is the same.

Not a bug, you may need to reattach your tool when loaded lime.
