### ISSUE TITLE
[BUG_SP] Debug aktiv ohne es zu aktivieren

### ISSUE THREAD

**Issue by Stummerl** [Courseplay/Courseplay_FS22#404]
**Steps to reproduce**
Keine, ist immer da.

**Actual behavior**
Siehe Screenshot. Obwohl kein DebugChannel aktiv und Debug nicht aktiviert, wird bei der Wende das angezeigt. Egal ob in dem Fahrzeug welches sich mit CP bewegt oder in einem anderen welches sich nicht bewegt, wird die gleiche Zeile angezeigt.

**Expected behavior**
Keine Debugzeile

**Screenshots**
![fsScreen_2022_01_07_12_20_41 (Large)](https://user-images.githubusercontent.com/97124563/148537310-82437099-5735-4c25-91af-16754d1b9f8b.png)

**Courseplay version**
7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7828497/log.txt)

**Map**
Erlengrat

**Vehicles/ implements involved**
Fendt 724
Steinsammler
Beide Standard ausm Spiel, keine Mods.

**Relevant script mods**
Einziger aktiver Mod CP. Alles andere siehe LOG.

PS: Wenn der Steinsammler voll ist, fährt der CP-Helfer einfach weiter und sammelt weiter Steine auf. Steine verschwinden, aber mx. Volumen vom Sammler ist erreicht. Sollte ich dazu evtl. einen neuen Issue Schreiben?

**Comment by Tensuko** [comment]
Suche hilft und ist schon gefixt für die nächste Version.
