### ISSUE TITLE
Häcksler hebt Pickup nicht[BUG_SP]

### ISSUE THREAD

**Issue by eric4072** [Courseplay/Courseplay_FS22#405]
**Steps to reproduce**
CP Häcksler mit Pickup +AD Abfahrer 

**Actual behavior**
Am Ende eines Schwads hebt der Häcksler die Pickup nicht. Dadurch kommt es vor dass:
1. er im Wendemanäver kleinste "Reste" an Gras erkennt und dadurch stehen bleibt 
2. AD scheinbar das Wendemanöver nach links nicht zu erkennen. (ich melde das auch dort ein weil ich nicht weiß wo der Fehler herkommt) 

Video:
https://youtu.be/AbxWo694feo 

leider habe ich nicht an die log gedacht...

könnte es aber in ein paar Tagen nachstellen

Danke an gesamte Team, CP fühlt sich schon richtig gut an ;-)

LG
Eric

translated via google:
The forage harvester does not lift the pick-up at the end of a swath. This means that:
1. He recognizes the smallest "remnants" of grass in the turning maneuver and thus stops
2. AD apparently does not recognize the turning maneuver to the left. (I also report that there because I don't know where the error comes from)

Video:
https://youtu.be/AbxWo694feo

unfortunately I didn't think of the log ...

but could readjust it in a few days

Thanks to the whole team, CP feels really good ;-)

LG
Eric

**Expected behavior**

**Screenshots**

**Courseplay version**
aufgenommen mit 7.0.0.12 (habe in den releases nichts darüber gefunden)

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
> 2\. AD scheinbar das Wendemanöver nach links nicht erkennt. (ich melde das auch dort ein weil ich nicht weiß wo der Fehler herkommt)

Es gibt noch keine offizielle Schnittstelle...

Mit dem Pickup gucken wir uns an.

**Comment by eric4072** [comment]
Danke

**Comment by knoxville73** [comment]
Hello,
It's the same with a loadwago
![fsScreen_2022_02_05_11_05_27](https://user-images.githubusercontent.com/23388102/152637359-39249e15-aa52-453b-85a9-d4afcbd3bcd3.png)
n
