### ISSUE TITLE
Traktor mit Ladewagen fährt den Kurs nicht ab.

### ISSUE THREAD

**Issue by freiser77** [Courseplay/Courseplay_FS22#406]
Hallo,

ich habe auf der Erlengrad-Karte mit dem Krone Big-M die Felder 18-20 (habe ich zusammengelegt) gemäht.
Wenn ich jetzt mit einem Traktor (Claas Arion) mit Ladewagen (Claas) denselben Kurs zum aufsammeln fahren will, bleibt der Helfer am Startpunkt einfach stehen. Ist das noch nicht implementiert? Ist doch auch Feldarbeit, oder?

**Comment by Onkel2000** [comment]
Ist noch nicht implementiert.
