### ISSUE TITLE
[Feature] Disable remainder cleanup

### ISSUE THREAD

**Issue by freiser77** [Courseplay/Courseplay_FS22#407]
**What is the problem this feature/enhancement solves?**
I have big fields where I use multiple tractors in combination to do the field work. On the last track, they tangle, because it is only the cleanup of the last one meter (for example). Then the tractor that has already turned, collides with the one that has not turned.
In combination with the missing obstacle detection, it creates a real mess.

**Describe the solution you'd like**
It would be sufficient for me to be able to switch of lanes, that do not have the full working width assigned.

**Describe alternatives you've considered**
A working obstacle detection, stopping the machine when something is in the way (like another machine, bales, etc.)

**Additional context**
<img width="725" src="https://user-images.githubusercontent.com/14125584/148552437-70ac7755-652c-4140-b4cb-d6d3e6cfd0b5.png">

**Comment by Tensuko** [comment]
To complicated to do that.
Won't happen, sry.

**Comment by rohne83** [comment]
Multitool courses are not implemented yet. And if you want to have all vehicles following the same course a collision is unavoidable for normal up/down rows. You can avoid when using skip rows or a different pattern for the field rows.
