### ISSUE TITLE
Imperial Units not being correctly converted in Course Generator [BUG_SP]

### ISSUE THREAD

**Issue by PeanutthaKid** [Courseplay/Courseplay_FS22#409]
**Steps to reproduce**
Use Miles setting in Game

**Actual behavior**
The work width being displayed in the course generator is being converted the wrong way.  It appears the conversion is happening as m * 0.3048 which is the imperial to metric conversion (feet to meters).  In my testing I am using a seed cart which is 18.2m, a 24 meter cultivator, and a 42m fertilizer spreader.

**Expected behavior**
The Imperial measurement number should show as a higher number than the metric number.  The 18.2 meter seed cart should show as 59.696 ft, but instead shows as 5.55 ft, the 24 meter cultivator should show as 78.72 feet, but instead shows as 7.32 feet, and the 42 meter fertilizer spreader should show as 137.76 feet, but shows as 12.80 feet.  This indicates that the metric unit is either being divided by 3.28 when it should be multiplied by that, or that the metric number is being multiplied by 0.3048 when it should be divided by that.  

**Screenshots**
![fsScreen_2022_01_07_10_30_22](https://user-images.githubusercontent.com/2148439/148577732-55547de3-1080-4db8-be17-e6fa858e2fde.png)
![fsScreen_2022_01_07_10_49_23](https://user-images.githubusercontent.com/2148439/148577763-94dd75c9-df57-4684-85fe-0b0bd8fae94f.png)
![fsScreen_2022_01_07_10_38_56](https://user-images.githubusercontent.com/2148439/148577739-e060a516-aeab-4196-8308-057007e3a67a.png)
![fsScreen_2022_01_07_10_49_16](https://user-images.githubusercontent.com/2148439/148577749-8aa65a66-97d6-49ca-b71f-8323c36bd846.png)
![fsScreen_2022_01_07_10_43_33](https://user-images.githubusercontent.com/2148439/148577745-347ba4dc-e948-4fd9-8c6f-8cc91e7a3c9e.png)
![fsScreen_2022_01_07_10_49_31](https://user-images.githubusercontent.com/2148439/148577778-95e73b1e-86d3-468a-9adf-2f046e7a9691.png)

**Courseplay version**
Version used: 7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830197/log.txt)

**Map**
All maps tested the same way.  

**Vehicles/ implements involved**
Flexicoil ST820 cultivator - mod
CaseIH Precision Disk 500 seed cart - mod
Amazone ZG-TS 10001 Spreader - base game

**Relevant script mods**
Autodrive and VCA. Both active, but neither used.

**Comment by Tensuko** [comment]
#128 got another fix for this, mentioned in that Issue...

**Comment by PeanutthaKid** [comment]
Still no fix. I'm on .16 as instructed
