### ISSUE TITLE
Conflict with AI Vehicle Extension mod

### ISSUE THREAD

**Issue by fudoido** [Courseplay/Courseplay_FS22#41]
Hello team.
I have been using the AIVE mod while i was waiting for CP, and now that i got both mods active ingame, i started a spraying contract (herbicide, not fertilizing) and when vehicle arrived at field, instead of starting the CP route, it started AIVE instead.
Since both mods use the helper AI for use, dont think this will have a simple solution, but letting people know that courseplay will not play properly if AIVE is also active. Players will most likely to choose AIVE or CP, and i would say CP has a much better refinement than AIVE, considering that author has not put many alterations to the mod compared to fs19 version.....

**Comment by Tensuko** [comment]
When you want the driver to use cp, you have to go into the aive menu and turn off aive for this vehicle. It worked fine when we tested it.

**Comment by pvaiko** [comment]
Duplicate #35

**Comment by fudoido** [comment]
> Duplicate #35

didnt realized that issue was about AIVE as well, sorry for duplicate.
since i prefer CP fieldwork functions over AIVE, i will just disable AIVE at game load instead, easier than going through every vehicle to turn it off :p 
Just wanted to warn people in case they get the same issue, its not hard to solve by player input, dont think you guys should even bother too much with it for the time being anyway :)
