### ISSUE TITLE
[Feature] Have Forage Harvester not wait for trailer with lifted implement

### ISSUE THREAD

**Issue by nlcoredump** [Courseplay/Courseplay_FS22#411]
**What is the problem this feature/enhancement solves?**
At the moment when a forage harvester is turning to get to the next lane with the implement raised, it is still waits for a unloader to be close.  If you have automatic unloaders like from autodrive, things get close a lot of stopping, starting, and waiting happens. The harvester has no need for a unloader at this point, it is not harvesting.  Autodrive will move out of the way, but then harvester is waiting for it to get close again before it starts to move again.

**Describe the solution you'd like**
Have harvester move freely when implement is raised and mabe nothing to unload, start waiting for unloader when it is at start of new lane and implement down, not on the temp connecting track.  It gives some extra room to move when there is no unloader close.

**Describe alternatives you've considered**
Have courseplay unloader which is more "connected" with the courseplay harvester.  But you probably run into similair problem.  And i expect this feature to be already on a roadmap to be implemented at some point in the future.
 
**Additional context**

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.17
