### ISSUE TITLE
Game stops loading at 95% after using courseplay[BUG_SP]

### ISSUE THREAD

**Issue by PliskoFarmer** [Courseplay/Courseplay_FS22#412]
**Steps to reproduce**
Steps to reproduce the behavior.
Install courseplay on a copy of a game save.  Create courses on field 70 and 71 in Elmcreek with a Krone Big M.  Mow and create silage bales with the courses.  Save and quit.

**Actual behavior**
A clear and concise description of what happen.
Everything worked once I figured it out and I was happy when saving and quitting.  When trying to start the game again later, the game will not load past 95%.  I started the original save from before courseplay was used, it loads normally.  The only thing I did between the two saves was install courseplay 0.0.0.7 create those paths and use them for silage baling.  I got through it all once.  Then I quit and came back several days later to a game save that won't load.

**Expected behavior**
I expected the game to load.

**Screenshots**

**Courseplay version**
Version used: 
Installed 7.0.0.7  updated to 7.0.0.16 no change.

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
No log available because the game did not load.

**Map**
Map played on.
Elmcreek
**Vehicles/ implements involved**

Krone Big M.  Fastrac with a vicon fastbale on it

Mod yes/no ?

Other mods are on the map including AutoDrive.

**Relevant script mods**
Mods like Autodrive or VCA and so on.

See attached screenshot below.

I tested the latest backup save of this in a new save slot. It also won't open.  The original save, from JUST before using courseplay opens normally.   Turning off courseplay on the save and updating does not help the game load.

**Comment by PliskoFarmer** [comment]
Sorry I accidentally posted a blank title and bug form.. lol

**Comment by PliskoFarmer** [comment]
Mods
![Screenshot (14)](https://user-images.githubusercontent.com/96460007/148594410-9f173f78-1c5f-49c0-91a6-188c9cd9dee7.png)

**Comment by pvaiko** [comment]
There is always log, even if the game does not completely start, and we need that log....

**Comment by PliskoFarmer** [comment]
OK I expected that I would need to turn on the debugging to get a log... This is my first time dealing with FS logs.   I will look for it.

**Comment by Tensuko** [comment]
Our Wiki Page might help you with that:
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by PliskoFarmer** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830873/log.txt)
I guess I was only reading about the debugging logs.  Is that the log you need.

**Comment by Tensuko** [comment]
Error: NVIDIA DLSS cannot be loaded due to outdated driver. Minimum Driver Version required : 0.0

Not a CP Error, that is a driver Error that you got there.

But you should remove (Version: 7.0.0.7) FS22_Courseplay and place the newest Version :)

**Comment by PliskoFarmer** [comment]
Ok.  Thanks.  I only suspected CP because the other saves open normally.  I wouldn't expect a driver to know the difference.

**Comment by PliskoFarmer** [comment]
I updated courseplay already.  I'll let you know if the driver update doesn't work.

**Comment by PliskoFarmer** [comment]
Driver updated.  The game save is still hanging at 95%. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830978/log.txt)
