### ISSUE TITLE
Probleme mit dem Ladewagen!!!

### ISSUE THREAD

**Issue by Foody1986** [Courseplay/Courseplay_FS22#414]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Ist noch immer nicht implementiert!!!
Nutzt doch bitte mal die Suche Jungs...
