### ISSUE TITLE
Probleme mit CP und Ladewagen Feldarbeit erstellen!!

### ISSUE THREAD

**Issue by Foody1986** [Courseplay/Courseplay_FS22#415]
Hallo liebes Courseplay Team 

Erst mal vielen dank für diesen mega geilen Mod!!!
Ich habe leider festgestellt das mann mit einem Ladewagen am Traktor keine CP Feldarbeiten erstellen kann. würde mich freuen wenn ihr mal das Problem anschauen könnt, dass man auch mal Stroh oder Gras Schwaden automatisiert einfahren kann.

LG Foody

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
#414
Nein ist noch nicht!
