### ISSUE TITLE
[BUG_SP] Lua Error beim Kurs generieren

### ISSUE THREAD

**Issue by MST050706** [Courseplay/Courseplay_FS22#417]
**Steps to reproduce**
Kurs generieren 

**Actual behavior**
Wenn ich einen Kurs generiere dann kommt ein Lua error und es bewegt sich nur die Map im Hintergrund und es wird kein Kurs generiert. Mit der ersten Version ging dies Fehlerfrei.

**Expected behavior**
Das der Kurs normal generiert wird.

**Screenshots**

**Courseplay version**
Version used: V7.0.0.16 

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7831017/log.txt)

**Map**
Osina

**Vehicles/ implements involved**
Mod yes

**Relevant script mods**
VCA

**Comment by Tensuko** [comment]
Welche Version hat auf der Map noch funktioniert ?

**Comment by MST050706** [comment]
Die aller erste

**Comment by MST050706** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7831054/log.txt)
Nocjmal die Log mit allen Debug Channels. Hatte ich vergessen sorry ;)

**Comment by Tensuko** [comment]
Und was ist für dich die aller erste ?

**Comment by MST050706** [comment]
Die die ihr für den 22er releast habt. 
v7.0.0.1

**Comment by Tensuko** [comment]
Da liegen 15 Versionen zwischen.... keine Idee ab wann es nicht mehr ging ?

**Comment by MST050706** [comment]
Hatte es nie aktualisiert.

**Comment by MST050706** [comment]
Also hab nur die 2 Versionen gespielt. kann es dir leider nich sagen.

**Comment by MST050706** [comment]
UPDATE: Bei V7.0.0.10 gehts zu letzt

**Comment by Tensuko** [comment]
Ah super, danke dir fürs probieren!

**Comment by pvaiko** [comment]
Das heisst, diese Map hat weniger als 10 cm zwischen Felder ...

**Comment by MST050706** [comment]
Jo kein Problem ging ja schnell mit dem Testen.
Ahh ok aber das Feld geht ja noch in v7.0.0.10 und in 0.11 nicht mehr? Kann man das irgendwie ändern oder könnt ihr das in einer Version fixen?

**Comment by Geradsralf** [comment]
Habe die gleiche Beobachtung gemacht. Habe große Arbeitsbreiten bei kleinen Feldern im Verdacht, den Fehler zu erzeugen. In 7_0_0_12 und 7_0_0_16 kann z.B. mit Düngerstreuer und oder Spritze kein Vorgewende auf  den Feldern 20, 64 und 65 und wahrscheinlich noch mehreren (Elmcreek) erstellt werden. In mindesten einer älteren Version war das auch schon mal als Fehler, kann aber nicht mehr genau sagen in welcher.
Wenn min. 1 Vorgewende ausgewählt ist, rastet die Map an den Mauszeiger beim Klick auf "Kurs generieren". Nächster Klick löst die Map wieder.
Stellt man dann Vorgewende auf 0, wird eine Route mit 1 Geraden oder 1 mal hoch und runter generiert. Dann klappt es.
Einen Log kann ich bei Bedarf beim nächsten mal liefern.

**Comment by MST050706** [comment]
Ja genau sowas habe ich auch beobachtet

**Comment by Tensuko** [comment]
@Geradsralf 
Mit 42m ein kleines Feld bearbeiten und dann noch mit Vorgewende macht man auch nicht... Was will man dann noch in der mitte ?

**Comment by Geradsralf** [comment]
Ja ist korrekt, passiert meistens bei der Abwicklung mehrerer Aufträge hintereinander wenn man mehrfach mit den gleichen Einstellungen einen Kurs generiert.
Grundsätzlich gibt es dann aber trotzdem immer Probleme mit dem Kurs ohne Vorgewende.
Mit der Feldspritze auf Feld 20 wurde z.B. ein Kursgeneriert, der weit außerhalb des Feldes die Wende vorsah. Die ging natürlich auf Grund der Bäume schief.
Auf 64 oder 65 mit dem Streuer wird eine einzige Bahn generiert, die einmal mit eingeschaltetem Streuer gefahren wird und dann aus irgendeinem Grund zurück gefahren wird ohne Streuer und noch einmal entlang des Kurses ohne Streuer gefahren wurde, bis schließlich am Endpunkt gehalten wird.
Da die Updates aber zum Glück schneller kamen als ich spiele, hatte ich noch keinen erneuten Auftrag zum Streuen auf dem Feld.

**Comment by Tensuko** [comment]
@Geradsralf Ich kann mit deinen Informationen rein gar nichts anfangen....
Feld 20 keine Ahnung was du meinst. Welche Fedlsprize, wie sah dein Kurs aus, hast du die Version in der die Feldrandberechnung verbessert wurde usw usw...
Kann bereits alles gefixt sein.
Und wie gesagt, keiner nutzt Vorgewende bei Feldern, wo man höchstens einmal rauf und einmal runter fährt...

**Comment by MST050706** [comment]
Um jetzt nochmal auf den eigentlichen Bug zurückkommen. Dafür gibt es afaik kein Fix oder?

**Comment by Geradsralf** [comment]
Sorry, aber mein Post von vor ein paar Minuten bezieht sich doch erneut auf meinen Post, 2 Antworten vorher. Da stehen doch Versionen und Karte drin. (Elmcreek)
Version bei dem Fehler mit der Feldspritze war bereits 7.0.0.16. 
Die genaue Bezeichnung der Feldspritze muss ich später erst nachschauen.

**Comment by Tensuko** [comment]
@MST050706 
Weis nicht, 10cm zwischen den Feldern ist schon etwas wenig, kenne die Karte jetzt nicht und muss sagen wenn das wirklich so ist, sehe ich das Problem eher an der Karte...

@Geradsralf 
Aber das alles hat nichts mit diesem Issue zu tun...
Häppchenweise Informationen inmitten eines andere Issues, damit kann man einfach nichts anfangen.
Auch keine Screenshots und logfiles....
Wenn das ein riesen Problem ist, dann mach bitte ein eigenes Issue auf.

**Comment by pvaiko** [comment]
So, mehr können wir momentan nicht machen, einige Felder funktionieren jetzt besser, aber die Feldgrenzen sind sehr unsauber auf dieser Map.

**Comment by MST050706** [comment]
Danke dir dafür

**Comment by F4bl32** [comment]
> So, mehr können wir momentan nicht machen, einige Felder funktionieren jetzt besser, aber die Feldgrenzen sind sehr unsauber auf dieser Map.

Seit dem Fix gehen zusammengelegte Felder nicht mehr da er nur noch die fieldID benutzt und bei zusammengelegten Feldern müssten es mehrere ID's sein.

**Comment by MST050706** [comment]
Das ist doof da ich viele Felder zusammen gelegt habe.

**Comment by pvaiko** [comment]
@F4bl32 dann weiss nicht wie ich das handeln soll.

**Comment by MST050706** [comment]
Gut dann lass ich es erstmal. Wenn eine neu Map kommt wird es schon wieder gehen.

**Comment by Tensuko** [comment]
Sry but as we said, this might be partly solved in 7.0.0.17
Not much more we can do about it without breaking other things.
Maybe you can try to contact the mapper to fix his Fields.
