### ISSUE TITLE
where is fail ?

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#42]
https://ctrlv.cz/m5Cx idk where is fail please help me ? i got translate on CZ if u want just edit on better translate

**Comment by Tensuko** [comment]
You mean the lines that are shown ?
That are some missed debugs that wasn't removed.
Try the new release.
If you have a translation to CZ and don't know how to make a pull request. I can do it for you if you attach the file here.

**Comment by Manyak007** [comment]
[translation_cz.zip](https://github.com/Courseplay/Courseplay_FS22/files/7775252/translation_cz.zip)

**Comment by Manyak007** [comment]
is it allowed to use more than 1 machine in the field? I have the impression that I did not find it in the settings, otherwise I found a problem if the combine has a full bunker so the pipe for opening opens and closes it makes such an unpleasant tick  sry my eng is bad use translator when u want movie not problem verzion 7.0.03

**Comment by Tensuko** [comment]
Multitool is not implemented yet, but will come back ofc!

**Comment by Manyak007** [comment]
ok thanks for you reply
