### ISSUE TITLE
Loadingwagon / Ladewagen

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#420]
Please stop opening issues and ask why loading wagons are not working...
This needs more than just collect on field, you all know that and this is not simple implement it for fieldwork.
Have a look at our search results!

Have patience! Thank you.

https://github.com/Courseplay/Courseplay_FS22/issues?q=ladewagen
https://github.com/Courseplay/Courseplay_FS22/issues?q=forage

**Comment by Zwox89** [comment]
If you always use the same harvester and it always follows the same route, you can help yourself out with Autodrive meanwhile.

**Comment by rohne83** [comment]
Workaround until the loading wagon is working: you can also attach i.e. a mower at the tractor's front, and have the CP fieldwork course followed for this one. Just have to manually turn on and lower the loading wagon before you engage the CP helper. And of course you have to unload manually (or engage Autodrive).

**Comment by Tensuko** [comment]
Loadingwagon are working now, unload somewhere is used with AD (I can't tell your what AD Version but it sure got to be .4 or higher)
