### ISSUE TITLE
[BUG_SP] Incorrect width in GUI

### ISSUE THREAD

**Issue by Drmattymd** [Courseplay/Courseplay_FS22#422]
**Steps to reproduce**
Open course generator

**Actual behavior**
Displayed width is off a decimal point. example: 24m width converts to 7.874 instead of 78.74 feet

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by PeanutthaKid** [comment]
It's not off by a decimal point, the math is completely wrong and there's supposedly a fix coming soon™

**Comment by Tensuko** [comment]
#128

**Comment by Drmattymd** [comment]
According to my math its just a decimal point off, and its only in the GUI,
it generates the course correctly
