### ISSUE TITLE
[Feature] Add an Informationlist where CP Helper shows their current 'needs' (e.g. Fertilizer is empty).

### ISSUE THREAD

**Issue by ConductorWon** [Courseplay/Courseplay_FS22#423]
**What is the problem this feature/enhancement solves?**
In previous versions of CP when there was an issue with a vehicle doing a course the prompt would remain on the screen until the issue was resolved/course was stopped. 

**Describe the solution you'd like**
Have the issue alerts remain on screen until issue is resolved. 

**Describe alternatives you've considered**
Maybe an audio tone when an issue arises? 

**Additional context**
N/A

**Comment by Tensuko** [comment]
We will see what we can do...
