### ISSUE TITLE
[BUG_SP] Ropa tiger 6: wired behaviour when reversing

### ISSUE THREAD

**Issue by AyakawaSakura** [Courseplay/Courseplay_FS22#425]
**Steps to reproduce**
When reversing Ropa tiger 6 and similar vehicle in a caterpillar style

**Actual behavior**
When reversing Ropa tiger 6 and similar vehicle in a caterpillar style

**Expected behavior**
Ropa tiger 6 reverse normally

**Screenshots**
https://youtu.be/xmcC7cD0or8

**Courseplay version**
Version used: 7.0.0.16

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7832890/log.txt)

**Map**
elm creek

**Vehicles/ implements involved**
Ropa tiger 6 (sugar beet harvester)

**Relevant script mods**
Enhanced vehicle

**Comment by AyakawaSakura** [comment]
This issue is also mentioned here: #424 . Hope it can be fixed soon.

**Comment by Tensuko** [comment]
Duplicate.
