### ISSUE TITLE
Pathfinder collision boxes shown when the pathfinder debug channel is on (surprise)

### ISSUE THREAD

**Issue by Podvorie** [Courseplay/Courseplay_FS22#426]
Step 1: Accidentally pressed the button to unhitch the header from the ROPA combine. Attached her back 
![изображение_2022-01-08_115250](https://user-images.githubusercontent.com/60159851/148638236-0df3a82d-4a75-418a-9cd2-246a3b791ba5.png)

Step 2: Auto begin displaing rate calculation 
![изображение_2022-01-08_115103](https://user-images.githubusercontent.com/60159851/148638174-52ce5bde-c5dd-4ee4-887e-96e39b525e4a.png)

Reload game - no effect. Calculation displaying.

How can I turn off the display of the course calculation?

Sorry. Ver. 0.16

**Comment by Tensuko** [comment]
I have to check that later.
Doesnt make much sence with those steps.

**Comment by Podvorie** [comment]
Thanks guys
