### ISSUE TITLE
CP Arbeit zu ende[Question]

### ISSUE THREAD

**Issue by masuti** [Courseplay/Courseplay_FS22#428]
Moin Leute,
wenn der CP Kurs abgearbeitet ist sollte das Gerät zugeklappt werden . Tut es aber nicht.
Ist das ein Bedienfehler von mir? Was muß ich machen?
Gruß Manfred

**Comment by Tensuko** [comment]
Irgendwo ist bereits ein Issue dazu, suche hilft.
