### ISSUE TITLE
worker menu, nearest waypoint will not drive course

### ISSUE THREAD

**Issue by scarlettthyde** [Courseplay/Courseplay_FS22#43]
how to produce the bug, begin by generating a course, change your mode to starting point near point. start job. tractor will not follow path, just drives straight. change it back to begin at first point, and first point works.

**Comment by pvaiko** [comment]
Sorry, I screwed up 7.0.0.2, try with 7.0.0.3

**Comment by tigranhov** [comment]
I had a similar issue and it got fixed after updating to 7.0.0.3. Tried on a few scenarios and it starts on nearby waypoint on 7.0.0.3

**Comment by pvaiko** [comment]
@tigranhov thanks for the feedback

**Comment by tigranhov** [comment]
I had time to use this feature more. While it just did not work in 7.0.0.2, it currently works, but sometimes the worker drives somewhere, when I have the time I will try to get a video and share.
