### ISSUE TITLE
[BUG_SP] Wenden am Vorgewende

### ISSUE THREAD

**Issue by IROKILLER** [Courseplay/Courseplay_FS22#430]
**Steps to reproduce**
Am Vorgewende holt er zu weit aus um in die nächste Spur zu fahren ich habe es so eingestellt das er erst die Bahnen und dann das Vorgewende machen tut

**Actual behavior**
Am Vorgewende holt er zu weit aus um in die nächste Spur zu fahren

**Expected behavior**
Das er innerhalb auf dem Feld wenden sollte

**Screenshots**
[https://youtu.be/QXA9fEIf69s](url)

**Courseplay version**
Version used: 7.0.0.16

**Log**
[https://pastebin.com/x99Nic7x](url)

**Map**
Elengrad 

**Vehicles/ implements involved**
Ja

**Relevant script mods**
 Autodrive

**Comment by Zwox89** [comment]
Da steht aber dabei "nicht mit allen Geräten möglich"

**Comment by IROKILLER** [comment]
Ja gut das hab ich jetzt nicht gesehen das war jetzt Fehler von mir. Aber vielleicht kann man das ja noch verbessern wenn das möglich ist

**Comment by Tensuko** [comment]
> **Vehicles/ implements involved**
> Ja

Ja wie wäre es zu schreiben WELCHES vehicle oder implement ?

**Comment by rohne83** [comment]
Die Wende im Video sieht doch gut aus, die macht er doch schon mit dem fast engstmöglichen Kurvenradius. Ein zwei Meter enger wäre im Optimalfall vielleicht noch drin, aber am grundsätzlichen Bild würde sich da nichts mehr ändern. Um ohne Rückwärtsfahrt auf dem Feld bleiben zu können brauchst du bei so einem Gespann einfach mehr Vorgewende als nur zwei Bahnen. Den Platzbedarf kannst du dabei noch reduzieren durch Reihen überspringen oder kreisförmig.

**Comment by Tensuko** [comment]
Jetzt konnte ich mir auch das Video angucken (war nicht am PC) und wie @rohne83 sagte, alles bestens.
