### ISSUE TITLE
How to continue sowing a field when the seeds run out?

### ISSUE THREAD

**Issue by Pchel07** [Courseplay/Courseplay_FS22#431]
the seeds ran out, the equipment got up, refueled the seeder. how to start the route further? from the nearest point he does not want to go or starts from the beginning or generally as he wants

**Comment by Pchel07** [comment]
![555](https://user-images.githubusercontent.com/97336733/148639579-cfa18fdb-c233-467b-a005-9e3f0bc5773a.jpg)

**Comment by Tensuko** [comment]
Fill it up again and either use the keybind to start cp or use the mini hud.
How did you fill it up ?

**Comment by Pchel07** [comment]
> Fill it up again and either use the keybind to start cp or use the mini hud. How did you fill it up ?

do you mean that the worker picks up the seed on his own and not me from my tractor?

**Comment by Pchel07** [comment]
> Fill it up again and either use the keybind to start cp or use the mini hud. How did you fill it up ?

is there in the CP setting, how to get a route after a stop? from the nearest point, something does not suit him.

**Comment by Tensuko** [comment]
So you did stop him or he was stopped then you willed him up and now you want continue. It should easy work with start cp keybind or mini hud.

**Comment by Pchel07** [comment]
> So you did stop him or he was stopped then you willed him up and now you want continue. It should easy work with start cp keybind or mini hud.

he was driving, he ran out of seeds, he stopped, I loaded the seeds, he does not continue the route.

**Comment by Pchel07** [comment]
> mini hud

mini hud, where is it?

**Comment by Tensuko** [comment]
Keybind must be set. Suggestion: del

**Comment by Tensuko** [comment]
I know what your problem is, when you set 1st waypoint, it will stay at 1st waypoint when use keybind.

**Comment by Pchel07** [comment]
not quite so, when he is standing, I go into the route, change to the nearest point and he either drives as he wants (for example, as in the screen, he went neither from the edge nor from the second lane, but from some point of his own) or starts from the starting point , although it is worth starting with the nearest

**Comment by Tensuko** [comment]
When I open the mini hud and I say start on the nearest point he starts where he is at the course.

**Comment by Pchel07** [comment]
I run, through the ESC menu to give work, in the route I change to start work from the starting point to the nearest point.

**Comment by Tensuko** [comment]
but where is your targetpoint set, if you start a job, he will always drive to the target that you have to set on the map!

**Comment by Pchel07** [comment]
I understood you, if the seeds ran out and he did not finish, then nothing can be done, just fill in and he will start from the beginning of the field.

**Comment by Tensuko** [comment]
No... thats wrong....
You just fill it up and then:
A) Use Mini hud, set to nearest and click on start.
B) if you rly want to do it on the map with start job, you have to set the target on the map to where your tractor is.

I can't explain you that any better, sry...

**Comment by Pchel07** [comment]
I tried to change the starting point in the approximate place where he stopped, it turns out badly, the tractor may go in the wrong direction, for example, not to the left, but to the right. in general, it turns out not as we would like.
