### ISSUE TITLE
Tasche beim Abtanken in der Bahn

### ISSUE THREAD

**Issue by Geradsralf** [Courseplay/Courseplay_FS22#433]
Hallo zusammen, ich kann mich vom LS19 daran erinnern, dass es bei der Ernte z.B. mit einem Drescher bei großen Feldern vorkam das mitten im Feld, links und rechts Frucht, abgetankt werden musste. Damals hat der Drescher die Situation erkannt, ist ein Stück rückwärts gefahren und hat sich eine Tasche gemäht, so dass das Fahrzeug zum Überladen auf abgeernteter Fläche stehen konnte.
Ähnlich bei Arbeitsweise rauf und runter, wenn das Rohr in Richtung der Frucht zeigte.
Ich kann aber nicht mehr sagen ob es CP oder AIVE war, womit diese Funktion erzeugt wurde. Ist dieses Verhalten zukünftig bei euch vorgesehen?

**Comment by Tensuko** [comment]
Das ist drin.

**Comment by Geradsralf** [comment]
Bedarf das einer bestimmten Aktivierung bzw. Deaktivierung? Habe gestern mit dem selbstfahrenden Grimme Kartoffelroder Feld 38 Elmcreek mit mehreren Vorgewenden und anschließend als Beete geerntet, da blieb der Roder mit 95% Füllung so stehen wie er gerade steht und machte weder Platz zur Frucht noch fuhr er eine Tasche.
Danke schon mal für eure Arbeit und die Unterstützung!

**Comment by Tensuko** [comment]
Diese Selbstfahrer machen halt generell noch Probleme.
Die werden irgendwie nicht als Combine gefahren. Siehe andere Issues. wie Panther oder Tiger.

**Comment by Geradsralf** [comment]
Okay, danke!
