### ISSUE TITLE
[BUG_SP] Renaming course only takes three characters

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#434]
**Steps to reproduce**
I do not seem to figure out how to reproduce this. It just happens and once it's happens, it will not go away.

**Actual behavior**
During playing, after generating courses, saving courses, the normal stuff you are doing with CP, Suddenly if you want to rename a course, the rename box only takes three characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/68871402/148646332-67f083f9-5bba-4791-812e-f777de6ef83e.png)

**Courseplay version**
Version used: v7.0.0.16

**Map**
Different maps, screenshot is taken from No Mans Land

**Comment by Tensuko** [comment]
Can't reproduce this. #200
When you figure out when and how to do this, let us know.
