### ISSUE TITLE
[Feature] Set current name in inputbox during renaming

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#435]
**What is the problem this feature/enhancement solves?**
When you have a typo in the name of your course, and you want to rename it, you have to type the whole name again

**Describe the solution you'd like**
After clicking rename (and selecting the course to rename), fill the inputbox with the old name, so you can change it.

After clicking rename, and then selecting the course to rename (1), the input box should be filled with the current name (2).
![image](https://user-images.githubusercontent.com/68871402/148646667-b321bfcd-2c0d-4d6c-b32a-616ec86a8e9b.png)

**Comment by Tensuko** [comment]
Sry taht won't work like we do it now, as it is not rly a simple 'rename'.
#299
