### ISSUE TITLE
Combine wait for straw discharged, before turning

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/Courseplay_FS22#437]
Right now on up/down rows, the turn begins before the straw swath is done, which makes the swath not straight.  When straw swath is enabled, I think it should finish unloading straw before it turns around.

**Comment by Tensuko** [comment]
So you talk about Combines I guess...

**Comment by enderwiggin07** [comment]
Oops yes, combines.

**Comment by ph1go** [comment]
On this note would it be possible to add an option to have the combine wait at the end of a row if it's unloading as it reaches the end of the row? So not "stop while unloading" but "stop at end of row if already unloading". It's something I've been meaning to bring up as a suggestion.

**Comment by Tensuko** [comment]
Since we don't have an official unloader yet, no, just wait until we are at that stage...

**Comment by Tensuko** [comment]
Should work fine now in 7.0.0.19
