### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Albatrozs112** [Courseplay/Courseplay_FS22#438]
Hello 
How to make course witH 3-4 tractors in one field seeding symmetrica?

**Comment by Tensuko** [comment]
Not implemented yet.

**Comment by Albatrozs112** [comment]
![20220108211851_1](https://user-images.githubusercontent.com/79331061/148656961-c9d7aab2-3bd8-473c-90c4-afa3d509ac5b.jpg)
But in setting is multiple tool
