### ISSUE TITLE
[BUG_SP] Combine won't stop at unloading

### ISSUE THREAD

**Issue by kennethraevdagmal** [Courseplay/Courseplay_FS22#439]
**Steps to reproduce**
While harvesting combine won't stop during unloading

**Actual behavior**
Combine stops wen full but starts drive when auto drive driver or my self  comes under the pipe

**Expected behavior**
Combine should stop during unload when chosen in options

**Screenshots**

**Courseplay version**
Version used: 
70016

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Several maps testet

**Vehicles/ implements involved**
Mod yes/no ?
Yes and in game, modded combine from modhud s690

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive

**Comment by Tensuko** [comment]
Can't reproduce, make sure you changed that setting on your combine.
![fsScreen_2022_01_08_17_28_47](https://user-images.githubusercontent.com/27344744/148651907-c63ad1b0-ea33-4df0-918c-42a71aa0bbaa.png)

**Comment by Tensuko** [comment]
It could also be that it works correct only with the next version.
