### ISSUE TITLE
Multiplayer Functionality 

### ISSUE THREAD

**Issue by Beedog743** [Courseplay/Courseplay_FS22#44]
Hello, just curious when to possibly expect multiplayer functionality? No rush of course just trying to see if it's even being thought about at this point in time

**Comment by Tensuko** [comment]
We have the 1st things implemented for MP and also first bug fixed, but it is not rdy yet.
When we are ready you will be noticed.

**Comment by SharcoonFarmer** [comment]
Does it work for dedicated server too??

**Comment by Beedog743** [comment]
> Does it work for dedicated server too??

Read the main page, still no multiplayer support yet unfortunately! Checking every day. Fingers crossed it comes soon
