### ISSUE TITLE
Courseplay nicht angezeigt?

### ISSUE THREAD

**Issue by TheWLU** [Courseplay/Courseplay_FS22#442]
Ich habe ein Problem bzw eine Frage: Ich habe zwar Courseplay installiert, es wird mir sogar angezeigt, wenn ich im Hauptmenü auf "Herunterladbare Inhalte" und anschließend auf "Installiert" klicke, aber sobald ich auf irgendeine Singleplayer-Welt gehe und versuche Courseplay als Mod auszuwählen, erscheint dieser Mod nicht. Natürlich könnte es auch mit Giants zusammenhängen, aber hat dieses Problem noch jemand und eventuell eine Lösung dafür? :)

**Comment by Tensuko** [comment]
logfile ?
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by TheWLU** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7833732/log.txt)
Das?

**Comment by Tensuko** [comment]
Kann nicht gehen:
Error: Invalid mod name 'FS22_Courseplay (7)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Du hast eine 7te Kopie im mdos Ordner.
Schmeiß mal alle .zip Dateien von CP raus, auch aus deinem download Ordner und lade neu runter:
https://github.com/Courseplay/Courseplay_FS22/releases
Dann kopierst du die in deinen mods Ordner.

**Comment by TheWLU** [comment]
Hat geklappt, vielen Dank für die schnelle Lösung =)
