### ISSUE TITLE
[Question] Getting straw of the field with loader wagon

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#443]
In FS19 we were able to get straw of a field with a loader wagon using CP. It his not implemented yet? Or will it not be available for FS22?
![2022-01-08 20_21_17-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148656995-b055c2f5-59cd-4e5a-b17b-bc043a51d99b.jpg)

**Comment by Tensuko** [comment]
#420
Why do I even create a sticky for this....

**Comment by JustDen1234** [comment]
Oh shoot, please forgive me. Very stupid of me.... 10000x sorry !!!

**Comment by Tensuko** [comment]
> Oh shoot, please forgive me. Very stupid of me.... 10000x sorry !!!

Relax buddy, I am not mad or anything but sometimes I wonder why we write all that informations :)
