### ISSUE TITLE
[Feature] Real Speed Limit Support

### ISSUE THREAD

**Issue by Satava** [Courseplay/Courseplay_FS22#444]
**What is the problem this feature/enhancement solves?**
When using the real speed limit mod Courseplay sets its speed to the same speed Giants sets for devices like vanilla gameplay. 

**Describe the solution you'd like**
A change in how speed is set, maybe using cruise control set to suggested working speed from the other mod, or just at whatever speed the player sets instead of calculating the working speed would solve this

**Describe alternatives you've considered**
There really isnt an alternative other than using in-game helpers instead of Courseplay.

Thanks for your time & wonderful mod, looking forward to harvesters cruising at warp speed if this gets implemented.

**Comment by Tensuko** [comment]
What is the real speed limit mod ?
What does it do ?

**Comment by Satava** [comment]
Real Speed Limit removes the imposed working limits on attachments and lets you go as fast as your horsepower will let you go.

From their mod description:
(https://mod-network.com/fs22-mods/detail/2312)
Real Speed Limit gives players the ability to disable the speed limit given to tools so they can use the cruise control speed instead.
Each vehicle can have the limit disabled individually.
By default the limit remains active.
Useful for large fields.
Horsepower and mass will still limit top speed.
Default Key: Left Alt + 0

**Comment by Tensuko** [comment]
Wont support this. Try increase fieldspeed in settings.
