### ISSUE TITLE
[BUG_SP] Turning radius too small causing helper stalling

### ISSUE THREAD

**Issue by AyakawaSakura** [Courseplay/Courseplay_FS22#446]
**Steps to reproduce**
Helper cannot turn because the pathfinder generates a course with small turn radius. I have set the turning circle radius to 10 meters in vehicle setting but it seems that it is not working.

**Actual behavior**
Some tractors with wide tools have difficulty to turn 

**Expected behavior**
Helper turns correctly.

**Screenshots**

https://youtu.be/LBCoTHKlkDY
**Courseplay version**
Version used:  7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7834329/log.txt)

**Map**
elmcreek

**Vehicles/ implements involved**
Fendt 1167 MT (large tractor)
Kompaktomat 1570 MAX (shallow cultivator)

**Relevant script mods**
Null

**Comment by Tensuko** [comment]
Duplicate. Turn Radius not active yet.
