### ISSUE TITLE
[Feature] Add an ability to change and save default value for "Where to start field work".

### ISSUE THREAD

**Issue by Himiriel** [Courseplay/Courseplay_FS22#447]
**What is the problem this feature/enhancement solves?**
At the moment I find "nearest waypoint" value to be more useful because:
1. It's difficult for Courseplay (well, and for AutoDrive as well) to drive to a proper waypoint through all the stuff I parked at random places close to a field, so I have to drive vehicles to a start point manually anyway. On top of that, Courseplay sometimes generates rounded headland turns even when "Headland corners: sharp" is selected, so I manually generate starting point near that rounded turn and manually start the job and then I press a hotkey to continue with CP.
2. AutoDrive creates a lot of collisions between a tracktor with a trailer and a harvester on a field so I have to solve them and then to continue the job manually by clicking a hotkey.

**Describe the solution you'd like**
I would like to change and save a default value for "Where to start field work" in settings.

**Describe alternatives you've considered**
Currently I reverted a0257f0b81d3efc404e7a6b80efe2f1545842e2c for myself.

**Comment by Tensuko** [comment]
Will see later, for the use of job start, 1st wp as default make more sence and other user agreed.

**Comment by Tensuko** [comment]
You drive the tools by yourself to the field, is it ? When you open mini hud and start on 1st wp, why it does not work for you ?

**Comment by Himiriel** [comment]
It's because I don't use mini HUD, but I like this idea, should work for me. Thanks. =)

**Comment by Tensuko** [comment]
Close for now then.
We think about own defaultsettings later.
