### ISSUE TITLE
Abfahren findet keinen Weg vom Feld

### ISSUE THREAD

**Issue by daserthomas** [Courseplay/Courseplay_FS22#448]
**Steps to reproduce**
Häckseln mit verschiedenen Abfahren.
Der Abfahrer kann keinen Pfad vom Feld runter berechnen berechnen.

**Actual behavior**
Nachdem der Anhänger voll ist kommt die Meldung "Der Fahrer von 1050 konnte keinen Pfad zum Ziel berechnen" und der Abfahrer bleibt stehen

**Expected behavior**
Der Abfahrer sollte das Feld verlassen und zum abladen im Keilsilo fahren

**Screenshots**

**Courseplay version**
7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7834672/log.txt)

**Map**
Standart Elmcreek

**Vehicles/ implements involved**
kein Mod. Standart 1050 und Fendt Katana

**Relevant script mods**
AD, CP, und VCA an

**Comment by Goofy78** [comment]
Da solltest dich an die Jungs vom AD-Team wenden.

**Comment by RealNeo80** [comment]
@daserthomas liegt meistens dran dass Streckenpunkte nicht sauber verbunden sind, Fahr die Strecke mal ab, ansonsten bitte [hier](https://github.com/Stephan-S/FS22_AutoDrive/issues) posten

**Comment by Tensuko** [comment]
AD Problem und nicht CP...
