### ISSUE TITLE
[BUG_SP] Text overlay when active CP driver moves backwards

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#449]
**Steps to reproduce**
Using CP on a field course with sharp edges. If vehicle drives backwards on edges, the text appears. 

**Actual behavior**
Text is displayed in the middle of the screen, nevertheless in which vehicle I am.  Text flickers fast.
Text is like this: xte=0.0 oe=0.2 ce=0.0 current=-0.2 reference=1.4 correction=-1.5 (also in log)

**Expected behavior**
No text. Have not seen this on preview CP versions. 
Hopefully I had no missed a switch to turn it of .

**Screenshots**
![fsScreen_2022_01_08_18_28_18](https://user-images.githubusercontent.com/96873819/148677835-8f4c7489-a11b-460c-b613-774f5601c1ab.jpg)

**Courseplay version**
Version used:  7.0.0.16

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log - Kopie (3).txt](https://github.com/Courseplay/Courseplay_FS22/files/7834828/log.-.Kopie.3.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Seenat several vehicles at field work. i.e.  Dalbo 1230 roll.

**Relevant script mods**
AD active (but appears also if inactive)

**Comment by Tensuko** [comment]
Fixed on next release.

**Comment by RealNeo80** [comment]
![image](https://user-images.githubusercontent.com/8066324/149390125-2da49af2-515d-4423-a143-ca293b44bbf2.png)
@Tensuko i have it again in 7.0.0.1
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7865218/log.txt)
