### ISSUE TITLE
Suggestion: option to generate course inside field boundries (to create new fields)(add island bypass options)

### ISSUE THREAD

**Issue by kroddn** [Courseplay/Courseplay_FS22#45]
I am currently playing on No Mans Land... and there are no fields, as the majority should know.

I would like to generate field courses just by the outlines of a field. I think that worked in CP19.

E.G.
- Use a plow to drive around a field you want to create
- Use the course generator with a new option "create field mode". Courseplay then should use the current field as the outer boundry for its course generation.

See screenshot
<img width="960" alt="Farming Simulator 22 Screenshot 2021 12 24 - 22 19 52 58" src="https://user-images.githubusercontent.com/63540443/147372507-db9896c1-6d90-4e09-b1f2-7d17194ce96e.png">
.

**Comment by Tensuko** [comment]
Good Idea, we will see what we can do about this.

**Comment by Redster999** [comment]
I can add... I also did this in no mans land. And it worked fine for a while. Then made a big field (oval shaped) Generator made the headlands and 8-10 lines (up and down) in the middle. Was missing lines of both sides of the midpoint. But I never checked if it could run all the course. Chrismas eve came in the way. ;)

**Comment by Tensuko** [comment]
It would be interesting if you make the field border bigger by yourself, like a 2nd or 4rd round.
I wonder if the island bypass setting is hitting here or the fieldscanner...

**Comment by kroddn** [comment]
I can test again Sunday evening. Is there a setting to ignore islands?

I guess the fieldscanner works properly, as you can see on the course on the screenshot. It Covers the whole "field".

Doing 4 rows might result in the field beeing completed though ;-)

**Comment by fudoido** [comment]
cp6 did had an option to select the "outline course" to generate a fielwork course within that outline, hopefully that can be added soon to cp7.
the option to turn on/off field creation is a good idea, considering most ploughs are very small in size and takes forever to create a field manually, CP would be very handy for that..... and i know there is a mod to make cultivators create fields also, but not so realistic for some people and they avoid using that mod im sure.

**Comment by rohne83** [comment]
not only for this. Also for having CP work on the grass areas around the fields (especially the standard maps have plenty of these) it would be very helpful again to create those custom field edge paths and have CP working only inside these.

**Comment by Tensuko** [comment]
@rohne83 try it on Alpine Map.
I simply placed the target at a Gras Field area in the Mountains and got my Course.
Not sure if that fits your needs for now. Sure we will check custom Fieldborders for later.

**Comment by kroddn** [comment]
I tested again with 2 x 9m Headleand. Still the same issue: 

![20211226182428_1](https://user-images.githubusercontent.com/63540443/147415675-dca7c83c-d454-4f36-9b7f-b20e23695236.jpg)

@Tensuko your suggestion works with existings fields of course. But i just created that field that did not exist before.

**Comment by pvaiko** [comment]
@kroddn just to clarify, what you created there is a field with a huge island in the middle, at least from the field scanner/course generator perspective. Turning off island bypass may help. We'll add that setting back, I never thought there'd be a use case for turning island bypass off, but here we go.

**Comment by pvaiko** [comment]
746e94e0 added the island bypass settings.

**Comment by kroddn** [comment]
YEAH!
