### ISSUE TITLE
[Feature] An letzter Position fortsetzen

### ISSUE THREAD

**Issue by Obsiana2019** [Courseplay/Courseplay_FS22#451]
**What is the problem this feature/enhancement solves?**

Derzeit stoppt CP wenn z.B. Dünger alle ist.

**Describe the solution you'd like**

Interessant wäre nachdem man manuell oder mit AD z.B. Dünger aufgefüllt und zum Feld zurückgefahren ist noch eine Funktion hätte "Start on last Position" also Starte an letzter Position. Also eine halb Automatische Funktion. Solange AD und CP noch nicht zusammen arbeiten. Ich kann z.B. teilweise ganz schlecht sehen wo ich zuletzt gedüngt habe das wäre eine echte Erleichterung.

lg Obsi

**Comment by DHempelmann** [comment]
In der LS19-Version konnte man an den Punkten über dem Feld auch sehen, an welcher Stelle er gerade ist. Vielleicht könnte man die Linien, die er bereits abgefahren hat, in einer anderen Farbe färben. Gerade bei Abbrüchen auf Kursen mit "Reihen überspringen", hätte man dann eine Chance, die richtige Position wieder zu treffen.

**Comment by Tensuko** [comment]
Letzter Wegpunkt ist mit der .20 rein gekommen.
Bitte probiere ob es probleme damit gibt, in unseren tests hat es sehr gut funktioniert. (auch nach game restart).
