### ISSUE TITLE
Fortsetzung einer Feldarbeit nach einem Stop[Question]

### ISSUE THREAD

**Issue by Ralf254** [Courseplay/Courseplay_FS22#454]
Bisher konnte ich eine unterbrochene Feldarbeit mit CTRL-H an der gleichen Stelle fortsetzen. Mit dem Release ....17 fährt das Gerät nach Eingabe von CTRL-H zum Startpunkt und beginnt dort die Arbeit, d.h. alle vorherige Arbeit wird noch einmal durchgeführt. In den Tastaturbelegungen habe ich keine Taste für die Fortsetzung der Arbeit an der gleichen Stelle gefunden.

**Comment by Tensuko** [comment]
Im mini Hud umstellen.
