### ISSUE TITLE
Häcksler und Gras Silage[Question]

### ISSUE THREAD

**Issue by Headcrank** [Courseplay/Courseplay_FS22#456]
Kurze frage bei der Version 7.0.0.12 funktionierte das aufsammeln der Grasschwade noch mit dem Häcksler und machte einen problemlosen Job nach heutigem update auf die aktuelle Version 7.0.0.17 funktionierte diese jedoch nicht mehr.

Haben andere dieses Problem auch noch oder hab ich da irgendeine Einstellung falsch? 

LG

**Comment by Tensuko** [comment]
Also Häcksler mit PickUp ?

**Comment by Headcrank** [comment]
Bin mir nicht sicher was mit Pickup gemeint ist.
Ich wollte die Wiese mit dem Häcksler in den Anhänger von dem Tracktor laden und das ging mit der neuen Version nicht mehr.

**Comment by Tensuko** [comment]
Das ist das Geräte was du an einem Häcksler vorne dran hängst um eine Schwad auf zu nehmen.

**Comment by Headcrank** [comment]
Ja genau das hab ich dran und damit lässt Sich die Schwade nicht aufnehmen und ich den Hänger werfen.

**Comment by Headcrank** [comment]
Was ist gemeint mit dem helfer menü ? 
Über die Reiter im hub lässt sich der Kurs für den Häcksler ja nur laden, aber wenn ich mich recht erinnere nicht starten.
gibt da eine tasten kombi wie ich evtl. ein kleines hub öffnen kann wo ich den dann starten kann ?

**Comment by Space-Farmer** [comment]
Gesammelt/gehäckselt habe ich mit einem Jagur 960 mit Claas Pickup.
Mit Helfermenü meine ich den 2 . Punkt von oben wenn man [ESC] drückt.
![image](https://user-images.githubusercontent.com/48656375/148923932-d3b4628d-24bc-42a1-a6c5-a5337952748e.png)
Das kannst du hier:
![image](https://user-images.githubusercontent.com/48656375/148924116-e3e0b92a-e38a-4644-bf0a-28099f0774f3.png)
festlegen. Aber es ist anders wie im LS19 :-)

**Comment by Tensuko** [comment]
Ihr wisst schon, dass wir nicht umsonst eine Changelog schreiben, oder ?
H -> normaler Helfer
Neuer keybind -> CP (nutze z.B. ctrl + H)
Startpunkt für CP -> Mini Hud (vehicle settings dispaly) vlt sollten wir einen besseren Namen finden, aber ess funktioniert alles!

**Comment by Space-Farmer** [comment]
Ja, ist gelesen. 
Ist bei mir auch als [STRG]+[H] eingebunden.
Nur das Default "erster Wegpunkt" auch für o.g. Tastenkombination wirkt war mir trotz studiums des Changelogs nicht bewusst.
Dachte das es nur als default im "Helfer Menü" eingestellt ist.
Das HUD habe ich nur 1x im LS22 genutzt, da es sich nicht von dem "Helfer Menü" unterschieden hat, jedoch wieder verworfen.

Sorry das ich hier mehr Verwirrung gestiftet habe wie geholfen.

**Comment by Tensuko** [comment]
Ja das ist default überall, aber mal schauen ob man das getrennt bekommt irgendwie.

**Comment by Headcrank** [comment]
Danke für eure hilfe :-) habs jetzt auch raus Dankeschön

**Comment by Tensuko** [comment]
Geht mit Häcksler, also sollte kein Problem mehr sein.
