### ISSUE TITLE
[Combine drives off the course]

### ISSUE THREAD

**Issue by Niclas00-hub** [Courseplay/Courseplay_FS22#457]
**Actual behavior**
Combine drives off the track 

**Screenshots**
![20220109173136_1](https://user-images.githubusercontent.com/40001530/148691875-b5885215-3356-4db6-be12-3a39a38eb35e.jpg)

**Courseplay version**
Version used: v7.0.0.17

**Map**
Erlengrat

**Vehicles/ implements involved**
no mod Vehicles used 

**Relevant script mods**
Autodrive and VCA

**Comment by Tensuko** [comment]
Where is the logfile with debugchannel active ?
I am sure you did not start CP Driver or have set an offset.....

**Comment by wtfgh40** [comment]
![20220109191817_1](https://user-images.githubusercontent.com/40001530/148695621-78f7defd-3590-4844-a06a-e4534e98dcc0.jpg)
![20220109193013_1](https://user-images.githubusercontent.com/40001530/148695624-30a9f7c1-e9eb-436f-ada8-eeb435742f48.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7835662/log.txt)

**Comment by pvaiko** [comment]
Disable AIVE and try again, reopen if it does not work.
