### ISSUE TITLE
[BUG_SP] Fieldwork done, waiting to be unloaded. But pipe not out.

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#459]
Created new race course with v7.0.0.17 on two fields.
On both fields at the end the combine stops, but does not open the pipe to be unloaded.
The log file below is of one course only (closed FS22, removed log.txt, and started it again).

![2022-01-09 17_53_28-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148692781-ba4295d9-485f-4e71-93d6-98a624d81291.jpg)

Version used: v7.0.0.17
Map: No Mans Land
Combine: Rostselmash Nova 330
Installed mods: AutoDrive, AIVE 
Log: [here](https://gist.github.com/JustDen1234/133546b44fe790ce63fc8c20bb44ed5a)

**Comment by Tensuko** [comment]
Setting 'pipe always unfold' active ?

**Comment by JustDen1234** [comment]
Actually I had this on deactivated. WIth the previous versions of CP it worked with this to deactivated. Was this setting nog implemented? Will try this.

**Comment by Tensuko** [comment]
It should only open the pipe when that setting is activated or you drive close to combine.

**Comment by JustDen1234** [comment]
Turned on 'pipe always unfold', and the pipe unfolds at the end of the track, but it doesn't call AutoDrive. Or is this an AutoDrive issue?

Combine still running, pipe is unfold.
![2022-01-10 20_12_24-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148825392-c3aa63ce-cc13-40c8-93f9-ae8a7768f544.jpg)

Tractor keeps 'Waiting for call'.
![2022-01-10 20_12_04-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148825416-dd1ea1dd-f5fc-4242-8bb2-f4f210fc779d.jpg)

CP: v7.0.0.17
AD: v2.0.0.3

**Comment by Tensuko** [comment]
There is no active call yet.
If it does not work, it will not work.
Wait untill we implement that correct.
