### ISSUE TITLE
Hiring Courseplay AI worker by pressing the H key outside of the field makes future H key presses call default AI worker

### ISSUE THREAD

**Issue by tigranhov** [Courseplay/Courseplay_FS22#46]
After creating and starting the Courseplay route, stop the process by pressing the H key. If you try to press H, it resumes Courseplay from the nearby point. If you go outside the field and press H, it says that there is no field, but after returning to the field subsequent attempts, even when on the field, hire the default worker, while the tooltip still shows Hire AI Worker(CP).
Courseplay Version: 7.0.0.3

**Comment by Tensuko** [comment]
> If you try to press H, it resumes Courseplay from the nearby point.

That is correct and intended for now.

> If you go outside the field and press H, it says that there is no field

Thats an information from Giants System.

So, when you started the CP Helper outside of the Field with H once (msg comes up) and try to go back on the Field it will start the normal Giants Helpfer ?

**Comment by tigranhov** [comment]
> So, when you started the CP Helper outside of the Field with H once (msg comes up) and try to go back on the Field it will start the normal Giants Helpfer ?

Yes

**Comment by Tensuko** [comment]
Ok. Thanks for your Feedback.
Right now we overwrite the normale Helpfer with CP Helpfer, if the Job was a CP:Fieldwork once.
Seems like this gets resetted, if we could not start the course.
We try to find a solution for this.

**Comment by kroddn** [comment]
I can confirm this one. Should be rated as a Bug, not an enhancement.

It seems that this behavior breaks the Workers for the whole session. I was not able to convince any vehicle any more to start a courseplay job, it always falls back to the standard worker.

**Comment by Tensuko** [comment]
> I can confirm this one. Should be rated as a Bug, not an enhancement.
> 
> It seems that this behavior breaks the Workers for the whole session. I was not able to convince any vehicle any more to start a courseplay job, it always falls back to the standard worker.

Even if you start one over the AI Menu ?
Well we have Plans to make it more controllable, but yea I add the bug lable as well.

**Comment by dete96** [comment]
I also had the problems mentioned above. But when I (re)started the CP from the menu, it started to work again.

**Comment by Tensuko** [comment]
> I also had the problems mentioned above. But when I (re)started the CP helper from the menu, it started to work again.

That is basically how it was implemented.
Start CP as Job once, then H will use CP.
We also have Plans with Keybind.
To always start the CP Worker, you can use the Mini-Hud (need to set the keybind). #190
