### ISSUE TITLE
[Question] Change "Set start job on first waypoint as default" back to closed waypoint.

### ISSUE THREAD

**Issue by nlcoredump** [Courseplay/Courseplay_FS22#460]
Hi,

Could you change this back to closed waypoint.   Now if you want to continue a track mid-field and use the key-binding to start, it will drive to the start of the course not the point where you are at.  Or maybe make it configurable.  I only start once at the beginning, but most of the time i will restart somewhere down the track.  This change makes that very annoying having to go into the menu and start from there with closed waypoint.

**Comment by Tensuko** [comment]
Will not do. But we see if we can seperate that.
Becouse whenever you start cp it with start job you can forget to change it to 1st waypoint.
Also it should stay on nearest I think when you change it once it the mini hud.
