### ISSUE TITLE
[BUG_SP] CP stops during turn, and goes it's own way

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#461]
Created new race course with v7.0.0.17 on field.
The first turn is okay, but during the second turn, CP is completely lost.
During the turn all looks fine, but around the middel of the turn, the tractor stops in the turn, and goes somewhere.

![2022-01-09 19_45_15-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696421-1ca36dde-cf28-4994-930b-78df676622af.jpg)

![2022-01-09 19_45_22-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696424-3abbf2d5-04c6-4722-be1c-a9ee46683da1.jpg)

![2022-01-09 19_45_28-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696430-e1fb9ef2-bf15-4a54-982f-65a51c1dc8ef.jpg)

![2022-01-09 19_45_39-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696441-4a978b6e-2857-4093-96ed-3d58327d5d11.jpg)

I've tried it twice, in the images you already see the 'wrong' path of the first run.

Version used: v7.0.0.17
Map: No Mans Land
Tracktor: Streyr 8150
Cultivator: Rabe EG 3/9
Installed mods: AutoDrive, AIVE 
Log: [here](https://gist.github.com/JustDen1234/56ccd4908634b6516bfdd1a631f35785)

**Comment by JustDen1234** [comment]
Continued the track, this happens on the next turn:

![2022-01-09 19_57_43-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696655-46f65095-82af-42d5-8d3c-f5dd1b8a3387.jpg)

Seems at point 17 here, the tractor is stopping using the track, and goes straight forwards:

![2022-01-09 20_00_34-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148696707-1934e01f-38e8-4db5-819b-b84f23e10430.jpg)

**Comment by pvaiko** [comment]
Is this log from the same time when you made those screenshots?

**Comment by JustDen1234** [comment]
@pvaiko The logfile is from the first post, and it should contain both tries I mentioned in the bugreport.

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.18
Reopen if Issue persists.

**Comment by JustDen1234** [comment]
@Tensuko does this reopen the ticket? I'm not sure....

**Comment by JustDen1234** [comment]
@pvaiko Should I open another issue ?

**Comment by pvaiko** [comment]
Yes please. Please also add what your avoid fruit and turn on field settings are. I've seen this before but can't explain.

**Comment by pvaiko** [comment]
@JustDen1234 or test it with that last push before you do...

**Comment by JustDen1234** [comment]
Looks like it works with v7.0.0.19. 
Thanx for the good work !!!
