### ISSUE TITLE
[Question] CP Aufgabe erledigt -> Benachrichtigung ?

### ISSUE THREAD

**Issue by BigBlackBahamut** [Courseplay/Courseplay_FS22#462]
Hi, ich weiß nicht ob ich zu Blöd bin oder ob es einfach nicht bei CP vorhanden ist. Aber ich bekomme keine Benachrichtigung wenn CP mit einer Aufgabe fertig ist.

LG

**Comment by Tensuko** [comment]
Das ist die normale Helfer Benachrichtigung oben rechts wie auch vom Giants Helfer.
Eine eigene Benachrichtigungsliste ist geplant, wird aber erst später umgesetzt.
