### ISSUE TITLE
[BUG_SP] Problem mit Karat 12/500 KUA

### ISSUE THREAD

**Issue by Zwox89** [Courseplay/Courseplay_FS22#463]
Es gibt ein Problem mit dem Grubber: Karat 12/500 KUA. Man sieht es relativ gut in dem Video. Der hintere teil ist kein grubber aber wird als solches erkannt.

**Screenshots**

https://user-images.githubusercontent.com/96999699/148699829-5ec49ba0-ca91-4213-b352-8a1918d267c3.mp4

**Courseplay version**
Version used: v7.0.0.17

**Log**
https://pastebin.com/un54hkjS

**Map**
US

**Vehicles/ implements involved**
Mod no

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Tool absenken auf früh stellen.
