### ISSUE TITLE
[BUG_SP] Menu scroll bar on Vehicel Settings does not work

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#465]
The scrollbar on the 'Vehicle Setting page', does not work. It does not move when moving down, and the page does not move down when you move the scrolbar.

In the screenshot I'm at the bottom of the page, but the scrollbar is at the top.
![2022-01-09 23_28_45-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/148703753-63017a9d-c0f2-43c9-b473-07852f7849b2.jpg)

Version used: v7.0.0.17
Map: No Mans Land

**Comment by Tensuko** [comment]
Duplicate
