### ISSUE TITLE
[BUG_SP] Strg+H always starts the course at the beginning

### ISSUE THREAD

**Issue by mxalbert** [Courseplay/Courseplay_FS22#467]
**Steps to reproduce**
If a helper is stopped on course Strg+H doesn't start from nearest waypoint as before 17, it now always starts at first waypoint.

**Expected behavior**
The player should be able to make the helper start at the next waypoint, at least if it was set on job creation from helper screen.

**Courseplay version**
Version used: 7.0.0.17

**Comment by Tensuko** [comment]
Change it on mini hud
