### ISSUE TITLE
[Question] Course Generation

### ISSUE THREAD

**Issue by ve3jec** [Courseplay/Courseplay_FS22#468]
When i attempt to get a proper course generated all i can ever achieve is an angled mess 
![angled](https://user-images.githubusercontent.com/62829454/148734781-1159e092-8914-4ff9-b3e4-558817a0850f.png)

I have spent hours (when added up) regenerating courses trying to get a straight one like it should be.  messing with widths and settings to get one like this
![straight](https://user-images.githubusercontent.com/62829454/148735131-979e1a71-32c2-46a7-88e9-7940f69c471f.png)

That one was an accident, i missed setting the width from 3m to 10m i was so excited i saved it before i realized i was 3m 

For me its been like this from 7.0.0.0 through 7.0.017 

That straight one was generated with "row direction - Longest edge" i think that is the only time that setting has ever given me a course its always fails sometimes fast, sometimes it takes 30-60 seconds to fail. 

We used to have a setting  that would let you manually select the direction  in degrees like 0, 45, 90 and so on. I can't find it now though please tell me it didn't get ditched like the HUD

I can not impress upon you how much the current way sucks in comparison to the HUD. I know the HUD is dead sadly, and can only hope the mini hud that was mentioned fills the gap. 

So what is the proper way to get a course generated that is right, like the second picture?

**Comment by Tensuko** [comment]
You can only try things out.
Less Headland (maybe 2 is enough?) one more less skip rows.
Longest edge can help and ofc another start location.
They question is if the course on your 1st pic does not work ?

**Comment by ve3jec** [comment]
I've danced all over that field trying to get rows setup right. changing directions, widths, headlands, skips all the settings, if its not a square field its like hens teeth to get it setup right. 6.5 has the Manual direction setting and it fixes this right off. 

The course in the first pic "works" but just because it works doesn't mean its right. 
(in game) Angled rows can cause issues with equipment that follows, be it they can't make the turn in the sharp angles and spend time bound up and clawing (missing min turn circle settings) trying to pull around.  

(real life) Second I have yet to see or work a real life field (Ontario Canada) where that angle would ever be present its just not efficient and hard on drivelines for equipment like balers.  You might do an angle once in a few years doing tillage to cover ruts but its not to common.

**Comment by Tensuko** [comment]
This is already requested: #139

Will have to wait then.
