### ISSUE TITLE
[BUG_SP] Default "Go To" Job not working with Courseplay active

### ISSUE THREAD

**Issue by AdrianM20** [Courseplay/Courseplay_FS22#469]
**Steps to reproduce**
Activate CoursePlay mod when loading the save.
Enter a vehicle, attach a tool or trailer.
Set a destination.

**Actual behavior**
The worker activates and stays still in the place it was at the moment of "start job".
It consumes your money but it does not move towards destination.

**Expected behavior**
The worker should drive to the destination.
(If you deactivate CoursePlay from savegame loading, the problem goes away)

**Screenshots**

**Courseplay version**
Version used: 7.0.0.16

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Mod yes and no. It does not matter what vehicles and tools you use

**Relevant script mods**
VCA present but not active

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki

"1. Always update to the latest build and check if the problem really still exists before reporting issues."

https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by Tensuko** [comment]
Wasn't able to reproduce this, I could easy send a driver to another position.
Even when the driver was working before.
Tested with 7.0.0.18
