### ISSUE TITLE
Field work error

### ISSUE THREAD

**Issue by Drajo123** [Courseplay/Courseplay_FS22#47]
Hellou, Cuting grass with Big M 450, after finishing head lands it needs to start working on up/down rows, but its yust runing in circles at begining up/down rows, and its droped fps to 3-5fp
![20211224220901_1](https://user-images.githubusercontent.com/96635586/147372597-ac819a1c-e9f3-427a-a151-ef76a602c6fb.jpg)
![20211224220904_1](https://user-images.githubusercontent.com/96635586/147372609-74506b79-0146-4e24-bcfe-6b1818b90fe2.jpg)
s

**Comment by Tensuko** [comment]
What version did you use ? Logfile ?

Will have to check that ofc.

**Comment by Drajo123** [comment]
version v7.0.0.2
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7775172/log.txt)

**Comment by pvaiko** [comment]
upgrade to 7.0.0.3 and try again

**Comment by Drajo123** [comment]
with the old course it spins in a circle also in version 7.0.0.3, if I make a new course then it works normally. Here's the faulty course
[Gras Field.zip](https://github.com/Courseplay/Courseplay_FS22/files/7775218/Gras.Field.zip)
.

**Comment by pvaiko** [comment]
Low priority as it seems to work now, closing.
