### ISSUE TITLE
Courseplay berechnet nicht Arbeitsbreite

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#470]
Guten Morgen,
Wollte kurz mitteilen, dass Courseplay nicht die Arbeitsbreite automatisch berechnet.
Gruß Stefan

**Comment by Tensuko** [comment]
Setzen 6.
https://github.com/Courseplay/Courseplay_FS22/wiki
Doch macht CP, welche Version hast du welches Tool usw....

**Comment by StefanTreutler1974** [comment]
Die neuste Version vom CP.Als Tool hatte ich den Bredal Düngerstreuer.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.01.22, 12:56 schrieb Tensuko ***@***.***>:

   
  Setzen 6. https://github.com/Courseplay/Courseplay_FS22/wiki Doch macht CP, welche Version hast du welches Tool usw....

**Comment by Tensuko** [comment]
Bredal 18m für Kalk und 30m für Dünger, neu ankuppeln wenn was geladen.

**Comment by StefanTreutler1974** [comment]
Danke für den Tipp. Ihr macht wirklich gute Arbeit am Courseplay. Freue mich wenn es auch bald mit dem Ladewagen für Stroh usw. funktionieren wird.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.01.22, 16:08 schrieb Tensuko ***@***.***>:

   
  Bredal 18m für Kalk und 30m für Dünger, neu ankuppeln wenn was geladen.
