### ISSUE TITLE
[BUG_SP] John Deere 8R fieldwork not working

### ISSUE THREAD

**Issue by Yasp0** [Courseplay/Courseplay_FS22#471]
**Steps to reproduce**
Use the John Deere 8R and a tool like the mulcher Speedmax 560.

**Actual behavior**
When you start the CP job, it immediately says 'Done with the job'.

**Expected behavior**
The CP worker should start mulching.

**Screenshots**
![cp-john-deere-8r](https://user-images.githubusercontent.com/5689226/148791461-b7433ff4-f11a-4e72-a8c0-f57c2df6bc13.jpg)

**Courseplay version**
Version used: 7.0.0.17

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7839862/log.txt)

**Map**
Elmscreek

**Vehicles/ implements involved**
No modded vehicle and tool.

**Comment by Tensuko** [comment]
This is not a complete logfile.

**Comment by RealNeo80** [comment]
wieso geht der Kurs eigentlich über beide Felder?

**Comment by Yasp0** [comment]
Sorry, I found out it was caused by the mod 'AI vehicle extension'. I deleted this mod and it is working fine now. 

@RealNeo80 the course is over one field, because of the camera angle it looks like it's over two fields :p

**Comment by Tensuko** [comment]
But it should be no problem when you start the driver with the mini hud or the CP start hotkey.
You should be able to use AIVE as well.
