### ISSUE TITLE
Start am ersten Wegpunkt

### ISSUE THREAD

**Issue by Maverick-0815** [Courseplay/Courseplay_FS22#473]
Beschreibung:
In der 7.0.0.17 startet CP nach Unterbrechung und Fortsetzung mit "H" immer am ersten Wegpunkt, bzw. versucht irgendeinen scheinbar undefinierten Wegpunkt zu finden, auch wenn bei der Generierung des Kurses "Start am: nahester Wegpunkt" ausgewählt wurde.

Version: 
7.0.0.17

Wenn man dann das Mini-HUD öffnet, dann steht da auch tatsächlich noch "Erster Wegpunkt". Wenn man das dann auf "nahester Wegpunkt" ändert und mit "H" den Helfer neu startet, dann setzt er, wie zu erwarten am nahesten Wegpunkt den Kurs fort.

**Comment by Tensuko** [comment]
Hast dir selber die Antwort gegeben.
Und es gibt ein extra keybind für CP starten.

**Comment by Maverick-0815** [comment]
Wozu kann man dann bei der Kursgenerierung "nahester Wegpunkt" auswählen, wenn das scheinbar nur für den ersten Start gilt, aber danach "erster Wegpunkt" gesetzt, obwohl es nach dem Start keinen Sinn mehr macht, dass der Helfer nochmal am ersten Start beginnt?

**Comment by Tensuko** [comment]
nahester Wegpunkt im Job Menü hat rein gar nichts mit dem Kursgenerator zu tun, sondern damit wo CP starten soll, wenn er am gewählten Zielunkt angekommen ist.
Natürlich kannst du den auch mitten auf das Feld schicken wenn du weist ab wo er arbeiten soll und dann ab nahesten Wegpunkte starten. Das hat schon seinen Sinn.
Vom System wird gar nicht gesetzt.
Defaul Setting ist erster Wegpunkt, was du dann danach einstellst ist deine Sache.

**Comment by Maverick-0815** [comment]
Jetzt hab ichs kapiert. Das ist tatsächlich kein bug, sondern ein feature.
Ich hatte mich schon dermaßen an den CP-Helfer gewöhnt, dass ich mich erst wieder an den erneuten "neuen" Kursstart über das Mini-HUD gewöhnen muss ;-)

Vielen Dank für eure Arbeit. Als CP-Fan freue ich mich auf die nächsten Releases....

**Comment by Mike1977** [comment]
wie öffnet man denn das Mini Hud? Bei mir gibts in den Keybindings keinen solchen Eintrag...

**Comment by Maverick-0815** [comment]
In den game-settings kannst du dir Tastaturkürzel definieren (siehe Bild).
Bei mir war noch KEIN Kürzel für den Aufruf des "vehicle setting display" definiert.
Definiere dir da einfach eine Tastenkombination.
![courseplay_settings_display](https://user-images.githubusercontent.com/55902077/148873003-a26706df-53b4-4bbf-a71b-c40db999ae3b.jpg)

Wenn dann das kleine Menu aufgeht, dann kannst du dir "Nahesten Wegpunkt" als Startpunkt definieren und den Helfer gleich mit "Return" los schicken.
![vehicle_setting_display](https://user-images.githubusercontent.com/55902077/148874232-caa11df5-cdbd-430c-93e2-9b9738065136.jpg)

Falls du dann den "Nahesten Wegpunkt" definiert hast, dann musst du nicht nochmal extra in das setting-menu, sondern kannst dir auch ein Tastaturkürzel für "start/stop driver" (siehe oben) definieren (am besten nicht "H" ;-) ) und dann kannst du beim nächsten Start nach einem Zwischenstop die Sache abkürzen...

**Comment by Maverick-0815** [comment]
Oh Mann, jetzt muss ich mich fast entschuldigen, dass ich den thread überhaupt aufgemacht habe...
Ihr ward so schnell, dass ich direkt von der 7.0.0.12 auf die 7.0.0.17 umgestiegen bin und gar nichts von der Umstellung bei der 7.0.0.16 mitbekommen habe...

Da wäre es aber explizit dabei gestanden.

Wer lesen kann ist klar im Vorteil.

Nix für ungut.


![courseplay_keybinding](https://user-images.githubusercontent.com/55902077/148911797-af612e86-291a-493f-b14d-a60a1574b728.jpg)
