### ISSUE TITLE
[BUG_SP] After stopping worker, cant start CP worker again from closest course point

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/Courseplay_FS22#475]
**Steps to reproduce**
Create course, start course from first point.  Stop worker manually. 

**Actual behavior**
After stopping worker, cant start CP worker again from closest course point. After restarting the worker, it makes a full circle, starting work from the first point. I tried change to option  "start from the closest point" but still does the same. To Start worker from closest point, i need to create course again and set start point to "the closest point" and then  it works. But it works just fine in previous version of CP. 

**Courseplay version**
Version used: 7.0.0.17

**Relevant script mods**
Autodrive

**Comment by RealNeo80** [comment]
change in the mini HUD

**Comment by gruszon18** [comment]
> change in the mini HUD

Yeah.. That will do. Language barrier makes problems for me. Thanks buddy!

**Comment by rossc85** [comment]
#487 
#479 
#478

they close these reports as soon as they appear, i stated in mine changing to nearest DOES NOT WORK.
a solution for me was to roll back to v 7.0.0.16 it works ok
