### ISSUE TITLE
[BUG_SP] Course creation on Elmcreek F71 fails

### ISSUE THREAD

**Issue by Elite29er** [Courseplay/Courseplay_FS22#477]
**Steps to reproduce**
Load Elm Creek map. Select any tractor. Select any combination of mowers. Go to the Hire Worker menu. Create CP Fieldwork job. Open generate CP generation options. Select to generate course. No course is created.

**Actual behavior**
No course is created on F71 Elmcreek map. Possibly because is a grass field? 

**Expected behavior**
I expected a course to be generated.

**Screenshots**

**Courseplay version**
Version used: .17

**Log**
No logs created
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elm Creek

**Vehicles/ implements involved**
Any tractor and any mowers
Mod yes and no

**Relevant script mods**
Mods like Autodrive or VCA and so on. 
GPS is installed also.

**Comment by Tensuko** [comment]
I created some course on 71 so where is the logfile ?

**Comment by Elite29er** [comment]
Here is the pastebin for the Log file. It shows it starts and generates successfully, but no waypoints are made.

https://pastebin.com/GzzU0LKG

**Comment by pvaiko** [comment]
Works fine for me, are you sure you have not modified that field?

**Comment by Elite29er** [comment]
I made it bigger, but I don't see how that should keep CP from making the course.

**Comment by dansiegel1109** [comment]
I also have had similar issues with some merged fields on .17.  I'm running some other tests right now, however I can state that the problem I see is largely to do with when I select longest edge row direction (I definitely want the rows to be north-south or east-west) to help prevent avoiding trees near field edge.  If I select automatic, the course is created however always with a non-cardinal direction for the rows.  I didn't look at the logs, just passing on an observation.

**Comment by pvaiko** [comment]
@Elite29er use the console command cpSaveAllFields and post the resulting xml file here. 

If your changes are not clean, for instance making little nooks or introducing islands, it may very well cause issues, I see in your log at least one successful generation for field 71 and that shows the generator had to split that field into four blocks to somehow cover it, which should not be necessary for regular convex polygon.

**Comment by Elite29er** [comment]
Here is my cpSav~ file.  https://pastebin.com/cPx26ZzD
![Elite29er_F71](https://user-images.githubusercontent.com/34731180/148963629-94e4e31e-8198-48df-a84d-eeb45fb60c27.jpg)
Here is a screen cap of the field.

**Comment by pvaiko** [comment]
There is the problem:
![image](https://user-images.githubusercontent.com/2379521/148966521-bf39848f-5e7e-44d5-a902-f1b456bf602d.png)

You can also check this on your map, use the `cpToggleDevHelper` console command, then walk to the field and press LeftAlt+C, this will show the field contour as Courseplay sees it.

**Comment by Elite29er** [comment]
Thank you, this correction fixed it.
