### ISSUE TITLE
[BUG_SP] Drescher kann nicht mehr am aktuellen Punkt weitermachen

### ISSUE THREAD

**Issue by Mike1977** [Courseplay/Courseplay_FS22#478]
Seit der letzte Version mit dem Patch "Set start job on first waypoint as default" ist es nicht mehr möglich den Drescher mitten im Feld anzuhalten und dort weitermachen zu lassen. Da "start on first waypoint" nun default ist, und man das auch nur ändern kann, wenn man einen neuen Job startet, fährt der Drescher nun immer zum startpunkt und fängt von vorne an.

**Comment by Maverick-0815** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/473
