### ISSUE TITLE
[BUG_SP] Continuing a Course without starting from begining

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#479]
I use CP to pick stones, but have to stop it to unload the stones, when I try to restart the stone picker where it left off, it goes back to the beginning and starts the course over.

**Steps to reproduce**
Start a course, stop it midway, and attempt to start again.

**Actual behavior**
After stopping a CP AI in the middle of a course, then when restarting the CP AI, it goes back to the beginning instead of starting at the nearest, or closest, or current waypoint.

**Expected behavior**
CP AI to start where left off.

**Screenshots**

**Courseplay version**
Version used: 7.0.0.17

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7843898/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
no

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Mini HUD !!! Change to nearest.

**Comment by Maverick-0815** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/473

**Comment by rossc85** [comment]
#487 

seems they want to ignore this any similar report gets closed immediately, i can replicate this every time on v.17, 
a solution is to roll back to v.16 works fine for me
