### ISSUE TITLE
[BUG_SP] Falsche Arbeitsbreitenerkennung und fehlender Versatz bei Balkenmäher

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#480]
**Steps to reproduce**
Frontmähwerk und Heckbalkenmähwerk

**Actual behavior**
Die Arbeitsbreite wird an Hand des Frontmähwerkes berechnet. Das hitnere Mähwerk wird weder bei der Arbeitsbreitenberechnung noch beim Versatz berücksichtigt.

**Expected behavior**
Die Arbeitsbreite wird in meinem Fall auf 7.1 berechnet und es wird ein Versatz angelegt.

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/78980660/148901095-29d69989-08bb-4a57-93b8-a485fd946aac.png)
![Screenshot_2](https://user-images.githubusercontent.com/78980660/148901099-c6edb4bf-3ac8-48e9-bb84-69172c6e234f.png)

**Courseplay version**
Version used: 7.0.0.17

**Map**
Eerlengrat

**Vehicles/ implements involved**
Yes - Kuhn GMD 3123F und GMD 4411

**Relevant script mods**
No

**Comment by Tensuko** [comment]
@schwiti6190 
Arbeitsbreite ermitteln wenn Geräte ausgeklappt wurden ?
![fsScreen_2022_01_11_08_56_36](https://user-images.githubusercontent.com/27344744/148902901-cb161b6b-6c21-45af-a131-f3e607a4db92.png)

**Comment by BullFlag** [comment]
What AD Debug settings (screenshot of green/yellow) would I need?    I'd like to repeat the view with these lines and numbers.   Good to know

**Comment by Tensuko** [comment]
That is Giants debug and only needed for us to check the tools.
When you want our debugs, turn on debug settings for that vehicle.

**Comment by BullFlag** [comment]
I see     "only needed for us to check the tools"   

We'll for the others they can use the  Console Command 

  **gsVehicleDebug**       Then enter Shift+5      

![2022-01-11 10_35_58-Farming Simulator 22](https://user-images.githubusercontent.com/23723361/149002338-f7948801-59d1-44fb-ae6e-ca6606bddac8.png)

**Comment by Tensuko** [comment]
That is the Menu that I used.....

**Comment by 0scarZulu** [comment]
@Tensuko wie ist der aktuelle Stand hier? Auch mit 7.0.0.25 wird weiterhin keine Arbeitsbreite ermittelt bei ausgeklappten Mähwerken.

**Comment by Tensuko** [comment]
Der ist so wie du es siehst.
Noch nicht weiter.
Wenn dann würde heir etwas dazu stehen........

**Comment by Tensuko** [comment]
Das Problem hier ist, dass wir zwar die richtige Arbeitsbreite von dem großen Mähwerk ermitteln, aber man in diesem Fall die Breite zusammen rechnen müsste. Weis nicht wie wir diese Werte hinbekommen ohne was kaputt zu machen.
Da man das hintere Mäwerk auch alleine nutzen könnte, kann ich dafür auch nicht einfach 7.1m und entsprechenden Offset für festlegen...
![fsScreen_2022_02_24_18_56_20](https://user-images.githubusercontent.com/27344744/155580411-a3f900ac-41fb-4149-802c-ecb077f5fc6c.png)
.

**Comment by 0scarZulu** [comment]
Hilft es vlei beim Guidance Steering mal zu schauen wie Wopster es macht? Denn er bekommt die Arbeitsbreiten addiert.

**Comment by pvaiko** [comment]
> Hilft es vlei beim Guidance Steering mal zu schauen wie Wopster es macht? Denn er bekommt die Arbeitsbreiten addiert.

For the record, no, he does not, same issue, only get the correct width when everything is unfolded.
