### ISSUE TITLE
[Feature] Stopgap for Baleloaders

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#482]
**What is the problem this feature/enhancement solves?**
Currently baleloaders can load bales, but won't stop when full.

**Describe the solution you'd like**
Have baleloaders cancel the job, when fully loaded.

**Describe alternatives you've considered**
Stop after loading the last Bale, like combines do when full (might be easier to implement?)

Integration with Autodrive, to start driving to the unload point, when full, for further down the line

**Additional context**

**Comment by Tensuko** [comment]
Bale Loaders are not even in the Release yet... just have patience.

**Comment by JDTiger** [comment]
Huh, interesting... hte mode ingame is called "**collecting**/wrapping bales", so i thougthit was intended to work with blae collectors

**Comment by Tensuko** [comment]
Becouse you are on the Main Branch an not Release.
