### ISSUE TITLE
[Feature] Global Settings

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#483]
**What is the problem this feature/enhancement solves?**
Currently especially for speed, one has to configure every single vehicle, to drive the speeds one want.

it would be nice if such Settings could be configured globally (aka set it once and have them in all vehicles in the savegame).

Same for lowering/raising

**Describe the solution you'd like**
Have a Global settings Page or option to set as global

**Describe alternatives you've considered**
At least have holding down he buttons increase speed fast, or implement scrolling for Speedsettings

**Additional context**

**Comment by Tensuko** [comment]
> it would be nice if such Settings could be configured globally (aka set it once and have them in all vehicles in the savegame).

That doesn't make sence when you have so many differen tools and vehicles.
Sry that will not happen.



> Same for lowering/raising

Same here.
Some tools needs different settings.

I have the Idea to make that into vehilceconfig.xml for some tools as they always need a specific setting.
But global, no. It woul affect all vehicles at once.

> At least have holding down he buttons increase speed fast, or implement scrolling for Speedsettings

This is already as an enhancement and we will see how we can do that.
