### ISSUE TITLE
[BUG_SP] Tractor drives permanently backwards during the turning manoeuvre of the field lines

### ISSUE THREAD

**Issue by Scaracuila** [Courseplay/Courseplay_FS22#486]
**Steps to reproduce**
Vehicles: McCormic X8 with Bredal K105
Fendt Favorit 515C with Amazone ZA-TS 3200
(original Vehicles, no Mods)

**Actual behavior**
When driving down the field tracks, the tractor reverses a bit at the end of the track, then drives into its new track and then drives backwards. However, it does not stop reversing, at least as long as there is no object in the way. If you don't notice it, it drives backwards over the whole map.

With seeder Väderstad Rapid A800S I have no problems.

I noticed this in version ...17, but it still worked in ...16.

**Expected behavior**
I expected that the tractor would make a corrective move when turning into the new lane and then continue with its work.

**Screenshots**
![60vgfg](https://user-images.githubusercontent.com/34663971/149003305-b187acf8-90a9-480a-b42b-565a145eeb5e.gif)

**Courseplay version**
Version used: 7.0.0.17 plus all updates up to 5pm today, 11th January

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7849183/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Mod yes/no ? No

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Both of them and also
BewareOfStraw
playerActionCamera
BlackEchaustSmoke
CollectStrawAtMissions
PlayerSpeed
RefreshContracts
BetterTimeScale
HappyHorse
cultivatorFieldCreator
CabView
AutoTurnOffTurnlights
additionalFieldInfo
BaleCounter
ImproveRepairCosts
multipleMissions
PowerTools
StoreDeliveries
manualAttach
VehicleFruitHud
SeedingOptions

**Comment by pull2play** [comment]
God bless you for making this report, I observed this a couple of days ago but haven't had the time to make it myself. Devs, please note - this affects many tractors and many implements, but isn't 100% reproducible on every course. I've had this issue with nearly all combos, most recently a Fendt 1050 and the 15.8 cultivator.

**Comment by RealNeo80** [comment]
i never had this issue

**Comment by Tensuko** [comment]
Never heard of this problem, but hiw to know about this when no one report this.

But you should always stick to release becouse it is not said that every commit on main is already done and ready for release.

Ofc we will have a look.

@Scaracuila do you have discord ?

**Comment by pvaiko** [comment]
@Scaracuila you mean this is not the 17 release but a commit on the main branch? Which commit?

**Comment by Scaracuila** [comment]
Hi,

I have just tried the following:
Try 1: Release ...17 put back into mod folder, works without problems so far.

Try 2: Version from yesterday afternoon, comment from Tensuko "Merge pull request #485 from Gonimy-Vetrom/patch-6" has the problem with the permanent reverse.

Try 3: current download, comment from Tensuko "Smal translation changes", now everything works normally again! Currently tested on 3 fields.

@RealNeo80 I'm happy for you.

@Tensuko that's why I wrote this report, and yes, I know that we should stick to the releases, but then such errors do not appear.
Yes, I have Discord

@pvaiko correct, it wasn't the release but the comment I mentioned in try 2.

**Comment by Falkwa** [comment]
i have also noticed this problem.   happens at random but never on a headland.   i start the course in CP as usual.   2 headlands and if the worker goes into unending reverse i just finish field with reg worker.   noticed with mowers, planters/seeders, plow, subsoil, combine

**Comment by KCHARRO** [comment]
This problem does it to me too, starting from 7.0.0.17, the strange thing is that it is on one side of the course, when it starts to go backwards, you stop it, put it back to work and it goes to the other end and returns without trouble, when turning and going to the next one, it starts backtracking again.

for now I'm still using 0.16 ... until it's fixed.

**Comment by pvaiko** [comment]
b986c133 should have fixed this.

**Comment by Tensuko** [comment]
@Scaracuila 

> Yes, I have Discord

Can you contact me ?
Tensuko # 2300 (added space to not confuse github :) )

**Comment by pvaiko** [comment]
Reopen if issue still exists
