### ISSUE TITLE
[BUG_SP] After stopping cp worker, can't resume from where left off

### ISSUE THREAD

**Issue by rossc85** [Courseplay/Courseplay_FS22#487]
**Steps to reproduce**

John Deere X9 1100 with HD50F header.
when stopping course the cp worker cant resume from where he left off and wants to go back to the start of the course

**Actual behavior**

instead of resuming job the worker makes his way back to the starting point and starts again,

did not have this issue in v.16 this is my first try with v.17, tried all settings, (first waypoint, next waypoint) and changed all the other settings but all had same result

**Expected behavior**

to resume task where it was left off

**Screenshots**

![fsScreen_2022_01_11_20_29_08](https://user-images.githubusercontent.com/97556359/149016768-5509c3e7-5f76-475b-86b4-c1699f7f9fb1.png)

**Courseplay version**

7.0.0.17

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7849704/log.txt)

**Map**

elm creek

**Vehicles/ implements involved**

Base game John Deere x9 1100 with HD50F header

**Relevant script mods**

i have autodrive and gps steering none were active

**Comment by RealNeo80** [comment]
have you startet over the mini HUD? it seems you start with strg+H and this will start everytime how it is set in the mini-HUD

**Comment by Tensuko** [comment]
Exactly how RealNeo said.

**Comment by rossc85** [comment]
yes (although i have a different keybind for start cp worker), every time i interrupt the cp worker he wants to go back to the start, i have deleted and reinstalled v.17 still same issue, i deleted it again and installed v.16, issue gone

**Comment by rossc85** [comment]
wow, thanks for giving me chance to respond

**Comment by RealNeo80** [comment]
never got the answer from you if you started over the mini HUD or not ....

**Comment by rossc85** [comment]
never got a chance to reply before it was closed, and yes i have stated in my original post that i tried first waypoint , nearest waypoint etc

i was only trying to bring it to your attention but i'll not bother again

**Comment by RealNeo80** [comment]
it has nothing to do with bothering, you never told us how you started, the logfile is not complete ... sorry but my glass ball is under service at the moment i have it not by my hand. some pictures about the open hud and what are you klicking on will be as helpful as a complete log ..

**Comment by rossc85** [comment]
really? heres a video, note that you can see that i selected nearest waypoint.

[https://streamable.com/yy3fl6](url)

whereas when i do the same thing in v16 (same game save, same settings) it works fine

[https://streamable.com/zl4ihm](url)

I can replicate this every time by swapping v16 for v17, swap back again it works fine.
im only trying to help, and appreciate what you guys are doing, but you are asking for bug reports and then dismissing them.
As for the log, my log went on for like an hour before it got to where i had the problem and i deleted it and then replicated the problem so that it would be right there in front of your eyes without trawling through hours of logs....

**Comment by RealNeo80** [comment]
yep and this is NOT the mini hudcheck your key bindings for CP .... have pc off so i cant show you. you need to bin cp vehicle config or so to a key than you can open mini hud

**Comment by rossc85** [comment]
this is only available keybindings for CP tho 

![fsScreen_2022_01_11_23_03_50](https://user-images.githubusercontent.com/97556359/149035650-0023fc11-9ca5-428b-8ef8-1568ae2c72bf.png)

no mention of minihud anywhere in settings at all...

**Comment by Resandise** [comment]
From main screen, hit the "Delete" key to bring up the minihud.

![InkedfsScreen_2022_01_11_17_09_11_LI](https://user-images.githubusercontent.com/96673100/149035781-64fe53d6-ebf6-4477-8149-fce5b812582e.jpg)
.
Then switch to nearest waypoint.

**Comment by rossc85** [comment]
ok thanks for explaining that but unfortunately it doesn't bring up that display, i have tried a random empty keybind with both DELETE and backspace to see if they were already assigned to something but apparently not??

**Comment by rossc85** [comment]
could it be a problem with keyboard region?

**Comment by RealNeo80** [comment]
yeah its not exactly shown as mini-Hud @Tensuko  maybe you should name it MiniHUD in the keybindings
@rossc85 
here this one
![image](https://user-images.githubusercontent.com/8066324/149077419-95817124-0ee2-47c5-bf93-d53c7110c88c.png)

**Comment by Tensuko** [comment]
@rossc85 you may have a duplicate keybind, the game will tell you if so.

@RealNeo80 yea I guess I change the Name for next release...

**Comment by rossc85** [comment]
yeah got it to come up, but has to reassign the key bind for it, to the exact same keybind that it was already assigned to and then it would come up for some reason?
thanks for all the help
