### ISSUE TITLE
[BUG_SP] When using the worker and you forget the to put the trailer back in the field for the unload feature you have to restart the combine after unloading it yourself. Which is not the issue the issue is when you go back to where you left off and restart the worker he goes back to the beginning, Is there a fix for this or a way to get around it. I was also playing on the map No Mans Land and it seems to work great on that map even the fields you create yourself.

### ISSUE THREAD

**Issue by JuniorLaws** [Courseplay/Courseplay_FS22#490]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Use the Template correct.
