### ISSUE TITLE
[Feature] I would like the fs19 layout to come back instead of doing it through the worker screen. It looks better and i had a lot less issues.

### ISSUE THREAD

**Issue by JuniorLaws** [Courseplay/Courseplay_FS22#491]
**What is the problem this feature/enhancement solves?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
No, read Wiki and stop asking for it https://github.com/Courseplay/Courseplay_FS22/wiki
It works like a charm.
