### ISSUE TITLE
Change tool offset

### ISSUE THREAD

**Issue by pierrehicks** [Courseplay/Courseplay_FS22#492]
So I'm trying to manually change the tool offset for a plow while its running its course because the automatic offset is incorrect. However, almost as soon as I change the offset it resets to the automatic value. I also tried to change it before starting the course and it immediately resets. I then tried removing the course then setting the offset and creating a new course but it did not work either so I'm just wondering if I'm doing something wrong or if this is an actual issue.

**Comment by Tensuko** [comment]
Plow is calculated dynamically on purpose.
