### ISSUE TITLE
[BUG_SP] AVOID FRUIT causing combine to get stuck in mud

### ISSUE THREAD

**Issue by Philj030** [Courseplay/Courseplay_FS22#493]
**Steps to reproduce**
Engage Avoid Fruit - Run combine on a course (mine happened after it rained although not sure if that has any affect)

It seems that when Avoid fruit is turned and the combine does its reverse maneuver it is getting stuck in the mud and then the call for 'blocked by an object' happens resulting in CP being disengaged

**Expected behavior**
Combine should complete its reverse maneuver / unload / and then restart its course

*Courseplay version**
17

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
ND Hastings

**Vehicles/ implements involved**
Fendt Combine

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Rain should have no effect at all on the ground.
A logfile would help with debug channels active.
So you was able to harvest during rain or what is it ?
A bit more details or step by step would help...

**Comment by Tensuko** [comment]
Closed due to inactivity.
Sry but your report does not make any sence. We need more Informations.
