### ISSUE TITLE
Abfahrerproblem im Vorgewende

### ISSUE THREAD

**Issue by SaschaLie** [Courseplay/Courseplay_FS22#495]
Ich habe schwer Probleme im Vorgewende "scharf". Der Häcksler (auch Drescher) fährt immer am Ende so eine Tasche und setzt dann zurück bis zum Feldrand. Bis dahin klappt das mit dem Abfahrer, der schön hinterher fährt. Sobald der Häcksler in die Tasche fährt, setzt sich der Abfahrer daneben und steht dem Häcksler anschließend beim Rückwärtsfahren im Weg. Wäre es möglich mit einer Einstellung zB, die "Taschenfahrt" auszuschalten? (Vers. 7.0.0.17)
![H1](https://user-images.githubusercontent.com/96572157/149068418-1316bcaa-b416-4d54-8791-85f4592f2c89.jpg)
![H2](https://user-images.githubusercontent.com/96572157/149068420-f42cd3af-6cdc-4b3a-b816-e4c8bd595c25.jpg)
Hier ist der Abfahrer von Hand zurückgefahren worden.
![H3](https://user-images.githubusercontent.com/96572157/149068423-504da9c9-0bd0-4ff2-9d76-424ae35ec313.jpg)

**Comment by Osram1981** [comment]
Ja und der Häcksler führt sein Wendemanöver nicht fort wen der AD Fahrer nicht in Spuckreichweide ist somit dauert so ein wendemanöver Ewig kann man das nicht so machen das der das Manöver macht und erst wen er wieder an die Frucht geht den Abfahrer sucht?

**Comment by Tensuko** [comment]
Das ist noch nicht richtig implementiert und hier wäre auch die Frage was AD macht und nicht CP.
Wartet es doch bitte ab, nur weil es bereits so schon halbwegs funktioniert...

**Comment by SaschaLie** [comment]
Kein Thema! War ja nur eine kleine Anmerkung. Im AD habe ich das auch mal geschrieben

**Comment by SaschaLie** [comment]
PS: Was Ranzt Du mich denn so an? In meinem letzten Kommi ebenfalls. Ich schildere nur ein Problem und stelle normale Fragen! Ich erwarte NICHT!!!! das immer alles sofort gelöst wird, und weiß ich, das da was noch nicht richtig implementiert ist???? Und natürlich sage ich auch nicht, das es nur an CP liegt! Du solltest mal daran denken, das manche Leute Euch auch mit €uronen unterstützen, wie ich zB. Ich Spende aus Dankbarkeit für die Arbeit und da möchte ich nicht unbedingt so Angefahren werden!

**Comment by Tensuko** [comment]
Sag mir mal bitte wo ich dich 'angeranzt' haben soll ?!

Es gibt Dinge die werden des öffteren gefragt und gemeldet, statt mal bisschen selber zu lesen, dass ich dann manchmal etwas genervt bin mag sein, aber ich 'ranze' niemanden an.

Wenn ich sage wartet es doch bitte ab, dann ist das so gemeint wie ich es sage.
Einfach abwarten.

Deine Reaktion verstehe ich gerade Null
