### ISSUE TITLE
Integration AI Vehicle Extension führt in Courseplay zu Fehlern [Question]

### ISSUE THREAD

**Issue by jeffersondarsy** [Courseplay/Courseplay_FS22#498]
Ich habe als Mods Courseplay (7.0.0.17) und AI Vehicle Extension (0.0.1.1) im Single Player aktiviert.

Nach der Generierung eines Kurses in Courseplay und dem Start der Route, wird der Alternative Helfer aktiviert. Der abgefahrene Kurs entspricht weder dem berechneten Courseplay Kurs, noch dem normalen AI Kurs, welcher sich immer am Feldrand orientiert. Im getesteten Fall fährt der Mähdrescher einfach geradeaus, so wie der Original Giants Helfer.

Sobald ich den AI Vehicle Mod deaktiviere, funktioniert Courseplay einwandfrei und der Mähdrescher folgt dem berechneten Kurs.

Ich hatte bereits den Verdacht, dass das Verhalten bei aktiviertem AI Vehicle Mod an der im AI zugewiesenen Tastenkombination "STRG+H" bzw. "ALT+H" zum Aufruf der entsprechenden Helfermenüs liegen könnte und habe diese beiden Kombinationen geändert. Leider ist dieser Workaround nutzlos. Das oben beschriebene Verhalten bleibt.

Meine Frage an euch ist, ob dass Problem ein Courseplay Issue ist/sein kann oder ein AI Vehicle Issue ist/sein kann, um dann einen detaillierten Fehlerbericht an der richtigen Stelle erstellen zu können.

**Comment by Tensuko** [comment]
Du kannst im AIVE Menü nur für das entsprechende Fahrzeug AIVE deaktivieren.
An sich sollte kein Konflikt entstehen.
