### ISSUE TITLE
[Question] Zielpunkt festlegen

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#500]
Hallo Leute
wenn man im Helfermenü einen cp-job erstellt, kann man ja die Zielposition (=Startpunkt) festlegen, dann erst den Kursgenerator ändern.
wenn ich nun merke das der Startpunkt nicht ideal ist, muss ich den Kursgenerator erst schliessen um einen neuen Startpunkt festzulegen, und dann wieder den Kursgenerator öffnen,...
das ist etwas umständlich, kann man zukünftig den Startpunkt eventuell auch mal bei geöffnetem Kursgenerator ändern? 

lg
andreas

**Comment by Tensuko** [comment]
Das funktioniert mit dem GUI leider nicht.
Aber die bisher besten Startpunkte waren immer an der Kante vom Feld mit etwas Abstand zur Ecke.
Hast du ein Beispiel wo es nicht gut passte nach dem generieren ?

**Comment by andreasthu** [comment]
Hallo tensuko.
Ein konkretes Beispiel habe ich nicht. 
Bzw probiere ich gerade auf Haute-Beyleron bei Feld 43 (östlich vom Fahrzeughändler), das sechseckige, eine gute Drescherstrategie (Claas Trion, 10,5m Schneidwerk)
Mit z.b. 2x Vorgewende, Beete mit 5, 6, 7,.. Bahnen,...
Mir ist aufgefallen, das cp bei manchen 90grad ecken rundunge  generiert (obwohl scharfe Ecken eingestellt).
Wenn ich dann den Startpunlt einige meter vor oder zurücksetze dann Scharfe Ecken generiert werden.
Da muss ich natürlich aus dem kursgenerator raus, startpunkt ändern, kursgenerator rein, kurs generieren, kursgenerator raus, startpunkt ändern, kursgenerator rein,
...
Etwas inständlich
Lg
Andreas

**Comment by BullFlag** [comment]
Andreas makes a very insightful comment.  Worth taking seriously.   Andreas described the use case where the  **GUI is cumbersome.**    " Unfortunately, this does not work with the GUI'     A better "fit well after generating" will make it less cumbersome.    After a month of trying to improve the fit generation, and it's still cumbersome.    Still can't change Giant's GUI for CP use, what then?

He also pointed out the confusion with the Giant's GUI "   The  "target position (= starting point),"    His point is the target wording is confusing.   "Target point" means the destination not starting point.   Changes to the wording in the GUI is the point ... If " Unfortunately, this does not work with the GUI."     then live with the confusion .

**Comment by Tensuko** [comment]
> Mir ist aufgefallen, das cp bei manchen 90grad Ecken rundungen generiert (obwohl scharfe Ecken eingestellt).

Das ist scheinbar ein bug, der ist auch schon als Issue vorhanden.


> Wenn ich dann den Startpunlt einige meter vor oder zurücksetze aber dann Scharfe Ecken generiert werden.

Das soll so natürlich nicht sein.
Wir gehen natürlich davon aus, wenn man den Punkt einmal gesetzt hat, dass dann auch die Kurse richtig generiert werden.

Also nicht das eigentliche Problem mit einer anderen Lösung beheben.

Es wäre cool wenn du in #502 in einem logfile den Kurs einmal so generierst, dass Rundungen entstehen und einmal so, dass richtige Ecken entstehen und das dann dort postest, dass man vlt den Unterschied sieht.


@BullFlag sry buddy I don't know what you mean. The base problem is something else and when that is fixed, there is not rly a problem anymore :)

**Comment by andreasthu** [comment]
mach ich,
habe gerade was probiert 
lg
andreas

**Comment by Tensuko** [comment]
Super, danke dir.
