### ISSUE TITLE
[BUG_SP] Vorgewende Ecken: Scharf - funktioniert nicht immer

### ISSUE THREAD

**Issue by MrsJessica92** [Courseplay/Courseplay_FS22#502]
**Steps to reproduce**
Ich glaube es ist Fahrzeugabhängig - jedenfalls passiert es bei meinen JD9620 RX fast immer, bei meinen Fendt1050 nicht. Daher:
1) Traktor JD9620RX + Anbaugerät (in meinen Test einfach: Grubber Farmet Kompaktomat 1570 MAX)
2) Generiere Kurs mit Settings (siehe Screenshots) - Für den Test hab ich das Feld 47 auf Elmcreek genutzt - passiert aber auch auf anderen Feldern

**Actual behavior**
Es ist eine Ecke im Vorgewende nicht scharf.  (Das passiert eher random - nach dem ich für die Logs die Channel aktiviert habe, hat das für 2 Felder wieder funktioniert und beim 3./letzten nicht mehr)

**Expected behavior**
Alle sollten immer Scharf sein.

**Screenshots**
Corner: https://i.imgur.com/a0y8Msq.jpg
My Settings: https://i.imgur.com/rJ2rmOO.png

**Courseplay version**
Version used: 7.0.0.17

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7853696/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Traktor JD9620RX + Anbaugerät (in meinen Test einfach: Grubber Farmet Kompaktomat 1570 MAX)

**Relevant script mods**
Autodrive, GPS

**Comment by Tensuko** [comment]
Ist die runde Ecke zufällig unten links ?

**Comment by MrsJessica92** [comment]
Ich habe jetzt nicht drauf geachtet ob es immer so ist (da er ja auch manchmal unbeobachtet fährt, aber wenn es mir aufgefallen ist, dann war es schon immer die selbe Ecke (sprich unten links)

**Comment by Strawberry93** [comment]
Also bei mir ist die Runde ecke oft unten links. Meistens beim Düngen

**Comment by Tensuko** [comment]
Das Tool sollte keine Bewandtnis haben.
Arbeitsbreite und bei Ecken Rund der Wenderadius.

Aber ich habe auch des öffteren gehört, dass es unten links ist, desshalb fragte ich danach :)

**Comment by andreasthu** [comment]
Hallo Tensuko
hab das nun versucht, wie du mir im anderen Beitrag gesagt hast
Haute-Beyleron,
Feld 40
Trion + 9mSW

2x Rundum, scharfe Ecke, dann spiralförmig.
links unten runde Ecke
hier habe ich den Startpunkt ca mittig vom Feld plaziert:
![fsScreen_2022_01_13_09_40_35](https://user-images.githubusercontent.com/24860501/149296517-1f4239bb-d535-43c7-a0ef-27969d4421a8.png)

![fsScreen_2022_01_13_09_40_44](https://user-images.githubusercontent.com/24860501/149296712-3a3b1856-1fa7-4f84-8b9d-b1b6d992c858.png)

dann habe ich den Startpunkt etwas weiter nach unten, richtung Ecke versetzt:
![fsScreen_2022_01_13_09_41_21](https://user-images.githubusercontent.com/24860501/149296822-5bf44901-b4a0-4aff-8cce-d46335da71e2.png)

und dann den Kurs neu berechnen lassen, sonst selbe Einstellungen gelassen:
und ich hatte eckige Ecken:
![fsScreen_2022_01_13_09_41_24](https://user-images.githubusercontent.com/24860501/149296924-6f864c11-e328-4cab-9030-e201e8e9c29a.png)

![fsScreen_2022_01_13_09_39_52](https://user-images.githubusercontent.com/24860501/149296954-40851264-6683-4385-afc1-c9f1930651da.png)

ev hat das was mit der startposition zu tun?
btw, habe vorhin auch die Felder 38 und 39 versucht, da hatte ich immer eckige ecken. Kann es damit zusammenhängen das 38+39 vertikal (nord-süd, startpunkt oben) und Feld 40 horizontal (west-ost, Startpunkt links) bearbeitet wird?
lg
andreas

**Comment by Tensuko** [comment]
Super, danke dir.
Spannend wie das zustande kommt.

**Comment by pvaiko** [comment]
Nicht so spannend leider, bis wir ein Fix haben, versuch den Startpunkt weiter weg von der linken Feldseite zu verschieben, mehr als 5 m oder so.

**Comment by Roby1164** [comment]
Ok now field 40, get the correct angles ...
![Screenshot_2](https://user-images.githubusercontent.com/24955554/149335725-ee9eb14c-7b0d-4e31-a1aa-03f0782082af.jpg)

**Comment by Roby1164** [comment]
> 

Yes

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.19

**Comment by andreasthu** [comment]
Danke
lg
andreas

**Comment by moose31608** [comment]
>
This is what I get when I start my game

**Comment by moose31608** [comment]
Courseplay(7.0.0.19): For help, bug reports or patch notes, please visit:
https://github.com/Courseplay/Courseplay_FS22. This is what I get when I start my game

**Comment by mfehr94** [comment]
> Courseplay(7.0.0.19): For help, bug reports or patch notes, please visit:
> https://github.com/Courseplay/Courseplay_FS22. This is what I get when I start my game

That's normal you need to push the okay button
