### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by Laczkovics111** [Courseplay/Courseplay_FS22#503]
The translation_hu is XML, not translated into Hungarian. I translated it and sent it. I hope I could help.

[Hungarian_Courseplay.zip](https://github.com/Courseplay/Courseplay_FS22/files/7855343/Hungarian_Courseplay.zip)

**Comment by Tensuko** [comment]
Thanks for your translation, but can you make a pull request for this ?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by RealNeo80** [comment]
i can handle the pull request for you if you want @Laczkovics111

**Comment by Tensuko** [comment]
@RealNeo80 you might have to handle this forever then :)

**Comment by RealNeo80** [comment]
no i need to improve my lua speech, thats is what i need to handle :P i lost nearly all knowledge the last 10 years.

and i´m with you, if he is willing to do more translations to hungarian, he should install github desktop and make the pull requests himself ;)

**Comment by Laczkovics111** [comment]
Unfortunately, I can’t guarantee I can always deal with it. That's why I'm
happy to pass it on to others.

RealNeo80 ***@***.***> ezt írta (időpont: 2022. jan. 12.,
Sze, 19:09):

**Comment by Tensuko** [comment]
You don't have to, it can happen that we add stuff step by step and when you translate it in a big pack like now thats totaly enough.

**Comment by Laczkovics111** [comment]
Okay.

Tensuko ***@***.***> ezt írta (időpont: 2022. jan. 12., Sze,
19:26):

**Comment by RealNeo80** [comment]
i created
