### ISSUE TITLE
[Feature] HAWE SUW 5000 forage auger wagon

### ISSUE THREAD

**Issue by thenormal007** [Courseplay/Courseplay_FS22#508]
**What is the problem this feature/enhancement solves?**
Currently when trying to use the tractor mounted forage harvester in combination with HAWE SUW 5000 forage auger wagon, the wagon does no automatically dump into a trailer pulled by the secondary tractor.

Additionally i have found that it has trouble reversing with sharp corners enabled:

![Posnetek zaslona (21)](https://user-images.githubusercontent.com/97110199/149232587-1973d433-a045-4e65-bc2c-7548676bb161.png)

**Describe the solution you'd like**
I would love to see the forage auger wagon to work in a similar way a regular combine works. I want this auger wagon to act as the grain tank acts on the regular combine and have the ability to  unload through the pipe without me intervening.

It would also be nice to have other combine functions like self unload where the combine finds the trailer on its own.

**Comment by Tensuko** [comment]
This is something very special that you ask for.
We can't simply make that wagon to a 'combine'.

Sry but this have to super low priority and I will close this for now.
We can look into it when we have active unloading with AD implemented.
