### ISSUE TITLE
Can "avoid islands" be added like in FS19?  Many new maps being released will have obstacles and islands in fields. I am playing on a map with islands in the fields, when i try to generate a course it crashes the game. [Feature]

### ISSUE THREAD

**Issue by FXfarms** [Courseplay/Courseplay_FS22#509]
**What is the problem this feature/enhancement solves?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tensuko** [comment]
Avoid Island is default on. But setting will come back and we have another Issue for this already.
