### ISSUE TITLE
[BUG_SP] Forage Harvester Collision check 

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#510]
I'm having issues when I set my forage harvester to harvest with CP, and a tractor/trailer to unload the harvester with AD.  On headlands turns, the harvester frequently backs into the trailer, not waiting for the AD driver to back out of the way like there is not Collision check on the harvester.  I don't see a setting to turn on/off collision detection. Also, when doing Lands, going from 2nd pass to 3rd pass, it hits the unloader.  This happens with unloader AD setting of Restrict Unloader to Field set to yes and no.

**Steps to reproduce**
Create a course with forage harvester (Krone Big X with corn head) with 2 headlands on sharp. Start course, with a unloader being controlled by AD.  Allow the harvester to run the headlands. 

**Actual behavior**
At the headland turn, harvester backs into the AD trailer trying to back out of the way, then stops the course do to collision.

**Expected behavior**
the Harvester have collision detection, to wait for the driver to back out of the way.

**Screenshots**
![fsScreen_2022_01_12_19_43_56](https://user-images.githubusercontent.com/96673100/149251500-509425b1-288a-4561-8aa1-262fdd2304ad.png)
![fsScreen_2022_01_12_19_43_59](https://user-images.githubusercontent.com/96673100/149251508-767888c9-1d8f-43b5-b63b-7686e7097187.png)
![fsScreen_2022_01_12_19_59_04](https://user-images.githubusercontent.com/96673100/149252308-635641c5-88a8-46c5-ace2-e680a6e47cfd.png)
![fsScreen_2022_01_12_21_40_44](https://user-images.githubusercontent.com/96673100/149262343-cb388684-1c61-47df-a4af-6d9be1d66adc.png)
![fsScreen_2022_01_12_21_38_29](https://user-images.githubusercontent.com/96673100/149262353-ff2d2503-8d9d-427b-8b0a-9fb389b0d6a5.png)
![fsScreen_2022_01_12_21_40_42](https://user-images.githubusercontent.com/96673100/149262363-f737344c-1c0e-4ec1-95fd-496feed600cd.png)

**Courseplay version**
Version used: 7.0.0.18

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7859777/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Modded trailer (Rollspeed8851 from Rolland Pack Mod) and unmodded trailer (Bergmann HTW 65)

**Relevant script mods**
AD.

**Comment by Tensuko** [comment]
Unloader not implemented yet, buddy....
Wait untill we officially have it rdy together with AD.
