### ISSUE TITLE
[Question] Added Interface function for AutoDrive, what and how ?

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#512]
Hi
On the last downloadable version of CP, i can see this new feature : Added Interface function for AutoDrive

Can you explain what has been added, and how to ?

because i just installed the last version of CP, i have 2.0.0.3 of AD, but i don't see anything new, not in AD nor in CP
it is a way to tell CP to use Autodrive to refill equipment ? something else ?

**Comment by Tensuko** [comment]
Interface is Code Structure, nothing for the User.
Wait untill AD implemented the stuff and you will be noticed.
