### ISSUE TITLE
[BUG_SP] Seeder is fertilizing but is selected not to do

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#513]
**Steps to reproduce**
Amazone Citan, with fertilizer and seed in the hopper

**Actual behavior**
Machine is fertilizing instead of not

**Expected behavior**
not fertilizing if it is deactivated in options

**Screenshots**
![image](https://user-images.githubusercontent.com/8066324/149379362-065d34a3-3705-4cc9-902c-d260507a39ae.png)

**Courseplay version**
Version used: 7.0.0.18

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7864770/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Mod no

**Relevant script mods**
AD, VCA but not relevant

**Comment by Tensuko** [comment]
And wich seeder ?

**Comment by Tensuko** [comment]
This is tested with not to buy any seed or fertilizer in the game options:

Seeder without fertilizer in the machine + option fertilizer active = doesn't tell us the seeder is empty
Seeder with fertilizer in the machine + option fertilizer active = just does its work
Seeder with fertilizer in the machine + option deactivated = works but ignores the setting

**Comment by RealNeo80** [comment]
without fertilizer its working yes. but if i deactivate it should also not fertilize wenn something is in ;)

**Comment by Tensuko** [comment]
> without fertilizer its working yes. but if i deactivate it should also not fertilize wenn something is in ;)

Yea you are correct, that means the setting is not active.
