### ISSUE TITLE
[BUG_SP] Rohr ausfahren am Ende des Kurses ruft den AD-Abfahrer nicht

### ISSUE THREAD

**Issue by DHempelmann** [Courseplay/Courseplay_FS22#514]
Es mag sein, dass dies ein AD-Problem ist, aber vielleicht liegt es ja auch an CP.

**Steps to reproduce**
Ich habe es sowohl mit dem Panther (Rüben), als auch mit dem Drescher (Topliner 4090H) bemerkt. Man lässt den Ernter ein Feld abernten und stellt mit dem gleichen Autzodrive-Ziel einen AD-Abfahrer ein. 

**Actual behavior**
Wenn der Drescher/Ernter zwischendurch voll ist, fährt er das Rohr aus und der AD-Abfahrer kommt angefahren. So weit, so gut.
Ist der Ernter am Ende des Kurses angekommen, bleibt er stehen und fährt ebenfalls das Rohr aus. Jetzt rührt sich der AD-Abfahrer aber nicht. Übernimmt man den Ernter nun manuell (stoppt also den Helfer), fährt der AD-Abfahrer bei ausgefahrenen Rohr sofort los. Unabhängig davon, ob der Ernter voll ist, oder nicht.

**Expected behavior**
Der AD-Abfahrer sollte auch am Ende des Kurses gerufen werden.

**Courseplay version**
Version used:  7.0.0.18

Log:
Letzte Einträge:

2022-01-13 18:52 :28 [dbg4 lp105475] Panther 2: WORKING: getFillLevelInfoText
2022-01-13 18:52 :28 [dbg4 lp105475] Panther 2: WORKING: getFillLevelInfoText
2022-01-13 18:52 :28 [dbg4 lp105475] Panther 2: WORKING: Fieldwork done, fill level is 50.7, now waiting to be unloaded.
2022-01-13 18:52 :34 [dbg4 lp105828] Panther 2: UNLOADING_ON_FIELD/WAITING_FOR_UNLOAD_AFTER_FIELDWORK_ENDED: Opening pipe

**Map**
Elm Creek

**Vehicles/ implements involved**
Panther / New Holland T9 mit Strautmann Aperion
Autodrive

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
Weil noch nicht implementiert.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ#why-unloading-with-autodrive-does-not-work

**Comment by DHempelmann** [comment]
Alles klar. Danke.
Den Punkt in der FAQ ("Rohr immer ausfahren") hatte ich natürlich aktiviert. Er fährt das Rohr ja auch aus, aber eben irgendwie "anders" als wenn er voll ist.
Er sagt im log ja auch "opening pipe". AD scheint das trotzdem nicht als Aufforderung zum Ausladen anzusehen.
