### ISSUE TITLE
[Enhancement] Headland to Row transition, driver not waiting implement to be lowered 

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#516]
Hi
When the drivers finish the headland passes, he start maneouvring to the first row, but then continue to the 1st row whithout waiting the implement to be lowered
already happen since 7.0.0.14.
got this behavior with multiple implement (rolling, sowing, combine, etc)

so it leads to these kind of things :/
![149351871-f36c776d-d83b-4252-b846-c2cf828f47f8](https://user-images.githubusercontent.com/58886243/149384360-35429047-243f-4442-84d1-d3b57451602f.png)

**Comment by Tensuko** [comment]
Raise Implement late, Lower Implement early ?

**Comment by pvaiko** [comment]
> so it leads to these kind of things :/

also, these kind of things should lead to attaching a log with debug activated ...

**Comment by Chico0008** [comment]
Ok for the log, but with which debug canal activated ?

implement are set to lower early and raise late.
if it's set to lower late, the "gap" is bigger

**Comment by pvaiko** [comment]
Just activate 'debug' in the vehicle settings page. All the channels we need are on by default.

**Comment by Chico0008** [comment]
I made the thing happen again
here's the log attached

also made a small video if needed
https://drive.google.com/file/d/1lEUHuLT3vXFxBABe-FDC0xszRGmnqs4x/view?usp=sharing

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7870772/log.txt)

**Comment by Tensuko** [comment]
continue here #571
