### ISSUE TITLE
[Question/Feature] Grain cart implementation

### ISSUE THREAD

**Issue by nlcoredump** [Courseplay/Courseplay_FS22#519]
You are probably working on this feature allready, but would it be possible to implement a graincart solution in a way like is done with  bale collecting.

Have a grain cart job to select which does:

- find harvester in field
- unload harvester
- when full do a "combine selfunload" which looks for unload option on field side.
- repeat

This way you could put a vehicle (autodrive/courceplay/any) at the side of the field to be loaded for transport to storage.

I mix like al lot of players courseplay and autodrive, where autodrive handles the road network and transports and courseplay handles all the fieldwork (and hopefully in the future bunker loading/leveling/unloading)

Second question:
Is it an option to pin a topic with a roadmap of features already planned for future releases so i/we can check that before requesting a new feature?

**Comment by Tensuko** [comment]
We are not working on this and it is not planed, as this is part where AutoDrive comes in.

For Mode3, something like that is planed.

> Is it an option to pin a topic with a roadmap of features already planned for future releases so i/we can check that before requesting a new feature?

Won't do.
