### ISSUE TITLE
[BUG_SP] driving backwards out of the course

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#520]
**Steps to reproduce**
not direct reproducable, happens sometimes

**Actual behavior**
should do an sharp edge turn, but drive backwards from the middle of the turn

**Expected behavior**
A clean turn

**Screenshots**
![image](https://user-images.githubusercontent.com/8066324/149418860-728481f6-d886-46ed-b641-2cee683ebcb8.png)

**Courseplay version**
Version used: 7.0.0.18

**Log**
in the end, before i stopped the CP Helper

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7866411/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Arion 650 + Grimme GL 420
Mod no ?

**Relevant script mods**
AD + VCA

**Maybe related to**
#486 

![image](https://user-images.githubusercontent.com/8066324/149419571-b78f6d3c-9bb7-477b-9898-9581dd9dea7b.png)

new log with debug on
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7866428/log.txt)

**Comment by pvaiko** [comment]
I need that course.

**Comment by Humbleguycrumb** [comment]
It happens everytime on sharp Headlands

**Comment by RealNeo80** [comment]
[savegame20.zip](https://github.com/Courseplay/Courseplay_FS22/files/7868196/savegame20.zip)

@pvaiko as requested, you find the tractor waiting on the train tracks, where i found him. Field course is active and causing problem, just tested it again

**Comment by MagicalPug** [comment]
I have more ore less the same problem. I had it in the headland.
Tractor with a "Mulcher". When the track turns in an edge. He got in the right position for the new lane but he drives backwards without stop. Once I found the tractor beyond the railway line and it was still going slowely backwards.
Im back using the 7.0.0.17 Version. There the same track is working great

**Comment by pvaiko** [comment]
> [savegame20.zip](https://github.com/Courseplay/Courseplay_FS22/files/7868196/savegame20.zip)
> 
> @pvaiko as requested, you find the tractor waiting on the train tracks, where i found him. Field course is active and causing problem, just tested it again

The course is for whatever reason is not active, and if I generate one, I can't reproduce the problem in that same corner. Can you please save that course and post the saved course here?

**Comment by RealNeo80** [comment]
hmm ok, but it takes till around 19:00 today cause i´m on work right now

**Comment by pvaiko** [comment]
No worries, I see the course is in the savegame, I'll try something, no idea why it is not loaded.
