### ISSUE TITLE
[BUG_SP] Drescher 5 Beete (ungerade Zahl) turns in falsche Richtung generiert ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#522]
**Steps to reproduce**
Drescher, Reihen pro Beet 5 (oder ungerade Zahl, 5, 7, ...)
![fsScreen_2022_01_14_05_54_46](https://user-images.githubusercontent.com/24860501/149454656-07adefd0-b154-40da-9ad2-2ef283e0b78e.png)

**Actual behavior**
nach dem ersten Beet bzw der 5. Reihe wendet der Drescher nach rechts um eine Reihe zuviel und muss dann anschließend immer nach rechts wenden um das Beet zu machen. somit ist das Abladerohr "immer in der Frucht" 
![fsScreen_2022_01_14_05_55_44](https://user-images.githubusercontent.com/24860501/149454805-0555aa3d-b3b1-4c24-90c7-a432bcfaa8c9.png)

![fsScreen_2022_01_14_05_56_01](https://user-images.githubusercontent.com/24860501/149454979-2d550616-ec81-4501-b613-eb5d50c704bf.png)

![fsScreen_2022_01_14_05_56_32](https://user-images.githubusercontent.com/24860501/149455001-300ff4a1-9fc3-4474-b43e-db1532ad6fce.png)

![fsScreen_2022_01_14_05_56_44](https://user-images.githubusercontent.com/24860501/149455007-911b2d5a-8434-4318-ad74-69342833a274.png)

**Expected behavior**
der Drescher sollte eine Reihe früher einlenken um am Ende der Reihe dann wieder nach links lenken zu können. somit wäre das Abladerohr wieder immer auf der abgeernteten Seite.

**Screenshots**
siehe oben

**Courseplay version**
Version used: aktuelles master/main (4f0ebb1)

**Map**
Haute Beyleron

**Vehicles/ implements involved**
Claas Trion + Corio 1275 C

**Relevant script mods**
CP

lg
andreas

**Comment by Tensuko** [comment]
Das liegt an der Aufteilung und sieht für mich erst mal nicht nach 'fährt in die falsche Bahn' aus.

**Comment by andreasthu** [comment]
dann schau mal auf das letzte Bild:
![fsScreen_2022_01_14_05_56_44](https://user-images.githubusercontent.com/24860501/149487744-c2d1da98-2314-40cf-8bf3-edb318eebb22.png)

hier wendet der Drescher nach rechts, d.h. das Abladerohr ist in der Frucht.
würde er nach der 5. Reihe eine spur früher einlenken:
![fsScreen_2022_01_14_05_55_44](https://user-images.githubusercontent.com/24860501/149487919-815193cd-7f8b-470f-a7ba-7c361aa378f6.png)

würde er hier rauskommen wo er gerade reinfahren will
![fsScreen_2022_01_14_05_56_44](https://user-images.githubusercontent.com/24860501/149488070-e4f24570-60b0-4e0f-b1d7-4209661be515.png)
und könnte nach links lenken, in die Bahn von wo er jetzt gerade kommt und hätte das Abladerohr auf der Gedroschenen seite
lg
andreas

**Comment by andreasthu** [comment]
hier noch der kurs vergrößert:
![ist](https://user-images.githubusercontent.com/24860501/149490607-847adbf8-f1c6-4b7c-8571-436d33436e38.png)
das erste Beet ist korrekt, der Drescher wendet nach dem durchstich immer nach links, somit ist das Rohr immer Frei.
aber am ende des ersten Beetes fährt er eine Bahn zu weit, daher muss er am ende des Durchstiches nach rechts lenken und somit ist das Rohr das ganze Beet auf der Fruchtseite und nie frei zum abtanken.

so sollte es hingegen sein:
![sollte](https://user-images.githubusercontent.com/24860501/149491091-9a741be5-adcf-4465-a063-6a808d5e92e8.png)
wenn er hingegen eine Bahn früher einlenken würde, könnte er danach immer eine Linkswendung machen und das Abtankrohr wäre immer frei zum Abtanken.

lg
andreas

**Comment by Tensuko** [comment]
Das ändert nichts daran, dass der turn richtig funktioniert, nur der generierte Kurs falsch ist.
Es wird immer von grün (turn start) zu rot (turn end) gewendet.
Ich weis, dass du das wohl nicht oder nur schwer sehen kannst.
Daher ist es ein Generatorproblem und nicht vom turn.

**Comment by Tensuko** [comment]
Wir brauchen von genau dem kurs das logfile wenn der Kurs generiert wurde.

**Comment by andreasthu** [comment]
Hallo Tensuko.
Ja sry, der Turn ist ja eh richtig, hab mich ev unklar ausgedrückt.
Der Drescher fährt genau den generierten kurs nach.
Der Kurs sollte aber anders generiert werden.
Damit auch im zweiten Beet das Rohr immer innen ist und der drescher im Beet nach links wendet.
Lg
Andreas

**Comment by pvaiko** [comment]
@andreasthu hier gibt es zwei Tabellen: https://github.com/Courseplay/Courseplay_FS22/blob/be67d859b372b8a1d7f1ddd7a10310533a195a3d/scripts/courseGenerator/center.lua#L741
die die Reihenfolge angeben, abhängig von Uhrzeigersinn und Reihen pro Beet. 

Ich habe keine Zeit drüber nachzudenken aber kann es sein, dass beim ungeraden Zahlen bei den Restreihen müssen wir den Urzeigersinn ändern? In deinem Fall nehmen wir counterclockwise, 5 für das Teil oben und dann counterclockwise, 4, aber clockwise 4 wäre das Richtige.

Wenn du mir ein Regel findest der mit allen Kombinationen funktioniert, kann ich implementieren.

**Comment by andreasthu** [comment]
hallo pvaiko
kann ich mir mal anschauen.
nach welchem system sind die tabellen aufgebaut, bzw wie kann ich die lesen/verstehen?
lg
andreas

**Comment by pvaiko** [comment]
`{3, 4, 2, 5, 1},` heisst z.B. dass es 5 Reihen gibt, und erst wird Reihe 3, dann 4, dann 2, usw bearbeitet.

> im ls19 gingen nur gerade anzahlen (2, 4, 6,... ) einzustellen

Deshalb ist das problem noch nie aufgetaucht. Wir können es auch wieder einstellen.

**Comment by Tensuko** [comment]
Brauchen wir denn wirklich 3 5 7 usw ? Hat das große Vorteile ?

**Comment by andreasthu** [comment]
Hallo ihr zwei
ich habe mir mal einige gedanken gemacht.
@Tensuko 
der vorteil bei 357... ist der das der Verbindungsweg zwischen Beet 1 und Beet 2 kürzer ist, das ist eigentlich schon alles. siehe auf der skizze (4) und (3).

![20220115_094938](https://user-images.githubusercontent.com/24860501/149616402-43741312-f55c-4b5e-b0b6-4e5469ac8d86.jpg)

auf der skizze hab ich bei (1) angefangen.
wenn man immer 5 Reihen/Beet will, muss man jedes 2. Beet die Reihenfolge tauschen 32415 -> 34251 ->32415 -> 34251 ...
hat dann zw Beet 1->2 einen kurzen Verbindungsweg, zw. Beet 2->3 dafür einen langen , 3->4 wieder kurz, 4->5 wieder lang,...

wenn man aber nach 5 Reihen im ersten Beet eine wegnimmt (2) auf 4 Reihen/Beet oder eine dazugibt (3) auf 6 Reihen/Beet dann hat man immer einen kurzen Verbindungsweg.

aber eventuell ist es besser wieder wie im ls19 nur 2 4 6 8 ... Beete zuzulassen.
lg
andreas

**Comment by Tensuko** [comment]
Wow! Da hast du dir ja richtig gedanken gemacht.
Das ist echt super!

Ich glaube auch das es das einfachste ist, erst mal wieder auf gerade Zahlen zurück zu gehen.
Aber vlt kann man das hier als Referenz offen lassen, weil das ist wirklich gut gemacht.

**Comment by rohne83** [comment]
Das ist mir auch schon aufgefallen. Workaround wäre halt erstmal die Anzahl der Bahnen wieder wie im LS19 auf gerade Zahlen zu beschränken. Grundsätzlich interessant wäre es aber schon irgendwann auch wieder ungerade Zahlen zuzulassen sofern die dann auch richtig abgearbeitet werden (siehe Andreas' Skizzen).

Bin mir nicht sicher ob es so gut ist, die Arbeitsrichtung an der Uhrzeigersinn-Einstellung festzumachen. Vielmehr sollte eher allein die Rohrseite entscheidend sein (übrigens nicht nur bei Beeten sondern auch bei spiralförmig wo wir damit ja immer noch Probleme haben). Erstes Vorgewende wird im RL zB tatsächlich meistens gegen den Uhrzeigersinn gedroschen, also mit Rohr über der Frucht. Im 19er ließ sich das mit CP zumindest bei Drescherverbänden auch recht problemlos umsetzen. Klappt aber halt nur wenn die Vorgewende-Richtung keinen Einfluss auf die Arbeitsrichtung in den Beeten/Spiralen hat.

**Comment by pvaiko** [comment]
> Bin mir nicht sicher ob es so gut ist, die Arbeitsrichtung an der Uhrzeigersinn-Einstellung festzumachen. 

Wenn du den Code anguckts wird klar dass es hier nicht um die Uhrzeigersinn-Einstellung aus dem Generator geht. Uhrzeigersinn hier ergibt sich genau aus der Rohrseite.

**Comment by rohne83** [comment]
Danke für die Aufklärung. Dann bin ich ja beruhigt ;)

**Comment by Tensuko** [comment]
> Btw, ist es gewollt dass es hier keine Diskussions-Sektion mehr gibt?

Ist offen.

**Comment by andreasthu** [comment]
Bin gespannt was da noch alles rauskommt. 
Wenn noch was gebraucht wird, lasst es mich wissen.
Lg
Andreas
