### ISSUE TITLE
[Question] Combine harvester problem, not only ..

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#524]
I do not know if it has already been reported, if it is a bug or no, but the problem continues that, if you set that the combine harvester, which must unload at the end of the work, it stops, opens the tube, but remains on in work mode , and does not download. To unlock it, you have to go up, deactivate the CP, in this way, the unloading starts, this disturbs even when used in conjunction with the AD, that the trailer is not called automatically, if the CP is not deactivated. Instead it should in fact stop, open the tube and switch off, effectively deactivating the CP automatically. A similar problem also occurs with other means, which at the end of the work, do not close the tools, in this case, the vehicle switches off and deactivates the CP, but nothing else.
In use and testing version 7.0.0.18 latest manual version of 13 January
![Screenshot_4](https://user-images.githubusercontent.com/24955554/149477416-d7f88fd0-07e6-433b-96f7-e85ba2ae8295.jpg)

**Comment by RealNeo80** [comment]
Communication between AD and CP is not programmed yet. In the Last Version of CP they firstly implemented the interface to AD, so AD needs no to programm theire side

**Comment by Roby1164** [comment]
> Communication between AD and CP is not programmed yet. In the Last Version of CP they firstly implemented the interface to AD, so AD needs no to programm theire side

No, maybe I explained myself wrong?
The problem is that at the end of the work, the machines do not stop, the harvester continues to remain on as if it were threshing, but it stops, opens the tube, and even if you manually go under with a trailer it does not unload anything, you have to salt on the combine harvester, and manually turn off the CP, otherwise it remains there waiting for a command that never arrives, that is, that of the end of work. For this reason, even if you want to use the trailer with the AD, it does not move, it does not leave to go to unload the combine, which it does regularly, when the work is still running in the field, in that case the combine. when it is full, it stops regularly, turns off the blade, opens the hose, and calls the trailer, which with AD arrives regularly without problems, unloads, and goes back to work.

I am aware that the integration, between CP and AD, is not yet complete, but that between combine harvester and wagon is already working, since they are not connected directly, but the wagon only needs that the combine has your open .

**Comment by Tensuko** [comment]
That is the problem and as long as the connection is not there we won't change it.

**Comment by Roby1164** [comment]
???? Sorry, what connection ??
As I am trying to explain is that, there is the problem that at the end of the work the vehicles do not switch off, they do not really finish the job, and in the case of the combine harvester, it is not possible to unload it, otherwise by manually deactivating the CP. This is the real problem, not that there isn't a full integration with AD yet ....
Leaving the combine on there, waiting for it to be turned off, to unload it manually, is not nice, convenient and cheap, if then maybe it runs out of fuel ...
