### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by Laczkovics111** [Courseplay/Courseplay_FS22#526]
Replacing the missing part of the Hungarian translation for Courseplay v.7.0.0.19.

[Curseplay_translation_hu_Update_v.7.0.0.19.zip](https://github.com/Courseplay/Courseplay_FS22/files/7871162/Curseplay_translation_hu_Update_v.7.0.0.19.zip)

**Comment by Tensuko** [comment]
Pls do that with a pull request.
