### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by tuzlo** [Courseplay/Courseplay_FS22#527]
**Steps to reproduce**
Load CP version 18 or 19 and Vehicle control addon

**Actual behavior**
Mini gui closes as soon as you open it

**Screenshots**
none available

**Courseplay version**
version 18 or 19

**Log**
log file is useless, nothing appears in the log file

**Map**
Any

**Vehicles/ implements involved**
Any, stock or modded

**Comment by Tensuko** [comment]
> log file is useless, nothing appears in the log file

It is never useless!

**Comment by Tensuko** [comment]
Can't reproduce with CP 7.0.0.19 and VCA from ModHub.
Maybe you guys have duplicate keybinds ?

**Comment by RealNeo80** [comment]
no, i just updated to 7.0.0.19 with 18 it was working fine

**Comment by Tensuko** [comment]
So this is just a keybind conflict that we can't solve but just yourself :)
Keybinds - A nerver ending story.
