### ISSUE TITLE
[Question] Possible Feature

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#529]
With all the production chains in FS22, are you considering a mode to pickup the pallets and load trailers with Forklift or equipment with pallet forks?

I do know you can auto distribute and auto sell directly from the productions, but there is a surcharge on that.

**Comment by Tensuko** [comment]
Pallets are not so easy to handle nad if anything goes wrong, what to do ?
There is just to much involved to make that possible.
Also... a bit of fun in the game should stay to the player ;)
