### ISSUE TITLE
Harvester cannot open pipe for unload

### ISSUE THREAD

**Issue by tigranhov** [Courseplay/Courseplay_FS22#53]
Additional info:
Tried with default settings, always unfold pipe setting, stop while unloading setting
Tried on 2 combines, the Nova 330, Case IH 7150
Courseplay Version: 7.0.0.3

As a result, pipe starts twitching, videos below

https://user-images.githubusercontent.com/2148849/147374072-9705da1a-d1ad-45b2-9889-4aa4844f2f1a.mp4

https://user-images.githubusercontent.com/2148849/147374343-88b90736-0065-457b-b61c-dcbeec66f5cc.mp4

**Comment by Tensuko** [comment]
That will be fixed in the next version, the fix is already on the master branch. :)
