### ISSUE TITLE
Ballen Wickeln / Sammeln auch für Wiese

### ISSUE THREAD

**Issue by Vansan85** [Courseplay/Courseplay_FS22#532]
The ball wrapping / collecting does not start on an original meadow (Map Erlengrat).
There is the message" no field found" shown.

Is it possible to ad this feature?

Best regards Vansan and thanks for your great work

Das Ballen Wickeln/Sammeln startet auf einer original angelegten Wiese nicht ( Map Erlengrat).
Es kommt die Meldung kein Feld gefunden.

Ist es möglich das anzupassen?

Mfg Vansan

**Comment by Tensuko** [comment]
@pvaiko 
Das müsste irgendwie so funktionieren:
Zielpunkt auf die Wiese setzen + Job starten. (alternativ, auf Wiese fahren, Helfer mit sammel/wickel Ballen starten)
Feldrand scannen (wie beim Generator).
Suchbereich auf diesen Feldrand begrenzen.

Sollte so machbar sein, ohne Feldrandkurse extra speichern zu müssen.

**Comment by 60erjonny** [comment]
Dazu will ich hier auch was beitragen. 
Bei zusammen gelegte Feldern, erkennt er das "Nachbarfeld " nicht mehr und beendet seine Arbeit....fahre ich dann ein paar Meter weiter so erkennt er die darauf liegenden Ballen wieder..
![fsScreen_2022_01_14_21_46_09](https://user-images.githubusercontent.com/63659182/149584918-92b598f0-3631-4d6c-8b0e-6f3cf851d0a4.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7873211/log.txt)
.

**Comment by Mike1977** [comment]
> @pvaiko Das müsste irgendwie so funktionieren: Zielpunkt auf die Wiese setzen + Job starten. (alternativ, auf Wiese fahren, Helfer mit sammel/wickel Ballen starten) Feldrand scannen (wie beim Generator). Suchbereich auf diesen Feldrand begrenzen.
> 
> Sollte so machbar sein, ohne Feldrandkurse extra speichern zu müssen.

Wie willst du denn den Feldrand scannen, wenn es sich um kein Feld, sondern einfach eine Wiese handelt?

**Comment by mfehr94** [comment]
> > @pvaiko Das müsste irgendwie so funktionieren: Zielpunkt auf die Wiese setzen + Job starten. (alternativ, auf Wiese fahren, Helfer mit sammel/wickel Ballen starten) Feldrand scannen (wie beim Generator). Suchbereich auf diesen Feldrand begrenzen.
> > 
> > Sollte so machbar sein, ohne Feldrandkurse extra speichern zu müssen.
> 
> Wie willst du denn den Feldrand scannen, wenn es sich um kein Feld, sondern einfach eine Wiese handelt?
> Es bräuchte schon erstmal einen Weg den zu bearbeitenden Bereich festzulegen. Das ging früher ganz gut mit dem einfahren eines Feldrandes.

Der dunkel grüne Bereich in der Map wird als Feld erkannt und der Kurs wird berechnet

**Comment by Mike1977** [comment]
Wo in den Markierten Zonen gibt es denn einen dunkelgrünen Bereich?

![Unbenannt](https://user-images.githubusercontent.com/5852750/149999151-e1fbf41e-795d-4559-a601-170bbe1951f7.png)

**Comment by mfehr94** [comment]
> @mfehr94
> Wo in den Markierten Zonen gibt es denn einen dunkelgrünen Bereich?
> 
> ![Unbenannt](https://user-images.githubusercontent.com/5852750/149999151-e1fbf41e-795d-4559-a601-170bbe1951f7.png)
> 

Das isue bezieht sich auf Map Erlengrat und da ist das so z.B die 2 Wiesen die man schon am Start Besitz

**Comment by 60erjonny** [comment]
Blöde Alternative, diesen Bereich pflügen, um ein Feld zu erstellen. Um dann darauf wieder, Gras anzusähen...

**Comment by Vansan85** [comment]
Auf der Erlengrat sieht man die Wiesen auf der Map...
![Erlengrat](https://user-images.githubusercontent.com/97761944/150129523-2f5777bf-5d34-4811-9dc6-7d565bbfc113.jpg)
.

Bei den anderen nicht gekennzeichneten Wiesen wird es nur mit Pflügen gehen.

**Comment by Vansan85** [comment]
Ich habe jetzt mal Wiesen auf der Erlengrat gepflügt und bin auch mit Feld Erstellen außen rum gefahren.
Es wird trotzdem nicht als Feld erkannt
![Erlengrat1](https://user-images.githubusercontent.com/97761944/150596203-d2695b68-435b-47e6-b110-07da5c2a8762.jpg)
.

**Comment by 60erjonny** [comment]
Zitat: ...und bin auch mit Feld Erstellen außen rum gefahren.
Es wird trotzdem nicht als Feld erkannt...

Ok, wie genau hast du das gemacht...? 
Weiß jetzt nicht wie du das meinst...

**Comment by Vansan85** [comment]
Ich bin mit der Pflug Feld erstellen Funktion außen Herum gefahren und habe dann die ganze Wiese selbst umgebrochen und neu eingesät.

**Comment by 60erjonny** [comment]
Konntest du dann, sähen mit CP...? Kannst du düngen mit CP...?

**Comment by Vansan85** [comment]
Das ging vorher schon auf den Wiesen. Ich hab die ja auch mit CP gepflügt. Alles von CP hat funktioniert nur das Ballensammeln und Wickeln. Deswegen habe ich diesen Issue eröffnet.

**Comment by 60erjonny** [comment]
ok...

**Comment by Mr-Anivex** [comment]
I am having this issue as well. I have plowed a meadow into a field, and even lined it with gravel to make it easier to define. All of my tools worked fine on the field, but when I went to wrap bales, I get an error. 

I've tried generating a course with the starting waypoint set as "collecting and wrapping bales", but my tractor just runs the course at full speed ignoring bales. If I select the field in the menu without a course, but with a target position and the field selected, the tractor will go to the target postition and just sit there, with the worker still on, but the tractor not moving. 

If I just use the HUD with no course and collecting and wrapping bales as my starting waypoint, I'm told there is no field, even though I'm sitting in the middle of the field. 

I have also tried making a custom course around the field, but that did not help my situation.

**Comment by maxarndt** [comment]
> I am having this issue as well. I have plowed a meadow into a field, and even lined it with gravel to make it easier to define. All of my tools worked fine on the field, but when I went to wrap bales, I get an error.
> 
> I've tried generating a course with the starting waypoint set as "collecting and wrapping bales", but my tractor just runs the course at full speed ignoring bales. If I select the field in the menu without a course, but with a target position and the field selected, the tractor will go to the target postition and just sit there, with the worker still on, but the tractor not moving.
> 
> If I just use the HUD with no course and collecting and wrapping bales as my starting waypoint, I'm told there is no field, even though I'm sitting in the middle of the field.


@Tensuko I'm encountering the issues mentioned by @Mr-Anivex with the recently released version `7.0.0.27`. Should this issue be fixed in this release or is there still some work left?

**Comment by Mr-Anivex** [comment]
My issue was actually resolved with the latest patch. I made a custom field using the recorder, saved it, then used the HUD to start my work, setting it to collecting and wrapping bales with no course selected. 

Be sure you don't have a course currently loaded on your tractor.

**Comment by maxarndt** [comment]
I can confirm, it works with custom fields. 
I was wondering if it is supposed to work with the default meadows on the map.
