### ISSUE TITLE
[Feature] Alte HUD von LS19

### ISSUE THREAD

**Issue by ralfmuehle** [Courseplay/Courseplay_FS22#534]
Hallo,

erstmal danke für den super Mod und die schnelle Konvertierung zum LS22. 
Nun zu meiner Frage: wäre es möglich die alte UI vom LS19 wieder einzubauen. Fand die Bedienung von CP darüber um einiges einfacher und schneller.

**Comment by mfehr94** [comment]
Wäre echt nett wenn ihr bitte mal die Suche verwenden und das Wiki lesen würdet. Wurde bereits tausend Mal beantwortet. Es wird nicht passieren.
