### ISSUE TITLE
CP Helfer pflügt nicht sauber

### ISSUE THREAD

**Issue by SAM24986** [Courseplay/Courseplay_FS22#536]
**Steps to reproduce**
Mod Pflüge und Basisspiel-Pflüge benutzt, 

**Actual behavior**
Der CP helfer dreht die Pfüge nur sporadisch hin und wieder mal, lässt auch gerne mal den einen oder anderen Streifen stehen, senkt den Pflug zu früh.  Den Modpflug dreht CP gar nicht, der Helfer aus dem Spiel hat damit gar keine Probleme. Mit dem Kverneland Pflug aus dem Spiel geht es ein bisschen besser, ich habe aber aber auch hier festgestellt dass es ein bisschen von der Breite des Vorgewendes abhängt. Den Job starten aus dem Hauptmenü will er auch nicht, er fährt zum Feld, klappt den Pflug aus und bleibt dann stehen und fährt nicht zur Startposition. Startet man den Helfer aus dem "Mini HUD" dann funktioniert es.

**Courseplay version**
Version used: 7.0.0.19

**Log**
Map played on.

**Vehicles/ implements involved**
Fendt 724 und Kvernland Pflug aus dem Spiel
Vogel und Noot Pflug Mod

**Relevant script mods**
Zum testen der Funktion sind außer dem Modpflug und CP keine weiteren Mod im Ordner

Das hat der Basishelfer geplügt
![fsScreen_2022_01_15_09_24_07](https://user-images.githubusercontent.com/59346694/149616229-133e0a90-acc5-455a-b87e-706273a93152.png)

Das hat CP gepflügt
![fsScreen_2022_01_15_09_27_24](https://user-images.githubusercontent.com/59346694/149616256-947741d5-579d-4208-958b-d7852d485d99.png)

**Comment by Tensuko** [comment]
log wie im wiki beschrieben anhängen und nicht auf irgend einer upload seite!
https://github.com/Courseplay/Courseplay_FS22/wiki

**Comment by SAM24986** [comment]
<script src="https://gist.github.com/SAM24986/60930a7442629e3b642ff11d871fa1ce.js"></script>

**Comment by SAM24986** [comment]
Sorry, hab ich nicht gelesen.
https://gist.github.com/SAM24986/6d7c86e97556759462f02a5e891d0d1e

**Comment by Tensuko** [comment]
@pvaiko 
Pflug wird im Pathfinder turn nicht rotiert wie es scheint.
Auch der Versatz ist im turn End damit nicht richitig so entstehen diese Ecke und auch die nicht gearbeiteten Streifen zwischen den Bahnen.

**Comment by Tensuko** [comment]
Plow rotation is now working correct.

**Comment by Alfdinox** [comment]
i also had the issue with Courseplay 7.0.0.20
with every vehicle and plow 
with or without mods
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7891853/log.txt)

**Comment by SAM24986** [comment]
> Die Pflugdrehung funktioniert jetzt korrekt.

Nun denn, nein, Pflügen ist definitiv keine Stärke von CP. Auch mit dieser Version klappt das nicht...
Siehe Bilder
![fsScreen_2022_01_18_23_33_50](https://user-images.githubusercontent.com/59346694/150030484-6ea40d42-627a-4d74-8790-57de2eab8304.png)
![fsScreen_2022_01_18_23_33_54](https://user-images.githubusercontent.com/59346694/150030587-cc5a0cc1-a553-4e00-94d6-7cdf280eb84c.png)
![fsScreen_2022_01_18_23_33_58](https://user-images.githubusercontent.com/59346694/150030612-cab77dca-8352-45d1-8bbe-ad97415aa2a3.png)
![fsScreen_2022_01_18_23_33_08](https://user-images.githubusercontent.com/59346694/150030696-d06745f4-5675-45f9-a125-d0b42fe24560.png)

Log txt:
https://gist.github.com/SAM24986/a6f8577f9c03524508f2363939849212

**Comment by pvaiko** [comment]
> Nun denn, nein, Pflügen ist definitiv keine Stärke von CP. Auch mit dieser Version klappt das nicht...

Nun denn, nein, eine genaue Problembeschreibung ist definitiv nicht deine Stärke. Inzwischen versuche es mit Pathfinder Turns ausgeschaltet...

**Comment by SAM24986** [comment]
> Nun denn, nein, eine genaue Problembeschreibung ist definitiv nicht deine Stärke. Inzwischen versuche es mit Pathfinder Turns ausgeschaltet...>

Hallo, ja, sorry, tut mir leid, war irgendwie nicht mein Tag gestern und zudem auch zu spät. Man ist zu unkonzentriert wenn man müde wird. 
Ich werde das heute Abend noch mal ausprobieren, habe aber das Gefühl dass es nicht an dem Wendmanöver liegt sondern eher an der Berechnung der Arbeitsbreite. Auf den Bildern ist zu sehen dass der Turn eigentlich gut funktioniert, aber die Arbeitsbreite nicht stimmt. Auf dem einen Foto ist zu erkennen dass der Helfer nach den Einsetzen des Pfluges schräge fährt und die Spur korrigiert. Das er dann den Pfug nicht dreht liegt dann evtl an der falschen Arbeitsbreite?

**Comment by pvaiko** [comment]
Was nicht klar war (und es ist immer noch nicht): dreht er jetzt oder nicht? Wenn nicht, dann nie oder nur ab und zu, bei jeden zweiten Reihe nicht? Nur dieser Pflug? Wenn er nicht dreht, dann wird der immer schräge fahren weil der Turnberechnung wird mit dem gedrehten Pflug berechnet.

**Comment by Alfdinox** [comment]
Also bei mir ist es das er den Pflug am Start in die richtige Position bringt. 
Danach beim Wendemanöver den Pflug in Mittelstellung bringt und dann ihn so absenkt und weiterfährt.
Das passiert mit jedem Originalen Pflug ( bei Pflügen ohne diese Mittelstellung dreht er den Pflug gar nicht) und auch mit einem Mod Pflug.
Habe es auf allen Maps getestet und ebenfalls auf einer Mod Map ebenso mit verschieden Zugmaschinen.

**Comment by pvaiko** [comment]
Hättest du ein Log mit Debug an noch beigefügt...

**Comment by Tensuko** [comment]
Works a lot better with 7.0.0.21

**Comment by SAM24986** [comment]
> Works a lot better with 7.0.0.21

Hallo, 
leider bin erst heute dazu gekommen die jetzt neueste Version zu testen. Was soll ich sagen.....

Ihr habt nen' super Job gemacht, das funktioniert jetzt tadellos.
Vielen vielen Dank, echt Klasse
Bis auf ein paar kleine Stellen alles tadellos umgedreht.
![fsScreen_2022_01_21_18_01_57](https://user-images.githubusercontent.com/59346694/150594137-bf1e2efb-691f-4fdc-995b-abc58b27d505.png)
Der Modpflug lässt noch ein bisschen mehr stehen am Vorgewende, aber das liegt, denke ich, eher am Pflug, da werde ich nochmal feinjustieren
![fsScreen_2022_01_19_21_05_55](https://user-images.githubusercontent.com/59346694/150594381-32a30874-4326-4d60-a5f6-c1405294aaab.png)

Nochmals vielen Dank

**Comment by Alfdinox** [comment]
Hallo zusammen

also ich habe es heute erst testen können und muss sagen dass, das Pflügen etwas besser funktioniert.
Leider funktioniert das drehen des Pfluges immer noch nicht so recht.

1.Beim ersten Wendemanöver holt er nicht weit genug aus druckt den Pflug dabei nach oben und stellt den vorderen Teil auf ca. 45° und so bleibt er dann.

![1](https://user-images.githubusercontent.com/75907452/150653818-2cbe7499-4c4c-4b5a-946f-b119c01d5809.jpg)
![2](https://user-images.githubusercontent.com/75907452/150653820-a9bf1722-55cc-4a99-9f64-b1dfec3d46ae.jpg)
![3](https://user-images.githubusercontent.com/75907452/150653815-319e80e0-3d91-4ca6-94f1-a683d0646713.jpg)

2. Das komplette drehen des Pfluges Kvernland PW100-12 funktioniert immer noch nicht wie in den Bildern zu sehen er bleibt immer noch in der Mittelstellung und senkt ihn so ab.
![4](https://user-images.githubusercontent.com/75907452/150653857-35227b03-cd33-42a8-aeac-fb5342a381a7.jpg)
![5](https://user-images.githubusercontent.com/75907452/150653858-f71ca235-9624-48f5-92d3-88570bb1188b.jpg)

und hier noch die Log Datei:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7919178/log.txt)

**Comment by Alfdinox** [comment]
Hallo 

reagiert hier noch jemand oder soll ich ein neues issue aufmachen zu meinem Problem :)

**Comment by pvaiko** [comment]
Fix kommt mit dem kommenden Release.

**Comment by Alfdinox** [comment]
> Fix kommt mit dem nächsten Release.

ok alles klar vielen dank für die Antwort
