### ISSUE TITLE
CP für den Multiplayer

### ISSUE THREAD

**Issue by Icke09** [Courseplay/Courseplay_FS22#538]

**Comment by Tensuko** [comment]
Bevor hier irgendwas sinnvolls geschrieben wird, lesen hilft (Code -> runter scrollen!)

**Comment by Icke09** [comment]
Sorry die Frage wurde versehentlich zu früh gepostet. Ich habe aber in den Issues keine Einträge diesbezüglich gefunden und wollte deshalb nur wissen ob es CP iwann auch im Multiplayer geben wird oder nicht... Was bedeutet (Code-> runter scrollen) . Stehe da wohl ein wenig aufm Schlauch...

**Comment by Icke09** [comment]
Hat sich geklärt.....

**Comment by mfehr94** [comment]
@Icke09 ich glaube er meinte das [Wiki](https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ#will-multiplayer-support-come-back)

**Comment by Tensuko** [comment]
Nein ich meinte oben auf Code klicken und dann runter scrollen, da ist der Readme Teil und da steht in großen Buchstaben etwas zum Multiplayer.
