### ISSUE TITLE
[Enhancement] Gerät etwas zu früh abgesenkt, pahtfinder turn obwohl start und ende dicht beisammen ?

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#539]
**Steps to reproduce**
Traktor mit Grubber - in meinem Fall Köckerling Flatline - und dann Kurs generieren
![Screenshot_4](https://user-images.githubusercontent.com/78980660/149620527-2b3237e8-63fb-4da8-999f-18987852ead4.png)

**Actual behavior**
CP wendet zu ausladend und umständlich 

**Expected behavior**
CP wendet in einem sauberen Kreis mit zurücksetzen

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/78980660/149620467-e2e66e42-53a6-43a6-a6f4-03de7a4d8a5b.png)
![Screenshot_2](https://user-images.githubusercontent.com/78980660/149620469-d274ffbe-1226-4d0a-be0a-96c1f369bd90.png)
[Screenshot_3](https://user-images.githubusercontent.com/78980660/149620471-2fb50a1e-e842-4b69-81c9-e0b55c186844.png)

**Courseplay version**
Version used: 2.0.0.19

**Map**
Elmcreek

**Comment by Tensuko** [comment]
logfile mit debug und vorallem screenshot mit debug damit man sieht was du meinst.

**Comment by 0scarZulu** [comment]
Mach ich später. Aber man sieht doch klar wo er nach der Wende einsetzt und dann im V morgewende schon arbeitet.  Die erste Bahn von links hat er eingesetzt, die zweite kam er zurück und ist gerade in der Wendung zum erneuten einsetzen. Und setzt dann wieder so zeitig ein das er durchs Ganze VG zieht

**Comment by RealNeo80** [comment]
Zauberworte Gerät senken/heben früh spät? wie ist das eingestellt bei dir

**Comment by 0scarZulu** [comment]
@RealNeo80 sieht so aus :D 
![Screenshot_1](https://user-images.githubusercontent.com/78980660/149636807-b35b76b6-05d6-47ec-9a37-8e2ce646c470.png)


@Tensuko hier die Log .. was noch? 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7875843/log.txt)

**Comment by Tensuko** [comment]
Debug im Fahrzeug war eingeschaltet ?

**Comment by 0scarZulu** [comment]
ich habe es über umschalt+1-4 aktiviert wenn du das meinst .. oder welches meinst du? gsVehicleDebug? War auch an

**Comment by Tensuko** [comment]
was ist gsVehicelDebug
Ich meine im Fahrzeug Einstellungs Menü von uns.

**Comment by 0scarZulu** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/78980660/149638032-68b2cd81-c9b9-4bc4-ab51-0e10e4df27f6.png)
![Screenshot_3](https://user-images.githubusercontent.com/78980660/149638034-4e9bb4db-0b08-4f60-9b97-f05dff3fb773.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7875904/log.txt)

**Comment by Tensuko** [comment]
Ich frage mich gerade eher wie diese turns wieder zu stande kommen, obwohl start und stop so dicht beisammen sind.

**Comment by 0scarZulu** [comment]
Gut, das kann ich dir nicht beantworten :D Brauchst noch was?

**Comment by Tensuko** [comment]
Ne passt schon, aber das ist so erst mal kein bug, das ist eher enhancement...

**Comment by Strawberry93** [comment]
Ich bin da auch der Meinung das dadurch die Übergänge vom Vorgewende zu Bahn hoch/Runter unsauber vom CP Helfer bearbeitet werden.

**Comment by Tensuko** [comment]
> Ich bin da auch der Meinung das dadurch die Übergänge vom Vorgewende zu Bahn hoch/Runter unsauber vom CP Helfer bearbeitet werden.

Sry aber eine Meinung ohne weitere Informationen wie Bilder Tools benutzt, logfile mit debug usw usw nützt das gar nichts...
Ich bin der Meinung das funktioniert bisher sehr gut! So und nun ? :)

**Comment by SaschaLie** [comment]
Das selbe Problem hatte ich ähnlich schonmal geschildert! Wurde leider sofort als Geschlossen makiert mit dem Comment: Und, wird das Feld denn nicht sauber bearbeitet?
![grub2](https://user-images.githubusercontent.com/96572157/149663177-2b7099e1-a330-4827-8585-caf043c43356.jpg)

**Comment by Strawberry93** [comment]
![fsScreen_2022_01_16_16_31_56](https://user-images.githubusercontent.com/16910900/149666865-fe958a60-3915-4fca-83b7-827fa3bc7c5f.png)
![fsScreen_2022_01_16_16_31_58](https://user-images.githubusercontent.com/16910900/149666868-e94b1d85-7201-43e8-9adf-28c0417b52e3.png)
![fsScreen_2022_01_16_16_32_02](https://user-images.githubusercontent.com/16910900/149666870-0152f52f-5ce6-4ac7-a3a9-9acb5bf51436.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7877260/log.txt)

So ich habe das mal reproduziert. Der Pathfinder kommt beim Wenden vom Vorgewende zu den Bahnen nicht.

Ja leider ist der Umgang hier manchmal nicht so nett, als ob wir Spieler den Entwickler der Mod immer was böses wollen oder sie persönlich Angreifen was ich mit meinen Aussagen die ich hier geschrieben habe nicht zum Ausdruck bringen möchte.

**Comment by Tensuko** [comment]
@Strawberry93 
Das geht nicht darum das wir uns angegriffen fühlen, es geht darum das uns gewisse Aussagen einfach keinen Stück weiter bringen...
Wir brauchen Daten.
Was bringt ein Issue mit 10 Meinungen, wenn nicht eine davon Informationen enthält, mit denen wir etwas anfangen können?
Nur wenige begreifen das und das sich ständige wiederholen müssen, obwohl wir alles mögliche an Infos bereitstellen (Wiki, Templates, Stickys, Readme usw) ist schon irgendwann nervig...

Wir gucken uns das an wenn wir die Zeit dazu haben, es sind auch noch weitere Verbesserungen geplant...

**Comment by 0scarZulu** [comment]
Also was ich noch sagen kann es kam erst mit einem Update rein das Problem. Die Wende klappte mal sauber.

**Comment by rohne83** [comment]
Wende auf dem Feld aktiviert und Pathfinder darf rückwärts fahren deaktiviert? Bei deinem letzten Screenshot hat er ja deutlich mehr Platz auf dem Vorgewende um innerhalb der Feldgrenzen zu wenden. Auf deinen anderen Screenshots dagegen ist das Vorgewende ziemlich schmal. Wenn da Wende auf dem Feld aktiv ist, wird er da natürlich viel mehr ausholen müssen um ohne Rückwärtsfahrt wenden zu müssen. Interessant finde ich eher, dass er die Wende in deinem fünften Screenshot tatsächlich so gut hinbekommt (da gabs im 19er mal ein Issue wo genau solche Wendemaneuver vorgeschlagen wurden, aber hätte nicht gedacht dass das schon umgesetzt wäre).
Einzig das mit dem frühen Tool absenken sieht etwas unschön aus, aber von der Texturoptik abgesehen hat das ja keinerlei andere Auswirkungen. Das Feld wird ja trotzdem sauber abgearbeitet. Besser zu früh einsetzen als zu spät.

**Comment by SaschaLie** [comment]
Herzlichen Dank für die Antwort. Das Problem ist, wenn die so in einem Bogen fahren, klemmt der Grubber das innere hintere Rad des Tracktors ein, welches dann stehen bleibt. Auch durch das in der Kurve Absenken wird an den „Schnittpunkten“ teilweise eine kleine Fläche nicht gegrubbert wegen der Kurve, wo ich dann von Hand nachfahre. Er fährt im Bogen schon in die Bahn ein, wo er eigentlich noch etwas zurücksetzen müsste. Alle Einstellungen sind bei allen Bildern und Tracktoren  die Gleichen. 
Wende auf dem Feld ist aktiviert und Pathfinder darf rückwärts fahren ist aktiviert. 
Wie gesagt, es war ja nur ein Hinweis, absolut keine Kritik. Man kommt ja so zurecht, ist nur nicht sehr schön. Ich dachte auch eher, daß evtl. jemand anderes eine andere Idee hätte

Gruß und Danke sehr, Sascha

Gesendet von Mail für Windows

Von: rohne83
Gesendet: Sonntag, 16. Januar 2022 23:57
An: Courseplay/Courseplay_FS22
Cc: SaschaLie; Comment
Betreff: Re: [Courseplay/Courseplay_FS22] [Enhancement] Gerät etwas zu früh abgesenkt, pahtfinder turn obwohl start und ende dicht beisammen ? (Issue #539)

Wende auf dem Feld aktiviert und Pathfinder darf rückwärts fahren deaktiviert? Bei deinem letzten Screenshot hat er ja deutlich mehr Platz auf dem Vorgewende um innerhalb der Feldgrenzen zu wenden. Auf deinen anderen Screenshots dagegen ist das Vorgewende ziemlich schmal. Wenn da Wende auf dem Feld aktiv ist, wird er da natürlich viel mehr ausholen müssen um ohne Rückwärtsfahrt wenden zu müssen. Interessant finde ich eher, dass er die Wende in deinem fünften Screenshot tatsächlich so gut hinbekommt (da gabs im 19er mal ein Issue wo genau solche Wendemaneuver vorgeschlagen wurden, aber hätte nicht gedacht dass das schon umgesetzt wäre).
Einzig das mit dem frühen Tool absenken sieht etwas unschön aus, aber von der Texturoptik abgesehen hat das ja keinerlei andere Auswirkungen. Das Feld wird ja trotzdem sauber abgearbeitet. Besser zu früh einsetzen als zu spät.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tensuko** [comment]
Update für turns ist auf dem Weg.
Genauso werde ich einen Wiki Eintrag machen (basierend auf den Kommentar im Code), der die Auswahl des Turns verdeutlicht.
Dinge die dann nicht so laufen wie gewollt (dazu zählt NICHT das zu frühe absenken oder anheben) schauen wir uns an.

Frühes und spätes absenken/anheben ist als Setting implementiert.
Sollte keine Kombination der Einstllungen zum Erfolg führen, schauen wir was machbar ist.

Aber erneut die Bitte darum:
Logdaten mit debug aktiviert!
Alles andere hilft nicht!

**Comment by Tensuko** [comment]
Turns should work better now.
Pls read our Wiki article about the turns.
