### ISSUE TITLE
[BUG_SP] lua error

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#545]
7.0.0.19

not reproducable at the moment, just seen it, if i know more i sent you a log

![image](https://user-images.githubusercontent.com/8066324/149651779-ce38c70e-96a7-4dc0-8d00-e2bd64684b32.png)

i think its coming from the JD 8RX and the Amazone Citan

Got another one after finishing course (reproducable after each course)
dataS/scripts/vehicles/specializations/AIFieldWorker.lua(254) : attempt to index local 'driveStrategy' (a nil value)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7876581/log.txt)

**Comment by Tensuko** [comment]
The end Error is fixed on main, the 1st need to be checked.

**Comment by Tensuko** [comment]
Still a problem with .20 ?

**Comment by RealNeo80** [comment]
not updated yet, will do it this evening
