### ISSUE TITLE
[BUG_SP] Bale Loaders

### ISSUE THREAD

**Issue by lgxxxxx** [Courseplay/Courseplay_FS22#547]
Hello and thank you for the amazing work!

Commits 8646ffe212e7885f73e8e315c8a863b39d3cca15 and the next to the last do not work well
Тhe bale collector misses the nearby bale and goes to the next one. Then he starts moving backwards until he stops in an obstacle and the course turns off. 
In fact, once I start it elsewhere on the map, it starts moving backwards.
Commit 0070f547bf8b78026f22a45ae16435aa5fd4d1d6 work good 

**Screens
![1](https://user-images.githubusercontent.com/11899013/149656869-dee6993b-1110-4ae4-afaf-c2cdf5d91cff.jpg)
hots**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7876742/log.txt)

**Comment by Tensuko** [comment]
I don't get it, when you say us that one commit does not work well but a later commit works good, is it still not working then or what happens ?!

We have a Template on purpose!

**Comment by lgxxxxx** [comment]
Commit 0070f54 is the last one working well.
Sorry for my poor English

**Comment by Tensuko** [comment]
So it is fixed ?

**Comment by lgxxxxx** [comment]
No. when I open Commits are sorted by date and time. so i wrote that after this Commit 0070f54 all the newer ones don't work.
I apologize for our language barrier. I'm trying to help.

**Comment by Tensuko** [comment]
We have a look.

**Comment by pvaiko** [comment]
This has been fixed in 1f15bd28
