### ISSUE TITLE
Courseplay

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#548]
Bin gespannt, wann es klappen wird mit einem Ladewagen das Stroh zu sammeln.
Bin jetzt schon begeistert vom Courseplay. Ihr macht wirklich eine gute Arbeit. Ich könnte es nicht. Großen Respekt habe ich vor Euch. Macht bitte weiter so. Danke an die Entwickler.

**Comment by Tensuko** [comment]
Gibt doch genug Info dazu bereits auf GitHub, dafür muss man wirklich kein neues Issue aufmachen.....

**Comment by StefanTreutler1974** [comment]
OK. Ich dachte ja nur 😁--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.01.22, 12:47 schrieb Tensuko ***@***.***>:

   
  Gibt doch genug Info dazu bereits auf GitHub, dafür muss man wirklich kein neues Issue aufmachen.....
