### ISSUE TITLE
Ballen pressen

### ISSUE THREAD

**Issue by Matzenie** [Courseplay/Courseplay_FS22#55]
Hallo Leute, 
Das funktioniert soweit super nur etwas ungewohnt wenn man die LS19 Version kennt.
Ich habe den Kurs von meinen Mähwerken zwar gespeichert und in den Traktor mit der Presse geladen. Leider will der Traktor mit der Presse dran nur freies Fahren auf der Straße. Ich habe die 7.0.0.3 verwendet. Ich würde mal behaupten hier braucht ihr keine Log. 
Macht euch keinen Stress. Genießt erstmal die Feiertage.

**Comment by Tensuko** [comment]
Bitte nach bereits vorhandenen Issues schauen :)
#21
