### ISSUE TITLE
Ordner

### ISSUE THREAD

**Issue by Fitti-1983** [Courseplay/Courseplay_FS22#557]
Hallo zusammen, ich habe folgendes Problem bei CP. Ich kann nur 3 Buchstaben in einen Ordner oder Feldkurse zum Speichern eingeben. Könnt ihr mir da irgendwie helfen. Danke im voraus.

**Comment by Tensuko** [comment]
Wir wissen nicht wann und wodurch das passiert, solange wir keine steps zum reproduzieren haben, können wir da nichts machen, sry.
