### ISSUE TITLE
[BUG_SP] Wonky driving with Dollied implements

### ISSUE THREAD

**Issue by flederboa** [Courseplay/Courseplay_FS22#558]
**Steps to reproduce**
Drive a Course with a Bourgault Paralink Seeder or other implement with simillar "dolly
" steering

**Actual behavior**
Worker doesnt follow the Course correctly and starts pulling to one side and driving slower.  behavior stops when switching into vehicle or if its in visual range (thats the really weird bit)

**Expected behavior**
Normal driving of the Course.

**Screenshots**
(https://imgur.com/a/pLFdZEN)

**Courseplay version**
v7.0.0.19

**Log**
https://pastebin.com/bM5aYvhX

**Map**
No man's land

**Vehicles/ implements involved**
JD 9620 r  +  Bourgault Paralink how drill  +  7950 Air Cart
 drill+air cart are mods

**Relevant script mods**
Autodrive installed but not involved

**new Bug after v7.0.0.20**

Courseplay does not recognize the air cart as a seed or fert tank and doesnt work.
https://imgur.com/a/j30wVQE
The ingame helper works.

So because of this i cant recreate the previous issue.

**Log**
https://pastebin.com/QAB0cNgn

**Comment by Tensuko** [comment]
I haven't seen those seeder as mods on modHub and I am pretty sure we have a "attach logfile" section on that Template...
So where is it ?

**Comment by flederboa** [comment]
https://pastebin.com/bM5aYvhX

No idea if im doing this right

**Comment by Tensuko** [comment]
Thats correct.
But I would rather like to see what is the air cart dooing there.
Is it possible that you make a video of it when this happening ?
+ debug active for that vehicle (scroll down on the settings page)

**Comment by flederboa** [comment]
Can you give me 1-2 days?
dont have alot of time to recreate it as of now.

**Comment by Resandise** [comment]
I had a similar issue when using Dalbo Mega Roll 2430 on field 44 of Haut-Beyleron.  That field has a large degree of slope and the roller wants to slide down the slope, which to me would be Physics at work.

**Comment by flederboa** [comment]
So i downgraded to 7.0.0.19 BC of the reasons stated in the original post.

I couldnt find any mods with the same "architecture" dollys and things.
Log
https://pastebin.com/3YKv1LQM
Some gifs
https://imgur.com/a/I0sMrSx

**Comment by pvaiko** [comment]
Sorry, but I don't see any reason why Courseplay would be causing this. If you can reproduce this with no other mods, reopen this issue.
