### ISSUE TITLE
Mähwerk senken zeitgleich

### ISSUE THREAD

**Issue by Matzenie** [Courseplay/Courseplay_FS22#56]
Die Mähwerke vorne und hinten senken zeitgleich nicht an der gleichen Stelle auf der Strecke. Dadurch entsteht besonders bei der ersten Runde eine Gras Schwad außerhalb des „Eigentums“. Diese Stück Schwad kann man nicht mit normalen Ladewagen oder Pressen sammeln. Es wäre cool wenn das Mähwerk hinten an der Stelle senkt wo auch das vordere senkt. Ein ähnliches Problem könnte es auch am Ende der Band geben, musste leider los und konnte mir das nicht mehr anschauen. Version 7.0.0.3 war im Einsatz. Bilder und Log muss ich nachreichen falls erforderlich.
Ist eher ein Luxus Problem, aber vielleicht könnt ihr es irgendwann wenn mal Luft ist lösen

**Comment by Tensuko** [comment]
Schauen wir uns auf alle Fälle an.
Bilder wären Hilfreich, damit ich sehen kann, an welcher Stelle das genau passiert.

**Comment by Matzenie** [comment]
Ich habe mir das nun nochmal angeschaut und ein paar Screenshots gemacht. Den Traktor mit den Schneidwerken habe ich für das Bild manuell hingestellt. Müsste sonst erst wieder 2 Tage spielen... Das Problem entsteht nur beim Senken, das Ausheben ist scheinbar sauber. Ich hoffe die Bilder helfen.

![1](https://user-images.githubusercontent.com/62774535/147381403-ecb9d8cb-93d0-4f7a-a5cd-f946a72ef774.PNG)
![2](https://user-images.githubusercontent.com/62774535/147381410-35303764-9938-4a9a-a453-9c4a0539e6c5.PNG)
![3](https://user-images.githubusercontent.com/62774535/147381414-7e2e2e8e-a48f-4514-9023-1ddceeb9b58e.PNG)
![4](https://user-images.githubusercontent.com/62774535/147381415-475dd418-1580-4d60-8ae3-39068f2591e4.PNG)

**Comment by pvaiko** [comment]
Sorry, dafür werden wir in der nächsten Zukunft keine Zeit haben, pull requests sind immer wilkommen!
