### ISSUE TITLE
[Feature]ETA time to finish

### ISSUE THREAD

**Issue by Falkwa** [Courseplay/Courseplay_FS22#561]
**What is the problem this feature/enhancement solves?**
i know you are busy,   things are still new and we the users are still learning the new stuff also.

**Describe the solution you'd like**
on the mini hub or wherever you would like to put it.   ETA until job finished

**Describe alternatives you've considered**

**Additional context**
fabulous job so far in such little time.  iv noticed a few errors here and there.  but ill admit 90% of them tend to be learning the new setup just like you are.     my biggest hope is that loading wagons and self unload can be figured out.   but only time will tell

**Comment by Tensuko** [comment]
Is already WIP.
But not big priority.
