### ISSUE TITLE
[BUG_SP] Game freeze

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/Courseplay_FS22#565]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Loaded new game with base elmcreek with courseplay only.

**Actual behavior**
Game freezes at 85 percent after updating today with all main updates today
**Expected behavior**
Game should load and play

**Screenshots**

**Courseplay version**
Version used: 7.0.0.19 main branch

**Log**
(https://pastebin.com/PzgmsgZ8)

**Map**
Any map but this try was with a new game with elmcreek to make sure

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?

**Relevant script mods**
none active

**Comment by KCHARRO** [comment]
If there are problems in this lua: Line 15

"Courseplay_FS22/scripts/ai/jobs/AIJobFieldWorkCp.lua" 

At least that's what the log says...

2022-01-16 23:06 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
F:/Low Level Prog/AAA/ADDON - FS22/MOD/FS22_Courseplay/scripts/ai/jobs/AIJobFieldWorkCp.lua:15: attempt to index global 'AITaskFieldWorkCp' (a nil value)

Always on all maps (mods included), I don't think it's necessary to put the full log...

**Comment by mfehr94** [comment]
@jobyrns72 @jobyrns72  is that a official version from the release page or did you pull from main branch?

**Comment by ct177mak** [comment]
Courseplay version
Version used: 7.0.0.19 main branch ,i use allready the main branch and no Problems with this .

**Comment by jobyrns72** [comment]
@mfehr94 main branch. Everything worked fine yesterday but it was an update today that did it

**Comment by caplink811** [comment]
morning,

same here. It worked with the version I got from the main branch sources and zipped at 01/16 09:22 GMT+1, but wont work with the version I got the same way in the evening around 9pm GMT+1. In between there was a merge happened (when I remebered correxct).

regards

**Comment by andreasthu** [comment]
same here, load to 85%:
```
C:/Users/athum/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/ai/jobs/AIJobFieldWorkCp.lua:15: attempt to index global 'AITaskFieldWorkCp' (a nil value)
2022-01-17 08:59 Application exit request forced.
```
also the last main version (fd019bd)
lg
andreas

**Comment by Tensuko** [comment]
Pls try with the latest push. https://github.com/Courseplay/Courseplay_FS22/commit/e718004787bf2dde11930e18df4773a06e70b5d4

**Comment by Roby1164** [comment]
Ok, now start it and everything looks ok

**Comment by jobyrns72** [comment]
Thank you! Loads up perfectly now!
