### ISSUE TITLE
[Question] CP driver to unload a combine ?

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#566]
Hi
Will we have in a futur version a function to the CP driver to go unload a combine ?
because in my case, Unloading a combine using AD driver just suck (suck at following the combine, unload, keep position, free position so the combine can turn, ..., it was the same shit for me as in FS19 AD dirver to unload a combine is shitty as hell)

Thanks :)

**Comment by RealNeo80** [comment]
CP / AD is not implemented yet, so just wait! and whats the Problem to use the search function? its answered 1000 times now ....

**Comment by Chico0008** [comment]
because we love to have personalized answers :)

Thanks, and keep up the good work ;)
we all love CP

**Comment by Tensuko** [comment]
Overloader to just unload Combine is planed but nothing more.
The guys from AutoDrive currently working on unloading CP.
How this is going to be improoved over the next few month, we will see.
