### ISSUE TITLE
Suggestion: make it clearer that vehicle needs to be ON FIELD to generate a course

### ISSUE THREAD

**Issue by kroddn** [Courseplay/Courseplay_FS22#57]
It took me a while to find out that logic. The "generate" course was not showing on one of my tractors. I had to drive on the field to let the generate course "button" to appear.

Mabye show the functionality all the time, but when pressing it show a message "drive onto the field to generate a course".
More convenient would be to scan the field that the position cursor of the helper menu is showing to, in a radius of let's say 25 meters.

**Comment by Nevsix** [comment]
You can just mark the field on klick on the coordinates on the right and then choose the field

**Comment by kroddn** [comment]
That did not work in my case. I always had to drive the tractor onto the field before that button appeared.

**Comment by pvaiko** [comment]
The vehicle does not have to be on a field to generate a course. You have to select a target on a field to generate a course. The vehicle can be anywhere on the map, it'll drive to the field and start working.
