### ISSUE TITLE
[Enhancement] Feldarbeit, CP wartet nicht bis Dalbo 1230 abgesenkt wurde

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#571]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Claas Axion 870 + Dalbo 1230
Haute Beyleron, Feld 44 walzen 
anheben spät,
absenken früh,
![fsScreen_2022_01_17_19_39_39](https://user-images.githubusercontent.com/24860501/149824413-8c00f583-828e-4a65-8907-c80a3977defd.png)
![fsScreen_2022_01_17_19_40_07](https://user-images.githubusercontent.com/24860501/149823843-7aa40131-7758-4719-b0fa-16d99e4ee163.png)

**Actual behavior**
der Traktor mit CP wartet nach der Wende nicht, bis die Walze abgesenkt wurde
![fsScreen_2022_01_17_19_39_55](https://user-images.githubusercontent.com/24860501/149823854-6eeaff27-d1af-49f1-9401-f6baabc70766.png)
hier sieht man gut, die 4 Flecken im norden von Feld44 die nicht gewalzt wurden

**Expected behavior**
Der CP traktor sollte stehenbleiben, die Walze senken und dann erst losfahren

**Screenshots**
vor der Wende
![fsScreen_2022_01_17_19_40_45](https://user-images.githubusercontent.com/24860501/149823961-0bdc8e83-1cdc-4e15-b53c-797ab2a8d6fe.png)

anheben:
![fsScreen_2022_01_17_19_40_48](https://user-images.githubusercontent.com/24860501/149823991-90ff77b8-239f-4e38-97bd-9b5148732899.png)

Wende
![fsScreen_2022_01_17_19_40_52](https://user-images.githubusercontent.com/24860501/149824015-68200b5c-10f8-47ed-9a57-a13af4b0cc79.png)
![fsScreen_2022_01_17_19_40_55](https://user-images.githubusercontent.com/24860501/149824040-95ce04c0-5a4b-4a38-99d6-1055d0019f6e.png)

wende fast beendet:
![fsScreen_2022_01_17_19_40_58](https://user-images.githubusercontent.com/24860501/149824082-0ba64c07-3030-44d7-a20d-871fde6197e4.png)

aber die walze wird nicht abgesenkt:
![fsScreen_2022_01_17_19_41_00](https://user-images.githubusercontent.com/24860501/149824122-d1e7d425-6099-475e-8a96-ce489a764740.png)

jetzt erst, viel zu spät:
![fsScreen_2022_01_17_19_41_02](https://user-images.githubusercontent.com/24860501/149824135-87e0439e-bab0-42fd-bddc-3abe576b95a2.png)

**Courseplay version**
Version used:  7.0.0.19 main von
main von vor 2 stunden
Get the vehicle DirectionNode to measure the distance to the fieldbor…
…der.
403f469

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7884162/log.txt)

**Map**
Haut Beyleron

**Vehicles/ implements involved**
Claas Axion 870 + Dalbo 1230
no modvehicles

**Relevant script mods**
-

lg
andreas

**Comment by Roby1164** [comment]
Used just today, the roller with CP, and has regularly lowered the tool, before starting to work, as well as other types, such as seeders, plows, etc .. indeed the latest releases, at the end of the work, finally close the tools.

**Comment by Roby1164** [comment]
It is important that in the settings, it is set, that the tool must be lowered in advance, and raised late, by default it is set on the contrary, lower late and raise early.

**Comment by Tensuko** [comment]
#516 but I close it and keep this, but I must say this is not a bug, it is only this tool.

**Comment by andreasthu** [comment]
> It is important that in the settings, it is set, that the tool must be lowered in advance, and raised late, by default it is set on the contrary, lower late and raise early.

Schrieb ich doch:
Haute Beyleron, Feld 44 walzen
anheben spät,
absenken früh,

Das interesannte, im Feld44 im süden hat er gestoppt und gewartet,
Auch Feld43 nördlich davon (sieht man oben am 3. Bild) hat er lückenlos gewalzt.
Da war der kurs ebenfalls, hoch/runter, 1x Vorgewende, beginnend mit den Bahnen, Richtung Ost-West.
Da hat er auch keine Lücken am Ende gelassen.
Lg
Andreas

**Comment by Chico0008** [comment]
I confirm still  having the same problem on Elmcreek.
the driver start to drive in a row having the implement still lowering, making this :(
The driver should wait the implement to be fully lowered before continue.
![Sans titre](https://user-images.githubusercontent.com/58886243/150642300-11ef7b69-3965-4987-9e3e-0ff4b8d22345.png)

**Comment by pvaiko** [comment]
Reopen if this is still a problem we made quite a few improvements in the meantime.

**Comment by andreasthu** [comment]
Problem besteht immernoch mit 7.0.0.28:
1x rundum
Eckig
12,2m AB
Hin und Her
Anheben spät
Absenken früh
![fsScreen_2022_02_09_08_39_52](https://user-images.githubusercontent.com/24860501/153144308-e4b4d593-b5fb-41ec-ad17-3d59c283a4df.png)
![fsScreen_2022_02_09_08_39_59](https://user-images.githubusercontent.com/24860501/153144315-bfc5ad08-8ad6-4fd8-b0a4-3e5f9f8c63f1.png)
![fsScreen_2022_02_09_08_40_05](https://user-images.githubusercontent.com/24860501/153144321-e25c6e4f-79a3-449e-89db-c22ee073e039.png)

dasselbe mit einer Reihe abstand:
![fsScreen_2022_02_09_08_38_57](https://user-images.githubusercontent.com/24860501/153144372-b4951595-d2e7-478e-be14-495638492f45.png)

also ja, sollte ev noch überarbeitet werden.
lg
andreas

**Comment by hermannbrauer** [comment]
hast du das mal mit 2 Vorgewenden ausprobiert.. bei der Arbeitsbreite könnte das Sinn machen!

**Comment by pvaiko** [comment]
@andreasthu ich kann es nicht reproduzieren. Brauche ein komplettes Log mit Debug.

**Comment by pvaiko** [comment]
@andreasthu that turn speed 17 is the problem.

**Comment by andreasthu** [comment]
And that means?
Set a slower turn speed?
I worked wirh many different machines.
In all others, grubber, disk, sowingmachine, mulcher, stonepicker, dresher-combine,.. the traktor stops, lower the tool, and then he beginn to drive forward.
Only wirh rhe dalbo roller he dont stop, he drives his way along and lower the tool in drive-by.
Lg
Andreas

**Comment by pvaiko** [comment]
It means it'll work if you set the turn speed to 10 for instance.

There's an underlying bug which only surfaces when you are driving fast.

**Comment by andreasthu** [comment]
Danke,
nach ersten Tests funktioniert das nun gut.
lg
andreas
