### ISSUE TITLE
Doesn't start course. Just drives in circles before start point. Doesn't seem to be working with in game helper anymore. Using PC version with steam. H[BUG_SP]

### ISSUE THREAD

**Issue by cdolso** [Courseplay/Courseplay_FS22#574]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Resandise** [comment]
Well this is interesting, please tell me more about this issue

**Comment by pvaiko** [comment]
No useful information to do anything about it, closing.

**Comment by cdolso** [comment]
To whom it may concern,
From the beginning. I open the helper screen and go to courseplay. I first set to start at first way point. Then I set initial start point. I have the course calculated. I close the course editor. I press start course. It goes to start point. then the tractor does not go to first way point. It just makes a wide left circle and returns to start point. Then repeats the left circle. The tractor never finds the first way point. 
Also if I stop a helper in the middle of a course. The "H" key does not resume course.
I tried to reinstall version 13. Now the automatic tool calculation doesn't work.
Are there any game files that I could copy and send you to help?
Thank youCarl Olson    On Monday, January 17, 2022, 05:16:00 PM CST, Resandise ***@***.***> wrote:  
 
 


Well this is interesting, please tell me more about this issue

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
