### ISSUE TITLE
Call Stack Bildschirm Flackern

### ISSUE THREAD

**Issue by Andy2612** [Courseplay/Courseplay_FS22#577]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Einfach den CP Helfer wieder auf den Kurs schicken und der Fehler tritt wieder auf.

Fehler konnte auch auf der Elmcreek reproduziert werden, diesmal ohne Mod außer Autodrive und FS22_EnhancedVehicle.
Es wurde wieder ein Kurs auf Feld 56 erstellt und gespeichert. Im Anschluss wurde das Feld mit dem Landschaftstool zu einer Wiese gemacht. Nun wurden die Wiese manuell mit Hilfe von EnhancedVehicle gemäht. Dann wurde der Wender (Vicon
 Fanex 904 von Giants) mit dem gespeicherten Kurs auf das Feld geschickt.
![20220118043428_1](https://user-images.githubusercontent.com/61479274/149867305-cfaec657-6f2a-47bd-b18d-1f50a5c01b09.jpg)

Simply send the CP helper back onto the course and the error reoccurs.
**Actual behavior**
A clear and concise description of what happen.
Ich habe als erstes einen Kurs auf einem Feld für den CP Helfer erstellt und gespeichert. Im Anschluss habe ich das Feld entfernt und als Wiese mit dem Landschaftstool gemalt(besser Optik als eine Wiese auf dem Feld). Dann sollte der CP Helfer die Wiese abernten, was leider nicht funktioniert und manuell dann gemacht wurde. Im zweiten versuch mit einem Wender(Heu) hat es funktioniert bis der Fehler dann auftrat.
Auf dem Kurs nach ein paar Bahnen hat CP dann einen Wegpunkt nicht erkannt,ist einfach geradeaus weiter gefahren und so wahrscheinlich den Fehler verursacht.
Wenn ich dann in ein anderes Fahrzeug gewechselt habe kam es zu dem Flackern des Bildschirms.

First I created and saved a course on a field for the CP helper. I then removed the field and painted it as a meadow with the landscape tool (better look than a meadow on the field). Then the CP helper should harvest the meadow, which unfortunately does not work and was then done manually. In the second attempt with a turner (hay) it worked until the error then occurred.
On the course after a few laps, CP didn't recognize a waypoint and just continued straight ahead, probably causing the error.
When I then switched to another vehicle, the screen flickered.
 

**Expected behavior**

**Screenshots**
![20220118031745_1](https://user-images.githubusercontent.com/61479274/149860189-59740f01-39c0-495a-88fb-c6878eda23a2.jpg)

![20220118034506_1](https://user-images.githubusercontent.com/61479274/149862056-52d02a49-8553-45f3-b294-bb2e01b2a774.jpg)
![20220118034515_1](https://user-images.githubusercontent.com/61479274/149862069-8d2f50d7-64fd-4fd2-9879-836cf423dc62.jpg)

**Courseplay version**
Version used: Courseplay for FS22 v7.0.0.19

**Log**
log von Haut-Beyleron
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7885719/log.txt)

log von Elmcreek mit Fehler reproduziert
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7886026/log.txt)

**Map**
Map played on. Haut-Beyleron von Giants

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ? Kein Mod: AXION 870-800,Claas DISCO Pack von Giants,Vicon Fanex 904 von Giants  
Diese Fahrzeuge waren der Auslöser,der sich dann auf alle anderen verbreitet hat.

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive und FS22_EnhancedVehicle

**Comment by Tensuko** [comment]
> Version used: Courseplay for FS22 v7.0.0.19
Deine log sagt etwas anderes:
(Version: 7.0.0.18) FS22_Courseplay

**Comment by Andy2612** [comment]
Hallo, sorry keine Plan was da schief ging. habe selbst in der log geschaut und ja es war die .....0.18, allerdings im modordner laut modDesc 0.19, aber egal. habe log gelöscht auch CP und neu geladen. Fehler konnte erneut reproduziert werden
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7888864/log.txt)
.

**Comment by Tensuko** [comment]
Fis ist schon auf Main. Wird in der nächsten Version behoben sein.

**Comment by Andy2612** [comment]
Danke
