### ISSUE TITLE
jump to Course editor button via CP mini GUI [Feature]

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/Courseplay_FS22#579]
I would like to have access to the ESC Map and coursegenerator via the mini GUI as I use this to start CP and have light controls over it.
It is very annoying for me to have different locations for the work with the courseplay tool.

I think implementing a quick jump button on the mini GUI would be a good step to make work with CP smoother.

**Comment by Tensuko** [comment]
That won't work rly well.
You just sit in your vehicle and open up the ESC Menu and thats it, not sure why you should work with the mini GUI for this.
Will keep something like that in mind bot not rly planed.
