### ISSUE TITLE
Stuck Vehicle Speed Settings

### ISSUE THREAD

**Issue by daspamma** [Courseplay/Courseplay_FS22#58]
When I create a course all the speed settings are set to 3 mph. I can not raise them past 3 mph. I have tried setting a course with multiple tractors. For example the MCCORMICK X7 with a KNOCHE Mulcher and the NH T7 with the VÄDERSTAD speeder. All tractors and implements are in good condition. 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7775331/log.txt)

**Comment by Tensuko** [comment]
Will try it out later, thats strange...

**Comment by Sandro-Bauer** [comment]
Bei mir das gleiche Phänomen:
- die Geschwindigkeit bei Feld und Feldarbeit kann ich nur von 5km/h bis 9km/h einstellen (egal, ob Drescher oder Traktor)
- die Geschwindigkeit für Wenden und Rückwärts lässt sich nur von 2km/h bis 9 km/h wählen.

Vielen Dank für eure Arbeit... immer wieder faszinierend :-)

**Comment by Maverick-0815** [comment]
Bei mir das gleiche Phänomen:

    die Geschwindigkeit bei Feld und Feldarbeit kann ich nur von 5km/h bis 9km/h einstellen (egal, ob Drescher oder Traktor)
    die Geschwindigkeit für Wenden und Rückwärts lässt sich nur von 2km/h bis 9 km/h wählen.

Vielen Dank für eure Arbeit... immer wieder faszinierend :-)

**Comment by Maverick-0815** [comment]
Bei mir das gleiche Phänomen:

- die Geschwindigkeit bei Feld und Feldarbeit kann ich nur von 5km/h bis 9km/h einstellen (egal, ob Drescher oder Traktor)
- die Geschwindigkeit für Wenden und Rückwärts lässt sich nur von 2km/h bis 9 km/h wählen.

Vielen Dank für eure Arbeit... immer wieder faszinierend :-)

**Comment by Sheep610** [comment]
Habe das gleiche Problem, allerdings nicht bis 9 km/h, sondern bis max 5 km/h. Problem bestand mit 7.0.0.3 und auch mit 7.0.0.4. Ich meine mit der ersten Version konnte ich es höher einstellen, bin mir aber nicht zu 100% sicher.

**Comment by rM16A2** [comment]
It won't let me set the field work speed, it's frozen at 5km / h with any vehicle.

**Comment by Tiba570** [comment]
moin bei mir habe ich das Problem, dass alle Fahrzeuge nur bis zu 5 km/h schnell fahren könnten und ich kann dies im Menü nicht erhöhen und mit einem neuen Profil kann ein Drescher bis zu 20 km/h fahren und mit meinem Profil nur 5 km/h und ich möchte kein Neuers Profil starten.

log.txt
savegame1.zip

**Comment by Peiren85** [comment]
Wenn ihr Förberbänder besitzt oder vielleicht ein anderes, fahrbares, Gerät, welches extrem langsam unterwegs ist, was ihr besessen habt bevor ihr die Mod installiert habt zu verkaufen danach das Spiel speichern und neu laden. Danach sollten die Settings wieder funktionieren. Ich habe es mit den Förderbändern getestet und anscheinen kann man sie danach wieder kaufen und sie funken nicht mehr in die Settings rein.

**Comment by Resandise** [comment]
Same here, 3mph max for all speed settings.

**Comment by Maverick-0815** [comment]
> Versucht mal, wenn ihr Förberbänder besitzt oder vielleicht ein anderes, fahrbares, Gerät, welches extrem langsam unterwegs ist und was ihr besessen habt bevor ihr die Mod installiert habt, zu verkaufen, danach das Spiel speichern und neu laden. Danach sollten die Settings wieder funktionieren. Ich habe es mit den Förderbändern getestet und anscheinen kann man sie danach wieder kaufen und sie funken nicht mehr in die Settings rein.

DAS KANN ICH BESTÄTIGEN!
Bei mir war es die Standard-Map "Erlengrat". Darauf ist als erstes Fahrzeug schon standardmäßig der Balkenmäher (Typ aebi CC66) am Hof.
Diesen Balkenmäher verkaufen, das Spiel speichern, raus gehen und wieder neu starten und schon kann man die Geschwindigkeit höher einstellen.
Ich habe aber den Eindruck, dass beim Start des Spielstandes als Geschwindigkeitslimit die Geschwindigkeit des langsamsten Fahrzeuges übernommen wird. Das merkt man aber fast nicht, denn eine Feldarbeit mit z.B. 50 km/h benutzt wahrscheinlich eh fast niemand ;-)
Vielen Dank an Peiren85 für den Hinweis.
Vielleicht hilft dieser Workaround ja bei der Fehlersuche.

**Comment by Nordvarg** [comment]
Thanks, @Peiren85. Can confirm that your solution worked for me as well. So, for any English speaking readers:

If you have bought or leased a driveable auger, conveyor, or other really slow moving tools or vehicle, sell or return them, save the game, and restart. When you open the game again, speed settings should work as intended.

If you buy another "slow mower" now, it doesn't seem to affect the speed settings. 

P.S. Dear dev team: Thank you so much for this great Christmas gift.

**Comment by survanas** [comment]
yea this issue happens to me aswell. But this happens only old saves before CP was released. This issue does not happen on new saves. I've tried it on 7.0.0.4, I did not test it on the olders versions.

**Comment by survanas** [comment]
> Thanks, @Peiren85. Can confirm that your solution worked for me as well. So, for any English speaking readers:
> 
> If you have bought or leased a driveable auger, conveyor, or other really slow moving tools or vehicle, sell or return them, save the game, and restart. When you open the game again, speed settings should work as intended.
> 
> If you buy another "slow mower" now, it doesn't seem to affect the speed settings.
> 
> P.S. Dear dev team: Thank you so much for this great Christmas gift.

I'm gonna try this and will let you if this works.

**Comment by Tensuko** [comment]
Can you try the newest Version, as this got a temporary fix. also Duplicate #28

**Comment by survanas** [comment]
I may have found the issue, I'm testing it

**Comment by survanas** [comment]
> I may have found the issue, I'm testing it
> Can you try the newest Version, as this got a temporary fix. also Duplicate #28

@Tensuko the speed issue happanes in Erlengrant map which map gives you the mover Aebi CC 66, and this mover makes CP at fault. I sold it in my original save and it solved the problem, I bought it from market again and the speed issue did not occur. So to make sure I've created a new save game in Erlengrant map logged in the game but did not save it, and the issue occured again. I sold the mover Aebi CC 66 but the problem wasnt solved wihtout saving it. So I saved it once and quit the game. I logged in the game 2nd time and the issue was solved. I beleive the problem is Aebi CC 66 is given by the map, not the Aebi CC 66 is sold by the market.

**Comment by survanas** [comment]
7.0.0.5 solved the problem

**Comment by Tensuko** [comment]
Ok thanks for feedback, closing this Issue for now.
