### ISSUE TITLE
[Feature]Resuming work

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#581]
When using the resume work from the last point worked, in this case with the seeder, it immediately lowers the implement and proceeds slowly to the point, where the path starts again.
If possible, it would be ideal for the vehicle to proceed at normal speed, and the implement closed, and then, when it reaches the restart point, stop, lower the implement and start work again.
In the picture an uncomfortable situation, I have to waste a lot of time, which should be avoided.
![Screenshot_2](https://user-images.githubusercontent.com/24955554/149924567-8ac1f18e-2271-4e55-89ee-7be133dd7d74.jpg)

**Comment by Roby1164** [comment]
Main Branch, penultimate, before the Fix callstack for ..
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7889215/log.txt)

**Comment by Tensuko** [comment]
What happens if you increase the Fieldspeed (not Working Speed) ?

**Comment by Roby1164** [comment]
> What happens if you increase the Fieldspeed (not Working Speed) ?

Nothing changes, I have already done some tests, at that moment, I had set the speeds to the maximum, both for work and driving on the field, in fact as part of the work, the speeds are correct. If it can be useful, I have noticed that he has this problem, even when starting the work, and he is some distance from the first point, he leaves towards the point. but then it slows down almost immediately, and opens the tool, and slows down until or when it reaches the starting point, everyone does it, including the combine ...

**Comment by KCHARRO** [comment]
In my case, it just unfolds whatever it brings back, but doesn't start working, it starts moving across the field and resumes working when it reaches and lines up at the last waypoint.

This is how I have it:
Field work speed: 15
Driving speed in the field: 20 

By the way, this new feature is very well implemented, and perhaps it can be integrated with AD, go alone to fill in, and resume work as before.

**Comment by Tensuko** [comment]
> By the way, this new feature is very well implemented, and perhaps it can be integrated with AD, go alone to fill in, and resume work as before.

Thats what the new Interfaces are for :)

**Comment by Roby1164** [comment]
Even with the last modification you made, nothing has changed, when it has to go towards the starting point, the speed is always at 15 Km / h, even if the positions are higher
![Screenshot_2](https://user-images.githubusercontent.com/24955554/150116485-250aa70f-cd8d-464d-93aa-ca6d53eef409.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/24955554/150116495-5817b052-4a69-41fd-831b-1d6793cdffce.jpg)
Here, on the other hand, during work the speed is as per settings
![Screenshot_5](https://user-images.githubusercontent.com/24955554/150116626-e4bdb012-5b7e-4de3-8b3c-73932e157feb.jpg)

**Comment by Tensuko** [comment]
Fieldwork Speed is limited to the Tool as long as the setting is higher then the toolspeed, else you can limit the working speed with that setting.

For Fieldspeed, the way to last or 1st waypoint should be adjustable with fieldspeed, we have a look as this seems to not work correctly.

**Comment by Bovrinox** [comment]
How do you make it resume work? my seeder stopped when it was out of fertilizer, and all i can do is make it start all over again in the job creation bit

**Comment by Roby1164** [comment]
> How do you make it resume work? my seeder stopped when it was out of fertilizer, and all i can do is make it start all over again in the job creation bit

If you have the V. 7.0.0.20, when you want to start again, after having reloaded the seeder, use the mini gui, you will find the voice to resume from the last worked point ...

**Comment by Roby1164** [comment]
Perfect now it's ok ....
![Screenshot_2](https://user-images.githubusercontent.com/24955554/150227199-e96bc2dc-ec8d-484f-8e98-6f37fd653af5.jpg)

**Comment by Bovrinox** [comment]
> 

ok, great, how do i do that? 
What is this mini gui? I cant find it, i pressed every button on my keyboard using every combination of modifier keys i could think of, and nothing. Ive been told to "read the wiki" rather than having my question answered, but all that says is that there isnt one lol
be nice if the wiki actually had some info about how to use the program....

**Comment by mfehr94** [comment]
> > 
> 
> ok, great, how do i do that? 
> What is this mini gui? I cant find it, i pressed every button on my keyboard using every combination of modifier keys i could think of, and nothing. Ive been told to "read the wiki" rather than having my question answered, but all that says is that there isnt one lol
> be nice if the wiki actually had some info about how to use the program....

Delete button does the trick. If not check your key binding settings

**Comment by Roby1164** [comment]
> 

If you look in the FS22's key settings, you will find the CP section, with the various dedicated keys. However the mini Gui opens with Left Shift + H ...

**Comment by Bovrinox** [comment]
oh thanks. Yeah for some reason it wasnt automatically assigned a keyboard shortcut. didnt realise you could change the buttons for it in settings, did it have this on fs19? I dont remember it did, but maybe i just never needed to haha
Thanks
