### ISSUE TITLE
[BUG_SP]Lexion 5900 Self unload placement wrong

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#582]
**Steps to reproduce**
use a Lexion 5900 combine with self unload mode

**Actual behavior**
after going to a trailer, stop too far and can never unload

**Expected behavior**
stop with the pipe over the trailer

**Screenshots**
https://drive.google.com/file/d/1t2DXHqdrv_w-Y1HMRyChYN94rv0vAo8x/view?usp=sharing

**Courseplay version**
Version used: 7.0.0.19

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7889532/log.txt)
debug for this case is at the end of the log around 2022-01-18 14:47 :01

**Map**
Erlengradt, on fields 32, 33 and 34 as one big field.

**Relevant script mods**
AD 2.0.0.3 waiting near the field for the trailer to be filed.

**Comment by Tensuko** [comment]
Not sure if this problem will be fixed with the next Release, but we have some changes/fixes.

**Comment by Tensuko** [comment]
Pls test 7.0.0.20

**Comment by Chico0008** [comment]
Just tried with 7.0.0.20, still the same, the combine goes too far and the pipe is over the tractor and not the trailer :(

**Comment by Tensuko** [comment]
okay, is that Vanilla one or a mod one ?
Btw for this we have the vehicle section in the Template....

**Comment by Chico0008** [comment]
it's the vanilla one

**Comment by pvaiko** [comment]
@Chico0008 looks like you don't have the Fieldwork debug channel on, we need a log with that on.

**Comment by Chico0008** [comment]
Made a new log, fieldwork was already activated on the last one, strange.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7895090/log.txt)

**Comment by pvaiko** [comment]
You probably don't have the debug activated on the combine (in the vehicle settings?)

**Comment by Chico0008** [comment]
Oh, i thought you only just have to press SHIFT+4 to activate debug channel >_<
so, new log with debug activated on the combine
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7903391/log.txt)

video of it
https://drive.google.com/file/d/1lXdyzR9AkDZT1z1aGz72HntS0az1Ra1s/view?usp=sharing

**Comment by pvaiko** [comment]
Ok, I can't reproduce this, seems to work fine here:
![image](https://user-images.githubusercontent.com/2379521/150443753-d59ccab7-064b-4994-86cb-51934882b082.png)

**Comment by Chico0008** [comment]
Strange, for me it's never ok with this combine
updated to 7.0.0.21, change the position of the waiting trailer, but still the same :(

![Sans titre](https://user-images.githubusercontent.com/58886243/150570616-5ac7fa8f-4641-4714-a8b4-5dff2d2d5273.png)

**Comment by pvaiko** [comment]
what are your speed settings? Field speed/turn speed?

**Comment by pvaiko** [comment]
Your video shows your combine driving past the end of the course by 5-6 meters, whereas on my screenshot it's probably a meter or less.

**Comment by Chico0008** [comment]
on the last screen the trailer was closer to the field as before, 
the combine is set to run a 40Km/h on field, 25km/h working, 15km/h manoeuver and 10km/h reverse

I'll try with another combine and trailer with the next season and ses what happen.

**Comment by Blackjack155** [comment]
> Ok, ich kann das nicht reproduzieren, scheint hier gut zu funktionieren: ![Bild](https://user-images.githubusercontent.com/2379521/150443753-d59ccab7-064b-4994-86cb-51934882b082.png)

hast du es mal mit AD Probiert ich sehe bei dir kein AD aktiv das könnte der unterschied sein

**Comment by pvaiko** [comment]
Habe ich nicht. Hast du mit 20 km/h probiert?

**Comment by Tensuko** [comment]
AutoDrive hat darauf keinen Einfluss.

**Comment by Tensuko** [comment]
Should work better with 7.0.0.22
Pls make a new Issue when still have problems with this (use template, debug and add logfile pls).
