### ISSUE TITLE
[BUG_SP]French text is missing CP .20

### ISSUE THREAD

**Issue by Novarion** [Courseplay/Courseplay_FS22#587]
Hi got troubles with the latest french version of CP

**Screenshots**

https://puu.sh/IDq6C/80f49b2fb8.jpg

**Courseplay version**

Version used:  ...0.20

**Log**

no log

**Comment by Chico0008** [comment]
same here, had to delete the translation_fr.xml file for now, and stay with english text, otherwise it's impossible to read

**Comment by Tensuko** [comment]
Thanks for quick feedback.
Pls try redownlaod the release.

**Comment by knoxville73** [comment]
It's now ok, many thanks
