### ISSUE TITLE
[BUG_SP] Trigger Anzeige nach Update auf 7.0.0.20

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#589]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Nichts, EInfach das Spiel öffnen.

**Actual behavior**
Trigger offenbar sichtbar 

**Expected behavior**
ausgebelndete Trigger

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/78980660/150002184-9e216e71-57aa-43da-a217-2426ebdde4da.png)

**Courseplay version**
Version used: 7.0.0.20

**Log**
Ist denk ich nicht nötig

**Map**
Map played on. Erlengrat

**Vehicles/ implements involved**
Wich vehicle or implement? Jedes Fahrzeug

**Relevant script mods**
No

**Comment by Tensuko** [comment]
"ich denke nicht" ist keine Option :)
Logfile könnte trotzdem helfen.

**Comment by 0scarZulu** [comment]
Okay :D DAnn aber jetzt von nem anderen Savegame aber ist der gleiche Fehler an jedem Fahrzeug
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7891797/log.txt)

**Comment by Tensuko** [comment]
Welche Ansicht erwartest du denn ?
Also wie soll es aussehen ?
Weil ich habe keine Probleme wenn ich F5 durchschalte...

**Comment by 0scarZulu** [comment]
Das die weißen vierecke weg sind .. Die sind bei mir von Anfang an da sobald ich das Savegame starte seit der neuesten Version. Mit F5 bekomme ich sie nicht weg

**Comment by Tensuko** [comment]
Das ist aber nicht durch CP.
Da hast du irgend etwas anderes aktiv oder falsch in deinem Spiel.
Guck erst mal ob das andere Mods sind, dann melde dich sonst noch mal.
