### ISSUE TITLE
Course-Generator Headland issue (CP v. 7.0.0.3)

### ISSUE THREAD

**Issue by Opa-Andre** [Courseplay/Courseplay_FS22#59]
In the settings you are able to define if the course should be generated using headlands first and rows after (default) or if it should start with the lanes and add the headland at the end. However independend how this setting is set, CP will always generate headland first and  the lanes at the end... obviously the setting is ignored.

**Comment by SledgeHammer75** [comment]
can confirm

**Comment by Tensuko** [comment]
Ok, will have a look

**Comment by Keppchen** [comment]
Works. Thanks for the fix!
