### ISSUE TITLE
[BUG_SP]Düngerstreuer Beendet vorgewende nicht seit version 7.0.0.20 

### ISSUE THREAD

**Issue by Osram1981** [Courseplay/Courseplay_FS22#594]
![fsScreen_2022_01_18_23_08_44](https://user-images.githubusercontent.com/89778771/150026870-bbb3f0af-d712-4f98-9fad-c316b8ae9e8b.png)
Seid dem ubdate heute auf 7.0.0.20 bendet der Düngestreuer Kverneland TLX Geospread das vorgewende nicht mehr sondern fährt das Vorgewende bis die einfahrt in die bahnen kommt und fährt dan die Bahnen ab. Start von 1. wegpunkt!

**Comment by Tensuko** [comment]
Versuch es noch mal richtig mit dem Issue!
