### ISSUE TITLE
[Feature] Automatic Working speed

### ISSUE THREAD

**Issue by TheSoldier91** [Courseplay/Courseplay_FS22#595]
**What is the problem this feature/enhancement solves?**
CP should be able to detect the working speed of the implement or sprayer or whatever.

**Describe the solution you'd like**
Automatic detect Working speed 

**Describe alternatives you've considered**
Be able to set a global default speed for fieldwork, maneuver, turn, reverse like in the vehicle settings, but global

**Comment by Tensuko** [comment]
It works with the maximum speed, wich the implement allows.
Fieldworkspeed can be limited in the vehicle settings and will never be a global setting becouse that won't make any sence.

**Comment by TheSoldier91** [comment]
Oh, it doesn't.

Field Sprayer Bruin 4200 for example.
25 kmh working speed, only works with 15 kmh if 15 is Set in CP.

Better I do open up an issue for that 😉
