### ISSUE TITLE
[BUG_SP] Working Speed

### ISSUE THREAD

**Issue by TheSoldier91** [Courseplay/Courseplay_FS22#598]
**Steps to reproduce**
Only tested with Bruin 4200 Selfdriver Sprayer.
Generate course like always.

**Actual behavior**
Workspeed is not as expected. (Tensuko said it works with the detected implement work speed, can limited by CP)
If limited to 15kmh, it works with 15kmh. If raised, it will speed up as it should.

**Expected behavior**
CP should detect maximum working speed for the implement or tool.
Or default settings should be able to change, like from 15kmh default to 25kmh or so.

**Screenshots**

![20220119093511_1](https://user-images.githubusercontent.com/60544088/150095160-84add15a-4100-430c-a4de-cc21514ab3dd.jpg)

![20220119093543_1](https://user-images.githubusercontent.com/60544088/150095218-70b7d288-abde-49c1-900f-16850971077f.jpg)

![20220119093600_1](https://user-images.githubusercontent.com/60544088/150095246-8f812fcb-a72f-4ac8-aced-58730dd04b7c.jpg)

![20220119093622_1](https://user-images.githubusercontent.com/60544088/150095274-68e51d20-ffee-4157-880b-913c49490540.jpg)

![20220119093637_1](https://user-images.githubusercontent.com/60544088/150095304-fcb15ab0-4c7c-423d-b3aa-ed730be806c0.jpg)

**Courseplay version**
Version used: v7.0.0.20

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7895476/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Bruin 4200 Field Sprayer

**Relevant script mods**
CP, MoneyTool

**Comment by Tensuko** [comment]
Geeze, increase the speed and its fine....
There is not a bug or anything to enhance, sure can increase the default limit but there is not reason to open one Issue after the other.....

**Comment by Tensuko** [comment]
And btw if you don't know that.
That speed setting is under vehicle settings.

**Comment by Tensuko** [comment]
Nevermind your screenshots are too smal....
But where is the problem to just increase this ?!

**Comment by TheSoldier91** [comment]
For sure i know where to find.
But in case you work on several missions with rental machines, isnt it easier to adjust it once (as default) as for every vehicle?

**Comment by Tensuko** [comment]
Pushed the default change for you but this is something you can explain in the 1st Issue. Thats why we ask for informations!

Example:

- Default setting is to low from some vehicles
- With many Vehicles from Missions it is a lot of work to increase each single vehicle's field work speed

Suggestion: Increase default valure to 25

That got nothing to do with detection or anything and when we don't know the core problem, it is hard to tell what you rly want...

**Comment by Tensuko** [comment]
Ach und nur so, wenn es auf englisch zu schwer ist für dich, darfst du auch auf deutsch schreiben :)

**Comment by TheSoldier91** [comment]
> Ach und nur so, wenn es auf englisch zu schwer ist für dich, darfst du auch auf deutsch schreiben :)

Ist mir auch lieber :)
Dann kann ich mich vielleicht auch mal vernünftig ausdrücken..

Mir gehts darum dass ich normalerweise ca. 10 Aufträge gleichzeitig laufen habe mit gemieteten Geräten.
Wenn ich für jedes Gerät die Arbeitsgeschweindigkeit einstellen muss ist das ziemlich nervig.
Deshalb die Frage nach der Erhöhung der Standard Arbeitsgeschwindigkeit oder der automatischen Erkennung der max. Geschw.

**Comment by Tensuko** [comment]
Gefahren wird immer mit der maximalen höchstgeschwindigkeit des Tools, begrenzt durch Feldarbeits Geschwindigkeit.
Die haben wir mit 15km/h angenommen aber klar hast du recht, einige arbeiten uach mit 20 oder 25.
Da kommt der Punkt wo wir sagen naja dann erhöhe es halt.
Ja wenn du sagst du hast viele Geräte wo du das immer erhöhen musst, dann kann man das tun, aber diese Erklärung brauchen wir halt weil nur weil "man das gerne so will" reicht uns nicht :)
Wird also für die nächste Version auf 25 km/h Limit als standart drin stehen ;)

**Comment by TheSoldier91** [comment]
Dann verzeiht meine unverständliche Ausdrucksweise ;)
Bis dahin ändere ich für mich selbst die config :)

**Comment by Tensuko** [comment]
Alles gut.
Siehst du ja im Commit wo ich das geändert habe.
