### ISSUE TITLE
[Feature] Auto close the mini hub after hiring (or fireing) a helper

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#602]
After starting a course using the mini hub, you always have to close the mini hub.
It would be nice that the mini hub will automatically close after hiring (or fireing) a helper.
Or maybe make this configurable.

![image](https://i.imgur.com/1UWAKwq.jpeg)

**Comment by Tensuko** [comment]
Will have a nice update soon.
