### ISSUE TITLE
[BUG_SP] Course generation and turns

### ISSUE THREAD

**Issue by JustDen1234** [Courseplay/Courseplay_FS22#603]
Created a course for field with 90 degrees angles (default field on NoMandLand).

The generated course does not align with the fields sides (in previouse versions of CP it was fine).

Start point:
![2022-01-19 13_06_47-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128641-42b95144-9b25-4fc4-be8f-b544a5e236dd.jpg)

Settings:
![2022-01-19 13_07_02-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128659-65b5214a-4482-456c-8f39-28de1aaf67de.jpg)

Result:
![2022-01-19 13_07_11-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128646-3642c051-e8c2-437c-8353-24958345f91c.jpg)

![2022-01-19 13_08_16-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128800-2d9fbb27-125b-4701-9027-e45b0b817d14.jpg)

And the first couple of turns are a little bit strange.

First turn:
![2022-01-19 13_09_10-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128847-e21b4fa3-f033-4d5d-a2bb-40d7a7e08236.jpg)

Second turn:
![2022-01-19 13_09_52-Farming Simulator 22](https://user-images.githubusercontent.com/68871402/150128855-29b5f449-3cda-4d51-b79e-3ae780d6e43e.jpg)

The third turn was fine.

Maybe the issue with the turns is related to the course generation? 
Becuase on two other fields on the map, the generation of the courses and the turns are not a problem at all.

Version: v7.0.0.20 
Logfile: [log](https://gist.github.com/JustDen1234/512ff61703fe1f445d57f961a62aa06a)
Map: No Mans Land
Combine: Rostselmash Nova 330 (start combine on map)

Installed mods:
- AutoDrive
- VCA

**Comment by JustDen1234** [comment]
Just restarted the game, generated the course with the same options as above, and now the generated course is alligned with the field as expected. Very strange. Maybe a hickup?!

**Comment by Tensuko** [comment]
Don't know but I had the same with the generator.
Choosed longest edge as starting direction.

About turns:
https://github.com/Courseplay/Courseplay_FS22/wiki/What-type-of-Turns-and-when-they-are-used.
But we should have a look.
Debug was on ?

**Comment by Tensuko** [comment]
Check 7.0.0.21
