### ISSUE TITLE
New Anhydrous Tools[BUG_SP]

### ISSUE THREAD

**Issue by jdog1981** [Courseplay/Courseplay_FS22#605]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Using the New anhydrous toolbar with a pulled tank. Ai will not turn on the tool and put down fertilizer. It just drives around like a plow. Wasnt sure if its a mod issue or something courseplay has to add. I know these type of tools will become more relevant with anhydrous being added to maps now. 

**Actual behavior**
A clear and concise description of what happen.
New anhydrous toolbar with a pulled tank. Ai will not turn on the tool and put down fertilizer. It just drives around like a plow
**Expected behavior**
The ai should turn on the tool like a plater does and allow spray to be put to the ground. 
**Screenshots**

**Courseplay version**
Version used:  Newest 20

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Deer Creek , this map comes with said toolbar and tanks as its the first map with anhydrous. Can be downloaded from Central Ohio Modding on Facebook. Thanks
**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ? yes

**Comment by Tensuko** [comment]
Sounds like a mod Issue and as this is not on ModHub, this could be anything.
Sry will not support this for now.
If tool does not turn on it seems to be mod Issue.
