### ISSUE TITLE
[Feature] Anlegen von Rübenmieten

### ISSUE THREAD

**Issue by MermaidSystem** [Courseplay/Courseplay_FS22#606]
**What is the problem this feature/enhancement solves?**
Die Möglichkeit, mit den Rodern mieten am Feldrand anlegen können.

**Describe the solution you'd like**
Zuckerrüben werden nur selten direkt verladen. Stattdessen werden die Rüben erst einmal am Feldrand zu einer Miete abgeladen umd später abtransportiert werden zu können. Dies sollte sich über die "Unload Anywhere" Möglichkeit umsetzen lassen. Das Feature "Drescher fährt selbst abtanken" dürfte sich hierfür verwenden lassen.

**Comment by rohne83** [comment]
Wäre eine coole Sache. Aber nicht nur durch den Roder selbst sollten die Mieten angelegt werden können, sondern zumindest auch durch die Kartoffel/Rüben-Überladewagen. Standardspiel hat ja schon drei davon dabei, und auf großen Feldern sind die auch bitter nötig. Da die wie die Roder ebenfalls seitlich abladen sollte da ein und die selbe Implementierung der Abladefunktion für beide ausreichen.
Im 19er ließen sich Mieten ganz gut mit normalen Anhängern im Mode 2 per Rückwärtsabkippen anlegen. Für sowas stell ich es mir ohne selbst einfahrbare Kurse schwieriger vor, aber könnte man ebenfalls zumindest im Hinterkopf behalten.

**Comment by Tensuko** [comment]
Wir überlegen uns was.

**Comment by rohne83** [comment]
Falls ihr euch noch nichts zu überlegt habt, eine Idee die mir kam, jetzt wo man auch Feldrandkurse einfahren kann: Man könnte ja die Kursaufzeichnungsmöglichkeit nutzen um auch eine Strecke für die Miete einzufahren. Also wenn aus dem eingefahrenen Kurs kein geschlossener Kreis wird sondern eher eine Gerade, dann deutet CP dies nicht als Feldrandkurs sondern als "Abladekurs" für solche Mieten. Anfang der Miete am Startpunkt, Ende am Endpunkt. Sobald der Abfahrfüllstand erreicht und auf irgendeine Art dieser Mietenkurs ausgewählt ist, fährt CP dann immer zunächst den Startpunkt an, versucht dort abzuladen wie mit STRG+I, und sobald an dieser Stelle nichts mehr auf den Boden geht wird entlang des Kurses ein Stück nach vorn gefahren (ähnlich wie AD das in Keilsilos macht).
Sollte für Roder und Rüben-ULW gleichermaßen funktionieren, und theoretisch sogar für normale Anhänger anwendbar sein.
Liegt natürlich am Spieler dafür zu sorgen, dass die Abladeseite aller Fahrer übereinstimmt, das Feld auch in seinem Besitz ist wegen dem auf den Boden kippen, und auch dass der Mietenkurs überhaupt lang genug ist um den ganzen Ertrag des Feldes aufzunehmen. Aber CP muss das Denken den Leuten ja nicht auch noch abnehmen ;)

**Comment by hermannbrauer** [comment]
hast du mal versucht das mit AD zu lösen? also den ersten Abkipppunkt musst du von Hand setzen, dann sollte das eigentlich gehen... wäre doch mal ein versuch?!

**Comment by Tensuko** [comment]
> Man könnte ja die Kursaufzeichnungsmöglichkeit nutzen...

Nein.

Das wird wenn dann anders gelöst und Ideen gibt es, aber über die sprechen wir noch nicht.

**Comment by Terrabey** [comment]
Wie sieht das jetzt aus mit den Mieten also klar ich sehe es Low Prio aber ist ja jetzt schon fast ein Jahr rum und gesehen haben wir immer noch nicht.

**Comment by Tensuko** [comment]
Ist das jetzt dein ernst ?
1) wir machen das neben Arbeit und Familie
2) Haben wir viel anderes gemacht
3) und wenn es 2 Jahre dauert ist es halt so!

Lerne LUA programmieren und mach nen pullrequest auf mit dem das sauber implementiert wird. Dann geht es schneller!
