### ISSUE TITLE
[BUG_SP]Seedhawk not fertilizing

### ISSUE THREAD

**Issue by Petromotion** [Courseplay/Courseplay_FS22#614]
**Steps to reproduce**
Seeding with 84ft Seed Hawk trailer and toolbar.

**Actual behavior**
Unable to fertilize

**Expected behavior**
Assuming CP only sees seed in the Seed Hawk and not the fertilizer. 

**Courseplay version**
Version used: .20

**Map**
Deercreek

**Vehicles/ implements involved**
Wich vehicle or implement? 9rx / seed Hawk and toolbar by Forward AG
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
This is a none ModHub Mod.
And you attached no logfile...
Does it work with the Giants Helper ?

**Comment by Tensuko** [comment]
Might be this "Fertilizer Setting fix #513"

**Comment by erscal** [comment]
For what it's worth, using the Seedhawk 84ft toolbar I'm receiving the same error as other users with the Bourgault: "Stopped CP, as the fertilizer is empty", not even continue the work with seeds only.
To my memory, I've never used the Bourgault with CP until today but I may be wrong.
Actual CP version is 7.0.0.25

At this point, to me that seems an issue within the toolbar+tank setup whereas the code isn't able to read the tank connection but stops at the toolbar "filllevel" (an obvious 0) and decides to look no further.
I'm afraid I'm not able to help right now, I've never investigated the tool/tank relations, I'm just using logical thinking based on this thread and my experience.

**Comment by erscal** [comment]
I've just noticed the waiting for user label, so I chime in hoping to give some input.

1) Helper AI works fine
2) I can't pass you my logfile right now, it's 8 MB and completely messed up; I will just copy the error line:
`2022-01-31 23:40 :59 [dbg20 lp194043] Magnum 340 BI Turbo/820: Seed Hawk XL Toolbar 84FT/?: Stopped Cp, as the fertilizer is empty.`

Tell me if you need anything else, I can give a test to the Bourgault 3320 in a mod free run (just tell me how to enable CP logging and what do you need.....).
