### ISSUE TITLE
Bug & Enhancement: Bale collect/wrap mode does not work when vehicle has a course

### ISSUE THREAD

**Issue by TransportTycoonJoker** [Courseplay/Courseplay_FS22#615]
I know its still in early stage, but still some feedback on the wrapping task.
**Steps to reproduce**
Setup a course for mowing and use it for baling.

**Actual behavior**
Driver uses the course as generated. No issue here. Though he runs it with max possible speed, completely ignoring any settings on either the work or the field speed. As all wrappers to have an offset, it is not collecting & wrapping any bales. 

**Expected behavior**
Settings on working and field speeds are respected. Offset is identified and adjusted automatically. Once manually adjusted it does the job correctly. a bit fast, but correctly

**Comment by Tensuko** [comment]
Mixing 2 things into one Issue with such a smal description does not make it easy to understand whats going on...

So you say Balers ignore the field work speed ?

What is the problem with wrapping and collecting ?
Discribe it one by one....

**Comment by pvaiko** [comment]
@TransportTycoonJoker you know we have bale wrapper/collector mode which does not need a course at all?

**Comment by TransportTycoonJoker** [comment]
sorry for being unclear.
So I have a field, the worker did the baling. That worked excellent. I've used the same course then use the new functionality for wrapping the bales. This worker however just runs down the same course in max speed. I've started this via the Mini HUD menu, with the course being active.

@pvaiko: ok.  How does that work? I have the wrapper attached, opened the Mini Hud, selected the corresponding mode and hired the worker. It immediately tells me that there is nothing to do. (I am on the field)
![image](https://user-images.githubusercontent.com/80276998/150337947-3c0f3248-c058-4c0f-a29b-6ec1a77e1e99.png)

**Comment by TransportTycoonJoker** [comment]
Never mind for the pic. I've combined fields and the grass bales are on another field. Wrapper mode works. Please discard this item!

**Comment by TransportTycoonJoker** [comment]
One thing to add:
the Collect/Wrap Mode only works if there is no other loaded course for the vehicle. Otherwise it will fall back to the above behaviour or will just run straight in full speed

**Comment by fudoido** [comment]
Myself can't get it to work even, no courses loaded, tractor is on field, option to collect/wrap is on, but when I start it tractor just drives backwards. If I load the combine course (which was also used for the baler, meaning bales will be in the same alignment most time), then it drives full speed ahead and no matter what offset I put, it will still drive centered to course.

**Comment by pvaiko** [comment]
@fudoido there is nothing we can do without a log with activated debug for the vehicle.

**Comment by rohne83** [comment]
For the original issue: in FS19 it was always very helpful that you could run the bale wrapper/collector not only in mode 7 but also in mode6 on the baler's course. Used this mode (with proper offset set manually of course) to get large part of the bales off the field quite quickly, and then only used mode 7 for the remaining bales. Especially on larger fields this approach saved me dozens of hours. Mode 7 is very good to clean sweep the field quite quickly if the amount of bales and the distances are not too huge. But for bales in long field rows, it is much slower than the mode 6 approach.
Would it be possible to have those vehicles also drive down a loaded course again, just obeying to the offset and speed settings?

**Comment by pvaiko** [comment]
Bale wrapper should be working already if you start a course, doesn't it?
