### ISSUE TITLE
[Question] 4 more strings !!

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#617]
In the Italian translation file, I find these 4 strings, but I can't find them in the English and German files. I don't understand where they come from, since I can't even find the link to the function. Now I have temporarily eliminated them, I do not want them to cause problems.
![Screenshot_4](https://user-images.githubusercontent.com/24955554/150379711-9017ccf9-0699-4fe3-b004-ccce36213e30.jpg)

**Comment by Tensuko** [comment]
Dramatical !! :)
