### ISSUE TITLE
[BUG_SP]mäht nicht

### ISSUE THREAD

**Issue by bertls-hof** [Courseplay/Courseplay_FS22#619]
version 7.0.0.20
nomans land
1.fahrzeug
krone bigM450
2.fahrzeug
jcb fastrac8330
poettinger novacat301
poettinger novacatA10CrossFlow

bei den Varianten wird der Mäher abgesengt und eingeschaltet aber es wird nichts geschnitten.
![fsScreen_2022_01_20_17_39_35 Kopie](https://user-images.githubusercontent.com/97104733/150383921-fb225844-b361-4c1e-92d4-39eb4e795c5e.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7907024/log.txt)

im Voraus danke für etwaige Hilfe!

**Comment by Tensuko** [comment]
![fsScreen_2022_01_20_18_07_53](https://user-images.githubusercontent.com/27344744/150387371-073c5e0e-b262-4da8-98c9-47e8e791fb3d.png)
Can't reproduce, must be the map or anything else.
When tool is lowered and turned on, there is nothing else that we control to prevent mowing grass.

**Comment by bertls-hof** [comment]
thank you
