### ISSUE TITLE
Helfer wird von einem Objekt blockiert

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/Courseplay_FS22#62]
Habe versucht, einen angefangenen Kurs nach einem Spielneustart fortzuführen (Feld dreschen). Hat mir dann mit der Meldung "Kein Feld gefunden" abgebrochen. Habe dann den Kurs neu gestartet (nahester Wegpunkt), dann bekomme ich die Fehlermeldung, das der Helfer von einem Objekt blockiert wird, fährt dann zum ersten Wegpunkt (obwohl nahester eingestellt ist). Dort kommt dann die Meldung, dass er kein Feld gefunden hat. Bin auf Version 7.0.0.3 aus dem repository.
Was mache ich falsch? Wie kann ich einen angefangenen Kurs fortführen? Es ist echt schwierig, CP ohne ein HUD, nur über das LS-Menü zu konfigurieren.

![fsScreen_2021_12_25_08_30_37](https://user-images.githubusercontent.com/21023840/147380012-0a272d8e-00d9-4ee7-abae-285673e4af39.png)
![fsScreen_2021_12_25_08_30_48](https://user-images.githubusercontent.com/21023840/147380014-505d60d6-b191-445b-beb9-9bc4e0fb06a7.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7775583/log.txt)

**Comment by iljarogoff** [comment]
Anmerkung noch: habs mit der latest zip probiert, da funktioniert es.

**Comment by alex2ruote** [comment]
Ich hatte das gleiche Problem mit dem Mähdrescher, ich musste nur aus dem Fahrzeug aussteigen und er begann sofort seine Arbeit.

**Comment by Tensuko** [comment]
Da es der giants helfer ist, sind da auch ein paar funktionen von drin. Eventuell müssen wir was davon anpassen, aber mit H muss es funktionieren

**Comment by Tensuko** [comment]
Denke das ist erst mal gelöst.
Tip am Rande: Man kann CP auch mit H starten, wenn man einmal einen Job CP Feldarbeit gestartet hat.
Wird in Zukunft noch verbessert.
