### ISSUE TITLE
[BUG_SP] Implement Folding at end of Course

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#623]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Run course with Fendt 1050 and Farmet Kompaktomat 1570 Max with Fold Implement on.

**Actual behavior**
Incorrectly folds equipment

**Expected behavior**
Correctly fold equipment

**Screenshots**
Incorrect

![fsScreen_2022_01_20_13_14_52](https://user-images.githubusercontent.com/96673100/150406868-584a484b-fe68-471f-b925-c5bedb869520.png)

Correct

![fsScreen_2022_01_20_13_15_09](https://user-images.githubusercontent.com/96673100/150406919-1918e501-c4e0-44c9-a80a-fe77c137754e.png)

**Courseplay version**
Version used: 0.20

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7907924/log.txt)

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
See Above

**Relevant script mods**
AD, but not active

**Comment by Tensuko** [comment]
This could be the tool itself.
I heard about Issues with that Tool for a long time now.

**Comment by berni3786** [comment]
dass Problem hab ich mit diesem gerät auch auf dem dedi Server und das ohne Courseplay!! 
Hat eher mit Autodrive zu tun als mit Coursepley.

**Comment by Tensuko** [comment]
Ich hatte schon probleme mit dem Gerät gesehen da wusste noch niemand das AD kommt und CP war noch nicht da also.....

**Comment by Tensuko** [comment]
Works so it is the problem of that tool.
![fsScreen_2022_01_20_21_45_30](https://user-images.githubusercontent.com/27344744/150419463-ecb0847c-ee29-4b04-9485-f3b7b005d6eb.png)
