### ISSUE TITLE
[BUG_SP] game fails to load

### ISSUE THREAD

**Issue by SledgeHammer75** [Courseplay/Courseplay_FS22#625]
current GIT-version (2022-01-22, 20:21 CET, should be 7a57985) hangs on loading savegame at 85%, log shows

```
Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/censored/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/specializations/CourseplaySpec.lua:89: attempt to call global 'CourseplayHud' (a nil `value)
```

release version .20 works fine

**Comment by Tensuko** [comment]
We have a Template, it would be nice if you use it...
I can load both, an old savegame and a new savegame.

**Comment by leo32128fs** [comment]
I also had the same problem in the saved game it crashes at 85% in a new game it crashes in the store when buying new vehicles both with the same error in the log
