### ISSUE TITLE
[BUG_SP] Incorrect speed for turning maneuvers

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#626]
**Steps to reproduce**
Set speeds for field, fieldwork and turning to different levels

**Actual behavior**
Vehicle always using the fieldwork speed as the max for turning. We have

**Expected behavior**
As I understand, it should rather use the set speed for field and/or turns. I like to use the fieldwork speed for having the vehicles run more realistically (10kph is too much for a combine), but that would slow down the turns drastically as well. It's not a new issue, we had it with the first CP 7 version as well as with CP 6.

**Screenshots**

![fsScreen_2022_01_20_20_13_59](https://user-images.githubusercontent.com/71030138/150411152-5e6c31b1-e757-4a4f-9d18-22dba14dfe9d.png)
![fsScreen_2022_01_20_20_14_44](https://user-images.githubusercontent.com/71030138/150411186-8a8d2be6-2ac4-4b91-a2b8-ab51b530b7e9.png)

**Courseplay version**
Version used: 7.0.0.20 

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7908049/log.txt)

**Comment by Tensuko** [comment]
Looks like Pathfinder turn.

**Comment by pvaiko** [comment]
This is fixed by @Tensuko in 71dc2a67bb1e2a79eb877238fab5e420e90d5f00, he just can't remember it...

**Comment by Tensuko** [comment]
I thought that was only for drive to 1st and last waypoint... but yes sure this is also for long distance turns....
