### ISSUE TITLE
[BUG_SP] Bourgault Air Seeder empty tank when not empty

### ISSUE THREAD

**Issue by ThomasDeMarez** [Courseplay/Courseplay_FS22#628]
**Actual behavior**
Worker does not want to plant and seed because it thinks the fertilizer tank is empty. When running the same course with the fertilizing disabled there is no issue.
I reset the tractor and reloaded seed and fertilizer into the cart, no difference.

**Expected behavior**
Worker should seed and apply fertilizer
-> Regular AI worker has no issues
-> No issue in release 7.0.0.19

**Screenshots**
![course](https://user-images.githubusercontent.com/10974106/150417191-3e4ff77c-a404-461a-8ef3-c0dfb6b7435b.png)

**Courseplay version**
Version used: 7.0.0.20

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7908315/log.txt)

**Map**
Base US map

**Vehicles/ implements involved**
Wich vehicle or implement? Bourgault Air Seeder 23.2m
Mod: yes (I can provide a link to the mod if necessary)

**Relevant script mods**
Guidance Steering, but not activated at that time.
Real Speed Limit, also not activated.

**Comment by Tensuko** [comment]
Does this work with Giants Helper ?

**Comment by ThomasDeMarez** [comment]
Yes, regular AI has no issue seeding and fertilizing

**Comment by Tensuko** [comment]
#614
