### ISSUE TITLE
Düngefunktion bei Saatmaschine kann nicht Deaktiviert werden

### ISSUE THREAD

**Issue by Nealswiss96** [Courseplay/Courseplay_FS22#63]
Wenn man in den Grundeinstellungen vom Helfer, Dünger auf Kaufen hat, gibt es eine Düngerstufe egal ob die Düngefunktion der Saatmaschine über die CP Einstellungen ausgeschalten wurde.
<img width="1752" alt="1" src="https://user-images.githubusercontent.com/66141267/147380545-e33d15c4-1b07-4e1a-907e-b596901322b6.png">
![2](https://user-images.githubusercontent.com/66141267/147380552-954740ec-ee4b-41d4-8972-4f972c0b15b4.png)
<img width="1752" alt="3" src="https://user-images.githubusercontent.com/66141267/147380554-d645e44a-bd14-4041-988c-ff917c96eaff.png">

**Comment by Tensuko** [comment]
Dann ist das setting noch nicht aktiv, kommt aber wieder.

**Comment by Tensuko** [comment]
Duplicate #110
