### ISSUE TITLE
[BUG_SP] Rock Pickers Keep Going When Full

### ISSUE THREAD

**Issue by SpacemanJay** [Courseplay/Courseplay_FS22#630]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use CP to drive any of the 3 ingame rock pickers on a field until it isi full, and it will keep going.

**Actual behavior**
All 3 ingame rock pickers will continue to work the field when they reach 100% full. However the game still counts the stones as cleared from the field..

**Expected behavior**
When full, the player should be given a message it is full, such as with a harvester, and work should pause.

**Screenshots**

**Courseplay version**
Courseplay for FS22 v7.0.0.20

**Log**
Please let me know if log is needed in this case and I will read up on how to provide one.

**Map**
No Man's Land, but happens on Elm Creek as well.

**Vehicles/ implements involved**
All 3 ingame rock pickers

**Relevant script mods**
GPS installed and active, not being used when CP is used.

**Comment by Tensuko** [comment]
Giants bug.
