### ISSUE TITLE
Wie bekomme ich das neue Mini-Hud ausgeblendet?

### ISSUE THREAD

**Issue by Porter76** [Courseplay/Courseplay_FS22#633]
![fsScreen_2022_01_21_15_43_12](https://user-images.githubusercontent.com/96634197/150546613-13cd4421-6066-4cb6-9a0e-56f4293d3230.png)

Wie bekomme ich das neue Mini-Hud ausgeblendet? 
Fahrzeuge wie Telelader oder Radlader benötigen kein CP.
Danke

**Comment by Tensuko** [comment]
Aktuell gar nicht. Siehe bitte #632

**Comment by Porter76** [comment]
Schade. Denn damit hat man derzeit eine sehr nervige Doppelbelegung der rechten Maustaste. Besonders bei Radlader oder Teleskoplader. Hoffe ihr kümmert euch recht schnell darum. Ansonsten gute Arbeit!

**Comment by Tensuko** [comment]
Oh sh!t.
Das haben wir wirklich übersehen.
Ehm ja muss leider erst mal so bleiben weil wir noch ein Großprojekt am start haben das erst mal fertig werden muss, dann kümmern wir uns natürlich darum!
