### ISSUE TITLE
[BUG_SP]Pflug dreht nicht vollständig beim wenden (Kverneland PW 100 - 12)

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/Courseplay_FS22#634]
**Steps to reproduce**
Kursgenerierung: 3x Vorgewende, Anfang im feld nicht vorgewede, Vorgewende Scharf, sonstiege einstellungen Standart CP

**Vehicles/ implements involved**
in meinem Fall war der John Deer 7r und Kverneland PW 100 - 12 beteiligt

wie im viedeo zu sehn gepannt startet fährt zum wende punkt pflug hebt aus er wendet setz ein und dreht denn plug nicht zu ende 
Wie man sieht hat er auch probleme die spur zu finden (denke ich)

**Expected behavior**
er solte denn Plfug ausheben weden dabei Pflug drehen und wieder ein setzen und gerade weiter fahren 

**Map**
Elmcreek

**Courseplay version**
v7.0.0.21 

Video:
https://drive.google.com/file/d/1JaXbYTBGY5qc5bBHlKMAaLH-DCiq3XYo/view?usp=sharing

Log:
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7914824/log.txt)

**Relevant script mods**
keine

**Comment by Tensuko** [comment]
@pvaiko ich hab mir den Pflug mal angeschaut.
Er hat 2 workAreas wesshalb wir wohl die Arbeitsbreite nicht richtig kriegen (wird auf 1m gesetzt wenn eingeklappt, aber pack ich noch in die config) aber auch der Offset ist falsch.

Warum der Pflug nicht bis zum schluss gedreht wird verstehe ich aber nicht, Event wird gesendet und er fängt an, landet aber in der "eingeklappt" Stellung.

![fsScreen_2022_01_21_16_24_47](https://user-images.githubusercontent.com/27344744/150556523-5108a29e-85ca-4e8e-84ac-86ac73d54c96.png)

**Comment by Neotras2552** [comment]
Vorgewende wird auch nicht sauber ausgearbeitet
