### ISSUE TITLE
[Feature] A separate small mod to "set" and "go to" Shovel Positions? 

### ISSUE THREAD

**Issue by Justin3625** [Courseplay/Courseplay_FS22#639]
**What is the problem this feature/enhancement solves?**
I'm always frustrated when I have to move to the load and unload positions for loading/unloading things on a trailer or bucket filling and is very repetitive and you have to be accurate each time.

**Describe the solution you'd like**
I would really love a mod for vehicles that I can move the bucket to a position and "save" that position to "slot 1". Then with a key press (1) for example have the bucket always return to the saved position of that slot.
Very similar to how in Courseplay you set the Shovel Positions but just a small mod on its own for when you're driving vehicles and set/changed with a keyboard/controller input. also have a button for "next" and "previous" position.

For pallets, perhaps from "load position" it drops the forks a small bit so it lets go of the pallet and you can back away.

**Comment by schwiti6190** [comment]
A mod for manual shovel positions, similar to the position of the old cp shovel mode mentioned, was send to the modhub by us a while a go and will be released soon hopefully :)

**Comment by Justin3625** [comment]
@schwiti6190 Thank you! what's the title? so I can keep a look out for it.

**Comment by schwiti6190** [comment]
ToolPositionSaver_FS22 or something similar :)

**Comment by Tensuko** [comment]
FS22_ToolPositionSaver

I try to push it a bit for modHub but untill now I got ignored xD
