### ISSUE TITLE
The "CP Fieldwork job" does not show up on the helper screen

### ISSUE THREAD

**Issue by reggie368** [Courseplay/Courseplay_FS22#64]
Hi !
First, thanks for this new version. :)
The "CP Fieldwork job" does not appear on the helper screen.

**Comment by Keppchen** [comment]
In Helper Screen on Top Left you can swap between Fieldjob, Drive (or similar - i play in german) and CP: Fieldjob

**Comment by Tensuko** [comment]
Top right. But what tool do you have attached ?

**Comment by Keppchen** [comment]
> Top right. But what tool do you have attached ?

Oh no. After 30 years I get a left/right issue 😅

**Comment by reggie368** [comment]
> In Helper Screen on Top ~Left~ Right you can swap between Fieldjob, Drive (or similar - i play in german) and CP: Fieldjob

Ah Ok, I get it ! Thanks !
