### ISSUE TITLE
[BUG_SP]Currently baleloaders can load bales, but won't stop when full.

### ISSUE THREAD

**Issue by lgxxxxx** [Courseplay/Courseplay_FS22#643]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
Currently baleloaders can load bales, but won't stop when full

**Expected behavior**
Stop after loading the last Bale

**Screenshots**

https://user-images.githubusercontent.com/11899013/150637411-e09d2de4-81c2-42a9-b414-294a1e13eac0.mp4

**Courseplay version**
Version used:  d9bb904c5610ed1fe38fef1e1a1c9d674df14690

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7918265/log.txt)

**Map**
Elmcreek 

**Vehicles/ implements involved**
Wich vehicle or implement? 
Mod  - no 

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Only Autodrive

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.22
Reopen if issue persists.
