### ISSUE TITLE
[Question] Wann kommt die Multiplayer Unterstützung?

### ISSUE THREAD

**Issue by Kitekater** [Courseplay/Courseplay_FS22#644]
Hallo zusammen,

ich sehe zu, wie die Versionsnummern wachsen, mit Verbesserungen oder neuen Features, aber dass die Multiplayer Unterstützung endlich mal eingebaut wird, vermisse ich leider immer noch.

Wann wird das in Angriff genommen?

**Comment by mfehr94** [comment]
@Kitekater laut Aussage der Entwickler werden keine Timelines kommuniziert. Also kommt es wenn es kommt. Habt bitte etwas Geduld.

**Comment by Tensuko** [comment]
Desshalb zu.
