### ISSUE TITLE
[BUG_SP] Tiersound 

### ISSUE THREAD

**Issue by PascalVR** [Courseplay/Courseplay_FS22#647]
Wenn man am Kuhstall in einem Fahrzeug sitzt, werden die Tiergeräusche extrem Laut und sind sehr verzerrt.

**Comment by Fendtie** [comment]
This has nothing to do with CoursePlay, it exists without CP too. ;)

https://forum.giants-software.com/viewtopic.php?t=187329

**Comment by Tensuko** [comment]
Ja und was haben wir damit zu tun ?

**Comment by PascalVR** [comment]
Alter was ein Service hier 🤦🏻‍♂️

**Comment by mfehr94** [comment]
> Alter was ein Service hier 🤦🏻‍♂️

Das hat nix mit Service zu tun. Das Problem hat aber nix mit dem Mod zutun sondern mit dem Basisgame an sich siehe link von @Fendtie
