### ISSUE TITLE
[BUG_SP] Problems Saving Courses

### ISSUE THREAD

**Issue by Rosencrafter** [Courseplay/Courseplay_FS22#651]
**Steps to reproduce**
I could reproduce the issue in the same session with that vehicle multipl times.
i had this issue before, but i cant tell how it is initially produced. restarting the game sometimes helps to solve the Problem.

**Actual behavior**
1. genereated a CP Course in the ESC-Menue
2. Opend the Coursemanager
3. clicked "X Kurs Speichern"
4. clicked "LEER Activate
5. opend the popup to enter name of Course
6. **only takes 3 characters (see Video below)**
7. click "ENTER Ok"
8. Course is saved to folder

**Expected behavior**
1. genereated a CP Course in the ESC-Menue
2. Opend the Coursemanager
3. clicked "X Kurs Speichern"
4. clicked "LEER Activate
5. opend the popup to enter name of Course
6. takes at least 20+ characters
7. click "ENTER Ok"
8. Course is saved to folder

**Screenshots**
https://youtu.be/d553Dzc4KNA

**Courseplay version**
Version used: 7.0.0.21

**Log**
https://gist.github.com/Rosencrafter/27c78308c022140dc0503e693abdd618

**Map**
Standard US

**Vehicles/ implements involved**
Wich vehicle or implement? JCB Fastrac 8330 with Terrasem C6F
Mod yes/no ? a lot...

**Relevant script mods**
Mods like Autodrive or VCA and so on.
AD latest, GPS, Autoload

**Comment by Tensuko** [comment]
So that means:
Save and restart, one course is okay, then only 3 Letters.
Save and restart again, and everything is fine again.
Save and restart again, onc course is okay then only 3 Letters.
...

Is it like that ?
So like every 2nd save and restart it won't work ?

**Comment by Rosencrafter** [comment]
no.
i teste4d it like 5 cycles and the outcome was:
1. one okay, then only 3
2. all okay ( i saved 4 courses in a row)
3. one okay, then only 3
4. one okay, then only 3
5. all okay ( i saved 4 courses in a row)

So it seems to be more random

**Comment by sirbum69** [comment]
Just for info on this I have also had this happen a few times. Never seemed to be a rythem to it though. Usually closing the game and reopening seems to help it.

**Comment by Tensuko** [comment]
Okay thanks for your testing.
So we at least know when it can appear.
If you find anything more, let us know pls.

**Comment by MaLiXs** [comment]
same issue here using same version than the OP

**Comment by Tensuko** [comment]
Might be fixed, we guessed a mod conflict that should be solved.
Pls reopen if Issue persists in 7.0.0.22
