### ISSUE TITLE
[Feature] Fahrzeugübergreifende Minihud-Position

### ISSUE THREAD

**Issue by Natsu83** [Courseplay/Courseplay_FS22#652]
CP 7.0.0.21
Das neue Minihud ist zwar schön und vereinfacht einigens. Allerdings muss man in jedem Fahrezug das Hud an die richtige Position ziehen. Dies ist insbesonderes dann sehr benutzerunfreundlich und zeitintensiv, wenn man viele Fahrzeuge auf der Map hat.
Sicherlich mag dies auch seine Vorteile haben, aber wie gesagt, ist es viel Aufwand, wenn man viele Fahrzeuge hat.
Mein Vorschlag daher, dass es eine Option gibt, in der man einstellen kann, dass es möglich ist festzulegen, dass die Position des Minihuds für alle Fahrzeuge gültig ist. Um nicht die vor dem Kopf zu stoßen, die das gerne für jedes Fahrzeug einzeln machen wollen, könnte man in den Settings einen Switch implementieren, der zwischen Fahrzeugübergreifend und Einzelposition hin und herschalten kann.

**Comment by Natsu83** [comment]
Ok, sehe gerade, dass es bereits eine ähnliche Anfrage gab: https://github.com/Courseplay/Courseplay_FS22/discussions/632

**Comment by Pandahma** [comment]
Hallo!
Sehe ich ähnlich. Vor allem sollte man das neue Minihud auch ausblendbar machen.
VG!

**Comment by Tensuko** [comment]
> Vor allem sollte man das neue Minihud auch ausblendbar machen.

#632

Für alle Fahrzeuge gleich, ja vlt später, mal gucken...

**Comment by RealNeo80** [comment]
@Tensuko ich will hier keinen extra aufmachen, aber die Position von dem neuen MiniHud wird auch nicht gespeichert sondern ist nach laden eines SaveGames wieder auf Standard

**Comment by Tensuko** [comment]
Wir speichern jetzt die Position des HUD.
Ich behaupte mal das mal eben das Fenster einmalig für ein Fahrzeug verschieben nicht der riesen Aufwand ist.
Issue wird erst mal geschlossen.

**Comment by Tensuko** [comment]
Ach und ist sogar doch global, von daher alles perfekt :)
