### ISSUE TITLE
[Question] Load another course without deleting the current one first in the course manager? - Laden anderer Kurs ohne aktuellen erst zu löschen im Kursmanager?

### ISSUE THREAD

**Issue by haamic** [Courseplay/Courseplay_FS22#655]
Hello,
currently it is so that you have to delete the current course on a vehicle in the course manager before you can load a new one.
Is it possible in the future to be able to load the same without first deleting?
If there is a course on the vehicle and you generate a new one via the helper menu, the current one will be replaced with the newly created one, without having to remove the old course manually.
Greetings Micha
+++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
derzeit ist es ja so, das man im Kursmanager erst den aktuellen Kurs auf einem Fahrzeug löschen muss, um einen neuen zu laden.
Ist es künftig auch möglich, den gleich laden zu können, ohne vorheriges löschen?
Wenn ein Kurs auf dem Fahrzeug vorhanden ist und man generiert einen neuen über das Helfermenü, wird der aktuelle ja auch mit dem neu erstellten ersetzt, ohne vorherigem manuellen entfernen des alten Kurses.
Gruss Micha

**Comment by Tensuko** [comment]
Wow....
ist schon ziemlich schwer einen Knopf in exakt diesem Menü vorher zu drücken.

Sry aber der Aufwand dafür sit zu groß.
