### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by Edwin1631** [Courseplay/Courseplay_FS22#658]
Since this morning i get a error while loading the game..
2022-01-23 11:00 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/Gebruiker/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:61: attempt to index a nil value
2022-01-23 11:02 Application exit request forced.
Any solution on how to fix this?
Yesterday i played the game, and this morning i couldt start the game because of this error.
Didnt changed anything in my mods or so

**Comment by mfehr94** [comment]
No Issue templated used, no complete log. Please read [How to provide a nice and sexy bug report](https://github.com/Courseplay/Courseplay_FS22/wiki#how-to-provide-a-nice-and-sexy-bug-report). With out that the issue will be closed.

**Comment by Tensuko** [comment]
Correct, closed.
