### ISSUE TITLE
With Courseplay the game don't load after 85%[BUG_SP]

### ISSUE THREAD

**Issue by 78sandro** [Courseplay/Courseplay_FS22#659]
With Courseplay my game don't load after 85%.

Without courseplay i can start the game normaly, 2 days ago i have used couseplay and it works 100%.

Thank you

**Comment by Tensuko** [comment]
And another bad report. Read Wiki and use Template!!!

**Comment by andreasthu** [comment]
Hatte ich heute auch, habs aber nicht gemeldet weil in der log stand das mein deutz7 einen courseplay kurs mit 0 wegpunkten hat.
Han dann die vehicle.xml durchgesehen und da standen 3 zeilen beim deutz in der coursplay sektion, die hab ich gelöscht und dann gings wunderbar
Kann dir morgen die xml vom deutz schicken.
Lg
Andreas
