### ISSUE TITLE
I get a warning when entering the game "Missing 'CP_InfoText' in l10n_ru.xml"

### ISSUE THREAD

**Issue by pallexx818** [Courseplay/Courseplay_FS22#66]
Tell me what to do with this problem
![FarmingSimulator2022Game_fuuL9NbKrU](https://user-images.githubusercontent.com/55815470/147381212-326a6d57-b569-409e-9824-d1a50db57dfa.png)

**Comment by Tensuko** [comment]
Should be already fixed, just missed the information inside the translation.

**Comment by adilsonbn** [comment]
I have the same problem in language Portuguese Brazil
