### ISSUE TITLE
[BUG_SP] Minihud is clickable in Building Menu

### ISSUE THREAD

**Issue by Rosencrafter** [Courseplay/Courseplay_FS22#660]
**Steps to reproduce**
1. sit in a vehicle
2. open Building Menu
3. klick on a position where in the backround the CP-Minihud is

**Actual behavior**
1. sit in a vehicle
2. open Building Menu
3. klick on a position where in the backround the CP-Minihud is
4. the Building Menu is closed and the CP ESC-Menu is opend (depends on what you click in minihud: Vehicle, coursemanager etc)
5. you need to get out of ESC Menu and reopen Building Menu

**Expected behavior**
1. sit in a vehicle
2. open Building Menu
3. klick on a position where in the backround the CP-Minihud is
4. Minihud is not clickable

**Screenshots**
https://youtu.be/YrufhhBJkE4

**Courseplay version**
Version used: 7.0.0.21

**Map**
Standard US

**Vehicles/ implements involved**
Wich vehicle or implement? any Driveable Vehicle that has a CP-Minihud
Mod yes/no ? all

**Relevant script mods**
AD, CP, GPS, AutoLoade

**Comment by Rosencrafter** [comment]
Ok its not only the Bulding Menue....
I just recreated it in the Price tab, as you can see in this clip:
https://youtu.be/45n0HH3ZgxM

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.22
