### ISSUE TITLE
[Feature]About Chinese Translation

### ISSUE THREAD

**Issue by aini1123** [Courseplay/Courseplay_FS22#662]
Hi. I have completed the Chinese translation of the latest version 7.0.0.21, but due to the relationship between the Chinese font library of the game, the translation may not be fully displayed in the game, but it does not hinder normal use. How do I upload it nex
[translation_cs.zip](https://github.com/Courseplay/Courseplay_FS22/files/7921952/translation_cs.zip)
t

**Comment by Tensuko** [comment]
The correct way is this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
