### ISSUE TITLE
[Question] New Mini HUD

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#667]
With the latest update, there had to be commands to open and close the new mini hud, but this one is gone .....
If you do not activate it in the settings, the control of the Hud from the gamepad does not even open the old gui with the keyboard, using the Lshift + H keys, to open the old gui, you need to set that command as "activated", while with the mouse , nothing happens, nothing opens ....

**Comment by Tensuko** [comment]
Working as intended.
Setting active, only keybind will open the gui on the side.
Setting deactivated, the new mini HUD will open.

Right click open is a seperate vehicle setting.

**Comment by Roby1164** [comment]
???? Maybe there is a problem, even in making myself understood ....
I understood that in theory, if you put it off, the new mini hud should open, but this does not happen, the old gui on the right continues to open, but there is no trace of the new one. And also, as mentioned, if you leave the compatibility setting with the gamepad disabled, the old gui on the right does not even open anymore ...
How do you say that it works, if already entering the game, the new hud is not visible ???
