### ISSUE TITLE
[BUG_SP] MiniHUD could not be opened with mouse click (or keybind) when AutoDrive is used as well.

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#673]
**Steps to reproduce**
download last branch, try to open the mini HUD

**Actual behavior**
i press the key, nothing happens, also the new MiniHud is not visible

**Expected behavior**
miniHud should open

**Screenshots**
![image](https://user-images.githubusercontent.com/8066324/150780870-80f9525c-886b-4b47-82e3-be2cd7d92a95.png)

**Courseplay version**
Version used: 7.0.0.21 main branch

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7925414/log.txt)

Edit: i made a rollback to commit 600 this is working but still with the old settings, so it has to do something with @schwiti6190  ´s merge of the 2 huds

**Comment by Roby1164** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/667
Idem........

**Comment by RealNeo80** [comment]
#667 i think that was the problem roby thought

**Comment by RealNeo80** [comment]
@Tensuko i think its better here then in the other issue, if i press the right button nothing happend. but its bond to mouse on/off in the settings, is this correct?

![image](https://user-images.githubusercontent.com/8066324/150790524-4f837601-a7d8-4ff3-8ab3-a002f026aa17.png)

**Comment by RealNeo80** [comment]
@Tensuko @schwiti6190 

found it ... Autodrive is interfering somehow ... if i load the save without autodrive i can open the miniHUD by right click. But still not with the insert key like its bond

**Comment by Tensuko** [comment]
What does work is:
Open hud with Mouse activated = Hud opens with Mouse.
Open hud with Mouse deactivated = Hud opens with Keybind.

If you guys would have waited for the Release and read the changelog, you would know it.
And THEN we can talk about, make it possible to use both, Mouse and Keybind always and only turn off the Mouse with that setting and not open 3 Issues for this.

So there is nothing wrong with any commit, but something that you would like to have and we will have a look later.

@RealNeo80 Thanks for testing out in combination with AD. Finaly some useful informations :)
Will have a look.
BTW, do you have Discord ?

**Comment by RealNeo80** [comment]
yep i have ;) use it mostly for writing cause no headset attached on most of my pcs

**Comment by Tensuko** [comment]
Can you contact me ?
Tensuko # 2300 (space to not confuse github)

**Comment by Roby1164** [comment]
So the problem is a conflict with AD ??
This is a problem to be solved ...
If you can't use AD to get the hud, that's not good ...

**Comment by Tensuko** [comment]
The initial problem that got reported was can't open hud with keybind, thats wrong, it is working like we planed it.

But what was found out by @RealNeo80 is a conflict with AD. That we will solve for sure!

**Comment by RealNeo80** [comment]
yep is fixed
