### ISSUE TITLE
[Question] New Mini Hud disappeared

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#674]
Closed with no effective resolution ??
https://github.com/Courseplay/Courseplay_FS22/issues/667

**Comment by mfehr94** [comment]
@Roby1164 please dont open a new issue you can write on the old issue with more info and it will be reopen.

**Comment by Roby1164** [comment]
Same report here too
https://github.com/Courseplay/Courseplay_FS22/issues/673

**Comment by RealNeo80** [comment]
as far as i unterstand the commits schwiti used the new one instead of the "old" mini HUD and something happend when he merged both

**Comment by Tensuko** [comment]
#673
