### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by GabeADemarco** [Courseplay/Courseplay_FS22#675]
First of all thank you guys for your work and beautiful mod.

I'll leave the guidelines, i like them.

**What is the problem this feature/enhancement solves?**
Well i'm working with CP and AD (AD takes care of moving the harvested crop, from near the field) to the silos or wherever), and set CP on the combine to Self Unload.
The "problem" (it's not that bad, nor is it breaking anything), but the problem is that if i set 2 workers on AD to line up and "be filled by the combine", the combine will only unload on the first one and then as soon as it can't unload further on that first one, it goes away.
Moments later the next empty tractor moves a little bit forward and stops at the "fill me please" position, the thing is, i'm using 2 small trailers so one trailer cannot unload the entire combine, but it's about half so it ends up taking more time as the combine capacity is greatly "reduced" by this quirk.
While i'm writing this i'm running FS on the other monitor, and just witnessed the combine unloading on the second tractor (both were lined up to be filled, this time it seems the second one was closer so it decided to unload on that one), now the "back" tractor is filled and the front one is not, i'm not sure if the combine will realize this if the same case (back tractor closer) happens again (and unload on the empty one), if it does it would be by mere chance.

**Describe the solution you'd like**
Well i guess it would be:
-for the combine to detect if more than one "trailer" is near the field and unload on all of those

**Describe alternatives you've considered**
-detect the trailer with the tractor's front end "clear" (i'm trying to say the first one if there's more than one) and always unload on that one, and after that trailer is full if there's still crop on the combine, wait i don't know 30 seconds before moving away to continue to harvest, as it will give time for the AD driver to move forward and keep unloading.

**Additional context**
this photo is from the thing i witnessed earlier, don't worry about the combine not positioned properly i guess something went wrong.
![imagen](https://user-images.githubusercontent.com/98179967/150782928-a00eb9fc-6928-4a3b-9d9c-5ef438adc693.png)

**Comment by Tensuko** [comment]
- Keep self unloading as long as there are trailers around #347

That is aprt of the next Release.
Did you mean something like that ?

**Comment by GabeADemarco** [comment]
> * Keep self unloading as long as there are trailers around [[Enhancement] Combine selfunload, check if trailer got the same filltype #347](https://github.com/Courseplay/Courseplay_FS22/issues/347)
> 
> 
> That is part of the next Release. Did you mean something like that ?

Thank you Tensuko, i believe this is the same, as long as empty trailer means not only an empty trailer in the "active tractor", but also another tractor with another trailer which is empty!

I'm sorry i should've checked the german ones aswell. I'll have to use google translate before posting.

**Comment by Tensuko** [comment]
Its okay and yes, as long as a trailer is available.
