### ISSUE TITLE
[BUG_SP] MiniHUD Textskalierung

### ISSUE THREAD

**Issue by regs1980** [Courseplay/Courseplay_FS22#676]
Die Schriftskalierung des HUDs hat einen leichten Fehler, wenn man die Ingame HUD-Skalierung ändert.

Bei 100% ist alles Normal.

<img width="821" alt="2022-01-24 13_29_31-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/150787897-c8b363da-529b-464f-86f4-2c4e187d66d5.png">

<img width="600" alt="2022-01-24 13_30_31-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/150787913-d7a86ba9-cc2f-41d0-8329-5874367a7bce.png">

Geht man mit den Werten runter, verändert sich zwar die Größe des HUDs nur halt die Schrift und deren Abstände nicht.

<img width="843" alt="2022-01-24 13_25_06-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/150788068-18158917-697b-4f40-b5a3-4e544f031e36.png">

<img width="457" alt="2022-01-24 13_27_58-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/150788079-70734a72-8abb-4596-875f-36ab9abe2abc.png">

**Comment by RealNeo80** [comment]
Zwischenfrage wieso siehst du das mini-hud, welchen Stand hast du von CP?

**Comment by Tensuko** [comment]
Schon mal rechte Maustaste gedrückt @RealNeo80 ?

**Comment by Tensuko** [comment]
> Geht man mit den Werten runter, verändert sich zwar die Größe des HUDs nur halt die Schrift und deren Abstände nicht.

Dann liegt da also das Problem.
Danke fürs ausprobieren!

**Comment by regs1980** [comment]
Sieht sehr schön aus das Endergebnis
Ingame HUD-Skalierung  70% bei 3840x2160

<img width="1344" alt="2022-01-24 22_39_48-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/150869780-77570cdb-0f46-4a3a-b479-d9a6c8291d67.png">

**Comment by IcemanGSXR** [comment]
Wie bekommt ihr dieses HUD? Habe schon einiges probiert aber bei mir kommt dieses HUD nicht!

**Comment by regs1980** [comment]
Nächstes Release abwarten, dann ist es drin.

**Comment by Tensuko** [comment]
Wie bereits berichtet, funktioniert :) Jetzt in der .22
