### ISSUE TITLE
[Question] How do you turn off the little box hud thing in the latest version of Courseplay

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#679]
So have updated to Courseplay Release 21, and now when I load into game, I'm greeted with a new hud element smack bang in the middle of my screen when I'm in vehicles. 

![fsScreen_2022_01_24_17_54_17](https://user-images.githubusercontent.com/13921716/150838840-7ef602c5-a72f-4f4c-805e-d1e53db87f71.png)

I've figured out I can move and position the box to somewhere less irritating on the screen by dragging it with a mouse, but I have to do this with every single vehicle as every single vehicle wants it own box and wants to put it in the middle of the screen. Is there no option anywhere to just be able to disable this? I really don't like huds or gui on the screen all the time if I'm not using that particular mod/tool/feature. In Autodrive I can turn toggle their hud box on and off with a button press. Can we not do the same for this new courseplay box?

**Comment by Tensuko** [comment]
#632

Will be part of our next Release but we have to fix a conflict with autodrive first.
A bit patient pls.
