### ISSUE TITLE
Ladewagen sammelt Stroh

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#680]
Es ist ja Super, dass nun der Ladewagen Stroh einsammelt aber irgendwie bekomme ich es nicht hin, dass er auch - wenn er voll ist direkt dann mit Autodrive zum Abladen fährt und wieder dann am letzten Punkt weiter macht ?

**Comment by regs1980** [comment]
Dafür brauchst du die aktuelle DEV Version von AutoDrive.

**Comment by StefanTreutler1974** [comment]
Welche DEV-Version wäre das ?

**Comment by Tensuko** [comment]
Nicht nur CP, sondern auch die entsprechende AD Version.

Tut mir den gefallen und wartet bis beide Versionen erschienen sind.

Es kommt, ob heute, morgen oder erst am Wochenende....

**Comment by StefanTreutler1974** [comment]
Danke für die schnelle Antwort.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.01.22, 20:50 schrieb Tensuko ***@***.***>:

   
  Nicht nur CP, sondern auch die entsprechende AD Version. 
  Tut mir den gefallen und wartet bis beide Versionen erschienen sind. 
  Es kommt, ob heute, morgen oder erst am Wochenende....

**Comment by ct177mak** [comment]
> Es ist ja Super, dass nun der Ladewagen Stroh einsammelt aber irgendwie bekomme ich es nicht hin, dass er auch - wenn er voll ist direkt dann mit Autodrive zum Abladen fährt und wieder dann am letzten Punkt weiter macht ?

verate  mir mal mit welcher Traktor/Ladewagen Kombi du stroh sammelst ?? Ich hab das mit dem Mainbuild hier versucht ,bei mir senkt er nur unterm Ladewagen die Sammelvorichtung ,aber Geschwindigkeit nimmt das Gespann nicht auf .
