### ISSUE TITLE
bug with bourgault seeders downloaded from fs22 mods. keeps saying tank is empty even though it is not.[BUG_SP]

### ISSUE THREAD

**Issue by dcroft2020** [Courseplay/Courseplay_FS22#683]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen. I enabled cp, helper drives to field (at very beginning does a weird stuttering before driving) unfolds and then says that either the tank is empty or the tool is setup incorrectly.

**Expected behavior**
expected to start planting soybeans on field 56.
**Screenshots**
![20220124143154_1](https://user-images.githubusercontent.com/98356149/150869339-5d77f184-d05c-4b6c-a24a-5daad7e00d86.jpg)

**Courseplay version**
Version used: FS22 v7.0.0.21

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
https://1drv.ms/u/s!AuFi6kiYpAL_yllegpVgy0BPJpqX?e=hCHZPi
**Map**
Map played on. Elmcreek

**Vehicles/ implements involved**
Wich vehicle or implement? John Deere 9620 rx, Bourgault 3320-76 paralink hoe drill. Bourgault 7950 air cart.
Mod yes/no ? yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. AI Vehicle extension add-on, real speed limit, power tools,  player speed,

**Comment by RealNeo80** [comment]
sorry but, Version you play, Logfile Screens?

The Template is to be used!

**Comment by dcroft2020** [comment]
I’m new to pc fs 22 I don’t know what you mean sorry

**Comment by Resandise** [comment]
He means, you should be filling out the template under each **BOLDED** line.

**Comment by dcroft2020** [comment]
yes im trying to figure out how to do everything now. apologies

**Comment by dcroft2020** [comment]
what do i do if it says the log is to big? its not letting me add it...

**Comment by RealNeo80** [comment]
for best, shut down ls22 completely and then restart and do the part what is making problems. then you have a short small log.
its also easier for us to read, if we not have to go through 100K lines in the file

**Comment by dcroft2020** [comment]
Ok, thanks.

**Comment by dcroft2020** [comment]
let me know if I need to send anything else or try and reupload something. sorry it took me so long.

**Comment by RealNeo80** [comment]
i tested it and i´m pretty shure that you have the fertilizer activated and no fertilizer in tank!
fertilizing for seeder need to be deactived in the vehicle settinges, or you need to fill the tank
![image](https://user-images.githubusercontent.com/8066324/150871236-d0254e5c-d24f-499c-a5de-4d6767ae6c02.png)

**Comment by Tensuko** [comment]
Duplicate #614

**Comment by RealNeo80** [comment]
could you please do me a favor: create a new savegame and just use CP and your Seeder. your Log is horrible :p

**Comment by dcroft2020** [comment]
Will do.

**Comment by dcroft2020** [comment]
The bourgault air drill has seed and fertilizer tanks should it still be
deactivated?

**Comment by dcroft2020** [comment]
yea theres a bug with the bourgault planter wont use fertilizer for me.

**Comment by dcroft2020** [comment]
[log.zip](https://github.com/Courseplay/Courseplay_FS22/files/7929549/log.zip)
