### ISSUE TITLE
ESC menu UI/button bug

### ISSUE THREAD

**Issue by bleubasher** [Courseplay/Courseplay_FS22#69]
Strange UI bug in ESC menus where various icons become bundled into a single spot, some of which should not be appearing in ESC menu (Store garage, store sales icon, etc.) Issue confirmed on new save with only CP loaded. Issue seems to happen whenever a CP icon occupies the top most slot of the ESC menu, since everywhere else the CP icons are as expected.

https://i.imgur.com/qVyTBaP.jpeg
https://i.imgur.com/8NjU00Qm.jpg
https://i.imgur.com/tnK8ELt.jpeg

**Comment by Tensuko** [comment]
Yes, this is a very strange one wich come up suddenly. Will have a look at this.

**Comment by pvaiko** [comment]
Fixed already
