### ISSUE TITLE
[BUG_SP] Cannot load my savegame anymore

### ISSUE THREAD

**Issue by freiser77** [Courseplay/Courseplay_FS22#693]
**Steps to reproduce**
I've tested current dev-branch of CoursePlay with self created zip file. Worked before, but not today, so reverted back to stable 7.0.0.21.

Load a savegame of the Haut-Beyleron map with AD and CoursePlay.
AD: Version 2.0.0.3
CP: Version 7.0.0.21

If I delete CoursePlay, savegame can be loaded again.

A revert to version 7.0.0.20 did not help either.

**Actual behavior**
Load stalls at 85 percent.

**Expected behavior**
Loading finishes and game could be played.

**Courseplay version**
Version used: 7.0.0.21

**Log**
https://gist.github.com/freiser77/d6cc25267bc7e7e16d7fabdca94c4874

**Map**
Haut-Beyleron

**Relevant script mods**
AD, guidanceSteering, headlandManagement

**Comment by patrilln** [comment]
i got the same, error was: 2022-01-25 21:11 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
e:/Users/Gebruiker/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:61: attempt to index a nil value

**Comment by Tensuko** [comment]
Did anyone tell you to download the "current main branch" (whatever that means) ?
We create Releases for a reason as the Main Branch can contain untested and unfinished pushes.

**Comment by Tensuko** [comment]
Try to remove more courseplay files from savegame and the My Games Folder of FS22.
More tips I can't give you.

**Comment by freiser77** [comment]
@Tensuko : Is this the way you talk with persons that appreciate your work and can't wait to see what features come next?
Sorry for disturbing "Your royal highness".

**Comment by Redster999** [comment]
One thing is to test it. Another thing is to make an issue regarding this. Stop wasting their time and let them do some real work

**Comment by Tensuko** [comment]
@freiser77 
Sir, when you drive a car that is not finish and create a crash, who is responsable for this ?

Think about this...
This is all due to your unpatient!
