### ISSUE TITLE
[BUG_SP] Fehler bei Lexion 8900 auf Feld 56 bei Elmcreek (CP Vers. 7.0.0.22)

### ISSUE THREAD

**Issue by country1706** [Courseplay/Courseplay_FS22#696]
Nach Erstellen eines Feldkurses auf Feld 56 fährt der Drescher nicht selbstständig los und drescht den Kurs.
Der Drescher wurde danach durch mich manuell ins Feld gefahren und der nächste Wegpunkt ausgesucht.
Auch hier kein Erfolg.

Ich bitte um Hilfe.

Video ist verlinkt.
https://youtu.be/M0tbJr0CoRU

**Comment by rohne83** [comment]
scheint ein generelles Problem zu sein, das auch bei anderen Geräten auftritt. Mähen funktioniert noch, aber zB beim Wenden und Schwaden will er ebenfalls nicht losfahren.

**Comment by polosubtil** [comment]
I have that too. Seems to be happening with temporary courses. It works for me only with saved courses

**Comment by JIIIK** [comment]
Das Problem ist das Konvoi System. Sobald ein anderes Gerät einen Kurs auf dem selben Feld hat, warten die Maschinen aufeinander und fahren nicht an. Einfach alle Kurse aus den Fahrzeugen löschen, und nur das Arbeitsfahrzeug arbeiten lassen, dann klappt es.

@polosubtil I try translating it for you. Sry for the bad english. 
For me, i could solve the problem by deleting all courses from other vehicles on the same field. Just your working vehicle is able to operate on the field. As long as more vehicles have a course on the same field, all vehicles will wait for the others. Seems to be some problem with the convoy system.

**Comment by country1706** [comment]
@JIIIK 
Mein Fahrzeug ist das einzige auf dem Kurs und das ist auch so eingestellt. Daran liegt es also mal nicht.
Ich habe nun wieder die 21er Version von CP drauf, damit funktioniert es einwandfrei.

@polosubtil 
Just to translate my answer.
My vehicel is the only one on the field, and I made sure, that this ist also in the options.
I now tolled back to the version 21 of CP and it works properly

**Comment by JIIIK** [comment]
Um meine Antwort genauer zu geben, bevor es zu Irrtümern kommt. Ich meinte nicht denselben Kurs. Es lag nur daran, dass mehrere Fahrzeuge, unterschiedliche Kurse auf demselben Feld im System haben, auch ohne, dass diese Kurse akltiviert sind.
Nach dem Löschen der Kurse aus den Systemen der anderen Fahrzeuge, fuhr das Arbeitsfahrzeug los.

**Comment by country1706** [comment]
> Um meine Antwort genauer zu geben, bevor es zu Irrtümern kommt. Ich meinte nicht denselben Kurs. Es lag nur daran, dass mehrere Fahrzeuge, unterschiedliche Kurse auf demselben Feld im System haben, auch ohne, dass diese Kurse akltiviert sind. Nach dem Löschen der Kurse aus den Systemen der anderen Fahrzeuge, fuhr das Arbeitsfahrzeug los.

Jetzt versteh ich auch was Du meinst.
Das ist ja nicht so schön.
Dann mach ich erst mal mit der 21 Version weiter bis das gefixt ist.

Danke für die Info 👍

**Comment by JIIIK** [comment]
Gerne, hoffe das hilft dir oder anderen erstmal weiter bis das gefixt wird.

**Comment by pvaiko** [comment]
Was wirklich hilft ist ein Logfile mit Debug. So viele Posts und kein Logfile...

**Comment by MaGGuS3206** [comment]
Hey,

Ich denke ich habe ein ähnlichen bzw den gleichen Fehler. 

Wenn ich zB den Schwader los schicke fährt der ganz normal los. Wenn ich dann den Schwaderkurs in den Ladewagen lade, fährt der Ladewagen los und der Schwadert bleibt stehen. Oder der Ladewagen fährt nicht los. Generell liegt das Problem darin, wenn 2 Fahrzeuge den gleichen Kurs geladen haben.

Hier noch ein auszug aus den Logfile. dieser Fehler wiederholt sich sobald ich im 2. Fahrzeug den startbutton drücke.


2022-01-26 03:19   D:\auto_builder\cache\svn\bc39c0c6d611016d38088dfeb30cadc8\src\engine\app\ReflectionAndScriptBinding.cpp (8113): dirLen > 0.0001f
2022-01-26 03:19 LUA call stack:
  dataS/scripts/vehicles/specializations/SplineVehicle.lua (196) : printCallstack
  dataS/scripts/vehicles/specializations/Locomotive.lua (566) : superFunc
  dataS/scripts/placeables/specializations/PlaceableTrainSystem.lua (729) : alignToSplineTime
  dataS/scripts/placeables/specializations/PlaceableTrainSystem.lua (773) : setSplineTime
  dataS/scripts/vehicles/specializations/Locomotive.lua (546) : updateTrainPositionByLocomotiveSpeed
  dataS/scripts/vehicles/specializations/Locomotive.lua (163) : updateVehiclePhysics
  dataS/scripts/specialization/SpecializationUtil.lua (19)
  dataS/scripts/vehicles/Vehicle.lua (1877) : raiseEvent
  dataS/scripts/vehicles/RailroadVehicle.lua (49) : update
  dataS/scripts/network/NetworkNode.lua (112) : update
  dataS/scripts/network/Server.lua (59) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1180) : update
  dataS/scripts/FSBaseMission.lua (2006) : update
  dataS/scripts/missions/mission00.lua (582) : update
  dataS/scripts/main.lua (1323) : update
2022-01-26 03:19 Validity check failed in TransformGroup_setDirection: Direction is zero 


Hoffe das hilft euch weiter

Gruß MaGGuS

**Comment by dQeLse** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7939145/log.txt)

Hier mal ein Log mit Debug, so wie es aussieht liegt es am Combine.
Ich nutze AD für das Drescher abfahren.

**Comment by Tensuko** [comment]
Continue here: #698
There was used the Template and added a logfile from the start.
@dQeLse ofc thank you for logfile, but this topic got spamed to much already...
