### ISSUE TITLE
[BUG_SP] Course not starting

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#698]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create course and attempt to start it.

**Actual behavior**
Vehicle just sits there with implements on.

**Expected behavior**
Vehicle to drive the course

**Screenshots**
![fsScreen_2022_01_25_21_11_28](https://user-images.githubusercontent.com/96673100/151098646-a7807d47-31ae-417e-bcf5-c3e36dfbeb48.png)

**Courseplay version**
Version used: 7.0.0.22

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7938700/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Case IH Magnum 400 PowerDrive
Vicon EXTRA 132 FT (Mod - Vicon EXTRA Pack (Modhub DL)
Vicon EXTRA 7100T (Mod - Vicon EXTRA Pack (Modhub DL)

**Relevant script mods**
AD but not active

**Comment by Resandise** [comment]
Thought maybe it was the modded mowers, so I tried with a Lindner Lintrac 130 with a POTTINGER HIT 16.18 T tedder, neither are modded, and still the same result

![fsScreen_2022_01_25_21_31_00](https://user-images.githubusercontent.com/96673100/151099473-a5cfa3ad-d7d9-47f1-9979-02b55bbc

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7938736/log.txt)
81b9.png)
.

**Comment by MataGaming** [comment]
I am experiencing the same issue, single tool courses do not start. however multi tool courses work fine

**Comment by Resandise** [comment]
I saved a copy of my gamesave on desktop, started the game with only CP active and still having the same issues.  Reviewing the log, I think I see the issue, if you have multiple vehicles that have a course on the same field, it sits a waits for the others, even though the courses are not the same, a for a Vicon EXTRA mower set is 10.2 meters, but for the Pottinger HIT 16.18 T in 17 meters, and with the multitool setting set to 1, it should not be looking for others to be running the course.

I cleared all other course for the field, and it started up fine, so as of now, you can not have multiple courses loaded for the same field unless your doing multi tool on that field.  I have not tested if there is course loaded on other fields, if it sits a waits.



[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7938776/log.txt)

**Comment by Resandise** [comment]
So, I had a course loaded on one other field, and it still would not start.  Also for SHIT and Giggles, I have one vehicle running a course, and attempt to generate and start another vehicle on a different field, and it just sits there.  So we are unable to run multiple vehicles, even on different fields, unless we are doing multi tool on the same field with 7.0.0.22

**Comment by syk24** [comment]
I have the same issue. I was able to get it to work, but I have to clear the current courses on all of my other machines, and can only run one job at a time.

**Comment by cmorse** [comment]
I'm also having this issue. As a workaround I added a `false and` to the beginning of this if statement: https://github.com/Courseplay/Courseplay_FS22/blob/main/scripts/ai/AIDriveStrategyFieldWorkCourse.lua#L749

**Comment by Natsu83** [comment]
Habe das selbe Problem. Allerdings erst seit 2.0.0.22, in der 2.0.0.21 funktioniert es bei mir noch einwandfrei. 

Frisch generierter Kurs für ein Drescher funktioniert nicht. Aber wenn ich ein kurs für einen Drescherverbund erstelle, so fangen beide an, das Feld abzudreschen. Scheint so, als wäre der Fehler in diesem zusammenhang zu suchen. Denke mal, dass der Drescher beim Singlekurs auf einen zweiten Drescher wartet, den es aber im Singlekurs nicht gibt.

**Comment by ct177mak** [comment]
Mein Sammelwagen für Stroh macht den gleichen Stress ,als Singelkurs kommt er nicht aus die Pötte ,nehm ich einen zweites Gespann mit dazu werkelt zumindest ein Gespann los, das andere Gespann brüllt nur im Stand mit 0Km loool .alles Vanilla .

**Comment by rohne83** [comment]
Seems it happens when more than one driver has a temporary course. I can easily engage several drivers on different fields as long as they use saved courses. As soon as I have two drivers with a temporary course (no matter on which field), those temp course drivers will stop their work.

**Comment by Tensuko** [comment]
Thats what my guess already is...
"temporary course" <- same name as all other "temporary course"
We will solve that, but give us some time and this will come as a hotfix.

**Comment by Tensuko** [comment]
7.0.0.23 should fix that.

**Comment by marcelmmx** [comment]
For me multiple tools are not working on one field - two harvesters - they start moving at first, but the second one stops after a few hundred meters and refuses to move again. When CP on the second one is disabled, the first one stops too. When I enable CP on the second one the first one starts moving, but the second one just sits there doing nothing. Tried to manually bring the second one closer or further, reload the course, change distance settings - nothing helps.

**Comment by mfehr94** [comment]
> For me multiple tools are not working on one field - two harvesters (all equipment is standard game stuff - no mods) - they start moving at first, but the second one stops after a few hundred meters and refuses to move again. When CP on the second one is disabled, the first one stops too. When I enable CP on the second one the first one starts moving, but the second one just sits there doing nothing. Tried to manually bring the second one closer or further, reload the course, change distance settings - nothing helps. I also noticed the second harvester is moving slower and the speed varies from 4 to 8 km/h, despite the first one being far away.

Would be nice if you could provide more info:

- did you use 7.0.0.23
- witch map
- witch harvesters
- log file?

**Comment by marcelmmx** [comment]
Hope this helps. If you have more questions, feel free to ask.

Would be nice if you could provide more info:

did you use 7.0.0.23 
Yes, I did.

witch map
I am playing Angeliter land (field 9), but the behaviour was the same on Shellbrook map (huge irregular field)

witch harvesters
2x Claas Trion 750 with Convio Flex 1080 headers.

log file?
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7943654/log.txt)

**Comment by Dmitriy-30** [comment]
Сделайте старый Mini hud как был в 19 ферме
