### ISSUE TITLE
[Feature] Clear course from Hud

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#699]
**What is the problem this feature/enhancement solves?**
Ability to clear current course from the HUD, elimantes having to go in to Course manager to clear the current course

**Describe the solution you'd like**
A way to clear the course from the HUD

**Describe alternatives you've considered**
A hotkey

**Comment by Tensuko** [comment]
Where and how could you imagine a clear current course?
We do NOT want to expand the HUD any further, this sice is the maximum that we wanted to use.

**Comment by Resandise** [comment]
FS 19 had a circle with a X in it that cleared the course, if I remember right.  It could be added right next to the "Play" button that starts the helper.

**Comment by Tensuko** [comment]
That could work.

**Comment by skjatala** [comment]
Also Mouse's Right bouton Conflict with AutoDrive's Mouse Right bouton.

**Comment by Resandise** [comment]
> Also Mouse's Right bouton Conflict with AutoDrive's Mouse Right bouton.

When I am adjusting AD, I turn of the "Open Hud with mouse" setting in CP, then turn it back on when I'm done, but yes, if you are trying to move Waypoints in AD with that setting on, it interferes.  It had a similar issue in FS19 with CP and AD, but you were able to move a WP, then have to reactive the mouse cursor after each move, or turn of the HUD on mouse click in CP.  I'm not sure if there is any way to fix this issue, seeing how they are two independent Mods.

**Comment by Tensuko** [comment]
> Also Mouse's Right bouton Conflict with AutoDrive's Mouse Right bouton.

Thanks for mixing problems in issues again...

Aynway, that will be fixed in next release.

About clear course from HUD, that will be delayed for now. Not sure if we will implement it.

**Comment by schwiti6190** [comment]
Same feature request as #791.
