### ISSUE TITLE
Bitte bringt das HUD zurück

### ISSUE THREAD

**Issue by eric4072** [Courseplay/Courseplay_FS22#70]
Hallo Leute, erstmal großen Dank für eure Arbeit 👍

Die Idee, alles in das Helfermenü zu integrieren, ist super, jedoch vermisse ich das CP-HUD beim spielen.

Ich kenne eure Roadmap nicht, jedoch kann ich euch als langjähriger LS-Spieler sagen, dass ich das steuern von CP über das Helfermenü eher als umständlich empfinde.

Ich wünsche euch frohe Weihnachten und in diesem Sinne auch gleich ein gutes neues Jahr

LG
Eric

**Comment by mulei2507** [comment]
Eric du könntest doch die Feldarbeit selbst erledigen. Ja es ist anders als zuvor. Und bevor ich mir ein HUD wünsche nehme ich das es auf den Servern auch geht. Gebt doch den Modern mal Zeit oder macht es besser.

**Comment by eric4072** [comment]
Was soll deine Antwort? die tut absolut nichts zur Sache! Ihr wünscht Euch Antworten von den Usern und dann bekommt man so eine Antwort drauf...

**Comment by mulei2507** [comment]
Das ist auch nur eine Antwort von einen User. Jeder möchte wohl sein Ziel schnell haben aber die können sich nicht zehnteilen. ist ja jetzt auf Wunschliste gesetzt. Schöne Festtage noch

**Comment by Keppchen** [comment]
> Was soll deine Antwort? die tut absolut nichts zur Sache! Ihr wünscht Euch Antworten von den Usern und dann bekommt man so eine Antwort drauf...
> 
> Ich habe weder wen angegriffen noch beleidigt...

Soweit ich weiß gehört @mulei2507 nicht zum Entwicklerteam. Seine Reaktion auf deine Kritik/Wunsch solltest du nicht zu wichtig nehmen.

Deine Formulierung ist vollkommen okay und die Bitte/Idee (wie auch immer man das nennen mag) ist vollkommen legitim.

**Comment by Tensuko** [comment]
CP in das Helfermenü zu integrieren war relativ einfach. Jedenfals einfacher und schneller als ein neues Hud zu bauen.
Das alte Hud wird es auf keinen Fall geben, aber da es ein paar Anfragen gab, werden wir uns etwas überlegen. Das braucht aber Zeit. Bis dahin bin ich der Meinung, man kann seine Feldarbeiter relativ leicht zur Feldarbeit schocken, ohne viel Aufwand. Es ist nur anders und Ungewöhnlich und das sage ich nach über 4000 Stunden LS 19 mit CP :)

**Comment by Keppchen** [comment]
Das stimmt. Ich fand es auch recht einfach da rein zu finden. Gute Arbeit

**Comment by eric4072** [comment]
Tja, Umstellung und ich, zwei Sachen die nicht wirklich zusammenpassen 🤣

die Routengenerierung im Helfermenü find ich ja cool 👍 jedoch wär ein kleines "Remotefenster" mit Start + die Art zu starten (erster oder naher Punkt), Pause, sofort abfahren und ev. das Ändern der Wendemöglichkeit cool, damit man nicht immer in das Menü muss.

Mit 4000std kann ich nicht dienen, jedoch 1600 im SP sind auch nicht so wenig 🤣

lg
Eric

**Comment by SuperSeba** [comment]
Ich bin da durchaus bei eric4072. In der Version 7 ist die Bedienerfreundlichkeit doch sehr zu kurz gekommen. Ich könnte mir vorstellen das auf lange Sicht ein Release auf Konsole geplant ist und daher diese "umständliche" Bedienung gewählt wurde. Für PC-Spieler die die Möglichkeit der Mausbedienung haben ist das ganze natürlich nicht so toll. Wie oben schon geschrieben vermisse auch ich das Menü aus der Version 6 bzw. AD.

**Comment by Beedog743** [comment]
I deffinately dont think there is a release for console on this. This mod depends on scripts which consoles dont get access too because of microsoft and sony not allowing scripts etc

**Comment by Tensuko** [comment]
Controller yes, console is not in our hands.
Just try it out and dont focus to much 'but it was different in the last version' basic is the same, you just dont see your vehicle while change stuff and I have to ask you: What do you change while you have to watch your vehicle ? So far I can only imagine offset and work width.

**Comment by wariacik33** [comment]
I hope that the old version of CP-HUD will come back over time because the current one is not comfortable.  In the older version, I was able to drive the tractor and position the courseplay at the same time.  Now you have to enter the ESC menu and just set something and additionally everything is obscured by the menu.  I sincerely hope that it will happen because now the modification is cumbersome to use.

**Comment by Keppchen** [comment]
Die ursprüngliche Anfrage war legitim. 

Dann hat @Tensuko erklärt, dass es für den Start so einfacher war und dass man über Zeit schaut, ob nochmal ein HUD gebaut wird.

Die Nachrichten die danach jetzt hier noch gepostet wurden finde ich recht undankbar. 
Nach der Erklärung des Entwicklers zu schreiben "Ja aber HUD ist besser" ist schon bisschen frech.

Meine Meinung

**Comment by Tensuko** [comment]
New HUD: Maybe
Old HUD: Never.

Give us time...
In the meantime, try it out...

**Comment by Playlord75** [comment]
Also mir persönlich gefällt die neue Steuerung über das LS22 Helfer Menü da man von 1 position aus alle Kurse steuern kann man kann in einem fend 1050 gan oben auf der map sitzen und sagen das der Lexion auf feld X ganz unten auf der map denn kurz generiren soll und starten soll ohne da man erst in das fahrzeug wechseln muss dann wieder denn job aufrufen muss und dann erst alles wieder generieren lassen muss 
über was ich mich freuen würde wenn der Silo Modus überlade wagen Modus etc. wiederkommt und man kurse aufzeichen muss das es dafür ein zusätzliches Hud kommt aber so wie es derzeit funtioniertgefällt es mir eindeutig besser

**Comment by XPiRiJenZ** [comment]
Es wird ja niemand dazu gezwungen CP in der jetzigen Form zu nutzen...

Mensch Leute, seid doch froh, dass wir innerhalb von 4 Wochen eine erste funktionale Version vom Team erhalten haben.
Meckern ist immer leicht, aber habt doch einfach ein wenig Geduld!

**Comment by Tensuko** [comment]
@XPiRiJenZ Schön wieder etwas von dir zu hören :)
Und ich danke dir für deine Übersetzung meines Videos, da spare ich mir die Arbeit :)

**Comment by XPiRiJenZ** [comment]
@Tensuko Danke und gerne ;) Ist zwar stark zusammen gefasst, aber prinzipiell sind alle Infos enthalten.
99,9 % der Kommentare sind Danksagungen an euch und eure Leistung, CP in kürzester Zeit anbieten zu können.

Die lange Abstinenz ist der Familie "geschuldet". Man setzt eben andere Prioritäten...aber was sich in der Zeit getan hat, ist m. M. n. nicht tragbar und es braucht einfach wieder qualitative Tutorials :D ok, Spaß beiseite... man tut eben, was man kann :) 
Noch ein frohes Fest euch allen und euren Lieben. 
Wir bleiben auf alle Fälle in Verbindung! :)

**Comment by rohne83** [comment]
> Es ist nur anders und Ungewöhnlich und das sage ich nach über 4000 Stunden LS 19 mit CP :)

Ich hatte bei meinem Studium auch mal das Fach Human Computer Interaction, und auch wenn das Thema da in einem Semester nur angeschnitten werden konnte, hat man da schon recht drastisch vor Augen geführt bekommen wie krass die Wahrnehmung von Nutzerfreundlichkeit zwischen Projektinvolvierten und Endbenutzern differieren kann. Das ist jetzt keine Kritik an euch, das Thema geht auch bei vielen professionellen Softwareherstellern unter, man schaue sich nur Windows an oder eben jetzt Giants mit dem nicht sonderlich einfach zu bedienenden ESC-Menü im LS in dem man mehr scrollt als alles andere ;)
Klar, der Fokus sollte erstmal auf der Funktionalität liegen. Für Leute die Hirschfeld-mäßig ein Logistikunternehmen aufbauen und die Feldarbeit nur nach dem Prinzip fire&forget automatisieren, reicht sicherlich auch die Bedienung über das ESC-Menü, und laut deinem Video wird da von euch auch noch einige zusätzliche geile Funktionalität eingebaut werden. Generell denke ich dass zumindest der Kursgenerator und Kursmanager, sowie die erweiterten Einstellungen problemlos ausschließlich im ESC-Menü verbleiben können.

Aber für Leute (zu denen gehöre auch ich), die sich das Treiben auf dem Feld dann genau anschauen, und dabei auch dann öfter mal "Babysitting" betreiben ist das ESC-Menü dann in vielen Situationen doch recht unkomfortabel. Also grade für die Einstellungen die man für dieses Babysitting oftmals braucht ist ein HUD sehr wünschenswert, egal ob es so aussieht wie das alte oder ein komplett neues wird. Ich denke da zB an die Offsets und eventuell Geschwindigkeiten, die Auswahl an welchem Punkt wieder gestartet werden soll (grade in den Überlappungsbereichen der Vorgewende muss man da sehr aufpassen), Teile der Drescher-Steuerung, die Fahrzeugverbandseinstellungen (vA beim Arbeiten mit Beeten musste ich da im 19er öfter mal die Werte anpassen um den Konvoi nicht auseinanderreißen zu lassen), und Schaufelpositionen. Und wenn irgendwann Mode 2/3 in welcher Form auch immer wiederkommen sollten, die entsprechenden Füllstands-Prozentwerte, Abfahrer-Prioritäten sowie die Buttons um den Abfahrer außerplanmäßig zu rufen oder wegzuschicken.
Im HUD kann man dann auch gleich wieder solche nicht ganz unwichtigen Informationen anzeigen, wie an welchem Wegpunkt man sich befindet, der geschätzte Abstand zum vorausfahrenden Fahrzeug des Verbands, oder die verbleibende Netto-Arbeitszeit. Und nicht zu unterschätzen die Möglichkeit den Feldkurs als vergrößerte PDA-Ansicht einzublenden (im alten HUD wenn man glaub zweimal auf das Auge geklickt hat) wenn man bei komplizierteren Kursen (vA Beete oder kreisförmig) die richtige Bahn zum Neustarten des Helfers nach Eingriff bei der Feldreihenwende finden muss.

**Comment by pvaiko** [comment]
@rohne83 du hast volkommen recht. Wir wollten so früh wie möglich was rausbringen, um genau dieses Feedback und Ideen zu sammeln. Was wir jetzt haben ist was man minimum viable product nennt, in welche Richtung es sich wieterentwickelt werden wir sehen.

**Comment by EiksYt** [comment]
> New HUD: Maybe Old HUD: Never.
> 
> Give us time... In the meantime, try it out...



> Es wird ja niemand dazu gezwungen CP in der jetzigen Form zu nutzen...
> 
> Mensch Leute, seid doch froh, dass wir innerhalb von 4 Wochen eine erste funktionale Version vom Team erhalten haben. Meckern ist immer leicht, aber habt doch einfach ein wenig Geduld!

So ist es !!!! Ich finde beide Varianten gut...  Das erstellen der Kurse über ESC-Menü ist prima . Was ich allerdings vermisse ist dieses "Abfahrer einstellen" am nächsten Wegpunkt. Also ein MiniHud für Shortcuts wäre eine gute Lösung ! 

Aber erstmal Vielen DANK für eure Arbeit !!!! Großartige Leistung !!

**Comment by Cassy-Blair** [comment]
> CP in das Helfermenü zu integrieren war relativ einfach. Jedenfals einfacher und schneller als ein neues Hud zu bauen. Das alte Hud wird es auf keinen Fall geben, aber da es ein paar Anfragen gab, werden wir uns etwas überlegen. Das braucht aber Zeit. Bis dahin bin ich der Meinung, man kann seine Feldarbeiter relativ leicht zur Feldarbeit schicken, ohne viel Aufwand. Es ist nur anders und Ungewöhnlich und das sage ich nach über 4000 Stunden LS 19 mit CP :)

Ok also wenn ich das richtig verstehe, 

1. CP ins Helfermenp zu integrieren war einfach
2. ein neues HUD braucht seine Zeit (ist verständlich)

Aber wäre es nicht einfacher, das alte HUD, welches jeder nun schon gewöhnt ist und sich zurecht findet, einfach für den LS22 zu konvertieren, als jetzt wieder was ganz neues zu entwerfen, wo sich dann wieder jeder erst zurechtfinden muß?

**Comment by Keppchen** [comment]
> > CP in das Helfermenü zu integrieren war relativ einfach. Jedenfals einfacher und schneller als ein neues Hud zu bauen. Das alte Hud wird es auf keinen Fall geben, aber da es ein paar Anfragen gab, werden wir uns etwas überlegen. Das braucht aber Zeit. Bis dahin bin ich der Meinung, man kann seine Feldarbeiter relativ leicht zur Feldarbeit schicken, ohne viel Aufwand. Es ist nur anders und Ungewöhnlich und das sage ich nach über 4000 Stunden LS 19 mit CP :)
> 
> Ok also wenn ich das richtig verstehe, 
> 
> 1. CP ins Helfermenp zu integrieren war einfach
> 2. ein neues HUD braucht seine Zeit (ist verständlich)
> 
> Aber wäre es nicht einfacher, das alte HUD, welches jeder nun schon gewöhnt ist und sich zurecht findet, einfach für den LS22 zu konvertieren, als jetzt wieder was ganz neues zu entwerfen, wo sich dann wieder jeder erst zurechtfinden muß? Außerdem passte das alte HUD sehr gut zum AD-HUD

Vielleicht kommt ja ein gemeinsames HUD mit AD oder ein HUD mit Baby Alpakas. Gebt doch mal Neuem eine Chance. :D

**Comment by iljarogoff** [comment]
> Aber wäre es nicht einfacher, das alte HUD, welches jeder nun schon gewöhnt ist und sich zurecht findet, einfach für den LS22 zu konvertieren, als jetzt wieder was ganz neues zu entwerfen, wo sich dann wieder jeder erst zurechtfinden muß?
Ob sich das so einfach mal konvertieren lässt, bezweifle ich. Es ist erstmal gut, so schnell eine lauffähige Version von CP zu haben. Aber auch ich würde mir ein HUD wünschen, muss ja nicht so ein klobiges (aber geniales) Teil sein wie im LS19, vielleicht eher eine Buttonleiste, ähnlich wie bei AD, und wenn man einen Button anklickt, geht eben ein entsprechendes Einstellungs/Funktionsmenü auf. Dann wäre es dezenter und man hätte dennoch jederzeit Zugriff und hat das Spiel im Blick (das hat man im AIHelfer Menü leider nicht). Aber das dürfte schon einigermaßen aufwändig zu programmieren sein...

**Comment by Tensuko** [comment]
Das alte Hud passt nicht in unser Konzept und es ist viel zu Wartungsaufwändig. Der Code auch Uralt, desshalb nein, es wird nicht konvertiert. Es wäre warscheinlich mehr Aufwand, als ein neues zu erstellen

**Comment by EiksYt** [comment]
> Das alte Hud passt nicht in unser Konzept und es ist viel zu Wartungsaufwändig. Der Code auch Uralt, desshalb nein, es wird nicht konvertiert. Es wäre warscheinlich mehr Aufwand, als ein neues zu erstellen

Find ich gut ! Und wir werden sehen was kommt !!

**Comment by SilverWheelz** [comment]
Props to you guys for being able to release CP quickly. Not only that, y'all stay active on Github, reponding to the issues reported even during the holiday season. Wishin' y'all a Merry Christmas and a prosperous New Year!

> The old Hud doesn't fit into our concept and it's way too maintenance-intensive. The code is also ancient, so no, it is not converted. It would probably be more effort than creating a new one

I love CP's integration into the helper menu but I think having CP's settings on different pages is counterintuitive and may become worse as you reintroduce more features. Nonetheless, I can't wait to see what you'll bring us. Maybe instead of only having the course generator, you can have something like Wopster's Guidance Steering menu pop up where you can access the course generator as well as all the settings so you can make changes without leaving the helper menu. 
![Screenshot (478)](https://user-images.githubusercontent.com/94125770/147410615-4bde9fcf-8c72-4457-a06c-1b8b5d44a6ad.png)
Then, you can use that same menu as the HUD to make adjustments or control CP on the go, with clickable switches/toggles like the old HUD. I also miss being able to adjust values by scrolling, hopefully that feature will make a comeback.

**Comment by Tensuko** [comment]
Something like that we have in mind and it is W.I.P. But it needs time.

**Comment by regs1980** [comment]
Gespannt bin ich schon wie die Umsetzung für das Stecken erstellen sein soll, bei einem ÜLW oder Radlader per Overlay Menü.
Zum Thema altem HUD ihr hättet in LS19 einiges raus werfen können, CP hätte da nicht alles machen müssen, Straße AD Feldarbeit CP nur zusammen arbeiten, es muss nicht ein Tool alles können.
AD HUD gibt es ja auch und man kann es ähnlich aussehen lassen wie das F1 HUD in LS22

<img width="1248" alt="2021-12-26 18_36_38-Farming Simulator 22" src="https://user-images.githubusercontent.com/13314443/147457280-c674480f-bb8b-4517-8ebb-8805942ac86a.png">

Ihr müsst auch nicht alles selber machen.

**Comment by rohne83** [comment]
Was hätten sie denn rausschmeißen sollen? Eigentlich nur die Modes 1 und 5, wobei 5 sowieso schlicht die Basis für fast alle anderen Modes dargestellt hat. Jetzt im LS22 könnte vielleicht auch Mode 8 verzichtbar werden, falls das mit dem Saatgut/Dünger nachholen auch an einem AD-ULW zuverlässig hinbekommen werden kann. Bei Mode 2 bin ich nicht so zuversichtlich, dass AD das jemals so reibungslos hinbekommen wird wie CP. Ist hier jetzt aber eh nicht Thema.
Jedenfalls kann man aus den Kommentaren des Dev-Teams aber rauslesen, dass da beim Thema HUD durchaus irgendwann nochmal was kommen könnte. Wie genau das dann aussieht, werden wir dann ja sehen wenn es soweit ist (bezüglich Größe wäre etwas kleines a la AD-Hud sicherlich praktischer als das ziemlich große GuidanceSteering-HUD). Spannender dürfte dann eher die Frage sein, welche Einstellmöglichkeiten da den Weg in ein neues HUD finden.

**Comment by regs1980** [comment]
> Was hätten sie denn rausschmeißen sollen?

Alles was mit der Straße in Verbindung steht, die Übergabe an AD war doch das beste was man machen konnte.

**Comment by XPiRiJenZ** [comment]
> Alles was mit der Straße in Verbindung steht, die Übergabe an AD war doch das beste was man machen konnte.

Man kann Leuten aber nicht einfach einen Mod (in diesem Falle AD) einfach "aufzwingen". Natürlich war die Verzahnung mit AD sehr edel und ein Gewinn für beide Mods, aber einfach zu sagen "So, wer jetzt Transporte und Fahren von A nach B machen will, der muss jetzt zukünftig AD nutzen" funktioniert nicht, wenn du ein bestehendes System hast.

Jetzt im 22er sieht die Sache anders aus! Hier kann man die Leute von vornherein an AD ran führen, wenn die Implementierung von CP im ESC-Menü so bleibt und anraten, sich mit dem Mod und seinem Potential auseinander zu setzen.

**Comment by Tensuko** [comment]
@XPiRiJenZ 
Wir wollten diesen Neustart aus dem Grund und auch die Kommunikation und Verbindung mit AD soll neu und besser aufgebaut werden.
Gezwungen wird hier niemand, aber es gibt eben auch Entsheidungen bei den Moddern (in dem Fall CP und AD) sich eher zu ergänzen, als Konkurrenz zu sein.

**Comment by XPiRiJenZ** [comment]
@Tensuko ich wollte ja nur Bezug auf das nehmen, was @regs1980 geschrieben hatte.
Ich bin ja offen für die engere Verbindung mit AD und kann euren Hintergrund verstehen, dass ihr die verfügbaren Kapazitäten dann anderweitig nutzen könnt, wollt und nicht alles doppelt entwickelt wird :)

**Comment by eric4072** [comment]
Hallo Leute!

Habe gerade das die 7.0.0.8 geladen, test mit neuen MiniGUI: cool..

Dann hab ich mir gedacht: ich hätte da eigentlich an ganz was anderes gedacht, wie ich MiniGUI gelesen habe :-)

Wieder ist meine Meinung natürlich nicht als Kritik zu sehen. Nutze nur diese Möglichkeit um direkt mit Ideen zum "Hersteller" zu gehen. Ich zocke den LS fast täglich, durch CP und AD ist das ganze ein "läuft den ganzen Tag so nebenbei"-Spiel geworden, was ich äußerst positiv meine ;-)

hier meine Meinung und Vorstellung zu dem Grund, warum ich diesen Beitrag überhaupt erst geöffnet habe.

Ich spiele den LS fast nur als "Manager", für diese Spielart kann ich mir eines gut vorstellen:

 eine kleine Iconbar, frei zum verschieben, mit: 

Icons wie: CP ON/OFF/ev. Pause (ev. bei activ grün), ein kleines Dropdown-menü für die Kursauswahl, den CP-Modus 1-9, ein Icon für Kurspunkte anzeigen und ein Icon "Direkt ins Helfermenü".

Die Kursgenerierung per Helfermenü finde ich richtig gut ;-)

LG
Eric

**Comment by throsten** [comment]
Hallo, bin neu hier. 

Genau wie mein Vorredner handhabe ich es auch gerne. Was mir aktuell (7.0.0.9) am meisten fehlt: Man erkennt nur im ESC Menü unter Job Starten, ob CP oder der Giants Helfer mit H aktiviert werden.  Wenn man nun durch die Geräte tabbt und gelegentlich zwischen CP und Helfer wechselt, ist das verwirrend. Ich würde daher sowas wie ein Auswahlfeld oder eine Anzeige  "verwendeter Helfer" im neuen HUD begrüßen.

Nebenbei: Die Entscheidung das alte HUD in Rente zu schicken, vieles in das ESC Menü zu stecken und mit einem schlanken, neuen HUD zu ergänzen finde ich gut!

**Comment by haamic** [comment]
@throsten 
Ich nutze den Mod vehicleinspector. Da werden mir in einer Liste meine Fahrzeuge angezeigt, auch welche mit cp Feldarbeit beschäftigt sind. Da sehe ich sofort, wenn ich "H" drücke, mit welchen Helfer das Fahrzeug startet. Vielleicht hilfts dir ja.

**Comment by pvaiko** [comment]
HUD ist jetzt zurück.
