### ISSUE TITLE
[BUG_SP] Work Width not reseting (feet Problem)

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#702]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Attach a implement, adjust the work width on the Hud, then click the text to reset

**Actual behavior**
It does nothing

**Expected behavior**
The work width resets. 

**Screenshots**
Before adjustment

![fsScreen_2022_01_26_01_08_57](https://user-images.githubusercontent.com/96673100/151118682-986e8e7d-1d7f-4709-9eaf-4a35fd95ce8d.png)

After adjustment and attempt to reset.

![fsScreen_2022_01_26_01_09_28](https://user-images.githubusercontent.com/96673100/151118690-f6fec3d4-a58f-4e1b-bd08-74e4d00910a3.png)

**Courseplay version**
Version used: 7.0.0.22

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7939573/log.txt)

**Map**
Elegrant

**Vehicles/ implements involved**
All

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Did that tool get a workwidth at all ?
If we can't detect the workwidth of that tool, it could be a problem of that tool.
For that I can add it into out vehicleconfiguration.

But that means it is not a general auto work width bug.

**Comment by Tensuko** [comment]
Forget what I said, it might be the feet input.
But those press we can't auto adjust due to a mistake in the mod itself.

**Comment by Resandise** [comment]
It shows waiting on user, but I am unsure what you are waiting for.

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.24
