### ISSUE TITLE
[BUG_SP] Click to Type Work Width (problem with feet input)

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#703]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Game set to "Miles", click to set work width, input the width in feet.

**Actual behavior**
CP thinks your inputting the text as meters and converts it to feet.

**Expected behavior**
When typing work width while game is set to "Miles" and CP is displaying work width as Feet, that you should be inputting the width as feet, not meters.

**Screenshots**
Input of 10.3 meter implement as feet.

![fsScreen_2022_01_26_01_14_01](https://user-images.githubusercontent.com/96673100/151119525-667b30c7-f46a-4c25-8824-32eba9d71199.png)

What CP shows at work width after inputting the width as Feet.

![fsScreen_2022_01_26_01_14_04](https://user-images.githubusercontent.com/96673100/151119526-a50c2f5c-1384-4ffa-87a2-c20f62f1c3d5.png)

Input 10.3

![fsScreen_2022_01_26_01_14_15](https://user-images.githubusercontent.com/96673100/151119527-812c93b5-3f02-43b0-b85d-abf59943a361.png)

What CP shows after inputting width as meters.

![fsScreen_2022_01_26_01_14_17](https://user-images.githubusercontent.com/96673100/151119530-11c76d57-5d04-4e90-b07c-4fce60b422be.png)

**Courseplay version**
Version used: 7.0.0.22

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7939622/log.txt)

**Map**
Elegrant

**Vehicles/ implements involved**
All

**Relevant script mods**
AD

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.24
