### ISSUE TITLE
[BUG_SP]Multi Tool Object Blocked

### ISSUE THREAD

**Issue by Skyden72** [Courseplay/Courseplay_FS22#704]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

Run Two harvesters and see what happens. When the one has to wait for the other one because it's offloading it stops and says object blocking Harvester

**Actual behavior**
hen the one has to wait for the other one because it's offloading it stops and says object blocking Harvester

**Expected behavior**
Shoud wait without stopping and first harvester should go on without waiting for rest of the harvesters
**Screenshots**

**Courseplay version**
Version used: 1.0.0.22

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Shellbrook, Saskatchewan

**Vehicles/ implements involved**
Wich vehicle or implement? JD X9 1100, 15m JD header
Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive

**Comment by Tensuko** [comment]
Is the blocked combine dismissed or will he continue drive when 'unblocked' ?

**Comment by Skyden72** [comment]
Dismissed

**Comment by TheMutabor** [comment]
Same issue for me but not with a Combine, i have two Fendt 1167 MT with a Swifter SM 18000 cultivator and seems like sometimes the second driver needs to long to switch and align to the next row and the first driver get deactivated then with the same reason blocked by a Object when he have to wait to long for the other driver.

But could fix that for now by deactivating the turn in field option, it seems to turn faster when he turn outside of the field

**Comment by TheMutabor** [comment]
Seems like the Driver get dismissed when he is idling to long and waiting for the other.

**Comment by Tensuko** [comment]
Okay thanks for the feedback.
That was never the case in our tests.

**Comment by Skyden72** [comment]
The same course loaded and set to two (in Multitool)

**Comment by TheMutabor** [comment]
Or corse it's the same course otherwise they would not wait for each other, i uploaded a video showing this issue: https://youtu.be/DgdnTP6TmAc

**Comment by Skyden72** [comment]
Exactly, mine is just with two combines. When ether has to wait for the other to offload it dismisses the driver and stop.

**Comment by Tensuko** [comment]
yea we know, give us time pls.

**Comment by elkatronas** [comment]
I was about to write a issue about it, but here I am. Same here with modded combines.

**Comment by Tensuko** [comment]
We did overwrite the timeout in 7.0.0.24 so the driver will stay active.
More convoy improovements will come step by step.
