### ISSUE TITLE
[Question] Odd course behavior 

### ISSUE THREAD

**Issue by criss20ster** [Courseplay/Courseplay_FS22#707]
And I have a question why this course with this tractor and plow behaves as if it were "dancing" I have such CP settings 

https://www.youtube.com/watch?v=Fo-kOWG7KFg

in the 2nd film, at the end of the field, it goes to the end of the field for about 3 minutes, it turns well ok, but at the other end of the field it turns 2 times and it blocks. Why is this happening? What do I have wrongly set in the course if it concerns the settings 

https://www.youtube.com/watch?v=73mWS3cJiwg

**Comment by Tensuko** [comment]
You can add pics directly on github and not any website that gives me a warning.
And I don't even know what version you use...
Try the newest or better wait untill the hotfix. Like that I can't help you in any way.

**Comment by criss20ster** [comment]
I have used 7.0.0.22 ok I didn't know with these photos, I rarely use the github
