### ISSUE TITLE
[BUG_SP] Tractor not moving when activating worker

### ISSUE THREAD

**Issue by AdrianM20** [Courseplay/Courseplay_FS22#708]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
For this situation I had a Claas medium tractor with Hardi mega 1200 Sprayer.
I created the course for field 46 and 47 on Haut-Beyleron and hit start. 
The tractor drives to the beginning of the course, unfolds and starts tool (spays herbicide) and just stays there, consuming herbicide.

**Expected behavior**
Tractor should move around the course.

**Screenshots**

**Courseplay version**
Version used: 7.0.0.22

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Haut-Beyleron

**Vehicles/ implements involved**
Hardi mega 1200L
Claas Axio 870
Mod yes/no ?
No

**Relevant script mods**
VCA mod

**Comment by Tensuko** [comment]
Good Morning.
https://github.com/Courseplay/Courseplay_FS22/releases
#698
I know it was just few min ago so its okay :)

**Comment by Redster999** [comment]
Must be a record!
