### ISSUE TITLE
Kverneland Fastbale legt Ballen nicht ab[BUG_SP]

### ISSUE THREAD

**Issue by Tobias80** [Courseplay/Courseplay_FS22#709]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

Hi die FastBale funktioniert mit Version .23 nicht mehr

Map ist Haut Beyleron

Deutz TTV 8280 und Kverneland [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7942113/log.txt)

**Comment by Tensuko** [comment]
Template nicht richtig ausgefüllt, debug nicht eingeschaltet....

**Comment by Tobias80** [comment]
Muss ich schauen meld mich nochmal

**Comment by Tensuko** [comment]
Can't reproduce.
![fsScreen_2022_01_26_15_16_26](https://user-images.githubusercontent.com/27344744/151179253-b2cd3e41-508a-4c98-ad8b-274472faba3f.png)

**Comment by Tobias80** [comment]
Habs grad auch nochmal getestet und jetzt funktionierts -- keine Ahnung wieso vorher net

**Comment by Tensuko** [comment]
Kann passieren :) Wäre aber schon merkwürdig wenn es nicht mehr geht. Haben das lange nicht angefasst :)
