### ISSUE TITLE
Collection of some anomalies

### ISSUE THREAD

**Issue by Markus33-ITA** [Courseplay/Courseplay_FS22#71]
Hi. Merry Christmas. 
[https://i.imgur.com/cxLcHeZ.png](https://i.imgur.com/cxLcHeZ.png) [https://i.imgur.com/jw6i9BG.png](https://i.imgur.com/jw6i9BG.png)
In the first and second link the worker stops working with the wording blocked by an object.

[https://i.imgur.com/m7QySwz.png](https://i.imgur.com/m7QySwz.png) [https://i.imgur.com/c1jm9gB.png](https://i.imgur.com/c1jm9gB.png) [https://i.imgur.com/TLVe9bu.png](https://i.imgur.com/TLVe9bu.png)
I did 3 tests and in all 3 tests he jumped the first lap.

**Comment by Tensuko** [comment]
Pls do not post your logfile like that, is is unreadable...
Also you can upload pictures directly here.
The Comment box got a drag and drop function, as it is written under it.. or follow those steps:

Post the complete game log:

    You can find it in the following directory:
        Windows (7 and above):
        C:\Users\[YOUR USER NAME]\Documents\My Games\FarmingSimulator2019\log.txt
        Mac:
            Mac OS X Download/DVD/Steam-Version:
            /Users/[YOUR USER NAME]/Library/Application Support/FarmingSimulator2019/log.txt
            Mac OS X AppStore-Version (Mac OS X 10.7 and newer):
            /Users/<your username>/Library/Containers/com.focus-home.farmingsim2019/Data/Library/Application Support/FarmingSimulator2019/log.txt
    Upload the log:
    Go to Gist or Pastebin, and add your log content by either using copy and paste, or dragging the log.txt file into the text area (Gist only).
    Post the link to your log in the issue.
    You can also drag and drop the log.txt into the comment box.

**Comment by Markus33-ITA** [comment]
Forgive me Tensuko. I'm not that good on github yet. I had to create a new game. the one of the screenshots I added my mods and I wanted to recreate the previous situation.
the field is what it once was. the worker stops because he has found obstacles. 2 tests. the first time yes and the second no.
I have enabled full debugging and i hope you can tell me something about it. [https://pastebin.com/Uk9k7rzu](https://pastebin.com/Uk9k7rzu)

![fsScreen_2021_12_25_17_17_56](https://user-images.githubusercontent.com/96330304/147389629-69f76a9b-800b-40e1-bbd3-532d02e6604c.png)
![fsScreen_2021_12_25_17_18_58](https://user-images.githubusercontent.com/96330304/147389656-5f770836-54b9-4301-a279-d307cebbdb76.png)
![fsScreen_2021_12_25_17_19_26](https://user-images.githubusercontent.com/96330304/147389667-22da814d-2454-4721-a365-557b80cceb5a.png)
![fsScreen_2021_12_25_17_25_28](https://user-images.githubusercontent.com/96330304/147389681-bcac7fdd-a016-4ceb-ae3c-0378c6ce9e39.png)
![fsScreen_2021_12_25_17_34_56](https://user-images.githubusercontent.com/96330304/147389689-07ec2bda-3b79-4a93-b289-4b44a5e4fee5.png)

**Comment by Tensuko** [comment]
The Problem right now is, that you can start CP at the 1st Waypoint only with Start Job.
The H key will start it at the nearest.
When you want it to do all the Headland, drive it just a bit behind the start waypoint and then start it with H so it finds the first Headland as a starting point. Enhancement is already WIP.

**Comment by Tensuko** [comment]
I think some things are cleared, I try to add this into our upcoming FAQ.
