### ISSUE TITLE
[Info] Upgrading from 7.0.0.22 to .23 (.24 ?)

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#710]
Just an FYI, when I updated from .22 to .23, my game save that I ran .22 in, would not load past 85%.  I had to load the game without CP active, save and reload with CP active to get it to load fully.  My game saves that I did not use .22 with, loaded fine with .23.

**Comment by Tensuko** [comment]
Can be stucked settings. But thanks for Information.
Will put that as a sticky.

**Comment by KCHARRO** [comment]
Thaks for Info....

**Comment by sirbum69** [comment]
as a side note, i myself loaded a save used with .22 upgraded to .23 and did not have any issues.

**Comment by Tensuko** [comment]
Well, it is not said that you will have those issues.
That might depend on what have you done with the .22 ( I guess multi course was the issue).
So that is just in case when you have problems with upgrading from .22 to .23 :)

**Comment by KCHARRO** [comment]
Sorry for this one. Off-topic question so as not to create another thread.

Since 0.22 the MiniHud disappeared, the little one that was below the center of the screen, any idea what's going on?

**Comment by Resandise** [comment]
> Sorry for this one. Off-topic question so as not to create another thread.
> 
> Since 0.22 the MiniHud disappeared, the little one that was below the center of the screen, any idea what's going on?

Are you talking about the moveable one, or the one that comes up when you hit delete?

**Comment by KCHARRO** [comment]
Yes the little moveable... don´t show up...

**Comment by Tensuko** [comment]
Right mouse click should always work.
Next version both is working again, keybind and mouse click.
Will have more information in the changelog.

**Comment by KCHARRO** [comment]
ok, thanks...

**Comment by ConstructionGamer** [comment]
Thanks for info, thought I'd lost my save game.

**Comment by Dennis-02** [comment]
Have the same problem when upgrading from .23 to .24. But load without CP->save->reload with CP it works!

**Comment by schabil** [comment]
Ich habe ebenfalls das Problem, er lädt bis 60 Prozent und dann bleibt er stecken. Auch ein Laden/Speichern ohne CP hilft da leider nicht.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966771/log.txt)
