### ISSUE TITLE
[Question] ingame CP-editor

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/Courseplay_FS22#711]
Hallo Leute.
Habt ihr geplant, bzw ist es in CP7 überhaupt möglich, wieder den ingame courseplay editor zu integrieren?
Wäre derzeit ganz cool, um fehlerhafte kurse etwas einfacher ändern zu können.
Lg
Andress

**Comment by Tensuko** [comment]
Nein ist nicht geplant.
Kann man irgendwann mal drüber nachdenken.

**Comment by andreasthu** [comment]
Ach schade.
Fand den in cp6 sehr hilfreich.
Damit könnte man in cp7 ja schnell berechnungsfehler einfach selber korrigieren.
Z.b. eine scharfe Ecke aus einer runden machen.
Geht jetzt ja auch mit notepad und der kurs-xml, ist aber umständlich und kompliziert mit den koordinaten.
Danke fürs drüber nachdenken, irgendwann mal. 
Lg
Andreas
