### ISSUE TITLE
[Feature] Improved Hungarian translation

### ISSUE THREAD

**Issue by thenny23** [Courseplay/Courseplay_FS22#712]
I like to share my improved Hungarian translation.
Thank you.

[https://drive.google.com/file/d/1QmNkJ2DyTRYSKkJ_PwjaEhoqZpyYTyZ1/view?usp=sharing](url)

**Comment by Tensuko** [comment]
Can you pls create a pull request for this ? Thanks a lot for your contribution.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
