### ISSUE TITLE
[BUG_SP] Multitool Bug temp course

### ISSUE THREAD

**Issue by TheMutabor** [Courseplay/Courseplay_FS22#714]
**Steps to reproduce**
Take 2 Vehicles and create with both on different fields a new course withouth saving them (Temp course) and set in the Generator Settings Vehicles with same course to 1, then they are still connected to each other and will not start working because the system think they are in a Convey because both have Temp course even when only 1 vehicle is selected in the Generator.
See here: https://youtu.be/shsHqSzjC8k

**Actual behavior**
If two vehicles have a Temp course they will not Start doing it's work, they will wait for each other even when the course was generated with the flag that only 1 vehicle have the same course.

**Expected behavior**
It should be possible to create and let the Worker drive on 2 seperate temp courses, withouth having to save them.

**Courseplay version**
Version used: 7.0.0.23

**Comment by Tensuko** [comment]
Exactly this I tested and it wasn't a problem at all...

**Comment by Tensuko** [comment]
No complete Template and no logfile......

**Comment by Tensuko** [comment]
Is the other temp course for that lexion a multitool course ?

**Comment by TheMutabor** [comment]
No it is not, when i create a Multitool course i save them, how i should otherwise load the course in the other Vehicle. The lexion did have the same course generating settings with only 1 Vehicle with same course as the Vehicle shown in the Video, also you will find not more informations to this in the log, but here it is
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7944408/log.txt)

**Comment by Tensuko** [comment]
Available mod: (Hash: 982f0911dc251270c105a9aa2234af39) (Version: 7.0.0.22) FS22_Courseplay
Awesome....
Try the real 7.0.0.23 pls
https://github.com/Courseplay/Courseplay_FS22/releases
