### ISSUE TITLE
Wieso lassen sich im CP nur Kurse erstellen mit 2 Fahrer und mehr

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/Courseplay_FS22#715]
ich Habe da mal eine Frage,
ich benuze die Version von CP7.0.0.23 wiso kann ich nur Kuse ertellen die für Merre Fahrer Gedacht sind was muss ich da einstellen

**Comment by RudiBergfeld** [comment]
Ach so [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7944611/log.txt)

**Comment by RealNeo80** [comment]
ich hab das gestern festgestellt, probier mal was passiert wenn du das feld ganz nach oben scrollst da kannst du Fahrzeuge einstellen. Stell das mal auf 1 und lass nach oben gescrollt. Schau mal obs dann geht. ich hab die Vermutung das das Scrollfeld darunter noch aktiv ist, wenn du mit der Maus auf Kurs generieren klickst

**Comment by Tensuko** [comment]
Ja du musst die generator settings nach oben scrollen, sonst kann es passieren das du beim klick auf generieren das fahrzeug auf feld setting erwischst.

**Comment by Tensuko** [comment]
Ist natürlich ein bug, ich achte z.B. immer das das "generiere settings" aufleuchtet bevor ich klicke daher mir noch nie aufgefallen....

**Comment by Tensuko** [comment]
Fixed in 7.0.0.24
