### ISSUE TITLE
2 Fahrzeuge auf dem selben Kurs

### ISSUE THREAD

**Issue by loeschknecht** [Courseplay/Courseplay_FS22#723]
Mahlzeit, 
ich fahre mit Traktor 1 und Mähwerk auf einem Kurs. Sobald ich Traktor 2 mit Ladewagen auf den selben Kurs schicke bleibt Traktor 1 stehen. Lösche ich aus Traktor 2 den Kurs fährt Traktor 1 weiter. Die Einstellung 2 Traktoren auf dem Kurs fahren zu lassen bringt mich auch nicht weiter da die ja nebeneinander fahren. Was mache ich falsch? CP7.0.0.23

**Comment by Tensuko** [comment]
Das ist Convoy, das ist jetzt erst mal so, wir schauen wie wir das später noch anders lösen können.
Workarround: Speicher den Kurs unter einen anderen Namen ab.

BZW bist du dir sicher, dass du die .23 hast ?
Sollte an sich nur passieren wenn es ein Multikurs ist.
Logfile ?

**Comment by loeschknecht** [comment]
Ups, lt. moddesk .22 ok thx

**Comment by Tensuko** [comment]
Update auf .23 dann muss es eigtlich gehen.
