### ISSUE TITLE
Mini Hud

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/Courseplay_FS22#724]
Wie bekomme ich das Mini hud was bei einer älteren Version war wieder?? War sehr praktisch! LG

**Comment by Tensuko** [comment]
In den globalen Einstellungen das, glaub ich habe es gamepad freundliches hud genannt, aktivieren.
Das lässt sich dann aber nur über Tastenbelegung öffnen.

**Comment by Paul2510** [comment]
Ok das blaue erscheint dachte eher an das gelbe kleine was am unteren Bildschirmm in der mitte war?? LG
