### ISSUE TITLE
[BUG_SP] Dalbo Mega roll 2430 not raised during maneuvre

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#725]
EDIT : NOTHING TO DO
just discovered it's always low, you can't raise this implement

sorry >_<

CP 7.0.0.22

**Actual behavior**
during manoeuver, implement is not raised

**Expected behavior**
should be raised like other implement

**Screenshots**
https://drive.google.com/file/d/1Qydk6gpRR1ntOEg9GQHiFCDTOVb0pueL/view?usp=sharing

**Courseplay version**
Version used: 

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7949036/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Dalbo mega roll 2430
JD 7r

**Relevant script mods**
AD

**Comment by regs1980** [comment]
The device only has to be opened and closed

**Comment by Snigyman** [comment]
Hi, this is not a Bug with CP, this Roller is not raising after unfold.

**Comment by Tensuko** [comment]
Way to heavy to lift, that have to be like that. Before open Issue here, pls check the tool itself how it works.
