### ISSUE TITLE
[BUG_SP] Harvester stops too far from the trailer to selfunload

### ISSUE THREAD

**Issue by Mhuz** [Courseplay/Courseplay_FS22#727]
**Steps to reproduce**
Harvest a field with selfunload enabled. Doesn't occur always. 

**Actual behaviour**
Sometimes, when the harvester goes to the trailer to selfunload, stops too far from it and can't proceed with selfunloading. It doesn't occur in all fields (i.e it happened to me with field 41 and field 35). I don't think the problem is that trailer is outside field boundaries since it worked fine for field 38 and the trailer outside.

**Expected behaviour**
Reach the right distance from the trailer to start selfunloading.

**Screenshots**
![Farming Simulator 22 27_01_2022 11_16_50](https://user-images.githubusercontent.com/22480189/151341573-7e9cd56b-2001-4fe8-bbad-30dde367633f.png)

**Courseplay version**
Version used: 7.0.0.23

**Log**
[log](https://gist.github.com/Mhuz/5f080267333857f91f3b6dcc4256e27d)

**Map**
Haut-Beyleron.

**Vehicles/ implements involved**
John Deere T560 (Harvester)
John Deere 625x (Header)
Fliegl ASW 271 (Trailer)

**Relevant script mods**
Autodrive (not used during the issue).

**Comment by Tensuko** [comment]
Should be better now in 7.0.0.24
