### ISSUE TITLE
[Question] How to record manually a fieldborder.

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/Courseplay_FS22#729]
First of all: thanks for the great work again. I like the integration in FS22. Great Job!

In FS19 i could make with CP random field borders by driving manually around the field en record it with CP. After that i could made a course in it.
Until now i did not see how i can do this in the new CP.

Greetz Agro.

**Comment by Tensuko** [comment]
Not yet implemnted, working on it already.
What you can do is plow your border and then generate a field course without island bypass.

**Comment by AgroWillem** [comment]
Ok. Thanks!
