### ISSUE TITLE
[BUG_SP] 3 tools, same course, but on driver goes wrong

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#731]
**Steps to reproduce**
have a course with 3 driver
when going to the end of a line of work, the driver on the right goes off
(only the one on the right, and only on one way of the work, on other way it's ok)

Drivers on center and left are ok, but the one on the right goes wrong (tried changing the order, putting the fasttrack to the right, same)

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/1Rl8F0xsFZxtDUqV_bW5q2-2dUMstKTB8/view?usp=sharing)

**Courseplay version**
Version used: 7.0.0.23

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7951679/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
2 Fendt 1050 and a Fastrack with Dalbo maxiroll 630

**Relevant script mods**
AD

**Comment by pvaiko** [comment]
`2022-01-27 16:23 Recursion limit of 600 reached for headland generation`

**Comment by pvaiko** [comment]
I need that course

**Comment by Chico0008** [comment]
here's the course, i had to re-genen it because i deleted it

[33 - 3x6,3m.zip](https://github.com/Courseplay/Courseplay_FS22/files/7958384/33.-.3x6.3m.zip)

**Comment by pvaiko** [comment]
Is it still happening with this course?

**Comment by pvaiko** [comment]
To answer my question: no, it does not, this what you have saved works fine, CP has no issues generating the offset headlands.

I see you merged multiple fields together, it sometimes results in not so clear field boundaries which may cause issues with the generation. I'll try to handle these errors more gracefully but that's all I can do now.

**Comment by Chico0008** [comment]
it's seems to be ok now, right driver isn't goofing anymore.
