### ISSUE TITLE
[Question] [PC] I can see miniHUD only if I choose controller friendy version

### ISSUE THREAD

**Issue by meda22** [Courseplay/Courseplay_FS22#737]
Please, I have a question regarding miniHUD (course play v.23). I play on PC but I can see only controller friendly miniHUD - if set option for controller friendly miniHUD off, I won't get shown anything. I have attached log too but I don't see any error. I use "del" key to show miniHUD.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7959628/log.txt)

**Comment by Tensuko** [comment]
mini hud right now only opens with right mouse click.
Next Version will have it for both.
