### ISSUE TITLE
How do you clear a (finished) course?

### ISSUE THREAD

**Issue by Yasp0** [Courseplay/Courseplay_FS22#74]
When finishing a course the course stays 'unfinished'? How do you clear a course? Because now when you want to use the ingame AI helper the tractor drives to the field with the active CP course.

![fs22-cp](https://user-images.githubusercontent.com/5689226/147383536-51e20935-7891-40d2-ac5c-9d00c8d90b4e.jpg)

**Comment by Keppchen** [comment]
Try to swap in top left corner of helper sreen from CP:Fieldjob to Fieldjob when you want to use the AI Helper? Just an idea

**Comment by Tensuko** [comment]
Just switch to the coursegenerator and click on clear course.

**Comment by Yasp0** [comment]
When in de Course Generator I only see 'Generate fieldwork course' and 'Open/Close course generator'?

![fs22-cp2](https://user-images.githubusercontent.com/5689226/147383932-8c3d2078-537f-427b-9c6e-3a08c0c45c77.jpg)

**Comment by Keppchen** [comment]
I don't have that button either

**Comment by ph1go** [comment]
Click on the next button down on the left and you'll see the option to clear the current course. I agree, it's not *that* intuitive.

**Comment by Keppchen** [comment]
> Click on the next button down on the left and you'll see the option to clear the current course. I agree, it's not *that* intuitive.

I can't see a Next button either 😅

**Comment by ph1go** [comment]
> > Click on the next button down on the left and you'll see the option to clear the current course. I agree, it's not _that_ intuitive.
> 
> I can't see a Next button either 😅
![fsScreen_2021_12_25_12_59_06](https://user-images.githubusercontent.com/30246276/147384484-00274649-f159-4abf-abf4-27c67fb62f78.jpg)

**Comment by kahpe** [comment]
I noticed that sometimes you have to first select correct vehicle from the map, even when you are inside it. Had a same problem and could not clear course, clicking correct tractor on map helped and I was able to clear the course from course manager tab.

**Comment by Yasp0** [comment]
Thanks, I managed to clear the course.  But it's indeed not that intuitive.

**Comment by Alaxsxag** [comment]
1. In main-screen Click ESC and do this
![Farming Simulator 22 25 12 2021 14_23_40](https://user-images.githubusercontent.com/78574601/147386070-a40682fa-ddeb-451f-a30d-94ff24f77506.png)
:

**Comment by Tensuko** [comment]
Oh damn it, that was my bad, I mean Course Manager, not Generator... Sry guys, it was late already...

**Comment by Tensuko** [comment]
> I noticed that sometimes you have to first select correct vehicle from the map, even when you are inside it. Had a same problem and could not clear course, clicking correct tractor on map helped and I was able to clear the course from course manager tab.

Yea that part is tricky. The Problem that we had before was, when you tab arround in the Menus, your last selected vehicle wasn't always the same and it leads to even more problems like you set stuff on the wrong vehicle... I am not sure if it stays like that, maybe the selected vehicle will be changed when you enter a vehicle. That would be a possible option I think.

**Comment by Tensuko** [comment]
Use the Coursemanager or just set the target to a new position and generate the next one.
Work and is tested in 7.0.0.5
