### ISSUE TITLE
[BUG_SP] self-unload does not recognize multiple grain compartments

### ISSUE THREAD

**Issue by gnome1227** [Courseplay/Courseplay_FS22#741]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Actual behavior**
when unloading into a multiple section trailer, it only recognizes the whole trailer as one, so it will not move to the other compartments to unload.

**Expected behavior**
when unloading, it should fill the first section then move to the next

**Courseplay version**
Version used: 7.0.0.22

**Map**
all

**Vehicles/ implements involved**
Wich vehicle or implement?
wilson trailer pacesetter
Mod no

**Relevant script mods**
 Autodrive

**Comment by Tensuko** [comment]
And why did you remove the log part out of our Template and not add a logfile with debugchannels ?

**Comment by gnome1227** [comment]
i apologize for my ignorance but im not sure how and what to do. thought may it would have been pretty straight forward

**Comment by Tensuko** [comment]
Debug information can be turend on in your vehicle settings (last option) then you let it run.
In your case, while he try to fill up all trailers.
Then you post the logfile, how to do this, read this: https://github.com/Courseplay/Courseplay_FS22/wiki
