### ISSUE TITLE
Kursgenerator Einstellung mit 3 Bildschirmen

### ISSUE THREAD

**Issue by IHC553** [Courseplay/Courseplay_FS22#743]
Beim Spielen mit 3 Bildschirmen, wird das "Kursgenerator Einstellungen" Fenster, so groß, das die Einstellbaren Werte genau auf dem Schnittpunkt von 2 Bildschirmen liegt. Man kann die Werte nicht mehr erkennen wenn man sie verstellt.

( Version 70023 
![IMG_20220129_073904](https://user-images.githubusercontent.com/98634573/151650697-ef0448b1-21e8-41a0-8271-721a3fa31105.jpg)
)

**Comment by pvaiko** [comment]
Duplicate of #1015, keeping that one as it is in English
