### ISSUE TITLE
Moin, frage zum Kurserstellen. Wenn ich über das Minihud einen neuen Kurs erstellen möchte rechnet er immer einen Kurs vom vorherigen Feld aus[BUG_SP]

### ISSUE THREAD

**Issue by masuti** [Courseplay/Courseplay_FS22#744]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by masuti** [comment]
CP Version 7.0.0.23 bei erstellen eines neuen Kurses mit dem Minihud, auf einem neuen Feld, errechnet er immer einen Kurs vom vorherigen Feld. Der vorherige Kurs wurde gelöscht. das erstellen eines neuen Kurses mit dem Ingame helfer funktioniert aber.
Gespeicherte Kurse werdenproblemlos übernommen. Habe das auf verschiedenen Karten probiert. Ingame Karten und Modkarten 
immer das gleiche

**Comment by RealNeo80** [comment]
setzt du beim erstellen den startpunkt auch auf das feld wo du generieren willst?
und grundsätzlich würden schon logs mit den debug-infos helfen, ansonsten raten wir nur ...
dafür gibts doch das template, screen bei log bei und es wird einfacher

**Comment by Tensuko** [comment]
Der Zielpunkt (da wo der neue Kurs generiert werden soll) wird erst neu auf die aktuelle Fahrzeug position gesetzt, wenn beim öffnen des Generators, kein Kurs geladen ist.

Working as intended.
