### ISSUE TITLE
Drescher Kursende[BUG_SP]

### ISSUE THREAD

**Issue by masuti** [Courseplay/Courseplay_FS22#745]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by masuti** [comment]
Moin, wenn der Drescher seine arbeit beendet hat fährt er das Rohr aus aber das Schneidwerk wird nicht gehoben und so kann AD nicht abholen CP 7.0.0.32 AD 2.0.0.3

**Comment by RealNeo80** [comment]
ich hab das auch schon festgestellt, das das nicht mehr ganz so sauber funktioniert. AD ist aber gerade dabei das CP interface zu implementieren, damit sollte das dann besser werden. das hier mit Rohrausfahren usw war nur ein workaround bis das Interface steht

**Comment by Tensuko** [comment]
Abwarten bis es soweit ist.
