### ISSUE TITLE
Vehicle convoy too strict [BUG_SP]

### ISSUE THREAD

**Issue by Krel2011** [Courseplay/Courseplay_FS22#749]
**Steps to reproduce**
Create course with multiple tools.

**Actual behavior**
When starting course with two helpers, they wait for each other to start the task, leading to the behind worker, being blocked by the front. When turning in the end of a row, if convoy distance too small, first worker will not make the turn before second worker is "blocked" and stopping it´s task. Front worker is also waiting for back worker to finish turn, decreasing work speed.

**Expected behavior**
Multiple workers should be able to without interfering with each other, other than keeping a minimum distance to each other, set by the setting "convoy distance"

**Courseplay version**
Version used: 7.0.0.23

**Map**
ND Hastings

**Vehicles/ implements involved**
Wich vehicle or implement?
2x John Deere 9RX
2x Farmet Kompaktomat

Mod yes/no ?
no

**Relevant script mods**
Mods like Autodrive or VCA and so on.
VCA-on
AD-on

**Comment by Tensuko** [comment]
And why did you remove the most important parts of that Template ?!
logfile with debugs on ?!

**Comment by Krel2011** [comment]
https://pastebin.com/jZxciBkp
