### ISSUE TITLE
[BUG_SP] Tractor stuck on bale

### ISSUE THREAD

**Issue by winn69** [Courseplay/Courseplay_FS22#752]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Hire Ai driver and select wraping collect bales and make course and start job

**Actual behavior**
When Ai driver go reverse he stuck on bale and I got notification worker A blocked by object and he stop with work

**Expected behavior**
I expected that he avoid bale or something. When I have other fieldwork and example if I had vehicle on field Ai will push that vehicle 

**Screenshots**

![20220129162542_1](https://user-images.githubusercontent.com/98623764/151668781-74b2b8f5-73fa-4ae8-aa65-8ca6421ab402.jpg)

**Courseplay version**
Version used: 7.0.0.23

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
(https://gist.github.com/winn69/3cf6857d6299a617685f0783c0e6ff23)

**Map**
Map Wild West

**Vehicles/ implements involved**
Wich vehicle or implement?
Zetor Crstyal 12045 and Am Tunning pack poettinger impress 185vc pro

Mod yes

**Relevant script mods**
Mods like Autodrive or VCA  both and Vehicle inspector. But Autodrive dont have path so I dont use it

**Comment by Tensuko** [comment]
Won't dodge bales on course.
Start on up down and use turn on field off.
Should also fix your mods, lot of errors.
