### ISSUE TITLE
[BUG_SP] Savegame Loading Error

### ISSUE THREAD

**Issue by UnknwnArtst** [Courseplay/Courseplay_FS22#753]
Hallo zusammen, seit dem Update auf Version 0.23 habe ich Probleme ein Savegame zu laden.

Wenn ich den Error richtig deute hat es wohl was mit Courseplay zu tun.

Anbei Screenshot und Log.txt

![Error](https://user-images.githubusercontent.com/14059882/151669549-5d53a912-119c-4448-b46e-f4172282794d.jpg)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7964156/log.txt)

**Comment by Tensuko** [comment]
- Bist du wirklich auf Release .23 ?
- Warum hast du das Template nicht benutzt ?
- Schau dir #710 an und lade im Zweifel das Release runter.
