### ISSUE TITLE
Courseplay just sits there and uses fertalizer but wont move[BUG_SP]

### ISSUE THREAD

**Issue by sirbum69** [Courseplay/Courseplay_FS22#755]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Just create a new course

**Actual behavior**
When you start the course, CP turns on the Tractor and begins the implement spraying the fertalizer but wont
move the tractor out of Gear to run the course. Just sits in nuetral

**Expected behavior**
Should start the course, put the tractor into gear and move forward

**Screenshots**
![image](https://user-images.githubusercontent.com/47197381/151675881-03bde9b5-3269-4c89-ab2c-decf33b58e1f.png)

**Courseplay version**
Version used: 

**Log**
Not able to find the log, but the one i did find 
says that CP is waiting for convoy vehicle to start. There is no convoy
doing this. Only the one tractor. And i dont even have the option to pick 
the convoy amount as i seem to have with other implements.

**Map**
Remake of elmcreek by Stevie

**Vehicles/ implements involved**
Magnum 400 powerdrive Case
Mod no

**Relevant script mods**
Autodrive but its not running

This all seems to have started after the last update .23 as before that i was not having any issues
with Courseplay.

**Comment by Tensuko** [comment]
Read Wiki!
