### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by pulimatrix** [Courseplay/Courseplay_FS22#756]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki
Yes i Have

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

Hey everyone
Have the current version, the loader wagon, when it arrives at the field, lowers and drives across the field. Even at the end to start the new track, he doesn't lift it to drive to his last point to continue working I only noticed it since the last update lg

**Expected behavior**

**Screenshots**
https://ibb.co/qJmgGyc
https://ibb.co/zHbVRSC

**Courseplay version**
Version used: 
7.0.0.23
**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
https://filehorst.de/d/eunFJcnu (log)
**Map**
Map played on.
us map

**Vehicles/ implements involved**
Wich vehicle or implement?
Mod yes/no ?
no
Class Arion 660 Loadingwagon class cargos 8400
**Relevant script mods**
Mods like Autodrive or VCA and so on.
VCA and Autodrive

**Comment by Tensuko** [comment]
Wait untill AD have its official Release for this, then we have a look....
