### ISSUE TITLE
Mini GUI lässt sich nicht aktivieren. Bei der Kombination LShift +5 spielt das Radio, was es übrigens bei sämtlichen Kombinationen mit der 5 tut[BUG_SP]

### ISSUE THREAD

**Issue by Hawkeye1708** [Courseplay/Courseplay_FS22#759]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Sry, setzen 6.
Mini GUI wer sagt was von shift + 5 ?
Mini GUI für gamepad geht mit option an + del (default) mini hud ist rechte maustaste und del (default).

**Comment by Hawkeye1708** [comment]
Das mit dem Lshift 5 steht so in der Tastaturbelegung. Von rechte Maustaste und del. ist hier nirgends was zu lesen
