### ISSUE TITLE
[BUG_SP]Polish translation - too many letters, doesn't fit to mini GUI window

### ISSUE THREAD

**Issue by mdradek** [Courseplay/Courseplay_FS22#760]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Polish translation.

**Actual behavior**
As seen on screenshot

**Expected behavior**
Maybe adding option to adjust GUI size? Smaller font? 
Any solution will be fine:)

**Courseplay version**
Version used: 7.0.0.23

![Zrzut ekranu (307)](https://user-images.githubusercontent.com/47240006/151681907-ca73c02c-bf09-4148-b15a-b18f7d976fe9.png)

**Comment by KITT3000** [comment]
Można skrócić tekst do takiego:
Przes. poziome dla narzędzi
Przes. pionowe dla narzędzi

**Comment by mdradek** [comment]
Ogarnąłem, dzięki ;)

Simple solution - edit xml from "translations" folder and shorten text to fit to the mini GUI window.

Thank you.
