### ISSUE TITLE
Schönen guten Tag ich bin Englisch leider nicht so gut deswegen schreibe ich erst in Deutsch und danach lasse ich Übersetzen mit Google.[BUG_SP]

### ISSUE THREAD

**Issue by Blackfire0893** [Courseplay/Courseplay_FS22#766]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Template nicht ausgeüllt und doppelpost.
