### ISSUE TITLE
Schönen guten Tag ich bin Englisch leider nicht so gut deswegen schreibe ich erst in Deutsch und danach lasse ich Übersetzen mit Google. Mein Problem ist das ich nur mit der .10 Version spielen kann ich kann sie nicht auf die neuste Version aktualisieren ich weiß nicht woran es liegt oder wo der fehler ist er meint in der Meldung das es irgend wie mit Patch +#[BUG_SP]

### ISSUE THREAD

**Issue by Blackfire0893** [Courseplay/Courseplay_FS22#767]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
Template nicht ausgefüllt, so kann dir keiner helfen, sry!
