### ISSUE TITLE
Raise and lower tool no effect on plows

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#77]
Ich habe Felder grubbern und pflügen lassen. Beim grubbern mit einem großen Grubber hatte er Probleme beim wenden und schob beim zurücksetzen den Grubber im Kreis. Da wollte ich den Wenderadius erhöhen. Das hat jedoch gar nichts an der Fahr- und Wendeart verändert.

Beim pflügen hat er den Pflug immer zu früh gehoben bzw die Bahn 1m zu früh beendet. Einstellungen Gerät anheben/senken früh/spät verändert und ebenfalls keinerlei Veränderungen zu spüren.

Kann es sein, dass die Funktionen noch ohne Funktion sind oder muss ich nach der Änderung den Kurs neu generieren?

**Comment by Tensuko** [comment]
Nein den Kurs musst du nicht neu generieren.
Wendekreis ist glaube ich aktuell fix.
Ob absenken oder anheben für pflüge funktioniert bin ich nicht sicher.

Auf alle Fälle schauen wir uns das an. Danke für das Feedback.

**Comment by Keppchen** [comment]
Works perfectly. Thanks
-------------------------
Loift, danke :)
