### ISSUE TITLE
Neue Version macht Probleme

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#770]
Die Map bleibt beim laden auf 60% stehen. Anscheinend liegt wohl ein Fehler in Courseplay.
Bitte um Korrektur.
Freundliche Grüße und Dank
Stefan

**Comment by Tensuko** [comment]
Bei mir nicht.
Und jetzt ?
kein logfile wieder mal, schau dir bitte mal #710 an...

**Comment by joshi2** [comment]
I have the same problem with the .24 version, before that it worked fine.
I tried every map multiple times and it doesn't load past 60%, even on the standard ones.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966114/log.txt)
