### ISSUE TITLE
Aufzeichnung von Feldrandkursen mit dem Controller-freundlichen HUD/Tastenbelegung

### ISSUE THREAD

**Issue by XPiRiJenZ** [Courseplay/Courseplay_FS22#772]
Hallo!

Prinzipiell beschreibt die Überschrift meine Idee.
Mit dem controllerfreundlichen HUD ist es in der aktuellen 0.24 nicht möglich Feldrandkurse aufzuzeichen.

Das könnte mit Hilfe einer neuen Tastenkombination oder der Implementierung der Funktion in das Controller-HUD möglich gemacht werden, sodass die Spieler, die eher den Controller bevorzugen, das neue Feature ebenfalls nutzen können.

**Comment by Tensuko** [comment]
Jap, kam mir auch schon in den Sinn.
Das lässt sich bestimmt noch machen.

@schwiti6190 so wie du das für den Olivenkurs geplant hattest ?
Für Oliven überlege ich mir watt anderes.

**Comment by schwiti6190** [comment]
Sollte in der neuesten version gehen :)

**Comment by Tensuko** [comment]
Oops, vergessen das der schon drin war :D
