### ISSUE TITLE
[BUG_SP] Crash game on loading

### ISSUE THREAD

**Issue by winn69** [Courseplay/Courseplay_FS22#773]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
I load game and map come about 50% and game crash

**Actual behavior**
During map loading game crash

**Expected behavior**
I expected normal load and play game

**Screenshots**

**Courseplay version**
Version used: 7.0.0.24

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
https://gist.github.com/winn69/0f0eda7646c9e9e10b2fe8240ecfca28

**Map**
Wild West 

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment]
No Issue with .25 and original WW Map.
