### ISSUE TITLE
[BUG_SP] Course generator, one corner sharp, others round.

### ISSUE THREAD

**Issue by Roby1164** [Courseplay/Courseplay_FS22#774]
There is still a problem with the creation of the courses, as you can see in the photo, the problem is the corners, where the first peripheral course is created correctly, at an angle, while the innermost ones, from the second onwards, if the corner of the field, it is not at 90 °, it creates it as a radius curve, this leaves part of the crop uncharged.

Version used last release v. 7.0.0.24

![Screenshot_4](https://user-images.githubusercontent.com/24955554/151703091-1f88838a-5c1a-4ab9-bdbe-55a511218b94.jpg)

**Comment by Tensuko** [comment]
Why did you use question template and then mark that yourself as "[BUG_SP]" and not add a logfile and stuff.
I don't get it...

**Comment by Roby1164** [comment]
> 

It was a mistake, I wanted to report it as a bug, but then, I preferred it as a question, but the browser left the Bug indication, and I didn't notice ...

**Comment by Tensuko** [comment]
A logfile would be still great! Generate the same course and when it comes out like that again, attach logfile.

**Comment by Roby1164** [comment]
> 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966281/log.txt)

**Comment by pvaiko** [comment]
@Roby1164 you forgot to mention that this is a mod map. Either you can reproduce this on a standard map or you can export all your fields with the cpSaveAllFields console command and post the XML file generated here.

**Comment by Roby1164** [comment]
> @Roby1164 you forgot to mention that this is a mod map. Either you can reproduce this on a standard map or you can export all your fields with the cpSaveAllFields console command and post the XML file generated here.

The map is mod, La FermeBeyleron, but only for changes to buildings and other things, the fields are original, they are the fields of the standard Beyleron map, except for the changes made in the game, such as the union of some fields by plowing.
Tomorrow I see to do a test on the original map, for now I have tried to do the cpSaveAllFields, but it brings me an error that I don't know what it is:
![Screenshot_4](https://user-images.githubusercontent.com/24955554/152065584-a24d5ace-c451-480c-b125-7c6b65f1af00.jpg)

**Comment by Roby1164** [comment]
> @Roby1164 you forgot to mention that this is a mod map. Either you can reproduce this on a standard map or you can export all your fields with the cpSaveAllFields console command and post the XML file generated here.

I wanted to do the tests, but, today, with the latest main brach version, with the modification of schwiti6190, (Fixes course generator layout again ...), it seems that the problem has disappeared, in fact now creating the path on the same field, in the same configuration, the angles are correct. Dunno, I don't know if it has been fixed that those changes made .....
![Screenshot_4](https://user-images.githubusercontent.com/24955554/152122128-dfba201d-4827-43cf-a736-a34e87d21805.jpg)

**Comment by pvaiko** [comment]
Reopen if you see it again. And always attach the entire log, not a screenshot.
