### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by forstwirt** [Courseplay/Courseplay_FS22#775]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

Hallo Leute,
nach der Instalation der Courseplay v.7.0.0.24 für LS 22 bleibt
bei mir der Ladevorgang bei 60% hängen und geht nicht mehr weiter.
Ich habe das Spiel komplett deinstaliert, neu heruntergeladen und instaliert,alle Mods entfernt und nur mit Courseplay versucht ein neues Spiel zu starten,bleibt trotzdem bei 60% und der Ladevorgang geht nicht weiter.
Sobald Courseplay vor dem Start abgewählt wird funktioniert alles.
Ist es nur bei mir so ?

**Comment by Tensuko** [comment]
Template wieder nicht benutzt, ich dreh am Rad....

Versuch das was hier beschrieben wird! -> #710
