### ISSUE TITLE
[Feature] Improved turns for combines

### ISSUE THREAD

**Issue by SilverWheelz** [Courseplay/Courseplay_FS22#777]
**What is the problem this feature/enhancement solves?**
I had two combines running on a multitool course. The problem is that the combine on the outer side of the turn turns too wide to line up for the next row even though there was ample amount of space/headlands which causes it to collide with the fence.

1st scenario (pathfinder for turns was enabled):
![Screenshot (512)_LI](https://user-images.githubusercontent.com/94125770/151707304-7b11647e-0b54-413f-8bef-ea1b90932fe6.jpg)

The green line shows the actual route the combine took. The X marks the collision point with the fence. The yellow dashed line indicates the route the combine wants to proceed on. As seen here, the combine turns too wide just to line up with the next row.

2nd scenario (pathfinder for turns was disabled):
![Screenshot (506)](https://user-images.githubusercontent.com/94125770/151706808-c0f910e7-4775-475b-b1b1-b92d4b08cee7.png)

I tried disabling pathfinder for turns and reversing but it didn't help. The combine still turns too wide which was unnecessary with the amount of space it had.

**Describe the solution you'd like**
Lessen the turning radius for turns like these. Maybe make it similar with how combines turned on the FS19 version of CP, since it was better imo.

**Describe alternatives you've considered**
More headlands - will work but is unnecessary
More Field Margin - Will also work but at the cost of more crop loss or more manual labor
Slower turn speed - will help since as seen on the 2nd scenario, the combine overshot the turn. But still, that wide of a turn was still unnecessary.
Enable turn on field  - will maybe work but will cause unnecessary maneuvers
Manual row angle - will work for this field but probably not for odd-shaped ones

**Comment by Tensuko** [comment]
> Enable turn on field - will maybe work but will cause unnecessary maneuvers

What unnecessary maneuvers ?

Example ?

**Comment by SilverWheelz** [comment]
> What unnecessary maneuvers ?
> 
> Example ?

Not sure if this applies to combines but with a tractor + 3-point or towed implement, it generates a reverse turn for after each row. Haven't used turn on field for quite a while now since doing headlands will usually suffice.

**Comment by pvaiko** [comment]
We ask for a log with debug info because it makes life a lot easier for us, we don't have to guess for instance, what kind of turn maneuver your combine on your first screenshot was doing.

**Comment by SilverWheelz** [comment]
Fixed/Implemented with the latest version. I can no longer replicate what's happening in the screenshots using the same course.
