### ISSUE TITLE
Spiel Stand Bleibt bei 60% Stehen 

### ISSUE THREAD

**Issue by stefan10921** [Courseplay/Courseplay_FS22#779]
hey mein problem ist das sich mein Spielstand nicht mehr laden läst 
Habe jetzt die neue version von autodrive und due neuste version von CP

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966506/log.txt)

**Comment by Dennis-02** [comment]
Deaktiviere CP->lade in deinen Spielestand->speichern->verlassen->CP aktivieren->laden->es funktioniert wieder :)

**Comment by stefan10921** [comment]
@Dennis-02   nein das klapt auch nicht meine log spint jetzt total
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966540/log.txt)

**Comment by Tensuko** [comment]
C:/Users/Shadow/Documents/My Games/FarmingSimulator2022/modSettings/FS22_Courseplay/Courses/mapAlpine
Dort einen Ordner mit dem namen Singleplay erstellen, dann geht es wieder, wird bald gefixt.

**Comment by BizzWareX** [comment]
@Tensuko falls für dich noch relevant:
LOG:
https://share.bizzware.info/dtaV4z.txt

**Comment by stefan10921** [comment]
@Tensuko  Danke jetzt klabt es

**Comment by Dennis-02** [comment]
> @Dennis-02 nein das klapt auch nicht meine log spint jetzt total [log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7966540/log.txt)

Sorry. Bei mir hat es so geklappt deswegen dachte ich mir, ich schlage dir das mal vor...

**Comment by Tensuko** [comment]
Sollte mit der 7.0.0.25 gefixt sein.

**Comment by Geryls19** [comment]
Hast du die Mod Energie Starter oder Horse Helper in deinem Modordner wenn ja mache beide raus und es geht wieder wirsst sehen
