### ISSUE TITLE
Horizontaler Versatz resettet sich

### ISSUE THREAD

**Issue by Keppchen** [Courseplay/Courseplay_FS22#78]
Bei einem kleinen ~Grubber~ Pflug wollte ich den horizontalen Versatz von -0.3 ändern. Ich konnte klicken und er änderte auf -0.4, -0.5 und so weiter aber sobald ich aufgehört habe zu klicken wurde der Wert schnell auf -0.3 zurück gestellt.

**Comment by Tensuko** [comment]
Der Versatz wurde erst kurz vor release richtig eingebaut, hat sich wohl noch was eingeschlichen.
Gucken wir uns an. Danke fürs Feedback.

**Comment by Keppchen** [comment]
Ich bin grad wieder am grubbern aber kann nun den Versatz ohne Reset ändern. Habe dazu nichts in den Release-Notes gefunden, scheint aber behoben.

Soll ich das morgen noch genauer testen mit mehreren Geräten oder das Thema schließen?

**Comment by Keppchen** [comment]
Vielleicht hilft das: https://youtu.be/bPF86vRik3Q

**Comment by Tensuko** [comment]
Naja verstanden haben wir, was da passiert.
Passt es denn gar nicht ?

**Comment by Keppchen** [comment]
> Naja verstanden haben wir, was da passiert. Passt es denn gar nicht ?

Naja was heißt passt gar nicht. Mir ging es nicht mal unbedingt darum dass der Versatz nicht passt und das Feld nicht ordentlich geräumt wird sondern mehr darum, dass es eine Option gibt die man manuell anpassen kann, die sich dann aber selbstständig resettet, was ja bestimmt nicht in eurem Sinne ist. Aber eine hohe Prio hat das nicht, nein.

**Comment by Tensuko** [comment]
Die resettet sich aber nur bei einem Pflug, weil wir den aus bestimmten Gründen dynamisch berechnen. Das der z.B. beim Kverneland nicht passt, wissen wir, den Grund kennen wir auch mitlerweile.
Aber z.B. Mähwerke mit versatz funktioniert (vlt auch erst mit 7.0.0.8 die gleich kommen sollte...)

**Comment by Keppchen** [comment]
Agromasz POV nutze ich aktuell und hier stimmt der Versatz leider gar nicht. Er grubbert Reihe für Reihe immer nur wenige cm weg. Scheint aber nicht nur der Versatz zu sein. Sonst würde er ja bei jeder 2. Reihe zu weit sein. Ich könnte mal das Log posten ich aktiviere mal alle Kanäle. Und versuche ein Video zu machen

**Comment by Tensuko** [comment]
log wäre gut, mit debug natürlich.

**Comment by Tensuko** [comment]
Mit dem Pflug sollte nun erst mal geklärt sein.
Andere Geräte ist ein anderes Thema.
Wann da der Reset statt findent, schauen wir dann.
