### ISSUE TITLE
[BUG_SP] CP worker not able to use sprayers or toolbar

### ISSUE THREAD

**Issue by Allis1948** [Courseplay/Courseplay_FS22#785]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Try to start the Worker using a fertilizer sprayer.

**Actual behavior**
A clear and concise description of what happen.
-When using anhydrous tool bar with the tank behind,  CP worker does not detect the tank fill level.  The error is AI worker unexpectedly stopped - Tank Empty! when tank fill level was 100% tried with both anhydrous and Liquid fertilizer. 

The in game AI has no issues using the tank and works properly.

**Expected behavior**
- I expected the worker to go on like normal with the field work.

**Screenshots**

**Courseplay version**
Version used: .25

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
Deer Creek

**Vehicles/ implements involved**
Which vehicle or implement? BB Tool bar & Anydrous tank pack from Central Ohio Modding
Mod yes/no ? yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive

I have tried 2 different tank mods and 2 different tool bar mods.  I get the same issue weather it is filled with anhydrous or liquid fertilizer.

**Comment by Tensuko** [comment]
What is a tool bar mod ?
And where is the logfile ?

**Comment by Roby1164** [comment]
> BB Tool bar

I think how BB ToolBar refers to this mod https://fs22mods.com/bb-toolbar-tank-v1-0-0-0/
But I'm afraid that the problem is related to this type of articulated equipment, which performs two jobs in one. I with various fertilizers, solid or liquid, for the moment I have never had a similar problem.

**Comment by RealNeo80** [comment]
#614 i think its same problem as here and with the bourgault

**Comment by schwiti6190** [comment]
Same problem as #614.
