### ISSUE TITLE
Czech translation done!

### ISSUE THREAD

**Issue by SniperKittenCZ** [Courseplay/Courseplay_FS22#79]
Hi, I made Czech translation of Courseplay for FS22 v7.0.0.3. How can I sent it to developers for adding to the official release of mod?

**Comment by Markus33-ITA** [comment]
Courseplay_FS22/translations/translation_cz.xml  then do edit and put your change and then pull request

**Comment by SniperKittenCZ** [comment]
And how can I pull request?

**Comment by Tensuko** [comment]
You can also add the file here as an attach and I can add it for you. Thanks for your work.

**Comment by pvaiko** [comment]
Please create a pull request, do not attach files here. There are about a million descriptions about how to create pull requests on GitHub. Thanks.

**Comment by SniperKittenCZ** [comment]
Unfortunately, I don't have time to read a million descriptions of how to create pull requests on GitHub. Here is my translation. Take it or not. 
[translation_cz.zip](https://github.com/Courseplay/Courseplay_FS22/files/7775851/translation_cz.zip)
Merry X-Mas to all!

**Comment by pvaiko** [comment]
Fair enough. Just to clarify, if you create a pull request, all we have to do is click a button on GitHub to merge it. If you instead attach a file here, we'll have to download it, unzip it, resolve conflicts, commit and push it. For which, unfortunately **we** don't have the time for.

**Comment by SniperKittenCZ** [comment]
I understand, thx for your great work!

**Comment by SniperKittenCZ** [comment]
I finally found the way, how to create pull request, so I hope I did it right... 😉
