### ISSUE TITLE
[Feature] Verband arbeitet vollständig bis Kursende

### ISSUE THREAD

**Issue by CHW-user** [Courseplay/Courseplay_FS22#793]
**What is the problem this feature/enhancement solves?**
Aktuell hören alle Fahrzeuge im Verband mit der Arbeit auf, sobald das erste Fahrzeug das Kursende erreicht hat.
Vielleicht kann man das etwas verbessern?

**Describe the solution you'd like**
Option 1:
- Fahrzeug 1 erreicht das Kursende und fährt noch ein wenig weiter um den Patz für Fahrzeug 2 frei zu machen.
- Fahrzeug 2 erreicht das Kursende und fährt noch ein wenig weiter um den Patz für Fahrzeug 3 frei zu machen.
- etc.

**Describe alternatives you've considered**
Option 2:
- Fahrzeug 1 erreicht das Kursende. Wie bisher bleiben die anderen Fahrzeuge stehen. 
- Ich entferne manuell Fahrzeug 1.
- Fahrzeug 2 arbeitet weiter und erreicht das Kursende.
- etc.

**Additional context**

**Comment by Tensuko** [comment]
Kannst du mal Option 2 testen, wenn du nach dem manuellen entlassen den Kurs aus Fahrzeug 1 entfernst ?

**Comment by astra16v** [comment]
hallo...hab eben die 2. option überprüft...wenn man den kurs aus fahrzeug eins löscht fährt fahrer 2 wieder weiter bis zum schluss

**Comment by Tensuko** [comment]
Super dann weis ich wie man das vlt lösen könnte.

**Comment by Tensuko** [comment]
@pvaiko 
Multitool Kurs rausschmeißen wenn der Fahrer fertig ist ? :)

**Comment by pvaiko** [comment]
Kann hoffentlich auch schöner lösen.

**Comment by CHW-user** [comment]
@Tensuko:
 Ich kann bestätigen, was @astra16v schon beschrieben hat :-)

Vielleicht eine Lösungsidee (?):
Grundlage:

**_a = Anzahl der Fahrzeuge im Verband 
y = Anzahl der Kurspunkte (y entspricht somit auch dem Endpunkt)
x = aktuelle Position des Fahrzeugs im Kurs (Punkt x von y)_**


Sobald x = y (also, wenn ein Fahrzeug den Endpunkt erreicht) reduziert sich die Anzahl der Fahrzeuge im Verband um 1.
Also:

**_Wenn x= y, dann a = a-1_** 

Ganz phantastisch wäre, wenn das Fahrzeug am Punkt y dann noch Platz für die Nachfolgenden macht...

**Comment by Tensuko** [comment]
Sollte jetzt klappen mit der 7.0.0.26

**Comment by CHW-user** [comment]
funktioniert - vielen lieben Dank :-)
