### ISSUE TITLE
[Feature] Auswahl des "Feldes" bei Überlappung von normalen und recorded Feldern

### ISSUE THREAD

**Issue by DHempelmann** [Courseplay/Courseplay_FS22#794]
**What is the problem this feature/enhancement solves?**
Wenn ich einen Feldrandkurs eingefahren habe, der sich teilweise über vorhandene Felder erstreckt, dann habe ich Probleme, das "Feld" eindeutig zu treffen, in dem ich einen Kurs generieren möchte.

**Describe the solution you'd like**
Oben im Kursgenerator sollte eingeblendet werden, für welches Feld ich gerade einen Kurs berechne. Also ob es sich um ein "normales" Feld ("F-xx", anhand der Feldgrenzen berechnet) oder um ein eingefahrenes Feld ("CP-x") handelt.
Befindet sich meine "Field Position" in mehreren möglichen Feldern, so sollte es ein Auswahlfeld sein, in dem ich das auswählen kann, welches ich nutzen möchte.

**Describe alternatives you've considered**
Wenn ich die "Field Position" setze, dann könnte man das Feld bereits rot umranden, was jetzt gewählt ist. So sieht man vor der Generierung, ob man richtig geklickt hat.

**Comment by Tensuko** [comment]
> Oben im Kursgenerator sollte eingeblendet werden, für welches Feld ich gerade einen Kurs berechne.

Ja, gute Idee.

Ein Auswahlfeld wird schwer, aber ich kann mir vorstellen, dass wir sagen können bevorzuge den Feldrandkurs, schließlich hat man den nicht ohne Grund angelegt.

**Comment by pvaiko** [comment]
Wusste das es mit überlappungen kommt... Wenn unter der Startposition ein normaler Feld liegt wird immer der ausgewählt. Ob der Startpunkt auf einem eingefarhenen Feld ist wird nur gecheckt wenn er nicht auf einem normalen Feld liegt. 

Bei überlappende eingefahrene Felder ist es wählt CP wahrscheinlich den mit dem kleineren Nummer aus. 

Evt. müssen wir die Feldauswahl durch eine List zurückbringen.

**Comment by Tensuko** [comment]
> Evt. müssen wir die Feldauswahl durch eine List zurückbringen.

Eine Unterscheidung zwischen customField und normalen Feld ist nicht möglich?
Denke da an den Namen z.B.
Wenn ja customField bevorzugen.

**Comment by DHempelmann** [comment]
"Immer den Feldrandkurs" ist aber auch insofern unschön, weil man dann möglicherweise gar keine Chance mehr hat, nur das Feld zu wählen. Man müsste dann den FRK löschen...
Vielleicht kann man wirklich einfach schon beim Setzen der Field Position (hier fehlt noch die deutsche Übersetzung ;-) das aktive Feld markieren?

**Comment by Tensuko** [comment]
Dann verstehe ich aber nicht, warum du einen Feldrandkurs überhaupt erstellt hast...
Hast du mal ein Beispiel als Screenshot ?

**Comment by DHempelmann** [comment]
In meinem Fall hast du recht. Ich habe mir auf der Elmcreek aus Feld 40 und den ganzen Wiesen daneben ein großes dreiteiliges Grasfeld gemacht. Mähen und so habe ich bisher mit einem AD-Kurs gemacht (siehe Bild). Düngen musste ich bisher immer selbst, das macht jetzt aber auch CP.
![Elmcreek_Wiese1](https://user-images.githubusercontent.com/61832717/151791754-4a6c2861-f67b-4535-97d7-b75b695efc43.JPG)

Wie gesagt, in dem Fall ist es nicht so schwierig, das CP-Feld auszuwählen. Einfach irgendwo die Straße treffen. Aber es ging mir ja auch nicht nur um mich ;-)

**Comment by RealNeo80** [comment]
ich kenne das problem auch, die Feldrandkurse nutze ich manchmal um felder zum Dreschen zusammenzulegen, wenn die selbe frucht drauf ist. hab ich sie aber unterschiedlich bepflanzt brauche ich die alten Felder. Im Moment kann ich den FRK aber auswählen wenn ich auf den Feldweg klicke der nicht zu den feldern gehört

![image](https://user-images.githubusercontent.com/8066324/151792402-57e52ad0-d026-4d0b-9d52-0243ca3e0428.png)

**Comment by pvaiko** [comment]
Ok, use case offensichtlich existiert, wir bauen da was ein.

**Comment by Tensuko** [comment]
Es wird Visuell angezeigt, welcher Feldrand genommen wird.
