### ISSUE TITLE
[BUG_SP] Course Generator does not use recorded field edge

### ISSUE THREAD

**Issue by sootysax** [Courseplay/Courseplay_FS22#797]
I am recording a field edge on grass fields on Calmsden Map, but the CG is not using the edge, and creating a course that spans the two other fields that are separated by stone walls.   I put the target and field location marker within the recorded field edge, but not sure how to make CG use it.

https://gist.github.com/sootysax/d26dea1f9c6f246feeafdf2065c7ad36

![Screenshot 2022-01-31 07 54 53](https://user-images.githubusercontent.com/6591048/151797734-a8fc9f82-76da-4d72-9fd5-108fbe1af175.png)

**Comment by Tensuko** [comment]
duplicate  #794
