### ISSUE TITLE
Wrong turning with fertilizer + seeder tools

### ISSUE THREAD

**Issue by mckulich** [Courseplay/Courseplay_FS22#80]
So currently i am using CP 7.0.0.3 together with AutoDrive 2.0.0.2. I tried to send worker to work on field 68 (Elm Creek Map) Amazone ZA-TS 3200 42m width. I tried to set route which was all fine, but once driver hit the end of the field he just drive away from field instead of turning. He ended on train track instead (He was stucked) I tried to re-route course from different starting point, but result was the same. I even tried to run debug tool (but sadly, dont know where the output log file is located) 

Just in case i pressed Shift+4 then i selected mod fertilizing and then i hitted Shift+2, title was green so i supposed that it record something. then i hitted shift+2 again. but i cant find any files what so ever. So if u will need more info or upload any file, point me in right direction and i will run that test again and send that file.

**Comment by Tensuko** [comment]
> but sadly, dont know where the output log file is located

Same as always:

Post the complete game log:

    You can find it in the following directory:
        Windows (7 and above):
        C:\Users\[YOUR USER NAME]\Documents\My Games\FarmingSimulator2019\log.txt
        Mac:
            Mac OS X Download/DVD/Steam-Version:
            /Users/[YOUR USER NAME]/Library/Application Support/FarmingSimulator2019/log.txt
            Mac OS X AppStore-Version (Mac OS X 10.7 and newer):
            /Users/<your username>/Library/Containers/com.focus-home.farmingsim2019/Data/Library/Application Support/FarmingSimulator2019/log.txt
    Upload the log:
    Go to Gist or Pastebin, and add your log content by either using copy and paste, or dragging the log.txt file into the text area (Gist only).
    Post the link to your log in the issue.
    You can also drag and drop the log.txt into the comment box.

Our debugs are all written inside the log.txt
Screenshots also helps.

**Comment by mckulich** [comment]
Log file
https://gist.github.com/mckulich/06c7541964e15d6ede516abb7e22eaeb

I was looking for some special log output from mod itself ;) So here is that log, hope it will help

**Comment by mckulich** [comment]
So to keep this clean, i found out another issue with turning. This time it is field 25 US map as well. Width of seeder is 9m, dont know if it is important, but more info the better i guess, down below is link. it seems there is some error at the end of log and that was the time when driver should already turn around. Instead he hitted the near sign and stopped :D

Interesting fact in previous log i posted i was working on field 25 without issue, but i did some cultivation.

https://gist.github.com/mckulich/cd2a8fc517925123b6c2f472c560fd12

**Comment by Tensuko** [comment]
Thanks for your feedback.
As we pushed out new Versions kind of fast and also changed some stuff on turns, I would like to close this Issue.
If a Problem persits with the newest Version, pls open a new Issue and use our template.
If you can, reference this issue pls, thank you.
