### ISSUE TITLE
[BUG_SP] Convoy not starting when other Vehicles have same course loaded

### ISSUE THREAD

**Issue by bmsbwd** [Courseplay/Courseplay_FS22#800]
**Steps to reproduce**
Have a course planned with two Vehicles, load course to both vehicles, have course loaded to any further vehicle.

Following scenario: I got 2 mowers on a course and i wan't to collect the cut grass with two additional vehicles (Fastrac with loading wagon).

**Actual behavior**
The  vehicles won't start working. If i delete the course fron the two additional vehhicles an start again it works like a charm.

**Expected behavior**
As soon as 2 vehicles are on the field and have been started with a course that needs 2 vehicles on their respective (course-)positions (in this case left and right) they shoud start working.

**Screenshots**

![Kurs](https://user-images.githubusercontent.com/10153289/151808344-412de2f4-16f9-4c8d-b319-e1a627461ff2.jpg)

**Courseplay version**
Version used:  .25

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7971327/log.txt)

**Map**

Elmcreek

**Vehicles/ implements involved**

2 Fend 1050 with front- and butterflymowers
2 Fastrac 8330 with loadingwagons

Jes, as seen in log.

Thank's for your great work!

**Comment by Tensuko** [comment]
Working as intended.
You can save the course again under an extra name.

**Comment by pvaiko** [comment]
Let me think about this, what @bmsbwd expects makes sense, I think we can check if we have enough vehicles for the multitool setting of the course.

**Comment by pvaiko** [comment]
No I won't, I'll just let the users worry about that.

**Comment by rohne83** [comment]
Would there be a way to also turn off convoy mode completely? Thinking especially of balers or loading wagons the distance between the vehicles on course is totally unimportant in most cases. And most farms won't even own as many balers as they have combines, but of course they have to use the combines' course to get their straw.

**Comment by Tensuko** [comment]
For now we keep it like this.
