### ISSUE TITLE
[BUG_SP] Drescher im Verband Folgefahrzeug bricht ab wenn erstes Fzg abtankt

### ISSUE THREAD

**Issue by Zugross** [Courseplay/Courseplay_FS22#803]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Kurs für 2 Fahrzeuge -> 2 Drescher Fahren lassen warten bis der Erste voll ist

**Actual behavior**
Der erste Drescher bleibt zum Abtanken stehen. Der zweite Drescher beendet nun die Arbeit mit dem Vermerk "Objekt wird blockiert". 
Der erste Drescher startet erst wieder wenn der zweite manuell gestartet wird. Der Fehler tritt umgekehrt - Drescher 1 muss auf Abladen von 2 warten - ebenfalls auf

Siehe privates Video auf Youtube: 
https://youtu.be/LjNND8BHpbg Drescher 1 muss warten
https://youtu.be/-FmT1cdqovs Drescher 2 muss warten

**Expected behavior**
Ich würde erwarten, dass dioe Verbundsmitgleider erkennt, dass ein anderes Fahrzeug abgetankt wird und solange einfach warten.

**Screenshots**

**Courseplay version**
Version used:  7.0.0.25

**Log**
Log reiche ich beim nächsten auftreten nach

**Map**
WildWest 16x

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
AutoDrive 2.0.0.4

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS22/issues/704
Have my doubts as this got fixed already.

**Comment by Zugross** [comment]
@Tensuko #704 is the same. But now in 7.0.0.25 you see the behavior in the Video
![grafik](https://user-images.githubusercontent.com/90310863/151865335-2704351e-dc30-4c17-a5e4-4facea72d711.png)

**Comment by Tensuko** [comment]
Das logfile brauchen wir aber, mit debug an!

**Comment by Tensuko** [comment]
#804
