### ISSUE TITLE
[BUG_SP] Multitools : combines (x2) stop their course when they have to self-unload

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#804]
**Steps to reproduce**
1.ElmCreek map, field 36
2.Course generation : 1 headland, counterclockwise, centermode set to spiral
3. All combines have the self unload turned ON

**Actual behavior**
When the first combine reached 93%, it stops and so do the second combine following.

**Expected behavior**
First combine should try to unload to the closest auger wagon

**Screenshots**
![MultiTools-SelfUnload](https://user-images.githubusercontent.com/70093234/151870794-fdfab27a-d5d6-4a9a-817d-a17189016f47.png)

**Courseplay version**
Version used: 7.0.0.25

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7974171/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
NOVA330 with standard header
Mod : PongePack, RollandPack

**Relevant script mods**
ClickToSwitch, Tardis

**Comment by Tensuko** [comment]
log with debugs from the two combines would be helpful

**Comment by Lactic68** [comment]
Sure, here the debugs log attached
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7974316/log.txt)

The first combine miss one spot when entering the first row, see screenshots below : 
![MultiTools-MissASpot](https://user-images.githubusercontent.com/70093234/151874659-c1f5ac78-0c4e-4677-a0a1-e2a7e9c17e22.png)

![MultiTools-MissASpot-2](https://user-images.githubusercontent.com/70093234/151874684-ea2fc6ac-b213-45d8-8f3e-fd0055980125.png)

**Comment by pvaiko** [comment]
Not sure we even want to support multiple combines working on the field with self unloading. Maybe later.

**Comment by Lactic68** [comment]
@pvaiko Thanks for your answer, good to know that self unload is not supported in multitool. May I add it in the translation tooltip of the self unload ?

Should I create a separate issue for the missing spot left by the first combine when entering first row in spiral mode ?

**Comment by pvaiko** [comment]
Sure, add it, good idea. You can create a separate issue for that spot, but I have to tell you it'll be low prio.

**Comment by Tensuko** [comment]
We decided to not support selfunload for multitool.
It got added as Info text in Version 7.0.0.26
