### ISSUE TITLE
[BUG_SP] CP stops when switching destination in AD

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#805]
Not sure if this is a CP issue, an AD issue, or both.

**Steps to reproduce**
Start a CP course, then switch a destination selection in AD

**Actual behavior**
CP stops the field work when you set a new destination in AD but not activating AD

**Expected behavior**
CP continues to do field work.

**Screenshots**

**Courseplay version**
Version used: .25

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7974305/log.txt)

**Map**
Map played on. Elegrant

**Vehicles/ implements involved**
New Halland T7.315 HD with TMC Cancela TJP 610 mulcher

**Relevant script mods**
AD

**Comment by Resandise** [comment]
I found this when one of my CP course was close to finishing, I was setting up AD to have it ready to activate to send my tractor to the next field when CP was finished.  The CP button in AD was not active, nor was AD.

**Comment by Resandise** [comment]
AD issue report: 
https://github.com/Stephan-S/FS22_AutoDrive/issues/310

**Comment by Tensuko** [comment]
AD Issue, not CP
