### ISSUE TITLE
Has being able to choose whether to Start on Headlands or Up & Down Rows been removed in V25?[Question]

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#806]
Updated Courseplay today to the latest V25 release. Went into game and started playing as normal and noticed when I came to create some Field Work Courses for my Tractors to do things like Cultivating, Fertilising and Seeding the option in the Course Generator to choose whether to have them start on Headlands first or on the Up & Down Rows has disappeared from the menu.

<img width="1920" alt="2022-01-31 (2)" src="https://user-images.githubusercontent.com/13921716/151887641-ed5683a5-0209-4bf5-a729-70bfa8fa8133.png">

Now it seems like if you select to have any headlands Courseplay defaults to start working on headlands first before the Up & Down Rows and gives you no option to change this. Not sure about other users but typically for me if I do a course with Headlands the only time I'd ever work the headlands first, is when I'm combine harvesting. For all other field work tasks, I'd do the headlands last.

If the choice to do headlands first or last has been relocated to another menu or option somewhere else in Courseplay, can anyone point me to it now, as I've looked around this evening and can't find it?

**Comment by cwattyeso** [comment]
I also have now just noticed that handy option to be able to extend or decrease the field borders has also disappeared from the Course Generation screen, that I used quite a bit in the previous versions.

**Comment by Resandise** [comment]
You just need to scroll down more.


![fsScreen_2022_01_31_21_33_50](https://user-images.githubusercontent.com/96673100/151909265-7e0a70f3-431a-4298-a724-84f05d16b0b0.png)

**Comment by Tensuko** [comment]
Question answered.....

**Comment by cwattyeso** [comment]
Just tried it again today and unfortunately that screen does not scroll any further then in my screenshot for me. However I'm playing with a Controller and Wheel and not mouse and keyboard. So perhaps scrolling is just not working on either of those devices, which means I can't get to and see those options.
