### ISSUE TITLE
[Question] Course generation : centerMode_spiral : Must set headland to counterclockwise to make spiral go clockwise

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#813]
Hi,
When generating a course and using the Centermode Spiral the only way to make a clockwise spiral (to have the combine pipe to the left) with one or more headland is to set headland in counterclockwise. This is not really handy because in large fields we sometimes need to unload the combine.

Is there a way to set headland in clockwise and have the spiral go clockwise too ?
![SpiralMode](https://user-images.githubusercontent.com/70093234/151935868-57a735e8-1fc2-4a44-a090-3070e02b1d24.png)

**Comment by Tensuko** [comment]
CW/CCW is the Headland direction, not center.

**Comment by Lactic68** [comment]
@Tensuko Thank you for your anwser. But is there a way to define centerMode_spiral direction ? It seems that by default spiral direction is CCW.
