### ISSUE TITLE
[BUG_SP] endless driving backwards

### ISSUE THREAD

**Issue by MrsJessica92** [Courseplay/Courseplay_FS22#814]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
1. Ich hab ein Kurs auf dem Feld 40 Elmcreek generiert
2. Job gestartet für Big X Cargo (Mods siehe unten)
3. Ich weiß nicht ob relevant, aber ich hatte zwischen drin eine Pause gemacht (sprich Savegame neu geladen)
4. Job wieder aufgenommen 
5. Nach dem Vorgewende auf den Bahnen, fing er an Rückwärtszufahren und hörte damit nicht mehr auf (Wenden ging auch nach mehreren Versuchen nicht - Ergebnis war immer endless backwards driving)

**Actual behavior**
Nach dem Vorgewende auf den Bahnen, fing er an Rückwärtszufahren und hörte damit nicht mehr auf (Wenden ging auch nach mehreren Versuchen nicht - Ergebnis war immer endless backwards driving)

Anmerkung: Ich weiß nicht mehr welche Version, aber es hatte schon mal auch mit dem Mod-Häcksler richtig funktioniert. D.h. Es geht erst seit einem der letzten Updates nicht mehr

**Expected behavior**
Am Ende der Bahn wendet der Häcksler für die nächste.

**Screenshots**
Ich hab hier einen kleinen Clip gemacht, auch mit angeschalteten Debug: https://youtu.be/aSRaurs_P78

**Courseplay version**
Version used: 7.0.0.25

**Log**
[log_unlimited_backwars.txt](https://github.com/Courseplay/Courseplay_FS22/files/7978312/log_unlimited_backwars.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Mod Vehicle Big X Cargo: https://forbidden-mods.de/filebase/file/28091-ls22-krone-bigx-1180-gargo

**Relevant script mods**
Installiert sind: GPS, Autodrive und Enhanced Vehicles

**Comment by Tensuko** [comment]
Schöner bug report, sieht man leider selten :)

Das problem lässt sich am besten umgehen, indem du ein weiteres Vorgewende generierst, oder "Wenden auf dem Feld" deaktivierst (Schneidwerk wird wohl etwas über den Feldrand hinaus ragen). Berechnet wird der angezeigte Kurs so, dass er zum Wenden auf dem Feld ein kleines bisschen weiter rückwärts fahren muss, aber den Punkt erreicht er nicht, weil er schon dran vorbei ist.

Es wäre recht aufwendig das an zu passen, daher die 2 möglichkeiten, das zu umgehen.
