### ISSUE TITLE
[BUG_SP] Can't scroll to all options on Course Generator settings when using Controller or Wheel devices

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/Courseplay_FS22#817]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
When opening the Course Generator with a Controller or Mouse you can't scroll the screen down to access all the options. I did originally ask a question whether certain options had been removed in V25, and Tensuko replied you just needed to scroll down to find them. https://github.com/Courseplay/Courseplay_FS22/issues/806

Went back into game today and it's not possible to scroll down any further after you reach the option "Up Down Row Angle" it just cycles back to the top of the screen when you press down on the controller. It also doesn't matter if I have the Controller Friendly HUD option enabled or not, this doesn't appear to have any effect on the main menu options, just instead switches between whether you get the little mini-hud appear in game or the menu on the right hand side of the screen when you press the button for mini-hud.

**Actual behavior**
When navigating the Course Generator Menu with a Controller or Steering Wheel when trying to access options such as "Start Work On" and "Field Margin" you can't as when you press down on the controller or wheel from "Up/Down Row Angle" it just goes back to the top of the screen and highlights "Work Width". If you do have a mouse handy and can scroll the wheel you can access the options fine as Tensuko replied to my original question. However for those of us playing exclusively with Controllers or Wheels you can't scroll the page.

**Expected behavior**
I'd expect on the Course Generator Screen to continue to be able to scroll down and select/change all options using my controller or wheel and not have options excluded or hidden from me because the page doesn't change or scroll when navigating with a device that is not a mouse. In Previous Versions of Courseplay this menu worked fine, so this must be a new bug that has crept into V25

**Screenshots**
<img width="1920" alt="2022-01-31 (2)" src="https://user-images.githubusercontent.com/13921716/151971712-b2ec92a3-aaae-4a9e-bcba-cd518bc79033.png">

**Courseplay version**
Version used: 25

**Relevant script mods**
Autodrive latest version installed and Guidance Steering latest dev version.

**Comment by Tensuko** [comment]
Just tested a fix and I was able to use my gamepad to scroll down, so it should be fixed in the next version.

**Comment by cwattyeso** [comment]
Thank You

**Comment by Tensuko** [comment]
Fixed in 7.0.0.26
I guess I forgot this in the changelog.....
