### ISSUE TITLE
[BUG_SP] Multitool course -Spiral and land mode : First combine miss a spot after first headland

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#818]
Steps to reproduce
1.ElmCreek map, field 36
2.Course generation : 1 headland, counterclockwise, centermode set to spiral
3. All combines have the self unload turned ON

Actual behavior
When first combine has finished first and only headland, one spot is missed when entering first row. It shift to its position (right) too late to properly cover the spot.

Expected behavior
Treat first row as an actual one, not a headland extension.

**Screenshots**
https://user-images.githubusercontent.com/70093234/151874659-c1f5ac78-0c4e-4677-a0a1-e2a7e9c17e22.png
https://user-images.githubusercontent.com/70093234/151874684-ea2fc6ac-b213-45d8-8f3e-fd0055980125.png

Courseplay version
Version used: 7.0.0.25

Log
https://github.com/Courseplay/Courseplay_FS22/files/7974316/log.txt

Map
Elmcreek

Vehicles/ implements involved
NOVA330 with standard header
Mod : PongePack, RollandPack

Relevant script mods
ClickToSwitch, Tardis

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by pull2play** [comment]
Same issue with lands, clockwise. Only managed to catch a part of this in the log, as I was playing a "normal" game, not troubleshooting.
![20220201172340_1](https://user-images.githubusercontent.com/24781572/152012553-db5aca0b-3c50-471a-a3c8-9ba252b3ced2.jpg)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7980306/log.txt)
.

**Comment by Tensuko** [comment]
That looks like no turn at all. hmm

**Comment by Tensuko** [comment]
Seems to be the missing connection track for the left and right offset lanes.
Should impact all center modes.

**Comment by Tensuko** [comment]
Missed this one, should be part of 7.0.1.15
