### ISSUE TITLE
Mini HUD removed?[Question]

### ISSUE THREAD

**Issue by Spyrootjuh** [Courseplay/Courseplay_FS22#823]
Hi All, tried to search for my issue, but my German is not that good (and I am a Dutch guy, sorry).
For a time I had a small HUD when using CP. In the bottom middle of the screen. 1 that was showing how many wapoints the CP course had, on which waypoint is was and a start/pause botton. But today I downloaded versen 7.0.25, and now it has been gone. Tried to install version 7.0.24 again, but it didn't come back. Hope you guys know which HUD I am talkin about and I hope it come back, it was (for me) very handy for pause/play all the time.

**Comment by Spyrootjuh** [comment]
After searching any further on the internet, I think I found on which update it was released: 7.0.0.17 (Set default keybinds for open mini hud and start/stop CP Driver). Let me try to install this version again.

**Comment by Tensuko** [comment]
It is not removed, check your options! Vehicle option, global option and it won't open with right click when AD Waypoint Editor is on.
