### ISSUE TITLE
LUA Fehler

### ISSUE THREAD

**Issue by Pioner912** [Courseplay/Courseplay_FS22#824]
Hallo zusammen, 

Meine Figur dreht sich nur noch und es kommen ohne Ende LUA Fehler 
Ich kann per Tab in ein anderes Fahrzeug wechseln das drehen hört auf sobald ich aussteige dreht sich wieder alles.

**Courseplay version**
Version used: 7.0.0.25

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7981615/log.txt)

**Map**
Frankreich

**Vehicles/ implements involved**
Ich weiß nicht welches da mehrere Fahrzeuge Aktiv sind 

BIG M (Onkel Jogi)  

Massey Ferisson 8s + Striegel TS1520 (original) 

Massey Ferisson 8s + Terrasem C6F (original) 

Fendt Black Beauty + Lemken Koralin 9 (original)  

Fendt 1050 (original) + Amazone Citan (Peterzimmi) https://www.modhoster.de/mods/citan-15001-c-multi-fruit#description

Mod's JA

**Relevant script mods**
Autodrive + Courseplay und GPS (GPS aber nicht verwendet)  

Video wo der Fehler zu sehen ist! 
https://youtu.be/fNxAx8_SrgY

**Comment by Tensuko** [comment]
Das Video ist nicht hilfreich....
Was hast du gemacht als der Error kam ist wichtig.

**Comment by Pioner912** [comment]
Ich saß einfach im Big M welchen ich mit Autodrive zum Feld geschickt habe wo er zur Feldarbeit eingeteilt war, und der dann vor einem Hindernis stand und nicht weiter konnte dann wollte ich nur aussteigen und mit Starker Bauer mal kurz ein bisschen von dem Hindernis weg heben aber dann kam der Fehler und nichts ging mehr. 

Irgendwann später war der Fehler einfach weg.

**Comment by Pioner912** [comment]
Selber Fehler anderes Fahrzeug Der oben erwähnte 8s mit Pöttinger Sammelwagen wurde als er voll war und zum Hofsilo gefahren ist von einem AUTO auf die Seite gelegt selber Fehler In das Fahrzeug gesprungen und und Autodrive deaktiviert, Fehler weg!

**Comment by pvaiko** [comment]
Die Fehlermeldung kommt aus dem Giants Code. Das ist kein CP Fehler.

**Comment by regs1980** [comment]
@Pioner912  du hast 133 zusätzlich Mod im Ordner und es soll genau CP oder AD sein, schon mal die Mods allein probiert ohne 100 andere, ob da der Fehler auch entsteht. 
Hatte ein ähnlichen Fehler, als ich noch den FS22_PlayerPositionSaver Mod benutzt hatte. 
Da war es egal ob CP, AD oder Ingame Helfer, sobald ich ausgestiegen bin aus dem Helfer gesteuerten Fahrzeug hat sich mein Avatar angefangen zu drehen.

**Comment by Tensuko** [comment]
Dann machen wir hier zu.
