### ISSUE TITLE
[BUG_SP] Mähen nur auf Ackergras mit Feldrandkurs

### ISSUE THREAD

**Issue by cpp** [Courseplay/Courseplay_FS22#826]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Feldrandkurs erstellen, der sowohl Wiese als auch Ackergras einschließt.
CP Kurs erstellen und Traktor mit Mähwerk fahren lassen.

**Actual behavior**
Es wird nur das Ackergras gemäht, das Wiesengras wird stehen gelassen.

**Expected behavior**
Sowohl Wiesengras als auch Ackergras sollten gemäht werden.

**Screenshots**
![2022-02-01 23_12_23-Farming Simulator 22](https://user-images.githubusercontent.com/591443/152060857-f4e434ae-340d-40ad-bd2d-a57244ea1ad3.png)
![2022-02-01 23_25_37-Farming Simulator 22](https://user-images.githubusercontent.com/591443/152061879-614aeec7-7476-4b37-9175-3d396ccf5873.png)

Das erste Vorgewende wurde von Hand gemäht

**Courseplay version**
Version used:  7.0.0.25

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7982327/log.txt)

**Map**
Haut Beyleron

**Vehicles/ implements involved**
Fendt 724 Vario
Pöttinger Novavat A10 Cross Flow
Pöttinger Novacat 301 AM ED Pro

**Relevant script mods**

**Comment by Tensuko** [comment]
Das kommt von GIANTS.
Der normale Helfer kann das auch nicht abmähen.

**Comment by cpp** [comment]
Alles klar, das ist schade. Vielleicht gibt es ja irgendwann eine Lösung oder einen Fix von Giants.

**Comment by Tensuko** [comment]
Info/Notiz für das Issue:
- Der Helfer braucht immer Feld unter dem Gras
- Designentscheidung, da der Helfer keinen Feldrand mähen soll
- Da wir auf Kursen fahren ist es egal
- Zum ausschalten clearAITerrainDefailRequiredRange bei Mowern aufrufen.

**Comment by nobi9911** [comment]
Habe das Problem auf der Niemandsland auch immer.
Wie geht das mit dem ausschalten "Zum ausschalten clearAITerrainDefailRequiredRange bei Mowern aufrufen."

**Comment by Tensuko** [comment]
Für User gar nicht!
Das ist nur eine Notiz für uns (courseplay dev).

**Comment by Tensuko** [comment]
Should work now in 7.0.0.27
