### ISSUE TITLE
[BUG_SP] Courseplay not recognizing custom field for bale wrapping.

### ISSUE THREAD

**Issue by Mr-Anivex** [Courseplay/Courseplay_FS22#829]
I drew a custom field using the new recording feature. I used a couple tools in the field to mow/bale and everything went smoothly.

When it came time to wrap the bales, I leased the Kuhn SW 4014 and attached it to my tractor and pulled into the field a good bit, like I had seen someone else do successfully on youtube earlier.
I opened up the HUD and switched my starting waypoint to "collecting/wrapping bales", and started up courseplay. 

Nothing happens, and I get a message "AI worker (letter) has stopped work unexpectedly - no field found!"
I've also tried selecting the field using the marker like I would when i was going to generate a course, and I've tried actually generating a course first with "collecting/wrapping bales", but neither of these methods worked either, for the same reason according to the message produced.

I am currently using .25

My log and cpFields files are located [here](https://gist.github.com/Mr-Anivex/7aa5850ff12fb8c0cc79e6742e23d725).

The map is Erlengrat, Custom field I am trying to use is CP-2. I have Auto-Drive installed as well, though I'm not trying to use it in any fashion during this issue.

Just let me know if you need any more information, or if perhaps I'm just doing something wrong.

**Comment by Tensuko** [comment]
No bug, duplicate #532

**Comment by Mr-Anivex** [comment]
Okay, but the issue isn't solved there either? 

Also, their issue is different it seems. They are trying to use it on an open meadow...my issue is on a plowed field. 

I'm just not seeing where it isn't a bug.
