### ISSUE TITLE
[BUG_SP] Planter won't use fertilizer from tractor mounted tanks

### ISSUE THREAD

**Issue by cgfriberg** [Courseplay/Courseplay_FS22#830]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Use mods listed below to plant with liquid fertilizer

**Actual behavior**
CP worker runs until planter fertilizer tank is empty but tractor mounted fertilizer tanks are full

**Expected behavior**
CP worker runs until either seed or fertilizer is completely empty.

**Screenshots**
![Screenshot (36)](https://user-images.githubusercontent.com/98858610/152085077-4fae3489-78c5-4537-84cb-69705acedb96.png)

**Courseplay version**
Version used: 7.0.0.25

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Deer Creek

**Vehicles/ implements involved**
Which vehicle or implement?
John Deere 8RX by Siid Modding
John Deere Exact Rate Tanks by Siid Modding
John Deere 1775NT by JHHG
Mod: yes

**Relevant script mods**
Autodrive is installed but not active

**Comment by cgfriberg** [comment]
If operating manually, fertilizer pulls out of all tanks as expected.

**Comment by Tensuko** [comment]
Same as #614
