### ISSUE TITLE
Mouse Screen Issue

### ISSUE THREAD

**Issue by frankrexdale** [Courseplay/Courseplay_FS22#831]
I have finally figured out what was causing my mouse freezing up during game play. Its caused by the mini hub is still active even after the hub is closed.  Hopefully this video will explain the issue. Watch mini hub and log file even after I close the hub it's still active. This become issue when hub is closed and you click on action button without knowing. 

 https://youtu.be/vCWreRZgAWU

**Comment by Tensuko** [comment]
no logfile no template
