### ISSUE TITLE
Map issue or CP ?[Question]

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/Courseplay_FS22#833]
Hello guys. Started to play on first playable 4x map French plains. (https://www.kingmods.net/en/fs22/mods/la-plaine-francaise) But CP course manager wont start. When clicking on create course it will just bind click to map, Enter key just making noise but also not creating course. I tried owned field, and also contract field, and new option with creating boundaries, combinations of tractors with implements and also combine harvesters. I'm playing on other maps too and I know CP is working great, so I guess map must be somehow prepared for using CP?  Normal helper is working ok.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7984956/log.txt)

**Comment by Tensuko** [comment]
Few Screenshots of the Field and your position might help.

**Comment by pvaiko** [comment]
This looks like a map issue, most likely fields are too close to each other.

**Comment by Misamangame** [comment]
@Tensuko I did testing on fields 153 & 154 owned and 158 contract work.  But I think @pvaiko is right about fields beiing close to each other. Just did testing on field 167 which doesn't have any other field close by and all is working normally. 
Sorry I did not thought about that before, closing it now
