### ISSUE TITLE
[BUG_SP] Articulated vehicles - erratic turn behaviour

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#838]
**Steps to reproduce**
Create any course and use an articulated tractor. In this particular example - racetrack with two headlands, clockwise, 25% overlap, -2 field, starting in centre, pathfinder initially off, later on, turns on field off, avoid fruit off

**Actual behavior**
Articulated tractors overshoot turns, display erratic snaking behaviour when trying to readjust and capture the path. Effect is more severe with wider implements. May lead to jackknifing and tipping. 

**Expected behavior**
Turns properly executed at correct speed, without an oscillating snaking behaviour.

**Screenshots**
![20220202135543_1](https://user-images.githubusercontent.com/24781572/152161486-2698951d-b6de-4b4e-9c52-3fa3b475e292.jpg)

![20220202135550_1](https://user-images.githubusercontent.com/24781572/152161521-f34761a5-6d5d-4c31-9407-0b586bba5cf8.jpg)
![20220202135553_1](https://user-images.githubusercontent.com/24781572/152161537-fbbe49fa-0b97-4396-a64d-dc928a8f1365.jpg)

![20220202135721_1](https://user-images.githubusercontent.com/24781572/152161572-c5ca3bcc-323c-4182-ac1e-203a30a65023.jpg)
![20220202135730_1](https://user-images.githubusercontent.com/24781572/152161603-6b0af64f-f57a-4cc5-b304-0e91e7841c85.jpg)

![20220202135923_1](https://user-images.githubusercontent.com/24781572/152161668-e4b70fad-fe49-4b3a-ab6e-dcc957e8b9bc.jpg)

![20220202141133_1](https://user-images.githubusercontent.com/24781572/152161709-00ecfde5-59db-4bcc-a70f-0a2bc722f9df.jpg)

**Courseplay version**
Version used: 

.25

For help with the debug channels,
please check out the readme at the github front page.

**Map**
Elmcreed, field 39

**Vehicles/ implements involved**
Any articulated tractor with an implement. No mods.

**Relevant script mods**
N/A
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7986755/log.txt)

**Comment by pull2play** [comment]
Not sure what you changed, but... 🤣 

Too late in the date for a proper debug, I'll get on it tomorrow if you want :)

![20220203004546_1](https://user-images.githubusercontent.com/24781572/152256824-89e778ad-1190-4a53-900c-a1060f63de66.jpg)
![20220203004553_1](https://user-images.githubusercontent.com/24781572/152256833-54de0630-aaed-45a3-83f6-b674a79f4f36.jpg)

**Comment by Gibbanator** [comment]
waiting to do a proper debug is always the best way to get things properly looked at.
    On Wednesday, February 2, 2022, 06:48:22 PM EST, pull2play ***@***.***> wrote:  
 
 


Not sure what you changed, but... 🤣
 
Too late in the date for a proper debug, I'll get on it tomorrow if you want :)




—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pvaiko** [comment]
Not sure what you are doing, not sure what version you are running but if you don't turn on all possible debugs and show a video what your problem is, we'll never fix this...

**Comment by pull2play** [comment]
> Not sure what you are doing, not sure what version you are running but if you don't turn on all possible debugs and show a video what your problem is, we'll never fix this...

The latest commit that referenced my issue. My apologies for not including a proper bug report this time, was just having a lighthearted laugh. I'll refrain from such humour in the future.

Unfortunately I have no way to record a video at the moment, but I did do a quick up/down course on the same field as before. Debug and screens included.
![20220203012208_1](https://user-images.githubusercontent.com/24781572/152261142-107cc5f4-23c1-4c84-9a90-32a2c959da18.jpg)

![20220203012215_1](https://user-images.githubusercontent.com/24781572/152261167-6c41335d-5092-47d9-a139-38d62ff1a602.jpg)
![20220203012348_1](https://user-images.githubusercontent.com/24781572/152261182-108acb78-43e0-4d28-9501-2abe992d9133.jpg)
![20220203012708_1](https://user-images.githubusercontent.com/24781572/152261212-a29aa2b5-d1fa-47ff-a926-747ae2c24aa9.jpg)
![20220203013009_1](https://user-images.githubusercontent.com/24781572/152261242-604881a0-dcea-4d11-a562-1d47dfcf6037.jpg)

Please note that the issues here are now purely visual. The tractor does eventually complete the course with only some usual bits missing.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7990938/log.txt)

**Comment by pvaiko** [comment]
What is your turn speed setting?

**Comment by pull2play** [comment]
> What is your turn speed setting?

Everything is default (8km/h), as set by CP and by FS22. I only changed tool raising and lowering. I created a fresh save specifically to test this issue.

![20220203020917_1](https://user-images.githubusercontent.com/24781572/152264433-27d3d7b4-c5e9-4fd8-ac7d-3d4831dfa7ec.jpg)
![20220203020925_1](https://user-images.githubusercontent.com/24781572/152264462-38b9b6e9-d159-4f79-ba0e-448e436fec9e.jpg)

![20220203020929_1](https://user-images.githubusercontent.com/24781572/152264468-7cb7d8ec-f37e-40ef-98ab-56a46f4ec4f1.jpg)

**Comment by TJCares1966** [comment]
You need to skip a row.  Everything you have is big so it can't make the turn. Skip a row and see how much better it is.

**Comment by pull2play** [comment]
> You need to skip a row. Everything you have is big so it can't make the turn. Skip a row and see how much better it is.

Oh, that simple, huh? :)

![20220203104718_1](https://user-images.githubusercontent.com/24781572/152318982-8742cc8d-b408-4184-a44c-73671d6686a8.jpg)

The problem isn't in overall length or size, but in how CP handles articulated tractors. CP will have no problem turning the Fendt 1050 with a much wider and longer implement (there's a mod Seed Hawk out there). The initial bug report was made on a racetrack course. You can't give a tractor more room to manoeuvre than that. Hopefully this can be tuned, it would be a bummer if all the large tractors were - although usable - visually unappealing.

**Comment by Tensuko** [comment]
> Oh, that simple, huh? :)

Did you try it ?

**Comment by pull2play** [comment]
> > Oh, that simple, huh? :)
> 
> Did you try it ?

Of course. The screenshot is the result.

**Comment by pvaiko** [comment]
What happens here is that CP is trying to keep the *implement* on the track, so widens the turn for the tractor. If you turn on the AI Driver debug channel you'll see the "tight turn" offset in the log. For a combination of longer implements and small turn radius (typical for articulated vehicles) this offset can be very big (the tractor driving on a much bigger radius than the implement).

The shorter look ahead distance we use for the pure pursuit controller in turns further amplifies this effect. Let me see what we can do.

**Comment by pull2play** [comment]
> What happens here is that CP is trying to keep the _implement_ on the track, so widens the turn for the tractor. If you turn on the AI Driver debug channel you'll see the "tight turn" offset in the log. For a combination of longer implements and small turn radius (typical for articulated vehicles) this offset can be very big (the tractor driving on a much bigger radius than the implement).
> 
> The shorter look ahead distance we use for the pure pursuit controller in turns further amplifies this effect. Let me see what we can do.

I wouldn't know the first thing about scripting, so I'm glad you know what's going on :) I did a quick test with a tracked vehicle on the same course though, and it failed to successfully complete a turn at all. I assume this confirms your theory.

https://youtu.be/AzJ5RqrPE_8 (tight turn failed)
https://youtu.be/VEiTLy3XSAw (row skip turned failed)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7994352/log.txt)

**Comment by pvaiko** [comment]
Thanks, videos help a lot. Implements can have a configured minimum turn radius (`turnRadiusLimitation`) and many do, which CP takes into consideration, but these you are trying here, they don't have such a limitation.

**Comment by pull2play** [comment]
> Thanks, videos help a lot. Implements can have a configured minimum turn radius (`turnRadiusLimitation`) and many do, which CP takes into consideration, but these you are trying here, they don't have such a limitation.

They do work fine with non-articulated and non-tracked tractors though. I checked them all with the Fendt 1050, no issues.

**Comment by Tensuko** [comment]
#832

**Comment by pvaiko** [comment]
> They do work fine with non-articulated and non-tracked tractors though.

Because they have a higher turning radius, usually over 5 meters. Some of these tracked ones have 2.3 m.

**Comment by SilverWheelz** [comment]
> Because they have a higher turning radius, usually over 5 meters. Some of these tracked ones have 2.3 m.

Yes, the turns need to be smoother for tracked tractors since they can reach the max rotation in a dime. But, I've also noticed that both tracked and articulating tractors start the turn too late. This causes them to overshoot the turn and they end up reaching the max rotation since CP makes them stay at the max steering angle longer to correct/center the tractor back with the line. Despite the correction, CP still fails to center the tractor because it still turns too late and it overshoots again which causes the snaking behavior. If I'm not mistaken articulated tractors actually anticipate/start the turn early in CP19 which maybe could be used here as well?

https://streamable.com/yg03oe
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7995410/log.txt)

**Comment by pull2play** [comment]
Testing your recent changes, only one run so far, but it seems much better, other than the annoying snaking oscillation. Alas, Rome wasn't built in a day, certainly a massive improvement.

Course is racetrack, 2 headlands, 25% overlap, -2 field.

First tight turn (up/down): https://youtu.be/QNOjjMGwECw
First wide turn: https://www.youtube.com/watch?v=BvegsI0dfzs
Second wide turn: https://youtu.be/zcZYXi-u5Ws
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7997826/log.txt)

**Comment by pvaiko** [comment]
Just out of curiosity, when you run the built in helper with the same rig, is it using a bigger turn radius?

**Comment by pull2play** [comment]
I would say that on this particular course and in this specific configuration, it's almost perfect. Not much more you could do, really. 

Tight up/down turn: https://youtu.be/big_lFjFJmg
Wide turn with long transition: https://youtu.be/o5Z6xl_vVcE

Now to test it on my main save, and to see if this didn't affect something else :)

Thank you.

**Comment by pull2play** [comment]
It seems there are still some lingering issues with mods, although as this is not an official GIANTS modhub mod, I leave it up to you if you think it is worthwhile investigating.

https://youtu.be/t0-CV3W_S_s
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8008361/log.txt)

**Comment by pvaiko** [comment]
This does not look like Courseplay is screwing up, qe are in the middle of course, our pure pursuit controller is pretty reliably can drive a course, there's nothing special where it is going off to the right, I'm not ruling a CP issue out just saying it is very unlikely.

**Comment by pull2play** [comment]
> This does not look like Courseplay is screwing up, qe are in the middle of course, our pure pursuit controller is pretty reliably can drive a course, there's nothing special where it is going off to the right, I'm not ruling a CP issue out just saying it is very unlikely.

Ok, thanks. Still, weird that it would suddenly generate a 180 degree turn in the middle of that transition - it veers off to the right trying to turn around for some reason - at least that's how I understand it from the numbers. I guess that's what we get for playing with non-modhub mods :) I did recreate this course with two headlands, and when starting at the headland it was completed perfectly without any issues, so you're probably right that it's a mod issue.
