### ISSUE TITLE
[BUG_SP] Savegame not loading (85%, latest version .25)

### ISSUE THREAD

**Issue by magicd1982** [Courseplay/Courseplay_FS22#839]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Deactivate / Activate Courseplay

**Actual behavior**
Savegame could not load (85%)

**Expected behavior**
Savegame will load.

**Screenshots**
-

**Courseplay version**
Version used: 7.0.0.25

**Log**
2022-02-02 15:16 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/magic_d/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/gui/CoursePlot.lua:58: attempt to index a nil value

**Map**
Haut Beyeleron

**Vehicles/ implements involved**
-

**Relevant script mods**
Autodrive, VCA

**Comment by RealNeo80** [comment]
have you updated from 7.0.0.24 to release 7.0.0.25 or have u used the latest branch?
