### ISSUE TITLE
Video von Mario Hirschfeld[Question]

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/Courseplay_FS22#840]
Hallo,
ich habe ei Video von Mario Hirschfeld gesehen das CP und AD im 22 Schon wieder zusammenarbeiten wie so geht das bei mir nicht ?
Ach so ich benutze die neusten Versinonen von AD und CP die auf Github zu haben sind
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7987909/log.txt)
.

**Comment by hermannbrauer** [comment]
sicher das dein AD geladen wird???

"Error: Invalid mod name 'FS22_AutoDrive2.0.0.4'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit"

Grundsätzlich läuft das bei AD und CP :)

**Comment by hermannbrauer** [comment]
Schau dir mal das Video von Iwan1803 an...
https://youtu.be/jz1u4Weg2XY?t=559
der erklärt wie es laufen soll... 

teste sonst bitte mit einem sauberen Savegame CP/AD only >> wenn das läuft hängt es an einem anderen Mod

**Comment by Tensuko** [comment]
> wie so geht das bei mir nicht ?

Weis ich nicht ?



> Beide progamme Laufen aber nicht zusammen wenn Ad nich geladen wir kann es tosdem laufen ?

Siehe Video ?

Sry aber ein bisschen selber suchen wäre heir angebracht, closed!

**Comment by hermannbrauer** [comment]
Iwan hat bei AD geantwortet.. 

Hier hatte der User die 2.0.0.4 von AD umbenannt so das diese nicht aktiviert werden konnte und somit die 2.0.0.3 noch aktiv war, siehe auch den Log
