### ISSUE TITLE
The mod cannot be uploaded to the dedicated server

### ISSUE THREAD

**Issue by Barricade81** [Courseplay/Courseplay_FS22#841]
When I try to upload the mod to my server I get the following error message: The uploaded file is corrupt

![grafik](https://user-images.githubusercontent.com/98908411/152212020-70185805-1284-4ca7-a006-0dcd009d8942.png)

I can't create a course generation in the single player either
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7989031/log.txt)

Can anyone help me pls.

**Comment by Tensuko** [comment]
Oh man.... 1000 Issues immer das gleiche, warum schreiben wir überhaupt etwas unten in die Readme....

Note that the current version has no multiplayer support!

**Comment by Barricade81** [comment]
Ok das hab ich überlesen, aber dennoch gibt es ja auch ein Problem im Singleplayer. 
Ok, I overlooked that, but there is still a problem in single player.

**Comment by Barricade81** [comment]
Ich hatte unter meinen Screenshot geschrieben dass sich im Singleplayer kein Kurs generieren lässt und habe die log Datei dran gehängt

**Comment by Tensuko** [comment]
Das kann diverse Gründe haben.
Unter anderem, dass du viele LUA Errors in der log hast.
Ansonsten -> Tutorial angucken.

**Comment by Barricade81** [comment]
Ok, danke dir. Dann werde ich mal schauen welcher Mod die Fehler verursacht und hoffentlich beheben. Schönen Abend dir noch
