### ISSUE TITLE
[Feature] Farbiger Kurs / Wegpunkte

### ISSUE THREAD

**Issue by Sacred-Shadow** [Courseplay/Courseplay_FS22#842]
Wer kennt es nicht ... das Saatgut ist alle ... die Maschine stoppt und man muss erstmal nachtanken. 
Zurück auf dem Feld hat man nun das Problem, dass man erstmal schauen muss, wo man weitermachen muss.

Hier wäre es cool, wenn sich die bereits erledigten Wegpunkte o. Strecken anders einfärben würden.

Damit könnte man dann leichter sehen, wo man schon war und wieder ansetzen muss.

**Comment by RealNeo80** [comment]
du brauchst doch nur im Hud letzter Wegpunkt auswählen, dann fährt CP selber dahin wo es aufgehört hat

**Comment by Tensuko** [comment]
So ist es, closed.
