### ISSUE TITLE
[BUG_SP] disable convoy distance on pathfinder turn

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/Courseplay_FS22#843]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Course with large headland turn (6lands@14mX2tools)

**Actual behavior**
Lead vehicles stops during turn, waiting for trailing vehicle,to close distance. 
trailing vehicle waits for lead to finish turn

**Expected behavior**
lead finishes turn, drives onward on course, then trailing turns. after trailing finished turn, reestablish convoy spacing.

OR

trailing vehicle does not wait for leaad to finish turn, thereby not causing lead to wait.

**Screenshots**
![image_2022-02-02_213248](https://user-images.githubusercontent.com/9157835/152232726-4ed13bfa-dbca-4e43-a2c8-a9e3aac4b72a.png)

https://youtu.be/3-UPZQDExHs

**Courseplay version**
Version used: 7.0.0.25

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7989922/log.txt)
try on video starts at line 3494

**Map**
WildWest FS22

**Vehicles/ implements involved**
Lexion 8900&JDX9
Mod yes/no ?
JD yes
**Relevant script mods**
Autodrive, VCA and a few other active

**Comment by pull2play** [comment]
I am generally of the opinion that only minimum distance should be enforced. Having the leader constantly slow down for the follower(s) isn't workflow efficient. I assume that the reason we have maximum distance is for collision avoidance? I quit playing FS19 long before CP was fully fleshed out, but I do seem to recall that there was no maximum distance enforcement there, or at least not in the initial stages.

**Comment by Eldron81** [comment]
Depends: If the multitool function is enhanced to several tools behind each other (e.g. combine, baler, bale collector), the max distance becomes important. Otherwise most involved tools end up rotating on the bales ;).

**Comment by Tensuko** [comment]
Max Distance is needed, if you want it to go further away, increase it on the leading vehicle.
If you look back in FS19 and had overtaking vehicles, you will know why we did it like that.

**Comment by pull2play** [comment]
> Max Distance is needed, if you want it to go further away, increase it on the leading vehicle. If you look back in FS19 and had overtaking vehicles, you will know why we did it like that.

That is fair enough, and understandable. In that case, as per the original poster's suggestion, can we at least try to figure out some way to reduce the time a worker is held up while others are transitioning from one row to another? On larger fields, especially with lands or racetrack, this causes significant delays.

**Comment by JDTiger** [comment]
I don't know how the distance calculation works, but if possible i'd say the best solution would be to not stop the trailing vehicle before the turn and just let it keep the distance during the turn.

That way we don't cause dealys and avoid the overtaking problem.

**Comment by Tensuko** [comment]
Read the updated Issue Headline guys...

**Comment by Tensuko** [comment]
Da überlegen wir uns noch was.

**Comment by Tensuko** [comment]
Part of 7.0.1.3 (soon)
