### ISSUE TITLE
CP und AD Güllefass auffüllen

### ISSUE THREAD

**Issue by IROKILLER** [Courseplay/Courseplay_FS22#844]
Guten Tag Miteinander

habe da mal eine frage und zwar ich wollte via CP Güllefass auf Feld fahren lassen und dann mit AD via Feldrandcontainer wieder auffüllen lassen. Ist das bisher so möglich da der CP weiter arbeiten tut trotz leeren Güllefass. 

Samson PG ll 35 und Samson SD 700 ( Güllefass mit 7m Grubber )

**Comment by Tensuko** [comment]
Nein, das wird über AD gelöst.
Du kanns auch mit AD zu einem Feldrandcontainer fahren, musst nur den Kurs dafür haben.
Glaub da hat sich (bis auf wie CP für AD genutzt wird) nichts zu FS19 geändert.
Schau mal bei Mario Hirschfeld vorbei, was Tutorials angeht, vlt hat er auch schon das passende für FS22.

**Comment by IROKILLER** [comment]
Hab ich mir angeschaut. Habe nur das Problem das er trotz leeren güllefass weiter fahren tut solange er den grubber als aufsatz hinten mit dran hat mit schleppschlauch funktioniert das. Muss man da bezüglich CP was einstellen das er dann auch an AD übergibt ?

**Comment by Tensuko** [comment]
Nein bei CP wird nichts mehr eingestellt dafür.
Vlt geht die neue Version jetzt besser.
