### ISSUE TITLE
[Feature] Abfahrfüllstand anpassbar

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#845]
Derzeit wird immer genau bei 95% abgefahren, was aber nicht immer sinnvoll ist. ZB wenn die Kapazitäten der Abfahrer am Feldrand nicht recht damit zusammenpassen, oder der Ladewagen nur einen Teil des Grases aufsammeln soll weil der Rest zB zu Heu oder Ballen gemacht werden soll, etc. Hilfreich wäre es daher, wenn man den Abfahrfüllstand wieder selbst einstellen kann. Reicht grundsätzlich bei den Fahrzeugeinstellungen im ESC-Menü, nur muss man dort halt entweder ewig klicken, oder kann nur grobe Werte (zB alle 5%) einstellen.

In jedem Fall wäre zusätzlich auch ein einfacher Button im HUD (zB als Doppelpfeil) sinnvoll, mit dem der Spieler auch in bestimmten Situationen unabhängig vom tatsächlichen Füllstand das Fahrzeug vorzeitig zum Entladen schicken kann - also wie das "Sofort abfahren" im LS19. Einstellung und Button wären nützlich für das Drescher selbst abtanken, Ladewagen, und den zukünftigen ULW. Eventuell sogar den zukünftigen Schaufelmodus. Und würde wohl sogar bei Düngerstreuern/Sämaschinen Sinn machen - hier dann halt zum vorzeitigen Nachschub holen.

**Comment by Tensuko** [comment]
Ewig klicken musst du kaum noch, kannst auch auf die Felder klicken.
Weitere Buttons im HUD wird es NICHT geben.

**Comment by rohne83** [comment]
Dann irgendwo anders. Auf jeden Fall brauchts spätestens mit dem ULW ne Möglichkeit den vorzeitig wegfahren lassen zu können.

**Comment by Tensuko** [comment]
Das werden wir anders lösen, abwarten.
