### ISSUE TITLE
[Feature] Version Number 

### ISSUE THREAD

**Issue by yann-mrt** [Courseplay/Courseplay_FS22#848]
Good day to all,
It could be nice to have the version number appear somewhere, like in mini-hub for example, to keep track with all the version that are coming. like that when making screen shot we can see right the way what version is been used.
Thanks for your time and good job.
Yann

**Comment by yann-mrt** [comment]
Yes I agree with you, when it is bug related. 
But when it is to help someone how to do ..., in discord for example that sharing screen or sending screen shot, we can see right the way if they are with the last version. could be small letter to don't take lot of space or on the first setting page.

**Comment by Tensuko** [comment]
Will think about it.
