### ISSUE TITLE
[Feature] Stop driver if fuel is (very) low

### ISSUE THREAD

**Issue by throsten** [Courseplay/Courseplay_FS22#858]
**What is the problem this feature/enhancement solves?**
Maybe I did not found the right setup buttons, then execuse me. 
CP Driver do not stop if fuel is empty after start working. Only if you stop him manually you can't start him again.  

**Describe the solution you'd like**
It would be great if the driver stops working by himself if fuel is at i.e. 1% level. Then you have enough fuel to drive to the next fuel station. It also solves the "bug" that the driver finish a complete field even with an empty tank. 

Alternatively use AD to drive automatically for refueling and continue field work afterwards.

**Comment by Tensuko** [comment]
#140
That is still a general topic for us to do.
