### ISSUE TITLE
[Feature] Button for Fertilizing or not for seeding Machines

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#865]
**What is the problem this feature/enhancement solves?**
long way to change the fertilizing function over the standard menue

**Describe the solution you'd like**
a butten in the HUD to set Fertilizing on/off

**Additional context**
if i use oil radish as covercrop for some fields, or if i do missions i switch the fertilizing off, if i seed normal products after the cover fruit i switch it on. If you now "hopping" between these Field Operations its annoying to got over the standard-Menu to change the fertilizing option

**Comment by Tensuko** [comment]
No more Buttons for HUD.

**Comment by 0scarZulu** [comment]
No more buttons for the hud, ok. But then give us the possibility to do that via shortcut.
