### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Holzotte** [Courseplay/Courseplay_FS22#866]
Hallo Tensuko & Team,

Erstmal einen Riesen großen Dank für eure Arbeit. Ihr und das Team von AD macht mit eurer Arbeit dieses Spiel soviel besser.

Ich habe mal eine Frage, wird es in Zukunft möglich sein, das wenn man einen Kurs generiert hat und ihn abspeichert, das man im nachhinein den Kurs  noch bearbeiten kann bzgl. Arbeitsbreite, 1 o. X Fahrzeuge auf Kurs. Im moment muss man ja für jede Arbeit einen eigenen Kurs abspeichern.

**Comment by RealNeo80** [comment]
Du musst pro Arbeitsbreite einen Kurs haben, da ja die Vorgewende und Turns an die AB angepasst werden. Daher würde er eh einen neuen Kurs generieren. So einmal mit der AB abgespeichert und gut is

**Comment by Tensuko** [comment]
Richtig.
