### ISSUE TITLE
[Question] courseplay can no longer be started with v7.0.0.26

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#867]
Hey, I updated to the latest Version of Courseplay (7.0.0.26). But now I can't start Courseplay with CTRL + H or by clicking on the play button in the HUD. Do you have the same issue?

**Comment by alexx2104** [comment]
Tried to restore 7.0.0.25: Everything is fine.

**Comment by Tensuko** [comment]
Why not make an Issue with bug and fill in the template ?
Like this no one can help you!
