### ISSUE TITLE
[Question] Loading wagon only up to 95%

### ISSUE THREAD

**Issue by alexx2104** [Courseplay/Courseplay_FS22#868]
Loading wagon "Strautmann CFS 530 DO" is only filled up to 95% with gras. Have I set something wrong or is it a bug?

**Comment by Tensuko** [comment]
Not set wrong and not a bug, its fixed value!

**Comment by alexx2104** [comment]
I have found the problem: With the update to the 7.0.0.26 all active courses are deleted from the devices. Sorry, rookie mistake :)
