### ISSUE TITLE
Error with combinecourse on NML

### ISSUE THREAD

**Issue by rudshaag** [Courseplay/Courseplay_FS22#87]
I get a "bad argument" error while having courseplay running my combine harvester, nothing else running. I attach the log which shows this error. When console shows these errors I am unable to save the game, and when I exit the map/save menu the game freezes. This is with the Nova330 combine and Varifeed 28FT header.
[log.pdf](https://github.com/Courseplay/Courseplay_FS22/files/7775961/log.pdf)

**Comment by pvaiko** [comment]
update to the latest version, reopen if problem still exists

**Comment by rudshaag** [comment]
I first had the issue on 7.0.0.3, then went back to .1 as I thought I didn't have issues there, but it presisted in both versions.
