### ISSUE TITLE
[BUG_SP] CP not lifting baler Pickup on turns

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS22#877]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Create/run course with windrower, then attach a baler and re-run course.

**Actual behavior**
At the end of each up/down row, when turning to next row, CP does not lift the baler pickup.

**Expected behavior**
The baler pickup to be lifted when switching or making turns, excluding curves.

**Screenshots**

![fsScreen_2022_02_04_23_32_58](https://user-images.githubusercontent.com/96673100/152630188-356bbbb4-92c4-4ac5-8da7-7c9f04fd3ae1.png)

**Courseplay version**
Version used:  .25 and .26

**Log**

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8007449/log.txt)

**Map**
Map played on. Elmcreek

**Vehicles/ implements involved**
Claas Axion 920/ New Holland BigBaler 1290 High Density (Leased for Contract)

**Relevant script mods**
AD, but not used.

**Comment by Tensuko** [comment]
Duplicate #405
