### ISSUE TITLE
[BUG_SP] Pathfinder for drive to 1st or last waypoint

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/Courseplay_FS22#879]
**Steps to reproduce**
When you have a Field like in the picture. Entry Point and Start Point (or last Waypoint when using AD) are separated through an "edge" of the field. In the Edge there is a collidable fence. When starting course, it takes the shortcut (arrow in the picture) and collides with everything. Worst case would be a river, he would drive in it

**Actual behavior**
He takes the shortcut like discribed in "Steps to reproduce"

**Expected behavior**
He should drive along the field edge to the starting point (or last waypoint)

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/18227603/152632614-a4b639c4-b22f-4189-8173-1a53b45af51b.jpg)

**Courseplay version**
0.26

**Log**
[Log](https://pastebin.com/0kY5TrQv) 

**Map**
HB

**Vehicles/ implements involved**
Mods: With or without
Every Vehicle

**Relevant script mods**
AD and GPS, also tested without them.

**Comment by Tensuko** [comment]
Got implemented in 7.0.0.27

**Comment by Martin-L45** [comment]
The driver now follows the edge. But as the implement is unfolded when the driver starts driving towards the first point we need to make sure that the implement stays inside the field edge.
![Farming Simulator 22 Screenshot 2022 02 08 - 17 38 41 62](https://user-images.githubusercontent.com/85753728/153042595-fd373705-83d3-48a4-b43e-a42ee7c77348.png)
e
