### ISSUE TITLE
Anfahrt zum Feld

### ISSUE THREAD

**Issue by wusslerc** [Courseplay/Courseplay_FS22#880]
Hallo,
besteht die Möglichkeit, dass bei der Anfahrt zum Feld die Anbaugeräte geschlossen bleiben und erst beim erreichen des Feldes geöffnet werden?

**Comment by Tensuko** [comment]
Warum ist das wichtig ?

**Comment by wusslerc** [comment]
Weil wenn ich den Kurs starte z b die Walze aufklappen und ich dadurch nicht unbedingt bis zum Feld weiter fahren kannVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Tensuko ***@***.***> Datum: 05.02.22  09:31  (GMT+01:00) An: Courseplay/Courseplay_FS22 ***@***.***> Cc: wusslerc ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/Courseplay_FS22] Anfahrt zum Feld (Issue #880) 
Warum ist das wichtig ?

**Comment by Tensuko** [comment]
> Weil wenn ich den Kurs starte z b die Walze aufklappen und ich dadurch nicht unbedingt bis zum Feld weiter fahren kann

Was heist bis zum Feld, wenn du von sonst wo startest ist das ein ganzen anders Problem. Du solltest schon mit AD in die nähe fahren oder mit Giants in die nähe fahren....

Bleibt erst mal so, wir planen da eh noch was für, aber aktuell nicht.
