### ISSUE TITLE
Coursplay Hud lässt sich nicht mehr öfnen

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/Courseplay_FS22#882]
Hey ich habe ein Problem unzwar lässt sich das cp hud nicht mehr öffnen (auch nach Spiel neu starten und Cp deaktivieren und Aktivieren) nach dem sich Der 2 Drescher selbst entlassen hat weil der Vordere Drescher sich zum abtanken hingestellt hat und er Dadurch blockiert wurde  

ist jetzt schon das 2 mal passiert und das immer nach dem sich der Cp Helfer Selbst entlässt wenn er durch ein Objekt Blockiert wurde

![fsScreen_2022_02_05_13_03_05](https://user-images.githubusercontent.com/71101944/152641404-2ecec07a-84e5-4e8c-bc98-0aac0659262b.png)

Neuste Version 7.0.0.26

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8007977/log.txt)

NF Marsch 4 Fach

Benutze als Skript Mods CP AD GPS VCA

**Comment by Tensuko** [comment]
AD editiermodus an ? Sieht so aus. Dann ist es beabsichtigt, dass rechtsklick nicht mehr geht!
