### ISSUE TITLE
[BUG_SP] Multitool: Combine on right path overtakes combine on left path after game reload

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#883]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Created a Multitool course (2 combines). 2 headlands clockwise, afterwards fields. Restarting the cp drivers after they were stopped or the game was reloaded. 

**Actual behavior**
A clear and concise description of what happen.
After either restarting the game or restarting both cp drivers, the combine on the right path overtakes the combine on the left path. If I delete the course and create a new one it works, but again only until I reload the game or restart the cp drivers (for example after they crashed with the grain cart)

**Expected behavior**
The combine on the left course always stays in the front so the unloading augers are always pointing out to already harvested areas. 

**Screenshots**
![CED13139-2997-4619-BBBE-415CBA828BBB](https://user-images.githubusercontent.com/99053368/152648829-45d4afc5-078e-425a-a77b-59dbe459e22d.jpeg)

**Courseplay version**
Version used: 7.0.0.26

**Log**
https://gist.github.com/DemsMani/673f2aefac80d6ebca44f0fbcf34142a

**Map**
County Line

**Vehicles/ implements involved**
X9 (from ingame modhub) and C16F corn header (vanilla game)
Mod yes/no ?

**Relevant script mods**
AD and CP

**Comment by crazydunc** [comment]
Also getting this on Wild West 1.1, with 4x  X9s and the Lizard Durus 60ft Headers. Can provide Logfile and course if required. 

With 4 combines, they seem to completely disregard the convoy hierarchy. However, they do stop, if one Combine stops or whatever reason.

**Comment by Manyak007** [comment]
same problem 1 harvester is waiting for unloading and everyone is waiting

**Comment by DemsMani** [comment]
From my point of view the stopping is fully ok; but the distance doesn‘t seem to work properly. A bit of elasticity is of course great; but I had them drive in any order and sometimes even exactly beside each other even with 100m distance set.

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.27
