### ISSUE TITLE
[BUG_SP] offset tool calculated incorrectly.

### ISSUE THREAD

**Issue by kingslycamben** [Courseplay/Courseplay_FS22#886]
Steps to reproduce the behavior.
unia kormk xl 2.8 mod, use courseplay to mulch a field
**Actual behavior**
Courseplay doesn't reconise hte tool is offset so it incorrecting calculates its size.

**Expected behavior**
Courseplay should beable to leave 0 gaps between paths on fields with offset tools, it should beable to calculate correctly when the tool is offset

**Screenshots**
![image](https://user-images.githubusercontent.com/79064555/152659400-78281409-e59a-4b57-ab30-d6fe98195082.png)

**Courseplay version**
Version used: 7.0.0.26

**Map**
No mans land

**Vehicles/ implements involved**
Which vehicle or implement? unia kormk xl 2.8
unia kormk xl 2.8 mod

**Relevant script mods**
Autodrive.

Tried setting it manually and nothing changed when i recreated the course.

**Comment by kingslycamben** [comment]
Just found that i can do it manually.

**Comment by Tensuko** [comment]
Mod Issue.
Just adjust the offset by yourself.
Offset is NOT a course option, it is where he drives the course.
