### ISSUE TITLE
Suggestion: Let user shift gears when overseeing worker. 

### ISSUE THREAD

**Issue by talianagisan** [Courseplay/Courseplay_FS22#887]
I'm not sure if this is possible but my worker is revving the hell out of my tractor and probably wasting tons of fuel because he wont upshift. It'd be nice if i could manually get him to shift up. FS19 had this ability via VCA but I'm not sure how much control the ingame API gives you.

**Comment by Tensuko** [comment]
That is not a CP problem, that is Giants.
2 Options:
- Use another tractor.
- Set a lower working speed if you can't get your tractor into a matching gear.
