### ISSUE TITLE
[Feature] Allow larger negative field margin

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/Courseplay_FS22#888]
Using negative field margin is a great way to mow a band of grass around the perimeter of a field, but the -2 limit is a bit too small.  -- thanks for considering.

**Comment by Tensuko** [comment]
Increased to -5 in 7.0.0.27

**Comment by Pantax85** [comment]
Hi at all,

I have the same problem with the margin. The course is created always outside the field, no matter which equipment I use. This is very stupid, because now all my vehicles crash into trees at the field margin.

**Comment by rooymans** [comment]
You can fix this yourself by changing the below setting from -3 back to -0.2 or even 0.

![image](https://user-images.githubusercontent.com/56227140/152964628-46a52cdb-3606-48ab-b401-900950a8a434.png)
