### ISSUE TITLE
[BUG_SP] Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by piplarsson** [Courseplay/Courseplay_FS22#893]
**Actual behavior**
Hi. always get this error when the tractor is at the turning point of the course. (when it should turn to the course to the right)

**Screenshots**
![fsScreen_2022_02_06_13_52_19](https://user-images.githubusercontent.com/59544183/152682214-8cc754bb-9883-422f-b0c6-7f6d2d2b33f9.png)

**Courseplay version**
Version used: 7.0.0.26

**Log**
Error: Running LUA method 'update'.
dataS/scripts/utils/MathUtil.lua(207) : attempt to perform arithmetic on local 'x' (a nil value)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8010238/log.txt)

**Map**
DeerCreek v2

**Vehicles/ implements involved**
JD 8rt and Mod Ponge baletrailer 
Mod: yes

**Comment by Tensuko** [comment]
Should be fixed in 7.0.0.27
