### ISSUE TITLE
[Info] Course Generation 

### ISSUE THREAD

**Issue by watcher2312** [Courseplay/Courseplay_FS22#895]
Hey, i updated to version 7.0.0.26 and now i cant find the course generation at the job creation. I'm sure that i'm just too blind to find it :D
![image](https://user-images.githubusercontent.com/44786783/152683003-4761846d-e11c-4eca-9e96-23e980b463bf.png)

**Comment by Tensuko** [comment]
Feldmarker ist nicht auf dem Feld.

**Comment by watcher2312** [comment]
oh gott bin ich dumm, sry
