### ISSUE TITLE
Wo liegt der Fehler[Question]

### ISSUE THREAD

**Issue by gerohb** [Courseplay/Courseplay_FS22#896]
Hallo,
habe ein Problem mit CP. Wenn ich ins Spiel gehe bekomme ich die Fehlermeldung dass ich auf die Github Seite gehen soll um Hilfe zubekommen. Wenn ich OK-Button drücke Startet das Spiel. Im Spiel selber, werden die Reiter links für CP angezeigt, aber im Reiter Active Helfer/Job erstellen kann ich die Auswahl CP-Feldarbeit nicht einstellen. Somit auch keine Kursegenerierung machen. Habe die Aktuelle Version drauf von CP. Habe auch die aktuellen Versionen von AD und VCA. 
![fsScreen_2022_02_03_19_52_28](https://user-images.githubusercontent.com/97002086/152683574-0aeb8994-c5a6-4f3c-b3d0-ad40afb1e16f.png)
![fsScreen_2022_02_06_14_28_22](https://user-images.githubusercontent.com/97002086/152683580-8346b7a8-c983-41e2-a6de-558e1d07b156.png)
![fsScreen_2022_02_06_14_32_32](https://user-images.githubusercontent.com/97002086/152683592-f710d005-505b-4456-a3b4-a10cf949fc24.png)
![fsScreen_2022_02_06_14_33_58](https://user-images.githubusercontent.com/97002086/152683598-f1fca7b9-7fbc-427e-98fb-888b43bb6c00.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8010283/log.txt)

**Comment by RealNeo80** [comment]
du hast das schneidwerk net dran, dann erkennt der den nicht als "arbeitsmaschine"

**Comment by Tensuko** [comment]
Hast du das Feld überhaupt gelesen ? Ich glaube nicht. Lies noch mal richtig.

> das macht mich auch immer wieder narrisch

Ist aber richtig und gewollt.

**Comment by RealNeo80** [comment]
@Tensuko hab ja nix gegenteiliges behauptet, is bloß immer wieder ein AHA effekt wenn ich mich frage warum ich den Generator net einschalten kann

@gerohb deine Version is übrigens net aktuell

**Comment by gerohb** [comment]
Hab die 0.26 drauf. Muss mir nochmal die Videos anschauen. Die Mini Hub öffnet sich nicht, obwohl ich die eingestellte Tastenkombination betätige. Und Geräte zieren sich noch einbischen. Aber trotzdem **Danke** für die Unterstützung.

**Comment by RealNeo80** [comment]
GGF mal schaun ob sich die Tastenkombi net mit irgendwas überschneidet.
Es muss aber in den CP Fahrzeugeinstellungen Hud mit Maus aktivieren an sein, UND wen AD im Editmodus ist reagiert CP nicht auf die rechte maustaste, das kann auch ne Ursache sein.
Geräte ham sich net zu zieren, die solln machen was du anschaffst :p
