### ISSUE TITLE
[Feature] Suchfuntion im Coursemanager

### ISSUE THREAD

**Issue by CptRog** [Courseplay/Courseplay_FS22#897]
Könnt ihr bitte eine Suche in die Routenplanung implementieren 

Suchfunktion im Coursemanager, wo bei alle Order angezeigt werdenmit dem gesuchten inhalt um das Scrollen zu umgehen. 

Zum Beispiel bei der NF Marsch mit 79 Felder würde die Suchfunktion schon einiges erleichtern. 

Vielen Dank für Eure Arbeit.

**Comment by Tensuko** [comment]
Nein machen wir nicht.
Sry aber wenn du deine Kurso so suchen musst, solltest du mal überlegen die Kurse neu zu sortieren.

Pro Feld ein Ordner und das problem wäre bereits gelöst.

**Comment by CptRog** [comment]
Ja das habe ich ja bereits aber bei 79 Ordnern ist es etwas unübersichtlich.

**Comment by Tensuko** [comment]
Werden die nicht in der Reinfolge angezeigt ?
F01 F02 F12 F33 F65 F79
sollte nicht all zu schwer sein...

**Comment by CptRog** [comment]
Wenn man z.B. mit einem Gespann alle Grubber Mission oder Dünger missionen macht, wäre es besser alle Course anzeigen zu lassen pro Fahrzeug. 
1050 mit 15m Grubber also nur alle Course die Grubbern 15m enthalten.

**Comment by RealNeo80** [comment]
naja ich sortiers z.b. nach Arbeitsbreite und leg dann die Kurse unter den Feldnummern ab, aber das is wohl geschmackssache. ne suchfunktion hab ich bis jetzt noch net gebraucht
