### ISSUE TITLE
[Feature] Abfahren von Dreschern und manuell eingefahrene Kurse

### ISSUE THREAD

**Issue by Namajo** [Courseplay/Courseplay_FS22#899]
Wird es wieder die Möglichkeit geben, über Courseplay die Drescher abzufahren und über manuell eingefahrene Kurse das Ladegut zu verbringen, so wie es in FS19 möglich war?

Die Variante mit AutoDrive funktioniert mehr schlecht als recht. AutoDrive schaft es nur in wirklich sehr großen Feldern den Drescher vor dem Wenden zu erreichen. Eigentlich wird der Drescher erst entladen wenn er voll ist. Dazu Fährt der Abfahrer oft schon weg, bevor der Drescher leer ist.

**Comment by Tensuko** [comment]
Nein. Wird es so nicht geben.
