### ISSUE TITLE
Aktuell nicht Dedicated fähig ? 

### ISSUE THREAD

**Issue by Momo13092022** [Courseplay/Courseplay_FS22#90]
Hallo zusammen, ist meine Annahme richtig, dass Courseplay in der aktuellen Version nicht Dedicated fähig ist ? Wenn ich versuche den Mod hochzuladen, bekomme ich die Meldung Mod ist beschädigt.

Vielen Dank das er wieder da ist !! 

VG

**Comment by Sacred-Shadow** [comment]
Wie viel dicker soll denn der Hinweis sein? :D 
![image](https://user-images.githubusercontent.com/61997661/147390431-41615f86-f640-4387-9487-a9b6cc1c24f7.png)
