### ISSUE TITLE
Drescher zeigt 2 Rechtecke

### ISSUE THREAD

**Issue by StefanTreutler1974** [Courseplay/Courseplay_FS22#904]
Folgende Frage habe ich....
Wenn mein Standartdresche einen Courseplaykurs fährt, hat er neuerdings links immer neben sich 2 Rechtecke stehen. Haben diese Rechtecke irgendeine Bedeutung, oder wie bekommt diese wieder weg ?

**Comment by Tensuko** [comment]
Was für Rechtecke ?
Screenshot?

**Comment by StefanTreutler1974** [comment]
Kommt

Gesendet von Mail für Windows 10

Von: Tensuko
Gesendet: Montag, 7. Februar 2022 06:58
An: Courseplay/Courseplay_FS22
Cc: StefanTreutler1974; Author
Betreff: Re: [Courseplay/Courseplay_FS22] Drescher zeigt 2 Rechtecke (Issue#904)

Was für Rechtecke ?
Screenshot?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StefanTreutler1974** [comment]
![Drescher mit Rexhtecke](https://user-images.githubusercontent.com/58054938/152735103-e1bc6985-0ef2-4b3b-81fc-dc17002202b6.jpg)

**Comment by Tensuko** [comment]
logfile ?

**Comment by StefanTreutler1974** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8012900/log.txt)

**Comment by Tensuko** [comment]
Must be a problem of the vehicle (guess mod?).
Or any otehr Mod that you have in your mods folder (also got some with Errors).

Not a CP Problem buddy.
