### ISSUE TITLE
[Question] ist Multiplayer support geplant? 

### ISSUE THREAD

**Issue by Rene9696** [Courseplay/Courseplay_FS22#906]
Hi ich liebe Courseplay wie schon im 19er. Ist auch für denn 22er Multiplayer support geplant? Das wäre super :)

**Comment by Tensuko** [comment]
Wie oft eigentlich noch ?
Suchfunktion nutzen.
Diese Frage wurde schon 100 mal beantwortet....

**Comment by Rene9696** [comment]
Hab nichts gefunden. Man kann auch. Normal Antworten. Unsympathisch.

**Comment by Rene9696** [comment]
Danke :)
