### ISSUE TITLE
[InfoFromDev] Field margin setting

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/Courseplay_FS22#908]
As requested, we expanded the setting for fieldmargin from -2 to -5.

This seems to result in a change of the setting for saved vehicles.

So the saved value for saved vehicles is -3 instead of the default 0.

**This is only for existing vehicles.**

**Comment by Brandin2974** [comment]
How do I get it on Xbox one  courseplay I would like it while I'm playing fs22 cc an some help me out please
