### ISSUE TITLE
Error with "Running LUA method 'update'

### ISSUE THREAD

**Issue by rudshaag** [Courseplay/Courseplay_FS22#91]
Can't start a worker mid course, it then just starts the regular worker not the CP one. This is with a seeder attached to the MAN TGS. This same course has worked earlier but not anymore it seems.
[log.pdf](https://github.com/Courseplay/Courseplay_FS22/files/7776079/log.pdf)
.

**Comment by pvaiko** [comment]
This log has no error message from Courseplay. And please, please, stop posting log files as PDF. Please.
