### ISSUE TITLE
Start Course from Specific Point in a saved course [Feature]

### ISSUE THREAD

**Issue by erasma** [Courseplay/Courseplay_FS22#910]
**What is the problem this feature/enhancement solves?**
It would be great to start a course from a given point of a course - this will allow 2 pieces of machinery to start working at different locations as well if one needs the machine to get off the course it can resume from said point

**Describe the solution you'd like**
to enter the number in the hud menu where we can select First, Last or Nearest point 

**Describe alternatives you've considered**
Maybe add a function where we can move up course number in increments say 10 or 100 this would be controller friendly

**Additional context**
This would be great as it will allow us to use this to send trailers full and have it return to the same location and carry on the work it was doing

**Comment by Tensuko** [comment]
You can do that with nearest Waypoint, we won't implement a start at WP X or Y. Sry.
For getting back to the WP where it was -> start on last waypoint

**Comment by erasma** [comment]
Thank you - I assume the drop off when full integration with AD is still coming
