### ISSUE TITLE
[BUG_SP] Unable to load save - "No more interval timers"

### ISSUE THREAD

**Issue by pull2play** [Courseplay/Courseplay_FS22#912]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Load a save

**Actual behavior**
Save gets stuck at 50%, terminated by user

**Expected behavior**
Save should load.

**Courseplay version**
.27 release

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8015672/log.txt)

**Comment by Tensuko** [comment]
What the hell ? Closed...
Available mod:  (Version: 7.0.0.27) FS22_AutoDrive
Available mod:  (Version: 7.0.0.27) FS22_Courseplay

**Comment by Tensuko** [comment]
Maybe its time for a little spring clean up :D
