### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/Courseplay_FS22#914]
Hallo zusammen,

wenn ich CP in der Version [7.0.0.27] nutze wird mir die Log beim Einsteigen und dem Bewegen mit der Maus mit den "[dbg18 lp..."-Einträgen regelrecht zugemüllt.

siehe -> Log: https://pastebin.com/tP2gzehy

Getestet habe ich das auf einem neuen Spielstand nur mit CP im Modordner und auch in den geladenen Mod(Zusatzcontent ist mitgeladen worden). Somit kann einen Modkonflikt weitestgehend ausschließen.

Wenn ich länger spiele ist mir das Spiel auch schon eingefroren/abgestürzt.

Bei weiteren Fragen, einfach raus damit.

Danke für eure Arbeit.

mfg Trent 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8017043/log.txt)

**Comment by Tensuko** [comment]
dbg18 ist nur ein logeintrag und kein error oder bug.....
