### ISSUE TITLE
[Feature] Restzeit des Courses 

### ISSUE THREAD

**Issue by CptRog** [Courseplay/Courseplay_FS22#916]
Könnt bitte ihr wie im LS19 den Timer in das HUD einbauen damit man abschätzen kann wie lannge der Auftrag noch dauert.

![Screen](https://user-images.githubusercontent.com/87377728/152835767-bf7ada4d-ead9-4eed-bd02-ae3d72ad4233.png)

**Comment by Tensuko** [comment]
Ist nicht geplant und steht auch under Discussion.
