### ISSUE TITLE
[BUG_SP]

### ISSUE THREAD

**Issue by hecke82** [Courseplay/Courseplay_FS22#918]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.   Habe auf der Rade einen Kurz gezeichnet, der aber nicht erkannt wurde sondern darüber hinaus ging und dann kommt der Error in der Log 

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 7.0.0.27

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8021731/log.txt)

**Map**
Map played on. Rade 

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?   Habe es mit ohne Mods probiert ..macht keinen unterschied 

**Relevant script mods**
Mods like Autodrive or VCA and so on.
![Screenshot (44)](https://user-images.githubusercontent.com/99244054/152941651-4cdb9ada-8cbe-48fc-a9e3-0d30390682f1.png)
![Screenshot (45)](https://user-images.githubusercontent.com/99244054/152941657-85686fe5-47c3-4255-95b2-f6d21eaae1c2.png)
![Screenshot (43)](https://user-images.githubusercontent.com/99244054/152941660-ff8f0370-2e00-4060-b047-d8ed8c2289cf.png)

**Comment by Tensuko** [comment]
Bild 2 ist absicht so, ein custom field innerhalb eines großen Feldes wird erst mal so bleiben.
Bild 3 müsste in der nächste Version gefixt sein.
