### ISSUE TITLE
Fahrer startet immer im Vorgewende

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/Courseplay_FS22#92]
Hallo, ich habe heute das CP in den Modordner geschmissen und wollte voller Freude starten. 

Leider wird der Kurs immer so generiert, das der Fahrer im Vorgewende startet. Egal ob ich Starten auf der Bahn oder Vorgewende auswähle. Der Kurs ändert sich nicht und wird immer so generiert. 

Gibt es den Bug nur bei mir oder ist er reproduzierbar? 

Beste Grüße

**Comment by 60erjonny** [comment]
Hi
Welche Version hast du...? Mit der aktuellsten müsste der Fehler weg sein...

**Comment by 0scarZulu** [comment]
7.0.0.3 - quasi die die man über den Download Hyperlink zieht

**Comment by 60erjonny** [comment]
Hallo
Sorry, bei mir geht es ...
![fsScreen_2021_12_25_22_00_54](https://user-images.githubusercontent.com/63659182/147393572-f7d47bec-99c0-4b36-9f1c-95354ed468b9.png)
![fsScreen_2021_12_25_22_01_01](https://user-images.githubusercontent.com/63659182/147393574-2241babe-14d3-4d0b-afcf-f44c0ca9d716.png)

**Comment by 60erjonny** [comment]
Hallo

Sorry, jetzt habe ich es...:-)
![fsScreen_2021_12_25_22_24_47](https://user-images.githubusercontent.com/63659182/147393834-13ebde4d-c461-491e-90f5-9521287e8777.png)

**Comment by Tensuko** [comment]
An sich wählt man beim starten des Feldkurses im Jobmenü ein am ersten Wegpunkt starten. Zum fortsetzen sollte man einfach mit H weiterarbeiten können.

**Comment by rohne83** [comment]
ich glaube es geht ihm eher darum einen Kurs zu generieren der an sich auf den Feldreihen startet und nicht auf dem Vorgewende. Muss auch sagen, dass ich das selber auch noch nicht hinbekommen habe so einen Kurs zu generieren. Also die "Starte auf"-Einstellung im Kursgenerator (Bahnen oder Vorgewende) scheint aktuell noch keinen Effekt zu haben.

**Comment by Tensuko** [comment]
Oh okay, das kann gut sein. Schauen wir uns natürlich an!

**Comment by Tensuko** [comment]
Habe das Setting gerade probiert, funktioniert. Stop und Start sind jetzt vertauscht.
Eventuell neueste Version probieren, ansonsten bitte genauer beschreiben was nicht funktioniert.
![fsScreen_2021_12_26_01_16_14](https://user-images.githubusercontent.com/27344744/147395926-12637229-08c0-48e5-95cb-2d5303b0027a.png)

**Comment by Keppchen** [comment]
Bei mir läuft es auch sauber. Kann im Vorgewende oder auf der Bahn starten. Geht beides wunderbar

**Comment by rohne83** [comment]
Habs noch nicht selbst ausprobiert, aber #59 bezieht sich auf genau das gleiche, und das wurde wohl mit v7.0.0.3 behoben. Denke das hier kann damit zu.
