### ISSUE TITLE
[Feature] Display issue with Course generation GUI (Triple Screen setup)

### ISSUE THREAD

**Issue by stevti** [Courseplay/Courseplay_FS22#920]
**What is the problem this feature/enhancement solves?**
I play on a triple screen setup with a 5960x1080 resolution, so I fully appreciate this is a minor/uncommon problem, but the GUI for the course creation screen seems alligned to the left and stretched horizontally, while all the other GUI's are perfectly central and 'unstretched' (not sure if thats the correct word for that?) on the middle monitor.  What this means, for my setup anyway, is the numerical values for the course creation (number of headlands/course direction etc, that entire list basically) is slap-bang behind the bezels for the left & central monitor.

**Describe the solution you'd like**
Would it be possible to have the course generation GUI centralised on the display like the others?

**Describe alternatives you've considered**
My only solution to remedy this is to come out of the game, change the graphics settings to 1920x1080 on one monitor, go into courseplay to create the course, save the course, exit and reload with the 5960x1080 triple screen setup.  Each time I need to create a new course.

**Additional context**
I appreciate this is not a major bug fix or anything so I am very grateful that this Github is here so that I can at least tell you about this very minor issue.  Thankyou so very much to all involved for creating this amazing modification to the game. It really is a gamechanging addition, and together with Autodrive they really are an unbeatable combination for automation on our digital farms!

**Comment by Tensuko** [comment]
Duplicate #743

**Comment by merlinfive** [comment]
same Problem with Generator GUI with one screen , 3840x1080 Resolution
