### ISSUE TITLE
[Question] Breitablage obwohl  Schwadablage eingestellt 

### ISSUE THREAD

**Issue by The-Northchild** [Courseplay/Courseplay_FS22#921]
Ich hab das Problem das ich obwohl ich das Standard Claas Schetterlingsmähwerk auf Schwadablage gestellt habe der CP Helfer trotzdem das Gras in Breitablage ablegt. Gibt es da irgendeinen Trick?

**Comment by Tensuko** [comment]
Kein Plan, mit dem BigM klappts.

**Comment by Tensuko** [comment]
Mod Issue, schon gemeldet.
