### ISSUE TITLE
Probleme mit Ziehbaren maschinen beim vorgewende (Tools zu lang, Gespann fährt nicht weit genug vor)

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/Courseplay_FS22#93]
Hey mir ist aufgefallen das cp noch ein paar kleine Kinderkrankheiten hat mit ziehbaren Sämaschinen beim rückwärts fahren an manchen ecken klappt es super an anderen fährt er komplett krumm und schief wie auf diesem Bilder zu erkennen ist
![fsScreen_2021_12_25_19_49_17](https://user-images.githubusercontent.com/71101944/147391673-21617f68-775a-4f85-bab6-ae8cc84afa87.png)
![fsScreen_2021_12_25_19_57_02](https://user-images.githubusercontent.com/71101944/147391763-b0104cd9-640c-488d-91ec-b55688ad289e.png)
was mir dazu noch aufgefallen ist da er das Problem an jeder 2 ecke hat kann sein das es zufall ist kann aber auch sein das dort etwas nicht stimmt

**Comment by Tensuko** [comment]
Es kann sein das wir das über die configuration.xml hinkriegen.
Muss ich mir mal angucken was der mit diesem Tool macht.
Arbeitet er denn auch unsauber oder sieht es nur komisch aus ?

**Comment by Playlord75** [comment]
er fährt dann so ne kurve um wieder auf seine strecke zu kommen wenn du das mit unsauber meinst

**Comment by Playlord75** [comment]
![Unbenannt](https://user-images.githubusercontent.com/71101944/147394614-532f0f13-3481-4d5a-a73d-2f436c9dd59c.png)
ungefähr so die gestrichelte liene ist dann das was er auläst wenn er auf seinen kurs zurück fährt

**Comment by Tensuko** [comment]
Ja passt so ich weis was du meinst, schauen wir uns an was mit dem Tool los ist.
Wenn du noch andere Tools kennst die das Problem haben, melde dich bitte hier.

**Comment by Playlord75** [comment]
also ich hab es jetzt mit ein paar maschienen getestet alle volkommen unterschiedliche ergebnisse manche funtionierten einban frei die anderen hatten das selbe problem was ich mir dabei denke das die länge des wendemanövers damit zusammen spielen könnte weil cp hat das problem nur mit langen maschienen und da denke ich das die länge fürs vorwährst und rückwerts fahren zu kurs ist so das er passend sich in die bahn einfädeln kann evnentuel wieder die alte funtion zurück bringen wenn das natürlich möglich ist das er sich denn wendekreis wieder selber berechent ?

**Comment by Tensuko** [comment]
Es gibt kein 'alte Funktion zurück bringen'.
Wir müssen das nur anpassen :)

**Comment by Playlord75** [comment]
ich hab ein paar neue Informationen hierzu bezogen das problem trift auch bei kürzeren maschienen auf aber auch komischerweise nur bei manchen 
wie z.b. hier aber wieder nur jeder 2  1 . 3 . 5 ---> 
![fsScreen_2021_12_27_00_30_44](https://user-images.githubusercontent.com/71101944/147422435-6ff75b08-79cf-4222-b9a9-431116d415d2.png)

**Comment by XPiRiJenZ** [comment]
Hab hier mal ein Video gemacht:
https://youtu.be/bnR9QzbYwjI 

Standard-Tools, CP 7.0.0.7, M: Haut-Beyleron

An "geraden" Feldkanten klappt die Wende gut, Problem besteht (bei mir), wenn der Abfahrer an einer schrägen Kante wenden soll.

**Comment by pvaiko** [comment]
Mit dem 'turn' debug channel hätte man alles sehen können, keine Ahnung warum @Tensuko nicht danach gefragt hat...

**Comment by Goofy78** [comment]
@pvaiko 
 Ich hab mal einen gemacht... hoffe er hilft weiter ;-)

![fsScreen_2021_12_29_15_35_36](https://user-images.githubusercontent.com/96694308/147673269-b0fbc5b4-9d77-4e98-a90d-69f26b0fef34.png)

**Comment by Tensuko** [comment]
> keine Ahnung warum @Tensuko nicht danach gefragt hat...

Ich gelobe Besserung...

**Comment by Tensuko** [comment]
Try 7.0.0.10 
Reopen if Issue persists.

**Comment by McBenzer** [comment]
Macht mit 7.0.0.10 immer noch einen Knoten.

![fsScreen_2022_01_01_21_21_32](https://user-images.githubusercontent.com/96957355/147859540-e95991b6-69d0-4805-b825-d276c052b979.png)
![fsScreen_2022_01_01_21_21_51](https://user-images.githubusercontent.com/96957355/147859542-b683bb6f-64d9-4c7a-ac88-492c36917046.png)
