### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by manni1989** [Courseplay/Courseplay_FS22#932]
https://cdn.discordapp.com/attachments/938986589651099661/940905216855932958/image0.jpg

Ich hab ein kleines Problem ich hab Courseplay installiert seitdem seitdem bekomme ich dieses kleine Fenster was mitten im Bild kommt nicht mehr geöffnet dafür öffnet sich Andere Seite So ein anderes Fenster an was liegt das
[10:45]
Was kann ich dagegen tun oder ist das jetzt normal

**Comment by Tensuko** [comment]
Das ist das alte GUI.
Globale Einstellung, gamepad freundliches HUD auf aus.
