### ISSUE TITLE
[BUG_SP] Kursgenerierung / Feldposition auf selbst erstelltem Feldrand innerhalb eines vorhandenem Feldes 

### ISSUE THREAD

**Issue by XPiRiJenZ** [Courseplay/Courseplay_FS22#933]
**Steps to reproduce**
eigenen Feldrandkurs auf vorhandemem Feld zeichnen.

**Actual behavior**
Beim Setzen der Field position innerhalb des selbst gezeichneten Feldrandes wird dieser nicht berücksichtigt, sondern das urspürngliche Feld als Referenz zur Kursgenerierung angezogen.
https://youtu.be/CMajKliGTz4?t=230

**Expected behavior**
Der selbstgezeichnete Feldrandkurs sollte berücksichtigt werden und zur Kursgenerierung genutzt werden.

**Screenshots**
https://youtu.be/CMajKliGTz4?t=230

**Courseplay version**
Version used: 7.0.0.27

**Map**
NF Marsch 1.1

**Vehicles/ implements involved**
nicht relevant 

**Relevant script mods**
-

**Comment by Tensuko** [comment]
Das ist kein bug, das ist sogar so gewollt.
Weil du ein großes Feld als Custom Field um mehrere Felder drum herum ziehen kannst, aber dann immer noch auch die einzelnen Felder nutzen kannst.
Ein Trennen von Feldern oder ein Feld im Feld war und ist nicht vorgesehen.
