### ISSUE TITLE
Harvester driving into collecting tractor / trailer 

### ISSUE THREAD

**Issue by erasma** [Courseplay/Courseplay_FS22#934]
**What is the problem this feature/enhancement solves?**
At the end of a row the harvester will run into the collecting tractor and trailer (Auto Drive)

**Describe the solution you'd like**
Could the course have gentle turn the Auto Drive tractor and trailer can follow - have an option which is working with Auto Drive. this will then create the head lands space needed (IE 3 - 6) based on trailer size.

even if the route is longer and repeats some of the field it would save time in the long run 

**Describe alternatives you've considered**
Have Auto Drive always be on the outside of the Harvesters turn

thank you as always

**Comment by Tensuko** [comment]
AutoDrive Issue.
