### ISSUE TITLE
new bug ? tube from harvester

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#94]
https://uloz.to/file/hgoVvXFrclxb/farming-simulator-22-2021-12-25-19-44-29-01-zip#!ZJHmZmR2AzVlL2RjAwOyMTRjLJLjLzW4oTZ5ZaumYKH3qQWyAD== movie here

**Comment by Tensuko** [comment]
Link Error, what bug ? what version ? logfile ?

**Comment by Manyak007** [comment]
Combine pipe trembling fix #38 is fix with new version
