### ISSUE TITLE
[BUG_SP]Sämaschinen Konvoi mit Autodrive Aufladen falscher Pfad

### ISSUE THREAD

**Issue by dddanny79** [Courseplay/Courseplay_FS22#943]
**Steps to reproduce**
Convoy mit 3 Schleppern und Sämaschinen.
AutoDrive aktiv für automatisches Aufladen von neuem Saatgut bei einer Kaufstation in unmittelbarer Nähe.
Marschen Map auf Feld 78

**Actual behavior**
Nach dem Wiederauffüllen am Silo kommen die Schlepper korrekt zurück zur Bahn, aber anstelle auf seiner eigenen Bahn weiter zu fahren, fährt er auf dem mittleren Pfad vom Konvoi weiter.
Links (1) fährt weiter auf Mitte
Rechts (1) fährt weiter auf Mitte 
Stoppen und wieder starten des CP vom betroffenen Schlepper lässt ihn dann auf die richtige Spur wechseln

**Expected behavior**
Links (1) sollte weiter auf Links(1) fahren
Rechts (1) sollte weiter auf rechts(1) fahren

**Courseplay version**
Version used: 7.0.0.27

**Log**
https://pastebin.com/UaJVEygc

**Map**
Marschen 4fach ohne Gräben

**Vehicles/ implements involved**
Rapid A800S
John Deere 7RSeries

**Relevant script mods**

Autodrive

**Comment by ct177mak** [comment]
schon auf 7.0.0.28 geupdatet ?

**Comment by Tensuko** [comment]
Fixed in 7.0.1.0
More convoy fixes later.
