### ISSUE TITLE
[BUG_SP] Plow Kverneland PW 100-12 working width not reconized

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#946]
**Steps to reproduce**
On vanilla map, farm manager
Buy one tractor (for me it was the Fendt 1050) and buy the Kverneland Plow PW100-12.

**Actual behavior**
CP doesn't detect its working width.

**Expected behavior**
Working width proper detection

**Screenshots**
![2022-02-09_20-35-38](https://user-images.githubusercontent.com/70093234/153277851-91c2df37-87e3-40f1-a414-74609eb3794c.png)

**Courseplay version**
Version used: 7.0.0.27

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8035722/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Kverneland Plow PW100-12
No mods

**Relevant script mods**
None

**Comment by Tensuko** [comment]
Unfold it.
Then it is correct.

**Comment by Lactic68** [comment]
@Tensuko 
I have tried to unfold it and it is still not correctly detected.

**Comment by Tensuko** [comment]
It does, as soon as you press the work width text on the hud. Thats a refresh problem only.

**Comment by coatsy35** [comment]
The plough width refresh issue is still there in 7.2.0.2 is this an upcoming fix?

**Comment by Tensuko** [comment]
What is a width refresh issue? There is no width refresh.

**Comment by Tensuko** [comment]
Need to click again. We tried another way but that did not work.
What you also can do is use the vehicle config file.

https://github.com/Courseplay/Courseplay_FS22/wiki/The-VehicleConfigurations.xml-file.

There is no other way and wont happen

**Comment by harokyang** [comment]
This issue still happens now, with latest courseplay
