### ISSUE TITLE
Düngespritze bleibt an bei Spurwechsel und warten auf Verbandsfahrzeug

### ISSUE THREAD

**Issue by DasOppel** [Courseplay/Courseplay_FS22#949]
Moin, englisch geht leider bei mir nicht.

Ich spiele zZ auf der WW und habe dort für meine Amazone Pantera Flotte einen Kurs auf Feld 17 mit zwei Spritzen  und zwei Vorgewenden erstellen lassen. Mein Rechner ist nicht der Beste als hat das berechnen ca 2,5 min gebraucht aber macht ja nix, denn es ging... soweit Kompliment. Dann habe die beiden an den Start gebracht und Nr 1 gestartet.... Spritze enfaltet sich und geht an (nach ca 1 min Rechenzeit, fährt nicht los ???? 
Dann habe ich die zweite gestartet, enfaltet sich spritze geht an und Nr 1 fährt los, nach Abstand (100m) dann die Nr 2 alles gut und dickes Lob. 

Jetzt sind die zwei Vorgewende um und Nr1 muss zum nächsten Ansatzpunkt fahren...spritze bleibt an...bleibt an bis zu neuen Ansatzpunkt. Bei Feld 17 dauert das und kostest unmengen an Dünger, nicht so schön. Gleiches bei Nr 2.

Die beiden kommen an den Kehrpunkt, 1 muss jetzt um 2 herum fahren die spritze bleibt an, 2 wartet das 1 aus dem weg ist die spitze bleibt an, 1 ist in seiner neuen Spur fährt solange vor bis 2 mit der wende beginnt die spritze ist an, jetzt bleibt 1 stehen und wartet bis 2 fertig gewendet hat, natürlich mit spitze an.... und beide müssen auftanken fahren weil jetzt leer.........!!!!! Frust.

Ich hoffe es ist klar was ich sagen wollte, 
1. Tolle Leistng bisher von euch Fettes Danke dafür.
2. Es wäre schön wenn ihr es noch hin bekommt das die Geräte in StandBy gehen wenn sie warten oder Überführen.

Bitte weiter so.

**Comment by Tensuko** [comment]
> Frust.

Der ist auch bei uns, wenn das Template nicht benutzt wird und wir keine logfile bekommen etc...

**Comment by Amalith1** [comment]
Moin, habe genau das gleiche "Problem". Fahre im dreier oder vierer Verband in der Wild West Map. Da diese Felder sehr groß sind und man im Viererverband fährt, ist das laufen lassen der Spritzen bei dem fertigstellen der Vorgewende (Scharf) nicht so prickelnd.
Ansonsten ein dickes Lob an das CP Team :)

**Comment by Tensuko** [comment]
Ja das müssen wir unbedingt noch machen, dass die Streuer und Spritzen dann ausgehen.
Wird auf jeden Fall noch kommen, aber wann kann ich euch nicht sagen.
