### ISSUE TITLE
How do I fix combine strolling off?[Question]

### ISSUE THREAD

**Issue by Bull8Magn8** [Courseplay/Courseplay_FS22#959]
Hi all

I set up my courses yesterday and everything was working great. Today I am harvesting my fields again, the combine gets to full and goes off to unload at the trailer then it will stroll off into another field and keep on driving, will not go back to the original path. I have removed courseplay and all the saved folders, I am running the latest version. it is driving me insane.

**Comment by Tensuko** [comment]
Why not open a proper bugreport then just a question ?
I can't give you an answer to this little information.
Try it with a bugreport...
