### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Jeanmard** [Courseplay/Courseplay_FS22#96]

**Comment by Jeanmard** [comment]
I get the attached message when trying to load Courseplay 7.0.0.3. 
[Courseplay bug.docx](https://github.com/Courseplay/Courseplay_FS22/files/7776219/Courseplay.bug.docx)

When the game loads, Corseplay is not functional.

**Comment by pvaiko** [comment]
I'd hate to ask, but have you tried clicking on the OK button?

(also, absolutely no Word documents please, you can just copy paste images here)

**Comment by Jeanmard** [comment]
I did. It loads the game normally but no Courseplay functions.

**Comment by Jeanmard** [comment]
Sorry for the Word docx, won't happen again. I tried on a test save game and on a mod virgin new game and no change. Just will not load.
Also uninstalled and reinstalled the mod. No change.

System
AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
RAM 16.0 GB
X64 based processor

**Comment by Tensuko** [comment]
Watch my Video on how it works.
If that message comes up, it is definitly installed and active.

https://youtu.be/_kyAaN2r8Uk
