### ISSUE TITLE
[BUG_MP]

### ISSUE THREAD

**Issue by lgxxxxx** [Courseplay/Courseplay_FS22#966]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
The tractor continues its course with an empty slurry tank

**Expected behavior**
The tractor must stop when the tank is empty

**Screenshots**

**Courseplay version**
Version used: 9327f05

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8050190/log.txt)

Video
https://user-images.githubusercontent.com/11899013/153628350-9df8846d-ebf2-4df4-8047-87696d4d7b2c.mp4

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.

**Player on the server**
Number of players on the server, as the bug appeared.

**Dedicated server or local hosted server**
Dedicated server - no 

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement?
Mod no 

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment]
#927

**Comment by lgxxxxx** [comment]
I apologize for the wrong title. The game is SP
