### ISSUE TITLE
[BUG_SP] Güllefass wird nicht als leer erkannt

### ISSUE THREAD

**Issue by Neotras2552** [Courseplay/Courseplay_FS22#968]
**Steps to reproduce**
Kurs erstell mit Güllefass mit ausbringer inkl Grubber

**Actual behavior**
Fährt wenn das Güllefass Leer ist nicht nachfüllen

**Expected behavior**
Klappt den ausbringer zusammen und übergibt an AD damit AD Nachfüllen Fahren kann

**Screenshots**
nop

**Courseplay version**
7.0.0.28

**Log**
https://pastebin.com/y7SvwNAn

**Map**
NF Marsch

**Vehicles/ implements involved**
Samson PG II 35
Samson SD 700
Deutz Serie 9 MH

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Auto drive

**Comment by Tensuko** [comment]
Ein komplettes logfile wäre gut und wenn du unter Fahrzeugunstellungen ganz unten noch den debug an machst, den dann fahren lässt wenn er leer wird, das wäre dann super.
Dann können wir usn das besser anschauen.

**Comment by Neotras2552** [comment]
Die log ist zu groß 16482 zeilen

**Comment by Neotras2552** [comment]
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8050916/log.txt)

**Comment by Tensuko** [comment]
Should be fixed in 7.0.1.1
