### ISSUE TITLE
Kurs speichern[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#969]
Hallo
Ich wollte ein Kurs speichern was aber nicht funktioniert, es kann ein Ordner erstellt werden aber kein Kurs gespeichert werden, unten ist kein Button für Kurs Speichern

**Comment by Tensuko** [comment]
Da ist einer, habe ich gerade gemacht.
Hast du überhaupt ein Fahrzeug mit Kurs ausgewählt oder sitzt du drin ?

**Comment by Hendirk** [comment]
Hatte noch die alte Version, ist wieder da --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 11.02.22, 20:14 schrieb Tensuko ***@***.***>:

   
  Da ist einer, habe ich gerade gemacht. Hast du überhaupt ein Fahrzeug mit Kurs ausgewählt oder sitzt du drin ?
