### ISSUE TITLE
working and travelling speed on field is limited to 5 km/h

### ISSUE THREAD

**Issue by FarmerCedric** [Courseplay/Courseplay_FS22#97]
Hey community,

I got a fully repaired Massey Ferguson with also repaired mowing combines.
Unluckely courseplay does not allow me to set the working speed. It is limited to 5 km/h. No matter what machine I use.

It is the grass on the east side of the Erlengrat farm on mode "easy farmer" I want courseplay to mow. The course generates fine and works well, but it just drives 5 km/h instead of 22 (possible downhill).

I attached my savegame and the log files.

I hope, you can help me! Thank you

[log (2).txt](https://github.com/Courseplay/Courseplay_FS22/files/7776245/log.2.txt)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7776246/log.txt)

Savegame file can´t be uploaded here. You can find it in my onedrive:
https://1drv.ms/u/s!ArJlddqdoeT2gr0fEqtam0E3Xa3Qzw?e=pqqrqf

**Comment by Porter76** [comment]
There is already a thread for it! (# 28)
The problem arises and cannot currently be resolved as soon as you have a machine from the used car market on the menu. Or a rental vehicle! The developers are working on it!

**Comment by FarmerCedric** [comment]
okay thank you very much! I will wait for it
