### ISSUE TITLE
[BUG_MP] Helfer Menü

### ISSUE THREAD

**Issue by Schemo88** [Courseplay/Courseplay_FS22#971]
Leider ist mein Englisch echt scheisse sry

**Steps to reproduce**
Keine Ahnung wie genau das zu stande gekommen ist, ich habe einen Traktor (Fendt 1050 by Alex Mod) gestartet um ein Feld zu Grubbern, ausserdem einen gleichen Traktor mit Ladewagen auf einem anderen Feld der Stroh geladen hat. Dazu noch einen Krone BIG M 450 der sein eigenes Feld gemäht hat wo noch ein weiterer Fendt mit dem Fastbale hinterher gefahren ist und Silage ballen gemacht hat. Nach einer weile die allerdings der Big M und der Traktor ineinander gefahren und haben sich verkeilt. Habe den Traktor gerade gerückt und mit CP auf Nächster Wegpunkt weiterfahren lassen. Den Big M habe ich auf seine Spur gefahren und wollte auch auf nächsten wegpunkt setzten was er nicht zugelassen hat bzw die Arbeit verweigert hat.

**Screenshots**
![Zwischenablage01](https://user-images.githubusercontent.com/99513363/153679806-073d163a-6386-49d8-b70c-d39c2c8a6bd1.jpg)

**Courseplay version**
Version used: 7.0.1.0

**Client Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8052028/log.txt)

**Server Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8052030/log.txt)

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
NF Marsch 4x

**Vehicles/ implements involved**
Krone Big M 450 (original)
Fendt 1050 Alex Blue (Mod)

**Relevant script mods**
AutoDrive, HiredHelperTool, VCA

**Comment by Schemo88** [comment]
Zusatz info die Helfer auf dem Bild sind auch da wenn kein Helfer mehr aktiv ist

**Comment by Schemo88** [comment]
Ok habe nun die Mod auf dem Server deaktiviert aber irgendwie bleibt es gleich. 
![Zwischenablage01](https://user-images.githubusercontent.com/99513363/153707217-23c2c670-c72f-4531-bfa7-806b997538d2.jpg)

GameLOG
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8053167/log.txt)

ServerLOG
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8053173/log.txt)

Habe auch geschaut was als Helfer gerade an war, es war nur 1 Helfer der Gemulcht hat und der andere der als Aktiver Helfer gezeigt wird der hatte mit dem Ladewagen Gras gesammelt und war gerade auf dem Weg (mit AD) zum Parken.
Auch jetzt wird er mir als Helfer angezeigt obwohl er auf dem Parkplatz steht.

**Comment by schwiti6190** [comment]
@Schemo88 Kann es sein das es sich um einen mod conflict mit Autodrive handelt ?
Wäre cool wenn du versuchen könntest den Fehler ohne Autodrive zu reproduzieren :)

**Comment by keksi1991** [comment]
Der Bug scheint nicht an Courseplay zu liegen, wir haben den gleichen, bei uns ist auch das Hired Helper Tool und AD im Einsatz. Bislang noch kein Courseplay. Was bei uns geholfen hat war das deaktivieren der Helfer vor dem Verlassen des Servers, seitdem ist der Bug nicht mehr aufgetreten.

**Comment by schwiti6190** [comment]
Ich vermute mal das ist ein autodrive conflict dann. Könntet mal schauen ob es dort schon ein Issue dazu gibt. Falls der Fehler nur mit CP auftaucht einfach nochmal melden :)

**Comment by Schemo88** [comment]
Ich hab das Problem wirklich erst seit dem ich CP drauf habe.
CP + AD + HHT = Fehler
CP + AD = Fehler
CP = wird gerade getestet

**Comment by schwiti6190** [comment]
@Schemo88 Nur AD wäre noch interessant für den test

**Comment by Schemo88** [comment]
Ok also
CP + AD + HHT = Fehler
CP + AD = Fehler
CP = Kein Fehler
AD = Kein Fehler

also eventuell ein Problem zwischen CP und AD wenn beide aktiv sind zumal AD selbst keine Aktiven Helfer erstellt die haben scheinbar ihre eigene Art von Helfern also habe ich ein Paar Fahrzeuge mit dem AD losgeschickt und den Standart Helfer (der ein Aktiven Helfer erstellt) ein Ziel gegeben sobald die Arbeit/Job erledigt ist wird der Aktive Helfer entfernt.

**Comment by Schemo88** [comment]
Kein plan ob das ne Verstopfung war oder so, habe nun nach den Test's AD, CP und auch HHT wieder drauf und nun laufen sie ohne Probleme ausser das mir CP wieder Warnings und Error gibt die er auch gegeben hatte als ich nur CP drauf hatte.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8054001/log.txt)

**Comment by schwiti6190** [comment]
Die Warnings sind debug infos die uns helfen. Der error ist ein typo für das umbennen des Kurses. Wird in der nächsten version gefixt. Aber kein game breaking bug.

**Comment by Schemo88** [comment]
Ok also bis auf die Verstopfung die ein Rätsel immer noch ist läuft es erstmal wieder (keine Ahnung warum aber bin froh)

**Comment by Schemo88** [comment]
Also ich glaube wirklich das es irgendwie mit AD zusammen hängen muss, ich hatte jetzt 2 CP Fahrer auf Feldern unterwegs gehabt und mit AD einem LKW losgeschickt ohne irgendeinen Grund oder auch ne Meldung im LOG blieb er an einer Kreuzung stehen und bewegte sich nicht mehr. Ich musste ihn per Hand ein stück weiterfahren und hab ihn wieder gestartet und nun stapeln sich die 2 CP Fahrer wieder im Aktiven Helfer Menü.

**Comment by schwiti6190** [comment]
@Schemo88 Bitte einmal mit der neuen Version testen vlt. ist das jetzt weg :)

**Comment by Schemo88** [comment]
Also ich kann sagen bisher ist es mir mit der Neuen Version noch nicht passiert egal was ich an Helfer auf dem Weg hatte.

**Comment by schwiti6190** [comment]
Wenn es wieder auftritt einfach das Issue wieder auf machen.
