### ISSUE TITLE
Kurs laden[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#979]
Hallo 
Mache ich irgendwas falsch das ich kein Kurs laden kann
![Courseplay](https://user-images.githubusercontent.com/47453761/153722633-8b556c19-353f-485a-9179-7711e9184bed.png)

**Comment by Tensuko** [comment]
Du hast doch Kurs 40 geladen, steht oben
Coursemanager(MF7726 S) 40
Dein Kurs heist 40 also steht da oben auch 40

Kurs aus Fharzeug löschen dann kannst du auch wieder einen neuen laden.
