### ISSUE TITLE
Ladewagen

### ISSUE THREAD

**Issue by TonyDespo** [Courseplay/Courseplay_FS22#98]
Geht das schon das ich mit Courseplay Stroh/Gras mit dem Ladewagen laden kann?

Is that possible that I can load straw / grass with the loading wagon with Courseplay ?

**Comment by Tensuko** [comment]
Auf alle Fällte, aber siehe die Antwort hier: https://github.com/Courseplay/Courseplay_FS22/issues/21#issuecomment-1000862973
