### ISSUE TITLE
[BUG_SP] bad line harvest

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS22#980]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
3 harvesters left center right and each combine rides as it wants

**Actual behavior**
3 harvesters left center right and each combine rides as it wants

**Expected behavior**
everyone should ride their route

**Screenshots**
![image](https://user-images.githubusercontent.com/96631209/153722791-cbf19a3a-112d-4857-bcb8-606bab043ead.png)

in the picture there is a combine that has a route on the left but goes on the right
**Courseplay version**
last 2.0.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8054322/log.txt)

**Map**
wild west v1.1

**Vehicles/ implements involved**
Mod yes

**Relevant script mods**
Autodrive

**Comment by Manyak007** [comment]
edit: log is new

**Comment by Tensuko** [comment]
What Claas Combine do you use ?
Don't tell me this one:

`2022-02-12 18:15 Error: Could not parse GISL program.
C:/Users/Radek/Documents/My Games/FarmingSimulator2022/mods/FS22_FM_ClaasLexion8900_Spezial/vehicleShader.xml(1538): ERROR: 'max' :  unable to suitably promote arguments to function (parameter 2)`

It throws Errors.
Beside that, only up/down rows ?
Symetric lange change yes/no ?

**Comment by Manyak007** [comment]
do you think it's a combine?
the combine makes mistakes only on the rows

**Comment by schwiti6190** [comment]
@Manyak007 You could try changing this setting before starting the drivers:
![grafik](https://user-images.githubusercontent.com/58079399/153725661-b35d444b-d5ec-46d7-bca6-73ef038e994f.png)
Might help you there :)

**Comment by Tensuko** [comment]
Closed due to inactivity.
The symetric lane change should help here for the up/down pattern.

**Comment by Manyak007** [comment]
The symetric lane deactivated work ty all sry i more work ty very much
