### ISSUE TITLE
ballen abladen[Question]

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/Courseplay_FS22#981]
Hallo 
Ich wollte die Ballen einsammeln und dann bei der BGA abladen 
Wie geht das

**Comment by Tensuko** [comment]
Mit AutoDrive, bzw AutoDrive braucht erst noch ein Update dafür.
Am besten bei Mario Hirschfeld auf YouTube vorbei schauen, der macht super Tutorials zu AD und CP.
