### ISSUE TITLE
[BUG_SP] eingegeben Zahl bei Richtungswinkel Bahnen wird teilweise nicht übernommen

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/Courseplay_FS22#983]
**Steps to reproduce**
nicht 100% reproduzierbar

**Actual behavior**
eingegeben Zahl wird 
a) übernommen aber nicht für die Berechnung genutzt
b) gar nicht übernommen

**Screenshots**
![image](https://user-images.githubusercontent.com/8066324/153728478-12f9e176-a874-4697-8233-8eadca69fbf5.png)

**Courseplay version**
Version used: 7.0.1.0

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8054540/log.txt)

**Comment by Tensuko** [comment]
Can't reproduce.

**Comment by Clouseau219** [comment]
Wenn ich mich nicht irre musst du die Startrichtung auch auf Manuel stellen.

**Comment by Tensuko** [comment]
Comes in 7.0.1.3
