### ISSUE TITLE
[Feature] AD Unloader doesn't stop unloading Multitool

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/Courseplay_FS22#988]
**What is the problem this feature/enhancement solves?**
When having a multitool course with 2 or more combines the unloader doesn't stop unloading one combine when it's empty when other combine is full enough for unloading. 

**Describe the solution you'd like**
I think fold the pipe when combine is empty is enough. Ad should stop then and drive to the next combine (when I understand the handling from ad correct)

**Describe alternatives you've considered**
Don't know how it's handled, maybe the next combine can call the unloader with higher priority? Or is it something for the AD Team? 

Forgot to mention: version for AD is 2.0.0.5 rc
Courseplay 7.0.1.0

**Comment by Tensuko** [comment]
That is something for AD, as they control when to unload our combine.
Maybe some AD Setting in the combine, ask on their Discord or GitHub.
