### ISSUE TITLE
Speed Problem

### ISSUE THREAD

**Issue by Tiba570** [Courseplay/Courseplay_FS22#99]
moin with me I have the problem that all vehicles could only drive up to 5 km / h fast and I can not increase this in the menu and with a new profile a thresher can drive up to 20 km / h and with my profile only 5 km / h and I do not want to start a Neuers profile.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7776298/log.txt)
[savegame1.zip](https://github.com/Courseplay/Courseplay_FS22/files/7776300/savegame1.zip)

**Comment by Tensuko** [comment]
Pls look out for duplicates, thank you :)
#58
