### ISSUE TITLE
[Feature] Mini Hud - Rechte Maustaste / Mini Hud - Right mouse button

### ISSUE THREAD

**Issue by BigBlackBahamut** [Courseplay/Courseplay_FS22#991]
**What is the problem this feature/enhancement solves?**
Showing and hiding the Mini Hud with the right mouse button in connection with AD (AutoDrive)

**Describe the solution you'd like**
Switching on or off whether you want to show the hud with the right mouse button in the main setting and no longer dependent on the vehicle.

**Describe alternatives you've considered**
Not available

**Additional context**
Not available

**Comment by Tensuko** [comment]
It will stay per vehicle.
If we add an aditional global setting, we are not sure yet, for now we keep it like it is.

**Comment by BigBlackBahamut** [comment]
Hm, okay, but it used to be global. Is there a reason this isn't global anymore?

Or how about if you can disable it in the mini hud?

**Comment by Tensuko** [comment]
Very simple reason:
Per vehicle -> Every user can turn it off where they want, for example vehicles with a front loader or similar and keep right click where they want it.
If it would be global -> all off or all on, no other choice.
