### ISSUE TITLE
[BUG_SP] Slurry spreader moving at slow speed, can't stop vehicle, creates interface bugs

### ISSUE THREAD

**Issue by TuplexGaming** [Courseplay/Courseplay_FS22#993]
**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
On No Man's Land map, using a Fendt 1050 with the Veenhuis Premium Integral 30000 tank and Bomech Multi 4XL spreader, I created a course to fertilize a field.  After starting the worker, the vehicle moved at only 3kph.  I could not stop it except by stopping the engine.  After that the B button on my controller would take me back to the menu instead of going back.  This happened during a stream, you can see it here:  https://www.twitch.tv/videos/1296947177 @ 51:20.

**Expected behavior**
Expected normal slurry spreader speed and function.

**Screenshots**
I have video of it occurring during my stream:  https://www.twitch.tv/videos/1296947177 @ 51:20.

**Courseplay version**
Version used: 7.0.1.0

**Log**
Sorry, I was in the middle of a stream and didn't take the time to capture log files.  Let me know if you'd like me to try it again.

**Map**
No Man's Land

**Vehicles/ implements involved**
Which vehicle or implement?  Fendt 1050 with the Veenhuis Premium Integral 30000 tank and Bomech Multi 4XL spreader
Mod yes/no ?  No

**Relevant script mods**
See attachment for list of active mods.
[active mods.txt](https://github.com/Courseplay/Courseplay_FS22/files/8056711/active.mods.txt)

**Comment by Tensuko** [comment]
The logfile is actual as long as you have not restarted the game.
So you can just post that logfile after closing it.

Would like to see the log if there is any Issue so if you have to time to reproduce this would be cool.

**Comment by TuplexGaming** [comment]
Hi Tensuko.  I had already exited the game.  I tried to duplicate the issue on another field and it worked as expected, which is good for playing the game, but maybe not so good for fixing the issue I experienced.  I am attaching the log file anyway in case it can be of any help.
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8056785/log.txt)
.

**Comment by Tensuko** [comment]
Without the debuginformations when that issue happens we can't do much.
I would close this Issue and once you have that issue happen again, you can reopen it and attach the logfile.
