### ISSUE TITLE
[BUG_MP] When use course generator  he keep ketting 1 field number  

### ISSUE THREAD

**Issue by liteon1979** [Courseplay/Courseplay_FS22#995]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Afther 1 field work generate or sometimes 2 then a new one isnt working anymore u cant generate   the popup (See screenshot) options are gone. or it get its self a wronf field number and u wont we able to change it.
And yes ather job is done we remove the course job.
Some how the generator olso when this happens keeps in mind the field number where u did a job before. If u can generate  it generates to the fild and the field where u are on.
Olso noticed afther we activated Courseplay on the server the fps goes lower then before.

**Actual behavior**
A clear and concise description of what happen.
When a course is created and goes to another vichle to generate a course (doenst matter if u planting seed or plowing or whatever u want to do. The  wheni want to to do create course i get less options to put on. (see screenshot)
**Expected behavior**
When u wabt to create an new working course u able to it. lots of settings are gone or u cant even generate a new course.
Our option to get it working again is to sace the game.  log out and put server out and deactrive courseplay then save server, start and load the gamen then save in game. log out and get back to the server and put it out, then reativate courseplay on server , saven and start server again.
But then  same problem after making new course 1 or 2 times then again not table gain to generate a work course.
It keeps comming back
Sometime when u can generate it chooce self a field number and u cant change that the number kees comiing back where want to generate a course but its nog the filed number we want to generate.  And yes vehcile is on the field that we want to generate

**Screenshots**
![20220213224739_1](https://user-images.githubusercontent.com/71187188/153777120-9ae2aeb5-84c9-406b-844b-f33a7879b515.jpg)

**Courseplay version**
Version used:  7.0.1.0

**Client Log**
Please attach your personal log file with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Server Log**
Please attach a log from the server with all debug channels active, 
if it's possible.
[Serverlog.txt](https://github.com/Courseplay/Courseplay_FS22/files/8056808/Serverlog.txt)

**Player on the server**
Number of players on the server, as the bug appeared.

2 people

**Dedicated server or local hosted server**
Dedicated server yes/no ? Yes

**Map**
Map played on.
NF Marsch 4fach

**Vehicles/ implements involved**
Which vehicle or implement? All, doenst matter with plow or seerding of whatever of harvast

Mod yes/no ? Yes

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive  v.2.0.0.3

**Comment by Tensuko** [comment]
That seems to be a general and not MP problem only.
Reopen the generator should fix this.
I have no Idea when this happens, Maybe when generate more course with one vehicle ?

**Comment by Tensuko** [comment]
- Old AutoDrive on Server
- Mod with Error
- Callstack from any mod (Giants Code)
- More Callstacks from locksteeringaxles

Should should clean up your mods folder, there are to many mods what produce errors on your server.

**Comment by liteon1979** [comment]
now i removed the mod locksteeringaxles and tested in Singeplayer. look liked tht worked. Now i keep getting all the settings and can generate.
But when a vehicle is done with his job (field 5)  and i remove te temporary generate course and, drive to field 9  to do that  field. Then the old field what he done before the field number 5 he remeber. and doesnt matter is i go to a other field number he keep remind the field number what he has done (field 5 ).  Only way to get that out of that field number is to save game. get out and remove courseplay.  get back in the games do another save. get out again and activate courseplay again.  and start the game again. then eveything is normal again.  untile i use vehicle again ather a first job. then again he genretate on the  field number from his first job.

**Comment by Tensuko** [comment]
You doing something wrong then.
There is no "field number that we remember".
We generate a course where you put the field position.
Then we drive that course.

**Comment by Tensuko** [comment]
You have to place the fieldposition on the field where you want to generate the course.
If that position stays on the old field ofc it will be generated there.

**Comment by liteon1979** [comment]
ok how u move that?  its stuck thre cant drag is or somehow

**Comment by liteon1979** [comment]
with that menu on the right  then i have less options   like tell him to go arround twice and then up and down.

**Comment by Tensuko** [comment]
Not dragging... it is just like the Giant target, on the right side on the screen......
Improovements for the Menu will come with the next Version, but there is rly not a bug...

**Comment by Roby1164** [comment]
> with that menu on the right then i have less options like tell him to go arround twice and then up and down. And i always go stand on the field what i want to do before i go generatere

This shows that you don't understand how it works. The menu on the right is used to give the first inputs, in particular the starting points, then the rest of the settings are done in the central menu, before creating the path, you set them how many perimeters you want it to do, if you go in the direction clockwise or counterclockwise, etc ......... But as mentioned, if you start from the mini hud, you won't see the settings of the mini menu on the right.
