### ISSUE TITLE
BGA Bunkersilo entleeren

### ISSUE THREAD

**Issue by Marko230** [Courseplay/Courseplay_FS22#998]
Hallo
Erstmal vielen Danke für die tolle Arbeit. 

Ich wollte mal nachfragen ob es wieder die funktion geben wird das BGA silo mit einer schaufel entleeren zu lassen. So wie im ls19 auch. 

Ich hab hier jetzt nichts dazu gefunden, deshalb die frage. Wenn sie schon mal gestellt wurde sorry das es dann doppelt ist. 
mfG 
Marko

**Comment by Tensuko** [comment]
Ja, später mal.
Dafür dann bitte Question benutzen oder unter Discussion schauen.
Auch Suchfunktion benutzen hilft
